### ISSUE TITLE
Environment variables in conf.d/*.fish not set on SSH login

### ISSUE THREAD

**Issue by ostrich** [fish-shell/fish-shell#10003]
Fish version
3.6.1

uname -a
Linux lenovo 6.4.12-arch1-1.1 #1 SMP PREEMPT_DYNAMIC Fri, 25 Aug 2023 09:03:34 +0000 x86_64 GNU/Linux

No customizations

When I connect remotely via SSH, fish does seem to source ~/.config/fish/conf.d/*.fish (based on the merge alias being applied) but none of the environment variables are set until after I `exec fish`. In local terminals, the environment variables are set as expected.

```
[I] ostrich@desktop ~> ssh lenovo                                                                                                                                                           
[I] ostrich@lenovo ~> less .config/fish/conf.d/xdg_vars_aliases.fish
set -gx HISTFILE $XDG_STATE_HOME/bash/history
set -gx CARGO_HOME $XDG_DATA_HOME/cargo

alias merge='xrdb -load $XDG_CONFIG_HOME/X11/xresources'
[I] ostrich@lenovo ~> functions merge
# Defined via `source`
function merge --wraps='xrdb -load $XDG_CONFIG_HOME/X11/xresources' --description 'alias merge=xrdb -load $XDG_CONFIG_HOME/X11/xresources'
  xrdb -load $XDG_CONFIG_HOME/X11/xresources $argv
        
end
[I] ostrich@lenovo ~> echo $HISTFILE

[I] ostrich@lenovo ~> echo $CARGO_HOME

[I] ostrich@lenovo ~> exec fish
[I] ostrich@lenovo ~> echo $HISTFILE
/home/ostrich/.local/state/bash/history
[I] ostrich@lenovo ~> echo $CARGO_HOME
/home/ostrich/.local/share/cargo
```

**Comment by faho** [comment]
You're using `echo` to find out how a variable is set, that's the wrong tool for the job.

Use `set --show`. If you did, here's what you would see:

> $HISTFILE: set in global scope, exported, with 0 elements

You have set these variables to empty, because, and this is the important part:

**The XDG variables aren't set yet**

You likely set $XDG_STATE_HOME and friends elsewhere, and that seems to happen after xdg_vars_aliases.fish. So, if you set them (and export them), and run another fish, it goes through xdg_vars_aliases.fish again, except this time the variables are defined.

**Comment by ostrich** [comment]
Thanks. I even read other issues about conf.d/*.fish being sourced before config.fish and didn't put two and two together 😅. Closing.
