### ISSUE TITLE
Open fails when xdg-open would launch a terminal program

### ISSUE THREAD

**Issue by genevieve-me** [fish-shell/fish-shell#10045]
- fish 3.6.1
- Linux 6.6.0-rc3 #1-NixOS SMP PREEMPT_DYNAMIC
- I tried running fish with no configuration (`sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'`) and experienced the same behavior

#### Expected behavior

```
> echo $EDITOR
hx
> xdg-mime query default inode/directory 
lf.desktop
> xdg-open ~/mydirectory
(lf opens)
> open ~/mydirectory
(lf opens)
> open ~/myfile.txt
(hx opens)
> xdg-open ~/myfile.txt
(hx opens)
```

#### Current behavior

```
> xdg-open ~/mydirectory
(lf opens)
> open ~/mydirectory
(nothing happens and I'm still at a fish prompt)
> open ~/myfile.txt
(nothing happens and I'm still at a fish prompt)
> xdg-open ~/myfile.txt
(hx opens)
```

Furthermore, I tried copying the basic behavior of `open.fish`, and the following occurs:

```
> function opentest
       for i in $argv
             xdg-open $i
         end
     end
> opentest somedir/
(lf is opened correctly)
```

I see mention of a possible issue in the code comment here : https://github.com/fish-shell/fish-shell/blob/4ab34f2e86f91e90e732302446f1382cc122f07c/share/functions/open.fish#L33C48-L33C48 : could that be relevant?

**Comment by faho** [comment]
The issue here is that we background the `xdg-open` - we use `xdg-open $i &`. This is a workaround for an issue where in some paths it'll do that itself and in others won't.

Fundamentally we can't detect that and have to pick one - either we work around that bug or we enable things running in the terminal.

Ideally that would be fixed in xdg-open, but it's been pretty unmaintained for years (and never was all that great tbqh). If it isn't I'm not sure if we want to reintroduce a bug for graphical applications, which xdg-open was always geared towards more, or if we want to allow terminal applications.

Or we could always drop the `open` function and let people deal with it themselves.

**Comment by faho** [comment]
>This is a workaround for an issue where in some paths it'll do that itself and in others won't.

Fixed in xdg-utils [1 month ago](https://gitlab.freedesktop.org/xdg/xdg-utils/-/merge_requests/55#note_87).
