### ISSUE TITLE
fish_update_completions has trouble parsing man page for `parallel`

### ISSUE THREAD

**Issue by chanceymathews** [fish-shell/fish-shell#10060]
Hello,

Fish is unable to generate completions for `parallel`, possibly because many of the first options shown in the man page don't follow the expected format.

Running `fish_update_completions --verbose 2` gives this:

```2037 / 4702 : parallel.1.gz
Considering /usr/share/man/man1/parallel.1.gz
   Trying Type1ManParser
      Command is 'parallel'
      Unable to find options
      Trying fallback
      Still not found
      Trying last chance fallback
      '"command" ' doesn't contain '-'
      '"{}" ' doesn't contain '-'
      '"{.}" ' doesn't contain '-'
      '"{/}" ' doesn't contain '-'
      '"{//}" ' doesn't contain '-'
      '"{/.}" ' doesn't contain '-'
      '"{#}" ' doesn't contain '-'
      '"{%}" ' doesn't contain '-'
      '"{n}" ' doesn't contain '-'
      '"{n.}" ' doesn't contain '-'
      '"{n/}" ' doesn't contain '-'
      '"{n//}" ' doesn't contain '-'
      '"{n/.}" ' doesn't contain '-'
      '"{=perl expression=}" ' doesn't contain '-'
      '" Q(string)" ' doesn't contain '-'
      '" pQ(string)" ' doesn't contain '-'
      '" uq() (or uq)" ' doesn't contain '-'
      '" hash(val)" ' doesn't contain '-'
      '" total_jobs()" ' doesn't contain '-'
      '" slot()" ' doesn't contain '-'
      '" seq()" ' doesn't contain '-'
      '" \\f(CB@arg" ' doesn't contain '-'
      '" skip()" ' doesn't contain '-'
      Unable to split option from description
   Trying TypeDeroffManParser
   /usr/share/man/man1/parallel.1.gz contains no options or is unparsable (tried parser Type1ManParser, TypeDeroffManParser)
```

Full log and copy of the man page attached. Haven't dug any deeper yet.
 
- fish, version 3.6.1
- Linux leno-xcpn 6.5.6-300.fc39.x86_64 # 1 SMP PREEMPT_DYNAMIC Fri Oct  6 19:57:21 UTC 2023 x86_64 GNU/Linux
- xterm-256color
- Ran everything in a clean temp environment as requested

--

- [man_parallel.txt](https://github.com/fish-shell/fish-shell/files/13043916/man_parallel.txt)
- [fish_update_completions.log](https://github.com/fish-shell/fish-shell/files/13043917/fish_update_completions.log)

**Comment by faho** [comment]
To be honest: Any effort here would be better spent writing a completion script for `parallel` by hand. Adding more and more specific formats to the man page extractor is folly.

In this specific case, parallel has a lot of things that are in places where we expect an option, but aren't options. That's not something that's really extractable - because *either* it's a load of non-option stuff, or it's an option without the `-` specified.

I would recommend simply writing a completion script.

**Comment by chanceymathews** [comment]
I have to admit that for as long as I've been using Fish I've never paid attention to how the completions were done until today. I kind of assumed they were all automatically generated from the man pages. If I had spent a few more minutes digging I probably would have noticed share/completions and the contributors guide and spared you another ticket. I will take a stab at making a completion. Thank you for your patience!

**Comment by faho** [comment]
Alright, I'm closing this as not-planned because parallel's man page simply isn't parseable.

If someone wants to do something here, that something is to write a completion script.

(keeping issues open for "add completion script for X" isn't helpful because that would be hundreds of issues that purely mark demand)
