### ISSUE TITLE
git completion doesn't handle filenames with \r well

### ISSUE THREAD

**Issue by z3ntu** [fish-shell/fish-shell#10072]
fish, version 3.6.1

I know this is a super weird "use case"^^
```
$ mkdir /tmp/test && cd /tmp/test/
$ git init
$ touch foobar\r
$ git add foo<TAB>  # results in this:
$ git add foobar\\r
fatal: pathspec 'foobar\r' did not match any files

# this works
$ git add foobar\r
# or this also works (for some reason?)
$ git add foobar\\\r
```
So the tab completion is adding `\\r` while it probably just should be `\r`

Same it seems with `\n` from a brief test.

Sidenote: Tab completion for e.g. `less foo<TAB>` works correctly, using one backslash instead of two.

**Comment by faho** [comment]
I'm going to call this one unfixable as it stands:

We use `git status --porcelain=2`, and without `-z` that escapes things like `\r` on its own. That's not easily reversible in general because we don't really know *what* git escapes or how it escapes it, we can't really throw it into `string unescape`.

And unfortunately with `-z`, ostensibly the option meant for this, it will also start absolutizing paths, which makes it really hard to complete things. That's an awkward coupling of concerns from git's side, but if we have to pick one I'm going to pick the more common one.

That means I'm just going to tell you to not use carriage return in your filenames, sorry.

**Comment by z3ntu** [comment]
Ok :sweat_smile: Thanks for looking into this! Hopefully I'll never see a git repo again that has a file like this ;)
