### ISSUE TITLE
`$__fish_vendor_confdirs` is undocumented

### ISSUE THREAD

**Issue by 9999years** [fish-shell/fish-shell#10078]
As of Fish 3.6.1, `$__fish_vendor_confdirs` is undocumented.

There's `$fish_user_paths`, `$fish_complete_path`, and `$fish_function_path`, but there's no obvious place to add another `conf.d` directory. 

I was able to find `$__fish_vendor_confdirs`, but the double underscore seems to imply it's private.

The [documentation for configuration files](https://fishshell.com/docs/current/language.html#configuration-files) mentions a few places that `conf.d` directories are looked for (`$__fish_config_dir/conf.d`, `$__fish_sysconf_dir/conf.d`, `$__fish_user_data_dir/conf.d`, `$XDG_DATA_DIRS`), but doesn't mention `$__fish_vendor_confdirs` or any other variable that contains a list of `conf.d` directories.

See also:
- #8553

Context: Nix installs Fish completions, functions, and `conf.d` files under `~/.nix-profile/share/fish/`.

**Comment by faho** [comment]
> but there's no obvious place to add another conf.d directory.

And that's for a simple reason: Where would you add it? By the time you get to do that, the files will either already have been read or at least have been determined.

And since you can't unsource a script, there is no user-level knob to turn here.

> Context: Nix installs Fish completions, functions, and conf.d files under ~/.nix-profile/share/fish/.

For system integration like that we have a file called ,[__fish_build_paths.fish](https://github.com/fish-shell/fish-shell/blob/master/share/__fish_build_paths.fish.in) that packagers can customize during the build.

The nix people know about that because we added it specifically for them, in consultation.

Other than that you can always just source a directory yourself, it just doesn't participate in the conf.d precedence.

I'm happy to document something to that effect.

**Comment by 9999years** [comment]
Thanks, that makes a lot of sense! Having that documented would be great — if I have some free time I can put up a PR.
