### ISSUE TITLE
Tests are broken in release 3.6.2

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#10134]
I thought I'd run the test suite, but it looks like I didn't.

```
Testing file checks/basic.fish ... Failure:

  The CHECK on line 596 wants:
    \\Xef\\Xb7\\X92foo

  which failed to match line stdout:98:
    \\$\\\\ufdd2foo

  Context:
    [...] from line 542 (stdout:95):
    bar
    baz
    C
    \\$\\\\ufdd2foo <= does not match CHECK on line 596: \\Xef\\Xb7\\X92foo
    ./argv0.sh
```

The check is looking for the UTF-8 encoding.

I've already pushed the advisory and the new release, so I can make a 3.6.3 to fix the tests.

**Comment by cole-h** [comment]
I'm seeing the same -- 3.6.3 has this failure but 3.6.2 does not.

**Comment by zanchey** [comment]
Thanks. @faho reckons they pass on his machine as well, but they fail on my local machines and on all CI platforms with 3.6.2. So more digging to be done, but it's way past my bedtime here!

**Comment by faho** [comment]
The issue is /bin/sh - on my system that is bash, on Ubuntu and Debian it's dash.

And it turns out that dash won't do `$''` quoting. My fault, I could have sworn this was in POSIX. (this is one of the reasons I prefer to write for a specific shell)

I would like if we could easily get something *else* to generate a U+FDD2, but I don't believe there's a good version without introducing a dependency, so we'll just let our printf do it:

```fish
echo (printf '\ufdd2foo') | string escape
# CHECK: \Xef\Xb7\X92foo
```

That's https://github.com/faho/fish-shell/commit/b2ef44a277de5bfe85b193ae37c859ea61818ac6

**Comment by dcermak** [comment]
> That's [faho@b2ef44a](https://github.com/faho/fish-shell/commit/b2ef44a277de5bfe85b193ae37c859ea61818ac6). Passes on my system and Github Actions.

This patch fixes the test failure in openSUSE Tumbleweed and Fedora Rawhide, thanks for creating it!

Will you create another dot release or should we patch this downstream?

**Comment by zanchey** [comment]
I'll do a new release tonight.

**Comment by dcermak** [comment]
David Adam ***@***.***> writes:

> I'll do a new release tonight.

Thanks!
