### ISSUE TITLE
Upgraded to version 3.6.4 and now all my configuration is broken 

### ISSUE THREAD

**Issue by amir20** [fish-shell/fish-shell#10139]
version: `fish, version 3.6.4`
uname: `Darwin amirraminfar-macbookpro.roam.internal 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64`

I recently updated via `brew upgrade` from `3.6.1` to `3.6.4`. In the process, I can't figure out what happened but all my fishshell is broken. My `PATH` is reset. Commands like `psub` do not work.  I have a custom location for homebrew at `/Users/amirraminfar/homebrew/bin`. 

When creating a new tab,  I see a terminal which looks like this: 
<img width="1138" alt="Screenshot 2023-12-05 at 1 07 44 PM" src="https://github.com/fish-shell/fish-shell/assets/260667/76fe5274-7518-48bc-a799-77a9b58fbdd7">

```
cat /etc/shells
# List of acceptable shells for chpass(1).
# Ftpd will not allow users to connect who are not using
# one of these shells.

/bin/bash
/bin/csh
/bin/dash
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh
/usr/local/bin/fish
/Users/amirraminfar/homebrew/bin/fish
```

Fish is in my `shells` file.  and `echo $SHELL` prints `/Users/amirraminfar/homebrew/bin/fish`. 

But I am clueless to why everything seems broken. `starship` seems to not load. I get multiple errors.  When I do `set --export PATH /Users/amirraminfar/homebrew/bin $PATH` I can at least get some of my binary files back. 

I have tried doing `brew rm fish` and `install` again. No luck. It feels like none of my configuration files are being loaded.

Is there a way to investigate what might actually be broken?

**Comment by faho** [comment]
fish 3.6.4 has one effective commit over 3.6.1 (plus some changes to the test suite, which you do not run). This commit changes how some unicode non-character codepoints are handled and you are very unlikely to hit it.

That means any breakage here is much more likely to be in the *install* rather than the code itself.

You want to check `fish --debug config`. It will tell you 

>config: sourcing /usr/share/fish/config.fish
config: sourcing /etc/fish/config.fish
config: sourcing /path/to/.config/fish/config.fish

which includes which config it sourced. It is likely you have a setup that looks in the wrong place, because of $XDG_CONFIG_HOME or a miscompile on homebrew's part.

**Comment by amir20** [comment]
Thanks. I am not able to make sense of what is going on. I do agree it seems to be something about my install.  I tried running your command on a brand new tab and everything seems broken. If I manually update `$PATH` then I can run some these paths. 

<img width="1138" alt="Screenshot 2023-12-05 at 1 27 48 PM" src="https://github.com/fish-shell/fish-shell/assets/260667/921341e3-770a-48bf-94a1-d6c443a9dff0">

Based on the error it seems that `config: not sourcing /opt/homebrew/Cellar/fish/3.6.4/share/fish/config.fish (not readable or does not exist)` is the error.  But my install directory is `/Users/amirraminfar/homebrew/`

Both `echo $version` and `fish --version` point to `3.6.4`.  `$XDG_CONFIG_HOME` is blank. 

So great, I think the debug statement helps. However, I cannot understand why it is using that directory.

**Comment by faho** [comment]
Okay, that's a build configuration problem - "/opt/homebrew/Cellar/fish/3.6.4/share/fish/config.fish" is the equivalent of /usr/share/fish/config.fish in a regular configuration, while you expect a path in your $HOME.

It appears homebrew doesn't set the prefix correctly. Unfortunately there is nothing we can do on our side, this *has* to be fixed in brew.

And as far as I understand they do not support alternate prefixes, so it is possible if you file an issue it will be closed.

I believe your best options are to build fish yourself or switch brew to the default paths. Sorry.

**Comment by amir20** [comment]
Thanks @faho I was able to debug some more. At work, we are not allowed to use `/usr/share` but something must have changed with homebrew recently. Luckily, withe new M1 chip, the install location has changed which I was able to reinstall using the default homebrew location. 

I did find a problem that I can't tell if it is a bug or not. After installing homebrew, it suggest to use 

```
 (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/amirraminfar/.config/fish/config.fish
```

However, my files in `.config/fish/conf.d` where still not able to find the binary files from brew. I was able to use `fish_add_path` instead. 

Perhaps the files in `conf.d` files are loaded in parallel? Is this to be expected? 

Thanks again for the quick reply.

**Comment by faho** [comment]
>Perhaps the files in conf.d files are loaded in parallel? Is this to be expected?

The files in conf.d are loaded *before* config.fish. This is so you can drop in a file in conf.d and then undo something that did in config.fish.

So if you want your things in conf.d to have access to path changes, you can either create a conf.d file that is loaded first ("00-paths.fish"), or you can add the path changes to a universal $fish_user_paths, which is what you've effectively done now.

**Comment by SteffenDE** [comment]
This is interesting. I am experiencing exactly the same issue (non-default brew install), but it does not seem like anything changed in the homebrew fish formula except the version https://github.com/Homebrew/homebrew-core/commits/master/Formula/f/fish.rb

**Comment by amir20** [comment]
I see your comment on the other bug. I spent a lot of time on this for sure. Good to know `brew install -s fish` would have fixed it. I am also confused as it seems nothing has changed so not clear why this completely broke the installation.

**Comment by amir20** [comment]
Agreed. I also tried to spend some time figuring what prints out `(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/amirraminfar/.config/fish/config.fish` as it doesn't look to be the right step. But wasn't able to find it to send PR. 

Thanks @faho for quick responses.
