### ISSUE TITLE
Changing shell to fish on Raspberry Pi 5 breaks system

### ISSUE THREAD

**Issue by Multowz** [fish-shell/fish-shell#10132]
I've installed fish on my Raspberry Pi 5 and changed shell with `chsh -s /usr/bin/fish`. Then I restarted but couldn't access to system again. I'm getting `Cannot execute /usr/bin/fish: No such file or directory`. If I switch to another tty and try to login, every time the same message appears on screen and quickly disappears.

The message:
`Linux raspberrypi 6.1.0-rpi6-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.58-1+rpt2 (2023)
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the individual files in /usr/share/doc/*/copyright.
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent permitted by applicable law.
Last login: Mon Dec 4 00:12:40 +03 2023 on tty2`

OS: Raspberry Pi OS GNU/Linux 12 (bookworm)
Device model: Raspberry Pi 5 Model B Rev 1.0

**Comment by faho** [comment]
Alright. What most likely happened here was that your fish was not installed at /usr/bin/fish, and /etc/shells was wrong (or you added the wrong entry).

However, without your reply there isn't anything we can do to confirm that. I'll be closing this because it's been a week without more information, if you get back to us we can reopen.
