### ISSUE TITLE
this is /usr/bin/git in top of my command line. why this is

### ISSUE THREAD

**Issue by Afshinafshi** [fish-shell/fish-shell#10148]
this is /usr/bin/git in top of my command line. why this is .
this is not good for me .
please helps me
:
![Screenshot from 2023-12-11 23-27-37](https://github.com/fish-shell/fish-shell/assets/138600371/4cd9b618-87e4-4b13-93fc-24ae9f4f6fe9)

**Comment by faho** [comment]
You will have to check your prompt.

It appears you have *something* that prints output where it should be silenced, e.g. by using `if command -s git` instead of `command -sq git`.

Your prompt isn't a fish preset, and I am unaware of one of ours doing it, so I am going to assume it is something about your own functions or your plugins doing it.

Try `grep -r git ~/.config/fish` and see if that turns anything up. Try `funced fish_prompt` and see if there's anything there.

**Comment by Afshinafshi** [comment]
i using :
![Screenshot from 2023-12-11 23-49-33](https://github.com/fish-shell/fish-shell/assets/138600371/8a25c1cf-3f8a-42e5-81b9-54d7a65b64e2)

**Comment by Afshinafshi** [comment]
What should I delete?

**Comment by Afshinafshi** [comment]
or editing

**Comment by Afshinafshi** [comment]
Thanks you ,  you solving the my problem.

my problem was in my theme, because at one line writing 

`command -v` and i replacing the your code   `commnad -sq `
