### ISSUE TITLE
cannot bind ctrl+0

### ISSUE THREAD

**Issue by m4rch3n1ng** [fish-shell/fish-shell#10142]
```
$ fish --version
fish, version 3.6.1-1011-gccc8308d4
```

not sure if i missed something, but i can't seem to bind ctrl+0.

`bind \c0` throws an invalid token error, and `bind \c\0` just doesn't seem to do anything.

```
$ bind \c0 "echo test"
fish: Invalid token '\c0'
bind \c0 "echo test"
     ^~^
```

```sh
$ bind \c\0 "echo test"
$ 0 # << after pressing ctrl+0 it just prints the 0 instead of executing
```

**Comment by faho** [comment]
The answer here is simple, yet annoying: ctrl+0, that is "control plus zero" does not exist.

It is not a keychord your terminal can send.

You can try running `fish_key_reader` and pressing ctrl+0, and it will tell you to bind `0`, because pressing ctrl+0 sends the exact same thing as just zero by itself. You can compare e.g. emacs (press ctrl-h, then k and then ctrl+0, and it will also tell you about 0 by itself)

For historical reasons the protocol terminals use to send keys is quite limited and this is one of the casualties.

**Comment by m4rch3n1ng** [comment]
i don't know how, but i am able to bind `"<C-0>"` in neovim, so i figured that it should be possible for fish to handle that too

**Comment by faho** [comment]
Neovim probably supports one of the numerous attempts at extending terminal keybindings.

Fish does not, and tbh unless one of those actually turns out to win I don't see us supporting it.

Case in point: If I try binding `<C-0>` in my nvim in a terminal it doesn't error out, but pressing ctrl+0 does not actually trigger the binding.

Sorry, this is not possible with a typical terminal.

**Comment by m4rch3n1ng** [comment]
ah that makes sense, i'm using kitty and i think that one is known for supporting some wacky standards, so it makes sense that it works in neovim. still sucks that it doesn't work in a regular terminal (but now that i think about it i actually ran into a similar issue recently, where my program couldn't distinguish between space and shift-space)
