### ISSUE TITLE
calling job for event handler not found

### ISSUE THREAD

**Issue by gour** [fish-shell/fish-shell#10156]
Hello,

I'm using fish, version 3.6.4 on openSUSE Tumbleweed (`Linux atmarama.ddns.net 6.6.6-1-default #1 SMP PREEMPT_DYNAMIC Mon Dec 11 09:46:39 UTC 2023 (a946a9f) x86_64 x86_64 x86_64 GNU/Linux`), gnome-terminal-3.50.1 (`xterm-256color`) and after I quit mc (Midnight Commander) I get the following error:

```
/usr/share/fish/vendor_functions.d/mc.fish (line 17): function: calling job for event handler not found
    function _remove_tmp --on-job-exit caller --inherit-variable _fish_MC_PWD_FILE
    ^
in function 'mc'
```
and not sure whether it is fish-related problem or something with the version shipped by openSUSE?

I'm attaching `mc.fish` file...

[mc.txt](https://github.com/fish-shell/fish-shell/files/13692015/mc.txt)

**Comment by faho** [comment]
This is a function shipped with mc, it appears to have a bug.

The handler function here is pretty useless, and the `--on-job-exit caller` doesn't work because it needs a command substitution - it would be called when you do `cd (mc)` when the *cd* exits.

This has errored out for basically ever. The solution is to just entirely remove the event-handler and add the code in the function itself.

I'm going to call this an upstream bug.
