### ISSUE TITLE
some personal issues with documentation

### ISSUE THREAD

**Issue by perillo** [fish-shell/fish-shell#10201]
I recently installed fish (3.7.0) and after reading the official documentation I found some issues:

## Globbing

Coming from ZSH, I tried to do `**/*.fish`, and failed.

Looking at https://fishshell.com/docs/current/language.html#wildcards-globbing, it was not clear (to me) that the correct syntax is `**.fish`.

A simple fix is to add or replace the example with:
```fish
**.fish
```

or adding a "Fish for zsh users" document.

## Keyword/Reserved Words

I found it strange that the the list of reserved words is documented in https://fishshell.com/docs/current/cmds/function.html.   What about an additional section in `language.html`?

## Operators

It may be convenient to have a separate section/document for the supported operators.

Thanks.

**Comment by krobelus** [comment]
I think `**/*.fish` matches exactly the same as `**.fish` so I'm not sure what's the problem.
The docs put it as

> If ** is a segment by itself, that segment may match zero times, for compatibility with other shells.

**Comment by faho** [comment]
> I think **/*.fish matches exactly the same as **.fish so I'm not sure what's the problem.

Yup, these should be equivalent, and some testing seems to confirm that.

> It may be convenient to have a separate section/document for the supported operators.

What do you mean by "operators"? What would you expect in that section?

> or adding a "Fish for zsh users" document.

I don't believe that adding more of those is a great idea - "fish for bash users" does bash as a superset of sh, and that should be close enough for zsh people, who are likely to know sh in general and bash specifically.

It's 90% of the bang for very little of the buck, more documents means more to keep up-to-date. (plus I don't actually know zsh script and don't really want to learn it because it seems like sigil soup to me)

> I found it strange that the the list of reserved words is documented in https://fishshell.com/docs/current/cmds/function.html. What about an additional section in language.html?

The reason it is in function is because that's where you're likely to run into it. What other context are you seeing reserved keywords in?

**Comment by perillo** [comment]
> > I think **/*.fish matches exactly the same as **.fish so I'm not sure what's the problem.
> 
> Yup, these should be equivalent, and some testing seems to confirm that.

Thanks for the clarification.  Probably I run `**/*.xxx` on a directory without `xxx` files and I assumed it was not supported.

However this raises another question: what is the difference, if any, between `**/*.fish` and ``**.fish``?  As a counter example, in zsh the latter does not match subdirectories.

## fish

```console
> ls **/*.fish
conf.d/add-origin.fish  config.fish

> ls **.fish
conf.d/add-origin.fish  config.fish
```

## zsh

```console
% ls **/*.fish                                                                                                                    
conf.d/add-origin.fish  config.fish

% ls **.fish                                                                                                                      
config.fish
```

> 
> > It may be convenient to have a separate section/document for the supported operators.
> 
> What do you mean by "operators"? What would you expect in that section?
> 

The list of operators used by fish like `&` and `$`. Not sure if `&&` and `||` are operators, since `language.html` call them *combiners*.
  
> > I found it strange that the the list of reserved words is documented in https://fishshell.com/docs/current/cmds/function.html. What about an additional section in language.html?
> 
> The reason it is in function is because that's where you're likely to run into it. What other context are you seeing reserved keywords in?

When learning a new language I usually start with the language reference, looking at the keywords and operators.

**Comment by faho** [comment]
> As a counter example, in zsh the latter does not match subdirectories.

If you turn on `setopt GLOBSTARSHORT` it does.

If you don't, `**` is the same as `*`.

Both `**.fish` and ``**/*.fish` should return the same results in both fish and zsh with that option.

> The list of operators used by fish like & and $. Not sure if && and || are operators, since language.html call them combiners.

Well, that's just the question, we don't really use the word "operator" currently.

Are all these operators:

- `<` and `>` as well as variants like `&>` and `>>`
- `|` and variants like `&|`
- `&` and `;`
- `&&` and `||`
- `$`
- `$(` and `(`
- `*`

> When learning a new language I usually start with the language reference, looking at the keywords and operators.

There's a difference between "keywords" and "reserved keywords" (which tbh we should probably just call "reserved words"). The latter really *just* means "can't be used as a function name.

E.g. `read` isn't a keyword, but we disallow it as a function name because you cannot implement a compatible `read` function (because of `read --local`). So, to avoid common mistakes, we reserve it.

The list of "proper" keywords with syntactic relevance would just be "and", "or", "begin", "break", "builtin", "case", "command", "continue", "else", "end", "exec", "for", "function", "if", "not", "or", "return", "while".

You will find these, with the exception of `end` and `else`, in https://fishshell.com/docs/current/commands.html#keywords.

I'll add those latter two.
