### ISSUE TITLE
vi mode: user created shortcuts/bindings always exit insert mode

### ISSUE THREAD

**Issue by gretaSamsa** [fish-shell/fish-shell#10216]
fish, version 3.7.0
3.7.0
5.15.0-91-generic, Ubuntu, x86_64
I am not using any third-party customizations.

User created bindings, such as binding `/eL` to `__fish_list_current_token`, cause fish to exit insert mode and must be entered a second time before executing, while the default binding `/el` does not.

Steps to reproduce:
1. Create any user-defined binding, for example `bind /eL __fish_list_current_token`.
2. Enter vi mode and insert mode.
3. Enter the user-created binding. Fish switches to command mode.
4. Enter the user-created binging again. It works as expected otherwise.

Expected behavior:
Either fish should execute the user-defined binding while remaining in insert mode, or allow the user to specify that a binding should be executed while staying in insert mode.

**Comment by faho** [comment]
You defined your binding in default mode, which is the vi-normal mode, so your current mode does not *have* an `\eL` binding, so this is interpreted as `\e` and `L`. And `\e` is escape, which switches to normal mode.

That's what happens when you don't list a mode.

You want `bind --mode default \eL __fish_list_current_token`.

Or, as [the documentation puts it](https://fishshell.com/docs/current/interactive.html#custom-bindings):

> If you use [vi bindings](https://fishshell.com/docs/current/interactive.html#vi-mode), note that bind will by default bind keys in [command mode](https://fishshell.com/docs/current/interactive.html#vi-mode-command). To bind something in [insert mode](https://fishshell.com/docs/current/interactive.html#vi-mode-insert):
