### ISSUE TITLE
vi mode: output of user-created bindings can be erased while entering insert mode

### ISSUE THREAD

**Issue by gretaSamsa** [fish-shell/fish-shell#10217]
fish, version 3.7.0
3.7.0
5.15.0-91-generic, Ubuntu, x86_64
xterm-256color

Steps to reproduce:
1. Create the function `__test`, which is only the command `echo "test"`.
2. Create a keybinding for this function, for instance `bind --mode insert \e5 __test`.
3. Put fish into vi mode and insert mode.
5. Enter the keybinding. The function is executed and the text "test" appears after the prompt and the screen scrolls. The prompt is not printed.
6. Enter command mode. The line with the output is overwritten by the prompt, if it is a multi-line prompt.

Expected behavior:
The output produced by the user shortcut should be on the line under the prompt, which is the normal behavior for shortcuts like `\el`.
The prompt should also appear on the line under the output. If the user's prompt spans more than one line, the output of the shortcut function should not be overwritten.

**Comment by faho** [comment]
Fish does not move the cursor for functions called via bind.

That's because they could also do things to the commandline - in fact that's what they are meant for.

If you want to print output under the prompt, you'll have to do it yourself:

```fish
function __test
    # move the cursor down one line
    tput cud1
    # print what you want
    echo foo
    # echo printed a newline, so we need to go up *two* lines
    tput cuu 2
    # repaint the commandline to get the cursor back
    # at its old position in the line
    commandline -f repaint
end
```

This isn't something you're really supposed to do, it is going behind fish's back.

Alternatively, do what e.g. [__fish_list_current_token](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_list_current_token.fish) does and move *down* and print a new prompt:

```fish
string repeat -N \n --count=(math (count (fish_prompt)) - 1)

commandline -f repaint
```
