### ISSUE TITLE
custom bindings are ignored when using vi key bindings

### ISSUE THREAD

**Issue by joseluis** [fish-shell/fish-shell#10236]
using fish, version 3.7.0 installed from the ppa                                                                          
Linux t480lu 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
using multiple terminals
  
> Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:
  
    sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'
    
yes that solves it.

---

Custom bindings are being completely ignored in all terminals. I discovered that depends on having configured at some point:

    set fish_key_bindings fish_vi_key_bindings # or fish_hybrid_key_bindings

That setting persists a completely empty configuration. In order to revert it I have to run:

    set -e (set -U | cut -d" " -f1)

which only leaves 121 preset bindings, from more than 400 otherwise. And then I can successfully set and use a binding like this:

    bind \co nano
   
And it works even if it overrides a preset like Ctrl+R (e.g.: `bind \cr "echo CTRL+R"`)
   
The moment I configure the fish_key_keybindings  with something else than fish_default_key_bindings any custom bindings stop working.

My question is how can I use vi bindings, and at the same time being able to configure custom bindings?

**Comment by faho** [comment]
From https://fishshell.com/docs/current/interactive.html#custom-bindings:

> If you use [vi bindings](https://fishshell.com/docs/current/interactive.html#vi-mode), note that bind will by default bind keys in [command mode](https://fishshell.com/docs/current/interactive.html#vi-mode-command). To bind something in [insert mode](https://fishshell.com/docs/current/interactive.html#vi-mode-insert):

>    bind --mode insert \cc 'commandline -r ""'

**Comment by lydell** [comment]
It would be awesome if the note about vi mode was on https://fishshell.com/docs/current/cmds/bind.html as well. I ended up on that documentation page instead of https://fishshell.com/docs/current/interactive.html#custom-bindings, and it took me forever to figure out why the examples on that page “didn’t work” 😅

**Comment by zanchey** [comment]
It currently says

> The default mode is "default" (in vi-mode, that's vi's "normal" mode). Every key binding applies to a single mode; you can specify which one with `-M MODE`.

and the example uses `-M insert`, so I'm not sure if we can make that clearer.

**Comment by lydell** [comment]
> It currently says

That’s great! It’s so far away from the examples, though, that I didn’t notice.

> and the example uses `-M insert`, so I'm not sure if we can make that clearer.

Well, one of them do:

<img width="836" alt="Image" src="https://github.com/user-attachments/assets/cd879d8b-5e51-4bb0-bce8-81ece1dbb457" />

And I could totally have deduced how it works from that. But I just glossed over that example, because “I already know how to enable vi mode” and because my brain summarized the example as “here’s how to do something fancy in insert mode”.

The other page examples look like this:

<img width="840" alt="Image" src="https://github.com/user-attachments/assets/eff0df0a-2d30-4c8b-839f-fbd36e14f7dd" />

The section at the end makes it very clear that it is a common pitfall that the default mode is “command mode” (in other words, not the default mode when you start the shell) and how to “fix” your binding.

So my suggestion would simply be to add this at the end of https://fishshell.com/docs/current/cmds/bind.html#examples:

> If you use [vi bindings](https://fishshell.com/docs/current/interactive.html#vi-mode), note that bind will by default bind keys in [command mode](https://fishshell.com/docs/current/interactive.html#vi-mode-command). To bind something in [insert mode](https://fishshell.com/docs/current/interactive.html#vi-mode-insert):
>
>     bind --mode insert ctrl-g 'git diff' repaint
