### ISSUE TITLE
No bind mode for search fields, and no way to make forward-char move the cursor

### ISSUE THREAD

**Issue by krobelus** [fish-shell/fish-shell#10268]
https://www.reddit.com/r/fishshell/comments/1ac09ed/rebind_the_arrow_keys_in_the_history_pager/ shows that in the search field (as created by Shift+Tab for normal completions or Control+R for the history pager)

1. `forward-char` and `backward-char` always move to the next/previous completion, with no way to move the cursors left/right
2. rebinding navigation keys doesn't really work; doing something like `bind \ck up-line` would break things because it also applies outside search mode

Not sure if one of the active contributors will consider this as worth doing themselves but it sounds reasonable to make bindings more flexible.
Maybe the history pager makes this important enough.
Though I kind of doubt it, it's better to get used to the default key bindings IMO.
Just I wanted to open this so it doesn't get lost.

**Comment by wadeduvall** [comment]
So, I actually tried `bind \ck up-line`/`bind -M INSERT \ck up-line` etc and this doesn't take effect in the pager. So I really think this is a missing feature. I could be wrong (just switched to fish) but

**Comment by faho** [comment]
> I actually tried bind \ck up-line/bind -M INSERT \ck up-line etc and this doesn't take effect in the pager. 

Nah, it's just spelt "insert", not "INSERT".

**Comment by wadeduvall** [comment]
@faho ` bind -M insert \cj up-line` also does not work in the pager...

**Comment by faho** [comment]
Works for me.

`\cj` *is* newline (as in the terminal sends the actual bytes for newline when you press control and j), it is possible you've bound something else.

**Comment by wadeduvall** [comment]
@faho yup, tmux was grabbing it.

**Comment by faho** [comment]
Anyway, the underlying issue here is that the pager is a bit of a mess, binding-wise.

It was added before the introduction of modes (which were added when the vi-bindings were, which IIRC was the only time someone got a bounty for working on fish), and the entire system doesn't work *particularly* well.

For the most part it works because we've hacked the defaults to do things in the pager. E.g. complete-and-search will navigate backwards, which doesn't make a lot of sense except when you consider that it's bound to shift-tab by default.

The way I believe this was originally envisioned was that you would script bindings with `commandline --paging-mode`:

```fish
if commandline --paging-mode
    commandline -f up-line
else
    commandline -f forward-char
end
```

Which has some issues, especially given that we enqueue the commandline functions again, so if you're scripting bindings you run into the limits quite quickly.

I think something more akin to modes would work here - you would add specific bindings for inside the pager:

```fish
bind --mode pager -k btab up-line
```

Of course, this would, by default, clash with the vi-notion of modes.

**Comment by krobelus** [comment]
Ok so one possible solution would be to add readline commands that behave like `forward-char` except they always move the cursor, not the selected completion.

**Comment by faho** [comment]
That's forward-char and backward-char plus forward-single-char.

Plus if we get additional commands for vi-mode wrt cursor position that's another three.

**Comment by faho** [comment]
What about bind functions that change if the search bar is focused or not?

Moving to insert mode in the pager would then focus it, and moving to normal/"default" mode would unfocus it.

**Comment by krobelus** [comment]
> The way I believe this was originally envisioned was that you would script bindings with commandline --paging-mode:
> 
> if commandline --paging-mode
>     commandline -f up-line
> else
>     commandline -f forward-char
> end
> Which has some issues, especially given that we enqueue the commandline functions again,

This works fine now in latest master.
Also we have `forward-char-passive` and `backward-char-passive`, so both problems raised in this issue should be addressed.
