### ISSUE TITLE
cd tab completion can not show unicode characters

### ISSUE THREAD

**Issue by ghost** [fish-shell/fish-shell#103]
To reproduce: Enter a directory named "测试" which are Chinese characters. Type <code>cd&lt;space&gt;&lt;tab&gt;</code>.

Result: Fish shows the directore as "\Xe6\Xb5\X8b\Xe8\Xaf\X95/".

**Comment by pickfire** [comment]
I have a problem displaying **cjk** characters in `fish`.

- `ls` shows `?` instead of the characters
- **tab completion** show `\Xe8\X8a\Xb1\Xe3\X81\Xae\Xe3\X83\X80\Xe3\X83\Xb3\Xe3\X82\Xb9\` instead of characters
- `LANG` is `en_US.UTF-8`
- `LC_CTYPE` is ``
- I still cannot figure out how to change locale in fish, `export` and `set -U` does not work
- I am using `fish, version 2.2b1-50-ga5fabc6`
- `uname -a`: `Linux alarmpi 4.0.7-1-ARCH #1 SMP PREEMPT Wed Jul 1 15:20:35 MDT 2015 armv7l GNU/Linux`

**Comment by ridiculousfish** [comment]
This doesn't sound fish specific. fish doesn't try to set your locale or interfere with normal techniques. How do you normally set it? What happens if you run `set -x LC_ALL en_US.UTF-8`?

**Comment by pickfire** [comment]
In **.zshrc**:
```
#------------------------------------------------------------
# Language
#------------------------------------------------------------

# Enforce correct locales from the beginning:
# LC_ALL is unset since it overwrites everything
# LANG=en_GB.UTF-8 is used, except for:
# LC_MESSAGES=C never translates program output
unset LC_ALL  # Since it overwrites everything.
export LANG='en_GB.UTF-8'
export LC_MESSAGES=C  # Never translates program output.
```
It works now and `locale` shows no error after:
```
set -Ue LC_ALL
set -e LANG
set -Ux LANG en_GB.UTF-8
set -Ux LC_MESSAGES C
```
When I run `set -x LC_ALL en_US.UTF-8`, nothing happens and the `locale` is changed. Thanks.
