### ISSUE TITLE
feature: prompt_pwd function support hyperlinks

### ISSUE THREAD

**Issue by XhstormR** [fish-shell/fish-shell#10301]
Now tmux and alacritty both support interpretation of hyperlinks escapes, if fish function prompt_pwd can support this also, it would be grate.

Hyperlinks document: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

Demo:
```shell
printf '\e]8;;file:///usr/share/backgrounds/gnome/Waves.jpg\e\\This is a picture\e]8;;\e\\'
```

**Comment by faho** [comment]
Fish already gives the terminal the PWD via OSC-7, so your terminal already has the information.

Detecting if a given terminal supports a sequence is always a massive pain - unfortunately terminal developers tend to focus on adding features to their own terminal instead of making compatibility easy.

So I'm going to say that we don't want to do this. You can add it to your own prompt by doing something like

```fish
printf '\e]8;;file://%s\e\\\%s\e]8;;\e\\' $(string escape --style=url -- $PWD) $(prompt_pwd)
```

wherever you print the PWD.

**Comment by krobelus** [comment]
> Detecting if a given terminal supports a sequence is always a massive pain

We don't need to probe for this feature, we can use it unconditionally because terminals that don't support this feature will ignore it. systemd also outputs it always if stdout is a terminal (they have a compile-time option to turn it off but that's mainly for pagers that don't support this).

The question is whether this feature helps a real use case.
Since tmux by default open new windows in the directory of the session (not the current window's directory), I think it could improve the OOTB experience.
Unfortunately I haven't managed to make tmux 3.4 display hyperlinks, can you share steps to reproduce?

**Comment by XhstormR** [comment]
> Unfortunately I haven't managed to make tmux 3.4 display hyperlinks, can you share steps to reproduce?

@krobelus  Simply add this config to `.tmux.conf` file to enable the hyperlinks feature.
```
set -ga terminal-features "*:hyperlinks"
```

**Comment by faho** [comment]
> systemd also outputs it always if stdout is a terminal

That's good news, then.

I'm extremely careful to add any feature that terminals have to support because there are a ton of extremely bad terminals that people insist on using, but if we already have a big thing that uses a particular feature unconditionally it appears to be supported enough. If some obscure terminal has issues we can probably just tell people that better terminals are available for free.

> The question is whether this feature helps a real use case.

Tbh I personally haven't ever wanted this. I see now that the terminal would mark hyperlinks, which may be annoying. It will also typically open them in your graphical file manager, which I don't tend to really do.

**Comment by krobelus** [comment]
I agree that `prompt_pwd` doesn't have a strong case. Worth trying sure but not sure if it's a good default.

I think much more useful and less objectionable is to add hyperlinks to valid paths which are already underlined.
Possibly also to commands that resolve to scripts, like the new Ctrl-O binding.

> We don't need to probe for this feature

(actually we'd need to add a couple of exceptions for known-broken terminals; we can copy what gcc does (see `info gcc | less +/At.this.time`))
