### ISSUE TITLE
How to have completions for a command match that of an empty command line?

### ISSUE THREAD

**Issue by patrick-kidger** [fish-shell/fish-shell#10447]
I'm writing a (sub)command that should feel like it is executing on the original command line:
```shell
$ mytool run ...
```
e.g.
```shell
$ mytool run python path/to/foo.py
```

I'm trying to figure out how to add completions to this, so that it will provide these appropriately.

The best I've got so far is
```shell
complete --command mytool -n "__fish_seen_subcommand_from run" -a "$(complete -C)";
```
which will allow me to go from `mytool run<TAB>` to `mytool run python`, however at this point, extras tabs will continue to offer empty-command-line options: it will not redispatch to the completions for `python`. I'm not sure how to add this functionality.

Is this possible in Fish? The [docs on completions](https://fishshell.com/docs/current/completions.html) didn't make this clear for me, so if you like please consider this a doc-bug.

**Comment by faho** [comment]
This is essentially what the completions for [sudo](https://github.com/fish-shell/fish-shell/blob/master/share/completions/sudo.fish) or [env](https://github.com/fish-shell/fish-shell/blob/master/share/completions/env.fish) do.

In principle, what you need to do is to get `mytool run python` to complete like `python` - to do that, you need to run `complete -C python`.

So, you need to grab the commandline, and remove "mytool run" from it.

Fish has the [__fish_complete_subcommand](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_complete_subcommand.fish) helper function for this, and in the simplest case this would be

```fish
complete --command mytool -n "__fish_seen_subcommand_from run" -a '$(__fish_complete_subcommand --fcs-skip=2)'
```

where the "--fcs-skip=2" tells it to skip two tokens from the commandline - that's "mytool" and "run".

If your tool has e.g. options that come before the "run" this gets more complicated, see the sudo completions and the `__fish_sudo_print_remaining_args` helper function for how to do that.

-----

Your attempt here has two issues:

1. Because `"$(complete -C)"` is double-quoted, the `complete -C` will be run when the completions are *loaded*. That means if you attempt to complete something else, it will be stuck on the initial commandline
2. `complete -C` reruns completions on the entire current commandline (it's the implied default if you don't give it a "fake" commandline to operate on)

**Comment by patrick-kidger** [comment]
Aha! This is absolutely perfect.

I also learnt a lot about fish generates completions -- the explanation for how this comes together (I just spent a bit of time fiddling with `__fish_complete_subcommand` to see how it works) was super useful.

Thank you so much, I really appreciate the help.
