### ISSUE TITLE
disown key binding to fzf with xargs

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [fish-shell/fish-shell#10552]
Hi,

The below function and the key binding shows the shell prompt, but blocks the terminal so no new input can be entered until the opened document is closed. At this moment all new input is shown. Is it possible to disown the function and have the terminal accepting new input while the document is open?

```fish
function fzf_open
  fd --no-ignore -t file -e pdf -e djvu . ~/Downloads | fzf |
    nohup >/dev/null 2>&1 xargs -I {} xdg-open {}
end
bind \eo fzf_open
```
OS: Linux Arch (EndeavourOS)
Terminal: WezTerm 20240203-110809-5046fc22
Fish: v3.7.1

Thank you!

**Comment by faho** [comment]
You're running into what appears to be an xdg-open bug - in some paths, it will run whatever tool it opens in the foreground.

Now, you're *trying* to work around this with `nohup`, but that won't actually do what you're trying to do here because you don't background the job.

Of course you can't background the *job* because that includes `fd` and `fzf`, and you very much need `fzf` to be in the foreground.

Do something like this instead:

```
set -l file (fd --no-ignore -t file -e pdf -e djvu . ~/Downloads | fzf)
nohup xdg-open $file &>/dev/null &
disown $last_pid
```

**Comment by volodymyrprokopyuk** [comment]
Makes total sense! The solution you provided works! Thank you!
