### ISSUE TITLE
count full width space (aka Ideographic Space or U+3000) as a space

### ISSUE THREAD

**Issue by BPplays** [fish-shell/fish-shell#10592]
full width spaces are not counted as spaces i would like them to be

​
full width space:
```fish
censored@censored /d/d/__main [1]> docker　logs　nginx
fish: Unknown command: docker　logs　nginx
```
normal space:
```fish
censored@censored /d/d/__main [127]> docker logs nginx
Error response from daemon: No such container: nginx
```
​
​
​
fish --version:
```
-> fish --version
fish, version 3.7.1
```

**Comment by mqudsi** [comment]
Can we have some context here? Why are you using full width space? Is this the default for some international keyboard/locale?

**Comment by BPplays** [comment]
@mqudsi its somewhat of an niche use case but i find it easier to type on a phone one handed with a japanese flick input style keyboard and i was messing around with making aliases for common commands that i sometimes used when i ssh into a server from my phone and stuff like git has built in aliases for sub commands (i assume it support unicode chars) so you could use that and need to type 2 space separated strings of japanese chars and some japanese inputs use an Ideographic Space

**Comment by mqudsi** [comment]
I'm afraid that this is a significant change and a complication to how things are currently parsed and processed. It's a three-byte UTF-8 sequence, not defined in the C locale, and that would require making the tokenizer locale aware. I suggest looking into hacking the keyboard with some sort of shortcut for space or try a different app, because this is currently too out of scope with insufficient rationale to add.
