### ISSUE TITLE
Mistyping argument shows fish error

### ISSUE THREAD

**Issue by AxeldeWater** [fish-shell/fish-shell#10599]
Fish version: 3.3.1
OS: Linux Mint 21.3

I don't know whether this bug is fixed or not, since this is a pretty old version, but thought I'd file a bug report anyway.

Recently I started using Fastfetch, using its ppa. I tried using "fastfetch -v" but mistyped, and the moment I typed the wrong character an error is thrown at me by fish, before even executing the command. The error is as following:

`[CENSORED]@[CENSORED]-HP-ZBook-15u-G6 ~> fastfetch gstring match: Unknown option “-g”`

`/usr/share/fish/vendor_completions.d/fastfetch.fish (line 57): `
`string match -r -a -g "^###> ?(.*)" < (status -f) | string collect | python3 | source`
`^`
`from sourcing file /usr/share/fish/vendor_completions.d/fastfetch.fish`
`in command substitution`

`(Type 'help string' for related documentation)`

In this case I typed g, but same happens with other letters, consistently.

**Comment by zanchey** [comment]
This error is produced by the fastfetch completions, which are maintained by the [fastfetch project](https://github.com/fastfetch-cli/fastfetch/blob/dev/completions/fastfetch.fish) rather than in fish. The problem is that it uses an option to `string` which was only introduced in 3.4.0, but you are still using 3.3.1.

You could upgrade to a newer version [using the Ubuntu PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3) or create an empty completions file with `touch .config/fish/completions/fastfetch.fish` to suppress the loading of the completions completely and therefore preventing the error.

**Comment by AxeldeWater** [comment]
Ahhh alright, that explains a lot. I won't upgrade anything by force as it's not something really important to me. Would it make more sense to report this issue to the fastfetch developers in that case, or just leave it as is?

**Comment by zanchey** [comment]
Yes, you could ask them to reduce the version requirements. That whole stanza is easy to rewrite without the string magic. I'll look at a PR.

**Comment by AxeldeWater** [comment]
I see that the pull request has been merged. Does that mean this issue could be closed?

**Comment by AxeldeWater** [comment]
@zanchey I can confirm that the error is gone now. I'll close this issue.
