### ISSUE TITLE
SSH to machine with fish gives: `fish: Could not set up terminal`

### ISSUE THREAD

**Issue by terlar** [fish-shell/fish-shell#1060]
I have a machine I can not SSH into when it is running fish-shell as the shell. The strange thing is, if I use `mosh` instead of `ssh` it works. Or if I run `ssh` from within `tmux` then it works also. But never works when running directly from `fish` or `bash` launched under `fish`.

What could be causing this?

**Comment by kyleholzinger** [comment]
Just a little note, I had this issue and it was due to a small mistake when writing my fish config. I had:
```
set -gx TERM "xterm-256color" set -gx LSCOLORS "lksjakdjasdlk"
```

Looks like this causes fish to die immediately.

**Comment by faho** [comment]
@kyleholzinger: What fish version did you use with that? For me, fish screams about not being able to setup the terminal, but then goes on with a fallback TERM=ansi.

**Comment by kyleholzinger** [comment]
@faho I think 2.4.

**Comment by faho** [comment]
In that case, you'll be happy to hear that there have been fixes in this area since then.

Also, you should _not_ set $TERM in config.fish. Your terminal should set it properly. If it doesn't, complain to them or if it has a configuration knob for it, change it there. The reason for this is that we use $TERM for plenty of things, like detecting how many colors it supports (if this goes wrong, you'll see weird output) and detecting what sequence means what key combination (if this goes wrong, your binds will go weird). We also integrate with some special terminal features - in vte or terminal.app, we send the PWD specially (if this goes wrong, you'll once again see weird crap).

**Comment by krisavi** [comment]
I have same issue, but with custom made terminal sets. Combined 2 of the sets like "linux" and "rxtv-unicode-256color" to make "linux-256color". Well actually it even supports 24bit colors. After adding it as root it actually connected to fish shell without problems, but the shell is extremely slow and laggy. Seems to lag every time it tries to do any kind of character change on screen or show some suggestions...

Ansi fallback causes more problems, like screen popping up on autocompletion and overwriting text I was even typing. 

How can I force it to use 24bit or 256 color fish terminal mode?

**Comment by faho** [comment]
>I have same issue, but with custom made terminal sets. Combined 2 of the sets like "linux" and "rxtv-unicode-256color" to make "linux-256color"

You mean you made your own terminfo entry? I can only advise against that, since the remote machine won't have it so anything that uses terminfo will have issues.

And in this case specifically, using the "linux" entry makes no sense since that's the one for the kernel vt (the thing you get when you press ctrl+alt+fX), which is a rather... special kind of terminal, that supports very few things.

Unless of course you've patched your kernel to do 24bit color, in which case kudos to you and I'm eagerly awaiting upstream inclusion! 😄 

Or do you use rxvt? I wasn't aware that could do 24bit either.

>How can I force it to use 24bit or 256 color fish terminal mode?

Currently, the one knob we have for 24bit mode is a force-toggle. Set $fish_term24bit to 1 and it should use 24bit colors. However, other things like keybindings and such might have issues.

>Weird is that it seems to work fine on non-root mode, huge lag when on fish shell as root.

That actually points to it being caused by something different - how do you get root? By directly logging in or `su`? We've just merged a patch that works around some weird and unintuitive `su` behavior (it doesn't change $HOME when the target user is root), that might change something here.

**Comment by krader1961** [comment]
@krisavi, If @faho's feedback doesn't help please open a new issue. The problem you're describing is nothing like the problem this issue dealt with. Also, if you do open a new issue please provide some details such as the OS you're using, the terminal emulator, and the value of $TERM when running fish as root and a non-root user.
