### ISSUE TITLE
Command not found function not called in certain case

### ISSUE THREAD

**Issue by gwww** [fish-shell/fish-shell#10643]
```
fish, version 3.7.1
3.7.1
Darwin Glenns-MBP 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64
xterm-ghostty
```

Starting a fresh shell using recommended command: `  sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'`

Output without `fish_command_not_found.fish`, `foo` and `foo/goo` do not exist as files or directories:
```
glenn@Glenns-MBP /U/glenn> foo
fish: Unknown command: foo
glenn@Glenns-MBP /U/glenn [127]> foo/goo
fish: Unknown command: foo/goo
glenn@Glenns-MBP /U/glenn [127]>
```
Above output is as expected.

Create a `fish_command_not_found.fish` in the tempdir .config/fish/function with:
```
function fish_command_not_found
    echo "My unknown command:" $argv[1]
end
```

Output from `fish_command_not_found.fish`, `foo` and `foo/goo` do not exist as files or directories; `Library` and `Library/WebKit` do exist and both are directories:
```
glenn@Glenns-MBP /u/glenn [127]> foo
My unknown command: foo
glenn@Glenns-MBP /u/glenn [127]> foo/goo
My unknown command: foo/goo
glenn@Glenns-MBP /u/glenn [127]> Library
My unknown command: Library
glenn@Glenns-MBP /u/glenn [127]> Library/WebKit
fish: Unknown command. 'Library/WebKit' exists but is not an executable file.
glenn@Glenns-MBP /u/glenn [126]>
```

The issue is my command not found function is not called for the last case, `Library/WebKit`.

**Comment by faho** [comment]
This is on purpose.

fish found a valid path at the correct place, but there is something wrong with it.

So we assume there's a mistake somewhere (not executable, some component in the path is invalid, ...) and report that because it might be something you need to fix.

After that, running command-not-found isn't really applicable because we *have* found something.

And this isn't something we want to leave up to the command-not-found handler either, because those are frequently pretty simple and really *just* check the package repo.
