### ISSUE TITLE
Terminals and keyboard protocols survey

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#10663]
Here's some things I noticed as of bd5f9babd7cc57ea5467772073bcab39ee40db59 when running a variety of terminals and checking fish_key_reader and trying to bind keys.

Where I give a sequence I got it by running `od -t x1z` with manually enabling our protocols.

I'm not saying all of these "have" to be fixed for the next release, but we should take a look and see what we can do.

xterm (393):
- fish_key_reader says `alt-\[` for some keys and they cannot be bound. This includes shift-enter (sends `\e[27;2;13~`) and ctrl-tab (sends `\e[27;5;9~`)

wezterm (20240203-110809-5046fc22):
- `'` is identified as `shift-'`. This is caused by my QWERTZ keyboard where that *is* the key combination I press.
  This makes it impossible to enter single quotes AFAICT.
  This is clearly an upstream bug, but upstream has so many bugs open related to keyboard input that I'm not sure where to add it.
  Maybe a workaround would be necessary? Binding `shift-'` to inserting a single-quote would probably be least invasive. Ignoring the shift on single-quote would be another possibility.

putty:
- ctrl-left / shift-left and alt-shift are misinterpreted by fish_key_reader, but binding appears to work. They send `\eOD` (ctrl or shift), `\e\e[D` (alt).

Konsole and Gnome Console (the new vte-based thing they have):
- shift-enter sends `\eOM` but is recognized as enter (which sends `\r`). These otherwise support basically no protocols so it's old-school input. I'm not sure if that's an otherwise common sequence for enter?

Tmux and screen support nothing, it's old-school all the way.

I have also looked at alacritty, which sends a kitty sequence for ctrl-c/ctrl-d, but weirdly not for shift-enter which sends \r. That's their bug and nothing we can or should do anything about. Except it is another reason that we shouldn't enable the full disambiguation for all keys, because otherwise it's really easy to get stuck. I had a hard time getting out of `od`, and if fish crashed and you landed in bash you'd have a hard time getting out of bash. The more basic mode we currently use is much nicer in case of crashes etc.

**Comment by krobelus** [comment]
> Where I give a sequence I got it by running `od -t x1z` with manually enabling our protocols.

I guess we should add `fish_key_reader --verbose` for that, but it's not pressing enough because end users should never need it, and developers can cope with it in one way or another.

> xterm (393):
- fish_key_reader says `alt-\[` for some keys and they cannot be bound. This includes shift-enter (sends `\e[27;2;13~`) and ctrl-tab (sends `\e[27;5;9~`)

Actually we do have a legacy_bind for xterm's flavor of shift-enter:

	$legacy_bind --preset $argv \e\[27\;2\;13~ "commandline -i \n" expand-abbr # Sent with XTerm.vt100.formatOtherKeys: 0

but yeah, fish_key_reader behavior is super weird here; `fish_key_reader -c` only sees the first `alt-[`

If this encoding doesn't add conflicts we can support it easily.
The main reason I didn't add it yet is simply that I copied this from Kakoune which also fails to decode this as of today.

> wezterm (20240203-110809-5046fc22):
> This makes it impossible to enter single quotes AFAICT.
> This is clearly an upstream bug, but upstream has so many bugs open related to keyboard input that I'm not sure where to add it.
> Maybe a workaround would be necessary? Binding `shift-'` to inserting a single-quote would probably be least invasive. Ignoring the shift on single-quote would be another possibility.

Yeah that's bad, a workaround seems fine.
I'd completely disable the new keyboard protocols on wezterm until they fix it.
That way we can avoid a regression.
Binding individual keys like `shift-'` is whack-a-mole

> - ctrl-left / shift-left and alt-shift are misinterpreted by fish_key_reader,

ctrl-left and shift-left are parsed as `left` here. Maybe you saw this when using putty on Windows?

I also see that alt-shift sends `\e\e[D` where the fish_key_reader output will be confusing

```
bind alt-escape 'do something'
bind \[ 'do something'
bind A 'do something'
```

I have previously looked into additionally decoding `\e\e[A` as `alt-up` (that is, allow `\e` as prefix for arbitrary escape sequences; `\e[A` is up).
It is certainly possible (though I remember there was some minor ambiguity). 
The other ambiguity (`\e\e` could be `alt-escape`) can not be resolved in a general way, which is why I think this encoding should not be used.
Hence I didn't want to bake it into the Rust code, and keep basic compatibility with our legacy binds for `\e\e\[A` etc.
Given the fish_key_reader behavior here is actually a regression, I think it's fine to add this recursive parsing.

> Konsole and Gnome Console (the new vte-based thing they have):
> I'm not sure if that's an otherwise common sequence for enter?

Yeah `\eOM` (aka `SS3 M`) is specified as enter in
https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-PC-Style-Function-Keys
in

```
      Key              Numeric    Application   Terminfo   Termcap
      ---------------+----------+-------------+----------+----------
      Space          | SP       | SS3 SP      | -        | -
      Tab            | TAB      | SS3 I       | -        | -
      Enter          | CR       | SS3 M       | kent     | @8
```

They don't disambiguate shift-enter which is very unfortunate for us.

> Tmux and screen support nothing, it's old-school all the way.

I think tmux requires [special configuration](https://github.com/tmux/tmux/wiki/Modifier-Keys).
I remember struggling to get that to work. Probably I got it to work in the end but since tmux tends to be very conservative, should be similar to xterm.

**Comment by faho** [comment]
> I guess we should add fish_key_reader --verbose for that, but it's not pressing enough because end users should never need it, and developers can cope with it in one way or another.

My concern is that we might need it for debugging - user runs an uncommon terminal that we might not even have access to, and we need to know the actual sequence.

> I'd completely disable the new keyboard protocols on wezterm until they fix it.

Fine by me. I get TERM_PROGRAM_VERSION=20240203-110809-5046fc22 and TERM_PROGRAM=WezTerm.

> ctrl-left and shift-left are parsed as left here. Maybe you saw this when using putty on Windows?

Yup, putty on windows (but connecting to a linux host).

> Yeah \eOM (aka SS3 M) is specified as enter in

I have so far not found a single terminal that sends SS3 M when I press enter.

VTE/Konsole send it for shift-enter, and for just enter they send a carriage return (`\r`).

> Tmux and screen support nothing, it's old-school all the way.

> I think tmux requires [special configuration](https://github.com/tmux/tmux/wiki/Modifier-Keys).

I can't get it to work either. To be honest I mostly care about the defaults. From that perspective tmux just seems to be business as usual.

------

I have now also checked foot (kitty protocol, seems fine) and rio (old-school, seems fine), as well as zellij (multiplexer, old-school bindings, seems fine).

**Comment by krobelus** [comment]
Ok I added two changes to decode `\e\e[A` and `\e\[27\;2\;13~`, making `fish_key_reader` output nicer.
Note that crossterm and others support none of these, looks like they haven't gotten bug reports,
probably because these are all edge cases, keys that are rarely used inside a terminal.

> ctrl-left / shift-left and alt-shift are misinterpreted by fish_key_reader, but binding appears to work. They send \eOD (ctrl or shift)

Hmm `\eOD` is `left` so that's correct from our side.  What did those keys send on fish 3.7.1?
I can unearth my Windows machine later if necessary.

> Fine by me. I get TERM_PROGRAM_VERSION=20240203-110809-5046fc22 and TERM_PROGRAM=WezTerm.

The sad bit here is that CSI u legitimately improves WezTerm experience but only for English keyboards.
My concern is that things might break later in more subtle and less frequent ways (SSH in WezTerm means the workaround no longer applies),
and overall it might be better to fail hard, prompting the user to fix it for real instead of putting up with bugs.
WezTerm with a non-English keyboard is really broken, it even fails to reset progressive enhancement flags, so keyboard input in `cat` will spew CSI u sequences.
But I have no strong opinion, I'm fine with disabling it for WezTerm by default.
At this point we should probably add a runtime option to disable keyboard input protocols (bracketed paste can stay though).

**Comment by krobelus** [comment]
> Yeah \eOM (aka SS3 M) is specified as enter in
> 
> I have so far not found a single terminal that sends SS3 M when I press enter.

I just figured out `\eOM` is sent for the numpad version of Enter (by gnome-terminal).
That's the "application keypad mode" - a way to disambiguate numpad keys.
Not really relevant for us I guess.

**Comment by faho** [comment]
> Ok I added two changes to decode \e\e[A and \e\[27\;2\;13~, making fish_key_reader output nicer.

Cool, works.

> Hmm \eOD is left so that's correct from our side. What did those keys send on fish 3.7.1?
I can unearth my Windows machine later if necessary.

I'll check next time I'm at a windows machine, but I suspect these did not change.

> But I have no strong opinion, I'm fine with disabling it for WezTerm by default.

Yeah, I would rather input stay limited like before than have some people unable to enter single-quote.

> At this point we should probably add a runtime option to disable keyboard input protocols (bracketed paste can stay though).

Sounds fine. I don't want this to be *expected* for people to unbreak their experience, but it is possible we did not catch everything.

> I just figured out \eOM is sent for the numpad version of Enter (by gnome-terminal).

gnome-*terminal*, the old version on vte3, sends \eOM for numpad-enter (and \eO2M for shift-numpad-enter and \eO3M for alt-numpad-enter and \eO5M for ctrl-numpad-enter). Regular enter sends \r with most modifiers except alt, that's \e\r.

I think I've misidentified gnome-*console*, the "new" vte4 one. It appears to send \r for basically everything involving enter, except for alt-enter (but not the numpad one), where it sends \e\r.

*Konsole* sends \r for enter and numpad-enter and \eOM for shift-enter (but not the numpad one).

Yes, these sequences are all terrible. Honestly I don't think we can really do anything here, which is unfortunate for me because I use konsole and never use the notepad.

**Comment by krobelus** [comment]
yikes. I'm sure these terminals will implement disambiguation eventually.

**Comment by faho** [comment]
Okay, the xterm and wezterm thing are now fixed, the konsole thing we can't do anything about.

I would still like to see more terminals tested.

If you would like to help, install fish from git master, run it in whatever terminal emulator you have and see if bindings work. In particular run `fish_key_reader -cV` and see if it reports anything sensible, especially for modified keys.

In old-school terminals you will have the usual limitations, e.g. ctrl-i and ctrl-shift-i will both report "tab". This can't be fixed on our end, but it helps to catalog.

**Comment by krobelus** [comment]
People have been using these protocols for many years but apparently no one reported the problems you found

**Comment by faho** [comment]
> Hmm \eOD is left so that's correct from our side. What did those keys send on fish 3.7.1?

On putty: left sends the regular \e\[D, ctrl-lefts sends \eOD, without any fish involved at all. alt-left sends \e\e\[D.

This is controlled by a setting, "Shift/Ctrl/Alt with the arrow keys" which defaults to "Ctrl toggles app mode" and can be set to "xterm-style bitmap". The latter gives usable keys.

Nothing we can or should support.

**Comment by faho** [comment]
[cool-retro-term](https://github.com/Swordfish90/cool-retro-term) prints CSI u onto the screen. You get "0u5u" after every program.

It appears to be undetectable via environment variables (TERM=xterm, nothing else springs to mind), and it is unmaintained and more of a joke than something you would use in anger.

I would be fine with just not supporting it.

**Comment by zanchey** [comment]
> [cool-retro-term](https://github.com/Swordfish90/cool-retro-term) prints CSI u onto the screen. You get "0u5u" after every program.

It's not had any commits in two years, so I think that's fine.

**Comment by krobelus** [comment]
I wonder if we should support urxvt arrow keys.
`ctrl-up` send `\eOa` which we currently don't decode.
It's a regression - `ctrl-up` is no longer mappable because it's an invalid SS3 sequence to us

**Comment by krobelus** [comment]
> People have been using these protocols for many years but apparently no one reported the problems you found

Spoke too soon, someone else hit the alacritty numlock problems in https://github.com/mawww/kakoune/issues/5214
I sent our improvements [upstream](https://lists.sr.ht/~mawww/kakoune/patches/54517) except the ones I'm not sure they're worth it

**Comment by faho** [comment]
It turns out rio needs to have support enabled, and if you do pressing ctrl-i gives `\e\[105\;5u`, which is correctly seen as ctrl-i.

But ctrl-shift-i yields `\e\[73:105\;6u`, which fish *also* interprets as ctrl-i. Same with apparently all modifier+shift.

Here's me alternating ctrl- and ctrl-shift from q to r:

```
# decoded from: \e\[113\;5u
bind ctrl-q 'do something'
# decoded from: \e\[81:113\;6u
bind ctrl-q 'do something'
# decoded from: \e\[119\;5u
bind ctrl-w 'do something'
# decoded from: \e\[101\;5u
bind ctrl-e 'do something'
# decoded from: \e\[69:101\;6u
bind ctrl-e 'do something'
# decoded from: \e\[114\;5u
bind ctrl-r 'do something'
# decoded from: \e\[82:114\;6u
bind ctrl-r 'do something'
```

I assume it's the order? Kitty seems to send 105:73 for ctrl-shift-i, this does 73:105.

**Comment by krobelus** [comment]
yeah rio violates the [protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#functional-key-definitions) here, which says

> If the user presses, for example, ctrl+shift+a the escape code would be CSI 97;modifiers u. It must not be CSI 65; modifiers u.

And yeah, it's odd that users need to configure rio to opt into this

**Comment by faho** [comment]
Okay, I'm going to call this finished for now.

In summary:

- fish_key_reader got updated for some xterm sequences
- fish_key_reader --verbose is back
- wezterm is worked around (no kitty protocol for now)
- the rio issue got fixed upstream
- loads of other terminals have been tested and work (but mostly just with the oldschool protocols)
- urxvt sends some key sequences we don't currently decode. if someone cares enough they can be added.

The three broken terminals we know are:

- emacs' ansi-term and cool-retro-term, which fail by printing parts of escape sequences unto the screen. they are generally *usable* otherwise (well, emacs' ansi-term was already pretty badly broken cosmetically)
- urxvt, which sends some quite unusual key sequences

To be honest these are all pretty unmaintained and not super widely used. For the first two it's a clear bug on their end, for urxvt I would be fine accepting a patch, but it's not super necessary.

**Comment by krobelus** [comment]
looks like kitty keyboard protocol is [opt-in in wezterm via configuration option](https://wezfurlong.org/wezterm/config/lua/config/enable_kitty_keyboard.html).
So I'd remove our workaround. It makes no sense that every single app has to work around wezterm; that makes things unnecessarily complicated and makes it quite hard to use CSI u with the one keyboard layout that works (English).
Also our workaround is brittle; it breaks as soon as you're inside something like SSH.
Better simplify this for future generations; it's easy enough for users to toggle `enable_kitty_keyboard`.
