### ISSUE TITLE
fish in emacs' ansi-term has prompt issues

### ISSUE THREAD

**Issue by ahyatt** [fish-shell/fish-shell#107]
Under emacs's ansi-term (probably the only way to get the real power of fish inside of emacs), the prompt looks like:

2;fish  /home/ahyatt2;fish  /home/ahyatt
ahyatt@ahyatt /home/ahyatt>

My term is eterm-color, which is standard for ansi-term.  Probably some of the default ansi control sequences in the prompt are not quite kosher.

**Comment by ali** [comment]
@akrito Thanks! This worked for me, too.

**Comment by SlightlyCyborg** [comment]
The fish title hack is not working for me.

**Comment by faho** [comment]
@SlightlyCyborg: If you don't use the fish title thing, do you get the folder displayed twice (and only once with it)? If you use it on another terminal, does it work?

iTerm has [special integration with shells](https://iterm2.com/documentation-shell-integration.html), and [the fish version](https://iterm2.com/misc/fish_startup.in) isn't conditional on the $TERM being iTerm, and it only blacklists screen. By default this file will be saved as `~/.iterm2_shell_integration.fish`, so you might want to see what happens when you remove that.

**Comment by SlightlyCyborg** [comment]
@faho I only checked it on iterm (turns out it is just macs standard Terminal) to find out why I was still getting  a strange line printed on emacs term every time I used cd

`7;file://Collins-MacBook-Air.local/Users/collinbell/dameon`

Yes, if I remove the fish_title from the config, then I will see the folder appear twice on the mac Terminal app. The same thing still happens in emacs term.

**Comment by faho** [comment]
@SlightlyCyborg: Run this:

```fish
    if test "$VTE_VERSION" -ge 3405 -o "$TERM_PROGRAM" = "Apple_Terminal"
        echo "True"
    end
```

Does it print "true"? In that case, this is _our_ cwd reporting for VTE or Apple Terminal. Since you are running emacs in a terminal that can handle this, we're printing it, but emacs then mangles it so the term no longer gets the full sequence (yet another limitation of ansi-term).

**Comment by floam** [comment]
We might need [to do what Apple does](https://gist.github.com/floam/f535842a16226e77d014d67bade2b2f3) for Emacs:

```
# Working Directory
#
# Tell the terminal about the current working directory at each prompt.

if [ -z "$INSIDE_EMACS" ]; then
    update_terminal_cwd() {
    # Identify the directory using a "file:" scheme URL, including
    # the host name to disambiguate local vs. remote paths.

    # Percent-encode the pathname.
    local url_path=''
    {
        # Use LC_CTYPE=C to process text byte-by-byte. Ensure that
        # LC_ALL isn't set, so it doesn't interfere
```

**Comment by floam** [comment]
I'm going to add the $INSIDE_EMACS check for the CWD OSC and define and an empty fish_title if the user is using VTE/Terminal.app. The reasoning for the latter is that these modern terminals both compose a nicer title if we  don't try to provide a custom one (no path it title twice, "fish" in title twice) - and the user can configure which components they'd like in their terminal inside the terminal preferences.

**Comment by floam** [comment]
Before and after with the default settings (you can configure Terminal.app to show the full path, if you prefer):
<img width="513" alt="messy" src="https://cloud.githubusercontent.com/assets/291142/18655037/68209c48-7e9a-11e6-95dd-c4c5a2f15d44.png">

<img width="532" alt="cleaner" src="https://cloud.githubusercontent.com/assets/291142/18655041/6c595d36-7e9a-11e6-8f57-9998febee97b.png">

**Comment by rdrey** [comment]
I got tripped up by the iTerm shell integration. Could we mention that in the readme in the fish section, too?

**Comment by faho** [comment]
@rdrey: IIRC, iTerm ships that, so you'll have to take it up with them.

**Comment by rdrey** [comment]
Sorry, I was in the completely wrong repo last night. I thought I was commenting on an issue in https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Btools/shell. 😅 

I've created a PR for iTerm2 instead. (https://github.com/gnachman/iterm2-website/pull/35)
