### ISSUE TITLE
Please replace en_US.UTF-8 in __fish_set_locale.fish with C.UTF-8

### ISSUE THREAD

**Issue by DaanDeMeyer** [fish-shell/fish-shell#10736]
__fish_set_locale.fish has a final fallback to `en_US.UTF-8` for `LC_CTYPE`. This should ideally be replaced with `C.UTF-8` which these days has a bigger chance of being builtin into glibc compared to `en_US.UTF-8`. On mac systems this should probably be `UTF-8` as `C.UTF-8` isn't available there for use in `LC_CTYPE` but `UTF-8` is.

**Comment by faho** [comment]
This is a fallback's fallback. If it is used at all, your system is already misconfigured.

C.UTF-8 is still pretty new, I believe it doesn't exist on e.g. RHEL.

Since we can't detect the available locales in a portable way we pick one, after everything else has failed.

I think that that one is still the better choice for now.

**Comment by DaanDeMeyer** [comment]
@faho It is present in CentOS Stream 9, CentOS 7 and CentOS Stream 8 are both EOL. Whatever older RHEL is still being maintained on business support will not get a newer version of fish anymore.

Ubuntu Focal (20.04) does not have it but will be EOL in April next year. Ubuntu Jammy has glibc 2.35 which has C.UTF-8.

Any other distributions you'd like to know about?

**Comment by DaanDeMeyer** [comment]
@faho Also, according to https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html#Locale-Environment-Variables, `$LANG` is the fallback for `$LC_CTYPE` if it is not set, so there should be no need to set `$LC_CTYPE` at all?

**Comment by faho** [comment]
This fallback only runs if *no* locale variable at all has been set, and we cannot read e.g. /etc/locale.conf.

I am being literal when I say it is a fallback's fallback.

That is also why we only set the encoding, because that is the one that breaks shit. If the messages are in "C" language (which is probably english everywhere) that's fine and we do not care.

If you ever hit this your system is misconfigured and you should fix it.

**Comment by DaanDeMeyer** [comment]
@faho Sorry my bad, the `en_US.UTF-8` isn't even coming from fish, it's already set in the user manager environment before fish is even started. My search continues, thanks for the quick replies
