### ISSUE TITLE
Process expansion doesn't work like other expansions

### ISSUE THREAD

**Issue by dag** [fish-shell/fish-shell#1074]
For example,

``` console
$ ls /proc/%firefox
ls: cannot access /proc/%firefox: No such file or directory
```

Instead I have to do

``` console
$ ls /proc/(echo %firefox)
```

Which works, but of course doesn't do the right thing if there's more than one matching PID, so really I have to do

``` console
$ ls /proc/(for pid in %firefox; echo $pid; end)
```

I think it would be more useful and less surprising if that's what my first example did itself.

**Comment by zanchey** [comment]
I just ran into this today!

**Comment by krader1961** [comment]
> ... `%` is only expanded on beginning of the line.

I think you meant "expanded when the first character of a token" but your point still stands.

If we change this behavior it could only be done so in a major release. Furthermore, there are implications for the expansion. Presumably it follow the cartesian-product rule?

Personally, I think the process expansion syntax needs significant augmentation to the documentation and implementation. Consider this statement from the documentation:

> fg %ema will search for a process whose command line begins with the letters 'ema', such as emacs, and if found, put it in the foreground.

What happens if `ema` matches more than one command? Are multiple PIDs passed to the `fg` command?

**Comment by krader1961** [comment]
Note that for fish 3.0 we are strongly considering removing this feature. So if you have an opinion please comment on issue #4230.

**Comment by mqudsi** [comment]
Process expansion has been removed. It relied on dark magic and didn't really work.

**Comment by cben** [comment]
Also the standard `{$var}` workaround doesn't work for % expansion:
```
$ ls -l /proc/%self/exe
ls: cannot access '/proc/%self/exe': No such file or directory
$ ls -l /proc/{%self}/exe
ls: cannot access '/proc/%self/exe': No such file or directory
$ ls -l /proc/(echo %self)/exe
lrwxrwxrwx. 1 bpaskinc bpaskinc 0 Oct  8 14:56 /proc/11282/exe -> /usr/bin/fish*
```
