### ISSUE TITLE
Prompt jumps around when resizing terminal after a command that doesn't print a trailing newline

### ISSUE THREAD

**Issue by jfly** [fish-shell/fish-shell#10751]
- I'm using fish 3.7.1
- I'm using alacritty 0.13.2, but I've tried a handful of other terminal emulators (VTE derived, wezterm, and kitty)
- I'm on NixOS

With a stock fish configuration, after I run a command that does not print a trailing newline, I see that my prompt jumps around when I resize the terminal. I wasn't able to capture this in a asciinema.org, so here's a gif:

![2024-09-27_22-20-15_pattern](https://github.com/user-attachments/assets/458d3af0-6a47-4a5a-bcdd-a06f6d624612)

Notably, things behave much better if my prompt has a newline character right above it. The newline character disappears, but then things stabilize:

![2024-09-27_22-26-45_pattern](https://github.com/user-attachments/assets/df7a66c6-c886-4a3a-8a68-2eeaf32cce6c)

I've read through <https://www.vidarholen.net/contents/blog/?p=878>, and I think I understand the "trick" that fish uses to make this work. I can't imagine how it could possibly work when I resize my terminal emulator. That said, my buddy @lgarron said this works on his machine, so maybe I'm not fully understanding things.

I've also read through https://github.com/fish-shell/fish-shell/issues/7491 and https://github.com/fish-shell/fish-shell/pull/7623. If I `set fish_handle_reflow 1`, my prompt stays put, but I get even weirder behavior:

![2024-09-27_22-34-19_pattern](https://github.com/user-attachments/assets/b0bfdf1e-48fa-4c21-82ae-c433242165f4)

**Comment by lgarron** [comment]
> That said, my buddy @lgarron said this works on his machine, so maybe I'm not fully understanding things.

Well, this is interesting! I just did some more thorough testing on my computer (macOS) and:

- The indentation issue does not appear in iTerm or VS Code's terminal. However, if I shrink the terminal width then the previous line overflows into multiple blank lines.
- It *does* appear in the built-in macOS `Terminal.app`.

## VS Code

https://github.com/user-attachments/assets/0d6f77e6-4eed-47c5-b82c-815117fc2c9e

## iTerm

https://github.com/user-attachments/assets/1dccbca2-5ae9-4dd9-b55f-cbfec0ec28f7

## `Terminal.app`

https://github.com/user-attachments/assets/b2b6dad8-eb30-41de-8fb3-6cea32296a39

The VS Code / iTerm behaviour makes sense if `fish` is padding out the `⏎` character with trailing whitespace padding that is determined by the size of the terminal at the initial time of printing. I don't see why this couldn't be a newline instead, but there's probably a good historical reason?

I guess I've also probably seen the VS Code / iTerm behaviour hundreds of times, but it hasn't bothered me so much because an extra newline is a super mild visual bug compared to the kinds of issues shells can have. It would be nice to have a definitive fix that also works in other terminals, though.

**Comment by jfly** [comment]
> I don't see why this couldn't be a newline instead, but there's probably a good historical reason?

I think I know the answer to this! It's because the shell *doesn't actually know what the last character printed was*! From https://www.vidarholen.net/contents/blog/?p=878:

> Contrary to popular belief, the shell does not sit between programs and the terminal. The shell has no ability to intercept or examine the terminal output of programs.

Fish could always print a newline character, but then you'd always get a newline character (even when the program you ran printed a newline). I guess that's basically what I've done in my example by adding a newline to my prompt.

**Comment by jfly** [comment]
Thanks, @faho, it's good to have confirmation that this is unfortunately expected.
