### ISSUE TITLE
Panic: "user-provided comparison function does not correctly implement a total order"

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#10763]
Using https://github.com/fish-shell/fish-shell/commit/cd9e50c2cc64ea1fdefce9c803a89f37513ca2f1 and iTerm v3.5.5

---

Triggered by typing `$ scp <TAB>`

Running fish with `RUST_BACKTRACE=full`...

```
thread 'main' panicked at library/core/src/slice/sort/shared/smallsort.rs:862:5:
user-provided comparison function does not correctly implement a total order
stack backtrace:
   0:        0x102c7b4f4 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h14dcb4794e811c9f
   1:        0x102a8230c - core::fmt::write::h49a9cf68bfb4a321
   2:        0x102c7f45c - std::io::Write::write_fmt::h00e4f1b82d71ad85
   3:        0x102c6c0fc - std::panicking::default_hook::{{closure}}::hda52b8046522f561
   4:        0x102c6bcc4 - std::panicking::default_hook::h9566cb73367aef3e
   5:        0x102c49cc8 - fish::panic::panic_handler::{{closure}}::hc7afb970486c9538
   6:        0x102c6d6bc - std::panicking::rust_panic_with_hook::hfa41181adbcf532d
   7:        0x102c7df8c - std::panicking::begin_panic_handler::{{closure}}::ha417e66bf9de7acf
   8:        0x102c7df28 - std::sys::backtrace::__rust_end_short_backtrace::hc7b890f013fa9efb
   9:        0x102c6c51c - _rust_begin_unwind
  10:        0x102c85fd0 - core::panicking::panic_fmt::h29609029db4d41f4
  11:        0x102a89a84 - core::slice::sort::shared::smallsort::panic_on_ord_violation::h937e7dfddafee0e6
  12:        0x102ac4b04 - core::slice::sort::stable::quicksort::quicksort::hf96d425fb5fa6309
  13:        0x102ac3c80 - core::slice::sort::stable::drift::sort::hea5f8585f8f87de5
  14:        0x102c06434 - core::slice::sort::stable::driftsort_main::h7e0b5d3d0550d5d2
  15:        0x102b33df0 - fish::complete::sort_and_prioritize::h56b32710b0d80777
  16:        0x102c14a44 - fish::builtins::complete::complete::hf9e015076e99c073
  17:        0x102bf2ec0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1446bd85426f73ab
  18:        0x102be94d0 - fish::exec::exec_process_in_job::hc274c121eafaabfc
  19:        0x102be6680 - fish::exec::exec_job::haf53b5c55d659ef4
  20:        0x102c32e80 - fish::parse_execution::ExecutionContext::run_1_job::hafa811ca7d1b6094
  21:        0x102c31fb8 - fish::parse_execution::ExecutionContext::run_job_conjunction::h8989ff92d83ea214
  22:        0x102c31e98 - fish::parse_execution::ExecutionContext::run_job_list::h6a8e8e466fbaecd1
  23:        0x102c2e408 - fish::parse_execution::ExecutionContext::eval_node::hdb89f7103ba703d8
  24:        0x102b1b7cc - fish::parser::Parser::eval_node::h27147076a7283585
  25:        0x102b1a8b8 - fish::parser::Parser::eval_with::h5b3bffeaa81082ba
  26:        0x102bf5084 - fish::exec::exec_subshell_internal::h117e48e66c790efb
  27:        0x102b4de44 - fish::expand::expand_cmdsubst::haa4f3b172213739d
  28:        0x102b4862c - fish::expand::Expander::stage_cmdsubst::hc3fc426aad702ce9
  29:        0x102b47e20 - fish::expand::expand_to_receiver::h136883fe0e1035eb
  30:        0x102b47c00 - fish::expand::expand_string::h52e62a5df38d889d
  31:        0x102b3fcc8 - fish::complete::Completer::complete_from_args::h65fb6d10d913b6d2
  32:        0x102b3d8f0 - fish::complete::Completer::complete_custom::hf0ad31f88904c71f
  33:        0x102b3a0b0 - fish::complete::Completer::walk_wrap_chain::h2ef462fa69dbbd68
  34:        0x102b37980 - fish::complete::Completer::perform_for_commandline::h5218012f5b27d877
  35:        0x102b35d2c - fish::complete::complete::h51574e4567d56757
  36:        0x102b8ac4c - fish::reader::Reader::compute_and_apply_completions::h06ac70792b8f14e6
  37:        0x102b80224 - fish::reader::Reader::handle_char_event::h76ceb0cf9cdc02a3
  38:        0x102b7db44 - fish::reader::Reader::readline::h8d1852a5b6f1bc83
  39:        0x102b7b090 - fish::reader::reader_read::hb443380d135dbb16
  40:        0x102a7dcc4 - fish::throwing_main::h3d05b10616182ae8
  41:        0x102c49aa8 - fish::panic::panic_handler::hf7f50c2fcb7e5af0
  42:        0x102a799bc - fish::main::h0f7e66833727bf99
  43:        0x102c48dbc - std::sys::backtrace::__rust_begin_short_backtrace::h2fe7d47eaece26be
  44:        0x102a80e70 - _main
fish crashed, please report a bug. Debug PID 13662 or press Enter to exit
```

**Comment by faho** [comment]
This is a change in rust 1.81 - it panics if it notices a comparison function doesn't lead to a total ordering.

And indeed, ours doesn't:

https://github.com/fish-shell/fish-shell/blob/cd9e50c2cc64ea1fdefce9c803a89f37513ca2f1/src/complete.rs#L477-L484

The issue is that, if one completion has "DONT_SORT" and the other hasn't, we compare them normally.

So if you have completions "a", "b" and "c" and "a" and "c" have --keep-order, you get this:

- a == c (because DONT_SORT)
- a < b (because b doesn't have DONT_SORT)
- c > b

`a == c > b < a`

The solution is *probably* to sort the DONT_SORT completion as either less or greater.

As a sidenote I think this improvement isn't great - introducing a runtime panic dependent on compiler version is not what I would like rust to do, especially since it also depends on the data. I have not been able to trigger this, because AFAICT you actually need to have paradoxical comparisons happen for it to crash.

**Comment by faho** [comment]
Another candidate for this: https://github.com/fish-shell/fish-shell/blob/cd9e50c2cc64ea1fdefce9c803a89f37513ca2f1/src/builtins/path.rs#L723

I don't quite recall why that was added, but if it's a stable sort already that doesn't seem necessary?

**Comment by krobelus** [comment]
Looks like a regression in Rust; there's a comment saying

```
    // The Ord documentation requires users to implement a total order. Arguably that's
    // unnecessarily strict in the context of sorting. Issues only arise if the weaker requirement
    // of a strict weak ordering is violated.
```

They should lift the requirement to `StrictWeakOrd`.

Regardless, we want to work around this, either by implementing sort ourselves, or using a total order.

This would only break tests like 06d9708d4 (Add `complete -k` group order test, 2022-10-26)
which assert that we keep the relative order of `--keep-order` and `--no-keep-order` completions:

```fish
complete : -f -a 'aaa'
complete : -f -a 'bbb' --keep-order
complete -C": "
# CHECK: aaa
# CHECK: bbb
```

I don't think this behavior is super important because I don't expect there is a real world use case for mixing
`--keep-order` and `--no-keep-order` completions.
So I'd be fine with just sorting all  `--keep-order` completions first (or last), to make it a total order.
But there should also be a good option for sorting as before (maybe a 3rd party dependency), I just haven't found it.

**Comment by krobelus** [comment]
> I don't quite recall why that was added, but if it's a stable sort already that doesn't seem necessary?

Yes that seems completely redundant

**Comment by faho** [comment]
> Regardless, we want to work around this, either by implementing sort ourselves, or using a total order.

Note: A *total* order would be tricky here, because that would mean we could not use that Ordering::Equal either - so we would have to thread through the ordering we want.

I think we can get by with a strict weak ordering (it's what the comment says) by just sorting all DONT_SORT elements before or after all sorted ones.

This is okay because the current ordering makes no sense to begin with. From https://github.com/fish-shell/fish-shell/blob/38300a818e44585e7bacea579aab75a49985b83f/tests/checks/complete-group-order.fish,

we have four groups, "alpha delta bravo" sorted, "golf charlie echo" keep-order, "india foxtrot hotel" keep-order and "kilo juliett lima" sorted.

And the ordering we get is https://github.com/fish-shell/fish-shell/blob/38300a818e44585e7bacea579aab75a49985b83f/tests/checks/complete-group-order.fish#L21-L32.

alpha and bravo are first, which is fine. But why is "delta" *after* some keep-ordered elements? It's not even after a full group, it's after "india foxtrot hotel" *and* "golf charlie" (but not "echo")?

-----------

All of that notwithstanding, I am pretty disappointed by this runtime panic being introduced and do think it makes rust in practice less stable (in terms of backwards-compatibility) than it is sold to be. If it were a compile-time check or at least only enabled in debug builds I would be much happier with it.

**Comment by faho** [comment]
Okay I have been unable to trigger this, even after building with rust 1.81 and trying a bunch of completes with and without --keep-order.

@zx8 Can you try https://github.com/faho/fish-shell/commit/334b0151caf53fe4d27b277f48ce138b322a6f52 to see if that fixes it for you?

I would prefer that approach to vendoring the old sort function, because this is the intended behavior on the rust side apparently so we would be keeping that potentially forever. Since the current order is useless anyway, let's just change it.

**Comment by krobelus** [comment]
without a total order, there are multiple valid orderings which is a source of confusion.
The patch looks good to me, it's a good idea to get rid of this overly complex behavior
