### ISSUE TITLE
Fish silently accepts broken source commands and silently breaks non related software.

### ISSUE THREAD

**Issue by onnimonni** [fish-shell/fish-shell#10774]
Hey,

I found one of the weirdest bugs recently where totally non fish related program (nix copy) hangs indefinetely when I had a broken config in my `~/.config/fish/config.fish`.

You can reproduce this by adding broken `source` command into your config:
```fish
$ echo -e '\nsource $NON_EXISTING_VARIABLE/non-existing-config.fish' >> ~/.config/fish/config.fish
$ fish
```

I had been accidentally refactoring my fish config and didn't notice this issue for years. I only learned about this after I started using nix.

This was rather frustrating to [debug and find](https://github.com/NixOS/nix/issues/11582#issuecomment-2404856022).

Is there a way where I could automatically throw an error or at least output something to stderr when the target file of the source command fails?

## Software versions and config
```bash
$ fish --version
fish, version 3.7.1
$ echo $version
3.7.1
$ uname -a
Darwin $MY_MACHINE.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000 arm64
$ echo $TERM
xterm-256color
```

**Comment by faho** [comment]
What happens here is that nonexistent variables [eliminate the entire token](https://fishshell.com/docs/current/language.html#combining-lists-cartesian-product). This happens because all variables are lists, and attaching something to a list attaches it to every element.

E.g. `$PATH/fish` expands to "/usr/bin/fish" and "/bin/fish" and "/usr/local/bin/fish".

When the variable has 0 elements, it simply attaches the string "/fish" to nothing.

`source` will then return a false status without printing anything. This is an improvement over the previous behavior (#2633, changed in fish 3.0), where it would read from stdin, which would make config.fish appear to hang.

We can probably make it fail loudly, print an error, in this case instead.

**Comment by faho** [comment]
To be clear: A bare `source` in config.fish will *not* make fish's startup hang by default since fish 3.0.

So if you are experiencing that, something else is happening.

One possibility we should check is that something is piping to fish (e.g. `foo | fish`), and the `source` then reads that because it's not a tty.

That would not be fixed by making it error, that would only be fixed by e.g. `source` figuring out that it's not directly redirected. Which we could do, but it would be a compatibility break.

**Comment by onnimonni** [comment]
Thanks for the input 💪

> To be clear: A bare source in config.fish will not make fish's startup hang by default since fish 3.0.
> So if you are experiencing that, something else is happening.

The startup will not hang. It starts well and almost all software I have been using for multiple years have worked flawlessly.

> We can probably make it fail loudly, print an error, in this case instead.
I think just printing an error would already be a huge time saver 🙌

**Comment by onnimonni** [comment]
I think I'm just missing an option like `set -u` which treat unset variables as an error and exit immediately in bash and zsh.

Is there something like this in fish?

**Comment by faho** [comment]
#4163
