### ISSUE TITLE
Default fish colors unreadable in tty

### ISSUE THREAD

**Issue by stargazer1984** [fish-shell/fish-shell#10786]
fish, version 3.7.1

While fish is famous for its sane defaults, using it on the tty will result in partly unreadable terminal due to its default colors in that environment:

![tty](https://github.com/user-attachments/assets/ad915360-1715-4736-998e-6871408ef22f)

While the colors available on the tty are very limited, I would argue it is better to change the default color for the typed command to a more readable alternative (or use white). Currently it is very painful to work with that color and for visually impaired user it may be even impossible to use it like this.

**Comment by faho** [comment]
Fixed by #10758

**Comment by faho** [comment]
> While fish is famous for its sane defaults, using it on the tty will result in partly unreadable terminal due to its default colors in that environment:

To be clear: The actual issue here is that your terminal's palette is terrible.

Fish's default colorscheme restricts itself to the 16 color palette, and tries to work in both light and dark terminals, and with palettes as bad as that one it's an almost impossible task.

We've removed "blue" from the colors we use, which should improve things, but the underlying issue is a palette that has bad contrast.

**Comment by stargazer1984** [comment]
> > While fish is famous for its sane defaults, using it on the tty will result in partly unreadable terminal due to its default colors in that environment:
> 
> To be clear: The actual issue here is that your terminal's palette is terrible.
> 

I tested this on debian and arch and it seems to be the default on all ttys, hence the request for change.

Sorry for not testing the master branch though, and thanks for the fix :)
