### ISSUE TITLE
Rust build: Strange '=' character appears every new line under JetBrains integrated IDE

### ISSUE THREAD

**Issue by miranquil** [fish-shell/fish-shell#10829]
![CleanShot 2024-11-04 at 18 58 09@2x](https://github.com/user-attachments/assets/ad08bbdf-b5ac-43cf-b60a-2c71e9ffc99c)

* fish version: `0.1.0-g8aed929`
* OS: macOS 15.01(24A348) `Darwin Miranquil-MacBook Pro 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000 arm64`
* TERM: `xterm-256color`
* IDE: PyCharm Community 2024.2.4 & 2024.2.3

This `=` appears every new line in JetBrains integrated terminal with effects of cursur when pressing tab on inline hints appears, just like the image. The second `n` However it won't appear under other editors like VSCode, Zed, etc.

Though it seems like an issue caused by JetBrains, but this only happens on Rust version Fish. When switching to normal release version(installed by homebrew, `version 3.7.1`), fish works normally.

I've tried two solutions but none of them worked:

* remove all contents under `~/.config/fish`
* remove all contents under `~/Applications/PyCharm\ Community\ Edition.app/Contents/plugins/terminal/shell-integrations/fish/` or Goland's integration files.

This command did worked well: `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= XDG_DATA_DIRS= fish'`

**Comment by faho** [comment]
This is a jetbrains bug. It mishandles either of these two escape sequences:

https://github.com/fish-shell/fish-shell/blob/8aed929f5e34a8567edda56c4a7d27b3a70b4f87/src/input_common.rs#L484-L485

**Comment by faho** [comment]
Also of note:

> 0.1.0-g8aed929

You've miscompiled fish, most likely by doing `cargo install`. For master you'll have to keep using cmake, like https://github.com/fish-shell/fish-shell/blob/8aed929f5e34a8567edda56c4a7d27b3a70b4f87/README.rst?plain=1#L156-L159 says

**Comment by faho** [comment]
Yup:

```fish
echo \x1b"["=5u
```

prints a "=".

Like I said this needs to be fixed in Jetbrains, we can't work around it because there's no way to detect it.

**Comment by miranquil** [comment]
Thank you for replying! However, I've read the README and yeah I compiled by `cmake`.
Here's my build script:

```sh
rm -rf build
mkdir build
cd build
cmake ..
make
make install
```

I think it should do the right trick?

**Comment by faho** [comment]
If `fish --version` or `echo $version` says "0.1.0-g8aed929" something went wrong.

It should say "3.7.1-2470-g83fd521aa" (or something of that format).

>  Here's my build script (run by sudo):

There's your problem. `git` will now refuse to do anything in a repository owned by another user (as a pretty heavy-handed solution for a security issue).

You'll want to *only* run the `make install` with sudo.

Anyway, the version should be the only real casualty of this approach and this is unrelated to the issue here, which is a jetbrains bug.

**Comment by faho** [comment]
I linked it above: https://github.com/fish-shell/fish-shell/blob/8aed929f5e34a8567edda56c4a7d27b3a70b4f87/src/input_common.rs#L484-L485

There is no fix on our end.

This is the kitty keyboard protocol, which we enable on purpose, which works in almost every other terminal (if only by ignoring the sequence, which is fine).

We'll work around breakage where we can, but here we can't because jetbrains gives us no way to detect it.

**Comment by miranquil** [comment]
Thank you! I understand.

Still, I'm curious about that is this caused by some thing about Rust? For this issue did not happen under original version of Fish. Could you tell me when it pleases you?

**Comment by faho** [comment]
> Still, I'm curious about that is this caused by some thing about Rust? For this issue did not happen under original version of Fish. Could you tell me when it pleases you?

It is not caused by rust, it's that the new version gained support for the kitty keyboard protocol.

**Comment by miranquil** [comment]
Oh I see. Thank you very much for your time.

**Comment by faho** [comment]
> JetBrain IDEs set $TERMINAL_EMULATOR to JetBrains-JediTerm

I have CLion installed here and don't see it. I tested that before replying and could not find an identifying environment variable.

**Comment by zanchey** [comment]
I downloaded PyCharm and I can see it there.

**Comment by faho** [comment]
Okay, let's add it then.

**Comment by krobelus** [comment]
https://youtrack.jetbrains.com/issue/IJPL-166234

**Comment by miranquil** [comment]
> https://youtrack.jetbrains.com/issue/IJPL-166234

Say, I've submitted an issue too. But not assigned for now :(
