### ISSUE TITLE
Using nvim as PAGER hangs tab command completion

### ISSUE THREAD

**Issue by mitander** [fish-shell/fish-shell#10820]
fish, version 3.7.1
xterm-ghostty
macOS Sequoia 15.0.1 (24A348) - Darwin macos 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000 arm64

When using `set PAGER "nvim +Man!"` the tab completion for commands hangs in the __fish_apropos function when calling apropos, only recovering on ctrl-c (waited 10 min). 

```
mitander@macos /U/mitander> PAGER="nvim +Man!" fish_trace=1 complete -C 'cc'
--> __fish_describe_command cc
-----> string escape --style=regex -- cc
----> set -l argv_regex cc
----> awk -v 'FS= +- +' \{\n\t\tsplit\(\$1,\ names,\ \",\ \"\)\;\n\t\tfor\ \(name\ in\ names\)\n\t\t\tif\ \(names\[name\]\ \~\ /^cc.\*\ \*\\\(\[18\]\\\)/\ \)\ \{\n\t\t\t\tsub\(\ \"\(\ \|\\t\)\*\\\\\(\[18\]\\\\\)\",\ \"\",\ names\[name\]\ \)\;\n\t\t\t\tsub\(\ \"\ \\\\\[.\*\\\\\]\",\ \"\",\ names\[name\]\ \)\;\n\t\t\t\tprint\ names\[name\]\ \"\\t\"\ \$2\;\n\t\t\t\}\n\t\}
----> __fish_apropos ^cc
------> set -l whatis /Users/mitander/.cache/fish/whatis
------> set -l max_age 600000
------> set -l age 600000
------> if
------> test -f /Users/mitander/.cache/fish/whatis
--------> path mtime -R -- /Users/mitander/.cache/fish/whatis
-------> set age 3614
------> end if
------> apropos ^cc   <- hangs here
```

```
mitander@macos /U/mitander> PAGER="less" fish_trace=1 complete -C 'cc'
--> __fish_describe_command cc
-----> string escape --style=regex -- cc
----> set -l argv_regex cc
----> awk -v 'FS= +- +' \{\n\t\tsplit\(\$1,\ names,\ \",\ \"\)\;\n\t\tfor\ \(name\ in\ names\)\n\t\t\tif\ \(names\[name\]\ \~\ /^cc.\*\ \*\\\(\[18\]\\\)/\ \)\ \{\n\t\t\t\tsub\(\ \"\(\ \|\\t\)\*\\\\\(\[18\]\\\\\)\",\ \"\",\ names\[name\]\ \)\;\n\t\t\t\tsub\(\ \"\ \\\\\[.\*\\\\\]\",\ \"\",\ names\[name\]\ \)\;\n\t\t\t\tprint\ names\[name\]\ \"\\t\"\ \$2\;\n\t\t\t\}\n\t\}
----> __fish_apropos ^cc
------> set -l whatis /Users/mitander/.cache/fish/whatis
------> set -l max_age 600000
------> set -l age 600000
------> if
------> test -f /Users/mitander/.cache/fish/whatis
--------> path mtime -R -- /Users/mitander/.cache/fish/whatis
-------> set age 3809
------> end if
------> apropos ^cc
------> if
------> test 3809 -ge 600000
------> end if
cc      command
ccmake  command link
```

**Comment by krobelus** [comment]
Using plain Vim also reproduces the hang, and shows what's going on:

	$ PAGER=vim man man | cat
	Vim: Warning: Output is not to a terminal
	Vim: Warning: Input is not from a terminal
	^C

So macOS man has a bug: it invokes a pager even if stdout is redirected
(i.e. not a terminal).

Probably this hasn't been noticed because most pagers like `less` already
act like `cat` in that case, which is equivalent to using no pager.

A workaround is `PAGER='sh -c "if [ -t 1 ]; then vim; else cat; fi"' man man | cat`

This kind of logic needs to be added to the [upstream man implementation](https://cgit.freebsd.org/src/tree/usr.bin/man/man.sh).

I guess we still want to work around it by unsetting MANPAGER and PAGER in our subshells that call `apropos` or `whatis` (I don't think we call `man` from a subshell).

**Comment by krobelus** [comment]
reported as https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=282414
