### ISSUE TITLE
Run fish_config in terminal?

### ISSUE THREAD

**Issue by bbrk24** [fish-shell/fish-shell#10888]
Because of the way my terminal is set up, some of the colors are very different from standard. For example, using ANSI escape codes:

![image](https://github.com/user-attachments/assets/e038d0ff-75bf-4bbc-a72e-1f2773f2ae87)

This means that what the theme looks like in `fish_config browse` is very different from what it ends up being. Right now it's impossible to tell suggestions apart from what I've already typed because, while they are different color codes, they render identically or near-identically. (I think they might be 30 and 94 in the above list? But it's impossible for me to tell.)

Is it possible to run `fish_config` in the terminal itself, so that I can know what I'm setting my theme to?

**Comment by faho** [comment]
See https://fishshell.com/docs/current/cmds/fish_config.html:

```fish
fish_config theme show
fish_config prompt show
```

and so on.

**Comment by bbrk24** [comment]
```
> fish_config theme show
No such subcommand: theme
```

**Comment by faho** [comment]
Upgrade fish. Your version is older than 3.4.0, released in March 2022.

**Comment by bbrk24** [comment]
Huh, weird. When I try to upgrade it it says `fish is already the newest version (3.3.1+ds-3)`.

**Comment by faho** [comment]
Unfortunately, long term support distributions like the Ubuntu 22.04 you appear to be using do not upgrade to new versions during the lifetime of that version. That's just what that "long term support" means.

(in Ubuntu's case it's even worse because fish is in the "universe" part of the repository which makes the package essentially unmaintained entirely)

We offer repositories for fish at [fishshell.com](https://fishshell.com/), the Ubuntu one is hosted on launchpad: https://launchpad.net/~fish-shell/+archive/ubuntu/release-3. That will get you an up-to-date version.
