### ISSUE TITLE
`sudo make install` rebuilds everything

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#10894]
This is one of the reasons for 0083192fcbd8dcc63acc95e554ac6fa27e75dd01.

If you run

```fish
cmake ..
make
```

That will build fish once. If you then run

```fish
sudo make install
```

right after, it will rebuild the entire thing, possibly because the files don't have the right owner.

I'm not sure how to fix this. Can we get cmake to chown the files?

Or do we not want to support `sudo make install` at all, in which case we should remove it from the docs and potentially break it.

It seems pretty bad to have this rebuild, because it runs the entire build process as root.

**Comment by faho** [comment]
`ninja -d explain` tells us why it rebuilt something:

```output
[sudo] Passwort für alfa: 
ninja explain: output /home/alfa/dev/fish-shell/build/CMakeFiles/VerifyGlobs.cmake_force of phony edge with no inputs doesn't exist
ninja explain: /home/alfa/dev/fish-shell/build/CMakeFiles/VerifyGlobs.cmake_force is dirty
ninja explain: /home/alfa/dev/fish-shell/build/CMakeFiles/cmake.verify_globs is dirty
[0/2] Re-checking globbed directories...
ninja explain: output CMakeFiles/fish doesn't exist
ninja explain: CMakeFiles/fish is dirty
ninja explain: fish is dirty
ninja explain: output CMakeFiles/fish_indent doesn't exist
ninja explain: CMakeFiles/fish_indent is dirty
ninja explain: fish_indent is dirty
ninja explain: output CMakeFiles/fish_key_reader doesn't exist
ninja explain: CMakeFiles/fish_key_reader is dirty
ninja explain: fish_key_reader is dirty
ninja explain: output CMakeFiles/CHECK-FISH-BUILD-VERSION-FILE doesn't exist
ninja explain: CMakeFiles/CHECK-FISH-BUILD-VERSION-FILE is dirty
ninja explain: FISH-BUILD-VERSION-FILE is dirty
ninja explain: output CMakeFiles/sphinx-docs doesn't exist
ninja explain: CMakeFiles/sphinx-docs is dirty
ninja explain: fish_indent is dirty
ninja explain: output CMakeFiles/sphinx-manpages doesn't exist
ninja explain: CMakeFiles/sphinx-manpages is dirty
ninja explain: CHECK-FISH-BUILD-VERSION-FILE is dirty
ninja explain: sphinx-docs is dirty
ninja explain: sphinx-manpages is dirty
ninja explain: doc is dirty
ninja explain: CHECK-FISH-BUILD-VERSION-FILE is dirty
ninja explain: build_fish_pc is dirty
```

**Comment by zanchey** [comment]
`sudo ninja install` has [its own problems](https://github.com/ninja-build/ninja/issues/1302).

I think this is because cargo is running as a different user and redownloads/rebuilds all the crates, which means the binaries look like they need rebuilding.

Spelunking around finds https://github.com/eclipse-zenoh/zenoh-c/pull/105 which correctly identifies that `sudo cmake --install .` won't rebuild the targets. I'll switch the README (and also add some more verbiage about using prebuilt binaries, due to my ongoing campaign to avoid people messing up their systems).

It does leave the build directory full of artifacts owned by root, but if you can create that problem I figure you can fix it.
