### ISSUE TITLE
Call rust code from fish shell natively?

### ISSUE THREAD

**Issue by SerJaimeLannister** [fish-shell/fish-shell#10984]
Now that fish has been written in rust , can we have some sort of interop b/w these please?

My use case is that https://github.com/oconnor663/bao , I want to run this a lot of times in seeing if a collission is possible / just for fun and I don't know rust (simply because it fears me yet the ecosystem of rust justs keep on getting better & though I can spawn a process , I wouldn't like the process spawning overhead. )

Since fish has been ported to rust , I was hoping that maybe we can have  some sort of interop.

Now I am not entirely sure how we can go about doing it , but I currently think that if we can have the fish shell source code repository and we can add any rust repository & call that rust repository from the source code of fish and also instead of the source code of fish building the fish shell , it rather reads a fish script and outputs it , for example 

I am extremely sorry if I had complicated things in this text but I have sincerely tried my best to explain this in the picture given below . (If somebody else wants to paraphrase the thing that I am trying to say better , then I might edit this post to say that instead )

![image](https://github.com/user-attachments/assets/069031b1-337d-4c26-b4ae-3c7191284f76)

I truly believe in the potential of fish-shell now that it has become rusted and this can really increase that ten-fold .

**Comment by faho** [comment]
Okay, that's the third issue in like 5 minutes.

Please stop.

**Comment by faho** [comment]
If you would like to propose something here, it needs to be more fleshed out than can be gobbled together in five minutes.

Here are the questions you would need to answer:

- What do you want? To incorporate a hashing tool, to link more stuff into fish generally, or to add a "module" interface that can load stuff at runtime?
- Why do you want it? Note that "process overhead" isn't super convincing for a hashing tool, because hashing is notoriously computing-intensive and so there's going to be a lot of time spent in that tool.
- What other use cases are there besides "I want my hashing to be faster"?
- How, roughly, should this work? Would we have to add a dependency on the thing you want to add? Or would we add a new directory where the user could place libraries and then they are available for *some* use? Would this have access to all of fish's internals? Would there be a defined boundary? What about backwards-compatibility (newer fish, older module or older fish, newer module)? How do we make sure this does not crash fish?

Note that this is a high barrier - there are shells that have loadable module APIs (I believe both bash and zsh have them?). I've never seen them used and I don't have a clue why they exist. It seems like a lot of work and surface for bugs for very little gain for regular people, only supporting a few power users. I don't believe it is a good idea and would have to be convinced.

Please open this as a new issue, but spend at least a day on it, so we know you've done the work. Also, when in doubt leave out the big images.
