### ISSUE TITLE
Syntax improvements for redirection & pipes

### ISSUE THREAD

**Issue by dhasenan** [fish-shell/fish-shell#110]
Assuming I have a process that writes to both stderr and stdout, and I want to pipe both to tee, I should be able to do:

./a.out ^&1 | tee log

This ends up with 'log' being empty.

I suspect that fish is assigning the stderr input stream to the stdout sink, then assigning the stdout input stream to the pipe sink. Another layer of indirection would likely solve this -- instead of copying the stdout sink, you assign a wrapper sink instead. This would require caution to catch the case of redirecting >&2 ^&1, of course, but it would allow people to redirect and pipe at the same time and make it work.

**Comment by alphapapa** [comment]
Just a thought: Bash uses `&>` to redirect both STDOUT and STDERR, and `|&` (yes, reversed...) to pipe both STDOUT and STDERR.

So I propose that fish use `&>` to redirect both STDOUT and STDERR, and both `|&` and `&|` to pipe them.  (I propose using both pipe forms because, hey, who can remember whether it's "and-pipe" or "pipe-and"?  But remembering that they go together to "pipe-stdout-and-stderr" makes sense.)

So these would be equivalent:

Bash:
```
command |& grep
```
Fish:
```
command |& grep
command &| grep
```

**Comment by abc-mikey** [comment]
Just a gentle reminder that it's coming round to 4 years since this issue was opened.

**Comment by tsion** [comment]
```fish
function foo
    echo stdout
    echo >&2 stderr
end

foo ^&1 | tee out # out contains both lines of output
```

This works for me today (version 2.2.0). Both stdout and stderr get piped to tee. I tested with a little C program as well and it still worked. Maybe this should be closed?

**Comment by faho** [comment]
Doing @gustafj's [test](https://github.com/fish-shell/fish-shell/issues/110#issuecomment-12592722), I now get:

```fish
>  cmd | cat - >/dev/null
stderr
> cmd 2>| cat - > /dev/null # all "2>" can also be replaced with "^"
stdout
> cmd 2>| cat -
stdout
stderr
> cmd 2>&1 | cat - > /dev/null
>
```

This means it's okay since probably https://github.com/fish-shell/fish-shell/commit/4899086b3c57ff2c36e62458ebb2986b95c2f631.

However, as @ridiculousfish [pointed out](https://github.com/fish-shell/fish-shell/issues/110#issuecomment-22917180):

>I want to leave this open for further discussion on syntax improvements for redirections. The current thinking is that foo | bar pipes stdout, and foo ^| bar pipes stderr. The syntax for piping both is unclear, even though there's agreement that piping both is more common than piping stderr independently.

Personally, I don't really care. `2>&1 |` is okay for the few times I use it, though I might be weird - I pipe them separately more often than combined, including _just_ stderr.

Because of the repurposing of this issue, I'll change the title to something more fitting.

**Comment by rocketraman** [comment]
I'm not sure if this is related to the discussion here. If not, my apologies. In bash, if one does:

`sudo echo "foo" | grep foo`

one gets the sudo password prompt before grep finds the foo.

In fish, if one does the same thing, the sudo password prompt is not echoed to the terminal. And worse, input from the keyboard is not sent to sudo.

I don't know if bash has some special handling for this case, but thought I'd throw this out there.

**Comment by onodera-punpun** [comment]
I'd like it if something like `^>` and/or `>^` would redirect both stdin and stderr.

**Comment by anddam** [comment]
@onodera-punpun what about the current *^>* stderr redirection?

Adding a new *>^* syntax would indeed be confusing.

**Comment by solson** [comment]
@anddam What? `^>` is currently a syntax error.

**Comment by onodera-punpun** [comment]
@anddam tbh I never know, I'm pretty sure it's either `>&2` or ^&1`, anyways, both are ugly, confusing, inconsistent, and hard to remember, `^>` and `>^` are both not in use currency, and the opposite of the points I listed earlier.

**Comment by anddam** [comment]
@solson correct, I mixed up the syntax (that I've been using till an hour ago) and somehow thought *^* was *^>* in fact. My bad and sorry for the noise.

Anyway as a general principle I wouldn't overload too much combinations of > ^ and so, I'd rather have a more verbose but clear syntax than having to check man every time (as in fact I did with bash and what made me look for a shell with a tidier syntax).

**Comment by alphapapa** [comment]
To summarize the current suggestions:

*  Both `&|` and `|&` would pipe STDOUT and STDERR together.
*  Both `>^` and `^>` would redirect STDOUT and STDERR together.

Using both combinations for each case solves the problem of having to remember the order of the characters.

In a sense they mirror each other and seem to make sense.

However, the piping syntax is definitely a Bashism.  So even though I generally favor it, let me add a third suggestion:

*  Using `>^|` and `^>|` would pipe STDOUT and STDERR together.  This makes for a 3-character combo, which I guess is unusual, but it seems to make sense in that it composes existing Fish syntax characters in a logical way.

 However, this also raises the question of whether something like `>|` or `^|` should work, for consistency with the composability.  Of course, `>|` is redundant, as plain `|` pipes STDOUT, but what should `^|` do?  I guess it would make sense for it to pipe only STDERR, as in `>/dev/null ^&1 |`.  And that actually seems like it could be pretty handy; it sure saves a lot of typing in that case.

**Comment by solson** [comment]
@alphapapa  `>|` and `^|` already work. Additionally, there is an existing expanded form of `N>|`.

`>|` is equivalent to `1>|` and `^|` is equivalent to `2>|`.

I would support having `>^`/`^>` for double-redirection to a file and `>^|`/^>|` for double-redirection to a pipe. These seem like a natural extension of the existing syntax to me.

**Comment by alphapapa** [comment]
> >| and ^| already work. 

Well, how about that!  :D 

> I would support having >^/^> for double-redirection to a file and >^|/^>| for double-redirection to a pipe. 

I'd just like to point out how fishy some of those look, which I hope could be preserved in the docs somehow...  ;)

**Comment by balupton** [comment]
could someone add an answer on http://unix.stackexchange.com/q/70963/50703 with what the fish equivalents are for each one, cheers

**Comment by ridiculousfish** [comment]
fish has the same syntax for all of those cases, except that `|&` and `&>` are not supported. I can add that to the SO question if that would be useful.

**Comment by balupton** [comment]
@ridiculousfish yeah - I was wrestling with `&>` myself - I ended up going with `> /dev/null ^ /dev/null` - the `^ /dev/null` was not mentioned on the SO answer, so would be a good addition

**Comment by balupton** [comment]
with my above answer, the `command > /dev/null ^ /dev/null` works only for the `/dev/null` output - if you want to pipe stdout and stderr to the same file, it won't work, as the `>` and `^` will overwrite each other.

**Comment by Phidica** [comment]
Being that #4394 has removed `^` as the operator for redirection of the stderr file descriptor, I think that rules out all suggestions which involved the caret (leaving, for the most part, just things involving `&`). I have a new suggestion which as far as I can tell hasn't been brought up in GitHub discussions before.

How about, to redirect multiple file descriptors to the same file, we extend the syntax to allow a *list of file descriptors* into the redirection operator? To redirect both stdout and stderr to the same file, it would simply be `1,2>myfile`. I think this feels quite intuitive, as it hearkens to the comma used in brace expansion, implying the behaviour will be something like `{1,2}>myfile` = `1>myfile 2>myfile`.

Of course, this cannot *actually* "expand" to `1>myfile 2>myfile` because as @balupton has pointed out above this (unintuitively) causes each file descriptor to independently overwrite the file. It would have to result in `1>myfile 2>&1` or `2>myfile 1>&2` (both are equivalent), but the *idea* is there. Understanding brace expansion lends to an understanding of "redirection expansion" and the naive theory of what it would achieve.

This applies similarly in the case of redirection-into-pipe: `1,2>|` is suggestive of `1>| 2>|` (actually an invalid syntax) but it will achieve `2>&1 |`.

In discussion above, @ridiculousfish's take is that "no common redirections should require using numbers". But with the removal of `^`, redirection of stderr explicitly requires `2`, so we can't really avoid numbers in common redirections any more. In order to desire redirection of stdout and stderr, a user must already know about stderr and hence already know that it is represented by 2.

Discussion in this thread supports `&>` or `|&` as the "1 and 2" redirection or pipe. But that would effectively *limit* us to only having a convenient syntax to pair 1 with 2. #3303 is an open discussion of redirection involving file descriptors 3 and above, perhaps in some way where they just open on demand when first used. What if we want to pair redirection of 1 with 3? 2 with 4? I think that a list syntax (`1,3>`, `2,4>`) would be a good generic syntax that is prepared for a possible future where redirection with higher file descriptors is more practical.

(And if we really wanted to save another character, then `1` could be implicit around a comma. So `1,2>` could be done with `,2>` or `2,>` which are then just one character away from `&>`.)

**Comment by JoshCheek** [comment]
A bit late, but a note for @balupton, you can get it to work for files with 

```sh
$ bash -c 'echo out; echo err >&2' > file ^ /dev/stdout`
$ cat file
out
err
```

**Comment by crocket** [comment]
Why does `cmd >/dev/null ^&1` not produce the same result as `cmd ^&1 >/dev/null`?

**Comment by balupton** [comment]
What is the status of this now that https://github.com/fish-shell/fish-shell/issues/4394 landed in v3

**Comment by faho** [comment]
Yup, this should be closed.

An overview of the current situation:

- `^` is deprecated and can already be turned off. Use `2>`.
- `2>|` pipes just stderr.
- `2>&1 |` pipes both. (In my experience, this is rarely necessary)

**Comment by Phidica** [comment]
Should I open a new issue with my suggestion then? I think it's an interesting idea for extending the redirection syntax

**Comment by faho** [comment]
Honestly, I don't think shortcuts are needed here. Which is also why we stepped away from `^` - it looks a teensy bit nicer, at the cost of an additional special character.

If you want to redirect both stdout and stderr, use `>/path/to/file 2>&1`.

**Comment by floam** [comment]
Well, I like the {1,2}> idea. It's actually consistent with expansion. I've actually tried exactly that and hoped it'd work in the past. I say open up an issue!

**Comment by frankseide** [comment]
I have been reading several of these issues, and I still cannot figure out how to redirect both stdout and stderr into tee in the fish shell.

**Comment by faho** [comment]
@frankseide In fish 3.1 `&|` is shorthand.

Otherwise `2>&1 |`.

----

In future, please don't comment on random issues. Instead open a new one or ask on https://gitter.im/fish-shell/fish-shell.
