### ISSUE TITLE
Need command to print out fish logo

### ISSUE THREAD

**Issue by dhasenan** [fish-shell/fish-shell#114]
Something like:

```
function logo
  echo '                  ___
   ___======____=---=)
 /T            \_--===)
 [ \ (0)   \~    \_-==)
  \      / )J~~    \-=)
   \\\\___/  )JJ~~~   \)
    \_____/JJ~~~~~    \\
    / \  , \J~~~~~     \\
   (-\)\=|\\\\\~~~~       L__
   (\\\\)  (\\\\\)_           \==__
    \V    \\\\\) ===_____   \\\\\\\\\\\\
           \V)     \_) \\\\\\\\JJ\J\)
                       /J\JT\JJJJ)
                       (JJJ| \UUU)
                        (UU)'
end
```

Color would be nice, though.

**Comment by krader1961** [comment]
The official logo is included in the source as *doc_src/ascii_fish.png*.  Anyone who wants to can repurpose it for their needs.

**Comment by justinmayer** [comment]
In case anyone finds it helpful, my [Tackle](https://github.com/justinmayer/tackle) collection includes the ASCII-based logo via the `_logo` function: https://github.com/justinmayer/tackle/blob/master/functions/_logo.fish

**Comment by laughedelic** [comment]
For those who may encounter this issue later, I made a plugin for printing fish logo with different colors and "faces": [fish_logo](https://github.com/laughedelic/fish_logo#fish_logo).

**Comment by floam** [comment]
`The official logo is included in the source as doc_src/ascii_fish.png. Anyone who wants to can repurpose it for their needs.`

It's kind of awkward having that just as a PNG image requiring someone to OCR it or find the archived email if they wanted "the source".

I don't really see the harm in including that ASCII art as ASCII text, either somewhere in the repository or as part of the default greeting.

**Comment by floam** [comment]
Who owns the copyright to this creation? Who is the originator? That mailing list poster?

**Comment by krader1961** [comment]
I'm going to close this, again, for multiple reasons. First, it is five years old and we are not going to add a command to display a text version of the fish logo. Because such a command doesn't serve a legitimate purpose.

We could include a text version of our logo as an alternative to the PNG version we currently have. But the version linked to by @pathawks in his [comment](https://github.com/fish-shell/fish-shell/issues/114#issuecomment-270560843) assumes the terminal understands ANSI X3.64 escape sequences. While that standard is ubiquitous it is not clear a text version of our logo should require it. Too, nearly five months after @floam asked about attribution for that file we haven't gotten a response.

**Comment by pathawks** [comment]
> Too, nearly five months after @floam asked about attribution for that file we haven't gotten a response.

Are you asking about the text file in my comment? It's just the output from the script in @xfix's comment.
