### ISSUE TITLE
Suggestion, Implement "time"

### ISSUE THREAD

**Issue by etu** [fish-shell/fish-shell#117]
Like in bash:

```
$ time <do something that takes time>
...

real 0m0.000s
user 0m0.000s
sys 0m0.000s
$
```

**Comment by ryanhiebert** [comment]
AFAICT, the wrapper doesn't work for fish functions that aren't defined in the shell config. That means that I can't time functions that are only in the current shell.

So another :+1: from me to have it be builtin that is capable of running functions.

**Comment by krader1961** [comment]
FWIW, I agree with @ridiculousfish that

> We can probably leverage the existing profiling support to make for a really awesome version of time.

The `fish -p` switch is useful for evaluating the performance of an entire fish script (or interactive session) but isn't useful for evaluating the performance of a particular function in real-time. I'm not convinced that the `time` command should become a builtin since the time elapsed and CPU time doesn't provide useful insight into why a function is slow. It would, however, be very useful if there was a way to dynamically invoke performance profiling, ala `-p`, when running a specific command (i.e., function). Without including all the overhead of starting the shell, constructing a prompt, etcetera.

**Comment by sanmai-NL** [comment]
This is [already implemented](http://fishshell.com/docs/current/index.html):
Under Fish version 2.2.0:
```fish
sleep 10
echo $CMD_DURATION
````
> 10003

The issue can be closed ...

**Comment by krader1961** [comment]
It seems like this should work but doesn't:

```
function time
	eval (string escape $argv)
        echo command took $CMD_DURATION ms
end
```

For some reason `$CMD_DURATION` doesn't reflect how long the eval line took to execute. It appears to be the time required by the preceding command. That is, it appears to be updated only at the top-most execution context. So you can't actually use it within a function to find out how long the most recent command run by the function took to complete. I haven't yet looked at the source so it's hard to know if this is intentional or not. Certainly the documentation makes no mention of this limitation.

**Comment by etu** [comment]
Nowadays I mostly use:
```
function ltime --description 'Print command duration in seconds for last command'
	echo (echo 'scale=3; ' $CMD_DURATION ' / 1000' | bc)"s"
end
```

and run it after the command is completed. This assumes 2.2.0 or newer to work well. So my need for this is kinda dead.

ltime of course stands for "last time" or something like that.

**Comment by bucaran** [comment]
AFIK `$CMD_DURATION` is the epoch since the last command, **not** function. So, while @etu's is not forking a new instance of `fish`, I wonder if this is any better than `time fish -c "..."`?

:pensive:

**Comment by faho** [comment]
@bucaran: Yeah, that it doesn't include fish's startup time. Remember that fish always sources all of its configuration files.

Like @krader1961 noticed "$CMD_DURATION" is updated too late (which means you always need to check it after the next prompt, as a separate command), but that might not be unfixable.

But a much more awesome solution here would be what has already been proposed - a way to get our already existing profile stuff and apply it only to a certain command, e.g.

`profile for i in (seq 1000); fish -ic 'exit'; end`

And then `time` as a simpler way to get just the summary.

**Comment by jichu4n** [comment]
Shameless plug: I made a [fish-command-timer](https://github.com/jichu4n/fish-command-timer) plugin to do this - it makes fish print out the execution time of each command line. Please feel free to check it out!

Code: [jichu4n/fish-command-timer](https://github.com/jichu4n/fish-command-timer)

Screenshot:
![fish-command-timer screenshot](https://github.com/jichuan89/bash-command-timer/raw/master/bash_command_timer_screenshot.gif)

**Comment by whitelynx** [comment]
So, starting from some of @jichu4n's earlier code (before he switched `fish-command-timer` over to using `$CMD_DURATION`), I came up with this function to hack around the problem:

```csh
function realtime
	set -l command_start_time (date '+%s%N')
	eval (string escape $argv)
	set -l command_end_time (date '+%s%N')
	set -l command_duration (math "$command_end_time - $command_start_time")

	set -l minutes (math "$command_duration / 60000000000")
	set -l seconds (math "$command_duration % 60000000000 / 1000000000")
	set -l milliseconds (math "$command_duration % 1000000000 / 1000000")

	printf '\nreal\t%dm%d.%03ds\n' $minutes $seconds $milliseconds
end
```

It only tells you the "real" time (wall clock time) of the given command, not the user or system CPU time like bash's `time` command does, although that's the same as `$CMD_DURATION` anyway.

The big advantage over `$CMD_DURATION` is that you can use it in a loop, which is rather important for benchmarking. As an added bonus, it outputs in the same format as bash's `time` command. (minus the `user` and `sys` lines)

----

Regardless, I think the idea of a built-in command utilizing the existing profiling support is a very good idea; it's the only way we'd be able to get accurate insight into something like user/system CPU time, and it could easily give us more information too.

**Comment by pgan002** [comment]
Is it possible to make `CMD_DURATION` hold the runtime of the last function if the last command was a function, otherwise the last command?

We could even make `DURATION` an array containing the runtime of (1) the last function, (1) block, (3) individual command. If there is no block or function, `DURATION` would contain three identical elements. This allows the user to know the runtime after the command is executed, unlike a builtin which requires the user to think of it before executing the command.

Using three variables `CMD_DURATION`, `FUNC_DURATION`, `BLOCL_DURATION` feels like polluting the variable space.

**Comment by JoshCheek** [comment]
My system didn't have subsecond options for the date command, so I edited @whitelynx's script. Also added exit status and printed the result to stderr:

```fish
function realtime
       set -l start    (date '+%s')
       eval (string escape $argv)
       set -l _status  $status
       set -l stop     (date '+%s')
       set -l duration (math "$stop - $start")
       set -l minutes  (math "$duration / 60")
       set -l seconds  (math "$duration % 60")
       printf 'real\t%dm%ds\n' $minutes $seconds 1>&2
       return $_status
end
```

**Comment by devurandom** [comment]
That script does not appear to work with command line arguments:
```
> realtime planck -e '(println "Hello World")'
string escape: Unknown option “-e”
~/.config/fish/functions/realtime.fish (line 2):
in command substitution
        called on line 0 of file ~/.config/fish/functions/realtime.fish

in function “realtime”
        called on standard input
        with parameter list “planck -e (println "Hello World")”
[...]
```

I am using Fish Shell version 2.6.0.

**Comment by zanchey** [comment]
Change `string escape $argv` to `string escape -- $argv`.

**Comment by ikbelkirasan** [comment]
Another workaround is to add a `time` function that uses bash's builtin time command to your `~/.config/fish/config.fish` file.

```
function time
   bash -c "time $argv"
 end
```

**Comment by faho** [comment]
This has now been implemented.

**Comment by anrddh** [comment]
Is this a bug:

```
~ $ builtin time
fish: Unknown builtin “time”
builtin time
        ^
~ $ builtin time
```

**Comment by zanchey** [comment]
@anrddh, yes, see #6598.
