### ISSUE TITLE
Make `cd` with multiple arguments actually useful.

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1205]
Currently, arguments after first are completely ignored. In my opinion, the arguments should be joined by space, making fish on Windows platforms more convenient.

**Comment by faho** [comment]
It seems zsh's does "Path replacement", i.e `cd (string replace -- "$argv[1]" "$argv[2]")`. That might be an option and is easily implemented.

**Comment by alphapapa** [comment]
This seems like a pretty good idea to me.  It would be nice to not have to type quotes around names that contain spaces.  Tab completion usually handles it pretty well for me, but sometimes you need to type it out.  I can't think of a downside to doing this for just the `cd` command.

**Comment by faho** [comment]
You can try it out for yourselves - `funced cd` and replace both occurences of `$argv[1]` with `"$argv"`.

You'll see that syntax highlighting breaks - because the completion doesn't know about the special case, which means the special case doesn't show up in the completion (e.g. if you `cd /tmp/a b`, it will mark the "b" as wrong because the completion only has "/tmp/a\ b").

It's also completely inconsistent with the rest of the shell and bad for learning purposes - such a core part of the shell _doesn't_ need escaping or quoting?

I'd like the path replacement better.

**Comment by alphapapa** [comment]
> You'll see that syntax highlighting breaks - because the completion doesn't know about the special case, which means the special case doesn't show up in the completion (e.g. if you cd /tmp/a b, it will mark the "b" as wrong because the completion only has "/tmp/a\ b").

That would be a bit annoying.  How hard would it be for the syntax highlighting to handle `cd` specially?

> It's also completely inconsistent with the rest of the shell and bad for learning purposes - such a core part of the shell doesn't need escaping or quoting?

`cd` currently ignores everything except the first argument.  I don't see the harm in making this one command a bit more convenient to use.  It does become annoying to have to escape or quote spaces when typing paths containing spaces.  

The point of the `cd` command is to change the working directory, not to teach people about Fish's idiosyncrasies.  This change would make `cd` better at its job.  :)  In contrast, there are some actual, problematic idiosyncrasies in Fish that do need to be easier to learn or more prominently mentioned.

The only thing that would be negatively affected by doing this would be the syntax highlighting, which could be fixed.  IMO, the convenience this change would offer would be worth it.

> I'd like the path replacement better.

Maybe I'm dense, but I don't understand the example you gave.  Maybe it's because I don't have a version of Fish with the `string` command.  :)  But if it effectively does `sed "s/$argv[1]/$argv[2]/"`, how would that work?

I just did `funced cd` and added this to the very top of the function:
```fish
# Handle multiple arguments
if test (count $argv) -gt 1
    return (cd (printf "%s/" $argv))
end
```
Seems to work fine.  The syntax highlighting is a minor annoyance for now, but it's really nice to not have to escape or quote spaces now!

**Comment by faho** [comment]
>That would be a bit annoying. How hard would it be for the syntax highlighting to handle cd specially?

I don't see a way to do it purely via script (except adding a "-u" to cd's `complete` calls, but this would neuter the highlighting). And in C it would still probably need an actual special case.

>Maybe I'm dense, but I don't understand the example you gave. Maybe it's because I don't have a version of Fish with the string command. :) But if it effectively does sed "s/$argv[1]/$argv[2]/", how would that work?

See [this on stackoverflow](http://stackoverflow.com/questions/32531781/is-there-a-zsh-like-path-replacement-in-fish-shell).

I'm not particularly _in love_ with path replacement (it's one of the things I'd probably never use), but it's been asked about before and there's prior art. It's also not inconsistent with the rest of the shell, and it's almost trivial to implement.

**Comment by alphapapa** [comment]
> I don't see a way to do it purely via script (except adding a "-u" to cd's complete calls, but this would neuter the highlighting). And in C it would still probably need an actual special case.

Well, I'm not volunteering to do that special casing, so I can't volunteer anyone else's time either.  :)  But it sure would make `cd` more useful, which I think is one of Fish's goals in general.

Lacking that, perhaps this could be mentioned as an example in the FAQ or something as a "recommended customization."  Or maybe there should be a section in the Fish docs for "Frequently Recommended Code."

> I'm not particularly in love with path replacement (it's one of the things I'd probably never use), but it's been asked about before and there's prior art. It's also not inconsistent with the rest of the shell, and it's almost trivial to implement.

Ah, thanks.  That is very cool.  I think it would be great to have that in Fish, but maybe as a separate command.  `cdr` isn't a command on my machine, so maybe that would work, and `change directory (replacement)` could be the mnemonic.

**Comment by krader1961** [comment]
I'm closing this because

a) it is now three years old without consensus on how to change the behavior, and

b) special casing `cd` while leaving other commands that take pathnames with the current behavior will cause more problems than it solves, and

c) pathname completion via [tab] already handles whitespace as expected.
