### ISSUE TITLE
Completion of `perl -MModule` doesn't work.

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1229]
Write `perl -MModule`, and space. After that, press Tab. It tries to complete Perl modules, even if one was already specified.

**Comment by krader1961** [comment]
Unfortunately unless someone who uses the command actually writes the required completion script code it will never be implemented. We are happy to answer questions and provide guidance about implementing a better completion script for perl. However, I'm going to close this because unless someone like yourself actually does that work it will never be done. Feel free to reopen this issue if you, or anyone else, is interested in making the required changes and needs advice.
