### ISSUE TITLE
If command substitution fails, the rest of the command still executes

### ISSUE THREAD

**Issue by jamesgecko** [fish-shell/fish-shell#1246]
I have a command set up that prints out the name of the git current branch. I use it in a command substitution when I push a branch to master, like so: `g push origin (cbr)` Today I accidentally mistyped it.

```
><((°> g push origin (gcb)
fish: Unknown command 'gcb'
in command substitution
    called on standard input,

warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Counting objects: 173, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (54/54), done.
Writing objects: 100% (59/59), 7.17 KiB | 0 bytes/s, done.
Total 59 (delta 45), reused 13 (delta 5)
To git@github.com:foo/bar
PUSHING EVERY LOCAL BRANCH! CHAOS AND MAYHEM.
```

Fortunately, the command didn't have `-f`. And like git says, the default behavior of `push` is changing soon. But I was really surprised that a failing command substitution didn't abort the whole command. Is this intentional behavior? It seems kinda dangerous.

**Comment by krader1961** [comment]
I am opposed to modifying fish to not run an outer command if a command substitution fails. What would this mean if you had more than one command substitution and one of them fails? Since we don't define the order, AFAIK, chaos ensues. And even if we define a left to right (or opposite) order rather than parallel execution the semantics are still problematic.

The solution to this problem is to use the semantics of the `set` command. For example,

```
set gcb_output (gcb)
or return
g push origin $gcb_output
```

**Comment by faho** [comment]
Yeah it's not happening.
