### ISSUE TITLE
Remove unnecessary pressing

### ISSUE THREAD

**Issue by 3DRaven** [fish-shell/fish-shell#1286]
When typing text, it gives options previously entered. It is very good.
But that would be necessary after pressing "enter", he carried out an entire row with the team! He performs only what you typed and it is wildly angry. You should click first on the keyboard cursor, then to enter. Why extra touch?

**Comment by faho** [comment]
@ridiculousfish: Is there a chance of this being added to the defaults or are we going to leave it to user configuration?

**Comment by ridiculousfish** [comment]
shift + enter you mean? If terminals don't distinguish between enter and shift + enter, then there's no value in trying to do something different on them.

**Comment by faho** [comment]
No, I mean either:

- Making enter accept and execute at once

or

- Introducing a new keybinding that accepts and executes - whether that's Shift+Enter (which might have problems on some terms) or Alt+M or whatever

I'm opposed to the former because it's a large behavioral change and _will_ confuse and potentially destroy data (think "rm"), but I don't care much about the latter. It's easy enough to add with #1567 fixed, but noting that it's possible by actually including the key is also okay.

**Comment by dpc** [comment]
Google sent me here, because I was looking for a way to make Alt+Enter / Shift + Enter accept the autosuggestion.

I've tried suggestions here and they don't seem to work for me.

Can someone tell me what is the final solution for this?

Also, I think something like this should be a default.

**Comment by faho** [comment]
@dpc: What fish version are you running (`echo $FISH_VERSION`)? For me with fish from git (some 500 commits since the 2.2.0 release), `bind \cs 'commandline -f accept-autosuggestion execute'` seems to work. #1567 was fixed in 2.2.0, so you don't need to reverse the order anymore.

**Comment by dpc** [comment]
```
> fish --version
fish, version 2.2.0
```

Fedora, standard.

Do I have to have this commands or can I issue them interactively, to test?

**Comment by faho** [comment]
>And \cs means what exactly? I thought it should be \em.

`\cs` means "Control and s", while `\em` means "Escape or Alt and m". I just bound it to a different key because I found it easier to reach.

>Do I have to have this commands or can I issue them interactively, to test?

You can issue the above bind command interactively and it should then work for that running session. If you'd like to have it in all fish sessions, put it in the `fish_user_key_bindings` function (we currently overwrite all bare keybindings specified in config.fish).

**Comment by dpc** [comment]
OK, so can you paste the exact two commands, in the correct order, that I should copy and paste and it should work? I know there are above, but just for clarity and making sure I'm not making any silly mistake here.

**Comment by faho** [comment]
@dpc: That one command. This one: `bind \cs 'commandline -f accept-autosuggestion execute'`. Replace the `\cs` with something else if you like.

**Comment by krader1961** [comment]
@dpc: To find out what, if anything, your terminal sends when you press [Shift-Enter] or [Alt-Enter] try running something like `od -tx1z` then pressing the keys followed by [Ctrl-D] (assuming you're on Linux or other UNIX OS). You may need to configure your terminal to send a distinct sequence of characters when you press those keys. For example, by default iTerm2 (which is what I use) just sends a carriage-return regardless of whether or not I also press the [Alt] or [Shift] keys.

**Comment by faho** [comment]
Okay, binding this should work, and I don't believe we should add something like this to the default keybindings, so I'm closing this issue.
