### ISSUE TITLE
ssh's completions for "-o option" should include "=" as a suffix

### ISSUE THREAD

**Issue by MerelyAPseudonym** [fish-shell/fish-shell#1299]
(N.B. as far as I'm concerned, this a **minor** issue and should cause no one stress. In fact, I'd be happy to tackle this issue.)

With the current behavior, I _always_ need to press <kbd>delete</kbd> once after accepting a `ssh -o` tab completion. For example, if I press <kbd>tab</kbd> after typing `ssh -o Pu`, fish will expand to `ssh -o PubkeyAuthentication` (note the trailing space!). SSH will fail unless you delete the space and replace it with `=yes` or `=no`.

```
$ ssh -o PubkeyAuthentication localhost
command-line line 0: Missing yes/no argument.
$ ssh -o PubkeyAuthentication yes localhost
command-line line 0: Missing yes/no argument.
$ ssh -o PubkeyAuthentication no localhost
command-line line 0: Missing yes/no argument.
$ ssh -o PubkeyAuthentication=no localhost
# *now* it'll work
```

**Comment by krader1961** [comment]
Unfortunately unless someone who uses the command actually writes the required completion script code it will never be implemented. We are happy to answer questions and provide guidance about implementing a better completion script for ssh. However, I'm going to close this because unless someone like yourself actually does that work it will never be done. Feel free to reopen this issue if you, or anyone else, is interested in making the required changes and needs advice.
