### ISSUE TITLE
Command substitution leaks processes if they expect input (command substitutions run in their own process group)

### ISSUE THREAD

**Issue by Undeterminant** [fish-shell/fish-shell#1362]
Example: `set -l var (cat)`

Expected: `$var` contains value of user input.

Actual: `$var` contains an empty string, and if you run `jobs`, a stopped but not reaped `cat` process lingers unless you run `kill -9` on it.

I understand that in this case, I could use `read`, but this error would still be a thing.

**Comment by zanchey** [comment]
`fzf` recommends a workaround which may be helpful in some instances - see the [fzf README](https://github.com/junegunn/fzf#fish-shell) for an example.

**Comment by paulcarey** [comment]
Rather than calling `$ vim (git ls-files | peco)` which fails for the reason described above, `xargs` can be used to the same effect.

     $ git ls-files | peco | xargs -I _ fish -c 'vim _ < /dev/tty'

I'd guess that the original issue with `set` could be worked around with a wrapper function that set a universal variable, but I haven't tried this.

**Comment by jcelliott** [comment]
Another vote for finding a way to fix this. Is it something that can reasonably be changed?

**Comment by ridiculousfish** [comment]
Oh sure, we just have to fix it.

**Comment by jcelliott** [comment]
Any pointers on where to start looking?

**Comment by ridiculousfish** [comment]
The key change is to run command substitutions in the foreground process group, and to properly handle stopped jobs when doing command substitutions .It would be interesting to investigate how bash handles this - what happens if you stop (e.g. ctrl-Z) a job in a command substitution?

**Comment by JoshCheek** [comment]
Looks like it just kills it.

![bash-interrupt-bg](https://cloud.githubusercontent.com/assets/77495/6248384/52556960-b73c-11e4-9575-53c244921d02.gif)

**Comment by zanchey** [comment]
It swallows Ctrl-Z, but running `kill -SIGSTOP` from another session just queues input until sent `SIGCONT`.

**Comment by merlinthered** [comment]
I'm just bumping this, since it has become a problem for me.

**Comment by sebastianmarkow** [comment]
Just wanted to share a workaround via `read(1)` which is IMHO better than dumping stdout to file (seen elsewhere).

A snippet from my interactive history search keymap:
~~~fish
    history | fzf --tiebreak=index --header="history" -q (commandline -b) | read -l fzf_last_select
    [ $fzf_last_select ]; and commandline -rb $fzf_last_select
~~~

Use `-l` flag on `read` to limit env to local scope, `-x` to inherit it to spawned child processes.
Further, if you want to use multi select via `fzf -m` pipe it to the new `string join " "` function in the current `HEAD`.

**Comment by danielb2** [comment]
Any progress on this?

**Comment by ridiculousfish** [comment]
Nope, but thanks for reminding me

**Comment by PwnArt1st** [comment]
bump

**Comment by mong8se** [comment]
For what it's worth, at least on OS X, a work around for something like fish + fzf + an interactive editor is xargs -o.

`git ls-files | fzf | xargs -o vim`

**Comment by sassanh** [comment]
I know some bugs by their nature make developers forget them unconsciously, so I'm here to fight their nature.

**Comment by CrashyBang** [comment]
:+1:

**Comment by mnewt** [comment]
It seems `test -z` and `test -n` both return zero when a subshell prints a blank string. Is this the same bug, or is something different going on here?

```fish
> uname -a
Linux mc 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux
> fish -v
fish, version 2.3.0
> set -l t (printf "")
> test -z "$t"; echo $status
0
> test -n "$t"; echo $status
1
> test -z (printf ""); echo $status
0
> test -n (printf ""); echo $status
0
> test -n (printf "What?"); echo $status
0
> test -z (printf "What?"); echo $status
1
```

**Comment by faho** [comment]
@mnewt: That's #2037, something completely different.

The gist of it is that our `test` follows POSIX (one of the few parts of fish to do so), and it specifies that if test receives one argument, it should check if that argument is empty. And in this case, test receives one argument, since no output from a command substitution (it's not really a "subshell" as such) expands to no argument. So test checks if `-z` is the empty string - and it isn't. In other words, POSIX defines `test -z` to return true.

**Comment by layus** [comment]
I have the same issue with sudo. `sudo netstat -tnpa | grep sshd` hangs forever, and leaks a process when killed, as can be seen when I logout:

```
$ ssh sto-lat
Last login: Mon Oct 17 13:08:25 2016 from 130.104.228.22
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish

layus@sto-lat ~  $ sudo netstat -tnpa | grep sshd
# hangs forever, kill with ^C
'sudo netstat -tnpa | grep sshd' has stopped

layus@sto-lat ~  $ sudo echo lol
[sudo] password for layus: 
lol

layus@sto-lat ~  $ sudo netstat -tnpa | grep sshd
tcp        0      0 0.0.0.0:3248            0.0.0.0:*               LISTEN      768/sshd            
... # works fine.

layus@sto-lat ~  $ # type ^D (logout)
There are stopped jobs. A second attempt to exit will enforce their termination.

layus@sto-lat ~  $ # type ^D (logout)
Connection to 37.59.63.147 closed.
```

This means that you cannot pipe the output of a sudo command. This may be a more comman use case than fzf.

**Comment by alphapapa** [comment]
Ah, I keep running into this and wondering what I'm doing wrong, because I forget about this bug...  :)

**Comment by tbodt** [comment]
@ridiculousfish Any more progress on this since March?

**Comment by ridiculousfish** [comment]
No, I haven't done any work on this. I guess the first step would be to answer the question of, what should fish do if a command substitution stops instead of exits?

**Comment by JoshCheek** [comment]
Not 100% sure I understand (and my prev gif seems like its wrong to me right now)

This is what I think you're saying is happening:

* User enters the command `$ a (b)`
* A process group is created
* B a new process is made to run `b`
  * Its in the new process group
  * Its standard input is the shell's standard input
  * It runs in the background
* `b` tries to read from standard input
* `b` is put to sleep (by the OS) because it's not in the foreground (active?) process group (this is because the process itself is in the background?)
* Fish sees `b` went to sleep
* Fish continues as if `b` had exited successfully and printed nothing, invoking `a ""`
* The world forgets about poor old `b`... well, except for those of us in this thread

If that's correct, then these are potential solutions? (note that they handle this case, which is probably the common case, but they don't address the general case of a command substitution stopping)

* Give it an empty stream for standard input (looking at `fzf`, this is probably the wrong answer.)
* Run command substitutions in the foreground (what does that mean, why aren't they run in it currently? I'm guessing separate process groups are used so we can kill it and all its children if we need? If so, do w actually need that? If so, do is there a way to get both? I don't know a lot about process management)
* Somehow ferry stdin to the process? eg if fish's stdin is a tty then run `b` through a pty, using `select` to or something similar to detect when its trying to pull from stdin, pulling from the real stdin in fish, and printing it to the `b`'s stdin (seems fragile, but who knows)

**Comment by ridiculousfish** [comment]
This is really a UI question - what ought fish to do if a command substitution stops without exiting?

Realistically I think we have three options:

1. Wait forever
2. kill the process
3. orphan the process

It looks like bash and zsh use option 1.

**Comment by ninjaaron** [comment]
seems like a fairly acceptable 90% solution.

**Comment by maletor** [comment]
+1 wait forever.

Like with this issue.

Just kidding.

**Comment by JoshCheek** [comment]
@maletor that probably was intended to be funny, but it comes off as condescending, maybe enjoy the laugh without sharing next time :)

**Comment by JoshCheek** [comment]
I hit this issue again both yesterday and today. I didn't reread the thread, the last comment makes it look like this might be a known deficiency. After some debugging, I was able to identify that the issue occurs when I pipe `bash -i` into a function. SS included to make it easier to read, source included to make it easier to reproduce.

![screen shot 2018-04-18 at 4 04 39 pm](https://user-images.githubusercontent.com/77495/38958480-02aa18e0-4323-11e8-8bdd-59f8d09b0b64.png)


```sh
# ===== Demo the issue =====

# hangs (I'll press C-c)
$ bash -i -c 'echo hello >&2' | grep whatever
Job 3, '$ bash -i -c 'echo hello >&2' |…' has stopped

# works (use the command instead of the function)
$ bash -i -c 'echo hello >&2' | command grep whatever
hello

# works (remove the -i flag)
$ bash -c 'echo hello >&2' | grep whatever
hello


# ===== Other potentially useful info =====

# the grep function
$ type grep
grep is a function with definition
function grep
    command grep --color=auto $argv
end

# the fish version
$ fish --version
fish, version 2.7.1

# this is as up-to-date as is installable
$ brew upgrade fish
Error: fish 2.7.1 already installed
```

**Comment by JoshCheek** [comment]
Oh. One other maybe relevant thing: I pressed C-c, but it really stopped the process. `ps` shows a "T" (I assume this is SIGSTOP) both before and after I press C-c. After I `fg`, it prints "hello" and exits normally.

This kind of implies to me that it could be a different issue (b/c it resumes when I foreground it, but the the original had to be SIGKILLed, I believe). Let me know if you want me to post this as its own issue.

**Comment by faho** [comment]
>This kind of implies to me that it could be a different issue

Very much a different issue - this one is explicitly about _command substitutions_ - `echo (this stuff)`.

The problem with `bash -i` seems to be that it grabs the terminal for itself - `strace -e ioctl` shows it doing one with TIOCSPGRP - which is the underlying syscall for `tcsetpgrp` on linux.

**Comment by JoshCheek** [comment]
> Very much a different issue - this one is explicitly about _command substitutions_ - `echo (this stuff)`.

Okay, made a new issue for it [here](https://github.com/fish-shell/fish-shell/issues/4929)
