### ISSUE TITLE
Completions for systemctl --user

### ISSUE THREAD

**Issue by Stebalien** [fish-shell/fish-shell#1393]
Currently, the systemctl completions work great for system instance completions but not at all for user instance completions. It would be kind of nice if fish could detect the `--user` flag and complete user instance units when applicable.

**Comment by faho** [comment]
For those who don't know systemctl:

In current git, systemctl.fish uses `systemctl list-unit-files` to gather completions. This is completely user-mode aware, so all that needs to be done is to add "--user" if it has been specified on the commandline.

I've gotten that part working with code like

```
if __fish_contains_opt user
set USERMODE "--user"
end
systemctl $USERMODE list-unit-files --no-legend --type=path ^/dev/null | cut -f 1 -d ' '
```

in `__fish_systemctl_*`, though it doesn't work if one specifies `systemctl --user $COMMAND` instead of `systemctl $COMMAND --user`.

**Comment by faho** [comment]
As far as I'm concerned, this is fixed and should be closed.

**Comment by Stebalien** [comment]
Good point.
