### ISSUE TITLE
Trouble setting cursor shape using fish_bind_mode

### ISSUE THREAD

**Issue by danielmatz** [fish-shell/fish-shell#1403]
I'm trying to write my own function for setting the cursor shape based on fish_bind_mode.  This is what I have:

```
function fish_vi_cursor --on-variable fish_bind_mode
    switch $fish_bind_mode
        case insert
            printf '\e]50;CursorShape=1\x7'
        case default
            printf '\e]50;CursorShape=0\x7'
        case "*"
            printf '\e]50;CursorShape=0\x7'
    end
end
```

This does change the cursor shape, but it also seems to cause the command line to be reprinted every time I press a key.

Any thoughts?

I'm on Mac OS X.  I use iTerm2.

**Comment by lowfatcomputing** [comment]
`fish_vi_cursor` was also not working in my terminal, rxvt-unicode-256color.

As a workaround I added `set XTERM_LOCALE` before `fish_vi_mode` in my `~/.config/fish/config.fish`.

**Comment by knubie** [comment]
This happened to me as well. The simplest reproduction would be:
```fish
# config.fish

function fish_vi_cursor_handle --on-variable fish_bind_mode
  echo -en "\e[2 q"
end

function fish_prompt
  echo '-'
  echo ">"
end
```
where `-` is printed on every keypress.

**Comment by faho** [comment]
The line duplication is #1388. I'll add the iterm stuff after merging #2476.

**Comment by sassanh** [comment]
@faho What about the ITerm stuff? it's not there.

**Comment by faho** [comment]
@sassanh: Yes it is (https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_vi_cursor.fish#L10):

```fish
            if set -q KONSOLE_PROFILE_NAME
               or set -q ITERM_PROFILE
                set function __fish_cursor_konsole
```

iTerm just uses the same sequences as konsole, so we don't need another function.

**Comment by sassanh** [comment]
OK, by investigating this I found 2 issues with current implementation.
1. function `fish_vi_cursor_handle` defined in `fish_vi_cursor` assumes that variables such as `fish_cursor_insert` are defined (it should have value "line" for example). But I didn't find any file in /share/ that defines these cursor shapes, so it always falls back to `$fish_cursor_unknown` which is set to "block".
2. Even though it's defined in a way that i should run only when `$fish_bind_mode` is changed, it runs on every keystroke, I guess the problem here is

**Comment by sassanh** [comment]
OK, by investigating this I found 2 issues with current implementation.
1. function `fish_vi_cursor_handle` defined in `fish_vi_cursor` assumes that variables such as `fish_cursor_insert` are defined (it should have value "line" for example). But I didn't find any file in /share/ that defines these cursor shapes, so it always falls back to `$fish_cursor_unknown` which is set to "block".
2. Even though it's defined in a way that i should run only when `$fish_bind_mode` is changed, it runs on every keystroke, I guess the problem here is a bug in `--on-variable`. It makes fish really slow.

This is how I implemented this when I thought you didn't merge ITerm stuff.

```
function set_mode_pre_execution --on-event fish_preexec
    set command (expr $argv : '\([^ ]*\).*')
    set -g __last_fish_bind_mode $fish_bind_mode
    if test $command = 'node'
        or echo $command | grep 'python' >/dev/null ^/dev/null
    else
        printf '\e]50;CursorShape=0\x7'
    end
end
function set_mode_post_execution --on-event fish_postexec
    set temp $__last_fish_bind_mode
    set -e __last_fish_bind_mode
    set -g fish_bind_mode $temp
    fish_vi_cursor
end
function fish_vi_cursor2 --on-variable fish_bind_mode
    if set -q __last_fish_bind_mode
        and test $__last_fish_bind_mode = $fish_bind_mode
        return
    end
    set -g __last_fish_bind_mode $fish_bind_mode
    switch $fish_bind_mode
        case insert
            printf '\e]50;CursorShape=1\x7'
        case default
            printf '\e]50;CursorShape=0\x7'
        case "*"
            printf '\e]50;CursorShape=0\x7'
    end
end
```

the above implementation takes care of another issue which is when for example you run `vim` or `htop` or `mc` and cursor shape is "line" it should change to "block". Generally the above implementation changes shape to "block" before executing a command and changes back to its previous state when the command finishes except for an incomplete list of programs which are in insert mode by default (like Node and Python).

**Comment by faho** [comment]
@sassanh: See #3215 and #3216.

**Comment by sassanh** [comment]
@faho thanks. I don't know if you want to handle the case when user runs `vim`, `mc` or `htop` for example when he's in insert mode. It'd give much better experience to user if fish sets the cursor to block shape and revert it to its last shape when program exits. Running vim and seeing a line shape cursor (because fish already set it for itself) is not nice. Let me know if I should create an issue for it.

**Comment by faho** [comment]
>It'd give much better experience to user if fish sets the cursor to block shape and revert it to its last shape when program exits. Running vim and seeing a line shape cursor (because fish already set it for itself) is not nice. Let me know if I should create an issue for it.

Yes, it would. Please open an issue for it. If you like, you can also submit a PR.

**Comment by maxim-lian** [comment]
@sassanh [this](https://github.com/fish-shell/fish-shell/issues/1403#issuecomment-231510269) approach worked very well for me, thank you!

(let me know if this is still the recommended way; I couldn't get the cursor to change without adding that, including adding [these lines](https://github.com/fish-shell/fish-shell/issues/1403#issuecomment-41794863))

**Comment by sassanh** [comment]
I'm out of context as it's an old issue, currently the relevant lines for handling cursor shape in my `config.fish` are these:
```
function set_mode_pre_execution --on-event fish_preexec
    set command (expr $argv : '\([^ ]*\).*')
    set -g __last_fish_bind_mode $fish_bind_mode
    if test $command = 'node'
        or test $command = 'nesh'
        or test $command = 'bash'
        or test $command = 'funced'
        or echo $command | grep 'python' >/dev/null ^/dev/null
        set -g fish_bind_mode insert
    else
        set -g fish_bind_mode default
    end
    fish_vi_cursor
end
function set_mode_post_execution --on-event fish_postexec
    set temp $__last_fish_bind_mode
    set -e __last_fish_bind_mode
    set -g fish_bind_mode $temp
    fish_vi_cursor
end
set -x fish_cursor_default block
set -x fish_cursor_visual block
set -x fish_cursor_insert line
set -x fish_cursor_replace_one underscore
```

**Comment by maxim-lian** [comment]
Thanks! 

FYI mine doesn't work without this function, from your post above (i'm using iTerm2): 

```
function fish_vi_cursor --on-variable fish_bind_mode
    if set -q __last_fish_bind_mode
        and test $__last_fish_bind_mode = $fish_bind_mode
        return
    end
    set -g __last_fish_bind_mode $fish_bind_mode
    switch $fish_bind_mode
        case insert
            printf '\e]50;CursorShape=1\x7'
        case default
            printf '\e]50;CursorShape=0\x7'
        case "*"
            printf '\e]50;CursorShape=0\x7'
    end
end
```

**Comment by sassanh** [comment]
Currently I'm using Konsole, but i'm sure I've been using above snippet without that function for few months in iTerm, I don''t remember what happened (or what did I do) that it started working with default `fish_vi_cursor`.

**Comment by mredaelli** [comment]
Sorry to dig out this old issue, but I'm unable ot change the cursor in vim mode using [Kitty](https://sw.kovidgoyal.net/kitty/).

**Comment by faho** [comment]
>Sorry to dig out this old issue

The correct thing to do there would be to open a new issue.

Anyway, 7d2eb9649cfe345aa9ed204aad0d6f8de85f9a9c already added support for Kitty, so you'll want to wait for the next release. You might also be able to use a new copy of [fish_vi_cursor.fish](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_vi_cursor.fish) - drop it in ~/.config/fish/functions. It's not guaranteed tho, as our functions sometimes use features that'll only appear in the next release.

**Comment by mredaelli** [comment]
> Anyway, [7d2eb96](https://github.com/fish-shell/fish-shell/commit/7d2eb9649cfe345aa9ed204aad0d6f8de85f9a9c) already added support for Kitty, so you'll want to wait for the next release. 

Fantastic! Thank you very much
