### ISSUE TITLE
Poison status variable when entering `if` block.

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1428]
oh-my-fish project has the following code in http://git.io/o_hDOA.

```sh
  if test -d $argv[1]; and not contains $argv[1] $$path
    set $path $argv[1] $$path
  end
```

However, this does something completely unexpected by original writer of the code (possibly expecting that it will work like bash). In my opinion, this should be simply disallowed, and probably the easiest way to do so is poisoning `$status` (so reads would make an error, until the variable will be written to again) when entering conditional block.

Because some prompts may show status, the variable should be unpoisoned when leaving `if` block (to not make issues when the body of function is composed entirely of `set` commands, for example).

**Comment by faho** [comment]
>if foo
    and bar
    echo "this is confusing"
end

That and is completely redundant, no? It only executes if the last command succeeded, but because you've entered the body of the if-block, it by definition always did! An `or` in the same place would be even worse since it couldn't possibly trigger.

Because of that I'm sure that nobody ever wanted to start the body of an if-block with `and` or `or`, so I'd be okay to special-case it to imply `begin; end`.

**Comment by ridiculousfish** [comment]
I think I'm going to tackle this.

Specifically the change is that a sequence of `and` and `or` statements at the top of a `while`, `if` or `else if` block will be treated as part of the condition:

    if test -d $argv[1]
       and test -f $argv[2]
        loop body
    end

fish_indent will do something to make it clear - not sure what yet, maybe by indenting these conditions one more level:

    if test -d $argv[1]
            and test -f $argv[2]
        loop body
    end

**Comment by faho** [comment]
>fish_indent will do something to make it clear - not sure what yet, maybe by indenting these conditions one more level:

Or keep them on the same line as the `if`:

```fish
if test -d $argv[1]; and test -f $argv[2]
    loop body
end
```

That seems to be what people do intuitively.

**Comment by ridiculousfish** [comment]
fish_indent tries not to join lines. Of course if they're on the same line already they'll stay that way, and yeah, good point that's what people will do for short commands..

**Comment by krader1961** [comment]
FWIW, I agree with @ridiculousfish that "a sequence of `and` and `or` statements at the top..." should be treated as part of the preceding condition. That is, there should be an implicit __begin__...__end__ around such a sequence based on the principal of least surprise to the user. The alternative, which I also think is acceptable, is to raise an error if a `and` or `or` is seen immediately after a `if`, `for`, `while`, etc. The question is which fish behavior will result in the fewest programming errors and user surprise. I am personally always wary of implicit behavior where something like the formatting of the code, as just one example, can cause confusion. But in this instance I think the implicit `begin`...`end` wrapping is reasonably clear and likely to result in fewer problems than the current behavior.

**Comment by jakwings** [comment]
I think we should make the role of the semicolon `;` more clear before adding special cases. As I see, the semicolon is used to replace a newline, other than this, it has no other special meanings. So the code should be:

```
if (test -d $argv[1]; and not contains $argv[1] $$path)
  set $path $argv[1] $$path
end
```
Use parentheses properly. Do I misunderstand the mechanism of `and` and `or`?

**Comment by krader1961** [comment]
> Do I misunderstand the mechanism of and and or?

I can't tell if you've misunderstood the point of __and__ and __or__ but you seem to have misunderstand the role of parenthesis in the fish shell. Where you have open and close parens there should be the keywords __begin__ and __end__. A parenthesized expression is broadly analogous to `$(some command)` in other shells. Also, while a semicolon is equivalent to a newline that has no bearing on this issue.

**Comment by jakwings** [comment]
@krader1961 Yes, I just thought of `begin; end`, and there is no problem if we use `begin; end` to quote the command:
```
if begin; test -d $argv[1]; and not contains $argv[1] $$path; end
  set $path $argv[1] $$path
end
```
equals to
```
if begin
  test -d $argv[1]; and not contains $argv[1] $$path
end
  set $path $argv[1] $$path
end
```

**Comment by jakwings** [comment]
If `and` and `or` are not really special, I don't see any big problems about the syntax, though `begin; end` looks cumbersome.

**Comment by krader1961** [comment]
@jakwings The question is whether or not we should require someone writing something like

```
if test -d $argv[1]; and not contains $argv[1] $$path
```

to explicitly surround that sequence of commands with __begin__ and __end__ or infer their presence. The former is unambiguous. The latter is potentially ambiguous but more user friendly. Is there in fact any ambiguity? If not then the answer to this question is clear: it should be done. If there is ambiguity then the question is whether the new behavior of wrapping the conditions in an implicit __begin__...__end__ block   results in more benefits than problems.

**Comment by jakwings** [comment]
@krader1961 Ok, it is a mindset problem. If that is required, as I think, it is the user not really understanding the simple role of the semicolon. I don't think it is ambiguous, because I'll never try to end the condition with a `;` that way, and because it is a end-marker of the condition in my eyes, even if there is an `and` right after it. I know it well that `begin` and `end` are the most useful tokens to divide multiple commands. Now imagine somebody just tell me `;` is a special token to connect `and/or` with other commands, what? Why not just introduce `&&` and `||` into fish (and many bash users will like them) instead of abusing the semicolon?

**Comment by ridiculousfish** [comment]
This is definitely not semicolon abuse. The thing to understand is that where other shells introduce special purpose syntax, fish uses plain old commands. For example, the set command replaces the special purpose syntax `foo=bar`. Likewise, the `and` and `or` commands replace the special purpose syntax `&&` and `||`.

Since `and` and `or` are just commands, they obey command rules, and we already know how to use them. Compare to `&&` and `||`, which have their own rules (for example, precedence) that we have to learn and remember.

That said, this proposal is basically to add some special behavior to `and` and `or` in the name of convenience, so it's arguably abusing something. The response is that it's replacing a nonsense construct, so it's not so bad.

**Comment by jakwings** [comment]
@ridiculousfish 
> This is **definitely** not semicolon abuse.
> ...
> That said, this proposal is basically to add some special behavior to and and or in the name of convenience, so it's **arguably** abusing something. The response is that it's replacing a nonsense construct, so it's not so bad.

So my regular mindset is **arguably** wrong?

> Compare to && and ||, which have their own rules (for example, precedence) that we have to learn and remember.

`if true; and false; or true` is not fun too!

> Likewise, the and and or commands replace the special purpose syntax && and ||.

Now we may have a new special purpose semicolon `;`.

**Comment by jakwings** [comment]
@ridiculousfish You are the leader, but please don't fool me. Although `&&` and `||` is not implemented in fish, I can write it either.

**Comment by jakwings** [comment]
@ridiculousfish You are the leader, but please don't fool me. Although `&&` and `||` is not implemented in fish, I **cannot** write it either.

**Comment by faho** [comment]
>Is there in fact any ambiguity?

@krader1961: There's no _real_ ambiguity. Yes, in theory one could write

```fish
if a
   and b
end
```

and want b to belong to the body of the conditional, but in that case the `and` is completely superfluous since the only way to reach it is to succeed check "a". An `or` would be even worse as that would _never_ be executed. For an `else` clause these would be reversed.

What I mean by that is that while it's currently possible to write this, it's absolute nonsense.

@jakwings:

Semicolons don't really matter here - I only brought them up for `fish_indent`, a purely cosmetic change. And even with special powers for `and` and `or`, semicolons remain purely cosmetic. They are nice for e.g. `set -l a; set -l b` or to quickly write something interactively, or to disable a function by defining an empty substitute, but they can always be replaced by newlines without any change in functionality.

**Comment by jakwings** [comment]
@faho This change in my mind is just making `;and` `;or` new and confusing keywords (only for `if` and `while`), not as elegant as `&& ||`. Both semicolon and `and/or` become more special, not just the semicolon. The official document has stated in the `if` section:

> In order to use the exit status of multiple commands as the condition of an if block, use `begin; ...; end` and the short circuit commands `and` and `or`.

It is also nice to write short commands `test COND; and SOMETHING` without using `if; end`. And the semicolon between `test` and `and` is not special. Someone may argue it looks like `test (COND; and SOMETHING)` in the future.

**Comment by faho** [comment]
>Both semicolon and and/or become more special, not just the semicolon

No - there'd be no semantic difference between

```fish
if a; and b
   # body
end
```

and

```fish
if a
  and b
  # body
end
```

**Comment by jakwings** [comment]
@faho Ok, let the documentation tell the implicit `begin; end` for those `and/or` conditions. I'm going to change my mindset now. Sorry for my rants (because of someone definitely).

**Comment by ridiculousfish** [comment]
This is implemented in 594b460ba2d8dca59a3bfd282397c5f33aa9da6f (the other commit had a bogus message). Thanks to everyone who participated in the discussion.

**Comment by cben** [comment]
Indentation is still misleading (just built from master):
```
$ if false
      or true
      echo Run.
  end
Run.
```
IMHO it should be at same level as if:
```
$ if false
   or true
      echo Run.
  end
Run.
```
Another sensible option is same as the first condition — but the distinction is barely visible (with `if `, would be better with `while `):
```
$ if false
     or true
      echo Run.
  end
Run.
```

**Comment by ridiculousfish** [comment]
Let's track that in a separate issue. I filed #2646 to discuss indentation improvements.

**Comment by jakwings** [comment]
Maybe I ask a question?

Are `and` and `or` keywords, so there are actually two commands in this script?

```fish
false; and true

false
and true
```

**Comment by ridiculousfish** [comment]
`and` and `or` are keywords, yes. They short circuit so that `true; or foo` will not execute `foo`, and similarly with `false; or foo`.

**Comment by jakwings** [comment]
@ridiculousfish Thanks. Then if fish ever has a strict mode (exit once a error happens), `false; or true` won't exit fish?

**Comment by ridiculousfish** [comment]
Correct, `false; or true` won't die in any reasonable strict mode

**Comment by jakwings** [comment]
@ridiculousfish Oh yeah, I understand now. also find that #805 already has a more detailed and interesting discussion.

**Comment by andrex-e-schulman** [comment]
The documentation doesn't seem to have been updated yet to show this. The staging documentation for the [if command](http://fishshell.com/staging/docs/current/commands.html#if) still says:

> In order to use the exit status of multiple commands as the condition of an if block, use ```begin; ...; end``` and the short circuit commands ```and``` and ```or```.

**Comment by ridiculousfish** [comment]
Good catch, I'll update it.

**Comment by ridiculousfish** [comment]
Docs updated as 30ea7cc3f8a5d56ad30dc749ea374363c15f312a
