### ISSUE TITLE
Using Fish as logon shell in Cygwin gives errors

### ISSUE THREAD

**Issue by DanNixon** [fish-shell/fish-shell#1478]
When I configure fish to be my logon shell by adding ```/bin/fish``` to my ```/etc/shells``` and changing the ```/etc/passwd``` file I get around 2500 lines of errors when fish is loaded (an example [here](http://pastebin.com/E3ZW8P8C)).
If I launch fish via another shell (i.e. using bash as the login shell) it seems to work fine.
I am using the up to date version from the Cygwin installer.

**Comment by andrex-e-schulman** [comment]
I'm the current maintainer of fish for Cygwin, and AFAIK fish works just fine there now as a login shell.  Errors that used to happen at start have been fixed by making some adjustments to /etc/fish/config.fish.

So unless the OP verifies that this is still a problem for him using fish from the Cygwin repository, I think this bug should be closed.

**Comment by DanNixon** [comment]
I just gave this a try and have the same issues as before, but interestingly enough if I remove my config files it seems to work OK (apart from taking longer to get to the prompt than it should).

I'm not sure what the issue is for me, and I don't actually use Windows enough to try to fix whatever is causing the issue for me.
