### ISSUE TITLE
Validate arguments to rm command

### ISSUE THREAD

**Issue by siteshwar** [fish-shell/fish-shell#1511]
Arguments to rm command should be validated to avoid accidentally deleting important  files. Commands like :

```
rm -rf *
```

should be confirmed from the user. 

On GNU systems we can pass `-I` parameter to rm command to get confirmation from user before deleting more than 3 files.

**Comment by nakal** [comment]
tcsh does this, too. The feature is called `rmstar` there and prevents users from destroy data when accidentally space was pressed at a wrong time. Sometimes you see that you typed something like: `rm * .jpg`

**Comment by krader1961** [comment]
Please note that shells like zsh and tcsh provide very limited protection against this user error. If, for example, you rename your __rm__ binary then they won't protect you. For example, both shells will happily let you remove all files if you do something like this:

```
$ cp /bin/rm ~/myrm
$ ~/myrm *
``` 

I agree with @ithinkihaveacat: This shouldn't be handled by fish. Anyone using a CLI like fish should be presumed to know they're playing with fire. About the only thing we might do is document a function that counts non option arguments and prompts the user to answer in the affirmative if they want to proceed. Such a function could be readily adapted (by simply changing its name) to any dangerous command.

**Comment by anordal** [comment]
> there would need to be a difference between the command used with globbing and with regular filenames. I absolutely don't want to have to confirm every time I use it if I already made the effort to enter the complete filenames.
> And I'm not even sure this is the shell's job in fact.

That's the question. If so, the shell would have to do it. If anybody feels inspired to alter the glob behaviour when the command's name is "rm", commit 62b76b26b4a8afc6987b65f0ad02a18dee093f2e does something similar.

That said, I'm not sold on the justification for this hacky solution. I think the real problem is that rm is so damn unforgivable. How about:
* File managers offer a "move to trash" option. Why shouldn't rm?
* Some package managers (e.g. zypper) make a btrfs snapshot before and after the transaction. Why shouldn't rm? Or at least offer it as an option.
* Like Gmail's "unsend" function, which works by postponing the actual action a few seconds to let you think about it, I've thought that rm could for example spawn a process that keeps the file open for a few seconds just in case you want to run `rm --oh-shit-not-that-one important.txt` for example.

These things are possible by wrapping the rm command.

**Comment by krader1961** [comment]
Someone just asked about this on [StackExchange](http://stackoverflow.com/questions/35806519/check-for-wildcard-in-fish-shell-arguments). In addition to the examples in my previous comment note that zsh won't protect you if you use a full path to the command; i.e., zsh will happily let you execute `/bin/rm *` without confirmation. And, as I pointed out earlier, they do nothing to protect you against executing any other "dangerous" command you might not want to invoke with a `*` wildcard.

If you want this type of protection it is trivial to implement in one of two ways. First, simply do `abbr rm /bin/rm -I` if you're happy with the three file threshold. If you want a higher threshold use a function:

```fish
function rm
    set -l threshold 5
    if test (count $argv) -gt $threshold
        echo Do you want to delete (count $argv) files'? [yn] '
        read -l -n1 ans
        string match -qi y -- $ans; or return 0
    end
    command rm $argv
end
```

**Comment by krader1961** [comment]
I'm strongly inclined to reject this request.  Is there anyone who believes that fish should support this natively? If so I'd ask for an outline of a solution that isn't a stupid, easily fooled, hack like zsh and bash employ. For example, should there be a mechanism, perhaps involving the `commandline` builtin, by which a function could determine whether globs (not just `*`) were present in the original statement. Or should the `function` command have a new option that registers its interest in being passed the raw globs without expansion? It could then use the hypothetical `glob` command being discussed in another issue to explicitly expand them.

**Comment by GregDMeyer** [comment]
I was the one who asked the question on StackExchange. It seems to me that the best solution, which is general and useful for all kinds of stuff aside from this specific instance, would be to add a new option to the `function` command which causes globs to be passed raw to the function instead of being expanded (as you mentioned). That would open a whole lot of interesting possibilities for neat functions, not just protecting against `rm` typos.

**Comment by mwm** [comment]
The ability to access the unexpanded arguments is generally useful, akin to call-by-name in programming languages, or macros in LISP.

There should be no need to "fool" this kind of facility. It should be something that users who don't want it can easily turn off. A function is easy to turn off, even if they can't overwrite the function: "alias rm 'command rm'; funcsave rm" will do it. If you tried to force this on users, a few might appreciate it, but it would do little more than annoy others, turning into another stupid prompt that just gets ignored.

Giving users who want this ability to create it is another thing entirely.

**Comment by krader1961** [comment]
I'm closing this because it isn't the shell's responsibility and there isn't any way to do so that doesn't have more holes than a block of swiss cheese.
