### ISSUE TITLE
fish crashes while dragging/resizing iterm window

### ISSUE THREAD

**Issue by databus23** [fish-shell/fish-shell#1529]
Hi,

I can't really reproduce at will, but I have fish crashing regularly (2-3 times day) when fiddling with the item2 windows fish is running in.

The crash.log always yields the same stacktrace:
https://gist.github.com/databus23/e4929064b6fbe65b9a59

I'm using fish 2.1.0 on mavericks 10.9.4 with iterm2 

Cheers,
Fabian

**Comment by 0rax** [comment]
Hi, 

I have exactly the same problem (currently using fish version 2.1.1) but it seems to occurs differently based on the terminal used.
Evilvte will crash nearly instantly but sakura will take like 30 seconde before crashing.
```
fish: Job 1, “fish ^ ~/fish.log ” terminated by signal SIGABRT (Abort)
$ cat ~/fish.log
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

I just noticed @databus23 that you have an arrow `➜` in your prompt which is an UTF8 char. I am currently using my own prompt ([fishline](http://github.com/0rax/fishline)) which is a port of powerline-shell in fish and I use a lot of UTF8 special char. I might be the reason.

PS: another fishline user reported this issue on the project page, he is currently using rxvt-unicode.

**Comment by Fryie** [comment]
I can reproduce this issue on Mac OS X Yosemite with iTerm2. I also have a Linux machine at home where I use Gnome Terminal, and I never encountered the problem there - settings are exactly the same.

**Comment by siteshwar** [comment]
It should be crashing here https://github.com/fish-shell/fish-shell/blob/3c5d5b344ee945b99e4bb16a44af6f293601813d/builtin.cpp#L3068

Here is the sample code that invokes copy constructor for temporary object https://gist.github.com/siteshwar/b7e522d31274f4ed72f7

**Comment by ridiculousfish** [comment]
I can reproduce on 2.1.2 but not master. Bisecting yields d1feb9bcbf141e2195f37a8ab0f526c24a533cda as the fix, which makes perfect sense: the crash is in copying a bogus `io_chain` and that fix cleaned up a dangling pointer to an `io_chain`. 

It's easy to see what happened - something calls `source` twice, and the first one `source`s something else. The second `source` will then see a dangling `real_io` and is likely to crash. fish 1.x looks like it was vulnerable to the same thing. 

Closing as fixed in master. Thanks for the great tips that enabled me to reproduce this!
