### ISSUE TITLE
alt+left should move up the directory stack if there is no directory history

### ISSUE THREAD

**Issue by asantosca** [fish-shell/fish-shell#1532]
Using OS X 10.9.3 MacBook Pro.

If I define anything on my fish_prompt then the alt+left stops working. The message "Hit end of history..." is displayed, but pwd show that I am still on the same location.

I installed fish via the git clone instructions. No errors while following the instructions or while running fish.

BTW. Great product. Really enjoying using it.

**Comment by faho** [comment]
Okay, I'm rejecting this.

The reason being that 1. nobody has thought to work on int in 6 years and 2. it's awkward. If you did `prevd; or cd ..`, then *one* alt-left before any `cd` would move up, and from then on it would always prevd.

I don't see any good logic for making this work, so unless we want to change the defaults to use `cd ..` instead of prevd (this wouldn't be awful!), there's nothing left to do here.
