### ISSUE TITLE
enhance wildcard syntax to support matching hidden files (those beginning with a period)

### ISSUE THREAD

**Issue by mamiu** [fish-shell/fish-shell#1568]
See problem described here:
http://stackoverflow.com/questions/24841723/how-to-use-recursive-wildcards-in-fish-shell-for-dotfiles-and-folders

**Comment by faho** [comment]
So, to get the actual information on here and save people an extra click:

The issue is that recursive wildcards (or "globs") never match "hidden" files, i.e. `ls -a **.txt` never matches "subfolder/.haddock.txt".

The solution is to explicitly match dotfiles, like

    ls **/.*.txt **.txt

however, this means that you'd _also_ need to explicitly match dotfiles in the current directory, like

    ls **/.*.txt **.txt .*.txt

This should test it nicely:

    mkdir sub
    touch .flounder.txt halibut.txt sub/haddock.txt sub/.hagfish.txt
    ls **.txt # will print all non-hidden files
    ls .*.txt # will print .flounder.txt
    ls **.*.txt # won't match
    ls **/.*.txt # will only match sub/.hagfish.txt
    ls **.txt **/.*.txt .*.txt # will match all of them

(Also, I have now decided all examples should be fish)

**Comment by mamiu** [comment]
@faho:
Thanks for your detailed information and tests!

@ridiculousfish:
What do you think about the following approach?

**One** asterisk to get all non-hidden files and folders from the current directory:  

        ls *

**Two** asterisks to get all non-hidden files and folders recursively:

        ls **

**Three** asterisks to get all files and folders recursively, including hidden ones:

        ls ***

(These examples use `ls`, but naturally it should work with all commands.)

**Comment by faho** [comment]
It's important to note that all of this clashes with the existing documentation. [That says](http://fishshell.com/docs/current/index.html#expand):

>** matches any string of characters. This includes matching an empty string. The string may include the / character but does not need to.

There's no mention of hidden files being excluded. So the question is if it should do that, and for that the root question is "is it valuable to do something to just non-hidden files", and I'd argue it is.

Then the question becomes how to do something to hidden files, so you can nicely do something to both by specifying both.

Since I don't want to have new syntax for just that very special case, I'd like to see if the existing syntax can be adapted, and the most likely candidates for that are `**.*` and `**/.*`. 

If `**.*` would be changed to only match hidden files/folders recursively (i.e. in the current directory and all subdirectories) the meaning of "**" would need to be changed, since, if it matches any string, it would also match "fish/flounder" which means `**.*` would also match "fish/flounder.txt".

`**/.*` on the other hand, would only need to match "./.flounder.txt" for it to now work with all my examples, and "**" matching "." is completely in line with the documentation and IMHO also logical.

So, **TL;DR**: Make "**/.*" match all _hidden_ files and folders recursively (including current dir).

**Comment by ridiculousfish** [comment]
It seems like `.?**` ought to work.

**Comment by faho** [comment]
Why? That's "a dot, then something that's not a "/" and then maybe something else, including a "/"" or in regexp `\\.[^/].*`. That matches everything in hidden directories and all the hidden files in the current directory:

    mkdir .fish
    touch .fish/halibut .flounder catfish
    echo .?**

> .fish/halibut .flounder

**Comment by strannik19** [comment]
so far this is the most confusing thing for me with fish. if wildcards are supposed to be simple, why is it that rm ./* doesn't simply return all files in the current directory? not returning a subset of files in my directory is not expected and definitely not simple, as I need to figure out new ways to delete everything in current directory.

**Comment by braham-snyder** [comment]
@strannik19 I might agree with you to some extent, but I think backwards- and bash-compatibility mean that changing that wouldn't be a good idea (not that I'm an authority on the issue). Regardless, this helps: `rm {.,}*`.

(For the recursive case, something like `{**/,}{,.}*.txt` might or might not work, but of course even if it does it's too clumsy).

<br>

Also, it's probably worth noting that the stackoverflow question linked in the OP has been viewed over one thousand times as of today — I think an enhanced syntax here could improve fish quite a bit.

<br>

>>  It seems like `.?**` ought to work.
>
> Why? That's "a dot, then something that's not a "/" and then maybe something else, including a "/"" or in regexp `\\.[^/].*`. That matches everything in hidden directories and all the hidden files in the current directory.

He may have been alluding to how `?` works in regexps.

**Comment by strannik19** [comment]
it would def improve fish, just because its really counterintuitive that * doesn't match everything, hence the people going to stackoverflow.  plus there are other threads on SO around the same topic.
{.,}* is the best option really when you need to get everything at the moment, but it does feel very hacky (and slightly awkward to type :-) )

**Comment by Nnarol** [comment]
@strannik19 Changing the behavior of `*` compared to other shells would not make sense in my opinion. If `*` matched files starting with a dot, the whole concept of hidden files would be thrown out the window.
Probably the only thing to still respect the convention would be `ls`, and that's it.

`{.,}` is indeed hackish, because it is not globbing, but a shell expansion that happens before it (at least in Bash), and generates two globbing patterns using the preamble and postfix.
However, Bash's extended globbing syntax does accommodate this use case:  `?(<pattern>)`, which is the same as `<atomic_pattern>?` in regex.
E.g.: `echo ~/?(.)*` would print all hidden and non-hidden files in your home directory.
I do not know whether fish supports this extended globbing scheme, but if it does, this is pretty straightforward to do.

**Comment by cjbassi** [comment]
It seems like there are some people (including me) who would prefer to have dotfiles globbed by default so I think a configuration option would work nicely in this case. In Zsh, `setopt globdots` enables dotfiles to be globbed with `*`. Would adding that configuration option to fish be allowed?

**Comment by faho** [comment]
>Would adding that configuration option to fish be allowed?

It would not, as it would be quite against fish's philosophy.

In essence, adding this configuration option makes things *worse*, because it now means if you have code that is affected by it you need to consider the option (e.g. if you share scripts you need to make sure the option is the value you expect), instead of just writing things one way, always.

**Comment by xiruizhao** [comment]
> (If you start with a dot, then it will suggest hidden directories.)

@ridiculousfish in https://github.com/fish-shell/fish-shell/issues/88#issuecomment-6260396

1. But many dot files today are configuration files and there is no intention to hide them.
2. POSIX does not mention "hidden" files. They are called `filenames beginning with a <period> ('.')` (IEEE Std 1003.1TM-2017 p.2383)
3. `ls` does not mention "hidden" files. They are called  `entries starting with .`(https://www.man7.org/linux/man-pages/man1/ls.1.html)

I'm fine with globbing/pattern matching staying POSIX compliant. But if fish is a "friendly interactive shell", it should allow interactive tab completion of dot files, which is unspecified by POSIX.

**Comment by faho** [comment]
> So, TL;DR: Make **/.* match all hidden files and folders recursively (including current dir).

This now works, presumably after #7222

**Comment by yochem** [comment]
Sorry to comment on a closed issue, but I've been trying to match both `.test` and `test`, but I can't seem to get it to work. Is this currently possible with globbing? and if so, how?

context:
I want to automatically activate Python venvs, basically:
```fish
source */bin/activate.fish # this doesn't work if venv name (top level folder) starts with a period
```
I also can't do:
```fish
source */bin/activate.fish >/dev/null 2>&1
source .*/bin/activate.fish >/dev/null 2>&1
```
Because that still gives:
```
fish: No matches for wildcard '*/bin/activate.fish'. See `help wildcards-globbing`.
source */bin/activate.fish >/dev/null 2>&1
```

**Comment by faho** [comment]
@yochem The reason this fails for you is because one of the globs doesn't match, and so fish errors out instead of running something that might be nonsensical (think `ls *.foo` - if that didn't match, it would run `ls` and print your entire current directory).

So, the way to do this is what [the docs tell you](https://fishshell.com/docs/current/language.html#wildcards-globbing): Save it in a variable and check it.

```fish
set -l activate {.,}*/bin/activate.fish
set -q activate[1]
and source $activate[1]
```

Which also neatly sidesteps a problem in your original code if more than one file matches (if you do `source foo bar`, that reads the file "foo" with $argv set to "bar").

**Comment by yochem** [comment]
Awesome, thank you very much for your detailed explanation and solution! :)

**Comment by yump** [comment]
> > So, TL;DR: Make *_/._ match all hidden files and folders recursively (including current dir).
> 
> This now works, presumably after #7222

What now works?

```fish
> mkdir -p . ./child ./child/.hiddendir ./child/.hiddendir/.hidden ./child/.hiddendir/vis ./.hiddendir ./.hiddendir/.hidden ./.hiddendir/visdir ./.hiddendir/visdir/.hidden ./.hidden
> find . -mindepth 1 | count
9
> printf "%s\n" **/.* | count
3
> fish --version
fish, version 3.6.4
```

To anyone else who got here by searching "wildcard hidden" in the issue tracker, use `(find . -mindepth 1)` and stop beating your head against this.  If the directory is large enough, you're likely to hit "Expansion produced too many results".  The standard solution is `find | while read`.
