### ISSUE TITLE
Any variable with zero elements in argument deletes entire argument (Cartesian Product)

### ISSUE THREAD

**Issue by kballard** [fish-shell/fish-shell#160]
When using unquoted variables in a single argument (e.g. `$a$b$c`), if any of the variables have zero elements (e.g. are uninitialized), the entire argument is deleted even though the rest of the argument may be valid. This holds true if there is non-variable text in the argument too, as in `{$a}bc`. This also holds true even if the variable has been declared, e.g. `set -l a`. Giving all variables an actual value, even if empty, causes the argument to start working again, as does quoting the variables.

**Comment by krader1961** [comment]
I not only do not find this behavior weird but is what I would expect given that fish treats all vars as lists of one or more elements. The problem that @alphapapa seems to be having in issue #2438 is he expects __fish__ to behave like __bash__.  I don't have any objection to adopting features from other shells that fit the __fish__ philosophy but the requested feature implicit in this issue is incompatible.

Some shells actually have an option you can set to cause use of undefined vars to throw an error. Zsh and ksh93 have such an option (e.g., `setopt -u` or `set -u`) as well as special syntax for substituting a value when an unset var is used. Consider zsh which has

```
${name=word}
${name:=word}
$name::=word}
```

which all do different things but look very similar. Gah! I feel pretty strongly that we should not change this behavior or add an option to allow configuring the behavior.  That way lies madness and bogosities like zsh. I prefer that __fish__ stick to the __Python__ maxim that there should be one and only one obvious way to perform a task.

**Comment by krader1961** [comment]
I read through issue #2438 again with an open mind since I too was perplexed by this behavior the first few days I used fish.

Several people pointed out in the other issue, quite rightly, that the current published (i.e., 2.2.0) documentation is woefully inadequate about explaining how lists work (both vars and command substitution). The 2.3.0 documentation which will be published real soon is much improved in this regard.

The current behavior has now been in place for many years. Changing the behavior could only be done in a major release. The arguments for making such a disruptive change are simply not compelling enough to warrant the effort or pain it would cause. The fish community will be better served by continuing to improve the documentation and adding sane limits to keep people from creating OOM conditions.
