### ISSUE TITLE
Proposed changes to syntax/semantics

### ISSUE THREAD

**Issue by kballard** [fish-shell/fish-shell#1656]
Here's a collection of some changes I'd like to make to the syntax and semantics of fishscript. These are intended to be backwards-compatible, as I believe that's important. If backwards compatibility were not a factor I'd propose much more radical changes.

The changes, in no particular order:

---
## Syntax for command substitution without splitting

Command substitution, e.g. `(cmd args)`, splits the output on newlines. The only way to avoid this is to set `IFS` to the empty string. I'd prefer to disable the `IFS` behavior here, but that's backwards-incompatible, so we'll leave it alone. But I want to add an easier way to disable newline splitting. In Bash, a common thing to do is something like `"$(cmd args)"`, which is a quoted command substitution. We could introduce the same syntax, `$(cmd args)`, inside of double-quoted strings, but I don't like the inconsistency. Instead, I'm proposing an empty slice syntax, e.g.

``` sh
> set -l foo (cat thefile.txt)[]
```

The trailing `[]` on the command substitution is a marker that disables splitting, just as if `IFS` was set to the empty string. Today, the `[]` suffix causes all the output to be discarded, because it's selecting 0 elements from the resulting array. This is not particularly useful.

This same syntax would also be valid on variables. `$foo[]` today evaluates to an empty array (as opposed to an empty string, which is still a valid argument; an empty array is removed from the argument list entirely). This is not useful. For consistency, this syntax change would see `$foo[]` as evaluating to an "un-split" variable, which is to say, it would evaluate to a space-separated variable just as `"$foo"` does, with one difference: if `$foo` is an empty array, `$foo[]` is still an empty array rather than an empty string. This is potentially useful behavior. It seems inconsistent with command substitution, but it's actually not, as command substitution can be thought of as emitting an empty string if the command prints nothing (and it only becomes an empty array after newline splitting).

Note that `$foo[$idx]` where `$idx` is an empty array is _not_ equivalent to `$foo[]`. `$foo[$idx]` would still behave as it does today, which is to select 0 elements from `$foo`. This would be true of command substitutions as well, except command substitutions don't currently support using variables in slicing syntax. This also applies to `$foo[(true)]` (which I'm surprised actually works). Basically, the presence of anything (besides whitespace) inside the `[]` does not invoke this new behavior, even if the slice index evaluates to an empty array/string.

---
## No more "Array index out of bounds" errors

Currently, indexing into an array with an out-of-bounds index yields an "Array out of bounds" error. The only exception is for indexing into an empty array; in Fish 2.1, any index is silently accepted, and in current Fish nightly, the index `1` (and `-1`) is silently accepted but other indexes are treated as out of bounds (i.e. empty arrays are treated as one-element arrays for the purpose of indexing).

I believe this is unnecessary. "Array index out of bounds" errors don't help anybody, they just cause scripts to misbehave. And they necessitate strange workarounds like

``` sh
# use extra empty args to ensure array indexing doesn't fail
set -l tmp (some command) '' ''
set first $tmp[1]
set second $tmp[2]
```

Instead, I think providing an out of bounds index should merely return an empty string. This would be the desired behavior in most cases, certainly better than a Fish error (that doesn't even set `$status`!). Slice ranges would work as expected; `$foo[1..3]` is identical to `$foo[1 2 3]`, and `$foo[2..-1]` properly collapses to an empty range if there are fewer than 2 elements in the array.

---
## More conservative behavior around colon-separated env vars

(note: following proposal is an alternative to this one)

When Fish exports a variable with multiple values to the environment, it colon-separates the values. This is reasonable behavior, as it needs to convert it to a single value somehow, and it works with e.g. `$PATH`, `$CDPATH`, `$CLASSPATH`, etc.

Similarly, when Fish reads its environment when it first starts up, it splits env vars on colons and produces arrays. This is correct for `$PATH` and `$CLASSPATH`, but is not necessarily correct for other variables. Interestingly, Fish hard-codes an exception to this for `$DISPLAY`.

My proposal is to stop blacklisting `$DISPLAY` and instead whitelist `$PATH`, `$CDPATH`, and `$CLASSPATH`, and don't implicitly split anything else. I'm open to suggestions for other env vars it makes sense to split this way, but I don't want this list to change on an ongoing basis, I want it to just change once. This is a backwards-incompatible change, but it's unlikely to affect much code.

The motivation here is that `:` is not necessarily splitting multiple paths, it's often used to e.g. separate a port from a domain in a URL.

Once we get better string manipulation (see #156), then manually splitting other env vars on colons should be pretty easy. Assuming we use a `string` builtin like my last comment on #156, that would look something like `set NODE_PATH (split : $NODE_PATH)`.
### Language-specific env vars?

I listed `$CLASSPATH` as something to split. This is because it's an env var that Java has defined for a very long time. Do we want to support env vars for other languages? I'm worried that this will essentially privilege those languages, and not any others that we don't support. Since I want this whitelist to be frozen (as subsequent changes have backwards-compatibility implications), that would mean new languages could never get the same env var support. Here's the env vars I can think of right now that should be considered:
- `$NODE_PATH`
- `$PYTHONPATH`
- `$GOPATH`

I'm sure there are others as well.

---
## Alternative: Use `$foo[]` syntax with colon-split env vars to restore colons

As an alternative to the previous proposal, we can maintain full backwards compatibility by declaring that variables may have an associated "separator char" that is used with the `$foo[]` syntax. This actually makes the `[]` suffix slightly more consistent with `(cmd args)[]`, by treating command substitution as having an implicit "separator char" of `\n`. By default, exported variables have a "separator char" of `':'` and all other variables use the space `' '`. This character will not be used with `"$foo"` syntax, but will be used when exporting array variables to the environment. Updating a variable to be exported will set the separator char to `':'` only if it hasn't already been explicitly set to anything else. A new flag `-c` will be provided to `set` to explicitly set the separator char. Setting it to the empty string will un-set it so it remains as the default (Fish will not support having an explicitly empty separator char). Setting it to a multi-character string is an error. No facility will be provided to test the separator char, as I don't believe that's useful and it would unnecessarily complicate `set`.

With this change, scripts can use `$FOO[]` if they expect `$FOO` to have been provided through the environment and want to see it in its "un-split" form.

**Comment by eldridgejm** [comment]
While I don't find the `"$(cmd)"` syntax to be horrible (it's at least familiar from bash), I think it introduces some inconsistencies. I'll explain why, and propose new syntax that I think has the potential to simplify the language.

Both command substitution `(cmd)` and variable expansion `$x` produce arrays.  Currently, the function of double-quoting `"$x"` is to join the elements of an array with a space. The proposed `"$(cmd)"` syntax for disabling command substitution splitting can be interpreted as amending the functionality of double quotes so that arrays resulting from command substitution are joined by newlines, while arrays resulting from variable expansion are joined by spaces.

The proposed changes would mean that the arrays are treated differently when wrapped in double quotes.  Concretely, suppose we write `set x 1 2 3`.  In any other situation, writing `$x` is equivalent to writing `(echo 1\n2\n3)`: both are expanded to arrays with three elements. But now writing `"$x"` results in the string `"1 2 3"`, while `"$(echo 1\n2\n3\n)"` results in the string `"1\n2\n3"`.

A second problem that exists with the current syntax is that double-quoting array variables causes them to be joined on spaces, which may not always be desirable. For example, suppose we have files with spaces named "file one" and "file two", and we write `set x *`.  Now we'd like to pass the names to some command as a single argument. Writing "$x" has the effect of joining the names into the single string `"file one file two"`, which is definitely not what we wanted.  It would've been better to join on a different character, perhaps `\0`.

In summary, command substitution splits the `stdout` of a command into an array on newlines, and `""` joins arrays with spaces. The problems above exist because there are many times when we'd prefer to split on something other than newlines and join on something other than spaces.

### Proposed syntax: command substitution and "" delimiters

I propose the following syntax: command substitution parens and double quotes can each be followed by an `@[delimeter]` which describes how the splitting/joining should take place.  For example, suppose we have a command that produces its output as a sequence of space-separated tokens, and we'd like to put it in an array. Then we can write:

    (cmd)@' '

to signify that the output of `cmd` should be split at spaces. This offers a nice way of creating an array literal: `(echo 1 2 3)@' '`.

If we want to disable splitting, we either leave the `@` bare, as in `(cmd)@`, or introduce some sort of keyword, like `(cmd)@None`. I'd propose that omitting the `@` entirely preserves the current behavior of splitting on newlines, and would be equivalent to `(cmd)@'\n'`.

Likewise, double-quoting gets a similar treatment. For example, if we have an array `set x "1 2" 3 4`, writing 

    echo "$x"@':'

should produce the following output:

    1 2:3:4

Omitting the `@` would simply join on spaces, as it currently does.  

Adding this functionality would position double-quoting and command substitution as duals of each other. It would be more accurate to think of them as joining and splitting operations, instead. It would allow for the removal of brace expansion, as we could write `foo{1,2,3}` as `foo(echo 1 2 3)@' '`, which is more verbose, but also more consistent. And I think it's more consistent than the proposals for `list`, as its behavior doesn't depend upon whether its in a command substitution or not.

**Comment by anordal** [comment]
```
(cmd)@' '
```
Like it! No more IFS!

**Comment by Maelan** [comment]
I am also in favour of more control over splitting in command substitution (choosing which separator to split on¹ or disabling splitting), and the `(cmd)@` syntax sounds nice for that (terse).

However, I do not quite agree to reuse that `…@` syntax for the *opposite* operation, joining — to me it would be rather confusing. Nor do I like the inconsistent `…[]` syntax, by the way. I would say a `join` builtin would be neater, in addition to being more general (and already [on the way](https://github.com/fish-shell/fish-shell/issues/156#issuecomment-124138106)):

Examples:

    set x a b c
    echo (join ' ' $x)@     # equivalent to "$x"
    echo (join : $x)@       # to get colons instead
    echo (join \n (ls))@    # almost equivalent to the proposed "$(ls)", or just (ls)@
    env ARRAY=(join \x1c head $ARRAY)@ cmd    # use case: passing a modified array to the environment
    env PATH=(join : /my/path $PATH) cmd      # the same for a whitelisted array

Notice that since we use a command substitution to join elements, we should take care not to introduce extra splitting on `\n` characters… Hence the additional `@` in the examples above.

---
¹ As far as I understand, the value of the `IFS` variable currently only determines if the output of command substitutions is split or not, but do not actually alter the separators used for splitting (which is always `\n`). Am I wrong?

**Comment by faho** [comment]
I think this is all done, now?

>Syntax for command substitution without splitting

`string split0` has superpowers. It technically isn't completely _without_ splitting, but NULs can't be passed as arguments anyway.

>No more "Array index out of bounds" errors

This has been gone for a while now.

>More conservative behavior around colon-separated env vars

We've changed this again for 3.0, hopefully that'll be the winner.

So: It has taken a while, but I'm closing this now as implemented.
