### ISSUE TITLE
`bind -k` results in `fish: Could not set up terminal` if not started in a TTY

### ISSUE THREAD

**Issue by OwenAR** [fish-shell/fish-shell#1759]
I was trying to use [Unison](http://www.cis.upenn.edu/~bcpierce/unison/) between my desktop and laptop (both had fish as the login shell).

Entering this:
`$ unison $HOME'/'dirname    'ssh://'(otherhostname)'.local/'dirname    -auto -log=false -times`

Gets this:
`Contacting server...`
`fish: Could not set up terminal`
`Fatal error: Lost connection with the server`

More basically, this works:
`$ ssh (otherhostname).local -t 'echo $TERM'`
`xterm`
`Connection to otherhostname.local closed.`

But this doesn't:
`$ ssh (otherhostname).local 'echo $TERM'`
`fish: Could not set up terminal`

**Comment by krader1961** [comment]
This issue is now obsolete due to numerous changes since it was opened. You'll still get warnings if launching an interactive shell that tries to bind to named keys not available from the terminfo database. But those are now just warnings. And for non-interactive shells you get the expected result. For example, `env -u TERM ssh localhost 'echo hello'`. We have other issues open (e.g., #4188) to discuss other refinements to the current behavior.
