### ISSUE TITLE
Some child processes started with & exit when terminal closed.

### ISSUE THREAD

**Issue by fgpietersz** [fish-shell/fish-shell#1771]
This is similar to #773

This seems to depend on what you run.

ON Ubuntu 14.04 using :

`kate &`

it prints a bunch of stuff to the terminal, and hitting return give me

 `1     8625    0%      running kate &`

and if I close the terminal Kate exits

but:

`gvim &`

immediately give me:

    1	8757	0%	running	gvim &
    Job 1, “gvim &” has ended

What I want is something like Bash where something like:

`(kate &)`

works for everything I have tried.

**Comment by 1player** [comment]
Same problem here, Arch 64bit, fish 2.1.2

Some apps in background will be killed upon exiting the terminal emulator.

Scenarios:
1) gnome-terminal, run "xterm &", close gnome-terminal, xterm is still running -- **working as expected**

2) gnome-terminal, run "gedit &", close gnome-terminal, gedit is killed -- **bug**

Seems to affect GTK 2/3 apps only. Tested GTK, QT and X11 apps.

gnome-terminal 3.14.2, gedit 3.14.3, gtk2 2.24.27, gtk3 3.14.9

**Comment by zanchey** [comment]
Still not able to reproduce here. It might be worth `stracing` gedit once it is running to see what signals it is receiving - `strace -p (pgrep gedit)` or so in another window should work.

**Comment by 1player** [comment]
They are receiving a SIGHUP signal when the fish shell closes.

**Comment by 1player** [comment]
I've done further investigation, and, quoting from BASH manual:

> The shell exits by default upon receipt of a SIGHUP. Before exiting, an interactive shell resends the SIGHUP to all jobs, running or stopped. Stopped jobs are sent SIGCONT to ensure that they receive the SIGHUP. To prevent the shell from sending the signal to a particular job, it should be removed from the jobs table with the disown builtin

So SIGHUP is correct, but we shouldn't be sending it to background processes. I'm not an expert on fish internals but it seems to be that on reader.cpp:2903 we should also be skipping background processes when exiting.

Now, the question is why don't QT and X11 app exit? Because on my system they seem to ignore SIGHUP signals.
You can check with
    cat /proc/PID/status | grep SigIgn

That is a bitmap of ignored signals, with `1 << signal` set for every ignored signal.
On my system:

    ~ $ cat /proc/(pgrep xterm)/status | grep SigIgn
    SigIgn:	0000000000200001

    ~ $ cat /proc/(pgrep gedit)/status | grep SigIgn
    SigIgn:	0000000000001000

Bit 1 is set on xterm, meaning it is ignoring SIGHUP. Which also mean it's not killed even when not on background.
Although I don't know why QT and X11 ignore SIGHUP by default, it looks like fish shouldn't send a SIGHUP to any background process.

**Comment by zanchey** [comment]
OK - I can make this happen now (with a manual SIGHUP of the fish process). I agree with the analysis. This path only gets called by the SIGHUP handler, which is why a normal `exit` does not reproduce it.

**Comment by zanchey** [comment]
The OS appears to take control of sending SIGHUP & SIGCONT to orphaned background process groups that have stopped jobs, so I think fish just needs to do foreground jobs.
