### ISSUE TITLE
Gtk::IconThemeError with astroid

### ISSUE THREAD

**Issue by tannhuber** [fish-shell/fish-shell#1783]
My PC is unable to run [astroid](https://github.com/gauteh/astroid) when fish is set as default shell. It crashes with:

```
(astroid:824): Gtk-WARNING **: Could not find the icon 'mail-send-symbolic'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
    http://icon-theme.freedesktop.org/releases
terminate called after throwing an instance of 'Gtk::IconThemeError'
Abgebrochen
```

When I try to run it with strace, there are strange lines in strace log like these:

```
open("/usr/lib\36/usr/local/lib/tls/i686/sse2/cmov/libgtkmm-3.0.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

```
stat64("/usr/share\36/usr/loal/share/pixmaps/hicolor/index.theme", 0xbf8b83ac) = -1 ENOENT (No such file or directory)
```

The complete log file is [here](https://gist.github.com/tannhuber/c7cae862f897efccd3cb).
I would like to note that the path names are weird. I checked my home directory with ag-silversearcher (grep) whether these lines are within one of the config files. It's not the case. And astroid starts when bash is default shell. So I think the problem has something to do with fish. But I'm not sure. Can anybody confirm?

**Comment by kylemcdonald** [comment]
i had a related issue trying to load CUDA and found that the offending line was this:

```
set -x LD_LIBRARY_PATH $CUDA_ROOT/lib:$LD_LIBRARY_PATH
```

putting this line in my `config.fish` and then running `echo $LD_LIBRARY_PATH` would print nothing. but it works if i just write:

```
set -x LD_LIBRARY_PATH $CUDA_ROOT/lib
```

but i would rather not worry about keeping track of which order my variables are set in `config.fish`. if someone knows a more correct way to set variables i would appreciate it.

**Comment by krader1961** [comment]
The problem you're running into, @kylemcdonald, is that concatenating unquoted vars has a combinatorial effect and if one of the vars is "empty" (i.e., has no values) it causes no resulting output. This is by design. You simply need to quote the new value:

```
set -x LD_LIBRARY_PATH "$CUDA_ROOT/lib:$LD_LIBRARY_PATH"
```

Pedantic comment: Whether that is correct is itself a matter of debate since you've now set __LD_LIBRARY_PATH__ to two paths the second being the empty path (which often means whatever the PWD is at the time the var is interpreted). The trailing ":" you just added is in some sense incorrect.

**Comment by kylemcdonald** [comment]
@krader1961 thanks a bunch for that clarification! i only recently switched from bash to fish because i felt like i was starting to understand bash and maybe it was time to try something more feature-full :)

so it sounds like there is a tradeoff between:

1. having one line that must come first that starts `set -x LD_LIBRARY_PATH...`
2. being able to put the `set -x LD_LIBRARY_PATH` in whatever order you want., but having the PWD included in the LD_LIBRARY_PATH

in that case, i'll go with the first option.

thanks again!
