### ISSUE TITLE
Autocompleting delimiters

### ISSUE THREAD

**Issue by leebrooks0** [fish-shell/fish-shell#1807]
Is it possible to autocomplete delimiters like brackets and quotes etc?
eg. type '(' and you get '()'

**Comment by laughedelic** [comment]
@leebrooks0 hi! I've made recently a plugin exactly for this: [pisces](https://github.com/laughedelic/pisces). 
It works in a similar way as @zanchey proposed, but with more features, like removing empty pairs on backspace and skipping the closing symbol — trying to simulate the behaviour, familiar from most text editors.

**Comment by faho** [comment]
Okay, if you want this bind it like suggested or use pisces. Binding won't be much of a problem anymore because of bracketed paste.

Personally I *hate* this behavior and turn it off everywhere I can, but it seems to be entirely possible.

Closing because I don't think there's anything left to do here.
