### ISSUE TITLE
Investigate whether $PWD changes are reported to VTE terminals

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#1814]
As mentioned in #906, the claim is that VTE terminals no longer see PWD changes.

The relevant code is in `share/functions/__fish_config_interactive.fish`:

```
if test "$VTE_VERSION" -ge 3405
    function __update_vte_cwd --on-variable PWD --description 'Notify VTE of change to $PWD'
        status --is-command-substitution; and return
        printf '\033]7;file://%s\a' (pwd | __fish_urlencode)
    end
end
```

**Comment by dvdbng** [comment]
For anyone looking for a workaround: The problem is that gnome-terminal won't do this if you are running fish as a custom command instead of your shell. To fix make gnome-terminal run your shell instead of custom command (in preferences -> profile -> command)
![](https://bengoa.me/i/2019-11-24-18:19:08.png). Then to make gnome-terminal run fish instead of your default shell, you can either make fish your shell (run `chsh`), or, if you are like me and you have a lot of scripts that assume your shell is bash-like, you can:

- Run gnome-terminal with `env SHELL=/usr/bin/fish gnome-terminal`
- Reset `SHELL` back to bash or whatever in your `config.fish`: `set -gx SHELL /bin/bash`
