### ISSUE TITLE
First char of autocomplete is wrong color

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#1821]
Brian S reports on the mailing list:

> I’m running into an issue with the color of the autosuggestions. I’ve set the color of the
> autosuggestion to gray using fish_config. However, the very first character of the autosuggestion
> is black (my default color); which gets very confusing. I would like it to be gray like the rest of the
> autosuggestion. I’ve put a screen shot of the issue at
> https://drive.google.com/file/d/0B8RHIr7J8XHoTzRpLVJ0MTlnLTg/view?usp=sharing

I can reproduce this in OS X Terminal.app when the cursor is set to "vertical bar" or "underline"

**Comment by xfix** [comment]
It's worth noting that this may have been intentional to keep the cursor color consistent in terminal emulators like Konsole.

![2 1](https://cloud.githubusercontent.com/assets/1297598/6075585/95b10c20-add5-11e4-98ae-91d92513b2fa.png)
![master](https://cloud.githubusercontent.com/assets/1297598/6075586/95b3906c-add5-11e4-9b60-547d5d7cdbb8.png)

**Comment by ohAitch** [comment]
To expand on ^: on stock OS X Mavericks Terminal which has a grey on white cursor, this fix makes e.g. autocomplete hard to distinguish by virtue of the text being the same color.
