### ISSUE TITLE
Changing hostnames can lose "universal" variable values

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#183]
I just put my laptop to sleep on one network, moved over to another, and woke it up, and this caused me to lose 2 of my "universal" variables. If I look at my `~/.config/fish/fishd.originalhostname` file it lists the variables but my `~/.config/fish/fishd.newhostname` file is missing them.

Why are the fishd files specified on a per-host basis anyway? My only guess is so you can synchronize your `~/.config/fish` folder between machines and keep separate `fishd` variable sets, but that would be far better served using some permanent hardware identifier instead of the hostname which is prone to changing.

**Comment by szhu** [comment]
I am using fish on a computer system (the Berkeley CS department) where I can access my home directory through one of many login nodes. Because the MAC address of each of these login nodes is different, I am not able to rely on universal variables.

I understand that having only one universal variable file can cause race conditions, and this could happen because sometimes I'm using multiple login nodes at once. How does fish's persistent function storage (`~/.config/fish/functions`) not run into the same issue?

**Comment by ridiculousfish** [comment]
We have a PR to make the uvars filename settable, which ought to address your case. Functions are tracked as separate files so there's fewer synchronization concerns, and we don't make any attempt to have per-machine or per-host files.
