### ISSUE TITLE
Can't use `read` inside `eval` blocks

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#1844]
`somefunc.fish`:

```
function myecho
     read -l somevar
     echo $somevar
end

function somefunc
     eval myecho
end
```

`read` returns without setting any contents of the variable, probably because standard input is not as expected in `eval.fish`.

**Comment by ridiculousfish** [comment]
The behavior here seems to have changed recently with b4aa2b7c2cdd640f4f5e1fb9efd37bb280573c89. I need to short this out.

**Comment by ridiculousfish** [comment]
This was broken in fish 1.x as well.

**Comment by ridiculousfish** [comment]
What's going on is that fish is not in the foreground process group for the tty (i.e. `tcgetpgrp()`). Instead, the keepalive process is. fish calls select() on the tty, waiting for input. When the input occurs (you press a key) it tries to read, but gets EIO since it's no in the foreground. With `b4aa2b7` we (correctly, IMO) stop reading when a read from stdin errors, so we end up exiting out.

One possible fix is to make `builtin_read` try to grab the tty via tcsetpgrp.

**Comment by krader1961** [comment]
This is probably a dup of #1362 and several other issues. Nonetheless, I'm leaving this open so that others searching for issues that talk about a particular set of symptoms are more likely to find a match.
