### ISSUE TITLE
ant completion breaks on imports using property values

### ISSUE THREAD

**Issue by arloherrine** [fish-shell/fish-shell#1861]
when an imported file's path uses a property value e.g. `<import file="${common.build.dir}/common-build.xml"/>`, auto completion breaks because the file doesn't exist without the property value variable substitution.

The simple fix for this is to replace the entire `__fish_complete_ant_targets` function with just `ant -p | sed -n 's/^ \([^ ]*\).*$/\1/p'` but this might be a little slow. it might be better to augment the existing code with the variable substitution

**Comment by krader1961** [comment]
Unfortunately unless someone who uses the command actually writes the required completion script code it will never be implemented. We are happy to answer questions and provide guidance about implementing a better completion script for nant. However, I'm going to close this because unless someone like yourself actually does that work it will never be done. Feel free to reopen this issue if you, or anyone else, is interested in making the required changes and needs advice.
