### ISSUE TITLE
Move completions scripts to separate repository

### ISSUE THREAD

**Issue by rominf** [fish-shell/fish-shell#1865]
I propose to move all completions scripts (from `share/completions` directory) into separate directory. If I understand it correctly, completions loosely depend on fish internals. Also, they are changing rapidly comparing with fish releases (#1781).

Moving them to separate repository (`fish-completions`, for example) would allow to have uptodate completions in separate package. Most urgent users would have possibility just to clone repository into `/usr/share/fish/completions`.

**Comment by faho** [comment]
>Notice that e.g. grep completions are in share/functions directory.

Not since 0c1485c325df3a23d57fd26883597aeb27ddf2c6, they aren't (the buggers). When they (and a few other completions) were written, complete didn't have an idea of "wrapping", i.e. inheriting from another command.

I'm not completely certain we'd want to do this, especially since #478 would deprecate the current system.

**Comment by faho** [comment]
I'm going to have to reject this. Currently, the completions are tied too closely to fish's internals - we change our functions and adapt the completions along with them.
