### ISSUE TITLE
How to change universal  environment variables?

### ISSUE THREAD

**Issue by jhdxr** [fish-shell/fish-shell#1868]
I used `set -U  ANDROID_HOME /Applications/Android Studio.app/sdk` to set ANDROID_HOME to /Applications/Android Studio.app/sdk, and it works fine. Now I moved my android sdk to /Library/Android SDK/, but I fail to set ANDROID_HOME to the new location.
I have tried the following commands:
`set ANDROID_HOME /Library/Android\ SDK/`  ==> only works in current window
`set -U ANDROID_HOME /Library/Android\ SDK/` ==> only works in current window
`set -Ue ANDROID_HOME /Library/Android\ SDK/` ==> only works in current window

so i'm wondering how to change the universal environment variable?

**Comment by chanux** [comment]
I have a similar issue. When I run `react-native run-android` in a test project I get an error saying $ANDROID_HOME is not set

```
% fish --version
fish, version 2.3.1

% echo $ANDROID_HOME
/home/chanux/Android/Sdk

% react-native run-android
.
.
SDK location not found. Define location with sdk.dir in the local.properties \
file or with an ANDROID_HOME environment variable.

```
I have `set -g ANDROID_HOME $HOME/Android/Sdk` in my fish config file.

Anyhow if I run the command as follows, everything is fine. Trying to understand what is going on.

`env ANDROID_HOME=$HOME/Android/Sdk react-native run-android`

**Comment by floam** [comment]
First, it's not really necessary to put it in your fish.config - you might as well remove that line in your `fish.config` before you have the same trouble as the original poster next year when you go to change it. You can use `-U` instead of `-g` at the command line to accomplish the same thing.

Now that you've done that, it's set globally in fish, but isn't exported to the environment here. Normally, it's not important or even desirable for variables fish uses to be made available to every program that is run. In this case we want exactly that though. So you will want to use `-x` to also set it for export. Do a `set -Ux ANDROID_HOME /home/chanux/Android/Sdk`.

You can compare the output of `set` and set -x` to see what is currently being exported.

**Comment by chanux** [comment]
Thanks @floam for the explanation! I checked the man page for set and a couple other discussions here on issues and I think I now have a slightly better understanding of my universe :D

**Comment by chrise86** [comment]
I still can't get it working with fish. Keep getting the same message:

```
SDK location not found. Define location with sdk.dir in the local.properties \
file or with an ANDROID_HOME environment variable.
```

**Comment by faho** [comment]
@chrise86: The output of `env | grep ANDROID` would be helpful here.

**Comment by chrise86** [comment]
I _think_ it was a bad install; after restarting the whole install/setup process again it seemed to work 👍
