### ISSUE TITLE
Please honour TMPDIR environment variable

### ISSUE THREAD

**Issue by shevegen** [fish-shell/fish-shell#1875]
Hi there!
Fish is cool, I like it more than bash.
Hopefully one day I can use fish rather than bash but right now I am not completely sure - I am a lazy person, switching requires effort. :-)

At any rate, here is the issue.

I have $TMPDIR set:

echo $TMPDIR

/Depot/Temp

The above directory exists.

However, when I look in:

/tmp/

I see:
fishd.log.root

I thus assume that fish does not honour $TMPDIR environment variables.

Please add a check to the code, perhaps through getenv() to determine whether
a user has set this variable, and then assume another tmp dir if this
variable was provided. Most other programs I run are just fine in my
TMPDIR /Depot/Temp.

**Comment by zanchey** [comment]
I was pretty surprised how easy it was to switch completely - good luck!

It looks like you are running an old version - I recommend updating to 2.1.1. The files you describe have their location set by the environment variable `XDG_RUNTIME_DIR` in 2.1.1, so you can set that to control their location.

The reason that variable is used rather than `TMPDIR` is that it is more strongly specified by the XDG standards to support the features we need. `/tmp` is used as a fallback as it is the most likely place to support the features we need. There is no formal specification for the features of `TMPDIR` and thus it may point to a filesystem which is strange or unusual.

**Comment by zanchey** [comment]
I'm going to close this for now as I think the current behaviour is what we want; feel free to comment or reopen if you disagree!
