### ISSUE TITLE
gpg-agent compatible syntax

### ISSUE THREAD

**Issue by zabbal** [fish-shell/fish-shell#1885]
Upon startup gpg-agent prints information for environment variables to be set so it's usually executed as 
eval $(gpg-agent --daemon)

What would be fish equivalent to set variables based on the output of the evaluated program?

**Comment by bpinto** [comment]
```
λ set local_variable (echo 'abc')
λ echo $local_variable
abc
```

**Comment by ridiculousfish** [comment]
Example output: `GPG_AGENT_INFO=/tmp/gpg-MA93lU/S.gpg-agent:1598:1; export GPG_AGENT_INFO;`

This is sh syntax of course.

**Comment by zanchey** [comment]
For the GPG case in particular, you might find [Keychain](http://www.funtoo.org/Keychain) useful as it has fish support built in.

**Comment by faho** [comment]
Isn't this something like `eval (gpg-agent --daemon | sed -e "s/\(.*\)=\(.*\); export/set -x \1 \2/")`?

(As an aside, I absolutely dislike gpg-agent)

**Comment by demonking** [comment]
@faho thx for the fish line :) why do you dislike gpg-agent?

**Comment by faho** [comment]
>why do you dislike gpg-agent?

Because it needs stuff like this - instead of putting the socket at a well-known path (like e.g. "/tmp/gpg-$UID.socket") it outputs a randomly-generated socket path on start, making it a bit harder to start via systemd (it's possible, but requires configuration). Not just that, it outputs shell syntax to be `eval`'d - a security-related program that asks the user to `eval`. Also GPG_TTY and the fact that all pinentry programs suck. 

Anyway, that's neither here nor there. Revisiting this, this should work without eval (unless gpg-agent decides to print something else which AFAIK it can when also run as ssh-agent) by doing `set -l GPG_AGENT_INFO (gpg-agent --daemon | sed -e 's/^.*=\(.*\);.*$/\1/')` (or replacing sed with `cut -d"=" -f2 | cut -d";" -f1`).

Otherwise, this is one of the sh-compatibility bugs.

**Comment by Glandos** [comment]
@faho please use `--use-standard-socket` and the socket will be placed in `$HOME/.gnupg/S.gpg-agent`.
However, the `eval` part is still needed, because there is the PID and the protocol version in it. But it is much better: the PID can be fetched from systemd or fish, and for now, the protocol version is fixed to 1.

**Comment by faho** [comment]
>please use --use-standard-socket and the socket will be placed in $HOME/.gnupg/S.gpg-agent

That's what I meant by "possible, but requires configuration" - this should really be the default.

>However, the eval part is still needed, 

Nope, see above - you can cut out the value for the variable and set it to the variable - `eval` would allow arbitrary code to run (and also does some more splitting).

>because there is the PID

Huh? What does one need the PID for, exactly? To communicate with the agent, connect to the socket.

>and the protocol version in it

Since it doesn't appear the protocol version is going to change it's not a pressing issue currently. Anyway, this is more of a problem on the gpg-agent side since echoing that stuff just won't work with systemd.

**Comment by faho** [comment]
I think this question has been answered, so I'll close this issue. If there's anything else, feel free to ask!

**Comment by maxigas** [comment]
For the record, most of the suggestions about improving gpg-agent behaviour put on the table by  @faho have been implemented as of GnuPG 2.1:

https://www.gnupg.org/faq/whats-new-in-2.1.html#autostart

**Comment by zanchey** [comment]
Sockets in home directories? That might be fun.

**Comment by britter** [comment]
All I had to do to get gpg-agent running was to add `use-standard-socket` to ~/.gnupg/gpg-agent.conf

**Comment by jorpilo** [comment]
Following the .bashrc example of Arch https://wiki.archlinux.org/title/GnuPG#Set_SSH_AUTH_SOCK wiki I have set the following in my config.fish

```
set -e SSH_AGENT_PID
if not set -q gnupg_SSH_AUTH_SOCK_by; or test $gnupg_SSH_AUTH_SOCK_by -ne %fish_pid
    set -gx SSH_AUTH_SOCK "$XDG_RUNTIME_DIR/gnupg/S.gpg-agent.ssh"
end

```
