### ISSUE TITLE
Fish on Cygwin: "Runtime path not available"

### ISSUE THREAD

**Issue by badp** [fish-shell/fish-shell#1887]
Fish 2.1.1-5 (the newest version on the repositories) seems to misbehave when ran under Cygwin in a number of ways (possibly all cascading from the on-start message). I'll number them for ease of discussion.

https://gfycat.com/PlainThisAmericanratsnake

1. On start, I get this error:

        fish: Runtime path not available.
        Try deleting the directory /tmp/fish.b and restarting fish.

  * `rm -rf /tmp/fish.b` does not help.

2. Also this error:

        fish: Could not connect to universal variable server.
        You will not be able to share variable values between fish sessions.

3. fish is completely colorless:

        set_color: Expected an argument

4. Backspace does not work

5. Arrows do not work (e.g. pressing `←` results in `[D` being typed instead)

6. Occasionally tab completing shows this message four times:

        fish: Unknown command 'R'
        in command substitution
                called on standard input,

Things that *do* work include automatic indentation (e.g. for `function`), Ctrl-C wiping the command line in-place, always-on reverse search (although I can't actually use it as `→` is read as `[C`), the pager, plus perhaps a few other bells and whistles I didn't think to try.

In case it helps, here's my path (with a little bit of pretty printing for your viewing pleasure):

    b@ECHO ~> which R
    which: no R in (
		/bin:
		/usr/local/bin:
		/usr/bin:
		/cygdrive/c/Program Files (x86)/Intel/iCLS Client:
		/cygdrive/c/Program Files/Intel/iCLS Client:
		/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:
		/cygdrive/c/Program Files/ImageMagick-6.8.9-Q16:
		/cygdrive/c/Windows/system32:
		/cygdrive/c/Windows:
		/cygdrive/c/Windows/System32/Wbem:
		/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:
		/cygdrive/c/Program Files (x86)/MiKTeX 2.9/miktex/bin:
		/cygdrive/c/Program Files/Microsoft SQL Server/110/Tools/Binn:
		/cygdrive/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.0:
		/cygdrive/c/Program Files (x86)/gdipp:
		/cygdrive/c/Program Files/MATLAB/R2014a/bin:
		/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:
		/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:
		/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:
		/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:
		/cygdrive/c/WINDOWS/system32:
		/cygdrive/c/WINDOWS:
		/cygdrive/c/WINDOWS/System32/Wbem:
		/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:
		/cygdrive/c/tools/python:
		%SystemRoot%/system32:
		%SystemRoot%:
		%SystemRoot%/System32/Wbem:
		%SYSTEMROOT%/System32/WindowsPowerShell/v1.0:
		/cygdrive/c/ProgramData/chocolatey/bin:
		/cygdrive/c/tools/python:
		/cygdrive/c/tools/python/Scripts)

<sup>(Yes, I have Python installed in `C:\tools\python`, in addition to cygwin's own Python, in addition to LyX's own Python, and they're all different versions, and it isn't pretty.)</sup>

**Comment by zanchey** [comment]
Yes, 1, 2 and 3 are probably because of a problem with the fishd path. I'm not sure why that doesn't work, @xfix may be able to shed some light on the matter.

4 and 5 are probably because of problems with your TERM/termcap; what is the output of `echo $TERM`?

6 is because of #1569 - try defining a function called `R` that just does `echo "(R)"` and they will probably go away.

**Comment by badp** [comment]
> 4 and 5 are probably because of problems with your TERM/termcap; what is the output of echo $TERM?

    b@ECHO ~> echo $TERM
    xterm

(`bash` agrees.)

**Comment by xfix** [comment]
Problems 2-6 are all result of one problem, problem 1. Problem 1 suggests that something odd is going on (dunno, Cygwin installed on NFS or FAT32?). FAT32 could in theory be fixed by not enforcing file permissions (files on FAT32 don't have permissions), but NFS is unlikely to be fixed.

Anyway, if Cygwin is installed on some odd filesystem, the sockets in `/tmp` cannot be created. However, it's possible to set up socket in some location on drive C: instead. To do so, set `XDG_RUNTIME_DIR` environment variable to location where the sockets can be made (NTFS will work).

**Comment by badp** [comment]
> (dunno, Cygwin installed on NFS or FAT32?)

Nope, it's good old NTFS. And I can create and use sockets normally in that folder:

http://i.imgur.com/yIDw5N0.png

**Comment by zanchey** [comment]
I can't reproduce this with 2.2b1.

**Comment by floam** [comment]
@badp Can you reproduce any of this? `XDG_RUNTIME_DIR`  stuff?

**Comment by badp** [comment]
Sorry for the delay. No, I cannot reproduce this any longer :)
