### ISSUE TITLE
Issue with printf, echo, and unicode.

### ISSUE THREAD

**Issue by adamk33n3r** [fish-shell/fish-shell#1894]
Both `printf '\342\224\214'` and `echo -e '\342\224\214'` treat the string as 3 separate characters unlike the system printf and echo.

This should produce `┌` as does the system functions but instead produces `â` which as you can see is three separate characters.

**Comment by ridiculousfish** [comment]
fish's printf is derived from GNU /usr/bin/printf. I can reproduce this bug with on OS X Yosemite. [Here's Yosemite's printf](http://www.publicsource.apple.com/source/shell_cmds/shell_cmds-179/printf/printf.c) for reference.

It's not obvious to me that the above should output `┌`.  After all, you are specifying three separate characters; if you want just one character there's Unicode escapes like `printf '\U250C'`.

**Comment by adamk33n3r** [comment]
So why do the commands in /usr/bin, on linux at least, handle it this way? With the 3 pair octal being one character?

I do realize you can use the `\U250C` with printf but that doesn't work with echo.

**Comment by ridiculousfish** [comment]
My guess is that /usr/bin/printf is just being naive: it generates an 8 bit "character" for each of the octal sequences, and then outputs those characters. Your terminal is what interprets them as a UTF-8 sequence.

So a key question is whether octal escape sequences are meant to represent characters, or literal bytes. IEEE 1003.1 says _"\ddd", where ddd is a one, two, or three-digit octal number, shall be written as a byte with the numeric value specified by the octal number._ so I guess it wants literal bytes, which means we should store octal escapes via ENCODE_DIRECT_BASE rather than as characters.

**Comment by ridiculousfish** [comment]
Tests added and fixed as d4eded2376706c67b680ad522e61cbe54d8214b0 . Thanks for reporting this.

**Comment by adamk33n3r** [comment]
Cool and no problem. Happy to help out such a great project.
