### ISSUE TITLE
Extra lines in shell of Emacs

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#1913]
When I use `shell` (not `eshell` or `ansi-term` or `term`) in Emacs, it will execute `fish`(my default shell in my terminal) as shell,

But here is my problem:

```
# this is my original text in the shell in Emacs, note that my prompt is in the second line, `|` is my cursor
chz@localhost: ~/Projects/Go/exercism-cli 
➤➤ |

# if I type `Enter` key at `|` symbol, it will be (including the original text):
chz@localhost: ~/Projects/Go/exercism-cli 
➤➤ 
chz@localhost: ~/Projects/Go/exercism-cli 
➤➤
chz@localhost: ~/Projects/Go/exercism-cli 
➤➤ |

# if I type ls after the original text, it will be (including the original text):
chz@localhost: ~/Projects/Go/exercism-cli 
➤➤ ls
chz@localhost: ~/Projects/Go/exercism-cli 
chz@localhost: ~/Projects/Go/exercism-cli 
➤➤ ls
cli/  README
chz@localhost: ~/Projects/Go/exercism-cli 
➤➤ |
```

Need other info? Please go to #1907, or let me know.

**Comment by zanchey** [comment]
With zsh, I get the command echoed, but not the rest of the prompt. [This fix](https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/Shell-echo.html) covers zsh but does not work for fish.

**Comment by krader1961** [comment]
Is this still an issue? If it is we're going to need more data such as the value of $TERM, output of `stty -a`, and the interaction captured with `script`.

**Comment by liblit** [comment]
I can reproduce some form of this problem using **fish 2.3.1** and Emacs 25.1 as distributed under Fedora 25. I am running this all under a Vagrant-constructed virtual machine with no special Emacs or fish configuration beyond what is packaged for me at the system level. So this should be very close to a default configuration, modulo any special tweaks that the Fedora packagers may have applied.

I start Emacs by running `emacs --funcall shell`, which causes it to immediately drop into a bare-bones shell buffer as per @c02y's [original bug report](https://github.com/fish-shell/fish-shell/issues/1913#issue-55274435). Here is what I see as the initial text visible in the buffer:

>![initial greeting and prompt](https://cloud.githubusercontent.com/assets/1759836/24069676/839c4d14-0b7b-11e7-93c7-b80f3204f1f4.png)

Note the extra `^[` in red, which is actually a single escape character, not literally a `^` followed by a `[`. Right after that, notice the `(B` in dark gray. Although not visible in this screen shot, the text insertion cursor is positioned at the right end of the blue prompt: exactly where it should be. **I claim that both the red escape and the gray `(B` should not be seen here at all.**

If type no command but instead merely press enter, I now see the following:

>![no command, just press enter](https://cloud.githubusercontent.com/assets/1759836/24069702/0b9f772c-0b7c-11e7-999b-4d9153c8ad03.png)

Notice the **extra white copy of the prompt,** and then the expected blue copy. Although not visible in this screen shot, the text insertion cursor is positioned at the right end of the most recent blue prompt: exactly where it should be.

If I type a command (such as `pwd`) and then press enter, I now see this:

>![type `pwd` and then press enter](https://cloud.githubusercontent.com/assets/1759836/24069710/5f0afff8-0b7c-11e7-81ac-6f7c788146d9.png)

The first place where you see `pwd`, it is bold, white, and just to the right of a blue prompt. That is where it appeared, character by character, as I typed it. That is how it should be. However, on the next line after that notice an **extra white copy of the prompt, now including an extra copy of the `pwd` command I entered.** After that comes the command output as expected, and then we are back to the blue prompt again.

@krader1961, regarding the additional information [you requested](https://github.com/fish-shell/fish-shell/issues/1913#issuecomment-287513435):

* `$TERM` is set to `dumb`
* `stty -a` output is here: [stty-a.txt](https://github.com/fish-shell/fish-shell/files/852218/stty-a.txt)
* interaction captured with `script` is here: [typescript.txt](https://github.com/fish-shell/fish-shell/files/852219/typescript.txt)

I hope this is helpful.

**Comment by liblit** [comment]
I just repeated the above steps using a fish 2.5.0 release downloaded as source directly from GitHub and built within my Fedora 25 virtual machine. This time around, I did *not* install the Fedora-provided `fish-2.3.1` package, so the fish configuration here should be pristine, with nothing included except whatever the fish developers themselves provide.

Bringing up the Emacs shell buffer, I no longer see the initial `Welcome to fish` greeting at all. Instead I'm taken directly to a blue `vagrant@localhost ~ > ` prompt. After that, though, everything proceeds as I described [above](https://github.com/fish-shell/fish-shell/issues/1913#issuecomment-287521801). I still see the extra, all-white copy of each prompt line, along with any command I may have typed before pressing enter. So it seems that any changes made between 2.3.1 and 2.5.0 did *not* fix this problem.

**Comment by krader1961** [comment]
The problem is that emacs shell mode is echoing what you type, not fish. Then emacs moves the cursor to the next line when you press [enter]. Emacs then sends what you typed to fish which repaints the command line to show what you typed with syntax highlighting and such. Which is why you see the command line twice. If you capture the output with `script` you can see that fish is doing the right thing. The problem is that emacs shell mode is fundamentally incompatible with shells like fish and zsh. Emacs shell mode is not a terminal emulator. It doesn't even initialize the termios rows and columns (i.e., what you see if you run `stty -a`).

The only way to avoid this visual artifact would be to draw the prompt once and not repaint it when input is received. Personally I don't think it's worth complicating fish in that fashion just to support emacs shell mode but I'm going to leave this open in case someone is willing to do the work and can show that the changes aren't too intrusive.

**Comment by npostavs** [comment]
comint.el has a `comint-process-echoes` option which tells Emacs to delete the second copy of the input. It was reported in [Emacs#26229](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=26229#11) that this doesn't work for fish. I think it's because the copy that fish echoes is a bit different from the original (due to the syntax highlighting?)

**Comment by faho** [comment]
Yeah, I'm gonna put the onus for this one on emacs.
