### ISSUE TITLE
Fish seems to mishandle focus events

### ISSUE THREAD

**Issue by baroldgene** [fish-shell/fish-shell#1917]
After running tmux with `tmux set-option -g focus-events on` and then disconnecting every time the iterm window gains focus characters are output to the shell.  Something to the effect of `$ [O[I`  This seems to be iterm attempting to pass on a focus event to the shell and fish shell failing to properly interpret (or ignore) it.

**Comment by geoff-codes** [comment]
I can reproduce this, but it doesn't seem to be a fish issue to me.
With bash (after disconnecting) I get a bell on each focus event (rather than `[O[I`).

I also can't reproduce it at all with Terminal.app or xterm.

My guess is its something to do with iTerm's [tmux integration](https://code.google.com/p/iterm2/wiki/TmuxIntegration). I'd recommend seeing if @gnachman can shed any light here, maybe by [opening an iTerm2 issue](https://code.google.com/p/iterm2/issues/list)?

**Comment by baroldgene** [comment]
The bell is expected behavior as far as I understand it. The characters are not. I don't get any characters with bash on iterm. Nor Zsh.  

I'll try with terminal.app and see if it's an issue there. 

My assumption is that terminal.app is not passing focus events to the shell like iterm is. Regardless though shouldn't these events be ignored by fish?

Thank you,
-Barry

**Comment by geoff-codes** [comment]
> The bell is expected behavior as far as I understand it.

I don't think so. The bell (in other shells) only occurs after a tmux session is initiated and then disconnected, just as is happening with the gremlins you get with fish. What we're seeing in fish is a portion of the [FocusIn/FocusOut control sequences](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#Mouse%20Tracking), which uses `CSI O` and `CSI I`. The difference in behavior (between fish and bash) probably has to do with what the shell does with an escape that isn't consumed by the terminal (or tmux) — fish prints the sequence, while bash "prints" a bell.

In any case, there's no reason why the behavior should be any different than _before_ the tmux session.
I suppose this could be a _tmux_ bug (if tmux is issuing some proprietary control sequence(s) to the terminal, or something to that effect, and doesn't reset these on exit), but I still think its more likely something to do with iTerm.

> My assumption is that terminal.app is not passing focus events to the shell like iterm is.

You're probably right — probably better to use the behavior of XQuartz's xterm for comparison.

> Regardless though shouldn't these events be ignored by fish?

I think a better question would be, why are raw escape sequences being passed to the shell/tty in the first place? Why aren't they being consumed by the terminal? My guess would be that it has something to do with how the `tmux -CC` integration is implemented, since iTerm needs to tell tmux about such events. Or perhaps the sequence is getting munged somewhere alone the way...

**Comment by zanchey** [comment]
I wonder if tmux isn't clearing the focus mode on detach, or if iTerm is ignoring it. What versions of those are you running?

The behaviour of shells in response to unrecognised control characters is inconsistent. As a test, I am using Alt + J and the F1 key on PuTTY (which sends `ESC [ 11 ~`).

 * Dash prints the entire sequence, using some magic to represent the escape character as a printable sequence.
 * Fish swallows the escape character and prints the rest.
 * Bash replaces some or all of the escape sequences with a bell (e.g. with F1 on PuTTY there is a bell and the ~ character is printed).
 * Zsh replaces the entire sequence (of those that I have tried) with a bell.

I think the zsh behaviour might be the right thing to aim for but I'm not certain.

**Comment by gnachman** [comment]
Doesn't look related to iTerm2's tmux integration (I can repro without using tmux -CC). It does look like a tmux bug to me. It sends CSI ? 1004 h when you do "tmux attach" but not CSI ? 1004 l on detach. It's not unusual for focus mode to get left on (for example, a program turns it on and crashes or the ssh session is lost); I know this because I frequently get issues filed against iTerm2 when this happens. I'd recommend either silently swallowing the FocusIn/FocusOut sequences or doing something dash-like (or be super clever and warn the user about what's going on). dash's approach gives the user something to help diagnose the issue, whereas a bell is just maddening.

**Comment by baroldgene** [comment]
Seems to be a lot of talk about if this is a TMux bug or a Fish bug or an iTerm bug.  I feel like it shouldn't really matter.  Maybe it's a TMux bug, but I feel like Fish should handle it when TMux (or iterm, or terminall.app, or....) fails.

I like @gnachman's suggestion of ignoring it.  Is there ever a situation in which ignoring it could cause problems?

**Comment by geoff-codes** [comment]
> Seems to be a lot of talk about if this is a TMux bug or a Fish bug or an iTerm bug. I feel like it shouldn't really matter. Maybe it's a TMux bug, but I feel like Fish should handle it when TMux (or iterm, or terminall.app, or....) fails.

> I like @gnachman's suggestion of ignoring it. Is there ever a situation in which ignoring it could cause problems?

Yeah, I agree with this sentiment. While we probably open a tmux bug for this, I think the most `fish`-like way to handle this would be to either:
- swallow it (@baroldgene, no, I can't really think of a use case for the present behavior, and it certainly doesn't shed any light on the situation)
- "be super clever and warn the user about what's going on" - print a descriptive message to the effect of `We're getting a bunch of weird input, did your last application leave focus mode on?` - _if_ we're aware of what's going on to that level of detail.

@gnachman Thanks for weighing in. I didn't mean to accuse you unfairly, I guess I'm just so used to using `tmux -CC` at this point it didn't even occur to me to try without it :grimacing:.

**Comment by zanchey** [comment]
It's actually pretty easy to ignore just the FocusIn/FocusOut control sequences by using bindings, so I'll do that. I will open a separate issue for what to do about unrecognised control sequences in the general case.

In the short term, you can fix this by adding something like this to your `fish_user_key_bindings` function:
```
bind \e\[I 'begin;end'
bind \e\[O 'begin;end'
```

Or, if you want to go the super clever route, `bind \e\[I 'Unexpected control sequence received: try disabling focus mode'`... but how does the user do that? `bind \e\[I 'echo -n \e\[\?1004l'` will disable the focus mode for them, but I'm not convinced that is a good idea.

**Comment by geoff-codes** [comment]
:+1:

**Comment by geoff-codes** [comment]
Opened a tmux ticket at: https://sourceforge.net/p/tmux/tickets/176

**Comment by geoff-codes** [comment]
@gnachman ftw.

From [nicm|at|users.sf.net](https://sourceforge.net/u/nicm):

```diff
diff --git a/tty.c b/tty.c
index 9f57c36..534d239 100644
--- a/tty.c
+++ b/tty.c
@@ -290,7 +290,7 @@ tty_stop_tty(struct tty *tty)
 	if (tty_term_has(tty->term, TTYC_XT)) {
 		if (tty->flags & TTY_FOCUS) {
 			tty->flags &= ~TTY_FOCUS;
-			tty_puts(tty, "\033[?1004l");
+			tty_raw(tty, "\033[?1004l");
 		}
 	}
```

is the ticket.

Should be committed [upstream](git://git.code.sf.net/p/tmux/tmux-code) shortly, I would think.

@zanchey I suppose you could back out 028d9e8 if you wanted, but we don't know the timeframe on when this will will see the light of day in a release.

**Comment by zanchey** [comment]
I'll leave it for now; I can't see it causing any problems.

**Comment by gnachman** [comment]
Don't back it out, it's still a real issue when an ssh session dies while the user is in tmux or the like.
