### ISSUE TITLE
Do something with unrecognised control sequences

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#1924]
Per #1917, when fish receives a control sequence it prints it verbatim. This means that the escape character is not echoed but the remaining characters end up on the prompt.

How do other shells behave?
- Dash prints the entire sequence, using some magic to represent the escape character as a printable sequence.
- Bash replaces some or all of the escape sequences with a bell (e.g. with F1 on PuTTY there is a bell and the ~ character is printed).
- Zsh replaces the entire sequence (of those that I have tried) with a bell.

One of these approaches could be adopted. Notably, a bell is not terribly helpful.

**Comment by geoff-codes** [comment]
I think a diagnostic would be really helpful here. Doesn't have to be super clever, its just:

```
Unexpected control sequence received: [I
Unexpected control sequence received: [0
Unexpected control sequence received: [I
Unexpected control sequence received: [0
...
```

is infinitely more helpful than `~> [I[O[I[O...`

**Comment by faho** [comment]
Alright, I'm going to close this, because unfortunately there is nothing about `\e[I` that tells us that that's one escape sequence.

There are certain *shapes* we could handle (e.g. just how the usual color sequences look like `\e[31m`), but I can't come up with a lot of those on input, and I don't believe that would be terribly useful in practice.
