### ISSUE TITLE
fish "An error occurred while redirecting file '/run/user/0/fishd.log.root'

### ISSUE THREAD

**Issue by halon176** [fish-shell/fish-shell#1955]
i'm using opensuse 13.2 and fish is the default shell, but every time i'm going to root, it sent this message
fish "An error occurred while redirecting file '/run/user/0/fishd.log.root'

so i try to change /run/user/0 permission to alow him to write log file and them the problem go away, even if i change hack the correct folder permission

so... i just try to do a bug report
fish, version 2.1.1

**Comment by zanchey** [comment]
This came up on IRC recently, too.

You are getting bitten by the fact that `su` doesn't reset your `XDG_RUNTIME_DIR` - see https://bugzilla.redhat.com/show_bug.cgi?id=753882

Instead of using `su`, you may need to use `su -` which will at least clear the variables. Unfortunately, I don't think there's much we can do here - fall back to `/tmp` if `XDG_RUNTIME_DIR` isn't writeable? Surely we can assume sane input.

This particular error will disappear in the next release, but it might manifest in other ways.

**Comment by ridiculousfish** [comment]
On OpenSUSE master currently spews "Unable to make or open a FIFO for universal variables with path '/run/user/0/fishd.0800273b325b.notifier': No such file or directory" In this case the directory `/run/user/0/` does not exist.

I'm not sure what the best course of action here is. Maybe we simply do nothing: then universal variables will only update after commands are run (instead of instantly) but that might be better than spewing.

**Comment by zanchey** [comment]
That sounds reasonable.

**Comment by zanchey** [comment]
... although it would be useful to have some way of working out whether that is the strategy being used; otherwise it may cause difficult-to-diagnose issues.

**Comment by JonSteyn** [comment]
I am not sure if it is better to open a separate issue?
I receive what seems to be a redirection error running `ls` with a recursive wildcard on a mounted filesystem and piping the output to a file in the user account home directory.
If I pipe output to a file in the root directory of the directory tree where I'm running the command - on the mounted filesystem, it works fine.
I see the message only when I pipe the output to a file in the user account home directory.

I'm using Fish Shell via Homebrew on Mac OS 10.6.8. Homebrew gives the version as 2.1.2, however `fish --version` reports "2.0.GIT". The fish executable is under ../2.1.2/bin/ and run via symlink /usr/local/bin/fish.
Fish is the default shell.
The directory tree where I am running the `ls` command is mounted 'the Mac/Finder way' via AFP.
(afpfs, nodev, nosuid)
The message I see is 
"fish: An error occurred while redirecting file '/Users/jonathan/Documents/Notes/todo.txt'
open: Not a directory"

**Comment by zanchey** [comment]
@JonSteyn, that sounds like a separate issue.

**Comment by lerori** [comment]
message fish "An error occurred while redirecting file '/run/user/0/fishd.log.root'
I solved it by creating the directory '/run/user/0/' as root and from the terminal entering with 'su' on my Debian Jessie.

**Comment by ridiculousfish** [comment]
I reproduced the problem on OpenSUSE and verified this fix eliminates the log spew.

**Comment by ridiculousfish** [comment]
Cherry-picked to 2.2.0 as 6c53862ff1cc7ada37f76a2fdabf85f3c3ba40d9
