### ISSUE TITLE
Read /etc/profile.d/*.fish at startup?

### ISSUE THREAD

**Issue by amluto** [fish-shell/fish-shell#1956]
I have a request from some other Fedora folks to allow fish configuration snippets (e.g. ccache configuration) in /etc/profile.d/*.fish.  Would this make sense as default behavior in upstream fish (via /usr/share/fish/config.fish perhaps)?

**Comment by zanchey** [comment]
[LSB section 16.2](http://refspecs.linuxfoundation.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/etc.html) requires the use of `/etc/profile.d/*.sh`, although the behaviour is not specified for `*.fish` scripts. Does this directory exist on OS X at all?

There was a similar intention behind `/usr/share/fish/vendor-completions.d`, and I think it's better done in the `/usr/share` hierarchy, but `profile.d` might be a special case.

**Comment by amluto** [comment]
I would argue for something in /usr/share and /etc/profile.d/*.fish.  The
former is a much better place for distro scripts, sh tradition
notwithstanding.  The latter is good for admins to drop snippets.

Fish isn't sh, so I think LSB barely applies.

**Comment by zanchey** [comment]
Thinking about it, completions are a bit different to configuration snippets that are run for all users, and I think `/etc/profile.d/*.fish` would be a reasonable compromise as they may need to be overridden and thus treated as conffiles.

Local administrators should drop snippets in `/etc/fish/config.fish`.

**Comment by rapgro** [comment]
:+1:

**Comment by ridiculousfish** [comment]
Simple. Tested with Ubuntu Precise.

**Comment by ridiculousfish** [comment]
Thanks for reporting this.

**Comment by zanchey** [comment]
Probably should use `__fish_sysconfdir`?

**Comment by zanchey** [comment]
Actually, possibly not.

Additionally - should `profile.d/*.fish` only be evaluated for interactive login shells, in line with the standard `/etc/profile` conventions? Or should all snippets call `if status --is-login`?

**Comment by ridiculousfish** [comment]
Good question - what do you think @amluto ?

**Comment by rapgro** [comment]
I am the reporter of the original downstream (Fedora) bug.
```
The sh utility shall read and execute commands in its current execution environment from all the shell scripts in this directory that have the suffix .sh when invoked as an interactive login shell, or if the -l (the letter ell) is specified (see Shell Invocation).
```
So the answer is "yes" to "interactive login shell" only.

**Comment by zanchey** [comment]
[The downstream bug for those playing at home](https://bugzilla.redhat.com/show_bug.cgi?id=1189036)

I'm still not convinced about using `profile.d`. Could it mislead people into thinking fish reads `/etc/profile` or any of the other Bourne initialisation files? Do we want to go down the road of having some files that get read sometimes and not others? I found that enormously confusing when starting out with bash and zsh:

> Commands are then read from $ZDOTDIR/.zshenv.  If the shell is a login shell, commands are read from /etc/zsh/zprofile and then $ZDOTDIR/.zprofile.  Then, if the shell is interactive, commands are read from /etc/zsh/zshrc and then $ZDOTDIR/.zshrc.  Finally, if the shell is a login shell, /etc/zsh/zlogin and $ZDOTDIR/.zlogin are read.

Before the advent of autoloading, fish used `/etc/fish.d` for this sort of thing - see [the discussion from 2006](http://sourceforge.net/p/fish/mailman/message/6609911/). In keeping with the current pattern, that would now probably become `$__fish_sysconfdir/config.d/` or something similar.

I would appreciate perspectives from other packagers - @tianon @mithrandi ?

**Comment by ridiculousfish** [comment]
Sounds like I jumped the gun. Sorry zanchey.

**Comment by tianon** [comment]
@zanchey happy to jump in and provide opinions from both a Debian/Ubuntu and a Gentoo packaging perspective :+1:

For things like completions that really oughtn't be modified by users (unless they copy them wholesale), I definitely agree that somewhere in `/usr/share` is the place.  For user-specified stuff, something in `/etc` would be appropriate, but `/etc/profile.d/*.fish` sounds like a step backwards, since `/etc/profile.d` is traditionally for posix-compatible shells, and stretching that to include fish just to avoid a new directory in `/etc` feels wrong IMO.  The bit from the LSB spec that worries me is "The behavior is unspecified if a script is installed in this directory that does not have the suffix .sh.", since that means that implementations could 100% legitimately be sourcing any file in there as if it were posix shell, regardless of extension, and still be following the LSB spec to the letter.

Both Debian and Gentoo have been working to move away from package-installed scripts being in `/etc` because `/etc` is explicitly defined as "user mutable knob storage", essentially.

**Comment by tianon** [comment]
As a user, I'd add that I definitely agree with the sentiment that having so many different files sourced depending on how the shell is run is downright confusing and irritating, as opposed to making simple things like testing for it being an "interactive shell" simpler so we can just "SOURCE ALL THE THINGS" and have "THE THINGS" be reasonably intelligent about whether to perform some bit of logic or not.

**Comment by zanchey** [comment]
I think without clear consensus we should back this out for 2.2. In particular:

> The bit from the LSB spec that worries me is "The behavior is unspecified if a script is installed in this directory that does not have the suffix .sh."

is a concern I had not previously considered.

I still think these are closer to configuration files than say, second-party completions. I think installing global environment variables across shells is rather unwise and I agree with the Debian policy in this area, but both distributors and systems admins are going to want to do it - and importantly, systems admins may want to modify the distribution-supplied configuration.

**Comment by ridiculousfish** [comment]
Reverted as 6faac2d2c8342077eea312ddf6254e3d268e8921.

**Comment by Darkshadow2** [comment]
How about a directory in $__fish_sysconfdir that would work like profiles.d?

**Comment by zanchey** [comment]
`/etc/environment` is another potential target.

**Comment by despairblue** [comment]
What about vendor functions? Where would those go? Arch's autojump ([this file](https://github.com/wting/autojump/blob/master/bin/autojump.fish)) package puts it into `/etc/profile.d/`, which, of course, does not work.

**Comment by faho** [comment]
My 2 cents:

I'd like to step back from "profile.d" a bit here.
As far as I can see, there are three groups of people we should satisfy with our configuration options:

- Upstream software developers or distributions wishing to hook into fish (like the pantheon people, see #1382)

- Admins wishing to add configuration for all users

- Users wishing to add configuration

In particular, admins might wish to override upstream, and users might wish to override both admins and upstream. The admin should not need to touch the upstream directory because package managers (and the user should not have to touch the admin directory because... well, UNIX, privilege separation and all that). Every one of these groups should have their own directory.

Apart from the three groups of people, we have three types of code they might want to add:

- Functions

- Completions

- Event handlers and other code that can't be autoloaded (this is unless we can come up with a better solution to the autoloading problem - calling it "config" as a catch-all for configuration that doesn't fit into the other two is also possible)

We already have the first two for users and fish itself, and I have proposed the third somewhere else already, but I can't come up with a good name for it.

I don't consider /etc/profile.d a good solution because of the undefined behavior - we should not break other shells.

----

So, now, with all that in mind, I propose the following solution:

- Users get ~/.config/fish (replace with appropriate variable)

- Admins get /etc/fish

- Upstream gets /usr/share/fish/vendor_* (since vendor_completions.d already exists)

- Every one of those gets subdirectories "completions", "functions" and "event" (final name TBD) (i.e. vendors/upstream get "/usr/share/fish/vendor_functions.d" and such)

- The preference is User > Admin > Upstream > fish (not too sure about the latter two)

- Completions and functions are autoloaded and named after the program they complete or function they provide, respectively, plus a ".fish" extension

- "Event" files are all sourced at startup in lexical order (unless we find a different solution - naming after the event plus a suffix is also possible to allow for multiple upstreams hooking into the same event)

What does everyone think of this idea?

**Comment by pickfire** [comment]
Good ideo, I even thought about that.

**Comment by Profpatsch** [comment]
For NixOS I thought about sourcing everything in a environment variable on startup.
Stumbled over https://github.com/fish-shell/fish-shell/issues/2391 though.

**Comment by amluto** [comment]
I like this.  I think that, if this happens, that fish should follow the
sysctl / systemd model in which a file in ~/.config/fish/* that has the
same name as a file in /usr/share/fish/* overrides it and that a symlink
from ~/.config/fish/* to /dev/null suppresses a similarly named file in
/usr/share/fish/*, etc.

**Comment by faho** [comment]
@amluto:

That's basically what happens for autoloaded files already (probably not 100% the same, but close enough). 

For the eager-loading stuff this should be implemented as well, I agree.

**Comment by Ahti** [comment]
I like the suggestion by @faho, but there is one thing I think might be missing:

You mentioned the subdirectories "completions", "functions" and "event". One thing `/etc/profile.d` is used for on Arch Linux (at least for the perl package) is adding directories to `$PATH`, and I don't see a subdirectory that this kind of behavior would fit into.

**Comment by faho** [comment]
@Ahti: Check #2498 - after my proposal, I noticed that the "event" directory can be used much more generally, so it's now called "conf.d".

In essence that proposal includes three kinds of directories:

- Completions - autoloaded

- Functions - autoloaded

- Configuration snippets - eagerly sourced

extending $PATH would fall under the third category.

**Comment by Ahti** [comment]
:+1:
