### ISSUE TITLE
Global alias a la ZSH

### ISSUE THREAD

**Issue by iax7** [fish-shell/fish-shell#1963]
I haven't seen in the documentation the use of global alias as ZSH has. That feature is so useful.

**Comment by ridiculousfish** [comment]
What do you use them for?

**Comment by zanchey** [comment]
Global aliases are expanded in any position, rather than just command position. Neither our current I-can't-believe-they're-not-aliases or abbreviations are expanded anywhere except command position.

**Comment by ridiculousfish** [comment]
That matches my understanding. You can even do crazy things like make a global alias with unbalanced quotes, etc. Any fans of global aliases, please share - what do you use them for?

**Comment by terlar** [comment]
I think one use case could be like `ls P` where `P would expand to | $PAGER`. I think most of the stuff seems pretty crazy, but one way to cover a few of these use cases would be to let the abbreviations expand after pipe `|` also. So like

```
abbr jless 'jq -C . | less -R'
```

Then you could do something like this:
```
curl http://api-endpoint.example.com | jless
```

**Comment by balta2ar** [comment]
I'm on zsh and I can't imagine my life without global aliases. Here is my top:

```
alias -g L='| less'
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g WC='| wc'
alias -g SP='| curl -s -F "sprunge=<-" http://sprunge.us'
alias -g J='| j'
alias -g X='| xmlstarlet format'
alias -g XC='| xmlstarlet format | pygmentize -l xml -O encoding=utf-8'
alias -g CC='| ccze -A'

```

Sample usage: `some_command.py G filter WC`, `command.py XC L`. Specifically, `G` and `L` are my favorites.

**Comment by kaleb** [comment]
I also think that it is better to be explicit about pipes.

    some_command.py |G filter |wc

One could always make a key binding, however:

    > bind \cg 'commandline -i " | grep "'
    > some_command ctrl+g filter |wc

**Comment by balta2ar** [comment]
Excuse me, better for what? It never came into my mind to use an alias in scripts, even those that are local to my machine. However, I use global aliases every day when I mess around with the command line because it really helps. I know exactly what it stands for, so implicit pipe is not a problem at all, plus it saves me against typing a pipe which is in fact a key that is placed rather far from the home row (under the backspace on my keyboard).

I came into this issue and commented because I recently was thinking about giving fish a try. Considering the lack of global aliases (my ignorant assumption, I haven't digged into fish docs yet) and their importance to me, and also availability of such plugins for zsh as zsh-autosuggestion, zsh-syntax-highlighting and fzf, I don't clearly see the benefits of switching.

My point is that global aliases is a very nice feature that can attract new users (probably ex-zsh users) and it should be implemented.

**Comment by ridiculousfish** [comment]
Are global aliases in zsh limited to interactive use? That is, can they be used in scripts?

**Comment by balta2ar** [comment]
@ridiculousfish They can be used in scripts.

**Comment by ridiculousfish** [comment]
Supporting them in scripts seems dangerous - what if some function uses one accidentally?

**Comment by balta2ar** [comment]
This is like saying that selling cars is dangerous. What if some person runs over another person accidentally? Anyway, I've never seen anyone complaining about zsh for the support of global aliases. If you don't like it, don't use it. I've personally never had any issues with that, maybe because I 1) only have a few of them 2) they all are upper case 3) I write and run bash scripts, not zsh.

**Comment by ridiculousfish** [comment]
fish relies on functions more heavily than does zsh, e.g. all of the "builtin functions". So when you do this:

    alias -g CC='| ccze -A'

Then scripts can no longer run:

    echo CC

and if they do, the error messages will be baffling. Surely this isn't a desired behavior?

To me, it looks like zsh's global aliases are a syntactic solution to a UI problem. The UI problem is wanting a quick way to apply a frequent suffix; the solution ought to live in the UI as well. I could see this being implemented with key bindings, but extending abbreviations also seems natural to me.

**Comment by zanchey** [comment]
As an example, the default Ctrl-P binding inserts `|less;` at the current position.

**Comment by iax7** [comment]
bind is not the same, I think that ZSH's global alias feels more natural, but I guess this feature could be somewhat equivalent.
Where can I see some good examples about **bind** and **commandline** working together to achieve this? I didn't quite get it from documentation alone.

**Comment by zanchey** [comment]
The output of `bind` will show you some simple examples, and https://github.com/fish-shell/fish-shell/wiki/Bash-Refugees has an example of a reasonably complex setup.

**Comment by GReagle** [comment]
I imagine that to emulate the "global aliases" feature, it would be good to have a prefix key (e.g. Ctrl-x) that is followed by the second key that determines the text.  For example, Ctrl-x followed by g would insert '| grep'.  Ctrl-x followed by t would insert '| tail'.  I cannot get bind to accept a two key sequence though.  Am I missing something?

**Comment by GReagle** [comment]
I did it!  It uses a postfix key rather than a prefix key.  I chose Ctrl-x arbitrarily and because it is free.  So if you type "who cc" then hit Ctrl-x, the command will change to "who | ccze -A"

```
function bind_global_alias
        switch (commandline -t)
  case "l"
    commandline -rt '| less'
  case "h"
    commandline -rt '| head'
  case "t"
    commandline -rt '| tail'
  case "g"
    commandline -rt '| grep'
  case "w"
    commandline -rt '| wc'
  case "cc"
    commandline -rt '| ccze -A'
  end
end

bind \cx bind_global_alias
```

**Comment by iax7** [comment]
@GReagle your solution is even more elegant than global aliases. The only thing is the syntax sugar, the code would be cleaner in ZSH.

**Comment by GReagle** [comment]
@iax7  Thank you!  What a nice compliment.  I hope you find it useful.

**Comment by gawells** [comment]
Thanks GReagle!

I really miss this from zsh:

```
alias -g xp=' | xargs -I @ -n 1'
alias pl="print -l"

pl * xp somecommand @

```

**Comment by c02y** [comment]
Is `global alias` implemented in fish-shell?

**Comment by c02y** [comment]
@GReagle what if I define an alias and want it to be used in pipe, but just pipe, for example, I define an alias for less with some arguments (-RM -s +Gg), whenever I use `less`, it will use those arguments, so sometimes I use less in pipe, but fish shell will parse `less` here as the default `less`  without argument.

**Comment by ridiculousfish** [comment]
fish does not have global aliases today.

However if you want `less` to always be run with certain arguments, you can do that easily, e.g.:

    alias less 'less -RM -s +Gg'

This works in all command positions, including in pipes.

The advantage of this over global aliases is that it will ONLY modify `less` in command positions, e.g. `which less` won't do something terrible.

**Comment by TSFoster** [comment]
If you are determined to have global aliases that work like zsh, you can kind of do it … I doubt this is very 'fishy', but it is **definitely hacky** …

In your `fish_user_key_bindings` function:

```fish
bind \r 'replace_then_execute'
bind -M insert \r 'replace_then_execute' # if you use vim bindings
```

Then in a `replace_then_execute` function:
```fish
function replace_then_execute
    set -l new_command ( \
        commandline \
            | sed 's/ G / | grep /g' \
            | sed 's/ H$/ | head/g' \
    )
    commandline -r $new_command
    commandline -f execute
end
```

It works! But if you use `<space>G<space>` anywhere, it will be replaced with ` | grep ` (e.g. `echo 'A B C D E F G H'` becomes `echo 'A B C D E F | grep H'`).

**Comment by mig-hub** [comment]
I know that this issue is closed but since @ridiculousfish asked what people use global aliases for, I thought I would give my 2 cents because most people seem to use it to add a kind of piping.

My personal attachment to global aliases is that it makes my aliases work even with a command that is taking a command as an argument, like `sudo`, `dotenv`, `bundle exec`. To me it is very helpful and make sense because conceptually it is still a kind of command I am entering.

I understand how it can make things more difficult and can lead to undesired bugs though. To be honest since I use `fish`, I started to use `abbr` instead of `alias`es because I find them more practical, clearer and allow further editing as opposed to just appending. If there was a way to make `abbr` work at any place, not just at the beginning, I'd be quite happy.

**Comment by faho** [comment]
@mig-hub: See #5003.

**Comment by tkkcc** [comment]
I find I only need `less` and `fzf` to view output, others like `grep`, `tail`, `head` are in abbrs and functions
```sh
bind \ep 'commandline -a "|less";commandline -f execute'
bind \eo 'commandline -a "|fzf";commandline -f execute'
```

**Comment by haifengkao** [comment]
It's not difficult to do with [expand](https://github.com/oh-my-fish/plugin-expand)
Just install it `omf install expand`
Then add the following to config.fish
`expand-word -p '^jless$' -e 'echo "jq -C . | less -R"'`

When you type
`curl http://api-endpoint.example.com | jless`
press `<TAB>`
it will be expanded to 
`curl http://api-endpoint.example.com | jq -C . | less -R`
