### ISSUE TITLE
Automatically cluster history

### ISSUE THREAD

**Issue by snnw** [fish-shell/fish-shell#1995]
A sky's-the-limit proposal for improving history, riffing off of @simotek's mention of hiset in #862:

Suppose we clustered commands in history based on proximity in time (possibly differentiating between shell processes).  We would then automatically get a collection of "history sets".  Now, if we see the user enter a sequence of commands that mostly belong to a previously determined cluster, we switch completions to that cluster.  That is, we prioritise completions and suggestions from that specific cluster.

By default, this should be transparent to the user: hopefully, they just get better completions.  Additionally, we could add some management functions to, for example, define names for clusters, and force switching to a certain cluster.  This would cover the 'hiset' use case.

How do people feel about this?  Would this be useful? Is it in line with fish's design goals? @ridiculousfish, @zanchey 

(For background on hiset, see http://simotek.net/tech/projects/opensuse-e/hiset-multiple-history-files-and-sessions-for-bash-and-other-tinkering/ )

**Comment by snnw** [comment]
Hmm, maybe also a solution for #102 ?

**Comment by ridiculousfish** [comment]
@snnw by completions, do you mean tab completions, autosuggestions, or the up-arrow history? Or some combination?

IMO up-arrow history ought to remain a very predictable LRU cache, but management functions are fine as long as they are user-invoked, not something fish does on behalf of the user.

Autosuggestions, on the other hand, should be as smart as we can possibly make them! Any improvements here are welcome. The idea of "history sets" is intriguing, and I'd love to hear your thoughts on the details for how we identify and implement sets.

**Comment by snnw** [comment]
@ridiculousfish, I wasn't clear in my language.  I agree that history sets
are most useful for auto suggestions.  However, I'd imagine that at any
point there are multiple likely next commands.  An auto suggestions
wouldn't allow selecting e.g. the second most likely one.

Yes, up arrow history should be predictable and lru.  But what about down
arrow prediction? :)

I could imagine history sets working for tab completions too.  A likely
next command (or argument) would appear before all other possible
completions, if there's more than one completion.  But maybe this would be
too confusing..

I'll try to think of a simple way to characterise and compute history
sets.  How hard could it possibly be, right? ;)

**Comment by simotek** [comment]
@ridiculousfish the core idea of my hiset idea swaps history files this gives you a predictable up history but not the last run commands, Similar could be implemented from within 1 file using a label. If you have a command that jumps you to a label in the history file so that the up history is predictable from there and new commands get appended at the point of the label and the label moves down. The other thing to keep in mind that I find useful with the separate history file approach is that commands that have been run in a different history file last in history for a lot longer. There are some tasks I only do every 3-6 months and other projects I don't touch for several months at a time so I put the history in another file so it doesn't get pushed out by the commands i use everyday that I don't care about. So if we went down the label path with 1 file it would be nice if labeled commands didn't get pushed out by non labeled ones. 
My other use case is for most projects I work on I set up a alias / function that sets some environment vars, sets a history file and cd's to the correct directory which is useful when working on multiple projects at the same time.

**Comment by zanchey** [comment]
There is some discussion in #940 on things getting "pushed out" of history.

**Comment by snnw** [comment]
I've been thinking on this.

First, lets see how we would build a history set.  Lets say we have a two commands `cmd1` and `cmd2`.  `cmd1` and `cmd2` are in the same history set iff one of the following conditions holds:
- `cmd1` and `cmd2` were executed in 'close' succession multiple times
- there are two commands `cmd1'` and `cmd2'` that are similar to `cmd1` and `cmd2`, and `cmd1'` and `cmd2'` are in the same history set

The exact requirements for 'close succession' and 'multiple times' would be up for discussion and experimentation.  Initially, I'd say 'close succession' means with at most 2 intermediate commands, and 'multiple times' is at least 3 times.  Commands are similar if they differ in at most one argument.


I personally quite like the idea of down-arrow predictions, but I wonder how it would work in practice.  @ridiculousfish what do you think?

With regards to @simotek's use case, I'd say that explicitly defining and switching between sets would cover this neatly.  I'm not sure how this would interact with the automatic history sets, though.

**Comment by quartzjer** [comment]
I used a technique this to have a unique history-per-window (and also keep more of my history logged in individual sessions):

```
temp=$(tty) ; echo ${temp:5}
HISTFILE=~/.hist/term-${temp:5}.hist
```

It's the biggest thing I'm missing so far since I've converted to fish, and I'd love to import all my 100k+ lines of old history yet too :)

**Comment by krader1961** [comment]
If I ever get around to completing the change I've started to implement issue #102 (currently ~50% done) is that sufficient to address this issue.

**Comment by simotek** [comment]
yep for me it is, and is how I did it in bash, I just wrote a function to easily swap between history files
