### ISSUE TITLE
Distinguishing string and array variables to allow string manipulation

### ISSUE THREAD

**Issue by Undeterminant** [fish-shell/fish-shell#1997]
(We'd treat each character as a byte or unicode code point, depending on how we want to do it.)

There's a reasonable amount of desire for string manipulation in fish, and being able to use the slice syntax for arrays on strings would be very useful. Unfortunately, this would be a breaking change.

The main idea is that all variables can be arrays, although each array element is a string. If you use the standard `$var` syntax, you'll get the first argument of the array, or an empty string if the array is empty; syntax like `$var[-1]` would give you the last character, `$var[1..-2]` would chop off the last character, etc.

To access an array, you would use a different syntax, like `@var`. This would clearly indicate that the variable is an array, and slicing on the array would work as normal. You could do things like `@var[3][-1]` to do string slicing as well.

Additionally, a new builtin would be added, `length`, which takes in exactly one argument and returns the length of the string. We would likely want to make sure that `length` executes in `O(1)` time, which may involve converting some of the strings that we store for variables from `char*` to `std::string`, although I haven't actually looked at the code to verify this.

**Comment by anordal** [comment]
We don't _need_ to make a distinct string type of variable — "$var" and $var[1] are already strings.

**Comment by anordal** [comment]
Regarding byte vs codepoint, that's the tip of a little iceberg: there are many potentially useful ways to index a string and measure its length:
* by byte
* by code point
* by character — count _combining codepoints_ as part of the character. While the character ẍ always takes two codepoints, ë is encoded as two codepoints in Mac OS X and one in Linux. In any case, one character.
* by display width — ignore nonprintable characters and terminal escape codes, and account for double-width characters. \r and \n are nontrivial, but simplest to ignore.

Considering this (or at least possibilities for future expansion), I'm thinking a command is more appropriate & fishy:
`stringslice [--byte|code|char|width] [--length] $from $to $string`
alternatively
`substr [--byte|code|char|width] [--length] $from $length $string`
where `--length` would return the length of the string instead of the string.

**Comment by faho** [comment]
I believe this solved in a more fishy (and IMHO better) way by #2296.

**Comment by techtonik** [comment]
So, how to do `somevar[4:-3]` as in Python, but in fish shell?

**Comment by krader1961** [comment]
> So, how to do somevar[4:-3] as in Python, but in fish shell?

Use the `string sub` builtin. Which is obviously not as concise as Python slice syntax but still usable . Please don't respond here since this discussion belongs in issue #4049 that you opened.

**Comment by techtonik** [comment]
@krader1961 there is no way to make `somevar[4:-3]` with `string sub` alone.
```
string sub [(-s | --start) START] [(-l | --length) LENGTH] [(-q | --quiet)]
           [STRING...]
```

**Comment by krader1961** [comment]
> there is no way to make somevar[4:-3] with string sub alone.

Yes, I know that, @techtonik. But enhancing that command to have a `-e` / `--end` flag to support slicing is trivial. I probably should have made that clearer in my previous comment. If we did make such an enhancement would that satisfy you? Please put your response in issue #4049 rather than in this issue.
