### ISSUE TITLE
I want to use fish_config on a remote server but it's not possible anymore because it tells me to open a local file instead of using a port like it used to

### ISSUE THREAD

**Issue by hnsl** [fish-shell/fish-shell#2024]

**Comment by hannes-landeholm** [comment]
Found workaround: ssh port forwarding. -L 8000:localhost:8000

**Comment by ridiculousfish** [comment]
It seems OK for `fish_config` to support an argument to enable remote connection, if you want to take it on.

**Comment by almson** [comment]
@hnsl SSH port forwarding fails with `channel 3: open failed: connect failed: Connection refused` probably because of how the fish server binds the port. `lynx` seems unable to render the page. What am I to do?

**Comment by almson** [comment]
I just want to change the color theme. I can't figure out how to 1) edit some sort of config file (instructions talk about setting env variables, but I'm assuming those aren't permanent) and 2) change the color theme without editing each color individually.

**Comment by almson** [comment]
I'm a bit lost trying to understand the _threat model_ under which the config webpage security decisions were made. What attacker are we protecting against? A persistent unprivileged process that wishes to connect to the server and change the prompt in the hope that the user will start a privileged shell (sudo su)?

Can this process access the terminal window (through the X security hole)? 

 - Yes: Then you're screwed. (Linux security sucks :( )
 - No: Then show a password in the terminal that has to be entered into the website over a self-signed HTTPS session. Allow anyone to connect. Don't hide the URL.

**Comment by zanchey** [comment]
The problem is that the `fish_config` server allows arbitrary variables to be set and fish code to be executed - that's how the prompt functionality (and others) works. The changes we made in 2.1.1 were to prevent connections from other hosts but also from other users on the same machine.

In particular, users on the same machine can connect to any loopback-bound ports (hence the use of the token), but on some systems they can also read the arguments to programs (with `ps axuw` or similar) - which means that running "some-browser http://localhost/my-url-here" from fish makes the authentication token visible.

Having a password you can copy and paste sounds like a great idea - perhaps the 403 handler should ask for it?

**Comment by almson** [comment]
@zanchey That was my understanding as well, hence the proposed solution. Simple URL + publicly-bound port + HTTPS + password. I could then forward the relevant port in SSH and connect.

**Comment by dudeofawesome** [comment]
I came across this issue as I was trying to set my syntax highlighting colors on a remote machine. If anyone else is trying to solve this as well, I've written a simple script to export your defined colors from one machine, and set them on another.

https://gist.github.com/dudeofawesome/ce2d84b08a508fdaf0a066ca039c8ce8

**Comment by faho** [comment]
@dudeofawesome: That script is in dire need of a for-loop. I have played around with

```fish
for i in (set -n | string match 'fish*_color*')
    echo $i (set_color $$i)$$i(set_color normal)
end
```

which will print all the color variables in the actual color. Note the use of "$$i" to get the contents of the variable named by $i.

**Comment by dudeofawesome** [comment]
@faho That's a good idea. I didn't know about `set -n`.

**Comment by krader1961** [comment]
Closing as a duplicate of #1916.
