### ISSUE TITLE
Items are added to history too early

### ISSUE THREAD

**Issue by kballard** [fish-shell/fish-shell#2028]
New commands are added to the history before the command itself is evaluated. This means that `$history[1]` expands to the current command, as does `history | head -n1`. I've been informed that Fish v2.1.2 does not do this (they expand to the previously-executed line instead), and it also seems rather surprising for a command to be considered "history" when it hasn't executed yet.

I believe this was caused by aa1b065dd1c03f7c0867d002badcf0dc88feb3c4.

/cc @ridiculousfish

**Comment by ridiculousfish** [comment]
`> echo $history[1]
echo $history[1]
`
Whoa, meta.

**Comment by ridiculousfish** [comment]
Nice find by the way.

**Comment by ridiculousfish** [comment]
In order to make commands like `reboot` appear in the history, we need to add them before the command is executed. But of course the command itself should not be able to see them. So I guess we need to temporarily hide the most recent item while he command executes.

**Comment by snnw** [comment]
+1 I've seen this as well, but didn't know it was a bug.  I'll whip up a
patch of no one beats me to it.

**Comment by ridiculousfish** [comment]
These are some fixes I've considered:

1. Add a `is_pending` bool to `history_item_t`. I dislike this because, after we execute the command, we need to clear the pending flag, and there's no easy way to do that except by iterating through all of the new items.
2. Add a `first_pending_new_item_index` offset in history_t, similar to `first_unwritten_new_item_index`. Then `history_t::item_at_index` returns values counting from this index, instead of from the end of the item array. This is not so bad, except a little more complex than I'd like.
3. Add a `pending_items` array, similar to `new_items`. This avoids having to change `item_at_index`. This raises the question of how the pending item is handled during save. Probably the simplest thing is to just not save pending items, until we mark them as not pending. We already have some hacks for commands `reboot` and `exit` to trigger an immediate save; we can extend that to not mark the item as pending. This seems like the cleanest approach.

**Comment by ridiculousfish** [comment]
I noticed that a simple flag was sufficient. Thanks for reporting this.

**Comment by snnw** [comment]
Nice fix! :D
