### ISSUE TITLE
syntax-highlight `type FUNCTION` output

### ISSUE THREAD

**Issue by cben** [fish-shell/fish-shell#2059]
When `type` displays function source, it would be nice to syntax-highlight it same way as it would look in command line.
Not sure if the lower-level `functions FUNCTION` should also do it.
Is the syntax highlighter exposed for scripting?

**Comment by ridiculousfish** [comment]
On master and upcoming 2.2 beta, you can do this:

    functions cd | fish_indent --ansi

I think it should not do this by default, because you might be piping the function to a file and then you don't want the escape sequences in it. Ok to close?

**Comment by cben** [comment]
Cool.

That's why I wasn't sure it belongs in `functions` but I think `type` is a
user-facing command.
Plus we can do the standard dance of inhibiting highlighting when stdout is
not a terminal...
I can send a PR if you think that's a better idea.

**Comment by ridiculousfish** [comment]
Sure, that sounds fine to me.

**Comment by lordlycastle** [comment]
Any progress being made in this?

**Comment by faho** [comment]
@lordlycastle: No. I think I tried it a while ago and there was something blocking me, but I can't quite recall.

**Comment by lordlycastle** [comment]
@faho Maybe I'm missing something, but isn't it just piping the output of `type` through `fish_indent --ansi` whenever it's a function? I had a look through the `type.fish` file and I think the relevant part is:

```
if functions -q -- $i
	set res 0
	set found 1
	switch $mode
		case normal
			printf (_ '%s is a function with definition\n') $i
			functions $i

		case type
			echo (_ 'function')
	end
	if test $multi != yes
		continue
	end
end
```
The `normal` case is where the function is printed so syntax highlight would be required. We would have to check if the output is to terminal (_don't know how to do that_), and pipe through `fish_indent --ansi`

**Comment by krader1961** [comment]
> We would have to check if the output is to terminal (don't know how to do that)...

`if test -t 1`

**Comment by faho** [comment]
Unfortunately I can't find what issues I had previously.

However, this is still a bit weird because there's no way to make fish_indent do _just_ highlighting, so it will do its thing in addition to highlighting (and "--no-indent" makes it remove _all_ indentation). This means this function:

```fish
function bar --description 'Display percentage bars'
	for num in $argv
		test $num -ge 88; and printf "█"; and continue
		test $num -ge 76; and printf "▊"; and continue
		test $num -ge 64; and printf "▋"; and continue
		test $num -ge 50; and printf "▌"; and continue
		test $num -ge 38; and printf "▍"; and continue
		test $num -ge 26; and printf "▎"; and continue
		test $num -ge 14; and printf "▏"; and continue
		test $num -lt 14; and printf " "; and continue
	end
end
```

will be turned into this:

```fish
function bar --description 'Display percentage bars'
    for num in $argv
        test $num -ge 88
        and printf "█"
        and continue
        test $num -ge 76
        and printf "▊"
        and continue
        test $num -ge 64
        and printf "▋"
        and continue
        test $num -ge 50
        and printf "▌"
        and continue
        test $num -ge 38
        and printf "▍"
        and continue
        test $num -ge 26
        and printf "▎"
        and continue
        test $num -ge 14
        and printf "▏"
        and continue
        test $num -lt 14
        and printf " "
        and continue
    end
end
```

I could swear there was some bug caused by this, but I can't find it and it's driving me crazy.

>if test -t 1

(#1228 - currently, you'll want `command test` or `isatty`)

**Comment by lordlycastle** [comment]
Oh! I see what you mean. I think, from 5 minutes of looking at `fish_indent.cpp` file, the reason why it changes the `;`  to `\n` is because both `\n` and `;` have same type i.e. `parse_token_type_end`.
In `fish_indent.cpp::prettify_node_recursive`:
```fish
if (node_type == parse_token_type_end)
    {
        out_result->push_back(L'\n');
        *has_new_line = true;
    }
```

I couldn't find where and how they're defined. I can see many problems occurring because `;` __is__ end of a command. It would be easier to _hack_ `fish_indent` then try to do a proper fix, IMO. If there is currently a way to distinguish between `;` and `\n` in the `fish_indent` file then it would be as simple as simple:
```fish
if (node_type == parse_token_type_end)
    {
        if (node.currentChar == '\n'){
            out_result->push_back(L'\n');
            *has_new_line = true;
        }else {
            out_result->push_back(L';');
            *has_new_line = false;
        }            
    }
```
Then again, I don't know much about C++, or FISH. I also don't fully understand what a _node_ exactly is.

How about temporarily we at least have some syntax highlight, even though it messes the format up?

**Comment by faho** [comment]
>How about temporarily we at least have some syntax highlight, even though it messes the format up?

I'm uncomfortable with adding this for the next release because it's rather late in the cycle, and for the one after that we'll probably get some fish_indent fixes. I'll tag this so we'll revisit it.

**Comment by krader1961** [comment]
I agree with @faho. We should not be introducing such changes until 2.3.0 is out the door. I was going to open an issue to remind me to make the above mentioned change but found #2646 was already opened. We absolutely want `fish_indent` to be the equivalent of `gofmt` for the Go language: the final word on how to format a fish script.

**Comment by floam** [comment]
Never noticed this issue. 2.3.1 does this, when interactive.
