### ISSUE TITLE
cd ... -> cd ../..

### ISSUE THREAD

**Issue by pickfire** [fish-shell/fish-shell#2109]
I like the function in zsh to have `cd ....` -> `cd ../../..`

**Comment by xfix** [comment]
I don't like the proposed syntax myself, if anything, because it's inconsistent. Sure, it could work for `cd`, but what about other commands.

**Comment by pickfire** [comment]
What do you mean? I mean to only use it in `cd`.

**Comment by xfix** [comment]
Let me explain once again. The issue is that it caused inconsistent behaviour of `cd` vs other commands. If an user can do this.

```fish
cd ...
```

Then you also can expect this to work.

```fish
ls ...
```

That said, if you want this to work, you can use bindings to make this work. Save this as some file, use `fish somefile`, and restart fish. After doing that `...` should work as you expect.

```fish
function bind_period
    if commandline -t | sgrep -q '\(^\|/\)\.\.$'
        commandline -i /..
    else
        commandline -i .
    end
end

function fish_user_key_bindings
    bind . bind_period
end

funcsave bind_period
funcsave fish_user_key_bindings
```

**Comment by pickfire** [comment]
Yeah, I had never thought of `ls ...`. Good idea, great job, @xfix.
