### ISSUE TITLE
functions -e ought to not allow autoloading

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#213]
When you use `functions -e` to erase an autoloader function, it just gets autoloader again immediately. We should be smart about this and set a tombstone function to block it.

**Comment by ridiculousfish** [comment]
Very nice fix. Merged with rebase as 73f344f41bd20c005a0f5b810dc20229392f2bf8. Thanks!!

**Comment by RomanHargrave** [comment]
@ridiculousfish @snnw It looks like `73f344f` or similar somehow borked autoloading hidden functions. I say this because it is the only major modification to either `function.cpp` or `builtins.cpp` between effected revisions. This is [causing issues with the oh-my-fish startup script](https://github.com/bpinto/oh-my-fish/issues/420#issuecomment-90778090). In short, OMF uses a few `_functions` defined in `$oh_my_fish_path/functions/_$name.fish` during the plugin loading process. As of `e421c12`, they were being discovered correctly, however, as of `8742867` they are being ignored by the autoloader, thereby creating a waterfall of errors that exceeds my scrollback.

**Comment by snnw** [comment]
@RomanHargrave Thanks for the heads-up.  Confirmed on my machine.  I'll try to see what's going on..

**Comment by snnw** [comment]
@ridiculousfish 
This is what happens:
If `fish_function_path` has changed, then `autoload_t::load` evicts all its nodes, tombstoning any autoloaded functions, which then never get autoloaded again, resulting in oh-my-fish missing a few functions.  I think we shouldn't tombstone functions in this case.  

@RomanHargrave 
A PR with a quick fix (with limited testing), which fixes this for me, is incoming.  Can you please test?

**Comment by ridiculousfish** [comment]
Nice analysis.
