### ISSUE TITLE
complete choices for a2enmod / a2dismod etc.

### ISSUE THREAD

**Issue by n3o77** [fish-shell/fish-shell#2141]
i'm having trouble to get auto completion running for a2enmod, a2dismod, a2ensite and so on. with bash i can just type "a2enmod <tab>" and get a list of all available mods. is there a way to do this with fish as well? another problem i'm having is that i don't get proper suggestions for sudo. when i'm typing as my user "sudo a2e<tab>" I don't get any suggestions, but executing "sudo a2enmod" works just fine.

thank you very much in advance!

**Comment by zanchey** [comment]
The first problem is easy enough to fix - completions for `a2{en,dis}{mod,site}` are pretty easy to write.

The second example works fine for me on 2.1.1 and 2.2b1 - what version are you running?

**Comment by n3o77** [comment]
Thank you very much!
I'm running version 2.1.1 on debian wheezy.

**Comment by faho** [comment]
The completions are now written, so the question remains:

Is the sudo thing still occuring? Does it also happen with fish 2.2.0?

**Comment by n3o77** [comment]
Yes, I'm still having the problem with sudo in 2.2.0. Completions aren't in 2.2.0, right?

**Comment by faho** [comment]
No, they aren't - though you can download them manually and add them to ~/.config/fish/completions/.

Do you have any sudo function/alias (`type sudo`)? Otherwise [__fish_complete_subcommand_root](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_complete_subcommand_root.fish) is not working as it should.

**Comment by n3o77** [comment]
OK i just took another look and it seems that it's partially Working. See screenshots.
```
/v/www  type sudo
sudo is /usr/bin/sudo
```
As user:
![screen shot 2015-07-16 at 20 20 19](https://cloud.githubusercontent.com/assets/321891/8731539/57731132-2bf8-11e5-9f8d-efd66d7b1f3a.png)

As root:
![screen shot 2015-07-16 at 20 20 34](https://cloud.githubusercontent.com/assets/321891/8731540/57777aec-2bf8-11e5-8d15-a90f9e076e18.png)

**Comment by faho** [comment]
I have an idea:

     getfacl (which a2enmod)

It appears that fish will not complete commands you can't execute (though I'll be damned if I find where that's defined).

**Comment by n3o77** [comment]
```
root@my ~# getfacl (which a2enmod)
getfacl: Removing leading '/' from absolute path names
# file: usr/sbin/a2enmod
# owner: root
# group: root
user::rwx
group::r-x
other::r-x
```

**Comment by zanchey** [comment]
I think the problem here is that because PATH is set as a local variable in the `__fish_complete_subcommand_root` scope, it is shadowed in the `__fish_complete_subcommand` scope. Certainly adding `--no-scope-shadowing` to the definition of `__fish_complete_subcommand` seems to fix things.

**Comment by zanchey** [comment]
This worked in 1.23.1 (!) but I think b0c6d891e967 broke it well before 2.0.0. I don't think the change is wrong; certainly it doesn't seem wise to alter the global PATH, but I'm not 100% sure that `--no-scope-shadowing` is sensible in `__fish_complete_subcommand`; thoughts welcome!

**Comment by faho** [comment]
Either adding an option to `__fish_complete_subcommand` or duplicating it in `__fish_complete_subcommand_root` should work.

**Comment by faho** [comment]
>I'm not 100% sure that --no-scope-shadowing is sensible in __fish_complete_subcommand; thoughts welcome!

@zanchey: As far as I understand, "--no-scope-shadowing" means that the calling "local" scope is inherited, right? __fish_complete_subcommand defines all variables it uses as local and __fish_complete_subcommand_root doesn't use any variables of the same name after the call (in fact it does nothing). 

So I don't see any bugs popping up because of that change - though it'd mean we'd have to be careful. But given that the last change to __fish_complete_subcommand was in 2012, I think it's rather stable.

The other options I see are:

- Duplicate __fish_complete_subcommand's logic in __f_c_s_r (as in "literally copy all the code in")

- Add an option to __f_c_s to take a path

**Comment by zanchey** [comment]
I went with the easy option in f68b339 - this should work now.
