### ISSUE TITLE
Why fishshell.com and not fishshell.org

### ISSUE THREAD

**Issue by pickfire** [fish-shell/fish-shell#2142]
I think that fishshell which is a non-profit organization should be fishshell.org which is the normal domain for non-profit, I could not find out where fishshell gain money from. Is there any reason to use .com and not .org?

**Comment by ridiculousfish** [comment]
`http://fish.sh` is the best!

**Comment by pickfire** [comment]
On Sun, Jun 21, 2015 at 01:58:57AM -0700, ridiculousfish wrote:
>`http://fish.sh` is the best!

Don't use http, +1 to ***https//fish.sh***

-- 
 _____________________________________
< Do what you like, like what you do. >
 -------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by zanchey** [comment]
Maybe when letsencrypt gets off the ground.

**Comment by nyarly** [comment]
Is $10 too much to pay for a cert? "fish.sh" probably cost more than that :)

**Comment by ridiculousfish** [comment]
fishshell.com is currently hosted as S3. Does that support HTTPS? My understanding is that it does not, but I'm far from an expert in this area.

**Comment by nyarly** [comment]
https://bryce.fisher-fleig.org/blog/setting-up-ssl-on-aws-cloudfront-and-s3/

**Comment by pickfire** [comment]
Well, let's wait for September 2015 and get a free certificate from https://letsencrypt.org/. And how much does .com and .org cost?

**Comment by pickfire** [comment]
It seems like lets' encrypt is here now and [fish.sh](fish.sh) seems to redirect the page to fishshell.com

**Comment by alphapapa** [comment]
```sh
➤ whois fish.sh

Domain : fish.sh
Status : Live
Expiry : 2016-11-30

Owner  : ridiculous fish
Owner  : 123 Fake Street
Owner  : Nowhere
Owner  : CA
Owner  : USA
```
:D

**Comment by ridiculousfish** [comment]
they found my address :astonished:

**Comment by pickfire** [comment]
Maybe that is where you host as it have a lot of site there, but you seem to have timezone `-7`, I think it is USA. Am I correct?

**Comment by krader1961** [comment]
Is anyone advocating for this change willing to both pay for the new domain(s) and put in the effort to make transition to those domains a reality?

The reality is that the the ".com", ".org" distinction became irrelevant almost immediately after the WWW (world wide web) was created. And, as a grey beard who was active before the HTTP/WWW "internet", I can attest that the distinction was frequently violated prior to that innovation.

I agree that it would be nice if we had a "fishshell.org" domain and deprecated the "fishshell.com" domain. But unless someone is willing to put in the work to do so and pay for the transition it won't happen. I'm looking at you @pickfire since you opened this issue.

**Comment by pickfire** [comment]
@krader1961 I think I am not willing to pay for the domain since after converting my currency to usd, it just seems to rediculous to rent it at the expense of 1 week food for just a year. But I am still able to suggest alternatives like the `.tk` domain, I am also using that for my personal website.

**Comment by krader1961** [comment]
Understood. My proposal that you pay for it, @pickfire, was rhetorical rather than serious. I was just trying to make the point that such a change is unlikely unless we get a corporate sponsor or someone working on the project has enough disposable cash to be willing to purchase the domain with a five year expiration so no one has to pay to renew it before we retire fishshell.com.

**Comment by zanchey** [comment]
I don't think there's a huge amount of utility in moving, so I'm going to close this for now.
