### ISSUE TITLE
Sort abbr --show

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#2156]
It would be really nice when doing an `abbr --show` to list them alphabetically. I suppose one way to do that would to actually store them that way. 
#731

**Comment by scooter-dangle** [comment]
You can always just do `abbr --show | sort`, though, right? Wouldn't this violate fish's goal (assuming it's still relevant) of following the Unix small, composable tools?

It currently lists them by the order in which they were added, which is still something informative and wouldn't be discoverable by a tool other than `abbr` if you needed to know that for some reason.

**Comment by krader1961** [comment]
In this case, @scooter-dangle, I think the principal of friendliness outweighs the other considerations you mentioned. In particular many of us always define abbreviations in our *config.fish* so there isn't really any such thing as a meaningful order they were added. Too, for anyone interested in such information it would be better for them to add comments to each `abbr` command in their *config.fish*.

P.S., What I actually do is the following to make it maximally efficient and the file containing that code is only run for interactive shells.

```
# Increment the following number every time this file is edited.
set -l _abbr_generation 2
if test "0$_abbreviations_loaded" -lt $_abbr_generation
    set -U _abbreviations_loaded $_abbr_generation
    abbr -a -- - 'cd -'
    # more abbr commands
end
```

**Comment by scooter-dangle** [comment]
I was thinking of the order preservation being more useful for automated tools that one might use to modify/update/install/uninstall abbreviations. I don't have any particular tools at hand that do that, but in those cases, it's often nice to have the programmatic list generation rather than relying on having to parse _config.fish_ with such a tool.

I like fish primarily because its various completion features have made the command line more approachable. I can more easily explore how to use a standard Unix command than I could with bash or—to a lesser extent—zsh. As a result, I'm often suspicious of adding ad-hoc functionality to fish commands that is easily obtained by the Unix tools fish lets me more easily explore and take advantage of.

(Notice, I'm totally okay providing my two cents, but have I contributed any code to fish? No! What a moocher! As a dolphin I knew once said, "Thanks for all the fish!")

**Comment by krader1961** [comment]
No worries, @scooter-dangle. Even if you never contribute a patch we highly value users taking the time to comment on open issues. We just hope you understand when we reach a different decision than you would have made :smile:

FWIW, I'm still unclear on how having the `abbr --show` command output the abbreviations in the order they were added is useful. It's also currently just an artifact of the implementation with no explicit guarantee that will be the case now or in the future. So if you can make a convincing argument for preserving FIFO ordering of the entries the first thing we should do is update the documentation to lock that behavior in place.

**Comment by ElijahLynn** [comment]
My initial use case for opening this issue was to export just the abbreviations into their own file, for use with Homeshick (dotfiles/config backup). I currently am doing a `abbr | sort` and then I actually reimport them back into fish. I didn't realize I could manage them in config.fish but on second thought then I wouldn't get the low friction way to manage them the way I manage functions via the CLI.

**Comment by zanchey** [comment]
Having stable output sounds sane.

**Comment by ElijahLynn** [comment]
Just want to clarify that while we can put abbreviations in our config.fish, that is not the way I use fish. One thing I really love about fish is to make functions on the fly. By using `function` and `funcsave` and `funced`. I also really like managing abbreviations via commands and not files as well.

**Comment by faho** [comment]
This has now happened as a side-effect of changing abbr's storage. The output is generated by going through `set --names`, and that is sorted by scope and then name, since that's how the underlying storage is sorted.

Which seems good enough.
