### ISSUE TITLE
short option name for `read --shell` conflicts with planned `--silent`

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#2166]
Apropos of #838, I think the short name for `read --shell` to should be something that isn't `-s`, and I think this change should be made before 2.2.0 to avoid backward-incompatible change in the future. `read -s` is a reasonably common construct from other shells and a conflict is not helpful to migrants.

How about `read -S`?

**Comment by zanchey** [comment]
Why did I think `--shell` wasn't released yet? It's been in fish for forever.

**Comment by cben** [comment]
I presume this is closed because we can't break backward compatibility?

For the record, another read option that'd be nice if it were bash-compatible is `-p`.
It's named exactly the same, but unlike bash where it takes a string, in fish it executes it as a command.
It's also confusing the long form is called `--prompt`; it should have been `--prompt-cmd` or `--prompt-command`.  Then there could also be a separate `-p`, `--prompt` which takes a string (I dare say  `--prompt-cmd` behavior is esoteric enough to not deserve a short form).

The thing with bash's `read` is that it has *only* short options.  If bash had `cmd --some-opt` and fish had `cmd --another-opt`, that's great; when both have `cmd -o` but behave differently, that's confusing.

**Comment by bucaran** [comment]
@cben This can be achieved in userland more or less easily. I just published [this](https://github.com/fishery/get) yesterday.

**Comment by Pysis868** [comment]
[GitHub - fish-shell/fish-shell - fish 2.6.0 (released June 3, 2017)](https://github.com/fish-shell/fish-shell/releases/tag/2.6.0):

> - ...
> - `read` supports a new `--silent` option to hide the characters typed (#838), for when reading sensitive data from the terminal. `read` also now accepts simple strings for the prompt (rather than scripts) with the new `-P` and `--prompt-str` options (#802).
> - ...
