### ISSUE TITLE
`fish_config` command opens Wine's Notepad on my Ubuntu system

### ISSUE THREAD

**Issue by mandx** [fish-shell/fish-shell#2196]
$ fish_config
    Web config started at 'file:///home/mandx/.cache/fish/web_config-IOPRCS.html'. Hit enter to stop.
    fixme:exec:SHELL_execute flags ignored: 0x00000100
    ::ffff:127.0.0.1 - - [13/Jul/2015 10:15:38] code 403, message Forbidden, path /favicon.ico

But the window that opens is Wine's Notepad, instead of my default browser. If I copy the `file:///...` URL and paste it on my browser it works fine. I think it's trying to open the URL using `gvfs-open` to launch the browser:

    gvfs-open: file:///Z:/home/mandx/.cache/fish/web_config-27AKAI.html: error opening location: Error when getting information for file '/Z:/home/mandx/.cache/fish/web_config-27AKAI.html': No such file or directory

I think the `fixme` line is output from Wine, not from Fish.

**Comment by faho** [comment]
fish uses `xdg-open` (which in turn should redirect to gvfs-open) to open that file, which uses the xdg-mime database, which is also most likely what powers your DE's file associations.

Wine (annoyingly) likes to grab a few default associations and you need to fix that, but **it's not a fish issue**.

See the output of `xdg-mime query default text/html`, which should be something like "wine-notepad.desktop".

Otherwise, you can set "$BROWSER", which fish seems to use before resorting to xdg-open.

**Comment by mandx** [comment]
I understand that it is not a Fish issue, (and I went with the `$BROWSER` solution). And also, instead of running "open this file", Fish could run "open this file with the system's default web browser".

**Comment by faho** [comment]
Whatever `xdg-open` runs, _is_ the "system default". Or close enough. That's how this stuff is supposed to work. Try opening a .html file in your filemanager, it should also open wine's notepad.

**Comment by mandx** [comment]
Yep, it does. Thanks!
