### ISSUE TITLE
alias throws error after upgrade to 2.2.0

### ISSUE THREAD

**Issue by yangchenyun** [fish-shell/fish-shell#2220]
whitespace has to be escaped for this alias to work.
```
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'
```

throws:

```
- (line 1): begin; function chrome --wraps /Applications/Google\;  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome $argv; end
                   ^
from sourcing file -
	called on line 60 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/eval.fish

in function 'eval'
	called on line 69 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/alias.fish

in function 'alias'
	called on line 66 of file ~/.config/fish/functions/aliases.fish
	with parameter list 'chrome=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'

from sourcing file ~/.config/fish/functions/aliases.fish
	called on line 151 of file /usr/local/Cellar/fish/2.2.0/share/fish/config.fish

in function '.'
	called on line 3 of file ~/.config/fish/config.fish
```

**Comment by faho** [comment]
Urgh, yeah.

alias.fish contains this little nugget:

    # Extract the first command from the body
        switch $body
                case \*\ \* \*\t\*
                        # note: strip leading spaces if present
                        set first_word (echo $body|sed -e 's/^[[:space:]]\{1,\}//;s/[[:space:]].*//;q')
                case '*'
                        set first_word $body
        end

What I don't get is why we not just assume that the first argument is the name, the second is the command and all the rest are options?

**Comment by faho** [comment]
Hmm... this is a bit harder than I thought.

The issue is we want to support both "alias cod gadus" and "alias cod=gadus", and with whitespace and additional arguments in the latter, while "function --wraps" can't take arguments, only the filepath. Of course it would be easiest if it would just throw those away, but it might also be nice if "--wraps" could _use_ them, to select certain completions. That way I can do "alias gl=git log" and get completions for git log.

The easiest solution to the entire thing would be to mandate alias as "alias $name $command $arguments", i.e. leave the quoting up to the user.

**Comment by faho** [comment]
I've worked further on this, and the approach of doing "alias" with a function has one inherent limitation:

We need to reconstruct all the quoting and masking to what it would need to be if it were to be interpreted as a commandline. And then we need to do some of that again so `eval` doesn't mess everything up.

I now have something that can deal with spaces in the name of the program (if it was quoted in the first place, since otherwise fish wouldn'd recognize it as a command), arguments (especially arguments with matching parens - i.e. those that would trigger command substitution), but it absolutely _can't_ have the entire command as one argument, i.e. what used to be "alias f='fry salmon'" now _needs_ to be "alias f=fry salmon". If it is quoted, it interprets it as a program name with whitespace.

It looks like this:

```
function ali
	if not count $argv
 		echo "Fish implements aliases using functions. Use 'functions' builtin to see list of functions and 'functions function_name' to see function definition, type 'help alias' for more information."
		return 1
	end
	set -l name
	set -l exe
	set -l args
	switch $argv[1]
		case "*=*"
			set -l IFS "="
			echo -e $argv[1] | read name exe
			set -e argv[1]
		case "*"
			if test (count $argv) -lt 2
				echo "Not enough arguments"
				return 1
			end
			set name $argv[1]
			set exe $argv[2]
			set -e argv[1]
			set -e argv[1]
	end
	set args $argv
	# In case $exe contains spaces or matching parens, we need to escape them for eval
	echo $exe  | sed -e "s/ /\\\ /g" -e 's/(\(.*\))/\\\\(\1\\\\)/g' | read exe
	# Same for $args and matching parens (think emacs)
	echo $args | sed -e 's/(\(.*\))/\\\\(\1\\\\)/g' | read args
	# Same for matching parens
	echo "NAME: $name"
	echo "EXE: $exe"
	echo "ARGS: $args"
    eval "function $name --wraps $exe; $prefix $exe $args \$argv; end"
end

ali mu4e emacs --eval "(mu4e)"
ali mu3e=emacs --eval "(mu4e)"
ali todo emacs ~/docs/org/TODO.org
ali abs $HOME/dev/abs-replacement/abs.sh
ali upo upower -i /org/freedesktop/UPower/devices/battery_BAT0
ali f "~/.local/bin/fried catfi.sh" --help
ali g ~/.local/bin/fried\ catfi.sh --banana
```

I'm sure this still has a ton of edgecases. The test calls below are some of my real aliases, and some synthetic tests.

**Comment by zanchey** [comment]
As noted, this is a regression from 2.1.x. @kballard did a lot of the heavy lifting in the alias function, so perhaps he can cast some eyes over the proposed changes?

**Comment by kballard** [comment]
I appreciate what you're trying to do, but I think the proposal here of making alias look like `alias gitl=git log`, where the alias is taking an arbitrary number of whitespace-separated words, is a bad idea. This change would break *every single* alias that expands to multiple words that exist today, as well as being incompatible with POSIX shells' `alias` command which—as the help will tell you—is the entire reason `alias` exists.

**Comment by kballard** [comment]
I'm tempted to say the right solution here is to add a flag to `read` that parses according to shell tokenizing rules instead of splitting on IFS. That way you could just pass the whole shebang to `read` in order to get that first word.

**Comment by ignlg** [comment]
I'm suffering this issue too after a `brew upgrade fish`. Only one fish version installed:
```
> echo $FISH_VERSION
2.2.0
> fish -v
fish, version 2.2.0
> which fish
/usr/local/bin/fish
```
Same issue with aliases.

This is the alias, with escaped whitespace:
```
alias sublime="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
```
and the error
```
- (line 1): begin; function sublime --wraps /Applications/Sublime\;  /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl $argv; end
                   ^
from sourcing file -
	called on line 60 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/eval.fish

in function 'eval'
	called on line 69 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/alias.fish

in function 'alias'
	called on line 72 of file ~/.config/fish/functions/aliases.fish
	with parameter list 'sublime=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

from sourcing file ~/.config/fish/functions/aliases.fish
	called on line 151 of file /usr/local/Cellar/fish/2.2.0/share/fish/config.fish

in function '.'
	called on line 5 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

function: Expected one argument, got 5
```

**Comment by mopsled** [comment]
Here's a quick-and-dirty workaround:

    alias sub "/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"

becomes

    function sub
        /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl $argv
    end

**Comment by zanchey** [comment]
This has bitten someone on [StackExchange](http://unix.stackexchange.com/questions/231059/fish-whitespace-in-alias/231090)

**Comment by faho** [comment]
@ridiculousfish: It seems you'd like to take this. I've been working on it a bit, and I think I've almost solved it.

The heart of the matter is this I've written to extract the first word (i.e. the "command"):

```fish
    # Extract the first command from the body
    set -l tmp (string replace -ra "([^\\\]) " '$1\n' -- $body)
    set first_word (string trim $tmp[1])
    if set -q tmp[2]
        set body $tmp[2..-1]
    else
        set body
    end
```

This almost works, but chokes on (rather theoretical) input that has a masked backslash before a space.

(`string escape` doesn't help us btw because that makes _not escaping spaces_ impossible - i.e. `alias gl="git log" wouldn't work with it if the aliases here do)

**Comment by ridiculousfish** [comment]
If you have a fix, go for it!

**Comment by faho** [comment]
I have what should be a fix now, I tested it with the following "script":

```fish
# first_word needs to be the entire string except "banana"
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome banana'
# first_word "git", body "git" "log"
alias gl='git log'
alias f='fish /home/alfa/some\ test.fish'
```

and it seems to work. I'm still not sure about the "literal backslash before space" part, but I don't think that actually exists in the wild.

**Comment by OlivierCuyp** [comment]
@faho Any idea when this fix gone be release ?
