### ISSUE TITLE
because --bold takes an argument, set_color can't set bold background colors

### ISSUE THREAD

**Issue by oconnor663** [fish-shell/fish-shell#2247]
`set_color -ob red` works fine. (It sets the background color to bright red.)

`set_color -bo red` should do the same thing, but instead produces an error:

    set_color: Unknown color “o”

**Comment by ridiculousfish** [comment]
The issue here is that `-o` is an option, while `-b` is an option-argument. The question is whether an argument `-bo` is interpreted as an option-argument with the argument abutting, or as combined short options with the argument in the next parameter.

OpenGroup [says](http://pubs.opengroup.org/onlinepubs/009696899/basedefs/xbd_chap12.html#tag_12_02) "Each option and option-argument should be a separate argument" which means this is non-conformant. It's certainly ambiguous.

Is this something that you tried and expected to work, or do you have reason to believe that it ought to behave this way?

**Comment by oconnor663** [comment]
My bad, I was misinterpreting the `--background` option. I didn't realize it took its own color argument -- I assumed it meant that the whole command applied to the background.

Which leads to a different question: What if I want to set a bright/bold background color? Right now, because the background flag is taking its own color, the bold argument only applies to the foreground part of the command. But bold background colors are [totally a thing](https://unix.stackexchange.com/questions/93814/cant-apply-brightness-to-terminals-background-color/93872#93872)!

**Comment by ridiculousfish** [comment]
The behavior of bold background colors varies across terminal emulators, so it's tricky to get right.

The ANSI 8-color interface is just...wretched. You're better off using the direct RGB support:

    set_color --background F00 ; echo "Red background!" ; set_color normal

no ambiguity!

**Comment by oconnor663** [comment]
Got it, thanks for the quick response.
