### ISSUE TITLE
syntax for long comments

### ISSUE THREAD

**Issue by kairuku** [fish-shell/fish-shell#2257]
I wonder if there is any alternative syntax for commenting out large code blocks or writing verbose multiline comments, rather than having to put a `#` before each line a user wishes to comment out, i.e., something analagous to:
```
/*
long comment line 1
long comment line 2
long comment line 3
long comment line 4
*/
```
or
```
/*
hiding this block temporarily for such and such reason ....

switch
    case A
        action 1
        action 2
    case B
        if some test
            action 1
            action 2
        else if another test
            action 1
        else another test
            action 1
        end
end
*/
```
If this doesn't currently exist, then I wondered if perhaps it could be an enhancement in a future version.

**Comment by pickfire** [comment]
This currently doesn't exists, you can just add '#' to the beginning of the lines. Maybe this can also be a feature request.

**Comment by faho** [comment]
This is something where a text editor can really help. Look at vim's [nerdcommenter](https://github.com/scrooloose/nerdcommenter) or [evil-nerd-commenter](https://github.com/redguardtoo/evil-nerd-commenter), the emacs/evil port.

I'm inclined to argue that this shouldn't be part of fish because of that, because it's not common in other shells and because you can deactivate blocks with `if false` and `end` - fish doesn't even check syntax then, so it's also usable (but non-obvious) as comment blocks.

**Comment by terrycloth** [comment]
The other use for comments that you have to open and then close is that you can open/close them within the same line.

A trivial example:

``` fish
if test /* $option = "first option"  -o */  $option = "second option"
    echo "Let's go with the $option"
end
```

**Comment by kairuku** [comment]
@faho I understand your point but firstly I'd mention that in bash there is at least the heredoc syntax option, though that doesn't feel explicitly designed for *comments* per se and feels like a verbose and clumsy hack when I have used it for commenting purposes.

Then secondly I'd mention that I thought part of the point of fish was to depart somewhat from other traditional shells, and at least per Wikipedia, be "more ... user-friendly"; in that context I'd like to believe the prior art in various C-like languages would make `/* */` syntax a beneficial addition to fish, and a common enough style of comment syntax to be both **terse** and intuitive. Moreover, like these other languages, it would not make a user dependent on the functionality present or *not* present in any given text editor.

If it's a huge task to implement, then it's certainly not a make-or-break feature, but it would be nice if it's not too hard to implement :-)

@terrycloth This clean inline style is a nice aspect too.

**Comment by anordal** [comment]
> This is something where a text editor can really help.

For Kwrite/Kate/Kdevelop:
* Toggle block mode with Ctrl+Shift+B
* Comment out/in selected code with Ctrl(+Shift)+D (requires syntax highlighting, dunno if this exists for fish yet)

**Comment by krader1961** [comment]
C style comments couldn't be implemented without breaking backward compatibility in a major way. Ain't gonna happen. We could possibly introduce something like Python's triple-quoted string literals; e.g.,

```
###
This is a long
comment block
complete with invalid syntax $[]
###
```

But even that is risky because it's not backward compatible. Someone may have a script with something like the following in it:

```
###
# my special comment
```

P.S., @faho's suggestion to wrap the block in `if false; ...; end` doesn't work in the general case because the contents of the block must still be syntactically correct. So if, for example, you embed a line like `random $[] crap` fish will complain about the invalid variable reference syntax. That trick only works if the comment block contains lines that otherwise look like valid statements.
