### ISSUE TITLE
Invalid yaml in my history file

### ISSUE THREAD

**Issue by alex** [fish-shell/fish-shell#2258]
Attempting to parse my history file with the Python YAML library, I hit a parse error which appears to really be because of invalid YAML:

``` yaml
- cmd: "
  when: 1420779358
```

are the relevant lines

**Comment by ridiculousfish** [comment]
Thanks for filing this. I guess we need to escape some more.

**Comment by alex** [comment]
FWIW, here's another instance of invalid YAML, different root cause though:

```yaml
- cmd: python -mtimeit -s "from django.utils.functional import allow_lazy; from django.utils.translation import ugettext_lazy; f = allow_lazy(lambda s: s, str)" "f(ugettext_lazy('abc'))"
  when: 1423419155
```

**Comment by cdown** [comment]
Any reason not to avoid using a real YAML serialiser for this?

**Comment by ridiculousfish** [comment]
Serialization might be doable as long as fish controls the actual file writing - see the comments in `save_internal_via_appending` for why.

Deserialization will be trickier since fish doesn't want to deserialize the entire file all at once -  instead it just determines the boundaries of items within the file and reads them on-demand.

When I wrote this I didn't appreciate the special characters that YAML has and so I regret choosing YAML here. I think that making it valid YAML is less interesting than keeping it parseable using tools like `sed` and `grep` in the line-oriented Unix tradition. If some items have to be quoted and others don't, then it becomes harder to use these tools.

Does anyone know of a format that's simpler than YAML, and suitable for munging with line-oriented Unix tools?

**Comment by kaleb** [comment]
@ridiculousfish [toml-lang/toml](https://github.com/toml-lang/toml) is the first thing that comes to my mind.

**Comment by floam** [comment]
Hey, I didn't know this issue existed. There's also some discussion in #2759.

**Comment by krader1961** [comment]
If you're interested in addressing this issue please be sure to read the comments in issue #2759.

**Comment by krader1961** [comment]
Closing this issue because we're going to fix the problem by abandoning YAML in favor of protocol buffers (google protobufs) in fish 3.0. See issue #3341. We should have a single serialized format for both history entries and exported vars. Google protobufs are the best solution to this problem.
