### ISSUE TITLE
Expand '~'s in PATH

### ISSUE THREAD

**Issue by damienmckenna** [fish-shell/fish-shell#2310]
Adding "~/bin" to the path is not the same as "/users/me/bin" - the former doesn't seem to actually work whereas the latter does.

**Comment by faho** [comment]
Do it without quotes, then fish will interpret the "~" to mean "$HOME".

**Comment by damienmckenna** [comment]
Ah! I'm not sure where I saw the PATH values being wrapped in quotes, but I've removed them. Thanks for the quick reply!

**Comment by Qix-** [comment]
> Do it without quotes

Sorry to gravedig, but... why?

If I can do `set -xp PATH "$HOME/foo/bar", what difference does the tilde make? The UNIX subsystem makes that distinction in its system calls, too - why is Fish treating it like a special character of some sort?

**Comment by ridiculousfish** [comment]
(Sorry for the long delay, finally catching up with my backlog).

`~` is a character expanded by the shell, not by system calls. Double quotes expand `$` but not `~`. 

I can find nothing in POSIX that says to expand tildes in PATH. bash does this of its own volition (see [this link](https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html)). Probably fish should do it too, it seems harmless enough.

**Comment by Qix-** [comment]
`~` symbolically means "home directory". Tangentially, but related, as a shell user I'm expecting non-special/-escape characters and sequences to be treated the same between all string notations: `'foo'` == `"foo"` == `foo`. Until `fish`, `~` has never been a special character for _shell languages_ in particular. I think that's why it's kind of confusing behavior to not have it expand in `PATH`.

---

By the way, thanks for being a cool maintainer and being active - it's refreshing. I switched to Fish after years of bash and zsh and I'm loving the experience so far. Great work.

**Comment by floam** [comment]
I think this was closed before consideration as a feature request to expand literal tildes in `PATH`, reopening.

**Comment by floam** [comment]
The fact that fish could potentially be a child of a shell that does handle tildes in `$PATH` (bash) or is used alongside such shells where PATH is possibly already exported with ~'s in it is probably a good enough reason to quietly just deal with these.

**Comment by faho** [comment]
>The fact that fish could potentially be a child of bash which does expand tildes that are the first character of $PATH components or is used alongside such shells where $PATH is possibly already exported with ~'s in it is probably a good enough reason to quietly just deal with these.

It's a bit of a surprise that it happens, and e.g. git doesn't do it, so if you have your $EDITOR in such a path it's already broken. Zsh also doesn't do it.

So I'm against this, even if framed in this way.

**Comment by Qix-** [comment]
@faho Git is not a shell. That's an apples to oranges comparison.

The fact is, even though Fish isn't a POSIX shell, the tilde _is_ standardized in GNU shell language: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01

Again. It's strange to not have it work inside quotes but work outside of them. Do one or the other, not a mix. It's unexpected UX.

**Comment by floam** [comment]
I agree that the fact this is non-POSIX and bash is the only other shell out there that does this thing, kind of makes me not want to do it, and that by doing it, we might be helping people shoot themselves in the foot. My guess is that more often than this behavior is unhelpful, we would be doing the user "a solid" and allowing things to work as expected.

I'm OK with a compromise where if we detect a `~` at the beginning of a PATH component we give the user a **very** specific and helpful error message/warning to explain the problem and help them correct it.

**Comment by faho** [comment]
>I'm OK with a compromise where if we detect a ~ at the beginning of a PATH component, rather than expanding it, we give the user a very specific and helpful error message/warning to explain the problem and help them correct it.

Fine by me. A directory literally called `~` is 99.99999% likely to be an error, or a prank.

**Comment by floam** [comment]
There are certainly people out there who are using bash, have a PATH defined in terms of `~`, and they are using git OK. Most likely there are just a few binaries in something like ~/bin, and git will work just fine without whatever it is they installed into their home dir. It's a safe bet that probably it will never go noticed. For the shell however, stuff installed into ~/bin being missing will be noticeably absent when they can't run it interactively, and it can be very confusing to figure out what is going wrong since the path looks good to the casual observer.

**Comment by floam** [comment]
>GNU Shell = bash, which is bourne shell + extensions. Bash was written for the GNU Project. Bash was written to be POSIX compliant. The tilde is specified by POSIX for the shell shell language.

Right. But this is bash-specific behavior, a bash extension to POSIX shell. Only bash does this. ksh, zsh, ash do not do this.

A literal tilde is **not specified by POSIX to be expanded when it appears in PATH**, @Qix-.

**Comment by floam** [comment]
I think there is just some confusion here, so let me say it this way: the fact that POSIX describes the shell expanding the tilde to `$HOME` as it does is not relevant - please try to understand: The shell does not expand the contents of the `$PATH` variable as if each path were encountered unquoted in a shell script. `PATH` is supposed to be a colon-separated list of filesystem locations. Not a shell script to be evaluated to determine the paths.

Just like variables. e.g. `set PATH \$HOME/bin` (or` set PATH '$HOME/bin'`) would also not work, because instead of letting the shell expand `$HOME` to a path and putting that expanded path into the environment variable, we escaped the dollar sign so that '`$HOME`' is literally in the variable. This doesn't work. It's like `cd '$HOME'`.

**Comment by floam** [comment]
And, the good argument for us doing it anyway is that it's useful to decide to make an exception here, like Bash did. I can imagine a system administrator system-wide wanting to put '~/bin` in PATH so that all users automatically get their per-user `bin` directory in their `PATH`. On my computer for example, the way you would configure the default PATH for all users (`/etc/paths`), no shell is involved in setting up the PATH variable so it is just not possible to generally pre-expand that.

Its just not POSIX, which rarely stops us from doing the right thing in fish. :smile:

**Comment by floam** [comment]
@faho We could make it consistent and make `git` work, or even children shells work, by not just expanding the tilde when we interpret $PATH components internally, but actually go further and replacing the PATH components with the full paths.

**Comment by faho** [comment]
>On my computer for example, the way you would configure the default PATH for all users (/etc/paths), no shell is involved

We read /etc/paths, so in fish's case, a shell is involved.

>replace the ~-relative PATH components with the full expanded paths

That would be more useful, but still inconsistent.

Also that kinda breaks your rationale? If you keep the literal and only expand it when resolving, that means if you `sudo bash` that bash will look in the target user's home.

If you resolve it, that breaks.

**Comment by floam** [comment]
> We read /etc/paths, so in fish's case, a shell is involved.

But it's not fish script. And on other shells, `path_helper` operates on it and it does not do any kind of expansion either. The way you configure PATH on macOS doesn't really involve anything with any particular shell or scripting. You could probably hit this kind of problem on Linux if you are logging in with a directory service and PATH is in a database table. I think on many Linux setups, PATH is initially set up by a shell script, so you could have system-wide per user PATHs just by not quoting a tilde.

If it's not clear: Let's say I add `~/bin` to `/etc/paths`. It works great with the default shell, bash, to make it so every user has their `./bin` directory in `$HOME` already in `PATH`.

It doesn't work in fish. Let's say fish had the nice warning I was suggesting earlier. It would tell me I need to put `/Users/floam/bin` in PATH, or otherwise not use ~, maybe stop quoting it.

It wouldn't help me, because `/etc/paths` is just a list of paths, so there's nothing to stop quoting, and no kind of logic that can be added to make it result in homedir-relative PATHs for all users. It's not possible to actually address in any way - fish just can't do the thing bash can.

**Comment by paulpach** [comment]
The lack of this feature breaks dotnet tools in mac

Basically the dotnet installer adds `/etc/paths.d/dotnet-cli-tools` with the following content:
```sh
~/.dotnet/tools
```

Thanks to this,  as a user in bash I can install dotnet tools locally that only affect my user and they are in the path.

But when using fish,  since the ~ is not expanded in PATH, none of the dotnet tools are available out of the box.

**Comment by ridiculousfish** [comment]
Relevant #6641

**Comment by faho** [comment]
Closing this in favor of #6641.
