### ISSUE TITLE
s/sanity/reasonability/g

### ISSUE THREAD

**Issue by nyarly** [fish-shell/fish-shell#2319]
Is there any chance of renaming e.g. sanity.cpp to reasonability.cpp, from a concern for classy compassion?

**Comment by ridiculousfish** [comment]
No objection here.

**Comment by jrobeson** [comment]
I went looking into it, just because it I though it'd be a quick rename, but it isn't. Function names would need to be changed too

**Comment by krader1961** [comment]
The function names are all private to the C++ code and not visible to the public. So doing so would be a trivial search-and-replace. Having said that I don't see the point. No reasonable person can construe the use of the word "sanity" in the fish C++ code as implying anything about the mental state of a person. And if we were to change this then s/sanity/correctness/ makes more sense than s/sanity/reasonable/. Sorry, but this is the sort of silliness that gives conservatives a legitimate reason to complain about political-correctness.

**Comment by jrobeson** [comment]
sure doing it would be a trivial search replace, but reasonability_lose as a function name didn't make sense.

**Comment by jrobeson** [comment]
btw.. I don't really care what conservatives think about political correctness (nor do i have any particular thoughts on this issue either). I was just trying to pick some small easy thing to do.

**Comment by krader1961** [comment]
> ...but reasonability_lose as a function name didn't make sense.

Neither does **sanity_lose** make sense -- **lost_sanity** would be more grammatically correct. Again, a simple search-and-replace. Which still doesn't negate my observation about the hyper-political correctness of the initial issue description.

**Comment by ridiculousfish** [comment]
@jrobeson Word :) One piece of low-hanging housekeeping is the header comment in each file. For example, in common.cpp:
````
/** \file common.c
*/
````

D'oh! These ought to be updated, or removed outright, or whatever'd. If you're looking for an easy contribution cleaning that up would be appreciated!

**Comment by jrobeson** [comment]
@krader1961 : yes to implemnt the feature it would be a search and replace, but you can't search and replace until you know what you're actually replacing!

**Comment by jrobeson** [comment]
@ridiculousfish : I wonder if you might want to add an Easy-Pick label and file a bunch of stuff like that.

**Comment by jrobeson** [comment]
@krader1961: you have that opinion, i think that is clear. However @ridiculousfish accepted the idea of the change, so wouldn't it be up to them to decide?

**Comment by jrobeson** [comment]
@ridiculousfish
> D'oh! These ought to be updated, or removed outright, or whatever'd. If you're looking for an easy contribution cleaning that up would be appreciated!

whatever'ed isn't actionable :)

**Comment by krader1961** [comment]
> I was just trying to pick some small easy thing to do.

@jrobeson: Excellent. There's plenty work of that nature that would benefit from some attention by persons like yourself. Sorry if my comment seemed to be directed at you. It was really directed at the O.P.

There's a ton of style improvements to be made to the code. But that's probably best left until I've had a chance to convince everyone else on a consistent style. At the moment, despite a style guide for the project, the style of the code deviates wildly from it.

One way you can immediately contribute is by reviewing pull-requests. Especially if you are able to merge those changes onto your local machine and test them.

> However @ridiculousfish accepted the idea of the change, so wouldn't it be up to them to decide?

Yes and no. Yes, just as Linus Torvalds has final say on changes to the Linux kernel and Guido van Rossum has final say on changes to the Python language every project is a collaborative effort where senior contributors have significant influence on what gets committed and random people without a track record can expect to have their proposals more closely scrutinized.

**Comment by jrobeson** [comment]
but @ridiculousfish  isn't a random person.

**Comment by jrobeson** [comment]
@krader1961 : PS: i'm not a C++ coder, I'm only a C++ dabbler, I prefer to never touch the stuff except when trivial. I already look over the snippets.d proposal, since it was in fish code.

**Comment by ridiculousfish** [comment]
I'm happy with this issue open or closed. If someone is feeling some classy compassion and wants to do it, go for it.

**Comment by krader1961** [comment]
@ridiculousfish: Do you really think renaming files and function names solely because someone thinks someone else might be offended is productive? If the code contained clearly offensive comments like "person_x_is_insane" I'd agree that should be changed. But in this instance it is clear that the term "sanity" refers to the internal state of the process being internally consistent. How can that reasonably be construed as not showing compassion for people with a mental illness?

**Comment by krader1961** [comment]
I cannot believe we are having this discussion.

**Comment by pickfire** [comment]
I think sanity is better, it is *short* but the meaning might be a bit different.

**Comment by ridiculousfish** [comment]
@krader1961 The value of the change is not what's at stake. We welcome contributions, however small, as long as they aren't harmful. Worst case it costs us a few minutes and that contributor feels good, best case that contributor is encouraged and motivated to attempt more substantial improvements.

BTW that applies to users too. A user who takes time out to try a new shell, hunts down our page, and provides feedback - that's well beyond what most users will do, so I am grateful and appreciative even if I disagree with their conclusions.

**Comment by jrobeson** [comment]
I can definitely say that based on my own experience, it's a lot easier to get started with simple things like renaming, and ups my interest in continuing to contribute. I've only participated in the edges of the fish ecosystem up until recently, like rewriting the wahoo fish framework installation to follow the XDG Base Directory Specification, which ended up making its way into oh-my-fish before they had to redo it due to the DMCA debacle.

**Comment by krader1961** [comment]
@ridiculousfish: I completely agree that even teeny-tiny changes are welcome. That's why I merged a change a couple of days ago that did nothing more than introduce a single apostrophe in the docs to fix the grammar of a sentence. But not every suggested change can be welcomed (i.e., implemented). Some suggestions will be at odds with the architecture and design goals of the project (e.g., the desire to support `&&` in addition to `and`). Some will have been based on faulty assumptions (e.g., misdiagnosing an observed behavior). And a very few, like this suggestion, do nothing more than cause code churn with no benefit other than to make someone feel good. I don't think that's a sufficient reason implement a change.

On the other hand there are a ton of simple code cleanups that wouldn't change the implementation but would be a net benefit by improving the readability of the code. Such as the one you suggested to @jrobeson. I have a lengthy list of such changes I'd like to see made. But it's premature to make most them until a new consensus is reached on the [Style Guide](https://github.com/fish-shell/fish-shell/blob/master/CONTRIBUTING.md).
