### ISSUE TITLE
Request: echo with color (without having to set_color)

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#2343]
It would be nice if `echo` could take a `-c color` argument.  This:
```fish
echo -c orange Fish is awesome
```
...would be a lot nicer than:
```fish
set_color orange
echo Fish is awesome
set_color normal
```
Sure, I could make a function to do that, but it seems like `echo` ought to have this built-in.  :)

**Comment by pickfire** [comment]
You can do this:
```fish
echo (set_color orange) Fish is awesome(set_color normal)
```

**Comment by faho** [comment]
The more options we add to echo, the more careful you need to be when using it unless we add a "--" to stop option processing. So far we haven't done that because POSIX actually demands it doesn't. And even with that you couldn't do 

```fish
echo -c orange Fish -c normal is awesome
```

OR we could add an option to escape dashes to our fancy new `string` tool (#2296) - which would be useful in general.

However, I'm not convinced a "-c" flag to `echo` is the right option since it only affects that one tool and not `printf`, and it's not much more convenient than @pickfire's substitution solution (rolls right of the tongue, that one).

**Comment by alphapapa** [comment]
Thanks for the comments.  I guess a good compromise might be something like:
```fish
function c
    set_color $argv
end

echo (c orange)Fish is awesome(c normal)
```
It ends up being about the same number of characters as `echo -c` would be.

**Comment by faho** [comment]
Considering [the law of orthogonality](http://fishshell.com/docs/current/design.html), this doesn't seem like something we'd want to add upstream. You're of course free to add it yourself.
