### ISSUE TITLE
Fish command substitution passed as single variables

### ISSUE THREAD

**Issue by TrungACZNE** [fish-shell/fish-shell#2353]
$ printf "a=b\nc=d\n" > test
$ env (cat test | xargs) env
Shows "a=b c=d" as a single env var
$ bash -c 'env $(cat test | xargs) env'
Shows "a=b" as a single env var and "c=d" as another

$ cat count.py
import sys
print len(sys.argv) - 1
$ python count.py (echo "1 2 3")
1
$ bash -c 'python count.py $(echo "1 2 3")'
3

Is the above behavior intended?

**Comment by ridiculousfish** [comment]
Like bash, fish splits command substitutions according to the value of `$IFS`. Unlike bash, fish `$IFS` defaults to just newline instead of space-newline-tab. That explains the difference.

This is usually a good thing, since it prevents a host of issues for files with spaces in their name.

**Comment by TrungACZNE** [comment]
I'm not sure that's the case for me
$ echo -n $IFS | xxd
00000000: 0a20 09

That's newline-space-tab (from fish). Fish version 2.2.0. I think this is the default also, since I never even knew about $IFS until now.

**Comment by ridiculousfish** [comment]
err, sorry, you're right. The only two options are to split on newlines or not split at all, and this is conditioned on whether `$IFS` is set to something non-empty (and its value is otherwise ignored). It's been this way since fish 1.x.

My hope is to get rid of `$IFS` and just use the `string` builtin #2296 for munging arguments.

**Comment by zanchey** [comment]
Changes to IFS are suggested in #1656 - shall we track there?

**Comment by faho** [comment]
`xargs` is expecting us to split on space, which we don't do.

The IFS discussion here is unrelated, and removing the actual $IFS is not going to help because we'll still split on newlines by default.

What you'll want to do is `env (string split " " < test) env` - i.e. we split on newlines only by default (because that is much safer than splitting on spaces too), but `string split` can be used to split on something else.

Note that currently all `string split` does here is replace the split character with a newline (so it's not newline-safe, which isn't much of an issue in practice. The plan is to make it special so we only split on that argument and don't convert it to newline and then split on newlines.

That's tracked in 1656.

I'm not sure how to label this, so I just wont, but there's no issue that we'll fix left here that isn't already documented somewhere else. Closing.
