### ISSUE TITLE
Starts twice on init

### ISSUE THREAD

**Issue by Profpatsch** [fish-shell/fish-shell#2408]
When I start fish on Nixos, it execve’s itself again after loading the config files. This way if I e.g. add `echo foo` to `/etc/fish/config.fish` it gets printed twice.

The nixos-part of this issue is here: https://github.com/NixOS/nixpkgs/issues/9914

First off:
```
> readlink result
/nix/store/ns7kvqk9ybzvhp5q88ya1hka0xf45lw6-fish-2.2.0
```

1: (`strace -f result/bin/fish`)
```
22294 execve("result/bin/fish", ["result/bin/fish"], [/* 68 vars */]) = 0
…
22299 execve("/nix/store/ns7kvqk9ybzvhp5q88ya1hka0xf45lw6-fish-2.2.0/bin/fish", ["/nix/store/ns7kvqk9ybzvhp5q88ya1"..., "-c", "fish_update_completions > /dev/n"...], [/* 68 vars *
```

2: (`fish -p`)
```
> env fish_log_forks=1 result/bin/fish
546: g_fork_count: 0
starting to read initsourcing data config
…
fork #1: Executing keepalive fork for 'echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0'
fork #2: Executing fork for internal builtin for 'echo'
fork #3: forking for '/nix/store/r8m8d2r74dkn4amqlyhywqx30s8ycw8w-fish-2.2.0/bin/fish' in '-'
546: g_fork_count: 0
starting to read initsourcing data config
```

**Comment by faho** [comment]
If I understand the [packaging recipe](https://github.com/NixOS/nixpkgs/blob/ad4e17e94b8cda554df76dae08c189239fe6462b/pkgs/shells/fish/default.nix) correctly, this is basically pure fish 2.2.0, only with some sed-patching to make nix's directory structure work?

>22294 execve("result/bin/fish", ["result/bin/fish"], [/* 68 vars */]) = 0
>22299 execve("/nix/store/ns7kvqk9ybzvhp5q88ya1hka0xf45lw6-fish-2.2.0/bin/fish"

If I understand this correctly, that's your self-built fish execing system fish? Does it also occur with system fish?

**Comment by zanchey** [comment]
This looks like the built-in `fish_update_completions` running from [`__fish_config_interactive`](https://github.com/fish-shell/fish-shell/blob/054fb22/share/functions/__fish_config_interactive.fish#L99-L102).

**Comment by faho** [comment]
Yes, that sure does look like it.

How about we move the redirection to the fish call, not the function call? Unless we want to change that config.fish is always sourced, that seems to be the only thing we can do. Though it should probably call "this fish", not system fish.

**Comment by zanchey** [comment]
I don't think this is a bug. That the output of `config.fish` is displayed is something that should be fixed with `if status --is-interactive` in `config.fish`, not by hiding the output from a normal fish invocation.

This block should only run once to generate completions; if it's more than that, then there is a bug.

**Comment by faho** [comment]
@Profpatsch: That fish starts twice is a "feature" (well, more of a hacky workaround). Unless it's always starting (it should only do it once if ~/.local/share/fish/generated_completions doesn't exist), there's no real bug here. Therefore I am closing this. If it always starts, please say so and we'll reopen.
