### ISSUE TITLE
NVM causes shell start delay

### ISSUE THREAD

**Issue by krzkrzkrz** [fish-shell/fish-shell#2411]
I am using Bass (https://github.com/edc/bass) to source NVM (node package manager). I opened up an issue with them at https://github.com/edc/bass/issues/10 but thought I would ask here too.

In `~/.config/fish/config.fish`, I have:

    bass source ~/.nvm/nvm.sh ';' nvm use 0.12.2

Every time a new Fish shell terminal is opened. It takes almost a second for the shell to load. Without this line, the Fish shell loads fast.

Is there something I can do about this? What are you guys using for node packages?

There's an alternative to NVM, called N (https://github.com/tj/n), but don't know if this solves anything. Any feedback will be appreciated.

**Comment by faho** [comment]
The first thing you probably want to do is guard this with `if status --is-interactive` because fish _always_ loads config.fish. Other than that, I have no idea. It's probably just bass or nvm being slow.

**Comment by krzkrzkrz** [comment]
You mean `if status --is-interactive bass source ~/.nvm/nvm.sh ';' nvm use 0.12.2`?

**Comment by faho** [comment]
```fish
if status --is-interactive
  bass source ~/.nvm/nvm.sh ';' nvm use 0.12.2
  # and all other stuff you only want to happen if fish is interactive
end
```

You can, of course, also make a dedicated file for interactive fish and then just source it in that block.

**Comment by krzkrzkrz** [comment]
Yea still pretty slow. One thing I did to speed things up. Was replace RVM with Rbenv. Theres a difference with how Rbenv is loaded into the shell compared to RVM.

I'll try to replace NVM with N and see if that renders better results

**Comment by krzkrzkrz** [comment]
I can confirm. Using rbenv and n instead of rvm and nvm make fish a lot more snappier. I don't notice any delays. Closing for now

**Comment by krzkrzkrz** [comment]
Actually, before I close.

Can you clarify when `if status --is-interactive` is needed? What exactly is `interactive`?

**Comment by faho** [comment]
An "interactive" shell is... well... interactive - it's waiting for and then reading user input and stuff. If you run `fish` in a terminal (or have the terminal start fish as your shell), that's interactive. If you run `fish script.fish` or `fish -c "$somefishcommands"`, that's not interactive.

Now bash has ~/.bashrc, but it only reads that when run interactively, while when it's not interactive it'll read the "BASH_ENV" variable for a filename to read (before executing any other commands). Then it also differentiates between "login" and "non-login" shells - the former read the first of ~/.bash_profile, ~/.bash_login and ~/.profile that exists (and not ~/.bashrc!!). When a login shell exits, it also reads ~/.bash_logout. (See [the corresponding section in the bash reference manual](https://www.gnu.org/software/bash/manual/bashref.html#Bash-Startup-Files))

Because all of that is a bit complicated, fish does it simpler - it always reads ~/.config/fish, and leaves it up to the user to change behavior depending on what "mode" the shell is in.

**Comment by krzkrzkrz** [comment]
Thanks for the explanation. Should the following go inside `if status --is-interactive`

```
set -Ux EDITOR vim

# Modify the terminal's 256 color palette to use the gruvbox theme
set -l GRUVBOX_SCRIPT ~/.vim/bundle/gruvbox/gruvbox_256palette.sh
if test -f $GRUVBOX_SCRIPT
  bash $GRUVBOX_SCRIPT
end
```

**Comment by faho** [comment]
>set -Ux EDITOR vim

This probably doesn't matter much - but be careful, because `set -Ux EDITOR vim $EDITOR` would cause the "EDITOR" variable to grow with every fish invocation.

>set -l GRUVBOX_SCRIPT ~/.vim/bundle/gruvbox/gruvbox_256palette.sh
if test -f $GRUVBOX_SCRIPT
  bash $GRUVBOX_SCRIPT
end

If the shell's not interactive, output may not be attached to a terminal. So the escape codes that script prints (that was what your other issue was about, no?) might end up in a file or variable somewhere else and cause weird issues. --interactive it.

**Comment by faho** [comment]
I think all issues here have been solved. Thank you for swimming with the fishes. Closing.

**Comment by krzkrzkrz** [comment]
@faho thanks for the explanation. 

What would you suggest using instead of `set -Ux EDITOR vim`?

**Comment by faho** [comment]
>Should it be: set -g -x EDITOR vim instead?

Yes.

>in if status --is-interactive?

Yes.

**Comment by krzkrzkrz** [comment]
Thanks for that
