### ISSUE TITLE
How could I configure autosuggest ?

### ISSUE THREAD

**Issue by olivetree123** [fish-shell/fish-shell#2430]
I think control+F is inconvenient , I want to do this with command+R .  Where is the configuration file ?

**Comment by faho** [comment]
>Where is the configuration file ?

[~/.config/fish/config.fish](http://fishshell.com/docs/current/tutorial.html#tut_startup). To do keybindings, you might want to read the [bind](http://fishshell.com/docs/current/commands.html#bind) documentation. What we should highlight a bit more is that a bare `bind \cr forward-char` in config.fish doesn't work because there's a bit of magic going on behind the scenes.

What you want is

```fish
function fish_user_key_bindings
    bind \cr forward-char
end
```

(assuming you are using the default keybindings and not the vi-ones, `bind \cf` tells me it's bound to "forward-char").

**Comment by olivetree123** [comment]
Thank you.

**Comment by faho** [comment]
Do you have any related questions or can we close this?

**Comment by ridiculousfish** [comment]
Closing
