### ISSUE TITLE
$XDG_CONFIG_HOME issue on OS X El Capitan

### ISSUE THREAD

**Issue by qwoodmansee** [fish-shell/fish-shell#2452]
Just did a clean install of OS X El Capitan, installed Developer Tools, Homebrew, and Fish. 

After installing I get the error "Unable to create a configuration directory for fish. Your personal
settings will not be saved. Please set the $XDG_CONFIG_HOME variable to a
directory where the current user has write access."

I ran set -gx XDG_CONFIG_HOME /Users/myUsername/Documents/Fish\ Config/ and tried to restart fish, but got the same error. After running "set -gx", I saw that XDG_CONFIG_HOME isn't even listed.

**Comment by faho** [comment]
>I ran set -gx XDG_CONFIG_HOME /Users/myUsername/Documents/Fish\ Config/ and tried to restart fish

Of course that's not going to work - global variables aren't permanently saved anywhere, nor are they shared between sessions. Universal variables are, but we save them inside of $XDG_CONFIG_HOME - so to get the value of the variable, fish would need to know the value of the variable.

Try setting XDG_CONFIG_HOME inside a running fish and then run `fish` inside of it. That still won't solve the underlying issue, but I'd at least expect that to work.

When XDG_CONFIG_HOME is not set, we fallback to ~/.config/ - does that exists, is it writable? Otherwise try `mkdir -p ~/.config/fish`.

Which fish version are you running?

**Comment by qwoodmansee** [comment]
I tried your solution that "doesn't solve the underlying issue," and you were correct. I did not know that the global variables weren't saved.

~/.config/ does exist, but permission to it is denied (I am an admin.) I know that OS X changed some of its permissions with the the "rootless" system, but I didn't think it would stop us from accessing and editing /.config/

Note that if I run "sudo fish" the problem is resolved because fish can access /.config/

Running 2.2.0

**Comment by faho** [comment]
Then change the permissions to ~/.config - `chown` and `chmod` should do that.

**Comment by qwoodmansee** [comment]
I've fixed the issue by allowing the admin group of my computer to read and write to .config.

Should I leave this issue open for others? Thank you.

**Comment by zanchey** [comment]
My suspicion is that something you ran as root (e.g. under sudo) created the `~/.config` directory before fish had a chance to.

**Comment by jrobeson** [comment]
@zanchey must be right. why would OSX prevent writing in your own home otherwise?

**Comment by jrobeson** [comment]
@qwoodmansee : don't set `$XDG_CONFIG_HOME` directly to your fish config please. fish is a directory INSIDE `$XDG_CONFIG_HOME`

**Comment by faho** [comment]
I don't think there's anything left to do here. It seems like it was user error.
