### ISSUE TITLE
Man page output truncated

### ISSUE THREAD

**Issue by siteshwar** [fish-shell/fish-shell#247]
Trying to print man pages with commands like "history -h" skips printing last line of man page.

**Comment by krader1961** [comment]
Typing `history -h` reports `history: invalid option -- -h`.  However, I think I understand the gist of the problem. I can reproduce it by comparing `command -h` versus `man command`. It's not just the last line that's missing it's also the first three lines. That's because the `print_help()` function invokes `__fish_print_help` which says:

```
# The original implementation trimmed off the top 5 lines and bottom 3 lines
# from the nroff output. Perhaps that's reliable, but the magic numbers make
# me extremely nervous. Instead, let's just strip out any lines that start
# in the first column. "normal" manpages put all section headers in the first
# column, but fish manpages only leave NAME like that, which we want to trim
# away anyway.
#
# While we're at it, let's compress sequences of blank lines down to a single
# blank line, to duplicate the default behavior of `man`, or more accurately,
# the `-s` flag to `less` that `man` passes.
```

In other words the behavior is deliberate. If someone can make a good argument for why the behavior should be changed -- especially if useful information is being stripped -- we can revisit the issue.
