### ISSUE TITLE
mercurial command shortforms not supported by completions

### ISSUE THREAD

**Issue by eskhool** [fish-shell/fish-shell#2517]
the out of the box completions for mercurial does not support partial commands. In mercurial, the following are all the same (anything more than 3 characters of the command):
hg clo, hg clon, hg clone

fish requires one to first tab and wait for the command to be expanded before completing the parameters which shouldn't be required.

**Comment by danielmatz** [comment]
Yeah, I only implemented the full names and any aliases listed in the hg help output.  I think this would be easy to fix.

**Comment by eskhool** [comment]
I did look at the completions file...all the complete lines rely on 'contains export/diff' etc ..but replacing the full name of the command with just the short form makes only the short form work...how would one make a substring match in complete? Speaking as one who hasn't yet dived fully into the fish language

**Comment by danielmatz** [comment]
You'll see that some of the blocks of completion lines are wrapped by a for loop.  I was just going to do that for each block, and loop over all of the partial commands.

```fish
for cmd in cl clo clon clone
    # completions for clone
end
```

I won't get to this for a few days, so you are welcome to take a stab at it.

**Comment by faho** [comment]
There's one thing I'd like this to _not_ do, though - do _not_ offer the abbreviated versions. Accept them if they are there, but don't litter the output of `hg <TAB>` with four versions of "clone".

In other words, if the commandline is `hg `, offer `clone`, `init` etc. If it is `hg clo `, offer the completions for `hg clone `.

**Comment by danielmatz** [comment]
@faho Oh, yes, I absolutely agree.  As it stands, we only complete the full commands (for example, hg up<TAB> would give you hg update), but we complete options and arguments for the full commands and the documented aliases (for example, hg help update shows that you can also use hg up, hg co, and hg checkout).  So all we will do is update it so that we complete options and arguments for all possible command abbreviations (for example, we'll add completion for hg upd, hg upda, and hg updat).

@eskhool Do you want to take a stab at this?  If not, I'm happy to do it, and should have some time soon.

**Comment by eskhool** [comment]
@danielmatz I will leave it in your more than capable hands, lest I stumble and create a mess. Will wait for your upgrade!

**Comment by danielmatz** [comment]
With the pull release merged, this issue can be closed.
