### ISSUE TITLE
aliases lose environment

### ISSUE THREAD

**Issue by rwz** [fish-shell/fish-shell#2518]
Let's say we have a following script

```sh
#!/usr/bin/fish
# scriptname.fish

if test -n "$MYVAR"
  echo "MYVAR is set"
else
  echo "MYVAR is not set"
end
```

Also we have an alias for the script:

```sh
alias lolalias "./scriptname.fish"
```

Also, we have a following function:

```sh
function run_with_myvar
  set -lx MYVAR 1
  eval $argv
end
```

When we run `run_with_myvar ./scriptname.fish`, the output is `MYVAR is set`. If we run `run_with_myvar lolalias` however, the output is somehow `MYVAR is not set`

**Comment by ridiculousfish** [comment]
`alias` is just a wrapper around defining a new function, which will mask any locals. You can see that by running `functions lolalias`

What do other shells do here? Do they distinguish between aliases and functions, and have different scoping rules for both? Weird if so.

**Comment by faho** [comment]
The cause here is a slightly weird quirk of our scoping rules - when you declare a variable as "local and exported" with `set -lx`, it will be passed to called _programs_, but not to called _functions_.

This means that you can make a foo.fish with the following contents:

```fish
#!/usr/bin/env fish
function foo
    echo $MYVAR
end
foo
```

and then

```fish
  > set -lx MYVAR banana
  > ./foo.fish
  banana
  > source foo.fish
  >
```

Combine this with the fact that our `alias` is a wrapper around a function declaration like @ridiculousfish said, and you can see where it's coming from.

**Comment by rwz** [comment]
I see. I guess I'll close it since it's not a bug, but a feature :)
