### ISSUE TITLE
repaint doesn't work in fish_preexec

### ISSUE THREAD

**Issue by andyearnshaw** [fish-shell/fish-shell#2529]
I want to remove my rprompt when I hit enter (the information in it — backgrounded jobs and vi mode indicators — isn't relevant after executing the command and it adds a lot of noise).  I thought I'd be able to do it with

```fish
function __fish_preexec_repaint --on-event fish_preexec
    set -g __fish_prompt_no_right 'yes'
    commandline -f repaint 
    set -e __fish_prompt_no_right
end
```

but it doesn't seem to work. Does the event fire too late? Is it fixable?

**Comment by krader1961** [comment]
The prompt, both left and right, won't be repainted until the command completes and a new prompt is issued. The fish_preexec functions are run between issuing prompts and cannot modify the prompt that was displayed when that command was entered. What you're trying to do doesn't make much sense.

**Comment by andyearnshaw** [comment]
I appreciate the explanation, but saying that it doesn't make much sense isn't particularly helpful as I'm unfamiliar with fish's innards.  I'm merely interested in finding out of I can remove my rprompt by repainting before the command executes.

**Comment by floam** [comment]
> What you're trying to do doesn't make much sense.
He wants to repaint it by some mean - it'd be nice if it worked. This is an open fish bug:

https://github.com/fish-shell/fish-shell/issues/897

**Comment by krader1961** [comment]
My apologies, @andyearnshaw, for my terse reply. There is widespread confusion about what `commandline -f repaint` does and when it can be used because the documentation is unclear.  The short answer is, no, you cannot remove the right prompt from the screen just before a command is executed. Neither can you remove or modify the left prompt due to the same limitations of how fish manages the prompts.
