### ISSUE TITLE
Fish doesn't notice changes to PWD (except through cd)

### ISSUE THREAD

**Issue by Mabinogiysk** [fish-shell/fish-shell#2544]
I can't figure out a name. Here are the problems:
I have a folder like this:
$ /W/n/tmp> ls
111.txt  22.txt  abcd/
then I execute command:
$ /W/n/tmp> mv ../tmp/ ../tmp-ok
It shows:
$ /W/n/tmp>
gives a wrong prompt and shows folder abcd/ with wrong color when I type it in the fire time.

**Comment by ridiculousfish** [comment]
Retitling

**Comment by ridiculousfish** [comment]
Basically fish doesn't notice changes to PWD except for cd. bash and zsh are the same.

**Comment by krader1961** [comment]
Sorry, but this is not a problem with fish. The current working directory was not changed. The directory name was changed (behind fish's back). No shell will detect this unless it installs a handler (using something like the Linux inotify API) to monitor changes to the parent directory. Note that you can't simply monitor changes to the current working directory because it isn't being changed in this scenario. The name of the CWD is an attribute of the parent directory, not the CWD itself.

No shell I've ever used goes to the trouble of detecting that the CWD name was changed behind its back. And doing so cannot be done in an OS agnostic fashion except using an expensive heuristic of listing the contents of the parent directory, looking for the CWD inode, and noting if the name associated with the inode has changed. It's not worth the cost.

Also, what should fish do if the CWD is deleted? In other words, if instead of renaming the directory, it is deleted as in the following sequence of commands:

```
$ cd ~
$ mkdir -p tmp/abc
$ cd tmp/abc
$ rmdir ../abc
$ ls ..
```

On UNIX like systems that is perfectly legal. Because the shell holds a reference to `abc` it isn't actually deleted until the CWD is changed (i.e., the reference is dropped). But the name `abc` is no longer tied to the CWD. Should fish substitute something like "tmp/[deleted]"? How many questions do you think that will generate?

I think this should be closed with the annotation "working as intended".

**Comment by ridiculousfish** [comment]
It would be reasonable to have fish use `getcwd` before showing the prompt or something to check if the path is changed. Deletion is a stickier issue as you say.

**Comment by krader1961** [comment]
@ridiculousfish your suggestion to use `getcwd` reminds me that there are additional failure modes I didn't mention. For example, permissions changing on parent directories which precludes determining the current name even though the CWD still exists and its name has not changed. The `getcwd` function can also be expensive. It effectively does what I suggested. It opens the ".." file to get the parent directory then reads it looking for an entry that matches the inode number of the CWD. It then does that for all parent directories since they too may have been renamed.

This is also something that is probably OS specific. For example, AFAIK MS Windows doesn't let you do the sequence of commands the O.P. or myself described. So it's effectively limited to UNIX.

Lastly, if the CWD was reached via a specific `cd` command should fish dynamically change its conception of the CWD (i.e., change the value of $PWD) because of actions that occurred external to it? Do we really want all uses of $PWD to be affected by this scenario? What if someone has written a fish function or external command that is deliberately using the value of $PWD to see if the original name that was cd'd into is still valid? 

This is fundamentally different from other external actions such as `set -U` in another shell or the status of a background job changing. I still feel strongly that this is a "working as intended" issue.

**Comment by krader1961** [comment]
I still haven't changed my opinion and we don't want to incur the overhead (e.g., calling `getcwd()` when we otherwise would not do so) just to handle a corner case that very few people will ever notice.
