### ISSUE TITLE
native ConEmu support

### ISSUE THREAD

**Issue by MetaMemoryT** [fish-shell/fish-shell#2545]
https://github.com/Maximus5/ConEmu

This issue is for running fish directly in ConEmu without mintty wrapper.

some issues talk about it:
https://github.com/fish-shell/fish-shell/issues/1160
https://github.com/fish-shell/fish-shell/issues/1071
https://github.com/fish-shell/fish-shell/issues/2092

but no issues have ConEmu in the title, tracking this specific issue.

**Comment by edclement** [comment]
:+1: to get this fixed

**Comment by edclement** [comment]
:+1:

**Comment by krader1961** [comment]
Issues #1071 and #2092 (which are duplicates of #789) have been fixed.

Issue #1160 is still open but it is unclear if it is still a problem.

I'm closing this issue because it is not actionable. If you are seeing a specific problem with fish running inside the ConEmu terminal emulator on MS Windows please open an issue with information that will allow a developer to reproduce or at least diagnose the problem.
