### ISSUE TITLE
Exported variables in functions are not propegated to nested function calls

### ISSUE THREAD

**Issue by rolfmorel** [fish-shell/fish-shell#2563]
Hi, I would like to have a function that sets a exported variable in the environment for arbitrary commands (including other fish functions). In short I would to be able to do:
    
    function external-soundcard
        set -x ALSAPCM front:CARD=USB
        eval $argv
    end

This does work as expected when `external-soundcard` is passed a binary's name/path as the argv command (e.g.`external-soundcard env` shows the new environment), but does not work when the first argument is another fish function. In this case this function does not see the exported variable.

I was able to reduce it to the following simple example. The first function `set_var`  takes the place of the `external-soundcard` command and the second function just checks if VAR was actually set. (Note that these functions no longer use `eval`.)
    
    function set_var
        set -x VAR var_set
        check_var
    end

    function check_var
        echo $VAR
        set -n
    end

Setting the exported value globally (`set -xg`) is not an option as this environment variable needs to be controlled per application.

**Comment by ridiculousfish** [comment]
I thought we had a bug about this somewhere...

**Comment by zanchey** [comment]
Isn't this by design? Using `function --no-scope-shadowing check_var` gives you the desired behaviour, I think.

**Comment by faho** [comment]
@zanchey: Even if it is intended, it's rather confusing, since which variables your command inherits now depends on if it is a function or not. Though it would be a medium-sized change in behavior.

**Comment by bucaran** [comment]
Why is the example given by the OP confusing?

```fish
function set_var
    set -x VAR var_set
    check_var
end

function check_var
    echo $VAR
    set -n
end
```

Fish docs are explicit about this. A variable whose scope is not specified will be local to the current scope by default. So, that `set -x VAR var_set` will create a new environment variable which is local to the `set_var` function.

**Comment by faho** [comment]
@bucaran:

```fish
$ set -lx var banana
$ fish -c 'echo $var'
banana
$ function t; echo $var; end
$ 
```

Or think of cases where external commands read env vars and you make wrapper functions. Think `ls` and $LS_COLORS - you _can't_ make local modifications to it and then still use the wrapper, because that won't inherit your changes.

IFS is a good point, though.

**Comment by bucaran** [comment]
If we agree on that anything inside the function has an isolated scope it makes sense, which is why we have the odd `--no-scope-shadowing`.

I didn't think about making wrapper functions of external commands, right, in that case things would not work as expected. Tricky!

**Comment by polyphemus** [comment]
Thanks guys, for my use case it works if I annotate the inner function (``check_var`` in the example) with ``--no-scope-shadowing``. 

Because I am only likely to use the ``external-soundcard`` function on a limited number of functions the above solution works for me (when I edit all these functions), but it does mean that in the case where I just want to propagate environment vars to non-adjusted functions I can only do this if I make the env var global, which is not something I would want to do in this case.

In more conventional shells (example is valid bash and zsh) I can do the following:

    function set_var() {  
          VAR=var_set check_var
    }
    function check_var() {
        echo $VAR 
    }

(Trying the same syntax in fish I get informed that `env` should be used which is of course not possible if you call a function.) So what I would actually like to have is a mechanism whereby an environment variable (maybe even normal vars) can be propagated into a function and which is then passed on into all child calls (as is done in zsh/bash when making more calls from ``check_var``).

**Comment by faho** [comment]
I've finally found the original - it's #1091!
