### ISSUE TITLE
[question] about pkg-config

### ISSUE THREAD

**Issue by Matrix-Zhang** [fish-shell/fish-shell#2569]
as bug  #982 :

```
g++ -o code code.cc (pkg-config opencv --cflags --libs | perl -pe 's/\s+/\n/g')
```

i would like sed more than perl

so i change perl to sed 

```
g++ -o code code.cc (pkg-config opencv --cflags --libs | sed -r -e 's/\s+/\n/g')
```

the fish shell says g++ file or command not found ??

why??

**Comment by faho** [comment]
What does the command substitution print, i.e. what does just running `pkg-config opencv --cflags --libs | sed -r -e 's/\s+/\n/g'` say? It should print one "-lSOMETHING" per line.

Is the `g++` printed in red? If so, you don't have g++ installed (`type g++` should tell you what fish thinks it should run when told to run g++).

**Comment by Matrix-Zhang** [comment]
it just a example,,,

actually, i was try to compile the mongoc example source

whitch command in bash is :

gcc -o connect connect.c $(pkg-config --cflags --libs libmongoc-1.0)

because of fish shell command substitutions, i change to

gcc -o connect connect.c (pkg-config --cflags --libs libmongoc-1.0)

it still not work, then i google it and find #982, so i have two choices

1) eval gcc -o connect connect.c (pkg-config --cflags --libs libmongoc-1.0)

2) gcc -o connect connect.c (pkg-config --cflags --libs libmongoc-1.0 |  perl -pe 's/\s+/\n/g')

these both ok

at last i have the qustion, why i change to use sed not work ? such as :

gcc -o connect connect.c (pkg-config --cflags --libs libmongoc-1.0 |  sed -r -e 's/\s+/\n/g')

it says gcc file or command not found....

**Comment by krader1961** [comment]
> the fish shell says g++ file or command not found 

Please provide the actual command you ran and the output. That is, cut and paste what you saw in your terminal. I ask that because your replacement of perl with sed should not result in a failure to find the g++ program (but could result in other failures). Also, tell use what operating system you are using.

On my Ubuntu Linux server your sed command produces the expected output. On my Mac OS X system it fails because that sed command does not recognize the -r option.

**Comment by zanchey** [comment]
I use `(pkg-config ... | tr -s ' ' '\n')`, although like all of these solutions this will blow up with embedded spaces.

**Comment by pickfire** [comment]
It works by default. I will just run `make -j4`.

**Comment by Matrix-Zhang** [comment]
my operating system is fedora 23 and the terminal is gnome-shell 3.18.

matrix@matrix-fedora ~> gcc -o connect connect.c  (pkg-config --cflags --libs libmongoc-1.0 |  sed -r -e 's/\s+/\n/g')
gcc: error: : No such file or directory

**Comment by krader1961** [comment]
Please tell us what is displayed when you run

```
pkg-config --cflags --libs libmongoc-1.0 | sed -r -e 's/\s+/\n/g' | cat -evt
```

What happens if you substitute the "tr" command suggested by @zanchey? That is:

```
gcc -o connect connect.c  (pkg-config --cflags --libs libmongoc-1.0 | tr -s ' ' '\n')
```

**Comment by Matrix-Zhang** [comment]
1)pkg-config --cflags --libs libmongoc-1.0 | sed -r -e 's/\s+/\n/g' | cat -evt

-I/usr/include/libmongoc-1.0$
-I/usr/include/libbson-1.0$
-lsasl2$
-lssl$
-lcrypto$
-lrt$
-lmongoc-1.0$
-lbson-1.0$
$

2 ) it's ok...

pkg-config --cflags --libs libmongoc-1.0 |  tr -s ' ' '\n' | cat -evt

-I/usr/include/libmongoc-1.0$
-I/usr/include/libbson-1.0$
-lsasl2$
-lssl$
-lcrypto$
-lrt$
-lmongoc-1.0$
-lbson-1.0$

it seems because of sed add more $ at the end of result...

**Comment by krader1961** [comment]
It is not "because of sed add more $ at the end of result". It is because the output of the pkg-config command contains trailing whitespace and your sed command turns that into an empty line. The tr (when invoked with the `-s` option) and perl commands do not do that. This doesn't cause a problem for bash and similar shells due to how they split on whitespace (their behavior in my opinion is broken). TBD (to be determined) is how to achieve a similar result in fish.

**Comment by Matrix-Zhang** [comment]
thank you for all yours help!!!
