### ISSUE TITLE
Runtime options to disable gettext?

### ISSUE THREAD

**Issue by jakwings** [fish-shell/fish-shell#2571]
I don't like the translations bundled with fish, although I can compile it without gettext but it is not convenient when I share fish with other people. Any good way to disable it without touching environment variables LC_xxx (and even system configuration)?

**Comment by faho** [comment]
For our scripts, defining an "_" function that just does `echo -n $argv` should do the trick.

For the compiled code... dunno, delete the catalogs?

**Comment by jakwings** [comment]
Thanks. Deleting the translation files (*.mo) can work.

**Comment by jakwings** [comment]
Oh, should not delete the translation files… should provide a `fish_translate off` command to call the gettext functions to use the default language (en).

**Comment by krader1961** [comment]
I'm confused. Why would you assume "en" is the default language? Yes, it tends to be the default in practice if no localization is in effect but there is absolutely nothing that requires english to be the default language used by a program in the messages it emits. Furthermore, the whole point of the LANG/LC_* environment variables (and system level config) is to allow the user to control the display of dates, times, etc. and the language used when displaying messages. I don't understand why you want fish to provide a means for overriding the language used when displaying messages separate from the localization of dates, times, currency, etc. Also, what don't you like about the translations bundled with fish? Wouldn't it be better to provide better translations?

**Comment by zanchey** [comment]
I'm not sure how others feel but I don't particularly want to implement this as it's hard to get right. One option is to try and come up with a way of disabling localisations just in fish - perhaps something like `set -gu LANG C; set -Ux LANG fr_FR.UTF-8`?

The French localisations need a _lot_ of work - my French is not great but there's some obvious mistakes.

**Comment by krader1961** [comment]
So the problem is that fish's localization is so bad that people would rather disable localization just for the fish shell and not any commands it spawns? That is, they want the LANG/LC_* env vars to be retained when spawning external commands but ignored by fish? When I worked at Google, even though I worked on internal facing projects that did not require localization, I had visibility into what was required for a public facing project to be localized. It is a metric ton of work that is hard to do well in an open source project like fish that depends on volunteers.

The key question is whether localization of dates, times, currency, collating sequence, etc. as specified by the LANG/LC_* vars should be honored by fish while providing a way to disable translation of emitted messages. That would seem to be what @jakwings is asking for. Or should there be a way to tell fish to ignore all localization. Which seems to be what @zanchey is proposing.

As someone whose native language is English I am not qualified to answer that question. But I will point out that I don't see a viable alternative to an environment variable or a new command (or var) that can be set in ~/.config/fish/config.fish. I'm leaning towards a "private" var (i.e., one that begins with "_fish_") rather than a new builtin command. A variable makes it possible to set that behavior via an environment var that is exported before fish is started while still making it possible to establish the behavior early in the  initialization of the shell via a `set` statement in __~/.config/fish/config.fish__ or equivalent.

**Comment by jakwings** [comment]
Sorry for the confusion, everyone. My locale is set to en_US.UTF-8 but gettext is initialized with the system locale. I forgot to do more research about gettext and hurrily proposed a new function.

Now I find that it is a problem of gettext, will submit an issue later.
