### ISSUE TITLE
Opening error

### ISSUE THREAD

**Issue by ayhankuru** [fish-shell/fish-shell#2576]
Linux - Elemantary os
3.19.0-33-generic
Fish, version 2.0.0
![---](https://cloud.githubusercontent.com/assets/2834954/11477271/e4c45f66-978f-11e5-88e1-f3b35e2d40c9.png)

**Comment by krader1961** [comment]
Can you confirm that `trap -l` does not include __WINCH_? If so then the thing to do is wrap that function definition in this block:

```
if string match WINCH (trap -l) >/dev/null
...
end
```

Although it would be really nice if the `trap` command had a __-q__ option to query whether a given signal was supported.

**Comment by faho** [comment]
@krader1961: Not really applicable here - __fish_config_interactive is upstream fish territory, and `string` isn't in a release yet - especially not in 2.0.0.

@ayhankuru: Please try with a current fish release - 2.2.0 (released in july) would do nicely, but even 2.1.1 (released september of last year) would be an improvement.

The `trap -l` output would still be nice, though I strongly suspect this should be fixed by b32f770a69527eca4e76b9e8f648a39da17911cb.

As a workaround, you can also change your locale.

**Comment by krader1961** [comment]
> I strongly suspect this should be fixed by b32f770.

Huh? Signal names are case-insensitive. So while that change improves the style of the code it shouldn't make any functional difference. Also, my proposed fix wasn't really meant for the OP but for possible inclusion in the current development branch.

**Comment by ayhankuru** [comment]
@faho problem continues 
![ekran goruntusu - 2015-11-30 20 06 37](https://cloud.githubusercontent.com/assets/2834954/11480050/04f11302-979e-11e5-8e9c-3096f3fde84d.png)
 
![ekran goruntusu - 2015-11-30 19 52 30](https://cloud.githubusercontent.com/assets/2834954/11480056/125667d6-979e-11e5-8b93-6403ad5f5c42.png)

**Comment by ayhankuru** [comment]
@faho and problem gone, maybe new version updated this patch b32f770

**Comment by faho** [comment]
>Huh? Signal names are case-insensitive.

In theory, yes. In practice, this caused issues with the turkish locale since it has dotless "i"s and dotted "I"s in addition to the dotted lowercase and dotless uppercase versions. See #2236 and #2241.

@ayhankuru: Glad we could help! I'm writing the first try off as a fluke.

**Comment by krader1961** [comment]
I'm willing to bet that case-insensitive signal names were added after the 2.0 release.
