### ISSUE TITLE
Remove special treatment for colon-separated env vars

### ISSUE THREAD

**Issue by jakwings** [fish-shell/fish-shell#2596]
I think that feature brings more troubles than convenience. The whitelist is hard-coded and keeps changing, which sure breaks things again and again. By removing this feature we can just break once.

**Comment by faho** [comment]
>The whitelist is hard-coded and keeps changing

It never did since its introduction in c0b8e81b023bf1f118311a060662bea1ad565a19. Before that, there was a blacklist of $DISPLAY, otherwise all variables would be split on colons.

Anyway, in #436 I proposed making a function or builtin to split variables on colon which means the list could be moved to scripts, making splitting easier accessible to the users. This was then amended by @ridiculousfish to also include storing the separator so that outgoing variables would be joined by that same character. This makes the behavior more familiar and explicit.

I believe breaking this for $PATH especially to not be worth it, because that's well-documented, probably used in a lot of scripts and also a nice introduction to fish's lists (which are IMHO one of the killer features).

**Comment by jakwings** [comment]
Well, then only PATH is used most. CDPATH and MANPATH rarely. And recently people complain about MANPATH in #2090, and CDPATH in #2106.

If that is really important for $PATH, then I suggest minimalize the whitelist to `["PATH"]`, and never extend it.

> … This was then amended by @ridiculousfish to also include storing the separator so that outgoing variables would be joined by that same character. This makes the behavior more familiar and explicit.

No need to make it more complicated. `split` and `join` are sufficient. And as @krader1961 said in #436:

> In other words, why are the elements of $PATH separated by colons in the exported environment but spaces in the output of echo "PATH is $PATH"

I don't want to always query the internal representations of those `splitenv`ed variables when writing scripts. That's terrible.

**Comment by jakwings** [comment]
Some simple statistics about the use of PATH, CDPATH and MANPATH from GitHub:

* PATH: ~18100 https://github.com/search?p=4&q=PATH+extension%3Afish&ref=searchresults&type=Code&utf8=%E2%9C%93
* CDPATH: ~75 https://github.com/search?q=CDPATH+extension%3Afish&type=Code&ref=searchresults
* MANPATH: ~260 https://github.com/search?q=MANPATH+extension%3Afish&type=Code&ref=searchresults

And many of them are just dotfiles for personal use.

**Comment by krader1961** [comment]
Can we please continue this discussion in issue #436? We should also change the subject line of that issue since it is pretty clear no one really cares about fish's internal representation of vars (or at least hasn't made the case that it matters). Whereas lots of people care about reducing the current whitelist of auto-split vars to just __PATH__ and maybe __CDPATH__ or eliminating it completely and leaving it to up to each function or script to split and rejoin the value of these vars. In any case we really need to focus this discussion in a single issue.

**Comment by jakwings** [comment]
Why #436? Its title is about true array, not the whitelist. The whitelist/`splitenv` magic cannot solve the real problem, and is off-topic there. Now we have mentioned #436, everyone can still first read the comments there and come back to here later.

**Comment by krader1961** [comment]
> Why #436?

I already said why but I'll repeat myself. Because that issue hasn't about about the internal representation of arrays in a very long time. There has, however, been a vibrant discussion on the topic of this issue. Yes, the subject line of that issue needs to be changed. As I noted in my comment to issue #2456 there's also issue #2090 which talks about setting MANPATH. And issue #2596. And probably several more. Argh! :-)

**Comment by jakwings** [comment]
> We should also change the subject line of that issue since it is pretty clear no one really cares about fish's internal representation of vars (or at least hasn't made the case that it matters).

It is unfair. And I do care about true arrays. Only half of the comments there are about this issue. I can help improve the documentation if it is impossible to change the internal structure of arrays.

**Comment by krader1961** [comment]
I don't understand what you mean when you say "it is unfair", @jakwings. I think part of the problem is that you and I have attached different meanings to the phrase "true arrays" at different times. When I first read issue #436 I interpreted what was written to mean, among other things, that fish itself used an inefficient representation internally. Upon reading those comments again I see that is probably not what the author intended. But that only makes the problem statement even more confusing because how do you represent a "true array" in a serialized manner without resorting to an established standard (e.g., JSON representation) or private mechanism like Python's pickle representation (which is effectively what fish does).

The primary concern expressed by the initial comment in issue #436 is that \x1e is always used when reading or writing arrays to an external source, like the environment var name space, with the exception of the whitelisted special-case vars __PATH__, __CDPATH__, __MANPATH__ for the env var name space but not private data stores. Yes, I realize that at the time that issue was opened the set of special-case env vars might have been different but that is not relevant to this discussion. Your concern and the concern of the person who opened issue #436 are essentially the same: How to translate between an external representation and the internal representation of an env var. That persons proposal to implement "true arrays" also does not address the problem of how to represent the sequence of array values when writing them to an external store. Be that the ~/.config/fish/fishd.* file or the process environment var name space.

**Comment by jakwings** [comment]
Can you please don't continue to mess around these issues here? If *you think* the title of that issue is confusing and should be changed, please ask the poster first before arguing with me. Now you've make my post messy with off-topic comments.

> That persons proposal to implement "true arrays" also does not address the problem of how to represent the sequence of array values when writing them to an external store.

Yeah, it seems they are foolish. But please really tell them and keep discussing, instead of going off-topic and ignore them. Communications please!

**Comment by krader1961** [comment]
Okay, I'll be blunt. Your proposal isn't helpful. People will attempt to treat __PATH__ and other environment vars as arrays. Eliminating the existing whitelist won't fix this. People will still want to treat __PATH__ and other env vars as arrays. The question is what to do when someone does

```
set -x PATH /dir1 /dir2
```

If __PATH__ is no longer special-cased and there is no mechanism for serializing that array to a string that is meaningful to sub-processes what exactly should happen?

**Comment by jakwings** [comment]
It is your people, and I am not your person. Please refer to the comments of me and faho above. I sure know what will happen with that breaking change.

**Comment by krader1961** [comment]
Take a deep breath, @jakwings, and calm down. If you do know "what will happen with that breaking change" you have not said so clearly in this issue. You have only said that it is better to pay that price by breaking backward compatibility one more time. You have not said anything about what happens when people (and extant scripts) continue to treat __PATH__ as an array.

I am not opposed to your proposal. I am simply pointing out that your proposal leaves a lot of important details undefined.

**Comment by jakwings** [comment]
@krader1961 Thank you. I'm a new user and I don't use many third-party plugins, so I can pay the price. Since others aren't, I then suggest minimizing the whitelist. (I don't like verbose mode for every small thing.)

And another point due to #2022: always querying the vars in the whitelist before doing variable expansion is troublesome.

That's all. I'm having my bad days recently, so I'm not serious about these quarrel. Just want to be simple and quiet.

**Comment by jakwings** [comment]
I just feel bad now. If anyone is interesting, please reopen this issue.

**Comment by krader1961** [comment]
@jakwings There is no reason for you to feel bad about opening this issue. Most people, including me, have opened issues that mirror, or are equivalent to, already open issues. Even when we search to see if a given issue has been reported there is no guarantee we'll find a relevant, open, issue. In the past three decades I have lost count of the number of times I reported a problem that had already been reported.

Please contribute to the discussion at issue #436. You have ideas about how to improve the current behavior. I simply want to focus the discussion in a single issue.
