### ISSUE TITLE
Setting `fish_term24bit` to `1` breaks colors in neovim terminal

### ISSUE THREAD

**Issue by raichoo** [fish-shell/fish-shell#2600]
I just wanted to report this so that fellow `neovim` users might know what it going on.

Commit `b73bf53bd30cb8b6056888a473368968041dbe66` sets `fish_term24bit` to `1` on `truecolor` terminals. This breaks my highlighting in `neovim` like so:

![screenshot from 2015-12-11 23-10-54](https://cloud.githubusercontent.com/assets/151506/11757101/0c3ca53a-a05f-11e5-9e64-dac2a48fef9a.png)

What I'm expecting is something like this:

![screenshot from 2015-12-11 23-03-53](https://cloud.githubusercontent.com/assets/151506/11757108/165e9082-a05f-11e5-9860-c04ec003fa71.png)

I work around this issue by putting something along these lines into my `config.fish`.

    if test "$NVIM_LISTEN_ADDRESS" = ""
     # snip
    else
      set -u fish_term24bit
      #snip
    end

It's a little bit of a hack but does the job.

Kind regards,
raichoo

**Comment by ridiculousfish** [comment]
Thanks for the report! I don't understand what the issue is however. Is it that neovim has its own terminal emulator, but it's picking up environment variables from the "root" terminal emulator, and therefore fish thinks 24 bit color is supported?

**Comment by faho** [comment]
@raichoo: Is [this](https://github.com/raichoo/rcfiles/blob/master/nvimrc) still your nvimrc?

What's your config.fish?

>I work around this issue by putting something along these lines into my config.fish

Last I heard and when I just tested it, nvim assumes the shell is sh-compatible, so you'd have `set shell=/bin/sh` in your rc or it breaks in new and interesting ways. Can you try that?

The reason I'm asking is because it seems nvim _inheriting_ fish_term24bit breaks stuff, which is weird because to nvim it should just be another environment variable that it shouldn't care about. So it seems it's running fish somewhere which is known to cause issues.

**Comment by faho** [comment]
I just tried that nvimrc verbatim, and it works for me. So I'd like to take a look at your config.fish now.

Also, what is your terminal emulator?

**Comment by pickfire** [comment]
@raichoo, don't use `fish` as the `shell` for `nvim` as it will break a lot of things. Use `set shell=/bin/sh` instead.

I am not sure how to check if fish is using 24bits color. I can't reproduce this by:

1. `nvim`
2. `:terminal`
3. `fish`

**Comment by raichoo** [comment]
`fish` works fine for me with `nvim`.

@ridiculousfish: I've set turned on true color support for `nvim` but the build in terminal does not support true colors (this will be fixed some time in the future). I suppose this is where the mixup happens.

**Comment by pickfire** [comment]
@raichoo, take a look at https://gist.github.com/XVilka/8346728 to make sure you have true colors support in terminal in order to use true colors in `nvim`.

**Comment by raichoo** [comment]
I have true color support. It's the built in terminal of `nvim` that does not support that yet (there is an open issue addressing that).

**Comment by faho** [comment]
@raichoo: Again, what is in your config.fish? I've ran ":terminal" in nvim, which then launched an embedded fish, with your _exact_ nvimrc (at least what you have uploaded to github) and it worked. (This is with neovim 0.1.1 in konsole 15.08.3 on archlinux)

**Comment by pickfire** [comment]
@raichoo, as @faho asked: **What is your terminal emulator?**

That's easy for us to test it and to check for problems.

**Comment by faho** [comment]
@raichoo: Ping?

**Comment by rakr** [comment]
Not sure if it is the right place as I'm just discovering fish.
My setup: Iterm2 nightly Build 2.9.20160108-nightly
config.fish contains `set -u fish_term24bit` and everything works perfectly.
Again just a couple of hours on fish, but amazing so far. I thought I had the same issue as mentioned here, but realised that was because I was using an alias in zsh that I didn't create on fish (face palm)

**Comment by pickfire** [comment]
@rakr, if the terminal is detected to support true colors (by `$TERM`), fish will automatically set `fish_term24bit` for you.

You can actually use `set -Ux fish_term24bit 1` instead of setting it in `config.sh` if you want to set it everytime, but note that it will break framebuffer.

**Comment by krader1961** [comment]
@pickfire, You said

> if the terminal is detected to support true colors (by $TERM), fish will automatically set fish_term24bit for you.

As far as I can tell that is not true. Fish will, however, automatically set __fish_term256__ based on $TERM. See function __update_fish_color_support__ in input.cpp.

**Comment by faho** [comment]
@krader1961: https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_config_interactive.fish#L289-L296. It's a hack, but it's the best we can do.

I'll have to recheck which of those cases is true in nvim's terminal.

**Comment by krader1961** [comment]
Ah, yes, I was only looking at the core C++ code, @faho, and had forgotten about that recent addition to the interactive function. But that raises the question of whether we should move the equivalent logic for setting __fish_term256__ out of the C++ __update_fish_color_support__ function and into that fish script function.

@raichoo, can you tell us what the values of the following env vars are inside your neovim terminal: KONSOLE_PROFILE_NAME, ITERM_SESSION_ID, TERM, VTE_VERSION, COLORTERM?

**Comment by faho** [comment]
Urgh, I've found the issue.

neovim's terminal swallows the 24bit sequences without interpreting them, even in a terminal. That means e.g. `echo \e"[38;2;85;136;255mbanana"` will show a white "banana". This is just what fish will send for `echo (set_color 5588FF)banana` _if_ fish_term24bit is set. (This does not change with NVIM_TUI_ENABLE_TRUE_COLOR set)

The reason I didn't see that is because fish still sends the old-school sequences for named colors (`set_color banana`).

>can you tell us what the values of the following env vars are inside your neovim terminal: KONSOLE_PROFILE_NAME, ITERM_SESSION_ID, TERM, VTE_VERSION, COLORTERM?

TERM is set to xterm-256color, the rest seem to be inherited from the environment. There's also a $NVIM_LISTEN_ADDRESS set.

There's a few ways to deal with it:

- Ignore it - nvim's supposed to get 24bit support soon (tm)

- Back out the 24bit enabling entirely

- Guard it with `not set -q NVIM_LISTEN_ADDRESS`

Of those, I like the last the most, though it's possible neovim GUIs also set that and _do_ interpret the 24bit sequences properly, I consider (and this was a major goal of that way of enabling 24bit) it more important that nothing gets the colors _wrong_ than that everything gets the colors right.

**Comment by faho** [comment]
@raichoo, @rakr: I believe this is now fixed - by disabling 24bit for nvim.

**Comment by rakr** [comment]
Great thanks
