### ISSUE TITLE
is there a way to cd back to current directory when exit from fish?

### ISSUE THREAD

**Issue by rainchen** [fish-shell/fish-shell#2624]
let's say when I am in `/abc` path and using fish-shell, for some purposes I have to exit fish-shell to switch to bash-shell to run some bash-only commands, I want it auto cd `/abc` path after I run `exit` in fish-shell, any ideas?

**Comment by faho** [comment]
For exactly what you're asking for, there's no clean solution.

The issue is that environment variables are _inherited_ by childprocesses (in this case your fish is a child of your bash process) by way of copying the values. That means changes don't propagate upwards.

Now, what you could do is have fish echo something on exit that bash then `eval`s, but then the issue becomes what you do with fish's other output. 

A more workable "solution" is to have fish write the pwd to a file like

```fish
function writepwd --on-variable PWD
    pwd > /tmp/fishpwd
end
```

and then have bash read that (by way of alias or function).

However, if you're mostly in fish and only occasionally drop to bash, why not run it the other way around? Why not run fish and then execute `bash`, do your commands and exit bash when you want to go back to fish? This way fish's PWD will be copied in bash, where you can then execute commands and drop back to fish when you are done.

**Comment by rainchen** [comment]
@faho I "resolve" this issue by using a similar solution you mentioned, here is the steps:

1). define an alias named `fishshell` using
```
alias fishshell='fish; cd-last-pwd; rm -f /tmp/lastpwd'
# cd from /tmp/lastpwd
function cd-last-pwd {
  local lastpwdpath=/tmp/lastpwd
  if [[ -e "$lastpwdpath" ]]; then
    local lastpwd=`cat $lastpwdpath`
    #echo $lastpwd
    cd $lastpwd
  fi
}
```

2). add a `bye` function for fish-shell as

```
function bye
  pwd > /tmp/lastpwd
  exit
end
```

3). set `fishshell` as my default shell

Now I can run `bye` to exit fish-shell and auto switch back to the last directly where I was.
Would be cool if there are some hooks like `after exit` in fish-shell, then I can put these codes in just one config file.

**Comment by faho** [comment]
>Would be cool if there are some hooks like after exit in fish-shell, then I can put these codes in just one config file.

Well, "after exit" won't work because at that point fish won't be running anymore to execute anything. "before exit" might be possible, though I'm not sure if `function SOMENAME --on-process-exit %self` won't already work. For this particular thing, I've already gave you an example using "--on-variable PWD", which will be executed every time the PWD changes, which at least means you won't need to use `bye` instead of `exit` anymore. (Also note that all these solutions have problems with multiple running fishes - you'd need to add e.g. the PID to the file then - in fish that'd be "%self" for fish's PID, and in bash IIRC "$$" for the last run PID)

**Comment by rainchen** [comment]
the `function SOMENAME --on-process-exit %self` feature is quite dandy, I use it to update the `/tmp/lastpwd` so that I can quickly cd to the last dir in other terminal windows, and I don't care the PID case, it's working well for me now, thx @faho 's suggestion.
