### ISSUE TITLE
Git autocompletion should ignore the remote part in branch name

### ISSUE THREAD

**Issue by Kauko** [fish-shell/fish-shell#2628]
This was first reported and supposedly fixed in https://github.com/fish-shell/fish-shell/issues/675, but I can't get it to work.

Git has a feature where if the user types `git checkout foo` and a local branch does not exist by that name, git will check whether there are remote branches by that name, and if git finds any, a new tracking branch is set up and checked out.

Fish's git autocomplete should use this feature. When I type `git checkout some-feat`I want it to autocomplete to `git checkout some-feature`, instead of `git checkout origin/`.

**Comment by faho** [comment]
Did you install the updated git completions? Note that these currently require a git-build of fish as they depend on the unreleased `string` builtin.

If you have, do you get completions described as "Remote branch"?

What this does is complete any branch name that is unique among the remotes and not the name of a local branch (which is handled by another function and described as just "Branch"). That means e.g. when I complete `git checkout ` in a clone of the fish repo, I get "apropos" as a remote branch, but not "help", because that's both in my clone and here (i.e. "faho/help" and "origin/help" exist).

**Comment by Kauko** [comment]
Thank you for the reply! I'm downloading xcode now and I'll then build fish myself.

I'm curious, is this documented anywhere? I tried looking for information before I opened this issue, but couldn't find anything.

**Comment by Kauko** [comment]
It worked, thank you! Here's how I did it if anyone finds this with google:
1. Download the master branch as a zip, extract
2. ´cd Downloads/downloaded-fish-folder´
3. ´xcodebuild install´
4. ´sudo ditto /tmp/fish.dst /´
5. ´fish_update_completions´ (not sure if this is needed)
6. Restart iterm

**Comment by faho** [comment]
>I'm curious, is this documented anywhere? I tried looking for information before I opened this issue, but couldn't find anything.

What would you like to have documented? That the fix is in the next release? That it requires features in the next release? Those are pretty normal. Documenting the latter is unnecessary as, as soon as the commit is in a release the feature it depends on will be as well. Documenting the former isn't needed because there's `git tag --contains` (or the tag label on the github commit view).

**Comment by Kauko** [comment]
I did not mean to imply that I'd like to have it documented somewhere, rather I just wanted confirmation that this is not documented anywhere. Just wanted to make sure I didn't miss some website full of information.

Anyway, the problem is fixed. Thanks a lot for your help and your work on fish, loving it! :)

**Comment by aristidesfl** [comment]
Is this supposed to be available in 2.6.0 or is it necessary to install different autocompletions?

**Comment by faho** [comment]
@aristidesfl: A version of it is available since 2.3.0.
