### ISSUE TITLE
Remove paths from PATH environment variable, how?

### ISSUE THREAD

**Issue by simonbcn** [fish-shell/fish-shell#2639]
I've read this closed issue #527 but the problem still exists. Where does the PATH when I enter in fish shell?
`fish_user_paths` is a good alternative to add paths to `PATH`, but in my case, I need remove some paths from my `PATH`. How can I do this?

**Comment by derekstavis** [comment]
You can use the builtin `set` to remove components from any variable. Remember that in fish every variable is a list.

Imagine you have the following path

```fish
$ echo $PATH
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /usr/texbin
```

If you want to remove `/opt/X11/bin` from the `PATH` you can use `set -e` with the list index you want to remove
```fish
$ set -e PATH[6]
```

Remember that fish index lists starting in 1, not in 0.

**Comment by simonbcn** [comment]
But that only works for that session, in another session PATH again has the removed paths.

**Comment by derekstavis** [comment]
You need to check where the paths are being added to the `PATH` variable. Check your `config.fish` and any package installed via Oh My Fish.

**Comment by simonbcn** [comment]
Ok, those paths are assign in system-wide (no `config.fish` nor `omf`).

**Comment by kalsan** [comment]
Since this issue shows up high on Google but doesn't yield a clear answer, here's a link to a directly applicable solution:

http://superuser.com/questions/776008/how-to-remove-a-path-from-path-variable-in-fish/1091983#1091983?newreg=73ef956cba5a413aa6f2d21a85d88f5f

**Comment by explosic4** [comment]
Please note that when delete multiple paths at the same time, each command will change the index of paths, be careful and remember to adjust the index after each command.
```shell
> echo $fish_user_paths | tr " " "\n" | nl
     1	/root/Android/Sdk/platform-tools
     2	/root/Android/Sdk/tools
     3	/home/explosic4/.fzf/bin

> set --erase --universal fish_user_paths[1]
> set --erase --universal fish_user_paths[2]
#   after delete item 1, the results should be:
#   1	/root/Android/Sdk/tools
#   2	/home/explosic4/.fzf/bin
#   thus the command actually delete the 3rd item in original order
> echo $fish_user_paths  | tr " " "\n" | nl
     1  /root/Android/Sdk/tools
```

```

**Comment by JeanMertz** [comment]
I just came across this. I'm not sure if there is built-in functionality to simplify this, but I whipped up a quick function that makes it easy to list/add/erase path values:

```
$ fish_user_paths --help
USAGE: fish_user_paths [--add PATH|--erase NUM]
```

```fish
function fish_user_paths
    set -l usage "USAGE: "(status current-function)" [--add PATH|--erase NUM]"
    set -l count (count $argv)

    if test "$count" != "0"
        if test "$count" != "2"
            echo 1>&2 "$usage"
            return
        end

        if test "$argv[1]" = "--add"
            set --universal fish_user_paths $argv[2] $fish_user_paths
        else if test "$argv[1]" = "--erase"
            if test (count $fish_user_path) -lt $argv[2]
                echo 1>&2 "index $argv[2] does not exist:"
                echo 1>&2
                fish_user_paths >&2
                return
            end

            set --erase --universal fish_user_paths[$argv[2]]
        else
            echo 1>&2 "$usage"
            return
        end
    end

    echo $fish_user_paths | tr " " "\n" | nl
end
```

**Comment by faho** [comment]
@JeanMertz: You'll want to look at `contains -i`. That prints the index of the match, so you can use it to easily remove a path _by name_.

E.g.

```fish
if set -l ind (contains -i -- /usr/local/bin $fish_user_paths)
    set -e fish_user_paths[$ind]
end
```

**Comment by ipatch** [comment]
@explosic4 

building up your answer posted above I wrapped what you posted into a fish function to list the entries in my `$PATH` a little more elegantly, but one thing I noticed is with the below command,

```shell
echo $PATH | tr " " "\n" | nl
```

...the above command will inaccurately list entires contained within the `$PATH` especially ones that contain a _space_ <kbd>␣</kbd> and will be split across multiple entries (thus when removing entries from the `$PATH` could remove the wrong entry), so I ended refining the function I created based on the expression posted above to hopefully list entries that contain spaces or otherwise do not start with a _forward slash_ <kbd>/</kbd> and the below is what I came up with

cheers 🍩
Chris

```shell
function path_pretty_redux --description 'print a pretty listing of the $PATH'
  set -l p (echo $PATH[1..-1])
  # ❗️ requires GNU sed not BSD
  set -l p_colon (echo "$p" | sed s'/\ \//:\//g; s/\ ~/:~/g; s/\ .:/:.:/g')
  echo "$p_colon"  | string split ":" | nl
  echo "The above list are the ordered entries in the \$PATH"
  echo "$fish_user_paths"
  echo "The above list are the ordered entries in the \$fish_user_paths"
end

for unabridged version of the func [see](https://github.com/ipatch/dotfiles/blob/master/config/fish/functions/path_pretty_redux.fish)

**Comment by faho** [comment]
>  set -l p (echo $PATH[1..-1])

Okay, this just broke your $PATH if any entry contains spaces. [1]

`echo` will output all its arguments on one line, with spaces between them. `echo $PATH` will output all $PATH entries with one space between them. That means a path entry with a space in it is now indistinguishable from another path entry.

(also `$PATH[1..-1]` is *exactly* the same as `$PATH`. There is absolutely no need to specify the indices explicitly)

>  set -l p_colon (echo "$p" | sed s'/\ \//:\//g; s/\ ~/:~/g; s/\ .:/:.:/g')

This adds colons where you *think* they need to go, but it's actually already broken, because you've already lost information about what each entry is. You've already mushed them together, separating them again is hard.

Also, it is entirely unnecessary.

Just do

```fish
for i in (seq (count $PATH))
    echo $i $PATH[$i]
end
echo "$fish_user_paths"
```

This doesn't mush the entries together in the first place, so it can handle arbitrary path entries. Whether they contain spaces or newlines or whatever.

Also it avoids the ugly `sed` invocation and the call to the external `nl`.

[1]: Technically, spaces before a "/". But since that's allowed in Unix paths (because in unix paths basically anything is) it is good practice to avoid even that.

Also:

> `sed s'/\ \//:\//g; s/\ ~/:~/g; s/\ .:/:.:/g'`

Sed uses whatever character comes after the "s" as the separator, it doesn't have to be "/". This helps because you can choose one you don't use literally. "_" is often a good choice:

```fish
sed 's_\ /_:/_g; s_\ ~_:~_g; s_\ .:_:.:_g'
```

**Comment by shilangyu** [comment]
I removed the path from `$fish_user_paths` and yet the old path still persists in `$PATH`. Is that normal? 

```sh
➜ string join \n $fish_user_paths
/home/shilangyu/flutter/bin
/home/shilangyu/.local/bin
/home/shilangyu/.npm-global/bin
/home/shilangyu/go/bin
/home/shilangyu/.cargo/bin
```

```sh
➜ string join \n $PATH
/home/shilangyu/flutter/bin
/home/shilangyu/.local/bin
/home/shilangyu/.npm-global/bin
/home/shilangyu/go/bin
/home/shilangyu/.cargo/bin
/usr/lib/jvm/java-13-openjdk-13.0.2.8-1.rolling.fc31.x86_64/bin
/usr/local/bin
/usr/local/sbin
/usr/bin
/usr/sbin
```

jvm path is the intruder and I cannot get rid of it.

**Comment by zanchey** [comment]
@shilangyu, what version are you running? This works ok for me on 2.7.1 and 3.1.0-465-g4884a4080. Please consider opening a new issue if this is an ongoing problem.

**Comment by shilangyu** [comment]
Yeah sorry, I shouldn't be commenting on a closed issue. I made a mistake of not restarting my computer before complaining 🤦‍♂️ it's all good afterwards. Sorry again

**Comment by rocketraman** [comment]
Also useful here, to find the index of the path that needs to be removed as per comment https://github.com/fish-shell/fish-shell/issues/2639#issuecomment-167615175:

```
string join \n $PATH | nl
```

**Comment by jsx97** [comment]
I vote to re-open this issue and to changing its status from "Question" to something like "TODO".

I have added `/Users/john/bin` by adding `fish_add_path $HOME/bin` to my `config.fish`, and now I cannot understand how to remove it from there.

Yes, I did read answers posted here: http://superuser.com/q/776008, but hey, isn't it the whole idea of fish is that it just works out of the box?

There is `fish_add_path`, and now we need `fish_remove_path` or something like this, isn't it?
