### ISSUE TITLE
Feature request: configure option to change the #! lines in python scripts

### ISSUE THREAD

**Issue by amluto** [fish-shell/fish-shell#2655]
On Fedora, I currently patch all the shipped Python scripts to start with

    #!/usr/bin/python3

It turns out that, on EPEL, we'll want something different.  Other distros might do there own thing here.

Any chance we could get a configure option to set the path to python (defaulting to "/usr/bin/env python")?

**Comment by krader1961** [comment]
Did you mean to create this issue in the fish-shell project? This project has just four python scripts and they all use `#!/usr/bin/env python`. I only looked at __create_manpage_completions.py__ but it explicitly detects whether it is running under python2 or python3 and should do the right thing in each case. I don't see a need to complicate the configure script and related tooling. Can you elaborate on what you think should happen, and more importantly, why you're making this request?

**Comment by amluto** [comment]
The scripts do detect whether they're running under Python 2 or 3.  The
problem is that, on Fedora, they should run as Python 3, since Fedora
doesn't ship Python 2 by default.  So running /usr/bin/env python would
force the fish package to pull in all of Python 2 to prevent it from
failing to start the Python scripts.

It would be nice if I could ask fish to generate scripts that start with:

#!/usr/bin/python3

by specifying an appropriate config option.  I currently do this by
manually patching the scripts.

**Comment by krader1961** [comment]
> So running /usr/bin/env python would force the fish package to pull in all of Python 2 to prevent it from failing to start the Python scripts.

I cannot make heads or tails of that sentence. If Fedora doesn't install python2 by default how exactly will fish's shebang line force it to "pull in all of python2"? Do you not have a symlink from __python__ to __python3__?

**Comment by amluto** [comment]
On Jan 4, 2016 6:22 PM, "Kurtis Rader" <notifications@github.com> wrote:
>>
>> So running /usr/bin/env python would force the fish package to pull in
all of Python 2 to prevent it from failing to start the Python scripts.
>
> I cannot make heads or tails of that sentence. If Fedora doesn't install
python2 by default how exactly will fish's shebang line force it to "pull
in all of python2"? Do you not have a symlink from python to python3?

Exactly.  "python" is Python 2 on Fedora, and it may or may not exist.  If
I didn't patch fish, the fish would need to depend on python2.

See also https://www.python.org/dev/peps/pep-0394/

**Comment by krader1961** [comment]
That PEP is now five years old and as such its recommendation regarding the requirement that __python__ refer to __python3__ is questionable. It also contains this statement:

> however, end users should be aware that python refers to python3 on at least Arch Linux (that change is what prompted the creation of this PEP), so python should be used in the shebang line only for scripts that are source compatible with both Python 2 and 3.

Since the fish scripts are (or should be) compatible with both python major versions there shouldn't be a problem. Unless, of course, a distro has chosen not to install python2 and instead stub out the __python__ command with some sort of "Sorry, but you need to install python2" error. I guess I don't understand why you don't make __python__ a symlink to __python2__ if that is installed else symlink to __python3__?

I can see two solutions:

1. You're welcome to submit a change to this project to make your life easier.

1. Fish requires python3 for its handful of scripts. This would allow us to simplify those scripts and eliminate potential sources of bugs.

**Comment by amluto** [comment]
Fedora *does* make python a symlink to python2, but only if python2 is
installed, and that's not the default.  The Python 2 distribution is fairly
large, so avoiding dependencies on Python 2 is nice.

If I find some spare time, I'll send a patch.

I wouldn't object if fish switched its default, but that's a much bigger
deal.

**Comment by pickfire** [comment]
@amluto, that's like how Arch symlink `python3` as `python` but others symlink `python2` as `python` so it would cause some problem in running, most of the time you could use something like this IIRC:
```
make PYTHON=/usr/bin/python2
```

**Comment by oranja** [comment]
Just wanted to add to @pickfire's, @amluto's and @krader1961's points that I think it's a much healthier approach to set minimum requirements instead of trying to make everyone happy. It's hard to both build the shell of the future and strive to support the past in the same time. Needless to say, it also makes development and testing harder.
Having said that, **python2** still seems pretty much alive and kicking, at least in terms of usage. On the other hand, I don't know if assuming that Fish's user base all have **python3** readily available is a safe assumption. Personally I think it would be best to resort to setting **python2** (.7?) the minimum requirement (and the only requirement for now), and still try to make the scripts as ready as reasonably possible for a switch to **python3**.
Auto-detection resonates as needlessly complex to me. In the same manner, I'd vote for something like `#!/usr/bin/env python2` or `#!/usr/bin/env python3` if these are more compatible with a variety of systems (than their `/usr/bin/pythonX` counterpart). However, `#!/usr/bin/env python`, when you have no idea which major version you're going to get, sounds needlessly risky.
To come back to the original suggestion, I find the idea of such config option either a shoot in the foot or misleading. A shoot in the the foot if it's meant as a promise that Fish's python scripts will keep supporting both python 2 and 3. Misleading if there is no such intention, but there's still an option to point Fish to any version of python one desires.

Perhaps it is constructive to acknowledge what is the situation with each popular distro.? 
Fedora 23:

    /usr/bin/python -> python2
    /usr/bin/python2 -> python2.7
    /usr/bin/python3 -> python3.4

**Comment by pickfire** [comment]
@oranja: supporting both like now is better.

**Comment by krader1961** [comment]
It's been more than three months with nothing from the Fedora project. The current behavior appears to be acceptable for everyone else. We'll certainly accept a patch that provides more flexibility as long as it doesn't break any existing use cases. I don't see any reason for the fish developers to put effort into changing the current behavior given the risks of breaking other distros.
