### ISSUE TITLE
history --merge not working

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#2658]
According to https://github.com/fish-shell/fish-shell/issues/825 `history --merge` should merge the history of other sessions with the current one. Running `history --merge` returns a $status of 1 and invoking `history` thereafter does not show the history of other sessions.

Should this work as I expect?

**Comment by krader1961** [comment]
It works unless the history file is not in the expected format. For example, I merged PR #2458 then built and ran the resulting custom fish. That added text to my history file that `history --merge` doesn't know how to handle (see my comment to the related issue #2398).

It seems to me fish should report why the merge failed. Whether fish should be more forgiving about the input it tries to merge in order to try to complete the merge is debatable.

**Comment by krader1961** [comment]
Also, I've noticed that `history --merge` will also sometimes exit with a status of one yet still merge new entries from other sessions. Something else to be looked into.

**Comment by floam** [comment]
```
~ $ history --merge

No matches for wildcard '-*'.
/usr/local/Cellar/fish/HEAD/share/fish/functions/history.fish (line 34): 	case -* --*
                                                                         			     ^
in function 'history'
	called on standard input
	with parameter list '--merge'
```

**Comment by floam** [comment]
#2734, I think, addresses the status 1 thing.

**Comment by ridiculousfish** [comment]
#2734 and related addresses this. Thanks for filing it!

**Comment by ElijahLynn** [comment]
Just got the latest nightly from Launchpad and this works! W00t!
