### ISSUE TITLE
Any easy way to disable the newish tab complete folder search?

### ISSUE THREAD

**Issue by lunixbochs** [fish-shell/fish-shell#2677]
I've triggered it accidentally at least 5-10 times a day for the past 6-12 months since upgrading to whatever Fish version added it or made it easier to trigger, but I never actually want it to trigger.

This thing:

    ~/p/unicorn cd samples/msvc/msvc_sample_arm/
    search: /           
    …vc/msvc_sample_arm/    …vc/msvc_sample_m68k/  …vc/msvc_sample_sparc/  …vc/msvc_shellcode/
    …vc/msvc_sample_arm64/  …vc/msvc_sample_mips/  …vc/msvc_sample_x86/

**Comment by floam** [comment]
@lunixbochs Sorry nobody responded to this, it fell through the cracks. 

I'd be curious to know how you are carrying on today. Do you still use fish? Do you still find that you are triggering this in a way that is surprising and/or irritating/?

**Comment by lunixbochs** [comment]
```
mkdir tmp; cd tmp
mkdir ea eb
cd e<tab><tab>
```

This will complete to `cd ea/`. At this point, I'm perfectly content to start typing the next path element, which was my previous workflow. However, thanks to tab completion searching, typing focus is stolen by the search. I'm not sure if this is the only place I trigger search, but I never want to trigger it.

**Comment by krader1961** [comment]
Pressing tab twice is, by design, intended to drop you into the pager to select from the available matches when there is more than one match. Selecting the first match simply requires pressing [enter]. What @lunixbochs is asking for is a configurable option to disable the pager.  It seems unlikely we're going to change this behavior by making it configurable. Nonetheless, this is a duplicate of issue #2249.

**Comment by floam** [comment]
One of the upsides of some features being "always there" is it probably increases the number of "UX" reports like this after folks stick with it, where they might have otherwise disabled the feature a long time ago and never showed us what was going wrong for them.

What might help you into/out of/around the feature quicker @lunixbochs? For example I'd be surprised if it isn't somewhat common for someone to hit `/` hoping it does the same thing as enter here. #2249 looks a good place to track that.
