### ISSUE TITLE
Add documentation for how to unset universal variables

### ISSUE THREAD

**Issue by danielcompton** [fish-shell/fish-shell#2681]
I was reading http://fishshell.com/docs/current/tutorial.html#tut_path and ran a 

```sh
~ $ set -U myvar "hi"
~ $ echo $myvar
hi
```

I wanted to unset that universal variable, but I couldn't find any docs for where it is stored, or how to remove it. Would it be possible to add these docs to http://fishshell.com/docs/current/tutorial.html#tut_universal?

---

Update: this used to be the shell script in my question, but it wasn't clear what I was asking. I've replaced it with a more neutral example.

```sh
~ $ set -U PATH ~/bin/ $PATH
set: Warning: universal scope selected, but a global variable 'PATH' exists.
```

**Comment by krader1961** [comment]
You've misunderstood the warning. It's telling you that PATH was defined with the equivalent of `set -g -x PATH`. Fish is telling you you're about to shadow that global definition with a universal definition which is probably not what you want. To make it universal, which I don't recommend, you have to do this:

```
set temp $PATH
set -e PATH
set -U -x PATH $temp
set -e temp
```

It's generally a bad idea to make exported variables also universal.

**Comment by danielcompton** [comment]
I understand the warning, but it brought up the question for me "Where are universal variables set?". I've updated the question to use a more generic example. Thanks!

**Comment by krader1961** [comment]
See the output of `man set` or `help set`. Specifically the __--erase__ option. If you enter `set -e myvar` it should be unset.

**Comment by danielcompton** [comment]
Thanks, that's really helpful. One thing I'm still curious about is where the variables are stored on disk? I can see `~/.config/fish/fishd.d0509925e983` and in the header it says:

```
# This file is automatically generated by the fish.
# Do NOT edit it directly, your changes will be overwritten.
```

Where is the original source for these values?

**Comment by krader1961** [comment]
Universal variables are stored in the fishd file you mentioned. The actual file, at this time, depends on a "machine ID" derived from the primary network interface of your computer.  This is something I'm lobbying to change but that's a different discussion.

The original source for those values (i.e., variables) is wherever you executed a `set -U var_name var_value` be it an interactive prompt or a fish function or script.

**Comment by danielcompton** [comment]
Sorry, I don't think I'm being very clear here. If `fishd.d0509925e983` is automatically generated by fish, and changes to it will be overwritten, what is the source for overwriting those changes?

**Comment by krader1961** [comment]
> ..., what is the source for overwriting those changes?

It is `set -U` commands. Every time you execute such a command fish will write the variable to a "fishd" file such as the one you've identified; creating the file if it doesn't already exist. The comment at the top of the file stating that it will be "overwritten" simply means that any changes you make with an editor (e.g., vim or emacs) will probably not last very long because updates to the file outside of `set -U` commands will not be recognized by fish shells. Which implies that any subsequent update to a universal variable via the fish __set__ command will erase the changes you made external to fish.

**Comment by krader1961** [comment]
Bottom line: Do not edit the fishd.* files. If you need to create, modify, or remove a universal variable do so from a fish shell using `set -U`.

**Comment by danielcompton** [comment]
Gotcha, so the fishd file is the source of truth. Thanks for your patience and help!

**Comment by dideler** [comment]
Hey @krader1961, in https://github.com/fish-shell/fish-shell/issues/2681#issuecomment-172379679 you mentioned
> It's generally a bad idea to make exported variables also universal.

What's the suggested way to have variables be always present in fish instances (universal) and also in child processes such as bash (exported).

For example, I have set `EDITOR` once as `set -Ux EDITOR foo`. I like this approach because I don't want to execute `set -x EDITOR foo` on every new shell instance. But this causes warnings like `universal scope selected, but a global variable 'EDITOR' exists` when I run tools like [fishtape](https://github.com/fisherman/fishtape/issues/new).

**Comment by krader1961** [comment]
> I don't want to execute set -x EDITOR foo on every new shell instance.

Why not? Since uvars have to be loaded by every shell instance there is no difference in run time cost between that approach and putting `set -x EDITOR foo` in your *config.fish*. And, as you've found, making it a uvar can cause unexpected problems with fish script that expects it to have global scope.

**Comment by dideler** [comment]
> Why not?

To avoid as many writes as possible during startup. But maybe my mental model is wrong. If there is indeed no difference in runtime then I'll definitely switch to using `set -x` in `config.fish`.

**Comment by dideler** [comment]
😅 I figured it would write to the fishd file or elsewhere, though I'm not sure why I thought that, as storing it in memory would be sufficient. I now realise that the `SET_EXPORT`s in the fishd file is only for universal variables.

Thanks for the help! I've split my `Ux` variables into either [universal](https://github.com/dideler/dotfiles/commit/8f931aa6b4061f14de1d6d399eca0c5e4fb3fc49) or [export](https://github.com/dideler/dotfiles/commit/b7f71eec2c7b500b49247e0627c4e90c7d2c0d7f).

**Comment by intiocean** [comment]
I found this when trying to remove an entry from `fish_user_paths` and this is what I did which might help someone else to find the answer their looking for more quickly.

First just echo the paths to find the index of the one you want to remove (indexes in fish start at 1)
```
> echo $fish_user_paths
/usr/local/opt/icu4c/sbin /usr/local/opt/icu4c/bin /usr/local/opt/postgresql@9.4/bin /usr/local/Cellar/gettext/0.19.8.1/bin/ /usr/local/opt/postgresql@9.4/bin /usr/local/Cellar/node/7.5.0/bin /Users/inti/miniconda/bin /usr/local/Cellar/readline/6.3.8/lib/ /Users/inti/.yarn/bin
```
Then check you counted correctly
```
> echo $fish_user_paths[6]
/usr/local/Cellar/node/7.5.0/bin
```
Then unset it - this will create a local `fish_user_paths` variable the the 6th entry removed
```
> set -e fish_user_paths[6]
```
Check the entry I wanted to remove has gone. It has good!
```
> echo $fish_user_paths
/usr/local/opt/icu4c/sbin /usr/local/opt/icu4c/bin /usr/local/opt/postgresql@9.4/bin /usr/local/Cellar/gettext/0.19.8.1/bin/ /usr/local/opt/postgresql@9.4/bin /Users/inti/miniconda/bin /usr/local/Cellar/readline/6.3.8/lib/ /Users/inti/.yarn/bin
```
Overwrite the universal `fish_user_paths` with my edited local one.
```
> set -U fish_user_paths $fish_user_paths
set: Warning: universal scope selected, but a global variable 'fish_user_paths' exists.
```
