### ISSUE TITLE
Change key binding of 'accept auto-completion'

### ISSUE THREAD

**Issue by boazrymland** [fish-shell/fish-shell#2689]
How do I change the keybinding of 'accept auto completed word' and 'accept auto completion to end of suggestion' ?

Using Alt+RightArrow and RightArrow (respectively) is too slow as the arrows are soooo far right on the keyboard. I'd rather have some key combination that wont force me to do a formidable lifting and moving of my right hand to the right side... :-) . 
I do prefer leaving the Emacs style binding on and change only auto-completion bindings (I think the auto completion bindings share same binding with other functionality, when no auto-completion is relevant. Please correct me if I'm wrong...).

Other than that - gotta say - I love your shell. Finally! A shell for the new millennium! ;-)
Thanks!

**Comment by faho** [comment]
There's nothing special about the bindings for `right` (as we call it) - `bind -k right`:

>bind -k right forward-char

It just moves forward, and if it hits the suggestions (completions are something different - the greyed out stuff you see _on the commandline_ is a suggestion, what you get when you press tab is a completion) it'll accept it.

Incidentally, by default this same function is also bound to \\cf (in emacs terms that'd be C-f).

**Comment by boazrymland** [comment]
Great. Thanks for the swift response. 
Indeed I'm interested in customizing the suggestions. Re-examining the binding I noticed that Ctrl-F accept the entire line and Alt-F accept single "words". That's almost perfect - no need to turn on a journey to the other side of the keyboard looking for that arrow keys. 
But, I would have changed it to be Ctrl-F accept one word forward and Alt-F accepts whole line. Why? Since Ctrl-F was typically the jump one word forward binding for many years (Emacs style), so this just adds up intuitively the 'accept whole line' with the Alt-F combination. 
If you really want to make my day I'll humbly accept your quick recipe to alter those key bindings but if not - I'll use the force and RTFM to get an answer :-)

Thanks again! :-)

**Comment by faho** [comment]
> If you really want to make my day I'll humbly accept your quick recipe to alter those key bindings but if not - I'll use the force and RTFM to get an answer :-)

The general idea is to use [bind](http://fishshell.com/docs/current/commands.html#bind). Calling just `bind` will list all your bindings, calling `bind \cf` will list the binding for \\cf (Ctrl-F) and `bind \ef` for Alt-F. That will get you the functions you want rebound. `bind KEY FUNCTION` will bind KEY to FUNCTION.

Then put all of this together in a function called `fish_user_key_bindings` and insert the appropriate bindings, i.e.:

```fish
function fish_user_key_bindings
    bind \cf forward-word
    bind \ef forward-char
end
```

(There's a few keys we name - like "right" - see `bind -K` and use `bind -k KEYNAME` to use the named version. Unfortunately Alt-Rightarrow isn't among them since named keys can't be combined with a modifier)

**Comment by boazrymland** [comment]
Great, thanks! :-)  :+1:
