### ISSUE TITLE
syntastic error when using vi

### ISSUE THREAD

**Issue by fibo** [fish-shell/fish-shell#2701]
Hi all,

I started using fish shell yesterday. I wrote an article about it, as you can [read in the Cons section](http://g14n.info/2016/01/welcome-to-fish-shell/#cons)

when I launch vi, I got an error message from syntastic

```
syntastic: error: your shell /usr/local/bin/fish can't handle traditional UNIX syntax for redirections
```

while if I use vim I get no warning. Maybe I am missing something? Do you suggest I create a function to alias vi with vim?

**Comment by faho** [comment]
I'm assuming your `vi` isn't actually vi but another vim. Is that correct?

What you need to do is `set shell=/bin/bash` before syntastic tries to execute shell scripts, and it seems that happens when launched as vim but not as vi.

There's [a bit in the syntastic docs](https://github.com/scrooloose/syntastic/blob/master/doc/syntastic.txt#L885-L893), which also tell you that you could also set a special syntastic variable, but since more vim-plugins exhibit this issue, you are probably better off setting the general variable. (Also we do support "traditional UNIX syntax for redirections" - that claim's at least outdated)

**Comment by pickfire** [comment]
@fibo, `vim` and `neovim` have this issue, just `set shell=/bin/bash`.

https://github.com/junegunn/vim-plug/wiki/faq#errors-on-fish-shell have some documentation for this too, I have saw some troubleshooting for this everywhere, I just hope that we could use fish's wiki for this.

**Comment by fibo** [comment]
Actually my vi is the OSX default (/usr/bin/vim) which is version 7.3, while my vim is installed by brew and located ad /usr/local/bin/vim and has version 7.4: by the way I added to my .vimrc the line

```
let g:syntastic_shell = "/bin/sh"
```

and now also with vi (version 7.3) works. Btw I opened an issue to update syntastic doc: https://github.com/scrooloose/syntastic/issues/1681

**Comment by pickfire** [comment]
@fibo I suggest to use:

```vimscript
set shell=/bin/sh
```

Well, other plugins could be broken too.

**Comment by fibo** [comment]
do you mean to add it in the config.fish?

**Comment by faho** [comment]
No, in vimrc - fish syntax wouldn't have the "=". This is the general variable for a shell, while syntastic_shell is just for syntastic, but will by default use the value of shell, so just setting shell should work for syntastic and everything else.

**Comment by fibo** [comment]
Yes I got it, something like this https://github.com/fibo/home/blob/home/.vimrc#L11

it should be added before loading plugins I guess.

It works, I updated my article linked above, and yes: this tip should be suggested to all fish shell newbies like me.
