### ISSUE TITLE
Is it possible to print to standard error  in config.fish?

### ISSUE THREAD

**Issue by da99** [fish-shell/fish-shell#2702]
The last one is the only one that gets printed to the console in `config.fish`:

     echo "started 1" >&2
     echo "started 2" 1>&2
     echo "started 3"           # this one gets printed

Is this normal?

**Comment by oranja** [comment]
This is the current design, yes ([source]).
Personally I prefer to see errors if they exist, but I assume they are redirected in this case to avoid a clutter of warnings and errors on Fish initializations.

[source]: https://github.com/fish-shell/fish-shell/blob/master/src/fish.cpp#L227

**Comment by ridiculousfish** [comment]
When fish sources config.fish, it redirects stderr to /dev/null. It's been this way since literally the very first commit in 2005. My guess is that it's to handle the case where the file doesn't exist.

**Comment by oranja** [comment]
> My guess is that it's to handle the case where the file doesn't exist.

I think most can agree that it's a poor choice to leave it like this if that is true and it's still the only reason.
Others might disagree and suggest that people who make changes to **config.fish** should run their tests before adding to the config. I'd counter, ahead of time, by arguing that sometimes things break after a while from changes that seem unrelated.

**Comment by krader1961** [comment]
That behavior is so wrong I am amazed no one has changed it. If a command in my _config.fish_ doesn't exist or writes to stderr I want to know it. I don't want the error message to be silently discarded. If scripts that are part of the fish distribution which might be invoked from _config.fish_ (e.g., `fish_vi_mode`) write messages to stderr that should be ignored then the offending commands in those scripts should redirect stderr. But to blindly discard all stderr text is a really bad idea. The only possible exception might be for non-interactive invocations but even that is probably a bad idea.

It's trivial to test whether _config.fish_ exists and is readable and skip sourcing it if it is not.

**Comment by faho** [comment]
I have to agree with @krader1961. Errors from config.fish should _not_ be ignored - there shouldn't be a message if it doesn't exist (fish is still usable without it), but if there's anything wrong I'd want to be notified.

Hence, I'm reopening this.

**Comment by krader1961** [comment]
BTW, I've already written a patch that fixes this. I haven't created a pull-request yet because I'm trying to figure out if sourcing _/usr/local/share/fish/config.fish_ and _/usr/local/etc/fish/config.fish_ during unit tests is correct (that's in addition to the test specific _config.fish_ that is sourced last). It seems to me it is not correct as the unit tests are supposed to be hermetic; i.e., not influenced by the locally installed fish.

**Comment by krader1961** [comment]
Making the unit tests more hermetic is possible. The change is pretty straightforward thanks to fish's "relocatable" feature that causes it to look for its support files beneath the parent directory where the fish binary is located. But it does require a lot of individual changes due to all the `../fish` references in the tests. It's also not necessary for the core change that fixes this issue. So I'm going to open a separate issue for fixing the non-hermetic aspect of the tests.

**Comment by krader1961** [comment]
My fix for this exposed a mistake in my config.fish which contained this statement:

```
test $SSH_AUTH_SOCK = '' -a -f ~/.ssh/auth_sock
```

Note the lack of quotes around the variable. Since the var wasn't set in the login shell it was resulting in the error `test: Unexpected argument type at index 0`. And that error was being swallowed by the stderr redirection. Yay!

**Comment by krader1961** [comment]
This can be closed. My PR #2708 fixes this issue.

**Comment by zanchey** [comment]
Grand!
