### ISSUE TITLE
Fuzzy tab completion is not consistent with direct tab completion regarding case-insensitivity

### ISSUE THREAD

**Issue by jturcotte** [fish-shell/fish-shell#2710]
For example completing on OS X:
- `~/Library/application\ sup<tab>` will result in: `~/Library/Application\ Support/`

The same way I would expect that a lowercase fuzzy search string would also complete to ~/Library/Application\ Support/:
- `~/Library/appsup<tab>` won't complete at all.

I absolutely need to enter a case-matching search string for this to work, e.g.:
- `~/Library/AppSup<tab>` correctly results in: `~/Library/Application\ Support/`

fish, version 2.2.0
Slightly related: #2672
Not directly related: fish-shell is awesome :grin:

**Comment by ridiculousfish** [comment]
Thanks :>

We deliberately don't do fuzzy case-insensitive matching, because you can get into a situation where anything matches almost anything. In particular users often use tab-completion as a sort of "check" or exploration (where is this file...) so sometimes no match is better than a very very weak match. Still It may be worth relaxing this if it's "not too fuzzy."

**Comment by jturcotte** [comment]
OK, I can see how this could make things worse.
Since this isn't intended to be fixed, I guess it's better to close the issue. Thanks
