### ISSUE TITLE
Execution of the shell scripts w/o shebang

### ISSUE THREAD

**Issue by ycny** [fish-shell/fish-shell#2723]
Hi,

I've noticed this behavior of fish. Let's assume we have shell script (abc.sh) defined like that:

    echo "abc"

Only one line, w/o shebang (#!). Now when we run it (command and oputput):

    fish-shell ~> ./abc.sh 
    -----------------------
    Failed to execute process './abc.sh'. Reason:
    exec: Exec format error
    The file './abc.sh' is marked as an executable but could not be run by the operating system.

which in my opinion is ok and all shells should behave like that. The problem is when you do:

    fish-shell ~> fish ./abc.sh 
    ----------------------------
    abc

IMO, there is completely no logic in this behavior - don't mix things. There is only two options fish should behave like:

1) Don't run .sh files without shebang at any circumstances 
2) Do run .sh files without shebang at any circumstances

Bash did choose the second option:

    bash-shell ~> ./abc.sh
    -------------------
    abc

    bash-shell ~> bash ./abc.sh
    -------------------------
    abc

**Comment by krader1961** [comment]
You've misunderstood how things work in UNIX like operating systems. File name extensions have no relevance with respect to executing a file. If you create a file named *my_script.arglebargle* with shell commands there is absolutely no reason why you shouldn't be able to type `fish ./my_script.arglebargle`. Similarly if the first line of the file is `#!/usr/bin/env fish` and mark the file executable you'll be able to simply type `./my_script.arglebargle`. There is nothing that requires the extension to be *fish* in either instance.

When extensions are meaningful it is only a convention. For example, fish autoloaded functions being put in files named *function_name*.fish is just a convention of the fish shell. That convention could just as easily been to use a *.autoload* extension.

There is nothing wrong with the behavior you're seeing and it isn't going to be changed.

**Comment by ycny** [comment]
Sorry, but it looks like you didn't even noticed what is this issue about. I'm talking only about shell scripts without shebang. Of course I'm aware that we are talking here about convention. But it looks like fish didn't follow it in logical way.
Bash, zsh and sh will run abc.sh (w/o #!) script always, No matter how it was invoked. They are following a convention here, when kernel is returning ENOEXEC, these shells treat this as a shell script. You can say it is not safe, but you can't say there is no convention here.
What fish is doing is when he gets ENOEXEC in current shell, it is NOT trying to assume that this is shell script. But when exactly the same script is run in the fish subshell (fish ./abc.sh), fish changes his mind and run it. This is simply not ok.

**Comment by krader1961** [comment]
> Sorry, but it looks like you didn't even noticed what is this issue about.  I'm talking only about shell scripts without shebang.

I did notice. Try this:

```
$ echo echo Wow > abc.fish
$ echo ps -fp $$ >> abc.fish
$ echo set myvar val1 val2 >> abc.fish
$ echo set >> abc.fish
$ chmod 755 abc.fish
$ /bin/sh ./abc.fish
$ /bin/zsh ./abc.fish
$ /bin/sh
$ ./abc.fish
$ exit
```

Notice that /bin/sh still ran the script. It completely ignored the file name extension. What you're observing is historical behavior that says an executable file without the shebang line (or other magic signature recognized by the kernel) should be fed to /bin/sh. The reasons for doing so date back at least thirty years and are no longer relevant. Fish doesn't do that because it's a really stupid legacy feature.

**Comment by krader1961** [comment]
I forgot to include the final experiment in my previous comment:

```
$ /bin/zsh
$ ./abc.fish
$ exit
```

Notice that zsh also passes the script to /bin/sh when you do that but not when you run it as `zsh ./abc.fish`.

**Comment by ycny** [comment]
> but not when you run it as zsh ./abc.fish
Really? 

    zsh% cat abc.fish 
    echo "abc123"
    zsh% ./abc.fish 
    abc123
    zsh% zsh ./abc.fish 
    abc123
    zsh%

I'm not even trying to guess, why are you constantly talking about file names extension. I don't care about them right now and this issue is not related to them as well. Really, it's hard to get your point. 
Maybe we can try one more time. Please refer to this file: http://lxr.free-electrons.com/source/fs/binfmt_script.c line 26. Fish, in one case (./abc.sh) is returning the same as load_script function, but when invoked like (fish ./abc.sh) it ignores ENOEXEC and run script. This is completely not related to file extension...

**Comment by ridiculousfish** [comment]
Oh god, bash really does just try to execute the thing as a shell script on ENOEXEC. That's horrifying.

**Comment by ridiculousfish** [comment]
@ycny I think I understand what you're saying. Two questions:

1. What do you think should happen if the shebang is not for fish? `fish abc.sh` where abc.sh begins with `#!/bin/bash`? 
2. `fish abc.sh` is morally equivalent to `fish < abc.sh`. Do you think these should be different - require a shebang in the first case, but not with the redirection?

**Comment by krader1961** [comment]
You didn't run the commands as I gave them to you. When you're in an interactive zsh don't type `zsh ./abc.fish` just type `./abc.fish`. You're also not running the script I gave you since you didn't show the ps output. The ps command embedded in the script should show that it is being executed by /bin/sh. Also, when you type `fish ./abc.fish` the fish shell is not running an external command, thus no exec(2) syscall to fail with ENOEXEC. It is instead opening and reading the contents of the file. As @ridiculousfish points out it is roughly equivalent to `fish < abc.fish`.

The reason I keep talking about file name extensions is that you seem to think a *.sh* extension has some bearing on this issue. It does not. It doesn't matter if you use a *.sh*, *.fish*, *.arglebargle* or no extension. You'll get the same behavior from sh, zsh, and fish.

I'm also at a loss as to why you provided a link to Linux kernel source code. All that we need to know is the exec API: `man 2 execve` or `man 3 execve`.

Suggestion: You'll get a better response if you ask "Why does it behave this way?" as opposed to stating "The behavior is broken."

@ridiculousfish: There is nothing wrong with fish's behavior. The fact that bash and zsh pass the file to /bin/sh if the exec(2) call fails with ENOEXEC is for compatibility with the very first Bourne shell 30+ years ago. It made sense at the time (primarily because there was just a single shell). It's now a dangerous feature. Please, I beg you, do not implement that "feature".

**Comment by krader1961** [comment]
Let's see if we can wrap this up: No modern shell should implement the thirty year old feature of the original Bourne shell that would cause it to run the script via `/bin/sh script_name` if it doesn't contain a shebang line. The fact that bash and zsh implement this dangerous legacy feature is not a reason for fish to do so. Every single script should begin with an appropriate shebang line.

**Comment by ridiculousfish** [comment]
@krader1961 Yep! We're all agreed here that bash is insane, ycny included. The kernel says "Nope, can't execute that" and bash says "Oh, it's gon happen." Frankly I can't stop laughing at that.

Per my reading, what ycny is proposing is that in the `fish some_file` case, fish also refuses to read from the file unless it has a shebang.  I'd like to better understand what ycny is thinking here - worst case someone has their thinking clarified.

@ycny don't miss [my two questions](https://github.com/fish-shell/fish-shell/issues/2723#issuecomment-182590037), thanks!

**Comment by krader1961** [comment]
> Per my reading, what ycny is proposing is that in the fish some_file case, fish also refuses to read from the file unless it has a shebang.

Possibly, but that seems to be because he doesn't actually understand what sh, bash, and zsh are doing, and why they're doing it, when there isn't a shebang line. I would be opposed to having `fish script_file` require a shebang line. How would you validate it? What if the line is `#!/bin/fish` but you're now running */usr/local/bin/fish*? What if you've set up a symlink from *$HOME/bin/myfish* that points to */usr/local/bin/fish* and the shebang is `#!/usr/bin/env myfish` (assuming *$HOME/bin* is in **$PATH**)?

**Comment by bucaran** [comment]
I can't stop looking at the label of this issue. And the selected color, also, seems so adequate.

**Comment by ycny** [comment]
@ridiculousfish 

> what ycny is proposing is that in the fish some_file case, fish also refuses to read from the file unless it has a shebang

No. What I'm proposing is in the first message: 

> 1) Don't run .sh files without shebang at any circumstances 
> 2) Do run .sh files without shebang at any circumstances

I know what is the difference between running `./script` and `bash ./script`, but just wanted to notice, that even if fish is behaving theoretically ok when calling script w/o `#!` directly, you still can't stop the user from simply doing `fish ./script`. If so, what's the point of blocking the execution of script w/o shebang? You already running this from fish shell... I know, it is odd and different, but IMO there is still some logic here. Would you go now and fix a python to blocking its scripts from executing if there is no `#!/usr/bin/env python`?

> What do you think should happen if the shebang is not for fish? fish abc.sh where abc.sh begins with #!/bin/bash?

Just ignore the shebang then. AFAIK fish is not much compatible with bash;)

> fish abc.sh is morally equivalent to fish < abc.sh. Do you think these should be different - require a shebang in the first case, but not with the redirection? 

It can't require shebang in this situation. That is the point of this issue. And since it can't require, it also shouldn't when running script directly.

I don't think that there is point of making this discussion longer. So I'm glad that you learn a new thing about disgusting bash today. Hope it makes fish better:)

**Comment by ridiculousfish** [comment]
Ok, thanks for pointing this out! Closing.

**Comment by krader1961** [comment]
> you still can't stop the user from simply doing fish ./script

Correct. You also can't stop them from simply doing `bash ./script` or `python ./script` or `awk ./script` regardless of the contents of *./script*.

> If so, what's the point of blocking the execution of script w/o shebang?

The non-fish shells are not executing the script when you type `./script` and it doesn't have a shebang line. They're assuming you meant to include a `#!/bin/sh` line at the top of the file and execute `/bin/sh ./script` (yes, zsh and bash do that). This was a feature that was necessary long, long, ago when the UNIX kernel did not recognize shebang lines.

**Comment by bucaran** [comment]
> The non-fish shells are not executing the script when you type ./script and it doesn't have a shebang line.

I see! I had totally not realized this until now.
