### ISSUE TITLE
Job command is truncated and unreadable sometimes. 

### ISSUE THREAD

**Issue by lisimia** [fish-shell/fish-shell#2727]
Issue  #1119
and 
https://github.com/fish-shell/fish-shell/commit/6db82c162caa06f3f47ae248da7c4e354d4d28a1#diff-2496498d8489caaa1554877d00271179R654

forced a maximum length on my jobs. 

i run about 10~20 jobs regularly, all over 200 characters long, the first 30 characters, and last 30 characters are always the same

its a bit weird i know. 

but i would like to add an environment flag that truncate_command checks for in which if set, will NOT truncate the command. 

I view this as a regression because it broke existing behaviour, with no way to go back. I'm willing to put in the code if someone can point me in the right direction

**Comment by faho** [comment]
>I'm willing to put in the code if someone can point me in the right direction

The code seems visible in that diff - "truncate_command" in proc.cpp.

Though I'd like it if it wouldn't use an additional environment variable. I'd prefer if it filled $COLUMNS, if there has to be any truncation. @ridiculousfish: Remember why you added the truncation?

**Comment by ridiculousfish** [comment]
I added the truncation because status message could be unreasonably long, especially the "has ended" or "terminated by signal" messages.

@lisimia what is the context where you want to see longer messages? Is it for these signal status messages?

**Comment by lisimia** [comment]
`Job 3, “python Tasks/my_magical_script.py arg1 ar.…” has ended`

is what is see when i run a job in the background and it finshes
with 

`python Tasks/my_magical_script.py arg1 arg2 arg3 arg4 some_unique_hash_that_i_typed_in >> /dev/null ^^&1 &`

i want to the full command of what job finished.

maybe we can provide a custom implementation to `truncate_command` within in fish syntax? like how we can define the function for `fish_prompt`

**Comment by ridiculousfish** [comment]
Thanks for answering my question. What do you do with that information? Do you cross-reference that hash with something else? Or do you want to, say, copy and paste the whole command to run it again?

What I'm trying to ascertain is whether there's some smarter truncation or labelling or other behavior that would make this better for everyone, and wouldn't involve introducing new configuration. I suspect you don't actually want to see the whole command, but rather uniquely identifying part of it? But I could be wrong.

Maybe when multiple jobs have the same prefix, the truncation could start at the point that's different.

**Comment by lisimia** [comment]
yes that's the issue, i have up to 20 jobs that have the same starting prefix,
when a job finishes, i would like the see exact which one finished

---

one problem i predict in your proposed solution, the last running command (of the 20), would appear like it is the only command thus only print the prefix and not the important part of the command (some arbitrary part in the middle)   

---
printing the ending won't work either because in this case it'll only print ` ' /dev/null ^^&1 &' has finished`

**Comment by oranja** [comment]
@ridiculousfish 
I get the feeling that different users will have different reasons and requirements here.
`bash` doesn't do any truncating, and as much as no one here wants `bash` to be the role model, I think that this is the only possible solution that satisfies everyone without configuration.

To overcome the original problem,
> The command could be so long that the status change itself would be lost.

I'd suggest to separate the status from the command.
`bash` does it with a long space (tab?). In `fish` I'd prefer a newline between the status and the command, since the status description is longer and more informative in `fish`.

**Comment by ridiculousfish** [comment]
bash puts the status before the command - that's kind of clever in fact.

**Comment by lisimia** [comment]
it would sound like just a rewritten format string in: https://github.com/fish-shell/fish-shell/commit/6db82c162caa06f3f47ae248da7c4e354d4d28a1#diff-2496498d8489caaa1554877d00271179R694   and to not use the `truncate_command` function
should be enough? should I get started?

**Comment by ridiculousfish** [comment]
Sure, go for it.

**Comment by soumya92** [comment]
With #6959, this is customizable at the user level, without needing to change code in fish-shell.

For the specific use-case mentioned in this bug, you can choose exactly how to truncate the command (so, e.g. skip the first 20 characters, or truncate from the end rather than the beginning, or even grep for your hash...), by copying and then altering the fish_job_summary function to your local configuration.
