### ISSUE TITLE
Typing "~?" in the terminal displays a Wide character error

### ISSUE THREAD

**Issue by borisjoffe** [fish-shell/fish-shell#2732]
#### Repro steps
Type `~?` in the terminal (I'm using fish 2.2.0)

#### Expected result
`~?` appears in the terminal

#### Actual result
```
~ $ ~?fish: Wide character 62464 has no narrow representation
fish: Wide character 62464 has no narrow representation                       ~?fish: Wide character 62464 has no narrow representation
fish: Wide character 62464 has no narrow representation
fish: Wide character 62464 has no narrow representation

```

**Comment by bucaran** [comment]
Not on OS X, but I can reproduce in Ubuntu.

**Comment by krader1961** [comment]
I can't reproduce by typing a literal tilde followed by a question mark on either OS X or Ubuntu. Are you actually typing those two ASCII characters or something else? Perhaps your terminal emulator is converting that sequence to non-ASCII, Unicode, codepoints.

Note that code point 62464 is is 0xF400 which is reserved by fish:

```
wildcard.h:#define WILDCARD_RESERVED 0xf400
```

 One of the things I'm working on is making it impossible to feed Unicode private-use characters reserved by fish into the fish parser to avoid these types of problems. See issue #2684 and pull-request #2713.

**Comment by bucaran** [comment]
![fish-2](https://cloud.githubusercontent.com/assets/8317250/13067144/8988e686-d4b0-11e5-952d-892344045e98.gif)

**Comment by bucaran** [comment]
![fish-2](https://cloud.githubusercontent.com/assets/8317250/13067164/a62e3372-d4b0-11e5-959e-191b9cc87358.gif)

**Comment by krader1961** [comment]
@bucaran: What you're seeing from your linux environment is the `ssh` command you used to login to that system interpreting the tilde. Do a `man ssh` and scroll down to the section titled "ESCAPE CHARACTERS". That's not the problem @borisjoffe reported.

**Comment by bucaran** [comment]
@krader1961 Indeed, you are right. Sorry, for adding noise!

**Comment by pickfire** [comment]
I tried it in Linux with fish git HEAD, can't reproduce it.

**Comment by faho** [comment]
@borisjoffe: What's your `locale` and your OS?

**Comment by borisjoffe** [comment]
I'm using the rxvt-unicode terminal on 32-bit Arch Linux.

Adding `setenv LANG en_US.UTF-8` to `~/.config/fish/config.fish` actually fixed the issue and I can type `~?` now.

It's interesting that `/etc/locale.conf` and `~/.config/locale.conf` both had the `LANG` variable set to `en_US.UTF-8` and running `localectl status` showed that as well. But running `locale` showed that everything was set to POSIX. I guess fish looks at the environmental variables or the locale command instead of the locale.conf files and systemd localectl.

However, with the LANG env variable set, running fish in tmux displays an extra newline after the prompt (even when removing my custom prompt function). This newline appears somewhat randomly (sometimes two newlines appear) and eventually goes away after about the 11th prompt. This behavior only happens in tmux but is more annoying than the `~?` error. I could file a separate issue for it if you want.

**Comment by krader1961** [comment]
Aha! The tilde is introducing a wildcard which fish encodes as the private-use char 0xF400. When fish tries to expand the sequence (e.g., `~krader` => `/Users/krader` on my system) it can't serialize the non-ASCII char because LANG=C. The reality is that a lot of fish features won't work if the locale is not UTF-8 aware. FYI, you can avoid that specific failure mode by quoting the `~?`; which you should really be doing anyway since it's clearly not a valid tilde sequence.

As for fish not reading */etc/locale.conf* see https://github.com/fish-shell/fish-shell/pull/2381 for a spirited discussion. In general I don't believe the core fish code should be reading distro specific config files. Doing so is something the distro maintainers should be doing as part of customizing fish for the distro.

As for your extra newline after the prompt problem I can't reproduce that; and I use tmux extensively with fish. Nor do I recall anyone else reporting anything even vaguely like that. The fact it "eventually goes away" is particularly perplexing. My best guess is some command is running, possibly in the background, that is emitting an uncaptured newline as part of generating the prompt. Eventually something in the environment changes (such as the PWD changing) that stops that from occurring.

**Comment by borisjoffe** [comment]
I was actually typing `~?` accidentally instead of `~/` when I discovered this issue.

I agree about locale.conf - I just didn't have LANG set anywhere on my computer.

I'll look into the tmux newline thing a bit more before filing an issue - I think I ran across it before several months ago after restarting my computer.
