### ISSUE TITLE
Documentation website shows content too big. Making it unreadable on iPhone.

### ISSUE THREAD

**Issue by paidhi** [fish-shell/fish-shell#2739]
I am using an iPhone 6S & iOS 9.
The Fish documentation site (http://fishshell.com/docs/current/index.html) renders it's content hugely zoomed in when opened on the iPhone (Safari or iCab browser). The zoom gestures to reduce the site content also don't work.
The main site URL http://fishshell.com shows OK.

**Comment by ridiculousfish** [comment]
Wow, that's really bad. I had it working nicely at one point - not sure what happened. Nice find.

**Comment by krader1961** [comment]
FWIW, Opening that URL on my Moto X running Android OS 5.1 results in a reasonable view of the page. It is obviously not optimized for a mobile experience but neither is it "hugely zoomed in" and I have no difficulty changing the zoom level. Making the fish documentation viewable on as broad a range of devices as possible is a good idea but seems like a "stretch goal" rather than an essential feature. If this problem is easy to fix we should do so. But if it is going to take a lot of resources then I would argue our time is better spent elsewhere.

**Comment by pickfire** [comment]
@ridiculousfish It seems like the fish-site isn't optimized for mobile, I am learning how to create mobile friendly site by the way, want some help to make it mobile-friendly?

**Comment by bucaran** [comment]
@pickfire Maintaining a website is a lot of grunt work. I would rather focus on improving the existing wiki by making it more attractive to beginners which is something everyone could easily contribute to without the hassles of web engineering.

Nice Wikis:
* https://github.com/guard/guard/wiki
* https://github.com/mbostock/d3/wiki

Also, the Fisherman wiki, I put an awful amount of work on making it:
* https://github.com/fisherman/fisherman/wiki

**Comment by pickfire** [comment]
@bucaran Fish's wiki is nicely documentated except the github wiki page.

**Comment by ridiculousfish** [comment]
I definitely reproduced this once, but I just tried this with iOS 9.3.1 and it looks fine. Does anyone still see this?

**Comment by floam** [comment]
It's still problematic once you do zoom in and try to pan around the page if the touch event is int he side bar. I will improve this for mobile.

**Comment by faho** [comment]
This seems alright for me, and nobody has complained in two years. Closing!
