### ISSUE TITLE
cd slower since last few commits.

### ISSUE THREAD

**Issue by onodera-punpun** [fish-shell/fish-shell#2742]
I don't know if this is placebo, but I'm *pretty* sure cd is a lot slower.

For example when I cd to a location, the prompt disappears for about 0.3 seconds, even when cd-ing from ~ to ~ for example.

**Comment by onodera-punpun** [comment]
Hmm, I just installed fish 2.2.0 and it's does the exact same thing (hiding the prompt for a split second), I probably never noticed it before.

**Comment by faho** [comment]
@onodera-punpun: Even if it's not a regression, this kind of slowness should be fixed.

What is your configuration like? Is `builtin cd` faster (we have a wrapper function to provide history-cd, i.e. `cd -`)?

**Comment by onodera-punpun** [comment]
I don't use any functions that overwrite or modify cd if that's what you are asking, running `builtin cd` is exactly as fast (or as slow, lol).

This is my prompt, which might have some impact maybe:

```
function fish_prompt
	set_color fish_color_cwd
	echo (pwd | sed "s/\/home\/$USER/~/")" "
end
````

**Comment by faho** [comment]
Humm... the prompt looks okay - you could use `string replace -- $HOME "~" $PWD` instead of the pwd | sed thing, but it shouldn't change too much. Do you have any event handlers for the fish_postexec or fish_prompt events defined?

Or is your hardware just waaaay too slow, i.e. are you running this on a 486 with 66 MHz?

**Comment by onodera-punpun** [comment]
Hmm, so I just ssh'd into my raspberry, and surprisingly it's more responsive there even though the configuration is pretty much the same.

Pretty much the only difference is that I use a fish_title.fish on my pc, and indeed when disabling that function it's much more responsive again.

This is the function:

```
function fish_title
	echo "URxvt ["(history | head -n 1)"]"
end
```

Any way I could speed this up?

**Comment by faho** [comment]
You'll get a rather slight speedup by calling `builtin history` instead of `history` (there's a wrapper function that adds a few more functions). Using array slices (`echo (history)[1]`) is actually _slower_ than forking for head (`fish --profile FILE 'COMMAND'` is great for this kind of stuff).

Can you try without the function, just to confirm that it is causing the slowdown?

**Comment by onodera-punpun** [comment]
Yeah I tried it without the functions, and it's indeed causing the slowdown.

Since I pretty much created this slowness myself I'll be closing the issue, thanks!

**Comment by zanchey** [comment]
`$history[1]` might be faster still.

**Comment by krader1961** [comment]
FWIW, Since this issue was opened and closed the `history` command has been augmented to include a `--max` flag which obviates the need to do `| head -n` and will be noticeably faster.
