### ISSUE TITLE
Wrong prompt after executing ´su´

### ISSUE THREAD

**Issue by spilot** [fish-shell/fish-shell#2745]
When executing `su`, fish shows the wrong prompt afterwards (user prompt, no root prompt). 

Executing `su -` results in the correct prompt being displayed

![screenshot_wrong_su_prompt](https://cloud.githubusercontent.com/assets/12112224/13196232/d48d7d48-d7c8-11e5-9d74-6f179e1e9c2f.png)

**Comment by faho** [comment]
`type fish_prompt`?

My guess is your root shell doesn't access your users ~/.config/fish/functions.

You can either copy fish_prompt from the user to root, or add the users functions directory to $fish_function_path.

**Comment by faho** [comment]
That's because fish inherits the value for $USER in that case.

**Comment by spilot** [comment]
I think it shouldn't. At least bash doesn't and I don't find this behaviour intuitive.

**Comment by faho** [comment]
@spilot: Well, it will - $USER is exported (and some things don't like it when it's not so it should stay that way). What might work is checking if $USER is stale on startup, or something like that.

For now there's a number of workarounds you can use, from using `sudo fish` instead of `su` to setting $USER manually in your root config.fish.

**Comment by faho** [comment]
For the record: Bash suffers from the same problem, as does zsh.

**Comment by krader1961** [comment]
@spilot: Most `su` commands will explicitly set vars like $USER and $HOME appropriately. For example, from `man su` on a Ubuntu 14.04 server:

```
Note that the default behavior for the environment is the following:

     The $HOME, $SHELL, $USER, $LOGNAME, $PATH, and $IFS environment
     variables are reset.

     If --login is not used, the environment is copied, except for the
     variables above.
```

And I've confirmed that does in fact happen. However, on BSD based systems like OS X `su` behaves as described thusly:

```
     By default, the environment is unmodified with the exception of USER,
     HOME, and SHELL.  HOME and SHELL are set to the target login's default
     values.  USER is set to the target login, unless the target login has a
     user ID of 0, in which case it is unmodified.  The invoked shell is the
     one belonging to the target login.  This is the traditional behavior of
     su.
```

That appears to be the behavior you're seeing. This is fundamentally not the responsibility of the shell. If you want the "login" behavior that will set $USER appropriately on both BSD and GNU systems you should always use `su -` or `su -l`.

**Comment by exploide** [comment]
I agree that one should use `su -` or `su -l` and that it is the responsibility of this command to decide how the environment variables are set. But what is the purpose of the shell promt? Should it display the content of an environment variable or should it indicate whose session is currently active (and hence under which user the typed commands are executed)?

In my opinion it is the latter because it is more valuable for the user. It would conform to the output of `whoami` and who the owner of newly created files is. Additionally the shell promt is used as a warning sign because executing commands as root w/o noting it can cause damage (I guess that's the reason why fish's default color used in the root promt is red instead of green).

So maybe it is worth considering constructing the promt from the output of `whoami` instead of the `$USER` variable.
