### ISSUE TITLE
Add "only output Nth line" option to string.

### ISSUE THREAD

**Issue by onodera-punpun** [fish-shell/fish-shell#2756]
I'm trying to make most of my functions and scripts use string, but there is one option I miss very much. Here are a few example how this option would work:

Current: ```mpc -f '%file%' | string split '/' | head -n 2 | string join '/'```
Output: ```UA/2006 - cure jazz```
Without head and join (```mpc -f '%file%' | string split '/'```) output:
```
UA
2006 - cure jazz
01 - Born to be blue.flac
[playing] #4419
6498   3:14
6:08 (52%)
volume:100%   repeat: on    random: off   single: off   consume: off
```
With "line option" it could be: ```mpc -f '%file%' | string split -l [1..2] '/' | string join '/'```
Output would look like: ```UA/2006 - cure jazz```

==

Another example:

Current: ```ls -d media/videos/* | rev | cut -d / -f -1 | rev```
Outputs:
```
Autumn Tale
A Wife's Credentials
[ENG Subbed] Koukou Kyoushi 2003
```
What using string split (```ls -d ~/media/videos/* | string split '/'```) currently outputs:
```
home
onodera
media
videos
Autumn Tale

home
onodera
media
videos
A Wife's Credentials

home
onodera
media
videos
[ENG Subbed] Koukou Kyoushi 2003
```
With "line option" it could be: ```ls -d ~/media/videos/* | string split -l [-1]  '/'```

**Comment by floam** [comment]
This really doesn't make a lot of sense - just looking over your first example.. why give a tool that's supposed to be splitting stuff up an awkward option, just so it can do a bad job like head was doing there?

Why do you want to first split the whole thing up by '\'s first and cause it to give you a mess with the slashes in the other parts of the output getting in there to deal with? You should narrow down the output first. 

Isn't it nicer to just use another step in the pipeline, BEFORE it splits, there, and either have it stop after the first two lines of content then and there, before it murders the rest of the text and makes you clean up, or even better use string match to explain to it what that filename looks like and have it reliably match it to a pattern? Your initial example would break if, for example, you played a song that was ever three levels deep, since then you'd need to tell it to stop after 3 lines.

**Comment by floam** [comment]
Anyhow, string split does have a --max option and also an -r to make it go in reverse.

**Comment by onodera-punpun** [comment]
Oh I didn't really think about ```string replace -r ".*/" ''```

>I don't think this is really a bug with the string function, I think you will figure out a lot of solutions as you practice.

Well I more opened this a feature request, but yeah I guess you are right, I'll close this then.
