### ISSUE TITLE
Path autosuggestion abuse - high memory usage (potential crash)

### ISSUE THREAD

**Issue by bzaborow** [fish-shell/fish-shell#2771]
Path autocompletion is a very useful feature in general. But when it hits a single directory with milions of files it causes fish to consume huge amount of resources. And in such cases there is not much use of it. I suggest to limit the size of a completion list to something like 10k (preferably configurable).
### Reproduction Steps:
1. Create a directory TheDirectory and fill it with a few milion of files (e.g. using for + seq + touch)
2. Use autocompletion on this directory, that is: `cd TheDirectory<TAB>`
3. Observe your CPU and memory being eaten by fish 
### Expected behavior:

fish warns that the list of files is to large and doesn't show any suggestions or shows the first 10k suggestions and prompts that the list is incomplete.
### Observed behavior:

fish quite hangs (not entirely - it responds to ^C and backspace slowly) and eats resources. In my case about 6M of files resulted in 18GB of memory and 41 minutes of CPU usage. Even after ^C, when doing something else, it still computes those completions in background.
### Additional information:

---

Fish version: 2.2.0

Operating system: Ubuntu 15.10

Terminal or terminal emulator: screen opened inside rxvt-unicode

**Comment by faho** [comment]
First of all, I hope we are in agreement that having millions of files in one directory is a dumb idea. Directories exist for a reason, and they can be nested. Do that for every hundredthousand files or so just to get it nicely grouped.

I tried to test this, but it turns out I can't actually create that many files on my tmpfs. The most I've gotten is about 500000, which leads to fish taking about 300M of memory (that'd be 3,4G for 6 million files). Both standard file completion (i.e. `rm`) and cd completion take a few seconds but work. Even globs work (`echo *`). Even command substitutions work (`echo (printf '%s\n' *)`). That actually seems okay. 

So either 500k just isn't enough yet (though it's merely off by a factor of 12) or something's improved since 2.2.0.

The completion for `cd` was rewritten after 2.2.0, so you might want to try the new version.

**Comment by bzaborow** [comment]
Sure, having milions of files in a directory is not a normal thing. Some people do this for automated processing in cases when databases are too limited. In such cases one rather doesn't even use `ls`. I just wanted to point that autocompletion in this case may be unwanted, it's wasting resources and may cause crash when fish runs out of memory. And it doesn't really matter if it actually uses 300B or 3kB per entry when there is no hard cut - at some point it will start to annoy the user. I'll check the newer version tomorrow and update this post if it does better job.

**Comment by krader1961** [comment]
I do agree that fish should protect itself, and the user, by limiting the number of files it will deal with when performing path completion. I don't see any need to make the limit configurable. It should simply be high enough that any reasonable scenario doesn't truncate the list and unreasonable scenarios (e.g., a directory with millions of files) doesn't appear to wedge the shell. The devil is in the details. Obviously the limit should only apply to completions and not glob expansions. What should that limit be?  1K? 10K? 100K? If the limit is reached should the user be informed and if so how should that be done?

**Comment by faho** [comment]
I'm getting slightly different results when testing on an actual ext4 filesystem.

With about 2.8M files:

- `command ls | wc -l` starts using 700M
- `cd directory/<TAB>` and `rm directory/<TAB>` will take longer than I'm willing to wait and for `rm` the longer I wait the longer aborting will take - the biggest memory spike comes after aborting, with about 800M for 800000 options (which takes 5 minutes to collect, and 7 seconds to abort - that would suggest 38 minutes to get 6M options)

Throughout all this, my computer (an i7 with 4GB of RAM, ~~spinning rust~~ an HDD, not SSD) stays mostly responsive.

I have to again say: Overall, we're not doing _bad_ in my book in this (unreasonable) case. The biggest thing is this is abortable (and doesn't take too long to do so).

>Obviously the limit should only apply to completions and not glob expansions.

And what about completions that use globs? cd's do, and I'm not seeing any alternative since I don't want to invoke `find` or (shudder) `ls` from these rather important completions.

This is the general problem - for the file completions, which are in the C++ code, we could background it or freeze the job after a certain limit is reached, but for scripted completions, we can't. Or do we effectively send SIGSTOP to the running process? I'm not sure how many completions would weirdly fail with this.

For globs, the semantics are that everything gets expanded before the first argument is passed, so I don't see how any change is possible.

**Comment by krader1961** [comment]
Yeah, globs in completion scripts are a problem. I was originally thinking only about the file completion coded in C++. For scripts we would need a mechanism to limit how many entries a glob expands to. Using find doesn't really solve this because you'd have to resort to something like `find | head -$limit`. Ugh. Introducing new syntax just to support this can't be justified in my opinion. Given that we're not likely to be able to impose limits on scripted completions do we want to impose a limit on the file completions provided solely by C++ code which is likely to confuse people because of the inconsistent behavior? Probably not. If someone has a brilliant insight into how we can more gracefully handle this situation that would be great. Barring that I think people who do such things will just have to deal with the consequences of their decisions.

**Comment by ridiculousfish** [comment]
Good points @krader. I suggest the following principles, guided by the [law of responsiveness](http://fishshell.com/docs/current/design.html):

1. Things the user does not request explicitly (e.g. autosuggestions, syntax highlighting) should never cause memory blowup. Here it's reasonable to limit how many items a wildcard expands to.
2. Things the user does request explicitly may cause memory blowup. This includes explicit commands (`echo *`) and tab completions. However, these must always be cancellable via control-C.

This implies we need a flag to tell `expand_string` whether to enforce a limit or not.

**Comment by faho** [comment]
>Using find doesn't really solve this because you'd have to resort to something like find | head -$limit

Well, my thinking was that `for i in *; echo $i; end` (imagine something more complicated in place of echo) needs to expand the entire glob _before_ it can actually start generating output. This part of the semantics can't really change, otherwise

```fish
for i in *
    cp $i $i.bak
end
```

would be an infinite loop.

If you'd do `find | while read file; echo $file; end` instead, it could start generating output immediately, before find has ever finished. This could be terminated after a certain line-limit.

This is feasible, but quite ugly and annoying.

What I'd like more is if we'd just kill the completion after either a certain time (30s?) or memory consumption (100M?).

**Comment by faho** [comment]
@ridiculousfish: I don't think suggestions or highlighting are causing any issues here.

**Comment by ridiculousfish** [comment]
@faho It can in corner cases, e.g. `cd /tmp/foo/*/bar` will be highlighted if it expands to a valid directory there (though that's a weird thing to type). There's probably more realistic cases - also see #1893, which is basically the same thing except with brace expansion instead of wildcards.

**Comment by bzaborow** [comment]
I have an additional thought: the size of command line seems generally limited (on my systems /linux/ the limit is about 2M characters, I don't know about other *nixes), so commands like `cp * somewhere/` on milions of files will probably fail. But, in fish, this happens after computing the full list! So I think the point given by @ridiculousfish in (2) doesn't really make sense. I would also argue about the tab completion, it is not as explicit as pressing enter on what you see on the commandline, e.g. sometimes I hit <tab> to many times on laggy ssh sessions and I think I'm not the only one.

Message about limit on a much smaller directory (about 80k of files):

> Failed to execute process '/bin/cp'. Reason:
> The total size of the argument and environment lists 3.9MB exceeds the operating system limit of 3.9MB.
> Try running the command again with fewer arguments.

(the given limit is actually wrong - commands with different args counts show different numbers as a limit, but this is again the fish 2.2.0)

**Comment by faho** [comment]
We have now limited the number of globs - #7226
