### ISSUE TITLE
helping new users used to writing "if $status"

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2773]
Someone recently asked on [StackOverflow](http://stackoverflow.com/questions/35660206/variables-may-not-be-used-as-commands) what the fish equivalent is for a bash block of this form:

```
if $status; then
    echo success
else
     echo failure
fi
```

They were stymied by the unhelpful feedback they received for the `if $status`:

> fish: Variables may not be used as commands. Instead, define a function like “function status; 0 $argv; end”. See the help section for the function command by typing “help function”.

Nor did they find the documentation helpful.

I think we can do a few things to help new users with this specific issue:

- [x] The "Exit Status" section in the fish tutorial could include some verbiage about testing exit status the fish way; i.e., `if test $status -eq 0` or other value if `if command` isn't appropriate. 
- [ ] Improve the wording on the _test_ man page -- especially the summary ("perform tests on files and text"). 
- [ ] Augment the feedback that says "Variables may not be used as commands." to mention eval and test. 

- [ ] As a stretch goal make the feedback context aware; i.e., if the context is `if $status` replace the current feedback with an appropriate example using test.

(Editted by @faho: Make a checklist)

**Comment by krader1961** [comment]
Apply the new "Easy Pick" label since everything but the context aware feedback should be straightforward to implement.

**Comment by DraTeots** [comment]
Hi!
Since I was the new user, let me explain:

0. Background. I heard about fish shell some time ago, but using it for the first week. I really like features like path colored autocompletion out of the box, but one of the biggest motivation points is that I'm not satisfied how things are programmed in bash. I don't write bash scripts very often, and maybe that is the reason that each time I do it, it is SO much a pain. 

This time I was using fish-shell scripting for the first time. I will try to describe everying I met as a first time user (as a developer I know, that could be helpful)



1. Return status. I guessed that $? wouldn't work for fish and googled like "fish get return status" and the first place I met $status was FAQ  here:

https://fishshell.com/docs/current/faq.html#faq-exit-status

> How do I get the exit status of a command?

> Use the $status variable. This replaces the $? variable used in some other shells.

I would propose to add example there
```fish
command
if test $status -eq 0
    echo "Worked OK"
else
    echo "Error!"
end
```
Because using $status in conditionals after the command, I believe, is the major use case. 
If such example was there, that would solve everything right that moment. 

2. Fish-help. Fish error says two things
a. ```define a function like “function status; 0 $argv; end”```. - It was misleading because it used 'status' so I thought it was kind of  "auto generated right", but certainly the function above isn't working.

b. See the help section for the function command by typing “help function”. I should say now, that I like how "help somehting" work in fish. So I opened the help and... I see on my home system an example using with 'if test $status = 0' now. Swear I didn't see it on my work desktop =) Seriously, will check it on Monday. Then I started looking through the help html and found ```test``` function

3. ```test``` in html help. Looking through help, I've found ```test``` that looked something familiar. As I said, I don't write bash scripts so frequently so I remember that one should use test in bash. But fish documentation says:

    Tests the expression given and sets the exit status to 0 if true, and 1 if false.

    The following options are available:

    -h displays a help message and then exits.
    -L FILE returns true if FILE is a symbolic link.
    -S FILE returns true if FILE is a socket.
    COND1 -a COND2 combines two conditions with a logical and.
    -b FILE returns true if FILE is a block device.
    -c FILE returns true if FILE is a character device.
    -d FILE returns true if FILE is a directory.
    -e FILE returns true if FILE exists.
    -f FILE returns true if FILE is a regular file.
    -f FILE returns true if FILE has set-group-ID bit set.
    -n STRING returns true if the length of STRING is non-zero.
    COND1 -o COND2 combines two conditions with a logical or.
    -p FILE returns true if FILE is a named pipe.
    -r FILE returns true if FILE is readable.
    -s FILE returns true if the size of FILE is non-zero.
    -t FD returns true if FD is a terminal (TTY).
    -u FILE returns true if FILE has set-user-ID bit set.
    -w FILE returns true if FILE is writable.
    -x FILE returns true if FILE is executable.
    -z STRING returns true if STRING length is zero.

At this point I would propose adding this phrase from statckoverflow:

> Fish's test command currently works exactly like POSIX test

That would once again help me a lot, because looking at "FILE" in each line gave me an impression that  ```test``` in fish is used only for files.

**Comment by faho** [comment]
>test in html help. Looking through help, I've found test that looked something familiar. As I said, I don't write bash scripts so frequently so I remember that one should use test in bash. But fish documentation says:

You stopped right before the part of interest to you:

```text
The following operators are available to compare and examine text strings:

    STRING1 = STRING2 returns true if the strings STRING1 and STRING2 are identical.
    STRING1 != STRING2 returns true if the strings STRING1 and STRING2 are not identical.
    -n STRING returns true if the length of STRING is non-zero.
    -z STRING returns true if the length of STRING is zero.

The following operators are available to compare and examine numbers:

    NUM1 -eq NUM2 returns true if NUM1 and NUM2 are numerically equal.
    NUM1 -ne NUM2 returns true if NUM1 and NUM2 are not numerically equal.
    NUM1 -gt NUM2 returns true if NUM1 is greater than NUM2.
    NUM1 -ge NUM2 returns true if NUM1 is greater than or equal to NUM2.
    NUM1 -lt NUM2 returns true if NUM1 is less than NUM2.
    NUM1 -le NUM2 returns true if NUM1 is less than or equal to NUM2.
```

How about adding something like "test has operations for files, strings and numbers"?

And maybe add some section markup to separate the parts from each other? Depends on how that looks in our output formats (html, man and terminal).

**Comment by faho** [comment]
@DraTeots: Does 60bd3c8 help?

**Comment by leff** [comment]
@faho if that change will eventually update this webpage then it will help people like me:
 [https://fishshell.com/docs/current/faq.html#faq-exit-status](https://fishshell.com/docs/current/faq.html#faq-exit-status)  
If not, then please update that too.

I default to searching the web for answers; man pages and text files are the last resort. And I doubt that my behavior is that rare. Right now, this page right here is the top google result on this topic, and therefor the best resource. That seems less than ideal to me.

**Comment by faho** [comment]
@leff: That page simply contains the documentation of the current release, so anything we add to the docs will end up there once it is in a release.

Any particular wording anywhere you'd like to see? Should we just include an example in that FAQ?

**Comment by leff** [comment]
@faho The example above helped me a lot. I think it would be a great addition to the documentation.
 
Also, if it was easier to find documentation about how equality works that would help too. The stuff you posted above (quoted below) was really helpful, but I've never found it on the website. I keep expecting it to be near the section on [conditionals](https://fishshell.com/docs/current/tutorial.html#tut_conditionals), and I'd be happy if I found it there in the future.

> The following operators are available to compare and examine numbers:
> 
>     NUM1 -eq NUM2 returns true if NUM1 and NUM2 are numerically equal.
>     NUM1 -ne NUM2 returns true if NUM1 and NUM2 are not numerically equal.
>     ...

**Comment by faho** [comment]
@zanchey: 64d33fa is good for 2.6.0 (as is the other doc-only commit I just pushed).

@krader1961: I have taken the liberty to reformat your opening comment to include a checklist.

@leff: I think 64d33fa is an improvement!

**Comment by faho** [comment]
Okay, we've improved the docs and variables can now be used as commands, so the error is quite a different one (and technically it's a legal expression now, and I'm not sure we want to special-case $status? Unless we want to add builtins called "0" to "255" and let "0" return true and all others false?).

I also haven't seen this happen much.

So I'm closing this.
