### ISSUE TITLE
Can you stop a completion from including results of `*`?

### ISSUE THREAD

**Issue by OwenAR** [fish-shell/fish-shell#2780]
I have a function:

```fish
function sound
	mpv --really-quiet ~/Dropbox/.shared_configs/sounds/$argv.*
end
```

and a completion:

```fish
complete --command sound --arguments (echo (
	for f in ~/Dropbox/.shared_configs/sounds/*
		basename $f | sed 's/\..*$//'
	end
))
```

Contents of the dir in question are:

```
~/Dropbox/.shared_configs/sounds' $ ls
crow.mp3
holycrap.ogg
mail.ogg
max.ogg
min.ogg
oops.ogg
quit.ogg
startup.ogg
```

Now, say I'm in a dir with files and/or subdirs like

```
~/testdir $ ls
some_subdir/
file1
file2
```

When i enter `sound ` and hit tab,
I get the completions I want,
*plus* all the files and subdirs in the dir
(ie all the results of `*`):

```
~/testdir' $ sound 
crow   file2     mail  min   quit          startup
file1  holycrap  max   oops  some_subdir/ 
```

But I want just the actual completions I set up:

```
~/testdir' $ sound 
crow     mail      min   quit
startup  holycrap  max   oops
```

How do I get this?

[The documentation for `complete`](http://fishshell.com/docs/current/commands.html#complete) mentions this flag:

```
-A or --authoritative
   implies that there may be no more options than the ones specified,
   and that fish should assume that options not listed are spelling errors.
```

but it doesn't make clear how to use it
and I'm not sure if it's actually implemented...?
(It doesn't show up in the completions for `complete`.)

`fish, version 2.2.0-658-gf2246df-dirty`

**Comment by faho** [comment]
What you want is to inhibit file completion - the documentation says:

>-f or --no-files specifies that the options specified by this completion may not be followed by a filename.

This is a bit misleading in this case because you are still completing files, but it just inhibits the builtin file completion that would otherwise be offered in addition to what your script puts out.

It's currently probably a bit harder to do for non-trivial cases as you'll need to add that flag to _every applicable_ "complete" call.

**Comment by OwenAR** [comment]
Thanks!

```
complete --command sound --no-files --arguments (echo (
for f in ~/Dropbox/.shared_configs/sounds/*  
basename $f | sed 's/\..*$//'
end
))

**Comment by faho** [comment]
> the auto-indentation seems to break down inside of command substitutions like that.

I do believe there's an issue open about that.

By the way: Your style of passing the arguments is rather weird - the argument to --arguments can be a command substitution (that will then be split to arguments on newline), so 

```fish
complete --command sound --no-files --arguments '(
for f in ~/Dropbox/.shared_configs/sounds/*  
basename $f | sed 's/\..*$//'
end
)'
```

should work.

**Comment by OwenAR** [comment]
Yeah, the question of
when whitespaces are implicitly splitting strings apart
vs when they're literally inside of  them
always gives me a major headache, 
and my "style" of dealing with  is honestly just "flail out a bunch of kludges until it looks like it works"...

That being said, what you have written there doesn't work...?

**Comment by faho** [comment]
>That being said, what you have written there doesn't work...?

Ooh, yeah, sorry, I missed the single quotes around the argument to sed. The outer single quotes should be double quotes.

**Comment by OwenAR** [comment]
Like this?:
```fish
complete --command sound --no-files --arguments "(
for f in ~/Dropbox/.shared_configs/sounds/*
basename $f | sed 's/\..*$//'
end
)"
```
That's also a syntax error.

[The documentation on command substitutions](http://fishshell.com/docs/current/tutorial.html#tut_command_substitutions) says:
```
Command substitutions are not expanded within quotes.
Instead,
you can temporarily close the quotes,
add the command substitution,
and reopen them,
all in the same argument
```

Actually,
that reminds me of a related question
which I ran into ages ago
but was, well, too embarrassed to ask I guess?
Or worried someone would tell me it was dumb or in the wrong place.

But [I finally posted it](https://github.com/fish-shell/fish-shell/issues/2781).

**Comment by faho** [comment]
>That's also a syntax error.

Urgh, yeah. I should really check this before just commenting. The issue is the "$" in the sed expression, that fish tries to expand as a variable because for the purposes of calling `complete`, it's in double-quotes. Later, when this code is executed, it'll be in single-quotes and hence won't be expanded but we need to stop the first expansion. So either close the double-quotes and open single-quotes (then close them again or escape the single-quote that ends the sed argument), or escape the $:

```fish
complete --command sound --no-files --arguments "(
   for f in ~/Dropbox/.shared_configs/sounds/*
   basename $f | sed 's/\..*\$//'
   end
   )"
```

>The documentation on command substitutions says:

That's usually correct, but the case here is that `complete` will evaluate it as a command substitution, not fish as it calls complete. `complete` expects this kind of argument.

BTW:

Comments here tend to be more readable when you don't care quite as much about line-breaking. Just let the github formatter sort it out - you can occasionally open a new paragraph (by inserting an empty line), but doing that every two words or so makes it a bit hard to follow.
