### ISSUE TITLE
Command substitutions work like implicit brace expansion - how do you explicitly *prevent* that?

### ISSUE THREAD

**Issue by OwenAR** [fish-shell/fish-shell#2781]
I tried to make a self-demonstrating example of what I mean
(like,
so you can just copy it into fish
then hit enter to go through line-by-line):

```fish
function echo_foo
	echo foo
end

for l in (echo '
# example 1A
echo (echo_foo)-bar
# like I expected => foo-bar

# example 1B
set x bar
echo (echo_foo)-$x
# like I expected => foo-bar

# example 2A
echo (echo_foo)-bar baz
# like I expected => foo-bar baz

# example 2B -- implicit brace expansion?
set y bar baz
echo (echo_foo)-$y
# but I expected => foo-bar baz

# example 2C -- but you can get the exact same result *ex*plicitly if you want...
echo {(echo_foo)}-$y
# like I expected => foo-bar foo-baz

# example 2D -- So how are you supposed to explicitly *prevent* the expansion?
# at first glace, this looks like it works:
echo (echo_foo)-"$y"
# apparently like I expected => foo-bar baz
# but of course it is actually a single string:
count (echo_foo)-"$y"
')
	read -c "$l"
	eval $l
end
```

So what if you wanted "foo-bar" and "baz" to be two separate strings?

ie, how would you write something like this:
`set output #[do something with the output of the function `echo_foo` and the variable `y`]`

so that this:
`echo $output`
gets:
`foo-bar baz`

and this:
`count $output`
gets:
`2`

**Comment by faho** [comment]
```fish
# example 2B -- implicit brace expansion?
set y bar baz
echo (echo_foo)-$y
# but I expected => foo-bar baz
```

(You can write 
\`\`\`fish
SOMECODE 
\`\`\` 
to make a block with fish highlighting on github)

The issue here isn't the command substitution - it's the list, and it's by design.

This is called the "cartesian product" (because it is - it's a term from mathematics).

```fish
set a foo bar baz
set b spam eggs bacon
echo $a-$b
# foo-spam bar-spam baz-spam foo-eggs bar-eggs baz-eggs foo-bacon bar-bacon baz-bacon
# Same output as:
echo $a-(printf '%s\n' spam eggs bacon)
```

The idea is that the output "foo bar baz-spam eggs bacon", as the arguments "foo", "bar", "baz-spam", "eggs" and "bacon" is seldomly useful - do you have any usecase?

If you wish to achieve it, do it explicitly with list slices:

```fish
echo $a[1..-2] $a[-1]-$b[1] $b[2..-1]
```

because those are the arguments that are going to be passed - the first up to the second-last element of $a each as one argument, the last argument concatenated with a dash concatenated with the first element of $b as another and then the rest of $b each as one argument again.

**Comment by OwenAR** [comment]
Honestly, I had a use case, but I put off asking for so long that I forget exactly what it was.

Something about dealing with `$argv` that might be a filename, or a filename plus a flag...
