### ISSUE TITLE
Something similar to $HISTIGNORE in bash or minimum history entry length

### ISSUE THREAD

**Issue by JelteF** [fish-shell/fish-shell#2788]
I use Ctrl+Z a lot to move vim to the background to some other command such as `make` or `git commit`. To go back to vim I then use `fg` 

In bash the `HISTIGNORE` variable exists. This can be used to ignore certain patterns present in the history. In the case mentioned above you could simly set it like this to ignore both `fg` and `bg` when searching through history:
`export HISTIGNORE="fg:bg"`

Am I missing something or is something like this not available in fish? Another solution to this problem would be to have some form of minimum length of history entry that would be completed. That way any command of 3 or less letters could simply be ignored, as searching for it is probably more work than typing it again.

**Comment by faho** [comment]
Fish's history behaves like bash's "HISTCONTROL=ignoreboth", so you can prefix commands you want to be ignored with a space.

Alternatively you can `history --delete fg` from a function that triggers on the "fish_prompt" event. Currently you'd need to put that into config.fish, in the next release you could put it into a snippet in ~/.config/fish/conf.d.

>Another solution to this problem would be to have some form of minimum length of history entry that would be completed. 

That would be very surprising when you consider aliases (which are rather likely to be short).

**Comment by krader1961** [comment]
> Another solution to this problem...

I'm a little fuzzy on what the problem is. Note that in fish, unlike bash, each unique command line is stored exactly once in the history file. So even if you're using each a lot it won't clutter your history. As @faho also mentioned you can keep arbitrary commands from being logged by simply prefacing it with a space.

I'm also amused by this statement from the bash documentation regarding HISTIGNORE:

> The second and subsequent lines of a multi-line compound command are not tested, and are added to the history regardless of the value of HISTIGNORE.

That sort of thing suggests to me the mechanism isn't really well thought out.

**Comment by JelteF** [comment]
@krader1961 The problem I meant is that you would need to press up twice for subsequent makes, since the last command used is `fg`. 

@faho When I'm looking through my history with the up arrow, I'm never looking for commands of only 3 characters long. I could just simply type those, this also holds for aliases as I've aliased them for a reason. 
Right now I'm using the `abbr` suggestion found here: https://stackoverflow.com/questions/34001591/in-fish-is-it-possible-to-ignore-all-git-related-commands. However, this does not work when commands can have extra arguments. The `history --delete fg bg` command seems to work well though. How could I let that trigger on `fish_prompt` easily (when this function is already used by a theme I'm using).

**Comment by faho** [comment]
```fish
function ignorehistory --on-event fish_prompt # or maybe fish_preexec, see function --help
    history --delete fg bg
end
```

as I said, put this into config.fish

**Comment by krader1961** [comment]
This is a feature that very few people would use; especially when you consider that most people are using multiple terminals and/or tools like screen/tmux these days rather than switching tasks inside a single terminal. Too, this behavior can be implemented by those who want it using a solution such as the one @faho provided. So I don't see any reason to implement a **HISTIGNORE** variable.

**Comment by naggie** [comment]
I have a globally shared history with tmux (such that I can search the history for complex commands instead of writing them again) so that `sudo reboot` and `sudo halt` (for example) become a hazard. `fg` and `bg` are also annoying.

I, for one, would like HISTIGNORE.
