### ISSUE TITLE
Is there a way to pass or decode an alias to other command like `watch` or `entr`?

### ISSUE THREAD

**Issue by chengguangnan** [fish-shell/fish-shell#2797]
[Please include a short description of the problem here]

I made some long and tedious commands into alias, however, I can't pass them to `watch` or `entr` (invoke the command when file changed). Is there a way to archive that?

### Reproduction Steps:

1. alias mytask 'rsync -h'
2. watch mytask

### Expected behavior:

I would expect that `watch` would invoke `rsync -h`. 

### Observed behavior:

watch says sh: mytask: command not found.
---
Fish version: fish, version 2.2.0
Operating system: OS X
Terminal or terminal emulator: iTerm2

**Comment by krader1961** [comment]
The `watch` command isn't native to OS X. So presumably you did `brew install watch` or something equivalent. Your problem is that an external program (i.e., command) isn't going to have any knowledge of a fish function. The fish `alias` command is just shorthand for creating a fish function. Assuming you define the alias in your *config.fish* then you should be able to do `watch fish mytask`.

**Comment by chengguangnan** [comment]
Good idea!  It's `fish -c mytask` if define it in the config.fish file.  That worked! Thanks!
