### ISSUE TITLE
how to show part of the fish_prompt on special situation?

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#2837]
My current **fish_prompt** is like this:
    
    user@domain: ~/path
    ➤➤

Every time I hit just **Enter** key in the prompt, it will print the two lines, how can I make it just display "➤➤" at the prompt, and display the whole lines if only when I change the directory?

**Comment by krader1961** [comment]
Try creating a function like the one below and using the var it creates (**prev_PWD**) in your fish_prompt function to alter its behavior.

```
function _pwd_changed --on-variable PWD
  set prev_PWD $PWD
end
```

**Comment by krader1961** [comment]
Argh! Obviously my simplistic solution doesn't work since the function doesn't run until the var has changed and thus the assignment to **prev_PWD** will have the current rather than the previous value of the PWD. However, it is straightforward to deal with that "one step ahead" situation and is left as an exercise for the student.

**Comment by c02y** [comment]
Yeah, I tried, and it doesn't display the path after I change the directory.

**Comment by krader1961** [comment]
What you seem to be asking are two things:

1) how to display just the "➤➤" portion of your prompt when you press **Enter** without entering any command, and

2) how to display just the "➤➤" portion of your prompt if you enter a command that does not change the current directory.

I have to confess I don't understand why either optimization is useful. However, I don't use a multiline prompt so I'm probably not the best person to opine on this issue.

**Comment by c02y** [comment]
I'm asking the first one.

It's not that useful, I'm just thinking that if it can be configured like 
that it's would be better.

**Comment by zanchey** [comment]
```fish
function fish_prompt
    if test "$history[1]" != "$_last_command"
        echo $PWD
        set -g _last_command $history[1]
    end
    echo -n "> "
end
```

**Comment by krader1961** [comment]
So you're asking if there is a way for the **fish_prompt** function to determine if it was invoked because the user entered anything before pressing **Enter**. That doesn't appear to be possible as far as I can tell without rebinding the enter key. I don't think @zanchey's proposal solves your problem since the command history doesn't include "null" commands (i.e., just pressing **Enter**)

**Comment by c02y** [comment]
@zanchey  Hitting **Enter** will not be added into the $history, so it doesn't work. The $history[1] is the command with real content.

**Comment by zanchey** [comment]
Weird, it works for me as I understand your requirements - by relying on that behaviour and checking that `$history[1]` is the same as the last time `fish_prompt` was invoked.

**Comment by c02y** [comment]
@zanchey It works, sorry about that, I forgot to add the set line into my fish_prompt.

**Comment by zanchey** [comment]
Great!

**Comment by c02y** [comment]
@zanchey There is still a problem, if I open a new fish session, such as new terminal, a new pane in tmux, a new tab in tmux, there will be two lines of "➤➤" lines **without** the path line prompt. And the cursor will be at the first "➤➤" line, hitting Enter will move the cursor into the second "➤➤" line(not create new line of it), if I cd into other place, the second line of "➤➤" on the screen will be placed by something  the second line of "➤➤" is fake.

So now that snippet of code creates two new problems:
1. How to display the whole two lines of prompt when I create a new fish session?
2. How to get rid of the second duplicate of "➤➤" line when opening a new line?

BTW, the code snippet is not exactly the solution to my original question, if the output of a command is short, there still will be only the "➤➤" without path, and since it creates two new problems, maybe a new better solution will be appreciated.

**Comment by zanchey** [comment]
I can't reproduce either of those problems in tmux via PuTTY (nor the short output problem); what terminal are you running? Can you try making a screencast with asciinema or similar?

**Comment by c02y** [comment]
if test "$history[1]" != "$_last_command" -a "$_last_command" != ""

solved the second problem.

**Comment by c02y** [comment]
Terminal: Konsole or Yakuake

Since asciinema is not able to record videos across panes or windows, I use gif:

![recorded](https://cloud.githubusercontent.com/assets/2135996/13912869/6720f5c0-ef7c-11e5-9ef8-43193ca9f1a0.gif)

**Comment by zanchey** [comment]
Should have asked - can you show the exact contents of the `fish_prompt` function you are using at present?

**Comment by c02y** [comment]
function fish_prompt --description 'Write out the prompt'
            set -l last_status $status
    
            if test "$history[1]" != "$_last_command"
                # User
                set_color $fish_color_user
                echo -n (whoami)
                set_color normal
        
                echo -n '@'
        
                # Host
                set_color $fish_color_host
                echo -n (hostname -s)
                set_color normal
        
                echo -n ':'
        
                # PWD
                set_color $fish_color_cwd
                        echo -n (prompt_pwd)
                set_color normal
        
                echo
                set -g _last_command $history[1]
            end
    
            if not test $last_status -eq 0
                    set_color $fish_color_error
            end
            # http://unicode-table.com/en/sets/arrows-symbols/
            # http://en.wikipedia.org/wiki/Arrow_(symbol)
            set_color -o blue
            echo -n '➤➤ ' # ➥ '# '➢ ➣　'# # ➢ ➣, ↩ ↪ ➥ ➦, ▶ ▷ ◀ ◁, ❥
    end


I also tried to use only the code snippet of yours, I mean only the code snippet in ~/.config/fish/config.fish, and only config.fish in the directory nothing else, same result.

**Comment by zanchey** [comment]
Weird, I don't get that behaviour at all - it might be worth trying a different terminal (although that may not help).

Incidentally, your prompt is quite slow - it requires at least two forks. You might be better off looking through some of the sample prompts for how to cache the hostname, and using `$USER` instead of `whoami`.

**Comment by c02y** [comment]
My prompt is indeed slow, I tried to source the fish file named nim.fish (fish-shell/share/tools/web_config/sample_prompts/nim.fish) which provides its own fish_prompt, and it is pretty fast, I tried to modify my own fish_prompt (including replace whoami with $USER, and there is no "cache hostname" in nim.fish, so I think ) according to nim.fish, it doesn't help. I tried to comment the complicated parts such as the **prompt_pwd** in the code snippet, it doesn't help either.

So is there any profiler that I can check the time of a function in fish script?

**Comment by faho** [comment]
>So is there any profiler that I can check the time of a function in fish script?

fish has a "--profile FILE" option, so you can do

```fish
fish --profile prompt.prof -c 'fish_prompt; exit'
sort -k 2 --numeric-sort prompt.prof # Field 2 is the "Sum" field
```

Note however that this will include everything in the configuration file because fish still does a full startup.

This tells me the three slowest parts of your prompt are

- `if test "$history[1]" != "$_last_command"` (158ms, about half for the test and for the `set` if it succeeds)
- `echo -n (hostname -s)` (7ms)
- `echo -n (whoami)`  (1.1ms)

You can save 70ms if you `set -l h $history[1]` and then use that later on twice.

Turns out accessing history is rather slow.

**Comment by c02y** [comment]
Thank you for the profile.

I think I'll keep the original way. The code snipe of that solution is too 
buggy.

**Comment by krader1961** [comment]
Is there anything else you need help with, @c02y, or can this be closed?

**Comment by c02y** [comment]
I come up with another way to work it around: print the path line only when the directory changes.

Is there a way that I can set the path to a variable before doing anything in the prompt? 

Such as I just hit **Enter** or **C-l** to clear the screen or any other commands with real contents, so after that I can compare the variable which is the path before doing anything in in prompt with the path after doing anything in the prompt (**pwd** comand).

**Comment by krader1961** [comment]
> I come up with another way to work it around: print the path line only when the directory changes.

Yes create a function that monitors the PWD variable; for example,

```fish
function WTF --on-variable=PWD
    echo $PWD
end
```

Obviously replace the `echo` with whatever logic meets your needs. Such as replacing the contents of a global var with the previous PWD and the current PWD so that your fish_prompt function can determine if the PWD was changed. This also, obviously, requires that your fish_prompt function modify that var so that after the first prompt when the PWD has changed it doesn't continue to print the directory portion of the prompt.

**Comment by c02y** [comment]
What is the "previous PWD", since there is no **OLDPWD** variable like bash/ksh/zsh?

**Comment by c02y** [comment]
Now, it's done. This is the whole snippet:

    function dirp --on-event fish_preexec
    	set -g OLDPWD $PWD
    end
    function path_prompt
    	# User
    	set_color $fish_color_user
    	echo -n $USER
    	set_color normal
    
    	echo -n '@'
    
    	# Host
    	set_color $fish_color_host
    	echo -n (hostname -s)
    	set_color normal
    
    	echo -n ':'
    
    	# PWD
    	set_color $fish_color_cwd
    	echo -n (prompt_pwd)
    	set_color normal
    
    	echo
    end
    bind \cl 'clear; commandline -f repaint; path_prompt'
    function fish_prompt --description 'Write out the prompt'
    	set -l last_status $status
    
    	if test "$OLDPWD" != "$PWD"
    		path_prompt
    	end
    
    	if not test $last_status -eq 0
    		set_color $fish_color_error
    	end
    	# http://unicode-table.com/en/sets/arrows-symbols/
    	# http://en.wikipedia.org/wiki/Arrow_(symbol)
    	set_color -o blue
    	echo -n '➤➤ ' # ➥ '# '➢ ➣　'# # ➢ ➣, ↩ ↪ ➥ ➦, ▶ ▷ ◀ ◁, ❥
    end
