### ISSUE TITLE
Remove the duplicates in the output of dirh

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#2838]
There will be duplicates in the output of **dirh** command, is there a way to remove the old duplicates and leave the new one?

**Comment by faho** [comment]
The dirh command prints your directory history, i.e. where you've `cd`'d to. This will contain duplicates if you have been to the same place multiple times, e.g. via `cd /tmp; cd ~; cd /tmp`.

Removing duplicates would mean removing history, which seems like it misses the point of the function. In addition, which duplicate should we remove? We can't sort it (because that would jumble the history), so we'd need to decide which of the "/tmp" in the above example we should remove.

Why do you want this? If you just wish to see which directories you've _been_ to, without any ordering, you can also operate on the $dirprev and $dirnext variables manually, e.g. `printf "%s\n" $dirprev $dirnext | sort -u` (or `sort | uniq`).

**Comment by krader1961** [comment]
Allowing duplicates is intentional. As @faho pointed out by definition `dirh` shows the history of cd/nextd/prevd operations; i.e., it's a sequence of the directories you've visited not a set (of unique values). If you're motivated you could create change that adds a `dirh -u` option to cause it to emit a sorted list of the unique directory names. Don't forget to update the documentation and add unit tests.

**Comment by c02y** [comment]
Never mind, I'll keep it that way.
