### ISSUE TITLE
fish_prompt isn't aware of the variables defined in customized functions

### ISSUE THREAD

**Issue by imcaizheng** [fish-shell/fish-shell#2845]
I involve a custom function in the defintion of the fish_prompt function,
but unexpectly I got a error when starting the terminal.
I think of it as a bug because I have to treat the prompt function
as something special though it's placed in the functions directory
like any other function.

### Update

Sorry for the unclarity. I have corrected the title.

Below is the customized function:

    ~➜ cat .config/fish/functions/bat.fish
    set bat0 /sys/class/power_supply/BAT0

    function bat
        if not count $argv >/dev/null
            bat-all
            return
        end
        switch $argv[1]
            case "status"
                bat-status
            case "capacity"
                bat-capacity
        end
    end

    function bat-all
        begin
            bat-status
            bat-capacity
        end | tr '\n' ' '
    end

    function bat-status
        cat $bat0/status
    end

    function bat-capacity
        cat $bat0/capacity
    end

It could be executed on the command line sucessfully.

Here is how I invoke it in my fish_prompt function (simplified):

    function fish_prompt
        if test (bat capacity) -lt 20
            echo "Power is critical"
        end
    end

fish hangs with no error messages during the initialization.

fish version: fish, version 2.2.0-486-g1a3bcf6-dirty

### Additional information:

After some tests, I found that the `$bat0` variable would not be
defined as expected, which results in `cat $bat0/capacity`
being effectively the `cat` command reading from stdin.  That is why fish hangs (as #2848  pointed out).

It's wired because before I involved the `bat` command
in the fish_prompt function `$bat0` would be defined properly.

**Comment by krader1961** [comment]
We need more information. What was the error you saw? How did you define your "custom function"? How did you invoke the custom function? It's probably best to simply show us both function definitions and the names of the files in which you've placed them.

**Comment by c02y** [comment]
My fish_prompt called a customized function, it is totally OK, would you show us your code?

**Comment by faho** [comment]
@imcaizheng:

```fish
  if test (bat-capacity) -lt 20
        echo "Power is critical"
    end
```

I'm assuming you mean "bat-capacity" here? In that case this is expected - fish autoloads function files by name, so it's looking for a file called "bat-capacity.fish" in $fish_function_path. Which it doesn't find since you put it all into bat.fish.

I suggest one of the following:

- Split the functions into different files, named after the function

- Make "bat" the main function to call

- `source` the file on startup (from config.fish)

Also, the way github works you'll want to _add_ a comment after editing because otherwise nobody will be notified. I only found this because I was going through all issues labeled "needs-more-info".

**Comment by faho** [comment]
Ooh, sorry, I missed that `bat` already _is_ the main function. Let me check something!

**Comment by faho** [comment]
Ooooh, there's some weird scoping going on here.... 

If I change the first line to `set -g bat0 /sys/class/power_supply/BAT0` it works (note the "-g"). When I don't add a scoping argument `bat capacity` works, but `function t; bat capacity; end; t` doesn't (in a fresh shell)

I have no idea why the variable seems to receive global scope when run directly but local scope when not.

**Comment by krader1961** [comment]
It's because the first invocation is inside `fish_prompt` which is **function** scope. There is the equivalent of an implicit `source ~/.config/fish/functions/bat.fish` being done inside the the body of the `fish_prompt` function. The rules say (see `man set`):

> has never before been defined, the variable will be local to the currently executing function.

Basically, what the O.P. is expecting is behavior like that provided by Python (or even C). But fish doesn't have a "file" scope.

The solution is to explicitly make the var a global via `set -g`.

**Comment by krader1961** [comment]
Also, the reason the `cat $bat0/capacity` reduces to `cat` in this scenario is because of how fish handles concatenation of a var to a literal string. It's computing the cartesian product of an empty array with the string "/capacity" which yields no values. Quoting the string, i.e., `cat "$bat0/capacity"` would have avoided that particular problem since it would have reduced to `cat /capacity` which would at least have yielded an error that would have pointed to the problem.

**Comment by krader1961** [comment]
Any other questions, @imcaizheng?

**Comment by krader1961** [comment]
@imcaizheng: What could fish have done to make this easier for you to self-diagnose?
