### ISSUE TITLE
fall back to bash/zsh completion if no native completion found for a command

### ISSUE THREAD

**Issue by marmistrz** [fish-shell/fish-shell#2856]
I was just about filing a report _Java autocomplete is incomplete_, but I thought about one thing instead.

Many packages have built-in autocompletion for `bash` and `zsh` (for example pacaur). Maybe fish could fall back to such autocompletion if no built-in completion is available?

**Comment by krader1961** [comment]
Ugh! No. As the [zsh wiki](http://zshwiki.org/home/convert/bash) says regarding importing bash completions:

> Keep in mind that it is much better to rewrite completion functions for zsh than to spend much time getting a bash function to work with this.

Having said that if you want to create a proof of concept implementation I'm sure the fish community would be interested in testing it.

**Comment by faho** [comment]
>Having said that if you want to create a proof of concept implementation I'm sure the fish community would be interested in testing it.

We basically have half an implementation already in https://github.com/fish-shell/fish-shell/blob/master/share/completions/npm.fish#L37-L53. However it's not great because the completions never have descriptions and might not be of great quality. 

Personally I have a standing offer to write completions for something if I can get good enough documentation to write it from. @marmistrz: What's missing in the java completion?

**Comment by marmistrz** [comment]
Hmm... So the question remains: should the completions be fish-centric or should we create pull requests against the packages, so that the fish completion is a part of a specific package (so pacaur completion resides in the pacaur package, etc.)

In bash, when you run a class, then the completion

    java -cp <completes directory, separated with slashes> package.<completes this one, separated with dots, (takes classpath into account) >

in Fish the generic completion kicks in, so you have to type the whole class name manually.

**Comment by faho** [comment]
There is currently no java completion, btw - what you're getting is autogenerated from the manpage. This means it's rather sparse - basically only options, not arguments to those options.

>should the completions be fish-centric or should we create pull requests against the packages, so that the fish completion is a part of a specific package (so pacaur completion resides in the pacaur package, etc.)

Currently, we don't go out of our way to get third-parties to include fish completions. Fish isn't a huge thing, so it's probably better to keep the completions here because here's where the people with knowledge about fish are.

Some have decided to include fish completions (e.g. docker), and that's nice, but only if they then have enough people to maintain them. It also carries a different trade-off regarding compatibility - completions for e.g. docker now only have to be usable for the docker version they ship with, while they probably want to support multiple fish versions. For completions shipped with fish it's the other way around.

**Comment by marmistrz** [comment]
Should I create a separate bug report for the Java problem?

**Comment by faho** [comment]
@marmistrz: Yes, please.

**Comment by krader1961** [comment]
Closing this since I don't think we will ever implement compatibility with bash/zsh completions. Nor should we as there are a huge number of other deficiencies in fish that it would be better to solve.
