### ISSUE TITLE
[Documentation] How does the search ever work?

### ISSUE THREAD

**Issue by marmistrz** [fish-shell/fish-shell#2866]
I sometimes come across some search through the suggestions. But I don't really know how I enter it, and I can't see anything about it in the documentation.  

Besides, I noticed that ctrl+t transposes characters. Is there any documented set of keybindings? Because the current documentation is a "newbie intro" for someone who hasn't used any shell ever.

**Comment by occivink** [comment]
The bindings are defined in the function `fish_default_key_bindings`, which you can view with `funced` and redefine in your local config.

**Comment by faho** [comment]
You'll find the current default keybindings documentation at http://fishshell.com/docs/current/index.html#emacs-mode (unfortunately the "emacs-mode" is not clickable or listed in the sidebar).

It's not complete (not even in current git), so we'll have to change that. Of course PRs are welcome, otherwise I'll try to take a stab at it.

**Comment by faho** [comment]
> (unfortunately the "emacs-mode" is not clickable or listed in the sidebar).

That's because it's a subsection - the "Command line editor" _section_ is listed and clickable, and starts a sentence before.

**Comment by marmistrz** [comment]
Thanks! Just noticed that with `pacman -S` I need to type tab three times. Is this the expected behavior? (first 4 entries, then 9 entries, finally all entries which can be searched)
