### ISSUE TITLE
Change prompt based on location

### ISSUE THREAD

**Issue by lordlycastle** [fish-shell/fish-shell#2872]
I was wondering where the default prompts are saved. Because it would be nice if the prompt changed to the one of the default _Informative Git Prompt_ when current directory is a git repository. 

![screen shot 2016-03-30 at 14 20 20](https://cloud.githubusercontent.com/assets/11729541/14143324/996bfc34-f682-11e5-8772-edf2833cfd94.png)

Any ideas on how to do this? So far I was thinking a function that switches the prompt when run, maybe with the help of a global variable. It would better if there was an automatic way to do this.

**Comment by faho** [comment]
Fish uses the "fish_prompt" function as the prompt (and the "fish_right_prompt" function for... the right prompt), wherever it is stored. The sample prompts are stored in share/tools/web_config/sample_prompts, which ends up in $__fish_datadir when installed.

However, since each of these files define a function called "fish_prompt", sourcing it will overwrite the current prompt.

The "Informative Git" (now "Informative VCS" since it also supports mercurial and svn) prompt will only show git info when current directory is a default prompt, so I'm not sure why you'd want to switch to it only when you have a git directory - why not just always use it?

Anyway, the core logic of the vcs prompt is setting a few variables that make our git prompt function output a different format and then call the `__fish_vcs_prompt` function (which then calls out to `__fish_git_prompt`, `__fish_hg_prompt` and `__fish_svn_prompt`), so you can just incorporate it into your own prompt.

**Comment by floam** [comment]
> Also, the "Informative Git" (now "Informative VCS" since it also supports mercurial and svn) prompt will only show git info when current directory is a default prompt, so I'm not sure why you'd want to switch to it only when you have a git directory - why not just always use it?

This kind of behavior would potentially be a not-bad way to implement a fallback where someone wants to pick a prompt on a remote server (or Windows 10) where they do not have a web browser. They will have to do so manually but fish can make that as pleasant a possible: cd into and out of a handful of prompt directories (not how it is set up now), each with perhaps a prompt and right_prompt file inside and have autoloading change your prompt while you are in there. If you find one you like, to set that as your prompt, copy those files into a spot on ~ or symlink it to some special location.

**Comment by faho** [comment]
@floam: That could be solved in tandem with #2577 - add a proper directory for prompts (I'd rather have one file per "full" prompt than a directory) that fish_config reads, and then also offer a `prompt` function to source the themes. This would also move our samples out from the weird share/tools/web_config/sample_prompts directory.

Which still isn't really the idea behind this issue, which was basically an XY-problem.
