### ISSUE TITLE
fish shell in emacs does not have auto completion like in normal terminal

### ISSUE THREAD

**Issue by chenweiyj** [fish-shell/fish-shell#2888]
I use fish shell, and I really like the auto completion in the normal terminal. I use OS X. However, its wonderful feature has gone in the shell of emacs.

How to make it work like normal terminal in emacs (24) ?

---
Fish version: 2.2.0

Operating system: OSX 10.11

**Comment by krader1961** [comment]
What do you mean when you say "its wonderful feature has gone"? I don't use emacs but do use fish on Mac OS X and have not seen any obvious problems in regards to command completions. What is the **$TERM** value inside your emacs fish environment? What is the **$TERM** value in a "normal" terminal?

Your language locale might be relevant so what does `locale` report in the emacs and non-emacs fish shells?

Can you share your fish config files (e.g., *~/.config/fish/config.fish* and any files it references)?

**Comment by chenweiyj** [comment]
In the non-emacs shell, when I type a character, it will show me some hint to complete the command. However, in emacs it won't. I have found that $TERM in OSX terminal is `xterm-256color`, wheras in emacs shell it is `dumb`. 

But it does not work even if I type the command `set -gx TERM xterm-256color` in emacs shell. 

The `locale` report in non-emacs fish shell is 
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

While, the `locale` report in emacs fish shell is 
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

My fish config is
```
# Path to Oh My Fish install.
set -gx OMF_PATH "/Users/chenwei/.local/share/omf"

# Customize Oh My Fish configuration path.
#set -gx OMF_CONFIG "/Users/chenwei/.config/omf"

# Load oh-my-fish configuration.
source $OMF_PATH/init.fish

# Customize PATH
set -gx PATH /usr/local/sbin:/usr/local/bin

# fix emacs dumb term
if test "$TERM" = "dumb"
  function fish_title; end
end
```

**Comment by faho** [comment]
>wheras in emacs shell it is dumb. 

With a true "dumb" terminal, fish couldn't print suggestions because it would not offer enough features.

Please always use a value for $TERM that actually describes what you are using - for emacs "ansi-term" that would be "eterm-color", though it seems emacs ships the terminfo file in a weird place (see #2441). To work around that, execute `tic -o ~/.terminfo $TERMINFO/e/eterm-color.ti`.

After all that, fish should work, though not great, because ansi-term supports 8 colors at most and lacks support for other things like the title. You'll probably have more fun with it in a "real" terminal.

**Comment by faho** [comment]
@chenweiyj: Do you need anything else?
