### ISSUE TITLE
source references undocumented FISH_CLIPBOARD_CMD env var

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2894]
While commenting on issue #2882 (and indirectly issue #2556) I noticed that *src/kill.cpp* references env var **FISH_CLIPBOARD_CMD** that is not documented. Either document the environment var or remove the reference.

**Comment by faho** [comment]
I use this, for the reason stated in #2740 - I don't like that it overrides what I have in my clipboard.

As far as I can see, we have three options here:

- Document it as-is

- Abandon the syncing idea and instead offer explicit bindings to copy to clipboard

- Remove it

Personally I'd be okay with documenting it, but since I don't like the behavior I'd be happier with making it an explicit operation. It's also worth noting that the vi bindings already have a binding that mentions xsel.

**Comment by floam** [comment]
4. Improve it?

See tmux/vim.

**Comment by faho** [comment]
Also see #772 - it's "frustrating", #965, that calls for changing it to a function, and #605, where it calls for pbcopy being used on OSX (since presumably xsel isn't available).

How about this idea then:

- Make it a function (called `fish_clipboard`?) that calls `pbcopy` if it exists (which should only be on OSX) and `xsel` otherwise

- Document that function

**Comment by floam** [comment]
The function at the very least needs a way to indicate separate copy and paste functions. Just look at all the options ie. xclip takes to work well. This variable itself? Seems about useless.

**Comment by faho** [comment]
I'd like to revisit this for the release after the next, so I'm adding it to that milestone.

**Comment by krader1961** [comment]
See issue #2990. As I said there I don't object to explicit key bindings interacting with the clipboard. I do object to the current spooky action at a distance undocumented behavior. I vote we kill this code in the core C++ code rather than document it.

**Comment by faho** [comment]
Well, as I said I'm not using it either, preferring to use explicit bindings instead, so I second that.

**Comment by ridiculousfish** [comment]
Me three.

**Comment by faho** [comment]
Fixed by merge of #3061.
