### ISSUE TITLE
question: command sub treats args as one string, how to get it to be multiple arguments?

### ISSUE THREAD

**Issue by danielb2** [fish-shell/fish-shell#2909]
when doing command substitution, fish treats the output as a string instead of multiple arguments.

How do I get fish to treat it as arguments instead of a string? I looked in the section for command substitution, but the documentation there does not explain. 

### Reproduction Steps:

1. `git grep class (git branch | grep -v '\*' | xargs echo)`  in a repo with multiple branches

### Expected behavior:

do a git grep on all the branches

`git grep class $(git branch | grep -v '\*' | xargs echo)` works for bash

to repro the problem in bash, I must do:

`git grep class "$(git branch | grep -v '\*' | xargs echo)"`

### Observed behavior:

git gives a fatal error with ambiguous arguments

---
Fish version: 2.2.0-692-g168a156

Operating system: homebrew

Terminal or terminal emulator: iterm2

**Comment by faho** [comment]
Fish splits the output on newlines, so you need to ditch the echo and remove extraneous whitespace (via sed/awk/tr etc or `string trim` if you are using git fish). 

Also my `git branch` still displays the output in columns in this case, so I'd need to add the `--no-columns` option.

**Comment by faho** [comment]
To elaborate on this, the output of `git branch` looks like this when it's not going into a terminal:

```
  bashdoc
  invert-match
* master
  sgrepectomy
```

After the grep, it's

```
  bashdoc
  invert-match
  sgrepectomy
```

Every line here will be given, verbatim, as an argument to the main command, so your git grep invocation would be like

```fish
git grep class "  bashdoc" "  invert-match" "  sgrepectomy"
```

which will of course fail because those aren't branch names - the whitespace is in the way.

So you do `git branch | grep -v '\*' | string trim` (or `sed "s/\s//g"`) and it'll work.

**Comment by danielb2** [comment]
great! thanks

**Comment by danielb2** [comment]
actually, xargs the same thing as trim it seems for bash. So why doesn't it work for fish?

**Comment by faho** [comment]
>actually, xargs the same thing as trim it seems for bash. So why doesn't it work for fish?

Again, fish splits on newline, while bash splits on "any" whitespace (at least newlines, tabs and spaces).

Fish doesn't do this so e.g.

```fish
mkdir /tmp/banana
cd /tmp/banana
touch "a b c"
rm (ls)
```

works (not that you'd ever want to do that, it's just a simple example to demonstrate the behavior).

This means that `echo` does the wrong thing - it echoes (in my example above) `bashdoc invert-match sgrepectomy` - in one line, so fish will use it as one argument, while bash will split on the spaces, so it will be three arguments there.

What would work is `xargs printf '%s\n'` instead of the `xargs echo`, but that's less explicit (I'd pretty much consider the trimming to be a side-effect).

**Comment by danielb2** [comment]
OK, thanks
