### ISSUE TITLE
fish on Bash on Ubuntu on Windows assumes 256-color terminal emulator

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#2910]
The terminal emulator frontend used by the linux subsystem on Windows 10 supports 16 colors. It reports that`TERM=xterm`. Setting this to other values has no effect on the colors supported.

Fish intentionally decides to use 256 color codes in the case of `TERM=xterm`, unless it detects that it is running on Apple's Terminal.app, where it requires xterm-256color to be set before it tries. This causes `set_color` to simply not work on Windows much of the time. This seems like wrong behavior everywhere, though. Fish should just not make this leap at all when `TERM=xterm`. In the case of OS X most people will be reporting `TERM=xterm-256color` and will get their 256 colors. 

![Screenshot of bash.exe](http://i.imgur.com/3jINVjP.png)

**Comment by ridiculousfish** [comment]
Wow. Does `apt-get install fish` actually work on BoUoW?

**Comment by floam** [comment]
Yep, the PPA.

**Comment by floam** [comment]
https://github.com/Microsoft/BashOnWindows/issues/52#issuecomment-207161384

**Comment by krader1961** [comment]
You've got to admire Microsoft's insistence on maintaining backward compatibility &mdash; all the way back to DOS 2.0 apparently.

**Comment by kilobyte** [comment]
A lot of terminals other than xterm claim to be xterm -- most libvte ones, konsole, putty, etc.  But all of those support all important xterm's capabilities (even if they differ in less important details).  This is not the case for the new ConHost.exe which is a really poor terminal.

Thus, I'd say this is their fault and needs to be fixed there.  At least, BoUW **is** labelled as "beta" (I'd say it's early pre-alpha...), so there's hope they'll fix this, either by improving the terminal or at least not having it identify as xterm.

**Comment by floam** [comment]
except don't terminals that support 256 colors typically put the `-256color` there? Or no? Is it most right to assume 16 or 256 given just "xterm"?

**Comment by cjthompson** [comment]
I found that if I run `TERM=ansi fish` to start the shell, then it displays correctly.  I also use shell on my remove Linux servers, so using `ssh` passes along `TERM=ansi` and allows it to display remote sessions correctly as well.

**Comment by zanchey** [comment]
Is this something we want to try and fix before 2.3.0?

**Comment by floam** [comment]
> I found that if I run TERM=ansi fish

I found `TERM=linux-16color` a little better. I'm not sure if it's the right thing to *change* TERM, but in this case it actually would help the user in a number of apps.The fact is the entire / is simply a generic Ubuntu Linux cloud image and MS has done little to customize userland yet.

It's easiest to just have it be a fish universal variable that is exported rather than ask people muck with heir configuration. 

FWIW here's how to go about detecting it isn't Linux:

`~ $ cat /proc/version
Linux version 3.4.0-Microsoft (Microsoft@Microsoft.com) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Wed Dec 31 14:42:53 PST 2014`

**Comment by faho** [comment]
@floam: Is there anything else wrong with TERM=xterm? E.g. are some key combinations not working (backspace/delete or arrow keys, end/home, pgup/pgdown)? Does `clear` work?

Because if there's any other issue, then MS would need to change that anyway (and it's in beta right now, and presumably they want to beef up cmd.exe).

Though I don't think assuming 256 colors for xterm is _right_ as such, enough terms just set $TERM to it and otherwise work well enough that the workaround is probably a net-benefit.

@zanchey: I don't think we should _wait_ for this - I'd rather we push out a quick point-release afterwards.

**Comment by floam** [comment]
Actually, picking `ansi` instead of linux-16color makes scrolling through vim work, when it didn't out of the box.

**Comment by cjthompson** [comment]
It looks like Microsoft is working on a fix for this, so I suspect it might be better to wait for them to fix it rather than trying to work around it in the fish shell code.

**Comment by zadjii-msft** [comment]
It's my understanding that `TERM=xterm` is not supposed to imply 256 color support, which is why we decided to go with that particular TERM setting. Even if we do add 256 color support, it would seem like a bug to assume that just plain `xterm` supports 256 color, when there's specifically `xterm-256color` for that.

**Comment by cjthompson** [comment]
That's a valid point. I'd expect plain `xterm` to be 16 colors as well.

**Comment by faho** [comment]
>It's my understanding that TERM=xterm is not supposed to imply 256 color support, which is why we decided to go with that particular TERM setting.

@zadjii-msft: It's a hack. The issue is that everyone and their mum set TERM=xterm (you'll even see forum threads recommending users to set it in their e.g. .bashrc), which is why that particular setting has basically lost all meaning. By now every single graphical terminal application on linux supports 256 colors, so there it's a safe assumption.

I urge you to go with an actual accurate TERM setting - i.e. if you do set TERM=xterm, then make sure that your terminal does exactly what xterm does - that it sends the correct sequence for backspace/delete (gnome-terminal fails here), all possible modifier+arrow combinations etc, that it uses the same sequence for clearing etc. Also 256 colors would be really nice (though of course truecolor would be even better).

Now we can argue about whether our hack here is a net-benefit or net-negative - on the one hand a terminal that sets TERM=xterm (not even xterm-256color) most likely didn't bother, so it probably won't send the correct sequences, so maybe we should nudge the user in the direction of setting it properly or switching to a different terminal, but on the other hand, if it works reasonably well with this hack they won't even notice.

**Comment by kilobyte** [comment]
The problem with terminals accurately identifying themselves is that, even if installing the terminal in question installs the relevant termcap/terminfo definition on the local machine, ssh-ing to remote machines that don't have this definition will cause all termcap/terminfo-using programs to be unable to display anything.  And historic Unix vendors have been really bad about updating their databases -- for example, current Solaris *still* doesn't understand TERM=linux.

This led to everyone lying about their identification.  That's also the reason no terminal says "xterm-256color" by default, despite all of them who say "xterm" supporting 256 colors.

And not all graphical terminals support 256 colors, for example Debian ships broken rxvt and aterm, but they both identify as "rxvt".  Relying on "xterm" is safe.

Except for current Win10 console -- but it has a long long list of reasons to not identify as "xterm" anyway.  I suggest waiting for Microsoft's move.

**Comment by dstaley** [comment]
In the interim, would there be any negative side effects to adding `set -x TERM_PROGRAM Apple_Terminal` to my `config.fish` file? It seems to help with #2940, but I'm willing to bet there's other changes fish makes based on it besides just color support.

**Comment by floam** [comment]
That probably works. 

You may get even better behavior, by using TERM=interix, and set the terminal to be in the raster font. It makes curses work kind good. But you will only have 8 colors. 

download https://raw.githubusercontent.com/floam/lxsscons/master/bashOnLinuxOnWindows.terminfo and run `tic -v bashOnLinuxOnWindows.terminfo this is a modified terminfo to just make it say there's more colors now. Don't put this on a production environment, it's crazy. Also, there's no such thing as  production WSL environment yet...

**Comment by krader1961** [comment]
There was an extended discussion in issue #2940 after it was closed about how to reliably test whether fish is running on the new Win10 linux subsystem. The answer is that we can rely on the presence of "Microsoft" in the output of */proc/version*. See this [tweet](https://twitter.com/richturn_ms/status/721172947302350848?s=09).

**Comment by zadjii-msft** [comment]
So, a bit of an update. I've added some code to at least process the 256 color sequences into _something_, but true RGB color support out of the question for this particular release (though high on the backlog). It'll take a little while for it to bubble up through the pipeline, but it should come soon<sup>tm</sup>.

We picked `TERM=xterm` because that's what our goal to support is. However, a lot of the fixes are out of step with the linux subsystem releases. As insider flights come out, you'll see the terminal support get much better.

**Comment by floam** [comment]
It looks like it can handle 256-color escapes upstream. It's currently interpolating them to 16 color values which is fine, it will likely use them to the fullest in the future.

**Comment by StoneCypher** [comment]
24-bit color is now in insider builds

https://github.com/Microsoft/BashOnWindows/issues/345

**Comment by faho** [comment]
@StoneCypher: Do you know of a way to detect that we're running inside a version of that term that supports them? Then we could enable it by default. As it stands, I think it's still setting TERM=xterm, and xterm doesn't support 24-bit color.

**Comment by StoneCypher** [comment]
At this time I do not.  I'm a casual passer-by here.

**Comment by floam** [comment]
Probably the file in /proc/?

--  
Aaron Gyes

**Comment by kilobyte** [comment]
I'm not aware of any way to detect 256 nor 24-bit color support, and thanks to a misdesign, using it when unsupported will result in quite nasty undefined behaviour.

The most reliable way I know so far is looking at the response to \e[c\e[>c
```
konsole         \e[?1;2c\e[>0;115;0c
rxvt            \e[?1;2c\e[>85;95;0c
putty           \e[?6c\e[>0;136;0c
xterm           \e[?64;1;2;6;6;9;15;18;21;22c\e[>41;308;0c
xterm           \e[?64;1;2;6;9;15;18;21;22c\e[>41;320;0c
libvte[GTK2]    \e[?62;9;c\e[>1;2802;0c
libvte[GTK3]    \e[?62;c\e[>1;4600;0c
linux           \e[?6c
mlterm          \e[?1;2;4;7c\e[>1;96;0c
mlterm          \e[?1;2;3;4;7;29c\e[>1;277;0c
eterm           no response
terminology     \e[?64;1;2;6;9;15;18;21;22c\e[>41;285;0c
aterm           \e[?1;2c\e[?1;2c
termit          \e[?62;9;c\e[>1;2802;0c
```
but that requires waiting for and parsing a response.

Thus, I'd recommend assuming anything that reports as "xterm" can do 256 colors (including new builds Windows 10), if you're ok with mapping to 16 colors you can even use 256 colors on everything not "rxvt".  Using 24-bit color is currently a bad idea; for fish using the 6x6x6 colorcube should be enough.
