### ISSUE TITLE
Suggestion: remove the feature introduced in issue #983

### ISSUE THREAD

**Issue by ghost** [fish-shell/fish-shell#2929]
I cannot think of a good name for that feature in issue #983. A simple example about that:

```
prompt> echo A \
  # comment
  # still comment
  B  # done
A B
```

That feature implemented by @snnw missed out the case that a line continuation (a backslash plus a line-break) can appear at the end of tokens of any type, not just at the start of the next token, e.g.

``` fish
# At the start of a new token (if a line continuation can be seen as a token)
echo \
  #comment

# At the end of the token `A\` (plus a line-break)
echo A\
 #comment
```

According to [the referred StackExchange question](https://unix.stackexchange.com/questions/85253/is-it-possible-to-have-comments-in-multiline-commands-in-fish) in #983, fish is expected to work like bash:

expected:

``` fish
function my_function
  echo "hello" |
    # remove 'l' 
    tr -d 'l'
end
```

not this one (with an extra backslash):

``` fish
function my_function
  echo "hello" | \
    # remove 'l' 
    tr -d 'l'
end
```

So that feature is not hitting the spot.

Fortunately, there is still no documentation for that hackery feature, I suggest removing it for a simpler and more consistent behavior of line continuation in fish — line continuation just splits a line into two lines, not three or more lines.
#1285 and #1817 (dup) also express the wish for a more convenient pipe.

**Comment by krader1961** [comment]
I concur. Treating

```
echo A \
    # comment
    B
````

as semantically equivalent to

```
echo A \
    B
```

rather than

```
echo A # comment
B
````

is quite surprising. Not to mention trying to get `fish_indent` to handle the first interpretation is going to be a considerable challenge. It already (albeit with a small whitespace issue) treats that example like the second, more natural, interpretation.

**Comment by snnw** [comment]
Apologies for the silence, I had no idea this discussion was going on.

I must have misunderstood the behaviour of bash back then.  I am all in favour of removing "smart" continuation for smart pipes, as in #1285.

**Comment by mqudsi** [comment]
Pipes are now valid line continuations in fish 3.0 and this hack is no longer needed.

**Comment by floam** [comment]
2cdacbd was reverted, and 3.0 handles this the same way as when this issue was reported:
```fish
> echo hello | \
> # comment here
> tr -d 'l'
heo
```

**Comment by faho** [comment]
It's been 8 years since the offending feature was introduced, 4 years since people attempted to undo it.

Notably this hasn't been a big issue in practice, and now there's been a lot more time with this feature so now compatibility is a concern.

I'll be closing this unless someone comes in and champions this again.
