### ISSUE TITLE
Should vi-mode inherit from default-mode?

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#2930]
From comments in #2412, #2472 and #2255 I deduced that vi-mode users also want the bindings from default (aka emacs)-mode when they don't conflict with the vi bindings. So I went ahead and implemented it in #2474.

It seems I was wrong (@krader1961 has been particularly against it), but now the question remains what we should do about this? Should we revert the entire thing? How many of the requests should we implement or reject?

@krader1961: You [suggested](https://github.com/fish-shell/fish-shell/issues/2832#issuecomment-203168544) "retaining fish-specific bindings". Can you list what they are?

**Comment by krader1961** [comment]
> You suggested "retaining fish-specific bindings". Can you list what they are?

An obvious example is the recently discussed `\cC` binding. If we do decide to not inherit emacs bindings in vi-mode then I'll be happy to create a comprehensive list for whomever reworks this logic. Which will probably be you, @faho :-)

**Comment by floam** [comment]
Hm - well I found the commit to be not surprising. Things work fine - I haven't gotten too deep into this one yet.  What are some obvious bad ones that wouldn't make it through?

**Comment by krader1961** [comment]
I need to read the comments in the issues you reference, @faho, but I'm still not convinced inheriting emacs bindings make sense. For example, in Vim \cA adds *N* (the keystroke numeric prefix, defaulting to one) to the number at/after the cursor rather than moving to the start of the line. And \cE scolls *N* lines upwards rather than moving the cursor to the end of the line. You can certainly argue those behaviors are fubar but they are what most people using vi-mode expect. Which means that in fish they should perform equivalent actions or nothing at all rather than their emacs equivalent actions.

**Comment by faho** [comment]
>You can certainly argue those behaviors are fubar but they are what most people using vi-mode expect

I wouldn't argue that those behaviors are fubar, I'd argue that they aren't all that useful in a shell, where you're mostly dealing with single lines. Though the \cA thing might be useful in some circumstances, it's not implemented currently IIRC.

**Comment by ninrod** [comment]
@krader1961 
> For example, in Vim \cA adds N (the keystroke numeric prefix, defaulting to one)

yes. in normal mode. But in insert mode it could behave as emacs. Would be awesome if it did, actually.

**Comment by faho** [comment]
This has been fixed via 93b9e744.
