### ISSUE TITLE
Unexpected text on startup with my prompt configuration.

### ISSUE THREAD

**Issue by reiesu** [fish-shell/fish-shell#2941]
Fish is printing unexpected text on startup with my prompt configuration.

### Reproduction Steps:

`1.` Build fish from master (something broke this between 2.2.0 release and now).
`2.` Use my prompt: 
```fish
set -g f 1
function fish_prompt
  set -l exit $status
  set -l line1 (set_color blue)(pwd | sed 's|^'$HOME'\(.*\)$|~\1|')
  set -l line2 (set_color red)'\n❯'(set_color yellow)'❯'(set_color green)'❯ '

  if test $SSH_TTY
    set line1 (set_color red)(whoami)(set_color white)' at '(set_color yellow)(hostname)(set_color white)' in ' $line1
    echo
    echo -e -s $line1 $line2
  else if test $exit -ne 0
    set line1 $line1 ' '(set_color yellow)(format_time $CMD_DURATION)
    set symbols (set_color red)'\n❯❯❯ '
    echo
    echo -e -s $line1 $line2
  else if test $f -eq 1
    echo -e -s $line1 $line2
  else
    echo
    echo -e -s $line1 $line2
  end
  set f 0
end
```
`3.` Create new terminal window.
`4.` pwd is printed twice, as well as extraneous symbols in an incorrect place. This corrects itself with subsequent prompt printings. I've been fighting with it for like two weeks thinking it was the way I structured my prompt or something and I'm at my wit's end. I apologize if I've made some really dumb mistake that is causing this issue. Let's just say that coding is not my day job. 🙃

### Expected behavior:

<img width="570" alt="screen shot 2016-04-15 at 6 37 22 pm" src="https://cloud.githubusercontent.com/assets/2200609/14576755/2acacd72-033a-11e6-8282-d60a9e24e356.png">

### Observed behavior:

<img width="570" alt="screen shot 2016-04-15 at 6 35 40 pm" src="https://cloud.githubusercontent.com/assets/2200609/14576757/3303a7b6-033a-11e6-8e69-0b9a2a85ed53.png">

---
Fish version(s): `fish --version 2.2.0-g21e927d`

Operating system: OS X 10.11.4. Fish installed using Homebrew with `brew install fish —HEAD`

Terminal or terminal emulator: iTerm2

**Comment by faho** [comment]
I can reproduce it and I've narrowed it down to this minimal prompt:

```fish
set -g f 1
function fish_prompt

	if set -q f
  		echo ">"
	else
		echo
		echo ">"
	end
	
	set -e f
end
```

And... no joke, it bisects to b73bf53bd30cb8b6056888a473368968041dbe66.

If I remove the condition that causes `fish_term24bit` to be enabled (in my case the existence of $KONSOLE_PROFILE_NAME) it works. Also, if I add a `sleep 1` to right before the `set -e` part, it works.

In other words, we've got ourselves a good old-fashioned race that seems to only occur with multiline prompts that access global variables while in truecolor mode. @ridiculousfish?

**Comment by faho** [comment]
@rolyreyes: Can you confirm my findings by either adding a `sleep 1` before the `set fresh 0` or unsetting $ITERM_SESSION_ID and launching a new fish?

**Comment by rolyreyes** [comment]
Confirmed.

**Comment by krader1961** [comment]
@rolyreyes, What is the point of your `fresh` variable? Because given just the code you posted it makes no sense. It would only make sense if you're manipulating the `fresh` var elsewhere. And even then I'm perplexed why you're using the presence or absence of a single blank line to convey something meaningful.

@faho, This is not a race in the usual sense of the term. It's a consequence of fish's sophisticated prompt repaint mechanism and "--on-event" run function mechanism. What's happening is that `fish_prompt` is being called at the end of its startup initialization. That results in `fish_prompt` being called which writes the single line prompt.

That causes `__fish_on_interactive`, defined in *share/config.fish* to be run because it's monitoring the `fish_prompt` event. That function explicitly calls `__fish_config_interactive.fish` which sets variable `fish_term24bit`. That in turn causes `react_to_variable_change()` in *src/env.cpp* to run which special cases that var resulting in the prompt being repainted. Only now the `fish_prompt` function writes a multi-line prompt.

This is easier to see if you use the following function rather than @faho's version above:

```
set -g f 1
function fish_prompt

    if set -q f
        echo "1>"
    else
        echo B
        #echo
        echo "2>"
    end

    sleep 1.0
    set -e f
end
```

I don't think this is a regression in the usual sense so I'm removing that label. The observed behavior is due to running functions that are triggered on`--on-event` and `--on-variable` events only when the current execution context completes. Changing those semantics may, or may not, be a good idea but could only be done in a major (e.g., 3.0.0) release.

**Comment by krader1961** [comment]
I've also removed the 2.3.0 release milestone because there is no reason for this to block that release. TBD is whether the behavior is really a bug (probably not) or just insufficiently documented (more likely).

**Comment by reiesu** [comment]
It must make some amount of sense considering that it works? The purpose of $fresh is to differentiate between a fresh terminal session and an already existing one. At startup $fresh equals 1, the prompt is printed, and $fresh is set to 0 so that subsequent prompts include an extra line break.

If you have any suggestions to improve implementation or an idea for how I can better handle such a case, I'm open to suggestions.

**Comment by krader1961** [comment]
> It must make some amount of sense considering that it works? 

It only works on fish v2.2.0 by accident.

Did you just change your public ID from "rolyreyes" to "reiesu"? If so, that's a slightly rude thing to do in the middle of a dialog as it confuses everyone (other than yourself) about who is participating in the conversation and whom we're talking to.

If you want to distinguish between a new terminal session and subsequent interaction with an existing session the usual way is to add a statement such as `status --is-interactive; and echo Something about a new session` to your *~/.config/fish/config.fish* file.

**Comment by krader1961** [comment]
> The purpose of $fresh is to differentiate between a fresh terminal session and an already existing one. At startup $fresh equals 1, the prompt is printed, and $fresh is set to 0 so that subsequent prompts include an extra line break.

That only works in most shells because they don't have fish's feedback mechanisms I alluded to earlier which can cause the prompt to be rewritten even though no command was entered. Whether that is a feature or a bug is a matter of perspective.

**Comment by faho** [comment]
This is certainly an unusual thing to do, but the way it fails is not nice.

@krader1961: Wouldn't this be solved if we pushed setting fish_term24bit into share/config.fish, i.e. before the fish_prompt event? That'd be slightly more efficient anyway as it wouldn't cause the first prompt of every shell to be repainted.

**Comment by faho** [comment]
@reiesu: Please test #2945.

**Comment by reiesu** [comment]
Works! Thanks so much for your time and help, @faho.

Should I close this issue now or if/when your commit gets merged?

**Comment by faho** [comment]
@reiesu: It'll get closed automatically when that happens because I mentioned "Fixes #XXXX" in the commit message.
