### ISSUE TITLE
[SOLVED] fish equivalent to precmd/PROMPT_COMMAND ?

### ISSUE THREAD

**Issue by gawells** [fish-shell/fish-shell#2942]
Is there a fish equivalent for precmd (zsh) / PROMPT_COMMAND (bash)?

I'm looking for a way to store a more comprehensive history with path, date and command in a separate log file

**Comment by faho** [comment]
There's a variety of ways to do this. Fish's prompt is a bit of code in a function called `fish_prompt`. You can modify it via `funced fish_prompt` and then save those changes to disc with `funcsave fish_prompt` (this will store it in ~/.config/fish/functions/fish_prompt.fish).

Otherwise, there's the `fish_prompt` event that will be fired just before a prompt. You can write a listener for it like

```fish
function dostuff --on-event fish_prompt
    # do your stuff
end
```

Note that this cannot be saved in the functions directory as those are autoloaded.

There's also the `fish_preexec` and `fish_postexec` events that will be fired right before/after a job, respectively.

**Comment by zanchey** [comment]
@gawells, did this answer your question?

**Comment by gawells** [comment]
Yes, it did thanks
