### ISSUE TITLE
Better handling of string replace with arrays.

### ISSUE THREAD

**Issue by simotek** [fish-shell/fish-shell#2971]
Probably outside the scope of valid use cases so the behavior is justifyably undefined but I accidentally stumbled into this one today and thought its probably a candidate for improvement while you can still change behavior. When using string replace with an array ie the REPLACEMENT is an array rather then a string the behavior 

### Reproduction Steps:

simon@tek-top ~ ➤  echo $PATH 
/usr/bin /usr/local/bin /usr/bin /bin /usr/X11R6/bin /sbin /usr/sbin /home/simon/.local/bin /opt/QtCreator/bin /home/simon/Applications/.bin /home/simon/.local/bin
simon@tek-top ~ ➤  set TMP '/opt/foo $PATH /home/simon/src/Scripts' 
simon@tek-top ~ ➤  string replace '$PATH' $PATH $TMP 
/usr/local/bin
/usr/bin
/bin
/usr/X11R6/bin
/sbin
/usr/sbin
/home/simon/.local/bin
/opt/QtCreator/bin
/home/simon/Applications/.bin
/home/simon/.local/bin
/opt/foo /usr/bin /home/simon/src/Scripts

### Expected behavior:

I expected the following but again I asked it to do something silly

simon@tek-top ~ ➤ string replace '$PATH' (string join ' ' $PATH) $TMP 
/opt/foo /usr/bin /usr/local/bin /usr/bin /bin /usr/X11R6/bin /sbin /usr/sbin /home/simon/.local/bin /opt/QtCreator/bin /home/simon/Applications/.bin /home/simon/.local/bin /home/simon/src/Scripts
simon@tek-top ~ ➤z

---
Fish version: 2.3b1
Operating system: openSUSE Tumbleweed (Beta repo)

Terminal or terminal emulator: Terminology

**Comment by faho** [comment]
What you are observing here is an interaction between a few fish design decisions.

- Like bash (and every other shell I know), we expand variables and then pass the expanded strings to the command

- We pass arrays per-element - every command we launch receives each array-element as one argument (unlike bash, which likes to try to split your elements again)

>` string replace '$PATH' $PATH $TMP `

This _can't_ work with the shell model.

The problem is that you want to pass two arbitrary lists of things to a command, and then want the command to remember what belongs to which list. With the idea that the shell expands things and then passes them as arguments, the command can't know what came from where because it never saw lists to begin with.

(Of course it would theoretically be possible to special-case `string` because it's a built-in, but that would be against a few very fundamental things, so please let's not do it).

What you need to do here is double-quote your list, or use `string join` if you wish to use a separator other than space - `string replace '$PATH' "$PATH" $TMP`. (Ideally you'd also add "--" to guard against $TMP having an element that looks like an option).
