### ISSUE TITLE
Entered commands get copied when there's an auto-suggestion

### ISSUE THREAD

**Issue by bmintz** [fish-shell/fish-shell#2990]
Every time I start typing a command that has suggestions for arguments from past commands, what I've typed gets copied to the clipboard.

### Reproduction Steps:

1. `echo foo bar baz`
2. Run `echo "it would suck to lose this" | xsel -ib` in bash
3. In fish, type `echo` so that `foo bar baz` is suggested.
4. Run `xsel -ob` in bash

### Expected output:

`it would suck to lose this`

### Observed output:

`echo`

### Additional information:

Observed: always
First observed: a few months ago (no specifics, sorry)
Nothing has changed on my system recently that has affected the issue.  

---
Fish version: 2.2.0

Operating system: Ubuntu 16.04
I installed fish through the distro packages (repo: universe).

Terminal or terminal emulator: xfce4-terminal 0.6.3

**Comment by krader1961** [comment]
The `xsel` support was added before 2012. The exact date is murky because of all the reformatting and other cleanups to the code. The core fish code (i.e., the portions written in C++) invoke xsel if `$DISPLAY` is set when deleting text from the typed input (and possibly other conditions). But the behavior is not intuitive to me.

I vaguely recall a discussion about this a few months ago but can't find it now. Personally, I think this "feature" should be removed. In part because it doesn't work on OS X which is a privileged platform unless you create an external script named `xsel` that invokes `/usr/bin/pbcopy`. But more importantly because, as you noted, the unexpected alteration of the global clipboard without an explicit action on the part of the user (e.g., by selecting the text with the mouse) is surprising.

**Comment by jakwings** [comment]
`set -gx FISH_CLIPBOARD_CMD 'cat > /dev/null'` ?

**Comment by krader1961** [comment]
@jakwings: Mind creating a PR to document that variable? I find exactly two references in the fish project, both in *src/kill.cpp*.

**Comment by krader1961** [comment]
Argh! I take that back. Please don't document that bogosity, @jakwings. See the code from *src/kill.cpp*:

```
    const env_var_t clipboard_wstr = env_get_string(L"FISH_CLIPBOARD_CMD");
    if (!clipboard_wstr.missing())
    {
        escaped_str = escape(str.c_str(), ESCAPE_ALL);
        cmd.assign(L"echo -n ");
        cmd.append(escaped_str);
        cmd.append(clipboard_wstr);
    }
```

It assumes you've prefaced the command with a pipe symbol. That is, it's broken if you set `FISH_CLIPBOARD_CMD` as you suggested. Sure, we could fix that block of code but I'd prefer to just rip out this "feature".

**Comment by krader1961** [comment]
OMFG! I thought this sounded familiar. Do this [fish issue search](https://github.com/fish-shell/fish-shell/issues?utf8=%E2%9C%93&q=is%3Aissue++FISH_CLIPBOARD_CMD).

I have no objection to explicit key bindings invoking something like `xsel` or `pbcopy`. But I strongly object to this hidden, spooky action at a distance, implementation. Please, let's kill this.

**Comment by krader1961** [comment]
I'm closing this because we are going to have a lively discussion about this behavior in issue #2894. Hopefully with the outcome that we kill this "feature".
