### ISSUE TITLE
`abbr` command mangles its arguments

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2997]
@etu noticed that fish 2.3 had a regression in the behavior of the `abbr` command and created https://github.com/fish-shell/fish-shell/pull/2996 to fix it. Which caused me to ponder the code. Both the original regex and @etu's replacement are wrong. But that doesn't matter because of how `$mode_arg` is constructed and the behavior of `__fish_abbr_split`. They collude to turn `abbr -a "abc def" "wtf"` into the equivalent of `abbr -a abc "def wtf"`. Which is truly surprising behavior and clearly not what the user intended.

So there are two problems here:

1) The abbr code mangles its arguments in an unexpected manner that can negate the intent of the user.

2) The abbr unit tests don't adequately test corner cases such as invalid abbreviations.

**Comment by krader1961** [comment]
For the record, the regex on line 88:

```
if not string match -qr "[^\s]" -- $key
```

should be `'^\S+$'`.

**Comment by faho** [comment]
Currently, because of the way abbrs are stored (in a universal variable), we _can't_ have spaces in the key (because we use spaces to delimit the key from the value, and the value can definitely have spaces). That was what that test was originally meant to stop.

So `abbr -a "abc def" "wtf"` should probably throw an error, with us actually using the first argument as the key.
