### ISSUE TITLE
Make <TAB> accept auto-completion first

### ISSUE THREAD

**Issue by Elijen** [fish-shell/fish-shell#3011]
As I am coming from Bash I am very used to type few first letters of a command/parameter and then hit <kbd>TAB</kbd> to get the rest. With Fish this makes me execute unpredicted commands when hitting the <kbd>ENTER</kbd> too fast. Accept auto-complete key binding is also too complicated to be used as fast as <kbd>TAB</kbd> can be. 

Is there a way to make Fish behave more similar to Bash?

1. Type `git pu` -- `git pull origin master` is suggested
2. Hit <kbd>TAB</kbd> -- `git pull origin master` is accepted as if I pressed <kbd>Ctrl</kbd>+<kbd>f</kbd>
3. Hit <kbd>TAB</kbd> again -- Fish cycles through more options (same as how <kbd>TAB</kbd> works now)

**Comment by faho** [comment]
That's not how it's supposed to work. In fact how it is supposed to work is pretty much just how you want it.

What is your tab key bound to (`bind \t`)? The default binding is "complete". Try `bind \t complete` in an interactive session.

**Comment by Siecje** [comment]
If I type ```git pu``` there will be a suggestion of ```git pull origin master```. But if I press ```TAB``` it will become ```git pull``` and if I press tab again it will be ```git push```. 

It will not become ```git pull origin master``` by pressing ```TAB```. If you do press ```TAB``` and it becomes ```git pulll``` there will not be a suggestion for ```git pull origin master```.

The thing that is confusing to new users is ```TAB``` completion vs ```Ctrl+e``` suggestions.

**Comment by Elijen** [comment]
@Siecje Exactly, this is the problem.

@faho It seems to be set as expected:
```
$ bind \t
bind \t complete
```

**Comment by Elijen** [comment]
What I would like to have is:

1st <kbd>TAB</kbd> does `forward-char`
2nd <kbd>TAB</kbd> does `complete`

**Comment by laughedelic** [comment]
> 1st TAB does forward-char

Did you mean `forward-word`?

**Comment by Elijen** [comment]
@laughedelic It confused me a bit too, but `forward-char` seems to be the default way of accepting suggested command. See:

```
$ bind | grep forward-char
bind \e\[C forward-char
bind -k right forward-char
bind \cf forward-char
```

**Comment by laughedelic** [comment]
Oh, I see. `forward-char` will accept the whole completion, while `forward-word` will accept it word by word.

**Comment by faho** [comment]
So pretty much the exact opposite of how I understood it initially? Sorry.

>What I would like to have is:

@Elijen: I don't think you actually want that. It seems like you misunderstand what suggestions are, which is also why you think this behavior is "more similar to Bash" - it's not, because bash doesn't have suggestions.

When you enter a command, we often print a greyed-out continuation. That's the suggestion. This is our best guess of how that command _could_ continue, but it's just that - a guess. It checks a few datasources, including your history and the current directory for possibilities, but it can then only offer one, so it's often wrong (it's right surprisingly often though, which makes it so awesome).

In contrast a completion script would offer you all options and only ever directly insert the part that all options have in common (so if there's only "git push" and "git pull", it would insert "git pu"), and then ask you which way you'd like to go.

If you made your tab key behave the way you're asking, you'd have a hard time when we guess wrong. In your example this would occur if you wanted to enter "git push".

The way suggestions are supposed to work is that they are there, and when one is right it's this nice bonus, but when one is wrong it doesn't hurt. You'd turn that on its head.

This is the part where I'd offer you a workaround or hack to achieve your desired behavior anyway but I can't think of a way - you would want to bind something to `commandline -f accept-autosuggestion complete`, but that would never enter the pager (since you'd never execute the complete function twice in a row). Maybe `commandline -f accept-autosuggestion complete-and-search`.

**Comment by Siecje** [comment]
Why not have a suggestion (if one exists) after a completion. 

```git pull origin master``` is suggested but if you complete to ```git push```. Fish will suggest ```git push origin master```.

**Comment by faho** [comment]
@Siecje: Good question, that is now issue #3016.

**Comment by Elijen** [comment]
@faho Thanks for the explanation, I see your point.

> it's right surprisingly often though, which makes it so awesome
This is what I also think and that's why I would like to have `accept-autosuggestion` better accessible. I will try to use Fish some more and think about what would be the best way of handling this. One thing that came to my mind was re-ordering the completion list so the next word from suggestion is the first.

**Comment by faho** [comment]
I believe the question here has been answered. If anyone has any more ideas about making suggestions better, feel free to open a new issue.

**Comment by ChrisChiera** [comment]
Trying Fish out and ran into this issue as well where all the other apps and GUIs I've used tab on Mac at least always auto completes, such as Atom or other text editors. I've read through the above and see people mentioning you might auto complete something you didn't mean to, but from what I've read you can already auto complete by clicking right arrow. Since right arrow is allowed even though you might auto complete something you didn't mean to, a bit curious why we couldn't set it to be tab instead of right arrow. Not by default but at least a setting/option for people who prefer it?

**Comment by ridiculousfish** [comment]
@ChrisChiera If you want tab to accept the autocompletion, you can set a key binding:

    bind \t accept-autosuggestion

**Comment by demisx** [comment]
Adding to @ridiculousfish's answer, here is how to make it permanent for the current user:

```sh
$ vi ~/.config/fish/config.fish
---
(add this line)
bind \t accept-autosuggestion
```

**Comment by pkulak** [comment]
@demisx's solution won't _quite_ work. Any key bindings put in config.fish will be overwritten. Instead, put that line here:

    ~/.config/fish/functions/fish_user_key_bindings.fish

**Comment by expipiplus1** [comment]
I think the behaviour I'd expect would be to tab complete up until the next space or `/`

**Comment by pastephens** [comment]
I just want to not have to use right arrow, which takes my hand off the home row. Is that possible?

**Comment by faho** [comment]
@pastephens You can press any key combo that moves the cursor. In particular ctrl+f does the exact same thing as right-arrow.

**Comment by mario-holubar** [comment]
> What I would like to have is:
> 
> 1st TAB does `forward-char` 2nd TAB does `complete`

I also wanted this behavior and wrote a function for it:

```fish
# Tab once to accept suggestion, twice to trigger completion menu
function smart_tab
    # If already in completion menu, just navigate
    if commandline --paging-mode
        commandline -f complete
    # If command line changed, accept autosuggestion or trigger completion menu
    else if test (commandline) != "$__cl_after"
        set -g __cl_before (commandline)
        commandline -f accept-autosuggestion
        set -g __cl_after (commandline)
        if test "$__cl_after" = "$__cl_before"
            commandline -f complete
        end
    # If command line is unchanged since accepting autosuggestion, revert and trigger completion menu
    else
        commandline -r $__cl_before
        commandline -f complete
    end
end
```
Enable with
```fish
bind \t smart_tab
```

**Comment by mario-holubar** [comment]
Addendum: If you'd like it to also preselect the first item in the completion menu:
``` fish
# Tab once to accept suggestion, twice to trigger completion menu
function smart_tab
    # If already in completion menu, just navigate
    if commandline --paging-mode
        commandline -f complete
    # If command line changed, accept autosuggestion or trigger completion menu
    else if test (commandline) != "$__cl_after"
        set -g __cl_before (commandline)
        commandline -f accept-autosuggestion
        set -g __cl_after (commandline)
        if test "$__cl_after" = "$__cl_before"
            commandline -f complete
            # Preselect first item
            if commandline --paging-mode
                commandline -f complete
            end
        end
    # If command line is unchanged since accepting autosuggestion, revert and trigger completion menu
    else
        commandline -r $__cl_before
        commandline -f complete
        # Preselect first item
        if commandline --paging-mode
            commandline -f complete
        end
    end
end
```
