### ISSUE TITLE
NPM global commands not working with fish

### ISSUE THREAD

**Issue by coljung** [fish-shell/fish-shell#3023]
Basically I am able to install global NPM packages successfully. But then, when i try to run them, i always get: 'fish: Unknown command 'npm-check'

I thought the problem was associated with npm / node installation, but after redoing that process a few times, i tried switching from Fish back to bash and now all npm global commands work fine. 

Example: npm install npm-check -g

Installs fine, but i get the unknown command message when i type npm-check. Now, if i switch to bash shell, it works perfectly.

As a side note, several google results have commands like:

  sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share} 
and i get this message: 'In fish, the '$' character is only used for accessing variables.' So far i have been unable to make it work.

Thanks in advance for any help.

fish, version 2.1.2
osx captain

**Comment by faho** [comment]
npm puts its stuff into the directory that `npm bin` prints. It seems this is added to bash's $PATH automatically.

Add something like `set fish_user_paths (npm bin)` to your config.fish (or execute it once and add whatever it prints).

>As a side note, several google results have commands like:

>sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share} 

This is POSIX-sh code, which will not work in fish. In this case, it is easy to translate. Just remove the "$":

```fish
sudo chown -R (whoami) (npm config get prefix)/{lib/node_modules,bin,share} 
```

>fish, version 2.1.2

That's a rather old fish version. We're preparing 2.3.0, but 2.2.0 was released almost a year ago. Since it seems you are new to fish: How did you install that one?

2.3.0 has an improved error message in this case: "$(...) is not supported. In fish, please use '(whoami)'."

**Comment by faho** [comment]
Though I have to say that code would cause all sorts of issues on my system, since `npm config get prefix` seems to be "/usr" here. You'd make /usr/bin and /usr/share owned by your user.

**Comment by coljung** [comment]
Thanks a lot, issue appears to be fixed now, set fish_user_paths (npm bin) pointed me in the right direction.

**Comment by coljung** [comment]
Just a note, what ended up fixing my issue was editing the config.fish file and setting:

set PATH /Users/{myusername}/{global-npm-folder}/bin $PATH

**Comment by fifiteen82726** [comment]
Here is what I did


```bash
⋊> ~ npm config get prefix                                              
Now using node v8.9.4 (npm v6.0.0)
/Users/MyUserName/.nvm/versions/node/v8.9.4
```
So the npm path should be `/Users/MyUserName/.nvm/versions/node/v8.9.4`
```
vim ~/.config/fish/config.fish
```

Add the following code at the last line

```
set PATH /Users/MyUserName/.nvm/versions/node/v8.9.4/bin $PATH
```

It works for me.

**Comment by cesards** [comment]
```
set PATH /Users/MyUserName/.nvm/versions/node/v8.9.4/bin $PATH
```
This works for me as well, but I'm wondering if there is a better way, since changes in the npm version will cause the problem again.

Any ideas? Feedback is super welcome!

**Comment by BarbzYHOOL** [comment]
Same question, why do we have to do this hack fix?

**Comment by faho** [comment]
>Same question, why do we have to do this hack fix?

What "hack fix"? You need to add stuff to $PATH to be able to use it.

**Comment by faho** [comment]
AFAIK, that's what these "version manager" things are for. E.g. [nvm](https://github.com/creationix/nvm) says to source the script. Which presumably means that it'll change something about the shell's environment.

**Comment by BarbzYHOOL** [comment]
Hack fix in the sense that any package you install is normally working out of the box on linux, you don't need to add it to your path. The only other time it happened to me was with an obscure python package.

Also it works fine on bash, so it seems related to fish.

**Comment by ridiculousfish** [comment]
@BarbzYHOOL , I'm happy to look at how this works in bash. Can you give an example package where you ran into this (i.e. that works out of the box on bash, but not with fish)? Thanks!

**Comment by BarbzYHOOL** [comment]
@ridiculousfish yes, https://github.com/jwu910/check-it-out/ (I even opened an issue there)

Note: when I installed npm, I changed the default install dir to my home dir (to allow only --user installs) but I doubt it's related

**Comment by faho** [comment]
@BarbzYHOOL: Do you use nvm?

Does your bash config contain any variation of `source nvm.sh` or `. nvm.sh` or `eval $(cat nvm.sh)`? nvm adds that to .bashrc (and a few others) by default, but that won't work in fish. (also it's a bit of a hack, and will slow your shell startup down)

There really isn't anything great we can do here - we can't just execute `set -a PATH (npm bin)` on every start, because that goes against node version management (and also because it's dog-slow), we can't `source nvm`, because that's a POSIX script, and we don't want to take over node version management, so we're not gonna reimplement nvm.

Really... what do you expect us to do?

(As a side-note, I'd actually expect that these version managers could work without being `source`d, either by printing the values they need to set, or by using symlinks. They just tend to be written that way because it's easy)

**Comment by BarbzYHOOL** [comment]
> Really... what do you expect us to do?

I don't know? I see a bug, I report it to their repo and they tell me it's probably fish related, so I report the issue on fish repo. I guess I followed the right process :P


I never seen "nvm" but if you mean "npm", you are right, there is this in my bash config `export NODE_PATH="$NODE_PATH:$HOME/npm/lib/node_modules"`

It probably got added by npm package automatically as I suspected. So it means the responsible is npm for not caring about fish users?

**Comment by faho** [comment]
>I never seen "nvm" but if you mean "npm", you are right, there is this in my bash config export NODE_PATH="$NODE_PATH:$HOME/npm/lib/node_modules"

I don't think that particular line explains it.

Apparently, you can run an npm tool by just calling `the-name-of-the-thing` in bash. That means bash finds it via its lookup, which similar to fish checks a bunch of stages, including functions and $PATH for external commands. Most likely, what we are looking for is some line that adds to $PATH (not any other $SOMETHING_PATH, because those are of no interest to bash). So that means something that does `PATH=something`. Now, this can be hidden in anything that is `source`d (or `.`d) or `eval`d - that runs arbitrary code without showing it to you explicitly. Which is why I've asked for `source nvm.sh`.

>So it means the responsible is npm for not caring about fish users (or me for not using the "default" path)?

Well.... basically, yes. I mean I'm not going to demand fish support from anyone - it's a bunch of work for what is probably not a large part of your user base - but npm (or nvm, or whoever added to $PATH in your bash setup) adding fish support would be the easiest way of making this "just work".

Alternatively, either configure it manually, use [fnm](https://github.com/fisherman/fnm), which is apparently an nvm clone in fish, or use [bass](https://github.com/edc/bass) to run nvm in fish.

**Comment by BarbzYHOOL** [comment]
```
source nvm.sh
bash: nvm.sh: No such file or directory
```

Ok, nice for fnm, however I myself use "n" dunno if it's similar. Anyway I make very small usage of node and npm.

ty for conclusion

**Comment by Crypt0Graphic** [comment]
None of solutions in here worked for me. Probably they are deprecated. For example in Mac there is no config.fish. 

My closest solution (for mac) is that works only until i close terminal:

set PATH $PATH /Users/{USERNAME}/.npm-packages/bin/

**Comment by faho** [comment]
>For example in Mac there is no config.fish.

@Crypt0Graphic: You need to create it.

**Comment by Crypt0Graphic** [comment]
Ok, i figured it out. No need to config.fish. (Already i created it and still didn't work)

This command is permanent solution for me:

set -U fish_user_paths /Users/{USERNAME}/.npm-packages/bin $fish_user_paths

Os: MacOs Mojave
Fish: 2.7.1

**Comment by skheria** [comment]
This works flawlessly: https://medium.com/@joshuacrass/nvm-on-mac-for-fish-users-e00af124c540

**Comment by armikhalev** [comment]
> This works flawlessly: https://medium.com/@joshuacrass/nvm-on-mac-for-fish-users-e00af124c540

This worked for me, feels like robust solution.

**Comment by pablo-fior** [comment]
in 2024, if someone end up here trying to use fish + nvm + node and can´t get the version number on WSL2 Ubuntu-24.04
`set -U fish_user_paths /home/{USERNAME}/.nvm/versions/node/*/bin $fish_user_paths`
it actually updates when you change versions

**Comment by wthrajat** [comment]
[This is the solution](https://github.com/fish-shell/fish-shell/issues/3023#issuecomment-387944920) for anyone wondering.
