### ISSUE TITLE
Customise config file location

### ISSUE THREAD

**Issue by OJFord** [fish-shell/fish-shell#3030]
It doesn't seem to be possible to set (e.g. from the system-wide config, or environment variable) the location of the `~/.config/fish/fish.config` file to somewhere else.

I don't have anything else using a directory in `~/.config`, so in my dotfiles I have the ridiculous path `fish/.config/fish/fish.config`!

Has this been considered and dismissed, or it a possibility?

I have a feeling #862 intended to ask this (or at least, similarly for history) but that part of the question wasn't understood and the conversation focused on the others before the issue was closed.

**Comment by zanchey** [comment]
Fish tries to follow the XDG application specification, so it stores its configuration in the path specified by the environment variable `XDG_CONFIG_HOME`, falling back to `~/.config/fish` as recommended. Does that do what you want?

**Comment by OJFord** [comment]
@zanchey Thanks for your response. Not completely, though it helps.

What I'd like is to be able to `set FISH_CONFIG_HOME "$XDG_CONFIG_HOME/poisson"` - that is, even though I can set `XDG_CONFIG_HOME`, if I understand correctly fish is still always going to look for a `fish` directory.

**Comment by krader1961** [comment]
Correct, @OJFord. As @zanchey pointed out fish adheres to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). I don't think supporting a `$FISH_CONFIG_HOME` var can be justified since it adds complexity without solving any problem. Too, most fish users are likely to add additional scripts to *~/.config/fish*, most notably in a *~/.config/fish/functions* directory for user defined autoloaded functions.

**Comment by OJFord** [comment]
@krader1961 What I'm proposing would include those functions too.

Personally instead of `~/.config/fish/`, I would use `~/.fish/`

**Comment by krader1961** [comment]
Yes, I understand that. My point is that this adds complexity but no new functionality and doesn't solve any problem other than addressing the distaste some people have for the XDG standard. Doesn't seem worthwhile to me. Too, the fact you're not presently using any other apps that utilize the XDG standard is not a compelling argument. I'm using several apps that do so.

There's only a handful of volunteers (I'm one of them) contributing on a consistent basis and we're all doing it without pay. Which means we need to carefully weigh the value:cost ratio of each proposed enhancement. There is a huge backlog of actual bugs and more valuable enhancements. I don't think the ratio is high enough in this instance.

**Comment by OJFord** [comment]
No worries, I completely understand; an awesome job you do too :)

**Comment by OJFord** [comment]
@krader1961 Would you be open to a PR, or are you against it being implemented at all?

**Comment by krader1961** [comment]
The PR would have to be comprehensive. Not just the core implementation but also documentation and unit tests. Even then I would be ambivalent but as a general rule we don't reject PRs that are otherwise of good quality and that meet a real need. The question is whether the other core maintainers (e.g., @zanchey and @ridiculousfish) aren't bothered by adding yet another configuration option. Configuration options are something we try really hard to avoid in the fish project so that we don't turn into bash or zsh.

**Comment by krader1961** [comment]
FYI, I just checked the zsh source code and it does not utilize the XDG standard -- at least there's no mention of the XDG env vars other than in one completion script: *Completion/Unix/Command/_ncftp*. So your assertion that it does:

> Zsh does this in addition to respecting XDG

is apparently not true. I'd encourage you to wait a few days before creating a PR so that other contributors can provide feedback. I'm still disinclined to support such a change.

**Comment by krader1961** [comment]
Reopening since this is an enhancement request that deserves broader discussion and if @OJFord decides to create a pull-request they should be able to reference this issue in the PR.

**Comment by OJFord** [comment]
Sure, happy to wait for feedback.

The commit linked above implements it; I'm using it locally fine.

No tests for it yet though as it wasn't immediately clear how to go about that (currently it seems `XDG_CONFIG_HOME` is used for all tests; not set/unset and tested per se).

I was under the impression that zsh _supported_ the XDG standard, but didn't default to it. I may well be wrong, sorry.

**Comment by faho** [comment]
>I don't have anything else using a directory in ~/.config, so in my dotfiles I have the ridiculous path fish/.config/fish/fish.config!

Soo... why not set XDG_CONFIG_HOME to just the path to your main dotfiles directory? E.g. if you have it (like I do) in ~/dev/config, and the fish part would (sensibly) be in ~/dev/config/fish, if you set $XDG_CONFIG_HOME=~/dev/config, fish will look in ~/dev/config/fish.

**Comment by OJFord** [comment]
@faho Thanks for the response.

That's... a good idea 😄 

I'd still prefer a `FISH_CONFIG_HOME` layer of granularity, since it would be flexible enough to fit my setup and anyone else's without further modification.

For example, currently I symbolic-link all directories in dotfiles to `$HOME`, so to use `XDG_CONFIG_HOME` in the way that you suggest I need to change `stow *` to `stow <manually-maintained-list>`, lest I pollute home with links to fish config, history, etc.

It's a better workaround than keeping my own fork up to date with all of your awesome work - but it's not my ideal.

**Comment by miqlas** [comment]
It would be great to specify the config folder for Haiku too. We don't like to see dot folders in our Home, we have ~/config/settings folder for that.

**Comment by faho** [comment]
@miqlas: As with the others, wouldn't setting $XDG_CONFIG_HOME to ~/config/settings help? Then fish would look in ~/config/settings/fish.

**Comment by miqlas** [comment]
@faho : thank you, it worked.

**Comment by faho** [comment]
I'll close this for now. If anyone would like to propose a concrete design we'll discuss it, but the system we have now seems simple and flexible enough.

**Comment by buggymcbugfix** [comment]
@OJFord I just did `ln -s ~/.config/fish/config.fish ~/.fish`.

**Comment by OJFord** [comment]
Hm,  it's weird to revisit this. I've since (quite soon after, possibly because of!) become a proponent and user of XDG directories, and think everyone and every tool should use them. 😉 

Yes, on macOS too. (That's usually what I'm ranting about in issues such as these...)
