### ISSUE TITLE
Handling of third party bindings / organization (key_bindings.d)

### ISSUE THREAD

**Issue by terlar** [fish-shell/fish-shell#3032]
I like where we have gone with the functions and completions handling, also the `conf.d` has cleaned up the structure for fish customizations in a nice way. I feel that the key bindings has got left behind.

Some plugins and scripts include vendorized key bindings, currently there is not specified way of how this should be done, and each project ends up coming up with their own idea. Since key bindings is kind of special it cannot utilize the `conf.d` or other structures.

I know for example that [fzf](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.fish) provides out of the box key-bindings.

Also it feels like the maintainability of the key-bindings-file gets out of hand when you have a lot of key bindings and each of these define custom functions to isolate behaviour that would also be a good case for the `key_bindings.d` structure.

I propose that we have some folder like `$fish_datadir/vendor_key_bindings.d` and also in `$XDG_CONFIG_HOME/fish/key_bindings.d`. That would be able to auto-load.

The other alternative would be to have some function naming scheme which can be loaded. But I wonder if it is a good idea to litter the function namespace with these things.

**Comment by faho** [comment]
The underlying issue, for those reading along at home, is that binding functions need to be re-executed whenever the binding variable changes (because we want to get back to a pristine binding set, we need to erase everything). That's why this issue exists.

Of course adding another hierarchy would be possible, but there's a few more possible solutions here:

- Add an event ("fish-reload-key-bindings") that binding functions can listen for

- Add a variable ($fish_key_binding_functions) that binding functions can add themselves to

- Yes, call every binding function "binding_*" and execute it.

The first solution has the issue of ordering - bindings are _way_ more likely to clash than vendor scripts and we don't guarantee ordered delivery of events.

With both the second and third you could just disable a binding set via the existing functions/snippets mechanism (though functions would require you to declare an empty function).

I'm wary of adding yet another directory hierarchy, especially when the existing stuff _almost_ works.

What I'd like now is more examples of things that add keybindings, so I can evaluate how much of it clashes. I see that most of fzf's bindings already clash (though with stuff like "capitalize-word" that I never use anyway).

**Comment by terlar** [comment]
Thinking about this some more I agree that it would be nice to reuse the current structure and not introduce another hierarchy.

Currently I tried out emitting an event in the `fish_user_key_bindings` function and then have other functions defined in `config.d` which listens to this event. It works good, but as you raised the issue what if things are conflicting and also there is no way to control the ordering, as well as having a lot of events might be a performance issue(?).

The reason why I wanted to separate it into a different directory structure was that I were thinking that we don't want to load these files in the way `conf.d` files are loaded and also not litter the function namespace. If they had their own folder they could be ordered by prefixing with numbers and then later sourced inside the `fish_user_key_bindings` or other function.

However I think all different solutions have their strengths and downsides, and I think it is good to toy with it a bit, and as you requested if we can present some more use cases.

So far the other things I have seen is [pisces](https://github.com/laughedelic/pisces) and of course all local key bindings that I have, would be nice to split them out per category or isolation. For example I have keybindings for stashing and poping the commandline which is an isolated piece of functionality. If there was a way to structure key bindings in this way perhaps the community would share more and more of these things.

Definately would be good to have a way to opt-out of clashing key-bindings. Perhaps only have the structure locally for the user and not system wide key-bindings.

**Comment by faho** [comment]
>If they had their own folder they could be ordered by prefixing with numbers and then later sourced inside the fish_user_key_bindings or other function.

They can already be prefixed in conf.d. You can make `50-binding-pisces.fish` and `99-binding-terlar.fish`. That's what I'm talking about when I say conf.d "almost" works. All we need is a way to not trample over those keybindings when the bindings get reloaded - and the most likely solution is to trample over them and then add them again (because otherwise it's kinda hard to get back to pristine bindings, or to allow switching to vi-bindings in a running shell).

>So far the other things I have seen is pisces

This by design overrides a couple of keybindings - tab, backspace and the keys for the pairs.

**Comment by terlar** [comment]
That would work, I was thinking about a prefix with `binding`, that wouldn't work with ordering. But then you could also do `binding-50-pisces.fish`. However it is probably better to do what you say there and support re-sourcing any file including `binding`.

The reason that I didn't like that was that they would also be sourced without any real use during the regular `conf.d` sourcing, not that that would be a big problem.

1. All files are sourced `conf.d` several bindings are setup.
2. Keybindings are loaded resetting all the bindings.
3. The keybinding files in `conf.d` are sourced again.

Perhaps I am missing something?

**Comment by laughedelic** [comment]
> For example I have keybindings for stashing and poping the commandline which is an isolated piece of functionality. If there was a way to structure key bindings in this way perhaps the community would share more and more of these things.

@terlar Why not to make it a plugin with configurable keys to bind to?

> > So far the other things I have seen is pisces

> This by design overrides a couple of keybindings - tab, backspace and the keys for the pairs.

@faho Yes, overwriting key for the pairs is the point of this plugin, while overwriting existing bindings for <kbd>tab</kbd> and <kbd>backspace</kbd> could be optional. I was thinking how to make it better. For example, save existing key bindings before overwriting them to be able to restore them on plugin uninstall (or to warn user about overwriting). But probably it's easier to erase introduced bindings and call `fish_user_key_bindings` or some general bindings reload function?

Unfortunately I don't know enough about fish internals to give any suggestions about how to make key bindings mechanism better, but I'm interested in the discussion.

**Comment by faho** [comment]
>For example, save existing key bindings before overwriting them to be able to restore them on plugin uninstall (or to warn user about overwriting).

In that case just re-running the binding function would suffice. Just re-setting $fish_key_bindings should also work, though we have a line in the listener that prevents that (it explicitly skips a reset if the value hasn't changed). Maybe we should remove that.

This is something you shouldn't have to worry about.

>The keybinding files in conf.d are sourced again.

@terlar: They're not quite "sourced" again, the functions are run for the first time. I think your underlying worry here is that it's going to slow down too much (since the event-stuff is what cost OMF a bit of performance). I'm not sure that's going to be much of an issue here since I don't think you'll have fifty keybindings files.

Anyway, if you want to have bindings enabled automatically but autoloaded, you'll have to make it clear that something's a binding from the outside. That means either the separate directory you suggested (which I think is too much clutter for too small a feature) or a "namespace" for functions. That, or fish needs to peek at function files to find any event handlers (which has been suggested before, but that could cost some real performance and doesn't really seem all that pure).

Or a major rework of the binding system (which isn't without flaws, but coming up with something truly better is _hard_).

**Comment by faho** [comment]
This should be solved in 3.0 because `bind` statements can now appear anywhere - #5195.
