### ISSUE TITLE
string builtin always adds a newline

### ISSUE THREAD

**Issue by mrak** [fish-shell/fish-shell#3082]
First of all, I'm _really_ digging the new `string` builtin. I have noticed that it always appends a newline character. I see that this was discussed in #2296 but I'd like to add a formal issue here.

### Reproduction Steps:

Using `$PWD` as an example string as its value does not end in a newline.

```fish
~> cd
~> string replace $HOME '~' $PWD
```

### Expected behavior:

Here `⏎` represents the character that fish automatically inserts before writing the prompt if the previous output did not end in a newline.

```
~> cd
~> string replace $HOME '~' $PWD
~⏎
~> █
```

### Observed behavior:

```
~> cd
~> string replace $HOME '~' $PWD
~⏎
~> █
```

### Additional information:

Fish version: `2.3.0`

Operating system:
Mac OS X 10.11.5 El Capitan
installed via `brew`

Terminal or terminal emulator: iTerm2 Build 2.9.20160523

**Comment by faho** [comment]
My question here is which issues does this cause? So far I've not had any issues with this behavior - and when something ends up on the screen like here I'd usually want a newline anyway.

**Comment by krader1961** [comment]
I was going to ask the same question as @faho. When `string` is used in a command substitution (the common case) the trailing newline is harmless. When used in a pipeline you usually want the newline. So  in what situation does this behavior cause a problem?

**Comment by mrak** [comment]
I'm using

```fish
string replace $HOME '~' $PWD | string replace -ra '([^/.])[^/]*/' '$1/'
```

to display the folder path in my prompt but it's adding an extra newline to my prompt.

I'm currently adding a `| tr -d \n` to the end to prevent this. I had expected there not to be a newline originally, as `$PWD` doesn't have one.

**Comment by krader1961** [comment]
I see. The idiomatic fish way to do this is

```
set -l var (string replace $HOME '~' $PWD | string replace -ra '([^/.])[^/]*/' '$1/')
```

Then incorporate `$var` in a subsequent echo or printf command. And if you don't have one then simply do

```
echo -n (string replace $HOME '~' $PWD | string replace -ra '([^/.])[^/]*/' '$1/')
```

**Comment by mrak** [comment]
The strange behavior I was seeing appears to be because of `set_color`.

```fish
# ~/.config/fish/functions/__prompt_pwd.fish
function __prompt_pwd
  set_color green
  string replace $HOME '~' $PWD | string replace -ra '([^/.])[^/]*/' '$1/'
  set_color normal
end
```

```fish
# ~/.config/fish/functions/fish_prompt.fish
function fish_prompt
  set -l u (whoami)
  set -l p (__prompt_pwd)

  printf '%s %s\n~> ' $u $p
end
```

Result, the __directory text and the first `~>` are green__, while the username and second `~>` are the normal foreground.

```
myuser ~/.c/f/functions
~>
~> █
```

If I remove the `set_color` statements from the `__prompt_pwd` function, the output looks appropriate and non-colored:

```
myuser ~/.c/f/functions
~> █
```

I think the issue I'm seeing here may be specific to how `fish_prompt` is handled with newlines and not an issue at all with `string`?

**Comment by mrak** [comment]
forgot to add that if I put `| tr -d \n` at the end of my `string` operations, the prompt has the proper number of newlines and coloration.

¯\\\_(ツ)\_/¯

**Comment by krader1961** [comment]
The problem you're seeing has nothing to do with `set_color`. It is due to your private `~/.config/fish/functions/__prompt_pwd.fish` script expecting `string` to not terminate its output with a newline. The solution is to replace

```
string replace $HOME '~' $PWD | string replace -ra '([^/.])[^/]*/' '$1/'
```

with

```
echo -n (string replace $HOME '~' $PWD | string replace -ra '([^/.])[^/]*/' '$1/')
```

in your *~/.config/fish/functions/__prompt_pwd.fish* script.

**Comment by mrak** [comment]
Interesting. It looks like another I/O redirection needs to take place for the newline to be discarded.

Either explicitly removing it from the output with `tr`, or by converting the output of `string` to an array of values that gets passed to `echo` as arguments where the newline from `string` has been implicitly removed during the array conversion.

The `set_color` problem I realize is that I was using `set_color normal` after my `string` command, which had a newline. This caused the final characters in the `__prompt_pwd` output to be escape sequences for color reset instead of the newline. Therefore it didn't get automatically removed when the output was put into a variable within `fish_prompt`.

It looks intentional that `string` unconditionally adds a newline to output to be a good *NIX cli citizen. It can lead to some unexpected results when thinking of it as a string mutator such as `tr`.

**Comment by faho** [comment]
>Interesting. It looks like another I/O redirection needs to take place for the newline to be discarded.

Well, not really. It's just that command substitution discards trailing newlines.

>It looks intentional that string unconditionally adds a newline to output to be a good *NIX cli citizen. It can lead to some unexpected results when thinking of it as a string mutator such as tr.

It's not really an intentional, discussed, design decision. It was present in the original PR and we didn't feel it was worth investing too much thought into it - it could have led to bikeshedding.

So that's why we're having this discussion now. And I still believe that usually you'll want the newline. Another argument for that is that you can use `string` on multiple arguments, and it will separate them by newlines, which is pretty much _always_ what you want, so this would be about special-casing the last line (`string replace -- "$HOME" '~' $foo $bar` will print two directories with the tilde-replacement, and I don't think you'd want those on one line since you couldn't use it with command substitution as easily).

For prompts, it's nice to put every part into its own variable and then construct the entire thing afterwards - that makes it easy to get an idea of how the prompt will look.

**Comment by mrak** [comment]
Closing this issue. 

Thanks all for the patience and explanations!
