### ISSUE TITLE
inconsistent listing when tabbing on extensions

### ISSUE THREAD

**Issue by gawells** [fish-shell/fish-shell#3089]
When hitting tab on typing ".ext" I'll get different behaviour depending on the how files are name. 

### Reproduction Steps:

If I have a directory with typeIIa.pdb and typeIIb.pdb `pymol .pdb<tab>` will print out `pymol typeII`. However, if there are also files beginning with a different sequence, eg `typeIIa.pdb typeIIb.pdb test.pdb` I'll get all the pdb files listed, as expected. This seems to require a minimum length of the initial string in common.

### Expected behavior:

List all files matching an extension when tabbing on that extension

### Observed behavior:

If all files begin with the same string, only that string is printed in place of the extension. Otherwise, all files matching the extension get listed

### Additional information:
---
Fish version: [from the output of fish --version]
2.3.0
Arch linux

Terminal or terminal emulator: [e.g. PuTTy, iTerm2, GNOME Terminal, VT220]
xterm

**Comment by faho** [comment]
This is a consequence of our substring matching.

When you complete ".pdb", we look at all the files that have ".pdb" somewhere in the name. When you only have "typeII*.pdb", then we'll complete to the longest common prefix, which is "typeII". When you also have "test.pdb", then we (IIUC) decide that the prefix isn't long enough.

I've been personally bitten by this. In our share/functions directory, I was trying to edit `__fish_config_interactive.fish`, so I entered `emacs inter<TAB>`, and then it expanded to `__fish_` because `__fish_print_interfaces.fish` and `__fish_print_lpr_printers.fish` also exist. Which of course increases the number of candidates again instead of reducing it (118 vs 3).
