### ISSUE TITLE
Locale settings reset on 2.3.0

### ISSUE THREAD

**Issue by occivink** [fish-shell/fish-shell#3092]
Hi,

After upgrading to fish 2.3.0 my locale settings seem to be messed up: `locale` prints the following:
```
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
despite my `/etc/locale.conf` containing `LANG=en_US.UTF-8`. The issue also happens with an empty fish configuration directory. I don't have any user `locale.conf` either.
If I downgrade fish to 2.2.0 the locale variables are properly set. 
I'm on arch linux and use fish as my login shell.

**Comment by krader1961** [comment]
Fish has never, to the best of my knowledge, ever read */etc/locale.conf*. Issue #277 is open to ask that it do so but it's a controversial issue. I'm guessing the Arch Linux maintainers customized the 2.2.0 release and that hasn't happened for the 2.3.0 release.

**Comment by zanchey** [comment]
Not quite - there used to be code in `/etc/config.fish` to set the locale to `en_US.UTF-8` if no other locale was set, but I removed this in b4b52b8234098.

I would definitely encourage the Arch maintainers to ship something that reads `/etc/locale.conf`, as that is appropriate at a distribution level.

**Comment by faho** [comment]
@occivink: I'd really like to know what terminal and DE you're running - I also use arch and I don't think I've managed to not inherit a $LANG from the environment.

It seems like your DE doesn't read locale.conf, so there's nothing for us to inherit.

If you'd try again in fish 2.2.0, you'd probably see it always setting en_US.UTF-8, no matter what you set.

Anyway, reading locale.conf should boil down to about

```fish
if test -r /etc/locale.conf
    while read -l kv
        set -gx (string split "=" -- $kv)
    end </etc/locale.conf
end
```

**Comment by occivink** [comment]
@faho: I'm only using a wm (bspwm) and termite, but I don't think the issue stems from that, since the locale is not even correct in the TTY.

I'll try out your suggestion.

**Comment by thenewvu** [comment]
I've experienced this issue on `rxvt-unicode`. I'm using `fish` 2.3.0 on archlinux. I re-configured my locale settings, it was okay until I restarted `fish`, and every locales became `POSIX` just like @occivink. If you need me provide anything more to investigate this issue, please suggest.

**Comment by krader1961** [comment]
> the locale is not even correct in the TTY.

Technically it is correct. What's happening is that because no locale specific environment vars are set (e.g., `LANG`) the locale subsystem defaults to POSIX. That is the correct behavior in that situation. It's nothing fish is doing explicitly.

The problem is that the user session environment hasn't been properly initialized to include the `LANG` env var (or any of the `LC_*` vars) when fish is launched. That initialization is traditionally done in one of several ways. For example, the "init" (or "systemd") process might do it. Or it might be done indirectly by the PAM subsystem on Linux. Or the GUI session manager (e.g., "xdm") might have done it. As a fallback the distro maintainers might have put the initialization in a global init file for the shell such as */etc/profile*.

**Comment by faho** [comment]
Urgh... the [man page](https://www.freedesktop.org/software/systemd/man/locale.conf.html) lies (well, by omission):

>The locale settings configured in /etc/locale.conf are system-wide and are inherited by every service or user

Nope - getty@.service (shipped with systemd) clears locale on purpose:

```sh
# Unset locale for the console getty since the console has problems
# displaying some internationalized messages.
Environment=LANG= LANGUAGE= LC_CTYPE= LC_NUMERIC= LC_TIME= LC_COLLATE= LC_MONETARY= LC_MESSAGES= LC_PAPER= LC_NAME= LC_ADDRESS= LC_TELEPHONE= LC_MEASUREMENT= LC_IDENTIFICATION=
```

@occivink, @thenewvu: Let me guess - you're both starting the session via e.g. `startx`? In that case, that's the line that gets you. Otherwise your session manager should be doing this.

This isn't something we'd want to get into - reading /etc/locale.conf seems easy, but then you also need to read .config/locale.conf and the kernel commandline....

One possible solution is to create ~/.pam_environment with

```
LANG DEFAULT=en_US.UTF-8
```

or you can override the Environment= setting for getty@.service, or you can set LANG from config.fish (which works since 2.3.0)....

If this behavior annoys you, try talking to the systemd folks.

**Comment by thenewvu** [comment]
@faho: You're right, I've being started my session by `startx`. I've just tried your solution, and the issue doesn't happen anymore.

Thank you all for helping me out of this.

**Comment by occivink** [comment]
Indeed, I'm also using `startx`. 

>Otherwise your session manager should be doing this.

Wouldn't that mean that the locale is not set when you're logging straight into a TTY? Is it really the session manager who's supposed to be reading the different `locale.conf` files?

Anyway since there doesn't seem to be a canonical place to set these variables I've added the following to `config.fish`, as per your suggestion:
```
if status -l; and test -r /etc/locale.conf
    while read -l kv
        set -gx (string split "=" -- $kv)
    end </etc/locale.conf
end
```
which works fine. 

Thanks for your help.

**Comment by krader1961** [comment]
> Is it really the session manager who's supposed to be reading the different locale.conf files?

Yes. If you look at the source for bash or zsh you won't find any mention of *locale.conf*. To the extent those shells are reading that file it's always due to the distro maintainers providing custom global config scripts such as */etc/profile* (bash, zsh) or */etc/config.fish* (fish). This type of thing is highly distro specific. It's the responsibility of the session manager to provide certain basic env vars, such as HOME, LANG and TZ, to the top level shell (or window manager).

**Comment by occivink** [comment]
I'm not saying it should be the responsibility of fish, but rather of systemd or whatever does the basic initialization.

**Comment by faho** [comment]
>I'm not saying it should be the responsibility of fish, but rather of systemd or whatever does the basic initialization.

Yes, it is - and systemd does that (you can check /proc/*/environ for every service PID), except for getty, where it explicitly disables it again for a reason I don't understand.

Nevermind the bit about the "session manager", that was an oversight on my part. If something else _also_ does it, that's okay. But really, systemd has documented that they'll do it, only they don't in this case.

**Comment by krader1961** [comment]
> ... except for getty, where it explicitly disables it again for a reason I don't understand.

Linux VTs don't understand UTF-8 AFAIK (also true for hardware terminals on serial ports like a VT220). So non-ASCII chars like the Unicode return symbol fish likes to print in UTF-8 locales would cause weird output. So it's quite reasonable for it to disable the locale vars (or explicitly set them to C/POSIX) where getty is used. It's probably an oversight that `startx` doesn't reinit the locale vars. It really should do so since it is effectively starting a new session.

**Comment by faho** [comment]
@krader1961: I can actually use e.g. "ä" (0xc3a4) in mine. The problem isn't with the bytes that make up the characters, the problem is that it has (IIRC) 256 glyphs (i.e. "character images" - the arrangement of pixels to display for a character) at the same time.

So if you're showing characters that the "font" doesn't have, they'll appear as question marks.

Anyway, wherever this should be addressed, it's not fish. We can offer workarounds, but not a real solution.

**Comment by zanchey** [comment]
> If this behavior annoys you, try talking to the systemd folks.

I did!

https://lists.freedesktop.org/archives/systemd-devel/2015-October/034589.html
https://lists.freedesktop.org/archives/systemd-devel/2014-April/018583.html
https://cgit.freedesktop.org/systemd/systemd/commit/?id=1640944a847249d3f5f0fb0d5a5f820a82efaed0
https://bugzilla.redhat.com/show_bug.cgi?id=663900

**Comment by lucasb-eyer** [comment]
I ran into this too, thanks a lot for this discussion and suggested workarounds.

I wanted to add that the arch wiki contains a slightly more general [workaround](https://wiki.archlinux.org/index.php/Fish#.2Fetc.2Fprofile_and_.7E.2F.profile_compatibility) which includes all environment variables set by /etc/profile in other shells by suggesting this line in the `config.fish`:

```
env -i HOME=$HOME dash -l -c printenv | sed -e '/PWD/d; /PATH/s/:/ /g;s/=/ /;s/^/set -x /' | source
```
