### ISSUE TITLE
Source user's config.fish before running conf.d snippets.

### ISSUE THREAD

**Issue by ghost** [fish-shell/fish-shell#3099]
The current implementation sources conf.d snippets before config.fish. I didn't notice this until @daenney pointed it out to me.

I think the config.fish should be the user's entry point, the very first thing that I have control over that runs before anything else.

For example, if a snippet depends on an env var I am setting in my config.fish, it won't be available as a result of the current execution order.

**Comment by faho** [comment]
So, the thing is, if you source conf.d after config.fish, that means that

- Snippets can depend on config.fish

- config.fish can't override snippets

If you do it the other way around, those two are going to be switched - config.fish can depend on snippets _and_ override them, but snippets can't use config.fish stuff.

The tough question here is: What is less painful? What occurs more often? That snippets depend on config.fish, or that someone wishes to override snippets? It seems no matter which you pick there'll be some weirdness.

Then there's the issue that changing this would essentially require doing the snippets stuff in C++, since we don't have any script to hook it into (currently all stuff related to this is nicely encapsulated in share/config.fish).

So: What was your original issue with this? How'd you try to use it?

**Comment by brj** [comment]
> What is less painful?

The current situation is arguably more painful, only because it makes it impossible or very hard to have a unique entry point to configure some stuff. 

Making your config.fish depend on snippets sounds like a terrible idea, and snippets should not be considered this entry point, because there you can't guarantee the execution order in snippets.

**Comment by gretel** [comment]
i never really liked the idea of having a `config.fish` at all. how about
* get rid of `config.fish` as a requirement
* move it to `conf.d`
* change logic so `conf.d/config.fish` will be loaded first
** if it exists
*** which is debatable because it'd be another exception, so i'd could be named `00_config.fish`

**Comment by brj** [comment]
@gretel That's not bad, but it's more disruptive to change a behavior that has been the norm nearly since fish's inception (probably) than to tweak the execution order of snippets, which is a new feature in 2.3.

**Comment by faho** [comment]
>get rid of config.fish as a requirement

There is no config.fish requirement. You can move it over to conf.d if you so desire. I've just done so and it works.

>The current situation is arguably more painful, only because it makes it impossible or very hard to have a unique entry point to configure some stuff. 

No matter which order you pick, there is no "unique entry point". Either you configure something in config.fish and you don't see it because a snippet sets it (this would happen if config.fish before snippets, i.e. if we made this change), or you configure something in config.fish and a snippet can't use it (which is what happens now).

I'm quite wary of making it harder to override something a snippet does, because they can come from a variety of sources and might do something the user doesn't want - e.g. I could get a new snippet when I update some system package.

The only other thing I can come up with is making a "load-snippets" function that users can put into their ~/.config/fish/config.fish, and ship one that includes it by default.

**Comment by gretel** [comment]
@brj sure. but do rather popose solutions than backwards compatible changes 😸

**Comment by brj** [comment]
> I'm quite wary of making it harder to override something a snippet does

Hmm, I agree with this.

> The only other thing I can come up with is making a "load-snippets" function that users can put into their ~/.config/fish/config.fish, and ship one that includes it by default.

Let's not do this please. 

I think plugins will have to agree to the idea they can't see what the user has in its config.fish and be more conservative about the kind of functionality they provide.

Let's wait to hear @daenney's experience on this and what other people think.

**Comment by daenney** [comment]
I've currently worked around it by having a `conf.d/000-env` instead that does all the stuff I want to set up in my environment. It gets executed first and everything works. I think that as long as there's a good and documented way for people to achieve ordering of `conf.d` entries I would actually be pretty happy to get rid of `config.fish` entirely. It also makes splitting up, modularising and having your configuration in VCS easier.

My current confusion stems from the fact that most shells have no concept of these kinds of snippets. As a consequence any behaviour like this basically comes down to sourcing the files in your `.bashrc` etc, allowing you to control order and avoiding surprises like this.

**Comment by faho** [comment]
>I think that as long as there's a good and documented way for people to achieve ordering of conf.d entries

That we can do. Do you have any wording suggestions? This uses the same sort function our completions use, which is a "natural" sort - so "1" < "2" < "2_b" < "02" < "3".

**Comment by gretel** [comment]
@faho hum.. good question. natural sort seems fine but for something automatic it is less determinable. going to have a read on https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/

**Comment by daenney** [comment]
I'm not entirely sure what ordering to go for. The trick is mostly to figure out what makes most sense when people are trying to debug why things aren't loading in the right order. When that happens I would actually prefer the order in which we process them to be more identical to what an `ls -l` or `find . -type f` would give me on that directory as that would make it more obvious in which order things happen and I wouldn't have to do the conversion between different sort orders myself.

**Comment by daenney** [comment]
With regards to the ordering of `conf.d` first and then `config.fish` I think @faho is right and that order needs to be kept as is.

If we think about Fisherman plugins for example, they all get neatly loaded through `conf.d` snippets. However, if `config.fish` would get loaded first a plugin could override user defined behaviour and we'd take away the power of the user to fix that. With `config.fish` being loaded last it can essentially function as a user's override file, without needing some explicit other mechanism to do so. It's only counter-intuitive because everyone's used to `.bashrc` and `.zshrc` and so on being the entrypoint for all configuration in the shell but the reason I use fish is because it does things in slightly different but smarter ways.

**Comment by brj** [comment]
@daenney I can't agree more now.

**Comment by faho** [comment]
>When that happens I would personally prefer the order in which we process them to be more identical to what an ls -l or find . -type f would give me on that directory

It's the same order as globs (because that's where the sorting happens).

Anyway, does anyone have any idea what the documentation should say? I'm struggling to come up with anything.

**Comment by daenney** [comment]
Perhaps something like:

> The order by which snippets in `conf.d` get evaluated is based on the file name of said snippet using X sort order. This means that in order to set environment variables or other configuration that snippets might depend on you need to ensure it gets executed as early as possible. You can achieve this by using a filename along the lines of `0-env.fish` as that will guarantee it is evaluated first.

We should probably add an example or two about how the sort order works and how to fix things that aren't getting evaluated in the order the user expected.

**Comment by krader1961** [comment]
> In most other shells the equivalent of config.fish would be the entrypoint where we start evaluating configuration. 

That is not true for any shell I've used in the past three decades. Certainly not sh, ksh, zsh, bash. From the bash man page:

> When  bash  is invoked as an interactive login shell, or as a non-interactive shell with the --login option, it  first  reads  and  executes commands  from  the  file /etc/profile,  if  that  file  exists.   After  reading that  file,  it  looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads  and  exe- cutes  commands  from  the  first one that exists and is readable.  The --noprofile option may be used when the shell is started to inhibit this behavior.

**Comment by therealpxc** [comment]
@ghost On operating systems where Fish can't get by by just guessing what ought to be on the path in case it is empty, we're not talking about restricting plugin functionality just a little bit— we're talking about restricting plugins to the point that they can never call external programs. This will affect all operating systems where the OS needs to be able to set the PATH variable (or any other) before programs can find each other. That seems to me to defeat the purpose of even having an OS-level configuration file.

If you go through with this plan, the only way to make fish plugins which dare to use even `hostname` or `find` work correctly on NixOS will be by patching $prefix/share/config.fish in the Fish source. And the thing is that it doesn't just break the plugins. The breakage can propagate to the whole shell, affecting login at every virtual console and preventing the display server from launching if the display manager service inherits its environment from the login shell.

**Comment by ranisalt** [comment]
Why not letting user have
```for snippet in conf.d/*
    source $snippet
end
```
?

**Comment by hg42** [comment]
(I'm in the process to switch from zsh to fish and I am still unsure if it would fulfill all my needs.
I understand, that some things are possible but I need to use different solutions.)

@ranisalt that's what I thought 

A top level script that sources the (kind of) plugin scripts is very usual, e.g. see Debian Linux /etc/sudoers or /etc/profile.
The advantage is to have full control:
* a common entry point (bash etc. usually use different files for different situations, but you can implement these as links to a single file, at least zsh can be configured to reduce the number of files, fish already uses one file).
* control before the plugins (usually setting some variables necessary for the loop)
* control after the plugins (e.g. to cleanup after the loop)
* control inside the loop (e.g. tracing, script headers, you can source some files and execute others depending on the name)
* control of the loop sequence (e.g. you could have two loops one executes plugins from a framework and the other executes user scripts)
* if someone defines such behaviors, a change in the default behavior doesn't effect his installation, however he can import the new behavior

A missing config.fish should probably be replaced internally by a default script.

Note, it should already be possible to do something like this. I think you can create a different directory like user-conf.d/ instead of the standard conf.d/ and source it in config.fish. However, I don't know, if it is possible to prevent sourcing conf.d/ which could be created and used by a config framework or something.

Debian /etc/profile
```
% cat /etc/profile 
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ "`id -u`" -eq 0 ]; then
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
else
  PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
fi
export PATH

if [ "${PS1-}" ]; then
  if [ "${BASH-}" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "`id -u`" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
```

I usually output a header for each script in a login shell, because I output some info there
```
...
-- zshrc/mod-cap
-- zshrc/mod-stat
-- zshrc/mod-zprof
bindkey "^X^R" _read_comp
bindkey "^X?" _complete_debug
...
-- zshrc/set-beep-time
-- zshrc/set-cvs-options
-- zshrc/set-editor-e
...
```

my .zshenv
```
% cat .zshenv 
#!/bin/zsh

#set -x

typeset -A   zsh_loaded
typeset -A   zsh_log
typeset -agx zsh_stack
typeset -gx  zsh_level


##### config

zsh_log_file=~/log/zsh.log

# DISABLE ONLY FOR TESTING
#zsh_loaded[zshenv]=1
#zsh_loaded[zprofile]=1
#zsh_loaded[zshrc]=1
#zsh_loaded[zlogin]=1

#zsh_log[zshenv]=yes
#zsh_log[zprofile]=yes
#zsh_log[zshrc]=yes
#zsh_log[zlogin]=yes

if [[ $- == *i* ]]; then
  zsh_log[zshenv]=yes
  zsh_log[zprofile]=yes
  zsh_log[zshrc]=yes
  zsh_log[zlogin]=yes
fi

##### config.

zsh_level=${zsh_level:-1}
zsh_stack[$zsh_level]+=( ${ZSH_ARGZERO##*/} )
zsh_level=$((zsh_level+1))

if ! functions zsh_load >&/dev/null; then

  function zlog()
    {
    if [[ -n $zsh_log[$zsh_section] ]]; then
      echo "$*"
      echo "$*" >> $zsh_log_file
    fi
    }

  function zlog_each()
    {
    zsh_loaded[$zsh_section]=$zsh_file
    zlog "-- ${zsh_loaded[$zsh_section]#$HOME/.zsh/}"
    if [[ $- == *i* ]]; then
      #zlog "$(cat $zsh_loaded[$zsh_section])\n"
    fi
    }

  function zsh_load()
    {
    if [[ -z $zsh_loaded[$zsh_section] ]]; then

      zlog "========== S$SHLVL Z$ZSH_SUBSHELL z$zsh_level $zsh_stack $zsh_section"

      for zsh_file in ~/.zsh/$zsh_section/*(N^/) ~/.zsh/$zsh_section/${OSTYPE%-*}/*(N^/); do
        zlog_each
        source $zsh_file
      done
      unset zsh_file
      zsh_loaded[$zsh_section]=ok

      #zlog "\n---------- set:\n$(set)"
    fi
    }

fi

zsh_section=zshenv

zlog "\n\n\n$(date +%F-%T) ------------------------------------------------------------ zshenv\n"

zsh_load
```
