### ISSUE TITLE
`history --delete` (fish script, not builtin) is broken by entries with newlines

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#31]
Run this:

    foo\
    bar

Then this:

    history --delete --prefix foo

You get two items foo\ and bar; there should only be one.

**Comment by krader1961** [comment]
The following comment is from issue #3224 that I opened because I didn't find this issue when I did a superficial search.

The history --delete command is broken. If your history contains multiline commands each line is listed as an individual entry you can select for deletion. That's obviously bogus. It might be possible to fix that. However, I'm wondering if it wouldn't make more sense to simply change the UI to eliminate selecting individual entries for deletion. Just give the user the choice of deleting all or none of the matching entries.

Also, including the recently introduced -t or --with-time flag produces output that makes selecting an individual entry for deletion impossible. Yet another reason to remove that capability.

I noticed this while working on issue #3224.

**Comment by floam** [comment]
Moved from #3237:

>However, I'm wondering if it wouldn't make more sense to simply change the UI to eliminate selecting individual entries for deletion.

I like killing the interactive prompt, but: I think it's important to be able to easily delete just one of those entries one saw. It can be hard to copy and paste the command you want to delete - or impossible to narrow your query.

So we are having them choose one by number. We need to engage the user in that prompt, though, post-search, because they are referencing a match index on that search and those numbers are not IDs that could be used later with a `history -d -i 344" or something.

So how about we just use persistent identifiers? I think if we base36'd the timestamp (1168557245 -> jbq8jh) and showed the history items with a little tag before/after them like a git hash, [jbq8jh] it could always resolve back that same entry. It'd be an upgrade, and not require the interactive crap.

Or, get the same form a hashing function on the string itself since one second precision isn't quite good enough.

What's nice is you can see the history output in a terminal from last week and that id number can still be used to refer to a given history item, and as our history isn't sorted nothing can suggest an order.

**Comment by c22** [comment]
Running into this same bug when a command is in a begin/end block spanning multiple lines. I would expect slightly different behaviour to what @ridiculousfish talks about in the original report.

for example, if my history contains
```
begin
echo hello
echo world
end
```

history --prefix echo should return no results (as it does currently)
history --prefix begin should return (as it does currently)
```
begin
echo hello
echo world
end
```
(although it would possibly be even nicer if it indented output in the same way writing "begin[return]" at the interactive prompt does)

history --prefix begin --delete should allow me to delete the entire block (it currently does not)

history --contains echo --delete should also allow me to delete the entire block (it currently does not)

I don't think it would be consistent if "history --contains echo --delete" deleted only the lines in the block that contained echo, because then in the example above you'd be left with
```
begin
end
```
in your history and it wouldn't make sense.

**Comment by krader1961** [comment]
It seems like the only sensible solution is adding another flag to request that the `history search` output have newlines converted to `\n` and backslashes escaped (i.e., `\` -> `\\`). Similar to, if not identical to, running each history item through `string escape --no-quoted` before writing it to stdout. The caller can then easily and safely unescape the search output back to its original form for display and other processing. Even if `--with-time` or `-t` was also used.

It is unlikely this will be implemented in time for the 2.4.0 release but I'm going to focus on fixing this any way. Fixing this will make a nice finale to the other history improvements that have been made in the past couple of months.

**Comment by faho** [comment]
@krader1961: Wouldn't using \0 as the separator work as well? That way you could loop through history entries with `while read -z`. At least I believe that char can't occur in the history.

**Comment by krader1961** [comment]
> Wouldn't using \0 as the separator work as well?

Yes. I was worried about potentially having an embedded NUL in the history but that's impossible today and we should prohibit it in the future if we ever switch from "char *" style strings to C++ string objects in all the history code paths.
