### ISSUE TITLE
A more complex keyboard-interrupt issue

### ISSUE THREAD

**Issue by bzaborow** [fish-shell/fish-shell#3104]
I've run into a similar issue to the #13. Apparently, when the command executed in a loop performs some (nonstandard?) signal handling by itself, in my case a Python interpreter, the loop is non-interruptible from keyboard.

### Reproduction Steps:

1. Run this loop:
`while true; python -c "import time;print('hi');time.sleep(1)"; end`
2. hit ctrl+c a few times, or even press and hold it for a while

### Expected behavior:

The child command is interrupted and the loop exits.

### Observed behavior:

The child command is interrupted correctly, but the loop never exits.

### Additional information:

The same problem exists in other shells (at least bash and zsh).

---
Fish version: 2.2.0; 2.0.0

Operating system: Fedora; Ubuntu

Terminal or terminal emulator: urxvt

**Comment by krader1961** [comment]
> The same problem exists in other shells (at least bash and zsh).

Yes, that's how every shell I've ever used (going back to at least ksh93; that is, a shell from 1993) handles this situation.

Fish could examine the exit status of the external command and determine if it terminated due to receipt of a signal and use that information to decide to terminate a loop that was invoking the command. However, doing so causes problems. What if you have a script that is executing a program in a loop and explicitly checking its exit status? This also doesn't help if the program explicitly catches the interrupt signal and terminates by calling `exit()` (or related functions) since that makes it impossible for fish to know the external command was terminated by a signal.

I'm a grey beard who has been annoyed by this, and dealt with customers annoyed by this, behavior for three decades. I don't think there is any reasonable solution fish can employ that isn't worse than the problem. But I'm going to leave this open for a few days to see if anyone has any bright ideas.

**Comment by jakwings** [comment]
I guess the signal is caught by python and not received by the shell. If I send SIGINT to the shell with `kill`, the loop will break. In zsh and fish, I can just press <kbd>Ctrl</kbd>-<kbd>\\</kbd> to send SIGQUIT to terminate python and break the loop, but this method does not work well in bash.

The last resort is to keep holding <kbd>Ctrl</kbd>-<kbd>C</kbd> until the shell receives the signal and breaks the loop.

**Comment by krader1961** [comment]
> I guess the signal is caught by python and not received by the shell.

Yes, by definition the current foreground process receives the signal. Which in the examples given by the O.P. and yourself is not fish. That's by design so that the foreground process, a command external to the shell, can handle the signal. That allows the program to perform appropriate cleanup of temporary resources, for example, before exiting.

The correct way for the shell that spawned the external program to deal with this is to look at the exit status of that program and take an appropriate action. This is traditionally the responsibility of the person writing the shell script. I am not aware of any practical manner (given how UNIX ttys and process groups work) for a shell like fish to magically know the external command terminated as a result of a tty interrupt character.

Too, even if fish could somehow detect that situation what should it do if the process died due to some other signal such as SIGTERM or SIGSEGV?

**Comment by jakwings** [comment]
Good to know. Maybe the terminal (not the shell) can provide an easy way to send SIGINT to the shell without the users manually calling `kill -INT`? I too cannot imagine the shell handling this on its own.

**Comment by krader1961** [comment]
Fish already handles child processes that die due to SIGINT (\cC) or SIGQUIT (\c\\) and will break out of the loop. See the `handle_child_status()` function in *proc.cpp*. The reason your example doesn't behave that way is because python by default translates SIGINT into the KeyboardInterrupt exception. Which, if you don't catch it, terminates the program with an exit status of one. So as far as fish is concerned the python process was not killed by a signal. If you instead do `while true; sleep 10; end` and interrupt the sleep you'll see the behavior you want and `$status` will be 130 (128 + the signal number).
