### ISSUE TITLE
Accessing the last element in the completion menu should be possible by just using arrow-up

### ISSUE THREAD

**Issue by mineo** [fish-shell/fish-shell#3115]
### Reproduction Steps:
1. `git format-patch --<tab><tab><tab>`
### Expected behavior:

Accessing `--textconv` should be possible by just pressing arrow-up once.
### Observed behavior:

Trying to access `--textconv` requires me to either press arrow-down a lot of times or narrow the list down manually by typing parts of the command.
### Additional information:

Going back to the first suggested option by pressing arrow-down on the last one works.

---

Fish version: 2.3.0

**Comment by faho** [comment]
The behavior here is rather inconsistent - left/right wraps around, down also basically does (though the ordering is different than one would expect), but up in the first column doesn't because it moves back into the commandline. Which might be useful since it allows you to continue entering text, skipping the pager's search, but pressing up again does nothing.

I'd either have it wrap around directly, without moving into the commandline - this requires the user to press escape (i.e. execute "cancel"). Or I'd have it move into the commandline and then the next up wraps.
