### ISSUE TITLE
Get the current directory 

### ISSUE THREAD

**Issue by alexxsun** [fish-shell/fish-shell#3148]
Hi, when I set JAVA environment in the fish, I need to set the JAVA_HOME, CLASSPATH,  PATH, etc.
Like that:

    # Java env  
    set -x JAVA_HOME /usr/java/jdk1.8.0_91  
    set -x CLASSPATH . $JAVA_HOME/lib.tools.jar  
    set -x PATH $JAVA_HOME/bin $PATH

The problem is in the CLASSPATH,
how can I get the current directory in the fish? (Just like the . (dot ) in the bash )

I have tried $PWD, but it does not work.

Thanks.

---
Fish version: fish, version 2.2.0

Operating system: Linux Arch 4.5.4-1-ARCH x86_64 GNU/Linux, get fish from pacman -S fish

Terminal or terminal emulator: xfce4-terminal

**Comment by krader1961** [comment]
The problem is that only PATH is automatically converted to and from it's external format as a colon separated set of value to a fish array. At this time you need to treat CLASSPATH in the same way you would do so in bash. For example,

```
set -x CLASSPATH ".:$JAVA_HOME/lib.tools.jar"
```

See the "Arrays" section of http://fishshell.com/docs/current/index.html
