### ISSUE TITLE
Killing fish-shell does not terminate child processes

### ISSUE THREAD

**Issue by raphael-costa** [fish-shell/fish-shell#3155]
Killing a fish process does not terminate its child processes, possibly turning them into CPU-hogging zombies.

#### Harmless case:
1. Open a terminal
2. Type emacs, or any other graphical application
3. Close the terminal

#### Harmful case:
1. Open a terminal.
2. Type ranger, wifi-menu, deluge-console or another ncurses application.
3. Close the terminal

#### Harmless case
The emacs graphical window would close.

#### Harmful case
The ncurses application would be killed

#### Harmless case
Emacs is still open.

#### Harmful case
The application is now a CPU-hogging zombie

### Additional information:

Not killing the process is a nice feature of Fish. In bash we would need to wrap the command with nohup to leave graphical applications open, or in zsh we could disown it but Fish leaves the application open regardless.

But this problem is critical if you're using your terminal to launch TUI applications, I'm constantly opening htop in my machine because I always end up killing that terminal instead of properly ending the process first. 

####  When did this problem start?
Unfortunately  I always thought it was a bug with ranger or my configuration but it's happening for at least 3 months.

####  Does this happen all the time?
Always, tested by changing root shell to fish and using su. Also tested launching "urxvt -e bash" and the application was closed properly.

####  Has anything changed on your system recently?
Nothing.  

#### Fish version: [from the output of fish --version]
fish, version 2.3.0-233-g7ef40f4. However the problem also occurs with stable version.

#### Operating system: [your operating system and how you installed fish e.g. Homebrew, Ubuntu PPA, distribution package]
Arch Linux, compiled master from AUR. However the problem also occurs with stable version.

#### Terminal or terminal emulator: [e.g. PuTTy, iTerm2, GNOME Terminal, VT220]
Tested with urxvt and Konsole. Konsole asks me to kill fish if I try to close it.

**Comment by krader1961** [comment]
I can't reproduce on OS X (using a variety of ncurses based programs) or Ubuntu (using ranger). When you close the terminal the kernel should send a SIGHUP to the foreground process group. I'd be interested in the output of `grep Sig /proc/$pid/task/$pid/status` where $pid is the pid of the process that should be dying. Do that for the parent fish shell as well. For example,

```
$ ps -ef | grep ranger
krader    49180  49121  6 13:38 pts/0    00:00:00 /usr/bin/python -O /usr/bin/ranger
krader    49215  47304  0 13:38 pts/1    00:00:00 grep -P ranger
$ grep Sig /proc/49180/task/49180/status
SigQ:	0/3764
SigPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000001001000
SigCgt:	0000000188084002
$ grep Sig /proc/49121/task/49121/status
SigQ:	0/3764
SigPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000380004
SigCgt:	0000000188015013
```

**Comment by raphael-costa** [comment]
```
$ ps -ef | grep ranger
raphael   7127  7103  4 21:39 pts/2    00:00:00 /usr/bin/python -O /usr/bin/ranger
raphael   7245  7085  0 21:39 pts/1    00:00:00 grep --color=auto ranger
$ grep Sig /proc/7127/task/7127/status
SigQ:	1/9969
SigPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000001001000
SigCgt:	0000000188084002
$ grep Sig /proc/7103/task/7103/status
SigQ:	1/9969
SigPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000380084
SigCgt:	0000000188015013
```
To be sure, I deleted my .config/{fish/ranger} and started a new terminal before doing this.

**Comment by floam** [comment]
Hm. I've noticed this happen off and on for a couple months on OS X: I'll notice my fans have kicked in and I had a fish process using a bunch of CPU - with no terminals open or none of them being that fish.

I made a sample the last time it happened but haven't looked further into it or tried to debug it at all. It keeps happening at inopportune times when I need to be doing something else. No clue if related.

[Sample of fish.txt](https://github.com/fish-shell/fish-shell/files/322567/Sample.of.fish.txt)

**Comment by krader1961** [comment]
@raphael-costa Did you take that snapshot after or before you closed the terminal? Given the CPU time field of the ps output I'm guessing before. Before closing the terminal login from a different terminal and `strace -f /tmp/strace.txt -p 7127`. Then close the terminal in which `ranger` is running and repeat those commands. If the strace doesn't exit interrupt it with [ctrl-C].

**Comment by krader1961** [comment]
@floam Your trace shows fish writing the prompt (the s_write calls) and reading input from the tty (the input_readch calls).

**Comment by raphael-costa** [comment]
I apologize but it seems I must made a mistake when I tried to clean my installation earlier. I'm trying to reproduce the problem again and I'm unable to, I traced the culprit down to omf/theme-budspencer. Using theme-budspencer the applications don't close when I close fish, but without theme-budspencer, the applications close properly, this is due to budspencer, despite being just a theme, using some weird pre-exec  and fish termination code in an attempt to handle "sessions". The problem also disappears if I remove said piece of code from my configuration.

In the OP I said "not closing applications is nice feature of fish", can someone please confirm that this is not a feature? I have been using budspencer for a long time so I guess I mixed the two systems.

However, not to come home empty-handed, it seems closing a terminal with a man page open inside causes `fish` to remain open and turns `man` into a zombie. This seems related so I'll continue here.

I found this bug when I read `man strace` since @krader1961's command wasn't working.

## Reproduction steps
1. Open a terminal.
2. Run `man fish`
3. Close the terminal.
4. Confirm zombification using `top`

**Comment by krader1961** [comment]
@raphael-costa I can't reproduce any problem using the instructions in your latest comment on either OS X or Ubuntu. I know what a zombie process is (it's a dead process whose parent hasn't called `wait()`). I don't know what you mean by "zombification".

> In the OP I said "not closing applications is nice feature of fish", can someone please confirm that this is not a feature?

It is a feature of fish which is why it doesn't need commands like `disown`. However, if the command is running in the "foreground" then it will normally be killed by the OS by sending a SIGHUP to it if the terminal goes away.

**Comment by raphael-costa** [comment]
I apologize for using a joke-term such as "zombification" to refer to a process becoming a zombie and I'm afraid I'm more down below in the noob scale, after closing the terminal running `man fish` I opened the application `top` which outputs the following line:

`Tasks: 110 total,   1 running, 108 sleeping,   0 stopped,   1 zombie`

**Comment by krader1961** [comment]
The question is what is that "1 zombie" process. More specifically, what is its parent process? And what is that parent process doing that is keeping it from reaping its child process (i.e., calling `wait()`)? Note that a zombie process, by definition, cannot consume any CPU cycles because it is dead. So when you say "CPU-hogging zombies" that is an oxymoron. It is, however, possible that the parent process is "CPU-hogging" by repeatedly doing something useless rather than reaping its zombie child process.

I'm guessing that the top-level shell in which you're running commands like `ranger` is spinning (i.e., hogging the CPU) when you close the terminal. Which leaves the `ranger` process as a zombie. Running `strace` against that parent fish shell would help us understand why it isn't reaping its child process and exiting.

**Comment by raphael-costa** [comment]
Yes, calling ranger a zombie process in the initial post was a mistake I rectified when filing the bug to oh-my-fish/theme-budspencer. The bug I initially pointed could be tagged as "Not A Bug" since it's not a problem with stock fish-shell, however the currently issue I'm facing with `man` is in fact what the title says, if you wish I could post it as another bug.

When closing a terminal running `man $program`, `fish` is still running and `man` becomes de-facto a zombie, consuming 0 CPU cycles and becoming unkillable except by killing the parent process `fish`. This is mostly harmless, the extra `fish` will consume the usual RAM and you'll have a zombie process.

**Comment by krader1961** [comment]
No need to open a new issue. I cannot reproduce your most recent problem description. The reason that killing the parent fish process eliminates the zombie is that the Linux kernel re-parents orphaned process to pid 1 which reaps them (i.e., calls `wait()`). What we are interested in figuring out is what the fish process is doing that keeps it from reaping its dead child process.

There are several ways to gain more insight into this behavior. Including using the strace command and using `fish -d5 2>/tmp/fish.dbg` before running the `man` command and killing the terminal.

**Comment by tannhuber** [comment]
@raphael-costa referenced this by
https://github.com/oh-my-fish/theme-budspencer/issues/33. Can anybody explain why the ranger process doesn't terminate in the minimal example written in the second post there? I expected, fish would just execute an empty function on termination.

**Comment by faho** [comment]
@tannhuber, @raphael-costa: I can't even reproduce this with the budspencer theme (though it does unconditionally set the bind mode to insert, which effectively unbinds everything for me since I don't use vi-mode - you might want to look into that).

What I'd like to know from you is your budspencer configuration. All those variables in there, what are they set to? With those we might get what it's actually doing.

**Comment by tannhuber** [comment]
@faho Thanks for looking into it. I just tried the latest fish version 2.3.0-316-gd7bc20c in order to check whether I've missed an important development step. I still have this ranger issue. And it's reproducable with or without budspencer theme. Hence, I can say it's not the theme. The source must be somewhere else. I thought the definition of a function
```
function ontermination -s HUP -s INT -s QUIT -s TERM --on-process %self
end
```
wouldn't change anything. But obviously things are different if I then close a terminal window with a running ranger process. What would you expect?

off-topic: You're right. Budspencer needs vi-mode, now. Emacs mode was supported in the early days. But there're too many vi specific features. I couldn't translate them all for emacs mode. There're prompt themes with less than 4000 lines of code.

**Comment by krader1961** [comment]
@tannhuber and @raphael-costa: Don't do that. Since you're not doing anything on receipt of a signal that would normally terminate shell the shell is left running; quite possibly spinning and chewing up CPU time. The only reason I'm going to leave this open is there may be a bug in the tty input layer that doesn't correctly handle EOF when reading from the tty. I can't reproduce on OS X but is conceivably broken on your OS.

**Comment by raphael-costa** [comment]
@faho budspencer depends on vi-mode

**Comment by floam** [comment]
Does this still happen for you now?

**Comment by raphael-costa** [comment]
It does.

**Comment by krader1961** [comment]
@tannhuber and @raphael-costa: I earlier told you (on June 27) to not define functions such as

```
function ontermination -s HUP -s INT -s QUIT -s TERM --on-process %self
end
```

Since doing so is pretty much guaranteed to produce the behavior you're describing. Does the problem still occur if you don't define that function? Can you explain why that function is needed?

**Comment by raphael-costa** [comment]
I'm afraid I stopped using this theme due to constant problems caused by the bloated code. If @tannhuber does not want to continue I believe this can be closed, since this is clearly a programming issue.

**Comment by Ambrevar** [comment]
Same problem here on Arch Linux, fish 2.3.1: I have a function `ranger-cd` for syncing ranger and fish:

``` fish
function ranger-cd -d 'Run ranger and sync folders with shell'
	[ (count $argv) -eq 0 ]; and set argv .
	set -l tempfile (mktemp)
	command ranger --choosedir="$tempfile" $argv
	if grep -q . "$tempfile" ^ /dev/null
		set -l dest (cat -- "$tempfile")
		[ "$dest" != "$PWD" ]; and cd $dest; and commandline -f repaint
	end
	rm -f -- "$tempfile"
end
```

Running `ranger-cd`  and closing the terminal will (almost always) reparent ranger to PID1 and make it a CPU hog.

I noticed that if I make the function shorter:

``` fish
function ranger-cd -d 'Run ranger and sync folders with shell'
	[ (count $argv) -eq 0 ]; and set argv .
	set -l tempfile (mktemp)
	command ranger --choosedir="$tempfile" $argv
end
```

This almost never happens. Adding a few `echo`s is enough to trigger the issue back again:


``` fish
function ranger-cd -d 'Run ranger and sync folders with shell'
	[ (count $argv) -eq 0 ]; and set argv .
	set -l tempfile (mktemp)
	command ranger --choosedir="$tempfile" $argv
	echo
	echo
	echo
end
```

I guess there is a race condition on termination somewhere. Can anybody shed some light on this?

**Comment by Ambrevar** [comment]
It might be related to #1362 somehow...

**Comment by ridiculousfish** [comment]
The ranger issues are being investigated in #3644. So far it looks like a combination of glibc and ranger bugs.
