### ISSUE TITLE
\cy should not be bound to `fish_clipboard_copy` by default

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#3160]
*(See Gitter discussion for context: https://gitter.im/fish-shell/fish-shell?at=5767c6febd67400679db2fa8)*

To summarise: https://github.com/fish-shell/fish-shell/pull/3061 sets `\cy` to `fish_clipboard_copy` which is the opposite of what most (bash) users will be familiar with, i.e. from http://web.mit.edu/gnu/doc/html/features_7.html#SEC46 :
```
C-y    Yank the most recently killed text back into the buffer at the cursor.
```

Ping @faho - thoughts on binding this to `yank` by default and choosing something else for `fish_clipboard_copy`?

**Comment by faho** [comment]
This comes from the clipboard changes. The idea was to decouple our killring from the external (e.g. X11) clipboard, so not every change ends up overwriting that.

Now, where I went wrong is that I thought "yank" meant "yank from the buffer into the killring", where it's the other way around - doubly embarassing as an emacs user. So \cy should remain bound to yank, considering it's the opposite of this operation.

Is there any standard for where something like this should be bound? The CUA binding - \cc - won't work for obvious reasons. How about \cx?

**Comment by zx8** [comment]
`\cx` seems more sensible to me.

I don't know if there's a standard, but I personally associate `ctrl+x` with `cut` (outside of the Terminal) or as a leader key (in bash), which I don't expect many people actively used anyway (correct me if I'm wrong):

```
bash-4.3$ bind -P | grep '\\C-x'
abort can be found on "\C-g", "\C-x\C-g", "\e\C-g".
backward-kill-line can be found on "\C-x\C-?".
call-last-kbd-macro can be found on "\C-xe".
display-shell-version can be found on "\C-x\C-v".
do-lowercase-version can be found on "\C-xA", "\C-xB", "\C-xC", "\C-xD", "\C-xE", ...
edit-and-execute-command can be found on "\C-x\C-e".
end-kbd-macro can be found on "\C-x)".
exchange-point-and-mark can be found on "\C-x\C-x".
glob-expand-word can be found on "\C-x*".
glob-list-expansions can be found on "\C-xg".
possible-command-completions can be found on "\C-x!".
possible-filename-completions can be found on "\C-x/".
possible-hostname-completions can be found on "\C-x@".
possible-username-completions can be found on "\C-x~".
possible-variable-completions can be found on "\C-x$".
re-read-init-file can be found on "\C-x\C-r".
start-kbd-macro can be found on "\C-x(".
undo can be found on "\C-x\C-u", "\C-_".
```

**Comment by faho** [comment]
>I personally associate ctrl+x with cut (outside of the Terminal)

That's [CUA](https://en.wikipedia.org/wiki/IBM_Common_User_Access), an old IBM-ism that has become standard in GUIs. That's also where `ctrl+c` means copy.

>or as a leader key (in bash)

That's an emacs-ism - "C-x" in emacs is a common prefix, and "C-c" is defined to be the user's prefix (though plenty of modes also use it).

The combination I know some people use in bash is '\Cx\Ce' - "edit-and-execute-command".

I've also thought about using \Cx\Cc and \Cx\Cv for copying and pasting respectively (i.e. codify \Cx as a "leader" or "prefix" mapping), but it seems fish will still execute the \cc binding.

Since the CUA-binding is at least related (I don't think we'd want to clear the commandline here), let's pick \cx for the time being. If we ever really want to bind moar stuff, let's think about putting it all under \cx then.

(Since the clipboard stuff isn't in 2.3.0, there's no need to merge it in 2.3.1)
