### ISSUE TITLE
Wildcard args replacement

### ISSUE THREAD

**Issue by Mathiasb17** [fish-shell/fish-shell#3169]
I recently switched from zsh to fish, and a feature that i am really missing is the replacement of arguments when these are wildcards. For example in zsh assume a directory with many files with different extensions (.xml, .bin, etc.) :

I want to apply the same command on all xml files except one. What i will do is typing :

`command *.xml`

Pressing tab, the only argument will be replaced by as many arguments as there are xml files in the current directory, for example :

`command foo1.xml foo2.xml foo3.xml` 

Now it is really easy to apply 'command' on every xml file except foo3.xml, pressing ctrl+w.

If the argument was simply *, there would be every file and directory in argument displayed.

**Comment by faho** [comment]
I've offered a function to do this in #1831. I'm not sure we should add this by default, though all solutions I can come up with are either more dangerous than you might assume (i.e. will also run command substitutions) or _really_ hacky.

To save you some clicking, here's the simple expand-everything version:

```fish
function expand_glob
    set -l tokens (eval string escape -- (commandline -ct))
    if set -q tokens[1]
        commandline -tr ""
        commandline -i -- "$tokens"
    end
end
```

and here's the hacky will-probably-only-expand-globs version:

```fish
function expand_glob
    # EVIL HACK: Escape globs manually, pass it to escape, and then "unescape" the globs again
    set -l tok (commandline -ct | string replace -a '*' '\*' | string replace -a '?' '\*' \
    | string escape | string replace -a '\\\\\*' '*' | string replace -a '\\\\\?' '?')
    set -l tokens
    eval set tokens "$tok"
    set -l tokens (string escape -- $tokens)
    if set -q tokens[1]
        commandline -tr ""
        commandline -i -- "$tokens"
    end
end
```

Bind either of these to a key of your choosing and then press it when you have the cursor on the token you wish to expand.

**Comment by krader1961** [comment]
I agree with @faho that the zsh [tab] behavior vis-a-vis globs should not be adopted by fish. I used fish for ~6 years before switching to fish and never noticed, let alone relied upon, that behavior. While it might be useful when the number of paths matching the glob is small it is otherwise a disaster from a UI perspective.

We could provide a way get that behavior via a function bound to a key such as @faho proposed but it's not obvious that should be a default binding.

**Comment by Mathiasb17** [comment]
Well i perfectly understand both of your point of views.

Thanks @faho for your solution, i guess i will manage to replace this bad habit of mine ;^)

**Comment by dlukes** [comment]
Thank you very much @faho for providing a workaround! Apologies for necroposting, but the amount of negative feeling towards this feature surprised me (@krader1961 called it "a disaster from a UI perspective"), so I just wanted to provide the perspective of someone who relied on it extensively in zsh.

I agree it would be very intrusive if globs were expanded automatically as you type, especially if they match a large number of files. But that's not how the feature works in zsh, you have to explicitly press Tab to trigger the expansion. I only do that when I know the number of matched files will be relatively small, and I either want to interactively remove a few of those from the list (as mentioned by OP), or check to make sure that the glob doesn't accidentally match something I didn't mean it to.

This type of safety net when running something like `rm *.log` is so nice that I was positively uneasy doing so in `fish`, until I found the workaround above :) As a shell which prides itself on giving interactive feedback to the user (and with reason!), I think it would be far from unreasonable for `fish` to support this out-of-the-box, either as part of Tab expansion, or if it turns out that there are cases where pressing Tab would be ambiguous about what to expand, then maybe with a different key binding (although Tab as the "omni-complete" key is probably most discoverable).

Fun fact -- the [Wikipedia entry for fish](https://en.wikipedia.org/wiki/Friendly_interactive_shell#Highlights) already thinks fish does this:

> Tab-completion is feature-rich, expanding file paths (with wildcards and brace expansion)

**Comment by dlukes** [comment]
(To prevent flooding the terminal with expanded matches, there could even be a check which would prompt the user for confirmation if there's a lot of them.)
