### ISSUE TITLE
Tab completion of a//b crashes

### ISSUE THREAD

**Issue by msteed** [fish-shell/fish-shell#3185]
Tab completion of a path containing consecutive `/` characters causes fish to crash.

### Reproduction Steps:

`$ a//b<TAB>`

### Expected behavior:

Fish tries to complete the path as if it were spelled `a/b`

### Observed behavior:

```
fish: src/wildcard.cpp:986: void wildcard_expander_t::expand_literal_intermediate_segment_with_fuzz(const wcstring&, DIR*, const wcstring&, const wchar_t*): Assertion `c->completion.substr(segment_start, segment_len) == wc_segment' failed.
fish: 'fish' terminated by signal SIGABRT (Abort)
```

### Additional information:

-

---
Fish version: `fish, version 2.3.0`

Operating system: Arch Linux, fish installed from the distribution package

Terminal or terminal emulator: `tmux` running inside `urxvt`

**Comment by ridiculousfish** [comment]
Yikes! Good find.

**Comment by llwu** [comment]
It's not in master, should probably be closed.

**Comment by llwu** [comment]
Check out my PR, should fix this.

**Comment by krader1961** [comment]
I can't reproduce on either OS X 10.11 or Ubuntu 16.04.

```
$ cd tmp
$ mkdir a a/b a/bb
$ a//b[tab]
```

There is obviously a bug since an `assert()` fired. But I'd be happier about merging the fix if I had a way to reproduce the problem.

**Comment by llwu** [comment]
Those directories don't trigger the problem. Try `bar/baz` (if that doesn't trigger then you probably have asserts off, but it seems fish ships with asserts to at least Gentoo and Arch).

The issue is an off-by-n error. Even with asserts off it'll affect the completion by replacing the wrong substring index.

**Comment by msteed** [comment]
Don't do the `mkdir`s and it may crash for you. On Linux I see the problem only if there is no exact match for the first directory in the path.

**Comment by llwu** [comment]
Ah yes, the above makes sense in the context of the code - it first calls expand() to look for direct completions, and if it doesn't find any, it calls expand_literal_intermediate_segment_with_fuzz() to look for fuzzy completions. In order to trigger the bug you need to trigger the fuzzy search.

**Comment by krader1961** [comment]
@llwu, That helped. If I do

```
$ cd ~/tmp
$ mkdir -p bar/baz
$ a//b[tab]
```

that triggers the failure. Note that AFAIK we never build with asserts disabled. It's not even necessary to have an ambiguous (i.e., non-prefix) match for the first directory. It also fails if you do

```
$ cd ~/tmp
$ mkdir -p abc/def
$ a//d[tab]
```

**Comment by krader1961** [comment]
Obviously `a//d` is ambiguous in my previous comment. I was simply clarifying that the failure doesn't require a non-prefix max, just a fuzzy match.

**Comment by llwu** [comment]
To clarify, the existing code patches over finds the completion "a//def" and goes to patch over the "a" with "abc". This hack counts backwards from the end to find the index to patch over, assuming one slash. To make the minimal amount of code change, I just decided to preprocess the input as soon as we create the expander, so that it benefits everything (for example, seeing a completion list full of things "a/b/c/d/blah" is more visually appealing than seeing a completion list full of "a//b//c//d/blah". And it allows making shady assumptions such as the one which caused this bug.

**Comment by ridiculousfish** [comment]
I fixed this by reworking the fuzzy completion logic so it's less tangled. Thanks for filing this!
