### ISSUE TITLE
Doxygen XML tags should be restored

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3197]
- [x] Did you do [a quick search?](/issues?utf8=✓&q=is:issue+user:fish-shell)
- [x] Try [with the latest](/fish-shell/fish-shell/releases/tag/2.3.1) fish version?

In April a number of our custom tags were replaced with a backslashed form:

https://github.com/fish-shell/fish-shell/commit/dcef1a55932db5ad4394eb6fbcb76d63d8ab520d
https://github.com/fish-shell/fish-shell/commit/5df8fab4637865cc895bc698410efedc765dfd8c

This is rather unpleasant and the commit messages seem to indicate it was only done to silence warnings that we don't understand but seemed to not be HTML tags or XML conforming to Doxygen's XML DTD

Curiously, on my system I am actually getting less warnings printed if I revert these, and it improves the readability of the code a lot.

**Comment by krader1961** [comment]
Running `make` should never produce any warning, let alone error, messages. I should be able to assume that any warning or error message indicates a real, or at least potential, problem. Projects should have clean `make` output; i.e., without errors or warnings. Such messages cause unnecessary anxiety and wasted time investigating whether there is a real problem.

Personally I'd like to see us ditch Doxygen for our documentation. As you noted on Gitter the *lexicon_filter* script is a nightmare.

**Comment by floam** [comment]
>Running make should never produce any warning, let alone error, messages. 

This PR fixes all warnings in master and appears to improve the generated HTML.

**Comment by floam** [comment]
> Projects should have clean make output

That's good to have, but it's possible to sacrifice too much or do it wrong. I'm not convinced the hack was the appropriate fix.

**Comment by krader1961** [comment]
> I'm not convinced the hack was the appropriate fix.

Thanks for the laugh. Fish's use of Doxygen for its non source code documentation is a hack as evidenced by the *lexicon_filter* script. I agree that the change in question was probably not the best fix. It was an expedient fix by the person who implemented this method for writing our documentation. I haven't (and won't) review your change because I think that such refinements are, on principal, a waste of time. The rules (i.e., syntax) for writing fish documentation today is not something we should change unless said change radically improves the situation.

**Comment by MarkGriffiths** [comment]
_Apologies... I seem to be incapable of short posts_

It's a shame no one thought to give me a heads up about this as I could have sorted it easily and probably spared unnecessary effort. I've only just picked up on it due to being buried in non-github code..

At my last pull request on 4th April (and on 2.3.0-release), nothing was producing an error - and I tested against Doxygen 1.8.7 and 'current' on OSX and Ubuntu before submitting the pull request to be sure of this.

Now I'm getting the following on make doc:

```shell
/Users/mark/Projects/OpenSource/fish-shell/doc.h:5633: warning: found </pre> tag without matching <pre>
/Users/mark/Projects/OpenSource/fish-shell/doc.h:5633: warning: unexpected command endhtmlonly
```

I'm also seeing a structural failure in commands.html at the end of the `string` command .

The error ``unexpected command endhtmlonly`` is a structural problem caused by a misplaced or swallowed Doxygen backslash command.

Ever since I updated the documentation a couple of years ago I've always been happy to support it - the `lexicon_filter` in particular, as I'm very aware the stream processing techniques it uses are opaque at best; it was the best way to move on the status quo at the time, keeping Makefile changes minimal, fixing a bunch of Doxygen and make warnings and removing some tackiness _(well, maybe making it more consistent)_, all while giving the docs, man pages and the now defunct comment-driven html/latex developer docs (that included all the standard docs) a much needed boost. 

Due to the way the various help files are concatenated before being fed to doxygen, the custom tags are important as they are completely ignored by doxygen when it initially reads the file, however backslashes are structurally significant. Doxygen then opens the `lexicon_filter` via a bidirectional stream and begins streaming the content through. Basic html tags are allowed through so that Doxygen can use them as markup.

Doxygen will only report an unknown tag error if a tag has fallen through the filter without being matched and transformed to an `@alias{command}` for some reason, and extra backslashes could well be imposing different structural boundaries.

It might look like something Gödel, McMahon and Turing might come up with as an April fool after an absinthe fuelled weekend of abstract cryptography, but sed is an ideal tool here and the filter has to do it's job without ever seeing the document's complete structure, both for the html help and so that nroff can handle the man page production.

Also, it's all done on the fly with only a single buffer to hold each output tag composition. If you look in lexicon.log after building, it should be a well ordered cascade of assembled content elements. Stream event programming is never pretty when portability is an issue. That said, I produced the 'Game of Thrones' enhanced ebooks for HarperCollins some years back - the cleanup/markup scripts I wrote to handle the first 4 books (~14" of bookshelf) with modern tools were pretty hairy...

Originally it took me several weeks of found time to get the balance right to have it handle the documentation's semantics correctly (after I had edited all the content to make it consistent, a trial by regex in itself). It's been pretty robust, only needing some tweaks in April to handle new content that broke with the tone and formatting rules at that point; namely the addition of `string`.

My guess is that `lexicon_filter` was never at fault, but creeping  inconsistencies in the help source content's markup that's causing the problem. Changing the filter has now put it into a suboptimal state that is likely to cause further issues.

When I did the update, the files in `doc_src` were all over the place but it was just incremental creep. I wrote the `formatting.md` document to try and help reduce the amount of creep by laying out some guidelines. I've been an advocate for getting stuck into a complete rework of the documentation since I wrote that…

- Get rid of Doxygen and the makefile mess. 
- Move doc_src to fish-flavoured markdown for easy editing…
  or something more structured like YAML to prevent creep ([like I do here](/MarkGriffiths/Shoal/blob/master/lib/help/§sync.yaml))? 
- Maybe integrating `help`, `fish_config` and how about adding a shell status dashboard?
- Responsive html help that colours example code with your current settings?
- Dynamic docs that adapt to your current cursor context - expanded completions?
- Docs in their own branch or repo, or somewhere else?
- Wiki-like functionality to decouple source and docs?
- Live function interactive debugging?
- Live content fixes between releases, for both html and man?
- Add new functions from libraries in the docs?
- Let 3rd parties add local docs with function packages?

But where to start?

Ironically, I had only ever meant to fix the fact that, at the time, Doxygen was rendering double dashes `--` as n-dashes `–`, which turned out to be non-trivial, but in doing so I could see what could be done, and probably got a little carried away.

I still feel it was worth it as the docs are one of fish's distinct always-useful features. It's held up pretty well since that update, but if the consistency of the source drifts, the docs quality will drift too.

**Comment by floam** [comment]
> /Users/mark/Projects/OpenSource/fish-shell/doc.h:5633: warning: found </pre> tag without matching <pre>
> /Users/mark/Projects/OpenSource/fish-shell/doc.h:5633: warning: unexpected command endhtmlonly

Indeed, that's what got me looking, and I found not only that the two commits that #3198 reverts appeared to not only be a bad idea but also was surprised that doing so made the warnings go away - odd considering that the goal of the commits was to fix warnings - but there are zero errors reported without the changes. 

@MarkGriffiths Is it wise to merge #3198? I may have done something stupid - I'd appreciate some informed feedback.

Did I do anything stupid? A third commit on the PR is the result of running  `doxygen -u`on the Doxyfiles mostly "just because" while I have been trying to quickly learn how this whole thing works, and I liked the looks of the diff after it updated the files. Compatibility with other folks' doxygen installs is something I am concerned about. Should any other changes to the documentation system be looked at for undoing?

**Comment by floam** [comment]
> Doxygen will only report an unknown tag error if a tag has fallen through the filter without being 
> matched and transformed to an @alias{command} for some reason, and extra backslashes could
>  well be imposing different structural boundaries.

This is good to know. 

One thing I have done while researching this issue is I updated to Doxygen HEAD this morning just to see what affect it might have. I found that the number of warnings increases for this PR. 

```
Parsing code for file doc.h...
Generating file documentation...
Generating page documentation...
Generating docs for page tutorial...
Generating docs for page design...
Generating docs for page license...
Generating docs for page commands...
/Users/floam/src/githubfish/doc.h:2815: warning: Found unknown command `\cx'
/Users/floam/src/githubfish/doc.h:3652: warning: expected whitespace after tt command
/Users/floam/src/githubfish/doc.h:3654: warning: expected whitespace after tt command
/Users/floam/src/githubfish/doc.h:3656: warning: expected whitespace after tt command
/Users/floam/src/githubfish/doc.h:3658: warning: expected whitespace after tt command
/Users/floam/src/githubfish/doc.h:3660: warning: Found unknown command `\f'
/Users/floam/src/githubfish/doc.h:3664: warning: Found unknown command `\r'
/Users/floam/src/githubfish/doc.h:3666: warning: Found unknown command `\t'
/Users/floam/src/githubfish/doc.h:3668: warning: Found unknown command `\v'
/Users/floam/src/githubfish/doc.h:3672: warning: Found unknown command `\xHH'
/Users/floam/src/githubfish/doc.h:4892: warning: expected whitespace after tt command
/Users/floam/src/githubfish/doc.h:4893: warning: expected whitespace after tt command
/Users/floam/src/githubfish/doc.h:4894: warning: expected whitespace after tt command
/Users/floam/src/githubfish/doc.h:4895: warning: expected whitespace after tt command
/Users/floam/src/githubfish/doc.h:4896: warning: Found unknown command `\f'
/Users/floam/src/githubfish/doc.h:4898: warning: Found unknown command `\r'
/Users/floam/src/githubfish/doc.h:4899: warning: Found unknown command `\t'
/Users/floam/src/githubfish/doc.h:4900: warning: Found unknown command `\v'
/Users/floam/src/githubfish/doc.h:4901: warning: Found unknown command `\ooo'
/Users/floam/src/githubfish/doc.h:4902: warning: Found unknown command `\xhh'
/Users/floam/src/githubfish/doc.h:4903: warning: Found unknown command `\uhhhh'
/Users/floam/src/githubfish/doc.h:4904: warning: Found unknown command `\Uhhhhhhhh'
/Users/floam/src/githubfish/doc.h:5504: warning: Found unknown command `\t'
/Users/floam/src/githubfish/doc.h:6200: warning: end of comment block while expecting command </code>
Generating docs for page faq...
Generating group documentation...
Generating class documentation...
Generating namespace index...
Generating graph info page...
Generating directory documentation...
Generating index page...
/Users/floam/src/githubfish/doc.h:269: warning: Found unknown command `\x9'
/Users/floam/src/githubfish/doc.h:276: warning: Found unknown command `\u9'
/Users/floam/src/githubfish/doc.h:278: warning: Found unknown command `\U9'
/Users/floam/src/githubfish/doc.h:280: warning: Found unknown command `\ci'
/Users/floam/src/githubfish/doc.h:1527: warning: end of comment block while expecting command </code>
/Users/floam/src/githubfish/doc.h:1527: warning: end of comment block while expecting command </code>
Generating page index...
Generating module index...
Generating namespace index...
Generating namespace member index...
Generating annotated compound index...
Generating alphabetical compound index...
Generating hierarchical class index...
Generating member index...
Generating file index...
Generating file member index...
Generating example index...
finalizing index lists...
writing tag file...
```

So I guess a future Doxygen version will either require updates to the lexicon parser to escape stuff correctly, or a future Doxygen version has better diagnostic output and this upgraded doxygen linting is pointing out things that are already incorrect in `doc_src`?

**Comment by floam** [comment]
OK, the above stuff is entirely very plainly missing slashes to escape things. Should also be fixed.

**Comment by MarkGriffiths** [comment]
I've gone through everything and I can see a number of issues:

##### Doxyfile (doxygen -u) changes_

The way Doxygen is declaring the ALIASES parameter has been changed. According to the Doxyfile header, `ALIASES += …` is the correct method, and might be necessary for Doxygen 1.8.7.

Anyway I think it's a moot point as the Doxyfile version should match the minimum supported version, which is 1.8.7, so there's no need for this to be updated.

##### Escaping

This is a can o' worms as you always have to consider the target of the escaping. Are you trying to display an escape sequence in the html, prevent Doxygen from interpreting a string as a command or special character, or are you escaping to prevent a side effect in the transformation chain.

95% of the original escaping issues were solved by having `MARKDOWN_SUPPORT = YES` set in the Doxyfile and by using __backticks__ to enclose terms. Nothing in backticks needs escaping at all to display correctly, nor should it ever be interpreted as a Doxygen command. This was the primary change that was needed to fix `"--"` display, but with that came the need to edit every single page of documentation. It's also the reason the minimum version is 1.8.7.

__Also content within `\fish … \endfish` should never be escaped!__ This is because the Doxygen configuration forces these to be treated as fenced code blocks, just like GitHub. Unlike GitHub, some escape sequences can force Doxygen to close the code block and treat the escaped entities as commands... things will start to unravel quickly from then on!

I beleive it was changes to `\fish` block contents that first disturbed the wasps nest. The non standard tags were used to avoid this happening and every attempt at fixing it from then on was then just punching the wasps nest... It's going to hurt and not much you can do to avoid it.

I'd be surprised if Doxygen has changed markdown behaviour in a 'patch' release. Historically it might add functionality to a patch release, but bump the minor version if there are breaking changes. It doesn't really follow semantic versioning, but it's been fairly predictable. 

There are two special cases where three back ticks are required to prevent side effects if they contain single quotes. Just getting GitHub to display the table below was an adventure into alien backslash domains! [[xkcd]](http://xkcd.com/1638/)

bind.txt → | commands.hdr → | doc.h → | commands.html → | display
-----------|----------------|---------|-----------------|--------
<code>\`\`\`bind '' self-insert\`\`\`</code> | <code>\`\`\`bind '' self-insert\`\`\`</code> | <code>\`\`\`bind '' self-insert\`\`\`</code> | `<code>bind '' self-insert</code>` | `bind '' self-insert`
<code>\`bind '' self-insert\`</code> | <code>\`bind '' self-insert\`</code> | <code>\`bind '' self-insert\`</code> | <code>\`bind '' self-insert\`</code> | <code>\`bind '' self-insert\`</code>

In some places the escaping is so complex, it's easier to surround the content in `<code></code>` tags and escaping the content as can be seen in the 'Escaping Characters' sections of `/doc_src/index.hdr.in`. 


index.hdr → | doc.h → | index.html → | display
------------|---------|--------------|--------
`'<code>\\a</code>'` | `'<code>\\a</code>'` | `'<code>\a</code>'` | `'\a'`

So many of your escaping changes above are incorrect.

##### Process

It's probably worth asserting the myriad of steps that are made to build the docs (I'm simplifying, leaving out tmp files).

- __Command list__  
  `doc_src/` is scanned for .txt files, `cat`ing them to `command_list.txt` and stripping the command name from the filename and formatting the html links and outputting as `command_list_toc.txt`. Both these files are combined and `cat`ted to `commands.hdr.in` to make `commands.hdr`
- __Table of Contents__  
  `index.hdr.in` and all other `.hdr` files in `doc_src` are run through sed, pulling out section and page names and formatting html links in `toc.txt`
- __Index page__  
  The `toc` is added to `index.hdr.in` as `index.hdr`. All `hdr` file are now `cat`ted together to make `/doc.h` at the project root.
- __Lexicon__  
  `command_list_toc.txt` is scanned and built-in fish commands are added to `lexicon.txt` as `bltn` and `lexicon_catalog.tmp` (which tracks what has already been added). Completion and function directories are scanned and added to the lexicon files, and classified as functions or commands. Finally `lexicon.txt` is scanned, and every item is mutated to a simple sed substitution and added to build `lexicon_filter`.

The best file to check for pre-lexicon errors is `doc.h`.

Doxygen is then run, with `doc.h` as input, either `Doxyfile.user` for html, or `Doxyfile.help` for man pages, the `lexicon_filter` set as `input_filter`.

It's easy to make the mistake of looking at the filter as a bunch of sed commands in a script, but Doxygen is actually running it as an executable, opening and closing the pipe according to the structure of the document. When you consider it's marking up every fish language semantic construct, built-in, function and shell command, before Doxygen converts it all to styled html, it's surprisingly fast. There is simply no other way to apply syntax colouring to an unsupported language in Doxygen.

I doubt anyone would choose to produce user docs like this normally, it's a legacy element of fish that goes right back to its origin, way before it's current stewardship here. Back then it made sense as the code commenting was consistent and the user docs were a subset of the developer docs, which were produced both from external files and code comments. It was part of the original design philosophy to make and keep fish well documented. The old developer pdf documentation was surprisingly useful, but fish has evolved far beyond that now.

##### What needs to be done

- [ ] Restore lexicon_filter.in to my last commit cb6d5d76c8232264f66c9a1db895d9dd69d77bc3
- [ ] Revert all non standard tags such as `\\outp` back to `<outp>` (these are for use within fish blocks - see escaping warning above)
- [ ] Revert escaping changes made across all the docs.
- [ ] Check backticks across the docs for consistency. The 2nd paragraph above 'Example' of printf's contains an unbalanced pair for starters - "The \`format' argument". There are only two instances of triple backtick usage.
- [ ] If errors are still being produced, check source pages for inconsistencies.

**Comment by MarkGriffiths** [comment]
It's probably worth adding that the `lexicon_filter` actually only targets the content of `\fish` blocks and completely ignores other content. From the header, which also shows some the main transforms:

```sed
# Finds \fish..\endfish blocks in documentation source files and enhances
# markup. Requires that the four character word 'classes' declared here are
# added to Doxyfiles as aliases i.e.:
#.
# Enhance for HTML Help pages (Doxyfile.user)…
# ALIASES   = "fish=\htmlonly[block] \n<pre class=\"fish\">"
# ALIASES  += "fish{1}=\htmlonly[block] \n<pre class=\"fish \1\">"
# ALIASES  += "endfish=</pre>\endhtmlonly \n"
#.
# ALIASES  += "blah{1}=<span class=\"comment\">\1</span>"
# ALIASES  += "bltn{1}=<span class=\"command\">\1</span>" and so on...
#.
# And simplify for man pages (Doxyfile.help)…
# ALIASES   = "fish=<pre>"
# ALIASES  += "fish{1}=<pre>"
# ALIASES  += "endfish=</pre>"
#.
# ALIASES  += "blah{1}=\1"
# ALIASES  += "bltn{1}=<em>\1</em>"...
#.
# It's meant to only ever be run once, during make, as Doxygen's 'INPUT
# FILTER', though can be run interactively by passing a file in via stdin. It
# wont respond to arguments.
#.
# It's most easily tested by passing test strings into the compiled script:
#.
# echo "\fish Line to test" | ./lexicon_filter
#.
# The, at times, archaic looking regex is down to ensuring portable sed BREs
```

**Comment by floam** [comment]
Oh, phooey.

**Comment by floam** [comment]
#3247 brought back the syntax so this should be closed.
