### ISSUE TITLE
`history --delete` (fish script, not builtin) is broken

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3237]
The `history --delete` command is broken. If your history contains multiline commands each line is listed as an individual entry you can select for deletion. That's obviously bogus. It might be possible to fix that. However, I'm wondering if it wouldn't make more sense to simply change the UI to eliminate selecting individual entries for deletion. Just give the user the choice of deleting all or none of the matching entries.

Also, including the recently introduced `-t` or `--with-time` flag produces output that makes selecting an individual entry for deletion impossible. Yet another reason to remove that capability.

I noticed this while working on issue #3224.

**Comment by krader1961** [comment]
This is a duplicate of issue #31.

**Comment by floam** [comment]
> Also, including the recently introduced -t or --with-time flag produces output that makes selecting an individual entry for deletion impossible. Yet another reason to remove that capability.

Except, I think it's important to be able to easily delete just one of those things you saw. It can be hard to copy and paste the command you want to delete - or impossible to narrow your query. 

So we let them choose one by number. We need to engage the user in that awful prompt, though, because they are referencing a match index for a search and those numbers are not IDs shown with the history that could be used later with a `history -d -i 344" or something.

So how about we just display a persistent identifier? I think if we base26'd the timestamp (1168557245 -> `jbq8jh`) and showed the history items with a little tag before/after them like a git hash, `[jbq8jh]` it could always resolve back that same entry. It'd be an upgrade, and not require the interactive crap. 

Or, some hashing function on the string itself since 1 second precision isn't quite good enough.

**Comment by floam** [comment]
>  However, I'm wondering if it wouldn't make more sense to simply change the UI to eliminate selecting individual entries for deletion. 

Except, I think it's important to be able to easily delete just one of those things you saw. It can be hard to copy and paste the command you want to delete - or impossible to narrow your query. 

So we let them choose one by number. We need to engage the user in that awful prompt, though, because they are referencing a match index for a search and those numbers are not IDs shown with the history that could be used later with a `history -d -i 344" or something.

So how about we just display a persistent identifier? I think if we base26'd the timestamp (1168557245 -> `jbq8jh`) and showed the history items with a little tag before/after them like a git hash, `[jbq8jh]` it could always resolve back that same entry. It'd be an upgrade, and not require the interactive crap. 

Or, get the same form a hashing function on the string itself since one second precision isn't quite good enough. 

What's nice is you can see the history output in a terminal from last week and that id number can still be used to refer to a given history item, and as our history isn't sorted nothing can suggest an order.
