### ISSUE TITLE
Tilde expansion if named file exists

### ISSUE THREAD

**Issue by kaleb** [fish-shell/fish-shell#3239]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
> fish, version 2.0.0
> fish, version 2.3.1

**OS/terminal used**: 
> Ubuntu 14.04 Trusty
> Ubuntu 16.04 Xenial

I had a mis-configured program that was creating directories named `~` in its working directory. After I fixed the configuration, I attempted to clean up by running `rm -r ~` without thinking.  That could have caused some serious damage! Luckily nothing catastrophic happened.

Similar to how `fish` handles non-existent glob expansions to prevent serious errors, I think that checking for the existence of an expansion candidate before expansion could be useful. I do not think that we should check variable expansion candidates however, which leads to an inconsistency in my proposal and we all know how special cases affect complexity. I just put this forward to see how the fish community feels about this suggestion. 

## Reproduction steps
1. Launch fish
2. Run command

        $ mkdir ./~
3. Run command

        $ rm -ri ~

## Expected results
Fish should delete `./~` instead of $HOME probably by calling `stat` _STAT(2)_ on `./~` to see if a file named `~` exists in PWD before expanding. It should probably do the same for process expansion as well.

## Actual results
	rm: descend into directory ‘/home/me’?

**Comment by krader1961** [comment]
FYI, your asciinema link is broken.

I like the proposal from the perspective of being friendly, especially to inexperienced users. But I'm bothered by the inconsistency in behavior. It might be better to treat the situation as an error, similar to what we do when a glob doesn't match anything, and ask the user to quote the tilde or use $HOME to disambiguate their intention.

**Comment by kaleb** [comment]
@krader1961 Regarding the asciinema link, I forgot to remove that from the default issue template. The link has now been removed from the ticket description..

Regarding the inconsistency in behavior, I totally agree about that.  The current way it is handled may or may not break the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) depending on the user's perspective.  I was certainly astonished about the results of my thoughtless `rm` command :fearful:!

I think that an error would be closer in line with how fish handles wildcards, so I think that would be the best solution.

**Comment by ridiculousfish** [comment]
This sounds like a request for bash-style conditional wildcard expansion. I think it's a mistake for string expansion to depend on contextual things like which files exist, because it makes the rules more confusing and complex.

**Comment by kaleb** [comment]
@ridiculousfish wildcards err in `fish` if they are not found. I think tilde expansions should take a similar approach as suggested by @krader1961 in that if there is a conflict, then err. What about that scenario?

**Comment by ridiculousfish** [comment]
I don't think doing this as a one-off for ~ makes sense. There's a bunch of special characters that, when present in a filename, may be interpreted wrongly without special care. That includes: `$ * ? & < > | ^ () []`, quotes, spaces and leading dash, and some exotic ones (tab, newline, Unicode, etc).

We can imagine a shell that makes all of expansions these conditional. Perhaps they produce errors if there's a valid path matching the non-expanded string. I think this would help avoid some mistakes. I think there's also some objections to this approach.

One is that we would need some mechanism to say "really expand this." Maybe we disable ~ because of the ambiguity. But what if there's a file `$HOME` too? This has the potential to be annoying.

A second objection is scripting. It would be bad if non-interactive scripts start throwing errors when new files appear that make the expansion ambiguous. It would be hard to write a robust script. We would most likely have to limit this feature to interactive uses to address this.

A third is the complexity and difficulty. Consider for example a command like `the quick brown fox jumped over the lazy dog`. There's 8 spaces, so 256 different possible expansions - this is quite a lot, and checking them all is challenging. Maybe we don't give this treatment for spaces, but spaces are surely the most common mishandled character.

Lastly, you can have valid paths with no file present: consider `touch ~` where the user intends to make a local file ~. So it wouldn't handle all cases.

Based on those objections I'm not excited about implementing this in fish. IMO what we ought to do (and are currently doing):

1. Make the expansion rules simple and predictable, so they're easy to learn.

2. Leverage syntax highlighting to highlight special characters (~ is not, maybe it should be). The valid path underline helps many cases as well (though not raw ~). Docopt signatures will eventually teach fish which commands must be files, so we can highlight invalid paths (#478) 

Preventing wildcards from expanding to leading dashes will also help (#1519)

**Comment by krader1961** [comment]
I'm strongly inclined to close this issue as "will-not-fix" given @ridiculousfish's comment above.

**Comment by faho** [comment]
Yes, let's close this as will-not-fix. If any more obections come up, we can discuss them. But apparently @ridiculousfish, @krader1961 and I feel that this inconsistency is worse than the alternative.

**Comment by cben** [comment]
One usability improvement I can think of is coloring active characters like `~`, `*`, `?` differently while editing the command.
Though for particular case of user typing `rm -r ~` without fear :fearful: expecting it'll remove a subdir called `./~`, I guess that only happens if one is not aware of tilde expansion at all, and there the color hint wouldn't help.

**Comment by floam** [comment]
> One usability improvement I can think of is coloring active characters like ~, *, ? differently while editing the command.

This is already the case, `*`, `~` and `?` are colored as `fish_color_operator`, the other stuff on the line that isn't the command will be `fish_color_param`.
