### ISSUE TITLE
fish_indent --dump crashes with invalid syntax

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#3241]
```
echo 'ec(o' | ./fish_indent --dump
fish: Process 22695, “./fish_indent” “echo 'ec(o' | ./fish_indent --d…” terminated
by signal SIGSEGV (Address boundary error)
```

**Comment by krader1961** [comment]
I've confirmed this bug exists in the version of fish_indent in which I first implemented the `--dump` option. I'm not too surprised since the assumption or the original code, and my enhancements, is that the input is valid fish script. Nonetheless, a SIGSEGV fault is never acceptable. I'll figure out what needs to be done to harden the program so it deals with malformed input in a more reasonable fashion.

**Comment by krader1961** [comment]
The failure is because of this typedef in *src/parse_tree.h*:

```
typedef uint32_t source_offset_t;
```

The code I wrote (that's triggering the SIGSEGV) is this:

```
wchar_t prevc = node.source_start > 0 ? source[node.source_start - 1] : L' ';
```

Notice the test for a value greater than zero? Sadly that fails when `node.source_start` is -1 which it is in the example provided by @zanchey. Never, ever, assign -1 as a magic value to an unsigned int unless you're deliberately writing obfuscated code.

**Comment by krader1961** [comment]
Okay, the code does create a special symbol for this magic value so it is less magic. My mistake was in not noticing its definition when I wrote my code and instead assuming the var was a signed int:

```
#define SOURCE_OFFSET_INVALID (static_cast<source_offset_t>(-1))
```

**Comment by floam** [comment]
This is something `__fish_parse` handled nicely:

```
 echo 'ec(o' | __fish_parse
Parsing failed:
Unexpected end of string, parenthesis do not match
ec(o
  ^
(Reparsed with continue after error)
 0 -  0  symbol_job_list  [no src]
---New Tree---
 1 -  1  parse_special_type_parse_error  [0, 5]
---New Tree---
 2 -  2  symbol_job_list  [no src]
```
