### ISSUE TITLE
Expansion of {$undefined}x swallows the "x"

### ISSUE THREAD

**Issue by TallestHead** [fish-shell/fish-shell#3243]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.3.1
**OS/terminal used**: 
iTerm2 v3.0.4
Talk about the the issue here. 

Assuming {$undefined} is undefined, this expression:

{$undefined}x expands to nothing, instead of "x". This is in contrast to every other shell I can think of, including older versions of shell.

FWIW, this causes iTerm2's shell integration to fail when launched under terminal, as it uses this statement:

if test {$ITERM_PROFILE}x != x

Which is a very common shell idiom.

## Expected results
Fish should probably not eat that trailing x.

## Actual results
Fish eats the x.

**Comment by krader1961** [comment]
This is the expected behavior. See the example about "cartesian product" at http://fishshell.com/docs/current/tutorial.html. A consequence of multiplying a single element array (your "x") with a zero element array is a zero element array. That example should probably be enhanced to mention this specific failure mode.

**Comment by krader1961** [comment]
Also, you apparently didn't cut/paste the actual statement that is failing. That's because `{$ITERM_PROFILE}x` expands to `{}x` if `ITERM_PROFILE` is not defined.

Too, that shell idiom is a bad one. It should either be `test "$ITERM_PROFILE" != ""` or `test -n "$ITERM_PROFILE"`. I use, and love, iTerm but not its shell integration. I recommend asking its maintainer to change that statement to one of those forms.

**Comment by faho** [comment]
>That's because {$ITERM_PROFILE}x expands to {}x if ITERM_PROFILE is not defined.

No. It expands to nothing.

>Too, that shell idiom is a bad one. It should either be `test "$ITERM_PROFILE" != ""` or `test -n "$ITERM_PROFILE"`

Yes. That old idiom is a workaround for bad shell behavior. What you're actually trying to figure out is if the variable is empty, so you should check if it is. (Though of course the necessary quoting is still annoying)

**Comment by krader1961** [comment]
> No. It expands to nothing. 

Yes, under fish it expands to nothing due to our cartesian product concatenation behavior. On both macOS and Ubuntu under /bin/sh it expands to `{}x` regardless of whether the string is quoted. I mentioned in my previous comment that the O.P. probably made a cut/paste error but forgot to say that what they probably saw iTerm doing was `if test ${ITERM_PROFILE}x != x` (notice the placement of the open brace). Which does have the expected behavior under POSIX shells but not fish since we don't support bracketed var names.

**Comment by faho** [comment]
This has been answered.
