### ISSUE TITLE
`set_color` should support equivalent of `tput smso` (set standout mode)

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3249]
The solution for issue #2904 ultimately involved setting and clearing the terminal standout mode with `tput smso` and `tput rmso`. It would be nice if we didn't have to shell out to an external command to do something so useful. Whether it's done via pseudo colors (e.g. `set_color standout`) or adding new flags is TBD.

**Comment by floam** [comment]
I think that should be flags because `smso` can do the same thing as `rev`- the colors will be modified by it/will persist through it, albeit inverted. Same with `tput rev`. The `set_color` interface kind of stinks but I think this is not like "normal" or "reset" in that regard.

`--standout` makes sense to me. I wouldn't try to think up a cute analogous name for something that is rather this rather specific mode.

**Comment by krader1961** [comment]
This was implemented by commit b22842a52f5434768d46c8209d324786d0a17033 on 2016-12-31 (PR #3650).
