### ISSUE TITLE
Command substitution in curl

### ISSUE THREAD

**Issue by krackers** [fish-shell/fish-shell#3252]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.3.1

**OS/terminal used**: OSX, Terminal.app

Consider the installation of homebrew, in which you run:

`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Of course, `$(...)` is not valid in Fish as fish instead uses regular parentheses for command substitution so we try:

`/usr/bin/ruby -e (curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)`

This doesn't work, however, as it doesn't run anything.

## Expected results
Fish should run output of curl as a ruby script

**Comment by floam** [comment]
Process substitution works:

`perl (curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install | psub)`

**Comment by krackers** [comment]
Hm ok. The error message should probably be updated then to

`$(...) is not supported. In fish, please use '(curl ... | psub)'.`

**Comment by floam** [comment]
Process substitution isn't the same as command substitution which that error is referring to. 

The reason command substitution likely isn't working for you is going to likely be due to how ruby is parsing the arguments and fish is splitting them.

**Comment by krader1961** [comment]
The `"$(some_command)"` construct is not equivalent to fish's `(some_command)`. That's because the former takes all the output of `some_command` and passes it as a single argument to ruby. The latter splits the output no newline boundaries and passes each line as an argument to ruby. In fish you can do this in a couple of ways but the easiest is

```
set install_script (curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)
ruby -e "$install_script"
```

You can also do this by manipulating `IFS` to inhibit splitting the output of curl on newlines but that's considered a hack.
