### ISSUE TITLE
Python shell?

### ISSUE THREAD

**Issue by sassanh** [fish-shell/fish-shell#3264]
Is it like science fiction to have a python shell powered by fish with full features of fish and reading its config, etc?

**Comment by ridiculousfish** [comment]
Are you suggesting a fish-like readline, that has autosuggestions and smart history? Or are you suggesting allowing the use of Python code from within fish? (Or both/neither?)

**Comment by sassanh** [comment]
It consists of 2 parts:
1. A fish-like readline which reads `.config/fish/config` (like `.inputrc` for readline).
2. Implementing a python shell using this fish-like readline.
I'm not interested in allowing the use of Python code from within fish.

**Comment by krader1961** [comment]
Have you tried [iPython](http://ipython.org/). It's interactive behavior is tailored to python and is far superior to anything fish's readline behavior would give you even if it could somehow be integrated into python.

**Comment by sassanh** [comment]
Yeah I'm using iPython a lot. The problem is readline doesn't support `vi-mode` very well and it's not consistent experience switching a lot between ipython and fish as they have different characteristics. There are lots of shells using readline and switching between fish and those shells is kinda annoying. For example that binding you defined in fish doesn't work in ipython or node and there's no way to setup it in readline or if there is, it takes lots of time and you already have it in fish. It'd be great if we could have something like readline that other shells could use. I understand that it may take few years to be practical or even if it doesn't worse the effort required.

**Comment by krader1961** [comment]
The reason it's not a consistent experience is because fish's vi mode is relatively new and only approximates real vi behavior. Several significant differences in behavior have been fixed in the recent past but a lot more work is needed to provide true vi behavior. We'd love to see pull-requests from people like yourself to improve fish's vi mode.

The fish equivalent of the readline library is also not structured in a manner that would allow it to be hooked into other programs like python. This is something I don't think we would accept even If you or someone else did the work to create a series of changes that would make it possible to use fish's interactive input layer with python and other programs.

**Comment by sassanh** [comment]
What already fish's vi mode offers is way more than what readline offers, so as time passes and its vi mode evolves the amount of differences and consequently inconsistent will increase not decrease. So the main reason it's not a consistent experience is because readline's vi mode is immature even though it's old.

Ok I understand that the fish equivalent of readline library is not a good idea. I don't like it too. What about a fish library that doesn't run files existing in directories `$PATH` lists, a fish library that instead of running files in `$PATH` takes a command from the user and sends it to the program that ran this library. I'm talking about the ability to embed fish in a program, something like neovim offers via its `nvim --embed` option.

**Comment by sassanh** [comment]
It does exactly whatever current fish does, with 2 differences:
1. It doesn't care about $PATH.
2. It sends back the input user enters to the parent application.
Everything else (including reading `.config/fish/fish.conf` is exactly the same)
