### ISSUE TITLE
Problem with stjerm terminal emulator

### ISSUE THREAD

**Issue by chanux** [fish-shell/fish-shell#3269]
I'm probably just one of three users who use fish with [stjerm](https://github.com/stjerm/stjerm)

I have this issue where I don't get a prompt on stjerm when my default shell is fish. Anything I type in just vanishes. However if I start stjerm with bash (with -sh option to stjerm) and later launch fish from there things are fine. I don't know where to look so I'd appreciate any input.

It's probably not worth anyone's time but I'm just reporting for.. well.. completeness maybe?

**Comment by floam** [comment]
What is `$TERM` set to by this terminal? You could check in bash but you'd want to try to make sure the bashrc/profile isn't actually setting that. (Especially as it seems to work when it's being launched inside of bash.)

Can you tell the terminal itself what shell use? If so, try having it start fish as `fish -d3` for debug output, and share what is printed when fish is launching, clues might be there.

**Comment by chanux** [comment]
Hey, thanks for the super quick reply. I was trying strace on it and found something interesting. It apparently gets in a loop of read syscall. Please check whether this make sense to you.

https://gist.github.com/chanux/4576233f46ae4d4199a898faafd13e45

I'll do what you suggested and report back.

**Comment by ridiculousfish** [comment]
Thanks for posting that,that's cool.

```SIGCHLD {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=5047, si_uid=1000, si_status=SIGSEGV, si_utime=0, si_stime=0}```

Something is crashing repeatedly. It might be fish. Maybe you can watch your process list and identify what's crashing, or locate the core dump file and determine what process it was.

Also what OS are you running on?

**Comment by chanux** [comment]
I'm running Ubuntu 16.04. I'll try to report back with information you mentioned.

**Comment by ridiculousfish** [comment]
Thanks, that's useful. Looks like a NULL dereference. Can you please try the following:

`> gdb fish
  (gdb) info symbol 0x0429b52`

That should tell us what function is crashing.

If that doesn't work (no symbol info) can you please post the output of `disassemble 0x0429b52`

Thank you for your patience and willingness to help us track this down!

**Comment by chanux** [comment]
I did following and got the result in the link
`
> gdb fish
(gdb) set log on
(gdb) info symbol 0x0429b52
(gdb) disassemble 0x0429b52
`
https://gist.github.com/chanux/c799428dec4bd26285c6b4213b98b5d8

Fish is great. Glad to help improve fish!

**Comment by krader1961** [comment]
It looks like the failure is occurring in `fish_parse_opt()` at this statement:

```
// If our command name begins with a dash that implies we're a login shell.
is_login |= argv[0][0] == '-';
```

It looks like you're invoking the fish shell without any arguments. Which suggests a bug in sjterm since there  should always be at least one argument, the command name, by convention. Having said that fish should deal with an empty `argv` vector better; i.e., by not dereferencing a NULL pointer since there is no guarantee `argv` has at least one element.

**Comment by floam** [comment]
I think what's going on is the check for `-` by `argv[0][0]`. 

This was (maybe?) fixed in sjterm, where it also had problems for zsh:

https://github.com/stjerm/stjerm/commit/8ff7fa78cfc3ddab97530685d1aca2bf46bdfe8a

The fix was to pass the shell an empty string instead of NULL.

Nonetheless, we could use a more resilient method to look for the hyphen.

**Comment by ridiculousfish** [comment]
Great and very plausible theory! Both of you :)

**Comment by floam** [comment]
A survey:

`argouch.c:`
```c
#include <stdio.h>
#include <unistd.h>
#include <sysexits.h>

int main(const int argc, char* const argv[])
{
    if (argc != 2) {
        printf("./argouch COMMAND\n");
        return EX_USAGE;
    }
    return execvp(argv[1], NULL);
}
```

```fish
> argouch fish
fish: 'argouch fish' terminated by signal SIGSEGV (Address boundary error)
> argouch zsh
zsh: too few arguments
> argouch csh
fish: 'argouch csh' terminated by signal SIGSEGV (Address boundary error)
> argouch tcsh
fish: 'argouch tcsh' terminated by signal SIGSEGV (Address boundary error)
> argouch bash
bash-3.2$ exit
exit
> argouch mksh
$ exit
> argouch elvish
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x4333880, 0xc82000e0b0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
flag.init()
	/usr/local/Cellar/go/1.6/libexec/src/flag/flag.go:939 +0x101
main.init()
	/Users/floam/go/src/github.com/elves/elvish/main.go:245 +0x4c
>
```

**Comment by chanux** [comment]
I compiled latest stjerm and fish works fine there as @floam suggested.

There is a minor issue when I run stjerm manually (not as a startup app). It prints following line between my fish greeting and the  prompt.

`]7;file://nim/home/chanux⏎`

This is actually the directory stjerm is run from. Probably an stjerm issue again. Mostly a non-issue.

BTW, I would like to know how you get to code from instruction pointer(?). I assume it's from a fish compiled with debug symbols. Would like to look in to that :). Thanks in advance.

**Comment by floam** [comment]
Yours probably has debug symbols. The output you pasted has the offending code in it. Notice that you were able to tell us that we were at `main + 594` (instead of just an address).

 But even without symbols, we'd still see essentially be looking at the same instruction at +594:
```
   0x0000000000429b3f <+575>:	movl   $0x1,0x31fecf(%rip)        # 0x749a18 <is_interactive_session>
   0x0000000000429b49 <+585>:	jmpq   0x42998e <main+142>
   0x0000000000429b4e <+590>:	mov    0x0(%r13),%rax
   0x0000000000429b52 <+594>:	cmpb   $0x2d,(%rax)
   0x0000000000429b55 <+597>:	sete   %al
   0x0000000000429b58 <+600>:	movzbl %al,%eax
   0x0000000000429b5b <+603>:	or     %eax,0x31feab(%rip)        # 0x749a0c <is_login>
```
We can see that it's checking to see if whatever it just put in the rax register is equal to 0x2D, the ASCII code for '-'.

  (https://github.com/fish-shell/fish-shell/blob/master/src/fish.cpp#L397)`is_login |= argv[0][0] == '-'` ended up being an obvious match match in `fish.cpp`. We can also see those nearby symbols `is_interactive_session` and `is_login` in context here. We actually are slightly outside of `main()` in the original cpp because of compiler stuff like the static keyword.

**Comment by krader1961** [comment]
@floam's explanation is overly simplistic. The fact the faulting instruction was 594 bytes from the start of the main() function isn't helpful. In no small part because the failing instruction is actually from a different function that was inlined into main(). What I did was consider how the nearby references to symbols like `is_interactive_session` and `is_login` related to the source code. Then, I used the fact that the failing comparison was to 0x2D to confirm I had found the correct line of code.

**Comment by faho** [comment]
>There is a minor issue when I run stjerm manually (not as a startup app). It prints following line between my fish greeting and the prompt.

>�]7;file://nim/home/chanux⏎

>This is actually the directory stjerm is run from. Probably an stjerm issue again. Mostly a non-issue.

That looks like it's from `__update_vte_cwd` (a function conditionally defined in functions/__fish_config_interactive.fish) - vte, the terminal library that stjerm is based on, has a function where you can tell it the working directory. We do that if we detect that "$VTE_VERSION" is greater than "3405" (the version where this was enabled). Since stjerm is based on vte, it sets that variable. Only it seems like it can't handle it. I need to check why.

Anyway, it's a different issue.

**Comment by floam** [comment]
I'm surprised the static analyzers didn't assume `argc = 0` and complain about `argv[0][0]`. `argv[argc]` is guaranteed to be NULL.

**Comment by floam** [comment]
Why not just handle this like mksh or bash and make it work?

**Comment by floam** [comment]
(It seems like a message for a terminal emulator developer. Maybe show it on `-d2`?)

**Comment by krader1961** [comment]
OMFG, the [sjterm fix](https://github.com/stjerm/stjerm/commit/8ff7fa78cfc3ddab97530685d1aca2bf46bdfe8a) that @floam found is FUBAR. They're now passing an empty string for the program name. /facepalm

**Comment by krader1961** [comment]
> Why not just handle this like mksh or bash and make it work?

My change does "make it work". It also alerts the user that whatever program (terminal emulator or otherwise) that launched their fish shell is broken by violating long standing custom. Making it a debug message is pointless. If people feel strongly that we should silently correct this bogosity then there is very little reason to issue a diagnostic at any debug level. Better to just remove the diagnostic message.

> I'm surprised the static analyzers didn't assume argc = 0 and complain about argv[0][0]. 

How would static analyzers recognize that `argc == 0` mean that `argv[0][0]` is going to result in a SIGSEGV? Even if those tools could somehow know that `argc` was somehow linked to `argv` it would require an incredibly sophisticated data flow analysis to warn about the problematic dereference. Not to mention not warning if the code explicitly checked for that possibility.

**Comment by ridiculousfish** [comment]
It does no good to alert the user when their terminal misbehaves, because the user is in no position to fix it. This message will mainly succeed in annoying sjterm users. Please let's either up the debug level on this message, or remove it outright.

**Comment by krader1961** [comment]
> It does no good to alert the user when their terminal misbehaves, because the user is in no position to fix it.

They're in a position to tell the terminal developers their terminal is broken. But I'm inclined to agree that without a considerably more verbose message the average user isn't going to know what to do with that diagnostic. So I've removed it. If they're expecting a login shell and don't get one because of that bug that's their tough luck.
