### ISSUE TITLE
Give a couple GCC 6.1 warnings a glance-over

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3275]
This is on OS X. I won't report everything being output by default (I assume others have seen 'em), but I figured I'd pass along any that might be OS X-specific and/or mention `NULL`.

I seem to be able silence these ones if I revert [these lines](https://github.com/fish-shell/fish-shell/blob/master/src/fallback.h#L73-L76) which seemed to have been changed recently in https://github.com/fish-shell/fish-shell/commit/46be5ac468db923bd3d19c55638b723aa760cd4e. Not sure what exactly that part of the change was intended to fix and if the warnings should be ignored. Current builds (done on 10.7 or later) work fine on 10.6, right?
```
src/fallback.cpp: In function 'wchar_t* wcsdup_use_weak(const wchar_t*)':
src/fallback.cpp:140:17: warning: the address of 'wchar_t* wcsdup(const wchar_t*)' will never be NULL [-Waddress]
     if (&wcsdup != NULL) return (wcsdup)(a);
                 ^
src/fallback.cpp: In function 'int wcscasecmp_use_weak(const wchar_t*, const wchar_t*)':
src/fallback.cpp:145:21: warning: the address of 'int wcscasecmp(const wchar_t*, const wchar_t*)' will never be NULL [-Waddress]
     if (&wcscasecmp != NULL) return (wcscasecmp)(a, b);
                     ^
src/fallback.cpp: In function 'int wcsncasecmp_use_weak(const wchar_t*, const wchar_t*, size_t)':
src/fallback.cpp:150:22: warning: the address of 'int wcsncasecmp(const wchar_t*, const wchar_t*, size_t)' will never be NULL [-Waddress]
     if (&wcsncasecmp != NULL) return (wcsncasecmp)(s1, s2, n);
```

And these ones we can experience if we flip on `-Wnull-dereference`:

```
src/parse_tree.cpp: In member function 'const parse_node_t& parse_node_tree_t::find_child(const parse_node_t&, parse_token_type_t) const':
src/parse_tree.cpp:1309:20: warning: potential null pointer dereference [-Wnull-dereference]
         if (child->type == type) {
             ~~~~~~~^~~~
src/parse_tree.cpp:1309:20: warning: potential null pointer dereference [-Wnull-dereference]
src/parse_tree.cpp: In member function 'const parse_node_t* parse_node_tree_t::next_node_in_node_list(const parse_node_t&, parse_token_type_t, const parse_node_t**) const':
src/parse_tree.cpp:1578:24: warning: potential null pointer dereference [-Wnull-dereference]
             if (child->type == entry_type) {
                 ~~~~~~~^~~~
src/parse_tree.cpp:1578:24: warning: potential null pointer dereference [-Wnull-dereference]
src/parse_tree.cpp: In member function 'bool parse_ll_t::report_error_for_unclosed_block()':
src/parse_tree.cpp:1291:16: warning: potential null pointer dereference [-Wnull-dereference]
     if (parent.child_count > 0) {
         ~~~~~~~^~~~~~~~~~~
src/parse_tree.cpp:1291:16: warning: potential null pointer dereference [-Wnull-dereference]
```

**Comment by ridiculousfish** [comment]
Thank you for filing an issue.

> src/fallback.cpp:145:21: warning: the address of 'int wcscasecmp(const wchar_t*, const wchar_t*)' will never be NULL [-Waddress]

Well maybe not, depending on what gcc has set as the deployment target. But certainly for the deployment target we release under (10.6) the address of wcscasecmp may be NULL.

> src/parse_tree.cpp:1309:20: warning: potential null pointer dereference
> src/parse_tree.cpp:1578:24: warning: potential null pointer dereference

These two are both following the same pattern of iterating over a node's children. We should strengthen this so that it's more obvious that get_child won't return NULL here.

> src/parse_tree.cpp:1291:16: warning: potential null pointer dereference

That one just looks bogus - don't know what is going on in gcc's head here. Maybe someone else can figure it out.

**Comment by krader1961** [comment]
I'm not seeing the first three warnings from *fallback.cpp* on OS X El Capitan with gcc reporting `Apple LLVM version 7.3.0 (clang-703.0.31)`. The summary line for commit 46be5ac is misleading. Making fish build on OS X Snow Leopard was not the primary purpose of that change. And I don't see how the Snow Leopard portion of that change would cause those warnings on newer OS X releases. Apparently you're forcing the use of gcc rather than LLVM on OS X. Is there some reason we should care about that non-standard build environment?

The first couple of *parse_tree.cpp* warnings need to be suppressed. The final warning looks like a gcc bug.

**Comment by floam** [comment]
You're quoting the output from Clang, not GCC.

**Comment by krader1961** [comment]
> Because you're quoting the output from Clang, not GCC.

Yes, I said as much.

> This is about evaluating warnings produced on Darwin when compiled with a recent GCC.

And I asked "Do we care about that?" Are you seeing those warnings on Linux or BSD with GCC?
