### ISSUE TITLE
Suggestion: tab auto completion and history suggestion should both be selectable with tab

### ISSUE THREAD

**Issue by xamino** [fish-shell/fish-shell#3283]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

**fish version installed** _(`fish --version`)_: '`fish, version 2.3.1-441-g01f09cf`'

**OS/terminal used**: Ubuntu 14.04, gnome-terminal

I would like to suggest that tab completion and suggestion completion can both be selected with tab. Typing ctrl+f or especially right arrow breaks ten finger typing for me, meaning I have to move my hands (admittedly not a lot for ctrl+f, but still) and lose my flow.

Of course this may result in conflicts when selecting what the user actually wants completed. Looking at my usage of fish so far I think simply preferring the suggestion for the first tab, with subsequent tabs switching through the tab completions would be a working solution.

I'd love to hear some reasoning / discussion on this.

**Comment by faho** [comment]
>simply preferring the suggestion for the first tab, with subsequent tabs switching through the tab completions would be a working solution.

This would make tab completion a bit worse.

If, say, I enter `git`, fish will suggest the last git command I executed, say `git shortlog`. If I don't want that one, but e.g. `git show 0a51`, then with this change, I'd need to press TAB one more time.

>Typing ctrl+f or especially right arrow breaks ten finger typing for me

You can also rebind it. E.g. you _could_ do `bind \e accept-autosuggestion cancel`. Or switch to vi-mode.

Unfortunately it's not possible to bind anything to "accept a suggestion if there is one, otherwise complete", because completion will not go further (e.g. enter the pager) if there's another commandline function in between the complete calls. This might be solved via a function that tells us if there is a suggestion - which might enable more bindings of this type.

**Comment by faho** [comment]
Okay, this has been stuck on the RFC stage for two years, closing.
