### ISSUE TITLE
fish_vi_mode regressions jumping to end of autocomplete

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#3298]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
git f3e93f06669dc36c68dd86573b4ca7caf59db63a

**OS/terminal used**: 
Connecting to freebsd via putty, $TERM=xterm

There seems to be a regression (though I'm not sure if it's by design, as I am aware some restructuring of fish_vi_mode was in progress) in fish_vi_mode with regards to the behavior of autocomplete (and how to accept a suggestion).

The correct behavior is exhibited in 9aeed0dc06c4dc9b23701e56b62e9aa9de6e81d5

## Reproduction steps
`fish_vi_mode`

followed by these three cases (each separately)
1. begin typing something that matches an autocomplete entry, then press the END key
2. begin typing something that matches an autocomplete entry, then press the left arrow key
3. begin typing something that matches an autocomplete entry, then press ctrl+e

## Expected results
1. fish goes to end of autocomplete suggestion, still in insert mode
2. fish goes to end of autocomplete suggestion, still in insert mode
3. fish goes to end of autocomplete suggestion, still in insert mode

## Actual results
1. fish goes to end of autocomplete suggestion, but drops out of insert mode
2. fish goes to end of autocomplete suggestion, still in insert mode
3. has no effect

**Comment by krader1961** [comment]
That item 3, [ctrl-E], no longer works is intentional. If you want emacs bindings mixed in with your vi bindings you have to explicitly ask for that. It's no longer the default behavior because it's too confusing for people unfamiliar with the emacs bindings who accidentally enter those keystrokes.

For item 1 I see radically different behavior but that is even more broken. Looking at the output of `bind` I see `bind -M visual \e\[F end-of-line` but not the expected `bind -M insert \e\[F end-of-line`. So that is definitely a bug.
