### ISSUE TITLE
Question: bracket equivalent

### ISSUE THREAD

**Issue by danielb2** [fish-shell/fish-shell#3305]
What's the equivalent in fish to bash's `ls file.[0-3].*` ?

I tried finding this in the documentation but was unable to. are there any plans to support this pattern matching at all?

**Comment by faho** [comment]
See #839.

In some cases (numerical arguments, without caring about file existence or with further globs), like this one, you can use `seq`, like `ls file.(seq 0 3).*`.

When there's alphabetical arguments, like in `ls file.[a-c].*`, seq doesn't work.

We're unsure of how to handle this, but we shy away from adding more _syntax_.

**Comment by danielb2** [comment]
could this or something similar be added to the pattern matching section of the help document? That's where I went searching for an answer

**Comment by faho** [comment]
As I said, there's a few limitations, so I'm not sure we want to codify this just yet.

**Comment by danielb2** [comment]
There are limitations to including using `seq` in the documentation in section in pattern matching?

**Comment by faho** [comment]
No, this _solution_ of using `seq` has limitations. Like I said:

- If you want exact matches only, you need to awkwardly use `find` or something, since you need to check for file existence

- `seq` doesn't usually do leading 0s, so you'd need to use the "-w" option, which I have a feeling is non-standard - my example here is files named like "Series SXYEUV.mp4"

- If you want character ranges, you're out of luck - of course for just "[abc]" you can use brace expansion ("{a,b,c}")

I mean we could mention this, but given that we have no easy solution for checking file existence here it feels unwise to mention a half-assed workaround, when we already mention `find` - the swiss-army knife of finding stuff.

You can also do this with `find . -maxdepth 1 -regex "./file\.[a-c]\.*"`. That's the full-featured solution, and offers things we'd never even dream of.

**Comment by krader1961** [comment]
> There are limitations to including using seq in the documentation section about pattern matching?

Yes, because it's doesn't actually behave the same as the character class syntax. Documenting its use in the section on pattern matching would almost certainly cause more confusion than it solves.

There have been lengthy discussions about adding more glob syntax. No firm decisions have been made but so far we haven't been convinced that adding new syntax is worth the cost. We might be convinced to add support for character classes but it is almost a certainty we'll never add the more esoteric forms of globbing supported by bash and zsh.  The feeling among most of us is that for complex globbing it's better to use the `find` command. For example, I frequently want a list of all regular files in or below the cwd. For that I have the following function which I can then use like `grep something (ff)`:

```
function ff --description 'Like ** but only returns plain files.'
    # This also ignores .git directories.
    find . \( -name .git -type d -prune \) -o -type f | sed -n -e '/^\.\/\.git$/n' -e 's/^\.\///p'
end
```

**Comment by danielb2** [comment]
@krader1961   What are the limitations to including documentation? Technically challenging to explain how fish solves the problem? 

I'm not asking for a implementation solution in the shell, _simply documentation on how fish solves a problem in the same domain that virtually all shells solve with pattern matching_. It seems that that the section talking about pattern matching is reasonable.

**Comment by krader1961** [comment]
The limitations of documenting the use of `seq` as an alternative to the bracket glob syntax is that the two are not equivalent. So it's a poor alternative. Documenting that specific "solution" is likely to confuse more people than it helps. But you're certainly welcome to create a change with what you think would be helpful and we'll be happy to review it. While I'm not enthusiastic about documenting the use of `seq` in the section on globbing I do think we should add more examples using `find` for people used to the advanced globbing features of bash and zsh.

**Comment by danielb2** [comment]
If it were me, and I had that concern, I would simply reference the appropriate location in the documentation in that section, and then cover it there. This really shouldn't be this hard.

**Comment by YarekTyshchenko** [comment]
Was disappointed to see that `lsblk -f /dev/sd[ab]`  doesn't work. Would be nice to have some docs on how to solve this, seq obviously can't do that here, though I wouldn't mind a seq equivalent that does globbing.
I actually like that fish has fewer special characters in normal usage. I wouldn't mind something like `lsblk -f (glob /dev/sd[ab])` to be explicit

**Comment by floam** [comment]
> lsblk -f /dev/sd[ab] doesn't work.
