### ISSUE TITLE
env command doesn't escape control codes

### ISSUE THREAD

**Issue by dbrodie** [fish-shell/fish-shell#3318]
**fish version installed** *(`fish --version`)*: 2.3.1

**OS/terminal used**: Fedora 24 / Terminux

The env command doesn't escape control codes in its output.

## Reproduction steps
1. Launch fish
2. $ `set -x FROM_HERE_ON_GREEN (printf "\033[01;32m")`
3. $ `env`
(Might need to add some environment variables to be displayed after FROM_HERE_ON_GREEN)

## Expected results
Fish should escape the control codes in the output so that it is visible what the values in the environment variable is.

## Actual results
Green output after the FROM_HERE_ON_GREEN environment variable.

**Comment by faho** [comment]
`env` is an external command, so we don't have anything to do with it.

In this case, piping to `string escape` might be helpful, but we should not add it to fish.

**Comment by floam** [comment]
If you're just annoyed at the output of the (external program) env, because you use it to see what you've exported and that behavior is less than ideal (but the same as occurs in e.g. `zsh`), you can use `set -x` to check instead, which outputs basically the some information:

```> set -x
...
FROM_HERE_ON_GREEN \e\[01\;32m
```

A pager like `less` can be handle output like this generally in a good way too:

<img width="463" alt="screenshot 2016-08-21 at 6 51 09 am" src="https://cloud.githubusercontent.com/assets/291142/17837585/b248796c-676b-11e6-9894-381042785ff6.png">
