### ISSUE TITLE
Make functions shadowing builtins a warning, not a failure

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#3319]
#3013 added the `--shadow-builtin` flag, but I am concerned that it is setting up problems with forward compatibility. In particular, if you write a function today called `foo`, and then we introduce a builtin called `foo` down the track, your function will stop working completely.

The options here are not great - if we do nothing, your shell might explode (see the multiple `test` functions), but a soft warning rather than a hard fail is more acceptable as it is less likely to cause sudden explosions.

**Comment by krader1961** [comment]
@zanchey and I had a short discussion about this on the project's private Gitter channel. I'm inclined to agree that making it a warning rather than a hard error is preferable.

When this change was originally discussed everyone seemed comfortable with making it a hard error in order to keep people from breaking their system (e.g., via `function test; false; end`).
If people are now uneasy about taking such a hard line and think a warning is enough I have no objection. In fact I now think it should be a warning since doing so is more likely to leave the user with a working shell. Especially in the presence of third-party extensions that might predate the introduction of a new builtin command. Warning messages are annoying but at least they don't break the user's previously working shell.

**Comment by krader1961** [comment]
What follows is a "meta comment" that goes beyond this specific issue.

FWIW, In my $dayjob we don't normally apply the "bug" label to a design mistake. The "bug" label is normally reserved for behavior that is not compatible with the explicit, or implicit, documented behavior. In this case that would not appear to be true since the documentation reflects the behavior we now wish to change. I have no idea why I added the "bug" label yesterday.

This is a "[mice nuts](http://www.urbandictionary.com/define.php?term=mice%20nutshttp://www.urbandictionary.com/define.php?term=mice%20nuts)" distinction but I see this happening quite a bit on this project so felt compelled to point out my own mistake in incorrectly labeling this issue. Simply because having a consistent worldview when handling issues is valuable.

**Comment by floam** [comment]
I think we also do not want to cause an error where using `--shadows-builtin` where the function is not yet a builtin. See my original comment on #3000 and comments on @krader1961's proposed fix #3324.

**Comment by krader1961** [comment]
We definitely do want adding `--shadow-builtin` to a function that does not mirror a builtin to be an error. Allowing that use case without an error makes the feature almost useless. @faho actually proposed this during the original PR review and quickly realized why it doesn't make sense.

Consider the case of someone creating a `string` function meant for use on fish versions before that builtin existed. They have their function added to plugin managers like OMF and Fisherman. The author wants their function to work with versions of fish that do and do not have a string builtin. With your proposal they take the easy route and add `--shadow-builtin`. Now no error occurs when their function is used with a version of fish which has no such builtin. And their function likely incorrectly masks the builtin on versions with a builtin by that name. We want the author of such a function to explicitly deal with fish versions that do and do not have a builtin by the same name.

Making using that flag an error if there is no such builtin provides incentive to do the right thing and explicitly deal with fish versions that do and do not have a builtin by the same name. The author of the function doesn't even have to future proof their function. They can simply omit the flag. If and when we ever implement the function name as a builtin users will start seeing a warning message when the function is defined but they will continue to see the behavior provided by the function rather than the builtin.

**Comment by floam** [comment]
> Making using that flag an error if there is no such builtin provides incentive to do the right thing and explicitly deal with fish versions that do and do not have a builtin by the same name.

That's not what #3000 was trying to ensure, though.

**Comment by floam** [comment]
This might be better done with a simple special case for `builtin test` to prevent a very likely `function test; echo Hello world; end` and call it done. 

No matter what we do, by adding this argument to `function`, we can't do anything now will make using `--shadows-builtin` not break 2.3.1 or earlier because it causes an error there as an unexpected argument. That's bad enough - it's questionable if we're not shooting our foot off here by causing more grief for users than we are saving by protecting them from accidentally shadowing a builtin they didn't know about.

**Comment by krader1961** [comment]
In light of all the problems this "feature" causes I'm just going to revert it. If people shoot themselves in the foot that's their problem.

> This might be better done with a simple special case for builtin test to prevent a very likely function test; echo Hello world; end and call it done.

I can't parse that sentence but since I'm going to just revert this change don't bother clarifying. I mention it only because so many of your comments, @floam, leave me scratching my head. Also, this is not a "regression". I don't know what you do for a living but it's apparently not software development.

**Comment by floam** [comment]
Sorry, I didn't know what to label it!
