### ISSUE TITLE
fish set command replaces newlines with 0x20

### ISSUE THREAD

**Issue by andrewrk** [fish-shell/fish-shell#3329]
Problem occurs with fish 2.2.0. I searched open and closed issues for this problem and found no matches, and thus concluded that it is still an issue with the latest fish.

 * System: `Linux andypad 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
 * Terminal: `xfce4-terminal`

```
~> hexdump -C ~/foo.txt
00000000  61 3d 62 0a 63 3d 64 0a                           |a=b.c=d.|
00000008
~> sex -x FOO (cat ~/foo.txt)
~> echo $FOO | hexdump -C
00000000  61 3d 62 20 63 3d 64 0a                           |a=b c=d.|
00000008
```

Note that fish changed the newline in the environment variable to `0x20`. I expect both hexdumps to be the same. The equivalent bash has the expected behavior.

**Comment by faho** [comment]
This is #159.

The reason you didn't find it is because you went looking at the ASCII internals. "0x20" is an actual normal space. This one: " ".

When you do `echo $FOO`, it's expanding "$FOO" to its individual elements, passing each as a single argument to `echo`, and `echo` then adds spaces between them.

The reason it's expanding to multiple array elements is because we by default split command substitutions on newlines. Currently there's no easy way out of that, so #159 is still open.
