### ISSUE TITLE
printf(1) locales broken between 2.3.0 and 2.3.1

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3334]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**OS/terminal used**: FreeBSD, OS X 

## Reproduction steps

2.3.0 functions as designed/expected:

```
> set -x LC_NUMERIC "fr_FR.UTF-8"; builtin printf "%f" 5.55
5,550000
```

2.3.1 fails to take LC_NUMERIC into account:
```
> set -x LC_NUMERIC "fr_FR.UTF-8"; builtin printf "%f" 5.55
5.550000
```

**Comment by floam** [comment]
This commit likely is responsible: https://github.com/fish-shell/fish-shell/commit/0b385f145ce6144b5812bd89fa8f73369bcbe57f

@krader1961 the comment suggests that you thought the old code was forcing the C, but it was only falling back to the C locale. Also, it was restoring the per-process locale when it was done - these changes don't look like they are doing this.

**Comment by floam** [comment]
When the old functions as passing NULL to `setlocale()` it was saving the current per-process locale. And the other checks were making sure there was something to bother changing/from/ to restore to. You're "restoring" to C when it's done too.

**Comment by krader1961** [comment]
You're correct, @floam. Good catch. I could have sworn I tested that `setlocale()` returned the old locale but cannot reproduce that behavior. This is definitely a regression that I'll fix since I introduced it. I'll also add unit tests so this doesn't happen again.

**Comment by floam** [comment]
Huh! I thought xlocale.h in OS X was just some non-portable Apple extension. Actually, these per-thread locales and all these reentrant-safe versions of functions are just where apple put their POSIX 2008 locale implementation. 

We could make our strtod_c thread-safe here by using `strtod_l` and just passing the reentrant-safe function a `locale_t`. We could eliminate a lot of global process state and use this yesterday on a number of platforms if we ask autoconf, rather than waiting for C++11/std::locale to get it. Also can be flipped on on Linux, FreeBSD, Minix, Solaris..

**Comment by floam** [comment]
[C065.PDF](https://github.com/fish-shell/fish-shell/files/438819/C065.PDF)

**Comment by floam** [comment]
I think fish experiences issues on DragonFlyBSD and FreeBSD 11 due to these improved subsystems - not bugs in them exactly. 

New locale system writeup https://www.dragonflybsd.org/release44/

**Comment by krader1961** [comment]
Researching this problem made me notice calling `setlocale(LC_NUMERIC, NULL)` returns a pointer to a string that is changed by a subsequent locale change. The code I elided dealt with this by instantiating a C++ string object and thus make a copy of the C string. This observation makes me want to smack the authors of this API. Especially since calling `setlocale()` with a non-NULL string should return the old locale rather than the one we passed in. Apparently the current behavior is because the authors of the setlocale API didn't want to dynamically allocate memory.

Having said all that the reality is that `long double raw_string_to_scalar_type()` always forces the C locale before doing the conversion -- even before my change that inadvertently left the C locale in effect for `LC_NUMERIC`. The test for `setlocale(LC_NUMERIC, NULL)` returning NULL will only be true if the locale API is broken.

The fact the `raw_string_to_scalar_type()` function ignores the user locale (even before my change) itself is arguably a bug. Why is it correct for `printf '%f' 1.23` to use the user locale when formatting the result but ignore the user locale when converting the string "1.23" to a double? You can test this for yourself. Checkout the version of fish before I introduced this bug. Then set the locale to french and verify that it only accepts C/English style floating point numbers:

```
$ git checkout 44249098010c154e7dc24589a84db529687758fe^
$ make fish
$ env LC_NUMERIC=fr_FR.UTF-8 ./fish -c 'printf \'%e\' 1,23'
1,23: value not completely converted
$ env LC_NUMERIC=fr_FR.UTF-8 ./fish -c 'printf \'%e\' 1.23'
1,230000e+00
```

Now do the same thing with bash:

```
$ env LC_NUMERIC=fr_FR.UTF-8 bash -c 'printf \'%e\' 1,23'
1,230000e+00
$ env LC_NUMERIC=fr_FR.UTF-8 bash -c 'printf \'%e\' 1.23'
bash: line 0: printf: 1.23: invalid number
0,000000e+00⏎
```

Fish does the opposite of bash and in my opinion bash is correct and fish is wrong.

I can appreciate why fish behaves the way it does. Someone probably decided that hardcoded constants in scripts shipped with fish were likely to conform to C/English syntax for such things and would be incorrectly parsed if the user used a locale that had a different syntax for such values. Localization is hard. But in this instance the [author of this code](d9c9760aaca353da3deeb503da0a191b34683309), @siteshwar, got it wrong in my opinion.

The question is what to do. I can fix the problem I introduced. But that still leaves a more serious problem. What I recommend is improving on bash. We should first attempt to convert the string literal using the current locale. If that fails attempt to convert the string using the C locale. If that fails give up.

**Comment by floam** [comment]
@krader1961 Not exactly. I think bash is wrong there. I believe `LC_NUMERIC` is for formatting of output, just like for c printf(). Input should be interpreted by what LC_CTYPE is set to, I think.

**Comment by floam** [comment]
And it makes sense: you wouldn't want your shell scripts to have to worry.

**Comment by krader1961** [comment]
The problem, @floam, is that the standards are ambiguous on this point AFAICT. Also, `LC_CTYPE` is explicitly meant to only affect the classification of characters and how they are ordered for purposes of sorting. That, however, does not include how comma and period are used when writing or interpreting numbers. What do you expect to happen when someone does the equivalent of

```
printf '%e' (echo 1,23)
```

Where the echo is replaced by a command that emits a floating point value that respects the user's `LC_NUMERIC` setting?

**Comment by floam** [comment]
http://pubs.opengroup.org/onlinepubs/009696799/utilities/printf.html

**Comment by floam** [comment]
And you're right about LC_CTYPE: it affects the dealing with bytes here.

**Comment by krader1961** [comment]
Also, neither the opengroup document you linked to, nor [a different version](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/printf.html) I read a earlier today, talks about how floating point string literals are interpreted. Only how they are to be formatted for output by `printf`.

**Comment by floam** [comment]
Even handling floating point at all is pretty much undefined - shell arithmetic is integer after all. Hm, so what does ksh93 do, being so good math...

**Comment by floam** [comment]
`ksh` has no printf builtin so it does whatever `command printf` does. Which is one thing on BSD and another with gprintf.

**Comment by floam** [comment]
And I wouldn't blame @siteshwar - AFAIK we brought the printf in from GNU and they are responsible.

**Comment by floam** [comment]
```
env LC_NUMERIC=fr_FR-UTF.8 /usr/local/bin/gprintf "%e" 1,23
gprintf: '1,23': value not completely converted
1.000000e+00

env LC_NUMERIC=fr_FR-UTF.8 /usr/bin/printf "%e" 1,23
printf: 1,23: not completely converted
1.000000e+00
```

**Comment by krader1961** [comment]
Go to bed, @floam. Locale `fr_FR-UTF.8 ` isn't valid on macOS. What is happening in your latest examples is the printf locale is defaulting to C because you specified an invalid locale.

I'm going to implement my earlier suggestion to first attempt the conversion using the user locale and if that fails then try using the C locale.

**Comment by floam** [comment]
Ah, damn it.

**Comment by floam** [comment]
It's unfortunate that `bc` will not give output that will have the radix per the locale for us - but I'd prefer we monkeypatch that to be better if we want to do something before getting our own builtin.

> If that fails attempt to convert the string using the C locale. If that fails give up.

I don't really like this. I'd prefer we just do the strict radix-by-LC_NUMERIC.

**Comment by krader1961** [comment]
Sigh. The `bc` command is a really bad example for fish to follow because it completely ignores the user locale. At least bc 1.06 that is shipped with macOS 10.12 (bleeding edge macOS Sierra). So does bc 1.06.95 on Ubuntu 16.04. Which, I think, makes my point. It also argues for why we should as soon as possible stop shelling out to `bc`.

Also, @floam, your last sentence referencing "radix" doesn't make much sense since the `LC_NUMERIC` var doesn't affect the radix of the value only the characters used to separate the decimal and thousands positions of the value. Having said that you seemingly contradicted your earlier comments which argued for the original behavior that only honored the "C" locale syntax for floating point strings.

**Comment by floam** [comment]
I mean, how do you avoid issues due to not failing, when you were actually given something that wasn't a number but is after we flip the locale on them?

Consider someone using printf in a shell script, to fix up some weather data in csv format from Europe, that has empty fields when there was no data, and REALLY should have been using a different a different delimiter `,,,22,5,19,5,22,0,22,1,,,,78` - I doubt he wants to think through whether or not that fallback will bite him. 

I don't think I want (when `radix=,`) for `printf \%e .5` to work any more than we want ",5" to work in the US. Plus, it gets us out of doing every failed conversion twice and having this locale change momentarily.

**Comment by floam** [comment]
What, that isn't the radix character? Geez. Whatever it is, then!

**Comment by floam** [comment]
> which argued for the original behavior that only honored the "C" locale syntax for floating point strings.

I'm not arguing for that - not since finding out my initial guess about LC_CTYPE was wrong.

**Comment by floam** [comment]
> Sigh. The bc command is a really bad example for fish to follow because it completely ignores the user locale. At least bc 1.06 that is shipped with macOS 10.12 (bleeding edge macOS Sierra). So does bc 1.06.95 on Ubuntu 16.04. Which, I think, makes my point. It also argues for why we should as soon as possible stop shelling out to bc.

I checked brand new bc on my Linux machine, where it's brand new, same thing. They wrote the standard for `bc` as well and that's how it should work, apparently.

**Comment by krader1961** [comment]
"Radix" means the base of the system of numeration. That is, radix 10 is the same as base 10. There might be people, like yourself, who use it to mean the printed representation, including separating characters such as "," and ".", but that isn't the generally accepted definition AFAICT.

You now seem to be [arguing for changing the behavior for converting floating point literals](https://github.com/fish-shell/fish-shell/issues/3334#issuecomment-243337019) to their binary form. Whereas up to this point your were arguing the opposite.

Also, your reference to [parsing CSV output](https://github.com/fish-shell/fish-shell/issues/3334#issuecomment-243337019) in that comment is irrelevant to this issue. At least as your phrased the issue. It is, however, relevant to my point that the relevant locale standards are useless with regard to this issue.

**Comment by floam** [comment]
It's not about CSVs - that's an example I contrived because sometimes it can be useful to help to gauge how abstract or plausible in the real world a hypothetical might be.

My understanding of the fallback idea is that the radix character it would try to use can mysteriously change to '.' from the one defined by `LC_NUMERIC` anytime there is a failure, and our `printf` would again under different parameters. When this happens on, say, invokation # 56 in a script after 55 successful calls - it seems certain to me that it's probably not helping to succeed, and it's worse than just doing it in a locale-deaf, *wrong* way consistently. 

... Unless it totally breaks everything for people in Europe. I'd guess it won't, and either software is good about setting the locale it needs momentarily and setting it back, or they just en_US for `LC_NUMERIC` on login shells.
