### ISSUE TITLE
creates empty file when executing make

### ISSUE THREAD

**Issue by GitRASQ** [fish-shell/fish-shell#3335]
2.3.1 on konsole / yakuake

fish creates an empty file named '1' in current directory when executing `make`.
`hello.cpp`:

     #include <iostream>
     int main() { std::cout << "hello \n"; }

`makefile`:

      hello:

About as simple as it gets. Entering 'make' in fish creates two files: an executable 'hello' and an empty file '1'. The empty file is also created when using 'make clean' with another makefile with clean rule. Bash makes only the executable.

edit: An easier way to reproduce: 
$ cd /tmp
$ make
make gives an error 'no makefile found' and there is now an empty file /tmp/1

**Comment by faho** [comment]
- Have you tried without your customization - it's possible a prompt function or similar of yours has a bug
- What's the output of `type make`?

**Comment by krader1961** [comment]
I can't reproduce this. Nor can I imagine any way in which a plain vanilla fish installation would cause this to happen. As @faho points out this is almost certainly due to customization of your fish environment. Also, with that makefile `make` itself will use /bin/sh to run subcommands. So as @faho points out you've either got a custom fish function named `make`, your prompt is creating that empty file, or perhaps you've defined a `--on-event fish_preexec` or `--on-event fish-postexec` function that is causing this behavior.

**Comment by GitRASQ** [comment]
Sorry, this was caused by a poorly written alias for make.
