### ISSUE TITLE
Slash-stripping rsync function breaks rsync completion

### ISSUE THREAD

**Issue by ivan** [fish-shell/fish-shell#3337]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

(Yes, it works without customizations, but this is a useful customization!)

**fish version installed** _(`fish --version`)_: 2.3.1

**OS/terminal used**: Ubuntu 16.04.1, roxterm

If you use an rsync function that strips trailing slashes:

``` fish
# rsync, like BSD cp, interprets trailing slashes as "copy the contents of this
# directory".  But this interacts very badly with fish, which, unlike zsh, always
# adds a trailing slash when you complete a directory.  This rsync function
# fixes this behavior by stripping all trailing slashes.  You can still copy the
# contents of a directory by appending "/." instead of "/".
function rsync --wraps rsync
    for arg in $argv
        # Strip trailing slash on "hi/" but not "/"
        set fixed_arg (echo -n $arg | string replace -r '(.)/$' '$1')
        set new_argv $new_argv $fixed_arg
    end
    command rsync $new_argv
end
```

then fish's built-in tab completion for `rsync` breaks: completing a remote `dir/` will insert `dir/` again instead of matching the files in the directory.  This happens because [completions/rsync.fish](https://github.com/fish-shell/fish-shell/blob/3e30857e994c26db028da72e14a0f68fce15f174/share/completions/rsync.fish#L132) runs `rsync` (going through the user function) instead of `command rsync`.

It seems like other user functions could also interfere with tab-completion working properly, like aliases for the `sed`, `tr`, and `cut` commands.

**Comment by krader1961** [comment]
First, you don't need the `echo -n $arg`; just do `(string replace -r '(.)/$' '$1' $arg)`. Also, you should really add a `set -l new_argv` at the top of the function and do `set -l fixed_arg` so that your vars don't leak into the global scope.

As for the core of your issue I'm pretty confident we don't want to preface the use of every external command with `command` in the completion scripts. If you write such a function it's your responsibility to ensure it behaves reasonably. We want completions to work for functions and external commands. A `complete -c rsync` does not mean "an external command named rsync". It means a command, which could be a fish function, named rsync. I'll let people with more experience writing completions, such as @faho, opine on this rather than close it but I'll be surprised if they disagree with what I said.

**Comment by floam** [comment]
It seems to me that if a function is likely to be wrapped a completion would be wise to use `command`. We don't know of any things that *aren't* rsync commands people might use that this could mess up, right? 

If I understand correctly this seems safe and fine:

```patch
diff --git 1/usr/local/share/fish/completions/rsync.fish 2/fish-shell/share/completions/rsync.fish
index 6447075..26bf009 100644
--- 1/usr/local/share/fish/completions/rsync.fish
+++ 2/fish-shell/share/completions/rsync.fish
@@ -129,6 +129,6 @@ complete -c rsync -d "Remote path" -n "commandline -ct| __fish_sgrep -q :" -a "
        commandline -ct| __fish_sgrep -Eo '.*:+(.*/)?'
 )(
        #Get the list of remote files from the specified rsync server
-       rsync --list-only (commandline -ct| __fish_sgrep -Eo '.*:+(.*/)?') ^/dev/null | sed '/^d/ s,\$,/, ' | tr -s ' '| cut -d' ' -f 5-
+       command rsync --list-only (commandline -ct| __fish_sgrep -Eo '.*:+(.*/)?') ^/dev/null | sed '/^d/ s,\$,/, ' | tr -s ' '| cut -d' ' -f 5-
 )
 "

It'd obviously make it easier for this guy to work around this. Other functions may not be so cut and dry.

**Comment by floam** [comment]
To make sure: did you try guarding the changes that your wrapper commands make, first? 

I'd wonder if checking some combination of `status --is-command-substitution`, `status --is-block`,  and/or `status --is-interactive` to turn your behavior on in the first place might better avoid this.

**Comment by faho** [comment]
First of all, let me say that I'm not a big fan of aliases with the same name that do something more than e.g. "--color=auto" (which really should be the default) - a change that only changes the output, and then only when it goes to the terminal.

They are bound to cause issues, not only like this but also when you get used to the behavior and then use the command on another machine - because the command then does something different than you are used to.

Might I suggest renaming the aiias to e.g. "rs" - which is also a few characters shorter. In other cases I'd suggest an abbreviation, but I can't see that working here.

---

Now to the issue at hand. It's clear that people want this particular behavior. I've heard of it before, there's even been talk on the rsync list about adding an option.

We actually already have a completion script where we use `command` everywhere - the git completions. The case there was that people might want to type `git` but get `hub` instead. In that case, @ridiculousfish added it (see #622) because of performance issues.

See also #3117, where someone wants us to explicitly _not_ use `command` because they don't want the version in their $PATH.

This is kind of a tough decision because whatever we do, we're going to break _something_, so we need to decide what is more likely and more worthy of our support.

If we use `command`, then we'll break both a certain set of wrapping functions that might even enhance the completions, and the case of someone explicitly using a different tool than is in $PATH.

If we don't, we break wrapping functions that change behavior in ways we cannot predict and possible script reimplementations of tools. And another case that _might_ be common: Especially on OSX, the default tools are BSD-derived and in certain cases surprisingly limited, so one might want to install the gnu versions of those and then use an alias to use them without breaking system usage that expects the BSD tools (though for the most part the GNU versions accept supersets of the BSD versions' arguments).

Now the question here is what is more common? I actually cannot come up with an example of an alias that would lead to better completions, and the case of using a different tool than is in your PATH, under the same name, should be reasonably uncommon (and even when you use it, most things are probably compatible).

Coming up with an example of a breaking alias is much easier because we have one right in front of us.

In short, this would be a change to protect our users because they are likely to not get this right. It's still better for them to do so (because of scripts from _other_ users that don't do this). See also #2324, in which we also avoided using something that might be an alias.

So, for those reasons, I'm actually in favor of adding `command`, at least on a best-effort basis, unless we can find a reason not to in a particular case.


> I'll let people with more experience writing completions, such as @faho, opine on this rather than close it but I'll be surprised if they disagree with what I said.

@krader1961: Sorry to surprise you. I hope my argument at least makes sense.

----

I've got a change to the rsync completions in the pipeline anyway to switch it over to `string`, which will eventually allow us to ditch that annoying "__fish_sgrep" function, but I need some testers.

@ivan: I've opened #3338. Mind testing it?

**Comment by krader1961** [comment]
@faho Your argument is defensible but I am surprised by it and disagree.

Let's start with the example you cited regarding the git completions. If someone defines a `git` function that wraps `hub` it seems to me they want the `hub` behavior. Including any additional latency that adds. I use `hub` but deliberately did not make it an alias for `git` because I don't a) trust that it is transparent for non Github behavior and b) didn't want to incur its costs for non Github interactions. The fact it adds noticeable latency for non Github interactions (at least for some users) tells me no one should be using it as a transparent wrapper for the `git` command.

I do not believe it is our place to protect people from the choices they make when it involves trivial matters like wrapper functions that increase latency. We should only be implementing such protective measures when a) it doesn't limit functionality and b) the consequences of not doing so result in an unusable shell. Which does not include a slightly slower shell.

I'm reminded of my experiences with Microsoft MS-DOS/Windows many years ago. It explicitly differentiated between a script (ending in a `.bat` extension) and binary programs. That is a huge design mistake. UNIX got this right. It doesn't matter if the "program" is a shell script or a binary compiled from a language like C. Which means it shouldn't matter if the program is a shell function. And thus our completions shouldn't try to distinguish between those cases.

Consider the fish `history` command. This is a contrived example but should the completions only run `builtin history`? Yes, I recognize those completions do not invoke the history command/function/builtin. My point is that the `history` completions shouldn't have to specify `command` or `builtin` to avoid invoking the function by that name if they needed to do so.

**Comment by floam** [comment]
So what you you do differently?

**Comment by faho** [comment]
> If someone defines a git function that wraps hub it seems to me they want the hub behavior. Including any additional latency that adds.

That's false. Nobody _wants_ additional latency, and nobody wants breakage.

Like I said, you might want a _change_ in behavior (i.e. showing different, but still correct, things), but I can't actually come up with an example where that works. And if I did, it would still be the minority of cases.

Especially considering rsync - look through the man page and tell me which option you could add to all our rsync calls in the completions while still keeping correctness.

Let me go through a few:

- `--verbose` is likely to break since it would produce a different kind of output (this also applies to `--info`, `--debug` and `--quiet`)
- `--no-motd` we probably should be using anyway
- `--checksum` and `--archive` shouldn't change anything
- `--recursive` is likely to break (remember the case of `alias grep='grep -r'`?)
- Ditto for `--relative`

**Comment by krader1961** [comment]
> Nobody wants additional latency

You're right, of course, I worded that poorly. What I meant to say was that if someone renamed `hub` to `git` (or created a wrapper function) then presumably they understand that non-Github interactions may be slower and accept that as a cost of getting the additional features. I obviously did not mean to imply people want such operations to be slower.

I think there's a very fuzzy line between giving people enough rope to hang themselves (e.g., the ability to easily alter command behavior by creating a wrapper function) and actively helping them hang themselves. Also, it should be obvious that even prefacing each such invocation with `command` is no guarantee the external command will behave as the completion expects. The user may have an incompatible binary installed or have created a script in *~/bin* rather than a function of the same name.

My `history` wrapper was not a good example as there are likely to be good reasons for a completion to use `builtin` or `command` to avoid problems. But it's not at all clear we're making the right tradeoff by using`command` every place a completion invokes what we expect to be an external command. I'd prefer we provide a simple mechanism that a fish script can use to detect that it's being run from a completion so it can decide whether to simply pass thru to the external command in that situation. Something similar to `if isatty 1` that a fish script can use to decide how to mangle the output or whether to automatically send it through the user's pager.

**Comment by faho** [comment]
>I obviously did not mean to imply people want such operations to be slower.

Okay.

>they understand that non-Github interactions may be slower and accept that as a cost of getting the additional features.

The assumption is that, in the completions, they aren't getting additional features. So why pay the cost? (Of course if there were a way to get additional features...)

>I think there's a very fuzzy line between giving people enough rope to hang themselves (e.g., the ability to easily alter command behavior by creating a wrapper function) and actively helping them hang themselves.

In the spirit of the metaphor, we should be giving people knives, because you can use those to make a sandwhich. We should not be giving them live landmines.

What I mean by that is if there's "no way" something could be useful we should not be offering it.

>Also, it should be obvious that even prefacing each such invocation with command is no guarantee the external command will behave as the completion expects. The user may have an incompatible binary installed or have created a script in ~/bin rather than a function of the same name.

Of course, but the _chance_ of it succeeding is higher. As I aluded to before, nobody is going to have a compatible fish script reimplementation of rsync (we lack /dev/tcp).

>But it's not at all clear we're making the right tradeoff by usingcommand every place a completion invokes what we expect to be an external command

Not every place. I don't want to make this a hard rule. But in this case it seems like it.

>I'd prefer we provide a simple mechanism that a fish script can use to detect that it's being run from a completion so it can decide whether to simply pass thru to the external command in that situation. Something similar to if isatty 1 that a fish script can use to decide how to mangle the output or whether to automatically send it through the user's pager.

Like `status --is-command-substitution`? I'm actually not sure if that (correctly IMHO) returns true when called in a completion.

@ivan:

Can you try

```fish
function rsync --wraps rsync
    if status --is-command-substitution
         command rsync $argv
         return $status
    end

    for arg in $argv
        # Strip trailing slash on "hi/" but not "/"
        set fixed_arg (echo -n $arg | string replace -r '(.)/$' '$1')
        set new_argv $new_argv $fixed_arg
    end
    command rsync $new_argv
end
```

**Comment by ivan** [comment]
Very interesting, and thanks, that `if status --is-command-substitution` check does work and fixes the tab-completion.

**Comment by krader1961** [comment]
Using `if status --is-command-substitution` is an interesting solution. It didn't occur to me that would be true in this context but now that I think about it I'm not surprised. Presumably that expression is also true when executed by a key binding. In as much as these types of wrapper scripts are almost always, in my experience, meant to only modify interactive invocations of the command it seems reasonable to use that technique, probably in conjunction with `or not status --is-interactive`, to guard against the wrapper interfering with scripted invocations.

It seems reasonable to update the documentation to make it clear that expression is true in those contexts. If we don't already have them we should also add unit tests to ensure we don't inadvertently change this behavior in those contexts. Lastly, add verbiage, including your example, @faho, to the documentation explaining why doing this is a "best practice". I'd rather do that than pepper our completions (and key bindings) with `command`.

> As I aluded to before, nobody is going to have a compatible fish script reimplementation of rsync

True but the O.P. might have written their wrapper as a script rather than a function in which case using `command` wouldn't have helped.

> What I mean by that is if there's "no way" something could be useful we should not be offering it.

No argument. But how do we know that using hub in the git completions (because they installed hub as *~/bin/git*) isn't useful? Obviously, that's just a specific instance of the more general question.

**Comment by faho** [comment]
>Presumably that expression is also true when executed by a key binding

Unfortunately, it isn't. And that's currently actually correct - when executing keybindings, the output currently ends up in the terminal at the cursor's position, visually breaking the prompt. It might be better to either always redraw the prompt after any keybinding that produces output (keeping the commandline intact), or to always put the output into the commandline (in essence wrapping any binding inside `commandline -i -- ($function)` automatically.

In the latter case, `status -c` would of course work.

The question here is if it is worth detecting whether something is inside a command substitution but _not_ a completion or keybinding.

> No argument. But how do we know that using hub in the git completions (because they installed hub as ~/bin/git) isn't useful? Obviously, that's just a specific instance of the more general question.

I can't answer this in general (and I'm not sure anybody can). In that specific case it appears to not be useful, so we decided to not allow it. If and when someone comes up with a way it can be useful, we can rethink that decision.

**Comment by ivan** [comment]
I discovered another one of my aliases breaking a different tab completion, this time for `ls` (but only in some cases):

```fish
alias ls='env LC_COLLATE=C ls'

mkdir empty
cd empty
touch uptimefile
ls uptime<TAB>
```

completes `uptime` instead of `uptimefile`.  (Assuming you have an `uptime` binary installed.  If not, try another binary that is not the prefix of a longer binary.)

**Comment by faho** [comment]
>I discovered another one of my aliases breaking a different tab completion, this time for ls (but only in some cases):

That's a different case. `alias` sets up completions so that the script for the called command will be used. The called command in this case is `env`. That means instead of calling the ls completions, it'll call the env completions.

I suggest defining this as a function - which would also let you get rid of the `env` call with `set -lx LC_COLLATE C`.

**Comment by faho** [comment]
Alright, this isn't happening. I recommend naming your alias something else.

Sorry.
