### ISSUE TITLE
Unable to build master branch under CentOS 6.8

### ISSUE THREAD

**Issue by SchweinDeBurg** [fish-shell/fish-shell#3347]
I've tried the following values of TERM: xterm, xterm-256color, xterm-8bit, linux, linux-c. And there is always SEC-sequenses errors.

**Comment by faho** [comment]
Which commit have you been trying to build?

**Comment by faho** [comment]
And what is the actual error message? Weird escape sequences should make for weird output, not a broken build.

**Comment by floam** [comment]
I had broke it right before I left to work. I pulled over and broke it some more before I finally fixed it. It's times like this I wish I could `git push --force` all traces of my dysfunction away.  

Can you try again with a very fresh master?

**Comment by SchweinDeBurg** [comment]
```
[elijah@santiago ~]$ echo $TERM
xterm-256color
```
All output looks fine, rpmbuild succeeded.

```
[elijah@santiago ~]$ echo $TERM
linux
```
Almost everything looks as expected for 8-ocolor terminal except "black on black" in the "Run  make install to install fish." in place of "make install"? rpmbuild succeeded.

**Comment by faho** [comment]
@SchweinDeBurg: That part of the line uses two escape sequences: 

- `tput setaf 11`

and

- `tput setab 0`.

I'd wager that the former (which makes the foreground yellow) doesn't work - because 11 > 8, and a "linux" TERM supports 8 colors.

Though that is still weird, because in an actual linux VT, this line just prints in the default "white" for me, i.e. the sequences are ignored.

Which kernel version are you on?

**Comment by krader1961** [comment]
At this point I am confused by the issue summary. It states that you cannot build fish but the problem seems to be that the `make fish` output is hard to read yet you do get a working fish program. Is that correct?

Also, are you still having problems reading the output of `make fish` with $TERM set to values such as "xterm-256color" if you sync to the current git head? That assumes, of course, that TERM value is valid for the terminal you are using.

Are you still having problems reading the output if TERM is set to "linux" and you're actually using a Linux VT console? On my Ubuntu 16.04 server instance (kernel 4.4.0-36-generic) I had no difficulty reading the output of `make fish` on the primary console VT with TERM set to "linux".

**Comment by floam** [comment]
I adjusted the Makefile to never use colors over 8 a couple days ago. Did that fix it, whatever it was?

**Comment by zanchey** [comment]
No response and there's a solution for the best guess at the problem; closing this for now but feel free to reopen if it's still a problem!
