### ISSUE TITLE
New release, it's that time again

### ISSUE THREAD

**Issue by maxnordlund** [fish-shell/fish-shell#3364]
Hello, like before in #2760 I noticed that master is [~500 commits ahead](https://github.com/fish-shell/fish-shell/compare/2.3.1...master) and thought it might be time for an update. Last time it took around 3 months, so I figured starting the process now would be a good idea.

The [2.4.0 milestone](https://github.com/fish-shell/fish-shell/milestones/fish%202.4.0) has only 2 issues left, but the [next-2.x](https://github.com/fish-shell/fish-shell/milestones/next-2.x) has, as of writing this, 37. I'm not sure which ones are the most important, but like the last this could be used as an tracking issue.

**Comment by faho** [comment]
We've already discussed this. The "2.4.0" milestone is set to run out at the end of the month, so we'll release then.

The way we're doing it now is that 2.4.0 includes stuff that is already done or should _definitely_ be done, next-2.x is stuff that would be nice for 2.4.0 but can also be done later.

Personally, I'd really like #3260 to go in, and to find an actual solution for https://github.com/fish-shell/fish-shell/pull/3068#issuecomment-245864234 (since what I did previously was broken).

I don't really see any blockers, though.

**Comment by maxnordlund** [comment]
Nice, just curious where would one find such a discussion? Apparently my search-fu isn't strong enough.

**Comment by faho** [comment]
That was in our super-secret private gitter room, so your search-fu doesn't have anything to do with it.

**Comment by maxnordlund** [comment]
Ah, I feel much better now 😉

**Comment by zanchey** [comment]
Yes, there's no reason for the discussion to be secret. I want to try and avoid the 2.3.0 cherry-picking debacle this time around. I'll roll the beta towards the end of the month; I wanted to have the new release infrastructure sorted by now but hopefully the pain of the release process will help remind me why I wanted to do that!

**Comment by z3ntu** [comment]
Any update on the new release?

**Comment by zanchey** [comment]
I'm going to make a start tonight.

**Comment by Clowting** [comment]
Uhm, any new updates on the release, or did it get pushed back?

**Comment by krader1961** [comment]
It's in progress. There were some hiccups because we noticed, for example, that the thread sanitizer tests hadn't been running for a long time. We wanted to get those re-enabled to ensure we hadn't introduced any bugs it might have caught. And, sure enough, it brought to light a "use after free" bug that I introduced a couple of months ago. That's been fixed and a couple more history enhancements have been merged. There should be a 2.4.0 integration branch created later today.

**Comment by floam** [comment]
There's been an Integration_2.4.0 branch for a couple days now.

**Comment by z3ntu** [comment]
Again: Any news?

**Comment by zanchey** [comment]
fish 2.4.0 is out!
