### ISSUE TITLE
Idea: Command to change relative paths to absolute paths

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#3368]
Sometimes I run a long-running command in a directory that moves or rsyncs files around, but interrupt it before it's done.  Later I may re-run it from history, but I might end up doing it from a different working directory.  To fix that, I have to either change to the directory I ran the command from, or fix the paths.

It would be really handy if Fish had a command that could convert relative paths on the command line to absolute ones.  Ideally it could be bound to a key so that I could type in a command, realize that it would be more useful if the paths were absolute, and press something like Alt+A and have Fish convert the paths to absolute ones.  Then when I executed the command, it would be stored in the history with absolute paths.

**Comment by jinliu** [comment]
Try this:
```
function to-realpath --description 'Convert the path under cursor to absolute version'
        set t (commandline -t)
        if test -n $t
                commandline -t (realpath $t)
        end
end

bind \ea to-realpath
```

**Comment by faho** [comment]
We actually ship a `fish_realpath` builtin (because the realpath command on some systems is too limited for our internal use).

@jinli's proposal would work with that.

I'm not sure if it should be bound to a key by default since these kinds of things aren't discovered often - did you know that alt+h shows the man page for the current command? Or that alt+p inserts `^&1 | less` after the command?

**Comment by jinliu** [comment]
@faho but, quote help fish_realpath:
> In general scripts shouldn't invoke this directly. They should just use realpath which will fallback to this builtin if an external command cannot be found.

BTW, about the discoverability thing, how about show the "did you know ..." as some form of hint, when the first time the user enters "man ..." or a command producing many pages of output?

**Comment by alphapapa** [comment]
@jinliu Thanks, it should have occurred to me that I could already do this!  Here's what I came up with, which seems to do exactly what I want:

```fish
function commandline-paths-to-absolute
      set -l tokens (commandline --tokenize)
      set -l new_tokens
      for token in $tokens
          if test -e $token
              set new_tokens $new_tokens (readlink -m $token)
          else
              set new_tokens $new_tokens $token
          end
      end
      commandline -r (echo $new_tokens | tr '\n' ' ')
  end

bind \ea commandline-paths-to-absolute
```

I'm not sure, but it seems like `readlink` is installed by default, while on some systems or distros `realpath` is not.

**Comment by krader1961** [comment]
The proposed enhancement is impractical. It would also cause more problems than it solves. There is no way for fish to know which portions of a command line retrieved from history represents relative path names and thus should be magically converted to absolute paths. Furthermore, there is no way to know that even if we did that conversion the results would be sensible given the current working directory and the command being run.

I do agree that fish should record the cwd in its command history and provide a way to see that value when doing a `history search`. That is being discussed in issue #3373.

What I find interesting is that comments on this issue, including one by @alphapapa, imply that all that is needed is a way to press a key to convert a relative path to an absolute path based on the cwd. Yet that is not what was requested in the original comment when this issue was opened.

**Comment by alphapapa** [comment]
> The proposed enhancement is impractical. It would also cause more problems than it solves.

Would you please give an example of how it would cause a problem? 

> There is no way for fish to know which portions of a command line retrieved from history represents relative path names and thus should be magically converted to absolute paths.

I don't understand what you mean.  The function in the code above does exactly that, and it works fine.  `test -e` tests whether the token is an existing file or directory.  There's nothing magical about it.

> Furthermore, there is no way to know that even if we did that conversion the results would be sensible given the current working directory and the command being run.

I don't think this is correct.  The point is to change relative paths to absolute ones; after doing that, the cwd doesn't matter.  That's the whole point of this idea.

> What I find interesting is that comments on this issue, including one by @alphapapa, imply that all that is needed is a way to press a key to convert a relative path to an absolute path based on the cwd. Yet that is not what was requested in the original comment when this issue was opened.

I don't understand what you find interesting.  The original request was exactly that:

> It would be really handy if Fish had a command that could convert relative paths on the command line to absolute ones.

**Comment by krader1961** [comment]
@alphapapa, What I find interesting is that your original proposal was to convert those relative paths to absolute paths based on the most recent cwd of the command. Yet subsequent comments, including yours, completely ignored that aspect of the issue. Those comments focused on ways to interactively convert relative paths to absolute paths based on the cwd rather than the cwd of the previous execution of the command.

Furthermore, your comments on issue #3373, show that you are still not thinking clearly about what you want with respect to this issue.

**Comment by alphapapa** [comment]
@krader1961 You assume some kind of strange false dichotomy, that I must want either one or the other.  Both would be useful.  

You are imagining an inconsistency of thought which does not exist; you merely do not understand the discussion.  You are keen to blame others for a perceived lack of thinking or communication skills, while you yourself fail to understand what is said.  Other people simply ask for clarification if they do not understand, while you take it upon yourself to correct flaws in others which are of your own imagination.  I don't know what you get out of it; perhaps a sense of superiority in your condescending to bestow your wisdom upon lessers.  

I have observed this attitude from you for some time now.  It would behoove yourself and the project if you refrained from this in the future.  You are technically quite competent, but your interactions with others leave much to be desired.
