### ISSUE TITLE
`fish_realpath` is lacking

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3370]
fish_realpath has *zero* of the options one might expect from the realpath command. One useful option we currently aren't implementing is `--logical/-L`. I played with our builtin for a few minutes and it doesn't seem like we have this one up to snuff:

```console
> ls -F /etc/
lrwxr-xr-x@ 1 root  wheel    11B Sep 11 04:06 /etc@ -> private/etc
> grealpath -L /etc/.. /private/etc/.. /..
/
/private
> realpath -L /etc/.. /private/etc/.. /..
/private
```

Fish can't do it - worse, **it only accepts a single path** and isn't giving any hint of error when it's unable to do what the user requested. Maybe this should only be available as `fish_realpath` by getting rid of the wrapper until we can provide a proper implementation, like we managed with our `test` or `printf`.

**Comment by faho** [comment]
The original discussion that lead to this is in #2932.

The way our `realpath` is implemented currently means that the function isn't even defined if the system has a command by that name. The idea behind that is that resolving paths is a common task that hits pain points in some operating systems (specifically OSX), so we should ship a simple implementation of that. An implementation that does only what is necessary and available across all other implementations (if possible).

Since my system uses GNU tools, I don't have a simple implementation. I have the full thing, kitchen sink and all. Let me quote the help output:

>Usage: realpath [OPTION]... FILE...
Print the resolved absolute file name;
all but the last component must exist

>  -e, --canonicalize-existing  all components of the path must exist
  -m, --canonicalize-missing   no path components need exist or be a directory
  -L, --logical                resolve '..' components before symlinks
  -P, --physical               resolve symlinks as encountered (default)
  -q, --quiet                  suppress most error messages
      --relative-to=FILE       print the resolved path relative to FILE
      --relative-base=FILE     print absolute paths unless paths below FILE
  -s, --strip, --no-symlinks   don't expand symlinks
  -z, --zero                   end each output line with NUL, not newline

> --help     display this help and exit
   --version  output version information and exit

Which one of those are you proposing to implement?

To me this seems like a policy decision: How much should we defer to the OS?

**Comment by floam** [comment]
It seems like it is unlikely it would work as an effective fallback for that command currently - very handy to have a binding to the realpath system call available in fish- but I'm not sure it helps much if it's intended to fix up scripts on OS X machines that want the realpath command. 

I'm proposing it should probably do `-L` and `-P` (it effectively is doing -P always now).  So it needs to learn how to do `-L`.

What was problematic and led to report this issue is the output up above. This should be fixed: it is currently only giving a result for the first directory you give it, and the arguments given to it do not have any effect on anything, it will give you a good exit code and some output even if it can't do it.

**Comment by floam** [comment]
I mean hell, why didn't we call it `readlink`? It's a lot closer to that than realpath.

**Comment by faho** [comment]
>What was problematic and led to report this issue is the output up above. This should be fixed: it is currently only giving a result for the first directory you give it, and the arguments given to it do not have any effect on anything, it will give you a good exit code and some output even if it can't do it.

The wrapper function only passes $argv[-1]. The actual builtin `fish_realpath` fails if given more than one argument. Would that be acceptable?

**Comment by faho** [comment]
>I mean hell, why didn't we call it readlink? It's a lot closer to that than realpath.

It's not. readlink only resolves the last component, and only prints output if it is a link (unless given "-f").

**Comment by floam** [comment]
Good point.

**Comment by floam** [comment]
BSD realpath:

http://ftp.stu.edu.tw/pub/BSD/FreeBSD/branches/-current/src/bin/realpath/

**Comment by floam** [comment]
And it does not implement -L - which is actually the thing I wanted, to try to teach my prompt to take directory history into account to show me the symbolic link instead of the resolved filesystem path. It seems to me like realpath in fish would be not as handy a tool as in other shells. Where do we use it?

**Comment by floam** [comment]
Also, it is actually implementing a quite particular mode of operation through the GNU tool, not the default BSD or GNU behavior: `--canonicalize-existing`. 

> An implementation of the external realpath command that doesn't support any options. It's meant to be used only by scripts which need to be portable

It seems to me if I were writing a portable script we have given a further reason to stay the hell away from realpath, if we might silently substitute this ... special builtin of ours in for `command realpath`.

**Comment by krader1961** [comment]
FWIW, I couldn't find a single instance of `realpath` being invoked with any flags on my macOS or Ubuntu 16.04 servers by doing `grep 'realpath -'` on all regular files. Both at the time I implemented the `fish_realpath` builtin and now. Which is why our implementation is extremely limited in its capabilities. That very simple implementation seems to address the vast, nearing 100%, of the use cases I could find.

Similarly, all the uses I could find involve resolving a single path. So it there didn't seem to be much point in complicating the implementation to handle multiple paths.

Searching Google for uses of those flags, or multiple paths, is borderline useless. Nonetheless I made an attempt to do so and couldn't find any.

Obviously since those options were implemented someone needed them to solve a problem. But it appears those problems are extremely rare in actual practice and thus the use of those advanced capabilities is also extremely rare. So I'm a trifle annoyed at your tone of voice, @floam, in suggesting that the `fish_realpath` implementation is borderline useless because it doesn't implement those features.

A core fish project goal is to implement as little functionality as we can get away with while still providing a usable shell that people will want to use (something @faho alluded to earlier in this issue). It's not at all obvious that fish should have a builtin `realpath` that mirrors the GNU, or any other flavor, of that command in all its flags and behaviors. If you need the `realpath -L` behavior why not simply `brew install coreutils` and use that version? I don't believe you have made a good argument for adding more code to the fish project in order to implement our own version of that command.

**Comment by floam** [comment]
>It's not. readlink only resolves the last component, and only prints output if it is a link (unless given "-f").
> readlink -f /tmp/adobegc.log 
/private/tmp/adobegc.log

**Comment by floam** [comment]
@krader1961

I did that same grep and also couldn’t find more than 2 or 3 actual shell scripts on my computer using --options with realpath. I don’t find many real-world uses is the truth, actually, which makes sense on OS X.

What I mean by handling arguments, is it should refuse to run when called without the argument we emulate, we do not emulate bare readlink.

`realpath --canonicalize-existing’ /single_directory.

What I also see in these results is a theme of using it to construct configuration/installation file paths that don’t yet exist.

The most common `realpath` pattern where it looks like fish’s builtin could probably work, because it’s working on paths where the last component exists already: often glossing a bunch of files at once. Can’t work there.

I want to exorcise it - I know you can relate. 

I understand it’s shipped with fish for a few releases now, and so I am resigned to the fact we'r probably stuck with it. If that's the case, let's provide a high quality function.

**Comment by krader1961** [comment]
> find more than 2 or 3 actual shell scripts on my computer using --options with realpath

Please add those uses to this issue so we have some idea why implementing those flags would be useful. I'm particularly interested if your "computer" is running macOS/OS X since it doesn't have a realpath command and any use of it presumably is from HomeBrew packages which would require that GNU coreutils package to be installed.

> I know you can relate.

No, I cannot because what you just wrote appears to be word salad worthy of Sarah Palin. 

The only reason we implemented `fish_realpath` is so that uses in fish scripts would work on systems without an external realpath command. AFAICT those uses are so unlikely to use any of the GNU realpath flags that we can safely ignore them. If that assessment is incorrect I am more than happy to be corrected but you need to provide at least a couple of examples.

I agree that the fish fallback implementation should check that it is not being called with flags or arguments it doesn't understand (which, at this juncture, is any flags or more than one path). It's not clear if that was one of your points.

**Comment by floam** [comment]
Sure, here's some of my output. 

./Users/floam/Downloads/MacPin-master/eXcode.mk:	mkdir $(dir $@)/lib$*; cd $(dir $@)/lib$*; for i in $(realpath $^); do \
./Users/floam/Downloads/MacPin-master/Makefile:ZIP			 := $(realpath $(outdir))/$(REPO)-$(platform)-$(arch).zip
./Users/floam/Downloads/MacPin-master/Makefile:		--compress-pngs --compile $(dir $@) $(realpath $<)
./Users/floam/Downloads/MacPin-master/Makefile:		--compress-pngs --compile $(dir $@) $(realpath $(filter %.xcassets, $^))

**Comment by floam** [comment]
Or, some "config" plugin maybe. Still, I rest my case.

**Comment by floam** [comment]
And as far as during installs, if it wasn't clear, what people will often try to use the tool for is to get an absolute path so that they can safely make a symlink. Which doesn't exist yet but normally that's fine for the last path component in realpath.

```
[ -d ~/.config  ] || mkdir -p ~/.config
[ -L ~/.config/omf  ] || ln -svf $(realpath ./omf)/ ~/.config/omf/
```

**Comment by faho** [comment]
>people will often try to use the tool for is to get an absolute path so that they can use the output as an argument to ln to make a symlink. That's broken on our mode we implemented. 

Can you elaborate on that? In your example, all components _do_ exist. And when you use it for the target argument to "ln", that's what you usually want.

**Comment by floam** [comment]
> Can you elaborate on that? In your example, all components do exist

They do?

`[ -L ~/.config/omf  ] || ln -svf $(realpath ./omf)/ ~/.config/omf/`

~/.config/omf exists. It looks to me like `./omf` is not yet existing and this would break with the fish implementation. I'm probably missing something?

**Comment by faho** [comment]
Yes - the arguments to ln are the other way around - `ln TARGET LINK_NAME` or `ln TARGET... DIRECTORY`.

The "realpath ./omf" is what that link should be pointing _to_, and "~/.config/omf/" is where the link should _be_.

Of course you _could_ be making a link to something that doesn't exist yet, but that's not all that usual and I don't think that's happening here.

**Comment by floam** [comment]
You're absolutely right, that'll work fine.

**Comment by zanchey** [comment]
My understanding is that `fish_realpath` exists so that we have a wrapper for the `realpath(3)` system call available in shell scripts; nothing more.

**Comment by floam** [comment]
~/.config/omf is the default directory for OMF, no?

**Comment by floam** [comment]
> My understanding is that fish_realpath exists so that we have a wrapper for the realpath(3) system call available in shell scripts; nothing more.

Hm - What does that entail by "nothing more"? (there is no such system call but even if there were - what would that mean for a a fish utility?

**Comment by faho** [comment]
@floam: There is such a system call or library function at least on linux, and it mentions POSIX conformance (plus GNU extensions), so I'd expect it on BSD as well.

The "-e" btw isn't much of an issue - even though our tool does what "the real thing" only does with an option, in practice this only means that "the real thing" works _more_, not less. So there's no case where installing "the real thing" would _break_ anything. Our tool works in a subset of the cases that "the real thing" works in.

The behavior without that option is also easily achieved - resolve "/usr/local/share", and then add "/hypothetical".

-----

Like I initially said, this is a policy discussion in disguise. Of course some of the options that the GNU tools offer can be useful. But does that mean we should make versions of these that work everywhere, or should we leave it up to the OS developers to fix?

For some things, we've already added OS-independent tools. For example `string` helps paper over operating system inadequacies - we've had workarounds for BSD sed not allowing `\t` in the substitution expression that we no longer need with `string`. We've needed to use an option to grep that isn't actually documented for the GNU version.

But there are more reasons for `string`. It's often used in hot paths in scripts so forking less is a real performance improvement, it's also a bit simpler to use than some of the alternatives (and in some cases can even be more correct - try replacing in paths with `sed`. The delimiter can _always_ appear in the path).

In this case, the tool itself isn't used all that much, and not in tight loops of performance-critical scripts. And the additional options, while occasionally useful (I could use "--relative-to" in the git completions) are used even less.

Which leads me to believe that there's no real need to add this, so we shouldn't do it.

So let's examine another case of a tool that often has a rather limited version: `seq`. Should we add a `seq`? It's used more often (especially in our scripts), it has awkward alternatives (see #3372), I've seen it show up in profiles. A proper implementation is near-trivial.

**Comment by floam** [comment]
On OS X, realpath() is actually just C library function.

We used to ship `seq` -- I think we thought better of it after a while. Frankly though, that one certainly has a lot more going for it. Probably it'd be nice if we thought of something better than `seq` rather than emulate it. We had the right idea with shipping an actual binary, though.

**Comment by krader1961** [comment]
> Should we add a `seq`? 

Yes, albeit perhaps under a different name (`fseq`?). There have been so many issues where the difference in behavior of the various `seq` implementations (mostly involving negative increments or implicit counting down) that I think we would avoid many future bugs if we shipped a sane version. The most recent one is PR #3372.

> On OS X, realpath() is actually just the POSIX-defined C function and system utility. No help from the kernel exists or is needed AFAIK.

So what? 95% of what the GNU realpath(1) command does also doesn't require help from the kernel.

I noticed that your [earlier comment](https://github.com/fish-shell/fish-shell/issues/3370#issuecomment-246258002), @floam, makes my point that it is extremely unusual for any `realpath` invocation to pass any flags or more than one path. The one example you could find which uses a feature we don't support in our fallback implementation is from Oh-My-Fish. I'm moderately surprised no OMF user, or its maintainer, has complained to us that it doesn't work on macOS. Is it simply that there are no OMF users on macOS? Or is it the lack of support for `--relative-to` doesn't actually cause a problem for that use case?

**Comment by floam** [comment]
> Or is it the lack of support for --relative-to doesn't actually cause a problem for that use case?

It could be - who knows - it'd be a lucky accident if so

The point is we're not helping: To get predictable behavior, due to our builtin, a projects would, if they are wise, need to work around us - doing stuff **we** hate having to do: `command`-prefixing for one of our behaviors, leaving it out for the other - maybe just deciding to always fall back to working with readlink manually. Which would be unfortunate.

**Comment by floam** [comment]
> So what? 95% of what the GNU realpath(1) command does also doesn't require help from the kernel.

"so nothing" @krader1961  - I had found @zanchey's statement kind of mysterious and wanted some clarification - I made it clear that it wasn't the system call part I was asking about. 

> Hm - What does that entail by "nothing more"? (there is no such system call, but even if there
> were, what would that mean for a fish utility so designed?)

**Comment by floam** [comment]
> Which leads me to believe that there's no real need to add this, so we shouldn't do it.
> So let's examine another case of a tool that often has a rather limited version: seq. Should we add a seq? 

Wait, what?

The goal is not to add new features to fish's realpath. I want to remove the builtin from fish. It's used nowhere in our codebase (apart from test), I didn't imagine anyone was a fan of it. I started off discussion with the idea of renaming the function to no longer alias `fish_realpath` to `realpath` and have mentioned a few times more than I think I'd have to that I'd most prefer to just see it gone.

Responses have asked about features of GNU realpath, for examples of commands used in the real world we need to cover, etc. It seems like I'm repeatedly having to say for the record that I doubt it's worth improving.

> The behavior without that option is also easily achieved - resolve "/usr/local/share", and then add "/hypothetical".

Yes, it's easy to check the last bit and construct the path that way. We agree.

I brought up the examples of `-L`, and hypothetical paths not because I want them terribly bad, but because they're going to be the things that are tricky in fish. Nobody here seems to miss those features. So,

1. Our implementation's scope is existing files and directories.
2. We don't miss the other features either terribly much.
3. We're OK with folks doing manual work to construct the last path component.

It's really strange. We all understand that without the builtin, it's specifically super easy to check these paths anyhow - fish resolves symlinks: `pushd`, grab $PWD, and then check the last bit manually. Why did we add the builtin for that?

Why keep a builtin for doing exactly that?

**Comment by terlar** [comment]
I remember when this was first introduced at least from my perspective as a patch for the changed behaviour of `status -f`. Before it resolved the path and put the full real path to the script, but at some point it was changed to be relative and show the file executed so a symlinked script relying on `status -f` stopped working.

Then `realpath` builtin was added as a substitute that scripts could rely on to make sure all users could run or execute this code.

What I want to be able to achive is to be able to determine from a script where the original file lives and then add a few paths based on the script location. I guess this `pushd` method could be a substitute, but it seems a bit clunky.

**Comment by terlar** [comment]
```fish
mkdir sample
echo 'status -f' > sample/script.fish
ln -s sample/script.fish linked-script.fish

fish sample/script.fish
fish linked-script.fish 
```

would give output:

```
sample/script.fish
linked-script.fish
```

**Comment by terlar** [comment]
If the file is symlinked you cannot rely on the `pushd`, because then you would have to resolve the symlinked path, so is there any other way than `realpath` to achive the same thing?

```fish
pushd (dirname (status -f))
set script_path $PWD
popd
echo $script_path
```

this would yield:
```
/tmp/sample/
/tmp/
```

Perhaps the issue lies with `dirname` if all the functions are expected to resolve the path. But that might break other things.

**Comment by floam** [comment]
"just pushd to the containing directory!"

... heh, so if you can't do that I can't think of what you can do from a fish-script besides `status -f` - for some reason I think we are currently be giving you a full path to yourself. I'm not near fish right now to try - when did that change? I thought it worked for me in Homebrew's fish package to change into the parent of what `/usr/local/share/fish` points to, from an installed script in `/usr/local/share/fish/functions/`. (Homebrew links that).

**Comment by floam** [comment]
>An implementation of the external realpath command that doesn't support any options. It's meant to be used only by scripts which need to be portable

it occurs to me now that he didn't mean portable as in "running on Solaris"-portable.  It's useful for transient scripts. I guess it shouldn't be removed and just improved if need-be. Closing.

**Comment by floam** [comment]
https://github.com/fish-shell/fish-shell/issues/3295 could potentially help with portable scripts in addition to making heads and tails of autoloaded functions.

**Comment by terlar** [comment]
I agree that it would be useful to have some function/builtin that tells the absolute filename on the file system for an executed script. Personally this is the only use case I have had for the `realpath` command. I remember I had a lot of scripts using the `status -f` and then at some point all those scripts broke when the path became relative instead of absolute.

These are the related issues:
My initial issue: https://github.com/fish-shell/fish-shell/issues/2932
The part that changed the behavior: https://github.com/fish-shell/fish-shell/issues/2643

**Comment by floam** [comment]
Happen to have a script you can share where you are currently using realpath that worked prior to that change?
