### ISSUE TITLE
How to pass an array/list to a function?

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#3375]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
2.3.1
**OS/terminal used**: 
Ubuntu -> Guake -> Tmux

How do I pass a variable that is an array/list to a function? Every time I do when I try to loop through it I just get the first item.

I didn't see an example of passing an array in the documentation.

**Comment by faho** [comment]
What are you trying to do? Example code?

If you call a function with `func $list`, it will receive all elements of the list. `$argv` will be laid out just like `$list`.

**Comment by ElijahLynn** [comment]
Thanks, here is an example:

```
$ set colors red blue black
$ function echotest --argument car colors
       for color in $colors
           echo $color $car
       end
   end    
$ echotest Tesla $colors
$ red Tesla
```

I was expecting the loop to go on and list 'red Tesla', 'blue Tesla' and 'black Tesla'.

**Comment by faho** [comment]
Ah, okay. "--argument" applies to one argument.

So what happens here is that the first argument is assigned to $car, the second to $colors and all the rest aren't in named arguments at all, they're only in $argv.

The semantics here are a bit annoying - named argument variables are always set, always one argument and $argv still contains _all_ arguments.

What you'd need to do here is

```fish
function echotest
    set -l car $argv[1]
    set -e argv[1]
    set -l colors $argv
    for color in $colors
        echo $color $car
    end
end
```

**Comment by ElijahLynn** [comment]
Sorry, I was actually using --argument-names, I updated my example. Does the same apply with --argument-names?

... reading the rest right now.

**Comment by faho** [comment]
Yes, the same thing applies. (I actually didn't double-check the option name)

**Comment by ElijahLynn** [comment]
Okay, your example is working and I understand what is going on now. Thanks for taking the time on that! 

I don't understand the internals of fish yet but do you think it would be doable to add support to simply pass a list in as a variable, especially with --argument-names? That would be a very nice DX.

**Comment by faho** [comment]
There's a few ways to pass a list in as a variable, and all I'd describe as "advanced" techniques because they kind of break the expectation that functions and external commands are the same.

The first is "--inherit-variable" ("-V or --inherit-variable NAME snapshots the value of the variable NAME and defines a local variable with that same name and value when the function is executed.").

You'd define it like this:

```fish
function echotest -V car -V colors
    for color in $colors
        echo $color $car
    end
end
```

and execute it like

```fish
$ set -l colors red green blue black swamp
$ set -l car Tesla
$ echotest
```

The second is "--no-scope-shadowing". This will hand the function all variables, even the local ones, and will let you modify them at will (which includes erasing them). However any variable declared locally inside the function still won't be visible to the outside (which means if you need a variable inside the function to do some work you won't be able to work with a variable of that name from outside).

You'd do 

```fish
function echotest --no-scope-shadowing
    for color in $colors
        echo $color $car
    end
end
```

And execute it like the inherited example.

Now, you can also pass the name of a variable, like

```fish
function echotest -a carname -a colorname
    for color in $$colorname # note the second $ - we want to dereference twice
        echo $color $$carname
    end
end
```

and call it like 


```fish
set -g car Testla
set -g colors red green banana firn
echotest car colors
```

However, in this case, it won't be able to read local variables, so you'd need to declare them as global (or universal). (It should probably be made so local-but-exported variables are actually exported to functions, but currently they aren't)

----

In summation, I'd recommend just using $argv for the time being, because everything else has some limitations or is even dangerous.

**Comment by ElijahLynn** [comment]
Thanks for the detailed examples and explanations. I will stick to the first example for now but as I get more advanced I am sure this will be useful!

Cheers
