### ISSUE TITLE
Feature Request: Respect leading space in aliases, ignore in history

### ISSUE THREAD

**Issue by ideasman42** [fish-shell/fish-shell#3376]
A handy trick that works in bash & zsh is to use a leading space in an alias so this command is never saved to history.

eg:

    alias aunpack=" aunpack"

Once this is done running `aunpack` wont add its self into the history,
its useful for one off commands that aren't typically re-used.

**Comment by floam** [comment]
This can't work with aliases as they are currently implemented. At first, a thought might be that because they are implemented with functions, maybe we could desire for functions to have a way to mark them not to show up in history.

In this case though, what you actually want would seem to be an abbr, which specifically is like an alias but expands interactively:

> `abbr aunpack=" aunpack"`

Try it out
