### ISSUE TITLE
string replace -r x \\c locks up fish

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3381]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

This happens in master and 2.3.0, 2.3.1 on OS X 10.12 for me. The process seems to lock up as soon as you press enter when doing a regex replacement when ~~--all is specified and~~ the second string argument is `\\c`. There needs to not be another argument after.

**Reproduction Steps**
1. Enter as a command:`string replace -ra x \\c` - `x` can be anything.
2. Hit enter.

It looks like it's looping in `read_unquoted_escape` called from string_replace:

```
 frame #0: 0x000000010c1c3047 fish`read_unquoted_escape(wchar_t const*, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >*, bool, bool) + 551
    frame #1: 0x000000010c1b8452 fish`string_replace(parser_t&, io_streams_t&, int, wchar_t**) + 722
    frame #2: 0x000000010c1a5d9c fish`builtin_run(parser_t&, wchar_t const* const*, io_streams_t&) + 508
    frame #3: 0x000000010c1ddb1d fish`exec_job(parser_t&, job_t*) + 4013
```

**Comment by ridiculousfish** [comment]
Nice find.

**Comment by floam** [comment]
I mistakenly said `--all` needs to be specified in the post -- it doesn't need to be.

**Comment by krader1961** [comment]
Can someone explain why `class regex_replacer_t` is using `read_unquoted_escape()`? The replacement string has already been unescaped by `unescape_string_internal()`. The string man page implies that it is so you can embed sequences like `\t` in the replacement string to insert a tab. But that's already been done -- there isn't any need for `regex_replacer_t` to do the unescape a second time. The only reason this bug exists is because we're unescaping the string twice. And this is the only place in the code where we do so. This looks wrong to me.

**Comment by ridiculousfish** [comment]
@msteed do you remember what the thinking was here?

**Comment by krader1961** [comment]
Also, note that if we weren't doing the unescape a second time you would just write `string replace -r x \c` which would fail earlier because `\c` is an invalid escape. The reason you have to type `\\c` is because we're doing the unescape twice on the replacement string and, as the proposed fix notes, we're not dealing with the fact that `\c` is invalid.

For example, put `string replace -r x \c abc` in a file named */tmp/x* then run it:

```
$ fish /tmp/x
Invalid token '\c'
/tmp/x (line 1): string replace -r x \c abc
                                     ^
<W> fish: Error while reading file /tmp/x
```

The proposed fix silently ignores the invalid replacement string.

**Comment by ridiculousfish** [comment]
This may be related to the behavior of `PCRE2_SUBSTITUTE_EXTENDED`. [From here](http://www.regular-expressions.info/pcre2.html#subext)  we see that PCRE does its own interpretation of the replacement string.

**Comment by krader1961** [comment]
I thought about that but that's actually an argument against us doing the second unescape ourselves. Because now if you want to get a special backslash sequence into the PCRE engine you have to now specify four backslashes; e.g., `\\\\U$1` to for the matched string to uppercase.

**Comment by msteed** [comment]
Sorry, that part of the code is not ringing any bells for me.

**Comment by krader1961** [comment]
It's also interesting that there aren't any tests for backslash escaping in the string replace tests in *src/fish_tests.cpp*.

**Comment by krader1961** [comment]
The second unescape was introduced by commit d83ef07c which added the `string` command. Unfortunately I cannot figure out why the second `read_unquoted_escape()` is present in the `string` command execution path. The [PR](https://github.com/fish-shell/fish-shell/pull/2296) has an extremely confusing history. Most notably a huge number of commits not related to the feature introduction. There are, however, quite a few comments early in the life of that PR which hint at why the extra call to `read_unquoted_escape()` might be present. And many of those comments suggest to me a misunderstanding as to whether a backslash escape should be interpreted by fish or the PCRE library.

I would like to commit a change that removes the extra `read_unquoted_escape()` call. Doing so is strictly speaking not backward compatible. However it looks to me like the correct thing to do and the sooner we make that change the better since it minimizes the number of people depending on the current, problematic, behavior. Making that change should affect no one other than individuals exploiting corner cases.

**Comment by krader1961** [comment]
FWIW, the sooner we revert the second `read_unquoted_escape()` call the more likely we'll notice that someone is depending on the current behavior and can decide whether or not to keep that behavior.

**Comment by krader1961** [comment]
> We could fix the infinite loop without the backwards incompatible change. 

The problem, as exhibited by PR #3670, is that fixing the infinite loop is extremely difficult. The proposed, naive, fix doesn't actually correct the problem in a meaningful way.

**Comment by krader1961** [comment]
The fix in PR #3670 eliminates the "hang" (i.e., infinite loop) condition by introducing a new bug. I'd rather break backward compatibility in this case since this feature is still relatively new and the change is likely to affect few users. However, this is obviously a contentious choice. The question is what is in the best long term interest of the fish community.

**Comment by floam** [comment]
Hm, and I'm not quite sure I'd want to bother to figure out how fix that the right way Meh. I'm fine with killing two birds with one stone on second though. 

I'd be surprised if this breaks many scripts. Obviously it should be release-noted.

**Comment by faho** [comment]
Is this responsible for the weirdness in e.g. our `math` function? Where, to remove a "\\" before the end of the line, we need `string replace -r '\\\\$' ''`? That would also affect `alias`, and maybe `__fish_print_mounted` (run `grep "string.*\\\\\\\\" -r share/`).

**Comment by krader1961** [comment]
After further reflection I think I know why @msteed decided the `string` builtin should call `read_unquoted_escape()`. If the user quoted the original regex then the parser does not pass the string through that function. In other words `string replace -r \cX` is different from `string replace -r '\cX'`. But PCRE already supports most (all?) of the escapes supported by fish.

Despite my desire to correct this bogosity by making a backward incompatible change we can't do that. The fact that @faho was able to find several instances in our own code base where we rely on the current behavior is argument enough. There are undoubtedly a huge number of other places outside the fish project where people have already added extra backslashes to deal with this behavior. We can't break them.

I hate to do it but I think we need to introduce a flag (`-U`?) to `string` to communicate that the strings should not be unescaped by the command other than as recognized by the PCRE engine. At some point in the future, probably the next major release, that can become the default behavior. As part of that report a failure if the user does not use the proposed flag and the string fails to unescape cleanly.

**Comment by floam** [comment]
I gotta say, I hate that. I think we just got rid of the one spot in our code where we were using the extra backslashes in `math`.  Other can adapt.

Adding an option to select for two modes of behavior feels very unfishy. If we want to defer the change until after 2.5.0, fix the hang for now, I guess I support that - but I don't think we should add this option.

**Comment by krader1961** [comment]
The problem is that you have to allow for a smooth transition from the current behavior to the preferred behavior. And we can't unilaterally change something like this without doing a major release. We can't do it in fish 2.5.0, 2.6.0, or any 2.x release. This is sort of like the situation with Python where they recognized that `print` should not be a reserved keyword recognized by the parse but should instead be a standard function. So they added `from __future__ import print_function` to python 2.x so people could smoothly transition their code then made that the default behavior for python 3.x. If we were willing to add something analogous to the python `from __future__` that worked at a file scope level that would be better than a `string` flag. But doing so is immensely more complicated than adding a transition flag.

**Comment by floam** [comment]
I don't think is is nearly as big a deal as the python `print` keyword to `print()`change.

**Comment by krader1961** [comment]
For those following at home the regex strings are being "unescaped" up to three times if the original string was not quoted:

1) by the fish parser (if the original string was not quoted),
2) by the `string` command,
3) by the PCRE engine.

Ugh! The whole point of this discussion is how to remove the second unescape  in that sequence.

**Comment by floam** [comment]
This is more philosophical, but I feel like we've moved away from the idea of major releases with fish. As they ay at Facebook, "move fast and break things" has been how I think we've been doing it for several months with accelerated schedules.

**Comment by krader1961** [comment]
> I don't think is is nearly as big a deal as the python print keyword to print()change.

That's what I thought about some similar backward incompatible changes I championed in the past year. I think changing the default behavior in anything other than a major release will be noticed and result in a huge number of bug reports. We're all in agreement the future default behavior needs to be changed. The only question is how to get from A to B.

**Comment by krader1961** [comment]
> As they ay at Facebook, "move fast and break things"

And that's the philosophy for internal projects at $dayjob where we have more control over the affected parties when such changes are made. If fish was still in the 1.x stage I'd be willing to make this type of change in a minor release. But today I think we need to be cognizant of our much larger user base and the need to be stable in the sense of not changing old behavior in ways that will be noticed by more than a handful of users. That's why, for example, I argued so strongly that the rewrite of the `random` command maintain compatibility with the old behavior.

**Comment by floam** [comment]
If that's the stance, I'd prefer we just fix the bug bug for now and change the behavior later, without introducing a flag. 

I think we could really get away with just nuking the escape unescape for 2.5.0 though.

**Comment by floam** [comment]
In my mind, if there are scripts out there relying on this behavior, they are much more likely to be OMF/fisherman type deals which can update on a dime rather than user scripts.

**Comment by krader1961** [comment]
> they are much more likely to be OMF/fisherman type deals which can update on a dime rather than user scripts.

I had the same that but even if we were willing to review all those scripts to find the one affected by our change that doesn't help. Those scripts still need to work on fish 2.4.0 and 2.5.0.

**Comment by floam** [comment]
> Those scripts still need to work on fish 2.4.0 and 2.5.0.

Do they? Consider the incompatibilities between 2.2.0 (or earlier) with subsequent versions.

**Comment by mqudsi** [comment]
Do we want to do this for 3.0?

**Comment by ridiculousfish** [comment]
I made the `string replace` properly report errors when escaping.

Some other formatting fixes got caught in this commit; sorry :/
