### ISSUE TITLE
Bind prefix keys, or two-stage binds (like Emacs)

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#3398]
As mentioned in https://github.com/fish-shell/fish-shell/issues/1963, it would be handy to be able to bind, depending on how you look at it, prefix keys, two-stage binds, or Emacs-style key combinations.  For example, in Emacs `C-x C-f` is used by pressing Control and `x` together, releasing, then pressing Control and `f` together.

This would be nice in Fish, because it would let you bind sets of commands behind prefix keys.  For example:
- `Alt+P l` to insert `| less`
- `Alt+P w c` to insert `| wc`
- `Alt+P g` to insert `| grep`

**Comment by krader1961** [comment]
You can create those bindings today. For example,

```
function insert_pipe
    echo commandline -i " | $argv" >>/tmp/x
    commandline -i " | $argv"
end

bind \ePl 'insert_pipe less'
bind \ePwc 'insert_pipe wc'
bind \ePg 'insert_pipe grep'
```

However, due to how input is currently handled the characters must arrive with effectively no inter-char delay. So it isn't possible to manually press [alt-P]+l to trigger the binding. However, if you modify your terminal key map to translate something like [alt-l] to send the sequence \ePl it works.

I noticed this several months ago when working on some other issues involving keyboard input. I could have sworn there was an open issue discussing the need to improve this but I can't find it. So I'll take ownership to remind me to revisit this.

**Comment by faho** [comment]
@krader1961: Is it expected that this works with control?

I can reliably press \cxe and \cx\ce. I need to be quick (not quite like in emacs), but if I'm not slow on purpose I can do it pretty much 100%.

**Comment by krader1961** [comment]
Yes, it is expected to work with any multi-char sequence, including something like `\cx\ce` or even `\cxabcd`. I too can pretty reliably make such bindings work but that's mostly because of the placement of my [ctrl] key and that I'm a reasonably fast typist. The [alt] key placement makes it much harder to release and press the next character in the binding fast enough.

I definitely wrote a comment about this part of the fish code and how it handles input that is a prefix for a longer binding. I'm simply unable to find it :smile: At present the code doesn't wait anywhere close to long enough to see if the remaining characters of the binding will be received. On the other hand it uses a fixed timeout which means it waits longer than necessary even when the currently seen sequence of characters can't possibly match a binding.

**Comment by faho** [comment]
>At present the code doesn't wait anywhere close to long enough to see if the remaining characters of the binding will be received. On the other hand it uses a fixed timeout

Should it be using a timeout at all? The way it works in emacs is that if you bind $a$b (where "$a" and "$b" are some key sequences), then you can't use $a on its own at all. So if you press $a, it waits for you to press $b or $c, for as long as it takes. And binding $a when $a$b is already bound is an error ("$a is not a prefix" or something like that).

Though somehow emacs manages to distinguish between escape and alt.

**Comment by krader1961** [comment]
> Should it be using a timeout at all?

You can argue for and against our current behavior. At the moment you can do this:

```
bind \cx 'echo saw cx'
bind \cx\ce 'echo saw cxce'
```

Now press [ctrl-x] and wait. Then press [ctrl-x][ctrl-e] quickly. So an argument for using a timeout to allow that pattern is the flexibility it offers. The argument against is that it's ambiguous and fragile. If the rest of the longer sequence isn't received and processed quickly it won't be recognized (which is what caused the O.P. to open this issue). There may be other arguments for and against binding to sequences that are a prefix of longer sequences. Personally I'd prefer us to switch to the emacs behavior. Which would necessarily mean the second `bind` in my example above would need to be rejected as an error.

> Though somehow emacs manages to distinguish between escape and alt.

It does so the same way we do to support vi mode: by using a timeout. Specifically `$fish_escape_delay_ms` which defaults to 300 ms if it isn't defined.

**Comment by alphapapa** [comment]
Thanks @krader1961 and @faho for looking into this!

**Comment by krader1961** [comment]
Closing since the original question was answered and the user can customize how long fish waits for additional characters to match their typing speed to maximize flexibility while minimizing undesired latency.

**Comment by alphapapa** [comment]
@krader1961 

> Personally I'd prefer us to switch to the emacs behavior.

> Closing...

Does this mean that that option is off the table, or may I open an issue to discuss that possibility?  Thanks.

**Comment by krader1961** [comment]
> Does this mean that that option is off the table, or may I open an issue to discuss that possibility? 

I think it is worth discussing but no promise that it will ever be changed because there will undoubtedly be people who will argue for keeping the current behavior. And in any event we can't change it anytime soon since it could only be done in a major release.
