### ISSUE TITLE
should the exit status of a 'while' loop be 1?

### ISSUE THREAD

**Issue by vede1** [fish-shell/fish-shell#3402]
fish, version 2.3.1

The exit status of a successfully ended while loop is always 1 (in bash it is 0). If this is by design, then how to control the exit status of a script ending with a while loop?

```
▐ ~
▐ $ set cnt 0; while test $cnt -ne 3; echo $cnt; sleep 0.5; set cnt (math $cnt+1); end
0
1
2
▐ ~
▐ $ echo $status
1
▐ ~
▐ $ 
```

My specific usage pertains to pooling at the end of a script if a program is still running .
```
gedit &
while not test -z (pidof gedit); echo running...; sleep 1; end
```

**Comment by krader1961** [comment]
The last command executed before the loop terminates is the `test` conditional which is returning one (i.e., "false") thus causing the loop to terminate. So, yes, this is by design.

Just add an explicit `exit 0` to the end of your script. Or if you need to use the status of the last command in the body of the while loop do something like

```
while test $cnd -ne 3
    do stuff 
    some_command
    set exit_status $status
end
echo $exit_status
```
