### ISSUE TITLE
グ and ジ cause glitches

### ISSUE THREAD

**Issue by onodera-punpun** [fish-shell/fish-shell#3420]
## Info

`fish, version 2.3.1-586-g53f1eba`
`GNU/Linux`
`URxvt`

## Reproduction steps

* Type in `cp`, this will show the completion: https://punpun.xyz/sobc.png

* Press space, the cursor will jump like 5 or so characters and make the completion all weird: https://punpun.xyz/smsz.png

* Every character after that makes it worse: https://punpun.xyz/i7rt.png

---

Filename that caused this: `'相対性理論 - 天声ジングル (2016) [FLAC]'/`

Just interacting with this file in general will give glithes: https://punpun.xyz/y6iz.png

**Comment by onodera-punpun** [comment]
On closer inspection, it seems like `グ` and `ジ` are the specific characters that cause glitches.

**Comment by krader1961** [comment]
Those two characters are classified as "wide" characters. That means they consume two "cell" (that is, two columns) in a terminal using a fixed width font. The reason the cursor jumps like that is the `wcwidth()` function is returning two for those characters but your terminal (and mine which is iTerm) is treating them as taking one position.

Your first character is [U+30AF](http://unicode.org/cldr/utility/character.jsp?a=30AF). [Unicode TR11](http://www.unicode.org/reports/tr11/tr11-31.html) is confusing but in essence a "narrow" (or "halfwidth") character takes one cell in a fixed with font and a "wide" (or "fullwidth") takes two.

There isn't anything practical that fish can do to deal with this disagreement between the libc `wcwidth()` function and your terminal. I'd recommend opening an issue against your OS and terminal.

See also issue #2652.

**Comment by faho** [comment]
There doesn't appear to be anything we can do here, closing.
