### ISSUE TITLE
Message "Unable to make or open a FIFO for universal variables with path '/run/user/1000/fishd.$hostname.notifier': File exists"

### ISSUE THREAD

**Issue by f1u77y** [fish-shell/fish-shell#3426]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [ ] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_? 
  (**TODO**)

**fish version installed** _(2.3.1)_:

**OS/terminal used**: tmux 2.3 on konsole 16.08.1 and yakuake 3.0.2, all soft(including fish) from Archlinux packages
## Reproduction steps

(I dunno what exactly causes this but I'll try to name all stuff that could be related)
1. Set tmux as shell in konsole(and in yakuake because yakuake uses konsole)
2. Open konsole and yakuake on autostart
## Results

Error message in one of instances

``` console
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
 ~ Unable to make or open a FIFO for universal variables with path '/run/user/1000/fishd.navi.notifier': File exists
```

**Comment by faho** [comment]
Also, is $XDG_RUNTIME_DIR correct (or unset, which should also be correct)? Is that actually the UID for that user?

**Comment by f1u77y** [comment]
@faho oh didn't noticed that issue while searching.

* No, I only have config file with some aliases and prompt functions
* No
* I have never noticed that error message isn't present, after first occurence. Haven't relogined yet, will try now.
* `$XDG_RUNTIME_DIR` in `/run/user/1000` and 1000 correct UID for current user

**Comment by krader1961** [comment]
This is just a really unlikely, but not impossible, race condition. Look at the `universal_notifier_named_pipe_t::make_pipe()` method. It attempts to open the named pipe. If that fails it attempts to create the named pipe then repeat the open attempt. If you launch two fish instances simultaneously on a system with no previously running fish programs then it is possible for both to fail the initial open and one of them to fail the subsequent `mkfifo()` call because the other has already created the named pipe.
