### ISSUE TITLE
Vi Mode Cursor not changing in tmux

### ISSUE THREAD

**Issue by nabsiddiqui** [fish-shell/fish-shell#3429]
I'm using the latest nightly build of fish, and the Vi mode does not change  the cursor in tmux. In fish config, I have:

```
fish_vi_key_bindings
set fish_bind_mode insert
function fish_mode_prompt; end
set fish_cursor_default block
set fish_cursor_insert line
set fish_cursor_visual block
```

**Comment by krader1961** [comment]
Fish doesn't define or use any of the fish_cursor_*whatever* variables you mention. Are you using a theme from a plugin manager like Oh My Fish or Fisherman?

**Comment by nabsiddiqui** [comment]
I am using fisherman, but if I remember correctly, I got it from #1403

**Comment by nabsiddiqui** [comment]
I'm using gnome-terminal.  I can change it to a "line" cursor in fish config, but it does not redraw the cursor when changing modes, so the modes are working somewhat.

**Comment by krader1961** [comment]
@faho, Since you wrote most (if not all) of the *share/functions/fish_vi_cursor.fish* script, not to mention the most recent change on 2016-09-05 I think you're the best person to handle this. I also see on close inspection that it uses the variables mentioned in the original problem statement indirectly via variable substitution; e.g., `set -l varname fish_cursor_\$fish_bind_mode`.

P.S., I'd recommend adding the explicit variable names (e.g., `fish_cursor_default`) to that script in a comment at the top of the file so that grep'ing will find them.

**Comment by krader1961** [comment]
@nabsiddiqui, If you're comfortable building from source can you try `git checkout b0716885~; make fish; ./fish`? That's because the most recent change to that script to fix issue #3217 might be the cause of your problem.

**Comment by faho** [comment]
This is currently as expected. If you look into `fish_vi_cursor`, you might find this bit:

```fish
            if set -q KONSOLE_PROFILE_NAME
               or set -q ITERM_PROFILE
                set function __fish_cursor_konsole
                set uses_echo 1
            else if string match -q "xterm*" -- $TERM
                set function __fish_cursor_xterm
                set uses_echo 1
            else
                return 1
            end
```

In gnome-terminal inside tmux, both checks will be false because $TERM will be "screen-256color". We probably should be checking for $VTE_VERSION, but for that we should first figure out when VTE added support for this feature.

**Comment by faho** [comment]
Okay, it's version 0.19.1 - see [the NEWS file](https://github.com/GNOME/vte/blob/master/NEWS#L482).

**Comment by nabsiddiqui** [comment]
Thank you.  Works great in latest version.

**Comment by nabsiddiqui** [comment]
I didn't want to start a new issue for this, but when you switch from one window back to another window with fish shell, the cursor reverts back.

**Comment by faho** [comment]
@nabsiddiqui: How exactly are you noticing this? Do you switch to normal mode, switch windows and then it's back to the insert cursor? Or are you running something?

**Comment by nabsiddiqui** [comment]
Yes, that is correct.  It goes back to the "block" cursor for insert mode.  If I type in "fish" to start a new prompt, it will go back to the line cursor.  

For what it's worth, I am running tmux 2.1,, and I mean switching windows in the tmux sense not the GUI sense.

**Comment by faho** [comment]
That's very likely to be a tmux issue - it might not be remembering the cursor correctly.

You might try echoing the sequence (`\ePtmux;\e\e[6\e\\\\`) with disabled vi-mode or in another shell and then switching windows.

**Comment by nilehmann** [comment]
Sorry to revive this issue, but I'm having the same problem with the cursor in tmux. It seems that whenever the cursor changes in tmux it is changed in all windows and panes. @nabsiddiqui, did you find a solution or report an issue in tmux?

**Comment by nabsiddiqui** [comment]
Unfortunately, no. I actually just got used to it although it is pretty annoying. I realized that I don't use tmux enough to try to fix it. I use i3wm a lot and it serves my purposes better.
