### ISSUE TITLE
`alias` cannot handle trailing comments in the alias body

### ISSUE THREAD

**Issue by glennj** [fish-shell/fish-shell#3445]
**fish version installed** *(`fish --version`)*: 2.3.1

**OS/terminal used**: Fedora/gnome-terminal

## Reproduction steps
1. `alias foo='echo bar # comment'`
2. observe the traceback

## Results
```console
$ alias foo='echo bar #some description'
Missing end to balance this begin
- (line 1): begin; function foo --wraps echo;  echo bar #some description $argv; end 
            ^
from sourcing file -
	called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
	called on line 63 of file /usr/share/fish/functions/alias.fish

in function “alias”
	called on standard input
	with parameter list “foo=echo bar #some description”

source: Error while reading file “-”
```

## Suggestion

The `alias` function eventually does this:

    eval "function $name --wraps $first_word; $prefix $first_word $body \$argv; end"

The comment in the body comments-out the `end` keyword.

For robustness, replace the semi-colons in the eval argument with newlines

    eval "function $name --wraps $first_word
    $prefix $first_word $body \$argv
    end"

**Comment by faho** [comment]
Your suggestion doesn't really fix everything - after that, your resulting function definition will be:

```fish
function foo
	echo bar # some description $argv
end
```

This does not take any arguments since the $argv is commented out! That's actually worse than before, as now you have a non-working alias instead of no alias at all.

To fix it, we'd need to detect the comments and place the "$argv" before it. Since I cannot see any use for comments inside the alias definition (why not put them outside?), that seems like unnecessary complication. So let's just keep the current error. 

I'll close this for now. If you can make an argument for this feature, we'll reconsider.

**Comment by krader1961** [comment]
That's an interesting failure mode but I agree with @faho. Given the point of `alias` is to create trivial functions for simple one-liners it never occurred to me to put a comment in the body of an alias. If the alias is complex enough to warrant embedded comments then it should be defined directly as a function. If all you want is a comment reminding you why you created the alias put it outside the body of the alias:

```
alias foo 'echo argv is: ' # seemed like a good idea at the time
```

**Comment by floam** [comment]
Putting the comment outside makes it hard to identify the origin of the function later. But it'd be more fishy to somehow affect the function description.
