### ISSUE TITLE
abbr should allow setting to global variable

### ISSUE THREAD

**Issue by maletor** [fish-shell/fish-shell#3446]
I've been using `abbr` instead of `alias` for a good while now and it's been a wonderful feature. But, I must mention one flaw with the way the variable is set.

With `alias` it was very easy to control the scope of the alias, essentially it was a function so it was neither global or universal.

With `abbr` it sets a universal `fish_user_abbreviations`, but it is much harder to manage since `abbr` hardcodes it as such and in turn it is hard to edit on it's own so you wouldn't want to manage a `fish_user_abbreviations` global in `config.fish`, especially if adding ad hoc abbrs go into universal variables no matter what.

It's possible this is a broader issue of mine with the way way universal variables work in conjunction with trying to preserve a dotfile for fish configuration to share between computers. The way the universal variables are mapped by MAC address indicates they should not be checked into a dotfile git repository which leads to people setting global variables in `config.fish`, which in turn slows down startup because now these are run at each new setup in addition to the universal variables. I do not believe that setting a flag for whether the global file has been run in a universal variable is a good experience for new people to fish.

I guess my propsal would be to allow `abbr` to have an option to allow setting it as a global and to also read from there first. Open to thoughts and suggestions though. This way I can keep it out of my universal file entirely since it's not universal enough. My config.fish is really my universal variables since that one is actually shared between all my computers.

**Comment by krader1961** [comment]
You can in fact make your abbreviations global rather than universal. Simply put `set -g fish_user_abbreviations` in your *~/.config/fish/config.fish* startup script before you define any abbreviations. This isn't documented AFAICT so I'll take care of adding that to the `abbr` man page. Note that because of how abbreviations are implemented you can't have some be universal and others be global (i.e., only visible in a particular fish shell).  They must all be global (i.e., per session) or universal.

Many people, including myself, have asked that the universal var file name not include a machine ID. See issue #1912.

P.S., You also stated that functions are "neither global or universal." In actuality functions are implicitly global since fish doesn't have name spaces. You can define a function within another function but it will still be visible in the global scope.

**Comment by krader1961** [comment]
See also issue #3049 where this question was discussed at length.

**Comment by maletor** [comment]
I'm not the only one then :)

I would ask that the universal file not have a machine ID as well. It complicates for a use case that is not common.

`set -g fish_user_abbreviations` in config.fish is a good idea. Makes sense.
