### ISSUE TITLE
How to execute "source" command to reload the config file outside of fish-shell?

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#3461]
Sometimes I'm using Emacs to edit the config.fish file, after finishing editing, I always have to reload it using `source ~/.config/fish/config.dish` (I got an alias), I created a function in config.fish to edit and reload it after exiting the editing, but how can I execute the `source` command outside of fish-shell.

The usual way of executing a shell command in elisp is (if you know any Emacs lisp):

    (shell-command-to-string "command")

will work for regular command like `echo` or `date`, but it is not working for the command `source ~/.config/fish/config.fish`.

Got any solution?

**Comment by faho** [comment]
For new sessions, you don't need to reload it at all, because they'll just load the new version.

For existing sessions, we don't have any explicit support. It would be possible to use a universal variable to signal for a reload, like

```fish
function reload-config --on-variable _reload_config
    source ~/.config/fish/config.fish
end
```

And then you could set that variable from the outside (`set -U _reload_config 1`).

However, reloading config.fish may lead to unwanted results.

Consider this:

```fish
set PATH $PATH /something/else
```

If that was in your config.fish, it would append /something/else to $PATH every time you source it (which it would also if you started another fish inside of a fish).

There is no way to detect this in general.

What might work better for you is instead of using `source`, using `exec fish` - replace the currently running fish with a new one, but this would eliminate every change you've made in the old one - any variable you set, function you defined (without saving).

**Comment by krader1961** [comment]
Note that `shell-command-to-string` actually launches a new shell and has that shell run the command. So using that mechanism will implicitly load your new *config.fish*; no need to source it explicitly. I'm guessing you're actually using [M-x]term to run an interactive fish inside emacs and are wanting to have that session automatically load your updated *config.fish*.

What I normally do is employ the `exec fish` solution @faho mentioned. The universal var idea is nifty but does require that you actually change the value. If you just set it to a constant like `1` then the function will be run only the first time you set the var. So you'd want to read the current value and increment it (or alternate between two values).

**Comment by faho** [comment]
>If you just set it to a constant like 1 then the function will be run only the first time you set the var.

Actually not - 

```fish
function testvar --on-variable testvar
     echo testvar
end
set testvar 1
set testvar 1
```

I tested that before.

**Comment by krader1961** [comment]
> I tested that before.

Yes, but you didn't test doing the set in a different session on the same machine :smile:

It's arguably a bug that `set` in the same session behaves differently than `set -U` in different sessions. The latter only triggers the `--on-variable` function if the value changes. Alternatively we might consider changing the behavior of `set` inside a session to only trigger the function if the variable changes. But that's a discussion that should occur in a separate issue.

**Comment by c02y** [comment]
> For new sessions, you don't need to reload it at all, because they'll just load the new version.

@faho I'm not creating any new sessions of fish-shell, just the opened ones.

> I'm guessing you're actually using [M-x]term to run an interactive fish inside emacs and are wanting to have that session automatically load your updated config.fish.

@krader1961 Actually I'm not use a shell inside Emacs, I'm using a terminal program like konsole.

I'm wondering whether I can make some configuration in config.fish that once I modified and saved config.fish (modify it inside the current fish session using vim or other CLI editors **or** outside it using GUI program like kwrite from file manager), any opened session of fish-shell will detect the change and reload the config.fish file automatically (then the function that I created to edit and reload it after finishing editing won't be necessary).

**Comment by krader1961** [comment]
> Actually I'm not use a shell inside Emacs, I'm using a terminal program like konsole.

Okay, but then why did you mention emacs `(shell-command-to-string "command")`? That's a rhetorical question. I ask it only to point out that mentioning it caused me to make an incorrect conclusion.

Regardless, the answer is "no". There is no way to have fish sessions automatically reload *config.fish* without using something like the `function reload-config --on-variable _reload_config` solution that @faho and I talked about. In other words, fish already provides the mechanism you need to achieve your goal. However, because very few people want *config.fish* to be automatically re-sourced when it changes, and doing so can cause problems, that is not default behavior. Also, many users split our startup config into multiple files. For example, I have *alias.fish*, *environ.fish*, *interactive.fish*, and *login.fish*. All of which may or may not be sourced from *config.fish* depending on the current situation. So in my case it would be necessary to trigger the reload if any of those files was modified. Which, again, is probably not something I want to have happen since, for example, *environ.fish* modifies variables like $PATH that I almost certainly do not want automatically reset to its value when the shell was started.

**Comment by krader1961** [comment]
Also, it's pretty unusual to modify your *config.fish* (and any files it directly sources) frequently after the first couple of weeks of switching to a new shell. Which is one reason why no shell I've ever used automatically re-sources those config files if they happen to change once the shell is running. When someone does modify their shell config files the usual practice is to run `exec $SHELL` (e.g., `exec fish` or `exec bash`) to explicitly replace the current shell with a new one if the user deems it necessary.

Obviously different people have different needs. So we should try to accommodate your needs. Is there some reason the `function reload-config --on-variable _reload_config` solution outlined by @faho doesn't solve your problem?

**Comment by floam** [comment]
I wonder if it'd make sense to use HUP1 or HUP2 to signal a reload. There is some precedence in other tools for doing this.

**Comment by krader1961** [comment]
There is definitely precedence for using SIGHUP (as well as SIGUSR1 and SIGUSR2) to trigger reload of a program's configuration. But I don't think that is useful in the context of a shell like fish where you probably have multiple instances and each one needs the signal.

**Comment by floam** [comment]
Isn't that what `killall` does? 

Another option would be monitoring the file for changes on platforms where this is easy (at least OS X).

**Comment by krader1961** [comment]
> Isn't that what killall does?

That has its own problems. Not least of which is signaling non-interactive shells to reload their config. At least the `function reload-config --on-variable _reload_config` solution can be easily predicated on whether the shell is interactive.

> Another option would be monitoring the file for changes...

And what about files sourced from *config.fish*? Such as the handful I mentioned in an earlier comment that I utilize to keep my *config.fish* lean and readable.

**Comment by krader1961** [comment]
Note that the sending a signal approach suggested by @floam is typically only used when you have a single instance of a daemon running. Such as a HTTP web server or email server where you want that daemon to gracefully reload its configuration. I've never seen it used where there are multiple independent instances of a program running.

**Comment by floam** [comment]
> And what about files sourced from config.fish? Such as the handful I mentioned in an earlier comment that I utilize to keep my config.fish lean and readable.

Hm, that wouldn't cause an auto-reload.

**Comment by floam** [comment]
> Such as a HTTP web server 

Don't these often have a number of workers, possibly different processes for different webapps?

**Comment by krader1961** [comment]
> Don't these often have a number of workers, possibly different processes for different webapps?

We're now wandering far afield of the original question. To the extent that such programs employ multiple processes having the same name (e.g., because they're simple `fork()`s of the main process), rather than threads, they use mechanisms to ensure that only the appropriate processes receiving the signal reload the config. For a shell like fish we would have to establish rules such as only interactive shells reload the config. We could certainly do so but why? In other words, would the additional complexity with respect to the implementation and documentation warrant such a change relative to what I perceive as a tiny minority of users who might find it useful? And for the majority of users who would find that behavior objectionable you're now talking about making it configurable which is something we try really hard to avoid.

It's far better to make it possible, if not easy, for the small percentage of users who want fish to behave an unusual manner to do so via generally applicable mechanisms (such as the `function xxx --on-variable` mechanism). We definitely want to avoid adding mechanisms like zsh's `setopt` command to configure such behavior unless there is clearly no other option. This is very similar to Alton Brown's (of "Good Eats" fame) admonition to avoid single-tasker kitchen implements.

**Comment by c02y** [comment]
It does not matter the answer is "no", like you said,
> Also, it's pretty unusual to modify your config.fish (and any files it directly sources) frequently after the first couple of weeks of switching to a new shell. 

This problem came across to me yesterday when I was tweaking my config.fish (create a new function to do a task), and I have to modify-save-reload-test-modify-save-reload... again and agin, this is not happening quite often, so I'm guessing I'm OK with it.

Thanks for the help.

**Comment by krader1961** [comment]
> This problem came across to me yesterday when I was tweaking my config.fish (create a new function to do a task), and I have to modify-save-reload-test-modify-save-reload... 

The fishy way to deal with that scenario is to use auto loaded functions. It's not quite instantaneous but very close to it (I'd have to look at the source to refresh my memory of the max interval). Fish will notice that the file from which a function was loaded has changed and re-source it. Consider the case where you're experimenting with a custom prompt. You've created a script named *~/.config/fish/functions/fish_prompt.fish* which defines a `fish_prompt` function. Every time you write a new version of that script fish will automatically source your updated `fish_prompt` function.

**Comment by c02y** [comment]
> The fishy way to deal with that scenario is to use auto loaded functions.

I created a function `abc` in `~/.config/fish/functions/abc.fish` as the autoloading function (if I understanding the meaning of *Autoloading Functions* correctly), but the file is not loaded instantly, it is been loaded after more than 5 seconds, so not very efficient.

I created Ctrl-l to clean the buffer and reload the config.fish to do the work:

    function fish_user_key_bindings
        bind \cl 'clear; commandline -f repaint; source ~/.config/fish/config.fish; path_prompt'
    end

then defined the function inside the config.fish, and it works as expected.

**Comment by krader1961** [comment]
I could have sworn the reload interval was nor more than ten seconds, worst case (average of 5 seconds). But I checked the source and found the following in *autoload.cpp*:

```
/// The time before we'll recheck an autoloaded file.
static const int kAutoloadStalenessInterval = 15;
```

Which is typically fast enough that I personally don't recall being annoyed by the delay. Nor do I recall anyone complaining about the delay. Still, it would be nice if someone enhanced fish to utilize whatever capability the operating system provides for monitoring changes to files. Then the reload would be, for all intents and purposes, instantaneous on an OS that provided such a facility. I'd be more than happy to review patches to implement that capability. Alternatively, if you want to explore whether reducing that recheck interval is reasonable (i.e., doesn't hurt performance overall) we might be willing consider that as well.

**Comment by floam** [comment]
Using `fsevents` on OS X would indeed be nice. On Linux I'm not sure what the best way to do it is these days. 

Didn't fish at one point experiment with inotify?

**Comment by floam** [comment]
Personally I know when I'm editing functions in an editor I'm often having to manually source them otherwise I get confused when I'm not sure which version is loaded or I find myself manually running a function several times waiting to see if the behavior changes.

**Comment by floam** [comment]
> Didn't fish at one point experiment with inotify?

It seems in part we dropped it when it wasn't working on Travis. I personally forked @ridiculousfish's test repo and found it to now be working on Travis a couple months back.

https://github.com/travis-ci/travis-ci/issues/2342

**Comment by krader1961** [comment]
> Personally I know when I'm editing functions in an editor I'm often having to manually source them...

Yes, I do the same thing in that situation. And I suspect everyone else does as well. When you want to be certain you're testing the change to the function you most recently saved outside of the current fish session that's the only safe approach. I think @c02y's main problem is that he's putting functions in his main fish config rather in separate auto-loaded scripts that can also be easily manually reloaded if that's needed to aid rapid testing of changes. Regardless, we absolutely do not want to add a mechanism for automatically reloading the main *config.fish* script as that will cause more problems than it solves.
