### ISSUE TITLE
fish_default_key_bindings --help loops forever

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3472]
## Reproduction steps
1. Run `fish_default_key_bindings --help`
## Expected Results

Information about what this function does.
## Results

The `bind` manpage is printed repeatedly.

**Comment by faho** [comment]
These functions currently do not have any documentation associated with them. It would need to be written.

Also, this doesn't loop _forever_, it just takes a while because it calls `bind $argv` a lot of times, and all of those will print the error.

We should probably fail once if an option that's invalid for `bind` is printed, either by checking them manually or by checking the return value for the first `bind` call. The latter would of course still print an error for `bind`, not `fish_default_key_bindings`, but it would allow us to add new options to `bind` without updating the functions.
