### ISSUE TITLE
data type `size_t` causes more problems than it solves so stop using it

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3493]
My first attempt to eliminate signed/unsigned warnings with commit 851e449 introduced a bug. See issue #3488. We should stop using the `size_t` type explicitly in our code. The use of unsigned ints (integers) outside of specialized situations such as bit-strings causes more problems than it solves.  We should instead explicitly coerce unsigned int values from the functions we call to signed ints. This is consistent with the [Google C++ style guide](https://google.github.io/styleguide/cppguide.html#Integer_Types).

There are people who believe that C/C++ unsigned int types should be used more not less. I've read their arguments and am not persuaded to do so. In addition to the aforementioned problem I've seen this result in bugs many times in the past 30+ years that I've been programming.

**Comment by zanchey** [comment]
I've got no opinion in this regard, but I note that the style guide you reference allows (encourages?) the use of `size_t` and friends.

**Comment by anordal** [comment]
Just to present an alternative view, I think the *signed* ints are the dangerous ones, and that `int` should be forbidden (except APIs that specify just that). In my own code, I use `unsigned` as the generic type all over the place, and `signed` where I actually mean that. I find that very few numbers have to be signed, except results of subtraction.

Remember, "unsigned integer" is just programming jargon for "natural number".

**Comment by krader1961** [comment]
@zanchey, You probably ought to read that section of the Google style guide again. While it does say

> When appropriate, you are welcome to use standard types like size_t and ptrdiff_t.

It goes on to explain why unsigned ints should not be used even when you know the value will never be negative (e.g., a loop counter). And the opening paragraph is pretty clear that absent a good reason to use some other type you should use `int`. The style guide is basically saying "as a competent software engineer use your best judgement even if that means using something other than a plain `int`".

As a former Google software engineer I can attest that unsigned ints are rarely used. When they are used it's most often for specialized data structures (e.g., arbitrary length bit fields) or when shaving even a few nanoseconds from performance critical code is worthwhile.

@anordal, What percentage of C/C++ programmers do you think can correctly answer these questions:

> What happens if the statement is of the form `<signed int> = <unsigned int> <op> <signed int>` and the signed int on the RHS is negative? Does it matter if the int on the LHS is signed or unsigned?

I'd be surprised if it is greater than 50% and it's certainly nowhere close to 100% based on my interviewing experience. Yet fish is riddled with such statements. Which means those statements are alligators waiting to bite someone in the ass if they change the code without understanding the subtleties of those statements. And from what I can see 99% of our uses of size_t is apparently just because some C++ methods (e.g., std::vector::size()) return a size_t. Not because using an unsigned type is actually needed or makes a measurable difference to the performance of fish.

**Comment by anordal** [comment]
Embarrassingly few, I agree. If there was a list of things in C/C++ that should have been the other way around, integer promotion rules would be on it, along with operator precedence.

My point is, it is possible to draw the opposite conclusion from the same set of facts, depending on preference.

**Comment by ridiculousfish** [comment]
Well, on to bikeshedding! I strongly disagree with Google's style guide here.

Google considers the main advantage of unsigned types to be a form of documentation, but this is the low order bit. A more serious issue is that signed integer arithmetic has very ugly pitfalls: signed integer overflow or underflow is UB, it's a lot harder to check for if you want to avoid it, and there's the `INT_MIN/-1` case that everyone forgets about. These bugs are more insidious than unsigned modulo underflow, because they're more of an edge case, and the result is undefined instead of defined (so is sensitive to optimization levels, compiler version, etc).

Plus from a practical perspective, we are going to bump into unsigned types because we use STL types extensively, and `collection.size()` is unsigned. This doesn't look very appealing:

    int len = static_cast<int>(str.size());

and it only gets a little better if we wrap it in a function. Furthermore, this is assuming that we'll never encounter a string larger than 2GB - large, but not inconceivable. Coercions are an entry point for security bugs.

anordal is right that very few numbers make sense when negative. Google's recommendation to add assertions for every non-negative parameter is unappealing, and easy to forget too. Why write C++ like it's JavaScript?

One place where we can hopefully all agree is to use C++11 range-based for loops. The most common use of `size_t` is as a loop counter, and nearly all loop counters can go away.

**Comment by krader1961** [comment]
> Coercions are an entry point for security bugs.

Certainly. But at present there are a large number of implicit coercions between unsigned and signed ints. Even after my recent changes to suppress lint warnings. And simply using explicit casts to silence the lint warnings does nothing to obviate the problem you're pointing out. The code has to actively test for the boundary violations.

> This doesn't look very appealing: `int len = static_cast<int>(str.size());`

Neither does `if (len == (size_t)-1)`. Yet we have many such explicit casts in the code.

The reality is that there are a large number of places where we currently combine unsigned and signed ints in arithmetic expressions. And absent explicit typecasts those expressions are likely to produce the wrong result. Which is what lead to the bug I introduced when I made a change to silence such warnings.

There are a small number of places where using an unsigned type makes sense. For example, generation tokens; e.g., `typedef unsigned int process_generation_count_t;

There is probably no place in fish where signed versus unsigned overflow/underflow behavior matters other than things like the aforementioned generation tokens. On the other hand there are a huge number of places where the author of the code assumes signed arithmetic is in effect.

> One place where we can hopefully all agree is to use C++11 range-based for loops. 

Yes. :smile:

**Comment by krader1961** [comment]
> On the other hand there are a huge number of places where the author of the code assumes signed arithmetic is in effect.

This includes the places where the code calculates whether there is enough space by subtracting two values and expecting a negative value rather than a huge positive value if the second operand is larger than the first operand. The problem is that some of those situations currently involve a `size_t` (i.e., `unsigned int`) which, absent explicit coercion, results in the wrong behavior. We're far less likely to see such bugs in the future if we use signed ints.

> Furthermore, this is assuming that we'll never encounter a string larger than 2GB - large, but not inconceivable.

We're almost certain to have problems even if we use `size_t` to hold the result of expressions like `some_container.size()` in that scenario. The reality is that if we really need to handle strings (or other sequences) larger than 2 GiB we should be using `int64_t` (or `long long int`) rather than `size_t`. And regardless we should be range checking the values where a value outside the expected range could cause problems. Using `size_t` provides very little safety; especially when that data type is used in expressions with signed types.

**Comment by anordal** [comment]
> the author of the code assumes signed

I admit that sounds like a killer argument, if this is more often than not.

But speaking of range checks, that's a great example of the unsigned code being slightly more correct and slightly more performant – I'm sure some would call it the "proper" way:

Range checking, the signed way:
```
signed candidate = ...
signed upper_bound = ...
signed lower_bound = ...
if (candidate >= lower_bound && candidate < upper_bound) {
    // OK
}
```

Range checking, the unsigned way:
```
unsigned candidate = ...
unsigned upper_bound = ...
unsigned lower_bound = ...
if (candidate - lower_bound < upper_bound - lower_bound) {
    // OK
}
```

The unsigned range check has only one comparison and doesn't treat a high upper_bound as negative. It is not as readable in this general form, but note how simple it gets in the common special case that lower_bound is 0.

**Comment by ridiculousfish** [comment]
> This includes the places where the code calculates whether there is enough space by subtracting two values and expecting a negative value rather than a huge positive value if the second operand is larger than the first operand.

Hmm. Under what circumstances is it the case that, if a > b, then `a - b` is negative? And might this expression produce undefined behavior? The answer for signed types is "sometimes" and "sometimes," while for unsigned types it's "never" and "never."

So wouldn't you agree that the signed case is so much harder to reason about? Personally I can't do it - signed two's complement arithmetic hurts my brain!

Not having undefined behavior is really important. Arithmetic with unsigned types produce 100% deterministic bugs. Arithmetic with signed types produces undefined behavior that will be compiler dependent, optimization level dependent, latent, etc. Why sign up for that?

> The problem is that some of those situations currently involve a `size_t` (i.e., `unsigned int`) which, absent explicit coercion, results in the wrong behavior. We're far less likely to see such bugs in the future if we use signed ints.

Signed types are more likely to introduce such bugs, because we can't avoid unsigned types.

We agree that mixing signed and unsigned types is bad. The STL uses unsigned types for e.g. `string.size()`, `vector.size()`, etc., so using unsigned types is unavoidable. It seems to me the solution is to not use signed types, except when necessary.

> And regardless we should be range checking the values where a value outside the expected range could cause problems. Using `size_t` provides very little safety; especially when that data type is used in expressions with signed types.

Why sign up for twice as much range checking?

size_t provides much more safety because unsigned arithmetic is defined, except for divide by zero. I can't overstate how important that is. If I am trying to track down a bug, not having to worry about UB from arithmetic expressions is a huge benefit.

**Comment by ridiculousfish** [comment]
> The unsigned range check has only one comparison and doesn't treat a high upper_bound as negative. It is not as readable in this general form, but note how simple it gets in the common special case that lower_bound is 0.

I don't really care for this example TBH. `candidate >= lower_bound && candidate < upper_bound` is the right way to write this.

Here's one place where unsigned arithmetic has an advantage: range-type expressions. For example, say, we want to operate on values from a subarray, 

```
void subarray(size_t start, size_t len , const char *arr, size_t arr_size) {
```

We want to ensure that `start + len < arr_size`. How do we range check this? With unsigned arithmetic:

```
    assert(start + len <= arr_size && start + len >= start);
```

This requires familiarity with the overflow-idiom, but it's short.

With signed arithmetic, I think the best you can do is:

```
    assert(start >= 0  && len >= 0 && arr_size >= 0);
    assert(len <= INT_MAX - start);
    assert(start + len <= arr_size);
```

which is much worse, right?

**Comment by krader1961** [comment]
> Under what circumstances is it the case that, if a > b, then a - b is negative?

The case that bit me was a < b and where `a - b` would be negative if it weren't for the fact that one of the operands was a size_t. I admit the operand in question was originally a signed int. But it's counterpart (we're talking rows and columns) was a size_t and they were initialized in a similar fashion so I said to myself "hey, they should both be size_t since neither will ever be negative." Oops!

Too, let's say both a and b are unsigned and a < b. Sure `a - b` has well defined behavior. So what. The code is still broken since it is very unlikely we really want the unsigned arithmetic result. And depending on the specific values involved and how the result is used you may or may not get a failure close enough to that computation to make debugging the problem easy. I know where from I speak since I did UNIX (proprietary and Linux) kernel crash analysis for two decades.

> Why sign up for twice as much range checking?

Range checking is unavoidable regardless of whether you're using unsigned or signed ints. And realistically 99.99% of our range checks would be to ensure that string and array lengths are no larger than INT_MAX / 2; e.g., ensuring size_t values are no larger than 2^30 assuming 32 bit ints. Fish is a shell. There is no legitimate reason for a string larger than 1 GiB being manipulated by fish. Same for a fish var having more than one billion elements.

> It seems to me the solution is to not use signed types, except when necessary.

So you're arguing that all the places where we currently use a signed int should be changed to unsigned int? Such as the args for `pager_t::completion_print_item()`? Because that's what caused the bug I fixed with commit 070ef6fd: `git log -p -1 070ef6f`. There are similar inconsistencies in many other functions and structures.

You gave this example for checking whether the range being operated on:

```
assert(start + len <= arr_size && start + len >= start);
```

The question you should ask is how many programmers will recognize what is being done in that assert? I'd be surprised if more than 50% could answer that without a couple of minutes of thought and even then it's almost certainly nowhere close to 100%. And if you really need to perform such a check rather than the longer version that works if the operands are all signed just add explicit casts to the operands in the assert. Such asserts are very rare. In fact I just did `grep assert src/*` and got 411 matching lines. There were literally only a handful that might be using that pattern.

This is related to another problem with the code base: The huge number of functions which are so large and complex that absolutely no one, and I include the people who wrote the code 5+ years ago, understands it. We would be much better served by simpler code and that includes using signed arithmetic by default except where unsigned clearly makes more sense (e.g., generation counters where we need well defined overflow behavior). Where signed arithmetic might have undefined overflow/underflow behavior it is straightforward to ensure the values are in a reasonable range so that doesn't occur.

**Comment by krader1961** [comment]
Also, the "signed int overflow/underflow is undefined by the C/C++ standard" is almost entirely because C was created when computers with ones-complement (e.g., the [CDC Cyber 760](https://en.wikipedia.org/wiki/CDC_Cyber) supercomputer I used in college) or sign-and-magnitude representations were still somewhat common. The undefined behavior allowed the compilers for those systems to implement whatever was most efficient. The reason it is still undefined behavior is that it allows compilers to optimize loops and the like under the assumption now overflow/underflow will occur.

See this [stackoverflow](http://stackoverflow.com/questions/18195715/why-is-unsigned-integer-overflow-defined-behavior-but-signed-integer-overflow-is) question. In particular the link to the blog post by Ian Lance Taylor in that question.

There is no good reason for fish to use size_t or unsigned ints except for a few very specialized applications such as generation counters. Doing so causes more complexity and potential bugs than it avoids. Where we get a size_t value from a standard C++ method and there is a reason to worry its magnitude could cause undefined behavior after being cast to a signed int we should be range checking that value.

**Comment by ridiculousfish** [comment]
> Sure a - b has well defined behavior. So what. The code is still broken since it is very unlikely we really want the unsigned arithmetic result.

The point is that, if you are going to break, it is much much better to do so deterministically than non-deterministically. As someone with many years of experience debugging kernel crashes, I am sure you can appreciate how much harder it is to track down bugs that only reproduce under certain compiler versions and optimization flags.

> Range checking is unavoidable regardless of whether you're using unsigned or signed ints.

Many of them are avoided when using unsigned arithmetic.

> So you're arguing that all the places where we currently use a signed int should be changed to unsigned int?

Nope! We should use the right data type for the right purpose. The high order bit is to avoid type conversions, and usually this is dictated by the API.

`size_t` is used in a lot of APIs that fish depends on. Is the parameter going to be used to index into a `std::vector`? [That uses size_t](http://www.cplusplus.com/reference/vector/vector/operator[]/). Is it going to be compared against the number of items in a `std::map`? [`size_t`](http://www.cplusplus.com/reference/map/map/size/) again. Is it the size of a buffer to pass to `write()`? [That's `size_t` too](https://linux.die.net/man/2/write).

But of course that's not the case for all parameters. File descriptors and signals should both be `int` because their APIs are cast in terms of int. That's true despite the fact that valid file descriptors and signals are never negative.

If the type isn't determined by the API, the next bit is to prefer simplicity and safety. Negative values are not simple and not safe: you have logical vs arithmetic shift, division and modulus are weird, UB is possible, INT_MIN is a bag of hurt. For those reasons, I prefer to sidestep those issues by using unsigned arithmetic whenever negative quantities aren't needed (which is most of the time).

> Such as the args for `pager_t::completion_print_item()`?

I remember that one! That code is adopted from the old `fish_pager.c`. When I ported it, it wasn't clear to me whether `width` could be negative, so I left it alone. One could kindly say, my efforts to clean it up were incomplete.

Expressions like `maxi(mini((int)c->comp_width, 2 * (width - 4) / 3), width - desc_all);` are quite frightening. The range of `width` isn't known. Might the output be negative? It looks like it. Might it overflow? Can't rule it out!

This particular code sucks, and it's totally understandable why someone would be bitten by it.

> The question you should ask is how many programmers will recognize what is being done in that assert?

How many programmers are familiar with *any* overflow checking idiom? Most just hope that integer overflow doesn't happen.

> We would be much better served by simpler code and that includes using signed arithmetic by default except where unsigned clearly makes more sense (e.g., generation counters where we need well defined overflow behavior).

I am also in favor of simpler code, which is why I prefer unsigned arithmetic. Unsigned arithmetic is much much simpler. It has far fewer edge cases and undefined behavior.

If you doubt it, I invite you to write `pager.cpp::divide_round_up()` using signed arithmetic, without artificially restricting the domain (i.e. should produce the right value for all inputs). I am actually interested to see what you come up with here.

> Where signed arithmetic might have undefined overflow/underflow behavior it is straightforward to ensure the values are in a reasonable range so that doesn't occur.

It is not at all straightforward. Handwaving about "reasonable range" is no different than hoping it won't occur.

**Comment by ridiculousfish** [comment]
> The reason it is still undefined behavior is that it allows compilers to optimize loops and the like under the assumption no overflow/underflow will occur because the programmer knew what they were doing

Right. Compilers are very aggressive about applying this assumption, and the results can be very surprising.

> Doing so causes more complexity and potential bugs than it avoids. Where we get a size_t value from a standard C++ method and there is a reason to worry its magnitude could cause undefined behavior after being cast to a signed int we should be range checking that value.

Introducing unnecessary range checks and type conversions does not help us avoid complexity and potential bugs. It introduces more of them.

**Comment by krader1961** [comment]
> I prefer to sidestep those issues by using unsigned arithmetic whenever negative quantities aren't needed (which is most of the time).

The problem is that the C/C++ rule for implicitly coercing signed to unsigned leads to surprising behavior.

> I remember that one! That code is adopted from the old fish_pager.c. When I ported it, it wasn't clear to me whether width could be negative, so I left it alone. One could kindly say, my efforts to clean it up were incomplete.

The issue wasn't that the value could be negative. AFAICT the value of that argument will never be negative. So you should have changed the type to `size_t` as I did in my problematic change. The problem is that the code assumes that subtracting another unsigned value that is larger than the `width` argument will result in a negative value. Oops! Blindly using unsigned arithmetic for values that should never be negative doesn't protect us. Notwithstanding the well defined rule for underflow with unsigned ints.

I did `git log | less` and searched for "underflow". That returned exactly one commit: 3d5a3f03 from 2012-10-8. AFAICT that bug was also due to the use of `size_t` when that wasn't needed. I couldn't find any commits that mentioned "overflow". That specific bug would not have occurred if signed ints were used. Neither would the bug I recently introduced.

I'm tired of arguing about this so I'm going to drop the issue. Fish is not an image manipulation program or a typesetting program like Donald Knuth's TeX. Which I manually translated from Pascal to C three decades ago after obtaining the source code on 9-track tape. That was my first significant effort to make a program written in C work. The nature of TeX, especially its equivalent of a unit test, made me intimately aware of things like overflow and underflow. Those issues should never be a problem for fish. Not because we use `size_t` but because we sanity check that strings and arrays are never even close to overflowing the limits of `signed int` even on platforms where that is 2^15 on system where ints two two bytes.

I admit I am perplexed by the belief that using unsigned ints is some sort of magic talisman against problems. Especially given that the compilers and lints tools are warning us about potential problems when combined with signed ints.

**Comment by krader1961** [comment]
While I'm not going to aggressively change uses of `size_t` to `int` I do intend to change them as part of other changes that touch code involving uses of `size_t` vars. Such as `for()` loops which use `size_t` for the index when that is completely pointless. I challenge you to show me that using `size_t` rather than `int` in such contexts is either more clear or faster.

**Comment by krader1961** [comment]
I wrote

> The reason it is still undefined behavior is that it allows compilers to optimize loops and the like under the assumption no overflow/underflow will occur because the programmer knew what they were doing.

And you responded

> Right. Compilers are very aggressive about applying this assumption, and the results can be very surprising.

Please provide an example where this would affect a program like fish absent not just a bug but a fundamental bug.

**Comment by krader1961** [comment]
@anordal you wrote

> I find that very few numbers have to be signed, except results of subtraction.

Therein lies the problem. There are many places in the fish code which assumes that subtracting a signed from unsigned value will result in a signed value. That is an invalid assumption given the C/C++ implicit coercion rules. Too, given the values involved within fish (e.g., screen width or height) there is no reason to need the expanded range provided by an unsigned int.

**Comment by ridiculousfish** [comment]
> Such as for() loops which use size_t for the index when that is completely pointless. I challenge you to show me that using size_t rather than int in such contexts is either more clear or faster.

This is very easy to do. Consider a simple for loop over a vector:

    void foo(double x);
    void func(const std::vector<double> &v) {
        for (int i=0; i < v.size(); i++) foo(v[i]);
    }

Let's compile with warnings:

    > clang++ -Os -S -W -Wall test.cpp
    test.cpp:6:21: warning: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Wsign-compare]

It doesn't like `i < v.size()`. We can silence the warning like so:

    void foo(double x);
    void func(const std::vector<double> &v) {
        for (int i=0; i < static_cast<int>(v.size()); i++) foo(v[i]);
    }

except this is bad because we invoke UB for large vectors, so let's add your suggested sanity check:

    void func(const std::vector<double> &v) {
        assert(v.size() < INT_MAX/2);
        for (int i=0; i < static_cast<int>(v.size()); i++) foo(v[i]);
    }

I am not sure if the assertion is correct due to integer promotion rules. Also `-Wsign-conversion` results in additional warnings. But let's stop there.

That code is certainly less clear than:

    void func(const std::vector<double> &v) {
        for (size_t i=0; i < v.size(); i++) foo(v[i]);
    }

which produces no warnings at all, and is not gratuitously incompatible with large vectors.

As for "faster," I took a look at the codegen and the inner loop is identical, so they unsurprisingly perform the same by default. Though if you enable `-ftrapv`, UBSan, etc then the unsigned one will be faster.

**Comment by ridiculousfish** [comment]
> Please provide an example where this would affect a program like fish absent not just a bug but a fundamental bug.

You got it. Consider a saturating reference count - we'll just look at increment:

    struct refcount {
        int val = 0;
        void increment() {
             if (val < INT_MAX) val++;
        }
    }

This is fine. Now let's say we want to add some tracing. We get a little careless:

    struct refcount {
        int val = 0;
        void increment() {
            fprintf(logfile, "inc count to %d\n", val + 1);
            if (val < INT_MAX) val++;
        }
    }

We forgot about the saturation in our log, but whatever. Printing the wrong value isn't fatal, is it?

Except it is! Because `val+1` overflows when `val == INT_MAX`, the compiler is free to elide the `if` statement. Our errant log (hardly a "fundamental bug") just turned our saturating refcount into a *non*-saturating refcount. Or maybe it didn't. Whether our refcount saturates is now compiler and flag dependent.

That's signed arithmetic. That scares the crap out of me!

**Comment by ridiculousfish** [comment]
> There are many places in the fish code which assumes that subtracting a signed from unsigned value will result in a signed value.

This is really scary. If it's true, then that's a cause for concern.

Do you have examples of such places? Other than ones you wrote of course :/

**Comment by andrewrk** [comment]
We're figuring out what color to paint the bikeshed over here in libsoundio too: https://github.com/andrewrk/libsoundio/issues/130

Imagine the bikeshed we could create if we joined forces...

**Comment by krux02** [comment]
I randomly stubled upon this thread. It realld is long closed and I remember trying to convince people of the same thing. It is tough and people are stubborn. Maybe it helps to say that the inventors of C++ saw it as a mistake to make `size_t` unsigned. Here you can listen to their words on your own: http://www.youtube.com/watch?v=Puio5dly9N8&t=42m41s

I am not contributing to `fish`, I am only using it. So you can do whatever you think is the best for code maintainability. But I think using `unsigned` to ensure that a Number can't get negative is as effective as putting a soccer field on a skyscraper to prevent the ball from leaving the playing field. It doesn't work, it just makes it much harder to deal with the situation if the number gets out of range.

**Comment by greggwon** [comment]
The most prominent issue for me is simply the fact that you can't do
`struct foo {
   int s1;
   int tt2[32];
  double g;
};

struct foo val;

if( read( fd, &val, sizeof(val) ) < sizeof(val) ) {
   ... report error on read..
}`

because read(2) can return -1 which is not an unsigned value and thus type conflicts with size_t for sizeof() operator and the end result is chaos for any read failure due to a socket disconnect or some other place where read can return a negative number.

**Comment by anordal** [comment]
@greggwon Bad example. If you account for the fact that partial reads are not errors, there is only one error value, namely -1. Also, the return value of `read` isn't `int`.

    ssize_t bytes = read(fd, &val, sizeof(val)); 
    if (bytes == -1) {
        // error
    }

But okay, I see you're alluding to a range check where a negative value would be an error – the common case with indexes: Guess what; this is *also* a case where unsigned numbers shine, as you only have one side to worry about.

**Comment by ridiculousfish** [comment]
Please let's not rehash this here.
