### ISSUE TITLE
How to add npm global path to Fish shell?

### ISSUE THREAD

**Issue by corysimmons** [fish-shell/fish-shell#3508]
Please add docs for the most common use case of modifying path. I've been fighting with this for a bit -- using Oh My Fish.

**Comment by krader1961** [comment]
http://fishshell.com/docs/current/tutorial.html#tut_path covers the basics. I like to have a single config file that works regardless of which system I'm on. Whether that's macOS, Linux, Cygwin, etc. Each of which has a different set of directories where programs I want to run live. So this is what I do:

```
# Customize the PATH.
if string match -q 'CYGWIN*' (uname -s)
    set -x PATH $HOME/symlinks $HOME/bin $HOME/sbin /usr/local/bin $PATH
else
    set -x PATH $HOME/symlinks $HOME/bin $HOME/sbin \
        /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin /bin /sbin
    if test -d /opt/X11/bin
        set PATH /opt/X11/bin $PATH
    end
end

test -d /usr/local/go/bin
and set PATH $PATH /usr/local/go/bin

test -x /usr/local/bin/brew
and set PATH (/usr/local/bin/brew --prefix coreutils)/libexec/gnubin \
        (/usr/local/bin/brew --prefix findutils)/bin $PATH

if test -x /usr/local/git/bin/git; and not test -x /usr/local/bin/git
    # We must be on my OS X Snow Leopard VM with an old git from the official DMG image rather than
    # from 'brew install git'.
    set PATH /usr/local/git/bin $PATH
end
```

But I'm guessing that npm (whatever that is) probably provides a script meant to be run via the `source` command in a POSIX compatible shell to set env vars. I usually just write a fish version of the script since they're almost always trivial. But if you don't want to do that it seems that most people use [bass](https://github.com/edc/bass).

**Comment by corysimmons** [comment]
Okay, thanks
