### ISSUE TITLE
`set` output should indicate if variables are local, universal, exported, etc.

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3542]
I think typing `set` without arguments ought to indicate the nature of various variables. 

An obvious way to do this would be for it to simply output commands that could recreate them.

e.g..
```
$ set
set -x LANG en_US.UTF-8
set -U fish_color_autosuggestion 333
set -Ux TERMINFO /usr/local/Cellar/ncurses/6.0_2/share/terminfo/
...
```

Or: 
```
$ set
LANG 'en_US.UTF-8' (exported)
fish_color_autosuggestion '333' (universal)
TERMINFO '/usr/local/Cellar/ncurses/6.0_2/share/terminfo/' (universal, exported)
...
```

**Comment by krader1961** [comment]
If we decide to do something like this I'd prefer to see the output written as valid `set` statements. For example,

```
$ set
set -x LANG 'en_US.UTF-8'
set -U fish_color_autosuggestion '333'
set -Ux TERMINFO '/usr/local/Cellar/ncurses/6.0_2/share/terminfo/'
```

Whether to use short or long flags is debatable depending on how we define "friendly" in this case.

**Comment by floam** [comment]
Long options might be a bit more friendly, but column count inclines me against it.

**Comment by floam** [comment]
How should electric variables be displayed?

**Comment by krader1961** [comment]
> How should electric variables be displayed?

They're read-only. Which suggests to me we should add a `set -r` and `set --read-only` flags. Not just so that "electric" vars can be clearly identified in the output of a bare `set` but also so that the user can define read-only vars safe from unintended modification.

**Comment by krader1961** [comment]
Also, I don't see any reason a bare `set` should have its output formatted differently than `set -g`, `set -l`, etc.

TBD is whether this backward incompatible change, regardless of how the output formatting is changed, can even be allowed. It might be necessary to introduce a flag that requests the `eval` compatible format.

**Comment by floam** [comment]
Could also just comment them out, to keep it eval-compatible. 

`#set status 0`

**Comment by krader1961** [comment]
> Could also just comment them out, to keep it eval-compatible.

Yes, that works if we decide to not allow the user to define read-only vars. Personally, I think we should add that feature. On the other hand that's a pretty big change and has subtle implications. For example, should we allow `set -l ro_var temp_value` inside block scope? Bash doesn't allow that so probably shouldn't either. There are many related questions which are orthogonal to this issue. To keep the scope of this issue as narrow as possible I would initially implement it as you suggest: emitting those vars as "comments".

As before since whatever we do would not be a backward compatible change we need to decide if it should be done without introducing a new flag or, perhaps, predicating the change in output on whether we're in interactive context. We've had a lot of people complain about minor incompatible changes in behavior recently which suggests to me we need to be more thoughtful about these types of changes.

**Comment by floam** [comment]
And electric variables are more than just read-only, they are truly magic. I think `$status` or `$CMD_DURATION` are fair examples of variables you simply cannot recreate.

**Comment by floam** [comment]
Does anyone have any strong opinions regarding the output of `set` changing, with regards to backwards compatibility?

**Comment by ridiculousfish** [comment]
I think `fish_config` parses the output of `set`, we may have to update that.

**Comment by floam** [comment]
I believe we also parse it for the `set` completions.

**Comment by krader1961** [comment]
> And electric variables are more than just read-only, they are truly magic.

Yes, so we might want to add another comment line explaining why those vars are "commented out".

> Does anyone have any strong opinions regarding the output of set changing, with regards to backwards compatibility?

Yes, because several recent changes that break backward compatibility in very minor ways have been shown to be controversial. A couple of those I argued for which in retrospect I regret. I've become too accustomed to making such changes on an internal (i.e., non-public) project where the impact can be carefully managed. I now believe that even "minor" (as in unlikely to cause a problem) backward incompatible changes need a really strong justification.

**Comment by krader1961** [comment]
Also, I said earlier

> predicating the change in output on whether we're in interactive context.

That isn't sufficient. It might be sufficient to predicate the change in behavior on whether stdout is a tty.

**Comment by krader1961** [comment]
Also, it is likely to surprise someone that the output of `set` is different depending on whether the destination is a tty or something else (e.g., a file or pipe). Which will also lead to people telling us that fish has a bug since there is no obvious reason for the format of the output to differ in those situations.

Sadly, as much as I would like to see the format of the output improved as previously discussed I don't think we can do so without introducing a new flag or only doing this if we change the major version number. Anyone wanting the new, improved, output can define a `set` function. It might even be possible for us make that easy to do via a function that only prompts the user the shell is interactive, stdout is a tty, and there were no other options and then creates a user specific `set` function.

**Comment by zanchey** [comment]
You can already get a list of variables with various scopes using `set -g`, `set -l`, `set -Ux` etc.

**Comment by floam** [comment]
> You can already get a list of variables with various scopes using set -g, set -l, set -Ux etc.

That feels kind of roundabout to me.

**Comment by vaz** [comment]
I don't see an issue with keeping the output as it is (there are enough use cases for machine-parsing the current output without caring what scope it comes from, it is already used that way even in fish as mentioned above).

I'd be happy to see a `-v`/`--verbose` flag that does exactly what OP describes, outputs in a format that could be eval'd directly. It's trivial then to alias `set` to `set -v` when there's a tty. (In that case, I could see ignoring the verbose flag if `set` is being used to actually set (or export, etc) variables.

I found this issue while having something slightly different in mind, which is that it's surprising to me that `set -q` doesn't output. I can see the logic (not having to `^/dev/null` all the time in scripts). But in a tty shell some output would be much better. (Not everyone has a prompt that shows non-zero `$status` quickly, and checking it in an interactive session is a pain.)

I guess changing the behaviour would be an ugly pain for a ton of existing scripts, but having such a `--verbose` option apply to `-q` too seems like a good solution.

**Comment by krader1961** [comment]
> You can already get a list of variables with various scopes using set -g, set -l, set -Ux.

The problem with that is that if I do, for example, `set -U` it would be really nice if the output also made it clear which vars were also exported.

I agree with @vaz that the new output format has to be enabled explicitly via a flag and `-v` or `--verbose` is the obvious candidate. Also, we can't change the `set -q` behavior to write to stdout if stdout is a tty because there are undoubtedly functions run interactively which use `set -q` and we don't want the to suddenly start writing to stdout. But making `set -qv` write to stdout is okay since we're introducing a new flag combination. It might be possible to modify `builtin set` to check whether the command was entered interactively rather than being run from a function or script (including a `source`d script). If so then we can safely have `set -q` also write to stdout when run interactively (which is not the same thing as `status --is-interactive`).

I'm going to remove the RFC label since I think we have a consensus which would allow someone to create a PR.

**Comment by krader1961** [comment]
Does the `set --show var_name` feature I introduced resolve this? It is a different solution to what was envisioned when this was opened but does seem to address the need expressed by this issue. For example:

```
$ set -U abc universal value
$ set -gx abc global
$ set -l abc local value
$ set --show abc
$abc: set in local scope, unexported, with 2 elements
$abc[1]: length=5 value=|local|
$abc[2]: length=5 value=|value|
$abc: set in global scope, exported, with 1 elements
$abc[1]: length=6 value=|global|
$abc: set in universal scope, unexported, with 2 elements
$abc[1]: length=9 value=|universal|
$abc[2]: length=5 value=|value|
```

And this:

```
$ set --show CMD_DURATION                              1.7  m
$CMD_DURATION: not set in local scope
$CMD_DURATION: set in global scope, unexported, with 1 elements
$CMD_DURATION[1]: length=6 value=|101635|
$CMD_DURATION: not set in universal scope
```

**Comment by floam** [comment]
It probably does resolve this issue, although I'm not a huge fan of the output, which will inevitably be language-dependent. I'd have preferred something more similar to what I proposed way up above, albeit the fact we can't express read-only variables.
