### ISSUE TITLE
Shell specific PATH modifications

### ISSUE THREAD

**Issue by maxnordlund** [fish-shell/fish-shell#3548]
- [X] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.4.0

**OS/terminal used**: 
MacOS X 10.11.6/iTerm2 3.0.10

## Feature suggestion
It would be pretty sweet if there were an analog to the `$fish_user_paths` for specific shells to allow things like https://github.com/postmodern/chruby which is like rbenv but sets the PATH to point to the correct ruby version.

It would also allow for an alternative to the `.git/safe/../../bin` hack. I'm sure there are other uses as well, but this is what I got on top of my head.

I propose it would be named `$fish_shell_paths` and would work exactly as `$fish_user_paths` with the additional requirement to come before the latter.

Thoughts?

**Comment by faho** [comment]
Why not just modify $PATH directly?

The point of $fish_user_paths is that it's a universal variable. If you want these things to be global, then you can just use $PATH.

>the .git/safe/../../bin hack.

What's that?

**Comment by maxnordlund** [comment]
Try, but it feels wrong to mess with the path when you shouldn't do that in your `config.fish`. It also would enable third parties to have a cleaner (IMHO anyways) way of interacting with the users PATH.

The `.git/safe/../../bin` hack is to use bin stubs, aka repo scripts, without adding `./bin` to your path since that is a security risk. Instead you can mark "safe" repos by doing `mkdir .git/safe`.

https://robots.thoughtbot.com/but-i-dont-want-to-bundle-exec

**Comment by faho** [comment]
>Try, but it feels wrong to mess with the path when you shouldn't do that in your config.fish. 

Who said that? There's no problem with doing that. That would also be cleaner and better known than what we could do. 

The issue with another variable is that we either add a second variable or modify $PATH for every command search - i.e. do $fish_shell_paths lookup, then do $PATH lookup, or we add a function that constructs $PATH, like we do for $fish_user_paths - see `__fish_reconstruct_path` in share/config.fish (it's not pretty and there's a lot of subtlety to it). 

The former would also be worse to diagnose for people unfamiliar with it, since now you'd need to know that fish also uses fish_shell_paths, especially if you added a "plugin" that added stuff to it for you.

>The .git/safe/../../bin hack is to use bin stubs, aka repo scripts, without adding ./bin to your path since that is a security risk. Instead you can mark "safe" repos by doing mkdir .git/safe.

Interesting. Personally, I'd just type "./bin", but I know a lot of people use this stuff differently.

**Comment by krader1961** [comment]
Perhaps I'm missing the point of the proposal but I don't see how this helps. You're still left with a single var that multiple third party tools manipulate in order to pick specific versions of various tools (ruby, python, jsnode, etc.). How is having them manipulate `$fish_shell_paths` any better (or safer) than just manipulating `$PATH`? For example, I have two functions named `con` and `coff` that manipulate my `$PATH` to select (or unselect) a specific [Anaconda Python](https://docs.continuum.io/anaconda/) environment. They're just fish shims to the Anaconda `conda` command (similar to the `rbenv` command). Been using them for a year. Never had a problem or felt a need for another layer of indirection.

**Comment by ridiculousfish** [comment]
`fish_user_paths` exists only because, if you set PATH as a universal variable, then it would overwrite whatever gets inherited from the environment. As faho says, it's safe and encouraged to modify PATH directly.

**Comment by maxnordlund** [comment]
I didn't know it was safe to manipulate the PATH, which I assumed was not because of the universal variable for the users' path.

@krader1961 you're right about different tools needing to play nice with each other, but having a separate variable would contain any damage a bug would cause.

With that being said, I'll close this But maybe it would be good to document where and how one should manipulate the PATH.
