### ISSUE TITLE
fish shells sometimes don't notice the history file has changed

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3565]
We've had several reports about `history merge` not working. Most recently in issue #3496. I've noticed this as well and should have opened an issue many months ago. The problem is that sometimes a fish shell does not notice that the history file has been replaced. The fish instance continues to use the file descriptor on the now deleted history file. Which means that any commands it executes won't be seen by other fish instances. It also means that running `history merge` in that shell won't notice any commands run by the other fish instances.

I actually have a couple of fish instances on my system as I type this which are using old, no longer existing, fish history files. Which I found via the debugging steps in this comment I made in issue #3496:

Based on my testing what is happening is that sometimes a fish instance doesn't notice that fish history file has changed and continues writing to an old, no longer existing, history file. Which also means that when you do history merge it is reading a history file that is not being updated by other fish instances.

You can see this by running lsof -p %self in each of your shells where history merge isn't working. Find the line mentioning the ~/.local/share/fish/fish_history file. The number under the NODE column is the inode number of the file. What you'll see is that the two fish instances have different node/inum values. If you do ls -i ~/.local/share/fish/fish_history you'll see that only one of them matches the inode number of the current history file. That's what I see on my systems when history syncing stops working.

**Comment by ridiculousfish** [comment]
I think this is working as designed. The intended user experience of history is that, at startup time, each session sees a snapshot of the merged history of all previously run commands, which is *not* dynamically updated from other sessions:

1. In session 1, `echo alpha`
2. Create session 2. Its history will contain `echo alpha`
3. In session 1, `echo beta` 
4. Session 2's history is still just `echo alpha`

Because a session's history is conceptually a snapshot, it's fine and good for each session to *read* from a "stale" file descriptor. The file may have been replaced by another session, but we don't want to see new changes anyways.

However of course when we write, we need to write to the most current file. So that's when we detect the changed file. You can see some of this logic in `save_internal_via_appending()`:

        // Check to see if the file changed.
        if (file_id_for_fd(out_fd) != mmap_file_id) file_changed = true;
        ...
        // If someone has replaced the file, forget our file state.
        if (file_changed) {
            this->clear_file_state();
        }

So `lsof` may show a stale history file open and read from, BUT we should never write to that stale file.

**Comment by krader1961** [comment]
It might be working as designed but it's not working as I, and probably nearly everyone else, expects. I see the point of reading from a file descriptor open on a stale history session file. That's needed due to how searching the history uses mmap() and walks through the history as if it were a data structure stored in memory. But `history merge` is supposed to allow the user to explicitly say "please switch to the current history file" (or something like that). And that isn't happening.

So the file descriptor open on a stale history file might be expected and not really indicative of a problem if the user never runs `history merge` but after doing so shouldn't the fd be closed and reopened on the current history file?

**Comment by ridiculousfish** [comment]
The design is that `history merge` always discards a stale file, as you expect. It opens the new file lazily, when history is next requested.

> So the file descriptor open on a stale history file might be expected and not really indicative of a problem if the user never runs history merge but after doing so shouldn't the fd be closed and reopened on the current history file?

Yes it should. If you see otherwise, that's definitely a bug.

(I should confess there's one known race condition here: multiple calls to `history --merge` within the same second may be coalesced into the first call, so we may miss items. This is hard to do by hand, but a script can make it happen. I need to get around to fixing this.)

**Comment by krader1961** [comment]
> If you see that the old fd is still open after history --merge, that's definitely a bug.

I was reasonably certain I observed that but cannot reproduce it at this time. However, I rebooted my two main systems a few hours ago to update macOS. I'll keep a close eye on the behavior of `history merge` for the next few weeks. Especially in light of your recent commit 9b4310b that I installed prior to those reboots.

**Comment by krader1961** [comment]
A week has gone by and I'm no longer seeing the problem with @ridiculousfish's commit 9b4310b10. So I'm going to close this as resolved. If the problem reappears we can reopen.
