### ISSUE TITLE
How does set PATH work?

### ISSUE THREAD

**Issue by introom** [fish-shell/fish-shell#3580]
Some previous issues discussed the invalid PATH warning.

I am generally interested in how the PATH validation works.

Some facts are:
1. fish doesn't check path validity on inherited PATH env from parent process.

2. set PATH /nonexistent  fails.

3. set PATH $PATH /nonexistent will succeed. (though with some warning).

Looks like 1,2,3 all in all are a little bit contradictory to each other.

**Comment by krader1961** [comment]
Case 1 is deliberate and should not be changed. I can't reproduce case 2. I get the warning for both 2 and 3. What is different is that we keep the existing PATH if you attempt to set it to a sequence of pathnames that do not contain a single valid pathname. If you include at least one valid pathname then it sets it and includes the invalid ones; same as case 3. For example,

```
$ set PATH /bad /really/bad /bin
set: Warning: $PATH entry "/bad" is not valid (No such file or directory)
set: Warning: $PATH entry "/really/bad" is not valid (No such file or directory)
$ echo $PATH
/bad /really/bad /bin
```

If that's what you're observing that is the expected behavior. If you're seeing something else please elaborate.

**Comment by introom** [comment]
"What is different is that we keep the existing PATH if you attempt to set it to a sequence of pathnames that do not contain a single valid pathname. If you include at least one valid pathname then it sets it and includes the invalid ones"

That's what I experienced.
