### ISSUE TITLE
__fish_vcs_prompt has a noticeable delay on mercurial repos

### ISSUE THREAD

**Issue by introom** [fish-shell/fish-shell#3582]
I use a vanilla __fish_vcs_prompt as my fish_right_prompt.

I cloned the cpython repo, 
hg clone https://hg.python.org/cpython

and cd into that repo.

There is a noticeable delay in showing the right prompt.

A screen-record is here:

https://asciinema.org/a/1nzdqiz0gzgfji5x6vg3xnjaq

In the above record, when I run "ls", there is a significant delay in showing the prompt.

I'd suspect it's due to how the mercurial repo info is calculated inside __fish_vcs_prompt.

**Comment by faho** [comment]
Fish has a "--profile" option that produces some useful info. Can you use that with something like `fish --profile right_prompt.prof -c 'fish_right_prompt'`? This will create a file called "right_prompt.prof" that includes the profile information. I find that `sort -nk2 right_prompt.prof` will help to figure out what takes the longest.

My suspicion is that this is just mercurial being somewhat slow.I don't believe there's much more to be done to optimize the hg_prompt on our end, considering we call `hg` _once_ and do everything else ourselves (we read the branch directly from the file, we figure out if we might be in a hg repo by checking for a ".hg/dirstate" file).

**Comment by introom** [comment]
From the profile, it turns out `hg status' takes the most time.

I previously used zsh with __vcs_info enabled, and there was no time delay to show the repo info.

Are you aware of the implementation?

**Comment by faho** [comment]
>From the profile, it turns out `hg status' takes the most time.

That's what I expected. And from my experience, there is no better hg call, since the largest part of that is just startup time.

>I previously used zsh with __vcs_info enabled, and there was no time delay to show the repo info.

>Are you aware of the implementation?

I wasn't, but I checked just now. It turns out they (by default) don't call hg at all. Instead they use `hexdump`. I'll have a look if that can be adapted for fish. The issue there is that, as far as I can tell, there's no way to detect uncommitted changes with that approach, which I find rather useful.

How much delay are we talking about here? My internet connection currently is bad so I can't clone that repo, but my tests were always less than 100ms, which I still find tolerable.

**Comment by introom** [comment]
I am also experiencing a delay around 0.1s.

Instead of showing all the details, I now only set the prompt to show the branch name, which takes almost no delay.  I am ok with this setup.
