### ISSUE TITLE
need support to adjust the layout of the completion pager.

### ISSUE THREAD

**Issue by introom** [fish-shell/fish-shell#3592]
As shown in this pic:
http://imgur.com/a/zTBZR

The completion pager is too narrow, ignoring all the available space and making it aesthetically unpleasing.

**Comment by floam** [comment]
One thing you do lose with the pager growing to available width (while neglecting your large height available), is if everything is one just one row you can only navigate horizontally. To select an item roughly in the middle of the screen will require more keystrokes and time than if you could jump over areas with it wrapped.

**Comment by introom** [comment]
Can it be a pre-hook function passed wit the term size, and the number of completion items, 
the result is the NxM (nrows, mcols) ?

**Comment by floam** [comment]
Fish actually knows the terminal size, the rows and columns.

**Comment by faho** [comment]
Our logic yields something that is roughly square, which means you get the most opportunities to use different cursor keys.

The `ls` output you've shown is also just quite broad and I'd argue more difficult to scan at a glance since there's only one dimension to go in. The jarring thing here is really the stark difference between the two. If you don't currently have one-row ls output before the completion, it doesn't look as bad.

I'm wary of allowing configurability here since it gets quite complicated once you factor in descriptions.

>Can it be a pre-hook function passed wit the term size, and the number of completion items,
the result is the NxM (nrows, mcols) ?

That's not enough data actually. You really need the full text of all completion items, plus the description texts (since you might want or need to ellipsize them). This alone isn't easily representable in $argv.

I don't think we want to take this on. If anyone comes up with a better way of doing it (ideally just an all-around improvement instead of an option), we'll take a look at it.

Until such time, I'm closing this. Sorry.
