### ISSUE TITLE
port manpage completions from python

### ISSUE THREAD

**Issue by aeosynth** [fish-shell/fish-shell#3609]
it would be nice if the manpage completions script were ported away from python, as fish is currently the only reason i have python installed. would a pr for this be accepted?

**Comment by ridiculousfish** [comment]
This script is pretty big, so this sounds like a big effort. What language would you port it to?

**Comment by aeosynth** [comment]
`deroff.py` + `complete_manpage_completions.py` are about 2k loc, which seems manageable, especially if most of it is a very direct, mechanical port. the point is to reduce dependencies, so i was thinking of using fish + awk.

**Comment by ridiculousfish** [comment]
fish wants to have access to one real scripting language for auxiliary features, including `fish_config` and the manpage completions. It's not a goal for fish to break this dependency, and frankly maintaining a shell+awk script sounds less pleasant than a Python program. So I think we'd decline this.

Can I ask, are you looking at the manpage completions because you use them and they're valuable to you? Or is it because updating completions occurs automatically, and throws errors if Python isn't installed? The fish bespoke completion set has pretty good coverage already, so that you don't lose much by omitting manpage competitions. If your concern is just errors at install or startup, we can just fix those.

**Comment by aeosynth** [comment]
my goal was to reduce dependencies, and honestly i haven't really looked at the manpage completions. i will try life without them.

**Comment by floam** [comment]
> Or is it because updating completions occurs automatically, and throws errors if Python isn't installed? 

This shouldn't happen after https://github.com/fish-shell/fish-shell/commit/4f6ac06b211e7b858c9c88d227ce7256f9d71462
