### ISSUE TITLE
documentation for `function --inherit-variable` is not clear

### ISSUE THREAD

**Issue by adamcavendish** [fish-shell/fish-shell#3626]
How can I set the value of the variable to a variable?

```
set foo "hello"

function dummy
  set -l local_foo "$foo"
  echo $local_foo
end

set -e foo

dummy
```

And I hope that the dummy function will print "hello"

**Comment by krader1961** [comment]
You're trying to use a [closure](https://en.wikipedia.org/wiki/Closure_(computer_programming)). Fish does not support closures. In fact I'm not aware of any command line shell that does so. It's a common feature of languages like Python which have first-class functions.

**Comment by ridiculousfish** [comment]
Actually fish does have something to offer here, the `--inherit-variable / -V` flag to `function`:

```
set foo "hello"

function dummy -V foo
  set -l local_foo "$foo"
  echo $local_foo
end

set -e foo

dummy
```

prints "hello"

@adamcavendish  Is that what you're looking for?

**Comment by krader1961** [comment]
@ridiculousfish: That doesn't work at all the way I would expect given the verbiage on the man page. In particular the "when the function is executed" portion of the description. It does indeed do what @adamcavendish is trying to do. However, that isn't what the documentation implies. If you instead do

```
set foo "hello"
function dummy -V foo
  set -l local_foo "$foo"
  echo $local_foo
end
set foo "goodbye"
dummy
```

You get `hello` as the output. Since the current behavior is meant to provide closure like behavior the documentation needs to be changed (e.g., change "runtime" to "at time of definition" and add the word "closure"). And the example at the bottom could use a little more explanatory text.

**Comment by ridiculousfish** [comment]
Hmm, on a read the documentation is ambiguous:

    snapshots the value of the variable NAME and defines a local variable with that same name and value when the function is executed

that "when the function is executed" is meant to apply only to the "defines a local variable" part, not also the "snapshots..." part. It may be improved by adding a comma:

    snapshots the value of the variable NAME, and defines a local variable with that same name and value when the function is executed

but this can probably be improved still. So I agree.

**Comment by krader1961** [comment]
Also, ignoring for the moment that `functions dummy` does not include any `-V` attributes if you do `funced dummy`, add the missing `-V foo`, and save the resulting definition it does not snapshot `foo` again. Which seems wrong. Why would using `source` within the `funced` function to redefine the function not cause the current value of `foo` to be snapshotted again?

**Comment by adamcavendish** [comment]
@ridiculousfish Yes, thank you very much
