### ISSUE TITLE
Is it possible to use the linux installer of fish to install fish shell on a windows machine under cygwin?

### ISSUE THREAD

**Issue by thedonquixotic** [fish-shell/fish-shell#3631]
Hi, I'm a project manager/UX Designer for a non-profit hackathon group and I'm just trying to figure out some best practices for our teams. I am not trained as a computer scientist and I am not a dev but I am trying to learn and I was hoping if I could get something clarified. 

Is it possible install the linux installer of fish inside of cygwin on a windows machine?

I know that fish shell has a native windows app, and I know that it is possible to compile fishshell within cygwin in order to use it there, as per issue 319 and 680 which I presume to be outdated at this time, now that there is a windows install of Fish, but neither of these are preferable options. I'm trying to make as tightly self contained a environment as possible so that it can be easily distributed to non tech people at hackathons and get them up and running ASAP. Cygwin already has bash installed, and we could just use bash but I like Fish shell and I feel that it would help easy non-technical users into using CLIs for projects. 

I'm sorry if this is not following standard issue format, but I would be very appreciative if anyone could shed some light on this issue.

**Comment by faho** [comment]
There is no "linux installer of fish". There are linux _packages_ but those require a package manager and the file system structure and libraries that the package expects. You couldn't even install the openSuSe package on Archlinux or Ubuntu (well, probably not, I haven't tried).

I'm not all that familiar with Cygwin, but from what I read at https://cygwin.com/cygwin-ug-net/ov-ex-unix.html, you should be able to install fish via cygwin's setup.exe. It's available in the "shells" category. Any reason that won't work?

**Comment by krader1961** [comment]
> I know that fish shell has a native windows app...

Actually, it does not have a native MS Windows app. It does however build and run in the Cygwin environment which provides a UNIX like environment on MS Windows.

If you want to use a fish built from git head rather than whatever is available via the Cygwin setup program that relatively straightforward. The nice thing about fish is it is self-contained. After you do `autoconf; ./configure --prefix=/usr/local; make install` (or whatever prefix you prefer) it is a simple matter of copying a few directories and three executables to install it on a second machine. You could create "tar" archive and distribute that.

Beyond that advice we're moving into consulting territory. But if there is anyone on your project who has compiled open source code on Cygwin before they should be able to get you bootstrapped very quickly.

**Comment by zanchey** [comment]
@thedonquixotic, I think if you're already installing Cygwin then it is best to use the fish shipped with Cygwin - @andrex-e-schulman does a great job of maintaining the package there. You can set up a terminal shortcut to open fish instead of bash to drop people straight into the environment.

**Comment by andrex-e-schulman** [comment]
Yes, you should use the fish package in Cygwin. It's up to date. If there are problems you can report them to the Cygwin list, cygwin@cygwin.com.

**Comment by krader1961** [comment]
I think this has been answered so closing. Feel free to reopen, @thedonquixotic, if you need additional help.
