### ISSUE TITLE
unparsable value for LS_COLOURS environment variable

### ISSUE THREAD

**Issue by stephanecharette** [fish-shell/fish-shell#3633]
**fish version installed** *(`fish --version`)*:
fish, version 2.4.0-219-g59fa04b

**OS/terminal used**: 
64-bit Ubuntu 16.04, using the nightly fish PPA:  deb http://ppa.launchpad.net/fish-shell/nightly-master/ubuntu yakkety main

I see some references to past tickets about the error message "unparsable value for LS_COLORS".  But in my case, the error I get is "unparsable value for LS_COLOURS".  Note the spelling of COLOURS with a "U".  (I am in Canada, with Ubuntu setup with the Canadian-French keyboard, etc.)

I've never before attempted to customize the colours, and have no idea how fish is smart enough to know about the "U" in colour.  I do not have a variable named LS_COLOURS, but I do have one named LS_COLORS.

## Reproduction steps
1. ls -l
2. echo $LS_COLOURS
3. echo $LS_COLORS

## Results
```console
stephane@loup ~/test> ls -l
ls: unparsable value for LS_COLOURS environment variable
total 0
-rw-r--r-- 1 stephane stephane 0 Dec  9 11:39 readme.txt
stephane@loup ~/test> echo $LS_COLOURS

stephane@loup ~/test> echo $LS_COLORS
'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
```

**Comment by faho** [comment]
This is a bit weird. I'm assuming the "U" is a red herring since I don't want to believe that GNU ls is stupid enough to make a configuration-key (which the variable name is) locale-dependent, and because I can't get it to read $LS_COLOURS with en_GB. So let's assume for the moment that's just some weirdness in the error message.

Your $LS_COLORS is actually invalid in the same way that it was invalid in #3630 - it has additional quotes around it.

Commit b48b2ddfb21dbd04dcfa0a3378167109d403a29e, which you should have according to your version, was supposed to fix just that.

Can you post the output of `dircolors -c`? Most likely we just missed some other weird case.

Also try `set LS_COLORS (string trim -c \' -- $LS_COLORS)` (after running ls once in that session).

Another possibility is that you've just forgotten to restart fish since you updated to a version containing the fix. Can you check that?

**Comment by stephanecharette** [comment]
I did a sudo apt-get dist-upgrade and it picked up a new version of fish.  I'm now running:

stephane@loup ~> fish --version
fish, version 2.4.0-222-g05a640b

I exited the shell, started a new one, and now file & directory colours are working again.  So this ticket can be closed.  Don't know what happened there.

**Comment by zanchey** [comment]
In the dark ages, `ls` did support the `LS_COLOURS` variable as well, but that was [excised 20 years ago](http://git.savannah.gnu.org/cgit/coreutils.git/commit/?id=482d5be531dc28b4aee7f18324d02b5dc1a41a27). However, the message that gets printed with an invalid value is [translated by gettext](http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/ls.c#n2583), and it looks like the translation has the localised variable name. I don't know where it comes from - I can't find any references in any of the source packages!
