### ISSUE TITLE
grep "" error，use ' is ok

### ISSUE THREAD

**Issue by gMan1990** [fish-shell/fish-shell#3634]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.3.1

**OS/terminal used**: 
OS: Windows 7 Professional with Service Pack 1 Build 7601 x64 zh-cn
terminal: D:\Cygwin\cygwin64\bin\mintty.exe

Talk about the the issue here. 
grep "[^/]$"
![image](https://cloud.githubusercontent.com/assets/5050994/21074355/d188c53e-bf31-11e6-94b8-069c3d80a280.png)

## Reproduction steps
1. step one
2. …

## Results
```console
~ $ math 2 + 2
5
```

**Comment by faho** [comment]
I find that screenshot kind of hard to read - is that `grep "[^/]$"` (i.e. the last character in quotes is a dollar-sign)? In that case, this is working as expected - variables are expanded in double-quotes and this reads like a variable with an empty name. Escape the "$" - `"[^/]\$"` or use single-quotes.

**Comment by gMan1990** [comment]
ok, got it ;;;;;     grep "[^/]\$" 

![image](https://cloud.githubusercontent.com/assets/5050994/21074599/c3f25542-bf37-11e6-94eb-e3c028914c88.png)

**Comment by faho** [comment]
Now I'm confused. That first ls is `ls | grep "[z]$"`, right? Why is that working?

**Comment by radomirbosak** [comment]
Maybe the last screenshot was taken from bash. I think that in case of empty variable name, bash treats the the dollar sign as if it was escaped (I was able to reproduce this behaviour in bash).

**Comment by faho** [comment]
Ah, right.

In that case....

Bash has several cases where when it can't expand something it passes the literal through. One well-known case is "*" - if you do `for i in *`, bash will (by default, without the failglob option) always execute that loop at least once, with "*" as the argument if there is no match. This causes quite a few problems that are often difficult to debug.

Fish isn't bash, and prefers to handle these cases differently, up to raising an error. This is quite intentional.

@gMan1990: If you have any suggestions on how to make this clearer (better wording for the error, perhaps?) I'd be delighted.

**Comment by krader1961** [comment]
FWIW, I agree that we should not do what bash does in this case. The bash behavior seems friendlier at first glance but it's inconsistent and that isn't friendly. Note that you don't even need a regexp as such or to use a command like grep. Just do `echo x$` and notice that bash prints `x$` same with `echo x$~` rather than reporting that the variable reference is malformed as fish does.

**Comment by krader1961** [comment]
I don't think this can be improved upon and the consensus is we do not want to silently ignore the malformed variable reference like bash does. What the screenshot in the original comment doesn't show is that fish actually points to the source of the problem:

```
$ echo x$~
$~ is not a valid variable in fish.
fish: echo x$~
             ^
$ echo "x$"
Expected a variable name after this $.
fish: echo "x$"
             ^
```
