### ISSUE TITLE
fish imports invalid commands (along with valid) from bash's history

### ISSUE THREAD

**Issue by sixpointzero** [fish-shell/fish-shell#3636]
### system info
```
~ $ fish --version
fish, version 2.4.0
~ $ uname -a
Linux user 4.4.36-1-lts #1 SMP Fri Dec 2 14:35:21 CET 2016 x86_64 GNU/Linux
~ $ xfce4-terminal --version
xfce4-terminal 0.8.1 (Xfce 4.12)
~ $ cat /etc/os-release 
NAME="Arch Linux"
```

### the issue
It seems that `fish` indiscriminately imports `bash`'s history when it's invoked for the first time. As a result, some invalid commands are also imported which work in `bash` but not in `fish`. These invalid commands are then offered as autosuggestions which, obviously, don't work in `fish`. It seems like `fish`, in this case, prioritizes eye-candy over functionality.

Moreover, I think that it's illogical to import `bash`'s history considering that `fish` and `bash` are different shells and `fish` doesn't adhere to POSIX. It also seems "normal" that fish not have any history when it's started for the first time because, well, it *is* started for the first time.

I've also talked about this issue over [here](https://gitter.im/fish-shell/fish-shell?at=584bb7b8c29531ac5d44ee14).

### reproduction steps
1. create a custom alias in `bash` `alias dwn=aria2c -x4`
2. use the alias in `bash` `~ $ dwn -d /data/downloads "https://xy.org/xy.pdf"`
3. install `fish` and type `dw`. `dwn -d /data/downloads "https://xy.org/xy.pdf` is auto-suggested and it won't work in `fish`
```
~> dwn -d /data/downloads "https://xy.org/xy.pdf"
fish: Unknown command 'dwn'
```

**Comment by faho** [comment]
There are a bunch of related things in here.

One is that that suggestion is offered even though fish _knows_ it's invalid - nothing called `dwn` exists. So far, I haven't managed to reproduce this.

The larger thing is the idea that fish shouldn't import bash history. Personally, I think it's useful, and that we should just improve the importer whenever an example of it importing something syntactically invalid pops up. 

We might also want to not import items with non-existent (in fish) commands, but I'm not sure about that since in general we can not guarantee that history never contains non-existent commands - you could delete something after using it. So I think it is preferable to just not offer suggestions with non-existent commands (as stated above).

Another possibility is to just never offer these history items with non-existent commands, but that would preclude just looking up an earlier then-valid item or taking an invalid one and editing it until it's valid.

>Moreover, I think that it's illogical to import bash's history considering that fish and bash are different shells and fish doesn't adhere to POSIX.

There is a substantial common subset. And this subset probably comprises what you execute the most - e.g. simple `command arg1 arg2` calls, maybe a simple ">/dev/null" redirection, a simple variable-expansion (and a dash of pepper).

Stuff like `pacman -Syu` or `apt update` or `ls` or `echo I am the greetest` is stuff you can get from bash history, and so you'd never have to type the entire thing in fish - not even once.

**Comment by krader1961** [comment]
As I said on Gitter:

FWIW, I think we should continue to import the bash history. For the vast majority of users it will mostly contain commands usable by fish. For a smaller subset of bash users, like yourself @sixpointzero, which rely heavily on aliases it will be somewhat less useful. But as @faho pointed out after you've used fish for a couple of weeks those unhelpful history entries will stop appearing in the autosuggestions by virtue of being old.

The problem with making importing bash history configurable is not that it requires adding a flag or similar mechanism; i.e., make it configurable behavior. It's that by the time the user knows they wanted that non-standard behavior it's too late to use configure fish not to do it.

It would be more helpful, IMHO, to tag those imported entries so that they can be easily shown and removed with the history command.

**Comment by ridiculousfish** [comment]
fish is supposed to never autosuggest invalid commands. If it does, that's a bug.

However we do allow invalid commands in history. We do some very naive checks now (`should_import_bash_history_line`) that could be improved if someone wanted to take it on.

It's an important feature to have your history available on first run. This is part of making a great first impression, which is critical to overcoming the resistance to change (users look for excuses to give up). The implementation can be refined, but we definitely want to continue importing foreign shell history, in some capacity.

**Comment by sixpointzero** [comment]
> It's an important feature to have your history available on first run. This is part of making a great first impression, which is critical to overcoming the resistance to change (users look for excuses to give up). The implementation can be refined, but we definitely want to continue importing foreign shell history, in some capacity.

Would it be acceptable to add an option to disable the `bash` history importer, perhaps in the form of a compile time option? If not, `fish` should at least somehow check for invalid commands (bash aliases and functions) and not import them.

**Comment by krader1961** [comment]
> Would it be acceptable to add an option to disable the bash history importer

No for a variety of reasons already discussed.

> at least somehow check for invalid commands (bash aliases and functions)

Any ideas how to do that without creating false positives and still being fast at doing the initial import? As @ridiculousfish pointed out we already have a framework for doing so; see the `should_import_bash_history_line()` function. If you can provide some examples of the commands that shouldn't have been imported and tell us why they should have been ignored we might be able to enhance that function to skip them.

**Comment by krader1961** [comment]
I'm going to remove the "RFC" label because there is one pretty obvious way the import of bash history could be improved. Parse the command line and reject it if is is not valid fish syntax. This is probably as simple as calling `parse_tree_from_string()` on each bash history entry and ignoring those that cannot be parsed.

This would not reject commands that do not exist for fish. Perhaps they were bash aliases or functions. Perhaps they aren't in the fish `$PATH`. But I consider that a feature. Because if you subsequently define a fish function by that name or otherwise make that command available then the history entry will be valid. Conversely consider commands that were valid for fish in the past but are no longer valid because the external command has been eliminated or the function has been removed. Should fish remove those commands from its history? No!

**Comment by krader1961** [comment]
I made the obvious, trivial, change and `make test` now fails a few bash history import tests. TBD is whether those tests should fail (almost certainly yes) and perhaps add additional tests.
