### ISSUE TITLE
`set` should reset `$status` before executing

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3651]
While testing an unrelated change I noticed that if I ran a command with a non-zero status followed by `set var value` the exit status of the `set` still reflected the previous command. That is dangerous. The `set` command should only retain (i.e., propagate) the status of any subcommands involved in executing that command. It should not retain the exit status of the previous, unrelated, command. For example, consider

```
false
set var (echo val)
echo $status
```

The fact the `false` command failed is completely irrelevant to the success of the subsequent `set` command. I haven't looked at the parse tree and how it is evaluated so this may be trivial or extremely difficult to fix. There is also the question of whether fixing this is considered a backward incompatible change.

**Comment by faho** [comment]
Wait...

That example for me echoes status 0, because that's what `echo` returned.

Are you saying that shouldn't happen or do you see different results?

**Comment by krader1961** [comment]
You're correct. I copied the wrong line while experimenting. Just do

```
false
set var abc
echo $status
```

**Comment by ridiculousfish** [comment]
I agree, `set` should reflect success if there were no subcommands. Nice find.

**Comment by ridiculousfish** [comment]
`set`s behavior of preserving the exit status is actually contained in `builtin_set` (see `preserve_failure_exit_status`).  Unfortunately it's hard to see how this can be fixed using the same trick: `builtin_set` doesn't know if the exit status came from a command substitution or the previous command.

**Comment by krader1961** [comment]
Yes, fixing this is going to be hard, probably really hard. That's why I didn't just assign myself and spend a few minutes creating a fix. Hopefully someone will someday feel motivated to tackle it.

**Comment by krader1961** [comment]
What is needed is a way to communicate that the previous exit status was the result of a subcommand executed in the context of the current (`set`) command. That is, `proc_get_last_status()` needs a flag that `builtin_set()` can set true to indicate it does not care about any status other than that of a subcommand in its context.

**Comment by nbCloud91** [comment]
That this is a complex bug and wouldn't be fixed anytime soon, this should me mentioned prominently in documentation. I was using activate.d/deactivate.d fish scripts for setting some environment variables of a conda-env, there are `if test xyz` conditionals preceding `set -gx var val` and getting non zero exit status was perplexing. This doesn't cause any breaking problems and I can always put a `true` before any set block, but being a newbie to fish, I wasted time trying to find the reason for bad exit status.

**Comment by faho** [comment]
Okay, I'm going to do something entirely different, and reject the enhancement.

This is because:

1. It *complicates* the rule - currently it is "`set` in set-mode doesn't change $status", after this it would be "`set` only sets $status to 0 if no command substitution was given" or something - and since setting a variable can't conceptually fail, it would indeed always set it to 0, so there's little information to be had there

2. It would absolutely break things. In particular with the introduction of $pipestatus, how would you get both of them from a command? Currently you can do `set oldstatus $status; set oldpipestatus $pipestatus`, with this you'd... `set tmp $status $pipestatus; set oldstatus $tmp[1]; set oldpipestatus $tmp[2..-1]`?

>this should me mentioned prominently in documentation

See [the documentation for set](https://fishshell.com/docs/current/cmds/set.html)

>In assignment mode, set does not modify the exit status. This allows simultaneous capture of the output and exit status of a subcommand, e.g. if set output (command). In query mode, the exit status is the number of variables that were not found. In erase mode, set exits with a zero exit status in case of success, with a non-zero exit status if the commandline was invalid, if the variable was write-protected or if the variable did not exist.

Could we word that better? Sure. But it exists in the same place where we tend to document exit status - at the end of the description. So it's absolutely possible to find.

**Comment by nbCloud91** [comment]
Point taken, I did fail to understand the documentation, apologies for coming across as impatient.
@faho I see the improvements in documentation you have made. I hope newer users are benefited from it.
