### ISSUE TITLE
backspace in vi mode is not working in urxvt and terminology

### ISSUE THREAD

**Issue by cycomanic** [fish-shell/fish-shell#3653]
- [ x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [ x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.4.0
**OS/terminal used**: 
terminology, urxvt and console

I've seen several bugs related to the related to recent changes but could not find anything like this. Since upgrading fish to 2.4.0 backspace is not working anymore in vi mode when using terminology urxvt or the linux console. When I press backspace in insert mode it does nothing (i.e. not a delete backward to the right, even if i call `bind -M insert -k backspace backward-delete-char` manually. Similarly in normal mode it does not cause a move to the left. Vi mode has therefore unfortunately become complete unusable.

**Comment by cycomanic** [comment]
just adding to this, it does work in xterm

**Comment by krader1961** [comment]
Please verify what sequence your backspace key sends by running `fish_key_reader`.

**Comment by cycomanic** [comment]
Output below
```
[I] jschrod@linux-q7s5 ~/.config> fish_key_reader
Press a key

              hex:    8  char: \cH  (or \b)
bind \b 'do something'
[I] jschrod@linux-q7s5 ~/.config>
```
I just realised that somehow my TERM variable is set to xterm-256color even in though I set it correctly in Xresources. If I set TERM to rxvt-unicode-256color backspace works again, I don't quite understand where the TERM change came from (especially because it's also incorrect in the console). I think this probably still should be fixed because backspace does work correctly in bash.

**Comment by krader1961** [comment]
The default key bindings do include `bind $argv \ch backward-delete-char`. It appears to be an oversight that the vi key bindings do not. So, yes, we should add that binding.

**Comment by krader1961** [comment]
Also, in case it wasn't clear the reason the $TERM value matters is that not every terminfo definition contains a `backspace` key definition, which we do bind in vi mode, and if they do it's not necessarily going to be `\cH`. But since [backspace] almost always transmits `\cH` we should bind that as well.

**Comment by TieDyedDevil** [comment]
There's a stunning lack of consistency among terminal emulators regarding the character sequences emitted for Backspace and Delete keys.

For example, the terminals for which the solution to this issue (#3653) provides correct behavior all send \x08 (backspace) for the Backspace key. But the Linux console, st and xterm (on my Fedora 25 system, at least) send \x7f (del) for the Backspace key. The good news is that this is the simple case; I haven't noticed that any terminals send something besides either backspace or del upon pressing the Backspace key.

The Delete key is more complicated. Some emulators apparently send del for Delete, but all of the emulators I've seen send an escape sequence. For example, st sends \e\[P while the Linux console and xterm both send \e\[3~ . My understanding (from reading about ANSI escape sequences) is that this sequence may change in response to certain mode commands sent to the terminal.

For terminals that have a proper terminfo database entry, `tput kbs`  and `tput kdch1` return the character sequences sent for the Backspace and Delete keys, respectively. Querying the sequences may be a viable approach to normalizing behavior across terminals. Of course, given that some terminals may not support these queries, there may be a need for a fallback strategy.

Just a thought...

**Comment by manzur** [comment]
@krader1961 , looks like your commit(745bceb) breaks `ESC` key for `mate-terminal`(others as well, see comment above), which sends `\7f` as `ESC`. So with your commit `ESC` works as like normal `DELETE` press. So you would want to change only `\cH`, and not `\7f` in that commit.

**Comment by faho** [comment]
>For terminals that have a proper terminfo database entry, tput kbs and tput kdch1 return the character sequences sent for the Backspace and Delete keys, respectively.

Terminfo is almost worthless here, given that most terminals nowadays set TERM=xterm. I know mate-terminal does.

@manzur: That's weird, since \x7f was actually bound before. So it probably never really worked properly. Installing mate-terminal now to test.

**Comment by faho** [comment]
Okay, I installed mate-terminal, and it does _not_ send \x7f for escape.

It sends `\e` (i.e .\x1b) for escape, \x7f for backspace and \e[3~ for delete.

This is with mate-terminal 1.16.1 on archlinux, using gtk3 and vte 0.46.1.

**Comment by manzur** [comment]
@faho , not my day, I was thinking about `backspace`, but wrote `ESC`. Which means, you can't use `backspace` anymore to remove backwards.

**Comment by joehillen** [comment]
gnome-terminal sends `\x7f` for `backspace` as well

gnome-terminal gives this for the `Delete` key

```
fish_key_reader 
999999 usec  dec:  27  hex: 1b  char: \e (aka \c[)
   530 usec  dec:  91  hex: 5b  char: [
   479 usec  dec:  51  hex: 33  char: 3
   451 usec  dec: 126  hex: 7e  char: ~
FYI: Saw sequence for bind key name "dc"
```

**Comment by faho** [comment]
@krader1961: I have now reverted that part of the change, because it seems wrong on at least some terminals and is inconsistent with the default bindings.

Ideally we'd remove the need for explicitly binding \x7f (since we already have `bind -k backspace` and `bind -k dc`), but that needs some more work.

Even if we can't do that, anything done about this needs more testing, on multiple terminals (my konsole does the same thing as the mate and gnome terminals), and its own issue.

**Comment by krader1961** [comment]
You beat me to it. Yes, your change is more correct than mine with respect to [delete] key. This whole discussion made me realize we should introduce some sort of bind priority so that binding to a named key takes precedence over binding to the terminfo sequence for that key. That is, if terminfo defines `key_backspace` to send `\cH` and our bindings have both `bind -k backspace do-something` and `bind \cH do-something` then the latter should be ignored; possibly with a warning issued if the action was not identical.

**Comment by krader1961** [comment]
Also, the fact the [backspace] key in some terminals sends \x7F (aka \c?) rather than \x08 (aka \cH) dates back at least thirty years and reflects the fact that some people interpreted the ASCII standard to mean that \cH should be a non-destructive move left one char and \c? should be a destructive move left. Whereas others interpreted it to mean \cH should delete the char to the left and \c? should delete the char to the right of the cursor. This [article](http://www.columbia.edu/kermit/backspace.html) has a lot of detail.

As I indicated above we should give serious thought to a better mechanism for using the terminfo symbol names if defined and only using fallback literal sequences if the symbolic name isn't defined.
