### ISSUE TITLE
Error showing when using git autocomplete outside of git repository

### ISSUE THREAD

**Issue by Hunsu** [fish-shell/fish-shell#3659]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?
It doesn't reproduce but it shows HEAD, MERGE_HEAD and ORIG_HEAD that are invalid.

**fish version installed** *(`fish --version`)*:
2.4.0-243-g9870cf8
**OS/terminal used**: 
Ubuntu 16.04, Gnome Terminal
Talk about the the issue here. 
When doing `git checkout m[TAB] ` in non git repository, there's the output `fatal: Not a git repository (or any of the parent directories): .git`. Normally the error output should be redirected to /dev/null and show no auto-complete suggestions.  I can try to fix this if you point me where should I look.
## Reproduction steps
1. cd to a non git repository
2 git checkout m[TAB]

## Results
fatal: Not a git repository (or any of the parent directories): .git

**Comment by faho** [comment]
This should be fixed in 410d92ed6108e881ef40c88dbbf68c274f833d32, and it seems to work for me. 

Can you check that the first "git.fish" in your $fish_complete_path is from upstream fish and redirects stderr to /dev/null for every `command git` call? Most likely you have a stray completion script from somewhere.

**Comment by Hunsu** [comment]
Sorry for the trouble, I found another `git.fish`in my conifg folder.
