### ISSUE TITLE
Fish not reading /etc/profile in TTY

### ISSUE THREAD

**Issue by marmistrz** [fish-shell/fish-shell#3665]
**fish version installed**: 2.4.0
**OS/terminal used**: Arch Linux, TTY

Fish doesn't seem to source the environmental variables from /etc/profile when in TTY. For example `PATH`:
```
/etc/profile:PATH="/usr/local/sbin:/usr/local/bin:/usr/bin"
```
It sources them when run in a terminal emulator in the Cinnamon desktop environment

## Reproduction steps
1. Make sure PATH is changed in `/etc/profile`
2. Login on the TTY

## Results
in TTY
```console
~ $ echo $PATH
/usr/bin
```
in DE
```
/usr/local/sbin /usr/local/bin /usr/bin /opt/android-sdk/platform-tools /opt/android-sdk/tools /usr/lib/icecat /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
```

**Comment by krader1961** [comment]
Fish is not a POSIX 1003.1 compatible shell. It does not read */etc/profile*. This should probably be added to the FAQ. On Linux you should put changes to the global PATH in */etc/environment* or */etc/login.defs*.

**Comment by marmistrz** [comment]
But why is that read in DE?

**Comment by krader1961** [comment]
Most likely because starting the DE is done via a bash script which reads /etc/profile. The exported PATH is inherited by the DE which in turn passes it to the terminal program which in turn passes it to the shell run within the terminal.

**Comment by krader1961** [comment]
Also, it's not entirely clear what you mean by "TTY". I'm guessing you mean either logging in at the console VT (virtual terminal) or via SSH.

**Comment by marmistrz** [comment]
I mean the virtual terminal (ctrl+alt+f2)

Marcin

**Comment by ridiculousfish** [comment]
fish cannot read /etc/profile because it's not valid fish syntax. I think krader has the right explanation for why it seems to work in Cinnamon.  The simplest workaround is to just set the path yourself, by running (once):

    set -U fish_user_paths /usr/local/sbin /usr/local/bin /usr/bin

Thanks for filing this!

**Comment by marmistrz** [comment]
Hmmm... that's not a fix. Multiple applications added their scripts to profile.d:
```
android-sdk.csh*                 android-sdk.sh*  freetype2.sh  icecat.sh*  libreoffice-fresh.csh*  mercurial.sh*        perlbin.csh*
android-sdk-platform-tools.csh*  apache-ant.csh*  gpm.sh*       jre.csh     libreoffice-fresh.sh*   mozilla-common.csh*  perlbin.sh*
android-sdk-platform-tools.sh*   apache-ant.sh*   gradle.sh*    jre.sh      locale.sh*              mozilla-common.sh*   vte.sh
```

**Comment by marmistrz** [comment]
It seems even more grave, when you look at the `jre.sh`:
```
> cat /etc/profile.d/jre.sh 
# Do not change this unless you want to completely by-pass Arch Linux' way
# of handling Java versions and vendors. Instead, please use script `archlinux-java`
export PATH=${PATH}:/usr/lib/jvm/default/bin
```

**Comment by zanchey** [comment]
In this situation, I tend to leave my login shell as bash/zsh/whatever, but at the end put `[ -x /usr/bin/fish ] && exec fish` or similar.

**Comment by marmistrz** [comment]
Not a good idea to put it into `bashrc` because sometimes you need to access the real Bash shell. (e.g. some guide are written explicitly for Bash, it's easier to use Bash than to change every difference)

**Comment by faho** [comment]
There's a few possibilities to work around this, none of them great.

- You can do as @zanchey suggested and trampoline to fish from a login bash - in which case you can still run bash manually, because it won't be a login shell.

- You can run [bass](https://github.com/edc/bass)

- You can translate these sh-scripts to fish by hand - not too tricky to do since they tend to be very simple, though annoying if there are any changes.

This might be figured out via freedesktop.org and gnome, since they currently don't use a shell in the wayland startup path (and don't really want to). See https://bugzilla.gnome.org/show_bug.cgi?id=736660.

There already is a /etc/environment _file_ read via the "pam_env" module, but that kinda clashes with package management. All that is really needed there is a "/etc/environment.d/" _directory_ that can use these kinds of snippets, and then it'll be set no matter how you login. Well, that and some way to append and prepend.

**Comment by vizv** [comment]
@zanchey Reply https://github.com/fish-shell/fish-shell/issues/3665#issuecomment-268527236 :

> In this situation, I tend to leave my login shell as bash/zsh/whatever, but at the end put `[ -x /usr/bin/fish ] && exec fish` or similar.

This breaks `scp` and `sftp`, change to `[ "$PS1" -a -x /bin/fish ] && exec fish` to make it only applies to interactive shells.

**Comment by gyakovlev** [comment]
@vizv Seems you came here from getnoo wiki and edited the article as well.
default gentoo bashrc contains this:  

    if [[ $- != *i* ]] ; then
            # Shell is non-interactive.  Be done now!
            return
    fi

and also warns about breaking scp just above this code snippet.
check you /etc/skel/.bashrc for original version of the file.
it's better way of testing for interactive prompt. 
if you put your stuff (including launching fish) after those lines scp/sftp works just fine.

**Comment by vizv** [comment]
@gyakovlev Thanks for pointing this out.

In fact I didn't test it in my Gentoo. I have problem `scp` a file to my CentOS 7 machine that day, and I found it is caused by the bash safety net suggested in Gentoo Wiki.

I assume Gentoo would have the same issue so I edited the Gentoo Wiki, but apparently I was wrong for Gentoo.

**Comment by sullyj3** [comment]
Does this mean that there's no way to set my PATH in a shell independent way that fish will pay attention to?

**Comment by faho** [comment]
@sullyj3 Not by modifying /etc/profile, no. What else you can do depends on your system and what exactly you want to do.

E.g. on macOS you can use /etc/paths (and /etc/paths.d). On linux you can typically use /etc/environment or ~/.pam_env, which are actual declarative files that are more suited for the purpose of just setting environment variables.

----

In future, please open a new issue or come to https://gitter.im/fish-shell/fish-shell instead of commenting on random old issues.

**Comment by soredake** [comment]
@faho support for `~/.pam_environment` is removed https://github.com/linux-pam/linux-pam/blob/62d826471e87e27b39a36ccbeee58999e2514a92/NEWS#L29

**Comment by kidonng** [comment]
@soredake The behavior is easily revertable by setting `user_readenv=1` in pam_env config. For example Arch [added this config by default](https://github.com/archlinux/svntogit-packages/commit/2d5af94ae55a5c98837ce9631f331ad2aad32bb3#diff-87ca5e31e2024847284d656fb84d46fbfdaf9c93e73c6b17c5011afdcb341cbdR19).

**Comment by Edu4rdSHL** [comment]
For anyone else coming here, I ended up with this solution as the best overall:

Bash as user shell, taking care of `/etc/profile{.d}` and this `.bashrc`

```
#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

[[ "$SHELL" != */fish ]] && [ -x /usr/bin/fish ] && \
  SHELL=/usr/bin/fish exec fish
```

With the `$SHELL` condition, you can run `bash` from Fish without needing `--rcfile` to drop-in.

**Comment by ericjs** [comment]
Using bass was listed as one possible solution (all of which were said to be "not great"). What's the downside of that solution?
