### ISSUE TITLE
Right prompt shift

### ISSUE THREAD

**Issue by FliiFe** [fish-shell/fish-shell#3673]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: `fish, version 2.4.0`

**OS/terminal used**: URxvt

The right prompt is shifted by exactly one cell/character.

In zsh, this issue is solved using
`ZLE_RPROMPT_INDENT=0`

Is there any flag for fish ?

## Reproduction steps

Add a right prompt

## Result

![Shift](https://i.imgur.com/GAvRQvZ.png)

Here, `3%` is tmux, and `INSERT` is my Right prompt.

**Comment by ridiculousfish** [comment]
Can't repro with Apple Terminal or iTerm2. Can you share your fish_right_prompt? (`functions fish_right_prompt`)

**Comment by krader1961** [comment]
We try really hard to avoid the need for configuration options. We do not want to become like zsh where it is impossible to predict how the shell will behavior. Fish is supposed to put the right prompt flush with the right edge of the terminal. If it isn't doing so something is wrong.

In addition to showing us your `fish_right_prompt` definition it would be good to know if the problem happens outside of tmux. Since you mentioned you're using urxvt you probably won't be interested in trying either of the most popular macOS terminal emulators. But could you try running fish in another terminal such as Konsole or a plain xterm to help determine if the behavior is due to some quirk of urxvt?

**Comment by FliiFe** [comment]
Well, actually, `fish_right_prompt` is quite relevant (I think).
```fish
function fish_right_prompt
	env $POWERLINE_COMMAND  shell right --last-exit-code=$status --last-pipe-status=$status --jobnum=(jobs -p | wc -l) --renderer-arg=client_id=6010 --width=$_POWERLINE_COLUMNS --renderer-arg=mode=$fish_bind_mode --renderer-arg=default_mode=$_POWERLINE_DEFAULT_MODE
	echo -n " "
end
```

Oh, and also, it behaves exactly the same with xterm, gnome-terminal and terminator, with or without tmux, but it seems obvious given the line
```fish
echo -n " "
```

Is this powerline-related, or fish-related ?

**Comment by FliiFe** [comment]
It seems in their source code that powerline does that
```fish
function fish_right_prompt
	env \$POWERLINE_COMMAND $POWERLINE_COMMAND_ARGS shell right $addargs
	$rpromptpast
end
```

Il try to unset the right prompt prior to loading powerline

**Comment by FliiFe** [comment]
I fixed it using 
`set -gx POWERLINE_NON_FISH_ABOVE "-"`
Inside `$OMF_CONFIG/before.init.fish`
