### ISSUE TITLE
Wrong completions for nmcli

### ISSUE THREAD

**Issue by Kishore96in** [fish-shell/fish-shell#3674]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: Arch linux, konsole
**Networkmanager version**: 1.4.4

## Reproduction steps
1. Type `nmcli con` and press tab.
2. Compare suggested results with the results suggested in `nmcli con --help`.
3. The output of step 1 contains commands which do not work (eg. `nmcli con status`), and is also missing a few of the commands listed in the output of step 2.

## Results
```console
~ $ nmcli con #press tab here
delete  down  list  status  up
~ $ nmcli con status
Error: argument 'status' not understood. Try passing --help instead.
~ $ nmcli con --help
Usage: nmcli connection { COMMAND | help }

COMMAND := { show | up | down | add | modify | clone | edit | delete | monitor | reload | load | import | export }

  show [--active] [--order <order spec>]
  show [--active] [id | uuid | path | apath] <ID> ...

  up [[id | uuid | path] <ID>] [ifname <ifname>] [ap <BSSID>] [passwd-file <file with passwords>]

  down [id | uuid | path | apath] <ID> ...

  add COMMON_OPTIONS TYPE_SPECIFIC_OPTIONS SLAVE_OPTIONS IP_OPTIONS [-- ([+|-]<setting>.<property> <value>)+]

  modify [--temporary] [id | uuid | path] <ID> ([+|-]<setting>.<property> <value>)+

  clone [--temporary] [id | uuid | path ] <ID> <new name>

  edit [id | uuid | path] <ID>
  edit [type <new_con_type>] [con-name <new_con_name>]

  delete [id | uuid | path] <ID>

  monitor [id | uuid | path] <ID> ...

  reload

  load <filename> [ <filename>... ]

  import [--temporary] type <type> file <file to import>

  export [id | uuid | path] <ID> [<output file>]
~ $
```

**Comment by ridiculousfish** [comment]
Related #3648

**Comment by faho** [comment]
We've had a bit of an update to the nmcli completions after 2.4.0 (see #3648), so they'll behave quite a bit better, provided you use the _long_ form of the command (e.g. "connection", not "con", though that's also completed).

They should probably get support for the short forms since I suspect that's the more common form.

**Comment by krader1961** [comment]
Thank you, @Kishore96in, for bringing this to our attention. Unfortunately unless someone who uses the command actually writes the required completion script code it will never be implemented. We are happy to answer questions and provide guidance about implementing a better completion script for `nmcli`. However, I'm going to close this because unless someone like yourself actually does that work it will never be done. Feel free to reopen this issue if you, or anyone else, is interested in making the required changes and needs advice.
