### ISSUE TITLE
++options

### ISSUE THREAD

**Issue by maandree** [fish-shell/fish-shell#368]
It would be nice if completion scripts could complete ++options, instead of just --options.
And naturally also short variants.

Preferable, it should be possible to just any character instead of a hyphen and any
number of them instead of one for short and two for long.

**Comment by maxnordlund** [comment]
Another example of this is `ghc` compiled binaries having `+RTS <ghc options go here> -RTS`, and the `dig` DNS tool.

**Comment by floam** [comment]
+ options are not very uncommon, typically to toggle something *the other way* - `++option` I've never seen!

**Comment by krader1961** [comment]
I too have never seen `++option`. Looking at the [ponysay source](https://github.com/erkin/ponysay/blob/master/src/argparser.py) we can see that it has a custom, idiosyncratic, option parser. I don't think we should bother supporting that. The `dig` command is also unusual in that its `+` options are not command flags in the usual sense; they're query options that modify the DNS lookup. Still, it would be nice if that case could be handled more cleanly. Too, as @floam noted, there are commands which use  `+option` prefix to mean the  opposite of `-option` rather than have the user write `-nooption`.

The question is whether anyone cares enough to implement support for `+` in addition to `-`. This issue is four years old which suggests the answer is no.

**Comment by krader1961** [comment]
Sorry, but I'm going to close this request. The use of `+` to introduce a flag is sufficiently unusual that we can't justify the work to support it. And `++` is even more unusual and thus even harder to justify supporting it.
