### ISSUE TITLE
bind: combining user functions with special input functions does nothing

### ISSUE THREAD

**Issue by daleeidd** [fish-shell/fish-shell#3683]
Binding user defined functions with special input functions does nothing.

- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
`fish, version 2.4.0`

**OS/terminal used**: 

macOS 10.12.*
iTerm2 3.*

## Reproduction steps

Test function:
```
function test_backward_word
  commandline -f backward-word
end
```

Works:
```
function fish_user_key_bindings
  bind \cr backward-word backward-word
end
```
Works:
```
function fish_user_key_bindings
  bind \cr test_backward_word test_backward_word
end
```
Does nothing:
```
function fish_user_key_bindings
  bind \cr backward-word test_backward_word
end
```

**Comment by krader1961** [comment]
That's expected, albeit surprising and unintuitive behavior. Try

```
bind \cr 'commandline -f backward-word; test_backward_word'
```

The current implementation has too much magic, IMHO, in an attempt to make it unnecessary to use `commandline -f` when the command(s) is/are a `commandline` builtin function rather than an arbitrary function name or fish script. Since bind also allows arbitrary function names and even fish scripts not hidden inside a fish function this creates the ambiguous situation you found.

The question is what, if anything, we can do to improve the situation without breaking backward compatibility.

**Comment by daleeidd** [comment]
Thank you. That worked.

I have only just started using fish so I don't know the ins and outs. Adding this to the documentation for novices (unless it is already in there) will be a decent temporary solution.

**Comment by faho** [comment]
>The question is what, if anything, we can do to improve the situation without breaking backward compatibility.

What exactly is happening in that failing case? If there is no situation where this bind could work (e.g. only if "backward-word" and "test_backward_word" exist as fishscript functions), we could just print an error - it's already non-functional contrary to user expectations, so we should notify the user. That wouldn't really be incompatible, since nothing that previously worked would stop working.

Of course we could also try to resolve this to something that works, but then the question is how to do it in an intuitive manner - as @krader1961 has pointed out, this stuff is already too clever. 

Maybe try, for each call in the  binding, to resolve it as a fishscript function first, then as a bind function if that doesn't exist? So like the situation with functions, builtins and commands? If you want to make something always use the bind function, use `commandline -f`, like you'd use `command`.

**Comment by krader1961** [comment]
See `input_mapping_execute()` in *src/input.cpp*. Specifically the sequence of "if" conditions. The mixture of bind functions and commands is handled by this block of code:

```
    } else {
        // Invalid binding, mixed commands and functions.  We would need to execute these one by
        // one.
        input_common_next_ch(R_NULL);
    }
```

Someone will need to investigate the history of this code to figure out why that's illegal but if I had to guess it's because such combinations are ambiguous except in trivial cases such as the one in the problem statement of this issue.

**Comment by krader1961** [comment]
While I haven't looked at the history of the key binding code I suspect it started out only supporting the "special input functions" as they are described in the `man bind` documentation. Then someone realized it would be useful to allow arbitrary fish code, including regular function names (i.e., those not recognized as special by the `commandline -f` logic). Which resulted in the current logic for avoiding tragic misunderstandings when mixing the two types of functions.

It's not clear we can easily improve this behavior. How would you deal with something like

```
function test_backward_word
  do_something $argv
end

bind \cr test_backward_word arg1 arg2 backward-word
```

Yes, that is a silly example but would be completely legal if we allowed mixing "special input functions" with arbitrary fish script in bind actions.

**Comment by krader1961** [comment]
Regardless of whether we change the implementation the documentation should be improved.

**Comment by krader1961** [comment]
Since I don't think we want to, or can, change the existing behavior I've merged (with some word smithing) the change by @e-beach to improve the documentation.
