### ISSUE TITLE
AUR Autosuggestion

### ISSUE THREAD

**Issue by Hacksaurus** [fish-shell/fish-shell#3687]
I know I shouldn't be making another issue that was already touched, but I am pretty confused about it...

I am using Arch Linux and I noticed that autosuggestion for AUR packages does not really work when using pacaur. And all I want is that fish to be able to autosuggest packages like how it does for pacman!
Thanks for any help!

(Another question, how does autosuggestion work for packages anyways?)

**Comment by krader1961** [comment]
> how does autosuggestion work for packages anyways?

Via completions. See, for example, *share/completions/pacman.fish* and *share/completions/pacaur.fish* in the project source tree. On most systems those will be installed on */usr/local/share/fish/completions*.

I don't use Arch Linux but a quick review of the two command completions suggests they should be substantially the same.

You didn't mention the version of fish or Arch Linux you are using. That type of information should always be included when opening an issue. Completions for `pacaur` were added on 2016-04-15 and were clearly modeled on those for `pacman`. They would have first appeared in the fish 2.3.0 release.

**Comment by Hacksaurus** [comment]
Oh sorry, I am using fish 2.4.0... And I am thinking that you are talking about this:
![screenshot_2016-12-29_15-22-01](https://cloud.githubusercontent.com/assets/24832107/21556980/ac82c930-cdda-11e6-9859-36235da850f4.png)

Yes the autosuggestion is there for the "-" things, but what I'm talking about is **package** autosuggestions... Now if you see here when I try to install a package and I now it has "lol" in it and I double press tab it will give me this:
![screenshot_2016-12-29_15-26-00](https://cloud.githubusercontent.com/assets/24832107/21557020/48700bc8-cddb-11e6-91df-1e668e331d1c.png)

This is **super** helpful especially when I don't want to search the package in the first place. Now `pacaur` has its packages up there in the web and doesn't have a "cache" of all its packages that it has, like `pacman`. So when I try to autosuggest it give me nothing... 

I hope this clarifys...

**Comment by Hacksaurus** [comment]
I know I shouldn't be double positing, but @krader1961 have I stated enough information? Or do I need to edit my first comment...

**Comment by Hacksaurus** [comment]
So my main question is that, how does fish get the package names for pacman... Does fish find that file where it has that local source of packages, or does it have its own little "cache"... 

Because a solution could be made where each time you used pacaur it does its installation stuff, it also makes a file where it makes a local source of file names, just like a normal package manager does.

**Comment by faho** [comment]
>So my main question is that, how does fish get the package names for pacman... Does fish find that file where it has that local source of packages, or does it have its own little "cache"...

It's a bit convoluted since we have a helper function that defers to whatever package manager you have installed (since it might also be used for other completions). It's called `__fish_print_packages`, and here's what it does for pacman:

```fish
        set cache_file $XDG_CACHE_HOME/.pac-cache.$USER
        if test -f $cache_file
            cat $cache_file
            set age (math (date +%s) - (stat -c '%Y' $cache_file))
            set max_age 250
            if test $age -lt $max_age
                return
            end
        end

        # prints: <package name>	Package
        pacman -Ssq | sed -e 's/$/\t'$package'/' >$cache_file &
        return
```

So that still makes a cache file with the contents of `pacman -Ssq`. I'm unsure if the cache actually helps anything (pacman is usually plenty fast) and if it wouldn't be even faster to `zgrep` the databases ourselves (the format is really simple). Also the `sed` could probably be removed. I think I need to touch this stuff again.

Anyway, the important thing here is that pacman hands us that data (either via an invocation of it, or by storing it somewhere), and no AUR helper does that for AUR packages.

>Because a solution could be made where each time you used pacaur it does its installation stuff

Sorry, no.

That would mean two things:

- It would require us wrapping `pacaur` (and any competing AUR helper - that would mean about 10 or so implementations) with a function, which has other issues - both bugs on fish's end (we currently buffer all function output, so this might be a bit slower) and on the interaction side - should pacaur still print colors or should we strip them off?

- It would mean keeping track of a rather complicated cache, since the output of any one `pacaur` invocation is very likely to be rather incomplete - you're never printing _all_ aur packages, you're searching for specific terms - so we'd need to figure out a way to not duplicate packages we already know about, while ideally keeping the descriptions intact (unless they changed), while also invalidating entries for removed packages (otherwise this file would become huge). Either that or only keep data on the last ~3 invocations, which is likely to be very frustratingly incomplete - this would be something that feels like "magic", since it's not easily understandable when something is going to be in the completions or not

**Comment by Hacksaurus** [comment]
Oh I see... But zsh has the ability to do AUR searches?...

**Comment by faho** [comment]
Dunno how they do it, I might need to look that up. Do they do it for pacaur completions?

**Comment by faho** [comment]
These completions are shipped with pacaur directly, not zsh.

They [always search remotely](https://github.com/rmarquis/pacaur/blob/master/zsh.completion#L350-L355) if a certain configuration knob (this is still zsh, remember) has been set.  And it has just the annoyance I lamented - it takes ages (on my current bad connection), though at least it's killable. Since it's not even cached it takes ages _again and again_ - even pressing TAB again after it just completed something seems to re-search.

(Though the invalidation policy for the binary package cache is interesting - they throw out the cache if any of the sync databases (i.e. the database files for pacman's binary repositories) is newer.)

**Comment by Hacksaurus** [comment]
Ohhhhh... Hmm.... Well, I guess I'll just use the aur.archlinux.org site... 
Closing this thread.
Thanks for the help though!
