### ISSUE TITLE
Variadic options

### ISSUE THREAD

**Issue by maandree** [fish-shell/fish-shell#369]
A variadic option as an option which takes all other following command line arguments as its arguments.

An example is --f (which is a short option --files and --ponies are the long options) in ponysay 2.9:
When executing `ponysay --f pinkie rainbow -f` both `pinkie` and `rainbow`, and also `-f`, belongs
to the option `--f`.

Support this is auto-completion would be nice.

**Comment by anordal** [comment]
Python has an option parser that supports variadic options. To demonstrate how it understands arguments, here is a demo:

```python
#!/usr/bin/env python3
import argparse

opts = argparse.ArgumentParser()
opts.add_argument('--flag', action='store_true')
opts.add_argument('--zero-or-one', nargs='?')
opts.add_argument('--exactly-one', nargs=1)
opts.add_argument('--exactly-two', nargs=2)
opts.add_argument('--one-or-more', nargs='+', default=[])
opts.add_argument('--any', nargs='*', default=[])
args = opts.parse_args()
print(args.flag)
print(args.zero_or_one)
print(args.exactly_one)
print(args.exactly_two)
print(args.one_or_more)
print(args.any)
```

> also `-f` belongs to the option `--f`

This detail may be true of ponysay, but argparse disagrees.

**Comment by ridiculousfish** [comment]
The original request is basically the same as `--`: all further arguments are positionals instead of options.

**Comment by anordal** [comment]
… which is what I doubt is very standard, considering that that python framework assumes the opposite convention.

**Comment by krader1961** [comment]
I'm closing this because a) it is five years old, and b) "ponysay" is weird and nonstandard in how it handles flags and their associated arguments. Also, while @anordal's example shows how to handle options which require a finite or infinite number of arguments in Python it is not obvious we need to support that in fish command completions. Command completions are meant to help with 99% of the typical cases. This is in the 0.01% of cases (i.e., less than 1 in 10000).
