### ISSUE TITLE
make cd use pushd

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#3697]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: macOS 10.12.2, iTerm 3.0.13

zsh has a option where cd by default always pushes onto the directory stack. I find this very useful. I cannot alias pushd to cd in fish because pushd uses cd so it becomes recursive.

**Comment by krader1961** [comment]
Fish ships with `cd` as a function which does what you're requesting. It's how `cd -` is implemented; i.e., by using the same directory stack that pushd/prevd manipulate. Perhaps we need more detail about the sequence of commands you're typing, the result you're seeing, and the result you expect.

**Comment by faho** [comment]
What you can do is actually rather simple - `funced cd` to add `set -g dirstack (pwd) $dirstack`.

I'm unsure if we should do this by default (and it surely should not be an _option_ since it is that easy to implement yourself), and there's a bunch of subtlety in this area I'm not quite sure of.

**Comment by nhooyr** [comment]
@krader1961 I cd into a directory, but popd says directory stack is empty.

**Comment by nhooyr** [comment]
oh, i need to use `prevd` and `nextd`.

**Comment by krader1961** [comment]
Ahh, yes, pushd/popd don't really work well with the stack that fish's cd/prevd/nextd commands use. As faho said it might be possible to do better but since I consider pushd/popd essentially unusable I've never bothered to investigate how they interact with the other fish directory manipulation functions. You might also be interested in the `mcd` command (menu cd), issue #2487, that I wrote and use as a saner alternative to prevd/nextd and pushd/popd.

**Comment by nhooyr** [comment]
You meant #2847?

**Comment by krader1961** [comment]
> You meant #2847?

Yes.
