### ISSUE TITLE
highlighting glitch when pressing up on a suggestion 

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#3698]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: macOS 10.12.2 iTerm 3.0.13

Watch https://youtu.be/w1Wp_VdKII0

Interestingly enough, asciinema didn't pick up on it as you can see here https://asciinema.org/a/56ecz442pc083ql3t2frhudmh

**Comment by faho** [comment]
This actually looks like it's working as intended - you're searching through history, so we mark what we are using as the search string.

>Interestingly enough, asciinema didn't pick up on it

That might actually be a bug in asciinema, specifically their player. Due to the way it works, it just captures fish's output, including all special sequences (like color). As you can see in the json file, there's

```
"\b\b\b\b\b\u001b[1m\u001b[100mecho \u001b(B\u001b[m\u001b[30m\u001b[30m\u001b(B\u001b[m'hoo'\u001b[K"
```

That `\u001b` is a `\e`, so that is `\e[100mecho` - try `echo \e\[100mecho`, it should print something that looks just like your highlighted search string.

**Comment by nhooyr** [comment]
Oh alright then.

**Comment by nhooyr** [comment]
@sickill shall I close my issue on asciinema then?

**Comment by faho** [comment]
@nhooyr: Already closed.

@sickill: Thanks for the quick reaction!

**Comment by sickill** [comment]
Btw, thanks to all great fish developers and contributors! Fish is awesome 🙇
