### ISSUE TITLE
fish_vi_key_bindings doesn't call fish_user_key_bindings

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#3699]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: macOS 10.12.2 iTerm 3.0.13

fish_vi_key_bindings doesn't call fish_user_key_bindings at the end so reloading my config.fish causes my keybindings to disappear. I can manually call `fish_user_key_bindings` in my config.fish but it'd be cool if it was automatic.

**Comment by faho** [comment]
That's not how this works.

It's a bunch more complicated than that.

Calling `fish_vi_key_bindings` without  having $fish_key_bindings set to fish_vi_key_bindings should just set it.

Setting $fish_key_bindings to something should call that function and then fish_user_key_bindings.

(Yes, this is overly complicated - there are a bunch of really weird edge-cases we need to support here)

So I'm a bit confused that this is happening.

Can you post the output of `for file in $fish_function_path/fish_vi_key_bindings.fish; if test -e $file; md5sum $file; break; end; end`? That gets us the md5sum so we can confirm you're really using the 2.4.0 copy.

**Comment by nhooyr** [comment]
I mean sourcing my config.fish after having already started fish. Then it doesn't work. That would mean it is expected because `fish_vi_key_bindings without having $fish_key_bindings set to fish_vi_key_bindings should just set it.`, but I have `$fish_key_bindings` because fish is running.

**Comment by krader1961** [comment]
Okay, that explains it. @faho, I really think this mechanism needs to be changed. The problem here is that the `fish_*_key_bindings` functions only trigger the C++ code to re-execute the function plus `fish_user_key_bindings` if the `$fish_key_bindings` changes. In this case it is already set to `fish_vi_key_bindings` so the function simply instantiates the vi key bindings. We had problems due to this overly convoluted mechanism when we refactored the code a few months ago and required the user to explicitly ask for hybrid bindings if they wanted both emacs and vi bindings at the same time. This is just another symptom of the same underlying problem. The interaction with `__fish_reload_key_bindings` (defined in *share/functions/__fish_config_interactive.fish*) is hard to understand and leads to problems like this one.

**Comment by krader1961** [comment]
See also issue #3590 which is a closely related bug due to the indirect/recursive structure of this code. Fixing either issue will likely fix the other.

**Comment by faho** [comment]
Okay, so here's why we currently "need" the redirection:

To support both `fish_vi_key_bindings` and `set -g fish_key_bindings fish_vi_key_bindings`. If we did just one of the two, we could remove all that. And going by [a github search for "fish_vi_key_bindings"](https://github.com/search?q=fish_vi_key_bindings&type=Code&utf8=%E2%9C%93), it seems like the function-style is vastly more prevalent than the variable one.

Note that this is for people who put their config in git, which means they are less likely to `set -U fish_key_bindings` - in which case it wouldn't show up.

Okay, so let's say we switch to only supporting function-style. That means:

- The variable is still set, for other functions that need to see whether you are in vi-mode

- Binding functions need to call `fish_user_key_bindings` on their own

- The event ping-pong stops

- Most of the code to execute a binding function on startup remains

We could also print an error if someone tries to use the variable-style, but that requires a bit of a hack (an additional variable that is set in the function, and a variable listener for fish_key_bindings that checks if that variable is unset).

Needless to say, this is for after 2.5.0.

**Comment by krader1961** [comment]
Agreed. This has been slightly broken for quite a while. We should not rush a fix for the 2.5.0 release.

The problem with removing supporting for setting the mode by assigning to `fish_key_bindings` is that it breaks the useful behavior that if you leave that a uvar and change the bindings (using either style for doing so) it automatically changes the bindings in your other fish instances on that system. I think we definitely want to keep the current behavior that changing the bindings in one shell affects all the others. That does not mean we have to continue supporting `set -g fish_key_bindings fish_vi_key_bindings` as synonymous with just running the `fish_vi_key_bindings` function.

What if we made `fish_key_bindings` a list of binding functions to be run in sequence with `fish_user_key_bindings` always implicitly the last one in the list? Something along those lines would make it much easier to mix and match different functions that performed `bind` ops. That might make it easier and safer for third-party packages to modify bindings without editing the user's `fish_user_key_bindings` function. It would certainly make it simpler to use just the default/emacs, vi, or both major bindings. Then refactor the `fish_*_key_bindings` functions so that they only set that uvar to trigger actually changing the bindings. To be determined is how to name the "major" mode. Would it just be the last function in the list? That would mimic what we do now. Or would we want to explicitly set it as the first element of the list or perhaps have a different var that contains the name of the "major" mode?

**Comment by krader1961** [comment]
See also issue #3032 which discusses adding a means for third-party plugins and distro vendors to add bindings layered somewhere between the fish default/vi bindings and whatever the user has done in the `fish_user_key_bindings` function.

**Comment by krader1961** [comment]
I've removed this from the 2.6.0 milestone since there is no compelling reason to predicate that release on fixing this issue. Also, we are already a few days past the target date for a 2.6.0 release and there are several other higher priority unresolved issues targeted for that release.
