### ISSUE TITLE
Performance problem with `read` and fish processes not dying

### ISSUE THREAD

**Issue by samdmarshall** [fish-shell/fish-shell#3729]
**fish version installed** *(`fish --version`)*: `fish, version 2.4.0`

**OS/terminal used**: 
```
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67
```

**Issue**:
So I have a function that allows me to tunnel all my traffic through `tor`, and this function uses `read` to give the function something to block on until I want to shut down the tunnel (akin to behavior of activating an ssh tunnel but without having a second host to connect to). I ran this function and it became clear to me that this this wasn't going to let me connect out (network not vending me an IP address), I closed the terminal tab this was running in. Few minutes later I notice my shell lagging a lot, after diving into activity monitor, I notice an additional `fish` process that I couldn't account for that was chewing through a lot of CPU. I think that this is related to #3712 and #3691, i've attached the process sample below.

[Sample of fish.txt](https://github.com/fish-shell/fish-shell/files/703259/Sample.of.fish.txt)

**Comment by krader1961** [comment]
Actually, it looks to me like your function is expanding a wildcard and that has gone hay wire. Please show us your function.

**Comment by samdmarshall** [comment]
Here is the function in question, I didn't realize at the time but there was a typo in the function's code that may have caused `scutil` to not exit properly when first invoked (not sure if that has anything to do with this).

https://github.com/samdmarshall/dotfiles/blob/master/fish/functions/autotor.fish#L10

**Comment by krader1961** [comment]
Line 12 is wrong:

```
trap (command sudo networksetup -setsocksfirewallproxystate "$service_name" off; and command sed -i -e 's=^    ProxyCommand=#   ProxyCommand=' ~/.ssh/config) INT
```

The command substitution will be executed when the trap command is parsed not when a SIGINT is received. Assuming nothing in the substitution writes to stdout it's equivalent to `trap INT`, thus removing any trap on SIGINT, with the side-effect of running the commands inside the parens. Also, shouldn't you install the trap before setting up the tunnel? What's the point of doing that after you've entered something to terminate the `read` and proceed to tear down the tunnel? As currently written your doing the tunnel cleanup twice.

Line six also looks wrong. On my system, macOS 10.12, `scutil` has no `--service-name` flag.

When you run `autotor` are you running it in the foreground? Are you normally just pressing the [enter] key to complete the `read`?

You're also using `command` a lot when it doesn't appear to be needed. Which shouldn't cause any problems but is rather strange.

Looking at the process execution snapshot you attached I see one mention of `builtin_source`. The `source` command is not explicitly in your `autotor` function and nothing suggests anything that function does would indirectly run that command. Are you running this from your *~/.config/config.fish* startup script (or a script it sources)? Because that's the only way I can see for that function to appear in the execution snapshot.

**Comment by samdmarshall** [comment]
The scutil flag is something i've added through an [additional command flag](https://github.com/samdmarshall/dotfiles/blob/master/fish/wrappers/scutil.fish). which is also why I use `command` used so often, to prevent additional layers of call abstraction. 

This function is being run in the foreground, and whenever the read returns it should then continue on to do the tunnel tear-down. The trap was to allow for the tear-down to happen even if the process was ended irregularly.

None of this is run automatically.

**Comment by krader1961** [comment]
There still shouldn't be any reason to preface `sudo` and `sed` with `command`. I see in your scutil function you're doing `command echo`. Which is going to run the external /bin/echo command rather than the builtin. Which seems rather pointless. But that's not really relevant to the problem at hand just an observation.

> The trap was to allow for the tear-down to happen even if the process was ended irregularly.

Right, but you do understand that it doesn't serve that purpose as currently written? At present you're just running the `networksetup` and `sed` commands twice after you press [enter] to stop the tunnel.

> None of this is run automatically.

Which I take to mean you're typing `autotor` at a shell prompt. Correct? In which case the presence of `builtin_source()` in the snapshot is unexpected.

In issue #3644 we're investigating problems with fish not handling SIGHUP correctly when a command substitution is running. Can you reproduce the problem if you remove that `trap` line? If you can please start it by running `fish -d5 -c autotor 2>/tmp/fish_trace.txt` then close the window. Be prepared to quickly terminate the fish process from another window since it might be writing huge amounts of diagnostic messages to that file. Then attach the file to this issue.

**Comment by samdmarshall** [comment]
Does the trap work as written if i were to exit from the `read` irregularly?

I can look at getting the debug logs as soon as possible; thanks for all the feedback!

**Comment by krader1961** [comment]
> Does the trap work as written if i were to exit from the read irregularly?

No, for two reasons. First, you're trying to define the trap after the `read`. So if you do `kill -INT` or equivalent while blocked on the `read` there isn't any trap in place. Second, you're using a command substitution for the body of the trap. Which means the **output** of

```
command sudo networksetup -setsocksfirewallproxystate "$service_name" off; and command sed -i -e 's=^    ProxyCommand=#   ProxyCommand=' ~/.ssh/config
```

is used as the commands to be run when SIGINT is received. And since that statement doesn't output anything it becomes `trap INT` which removes any SIGINT trap that might exist. What you need to do is remove the existing `trap` statement and insert this after the `set service_name` line:

```
trap "command sudo networksetup -setsocksfirewallproxystate '$service_name' off; and command sed -i -e 's=^    ProxyCommand=#   ProxyCommand=' ~/.ssh/config" INT
```

Also, I put your function on my system replacing the `scutil` commands with `echo`. I can't reproduce the problem you're seeing. Which, along with the wildcard expansion calls in the snapshot you gave us, is evidence there is something else about your environment that is a factor.

**Comment by samdmarshall** [comment]
Hmmm, ok. I am having trouble reproducing the issue again. I will keep an eye out for it and see if I can get it to repro again. If you want to close this in the mean time, that is fine with me. It is possible that scutil didn't execute correctly and it ended up eating the rest of the script or doing some very strange behavior.

**Comment by krader1961** [comment]
Okay, feel free to reopen if it happens again.
