### ISSUE TITLE
Ctrl+Backspace and Ctrl+Delete to delete one word

### ISSUE THREAD

**Issue by almson** [fish-shell/fish-shell#3730]
I notice that fish shell doesn't support deleting whole words with Ctrl+Backspace and Ctrl+Delete. These shortcuts are typically supported by desktop environments. It would be nice to have these features to more quickly edit the command line.

**Comment by krader1961** [comment]
Note that can only be done if your terminal does something other than the traditional behavior for the [control] modifier key. That's because historically that modifier simply converted the other character to a control char; e.g., "A" to \x01 (aka the SOH char). Since backspace and delete often send \cH and 0x7F (aka DEL), which are already control characters, applying the [control] modifier doesn't do anything. You can use the `fish_key_reader` command to see what a given key combination sends.

However, some terminals, such as xterm and rxvt, send special escape sequences that encode which modifier keys were pressed and another key like [left-arrow] or [delete] are pressed. It is reasonable to expect fish to have bindings for some of those key combinations.

See http://invisible-island.net/ncurses/ncurses.faq.html#modified_keys

For example [shift][delete] in xterm sends `\e[3;2~`. While [control][delete] sends `\e[3;5~`. Because [backspace[ sends \x1F (or \177 in octal) by default it can't be modified by the xterm modifier key encoding. That is, by default we can't distinguish [backspace] from [control][backspace] -- they send the same thing. You would have to use Xresources to define a custom sequence for the [control] variant.

**Comment by almson** [comment]
That's too bad. Thank you for looking into it.

Ctrl+Backspace is the more useful one since command completion puts the cursor at the end of the line. A good alternative (again, in the world of GUIs) is to Shift+Ctrl+Left Arrow to select words at a time, and then Delete or Backspace.

**Comment by almson** [comment]
I have switched to the excellent Tilix 1.6.1 terminal emulator, and by default it sends different commands for the modified keys.

How can I bind them to delete words at a time?

- Backspace
```
hex:   7F  char: \x7F  (aka "del")
bind \x7F 'do something'
```

- Ctrl+Backspace
```
hex:    8  char: \cH  (or \b)
bind -k backspace 'do something'
bind \b 'do something'
```

- Del
```
              hex:   1B  char: \c[  (or \e)
(  0.131 ms)  hex:   5B  char: [
(  0.130 ms)  hex:   33  char: 3
(  0.113 ms)  hex:   7E  char: ~
bind -k dc 'do something'
bind \e\[3~ 'do something'
```

- Ctrl+Del
```
              hex:   1B  char: \c[  (or \e)
(  0.132 ms)  hex:   5B  char: [
(  0.113 ms)  hex:   33  char: 3
(  0.110 ms)  hex:   3B  char: ;
(  0.110 ms)  hex:   35  char: 5
(  0.119 ms)  hex:   7E  char: ~
bind \e\[3\;5~ 'do something'
```

**Comment by faho** [comment]
@almson: The `fish_key_reader` invocations have already given you the sequence you need to pass to `bind`, all that remains is to pick what command to run.

For that, I suggest "backward-kill-bigword" or "backward-kill-word". They differ in what they consider. E.g. for "backward-kill-bigword", running it on "some-thing" (with the cursor after) would delete it entirely, while "backward-kill-word" would only delete up to the "-".

So:

```fish
bind \x7F 'backward-kill-bigword'
```

Run it interactively to try it out, when you are satisfied put it in a function called "fish_user_key_bindings".

**Comment by mqudsi** [comment]
What exactly is the 'enhancement' tag here in regards to? The code sent to the shell is dependent on the terminal; what is being proposed here? Can we close this?

**Comment by zanchey** [comment]
Yes, I don't think there's anything that should ship by default here.
