### ISSUE TITLE
Prompt overwriting output of previous command when no newline present

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#3747]
Following on from Gitter discussion:
* https://gitter.im/fish-shell/fish-shell?at=587e830b6c1635643c400ca1

`fish` version:
* `2.4.0-348-gd905ed33`

Steps to reproduce:
* https://asciinema.org/a/echfhyzhs8ern23bbj6c218u9

**Comment by krader1961** [comment]
What is `$TERM`? What terminal are you using? What does `stty -a` report for rows and cols? Are you doing this inside `screen` or `tmux` or with the shell running directly inside the terminal?

**Comment by krader1961** [comment]
Does the problem still occur if you build fish at commit 01dbfb0a3? The next commit changed how fish handles this situation to match zsh so it is the most likely reason for the change in behavior since 2.4.0.

**Comment by zx8** [comment]
> What is $TERM?

xterm-256color

> What terminal are you using?

iTerm2 3.0.13 beta

> What does stty -a report for rows and cols?

rows 44 / columns 151

> Also, does the rows and cols reported by stty -a actually match the size of your terminal?

Yes

> Are you doing this inside screen or tmux or with the shell running directly inside the terminal?

Directly inside the terminal.

**Comment by zx8** [comment]
Seems unrelated to https://github.com/fish-shell/fish-shell/commit/01dbfb0a3f62c5a2765fbed481e17752191ac755...

![image](https://cloud.githubusercontent.com/assets/8544900/22128161/3696e03a-de97-11e6-8d7a-f0d100287ee6.png)

**Comment by faho** [comment]
@zx8: I think @krader1961 meant 58347d494a7c5da3692f7fe57a95b608c0c42368, the commit right after.

That changed the heuristic for getting the prompt onto the next line in the absence of a trailing newline.

**Comment by zx8** [comment]
@faho Same issue @ https://github.com/fish-shell/fish-shell/commit/58347d494a7c5da3692f7fe57a95b608c0c42368:

![image](https://cloud.githubusercontent.com/assets/8544900/22129063/bf825fb0-de9b-11e6-8d94-4553507604a9.png)

**Comment by faho** [comment]
WTF?

It turns out I can reproduce this, and bisecting shows the first bad commit is actually 01dbfb0a3f62c5a2765fbed481e17752191ac755, not the following 58347d4 - which also explains why the PR that added that commit worked for me.

There's some additional weirdness, in that this only triggers with a right prompt, but a simple `echo foo` there does _not_.

The simplest right prompt I have been able to come up with that causes the issue to appear is:

```fish
function fish_right_prompt
     __fish_vcs_prompt
end
```

**Comment by krader1961** [comment]
The right prompt is only somewhat relevant. I can reproduce with a simple "echo hello" in my right prompt. The reason I couldn't originally repro this problem is that I have an empty `fish_title` function and having an actual title is the critical element. I thought this might be the "don't mix narrow and wide stdio functions" issue. However, the `fputs()` and `fputc()` calls in `reader_write_title()` have already been changed to their wide equivalents and that doesn't fix the problem. Reverting those to `writestr()` does fix it. Why using stdio functions rather than writestr interacts with the PROMPT_SP mechanism is TBD.

**Comment by krader1961** [comment]
It turns out this does not need a right prompt or multiline left prompt (at least using iTerm2). My standard single line left prompt plus a non-empty fish_title is enough to see the problem.

**Comment by krader1961** [comment]
This problem is similar to the "don't mix narrow and wide stdio functions" problem. In this case it is because `writestr()` ultimately calls `write()`. Which means it is unbuffered. Switching to buffered stdio functions alters when the characters are written. More specifically, the `reader_write_title()` call at the top of `reader_run_command()` to change the title before running the command is now being buffered with my change. Which would be sort of okay if not for the fix for issue #2453 added a little over a year ago. Since the `echo -n whatever` output is unbuffered it is written before the buffered title change sequence and the `\r` is screwing up the PROMPT_SP mechanism.

The simplest fix is to add `fflush(stdout);` to the bottom of `reader_write_title()`. I've verified that fixes the problem. I'm going to merge that fix and add it to the 2.5.0 integration branch even though I think this probably needs a more comprehensive change.

I want to ponder this interaction of `writestr()` and `writechr()` with the rest of the I/O done within fish so as to avoid future issues of this nature. Perhaps `writestr()` should always call `fflush(stdout)` before calling `write(1, ...)`. Or perhaps it should insert the characters into the stdio buffers. But it's possible a more comprehensive change is needed as I said above.

@ridiculousfish, Do you have any insight into why fish is mixing buffered and unbuffered output like this?

**Comment by ridiculousfish** [comment]
Nice analysis. Any buffering by stdio is unintentional - we use stdio for its wide character support only. Probably we should configure stdout to be unbuffered to avoid this class of issue.

**Comment by krader1961** [comment]
> Probably we should configure stdout to be unbuffered to avoid this class of issue.

Yes, if it's attached to a tty. TBD is reviewing the code to figure out how best to accomplish that. We probably don't want to disable buffering if we're not interactive. I think I'll go ahead with the simple fix but add a "TODO" comment and open a new issue where we can track fixing this properly. That way we can fix the immediate problem with minimal risk before we ship 2.5.0.
