### ISSUE TITLE
Add a descriptive header at the top of completion scripts

### ISSUE THREAD

**Issue by moverest** [fish-shell/fish-shell#3751]
Reading through #3662 and seeing comments at the top of completion scripts [git.fish](https://github.com/fish-shell/fish-shell/blob/master/share/completions/git.fish#L1) gave me an idea.

So, we have, at the top of `git.fish`:

```fish
# fish completion for git
```

This kind of comment is obviously utterly useless. What could a file name `git.fish` in `completions` possibly be otherwise?

One of the problems in #3662 is to know what command a script makes completions for and if the project is still alive. I think we could use a structured comment at the top of every file like that:

```fish
# A short description of the tool.
#
# Project page: http://github.com/fish-shell/fish-shell
# Archlinux package: fish
# Archlinux AUR package: fish-git
# Debian package: fish
# Homebrew package: fish
# Last check: 2016-01-20
```

The idea here is that we could use a tool that reads the header and check on the package last updates to have an idea on whether the project is dead or not. We also won't have to guess what the tool is.

The `Last check` date would tell when the completion was last checked (or updated) for correctness. It could also be use to know if the completion it outdated.

If you find this useful I could add that to the existing scripts (or at least a handful of them).

*Edit: package not packet.*

**Comment by faho** [comment]
I feel like your proposal would mean too much work for too little gain, and I'd rather have a reduced version of this.

If a tool isn't ubiquitous (like git), a comment that describes it and includes the website should be added.

The package stuff (I know english is weird here, but it's "package", "packet" applies to bunches of bits send over the network) in particular strikes me as a bunch of work that is barely useful. Of course in certain cases it might be pertinent to add it, e.g. the `mu` mail indexer is available as `maildir-utils` in debian (IIRC).

The "last check" is bound to become unused and stale, and most of its usefulness can be achieved by looking at the git logs instead. The date is also not really all that helpful because then you'd need to look at release dates, so if we add something like this it should use version numbers instead.

For what we have now (and should do more of), see e.g. stack.fish:

> Completion for 'stack' haskell build tool (http://docs.haskellstack.org/en/stable/index.html)
(Handmade) generated from version 1.0.0

**Comment by moverest** [comment]
The funny thing with your example is that the link is dead. :-D

I have to agree on the date thing.

As for the package, in Arch, you can get the last build date of any package with a simple:
```fish
pacman -Si git | string match -r "Build Date[^:]*: (.*)
```
Which isn't a lot of work.

Parsing the script to get the name is as complex as:
```fish
string match -r "# Archlinux packet: (.*)" < git.fish
```

That way you can easily sort by last update date.

The part that requires a lot of work is writing the header for existing scripts.

**Comment by faho** [comment]
>The funny thing with your example is that the link is dead. :-D

Aaaah! Yeah, they reshuffled some stuff. Presumably to increase type safety or purify some monads or something. https://docs.haskellstack.org/en/stable/README/ works.

>As for the package, in Arch, you can get the last build date of any package with a simple:

Okay. Now do the same thing for debian and brew and fedora and solaris and nixos.

In 90% of cases, the application name -> package name mapping is obvious. In most the remaining 10%, it's only non-obvious on some systems. Plus, most of the time the application website will have links to the packages anyway.

**Comment by moverest** [comment]
> Okay. Now do the same thing for debian and brew and fedora and solaris and nixos.

At first glance, I would say you won't have to. You could do just do with one package manager and cover most of them. But I sure you are thinking about platform specific tools.

> In 90% of cases, the application name -> package name mapping is obvious. In most the remaining 10%, it's only non-obvious on some systems.

They are also false positives: application name that correspond to another package name which the package name exists for another application (I'm thinking about `chromium`, in Debian, which they renamed `chromium-bsu`).

I'm now really interested to do some stats with pacman to check on your 90% figure.

> Plus, most of the time the application website will have links to the packages anyway.

The idea is to go through all of them programmatically. If you have to go the their site for each one of them manually, it can take a long time and that is not really efficient at all.

**Comment by krader1961** [comment]
I'm in agreement with @faho. And I say that as someone who is anal about things like having our code follow a consistent style to the point of restyling all of it in the past year. I do agree with your core observation that a simple one line comment like `# fish completion for git` is pointless. I have no objection to people including package name information, especially if it's obscure. But I don't see enough value to make it mandatory. Far more useful is a URL to the project which owns the command. Including the version of the command or project that the completions are based on could also be useful but probably not enough to make it mandatory.

**Comment by faho** [comment]
>At first glance, I would say you won't have to. You could do just do with one package manager and cover most of them. But I sure you are thinking about platform specific tools.

- For most packages, the mapping is obvious anyway.

- For those where it's not, I need to know the package name on my system. The brew name won't help me if I'm using Fedora.

>I'm now really interested to do some stats with pacman to check on your 90% figure.

In my experience, Arch has rather straight-forward package names. I'd check something like Gentoo (which namespaces packages, so fish becomes "app-shells/fish") or Debian, which splits a bunch and has some weird names (like that mu example I gave above).

Also, the 90% was pulled from my gluteus maximus. It's a rough guesstimate from experience, not to be taken as gospel.

>The idea is to go through all of them programmatically. If you have to go the their site for each one of them manually, it can take a long time and that is not really efficient at all.

What exactly do you want to check programatically here? If there's an update for an application that we have completions for? Interesting idea.

Anyway, since the completions _have_ to be named after the executable, you could incorporate eg. `pkgfile` (or `pacman -Fs`) into your script. Or call the command-not-found-handler. We might even refactor that so the function to get the package name is split out from the output.

**Comment by moverest** [comment]
> Also, the 90% was pulled from my gluteus maximus. It's a rough guesstimate from experience, not to be taken as gospel.

There is something I learned a long time ago is that you should never trust your gut on that kind of thing. Confirmation biais is a real thing.

So, I have crunched the numbers from my installation (I used the local data base; packages I have installed). Out of the 488 completions scripts shipped with my installation, I only have 211 corresponding command on my system. Out of the 211, I have only 45 that use the same name for their package, which is only 21%.

For the script I have used (I may have made a mistake): see [here](https://gist.github.com/moverest/b2f67663adb70d48adbc14be50691cae).

> What exactly do you want to check programatically here? If there's an update for an application that we have completions for? Interesting idea.

The idea I had in mind was to sort all commands by last update date. That way we would have at the bottom of the list (those who weren't updated for a while) the commands that require attention, and that might be dead.

**Comment by moverest** [comment]
I think the real question is more: how do to make sure every completions are pertinent (meaning not for a dead tool that nobody uses) and up to date in an efficient way? Obvious, I know...

I think there should be a mostly systematic and automatic way to check that. I don't see how we can go through 450+ completion script manually each time.

Systematic headers. Too much work? Ok, let's agree on that.

I think there's need be better tooling. That was the idea with packages names. There's a some useful informations (like last update date) that can be retrieve with package managers. On a second thought, that maybe useless to write it manually because with, for example the Arch repositories, we can get the packages listing and retrieve the packages name that way.

Would you find useful a tool that would try to get the last update time of any command using Arch, Debian or Brew repositories? Another assumption that could be made is that if a tool is not in any repositories, it must be dead.

Am I seeing this wrong?

**Comment by faho** [comment]
>There is something I learned a long time ago is that you should never trust your gut on that kind of thing. Confirmation biais is a real thing.

Yup, though I wrote that before I got the automation angle. For humans, it's a lot more than 21%, especially if you count those you can find with a simple search.

-----

Okay, so let's say we do automation. This ideally requires that we

- Get the package name for the current system

- Get the build date for the package (though really it's just a proxy for the release date)

- See if the last commit for the completions is older than the package

The package name is often trivial, sometimes impossible to get - apt isn't packaged for arch (and won't be). Where this can be achieved, something like `pacman -Fo usr/bin/(string replace '.fish' '' -- *)` is the way to do it and requires no manual intervention.

The build date is (as I said) a proxy for the release date, and package rebuilds are annoying here - I've just installed `gnupg 2.1.17-4`, and I'm confident it won't have any new stuff to complete. Even for releases, `gnupg 2.1.17` most likely didn't add or change anything. And unlike what you might have read on $forum, semver won't save you here.


Okay, so now we've achieved automation. Did we achieve eternal bliss? No. What we have is

- A script that depends on the system you run it on, and won't help you with stuff that's not packaged there

- That will print a bunch of releases that aren't relevant to completions

Instead of going via OS packages, it might work a bit better to use e.g. https://release-monitoring.org/, which [lwn tells me](https://lwn.net/SubscriberLink/711906/7c5afea520608e3c/) "manages mappings between upstream names and package names used by distributors". (Also lwn.net is awesome)

But that still won't help with compatible releases.

What it would help with is finding dead upstreams. If there's been no release in (say) 3 years, we can remove the completions. However, having recently gone through all this, I'm reasonably confident that we don't have many such completions, and they won't accrue fast enough that such a script would save all that much time - about an hour every three years.

**Comment by moverest** [comment]
Okay, that seems reasonable.
