### ISSUE TITLE
Fish should not complete git command if we are not in git repository

### ISSUE THREAD

**Issue by Hunsu** [fish-shell/fish-shell#3761]
- [X] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.4.0-386-g176a291

**OS/terminal used**:
Linux Ubuntu 16.04

Fish should not complete git command if we are not in git repository. Fish should only complete init command and some other options like help, version. 

I can submit a PR that add a function that check if we are in git repository.  I did it here https://github.com/fish-shell/fish-shell/pull/3760 for another command. I'm asking if there is not a better way to do it.

## Reproduction steps
1. Go to non git repository
2. git pul [tab]

## Results
```console
~ $ git pull
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by krader1961** [comment]
I'm not convinced the complexity is worth the benefit. Also, consider that disabling the completions does not disable retrieving git commands from history. But doing `git rev-parse --is-inside-work-tree` is pretty cheap; averaging 5 ms on my Macbook Pro whether in or outside of a git repo. On the other hand I'm not thrilled about adding `-n __fish_is_git_repository` to every git complete command.

**Comment by ridiculousfish** [comment]
What's advantage of this? Is the idea here that we should produce an error message on tab-completing when not inside a git repo?

**Comment by faho** [comment]
@ridiculousfish: I believe the idea is that if you're not in a git repo, most git commands are useless (and will only end up erroring out), so we should steer the user towards those that are, and in doing so tell them that they aren't in a repo.

Unfortunately I also can't see a better way to do it than to check in every git completion (inside the condition, because otherwise it'd break if you completed in a repo and then cd'd out of it) whether we are in a repo. That's kinda ugly. Well, either that or check it in `__fish_git_needs_command` and pass an option - `__fish_git_needs_command --everywhere` would be true if not in a repo, without that flag it'd be false. That's not particularly beautiful either.

**Comment by ridiculousfish** [comment]
I think we shouldn't do this. Not only is it complicated, it will slow down existing git completions, because checking if you are in a git repo can be expensive.

**Comment by ridiculousfish** [comment]
Closing as NTBF. Thanks for filing this. Squawk if you disagree or if I missed something.
