### ISSUE TITLE
ANSI colors in suggestion 

### ISSUE THREAD

**Issue by tanmng** [fish-shell/fish-shell#3766]
I'm trying to implement suggestion for some tools that i use (https://github.com/ginatrapani/todo.txt-cli)

The tool offers color-highlighting contexts and projects. They are very useful. I managed to get Fish suggestion to display the tasks number + task description. However, the ANSI color code in task description doesn't show up at all.

I understand that fish offer colors via `set_color` command, but trying to replace ANSI color code with that will take too much time and I'm not even sure if it will work.

So, is there any way to make Fish display the text with ANSI color in suggestion? If not, is there any plan to implement this?

**Comment by krader1961** [comment]
What precisely do you mean by "ANSI color code"? Are you referring to the number embedded in the `\e[ Ps m` escape sequence? Where Ps = 44 to set the background color to blue as an example.

Also, the project you linked to seems to be composed of a single very long and complicated bash script. That should work fine when run from fish since you can run external scripts written in other languages (e.g., python, bash, ruby). Can you clarify what the problem is?

**Comment by tanmng** [comment]
@krader1961 you are correct. By "ANSI color code", I mean the [escape code in ANSI](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) that will set text color and background color.

The script works well in fish (as it should, because fish is really awesome).

The problem arose only when I try to create completion for it in fish.

In `todo.sh`, you can "tag" task by `context` and `project` (using the `@` and `+` sign respectively). When you print the list of tasks, `todo.sh` will display those tags with colors.

An example:
<img width="1453" alt="screen shot 2017-01-23 at 6 13 35 pm" src="https://cloud.githubusercontent.com/assets/4823728/22212497/ac8a31f2-e199-11e6-8054-01f2ac5f2791.png">
 
todo.sh achieves this by using ANSI color code, related settings in `~/.todo.cfg` is shown below

```bash
export BLACK='\\033[0;30m'
export RED='\\033[0;31m'
export GREEN='\\033[0;32m'
export BROWN='\\033[0;33m'
export BLUE='\\033[0;34m'
export PURPLE='\\033[0;35m'
export CYAN='\\033[0;36m'
export LIGHT_GREY='\\033[0;37m'
export DARK_GREY='\\033[1;30m'
export LIGHT_RED='\\033[1;31m'
export LIGHT_GREEN='\\033[1;32m'
export YELLOW='\\033[1;33m'
export LIGHT_BLUE='\\033[1;34m'
export LIGHT_PURPLE='\\033[1;35m'
export LIGHT_CYAN='\\033[1;36m'
export WHITE='\\033[1;37m'
export DEFAULT='\\033[0m'
export COLOR_DONE=$LIGHT_CYAN

# There is highlighting for projects and contexts.
#
export COLOR_PROJECT=$RED
export COLOR_CONTEXT=$PURPLE
```

When I try to create completion for `todo.sh`, the escape code doesn't work and I have to strip them down by this:

```fish
# Returh the list of all UNDONE task numbers along with description in the format that fish shell can accept
function __fish_todosh_all_undone_task_number_and_desc
  eval $todosh_alias ls | grep -E "^[0-9]+ " | gsed 's/ /\t/' | gsed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"
end

complete -c $todosh_alias -f -n '__fish_todosh_needs_task_number' -a '(__fish_todosh_all_undone_task_number_and_desc)'
```
note the `gsed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"` command

The result is shown below
<img width="1453" alt="screen shot 2017-01-23 at 6 24 39 pm" src="https://cloud.githubusercontent.com/assets/4823728/22212837/cc4f3aae-e19a-11e6-9b1f-85403d03ac8d.png">

Without the `gsed` command to strip down the escape code, fish won't recognize the description text and will show only the `action`

**Comment by ridiculousfish** [comment]
This looks to me like a difference in escape handling. In bash, backslashes are not escapes inside single quotes, but in fish they are. So `'\\033[0;30m'` will result in two backslashes in bash, but one in fish.

One fix is to use double quotes, which have the same escaping rules in bash and fish:

    export BLACK="\\\\033[0;30m"

Of course now you need four backslashes for the resulting string to get two.

**Comment by krader1961** [comment]
You can't have escape sequences embedded in the `-a` argument. It has to be plain text. Mostly because fish needs to be able to calculate how much visible space each suggestion requires and that isn't possible, in general, if we allowed embedded escape sequences. You don't even need that todo command. You can simulate it with a trivial fish script installed as *my_todo*:

```
#!/usr/local/bin/fish
printf "01\t%sone%s\n" (set_color red) (set_color normal)
printf "02\t%stwo%s\n" (set_color blue) (set_color normal)
printf "03\t%sthree%s\n" (set_color -b green) (set_color normal)
```

Then install a completion for it: `complete -c my_todo -f -a '(my_todo)'`. You'll see the exact same behavior. Fish ignores the description after the tab. But if you just run `my_todo` you get the expected colored output. Also, despite @ridiculousfish's suggestion I do not believe there is any way to escape the ANSI color sequences so that they will still color the descriptions in the list of completions.

**Comment by tanmng** [comment]
@krader1961 I see, so it's a no-no for making ANSI color escape code in fish completion then. I will just stuck with what I have. Thank you very much for helping. 

@ridiculousfish Thank you for your input, I tried changing the quotation, and juts as before, fish ignores the description (which contains the escape code).
