### ISSUE TITLE
hub command's tab completion does not work.

### ISSUE THREAD

**Issue by shigemk2** [fish-shell/fish-shell#3767]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:

fish, version 2.4.0-390-gf447610

**OS/terminal used**:

- Ubuntu 16.10

Talk about the the issue here.

## Reproduction steps

1. I used [hub command](https://github.com/github/hub).

2. I put [hub.fish](https://github.com/shigemk2/hub/blob/aa4d4ed36e2c52099700f858e6e144c0e403d234/etc/hub.fish_completion) on ~/.config/fish/completions/

3. I used alias for git. 

```sh
function git --description 'Alias for hub, which wraps git to provide extra functionality with GitHub.'
    hub $argv
end
```

4. I expected I could use hub auto completion with git alias, but I couldn't find hub completion(I supposed to find `browse` pushing tab when `git b`). But I could execute `hub browse` as `git browse`.

```sh
~> git b
bisect  (Find the change that introduced a bug by binary search) 
blame  (Show what revision and author last modified each line of a file) 
branch  (List, create, or delete branches)
```

**Comment by krader1961** [comment]
The git completions don't include any `hub` features. Someone will need to write a `hub` completion script. Preferably by refactoring the existing `git` completion script so it can be sourced by the `hub` completion script.

Patches are welcomed. Feel free to take a stab at implementing this, @shigemk2.

**Comment by faho** [comment]
@shigemk2: Please try the following:

Add `complete -c hub -w git` to the top of your completion script. Add `--wraps hub` to your git function.

On my system (without having hub installed currently), that seems to enable both hub-specific and git-general completions for both `hub` and `git`.

So all that would remain to be done here on the fish side would be to integrate hub completions.

**Comment by shigemk2** [comment]
Thank you for your comments.

I found only adding `--wraps hub` would be OK. If we add `complete -c hub -w git`,  hub's tab completion would be wrong. Here:

```
$ hub b
bisect          (Find the change that introduced a bug by binary search)  branch  (List, create, or delete branches)
blame  (Show what revision and author last modified each line of a file)  browse      (browse the project on GitHub)
```

**Comment by faho** [comment]
What exactly is wrong there?

**Comment by shigemk2** [comment]
In this case, the subcommand `browse` is not git's subcommand but `browse` is hub's subcommand. 
But my tab completion showed browse when pressing tab on `git b`.

```sh
~> git b
bisect  (Find the change that introduced a bug by binary search)  blame  (Show what revision and author last modified each line of a file)  branch  (List, create, or delete branches)
```

I think it is because git's completions might inherit hub's completion.

**Comment by faho** [comment]
>However, my tab completion showed browse when pressing tab on git b.

If your git is really hub (because you used that wrapper function/alias), then that is _correct_!

And since hub can do everything that git can do (otherwise you couldn't use it as `git`), completing everything git can do (plus the things only hub can do) is also correct.

So I fail to see what is wrong there.

**Comment by shigemk2** [comment]
I see. 
I want git to inherit hub command by alias, but I didn't want hub to inherit git command.

**Comment by faho** [comment]
> I want git to inherit hub command by alias, but I didn't want hub to inherit git command.

Just to be clear since I'm not sure we're on the same page here, you should want _both_.

`hub` can do the special hub-things ("browse" and such), and also the normal git-things ("commit" and "status" and so on). So you want completions for `hub` to offer both. And because you don't want to copy all the git completions over, you want to set up wrapping completions (`complete -c hub -w git`). And if a git-alias that starts hub instead is set up, you want that to inherit the hub-specific completions as well (`function git --wraps hub`).

And if you need any help with the hub completions, please feel free to ping me!

**Comment by shigemk2** [comment]
Thank you for your comments!!
