### ISSUE TITLE
Child process starts spinning when fish receives SIGTERM

### ISSUE THREAD

**Issue by Ambrevar** [fish-shell/fish-shell#3777]
This issue is a follow-up on #3644 and #3737.

When sending SIGTERM to a fish that is running a program, the child process _sometimes_ gets reparented to PID1 and starts spinning.

**Comment by Ambrevar** [comment]
@krader1961 About this issue you mentioned that 

> it isn't obvious we should change it.

Can you be more specific?

**Comment by krader1961** [comment]
This behavior dates back to at least fish 2.2.0 (I didn't bother to check any older releases). You wrote:

> the child process sometimes gets reparented to PID1

It should always get reparented because the SIGTERM should always kill the shell leaving any child processes orphaned. Can you show a case where that doesn't happen?

Note that fish behaves like bash with respect to background processes. They are left running and will get orphaned and thus reparented to PID 1. The only question is whether we should change how fish handles SIGTERM when it is running an external command in the foreground interactively as opposed to waiting for the user to enter a command.

Even if fish does not exit when there is an external command in the foreground that command will still spin in the situation you've described because the tty is no longer valid. There is nothing fish can do about that. You need to complain to whomever is maintaining that command to fix it.

**Comment by krader1961** [comment]
I've added the RFC label because it is not obvious we should change how an interactive fish shell should handle SIGTERM. Consider this, non-interactive, case: `fish -c 'sleep 1234'`. If you send SIGTERM to the fish process it terminates leaving the sleep command running but reparented to PID 1. The current fish interactive behavior is the same. Bash, on the other hand, handles the interactive and non-interactive cases differently.

Note that when exploring bash behavior you can't just run `bash -c 'sleep 1234'` you have to do something like `bash -c 'sleep 1234; echo true'`. If you don't then bash simply replaces itself with the sleep command (i.e., it does an `exec()` without first doing a `fork()`).

**Comment by Ambrevar** [comment]
You are right and I was wrong: Urxvt does not seem to send SIGTERM, but SIGHUP just like xterm (to be verified). The symptoms were different though, not sure why... Anyways, I cannot reproduce the spinning by closing Urxvt and ncdu-wrapper, which means "problem solved" for me! Thanks!

Both bash and zsh will ignore SIGTERM when a process is running in the foreground.
SIGTERM on fish does trigger the fork+spinning. Questions:
- Why is the process spinning at all?
- Is it possible to reparent the spinning process? If not, I don't see why fish shouldn't follow bash/zsh's behaviour.

**Comment by krader1961** [comment]
> Why is the process spinning at all?

No idea. That's something to ask whomever is responsible for the spinning program.

> Is it possible to reparent the spinning process?

I don't understand the question. When the parent process, fish, dies the spinning, child, process is automatically reparented to PID 1. Since in the UNIX process model every process other than PID 1 has to have a parent process responsible for reaping it.

Fish shouldn't follow bash/zsh behavior vis-a-vis SIGTERM sent to an interactive shell, IMHO, because it is inconsistent and, frankly, somewhat surprising. If I send SIGTERM to a process I expect it to die.

**Comment by Ambrevar** [comment]
Question was if it is possible to fire up a new shell and recover the spinning process, à-la nohup / job.

Agreed on your reasoning for SIGTERM: I think it should propagate the signal to its children and terminate only if all the children are dead.

**Comment by krader1961** [comment]
> ...is possible to fire up a new shell and recover the spinning process

No, the UNIX process model and API does not support anything like that. Furthermore, the reason the process is spinning is almost certainly because the tty it was attached to is no longer in a working state and the program is not correctly handling that condition. So you'd also have to change the controlling tty for the process, not just reparent it.

> Agreed on your reasoning for SIGTERM: I think it should propagate the signal to its children and terminate only if all the children are dead.

You misunderstood what I wrote, @Ambrevar. That is not what fish should do and is not what bash/zsh does.

In any event I see no compelling reason for fish to emulate bash with regard to handling SIGTERM when interactive and there is a foreground process running. As I said earlier that is inconsistent with how fish and bash/zsh handle SIGTERM in other contexts. Unless someone can provide a good reason for implementing for why fish should implement that inconsistent behavior we shouldn't change the current, consistent, behavior.

**Comment by Ambrevar** [comment]
@krader1961: I understand this is neither what fish nor bash/zsh do, I was simply suggesting a new behaviour which seems more convenient to me.
Regarding consistency, agreed: then why not changing the non-interactive behaviour as well?

I suppose the point is that we should leave the children terminating properly once reparented. Is that the use case you think about?
Then OK, agreed with you, and let's keep this issue closed.
