### ISSUE TITLE
Receiving 'error: identifier "siginfo_t" is undefined' when attempting to build from source

### ISSUE THREAD

**Issue by SurfaceThought** [fish-shell/fish-shell#3783]
Hello there,

I use fish on both my machine at home (Fedora) and my work machine (MacOS) and love it. However, for work, I would like to install fish locally in my home directory on a server I ssh into that I don't have admin privileges too.

Downloading the 2.4.0 fish tar works fine, and the config goes through without any warnings. However, as soon as a `make` I get the following error:

`src/proc.h(337): error: identifier "siginfo_t" is undefined
  void job_handle_signal(int signal, siginfo_t *info, void *con);`

The server is running Red Hat 6. Let me know what other info I can give you. 

Thanks!

**Comment by krader1961** [comment]
It's extremely unlikely RHEL6 doesn't define struct siginfo_t. It's traditionally defined in *<sys/signal.h>* which should be included by *<signal.h>* which is included by *src/proc.h*. Did you run `autoconf` or `autoreconf --no-recursive` first?

**Comment by SurfaceThought** [comment]
Thanks for the reply,

I did not run autoconf or autoreconf --no-recursive, just 

`./configure --prefix=$HOME/local --disable-shared`

As suggested by this script: https://gist.github.com/masih/10277869

**Comment by krader1961** [comment]
What happens if you first do `autoreconf --no-recursive`? RHEL6 is old enough (~7 years?) that the autoconf artifacts included with the fish source may not be compatible.  That script you linked to is misleading. In general you should always run autoconf/autoreconf before `./configure`.

**Comment by SurfaceThought** [comment]
`autoreconf --no-recursive` runs with no message or warning, running `make` still causes the same error.

**Comment by krader1961** [comment]
See issue #286. Like that individual you probably have an unexpected env var or something similar that is causing g++ to not use the system header.

**Comment by SurfaceThought** [comment]
Thank you. I did see that issue before I posted this one, however the issue with that user were include paths in his .bashrc. I do not have any include paths in my .bashrc, so I didn't think the same issue was applying for me.

Do you have any ideas how I try to sniff out any other env vars that might be causing the issue?

**Comment by faho** [comment]
@SurfaceThought: The output of `env` might be useful. Please do censor any private information though.

**Comment by SurfaceThought** [comment]
Okay, no private information as far as I can tell:

https://gist.github.com/SurfaceThought/449081c740b4c433633a30e0bf619054

Thank you!

**Comment by faho** [comment]
It appears you're trying to compile fish with icc - `CXX=icc`, and I don't think we support that.

Can you try gcc?

**Comment by SurfaceThought** [comment]
Woops, alright so do I just set `CXX=gcc` during `make`, or do I need go back and rerun `./configure`

**Comment by krader1961** [comment]
I would expect the Intel C++ (`icc`) compiler to be able to compile fish. But it may require other flags or env vars in order to allow fish to #include both its signal.h header and the system header. As @faho suggested just switching to gcc is probably the simplest solution; assuming you have gcc installed on the system. You should be able to switch temporarily while building fish by just doing `env CXX=g++ ./configure`. That should then be reflected in the `CXX` entry in the *Makefile*.

**Comment by SurfaceThought** [comment]
Thank you guys, this solved the problem.

Unfortunately, it is returning another error:

`undefined reference to `_intel_fast_memcpy'`

I am beginning to think this probably isn't going to work out...

**Comment by krader1961** [comment]
That error is probably due to the `LD_LIBRARY_PATH` env var which has paths to icc specific libraries. Since it is unlikely you need any of those directories for fish just

```
env CXX=g++ LD_LIBRARY_PATH= ./configure
env LD_LIBRARY_PATH= make
```

**Comment by SurfaceThought** [comment]
Holy Smokes! Finally got it going.

Thanks again for all the help. For the record, this is what I needed to get it working:

`autoreconf --no-recursive`
`env CXX=g++ CC=gcc LD_LIBRARY_PATH= ./configure --prefix=$HOME/local --disable-shared`
`env LD_LIBRARY_PATH= make`

It wasn't working without both the CXX and CC env variables set.

**Comment by zanchey** [comment]
> What happens if you first do autoreconf --no-recursive? RHEL6 is old enough (~7 years?) that the autoconf artifacts included with the fish source may not be compatible. That script you linked to is misleading. In general you should always run autoconf/autoreconf before ./configure.

For the record, this is incorrect. The autoconf artefacts are backward compatible without exception and the build is tested using these artefacts on RHEL 6. The advice to run autoreconf will prevent building on some platforms which are still supported and adds an extra dependency which is unnecessary.

For RHEL 6, I strongly encourage everyone to use prebuilt binaries from https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A2&package=fish - although unfortunately from 2.5.0 only 32-bit builds will be available (these will still run on all platforms).

**Comment by SurfaceThought** [comment]
I didn't have success installing the CentOS 6 .rpm running rpm -ivh -r /home/username. Is that the incorrect way to install the binary?

**Comment by faho** [comment]
@SurfaceThought: Yeah, that's not going to work. I'd assume that it wouldn't find the initialization files because it's been built to have them in /usr/share. So the rpm won't work without root access.

**Comment by SurfaceThought** [comment]
@faho Right, makes sense. So if you don't have root privilege and you are trying to install something to your home directory, there is no way to use prebuilt binaries, right?

**Comment by krader1961** [comment]
> ...there is no way to use prebuilt binaries, right?

Not at all. It depends on the program whether that will "just work". It mostly depends on whether the package includes supporting files that the program expects to find in */usr/share* (or */usr/local/share*, etc.).

In fact, it will sort of work for the fish rpm. However, when fish is compiled the default paths it looks in for autoloaded functions, completion scripts, and the system wide *config.fish* script is baked into the program. And that hardcoded default won't be affected by `-r /home/username`. Which means that you'll have to manually modify vars like `$__fish_datadir` and `$fish_function_path` since their default values won't point to where you've installed fish's supporting files. Frankly, unless you cannot build from source with `./configure --prefix=$HOME/local` (or some such) trying to use the prebuilt package is more trouble than it's worth. If you want to use the RedHat provided package it would probably be easier to use the source RPM than the binary RPM and have to manually edit all the run-time config vars.

**Comment by tormentliang** [comment]
Also hit by this, finally I found the reason:
[The siginfo_t type conforms to IEEE Std 1003.1-2004 ("POSIX.1"). ](https://www.freebsd.org/cgi/man.cgi?query=siginfo)

A _POSIX_C_SOURCE version should be set for the preprocessor to activate siginfo_t.
Adding `set(GKlib_COPTIONS "${GKlib_COPTIONS} -D_POSIX_C_SOURCE=199309L")` to GKlibSystem.cmake works for me.
