### ISSUE TITLE
Core documentation does not list the '\|' escape character

### ISSUE THREAD

**Issue by Phidica** [fish-shell/fish-shell#3794]
Description
=========
I'm looking at the current (2.4.0) documentation, and in the [section for escape characters](https://fishshell.com/docs/current/index.html#escapes) there is no entry for '\\|'. The parser internally uses this escape (running `function "|"; echo test; end` defines a function which can be called with `\|`), so it ought to be in that list with the others. Functionally speaking, it's no different to '\\&' or '\\;' which *are* listed

Proposed fix
==========
Insert `- '<code>\\|</code>' escapes the vertical bar character` at line 109 in `/doc_src/index.hdr.in`

**Comment by ridiculousfish** [comment]
Sounds good. Want to do a PR? 👍

**Comment by krader1961** [comment]
I'm actually surprised to see things like `\;` and `\&` explicitly documented since common practice in many programming languages is to use backslash to remove the special meaning of the next character. And that is normally documented in a generic manner. But given that the fish documentation explicitly mentions so many of those generic escapes are it makes sense to also mention `\|`. If you're interested in learning how to use git and create a Github pull-request we would be happy to merge a change authored by you, @Phidica. If not we'll be happy to do it on your behalf.

**Comment by Phidica** [comment]
I've never made a PR on a bugfix for a project as big as this one but I'm happy to give it a shot! 

I'd guess the reason `fish` documents the escapes explicitly is that the parser actively highlights a necessary escape like `\n` differently to a pointless escape like `\m`. Pointless escapes seem to be treated as two literal characters instead

**Comment by krader1961** [comment]
Closing since PR #3796 has addressed this issue.
