### ISSUE TITLE
`make test` reports failures if `xxd` is not installed

### ISSUE THREAD

**Issue by Phidica** [fish-shell/fish-shell#3797]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed**: 2.4.0

**OS/terminal used**: Fedora 24, GNOME Terminal 3.20.3

I'm on my way toward contributing to the project proper, but while running `make test` after tweaking some code I encountered high-level failures in `locale.in`, `printf.in`, and `test1.in`. The output shown indicated that the error was `Unknown command 'xxd -p'`

## Reproduction steps
1. `sudo mv /bin/xxd /bin/xxd-tmp`
2. `make test`
3. `sudo mv /bin/xxd-tmp /bin/xxd`

## Proposed fix
Add a check for the existence of the `xxd` command before attempting to run high-level tests and disable the tests if it is not found, similar to the check for `expect` which is made before running the interactive tests

**Comment by Phidica** [comment]
If there's no objection, I'll submit a PR for my fix

**Comment by krader1961** [comment]
I'd rather not see those tests disabled just because you don't have xxd installed. Is there some reason you can't install xxd?

It looks like disabling the interactive tests if expect isn't available was done by Kevin Ballard back in Sep 2014 when they were restructuring the tests and setting up Travis integration. It looks like there was a short period when our Travis config didn't correctly specify the need to have expect installed. I think we should remove that check and require expect to be installed. The only tests that should be disabled are those that are specific to a particular OS or machine environment and AFAIK we currently have no such tests.

**Comment by Phidica** [comment]
I was able to install `xxd` with the vim-common package, but my concern is that at no stage was `xxd` considered a "required" prerequisite and neither `make` nor `fish` told me I would need it. You're right, I didn't realise that disabling the test entirely was probably not ideal; I just took advice from how the interactive test behaved when `make test` discovered that I didn't have `expect` installed either

However, I feel it would be annoying to the user if tests seem to fail because programs they rely on aren't installed. Is there some better level at which uncommon programs like `xxd` and `expect` can be asserted as installed before the tests are attempted?

**Comment by krader1961** [comment]
I just checked my Ubuntu system and, sure enough, I have xxd installed by virtue of having installed Vim. I didn't realize that is where that package provided that command. It doesn't appear to be available in any other package. If we can find a suitable alternative to xxd that doesn't require installing a specific editor we should switch to it. The `od` command is the obvious alternative since it is in the coreutils package. The problem with `od` is that it is much older and different implementations support different capabilities.

I'm not opposed to testing for the presence of necessary utilities and providing a useful diagnostic message if they're not found. What I am opposed to is how it is currently done in *tests/interactive.fish*:

```
if not type -q expect
    say red "Tests disabled: `expect` not found"
    exit 0
end
```

That `exit 0` should be `exit 1`. We don't want to pretend the tests completed successfully when we did not even run them. The same sort of check for `xxd` would be fine. But before you do that let's see if we can find an alternative command that will do what we need in the non-interactive tests and is more likely to be installed on every developers system.

**Comment by zanchey** [comment]
`od` might be better, but the argument syntax is not very portable.

**Comment by krader1961** [comment]
Every `od` implementation supports the `-b` flag AFAICT. However, BSD and GNU implementations differ in the whitespace padding so we also need to run the output through `sed` to normalize the whitespace. I've got a change that switches us from using `xxd` to `od` and am in the process of verifying it works on the platforms available to me as well as Travis.

**Comment by floam** [comment]
Couldn't we actually do this just using our builtins? See `__fish_urlencode`.
