### ISSUE TITLE
Rationalize get/setenv with threads

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#3798]
[This aricle](http://rachelbythebay.com/w/2017/01/30/env/) observes that calls to `getenv()` may race with calls to `setenv()` with crashy results. fish does not call `getenv()` often, but library calls may use it more.

It looks like fish's `setenv()` calls are in response to locale and time zone changes. Presumably we call setenv() to export these to `gettext`, `curses`, etc.  We should figure out what if anything to do about this.

**Comment by krader1961** [comment]
We have no choice. We have to use setenv/unsetenv in order to affect ncurses, locale, and the timezone subsystems. AFAICT there isn't a proper API that would allow us to affect those subsystems when a relevant env var is changed without making those calls. At least not anything that we can expect to be available on all the platforms we support. I'd be happy to be proven wrong.

At the moment the fork scenario should be impossible. However, if we ever fork from other than the main thread in the future that deadlock could happen. I've pondered in the past whether we should add a barrier that keeps us from performing a fork unless potentially unsafe operations are guaranteed to not be executing and vice-versa. This could also be used to ensure threads are not executing possibly dangerous code around those potentially unsafe operations.

**Comment by krader1961** [comment]
Also, I don't think this is legitimately a bug in fish. It's really a bug in the libraries we depend on just like the stupid tty EIO bug we recently worked around. It is also such a low probability issue that frankly I don't think addressing this can be justified solely on the basis of setenv/getenv being broken. On the other hand the idea of a barrier mechanism we could use to ensure all but one thread is quiescent when performing a potentially unsafe operation has other uses which could justify doing this work.

**Comment by ridiculousfish** [comment]
forks are actually not the problem here. The issue is that threads that use `getenv()` may race with `setenv()` calls on other threads (in fish, only the main thread).

"Do nothing" seems fine, since we don't even have a test case. If we do find a case, waiting until background threads exit or reach a safe point seems like one reasonable path. Using locks to synchronize those libraries with our `setenv()` calls is an alternative.

I instrumented fish and spotted one `getenv` call in `getpwnam`, so I think it's possible in theory. 

Anyways I'll close but I'm glad we have this artifact to show that we thought about it :)

**Comment by zanchey** [comment]
Hah. I just came across this again after being reminded about `setenv`'s terribleness in https://ttimo.typepad.com/blog/2024/11/the-steam-client-update-earlier-this-week-mentions-fixed-some-miscellaneous-common-crashes-in-the-linux-notes-which-i-wante.html. `setenv` takes a lock, but it's not actually helpful because libraries might call `getenv` without it.

The `setenv` calls in `init_curses` can probably be dropped; no actual ncurses calls get used any more and the whole thing should probably be renamed `init_terminfo` etc.

`setenv` for locale changes probably needs to stay, because `setlocale` calls `getenv`.

I don't know either way for the timezone settings. I think it's hard to be sure that the variables set by `tzset` won't be used somewhere.

**Comment by faho** [comment]
> I don't know either way for the timezone settings. I think it's hard to be sure that the variables set by tzset won't be used somewhere.

`history --show-time` displays localized time and uses localtime_r, which will read $TZ: https://github.com/fish-shell/fish-shell/blob/d33cbfd1a309cea0d7a58501ccb7111714e64238/src/history.rs#L1442

I think that (and the corresponding tests) may be the only use in our codebase.

> setenv for locale changes probably needs to stay, because setlocale calls getenv.

Long term, it might be possible to stop using the libc-level locale entirely. We might be reasonably close for LC_CTYPE.

(iirc this would require a replacement for gettext)
