### ISSUE TITLE
send a Return key and execute after appending commandline.

### ISSUE THREAD

**Issue by amosbird** [fish-shell/fish-shell#3819]
- [x] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: fish, version 2.5.0-161-g09ad6969-dirty

**OS/terminal used**: Archlinux, urxvt

Can I make `Alt-p` send a `Return` key and execute for me after adding ` ^&1 | less` ?

**Comment by krader1961** [comment]
Create a function like this (you can obviously use a different name):

```
function pipe-less
    commandline -a ' ^&1 | less'
    commandline -f execute
end
```

Then bind it to the sequence your key sends: `bind \ep pipe-less`. You might want to use a different key since `\ep` is bound to `__fish_paginate` by default but that's totally up to you. You should put the bind command in a script named *~/.config/fish/functions/fish_user_key_bindings.fish* like this:

```
function fish_user_key_bindings
    bind \ep pipe-less
end
```

**Comment by amosbird** [comment]
Thank you.

**Comment by amosbird** [comment]
@krader1961 Can I make it like this `commandline -f execute ^&1 | fzf` so the history will contain the original commandline?

**Comment by krader1961** [comment]
Your comment makes no sense to me. Executing `commandline -f execute` does not produce any output as such. It causes fish to execute the current command line which might produce output. I don't use fzf. What history are your talking about? If you want "| fzf" to appear in the history just modify the pipe-less function to include it.

I suspect you're asking how to make the result of a command selected using fzf appear in the fish command history rather than the original, literal, command. I would expect fzf to modify the command line before you press [enter] to execute it. Or are your asking how to make the original command line before fzf modifies it appear in the fish command history? Either way I think that is a question better directed to the fzf community.

**Comment by amosbird** [comment]
@krader1961 well I was asking how to make function like
```
function pipe-less
    commandline -a ' ^&1 | less'
    commandline -f execute
end
```
put the original commandline in history, without ` ^&1 | less` part.

**Comment by krader1961** [comment]
> put the original commandline in history, without `^&1 | less` part.

Okay, that nicely clarifies what you were asking. Unfortunately that isn't possible. You could open an enhancement request but it isn't likely to be implemented any time soon, if ever, because there are a lot of other bugs and enhancement requests that are higher priority to address. Unless, of course, you actually made the necessary changes and submitted them for review and merging into the code base. Something we'd like to see more of from people who are passionate about a specific change.

**Comment by amosbird** [comment]
@krader1961 Cool, and the reason I asked this is to make sure I don't end up implementing something that can be trivially done. In fact, I think this feature is pretty nice to have. We may use it to add a function that let some specific commands transparently redirect long output to a pager with just a normal `Enter` key.

What would be the correct place to implement this? I'm considering adding arguments like this, `commandline -f execute " ^&1 | less "` .

**Comment by krader1961** [comment]
@amosbird: Just open an issue with your proposal to begin a discussion. Try to include as much detail regarding the rationale for the change, use case examples, and any ideas you have for how it might be implemented. Then the core dev team and others will respond with questions, concerns, etc.
