### ISSUE TITLE
Confusing screenshot

### ISSUE THREAD

**Issue by ShalokShalom** [fish-shell/fish-shell#3832]
- [x] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
2.5
**OS/terminal used**:
Linux based OS

The execution of this file is not working as described:

https://fishshell.com/assets/img/screenshots/scripting.png

This screenshot is linked here, just click on the image next to 'sane scripting'

http://fishshell.com/

## Reproduction steps

1. try to reproduce the steps in your screenshot

## Results

without ./ 
Unknown command 'detect_os'

without .fish being marked as executable
The file './detect_os.fish' is not executable by this user

without shebang
The file './detect_os.fish' is marked as an executable but could not be run by the operating system.

Besides the fact, that these error messages are not very helpful to me, is it possible to run .rb, .py and such files without any of these modifications above.

**Comment by faho** [comment]
The idea of that screenshot is probably that it's a function autoload file (in ~/.config/fish/functions). We should probably adjust it so that is either visible or use an interactively defined function (i.e. show running `function detect_os` on the commandline).

>without ./
Unknown command 'detect_os'

The way fish finds external commands is essentially the same as with all other shells I'm familiar with - it looks in $PATH for a file of the given name, and tries the first match.

>without shebang
The file './detect_os.fish' is marked as an executable but could not be run by the operating system.

It then hands that match to the operating system (via the `exec` family of functions - see `man 3p exec`). The OS then determines how to run that file, and if there's no shebang then it can't run it because it doesn't know how. Hence this error.

>Besides the fact, that these error messages are not very helpful to me, is it possible to run .rb, .py and such files without any of these modifications above.

The error messages document what happens - we can't find the command (so you haven't put it in a place fish will find it), the OS' permissions system disallows running that file or the OS can't figure out how to run it.

It is possible to run ".rb" and ".py" files and such with two different approaches. Either you add a shebang _and_ mark it executable, then you can run `/path/to/foo.py` (and if you put it in $PATH, you can skip the /path/to/), or you run `python /path/to/foo.py` or `ruby /path/to/bar.rb`.

In the latter case, the thing that is executed as far as the OS is concerned is the interpreter, which then reads the files. (This is also why the x-bit isn't really a security thing, because you can do this with all executable files - for ELF binaries you'd use the linker as the interpreter)

The fish-specific thing here is that, if you put a function called "baz" into a file called "baz.fish" into a directory in $fish_function_path, then fish will load it automatically.

Have I answered your question and if so, what better screenshot would you propose?

**Comment by ShalokShalom** [comment]
I think its a nice idea to create a functions directory in ~/.config/fish/ once a user launch fish for the first time.

This here shows the autocompletion in action too: https://asciinema.org/a/9vzt60y52krsjye6m9ol6w81t

Its also possible to embed an own player:

`<script type="text/javascript" src="https://asciinema.org/a/9vzt60y52krsjye6m9ol6w81t.js" id="asciicast-9vzt60y52krsjye6m9ol6w81t" async></script>`

You can do that for all the features?

Otherwise, here is a screenshot: 

![screenshot_20170209_133602](https://cloud.githubusercontent.com/assets/6344099/22783581/be957c68-eecc-11e6-85ec-c7beb3192e27.png)
  
This work, when a functions directory is already in place, otherwise use 
mkdir ~/.config/fish/functions/; cp detect_os.fish ~/.config/fish/functions/

**Comment by krader1961** [comment]
Fish will create that directory if you type `funcsave detect_os` after defining the function. Alternatively, as you noted you can simply move your script to that directory after possibly creating it by hand. It is not clear what you are suggesting we change.

**Comment by ShalokShalom** [comment]
> The execution of this file is not working as described:
> https://fishshell.com/assets/img/screenshots/scripting.png

**Comment by krader1961** [comment]
Okay, I've opened https://github.com/fish-shell/fish-site/issues/46 recommending that image be updated with one that is clearer. That image has simply omitted the implicit assumption that the PWD is *~/.config/fish/functions*.

**Comment by ShalokShalom** [comment]
Plus the source command?

**Comment by faho** [comment]
@ShalokShalom: No. If a file named foo.fish containing a function foo is placed in that directory, the `source` is unnecessary. We automatically load it.

**Comment by ShalokShalom** [comment]
when i run funcsave detect_os:
funcsave: Unknown function 'detect_os' 

I run this in the same directory

**Comment by faho** [comment]
For `funcsave` to work, you'll need to have the function defined.

So either run

```fish
function detect_os
      #do some stuff
end
```

or

`funced detect_os`, which will open your text editor.

After that, you can test the function out a bit interactively, change it (e.g. via doing `funced detect_os` again), and if you are satisfied run `funcsave detect_os`.

Either way, that's outside of the scope of this issue. If you have any more questions, please open a new issue for them or ask on https://gitter.im/fish-shell/fish-shell.

**Comment by ShalokShalom** [comment]
function detect_os is part of my code, as you can see above.

All i ever wanted is to reproduce a simply screenshot, which get showed on the homepage and this resulted into a issue report and some more lines in IRC.

And i am still without the knowledge, to run a simple script.

**Comment by krader1961** [comment]
> And i am still without the knowledge, to run a simple script.

Every shell script should begin with a `#!` line such as `#!/usr/local/bin/fish` or `#!/usr/bin/env fish`. It should also be marked executable: `chmod 755 script_file_name`. Then put it in one of the directories in your `$PATH` environment variable. We're happy to help new users but please understand that your question is not unique to fish. You need to do the same steps if you're using bash or zsh.

The only aspect of your question unique to fish is how autoloaded functions work. Those are technically scripts that are implicitly `source`d. Scripts that are run via the `source` command don't need the shebang line (i.e., the `#!...` line). Autoloaded fish functions need to be in a file with the name of the function and ending with `.fish`; e.g., `detect_os.fish`. Furthermore the file needs to be in one of the directories in the `$fish_function_path` variable. Most often this means your *$HOME/.config/fish/functions* directory.

Finally, expecting a screenshot like that to tell you everything you need to know about creating scripts and autoloaded functions is not a reasonable expectation. You should read the documentation. Starting with the [tutorial](http://fishshell.com/docs/current/tutorial.html).

**Comment by ShalokShalom** [comment]
As you state, is such a screenshot possible, or?
Its one line more, or two?

And yes, it might be, that these things are the same in bash and zsh.
Since bash is preconfigured and i never try to write an bash script before, is this all new to me. :)

I think it makes zero difference, if i am a new user to fish in specific or to scripting at all - it might be rare, that such a case happens, since the most start with bash or dash.

On the other hand make the assumption that every user know such basic details, the introduction for a beginner even harder, when they like to use fish as their shell - i am very interested into this project, simply because some of its advantages are pretty unique and helpful to me.
