### ISSUE TITLE
python completions are wrong for the non-default interpreter

### ISSUE THREAD

**Issue by asomers** [fish-shell/fish-shell#3840]
- [x] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.5.0-180-g0a929f7a-dirty

**OS/terminal used**:
FreeBSD 12.0, QTerminal

Commit f70b1ff simplified the Python completion code, but it introduced a new bug.  On a system with a symlink from `python` to either `python2` or `python3`, `python.fish` will use the completions for the default interpreter, regardless of which interpreter is invoked.  The problem is that, unlike in the old code, the new python2.fish and python3.fish files don't pass the executable name to python.fish.

## Reproduction steps
1. Ensure that /usr/local/bin/python points to /usr/local/bin/python2
2. Type "python3 -" and press tab
3. Among the suggestions should be "-q", "-X", "-b", and "-bb".  But none of those will be there.  Instead you'll see "-3", "-t", and "-Q"

**Comment by krader1961** [comment]
There are two problems here. First is that the version specific completions (e.g., *share/completions/python2.fish*) rely on the dynamic, run-time, version check in *share/completions/python.fish*. The second is that the generic *share/completions/python.fish* should defer the version specific completions to run-time since using mechanisms like `pyenv` or Anaconda `conda` command can change which version the `python` command refers to. Obviously fixing the second problem obviates fixing the first.

While it would be straightforward to fix the first problem it would be better to fix the second problem since doing so fixes both in a generic manner. Unfortunately I don't see any way to solve the second problem in a straightforward manner. None of the other completions, such as for `ruby`, appear to deal with multiple versions that might be invoked by the same name depending on how the shell environment has been manipulated.

So it looks like the only realistic option at this time is to add the version specific completions found in *share/completions/python.fish* to the version specific completion scripts.

**Comment by faho** [comment]
Should be fixed now.

>So it looks like the only realistic option at this time is to add the version specific completions found in share/completions/python.fish to the version specific completion scripts.

That's what I ended up doing.

>None of the other completions, such as for ruby, appear to deal with multiple versions that might be invoked by the same name depending on how the shell environment has been manipulated.

One difference here is that python's version brouhaha is special. I don't think the ruby community is as split on versions as python's is. For more information, I refer to lwn.net's comment section on an article that mentions python somewhere.
