### ISSUE TITLE
Core Infrastructure Initiative (CII) Best Practices

### ISSUE THREAD

**Issue by ypid** [fish-shell/fish-shell#3842]
I would like to point you to the [CII Best Practices Badge Program](https://bestpractices.coreinfrastructure.org). Could you go thought the [criteria](https://bestpractices.coreinfrastructure.org/criteria), [add the project](https://bestpractices.coreinfrastructure.org/projects/new) and keep it up-to-date there?

Refs:
- https://bestpractices.coreinfrastructure.org
- https://twit.tv/shows/floss-weekly/episodes/389

**Comment by krader1961** [comment]
Meh. I've seen such self-certification efforts many times in the past three decades. And one, ISO 9001, that required an actual audit by an independent party. ISO 9001 simply required that you document your processes and prove you followed that documentation. If your documentation stated, for example, that you only performed regression testing on 0.001% of the changes made to your code it was sufficient to show that is what you actually did.

I think we should follow best practices and for the most part we do (e.g., continuous integration testing, paying attention to lint errors, etc.). I don't see the point of spending any time self-certifying with a third-party that we do so.

**Comment by ypid** [comment]
Thanks for explaining. The advantage I see is that it gives users a clear hint how well the project is doing. But I agree that time is better spend in actually improving this than in self-certifying.

**Comment by faho** [comment]
I've skimmed the list, and most of the criteria are things we do.

We obviously have an issue tracker, we have a vcs repo that we use for actual development, the project is free software, we use CI, static analysis (@krader1961 is a huge fan) and so on. We're actually doing okay.

There are a few things I'm uncomfortable with declaring, like "The project MUST have at least one primary developer who knows how to design secure software". I'd assume we do, since we have some rather smart and knowledgeable folks here, but I'm not sure that they won't move on and I'll be the last one left.

I know they've stated that all criteria should also be achievable by small (even single-dev) projects, but I'm not sure that actually works. Of course one singular hacker can handle security for a small project, but what if that dude's on vacation? Or in the hospital? Then "rapid response" to security issues suddenly becomes impossible.

And at the end of the day, what matters much more is what we do, not what we declare.

**Comment by faho** [comment]
I'm going to close this now, since I believe the declaration isn't really worth all that much. 

If anyone feels the need to pick this up, feel free to do so.

**Comment by ypid** [comment]
> There are a few things I'm uncomfortable with declaring, like "The project MUST have at least one primary developer who knows how to design secure software"

I know what you mean. But you can just set it to unmet and explain your reasoning when you are not convinced that the criteria is fully met yet. That is what I did for now: https://bestpractices.coreinfrastructure.org/projects/237
No problem with being extra careful even if you don’t get the badge right now.

> I know they've stated that all criteria should also be achievable by small (even single-dev) projects, but I'm not sure that actually works.

I belief it is possible. ["The project's initial response time for any vulnerability report received in the last 6 months MUST be less than or equal to 14 days."](https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/doc/criteria.md#vulnerability_report_process). This is the shortest response time required across all criteria and you should normally be able to meet that. In case of vacation you might still check your personal mails. The only time where this might not work are accidents but they can not be planned or something and are hopefully not too likely.

Example: [yaml4rst](https://bestpractices.coreinfrastructure.org/projects/457)

**Comment by ypid** [comment]
Also note that going though the criteria might help to find issues like [Example installation vulnerable to MITM leading to the execution of arbitrary code](https://github.com/freshshell/fresh/issues/139) and [ Legacy HTTP and git:// URLs being used](https://github.com/fish-shell/fish-site/issues/47) without relying on someone who not uses Fish currently to stumble across it.
