### ISSUE TITLE
Unquoted abbreviations with second command are executed on launching fish.

### ISSUE THREAD

**Issue by mr-mustash** [fish-shell/fish-shell#3844]
Hey all, I discovered this today while trying to write a multi-command abbreviation and I noticed that git repositories I was in were auto-updating. I figured this out because the abbreviation was something like `abbr --add git-clean git gc ;and git pull ;and git remote prune origin ;` . After digging through `fish -d 2` I noticed that it was spawning lots of external command on startup, mostly from my aliases.conf. This lead me to do more testing, and you'll see the results and replication steps for those below.

This has been observed on macOS Siera and Ubuntu 12.04, both using Fish 2.5.0

## Reproduction steps
```
$ mkdir ~/testing                   
$ ls -la ~/testing/                          
total 8
drwxr-xr-x  2 pking users 4096 2017-02-11 17:57 ./
drwxr-xr-x 45 pking users 4096 2017-02-11 17:57 ../
$ echo "abbr --add testing sleep 1 ;and touch ~/testing/testing_auto_execute" >> ~/.config/fish/conf.d/aliases.fish
$ tail -n1 ~/.config/fish/conf.d/aliases.fish                                                                 
abbr --add testing sleep 1 ;and touch /nail/home/pking/testing/testing_auto_execute
$ fish                                                                                                                
$ ls -la testing/                         
total 8
drwxr-xr-x  2 pking users 4096 2017-02-11 17:58 ./
drwxr-xr-x 45 pking users 4096 2017-02-11 17:57 ../
-rw-r--r--  1 pking users    0 2017-02-11 17:58 testing_auto_execute
```
And here is the result of `fish -d 3` where you can see the touch command being executed
```
<3> fish: Job is constructed
<3> fish: Skipping fork: no output for internal builtin 'return'
<3> fish: Set status of return 0 to 0 using short circuit
<3> fish: Job is constructed
<3> fish: Job is constructed
<3> fish: path_get_path( 'touch' )
<2> fish: Fork #21, pid 29745: spawn external command '/usr/bin/touch' from '/nail/home/pking/.config/fish/conf.d/aliases.fish'
<3> fish: Job is constructed
<3> fish: Skipping fork: no output for internal builtin 'source'
<3> fish: Set status of and source $file to 0 using short circuit
<3> fish: Job is constructed
<3> fish: Skipping fork: buffered output for internal builtin 'string'
```

## Results
This should at the very least be documented behavior. I couldn't see this mentioned anywhere else. It would be great to figure out a fix for this, but having a look through some of the source myself I couldn't find an easy way to change this.

Cheers,
Patrick

**Comment by krader1961** [comment]
Did you look at the contents of *~/.config/fish/conf.d/aliases.fish* after you executed this statement:

```
echo "abbr --add testing sleep 1 ;and touch ~/testing/testing_auto_execute" >> ~/.config/fish/conf.d/aliases.fish
```

The problem here is that you aren't properly escaping the semicolons or quoting the string. If you had done the following (note the extra single-quotes) you wouldn't have had a problem. This has nothing to do with fish abbreviations. I would encourage you to simply edit your *aliases.fish* file rather than using `echo` where it can be difficult to get the quoting right.

```
echo "abbr --add testing 'sleep 1 ;and touch ~/testing/testing_auto_execute'" >>~/.config/fish/conf.d/aliases.fish
```

**Comment by mr-mustash** [comment]
@krader1961  That's what I am normally doing, the steps above were just too quickly illustrate what I was talking about.

I just filed this issue because I didn't see anything in the documentation about using a single quoted string for multiple commands abbreviations. I thought would be nice to have there so someone else wouldn't have to do the same investigation that I did.

**Comment by krader1961** [comment]
Sorry, but no. An abbreviation that expands to multiple commands is in general a bad idea and something only an experienced user should do. A simple function would be better in that scenario. I also don't think we should be documenting quoting rules for special characters like a semi-colon every place they might come into play. Which is pretty much every command; e.g., `set`, `string`, etc.

>  I didn't see anything in the documentation about using a single quoted string for multiple commands abbreviations.

Correct. Because we shouldn't have to document that `set var abc; echo hello` does not set `var` to `abc; echo hello` rather than setting it to `abc` and executing `echo hello`. There is no way for an individual command, like `abbr`, to tell the parser that it should treat special characters like the semi-colon as regular characters and it would be a very bad idea to do so.

**Comment by ridiculousfish** [comment]
Heh. It looks like there was an assumption that `abbr` was a syntactic thing that ate up the rest of the command line - perhaps reinforced by the inconsistent syntax of other shells. Of course `abbr` is a normal function, subject to the normal behavior of semicolons and all that.

@mr-mustash thanks for filing this. Probably it's easy to add quotes to the relevant docs. Is there a particular part of the docs that lead you astray? How did you find out about `abbr`?
