### ISSUE TITLE
Add easy parallelisation

### ISSUE THREAD

**Issue by ChrisJefferson** [fish-shell/fish-shell#3846]
I think it would be nice to have easy ability to use all my CPUs in the shell, without having to use external programs.

As a motivating example: Here's a greatly simplified example I wrote today

`for i in *.tst; echo 'Test("'$i'"));' | gap.sh -A -q ; end`

I would like some easy way of paralleising this, without external programs. I have two thoughts (these may be bad):

* `limitchildren` : Wait until there are only 4 active children.

`for i in *.tst; echo 'Test("'$i'"));' | gap.sh -A -q & ; limitchildren 4; end`

* Implement something like gnu-parallels `sem` as a builtin. This runs the program in the background, but limits the number of background programs running, by default to the number of CPUs (why not use sem from gnu-parallel? The license is horrible and it isn't available everywhere).

`for i in *.tst; echo 'Test("'$i'"));' | sem gap.sh -A -q; end`

**Comment by faho** [comment]
Between #1422, #238, #2728, we have this reported already, so I'm closing this as a duplicate.

**Comment by ChrisJefferson** [comment]
How is this duplicate?

1) I dont want wait, that's already in other shells and doesn't do this.

2) I can already use &, it works as expected.

3) is about an internal issue.

I don't mind won't fix,or go away, but I'm not sure which of those issues to take my problem to.

**Comment by faho** [comment]
Once you have

- A way to run stuff in the background

- A way to figure out what (and how much) is already running

- A way to wait for one of those things to complete

You can build your own "limitchildren".

>I can already use &, it works as expected.

Not with functions, you can't. This is a big problem if you try to background e.g. `grep`, since we ship a default wrapper function to enable color.

**Comment by krader1961** [comment]
As @faho noted the main problem is that fish tends to rely on functions quite a bit and at the moment you cannot background those. Also, this wheel has already been invented many times. I've done so myself at least once in the 1990's. It's not clear why fish needs its own implementation rather than telling people to use [GNU Parallel](https://savannah.gnu.org/projects/parallel/).

**Comment by ChrisJefferson** [comment]
@krader1961 : I can see now that backgrounded functions would help. I have three problems with GNU Parallel. (1) It's another thing to install on another machine. (2) I sometimes have trouble doing the necessary escaping on complex commands and (3) the author asked me not use it, when I questioned him placing restrictions on it's use which are incompatible with the GPL.

For me, using `&` almost does everything I want in a natural shell-like way, except I don't have any way of stopping a "process explosion" when I background too many things at once and grind my computer to a halt.

**Comment by faho** [comment]
>For me, using & almost does everything I want in a natural shell-like way, except I don't have any way of stopping a "process explosion" when I background too many things at once and grind my computer to a halt.

Here's roughly what this would look like if the linked issues were fixed:

```fish
while true
    if test (count (jobs)) -lt 5
        dostuff &
    else
        wait # to wait for _any_ job
    end
end
```

This requires that functions can be backgrounded and that there's a `wait` builtin. Otherwise it'd already work.
