### ISSUE TITLE
single-char output without a newline gets "lost"; i.e., isn't visible

### ISSUE THREAD

**Issue by giucal** [fish-shell/fish-shell#3850]
Fish version: 2.5.0  
OS: macOS  
Terminal: Terminal.app, iTerm  

With the exception of control characters, one-character outputs are swallowed during echo.

### Steps to reproduce

  - Issue a command that should print *one* non-control character. For instance, one of:

      ```sh
      echo -n x
      printf "%d" 9
      printf "%s" Y
      printf "%x" 15
      ```

### Result
Contrary to our expectations, apparently nothing is printed.

### Comment
As Kurtis Rader [noted][1] on the mailing list, `script` shows that the output is -- at least initially -- echoed.

[1]: https://sourceforge.net/p/fish/mailman/message/35664656/

**Comment by krader1961** [comment]
Note that writing two characters without a newline produces the expected result; e.g., `echo -n xy`. It is only a single character output without a newline that is not visible; e.g., `echo -n x`.

Zsh on my macOS system does the right thing in both cases so apparently fish has an off by one bug.

Thank you for reporting this, @giucal. It is definitely a bug but I am curious what caused you to notice this behavior. Especially since this problem is unlikely to be noticed by 99.9% of fish users.

Also, when you say the output is not "at least initially" echoed is incorrect. It is echoed. The problem is that the manner in which it is echoed makes that single character invisible due to how terminals display the sequence of characters written by fish.

**Comment by giucal** [comment]
@krader1961 I noticed this while debugging a script:

```sh
> script.sh invalid-cmd
> printf $status
> # I was expecting to see "2", but got naught. Bizarre!
> script.sh invalid-cmd
> echo $status
2 # Very bizarre!
```

And yes, it's actually printed. It's just that in my head "echo" meant "printing back *for the user to see*" (i.e. the result of echoing is what I end up reading on the screen). Also, I can sometimes see the character for a moment before it is replaced by the prompt (iTerm); which in retrospect agrees with your explanation.

**Comment by ridiculousfish** [comment]
Nice find. This is new. Bisects to 58347d494a7c5da3692f7fe57a95b608c0c42368

**Comment by krader1961** [comment]
The problem is that this statement

```
term_has_xn = tgetflag((char *)"xn") == 1;  // does terminal have the eat_newline_glitch
```

is returning false (zero) when the terminfo definition has that flag defined. Thus an off by one error when we use this bool to decide whether to adjust the whitespace we write by one character. What I don't understand is why that function isn't behaving correctly.

**Comment by krader1961** [comment]
Okay, the problem is that at the point we do the `tgetflag()` call we haven't yet called `setupterm()`. We do call the latter a couple of places. I've verified that adding it just before the `tgetflag()` call fixes this issue. But before I merge that fix I want to examine how we're interacting with the curses subsystem as a whole and see if some refactoring might be better.

**Comment by krader1961** [comment]
OMFG! I've been exploring the various ways that `input_init()` gets called by adding debug printfs and by calling `show_stackframe()` (which needs to be renamed). Just `grep input_init src/*` and `grep setupterm src/*` to get a feel for the madness surrounding this logic. I knew the situation was bad when I added this comment to `handle_curses()` in *src/env.cpp* to deal with dynamic changes to terminfo related env vars:

```
    // TODO: Modify input_init() to allow calling it when the terminfo env vars are dynamically
    // changed. At the present time it can be called just once. Also, we should really only do this
    // if the TERM var is set.
```

I did not realize just how fubar the existing code is until I started to refactor the code rather than add another hack by adding another call to `setupterm()`. Doing so does "fix" the problem but also makes the code logic even more difficult to understand. 

I might merge a very limited change to fix this specific issue but what really needs to happen is all the code involving initializing the curses subsystem needs to be overhauled. That is, refactored. Especially with respect to how changes to relevant env vars are handled.

**Comment by krader1961** [comment]
This took a lot more work than I anticipated. The code still needs more refactoring but I decided to stop with a delta of more than 500 lines. While fixing this specific issue I also made it possible to start an interactive shell if we can't load any terminfo definition.
