### ISSUE TITLE
source env/bin/active error

### ISSUE THREAD

**Issue by lbfreeze** [fish-shell/fish-shell#3875]
- [x] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish，version2.2.0
**OS/terminal used**:
linux
Talk about the the issue here.
when I run source env/bin/active , it has a error 
Missing end to balance this if statement
bin/activate (line 74): if [ -n "$BASH" -o -n "$ZSH_VERSION" ] ; then
## Reproduction steps
1. install python3.5 env
2. run env my_env
3. run source my_env/bin/active

## Results
```console
~ $ source my_env/bin/active
Missing end to balance this if statement
trensorflow/bin/activate (line 74): if [ -n "$BASH" -o -n "$ZSH_VERSION" ] ; then
~$ source my_env/bin/active.fish
$(...) is not supported. In fish, please use '(trensorflow)'.
trensorflow/bin/activate.fish (line 58):         if test -n "$(trensorflow) "
```

**Comment by krader1961** [comment]
Fish syntax is not 100% compatible with POSIX shells like bash. So the first error you reported is expected. Where did the *my_env/bin/active.fish* script come from? It too is obviously not a valid fish script despite its name.

Also, you checked the box saying you tested this with fish 2.5.0 but then reported that you're using version 2.2.0 which is confusing. Not that it really matters much for this issue since both versions will report the same errors when handed a bash script.

One solution that works for some people is to use [bass](https://github.com/edc/bass) to source bash scripts that only modify the current shell environment variables.

**Comment by lbfreeze** [comment]
I update my fish to 2.5.0, It has same problem, so I checked the box with 2.5.0 version

**Comment by krader1961** [comment]
> I update my fish to 2.5.0, It has same problem, so I checked the box with 2.5.0 version

Okay, that is what I suspected. We should probably remove that checkbox on the new issue template since it just causes confusion.

Again, fish is not compatible with the POSIX 1003.1 syntax recognized by bash, zsh, and similar shells. So scripts like your *my_env/bin/active* will not be executable by fish. As I said earlier most scripts of that nature can be handled by fish if you run them via the [bass](https://github.com/edc/bass) command. Alternatively do what I do and rewrite them to be compatible with fish. That is normally a trivial matter since the scripts themselves are trivial.

**Comment by lbfreeze** [comment]
thanks, but bass can not active my env ,so I go to [edc/bass](https://github.com/edc/bass) add a issue

**Comment by m-vellinga** [comment]
There is a bug in Python 3.5.2 venv that generates a fault activate.fish. See https://bugs.python.org/issue26664 as a reference.

**Comment by sae13** [comment]
```

 ✘  ~/P/app_nicico_link  source venv/bin/activate
venv/bin/activate (line 74): Missing end to balance this if statement
if [ -n "${BASH:-}" -o -n "${ZSH_VERSION:-}" ] ; then
^
from sourcing file venv/bin/activate
	called on standard input

source: Error while reading file “venv/bin/activate”
 ✘  ~/P/app_nicico_link  fish --version 
fish, version 3.0.0
 ~/P/app_nicico_link  python3 --version
Python 3.7.2


```

**Comment by faho** [comment]
@sae13: You're sourcing a bash script. Source "activate.**fish**" instead.
