### ISSUE TITLE
shell prompt not shown.

### ISSUE THREAD

**Issue by introom** [fish-shell/fish-shell#3905]
Using the fish 2.5.0

This is a weird behavior, and I just seem it recently. 
I am on macOS 10.12.   The fish shell is running inside tmux.

When I close the lid and open up it again.  (Oftentimes) The prompt is missing:
![image](http://i.imgur.com/uRfbe8n.png)

When I type clear, the prompt shows up again:
![image](http://i.imgur.com/WXXHYll.png)

I guess this might be a complication of fish+tmux.

Any suggestion on how to pinpoint the problem?

**Comment by faho** [comment]
>Any suggestion on how to pinpoint the problem?

As always, replace parts until it is working again.

- Don't use tmux

- Use a different terminal

- Use a different prompt

- What happens when you close the lid? Does the system suspend?

Also, do durians really smell that bad?

**Comment by krader1961** [comment]
I cannot reproduce this problem and I'm using fish on macOS 10.12 with or without tmux. In your first screenshot that illustrates the problem the cursor appears as an underscore in the expected position. In the second screen shot where the prompt is visible I don't see the cursor. There may be a clue in that difference. Also, fish should not be redrawing the prompt when you open your laptop. Which is a pretty strong hint the problem lies with your terminal emulator or tmux.

I tested with both Terminal.app and iTerm2.app. Fish within tmux in both terminal emulators resulted in the display being restored, the prompt visible, after closing the laptop and reopening it a few minutes later. It is likely that there is some quirk with your specific configuration that does not involve the core fish code. The first thing I would check is `echo $TERM` within the tmux window. It should absolutely not be anything like `xterm-256colors`. It should be `screen`, `tmux`, or a variation thereof. If it isn't you're incorrectly setting the value of `$TERM`.

@faho, I worked 19 months in the Asia-Pacific region with a lot of time in Singapore. The grocery stores there sealed uncut durian in multiple layers of plastic wrap to keep the smell contained. That's how obnoxious it is to some people. I've smelled a fresh durian cut in half. You couldn't pay me to eat it. It's probably like cilantro. We know that there is a gene that affects you'll like it or think it is the most awful thing on this planet to eat.

**Comment by introom** [comment]
Maybe It's not related to fish.  Actually dunno what it relates to.

How to reproduce:
Connect an extra display to the macbook ( a must).
Launch Terminal.app  in full screen mode.
Launch Tmux
Launch Fish.
Close the lid.

That behavior happens.

If you do not run tmux, that problem won't occur.
If you replace fish with bash, that problem won't occur.

**Comment by introom** [comment]
Rerun the above steps but replacing fish with zsh.  No problem occur.

**Comment by krader1961** [comment]
What is the value of `$TERM`? There might be a fish specific issue here but my experience is that this type of problem is due invalid `$TERM` values or similar problems. The fact that you have to "Connect an extra display to the macbook ( a must)" suggests that the issue very sensitive to your environment.

There may or may not be a bug in fish but it is so esoteric that I am unable to provide useful feedback.

**Comment by introom** [comment]
The term is "screen" or "screen-256color".  Haven't tested with other TERM value.

Currently I am at a loss.  I will keep this updated if I find something new.

**Comment by introom** [comment]
Checked out tmux from the master branch.

The problem is gone.  I'd assume it's some fault of tmux.
