### ISSUE TITLE
In fish, please use 'set BEFORE ﷓(

### ISSUE THREAD

**Issue by matthew-groth** [fish-shell/fish-shell#3915]
fish, version 2.5.0
OSX 10.12.3
iTerm2

I tried with `sh -c 'env HOME=$(mktemp -d) fish'` and the result was the same.

I was trying to set a variable to a command output.
```
BEFORE="$(grep -r modified .)"
```

So Fish said:
```
Unsupported use of '='. In fish, please use 'set BEFORE ﷓(grep -r modified .)'.
```

In the end I was still able to a set a variable with or without the unknown character. The quetsion mark character just threw me off for a moment so I thought I would report it here.

**Comment by krader1961** [comment]
The unexpected unicode char in that message is because when the statement is tokenized the dollar-sign is replaced with an internal token; specifically, `VARIABLE_EXPAND_SINGLE`. When it gets interpolated into the error message it is converted to `REPLACEMENT_WCHAR` (\uFFFD). This is a variation of issue #3187 and the same fix should be applied to this emitting this error message.

BTW, @matthew-groth, The fish way to write that statement is

```
set BEFORE (grep -r modified .)
```

Fish does not support the POSIX `$(subcommand)` syntax. At least not yet. We're discussing whether it should be allowed inside double-quoted strings or some other syntax used to allow interpolating subcommands in such strings.
