### ISSUE TITLE
Why I cannot unbind keys?

### ISSUE THREAD

**Issue by Chinggis6** [fish-shell/fish-shell#3923]
I cannot unbind certain keys, commands like `bind -e -k right` or `bind -e -M insert -k backspace` remove keys appearing from `bind` command's output, but has no effect, meaning they still act the same.

**Comment by krader1961** [comment]
Run `fish_key_reader` and press the key you are trying to unbind. It probably does not report a terminfo key name. Most of these behaviors are bound to multiple sequences precisely because many terminals send sequences not represented by name in the terminfo definition being used. The fkr program will tell you the sequence (or terminfo name) you need to use with the `bind` command.

**Comment by krader1961** [comment]
Also, you can do things like `bind -k Right 'echo key Right seen'`. In your case I would not expect that echo output to appear.

Given that you gave a thumbs up to my previous comment, @Chinggis6, do you have any other questions or can we close this issue?

**Comment by Chinggis6** [comment]
While `fish_key_reader` was really helpful (previously I tried `xkeybindings` for that reason which did output the key codes with `\e\`; and it succeded in helping me to unmap `Backspace`, it does not help with unmapping other keys properly such as navigational keys (up, left, etc) as they act randomly/unexpectedly/unknown after getting unmapped.

I'd like to completely unmap navigational/paging keys so they have absolutely no action in the shell. I'm not sure if I should do it in URxvt terminal too/instead.

**Comment by krader1961** [comment]
By any chance are you using vi mode? If yes then unbinding those keys will definitely cause erratic behavior because the escape prefix sent by most keys will switch from insert to normal mode. Then the rest of the sequence is treated as a vi normal mode command.

In any event it is better bind the key so it is a nop; e.g., `bind -k right true`.

**Comment by Chinggis6** [comment]
Oh, I think now I can understand it (yes I use `vi` mode), but still `bind -k right true` doesn't work for me. It still acts the same going one character forward.

**Comment by krader1961** [comment]
If `fish_key_reader` doesn't say `bind -k right 'do something'` when you press [right-arrow] then that binding won't have any effect. You have to bind whatever fkr reports. Also, if you type `bind | grep forward-char` you'll see all the bindings in effect that invoke that operation. Note that vi key bindings have multiple modes. So to keep [right-arrow] from doing anything in vi insert mode you need to `bind -M insert -k right true` (assuming fkr says that `right` is the key name). If you omit the `-M` flag it's the same as `-M default` (which is vi normal/command mode).

**Comment by Chinggis6** [comment]
It reported `\e\[D` for me, for the `Left` key, and binding it to `true` had indeed (no) effect as desired. I already know about the modal scope of key bindings in `vi` mode, as I noted on my first post. Thanks for helping so far. My issue is solved :)
