### ISSUE TITLE
sudo commands in a pipeline are fully buffered

### ISSUE THREAD

**Issue by bacondropped** [fish-shell/fish-shell#3927]
When running a sudo command in a pipeline, its output is fully buffered, making fish crash with bad_alloc if the output is large.

How to reproduce: `sudo cat /dev/urandom | head -c1T | wc -c` (assuming your machine can't hold a terabyte of data in memory).

Expected behavior: fish creates a pipe with a reasonable buffer.

What happens instead: fish tries to buffer whole output of `cat`, eats all available memory, and dies. `head` is never launched.

Non-sudo commands are buffered fine, and as such this behavior doesn't happen.

Probably related to #3702 and #1040.

***
fish: `version 2.5.0`
TERM: `tmux`
tmux: 2.3
terminal:
```
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
```

**Comment by faho** [comment]
This is a duplicate of #1396.

**Comment by faho** [comment]
Nope, sorry, it actually _isn't_, since there is no function involved here!

**Comment by faho** [comment]
However, #3702 is essentially the same thing, and like @krader1961 and @ridiculousfish stated there, I can't see us being of much assistance here - if the command you are calling wants to buffer, it's gonna buffer. Fish doesn't in this case (though it does for its own functions, which is rather annoying).

In my case nothing here does, actually, but it very well _could_. Try running `tail -c1T </dev/urandom`, in any shell.

Sorry!

**Comment by bacondropped** [comment]
This doesn't happen with any other shell for the exact same command. What makes the difference?

**Comment by faho** [comment]
>What makes the difference?

Let's find out! AFAIK other shells don't all mess with pipe buffers, so let's rule that out for the moment.

There's a variety of things that might have an effect here. The first thing I'd check is whether a function is involved - `type -t sudo cat head wc` should print "file" four times, otherwise it's #1396 like I originally assumed.

The second thing to check is whether `sudo` is trying to prompt for the password - then it could be a manifestation of #206.

Then I'd also like the software versions of the involved programs and your operating system.

Then you could also `strace` the involved commands and fish.

**Comment by bacondropped** [comment]
> The first thing I'd check is whether a function is involved

Bullseye, thanks! I forgot I aliased `sudo` to `sudo -E`. Guess I'll use a stub sudo script instead.

**Comment by krader1961** [comment]
@bacondropped: Your situation is a great example where an abbreviation is better: `abbr sudo 'sudo -E'`.
