### ISSUE TITLE
pushd calls "cd", should perhaps call "builtin cd"?

### ISSUE THREAD

**Issue by favdish** [fish-shell/fish-shell#3931]
fish 2.5.0/MX-16/64

I have a long-standing bash function called cd (to change directories) that does all sorts of things the OOTB cd doesn't do. This function, after translation to fish, calls pushd to change directories and, by doing so, transports me into a sort of recursive hell: pushd calls cd which is my function which calls pushd which calls cd which is my function which calls...

I have, as a stopgap measure, changed /usr/share/fish/functions/pushd.fish such that it calls "builtin cd" instead of plain "cd" thus breaking the recursion. Being new to fish I do not know into what other sort of hell this might transport me so any hint how to resolve this matter w/o resorting to editing /usr/share/fish/functions/pushd.fish is welcome (I could copy the pushd code into my config.fish and edit in place but this seems not the best solution). And perhaps pushd should in a future version call the builtin directly?

**Comment by krader1961** [comment]
A couple of observations. First, there are exceptions but in general `builtin` and `command` should be limited to a function with the same name as the builtin or external command to be run. Using those modifiers in other functions can cause problems by not letting the command be overridden by a function of the same name.

Second, it's a really bad idea to call a "higher" abstraction level command from a "lower" level command when the two form a natural hierarchy. In this case `pushd` is the higher level abstraction that naturally needs to call `cd`. It's a layering violation for `cd` to call something like `pushd` or `prevd`. I'm curious why you've implemented `cd` in terms of `pushd` rather than just use the latter? If it's to save typing a couple more characters why not create a new command, perhaps named `pd`, or an abbreviation?

If we were to modify `pushd` (and presumably `popd` would need the same mod) we would need to do the `builtin cd` conditionally based on whether `cd` appears higher in the call stack. The `status print-stack-trace` command could be used but its output is really meant for human consumption. We'd want something more amenable to manipulation by a script to ensure the solution is robust.

P.S., Until a more satisfactory solution is found it would be safer for you to `cp /usr/share/fish/functions/pushd.fish ~/.config/fish/functions` and edit the latter. That way when you update your fish installation your local customization won't be overwritten.

**Comment by krader1961** [comment]
> I probably should have kept shtum....

Not at all. It's situations like yours which drive many of the improvements to fish. If someone doesn't ask for a change it won't happen.

> incidentally, the bash version of my cd code had no such trouble

That's because `pushd` is a builtin in bash and it explicitly calls `cd_builtin()`. Whether or not the fish `pushd` function should (possibly conditionally) call `builtin cd` is still open for debate.

**Comment by krader1961** [comment]
Also, there is nothing stopping you from interacting with `pushd`/`popd` in your `cd` wrapper by manipulating the global `dirstack` variable. That is essentially what the core `cd` function does to safely interact with the `prevd`/`nextd` commands. Having said that I am still willing to implement a change to the core fish code that makes your situation "just work".

What I think we need to understand is why you expect `cd /some/place` to automatically play nice with `pushd` and `popd` and what those semantics should be.

**Comment by favdish** [comment]
> Also, there is nothing stopping you from interacting with pushd/popd in your cd wrapper by manipulating the global dirstack variable.

Actually, doing this was my first impulse. However, I thought (and think) that dirstack is an implementation feature and I am not overly happy to fiddle with something internal behind the back of its "official" interface, ie the (push/pop)d functions. Perhaps the best way forward is to leave the cd call inside those functions as it is but give both functions an additional switch which adds/removes+returns a directory to/from dirstack without actually cd'ing into it. Ie something like

`pushd --nocd /home/user/my/stuff/is/here `

Then I can push the directory in a transparent way and afterwards call the builtin cd myself.

I don't mind one way or the other... new releases of fish are not that frequent and I am in the habit of patching other Open Source packages I use to extend or adapt them, so doing this is a minor hassle.

**Comment by krader1961** [comment]
> I thought (and think) that dirstack is an implementation feature and I am not overly happy to fiddle with something internal behind the back of its "official" interface, ie the (push/pop)d functions.

Fair enough but the fact that you've implemented your own `cd` function means that you are fiddling with (breaking) the interaction with `prevd`/`nextd` unless you've copied that implementation detail. There really isn't any safe way to override the fish `cd` function that doesn't risk breaking something. For example, are you aware that one of the primary reasons this function exists is to support `cd -` since that is not supported by the builtin and said support involves interacting with the prevd/nextd mechanism?

I'm going to leave this open to see if anyone else has an opinion. But at this point I'm leaning towards "caveat emptor" for anyone defining their own `cd` function. You're really better off giving your custom function a different name.

**Comment by favdish** [comment]
> For example, are you aware that one of the primary reasons this function exists is to support cd - since that is not supported by the builtin and said support involves interacting with the prevd/nextd mechanism?

Yes I am. My cd function completely replaces the extended features of the builtin cd function and handles cd - (and many other things like cd ...[....] to move up one [or more] directory levels) on its own. It only calls the builtins cd, pushd and popd. It will probably not support prevd/nextd as it is but I do not use those ATM and if I started using them, I'd adapt my cd function as I have done many times in the past.

As to the name "cd"... that's not gonna change for the reasons I outlined above. I am spending 95% of my time in the shell (both in Windows and Linux) and so I have optimised and automated them as much as I possibly can.

**Comment by krader1961** [comment]
> My cd function completely replaces the extended features of the builtin cd function and handles cd -...

No, it does not, as evidenced by this issue. If it did so it would not be calling the `pushd` command which happens to be a function in fish that invokes the `cd` command. Rather than a builtin that invokes the `cd` builtin as in bash. This issue appears to be primarily due to your reliance on `cd` and `pushd` both being builtins in bash if the user has not defined functions by those names. Which itself is unsafe since either of those commands could be defined as a function in bash.

> It only calls the builtins cd, pushd and popd.

Bingo! You are assuming that `pushd` and `popd` are builtins. Which isn't even a safe assumption in bash. Although it is true that the bash builtin `cd` command will only invoke the builtin `pushd` command even if a `pushd` function exists. Which itself is yet another reason to favor fish over bash since functions are generally first class objects in fish which means you can, in general, modify the behavior of builtins by wrapping them in a function.

**Comment by krader1961** [comment]
Closing since no one has explained why modifying the `pushd` function to use `builtin cd`, or some other solution to this problem, makes more sense than the current behavior. If someone has a proposal for how to make it safer to override our `cd` function I would encourage you to open a new issue, that references this one, that explains how to do so.
