### ISSUE TITLE
Control characters in completions can lead to an assert

### ISSUE THREAD

**Issue by HuwCampbell** [fish-shell/fish-shell#3938]
fish 2.5.0

Running this completions script (with tab characters between testc* and the word Test)
```fish
function _optbroken
    for opt in 'testc1  Test this package, but process control chars \b
testc2  Test this package, but process control chars
testc3  Test this package, but process control chars
testc4  Test this package, but process control chars
testc5  Test this package, but process control chars'
      echo -e "$opt"
    end
end
 
complete --exclusive --command optbroken --arguments "(_optbroken)"
```
Gives
```
optbroken testcAssertion failed: (desc_remaining >= 2), function completion_print_item, file src/pager.cpp, line 161.
```
when pressing tab. Causing fish to crash completely.

The offending part is the backspace character '\b', which appears to mess up the pager.

**Comment by krader1961** [comment]
That failure is clearly a bug since assertions should never be triggered in normal use.

However, what caused you to notice this? Your `for opt in 'testc1`... loop will execute exactly once. It is thus either irrelevant or symptomatic of a deeper bug in the completion that you distilled that example from. It might be helpful to understand more about the actual scenario that caused you to open this issue.

P.S., I was tempted to label this an enhancement. By definition the `--arguments` values are supposed to be comprised of visible characters. And backspace (`\b`) is not. Nonetheless, fish should be defensive and safely handle unexpected input in this situation without crashing.

**Comment by HuwCampbell** [comment]
You are right, it can be shortened to just the `echo -e`. I was however distilling as you say.

I found this assertion as there was a "\b" written in the help documentation for a program I was using the optparse completion script for, and that was coming through and crashing fish.

**Comment by mqudsi** [comment]
I was able to reproduce this under 2.5.0 but it does not reproduce under master any longer. 

In the current fish code, a raw `\b` in the description text emitted by the completion argument function causes the description to not be displayed but does not crash the shell.
