### ISSUE TITLE
Alternate autocomplete behavior

### ISSUE THREAD

**Issue by MatthewScholefield** [fish-shell/fish-shell#3940]
As a new fish user, autocomplete never made much sense to me because hitting tab wouldn't follow the suggestion. Naturally, I would expect the suggestion to show what would happen if I press tab. However, this is actually done with what I find to be a rather inaccessible key combo, `Alt+Right`. Wouldn't it make sense to either change the default autocomplete key combo to something like `Shift+Tab` (very similar to `Tab`) or make the default autocomplete only show what tab will do?

**Comment by faho** [comment]
First of all, it's not "autocomplete". It's an "autosuggestion".

Which is important since that states the main difference between completion (what happens when you press tab) and the greyed-out thing _in_ the commandline. The latter is a "suggestion", that is purely speculative. For instance, on my machine right now I enter `p`, and the suggestion shows `pacman -Syu`. That would _certainly_ not be unique (tab completion shows I have about 240 commands starting with "p"), but as it happens, that's just what I want now.

So: No, we will not just use this to display the first completion. That would be defeating the point.

>However, this is actually done with what I find to be a rather inaccessible key combo, Alt+Right. Wouldn't it make sense to either change the default autocomplete key combo to something like Shift+Tab (very similar to Tab) or make the default autocomplete only show what tab will do?

"Alt+F" is bound to "nextd-or-forward-word". The suggestion is accepted by any movement that goes over it. As a special case, the "forward-char" movement accepts all of it, every other movement (IIRC) accepts only the part it moves over.

If you wish to bind this to something else, you can either rebind these movements (see `bind --help` for a list) or the special "accept-autosuggestion" input function, which will accept the suggestion and move the cursor after it if there is one, or not move the cursor if there isn't.

**Comment by MatthewScholefield** [comment]
Ok, thanks, I will indeed try changing the key binding. And I do understand that fish gives a best guess, not a unique completion. However, I still find myself expecting tab to accept the auto suggestion. I do get that many love having the autosuggestions. But, I also think it can be confusing for new users and should at least be configurable.

**Comment by krader1961** [comment]
FWIW, When I switched to fish I found autosuggestions confusing and wanted a way to disable them. Primarily because no shell I had used up to that point (zsh, ksh, others) had such a feature. But after a few weeks I not only got used to the feature I found myself depending on it to provide a good suggestion for the command I likely want to run.

> ... and should at least be configurable.

And it is configurable, as faho pointed out. Suggestions on how to better document this are welcome.
