### ISSUE TITLE
Weird character displayed in the console

### ISSUE THREAD

**Issue by mazzy89** [fish-shell/fish-shell#3942]
fish 2.5.0

![screen shot 2017-04-07 at 14 18 23](https://cloud.githubusercontent.com/assets/5463218/24799718/1872180c-1b9d-11e7-867a-15f4dac219ba.png)

Do you know what is that character on the left? It appeared when I updated to 2.5.0

**Comment by faho** [comment]
That's the vi mode-indicator. It means you are using vi-mode, and are currently in insert-mode. Press escape and notice it will turn into an "N".

To change it, change the `fish_mode_prompt` function. To disable it, define an empty `fish_mode_prompt` function.

If you didn't know that you where using vi-mode, it's most likely because some third-party plugin (sometimes even prompt!) enabled it for you. To disable it, remove whatever is enabling it (look for `fish_vi_key_bindings`) and run `fish_default_key_bindings`.

**Comment by mazzy89** [comment]
Super fast and clear explanation. Thank you ;-)

**Comment by faho** [comment]
No problem. I'm guessing this is answered, then. 😺 

Also, if you figure out whatever plugin/prompt/whatever is causing this and you don't want it to, you should open an issue with the authors of that.
