### ISSUE TITLE
Expand character escapes in double strings

### ISSUE THREAD

**Issue by Soares** [fish-shell/fish-shell#396]
Let's say you only have single quotes and you want a variable in a quoted string. You obviously can't do this:

    > echo 'Here is my $variable in a string.'
    Here is my $variable in a string.

But with a little cunning, you can work around the problem:

    > set variable expansion
    > echo 'Here is my '$variable' in a string.'
    Here is my expansion in a string.

Huzzah. That's pretty simple, and perhaps fish should have left things there. However, this pattern was deemed so common and so annoying that double quotes were introduced as sugar for this particular case. Now you can do:

    > echo "Here is my $variable in a string."
    Here is my expansion in a string.

Nice! Now, let's look at a very similar case: character escapes. We all know that fish expands character escapes and that single quotes preserve them:

    > echo \n

    > echo '\n'
    \n

So if you want an escape in your quoted string, you can't:

    > echo 'Line 1.\nLine 2.'
    Line 1.\nLine 2.

You can, of course, use the same old trick:

    > echo 'Line 1.'\n'Line 2.'
    Line 1.
    Line 2.

But, as before, that's annoying. Double quotes to the rescue! Right?

    > echo "Line 1.\nLine 2."
    Line 1.\nLine 2.

Wrong.

Right now, double quotes are sugar for one very specific use. I posit that double quotes don't do enough right now to justify their existence. They save only two characters of typing (`"some $var expanded"` vs `'some '$var' expanded'`). If it's worth introducing a new syntax to sugar up that pattern for variables then shouldn't it be worth the same sugar for the same pattern for character expansions?

**Comment by alphapapa** [comment]
I'm confused.  If you use `echo -e` then your example works fine:
```fish
➤ echo -e "Line 1.\nLine 2."
Line 1.
Line 2.
```
```fish
➤ echo --help | grep -- -e
       · -e, Enable interpretation of backslash escapes
       If -e is used, the following sequences are recognized:
       echo -e 'Top\nBottom'
```

**Comment by faho** [comment]
>I'm confused. If you use echo -e then your example works fine:

I presume the "echo" is a standin - with "-e" it works, but only because that processes the escape sequence. Plenty of commands don't do that (think of `rm`), so the wish is for something to do this interpretation within some kind of quotes.

Let me first get something out of the way:

>I posit that double quotes don't do enough right now to justify their existence. They save only two characters of typing

They do something a lot more important.

```fish
set -l alist flounder catfish
printf "%s\n" $alist
printf "%s\n" "$alist"
```

while for the first argument ("%s\n") it doesn't matter which quoting style you pick, for the second it changes to how many arguments the list will be expanded - an unquoted list of n elements (including 1 or 0) will be expanded to n arguments. A double-quoted list will always be expanded to one argument.

>If it's worth introducing a new syntax to sugar up that pattern for variables then shouldn't it be worth the same sugar for the same pattern for character expansions?

The possibilities I see here is to either introduce a new way of quoting or reuse an old one (i.e. double-quoting).

The problem with a new way of quoting is that you then have to pick it before you reach the offending character, or move back - both of which are actually _more_ work than typing `"\n"` or `'\n'`. Bash has this as [ANSI-C Quoting](https://www.gnu.org/software/bash/manual/bashref.html#ANSI_002dC-Quoting), the form being `$'string'`, not to be confused with `$"string"`, which causes [locale-specific translation](https://www.gnu.org/software/bash/manual/bashref.html#Locale-Translation). It also violates our "Law Of Orthogonality".

Re-using the old way will break existing code and make it harder to type other things in turn.

Because of that and because how old this is without any activity, I'm now closing this.

**Comment by ElijahLynn** [comment]
@Soares Thanks for posting this, you helped me at least realize how to do a variable expansion inside single quotes. This is one of the top results in a search!
