### ISSUE TITLE
Should have the ability to add extra directories to 'fish_function_path'

### ISSUE THREAD

**Issue by jpopadak** [fish-shell/fish-shell#3968]
Version: 2.5.0

Darwin <hostname> 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

ITerm2 Build 3.1.20170410-nightly - xterm-256color

1. Open up a terminal session
2. Type `set tmp_path $fish_function_path`
3. Type `set -e -g fish_function_path`
4. Type `set -U fish_function_path $tmp_path`
5. Create a new terminal session
6. Type `echo $fish_function_path`
7. Note how the variable `fish_function_path` is reset

**Comment by faho** [comment]
This actually works for me, and our [share/config.fish](https://github.com/fish-shell/fish-shell/blob/c0d80ab99628cd893ca825b13352a6c60a0baa05/share/config.fish#L93-L95) sets $fish_function_path like this:

```fish
if not set -q fish_function_path
    set fish_function_path $configdir/fish/functions $__fish_sysconfdir/functions $__extra_functionsdir $__fish_datadir/functions
end
```

There haven't been any pertinent changes to it since 2.5.0, so that can't be it.

Are you using any third-party "frameworks" or plugin-thingies like oh-my-fish or fisherman?

**Comment by krader1961** [comment]
I tested this on macOS 10.12 with fish built from git head and your directions work for me. I even changed it to `set -U $fish_function_path /tmp` to verify the uvar really is being honored by the new shell. Can you clarify what you mean by "the variable fish_function_path is reset"? Like @faho I suspect you've got some personal customization that is causing the problem. You should `grep fish_function_path ~/.config/fish/**` to see if it is referenced.

P.S., Making fish_function_path a uvar seems like a bad idea because it's likely to cause problems.

**Comment by jpopadak** [comment]
I am not using any third party frameworks.

I was actually trying this originally as `fish -c "<COMMANDS HERE>"` through a HomeBrew `install` script. I even debugged into where the issue was occurring into the shell and was not able to get it to set the value.

**Comment by faho** [comment]
>I was actually trying this originally as fish -c "<COMMANDS HERE>" through a HomeBrew install script.

I'm unfamiliar with HomeBrew. Does that run as another user? That would explain it, since universal variables are per-user.

**Comment by krader1961** [comment]
By "install script" do you mean that you ran "brew edit $pkg" to edit the formula for installing $pkg? Or, are you creating a brew package that others will install? And by the mere act of installing the package have it create a `fish_function_path` uvar? That should work but is dangerous and obnoxious. It's dangerous because different versions of fish may have different defaults for `fish_function_path` and making it a static uvar is likely to break things.

**Comment by jpopadak** [comment]
@krader1961  Yes, the brew edit commands using back ticks to execute commands.

I can type `brew irb` and execute `fish -c "<cmd>"` commands there. But nothing seems to be persisted to any other session I open in ITerm2.

I also attempted `fish_user_paths` to get around the `fish_function_path`. It did not work. I am really just trying to get a good easy way to share scripts with team members with brew.  It might just be better to go the route of using Oh My Fish to do this.

**Comment by faho** [comment]
>I also attempted fish_user_paths to get around the fish_function_path. It did not work.

Again, if that is executed as a separate user (which I suspect) universal variables won't work. Also, $fish_user_paths is only used for _command_ lookup, not functions.

>It might just be better to go the route of using Oh My Fish to do this.

I'm actually not sure what OMF would improve here.

----

I wouldn't use universal variables for this, at all. Like @krader1961 said this might cause issues - IIRC brew installs fish into a versioned directory, which makes the function path also versioned. If you make f_f_p universal, old running fishes will then pick up the new directory and go bonkers, or new fishes will keep the old one and probably run, but worse than they could.

What I would do (assuming I'm understanding you correctly and you have the functions on some form of shared drive - otherwise why not just install them?) would be to add a conf.d snippet - make a file called e.g. "jpopadak_functions.fish" (the .fish is important) to be installed in /etc/fish/conf.d/ or $__fish_datadir/vendor_conf.d (`pkg-config fish --variable confdir`, usually /usr/share/fish/vendor_conf.d), via your custom fish package or an additional one that sets up fish_function_path, globally.

That way it's all nicely tracked in the package, and anyone who wants to opt out can override the snippet (make a file with the same name in ~/.config/fish/conf.d)

**Comment by krader1961** [comment]
For those trying to follow along running `brew irb` is an obscure feature of the Homebrew macOS package manager. It puts you into an interactive Ruby shell environment from which a knowledgable person can perform magic. I had no problem doing what the O.P. implies they are doing:

```
$ brew irb
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
irb(main):001:0> `fish -c 'set -U wtf hello'`
=> ""
```

I then opened a new terminal with fish as my login shell was was able to confirm that the uvar was set:

```
$ set -U | grep wtf
wtf hello
```

I then verified that my environment did not have `fish_function_path` as a uvar and ran this:

```
$ brew irb
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
irb(main):001:0> `fish -c 'set tmp_path $fish_function_path; set -e -g fish_function_path; set -U fish_function_path /WTF $tmp_path'`
=> ""
irb(main):002:0> ^D
```

I then opened a new terminal window and ran the following to confirm the change had been preserved as a uvar:

```
$ set -U | grep fish_function_path
fish_function_path '/WTF'  '/Users/krader/.config/fish/functions'  '/usr/local/etc/fis'…
```

@jpopadak: This seems to be working as expected. But as both @faho and I have said you really do not want to do it this way as it is going to cause problems. Maybe not today but it will cause problems. Consider what happens if someone like yourself builds and attempts to run a fish with a different `./configure --prefix=...` value.

The solution @faho described in his previous comment may be overkill for your situation. Regardless, you definitely do not want to solve your problem by making `fish_function_path` a universal variable.

**Comment by jpopadak** [comment]
Thanks for the suggestions everyone. The reasoning we didn't want them in a shared drive is (1) so we can continuously update them, and (2) we have a secure environment which no shared locations are allowed on the network. Everything must go through an https protocol.
