### ISSUE TITLE
Switch to Python 3

### ISSUE THREAD

**Issue by paride** [fish-shell/fish-shell#3970]
On newer systems (e.g., Debian stretch) no Python 2 flavor is installed by default, only Python 3 is. This means that the three Python scripts
```
/usr/share/fish/tools/deroff.py
/usr/share/fish/tools/create_manpage_completions.py
/usr/share/fish/tools/web_config/webconfig.py
```
fail to run, as the shebang looks for `python` and not for `python3`. I think it's time to switch to python3. It has to be noted that https://www.python.org/dev/peps/pep-0394/ recommends that the `python` binary (or symlink) refer to some version of Python 2.x, and never to Python 3.x.

If the scripts support both Python 2 and 3, a trick like http://stackoverflow.com/a/26056481 could be used.

I'm running fish 2.5.0-314-g7c66008.

**Comment by faho** [comment]
>If the scripts support both Python 2 and 3

Yes, they do.

> a trick like http://stackoverflow.com/a/26056481 could be used.

Wow, that's amazing! Unfortunately, I don't think we want to rely on /bin/sh here and this won't work with fish script since IIUC we scan the entire file before execution (there'll be an invalid command name as soon as you have a `function()` call without a space between the function name and the parentheses). Also, it is a bit hacky.

What we should do (and already do in __fish_config_interactive) is to change the fish functions that call these thing. You're not expected to call these directly anyway, since they need a bit of setup.

Of these, deroff is basically a library and only ever imported, so it doesn't need a change.
