### ISSUE TITLE
Can't see start message

### ISSUE THREAD

**Issue by m-nagae** [fish-shell/fish-shell#3973]
fish, version 2.5.0

iTerm2 Build 3.0.15
macOS Sierra 10.12.4

Darwin 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

xterm-256color

I always can't see this message when start fish.

> Welcome to fish, the friendly interactive shell
> Type help for instructions on how to use fish

**Comment by faho** [comment]
What do you mean by "always"? Under what circumstances can you or can't you see it?

This should be printed

- When fish is interactive
- Right before the first prompt

Is it just totally random?

**Comment by krader1961** [comment]
You'll only see that message for interactive shells and only if you have not defined a `fish_greeting` function or variable. What does `functions fish_greeting` and `set | grep fish_greeting` output? What about `status --is-interactive; and echo yes`?

**Comment by m-nagae** [comment]
@krader1961 

Thanks.
I tried that.

 ```
~/.c/fish> set | grep fish_greeting
fish_greeting
```

I found `SET fish_greeting:\x1d` in `~/.config/fish/fishd.784f43956bac`.
But I haven't set it. Is this default value?

**Comment by faho** [comment]
>But I haven't set it. Is this default value?

No. That's the equivalent of `set -U fish_greeting` (i.e. an empty list), btw.

Are you using any third-party plugins or frameworks like oh-my-fish or fisherman? Any prompts or functions or themes you've downloaded from somewhere else?

**Comment by krader1961** [comment]
If you simply want to see the default greeting just run `set -e fish_greeting`.

**Comment by m-nagae** [comment]
> No. That's the equivalent of set -U fish_greeting (i.e. an empty list), btw.

I see.

> Are you using any third-party plugins or frameworks like oh-my-fish or fisherman? Any prompts or functions or themes you've downloaded from somewhere else?

Yes. I using fisherman and these plugins.
```
$ fisher ls
agnoster		brew			cask			docker-completion	getopts			peco			spin
```

**Comment by krader1961** [comment]
Neither of those plugins is likely to be the cause. It is more likely that sometime in the past you ran `set -U fish_greeting`; perhaps as an experiment. If you don't want to see the greeting you don't need to do anything. If you do want to see the greeting just type `set -e fish_greeting`. Does that answer your question?

**Comment by m-nagae** [comment]
> If you simply want to see the default greeting just run set -e fish_greeting.

I did it. But I can't see it. Hmm...

```
$ set -e fish_greeting
$ fish
$
```

**Comment by m-nagae** [comment]
> It is more likely that sometime in the past you ran set -U fish_greeting; 

I didn't it. Because I install the fish to clean installed a MacBook Pro a while ago.

**Comment by krader1961** [comment]
Thanks for working with us, @m-nagae, by answering our questions. I now see the problem. The *__fish_config_interactive.fish* has a subtle bug introduced 2016-09-10, seven months ago, by commit 90e535f66. The problem is that a `set -l` is being done inside a `if... else... end` block. But the value is being used outside that block. However the "local" set means the value won't be visible outside that block.

No one has noticed this before now because most of us explicitly disable the greeting. Thanks for bringing this to our attention. I'll fix it for the 2.6.0 release.

**Comment by krader1961** [comment]
Also, the reason you end up with a `fish_greeting` uvar that has no value is due to how fish evaluates `set -U fish_greeting $line1$line2` when `$line1` has a value and `$line2` does not. Which is true due to the bug I referred to in my previous comment. In that case the composite value is the empty set due to how cartesian products work.

**Comment by m-nagae** [comment]
I see. Thank you for helping me!

I have one more things to worry about.
Fish disabled syntax highlighting by default.
Should I add an issue about it?
<img width="93" alt="does-not-work-highlighting" src="https://cloud.githubusercontent.com/assets/1877680/25261560/5e9e0d18-268d-11e7-920a-a5c9a4d44774.png">

**Comment by krader1961** [comment]
> Should I add an issue about it?

Yes, open a new issue since it is unrelated to this issue. Note, however, that I cannot tell what the problem is from the information in your last comment. What exactly do you expect to happen if you type `fish` at a fish prompt? When I do that the command is shown in the color red until I type the final `h` which makes it a valid command. There isn't any syntax to be highlighted in that simple example. Only whether the token looks like a valid command name or not.
