### ISSUE TITLE
Can't reproduce tab completion using __fish_complete_subcommand like sudo

### ISSUE THREAD

**Issue by Kuroko-Komeiji** [fish-shell/fish-shell#3977]
Hello, 
   I am using fish version 2.5.0, and I want to write a completion file for proxychains4.
   Its usage:
         proxychains4 -q -f config_file program_name [arguments]
        -q makes proxychains quiet - this overrides the config setting
        -f allows one to manually specify a configfile to use

  So I tried to write a completion file for it at **~/.config/fish/completions/proxychains4.fish**
``` fish
complete -c proxychains4 -s f -r -d "Configure File"
complete -c proxychains4 -s q -d "Quiet Mode"
complete -c proxychains4 -d "Command to run" -x -a "(__fish_complete_subcommand -u -g)"
```
Problem is  when I enter 

**proxychains4 -q -f ./proxychains.config w**\<*Press Tab*\>      --->  expect to show whereis, which, wget, etc.

there is no any completion and terminal bells. 

Another problem is when I enter 

**proxychains4 -q -f ./proxychains.config wget -**\<*Press Tab*\>  ---> expect to show options for wget

But it is 
```
-f  (Configure File)  -q  (Quiet Mode)    ---> Custom completion
```

So I try to write a command called sudo2 to imitate sudo.

**~/.config/fish/completions/sudo2.fish**

``` fish
complete -c sudo2 -s c -a "(__fish_complete_users)" -x -d "Run command as user"
complete -c sudo2 -d "Command to run" -x -a "(__fish_complete_subcommand_root -u -g)"
```

(Just copy from /usr/share/fish/completions/sudo.fish)

I put a executable empty file sudo2 in PATH, then

**sudo2 -c** \<*Press Tab*\>   --> OK show completion of users.

**sudo -c root wget -**\<*Press Tab*\>   --> expect to show options for wget

But it is 
```
-u      (Run command as user)  -config          (Print ./configure options)
```
completions of command `root`. 

But strange thing  is when I change **~/.config/fish/completions/sudo2.fish** to ( option become **u** as sudo)
```fish
complete -c sudo2 -s u -a "(__fish_complete_users)" -x -d "Run command as user"
complete -c sudo2 -d "Command to run" -x -a "(__fish_complete_subcommand_root -u -g)"
```

Enter: 
**sudo -u root wget -**\<*Press Tab*\>     ---> OK show option of wget

So why it happens? 
1. Is completion working or not decided by option letter? 
2. How to  write a completion like sudo ( With option, and final paramater completion is other program)  correctly ?

**Comment by faho** [comment]
So.... `__fish_complete_subcommand` is a bit weird and should be documented better.

It takes some arguments. These are either `--fcs-skip=X`, which means the first X tokens (including the command itself) are skipped, or options that the original command ("sudo" in this case) takes that take arguments that are supposed to be skipped.

So the `sudo` completion invokes it as `__fish_complete_subcommand_root -u -g` (the "root" thing here is just a wrapper that adds /sbin and such to $PATH), because sudo's `-u` and `-g` options take arguments.

>sudo2 -c <Press Tab> --> OK show completion of users.

`sudo` doesn't have a "-c" option that does this (mine has a "-c" option that apparently takes a "class" but otherwise it is completely undocumented).

However, if it did, it would have to be added to 

    complete -c sudo2 -d "Command to run" -x -a "(__fish_complete_subcommand_root -u -g)"

i.e. `__fish_complete_subcommand_root -u -g -c`

That means since it appears your "proxychains4" command has one option that takes an argument (the "-f") you should pass that option to __f_c_s like this:

```fish
complete -c proxychains4 -s f -r -d "Configure File"
complete -c proxychains4 -s q -d "Quiet Mode"
complete -c proxychains4 -d "Command to run" -x -a "(__fish_complete_subcommand -f)"
```

**Comment by krader1961** [comment]
Closing since this since it has been a month since the last update. So I'm going to assume the provided answer was satisfactory. Feel free to reopen this, @Kuroko-Komeiji, if we haven't adequately answered your question.
