### ISSUE TITLE
Additional subsections in command help pages break man translation

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#3987]
In 5b6814d6ad3ee787e0c87e08e0dfaaffb296b0ca, @krader1961 changed the `string` help page to have one subsection per subcommand (which is a good idea).

Unfortunately, while this looks good in the html output, the man translation doesn't seem to work. `nroff` strips the subsection _content_, so the output looks like

```
   'length' subcommand
   'sub' subcommand
   'split' subcommand
   'join' subcommand
   'trim' subcommand
   'escape' subcommand
   'match' subcommand
       If you specify the -f or --filter then each matching string is printed including any prefix or suffix not matched by the pattern (equivalent
       to grep without the -o flag). You can, obviously, achieve the same result by prepending and appending * or .* depending on whether or not you
       have specified the --regex flag. The --filter flag is simply a way to avoid having to complicate the pattern in that fashion and make the
       intent of the string match clearer.
```

The source looks like

```
.SS "'length' subcommand"
'`string length`' reports the length of each string argument in characters\&. Exit status: 0 if at least one non-empty STRING was given, or 1 otherwise\&.
.SS "'sub' subcommand"
```

nroff is from GNU groff 1.22.3, doxygen is 1.8.13.

@MarkGriffiths: Any input?

**Comment by krader1961** [comment]
I had only glanced at the man output after first making the "match" subcommand a subsection and failed to notice that the entire first paragraph of that subsection was missing. I then converted all the other subcommands to subsections and checked the html without checking the man page again.

The problem is caused by quoting the first two words of each subsection (e.g., `"string length" reports the length...`). Removing the quotes fixes it. The rules for how quoting and escapes work in our raw documentation is too complex for a mere human to understand.
