### ISSUE TITLE
On Cygwin, if the prompt contain a character greater then U+00FF, pressing tab moves the cursor left

### ISSUE THREAD

**Issue by rgiordani** [fish-shell/fish-shell#4005]
fish version : 2.5.0
kernel name : CYGWIN_NT-6.1
kernel release : 2.8.0(0.309/5/3)
kernel version : 2017-04-01 20:47
machine hardware name : x86_64
term: xterm-256color (mintty)

My terminal uses CP1252 encoding. My fish prompt contain the character "›" (U+203A SINGLE RIGHT-POINTING ANGLE QUOTATION MARK).

If I press the TAB key, and there are more than one possible completion, the cursor moves left of one position. After this, what I digit is out of sync with what I see.

I found that the problem disappears if the prompt doesn't contains character with code greater than U+00FF. With n such characters the cursor moves left of n positions.

**Comment by krader1961** [comment]
What does `locale` output? Note that (CP1252)[https://en.wikipedia.org/wiki/Windows-1252] is essentially ISO 8859-15 which is not unicode. Its max code point is U+00FF by definition. Although using the `U+` notation isn't really correct since CP1252 is not unicode. Even if your locale is set to something like en_US.UTF-8 the mintty terminal emulator still has to support UTF-8. Does it? Even if it does it has to agree with fish on the width of code point \u203A. If it doesn't you'll see the sort of problem you're describing.

There are a surprisingly large number of special characters whose width as determined by a particular terminal emulator does not agree with the width a given program (e.g., fish) thinks it has. Sometimes this is because the unicode standard has changed the width over time and each piece of software is conforming to a different version of the standard. Sometimes it's simply that the version of the standard being used didn't define the character so the program is using a fallback width. Or, of course, there may simply be a bug in the software.

**Comment by krader1961** [comment]
I started my Windows 10 VM and opened a cygwin mintty window. I confirmed my fish locale was en_US.UTF-8. I added \u203A to my prompt and observed the correct unicode char and no spurious movement of the cursor. I then set the mintty text and font preferences to locale=C and encoding=CP1252 and saw the behavior you described. Which is not a surprise since \u203A has a width of one but because the fish locale is en_US.UTF-8 it actually writes three bytes to the terminal. So the terminals idea of how many characters have been written is two more than fish thinks has been written.

Your terminal and fish have to be using the same encoding. So either configure your terminal to use a UTF-8 encoding or tell fish to use a single byte encoding; i.e., `set LANG en_US`. But note that if you do the latter then code points greater than \xFF will be replaced with a question mark since they can't be represented in a single byte locale (what Windows calls a "code page" and UNIX knows as ISO 8859).

**Comment by rgiordani** [comment]
Thank you.

**Comment by faho** [comment]
@rgiordani: My question is why you chose that encoding? Is there any reason for it? Usually, I'd recommend a unicode encoding like UTF-8 or (possibly) UTF-16 (since that's what windows commonly uses, though I have no experience of using it with fish).

**Comment by rgiordani** [comment]
At home, linux & utf-8. No doubt.
At work, I've to adapt to use Windows with CP1252 encoding. It's the encoding of every text file shared in my organization, also for all the source code, and is the default for every windows system (even on unix system we have a similar encoding, probably iso-8859-1).

**Comment by rgiordani** [comment]
I used to think that cp1252 is the default western encoding for Windows, at least in italian distribution.
