### ISSUE TITLE
Problems testing for contents of $PATH

### ISSUE THREAD

**Issue by carlca** [fish-shell/fish-shell#4026]
_fish --version_
**`fish, version 2.5.0`**

_os_ 
**`Darwin Carls-Mac-Pro 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64`**

_echo $TERM_
**`xterm-256color`**

_also using_
**iTerm2
OMF
agnoster theme**

_functions_
 `~ cd .config/fish/functions/`
`~/.c/f/functions` 
`cat ae.fish`
**`function ae`
`........if grep venv/bin $PATH`
`................deactivate`
`........end`
`........source ./venv/bin/activate.fish`
`end`**
` ~/.c/f/functions`
`cat de.fish`
**`function de`
`........deactivate`
`end`**

The problem occurs when I try to issue the `ae` function. I am trying to execute the `deactivate` command **ONLY** if the string `venv/bin' is present in the $PATH. Instead I'm getting the following error messages:

```
grep: /usr/local/bin: Is a directory
grep: /usr/bin: Is a directory
grep: /bin: Is a directory
grep: /usr/sbin: Is a directory
grep: /sbin: Is a directory

```

How I can perform a grep on the PATH giving a boolean result that the if statement can use?

Thanks in advance,
Carl

**Comment by faho** [comment]
First o fall, this is not a fish-specific problem. `grep searchstring parameter` will understand "parameter" to be a path to a file that it should open and check for "searchstring".

What you would need to do instead is pass the paths to `grep` via stdin:

```fish
if printf '%s\n' $PATH | grep -q venv/bin
    # do something
end
```

(additionally, you should pass "-q" so that grep won't print output, but will instead just return true if it found something)

Or, if you want, you can use fish's `string` builtin:

```fish
if string match -qr venv/bin -- $PATH
    # do something
end
```

This will also often be faster because it is a builtin and not an external command.

**Comment by carlca** [comment]
Cor! That was quick Faho. I'll try it out right now.
Thanks!

**Comment by carlca** [comment]
Fantastic, it works! Thanks so much. I'm learning so much in this new world of Apple Macs!

**Comment by faho** [comment]
Happy to be of assistance.
