### ISSUE TITLE
`wcsfilecmp()` doesn't behave as advertised

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#4027]
I started to refactor `wcsfilecmp()` to eliminate some `make lint-all` warnings. But before doing so I  added unit tests to help ensure I did not change the behavior. That caused me to notice the function does not behave as described. Furthermore, it's interface is underspecified. It doesn't just return the traditional -1/0/+1 values for a typical comparison function. It ostensibly returns -2/-1/0/+1/+2 but in fact can return arbitrary values due to how the comparisons are implemented; e.g., I saw 103 returned for one pair of file names. What does that even mean?

So this issue is to remind me to rewrite the implementation, not just address the lint warnings. And add a comprehensive set of test comparisons. Also, improve the description of the function to make its semantics clearer without having to puzzle over the code.

**Comment by faho** [comment]
Like I remarked on gitter, this function is only used in one place - `completion_t::is_naturally_less_than`, where it is used like this:

```c++
bool completion_t::is_naturally_less_than(const completion_t &a, const completion_t &b) {
    return wcsfilecmp(a.completion.c_str(), b.completion.c_str()) < 0;
}
```

Because of the "< 0" comparison, most of the return values remain unused - "-2" might as well be "-1", and anything larger than 0 might as well be 0.

Also, this function is only used to sort the completions, so any changes in behavior are limited to that. The current behavior is good for most cases, but I think I've found an edge case that seems weird: ["a0", "a00", "a00b", "a0b"]. It is weird that the "0" component sorts before the "00" component in one case but behind in the other.

**Comment by krader1961** [comment]
> I think I've found an edge case that seems weird: ["a0", "a00", "a00b", "a0b"]. It is weird that the "0" component sorts before the "00" component in one case but behind in the other.

That is an artifact of the current implementation. It's an example of what caused me to decide to rewrite this function. My new version handles this consistently. However, it might still seem somewhat mysterious because disambiguating file names that are logically equal involves comparing Unicode code points. So "0" < "b". But unless you are familiar with the ASCII character set, let alone Unicode, that ordering will seem arbitrary and perplexing. But at least the behavior will now be consistent and predictable.

Also, my new version of this code is much clearer and easier to change the fallback semantics. So if we want to special case classes of characters such as alphabetic and numeric versus all others we can now do so relatively easily.
