### ISSUE TITLE
`set -q` documentation wrong?

### ISSUE THREAD

**Issue by dpc** [fish-shell/fish-shell#4033]
https://fishshell.com/docs/current/commands.html#set  :

```
-q or --query test if the specified variable names are defined. Does not output anything, but the builtins exit status is the number of variables specified that were not defined.
```

**not** defined

But when I run:

```
> fish --version
fish, version 2.5.0
> set -q $HOME; echo $status
1
> set -q $HOME $DISPLAY; echo $status
2
> set -q $fooodfsdfa $asdfasdfddd; echo $status
0
```

**Comment by faho** [comment]
No, the documentation is correct. The issue here is that you are expanding the variables, which means `set -q` will check if the _value_ of the variable is itself the name of a defined variable name.

E.g. `set -q $HOME`, will check if "/home/dpc/" (or similar) is a defined variable, which it isn't (it's not even a valid variable name).

`set -q $foo` will expand to `set -q` without other arguments if foo is undefined. It would probably be better to return a false value in that case, but that would necessarily break the idea that the return status is equal to the number of undefined variables - here, there are no undefined variables given.

The correct call would be `set -q foo` or `set -q HOME` - pass just the name, don't expand the variable.

Hope that helps!

**Comment by dpc** [comment]
Ooooooohhh... . Thanks!
