### ISSUE TITLE
implement a `select` function

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#4036]
Earlier today someone asked on StackExchange what is the [fish equivalent of the bash `select` command](https://superuser.com/questions/1209901/what-if-any-is-the-equivalent-of-bashs-select-in-do-done-in-fish). Surprisingly I can't find any issues, even closed ones, asking that an equivalent be implemented in fish so I'm opening this issue.

Note that I am not a fan of the sh/ksh/bash `select... in... do... done` behavior. It is extremely difficult to use it correctly. Which also means that it is hard to correctly understand what happens when you read a script which uses that construct.

On the other hand we have something similar in the `history` function and my `mcd` function. It strikes me it would be useful to abstract that logic into an independent function. The question is whether that is worth doing in light of issue #2805 that requests a way to use the internal pager used for completions from non-completion contexts. The advantage of making it possible to use the internal pager is that the user can then use arrow keys and its filtering mechanism and it would feel very like selecting an item from a completion. On the other hand a `select` function is likely to be something people find easier to use and more familiar. It's also something I could probably write in a couple of hours. With most of that time spent documenting it and generalizing the code I would copy from my `mcd` implementation.

Just a reminder of what `mcd` behavior looks like:

```
$ mcd
 d  4)  ~
 c  3)  ~/tmp
 b  2)  /private/tmp
 a  1)  ~/projects/3rd-party/fish-shell
Select directory by letter or number: 0
Error: expected a number between 1 and 4 or letter in that range, got "0"
```

**Comment by zanchey** [comment]
This came from https://bugs.debian.org/862527

**Comment by zanchey** [comment]
A select function might be more suited to a fish library; I don't think it requires shipping with fish.

**Comment by nhooyr** [comment]
I think that there have not been any issues regarding this because of fish's autocomplete, it already covers similar use cases.

**Comment by joelmaxuel** [comment]
So I was the one who asked on Stack Exchange, and earlier than that, erroneously put in a Debian bug report.
I would agree with zanchey because of Debian's packaging.  An extra function would be much easier to bring over and maintain than selecting a "bleeding edge" package version (or manually compiling fish from source) for a few years.
I will look at the MCD function more later on today.  Thanks for the help thus far.

**Comment by faho** [comment]
Soo... first of all let's close #2805, since we already have more info here.

Okay, done.

----

The idea of having a builtin "menu"-like thing appeals to me, and the main reason to include it IMHO is that we can maintain a UI consistent with completions.

This is something I'd currently recommend something like [fzf](https://github.com/junegunn/fzf) for, which is nice, but feels different from our pager. It's also a bit complicated and has a ton of options. I've hacked together a function to use it as completion pager, and it feels weird and doesn't interact well with our descriptions (there is a "field" selection method, but that can't use a field as purely descriptive).

I also have a usecase in form of my aur helper (think package manager), where it'd be nice to search for something and select the result in the same call.

However, I don't think bash's `select` is a good thing to copy verbatim.

**Comment by plainas** [comment]
Bash select is too primitive. I think it does its job, but fish' interactivity is already leaps and bounds ahead of it.

I use [percol](https://github.com/mooz/percol), which is similar to fzf. It's a tremendously useful tool, no doubt. What is in discussion is just tiny little bit of glue in the shell.

The reason fzf, percol, peco et. al. don't help, is because they are simple programs that, once the interaction is done, will send text to the output and immediately exit. This is, of course, what they are supposed to do.

We want to close the loop. Get data from and arbitrary source, possibly using a simple interactive menu like the one autocomplete one, and being able to use that data to do whatever we want without triggering or requiring a command execution as the user perceives it.

**Comment by sagebind** [comment]
I originally opened #2805 also with the intent of improving [my own directory navigator, marlin](https://github.com/oh-my-fish/marlin). Marlin is based on interactive word-level completions; all the brunt of the work is done using my [expand plugin](https://github.com/oh-my-fish/plugin-expand).

Right now, expand is either not very interactive (hit tab to cycle results, think bash), or it uses something like peco or fzf. It would be much nicer to use the built-in pager for these types of functions, because:

1. Context. The existing UI is nice that it does not clear the screen, but uses a few lines in the existing screen. This helps the user remember what they were doing and what command they were in the middle of typing.
2. Consistent. Improves consistency by giving the same experience as built-in completions for custom behaviors as well.
3. Portable. Well, if fish has it built in, you don't have to install fzf, etc...

A big issue with fzf and the like is that they write the user selections to output. This is a big pain because we can't use them in subshells and give them an interactive stdin. I don't know if a builtin would have the same issue, but I would recommend writing the results to a variable for such a function.

**Comment by plainas** [comment]
Hey everyone... any updates on this?

I agree with the three points outlined by @sagebind , specially 3. It boils down to triggering the fish pager pragmatically from any fish script.

**Comment by joelmaxuel** [comment]
I am satisfied with the current state, once @krader1961 (long ago) provided a concept to accomplish what bash's select does.

Was able to design my own [cdb](https://github.com/joelmaxuel/cli-productivity-config/blob/master/fish/functions/cdb.fish) (change directory below) and [cdfl](https://github.com/joelmaxuel/cli-productivity-config/blob/master/fish/functions/cdfl.fish) (change directory by first letter).  This issue was opened for me, I could have noted way back then that it could be closed, but it is serving other purposes now too.

So further to what was also brought up, given what `cdb` and `cdfl` do, expansion would be challenging and potentially (depending on directory structure) very resource intensive to accomplish, so it was something I was not particularly interested in trying to implement.

**Comment by plainas** [comment]
Maybe close this issue and re-open  #2805 ?

**Comment by floam** [comment]
I'm not big on the `mcd` UI - I am big on our pager UI - I agree with @plainas. I'm going to pull a switcheroo here.
