### ISSUE TITLE
Add OLDPWD environment variable

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#4040]
In line with [bash/ksh/zsh](http://hyperpolyglot.org/unix-shells#special-var), could we add an `OLDPWD` environment variable to fish?

**Comment by zanchey** [comment]
Do you mean like `$dirprev[1]`? I think that's an implementation detail rather than a documented feature, though.

**Comment by faho** [comment]
We have $dirprev, which is a list of the previous directories. So $OLDPWD would be equivalent to $dirprev[-1].

**Comment by zx8** [comment]
Oh, fantastic! I can just mimic other implementations by creating the following function then:
```
function __fish_set_oldpwd --on-variable dirprev
  set -g OLDPWD $dirprev[-1]
end
```

Case closed!

**Comment by guillonb** [comment]
When is the dirprev variable updated exactly?  It seems that, triggering a function on PWD variable change, will see the new pwd in `$PWD` but not the preceding one in `$dirprev[-1]`.  Here is an example:
```fish
cd /tmp
mkdir -p a b #(for the example)
cd a
function showmymoves --on-variable PWD
    echo "You moved from "$dirprev[-1]" to $PWD."
end
cd ../b
```
will show `You moved from /tmp to /tmp/b.` instead of what I expected namely `You moved from /tmp/a to /tmp/b`.  Is there a way of knowing the preceding PWD within the trigger fired on PWD change?

**Comment by ridiculousfish** [comment]
`$dirprev` is managed by [cd.fish](https://github.com/fish-shell/fish-shell/blob/640feeee676b9a3100385ab7a461750d5e84b5b4/share/functions/cd.fish#L30). `$dirprev` is updated after $PWD changes since the `builtin cd` command may fail. I expect you could manually manage an $OLDPWD by just watching $PWD.

**Comment by guillonb** [comment]
Thank you for the answer.  I already imagine a solution with my manually-managed $OLDPWD variable.  I could also fire my function on variable $dirprev instead of $PWD.
