### ISSUE TITLE
support string slicing as in Python

### ISSUE THREAD

**Issue by techtonik** [fish-shell/fish-shell#4049]
I stuck for more than an hour trying to figure out how can I extract site name out of `sync-bugs.debian.org.sh` filename with fish 2.4.0

In Python I woud just do:
```
>>> x = "sync-bugs.debian.org.sh"
>>> x[5:-2]
'bugs.debian.org.'
```

In fish?

**Comment by zanchey** [comment]
You can do this with standard UNIX utilities:

```
basename sync-bugs.debian.org.sh .sh | cut --delimiter=- --fields 2-
```

**Comment by techtonik** [comment]
That `cut` invocation is too cryptic to be useful. I don't see benefits in using `fish` then.
```
x = "sync-bugs.debian.org.sh"
${filename:5:-3}
```

**Comment by krader1961** [comment]
Not sure why you are using those particular indexes but:

```
set x "sync-bugs.debian.org.sh"
echo (string join '' (string split '' $x)[5..-2])
```

However, I would do this if what I want is the hostname or domain from the FQDN:

```
set x "sync-bugs.debian.org.sh"
echo Host: (string split -m1 '.' $x)[1]
echo Domain: (string split -m1 '.' $x)[2]
```

Fish currently does not have special syntax for slicing simple strings. That you can do so in Python is both good and bad. I've seen plenty of bugs introduced because someone thought they were slicing an actual list or tuple but were in fact slicing a string (which behaves like a tuple for the slice operator but no other operator). Not sure we want to add that to fish.

**Comment by techtonik** [comment]
[5..-2] is for slicing lists, why not to add [5:-2] for slicing strings?

**Comment by krader1961** [comment]
> why not to add [5:-2] for slicing strings?

For the reason I gave in the last paragraph of my previous comment. I've lost count of how many bugs I've encountered in Python code due to that feature. However, I concede the benefits of supporting the feature may outweigh the negatives.

Also, because every variable in fish is a list we would probably want to require specifying the element to be sliced; e.g., `$x[1][5:-2]`. If we made that a requirement it would eliminate the ambiguity and therefore make mistakes less likely; albeit at the cost of increased verbosity for the common case.

**Comment by techtonik** [comment]
I spent quote a time debugging Python code in many open source projects, reported a lot of issues and proposed quite a few things to python-ideas and I can not confirm that slicing strings instead of arrays and vice versa is a biggest Python problem that outweights the benefits of having a clear slicing syntax.

**Comment by krader1961** [comment]
I never said it was the biggest Python problem. Only that ability to apply slices to strings was the single most common source of bugs that was due solely to Python syntax. And I say that as a software engineer who did 95% of their coding in Python at Google for six years :smile:

@techtonik, Would you object to requiring that an index to explicitly select the element to be sliced be required?

**Comment by techtonik** [comment]
=) I see. Maybe it's the fish problem then - that it is easy to forget the quotes and create variable with list instead of string.  Anyway, that will do it for me:

    substr x 5 -3

But I guess it should be `6 -3`, because `fish` uses 1-based index.

> Would you object to requiring that an index to explicitly select the element to be sliced be required?

Not sure that that means. Maybe an example of that index?

**Comment by techtonik** [comment]
I am afraid that `string sub -s 6 -e -3 x` is too verbose to be readable.
```
x[5:-3]
string sub -s 6 -e -3 x
```

**Comment by krader1961** [comment]
> Not sure that that means. Maybe an example of that index?

@techtonik, I provided an example and rationale in [this comment](https://github.com/fish-shell/fish-shell/issues/4049#issuecomment-303236017). Consider this sequence of commands

```
set x abc def
echo $x[1..-2]
```

What should that write to stdout?  What if `$x` has a single value?

**Comment by techtonik** [comment]
Nothing? Because is `$x[1..-1]` is `def` then `$x[1..-2]` is nothing.

If `x` is a single string, then `$x[1..-2]` should fail with an error of array access, and `$x[1:-2]` (if `:` is adopted) should return `abc d` (because of 1-based index).

**Comment by krader1961** [comment]
@techtonik, What you seem to be suggesting is introducing new syntax. Specifically, using `:` rather than `..` to indicate that a string slice rather than an array slice is being requested. That still doesn't answer what should happen if you do

```
set x abc def
echo $x[1:-2]
```

Which element of the array is being string sliced? Is defaulting to the first element obvious? I suppose it is if the var has a single element. But what if it has more than one element as in that example? Should it fail or silently substring the first element?

**Comment by techtonik** [comment]
If we insist that index operator creates problem if applied to both strings and list in the same syntax, then we need to use strong typing and make string slicing syntax `x[1:-2]` fail with an error when applied to list (which has its own `x[1..-2]` syntax).

**Comment by techtonik** [comment]
```
set x abc def
echo $x[1:-2]
```
Should fail, because x is not a string.

**Comment by krader1961** [comment]
@techtonik, Note that every single fish variable is "not a string". It is a list/array of strings. So when you say "x is not a string" I'm assuming you mean it has more than one element.

What you seem to be arguing for is that a var with a single element be treated as a simple string with respect to the proposed `$var[start:end]` string slice syntax.  And that syntax would be an error if the var had more than one element. Also, you are proposing that the `[start:end]` syntax doe s not perform slicing of the variable list/array. It only slices simple strings. Yes?

**Comment by techtonik** [comment]
> ...that a var with a single element be treated as a simple string with respect to the proposed `$var[start:end]` string slice syntax.

Maybe even enforce that all strings should be distinguishable from lists when defining them. Scanning for the spaces may not be the best user experience to understand its type (if needed).

> And that syntax would be an error if the var had more than one element. Also, you are proposing that the [start:end] syntax doe s not perform slicing of the variable list/array. It only slices simple strings. Yes?

Right.

**Comment by krader1961** [comment]
> Maybe even enforce that all strings should be distinguishable from lists when defining them. 

That cannot be done without radically changing the behavior of fish (i.e. fish script semantics). That change could not even be done in a major fish release.

We could introduce support for string slicing, as opposed to list slicing, via your proposed `$x[start:end]` syntax. However, that would not behave like it does in Python since it would not allow you to slice a list using that syntax. You would still have to use the `$x[start..end]` syntax to slice the `x` list. Which is why I propose repurposing the existing syntax if the value being sliced has a single array element.

**Comment by techtonik** [comment]
> However, that would not behave like it does in Python since it would not allow you to slice a list using that syntax. You would still have to use the $x[start..end] syntax to slice the x list.

I am fine with it if it is documented for both entrypoints.

> You would still have to use the $x[start..end] syntax to slice the x list. Which is why I propose repurposing the existing syntax if the value being sliced has a single array element.

I don't think it will increase script readability or error message. It maybe a convenient hack, but it would probably confuse me if I try to debug some script and forget string quotes for some reason.

**Comment by IsaacOscar** [comment]
All variables are lists, but what about "$x"? We could define the slicing of quotes to be string-slicing, so that "str"[range] would be defined as equivalent to (string join '' (string split '' "str")[range]).

Or, one could just write a function:
```
function slice
    set s $argv[1]
    eval "echo -n (string join '' (string split '' \$s)[$argv[2]])"
end
```

Then:
```
$ set x sync-bugs.debian.org.sh
$ slice $x 6..-2
bugs.debian.org.s⏎
```
as expected.

**Comment by techtonik** [comment]
In Python:
```
>>> "sync-bugs.debian.org.sh"[6:-2]
'ugs.debian.org.'
>>> 
```

**Comment by faho** [comment]
I'm afraid I'm declining this. We already have `string sub`, and it's never really been fish's thing to be as short as possible.
