### ISSUE TITLE
fish_prompt not persisting

### ISSUE THREAD

**Issue by danielbertolozi** [fish-shell/fish-shell#4053]
Fish version: 2.3.1
Terminal: iTerm (xterm-256color)
Kernel: Darwin Kernel Version 16.5.0 (MacOS Sierra)

Using `fish_prompt` is not being persisted across sessions.
Even though `funcsave fish_prompt` is being used and the fish_prompt.fish file is present on the functions folder, it still is not being persisted across sessions.

[Refer here for the Steps by Steps to Reproduce](https://youtu.be/2EDMwjkAI4s).

Using `sh -c 'env HOME=$(mktemp -d) fish'` also didn't work.

**Comment by krader1961** [comment]
The trick to use `mktemp` to get a pristine home directory is, by definition, not going to use a prompt you've defined elsewhere. It is causing fish to use a randomly named home directory.

Please tell us what `echo $HOME` and `echo $XDG_CONFIG_HOME` output in the session where you create and save a `fish_prompt` function and then in the new terminal session where your custom prompt is not used.

I would also expect any random function to also not be available in a new terminal session. For example, if you do the following in the same session where you define `fish_prompt` what happens if you run `testme` in a new terminal session where your custom prompt isn't used?

```
function testme; echo testme ran; end
funcsave testme
```

**Comment by danielbertolozi** [comment]
Here's the output for that. The left pane was ran first, then the second pane was created. It is weird that `testme` ran without any problems, while `fish_prompt` simply didn't work.

![screen shot 2017-05-22 at 11 42 57 pm](https://cloud.githubusercontent.com/assets/7820615/26336364/6a2391f2-3f48-11e7-9b73-cc1e7d064ece.png)

**Comment by krader1961** [comment]
Okay, that tells me you're defining a `fish_prompt` function in your *config.fish* or a script it calls. Because that is the only reason the function wouldn't be autoloaded.

**Comment by danielbertolozi** [comment]
Well, and that's true.  I was indeed defining the `fish_prompt` inside the `config.fish`. Didn't knew about that behavior.

Removing the function from the config file solved the issue. Thank you very much!
