### ISSUE TITLE
string builtin methods jam when string looks like an option '-'

### ISSUE THREAD

**Issue by endowdly** [fish-shell/fish-shell#4055]
fish, version 2.5.0.

Pretty sure our string builtin methods have simple option parsing.

string builtins using any function when the string contains '-' will throw any number of parsing errors. 

`string length '-'` returns 1, as expected. 

`string length '--'` returns nothing; exits 1 

`string length '---'` returns `string length: Unknown option '---'; exits 2 ... and so forth.

**Comment by krader1961** [comment]
This is a consequence of how the `getopt_long()` function behaves coupled with fish trying to be permissive. Can you explain what you expect to happen in each of those scenarios? And how we can change the current behavior without breaking existing uses?

Option parsing in fish is not consistent. Within the C++ code I have been slowly working to normalize the code to a consistent pattern. It is possible that this inconsistency is because I haven't yet normalized this code. But it is more likely the behavior you have noted is inherent in the approach fish takes to such things. We would love to see you build on the changes I have already made by contributing more changes to make fish option handling consistent. Both in style and practice.

**Comment by krader1961** [comment]
Also, all of your examples behave as I would expect. But that is because I know how option parsing works. The only example that is surprising is the first one: `string length '-'`. I think most people would expect that to fail rather than succeed and return a length of one since the hyphen was not followed by a short flag character.

**Comment by krader1961** [comment]
FWIW, I have already updated a couple of `string` subcommands to use the pattern I am establishing throughout the fish code with respect to dealing with command flags/options. However, I have not yet done so for `string length`. Whether or not applying that change to `string length` would fix this issue is unclear.

**Comment by endowdly** [comment]
My C++ is pitiful at best. I have a basic knowledge of C++ but no implementation practice. That said, I would still consider helping to consolidate consistent patterns. When it comes to simple things like defining patterns for option parsing, I'm confident I could help there. 

The behaviors I listed behave as expected of an `optparser()` without escape cases for just strings of hypens. Yet, when someone actually just wants to know how many hyphens are in a line, e.g. '--------------', it could be beneficial to know that is 14 and not 12 or 15 hyphens. Returning an error on a string in a string function certainly shouldn't be considered expected. Of course we could do a quick simple call, like `ruby -e "p '--------------'.length"`, but I feel like this defeats the purpose of having `string` functions to begin with. 

The specific use case I was doing was moving a ruby script that builds a header like this 
 
    '<comment character> --- <header title> --------------------------' . . . # to a specific length

to pure fish. The parsing of the remaining length can be done with some looping math, but my first intuitive thought was to use the _very handy_ string functions. But they failed me. :( 

I hope that explains the case better.

**Comment by krader1961** [comment]
I should have mentioned in my previous comment how to make your examples work. You need to include a `--` argument to tell the option parser to stop looking for more options. For example: `string length -- -------`. We are definitely not going to change how option parsing works, not even just for `string length`, to accommodate your examples.

Note that fish 2.6.0 has a new `string repeat` command that will make your example easy to implement. See issue ##3864.

I think this can be closed. Let me know if you disagree, @endowdly.

**Comment by endowdly** [comment]
`string repeat` looks like a good feature, I'll be sure to update. 

However, using `string length -- ------` to get a count on the string of hyphens sure is idiomatic fish, but it isn't discoverable, nor 'friendly'. Unless you have an intimate knowledge of the opt parser or spend hours digging thru the code to see why your string isn't being counting, the average user isn't going to be able to discover the reason for that error very easily. That said, since there is an idiomatic workout that fits in the fish mindset, I don't disagree to close this.

**Comment by krader1961** [comment]
Using `--` to stop option parsing has been standard behavior for most UNIX commands for two decades. This is not something that the fish project invented. You'll see that pattern used a lot in the standard functions that are part of a fish installation to protect against arguments that might begin with a hyphen. Run `cd $__fish_datadir/functions; grep ' -- ' *` to see where we do so.

If you have ideas for how to improve our documentation so that this is easier to discover please let us know what they are.

**Comment by endowdly** [comment]
But every coreutil in Unix that I know of will allow to easily pass a string literal of `-` as expected without it confusing it for an option. So I argue this behavior isn't consistent with most UNIX commands. For example: 
```
echo '-a little short string with lots of --------' | tr '-' 'a' 
echo '-a is this an -option' | grep '-' 
```

and then ... 

```
set string '-foo
set pattern '-foo'
string match $pattern $string
```
_string match: unknown option '-foo'_

Hm. I doubt a user of unix for 2 decades would immediately think to 
```
string match -- $pattern $string
```

But! If you go to `help string` there is a lot of fantastic information. Even one line I missed: 

> Arguments beginning with - are normally interpreted as switches; -- causes the following arguments not to be treated as switches even if they begin with -. Switches and
required arguments are recognized only on the command line.

If we could incorporate this cleanly into the synopsis or error case, something like: 

> string <command>: Unknown option <string>; use '--' to stop option parsing on following arguments.

I bet a lot more people would catch it. Maybe. I dunno. Now that I see `string: Type 'help string'...` and the carefully read the full documentation, I feel a little silly.

**Comment by faho** [comment]
@endowdly: I can't see how `string` works differently from `grep` here.

```fish
echo - | string match - # works
echo - | grep - # works
echo -. | string match -. # complains about unknown option
echo -. | grep -. # complains about unknown option
```

>But every coreutil in Unix that I know of will allow to easily pass a string literal of - as expected without it confusing it for an option

As I just demonstrated, `string` does too! The issue is when it's not _just_ a single dash, but that's like other utilities.

>string <command>: Unknown option <string>; use '--' to stop option parsing on following arguments.

This actually sounds like it might be a good idea.

**Comment by endowdly** [comment]
Well... today I certainly learned something. Thanks @faho and @krader1961 for gently entertaining my tangent and teaching me a tiny bit more. 

> This actually sounds like it might be a good idea.

At least I'm not completely unhinged. :)

**Comment by zanchey** [comment]
And of course, a single dash sometimes means "standard input" when used in place of a filename :-)
