### ISSUE TITLE
Tab completion of paths prefixed by ~ does not work

### ISSUE THREAD

**Issue by ixjlyons** [fish-shell/fish-shell#4061]
`cd /home/kenny/sr<TAB>` correctly completes to `cd /home/kenny/src` whereas `cd ~/sr<TAB>` does not (though I can press the right arrow key to complete). I ran a bisect which identified a3a0692 as the offending commit.

**Comment by krader1961** [comment]
Good catch. Thanks for the bug report. This is an example of why we didn't want to include that change in the forthcoming 2.6.0 release. It wasn't clear that change wouldn't be negative side-effects.

P.S., Pressing [right-arrow] is accepting the autosuggestion. Something that is independent of file name completions.

**Comment by zx8** [comment]
In addition, this seems to have broken "partial matching" of directories as well, i.e.

**Expected**
```
$ ls
aaaabbbb  bbbbaaa  cccccddddd
$ cd d<TAB>
cd cccccddddd/
```

**Actual**
```
$ ls
aaaabbbb  bbbbaaa  cccccddddd
$ cd d<TAB>
[no results]
```

**Comment by faho** [comment]
The issue here is that `cd` is using two kinds of completions - the script, and some hardcoded ones in c++. These latter ones are classified as "file" completions.

The script does essentially one thing the hardcoded completions don't - for candidates from $CDPATH, it adds the corresponding $CDPATH-component as a description (which I find rather useful). On the other hand, it does not do various expansions, as you've seen here.

There are a few things we can do:

- Remove the cd.fish completion script since it's barely useful anyway - we can add the descriptions back later

- Add these expansions to the cd.fish script (and then remove the special expansion code). This is difficult to do since we'd have to redo a bunch of the matching logic, and then keep it in sync.

- Remove the "-x" from cd.fish - this makes it work immediately, and is exactly as clean as the status quo.

Since the third option is really easy to do and fixes everything _now_, I'm going to do that.

-----

The good news is that we now know what to look out for when testing the underlying change - anything that might use the file-matching logic as a fallback for missing expansions, which includes everything using `__fish_complete_directories`.

Most other completions won't be affected since they either use the builtin file-completion logic or don't accept files _at all_.

**Comment by zx8** [comment]
@faho https://github.com/fish-shell/fish-shell/commit/4afd41877ff9144807b8bdd108309ba84770f73d seems to have fixed "partial completion" issue and the `cd ~/<TAB>` cases but `cd ~<TAB>` (without the `/` after `~`) still seems to be broken (i.e. on my mac, it somehow autocompletes to `cd _amavisd`).

**Comment by faho** [comment]
>cd ~<TAB> (without the / after ~) still seems to be broken (i.e. on my mac, it somehow autocompletes to cd ~_amavisd)

That means you have a user called "_amavisd" - tilde-expansion covers not just "~/" for the current user's home, but also "~$USER/" for $USER's home. E.g. on my system "~root/" expands to "/root/".

This isn't directly caused by the change to not offer files. It is caused by c114cbc9af4b5a07fb6e87b50f36e78aa8aba615 since that `break`s on the first match.

@krader1961: Mind taking a look?

**Comment by zx8** [comment]
@faho Aha, I see

For what it's worth, assuming it is related to https://github.com/fish-shell/fish-shell/commit/c114cbc9af4b5a07fb6e87b50f36e78aa8aba615, it seems to complete `~_amavisd` even if the target directory doesn't exist:

```
$ grep _amavisd /etc/passwd
_amavisd:*:83:83:AMaViS Daemon:/var/virusmails:/usr/bin/false
$ cd ~_amavisd
cd: The directory '/private/var/virusmails' does not exist
```

**Comment by faho** [comment]
>it seems to complete ~_amavisd even if the target directory doesn't exist

I'm unsure if we should do anything about that. That _is_ what the "_amavisd" user's $HOME is set to, and it might be useful for some commands. I'm assuming the path is still marked as non-existing (i.e. it's not underlined)?

Anyway, I've now opened #4074 to track the `~/` issue (which I don't was ever offered as a completion).

**Comment by faho** [comment]
Also #4075 tracks the issue of only completing one user.
