### ISSUE TITLE
should we setup an open source bounty system for fish issues?

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#4062]
We regularly see people add a comment to an issue that amounts to "This has been open a long time why hasn't this been implemented?". To which I sometimes reply with a "Patches are welcomed" or "Please keep in mind that no one gets paid to improve fish." Perhaps it is time to address that second point by setting up an [open source bounty system](https://en.wikipedia.org/wiki/Open-source_bounty) for fish issues. That way people who really want some feature implemented but lack the skills to do so themselves can entice others to work on the feature. I've never been involved in paying or receiving a bounty so I don't have first-hand experience with the mechanism but I have seen it employed on other projects which I use.

Hard to say if this is worth the overhead or would generate enough revenue to motivate people to work on issues but I figured it was time to see how people feel about the idea.

**Comment by zanchey** [comment]
Someone did for vi mode:
https://www.bountysource.com/issues/986070-vi-mode/backers

**Comment by zx8** [comment]
As a long time fish user, I'm very much for this.

This project makes my day-to-day terminal experience a lot more pleasant than other shells and I'd be more than happy to pay/donate to see certain bugs/features implemented, if not only just to support the people who willingly contribute their own spare time to the project without remuneration.

**Comment by faho** [comment]
This is one of those things that I could write a (very rambling) book about, but I'll try to keep it short. So let's try bullet points!

- Bounties usually are far from competitive - the only bounty we had so far was $200 for vi-mode, and the PR that got it was #1218. Cursory duckduckgoing tells me the median salary for an entry-level software engineer is $31/h, so that PR should have only taken 6.5h - which seems a tad short. And even that is higher than some other bounties I've seen.

- There already is a bounty thing set up for fish, so there isn't much to do here - maybe add it to the README or website?

- The incentives here are weird, especially for core contributors - I already have a fix for #826 in the pipeline. Should I wait with that until the bounty gets higher?

- I have no idea how this works tax-wise where I am (I have no idea how taxes work in general). It's possible this adds even more friction to the process.

So this seems weird to me. I'm okay though with it existing and I'd be okay with adding it to README.md as an experiment.

**Comment by krader1961** [comment]
I concur with all of your points, @faho. I opened this mainly because I am tired of seeing people add a comment to an issue that amounts to them acting like a four year old stomping their feet because the issue hasn't been addressed. I opened this issue somewhat tongue in cheek. But also somewhat serious.  No one is going to be able to make a living via these hypothetical bounties. Too, anyone like you or myself working on this project in our free time will continue to do so regardless of whether or not anyone pays us to address a specific issue.

I am primarily wondering how formal code bounties might alter our response to people whining why a particular issue hasn't been fixed. Could we point those people to a code bounty site that compels them to say how much the change is worth to them? This could act as a prioritization mechanism for people inclined to contribute changes to the code. It would also let the people who want to see a particular change implemented realize there is a real cost to such requests.

I admit that I am annoyed by the volume of comments that amount to "why haven't you already addressed this issue I consider extremely important". Setting up a formal code bounty mechanism would allow us to tell those individuals to "[put up or shut up](http://idioms.thefreedictionary.com/put+up+or+shut+up)" without being rude.

**Comment by faho** [comment]
I think the Bountysource (since that's what we're talking about in practice since it seems the most used and is already set up) [FAQ](https://github.com/bountysource/core/wiki/Frequently-Asked-Questions) is important here.

Particularly, one question I've had was when exactly a bounty is considered claimable - does the code need to be written or written and upstreamed? What happens if the change is rejected upstream?

And it turns out the answers are quite sensible - the code needs to be upstream, and if the change is rejected (i.e. the corresponding issue is closed "will-not-implement") the bounties are refunded.

------------

With that in mind, I propose that we try using Bountysource officially as an experiment.

That means adding it to README.md and ~~plugging~~ offering it in comments where applicable. If it turns out to have negative consequences (people holding changes hostage or only work happening on issues with bounties or angry discussions on PR rejections), we can stop doing that.

We can't stop anyone posting or accepting bounties anyway (and we shouldn't be able to - it's _free_ software, not _free_ software), so let's see if leveraging them works.

**Comment by zanchey** [comment]
[Producing Open Source Software](http://producingoss.com/en/producingoss.html#crowdfunding-and-bounties) gives a good overview of some of the problems with bounties.

I'm against the idea of offering this routinely. I think it's misleading to suggest that a bounty will alter the course of an issue being solved without clear evidence or commitment from any particular developers. I'm certainly not skilled enough to agree to take on bounties, and I wouldn't derive much benefit from it. Perhaps others are in a different position.

I can appreciate the desire to have a good answer for repeated requests for a feature. "Patches welcome" or "we're not getting paid" are fair but they are not helpful. We should not meet rude (or at least what we perceive as rude) comments with more rudeness. I think it would be more constructive for us to come up with some standard approaches for addressing repeated requests for the same feature, such as reminding users that they can subscribe to GitHub issues if they want to be kept up to date, giving an overview of how potential contributors can make a start, or describing the particular challenge that prevents the issue from being implemented.

**Comment by krader1961** [comment]
@zanchey, I am under no illusions regarding code bounties. I recognize that pointing people to a code bounty is unlikely to result in the desired change being implemented. I personally am not going to be motivated to work on a particular issue unless the bounty is on the order of $1000 USD or more. I will continue to work on the issues that I deem worthwhile absent other motivation. You say

> I think it would be more constructive for us to come up with some standard approaches for addressing repeated requests for the same feature, ....

I agree. My thinking with regard to pointing people to a code bounty was that it is an impersonal way to say "how much are you willing to pay to see the change implemented?". Which is a way to tell the person that they can either "[put up or shut up](http://idioms.thefreedictionary.com/put+up+or+shut+up)".

One alternative is to ignore such comments. Something I find even more distasteful since it tells the commenter that we don't care what they have to say. When I started contributing to this project in 2015 there were several pull-requests that were more than a year old. Not to mention a large number of issues which deserved a response that were in a similar state. Since then we have improved our handling of stale issues and PRs.

It is not clear to me how

> ...reminding users that they can subscribe to GitHub issues if they want to be kept up to date...

will motivate those individuals, or anyone reading their comment, to stop saying what amounts to "why isn't this already fixed?".

**Comment by floam** [comment]
I could use some cash, so let's encourage this.

**Comment by faho** [comment]
Since nobody appears to be particularly interested, let's just keep the status quo.
