### ISSUE TITLE
problem with a specific item in $PATH

### ISSUE THREAD

**Issue by geokal** [fish-shell/fish-shell#4064]
- fish, version 2.5.0
- 2.5.0
- Darwin Giorgoss-MacBook-Pro.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
- giorgosk@Giorgoss-MacBook-Pro /U/giorgosk>

Hi, I have tried many times to remove a specific item in $PATH or unsetting it universal fish variables 
but every time I fire up the terminal (iterm2) it shows the following message:

`set: Warning: $PATH entry "/Users/giorgosk/anaconda/bin" is not valid (No such file or directory)`

- tried set -e $PATH[4] but no luck
- tried `set -U fish_user_paths /Users/giorgosk/anaconda2/bin /usr/local/share/dotnet  /usr/local/bin /usr/bin /bin /usr/sbin /sbin $fish_user_paths` again no  luck (tried to omit the unwanted "/Users/giorgosk/anaconda/bin")

Any ideas would be great!!! awesome project by the way

**Comment by krader1961** [comment]
Remember that variable expansion happens before the command is run. So when you type `set -e $PATH[4]` you're telling fish to unset the variable named by the fourth element of PATH. Just drop the dollar-sign to get the desired effect: `set -e PATH[4]`.

Also, that warning is only emitted when explicitly doing `set PATH /dir1 /dir2 /invalid_dir`. So rather than trying to erase the invalid entry I recommend finding where it is being set and fix that.

**Comment by geokal** [comment]
Great thanks a lot I'll try what you suggest!!
