### ISSUE TITLE
Feature Request: fine grained command highlighting

### ISSUE THREAD

**Issue by amosbird** [fish-shell/fish-shell#4066]
Currently fish doesn't distinguish `there was a file on the search path that matched your command but you don't have execute permission` and `there isn't a command match`. Using different colors to highlight them would be more user friendly.

**Comment by krader1961** [comment]
I'm not a big fan of introducing a color just for this case. We already use so many colors that it takes a while to learn what they all mean. And this is a really niche case. It would probably be better to just augment `command` and `type -a` to report when the file exists but doesn't have execute permission. Note that even that isn't foolproof because the file could exist and have execute permissions and still not be executable. It might be the wrong format for the system (e.g., a ARM binary on a x64 system) or a script with an invalid `#!` line. The only way to know for sure if it can be executed is to try to run it.

**Comment by ridiculousfish** [comment]
It's rare to have an executable that you don't have permission to execute. Having a separate color for this case, and giving it a name etc., seems like too small a win.  We can and should underline paths that are invalid (regardless of execute permission) - please file a bug  if we're failing to do that. But distinguishing between can't-execute and not-found is too fine-grained for the syntax highlighter, so I'm closing. Thanks for filing this regardless.
