### ISSUE TITLE
[Question] How is fish-shell build for a specific language ?

### ISSUE THREAD

**Issue by triklsbg** [fish-shell/fish-shell#4068]
Following the Readme leads to an english version. How is a germanized version build?
Thank you

**Comment by krader1961** [comment]
Primarily through use of the `gettext()` function and translation files. In the project source see the *po* directory. At run time if your locale is one for which we have localized messages then fish will translate the default english messages to your language.

**Comment by zanchey** [comment]
One important step is to make sure you are building with gettext. It is normally automatically detected but can be deliberately chosen

`./configure --with-gettext`

**Comment by triklsbg** [comment]
Thanks so far. I compiled fish under archlinux and indeed the language is "autodetected" or whatever. Background for my issue is a translation error in fish 2.5.0 "has beendet" should be "wurde beendet" ..
The compilation of 2.6b1 is even worse: The greeting is in german but the exit message is in english, the translation is not complete. If so a hint in the greeting to an unfinished translation would be usefull.
![fish_2 5 0](https://cloud.githubusercontent.com/assets/3647083/26489015/e756cd14-4205-11e7-9dcd-f00e4e0128c1.png)
![fish_2 6b1](https://cloud.githubusercontent.com/assets/3647083/26489021/eef9050a-4205-11e7-8409-cd97962a94e7.png)

**Comment by faho** [comment]
>the translation is not complete

Yes, it isn't, and we appreciate any help on that.

>"has beendet" should be "wurde beendet" ..

Well.... not quite. "wurde beendet" would translate back to "was finished/stopped/killed". That sounds like something _outside_ caused it. But in this case the application itself has quit peacefully. So something like "hat geendet"? I'm kinda struggling to figure out something that both sounds good in german and is technically correct. Which is also why I don't work on the translations much.

>One more: english "version" is "Version" in german.

That particular output _should not_ be translated. In fact I'd argue that it should just print the version ("2.6b1") and nothing else. The reason is that it should be possible for external tools to rely on that being stable.

Also Grossschreibung is annoying (as is "ß").

**Comment by krader1961** [comment]
I agree with @faho that `fish --version` should output just the version ID with no extraneous text. I'll open an issue for discussion since it may not be safe to unilaterally change the output.

The problem with the termination message is in part because function `format_job_info()` is being called with a localized word rather than phrase. Furthermore, having two distinct messages that are chosen based on whether there is one or more than one background job complicates the code without improving the user experience.

**Comment by krader1961** [comment]
Closing since I believe we have answered the question. Feel free to reopen if that is not true.
