### ISSUE TITLE
Get completions from `-h` option if there is no man-page

### ISSUE THREAD

**Issue by con-f-use** [fish-shell/fish-shell#4081]
I'd like to propose an enhancement.

Fish should be able to get command line completions from the help-option of the command itself or in fact arbitrary output. I.e. there should be something like:

```
$ ./mycommand -h    # does not have a man page but lists its options
Usage: ./mycommand [OPTION]... FILE

Options:
  -h, --help    Display help message
  -l, --list        List some stuff                

$ fish_get_completion_from (./mycommand -h)
# Now fish knows about the `-h` and `-l` options to ./mycommand
```

Reasoning:

Not all command line programs have man pages, but many that don't at least list their options when called with `-h` or `--help`. 

Considerations:

This should be done on a command-by-command base and only when requested by the user. This is because some programs use `-h` differently (e.g. in  "human readable"  in case of `df -h`) and might actually change the system accidentally rather than provide a help message.

**Comment by krader1961** [comment]
I vote no on implementing this. As the O.P. notes we can't automatically do this because there is no guarantee `-h` produces help output. Or, for that matter, that we can reliably extract useful completions from such output. If the user has to opt-in each command where they want this behavior it probably makes more sense to just create a completion script. Especially since anything completions we create automatically from the help output are going to be only a list of the flags supported. Something that is trivial to put into a completion script.

**Comment by con-f-use** [comment]
Most people don't bother writing a completion script. A single command that would create that completion script would still be very handy.

**Comment by krader1961** [comment]
> A single command that would create that completion script...

Yes, but your example of how it would be used is not friendly: `fish_get_completion_from (./mycommand -h)`. It seems to me that anyone inclined to run such a command is unlikely to need it. And a naive user is unlikely to understand that running an arbitrary command with `-h` might be dangerous. Furthermore, as I said earlier such a command is unlikely to do more than register the short and long options. Often without useful descriptions or recognizing that an option requires a value. Something that is trivial to do by hand.

**Comment by faho** [comment]
I agree with Kurtis.

Sorry, but this isn't as helpful as it appears on first glance, so I'm closing this.

Thank you for your idea!
