### ISSUE TITLE
`complete` on `cd` returns the result twice

### ISSUE THREAD

**Issue by Ambrevar** [fish-shell/fish-shell#4085]
fish, version 2.5.0-426-gc263c593
OS: Arch Linux
Terminal: Urxvt 9.22

The completion of `cd` returns the results twice. Let's write a prototype:

```
function foo
	complete -C(commandline -c) > ~/comp.log
end
bind \cY foo
```

In a folder containing `A/` and `B/`,
```
$ cd <Ctrl-y>
```
will output
```
A
B
A
B
```
to `~/comp.log`.

I suspect a bug was introduced recently, as 2.5 does not suffer from this nor did HEAD a few weeks ago.

**Comment by krader1961** [comment]
No need to use a key binding. Just do `fish -c 'complete -C"cd "'`. Since the `__fish_complete_cd` function is still producing the correct output the problem lies in the `complete` command itself.

**Comment by krader1961** [comment]
Bisects to commit 4afd41877ff9144807b8bdd108309ba84770f73d: "Fix various expansions in cd completions". Basically the removal of the `-x` flag is causing file expansion to be mixed in with the output of `__fish_complete_cd`.

@faho, was removing that flag intentional? Should it be reinstated or do we need some other fix?

Note that you don't see the duplication when pressing <tab> because fish internally removes duplicates when showing them in the pager.

**Comment by faho** [comment]
>@faho, was removing that flag intentional? Should it be reinstated or do we need some other fix?

Yes, quite intentional. That was the point of that commit (in fact the only other change is the removal of an empty line)! I've discussed alternatives in https://github.com/fish-shell/fish-shell/issues/4061#issuecomment-304304560.

-----

>Note that you don't see the duplication when pressing because fish internally removes duplicates when showing them in the pager.

Yes, and that's what my assumption was with that commit. The idea is that it would produce both the default file completions and the (slightly better) scripted ones, and duplicates would be removed.

The issue here is more general - `complete -C` doesn't remove duplicates (while actually showing the completions does), and maybe it should. Or maybe it shouldn't, and if you're using these for something other than providing completions (in which case they'd be removed again), then you should be prepared to deal with it. I believe we have other completion scripts that generate duplicates, and removing those might be hard to impossible, at least without explicitly using `sort` or `uniq`.


NOTE: The offending commit (and the change that necessitated it - c114cbc9a) is **NOT IN 2.6.0**.

**Comment by krader1961** [comment]
Doh! That was recent enough I should have remembered the discussion.

The problem is `$CDPATH`. If it isn't defined then it is implicitly defined to be just `.`.  But if you do define it you have to explicitly include `.` other wise you have to type `cd ./\<path\>` for any subdirectory of the CWD (assuming the CWD isn't otherwise in CDPATH). It seems the correct thing to do is modify the `__fish_complete_cd` function to ignore `.`. The subdirs of the CWD will still included by the core file completion logic but not duplicated by that function.

**Comment by krader1961** [comment]
I have a new version of the *__fish_complete_cd.fish* script which avoids the duplication in this specific scenario. However, it doesn't fix the broader problem. Because even after we fix this specific scenario we are still dependent on the undocumented behavior described in this comment in the `__fish_complete_cd` function:

``` 
        # TODO: There's a subtlety regarding descriptions - if $cdpath[1]/foo and $cdpath[2]/foo exist, we print both
        # but want the first description to win - this currently works, but is not guaranteed
```
