### ISSUE TITLE
Documentation for keybindings?

### ISSUE THREAD

**Issue by karlek** [fish-shell/fish-shell#4086]
Hi,

I am currently trying to increase my productivity with fish shell by learning some keybindings. However I can't find any documentation for the keybindings in fish, and when I searched for it I only found the source for fish_default_keybindings.fish [\[1\]](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_default_key_bindings.fish). This works for some keybindings, but the funkier ones like `\eOD` and `\e\[1\;5D` are hard to tell without comments.

Is there some documentation for keybindings in the help documentation or elsewhere? Otherwise, it might be a good thing to add! (I could volunteer).

Btw, using fish version 2.5.0.

\[1\]: https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_default_key_bindings.fish

**Comment by faho** [comment]
If you mean "which key does what", then see http://fishshell.com/docs/current/index.html#editor, which explains it for both the default (emacsish) and the vi-mode.

This can also be accessed locally via `help editor`.

**Comment by karlek** [comment]
Thanks! Was precisely what I was looking for.

Closing this issue.

**Comment by krader1961** [comment]
Also, many sequences sent by different keys aren't reliably defined in the terminfo database. Sometimes because the `$TERM` value isn't quite right for your terminal or because it is in an alternate mode (e.g., keypad transmit enabled). So many of the bind commands you see in those scripts won't be applicable to your specific situation. They're there to ensure fish behaves reasonably.

Lastly, you may find the `fish_key_reader` command useful for further exploration.

**Comment by karlek** [comment]
`fish_key_reader` helped me a lot. Thanks @krader1961!

**Comment by smammy** [comment]
> If you mean "which key does what", then see http://fishshell.com/docs/current/index.html#editor, which explains it for both the default (emacsish) and the vi-mode.

Current link to that information is:
http://fishshell.com/docs/current/interactive.html#shared-bindings

**Comment by sarnobat** [comment]
I'm trying to get up and running coming from a zsh background and I'm finding it very difficult for key bindings especially.
