### ISSUE TITLE
`complete -C` fails on subcommands

### ISSUE THREAD

**Issue by Ambrevar** [fish-shell/fish-shell#4093]
fish, version 2.5.0-430-g5e39efa4
OS: Arch Linux
Terminal: Urxvt 9.22

Works as expected:

	fish -c 'complete -C"fish --"'

Outputs nothing:

	fish -c 'complete -C"env LC_ALL=C fish --"'
	fish -c 'complete -C"sudo fish --"'

Am I hitting a bug?

**Comment by krader1961** [comment]
Not so much a bug but a fundamental limitation. The first thing to note is that fish has no way to know that `env` or `sudo` are commands followed by another command which you might want help completing. We work around this by using a function named `__fish_complete_subcommand` in the completions for `env` and `sudo`. Type `complete | grep 'command env'` and note how it gets invoked. Now look at the definition of that function. It relies on the `commandline` builtin to get the current *interactive* command line. But since you're not running in an interactive context it can't fetch that information and thus has no idea what command to complete. If you just type `env LC_ALL=C fish --` interactively then press \<tab\> you'll see the expected options for the fish command.

**Comment by Ambrevar** [comment]
`complete | grep 'command env'` outputs nothing and `complete` only outputs the aliases I've set.

```
complete --command l --wraps ls
...
```
Anyways, I've looked up the functions manually.

I'm trying to replace the fish completion menu with fzf using the code there: https://github.com/junegunn/fzf/wiki/Examples-(fish) (*Completion*).

Is there any workaround?

Generally speaking, it would be great if `complete -C` would effectively generate the same completion as `<tab>` does. This is related to #3469.

**Comment by krader1961** [comment]
Completions aren't loaded until you try to use the command in the current shell. They're like autoloaded functions in that regard. So `complete | grep 'command env'` won't show it's completions unless you've actually used the command.

The current solution for nested commands is a bit of a hack. I hate to say never but it is improbable the current solution will ever be improved as it would be adding a hack on top of a hack. You could certainly open an enhancement request that the core completion logic include support for nested commands. But I wouldn't hold my breath waiting for it to be implemented.

Since in practice there are only a handful of commands commonly used which have this pattern (`sudo` and `env` being the only two that immediately come to mind) it should be easy enough to special-case them in your wrapper around the `complete` command.

**Comment by Ambrevar** [comment]
Too bad. I'll see if I can work around this gracefully though.

**Comment by Ambrevar** [comment]
I've commited the following change:
https://github.com/junegunn/fzf/wiki/Examples-(fish)/_compare/c9afa3ef5c9fc5ed8c442f646405e7673695ad8d...eef88ee6f7d1d2d4b95471b5685d577f5ae27072

That seems to work well for the case of `env` and `sudo`.
