### ISSUE TITLE
glob expansion is exponential

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#4094]
I was reading [this article on glob expansion in various shells and platforms](https://research.swtch.com/glob), and decided to see what fish is like:

```
cd (mktemp -d)
touch (string repeat -n 100 'a')
for n in (seq 1 10)
   set -l pattern (string repeat -n $n 'a*')b
   time fish -c "echo $pattern"
end
```
n (`a*`) | User time
--|--
1 | 0.01
2 | 0.00
3 | 0.00
4 | 0.03
5 | 0.57
6 | 9.13
7 | 126.32
8 | 1521.75
9 | 16055.30
10 | 152573.24

I'm not sure if there's something we can, or want to, do about this, but let's at least consider it.

**Comment by krader1961** [comment]
For anyone wondering where the fish glob implementation can be found look at *src/wildcard.cpp*. Keep in mind that fish supports `**` to mean recursive globbing into subdirs. Whether or not that means we can't use the simple solution outlined in the paper linked to as our only implementation is TBD. Of course, we can always have two implementations. Scan the pattern and use the current, slow, implementation if it contains any instances of `**`. Otherwise use the fast implementation.

**Comment by krader1961** [comment]
I've removed the "RFC" label because we definitely should improve the performance of the common case. If we can also improve the performance of recursive globs (i.e., "**") so much the better. But at a minimum we should make the non-recursive case (which is the most common) non exponential in behavior.

I've added the "easy-pick" label because this should be straightforward to improve given the information in the document linked to if the recursive glob case is ignored.

**Comment by HazemSamir** [comment]
Hi there,
I'd like to pick this, if it is still available.

**Comment by cmansley** [comment]
This is issue is closed, correct?

**Comment by faho** [comment]
Yes, thanks for the reminder!
