### ISSUE TITLE
Accessing the current command

### ISSUE THREAD

**Issue by Dreamsorcerer** [fish-shell/fish-shell#4096]
I can't find anyway to access the current running command.
Specifically, when running something like:
`cd foo; alert bar`

In the alert function, I want to get the 'cd foo' string.

In bash, I can do this with `history | tail -n1` and then use sed to strip the alert off.

In fish, it seems the command is not added to history until after it is run, and I can't find any way to access this. The closest I can find is: `echo $_ $argv` which returns `cd bar`. That is, the command and the arguments to the function, I see no way to get the arguments to the command.

```
> fish --version
fish, version 2.2.0
>   echo $version
2.2.0
> uname -a
Linux s-laptop 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> echo $TERM 
xterm
```

**Comment by krader1961** [comment]
The first thing to note is that command history in fish only includes commands typed interactively and it isn't the command that is logged it's the entire command line. Which in your examples means that `cd foo; alert bar` is logged. That's why `cd foo` isn't in the history when `alert bar` is executed.

There is a `fish_prexec` and `fish_postexec` event you can use to cause a [function](http://fishshell.com/docs/current/commands.html#function) to be run when an interactive command is about to be run and after it completes. But that too gets the entire command line. Note that `fish_postexec` runs before the command is written to history.

It's not clear what you're trying to do but using a function that is run when the `fish_prompt` event is emitted might do the trick. That event is emitted just before the next prompt is displayed and after the previous command line is logged.

**Comment by Dreamsorcerer** [comment]
Having a hook running for every command all the time, just so this function (which I might use once a month) will work correctly seems a bit much. It would be much easier, if there was just a variable or something that contained the current command.

As mentioned in Bash, this is simply `history | head -n1`, because Bash appears to save the command to history before running the command.

The goal is that the alert command can say the previous command has been completed. e.g. `some_long_running_cmd args; alert` can create a notification saying "some_long_running_cmd args" has completed.

As mentioned previously, it's fine if I can get the full command, as my Bash version just uses sed to strip off the alert command.

**Comment by krader1961** [comment]
> It would be much easier, if there was just a variable or something that contained the current command.

If you care to flesh out this idea (it needs considerably more detail) feel free to open an enhancement request.

For now just define a function that runs when the `fish_preexec` function is emitted. Have it save the command line in a global variable. Your alert command can then use the contents of that var.

**Comment by Dreamsorcerer** [comment]
I'm not sure how much more detail there can be. How's this? https://github.com/fish-shell/fish-shell/issues/4111
