### ISSUE TITLE
Unexpected subcommand behaviour

### ISSUE THREAD

**Issue by lodo1995** [fish-shell/fish-shell#4097]
System informations (ArchLinux x86_64):

    > fish --version
    fish, version 2.5.0
    > uname -a
    Linux <username> 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux
    > echo $TERM
    linux

`llvm-config` is a command shipped with LLVM that outputs an options string to feed `gcc`.

    > llvm --cxxflags --ldflags --libs
    -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe <very long line...>
    -L/usr/lib
    -lLLVM-4.0

But when I use it as a subcommand, something goes wrong that makes `gcc` interpret it as a filename:

    > g++ (llvm --cxxflags --ldflags --libs) fib.cpp
    cc1plus: error: /usr/include  -march=x86-64 -mtune=generic -O2 -pipe <very long line...>: File name too long

Strangely enough, removing the `--cxxflags` (thus removing the long line and only keeping the two short ones) solves the issue:

    > llvm --ldflags --libs
    -L/usr/lib
    -lLLVM-4.0
    > g++ (llvm --ldflags --libs) fib.cpp
    >

On `/bin/sh`, I can run the subcommand fine by using backticks.
I have the same problem when using `clang` instead of `g++`.
So it looks like a problem of `fish`. Maybe the behaviour of the parenthesis does not match the behaviour of the backticks of `bash`. But why does it only happen when I use `--cxxflags`?

A possible hint:

    > g++ --verbose -Ifoo (llvm-config --cxxflags --ldflags --libs) fib.cpp 2>&1 >/dev/null | grep 'COLLECT_GCC_OPTIONS'
    COLLECT_GCC_OPTIONS='-v' '-I' 'foo' '-I' '/usr/include  -march=x86-64 -mtune=generic -O2 -pipe <very long line...>' '-L/usr/lib '

So it appears that the result of the subcommand is passed to the main command as one argument per line, while `bash` backticks pass it literally, as one argument per word (as if you pasted the result of the subcommand).

**Comment by krader1961** [comment]
You're being bitten by a fundamental difference between fish and POSIX 1003.1 compliant shells like bash. Shells like bash perform word splitting in many different contexts that can lead to strange unexpected behavior and require complicated quoting of arguments. This includes the output of subcommands (e.g., `` `llvm-config` `` or `$(llvm-config)`). Fish doesn't do that. Fish only splits the output of subcommands on newlines. So that very long line output by `llvm --cxxflags` is passed as a single argument to g++ rather than split into multiple arguments.

There are different ways to deal with this each having different pros and cons. The simplest is to preface the entire command with `eval`. That, however, can be dangerous and might require additional quoting. Another option is to use `string split ' '` on the output of llvm-config.

**Comment by lodo1995** [comment]
Ok. Thank you very much for your explanation. Now I know how to deal with it.

Maybe it would be a good idea to add a syntactic option (like some special character just before/after the open parenthesis) to select the kind of splitting (space/line/none).

I now realise that the documentation briefly talks about how it works (in the part about parameter expansion), but it is not in the tutorial (I expected it in the part about command substitutions). So maybe it should be better explained.

Thank you again for your answer and for your great shell.

**Comment by faho** [comment]
@lodo1995: I've changed the tutorial in 822ee63. I'm assuming the question is answered, so I'll close this.
