### ISSUE TITLE
No newline after typing command and pressing enter

### ISSUE THREAD

**Issue by miqlas** [fish-shell/fish-shell#4100]
Fish version: fish, version 2.6.0
OS: Haiku x86_64 hrev51178
echo $TERM : xterm (Haiku standard Terminal application)

Tested without third-party mods, with clean settings. Reproducible.

Steps to reproduce:

- open Terminal (i assume fish is the default shell, you can set it in /boot/system/settings/etc/passwd , it requires reboot)
- type commands
- press enter

![6e7](https://cloud.githubusercontent.com/assets/5569059/26764810/5f3d6904-496e-11e7-98f6-30623d40a301.png)

**Comment by miqlas** [comment]
Here is an up-to-date VmWare image with all the required stuff to test this bug:
http://extrowerk.com/temp/haiku_x86_64_vmware.zip

NEW! Now with 100% more preinstalled vim :)

**Comment by krader1961** [comment]
There is something wonky about stdio buffering on Haiku. The `fputwc(L'\n', stdout);` near the bottom of `reader_readline()` should result in a newline being written to the terminal but it doesn't. Or at least it doesn't happen synchronously with the write. Replacing that with a simple `write(1, "\n", 1)` has the desired effect. Note that fish already forces non-buffered I/O using `setvbuf()` without effect.

It's not clear why we're using `fputwc()` there. Presumably to avoid mixing stdio with low-level I/O. Something that is always risky. However, in this case it should be safe. But that still leaves the question of what exactly is wrong with Haiku.

**Comment by krader1961** [comment]
@miqlas, I've determined the problem is due to a bug in the `setvbuf()` function on Haiku. Fish calls it to set stdout to fully unbuffered. That causes any subsequent writes using that file handle to discard the output. It only seems to affect wide char output. If you compile and run the following program you'll see that "goodbye" isn't seen:

```
#include <stdio.h>
#include <wchar.h>
int main() {
    fwprintf(stdout, L"hello\n");
    setvbuf(stdout, NULL, _IONBF, 0);
    fwprintf(stdout, L"goodbye\n");
}
```

If you switch to `fprintf()` it works.

I think I'm still going to replace the `fputwc()` calls with simple `write()` calls since that should be okay but you should file a bug with the Haiku project about this.

**Comment by miqlas** [comment]
I'll create a bugreport asap, thanks for the Info!

**Comment by waddlesplash** [comment]
(the bug report is here: https://dev.haiku-os.org/ticket/13544)

Thanks for providing us with a reduced testcase!
