### ISSUE TITLE
Variable for current command

### ISSUE THREAD

**Issue by Dreamsorcerer** [fish-shell/fish-shell#4111]
It would be useful to have a variable which contained the current running commandline.

i.e. The same value that is passed to fish_preexec before executing a command should be available to those commands as a variable.

**Comment by krader1961** [comment]
This was opened in response to the questions in issue #4096.

What should the variable be named? When should it be set? What should it include? Just the command name being run? The command and its args? What about redirections? What about statements like this: `cmd1 (cmd2 arg1 arg2 > x; alert) >y`? When `alert` runs what should this proposed variable contain? Is this variable set only for interactive commands?

If we implement issue #154 you would be able to create an `alert` function that takes another command and its arguments to run and safely do so without needing to use the dangerous `eval`. That would seem to solve the original request in issue #4096. In which case is this still needed?

**Comment by Dreamsorcerer** [comment]
As I said, the same value that is passed to fish_preexec, the full commandline, would be absolutely fine. Another way of putting it, is whatever value will be written to history after the commandline has finished executing (given that is what I'm using in Bash).

I'm not sure what the eval function has to do with anything, perhaps I've not described my alert function well enough, so here is the actual code.

Bash:
```
# Add an "alert" alias for long running commands. Use like so: sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
```

Fish attempt:
```
function alert
    notify-send --urgency=low -i ([ $status -eq 0 ]; and echo terminal; or echo error) "$_ :: $argv"
end
```

**Comment by faho** [comment]
To me, this seems like something you'd want to use the `commandline` builtin for.

Unfortunately, it is erased before any command is run. It seems possible to change that, though I'm unsure if it would break anything else. I don't think so because `(commandline)` is currently empty when running a command. It would mean that you couldn't _set_ the commandline via executing a function. I have no idea if anyone uses that.

Changing that would allow the following:

```fish
function alert
    commandline | read -lz commandline # commandlines can't contain a NUL,
                                       # so this will handle multiple lines (see #159)
    notify-send --urgency=low -i \
    (test $status -eq 0; and echo terminal; or echo error) \
     "$commandline"
end
```

The alternative is adding it to $history earlier, but that _is_ likely to break stuff (any command that accesses $history[1] to get the previous element would have to be changed).

Or, as is requested here, adding a special variable "$next_history" or so, that contains what will later be added to $history.

**Comment by krader1961** [comment]
> I'm not sure what the eval function has to do with anything

I should have elaborated. I'll do so now. At this time if you want to write a function that accepts another command (and optional args) to run you have to use eval to do so. For example:

```
function alert
    eval $argv
    notify-send --urgency=low -i ([ $status -eq 0 ]; and echo terminal; or echo error) "$_ :: $argv"
end
```

This allows you to type `alert long_running_command arg1 arg2`. The problem is that `eval` is dangerous as it causes the parser to evaluate the arguments a second time. You can use `string escape` to mitigate the danger but it's a pain in the ass to have to do so. If we address issue #154 your function becomes

```
function alert
    call $argv
    notify-send --urgency=low -i ([ $status -eq 0 ]; and echo terminal; or echo error) "$_ :: $argv"
end
```

Also, what would the semantics be if you typed `long_cmd1; alert; long_cmd2; alert`? If I understand the request both `alert` invocations would get the entire command line. Seems less than optimal to me.

Note that there is a way, sort of, to do this today in fish. Simply press [enter] to execute the first command and then type `alert` to have it run when the first command completes. I recognize this isn't really ideal but it does work. My preference is to treat `alert` like `sudo` or `env`: as a command that takes another command to be run.

> this seems like something you'd want to use the commandline builtin for

Maybe but I have misgivings. Not least because you've now changed the semantics from a command that can only be used to manipulate a command line while it is being typed to something that can be used at anytime to fetch, but not modify, the current statement. This also means that trying to use flags like `--current-token` would be an error in this hypothesized new use case.

**Comment by evert-mouw** [comment]
It would be nice to be able to change or rewrite the current command before execution. The `function preexec_test` hook is nice; it can be used to evaluate the current command and take actions. But I still cannot change the current command, e.g. to automatically fix something.

**Comment by faho** [comment]
I believe this is now `status current-command` and `status current-commandline`.

**Comment by Dreamsorcerer** [comment]
Great, do you know which version current-commandline was introduced in? (Doesn't appear to be mentioned in the docs)

**Comment by faho** [comment]
The changes are listed in [the CHANGELOG](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.rst), `status current-commandline` was 3.6.0.
