### ISSUE TITLE
How to quickly load the Fish environment for scripts?

### ISSUE THREAD

**Issue by JeanMertz** [fish-shell/fish-shell#412]
I would like to use Fish for my scripting needs when writing git hooks or other shell scripts. However, I've noticed quite a delay when git launches hooks that are written in Fish, compared to say `sh`.

I tried looking for a command with `fish --help` that would maybe solve this by not loading all my configuration files, but I couldn't find anything. Is there a way to use the shebang `#!/usr/local/bin/fish` and have it load as fast (or comparable) as `/bin/sh`?

**Comment by faho** [comment]
I've done some benchmarks a few weeks back that found fish actually starting _faster_ than both bash and zsh, the latter with a much smaller than usual config file.

Quite a bit has changed with fishd being removed and a couple of builtins (echo, printf) being added since this has been opened.

So I'm closing this.
