### ISSUE TITLE
Failed to execute process '/usr/share/fish/tools/create_manpage_completions.py'

### ISSUE THREAD

**Issue by jimbobmcgee** [fish-shell/fish-shell#4121]
*fish version: 2.3.1 (installed on CentOS 7.3.1611, via EPEL)*
Out of the box, running `fish_update_completions` fails with the error message:
```
Failed to execute process '/usr/share/fish/tools/create_manpage_completions.py'.  Reason: The file '/usr/share/fish/tools/create_manpage_completions.py' does not exist or could not be executed.
```
I usually understand this to mean that whatever interpreter required to run that script (i.e. Python) is not installed, but this persists, even after installing Python 3.4.

If I manually edit the create_manpage_completions.py file, I can see that the hash-bang statement reads 
```
#!%{__python34}
```
I *presume* that this is some sort of build macro, that is supposed to be replaced with the real location of python3.4 (or compatible) but, since this wasn't installed beforehand (no dependency shown in the `yum install fish` output), I guess this doesn't happen.

Manually adding...
```
#!/usr/bin/env python3.4 
```
...to the top of the file resolves, as a workaround (assuming `yum install python34` has since been run).

Not sure if this is a packaging issue, or an upstream one; just reporting my findings, since Google wasn't particularly helpful...

**Comment by faho** [comment]
So, this is most certainly caused by EPEL/Fedora's packaging, since our scripts just all use `#!/usr/bin/env python` (and in fish 2.6.0 we changed it so our _wrapper functions_ try `python3`, `python2` and `python`).

In fact, I'm quite sure that it is caused by http://pkgs.fedoraproject.org/cgit/rpms/fish.git/commit/fish.spec?h=epel7&id=178a776c867c4c4839641e816bba07b6ff53bb2b.

@amluto: Mind taking a look? Also, I know that you were a bit bothered by us calling `python`, so you might want to either upgrade fish to 2.6.0 or cherry-pick 7ef2d5e86fb8dc75a6fc316a7a7cc5400709bcfa, e410d475655e68628279aa1286a2a21ffa5fadf0 and 805a1776733061fabf65409bb30568a253762a3e.

**Comment by faho** [comment]
@jimbobmcgee: Please report this to the EPEL/Fedora folks. Feel free to quote me!
