### ISSUE TITLE
Tab completions shouldn't move the cursor when there are no completions

### ISSUE THREAD

**Issue by rolag** [fish-shell/fish-shell#4124]
I think it's kind of annoying that fish moves the cursor to the end of a token when `<TAB>` is pressed and no completions are found.

To reproduce:
```fish
# Replace bar '|' with cursor and press <TAB>
mpv --|'https://...very-very-long-url...'
foo /path-typo|:/usr/lib
```

```
Version: 2.6.0-65-gedaef4e6-dirty
OS: Linux Debian (Unstable) 
Terminal: gnome-terminal, xterm
```

If this sounds like a good idea and would be merged, I'd like to have a go at this issue.

**Comment by faho** [comment]
I believe I agree - getting back to the old cursor position is hard (you need to remember it and then use some movements), while getting to the end of the token is trivial. I can't see a good reason for keeping the status quo - if there is a matching completion going to the end is good because you're most likely done with it, but since there is none here you might need to modify the current token some more - so I'd accept something.

>I'd like to have a go at this issue.

Go!

**Comment by krader1961** [comment]
FWIW, I can't tell from the original problem statement what the problem is. And thus cannot evaluate the proposed fix. Is this really a priority for the 2.7.0 release?

The problem appears to be that if you type `echo xyz` (which doesn't match any files), then move the cursor left to, say, just after the `x` (which might be valid prefix for some files), then press [tab] it moves the cursor after the `z`. Which seems reasonable to me. So I suspect I don't understand what the problem is.

**Comment by faho** [comment]
>The problem appears to be that if you type echo xyz (which doesn't match any files), then move the cursor left to, say, just after the x (which might be valid prefix for some files), then press [tab] it moves the cursor after the z. Which seems reasonable to me. So I suspect I don't understand what the problem is.

The issue is that it moves the cursor _even when it's not a valid completion_. Say I did `apt install` with the cursor somewhere in the "install" and pressed tab. Fish then moves the cursor to after the token, which is fine because "install" is a valid subcommand for "apt". But if I do "apt isntall" and press tab, it shouldn't move the cursor because I should be fixing that word. It does inform me that it's wrong by blinking, but to then fix the typo I need to move the cursor back again.

This is even weirder because with a correct token (as determined by completions) fish will insert a space after it (so it becomes `apt install |` with the pipe denoting the cursor). With an incorrect one it won't (`apt isntall|`).

**Comment by krader1961** [comment]
Retargeting since this appears to be difficult to improve and isn't a priority for 2.7.0.
