### ISSUE TITLE
Fish doesn't recognize aliases sometimes (WSL)

### ISSUE THREAD

**Issue by iamdevlinph** [fish-shell/fish-shell#4129]
Fish version: 2.6.0
OS: Microsoft Windows [Version 10.0.15063]
Terminal: Bash on Windows using ConEmu64

Fish sometimes doesn't recognize by aliases and I have to run them a 2nd or 3rd time. It happens randomly, hard to isolate.

This is one example.

![image](https://user-images.githubusercontent.com/19337229/27211359-5c226fc8-528b-11e7-8d11-bbb62d25c4ca.png)

As you see, the first `checkout` didn't work but worked on the 2nd time. But the alias `rebase` worked right away.

This is the content of the alias `checkout`.

```ssh
function checkout -d 'git checkout'
    git checkout $argv;
end
```

I've been using `oh-my-fish`. If it is necessary to disable this and try to replicate the issue then I will comply.

**Comment by krader1961** [comment]
Where is the red "X" coming from when you type `checkout pre-prod` the first time? If you add some debug echo statements to the function on either side of the command being wrapped do you see that output the first time you run the command? How did you determine that `checkout` was equivalent to the function you showed us? If you execute `type checkout` before using the command is that what you see?

Frankly, if functions (aliases are just trivial functions) were as unreliable as you imply we would have had hundreds of people reporting this problem.

**Comment by iamdevlinph** [comment]
> Where is the red "X" coming from when you type checkout pre-prod the first time? 

I don't quite understand, but the `X` came out after I type the first `checkout pre-prod`.

> If you add some debug echo statements to the function on either side of the command being wrapped do you see that output the first time you run the command?

Can you provide a specific syntax that I can add?

> How did you determine that checkout was equivalent to the function you showed us? If you execute type checkout before using the command is that what you see?

![image](https://user-images.githubusercontent.com/19337229/27211655-65c9afc6-528d-11e7-899f-0b4f9fccd5e6.png)
![image](https://user-images.githubusercontent.com/19337229/27211705-c1fa5cbe-528d-11e7-8155-9c42d1ec936a.png)

**Comment by krader1961** [comment]
> the X came out after I type the first checkout pre-prod 

Which suggests you weren't running the command you thought you were running or it failed in some unexpected manner.

> Can you provide a specific syntax that I can add?

Edit the function and add `echo run git checkout $argv >&2` before the actual git command and `echo ran git checkout $argv >&2` after it.

Also, did you run that `type checkout` command before you saw the failure? If not then what do you see if you do that? I think at this point we're going to need you to disable OMF and probably all of your other customizations. Please run `env HOME=(mktemp -d) fish`. Then interactively enter the definition for the `checkout` function (just copy paste it). Then invoke it. I'm betting it works just fine.

**Comment by iamdevlinph** [comment]
> Edit the function and add echo run git checkout $argv >&2 before the actual git command and echo ran git checkout $argv >&2 after it.

Will do this for now. Then proceed to the next step.

> Also, did you run that type checkout command before you saw the failure? 

No. The command fails randomly. I will try to run `type <command>` every time I will execute a function.

> Then interactively enter the definition for the checkout function (just copy paste it).

Regarding this one, i will run this?
```ssh
func checkout; git checkout $argv; end
funcsave checkout
```

**Comment by krader1961** [comment]
> Regarding this one, i will run this?

Yes, although you don't need to do the `funcsave checkout`. That is because you are running inside a dummy home environment and saving the function won't make any difference. I'm simply trying to show you that if you define and use that function without any customizations (such as done by OMF) in your normal home environment it works without error.

Honestly, this problem is almost certainly due to something in your fish configuration rather than due to a bug in fish itself. The question is what that "something" is and whether fish can be modified to protect against it. Or perhaps warn when that "something" is detected.

**Comment by krader1961** [comment]
@iamdevlinph, You should not edit your comments other than to fix spelling or grammar errors that do not change the meaning of what you wrote. The only reason I noticed the edit of your previous comment is because the Gitter application alerted me that you had edited your comment. Which caused me to notice you added new information. You should create a new comment if you are adding information to the issue.

You wrote "Unexpectedly, running git lg failed.". But you did not provide details about how it failed.

> Can you tell me how I can provide more details every time a command fails randomly?

No, because such failures are, by definition, idiosyncratic and thus require intuition to debug the problem. Given what you have written so far I am willing to bet the problem has nothing to do with the fish shell. The behaviors you have reported suggests the problem is unrelated to the CLI shell you are using.

**Comment by iamdevlinph** [comment]
> You should not edit your comments other than to fix spelling or grammar errors that do not change the meaning of what you wrote. 

Apologies for that.

I will add the syntax you provided to my functions for now and see how this goes. Then I will get back as soon as I find something.

**Comment by iamdevlinph** [comment]
I added the syntax and here is the result. I didn't run `type checkout`. And OMF is not yet disabled.

![image](https://user-images.githubusercontent.com/19337229/27214580-ce77fd5e-529f-11e7-96d1-08699eb5a789.png)

The first command didn't show an 'X' mark but it didn't checkout.

Here is the file.

![image](https://user-images.githubusercontent.com/19337229/27214592-df2b0dd0-529f-11e7-8b81-c53bb2059266.png)

Do I proceed to disabling OMF? Or I will execute `type checkout` first and get a result?

**Comment by iamdevlinph** [comment]
Here is one with `type checkout` executed.

![image](https://user-images.githubusercontent.com/19337229/27215014-ff5ef3d0-52a1-11e7-926e-9ed2c6780442.png)

**Comment by iamdevlinph** [comment]
There seems to be no issue when running in `env HOME=(mktemp -d) fish`. So the issue is with OMF, then?

**Comment by iamdevlinph** [comment]
I removed OMF and commands still fail sometimes. Like this `fetch` command.

![image](https://user-images.githubusercontent.com/19337229/27223226-2bdb6d4c-52c2-11e7-9de0-db60d4c93ce3.png)

**Comment by faho** [comment]
@iamdevlinph: That `fetch` function is defined in a file called `fetch.fish` in ~/.config/fish/functions? And ~/.config/fish/functions is in $fish_function_path, even when it fails?

Do you have your config.fish (and related files) uploaded somewhere so we can take a look?

Since all of these seem to be git commands, what does `type git` say? It looks to me like the `git whatever` is executed but returns failure ($status != 0), so that should be looked into.

**Comment by iamdevlinph** [comment]
Hmmm. I aliased git with hub, so running `type git` returns

![image](https://user-images.githubusercontent.com/19337229/27236822-0fe2989a-52f9-11e7-8947-15f5bc9f2bef.png)

So it's an issue with [hub](https://hub.github.com)?

**Comment by faho** [comment]
Possibly. Try removing that alias.

**Comment by iamdevlinph** [comment]
I will give that a try and get back with findings.

**Comment by iamdevlinph** [comment]
Removed the alias. Been working great so far. Will try adding back OMF.

**Comment by krader1961** [comment]
I use hub too but only for a couple of its functions. I'm glad I did not set it up as a replacement for git. Instead I created a couple of abbreviations such as `abbr -a gam 'hub am -3'`. In general I recommend against creating trivial aliases for such situations. Abbreviations are usually a better choice since they only affect interactive uses of the command and the immediate expansion on the command line reminds you what is actually being run.

**Comment by faho** [comment]
And now for the bonus round: Why is this failing in hub? Does it also do that when in bash? It's possible there is some kind of weird interaction between fish and hub (though that would most likely mean hub is too fragile). It's also possible this is an issue with windows.

@iamdevlinph: Can you try directly using `hub` in fish? Can you try using it in bash?

**Comment by iamdevlinph** [comment]
`Hub` only fails in `fish`. But it runs consistently in `bash`.

![image](https://user-images.githubusercontent.com/19337229/27250715-549206d2-5368-11e7-9629-317a38e09bff.png)

**Comment by iamdevlinph** [comment]
The previous screenshot was using `ConEmu`.

`hub` also fails in `bash` when using the "native" `Bash on Windows` terminal but not in `fish`.

![image](https://user-images.githubusercontent.com/19337229/27250751-2a4011ac-5369-11e7-9163-f344cfb3d790.png)

Maybe it's safe to assume the problem is with `WSL`?

**Comment by iamdevlinph** [comment]
I'm switching over to `deepin linux` and ditch `WSL`.

Closing this for now.

**Comment by edwincc-vital** [comment]
I'm having the same problem with fish 3.0.2, without oh-my-fish, just plain new install.
i defined my aliases by hand in `~/.config/fish/functions/*.fish`;
that works... when it does.
Very often my aliases are red and unavailable, and I found that using once another alias/command that the former depends on unlocks them... But it won't last. Each new session it's all over again.
Worse, some aliases do not load while they seem available :
for instance I have : 
```
alias l="ls -a"
alias ll="l -l"
```
and sometimes `l` is as expected, sometimes it's like i ran `ll` !!

**Comment by krobelus** [comment]
@edwincc-vital I assume you are on WSL; does it work if you put the aliases/functions in `config.fish`?
If yes, then the issue is with autoloading.

If you can reproduce the freezes, maybe it's useful to look at a profile generated by fish started as `fish --profile profile-file`

**Comment by edwincc-vital** [comment]
> @edwincc-vital I assume you are on WSL; does it work if you put the aliases/functions in `config.fish`?
> If yes, then the issue is with autoloading.
I'm not on WSL, i'm on an Ubuntu 19.10 host.
Sorry, I did't even notice that on this thread's title

But thanks, this does fix the problem with me `ll` alias
However I had to both `functions -e ll` and `alias ll="..."` for it work. I assume fish loads the `functions/*.fish` before `config.fish`... So should I put my alias in the former after all ?? A is, my aliases is not consistant...

> If you can reproduce the freezes, maybe it's useful to look at a profile generated by fish started as `fish --profile profile-file`
Ok, I  will try

**Comment by edwincc-vital** [comment]
also aliases are not accessible at all after `sudo`

**Comment by faho** [comment]
> I guess fish loads the functions/*.fish before config.fish

Not quite. When fish is asked to execute a thing it doesn't know (because the function hasn't been defined yet), it checkes the function files *by that name*.

That means if it's asked to do `l`, it'll check for `~/.config/fish/functions/l.fish`, and if it exists it will load it. If it's asked for `ll` it'll look for ll.fish.

That means you should, if you use function files, name them after the one function they contain.

In particular:

> I found that using once another alias/command that the former depends on unlocks them

Well, if you put multiple functions (which aliases really just are) into one file, then of course they'll only become available once that file is loaded, which will only happen once you've executed the function it is named after.

>also aliases are not accessible at all after sudo

That's because `sudo` runs a new shell, which opens that users configuration.

**Comment by edwincc-vital** [comment]
@faho Thank you alot, I indeed had several alias/functions per file. That's entirely my fault : I didn't read to doc well enough

> > also aliases are not accessible at all after sudo

>That's because sudo runs a new shell, which opens that users configuration.

my alias are accessible from `sudo -s`
that's because my config is duplicated in `/root/.config/fish/`
