### ISSUE TITLE
`wgetopt_long()` fails to correctly parse `function 0 -w0 -+0`

### ISSUE THREAD

**Issue by JacobEdelman** [fish-shell/fish-shell#4131]
In fish version 2.5.0, on "Linux botup 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux". 
The file
```
function 0
end
function 0 -w0 -+0
end
```
causes fish, including just the syntax checking to crash. Meaning:
```
jacob@botup /h/j/S/r/f/afl-shell-tmin> fish -n test
<E> fish: unexpected retval from wgetopt_long on line 1701 of file src/builtin.cpp, shutting down fish
<E> fish: Backtrace:
<E> fish: 0   builtin_function(parser_t&, io_streams_t&, std::vector<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, std::allocator<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > const&, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, int, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >*) + 2319
<E> fish: 1   parse_execution_context_t::run_function_statement(parse_node_t const&, parse_node_t const&) + 507
<E> fish: 2   parse_execution_context_t::run_block_statement(parse_node_t const&) + 160
<E> fish: 3   parse_execution_context_t::run_1_job(parse_node_t const&, block_t const*) + 1627
<E> fish: 4   parse_execution_context_t::run_job_list(parse_node_t const&, block_t const*) + 182
<E> fish: 5   parse_execution_context_t::eval_node_at_offset(unsigned int, block_t const*, io_chain_t const&) + 913
<E> fish: 6   parser_t::eval_block_node(unsigned int, io_chain_t const&, block_type_t) + 486
<E> fish: 7   parser_t::eval_acquiring_tree(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, io_chain_t const&, block_type_t, moved_ref<parse_node_tree_t>) + 201
<E> fish: 8   fish() [0x4b9520]
<E> fish: 9   reader_read(int, io_chain_t const&) + 1226
<E> fish: 10  main + 2909
<E> fish: 11  __libc_start_main + 234
<E> fish: 12  _start + 42
```

Performing `sh -c 'env HOME=$(mktemp -d) fish'` does not help.

Found this via using the [afl fuzzing library](https://fuzzing-project.org/).

The same error also appears on a ubuntu server.

**Comment by krader1961** [comment]
I thought I had fixed this months ago but the `function` option parsing is still broken. I noticed a related problem this week when working on refactoring the *src/builtin.cpp* module. So I'll take ownership and fix this after I complete that refactoring.

I'm assuming you didn't really expect that example to result in a valid function and are only bringing this to our attention because of the nature of the failure. If that is not the case please provide more detail about what you expected to happen.

**Comment by JacobEdelman** [comment]
Yeah, only bringing it up cause it seems to be a failure mode that isn't meant to occur. The other issue would be that this causes a hang which isn't something I'd expect from syntax checking.

**Comment by krader1961** [comment]
FWIW, this is a bug in our `wgetopt_long()` implementation that we copied from GNU long ago and converted to use `wchar_t`. It is not a bug in the `function` arg parsing code. This failure could theoretically happen with any fish command.

**Comment by krader1961** [comment]
The problem is in the `wgetopter_t::_wgetopt_initialize()` method. Notice the two `++optstring;` statements. This is clearly intended to ensure the rest of the code ignores a leading `-` or `+` in the short option string. However, as written those statements have no effect.

**Comment by krader1961** [comment]
Argh! My previous comment is incorrect. That function returns an updated pointer to the short option string that takes into account the increment. The problem is that `wgetopt_long()` doesn't correctly handle this pattern:

```
wgetopter_t w;
while ((opt = w.wgetopt_long(argc, argv, short_options, long_options, NULL)) != -1) {
```

Every call to `w.wgetopt_long()` calls `_wgetopt_initialize()` which parses the flag specification every time it is run rather than just the first invocation. So the first invocation does the right thing but subsequent invocations do not. Current versions of [GNU getopt.c](https://gnunet.org/svn/flightrecorder/src/flightrecorderd/getopt.c) handle this by introducing a `__getopt_initialized` variable. I don't see an equivalent in the fish copy.

**Comment by zanchey** [comment]
Time to re-import/implement wgetopt?
