### ISSUE TITLE
history built-in doesn't work when setting env 

### ISSUE THREAD

**Issue by pik** [fish-shell/fish-shell#4148]
> fish, version 2.5.0
> Linux 4.11.3-1-ARCH

According to the `history --help` description output is sent to the pager, which I guess is specified by `PAGER`. 

         Entries are ordered newest to
         oldest. If stdout is attached to a tty the output will be piped
         through your pager by the history function. The history builtin
         simply writes the results to stdout.

Unfortunately the following invocation `env PAGER=someotherpager history --search keyword` fails with: 

> env: ‘history’: No such file or directory

I don't know if this is difficult to handle architecturally for built-ins but it would be nice if one could specify a different PAGER when searching through history. Maybe a `--pager` flag would be a good compromise if it is hard to get built-ins to play well with `env` ?

**Comment by faho** [comment]
`env` is an external command, and can therefore only run external commands. `history`, as you stated, is a builtin/function. (Adding an `env` that can run functions is #438)

Because of #1091, you'll want to run something like this:

```fish
begin
    set -l OLD_PAGER $PAGER
    set -gx PAGER someotherpager
    history --search something
    set PAGER $OLD_PAGER
end
```

After implementing #438, this would become `env PAGER=someotherpager history --search something`.

With #1091, but not #438, this would be `begin; set -lx PAGER someotherpager; history --search something; end`.

**Comment by faho** [comment]
>it would be nice if one could specify a different PAGER when searching through history.

Out of curiosity: Why a different pager for history?

**Comment by krader1961** [comment]
Like @faho I too don't understand why you would want a different pager for history results. Having said that, other programs (e.g., `git`) support ways to use something other than your standard pager. So I'm not opposed to making that possible for the fish `history --search` output. But I would like a rationale to justify adding the necessary code other than just "it might be useful to someone".

**Comment by pik** [comment]
Sometimes I use vim as a pager depending on the task, also having `env` work would be useful not just for `PAGER` equals, but also for example `LESS=` to specify less options.

**Comment by faho** [comment]
Yeah, sure, that makes sense. Note that #4149 implements that variable thing I talked about, so with it you could do `begin; set -lx PAGER someotherpager; history --search something; end` (or the same without the "begin" and "end" if you then set $PAGER again later).

We'll most likely implement an `env` builtin, but that's tracked in #438. So I'm closing this since I feel all questions have been answered and the remaining things to be implemented already have their own issues.
