### ISSUE TITLE
Fish seems to escape dollar signs before passing them into grep

### ISSUE THREAD

**Issue by cowpig** [fish-shell/fish-shell#4207]
fish, version 2.6.0
ubuntu 17.04
xterm-256color
happens regardless of customization.

When I run
`~$ git grep -e '\\$'`
in bash, I get the expected behavior: a bunch of lines ending in backslash.

When I run
`~$ find . | grep -e '\\$'`
in fish, I get back a bunch of lines with dollar signs in them.

**Comment by krader1961** [comment]
[This](http://fishshell.com/docs/current/index.html#quotes) explains the quoting and escaping rules for fish. If we could go back in time we would change the behavior. We couldn't even change this in a major release because the impact would be too great so we're stuck with how backslashes behave inside quoted strings.

**Comment by cowpig** [comment]
OK, so it seems that to get what I was expecting I need to do
`~$ find . | grep -e '\\\$'`

...but that confuses me. The docs say
> Some characters can not be written directly on the command line. For these characters, so called escape sequences are provided[...]
This implies that I can't use '$', but when I use the dollar sign in single-quotes it seems to work, but effectively add an extra backslash to the left of it?
How does this work?

**Comment by krader1961** [comment]
That sentence you quoted isn't relevant. It's explaining that outside of quoted strings you can specify characters symbolically using the described backslash sequences. Inside of quoted strings those sequences aren't special.

You really need four backslashes. That three work is a quirk of how backslashes work inside quoted strings. The behavior is a wart in my opinion. So `echo '\\\\$'` happens to be the same as `echo '\\\$'` but the former is preferable because it is clearer. And if we ever did change the way backslashes work inside quoted strings the latter (three backslashes) is likely to no longer be valid.

**Comment by krader1961** [comment]
Closing since there hasn't been any followup in several days. Feel free to reopen if you still have questions.
