### ISSUE TITLE
"failed assertion: !is_missing" with empty /etc and environment

### ISSUE THREAD

**Issue by johnchen902** [fish-shell/fish-shell#4229]
This command:

    unshare -mr bash -c 'mount -t tmpfs tmpfs /etc && env -i fish'

will output this to stderr and abort:

    <W> fish: Could not set up terminal.
    <W> fish: TERM environment variable not set.
    <W> fish: Using fallback terminal type 'ansi'.
    <E> fish: src/env.cpp:1150: failed assertion: !is_missing
    <E> fish: Backtrace:
    <E> fish: 0   fish() [0x42960e]
    <E> fish: 1   env_init(config_paths_t const*) + 4152
    <E> fish: 2   main + 1562
    <E> fish: 3   __libc_start_main + 234
    <E> fish: 4   _start + 42

Fish version is 2.6.0 as provided by Arch Linux.
Kernel version is linux-userns 4.11.7-1 as provided in Arch Linux user repository.
TERM is rxvt-unicode-256color.
No third-party customization is used.

Works fine without `env -i` or the mount.
Also works fine if mouting on `/etc/fish` instead of `/etc`.

xterm didn't work.
2.6.0-263-gbb344bbd (master as I just cloned and built) didn't work either.
Didn't work if `env -i` is moved to the front either.
Changing to `env -i HOME=$(mktemp -d)` cause segmentation fault instead.

**Comment by zanchey** [comment]
I have to ask: is this a case that you expect to work (and if so, :confused:), or is this a reduced test case?

**Comment by johnchen902** [comment]
I was developing a sandbox (running arbitrary command) and wanted to limit the memory usage (along with other features). To test, I need a program that use too much memory, and I thought of 

    fish -c "echo (cat /dev/zero)"

And that assertion error hit.

I do expect without any configuration, fish will use whatever default compiled in, or at least fail gracefully.

**Comment by faho** [comment]
Soo.. the issue is that fish, when it doesn't get $HOME (which `env -i` also removes), will try to read /etc/passwd (via `getpwnam()`). Because you've completely emptied /etc, this also won't result in a value. So $HOME stays empty, and we have code that assumes it isn't - the code that tries to read ~/.config/fish/config.fish.

I'm not sure if it is sufficient to set $HOME to the empty list (or possibly the empty string). It's possible that would react badly with some other code.

**Comment by faho** [comment]
>It's possible that would react badly with some other code.

Soo...

- `cd` works by erroring ("Could not find home directory")
- `~` expansion simply does not expand - `~/foo` expands to `~/foo`.

The former is okay, the latter is probably bad, since it might result in writing to a subdirectory called "~". E.g. `mkdir ~/something` would create `./~/something`.

I think the best thing to do is to actually treat it like an empty list, by expanding ~ to nothing.

**Comment by faho** [comment]
We should also do this for string-empty $HOME (`set HOME ""`), because it needs to be a _path_, and tilde-expansion should not result in bogus paths.

That means:

- If we don't get $HOME after all our attempts, it's set like `set HOME`.

- Everything that uses it fails and never results in a bogus path.

- Tilde-expansion in particular results in no argument - `count ~/foo` prints "0".

- The latter is even if $HOME is set like `set HOME ""`.

Note that there is nothing we can do here to make $HOME-using code _work_ - whether it is `mkdir ~/foo` or `mkdir $HOME/foo`, there is no sensible place to create that directory (no, falling back to e.g. /tmp is _not_ it). The best thing to do is to try to ensure that we don't touch other directories.

We could also warn, but I'm willing to bet that 99.9999% of cases of $HOME not being set happen due to something like this, and in that case you've already gotten a warning on start, so that would just be additional noise.

**Comment by faho** [comment]
@johnchen902: 529ba30 should fix this.

**Comment by johnchen902** [comment]
> 529ba30 should fix this.

Unfortunately it didn't.

> Changing to `env -i HOME=$(mktemp -d)` cause segmentation fault instead.

So I don't think it's only about missing HOME.

**Comment by faho** [comment]
Aaah crud, $USER is empty as well.

**Comment by faho** [comment]
Aaah crud, $USER is empty as well.

**Comment by faho** [comment]
Okay, fixed that.

Aaand now the uvar stuff is crashing....

**Comment by faho** [comment]
@johnchen902: Please try again.

Note that I still can't quite recommend you run without $USER and $HOME, as it will very much result in degraded operation, but now it shouldn't crash.

**Comment by johnchen902** [comment]
Thanks, it works now.

Well, I don't think such degration matters to whoever intentionlly run in such an environment. 😈

**Comment by krader1961** [comment]
> fish -c "echo (cat /dev/zero)"

FYI, In fish 3.0 we're going to limit how much data subcommands will capture so that trick won't work anymore. We already limit how much data `read` will capture.
