### ISSUE TITLE
Setting `FISH_HISTORY` variable breaks syntax highlighting & tab completion

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#4234]
```
$ fish --version
fish, version 2.6.0-269-g9ef47a43
```

[As discussed on Gitter](https://gitter.im/fish-shell/fish-shell?at=59727a28614889d475da557b), setting `FISH_HISTORY` to any value (e.g. `test` or `""`) breaks syntax highlighting and tab completion.

![28484318-8a86c6d0-6e69-11e7-916f-4cbe08c27cbb](https://user-images.githubusercontent.com/8544900/28484366-c3e92d46-6e69-11e7-9ed3-53fc4449b366.png)

**Comment by floam** [comment]
This is caused by `reader_push()` resetting this stuff when reacting to the variable change.

**Comment by krader1961** [comment]
Obviously we should try to fix this for the 2.7.0 release if possible. But should it block that release? This is a niche feature used mostly for demos. And while we want to make it easy for people to use fish for demos involving the shell CLI it's not clear this problem should block our final 2.x release.

**Comment by zx8** [comment]
@krader1961 I don't think it's reasonable for this to _block_ the 2.7.0 release – perhaps it's more sensible to flag it as a known issue in the release notes and follow up with a fix in 2.7.1?

**Comment by krader1961** [comment]
To expand on @floam's analysis a bit... The problem is that at the point we react to `FISH_HISTORY` being set we're already inside `read_i()` accepting interactive commands and executing them. And that function does all the setup on entry needed to enabled completions, autosuggestions, etc. Then we turn around and call `read_push()` which, as @floam noted, resets most of that setup. What the person who made implemented this feature, and I, expected was that `reader_push()` would result in a new `read_i()` context being created. But that doesn't happen. TBD is the correct mechanism for changing the history file on the fly. And despite my previous comment I think this should block the 2.7.0 release. We really want to avoid a 2.7.1 release if possible.
