### ISSUE TITLE
Test completion scripts?

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#4249]
As discussed in #4241, it would be nice if we could test completion scripts.

The problems I see are:

>- We cannot guarantee that every single tool for every single completion is installed, so we need to allow for skipping tests (which we currently don't)
>
>- Completions often depend on a bunch of data (in fact that's the most interesting ones), so we'd need to ship that (e.g. a fake git repository for the git completions)
>
>- Tools often change their output based on configuration (which is generally okay), so we'd need to override that

@thalesmello suggested using docker as a dependency to set up containers with the tools installed. I don't have much experience with docker (about 15 minutes of mucking around with it), but that does seem like overkill to me. In particular AFAIK it requires root to run a service. But it's also possible my inner beard is too grey.

I also don't feel like skipping some tests depending on what is available is too much of a problem - these tests are going to have the most impact when someone is working on a completion script. Changes in the completion _system_ are bound to cause changes in a bunch of scripts, so it's likely to be caught even if not all scripts are tested.

Then again, deliberate changes in the completion system might cause us to need to rewrite all the script tests - imagine we change the ordering to be the other way around.

**Comment by krader1961** [comment]
Can someone who actually uses Docker explain how the fish project would use it? I went to https://www.docker.com and read about the use cases which include continuous integration. But apparently this is another service, like Suse Open Build Service (OBS), that we need to setup and manage. Which would be acceptable if we were a large project like Apache HTTPD. But it is far from obvious to me that the benefits of setting up and managing Docker containers for our unit tests outweigh the costs. And how would this integrate with Travis or something like it? If we did this and I run `make test` on my workstation or laptop will it require connections to the Docker cloud?

**Comment by thalesmello** [comment]
@faho @krader1961 Sorry for the delay in answering this issue. Here are my thoughts:

Docker provides a standardized way to build *containers*, which isolate its own dependencies from those of the system. It's very similar Virtual Machines, as they run in a virtualized environment, but they are generally more lightweight and can use the same resources as the host machine (as opposed to having its own separated virtual RAM, disk, etc).

If we were to use it with fish, the step by step would be:

1. Write a *[Dockerfile](https://docs.docker.com/engine/reference/builder/)* that builds a container with the `fish` binary and the tool we wish to test
2. Build the Dockerfile, which will generate an *image*
3. Use the `docker run` command to execute a suite of tests using the image from the previous step
4. Repeat steps 1 through 3 for every completion script we wish to test

The advantage of using this approach would be that docker would be the only dependency needed to execute the test suite. It would be able to build images with whatever versions of `node`, `python` or `java` we would want to. Also, because the images are standardized, we would guarantee the execution environments are always the same, which would make it easy to reproduce errors whenever they occur.

The disadvantage would be the complexity involved in setting everything up. It would take a long time writing Dockerfiles for all the projects, set up the first test suites. Also, building all the different docker images would increase the whole build time of the project significantly.

In order to execute the tests in the continuous integration, we would just need to include the `docker run` commands in the script Travis runs to test the project. So that would be straightforward.

My particular opinion is that using Docker would be the best way of including tests for the completions, but it might **not** be worth it due to all the complexity involved.

@derekstavis (a friend of mine with a lot more experience in Docker), do you have any ideas regarding this issue?

**Comment by faho** [comment]
>The advantage of using this approach would be that docker would be the only dependency needed to execute the test suite. It would be able to build images with whatever versions of node, python or java we would want to. Also, because the images are standardized, we would guarantee the execution environments are always the same, which would make it easy to reproduce errors whenever they occur.

Soo... that solves problem 1. We could guarantee that a container (this would also apply to other solutions) contains tools we want to test.

HOWEVER:

- There are some tools we'd want to test that aren't usually available on the same system (e.g. yum/dnf and apt), so we'd have to build them into the image.

- This does essentially _nothing_ to help with configuration - which is a large issue in conjunction with the point above (we'd have to set up apt and dnf so that they can actually print stuff).

- Some things aren't even available on the same _operating system_ - think macOS specific tools.

- This basically _reduces_ our test coverage, because tests are only ever run on the blessed container - no newer versions of the tools to be completed.

IMHO, that last point kills it. The most interesting cases for testing completions are different tool versions, and different configuration.

Not to mention the complexity of setting up a container that tests multiple completions properly.

**Comment by zanchey** [comment]
I think it would be worth doing some testing of the completions for things we are (almost) guaranteed to have - `git` would be the obvious choice as the completion exercises many parts of the shell.

**Comment by krader1961** [comment]
Note that there is some basic testing of expansions, the pager, and the completion logic in *src/fish_tests.cpp* but that obviously doesn't test the `complete` command and how tab completing works. I don't think think there is enough value in testing a broad swath of the completion scripts to warrant the added complexity of things like Docker containers. But I do like @zanchey's proposal to explicitly test something like the git completions. Anyone running `make test` should have git installed. And it's trivial to add that as a dependency to the Travis test environments.

**Comment by krader1961** [comment]
Having read this article, http://www.techrepublic.com/article/why-the-biggest-container-lock-in-threat-may-not-be-hardware-or-software-related/, I'm now certain we do not want to add a dependency on Docker or any other container technology. The costs far exceed the benefits. Too, we really only need to test one, maybe two, completions (such as those for `git`) to have confidence the completion subsystem is working correctly. And we don't need containers to do that.

**Comment by reitzig** [comment]
IMHO, what we (= people who write sets of completion with `complete`) need is a function that takes the prompt string as input and spits out the completion result (using the same definitions as a shell loaded by `fish` in the same "place"). Some form of interface to the internal completion functions, that is.

For example:

```
> fish-complete "git che"
checkout
cherry-pick
> fish-complete "git checkout "                                                                                                                                                     FETCH_HEAD  
issue-10
ORIG_HEAD
origin/master
<snip>
```

Writing completion tests would be trivial then. Not sure what the excitement over Docker is about in this context.

**Comment by zanchey** [comment]
Did you mean `complete -C"your command"?

```fish
> complete -C"git ch"
cherry-pick	Apply the change introduced by an existing commit
checkout	Checkout and switch to a branch
```

**Comment by reitzig** [comment]
Hah, how did I miss that? Thanks a bunch, exactly what I needed!

**Comment by faho** [comment]
>Not sure what the excitement over Docker is about in this context.

@reitzig: One thing we need to solve is that most completions depend on some sort of system state. For git for example, while `git ch` will always complete "checkout" and "cherry-pick", it might also complete "ch-my-alias". And when you then go on, `git checkout ` will complete branches/tags/commits/etc from the current git repo (which could also be not a repo at all).

So if you then did the naive thing and simply executed `complete -C` as part of the test suite, you'd have different output depending on the system. Which means you have no real way of knowing (automatically) whether the output is correct or not. Which defeats the point of having a test.

So with docker or other solutions, you'd pack up a git repository as a test case, so that you can run the test everywhere.

Now, docker would also come with its own git, which means you wouldn't have different git versions that people have on their systems run the test (which would have been helpful recently where I accidentally committed something that required a git version from the current year), and it's also probably overkill when, for git at least, a tarball would be perfectly okay.

**Comment by faho** [comment]
We now have some tests for the git completions, that path is workable - just test it if the thing is installed.

The git completions are also the juciest to test.

So this just remains an ongoing process so there's nothing really specifically actionable here. Closing.
