### ISSUE TITLE
Hidden characters in this string cause output problems.

### ISSUE THREAD

**Issue by tylerhjones** [fish-shell/fish-shell#4251]
Shell struggles to deal with characters in this string 'l~107~*￺~7'

fish version: 2.6.0
os: osx 10.12.2
term: iTerm2 3.0.15

https://asciinema.org/a/pHJbe2nPNT9vxWJvkqrqZP3nb

executed running with `sh -c 'env HOME=$(mktemp -d) fish'`

more info about the string in question:
```
bash-3.2$ echo "l~107~*￺~7" | xxd
00000000: 6c7e 3130 377e 2aef bfba 7e37 0a         l~107~*...~7.
```

**Comment by krader1961** [comment]
The problem is the 0xef 0xbf 0xba sequence. That's unicode [code point \uFFFA](http://www.fileformat.info/info/unicode/char/fffa/index.htm). It's visible width is zero and that confuses fish. I'm not going to make this an enhancement request because, frankly, there are lots of weird corner cases like this that we will never handle correctly until we switch to using something like the Boost library.
