### ISSUE TITLE
Man completion not working with new Homebrew packages

### ISSUE THREAD

**Issue by Palivec** [fish-shell/fish-shell#4258]
Hi !

I recently installed Fish via Homebrew package manager on OSX, where I already had couple of Homebrew packages installed. Fish correctly built man completions for the previous Homebrew packages, however, when I now install a new Hombrew package with a new binary, Fish will not integrate it into its man pages completion. (The completion for the binary itself works, its the man completion which is missing.)

I made no modifications, "fish_update_completions" runs but doesnt help, finishes with "2439 / 2439 : zic.8". Maybe Im missing some configuration, but this should work out of the box.

fish, version 2.6.0
16.7.0 Darwin Kernel Version, OSX 10.12.6
OSX Terminal 2.7.3 (388.1.1)
Homebrew 1.2.5

**Comment by krader1961** [comment]
Works for me. Do you have `MANPATH` set? If you do and it doesn't include */usr/local/share/man* then you won't get completions from the Homebrew man pages. If you don't `fish_update_completions` will search */usr/share/man* and */usr/local/share/man* and thus should include Homebrew man pages. Also, keep in mind that this is a best effort. Fish can't generate completions from every man page.

**Comment by Palivec** [comment]
Both the mentioned directories are in `MANPATH` variable and in a result of `manpath` command. A man page `/usr/local/share/man/man1/mpg123.1 ` exists and _can_ be read via the man command.

Ill try to clarify the problem. For example, I installed `mpg123` command. Fish _does_ correctly display completion for the mpg123 itself, but mpg123 doesnt appear in the _man_ completion command list. When I type `man mpg` and I press Tab, mpg123 wont appear in the list.

Another thing - if I type `man -k . | grep mpg123`, mpg123 wont be in the list, but the man page does exists and it _can_ be displayed. As if `man` didnt know that it had the page unless you explicitely asked for it :-)

It might not be a Fish issue, but in Bash and its completion it all works well.

**Comment by krader1961** [comment]
Let's start with the `man -k . | grep mpg123`. That obviously has nothing to do with fish. But it does provide a clue as to the reason `man` completions don't include the Homebrew commands. Those completions are generated by the `__fish_complete_man` function which relies on the `apropos` command. And `man -k` is just another way to invoke `apropos`. So there is something wrong with your config. Most likely explanation is your */etc/man.conf* file is misconfigured. For example, does it include these three lines:

```
MANPATH	/usr/local/share/man
MANPATH_MAP	/usr/local/bin		/usr/local/share/man
MANPATH_MAP	/usr/local/sbin		/usr/local/share/man
```

Once you fix whatever is keeping `apropos` from enumerating the Homebrew man pages you'll find that the fish `man` completions include them in the available selections.

P.S., `fish_update_completions` can't fix this because it only generates what are known as "fallback" completions. Fallback in the sense they are only used if an explicit completion for the command doesn't exist (e.g., a script in */usr/local/share/fish/completions*). And since the `man` command has an explicit completion the one created by `fish_update_completions` won't be used.

**Comment by Palivec** [comment]
Solved :-)

There is a whatis database containing all commands and their short descriptions. These are used in apropos command but also in Fish man completion. The database had to be updated via `sudo /usr/libexec/makewhatis  /usr/share/man  /usr/local/share/man` Its the first time I had to update it manually though.

Thanks for your help !
