### ISSUE TITLE
New shells reinstate an erased fish_greeting

### ISSUE THREAD

**Issue by cljacobs** [fish-shell/fish-shell#4263]
Version: 2.6.0
OS: Arch Linux
$TERM: xterm (qterminal)

Minor quirk with the greeting.
I noticed that the after running a system upgrade this morning that the Fish greeting was back and wouldn't go away no matter how many times/ways I tried to set get rid of it from the terminal, e.g.:

    set fish_greeting; echo $fish_greeting; fish
    #
    # Welcome to fish, the friendly interactive shell

    set -e fish_greeting; echo $fish_greeting; fish
    #
    # Welcome to fish, the friendly interactive shell

    set -x fish_greeting; echo $fish_greeting; fish
    #
    # Welcome to fish, the friendly interactive shell

    set -Ue fish_greeting; echo $fish_greeting; fish
    #
    # Welcome to fish, the friendly interactive shell

While trying to figure out how I had turned it off before, I found this line in my `config.fish` that had been there since forever:

    set -ex fish_greeting

Turns out that by removing the erase option, the greeting finally disappeared. I also tested removing that line from `config.fish` entirely. The same thing happens: if `$fish_greeting` is erased it will be regenerated, but if it is blank it will remain blank.

I'm not sure this is a bug, per se, since the FAQ explicitly demonstrate setting this variable to a blank value, but it was weird that this used to work and now it doesn't.

**Comment by krader1961** [comment]
The main problem is that `set -ex fish_greeting` doesn't do what you expect. It erases (unsets) the `fish_greeting` var. You can't both erase (unset) and export a variable. Those two flags don't make sense together. The `set` command has undergone a lot of revisions recently. It wouldn't surprise me if older versions treated the `-x` flag with higher precedence than the `-e` flag and the rewrite of the `set` command changed it so `-e` has higher precedence.

Your other attempts, such as `set fish_greeting; echo $fish_greeting; fish`, fail to have the outcome you expected because that's not how variables work. Doing `set fish_greeting` creates a variable visible only in the current shell. When you start a new shell it can't see that empty var.

I see that even the current git head code doesn't warn about using `-e` with `-x`. I'll fix that.

**Comment by cljacobs** [comment]
Ah, that makes sense. Thanks for the info.

However, setting `$fish_greeting` in a shell does appear to be inherited by subsequent invocations of Fish even if not explicitly exported:

    ...> set fish_greeting "HELLO"; echo $fish_greeting; fish
    HELLO
    HELLO
    ...> set fish_greeting; echo $fish_greeting; fish
    
    ...> # <- prompt is here now after single blank line from echo

I'm assuming this is because at some point the `$fish_greeting` variable gets marked as universal with `set -U` in `/usr/share/fish/functions/__fish_config_interactive.fish`. If you explicitly erase it and then reset it, it will behave as you described:

    ...> set -e fish_greeting; set fish_greeting "HELLO"; echo $fish_greeting; fish
    HELLO
    Welcome to fish, the friendly interactive shell
    ...> set fish_greeting "HELLO"; echo $fish_greeting; fish
    HELLO
    HELLO
    ...>

Actually, testing further, the logic is even a little weirder than that. I'll have to take a look at what exactly is happening in that file (at least, I believe it's in that file) around where the greeting occurs, but from the following I gather that the empty string is even more special than simply a marker for "do not greet, not even with an empty line".

    ...> set -e fish_greeting; set fish_greeting "HELLO"; echo $fish_greeting; fish
    HELLO
    Welcome to fish, the friendly interactive shell
    ...> set -e fish_greeting; set fish_greeting; echo $fish_greeting; fish
    
    ...> set -e fish_greeting; set fish_greeting "HELLO, AGAIN"; echo $fish_greeting; fish
    HELLO, AGAIN
    Welcome to fish, the friendly interactive shell
    ... >

**Comment by krader1961** [comment]
> I'm assuming this is because at some point the $fish_greeting variable gets marked as universal...

Correct. Universal variables aren't inherited in the usual sense of that word. It's more accurate to say they are shared among all instances of fish running on the machine.

> ... I gather that the empty string is even more special than simply a marker for ...

It's hard to tell if you're thinking `set -e fish_greeting` sets the var to an empty string. It doesn't. It erases, that is, unsets the var. What I think is confusing you is the relationship between local, global, and universal variable scopes. More specifically, what happens when you do something like `set fish_greeting` when a uvar of that name exists versus what happens when it is not a uvar. Keep in mind that "exported" (what you get from `set -x`) is not a visibility scope. Think of it as a modifier that simply determines whether the var is put in the environment of child processes. See the documentation: http://fishshell.com/docs/current/index.html#variables.

**Comment by cljacobs** [comment]
My apologies if I wasn't being clear. I understand that empty is not the same as unset. I was just surprised by the difference between these two examples:

*Example 1*: Unset `fish_greeting`, then set it to the string "HELLO", then invoke a new instance of fish.

    ...> set -e fish_greeting; set fish_greeting "HELLO"; echo $fish_greeting; fish
    Welcome to fish, the friendly interactive shell
    ...>

Result: The fresh Fish instance does not see the "HELLO" value and prints the default greeting.

*Example 2*: Unset `fish_greeting`, then set it to nothing, then invoke a new instance of fish.

    ...> set -e fish_greeting; set fish_greeting; echo $fish_greeting; fish
    ...>

Result: The fresh instance of Fish picked up on the empty variable and did not print any greeting.

In both cases `fish_greeting` was erased and then set to "something" (even if one of those somethings was nothing; it's no longer unset), but only in one of those cases did the effect of the variable remain local.

**Comment by krader1961** [comment]
That's a consequence of the scoping rules I pointed you to earlier plus the fact that the `__fish_config_interactive` sets it as a uvar if it isn't already set. It also depends on you doing the commands in example #1 first. Run `set -qU fish_greeting; and echo is universal var` then `run set -gU fish_greeting; and echo is global var`. Note too that uvars are instantiated as global vars when the shell starts running. Which further muddies the waters.

Don't feel bad. This is confusing. And it's one reason I don't recommend exporting universal variables (`set -Ux varname`).

**Comment by krader1961** [comment]
I'm going to close this since I think the question has been answered. Feel free to add more comments or reopen, @cljacobs, if that is not the case.
