### ISSUE TITLE
Change directory taking very long time (5+ min)

### ISSUE THREAD

**Issue by elrichindy** [fish-shell/fish-shell#4278]
`Running fish 2.6.0 on
Linux <servername> 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux with
xterm-256color`
I have installed omf, z and the sushi theme (also happened with one of the default git theme)
Not happening on my wsl instance only my Ubuntu server

Running fish with the command sh -c 'env HOME=$(mktemp -d) fish' does not exhibit the same behaviour however I haven't used it long enough to be 100% sure.

Often when using cd the change can take 5-10minutes.
I did a fresh install of Fish with omf, then z then sushi-theme and thought all was good but started happening again.
A similar issue was pointed to in #1878
However i'm not sure how to solve this issue or where to start trying.
Most i've looked at regarding the similar ticket is checking the git_is_repo function in case it was failing and causing it to freeze but seems to work correctly.
Loving fish but this is becoming a major problem and not just related to sushi theme.

**Comment by krader1961** [comment]
Okay, if running fish in an empty home directory doesn't exhibit the problem it is almost always due to a customization you have installed (often related to the `fish_prompt`) function that is performing some really expensive operation. A good starting point is to the the fish profiling feature. Start a new fish instance by running `fish -p /tmp/fish.profile` then after you have reproduced the problem type `exit`. Then sort the results: `sort -k2n /tmp/fish.profile >/tmp/fish.txt`. Look at the last ten to twenty lines. If it isn't obvious where the time is being spent attach that file to this issue.

**Comment by faho** [comment]
Since this is related to changing directory, the obvious suspect is `z` (a tool used to change directory depending on frequency and recency), which [does stuff when $PWD changes](https://github.com/sjl/z-fish/blob/master/z.fish#L18-L20) and keeps its own history. Check if removing just z fixes the issue, then see how large the z-datafile is (should be in ~/.z).

Then open an issue at https://github.com/sjl/z-fish/issues.

**Comment by elrichindy** [comment]
It definitely could be z looking at the last few lines, I'll disable z for the time being and see how that goes and have attached the file here for confirmation as I'm not entirely sure what i'm looking at here. What are each of the columns?
[fish.txt](https://github.com/fish-shell/fish-shell/files/1189097/fish.txt)

**Comment by krader1961** [comment]
The problem has @faho guessed that actually running the `z` command is the problem. You ran `cd` 137 times which caused `z --add $PWD` to be run 297 times for a total of 931 seconds (15.5 minutes):

```
931511170       931511170       ----> bash -c '
297     931513692       ---> z --add $PWD
81      931513794       --> z.pwd VARIABLE SET PWD
137     931513931       -> builtin cd $argv
```

That is one seriously broken utility from a performance viewpoint.

**Comment by faho** [comment]
>It definitely could be z looking at the last few lines

It _is_ z.

>What are each of the columns?

"Time" and "Sum" (i.e. the time it takes to execute that and all subcommands - if the command is a function, then that will include everything _inside_ the function) in microseconds.

The "third column" (the "-->" stuff) is for alignment, to print a tree-like structure.

So in this case you have `builtin cd $argv` taking 137 microseconds itself, but the `--on-variable PWD` event it causes takes 931 seconds. From context we can infer that that is mostly spent in `z.pwd`, which itself spends most of its time in `z --add $PWD`, which itself spends most of its time calling `bash -c` (with some arguments that have been removed in sorting).

**Comment by elrichindy** [comment]
Awesome, well not awesome, but thanks for your help! will log a ticket with the z fish and reference this.

**Comment by krader1961** [comment]
Argh! Ignore my previous comment. Insufficient coffee. The first column is the total time taken by the command, not the number of times it was run. But the point is that `z` is shelling out to bash and that's where all the time is being spent. Which is odd since @faho's link to the source doesn't seem to show any such thing.

**Comment by krader1961** [comment]
Out of curiosity what does the unsorted `/tmp/fish.profile` show for the lines that follow the expensive `bash -c`?

**Comment by faho** [comment]
>Which is odd since @faho's link to the source doesn't seem to show any such thing.

Apparently there's two _different_ z-for-fish things. I guess @elrichindy is using https://github.com/oh-my-fish/plugin-z. (Though I can't find where that's hooking up the variable event).

**Comment by krader1961** [comment]
Bingo. That one matches the other lines that got sorted to the top of the profile. That is downright hideous. Here's the comment for the `z` function:

> # Start a Bash process, source z, run the _z function, and capture the working directory and exit status.

Then look at the [implementation](https://github.com/oh-my-fish/plugin-z/blob/master/functions/z.fish). I gagged when I saw what it's doing.

**Comment by elrichindy** [comment]
All good, i got it :)
Yes, that's a point, before I submit a ticket there attached is the unsorted  output. Not sure it'll point to much now though but the difference between the two z's is telling.
Going to try sjl's z.fish, although tab completion would be nice, will try and fix it and see how it goes.
[fish_unsorted.txt](https://github.com/fish-shell/fish-shell/files/1189161/fish_unsorted.txt)
