### ISSUE TITLE
Fish shell exits immediately when opened as Python subprocess (connected to PTY)

### ISSUE THREAD

**Issue by Wramberg** [fish-shell/fish-shell#4282]
I am the author of a Sublime Text plugin that allows for terminals inside the editor. The way it starts the underlying shell can be seen here:
https://github.com/Wramberg/TerminalView/blob/master/linux_pty.py#L28

So basically a Python subprocess and a PTY. My question is: When fish is started as the shell it exits immediately with return code 1. Does fish only support being started through bash or am I missing something ?

Let me know if I need to provide more information.
Edit: I tried with both TERM=linux and TERM=xterm - same result.

```
jw@jw-VirtualBox:~$ fish --version
fish, version 2.5.0
jw@jw-VirtualBox:~$ uname -a
Linux jw-VirtualBox 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by krader1961** [comment]
> Does fish only support being started through bash...?

No, of course not. 98% of the time people are using an interactive fish shell that has been launched directly by their terminal (xterm, iTerm2, Konsole, etc.). You can also launch a fish shell via commands like `script`.  There is no requirement that fish be launched by bash or any other shell.

If fish is immediately exiting it means there is something about the environment it doesn't like. Since it sounds like this is reproducible 100% of the time I would start by starting it like this: `fish -d5 >/tmp/fish.out.txt 2>/tmp/fish.err.txt`. Put that in a file with `#!/bin/sh` header, make the script executable, then use that script name as the command to launch. After you launch it, and it presumably immediately terminates, take a look at those two files. If it isn't obvious what is wrong attach them to this issue.

**Comment by Wramberg** [comment]
> There is no requirement that fish be launched by bash or any other shell.

Great, thanks for the quick reply :-)

Starting fish through another shell like bash works. So If i use "bash -c fish" it starts. Using "fish -d5" as command it writes a bunch to stdout/stderr before exitting. Couldnt see anything obvious from scrolling through it though. 

[fish.txt](https://github.com/fish-shell/fish-shell/files/1194367/fish.txt)

**Comment by faho** [comment]
This fails in `reader_interactive_init`. Specifically, it tries to print "No TTY for interactive shell (tcgetpgrp failed)" (remove the "select.select" call in receive_output and you'll see it).

**Comment by krader1961** [comment]
I'm guessing you didn't get that from the fish debug trace, @faho, as it's truncated. Presumably you reproduced the failure.

@Wramberg, You'll probably want to consult a copy of "Advanced Programming in the UNIX Environment" (aka APUE) by W. Richard Stevens and Stephen A. Rago. It's the authoritative book for questions like how to properly setup a pty/tty and job control. Fish tends to be less forgiving than bash of mistakes in these areas. In part because it does some things during its initialization that are technically correct albeit perhaps not absolutely necessary. And while we're talking about rewriting that code it won't happen before the fish 3.0 release targeted for next year.

**Comment by faho** [comment]
>I'm guessing you didn't get that from the fish debug trace, @faho, as it's truncated. Presumably you reproduced the failure.

Yes. I downloaded that "https://github.com/Wramberg/TerminalView/blob/master/linux_pty.py" and added:

```python
pty = LinuxPty("fish", "/home/alfa")
print("Running: ", pty.is_running())
output = pty.receive_output(1000)
print(output)
```

At which point I noticed that `pty.receive_output(1000)` returned "None" while "is_running()" was true, so I uncommented the "select.select()" stuff, which then resulted in that error.

**Comment by Wramberg** [comment]
Thank you very much for the detailed answers guys. I'll give the APUE book a look 👍.
