### ISSUE TITLE
How do I change the tab completion's behavior of fish-shell to letting its tab completion have equal sign(=) after a long option which should be followed by arguments? 

### ISSUE THREAD

**Issue by xiaoxiangmoe** [fish-shell/fish-shell#4284]
Also asked in [Stack Overflow](https://stackoverflow.com/q/45480421/4469745)

In fish-shell, tab completion doesn't have equal sign(=) after a long option which should be followed by arguments, while oh-my-zsh do.

I think the equal-sign can hint us there should be a argument following. Can we turn on this feature？

**Comment by zhaojinxiang** [comment]
If There followed by an equal-sign, like `cut --delimiter=`, it will warn us that we need to follow an argument. That's why I wanna to open this feature.

**Comment by zhaojinxiang** [comment]
If There followed by an equal-sign, like `cut --delimiter=`, it will warn us that we need to follow an argument. That's why I wanna to open this feature.

**Comment by krader1961** [comment]
Are you under the misapprehension that long options always require an argument? Because they don't.

Also, in fish if an option takes an argument that is normally indicated by including the `-a` (or `--arguments`) flag to the `complete` command that defines the flag. That way after giving the flag if you press [tab] again you'll see a list of recommended arguments for the flag.

This won't be easy to implement due to how we currently depend on whitespace to tokenize the command line in order to know if a flag that takes an argument has been given one. It would certainly be nice to implement this bug since we're currently focused on our next major release this is unlikely to be implemented in the near future unless someone like yourself, @zhaojinxiang, write the code.

**Comment by zhaojinxiang** [comment]
I know some long options require an argument(like `--delimiter`) and some(like `--help`) don't. So it may be better if there exists an equal-sign `=` or a space-sign` ` to distinguish between them.

**Comment by mqudsi** [comment]
I think this could possibly be a matter of taste, remember that there is different syntax here (`--long-option=value` and `--long-option value` which are usually interchangeable) e.g. I never use an equal sign for longopts arguments unless the executable's parser requires them (which is almost never). Again, personally speaking, I would be highly annoyed if my shell started inserting equal signs I didn't ask for everywhere.

**Comment by iwoloschin** [comment]
How about for SSH?  I use keys for most servers, but sometimes I just need a throwaway server and I'm too lazy to push my keys, so I need to do something like this:

ssh -o PubkeyAuthentication=no user@server

With tab completion fish happily completes "PubkeyAuthentication" and drops a space, but then it requires me to hit delete and '=' to finish.  Is this a big deal?  Absolutely not!  It's just weird since fish seems to answer all of my other requests before I've even asked them, so it's a bit jarring when the one occasionally used command doesn't work "right".

**Comment by krader1961** [comment]
@iwoloschin, The scenario you describe would not be addressed by this issue since `-o` is the flag not `PubkeyAuthentication`. That ssh pattern for specifying config file options that take an argument is somewhat unusual. We'd be happy to implement better support for it if you open an issue and, more importantly, provide some ideas how the existing `complete` command and completion subsystem would be modified to accommodate that behavior.

**Comment by krader1961** [comment]
Also, @iwoloschin, you might find that simply defining an abbreviation is a better solution for the situation you described. For example

```
abbr sshnokey 'ssh -o PubkeyAuthentication=no'
```

**Comment by iwoloschin** [comment]
@krader1961, an abbreviation is probably the simplest solution, as you mention, SSH/SCP is kind of weird.

**Comment by laughedelic** [comment]
By the way, what I see when I type `ssh -o<TAB>` is 

<img width="612" alt="screen shot 2017-08-08 at 13 06 43" src="https://user-images.githubusercontent.com/766656/29069290-a3784a40-7c3a-11e7-9a77-fe0308484594.png">

And as far as I understand, it doesn't work in this format (without a space). Where does this completion list come from? I don't see it in [share/completions/ssh.fish](https://github.com/fish-shell/fish-shell/blob/master/share/completions/ssh.fish)..

**Comment by krader1961** [comment]
> By the way, what I see when I type ssh -o<TAB> is...

That is normal behavior for completing short flags that have arguments. You can see this with other completions such as `df -x<tab>`.  The getopt/getopt_long functions that most commands use to parse their options allow a space between the short flag and the argument but don't require it. If you type a space after the short flag then press tab you'll still get the arguments for the flag. I recommend opening a new issue asking that the space be inserted automatically like it is after the long flag.

**Comment by anordal** [comment]
> Does it work like this for any short options' arguments?

Yes, that's how short options work in the majority of programs – when a short option takes a parameter and the rest of the word is nonempty, the rest of the word is taken as the parameter. Ex:
* `ssh -oPort=22 …`
* `gcc -Wall -Wextra -Wpedantic -Iinclude/ -DHAS_PENGUINS=1 -lpthread file.c -cofile.o`
* `cut -d' ' -f2 /proc/mounts`

**Comment by krader1961** [comment]
> Does it work like this for any short options' arguments?

In addition to @anordal's comment I just noticed that gcc/clang do not allow a space between the short flag and its value. Which is probably why fish behaves this way.

**Comment by laughedelic** [comment]
But the current completion system doesn't allow to specify when it has to have a space and when it doesn't, right? What about argparse-based completion?

**Comment by krader1961** [comment]
Using `argparse` in the completion logic solves some problems but not this one, @laughedelic. That's because it is based on the GNU `getopt_long()` function which allows arguments to be separated from their short flag by optional whitespace. It doesn't provide any means of indicating that the space is required or must be omitted. We might be able to implement that logic within argparse itself but I'm unconvinced doing so is worthwhile just to accommodate weird commands with non-standard flag parsers.

**Comment by faho** [comment]
Okay, we're apparently not doing this, and there doesn't seem to be a particularly compelling case for it.
