### ISSUE TITLE
JIT

### ISSUE THREAD

**Issue by mcandre** [fish-shell/fish-shell#4316]
Could fish get Just In Time compilation for large shell scripts? Would be awesome to dramatically speed up looping and long running shell scripts!

**Comment by krader1961** [comment]
In theory, yes. In practice, it will never be implemented. If you have a fish script where the other changes that have been proposed, such as making `math` a builtin, is insufficient to make fish fast enough then fish isn't the right tool for the job.

**Comment by faho** [comment]
To expand on this:

Incorporating a JIT is a massive amount of complicated work, especially considering that shell scripting is rather different from typical programming. The model is different - e.g. much of it is executing external commands. I am unaware of any shell with a JIT.

Also, at this point I doubt it'd even help much, since we have some low-hanging fruit in terms of optimization (making math a builtin is one, not waiting to soak up all input before running a builtin is another), and since in shell scripts the bulk of the time is typically spent in those external commands, which we have zero control over.

I hope that makes sense!
