### ISSUE TITLE
Is the overhead of checking if a function file still exists acceptable on each call?

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4318]
Currently, if you create a file that defines an auto-loaded function, use that function, then delete that function, fish contains to act as if the function exists.

I'm not sure that this behavior is consistent. If a user manually `source`s a fish file, an explicit action has been taken to bring its contents (`foo`) into memory and place them there. On the other hand, if fish automatically sources a file, shouldn't it automatically "un source" the file when it no longer exists?

For automatically sourced functions, is it an unacceptable overhead to check if the file still exists (or better yet, if the file still exists or if its contents have changed) prior to execution?

If the answer is no, the solution could be as straightforward as pre-pending a file check to the autoloaded function in question, e.g. given a path `~/.config/fish/functions/foo.fish` that contains 

```fish
function foo
   echo hello world
end
```

if the user executes `foo` in the terminal and this function is automatically loaded, the function can be wrapped in a "file still exists" check:

```fish
function _foo
    echo hello world
end

function foo
    if test -e /path/to/foo.fish
        _foo
    else
        # unset foo and _foo
        eval foo #in case it was shadowing a command and to get an error message otherwise
    end
end
```

**Comment by krader1961** [comment]
> ... then delete that function, fish contains to act as if the function exists.

From the rest of your comment I assume you mean "delete that function's file" rather than `funcrm $func_name`.

Of course the function is still defined and usable. I don't see any practical difference between `source my_func.fish; rm my_func.fish`, typing `function my_func; do something; end`, and just running `my_func` to autoload it then typing `rm ~/.config/fish/functions/my_func.fish`. In the first and last cases I do not expect or want the function to magically removed as a result of deleting the file from which it was originally loaded. I definitely don't think we should be paying the cost of constantly checking if the file still exists. Think about all the autoloaded functions that are used constantly to do things like construct your prompt.

**Comment by mqudsi** [comment]
Ok, thanks.

**Comment by zanchey** [comment]
See also #213, #1980, #2017.
