### ISSUE TITLE
Request: make abbreviations global

### ISSUE THREAD

**Issue by thorstenkampe** [fish-shell/fish-shell#4320]
It would be nice if Fish supported global abbreviations - meaning abbreviations that are resolved everywhere in the comand line. This would allow some Zsh-style global aliases:
```
alias -g G='| grep'     \
         L='| less'     \
         S='| sort'     \
         SU='| sort -u' \
         WL='| wc -l'
```

**Comment by faho** [comment]
No.

Aliases and abbreviations already expand after pipes, so you can simply do `something | G`.

This feature only serves to save two characters, while being more confusing - how do you inhibit something like this from expanding?

For zsh, it's actually quite weird - with that "G" alias, `echo something G something` will run two commands in a pipeline, but without any pipe symbol. Abbreviations would be nicer here (since they actually expand visually, so you'll still _see_ the pipe), but as I said I don't see a need for this when you can just type the pipe.

**Comment by thorstenkampe** [comment]
I did not know that abbreviations are expanded after pipes, thanks. The remark about global aliases is valid. In my .zshrc I have a function which expands global aliases on space effectively creating abbreviations.

Since the functionality of aliases and abbreviations is quite similar (abbr = alias + expansion), wouldn't it make sense to make abbreviations an option of the alias command?

**Comment by faho** [comment]
>Since the functionality of aliases and abbreviations is quite similar (abbr = alias + expansion), wouldn't it make sense to make abbreviations an option of the alias command?

Well.... the "alias command" is currently a function that creates functions. Fish has no special support for "aliases", the core code doesn't even have any notion of them. It's all just functions. The entirety of the alias support is contained in one file.

Abbreviations on the other hand are supported by core (c++) code. Fish actually has a understands them, but only in the reader - they disappear after expansion.

So joining them together doesn't _really_ make sense from a code perspective. And from a usability perspective... abbrs are only useful interactively, and the command syntax is similar enough. `alias` is also a compatibility thing, to make transition from posixy shells easier. We don't want to change the syntax of it too much, while `abbr` is closer to the interface we'd envision. I don't think it's worth it to try to unify them.

**Comment by krader1961** [comment]
See also #1963 where this was discussed and rejected. But if you absolutely have to have this capability a user showed how to use `bind` to achieve it.

Also, it is somewhat unfortunate, IMHO, that the fish alias feature was named that. As @faho pointed out fish aliases are just trivial functions. They do not resemble zsh aliases in their behavior. From the zsh documentation:

> Every  eligible  word  in  the  shell  input is checked to see if there is an alias defined for it.  If so, it is replaced by the text of the alias if it is in command position  (if  it  could be the first word of a simple command), or if the alias is global.  If the replacement text ends with a space, the  next  word  in  the  shell input  is  always  eligible  for  purposes of alias expansion.  An alias is defined using the alias builtin; global aliases may be defined using the -g option to  that builtin.

From that it is clear that fish abbreviations, not fish aliases, are the analog of zsh aliases. We could theoretically implement "global" abbreviations. But if you read the rest of the zsh documentation you'll find that the rules for when they are expanded and how to keep them from being expanded are byzantine in keeping with most things involving tokenizing input in a POSIX shell. Like the other fish devs I don't think it is worth it.

And, FWIW, I already have many abbreviations similar to those in the O.P.'s comment. Here are just a couple:

```
abbr -a -g -- gca 'git commit --amend'
abbr -a -g -- l less
abbr -a -g -- see 'cat -evt'
```

The only difference is that I have to manually type the pipe character if I want to use the alias in a command position other than the start of the line. Personally I don't find that especially onerous. Especially since I don't have to remember to escape the alias if I use it someplace I don't want it expanded.
