### ISSUE TITLE
Python-style triple-quoted strings

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#4322]
It would be nice if Fish had support for Python-style triple-quoted strings.  It would be helpful, e.g. when writing usage messages, and would help compensate for the lack of heredocs.  Something like:

```fish
set usage """command [OPTIONS] [ARGUMENTS]
  Options:
    --message MESSAGE

  Examples:
    command --message "Hello world"
"""
echo $usage
```

It avoids having to escape newlines and quotes within the message.

**Comment by faho** [comment]
What's the actual difference here? Quotes already span newlines, you only need to escape them if you do not want to have them included. But if I understand this correctly, you _do_ want to have them included here.

```fish
set usage "command [OPTIONS] [ARGUMENTS]
Options:
  --message MESSAGE

Examples:
  command --message \"Hello world\""
echo $usage
```

should give the same output.

This includes whitespace from the beginning of the line (which is why the latter lines start there), but IMHO that's a very minor issue.

**Comment by faho** [comment]
Well, the quotes are a difference, but again that just seems like a tiny thing.

**Comment by krader1961** [comment]
This proposal doesn't affect the need to escape newlines at all. It only means you don't have to escape individual quote marks. That is, using the current single quote parsing rules you have to escape embedded quotes like this:

```
set usage "usage: abc def ghi

If you need to \"quote something\"...
"
```

If we had python style triple quoted strings you could omit the backslashes:

```
set usage "usage: abc def ghi

If you need to "quote something"...
"
```

Note that the other reason Python has triple quoted strings is because single quoted strings can't span multiple lines. That isn't an issue for fish single quoted strings. I don't think the added complexity, both implementation and user documentation, can be justified. Needing to escape embedded quote marks can often be avoided by simply mixing single and double quote marks. And where that isn't viable it isn't that hard to escape the embedded quote characters.

**Comment by faho** [comment]
After actually looking at how python does it again (haven't used them in a while), it seems like the sole difference is that you can use the quote-character you used inside of it (unless it occurs in triplicate, which of course doesn't happen as often).

It has both the indentation issue and includes newlines (i.e. if you want to continue the same line, you need to escape the newline), it also escapes with backslashes.

So I don't see how this helps.

I'm closing this. If anyone makes a good argument for introducing triple-quotes, we can reopen.
