### ISSUE TITLE
Cannot bind semicolon

### ISSUE THREAD

**Issue by nyarly** [fish-shell/fish-shell#4328]
fish, version 2.5.0
Linux neumann 4.9.31 #1-NixOS SMP Wed Jun 7 10:08:04 UTC 2017 x86_64 GNU/Linux
rxvt-unicode-256color

I cannot figure out how to get fish to bind "Control-;" `bind \c; echo hi` echoes immediately, because the ';' is considered to end the bind command. `bind \c\; echo hi` appears to work, but binds some key combination I can't figure out.

**Comment by krackers** [comment]
I don't think control-semicolon is a valid control combo that's accepted by any terminal. Run `fish_key_reader` and see if it reports anything.

**Comment by nyarly** [comment]
fish_key_reader reports it as ';' so it seems you're right.

It'd be *rad* to add fish_key_reader to the bind docs, though. Way easier than puzzling out escape sequences.

**Comment by krader1961** [comment]
Applying the control modifier to the semi-colon character doesn't make any sense. Doing `bind \c\; 'echo hello'` binds it to `\x1C\;` due to a long standing quirk of the fish parser. It doesn't make sense because unless you've customized your terminal pressing [ctrl-;] is the same as just pressing the semi-colon key. The way the control key normally works is to take the value sent by the next key and strip the high three bits. That is, it's equivalent to doing `key_code & 0x1F`. Except that most terminals limit applying that transformation to just a few other keys (mostly letter keys). If the terminal did allow [ctrl-;] it would be equivalent to pressing [escape] since semicolon is 0x3B and masking out the high three bytes yields 0x1B which is the [escape] key code.

**Comment by rickswe** [comment]
@nyarly I think you may be missing the "ctrl-".

This works:

```fish
        for mode in (bind --list-modes)
            bind -M $mode ctrl-\; 'commandline -i ";"; commandline -f repaint'
        end
```
