### ISSUE TITLE
`git reset` completions issues

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4329]
I'm pretty sure the `git` completion is one of the more complicated ones, so please let me know if more information is needed.

Before anything else, here's my output of `git status`:

```
On branch master
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   Makefile
```

If I type in

`git reset M<tab>`

the `M` gets expanded to/replaced with `master` (no other option is available).

If I type in 

`git reset Make<tab>`

the `Make` gets expanded to/replaced with `HEAD@\{0\}` (literally, with the escapes)

several issues:

* file completions should be supported for `git reset`
* shouldn't adding letters to the argument being completed narrow down the list of completion options, not change them entirely?

**Comment by faho** [comment]
>file completions should be supported for git reset

Yes, though I'd argue it should be _modified_ files. Ideally files modified since the "tree-ish" argument to `reset`, but that's complicated. It's almost trivial to add files modified since the last commit, since we already have that function (for `git checkout`).

>the Make gets expanded to/replaced with HEAD@\{0\} (literally, with the escapes)

That's a reflog entry.

The escapes are to be expected - without them, `HEAD@{0}` expands the braces and ends up as `HEAD@0`, which is invalid.

The issue here is that it's matching the description as well. That is behaving as expected - it'll only ever do that when there's no other match. We just need to add those matches.

**Comment by mqudsi** [comment]
OK, that explains why `m` didn't match HEAD and `Make` did. The first had a match (`master`) so the commit text wasn't being searched.

**Comment by faho** [comment]
@mqudsi: See my git-reset branch. I'm holding off messing with master for a while.

**Comment by mqudsi** [comment]
Does `__fish_git_modified_files` include deleted?

**Comment by faho** [comment]
Yes. It uses `git diff --name-only` under the covers.

**Comment by faho** [comment]
Though I think we might need another argument here. `git reset` changes the index ("staging area"). `git checkout` changes the working tree (the actual directory).

**Comment by faho** [comment]
Okay, `git diff --cached` should do the trick.
