### ISSUE TITLE
Why are there 400+ (TOO MANY) opened issues?

### ISSUE THREAD

**Issue by timofonic** [fish-shell/fish-shell#4348]
Hello.

Why are there TOO MANY opened issues? When I see things like that, it makes me distrust in the project. I'm sure you probably have some reason, but some users might have a bad impression of the project.

Excuse me for opening an issue just for this question. It's also a personal way to be sure the project is managed :P 

Kind regards.

**Comment by faho** [comment]
There are more than 400 issues open because there's a bunch of stuff to do.

You might also notice that, of those 436 issues, only 79 are labelled "bug" - a full 334 are "enhancement"s.

Of those bugs, many fall into a few categories:

- Issues with vi-mode

- Issues with multiline prompts

- Issues with completions (either scripts or edgecases)

(and a bunch more)

None of them is a dealbreaker.

Of course that's not to say that they aren't important or that there aren't more high-profile bugs - job handling comes to mind, it's just that you can't use that number to say "there's 79 very important and terrible things about this project".

>Why are there TOO MANY opened issues?

That's entirely arbitrary. At what point is it "too many"? 100? 10? It might be possible for us to e.g. group all of the vi-mode related issues together under one issue called "vi-mode needs improvement". Would that improve the situation?

>When I see things like that, it makes me distrust in the project

Frankly, I've seen a bunch of github projects that have like 10 open issues, and that makes me distrust the project because I believe they're sweeping stuff under the rug (closing after inactivity or something, like that makes it go away). Or nobody cares about them.

Of course you're free to distrust this project.

>It's also a personal way to be sure the project is managed :P

I don't think it's managed terribly. Of course there's room for improvement and I'm probably biased.

**Comment by zanchey** [comment]
Thanks for your interest in fish. I can see you have opened similar issues across some other projects (eg mobile-shell/mosh#922) and I am assuming you are new to open source development.

The issue tracker is used for many things - reporting problems, asking questions, documenting future plans and discussing potential enhancements. We try to only close issues where a definite decision has been made or where a question has been answered. Not all of those 400 issues are problems with the shell (although some certainly are - those tagged with 'bug' are the minimum set). I note that at times in the past we have been a bit slow to make a decision not to implement something, and often an open issue means "we'd take a patch for this, but nobody is actively working on it". 

Firefox has 24 491 open bugs in their tracker, and that's extremely popular and well-used software. Arguably the number of issues rises with the number of users, rather than the number of problems with the software!

As an aside, one of the challenges in open source is that contributors come from a wide variety of cultural backgrounds. Your message came across (at least to me) as quite rude, which I'm sure was not your intention.

**Comment by timofonic** [comment]
@faho @zanchey Thanks a lot to both for your time at your explanations: 
* You both made me learn a lot about FOSS. I wasn't so sure about how issue trackers are used. 
   * I'm curious: Do you think the current GitHub issue tags system is okay or could be improved? I somewhat remember other issue trackers (SourceForge?) in the past separated between "feature requests" and "issues" or something like that.
    * Would you like that and other features to be part of Git itself like in Fossil and now dead Veracity?   
* I'm sure others would be less polite and close this only: I'm not sure why, but I sometimes sound unintentionally quite rude when I only have a doubt about something and ask about it. We can discuss this in private if you want.

I was writing another dumb issue [here](/nelhage/reptyr/issues/62) but accidentally did read your messages and corrected it. Thanks a lot!

**Comment by krader1961** [comment]
It is presumptuous of you to assume we're interested in debating the merits of using Github, or anything else, with a random person who has made zero contributions to the project. Your original comment was also presumptuous and rude. As is the [comment](https://github.com/nelhage/reptyr/issues/62#issuecomment-324058279) you made on an issue in the reptyr project. And I see you did the same thing to the [mosh](https://github.com/mobile-shell/mosh/issues/922) project that you did here. And you opened a similarly rude, ill-informed, [fundle issue](https://github.com/tuvistavie/fundle/issues/31).

You are not making any friends in the Open Source community. I would encourage you to show these issues to your mentor at work and get feedback from them on how you can change your style so your issues get a better reception. If you don't have a mentor at work get one.
