### ISSUE TITLE
end keyword not always usefull

### ISSUE THREAD

**Issue by hamon-e** [fish-shell/fish-shell#4359]
I would like to share this idea (i don't know if this is the place to do it) :

In command line editing, maybe the end of the input could replace the "end" keyword.

For example in this command there is no need for the "end"
<code>
while true; echo "foobar"; end
</code>
and could be replaced with
<code>
while true; echo "foobar"
</code>

**Comment by ridiculousfish** [comment]
Hmm, how would fish distinguish when a newline is supposed to mean `end?`? Is the idea to be something like C where in `while (stuff) things()`; if the open brackets are omitted, it just takes the next statement?

**Comment by hamon-e** [comment]
Yes i think it could be a good idea

**Comment by zanchey** [comment]
As I understand it, this breaks the following idiom, which I sometimes use, although I'm not sure how common it is:

```fish
if begin something; and something_else; end
   do_something
end
```

**Comment by krader1961** [comment]
While I suspect something like @ridiculousfish's analogy is what prompted this proposal implementing it is likely to cause more problems than it is worth. First, would this only apply interactively? If not how would fish correctly handle non-interactive scripts that use that pattern but happen to have the `end` keyword on the next line?

Let's say we do this only for interactive input. What happens if I type your example then accidentally press [enter] while intending to add more commands to the block? With your proposal it will run rather than give me a prompt that clearly indicates more input is expected.

I've been using UNIX since approximately 1985 and can't recall any instances where saving a handful of characters in this manner would have been useful relative to the risks. This type of ambiguity is almost certain to cause more problems than benefit.

**Comment by ridiculousfish** [comment]
Yes, we're pretty wedded to explicit `end` at this point. Closing. Thanks for the idea.
