### ISSUE TITLE
Provide API for changing prompt input style

### ISSUE THREAD

**Issue by marcoms** [fish-shell/fish-shell#4370]
It would be very useful to add hooks for styling prompts. For example:

```
function fish_prompt_input
    # italic text
    echo -nse '\033[3m'
end
```

```
/home/marcoms > (italic start)ls
```

For my use case the font Operator Mono has really nice italics that would look good as an input font, but is not the most legible as a global font.

**Comment by krader1961** [comment]
Note that at the moment, due to how fish dynamically colors the command line, that won't actually work. You can see this for yourself by running `funced fish_prompt` and adding that `echo` command to the bottom of that function. You'll probably see that the first letter you type is, perhaps only briefly, italicized. The core fish input reader logic would have to call your `fish_prompt_input` function for every character. The expense could be mitigated through careful caching if we require the output of the function to be idempotent until the function is changed.

But there is a simpler solution: edit the relevant `fish_color_*` vars. For example, type `set -g fish_color_error --italics --bold red` then start typing an invalid command. That's not a great solution however because at the moment many of the color vars are used in more than one way. So we'd probably need to introduce some new vars to disambiguate the use cases. Alternatively, introduce just one new color var that is merged with the relevant color var only when coloring interactive input (rather than, say, the prompt).

**Comment by ridiculousfish** [comment]
Agreed, the color variables seem like the way to go. @marcoms please give that a try and let us know if they don't cut it.

**Comment by floam** [comment]
>`echo -nse '\033[3m'`

Just an fyi, `set_color` can do italics and dim. Though this doesn't work on MacOS due to an Apple bug they just seem to never care to take a look at. Still not fixed in 10.13 betas - they leave italics and dim out of the terminfo definitions they ship. I'm half-inclined to detect `Apple_Terminal` and force an override in fish. It's really frustrating.

**Comment by floam** [comment]
(the above Apple bug is [https://openradar.appspot.com/27624224](27624224) for those following along at home.)

**Comment by marcoms** [comment]
Thanks everyone, the color vars do seem to work from my testing. It would be nice as @krader1961 suggested to provide some more suited variables for styling the prompt input globally, as setting each color variable is error prone and probably missing some edge cases.
