### ISSUE TITLE
allow `env` to work with fish functions

### ISSUE THREAD

**Issue by chengguangnan** [fish-shell/fish-shell#438]
I'm not sure if a similar syntax exists in Fish?

(Please focus on fishshell rather than rails =)

**Comment by nyarly** [comment]
I can see the rationale for an env wrapper, but for the use case of RAILS_ENV=production, a) just add 'env' to the beginning of the command, and it works and b) the fish error in 2.1.1 at least recommends that you do exactly that.

**Comment by digaev** [comment]
Yea, I'm just two days on fish, and feel that pain with inline variable, but in particular case with `RAILS_ENV` you could just run `rails s -e production`.

**Comment by GReagle** [comment]
Using the external `env` command is fine except that it doesn't work with fish functions.  Using `begin ; set -lx RAILS_ENV production; rails ; end` is also fine except that it doesn't work with fish functions (at least in version 2.2.0).  Very similar issue is #2415 which maybe should be merged.

**Comment by zanchey** [comment]
It does work with fish functions, but your function will need to use `--no-scope-shadowing` because the local variable is "outside" the function's local scope.

**Comment by GReagle** [comment]
Thanks @zanchey that is good to know about the --no-scope-shadowing option.  However, I think that exported variables in the environment should be available to functions by default, so that functions can be used like shell scripts or other external programs in the same way.

**Comment by anordal** [comment]
> How can one separate
runwith variable ar1 ar2 command args
from
runwith variable ar1 command args
?

With an option I suppose? That's what Docker does. Try this!

    docker run --rm -e RAILS_ENV=production -e HOSTNAME=hamsterwheel2 busybox env

(Runs `env` in a busybox container with those variables set. `-e` is the short option for `--env`, which sets one variable.)

Unfortunately, using `-e` to *set* a variable isn't too consistent with `set -e` doing the opposite.

**Comment by anordal** [comment]
If we reimplement `env`, let's also make it able to set the current directory. I think that's a very silly omission of standard env! That's `-C` in most commands I know (git, make, ninja), or `-w` in docker.

**Comment by krader1961** [comment]
The original title was

> Inline environment variable define like this in bash `RAILS_ENV=production rails s`?

I've changed it since we are not going to allow inline env vars. However, there is merit in allowing the `env` command to be used with functions. It will be important to also make the var(s) local so they don't bleed into the enclosing environment. At the moment resolving a variable does not recognize an exported local var in the scope enclosing a function. So doing the following doesn't print `bar` as you would expect:

```
$ function foo
    echo $VAR
end
$ set -x VAR foo
$ begin; set -lx VAR bar; foo; end
foo
```

The key question is whether changing the var resolution rules to allow that example to work as expected would create a backward incompatibility.

**Comment by krader1961** [comment]
Someone asked on StackExchange today how to use `env` with fish functions. Which reminded me of this issue. I looked at the implementation @shamrin [mentioned](https://github.com/fish-shell/fish-shell/issues/438#issuecomment-65885098). There are some things I would do differently and it needs to be updated to take advantage of improvements made since they wrote that wrapper but the basic approach looks viable. I'm wondering if there is some reason we shouldn't use that approach.

**Comment by shamrin** [comment]
@krader1961 Thank you for checking out my implementation! I'm not currently using it, because I've found it not very robust in practice. Unfortunately I don't remember exactly what were the issues. I only remember that I had an idea to implement `env` builtin inside fish, to avoid messing around with scopes in a fish script. Never tried that though.

What are the "improvements made since they wrote that wrapper"?

**Comment by krader1961** [comment]
> What are the "improvements made since they wrote that wrapper"?

There are several but the most obvious one is using the new `string` builtin to avoid external commands like `cut`.

**Comment by danielpclark** [comment]
Grrr… Just ran into this issue.  The shell scope environment variables (outside the function) aren't observed within the function.

**Comment by jameydeorio** [comment]
I just want to add my vote for this. Why doesn't fish want to implement inline env vars?

**Comment by nesl247** [comment]
Any updates on this?

**Comment by ridiculousfish** [comment]
I know this is annoying. Specifying variables inline like `foo=bar cmd` is weird when you think about it (why is foo=bar not the command?) A builtin `env` is the way to go if anybody wants to take it on.

**Comment by darthdeus** [comment]
Is it really that confusing though? To be honest this was one of the things that pushed me back to ZSH and I haven't looked back since. There are many confusing things about regular UNIX shells, but I never saw a problem with this syntax, or anyone ever be confused about what it does.

**Comment by lilyball** [comment]
I really think we should just support `FOO=bar cmd` syntax. I've filed #6048 to track this specifically.

**Comment by kakra** [comment]
As with `make`, you can pass variables as arguments to `rake`, thus it should work with `rake RAILS_ENV=production db:migrate`. It doesn't work for the `rails` command, tho.

**Comment by faho** [comment]
#6048 was implemented, allowing `VAR=VAL` style overrides, so this issue has been superseded.
