### ISSUE TITLE
Fish not loading config inside phpStorm

### ISSUE THREAD

**Issue by cperezabo** [fish-shell/fish-shell#4382]
Using latest fish version, in latest macOS version and latest phpStorm version.

In phpStorm I see this
<img width="655" alt="captura de pantalla 2017-09-06 a la s 18 29 26" src="https://user-images.githubusercontent.com/3604722/30135504-587b36ac-9331-11e7-8a9c-3f5160db3a05.png">

But in the macOS terminal I see this
<img width="409" alt="captura de pantalla 2017-09-06 a la s 18 29 44" src="https://user-images.githubusercontent.com/3604722/30135509-6177e5ca-9331-11e7-8954-0ebb656adcfd.png">

phpStorm settings are pointing to the same binary than the terminal

<img width="779" alt="captura de pantalla 2017-09-06 a la s 18 30 31" src="https://user-images.githubusercontent.com/3604722/30135556-9b8f061c-9331-11e7-8733-bdf03a223fe0.png">
<img width="361" alt="captura de pantalla 2017-09-06 a la s 18 30 44" src="https://user-images.githubusercontent.com/3604722/30135557-9cbb47bc-9331-11e7-9afc-b7f53345d368.png">

Any Idea?

**Comment by krader1961** [comment]
The problem is that phpstorm isn't setting the window size for the pseudo terminal it creates. So when fish starts it finds that the equivalent of `stty -a` reports that either or both the terminal rows and lines are zero. Fish relies on that information to know how much space is available for drawing the prompt, displaying the completion pager, etc. and zero isn't a useful value. It falls back to the value of the `LINES` and `COLUMNS` env vars if they exist else 24x80.

**Comment by faho** [comment]
>Using latest fish version, in latest macOS version and latest phpStorm version.

What is the "latest" fish version in this case? The output of `fish --version` would be nice to know. If you are using current git master, this might be because of the removal of the `.` function.

You see, jetbrains' IDEs ship some fish support code (which is nice of them) that adds in a different config.fish (which is less nice of them), and according to https://github.com/fish-shell/fish-shell/issues/3988#issuecomment-297076432 that uses `.` to source your existing config.

Also the terminal doesn't specify its size properly, but your prompt should still be loaded.

The contents of `$XDG_CONFIG_HOME/fish/config.fish` would be nice to know.

**Comment by faho** [comment]
See https://youtrack.jetbrains.com/issue/IDEA-178131. Disabling "shell integration" in your settings should work around this.

**Comment by faho** [comment]
@cperezabo: I'm assuming your question has been answered - it's an issue in Jetbrains' products that you need to work around.
