### ISSUE TITLE
Builtin `string match` does not work as expected

### ISSUE THREAD

**Issue by externl** [fish-shell/fish-shell#4388]
```
❯ fisher --version
fisherman version 2.12.0 ~/.config/fish/fisherman/functions/fisher.fish

❯ uname -a
Darwin mactop 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

From [Gitter](https://gitter.im/fish-shell/fish-shell?at=59b1f409bac826f05490e907) question I posted.

---

I'm having an issue with the string builtin. I'm looking to do something like: `string match --index 'foo' 'foo1 foo2 foo3'`. According to the doc string match behaves like `grep -o`, however I'm not getting any matches.

Compare these two commands:

```
❯ echo 'foo1 foo2 foo3 foo4' | grep -o foo
foo
foo
foo
foo

❯ string match --all 'foo' 'foo1 foo2 foo3'
❯
```

I would expect something like `string match [--index] 'foo2' 'foo1 foo2 foo3'` to return `foo2` substring match as the doc states or `6` if `--index` as passed.

**Comment by faho** [comment]
There's a bit of weirdness in behavior here:

Without "-r", `string match` does glob-matching. That means without "*" or "?", it will try to match the entire string, and fail if it doesn't.

So `string match 'foo'` will match `foo`, but to match `foo1`, you'll need `foo?` or `foo*`.

This is inconsistent with the documentation and with the "-r" option (in that case, it does partial matching - if you don't want that, you'll need to explicitly anchor with `^` and/or `$`).

Unfortunately, I believe changing this behavior would be too annoying - _every_ use of `string match` without "-r" would need to be audited. So we should fix the documentation instead.

-----

Also note that the "--all" here is pretty much superfluous since you are only expecting one match per-string - if this behaved like you thought, you'd get `foo` three times with or without "--all".

**Comment by faho** [comment]
Also note that the fisher version is not interesting to us. It's a third-party project, so if you had any issues with it, you'd report your bug there (unless it uncovers an issue in fish itself).

**Comment by externl** [comment]
@faho Sorry that was a typo, I meant to type `fish --version`

**Comment by externl** [comment]
>>> Also note that the "--all" here is pretty much superfluous since you are only expecting one match per-string - if this behaved like you thought, you'd get foo three times with or without "--all".

I think `--all` is more interesting to use with `--index`. To get a list of matching indexes.

**Comment by externl** [comment]
For https://github.com/fish-shell/fish-shell/commit/9347951158c5b68db2d03cefa03115eb1a09ab30

I think maybe the line:

>By default, PATTERN is interpreted as a glob pattern matched against each entire STRING argument. A glob pattern is only considered a valid match if it matches the entire STRING.

should be moved into the first paragraph. Otherwise it may be missing if you're not interested in `--index`.

**Comment by krader1961** [comment]
The problem with the current behavior is that `string match -n` is not consistent with `string match -r -n` even allowing for the different regex flavors. The glob form is equivalent to

```
string match -q $glob $string
and echo 1 (string length $string)
```

It's not particularly useful. And because it's inconsistent with the regex form it's confusing. We should either clarify the documentation to make it clear that `--index` is really only useful in conjunction with `--regex` or change the implementation so the two forms behave similarly. Since the latter is a backward incompatible change (albeit one unlikely to break anything) it's another good candidate for fish 3.0.
