### ISSUE TITLE
git completions listing remote branches as local

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4395]
The completions for git are not correctly categorizing branches, listing (some?) remote branches as local. This is best illustrated by the following screenshot which first depicts the local branches (courtesy of `git branch`) followed by the suggested completions:

![image](https://user-images.githubusercontent.com/606923/30250732-5900db1e-9619-11e7-9bfc-619b9093c1b7.png)

My local branches are correctly included in the `(Branch)` categorization, but all non-origin remote branches are also included the `(Branch)` description. In addition, some `origin/xxxx` branches are also included in that list. (I think that's branches on `origin` that conflict with locally-named branches)

**Comment by faho** [comment]
>listing (some?) remote branches as local.

Not quite - they list them as "Branch". Which is neither explicitly remote nor local.

I think the issue here is that "Remote Branch" is a bit of a misnomer - what is listed here with that description is the output of `__fish_git_unique_remote_branches`. If only one remote (plus the local repo) has a branch of a given name, you can use `git checkout $branchname`, instead of `git checkout $remote/$branchname`. The description was meant to make it clear that those are remote, even though they look local.

**Comment by mqudsi** [comment]
@faho the new behavior includes all remote branches and all uniquely named remote branches as `(Remote Branch)`. There is no more generic `Branch`, only explicitly `Local Branch` and `Remote Branch`

Unique remote branches are accessible both via their branch name (without the origin name) and with the `origin/branch` syntax.
