### ISSUE TITLE
official tool for zsh history to fish?

### ISSUE THREAD

**Issue by jinleileiking** [fish-shell/fish-shell#4400]

**Comment by ridiculousfish** [comment]
None yet but it seems like a reasonable thing. What are the zsh history format(s)?

**Comment by krader1961** [comment]
The main problem with importing zsh history is that there is no default history file. The user has to explicitly set `HISTFILE` -- it doesn't have a default value like bash's *~/.bash_history*. So importing zsh history would probably have to be done via a command that takes a file name rather than automatically the first time fish is run.

The format depends on whether the user has done `set -o EXTENDED_HISTORY`. If they haven't then it's just one line per command. Multiline commands are wrapped with each line but the last ending with a backslash. If extended history is enabled the lines include a timestamp. For example:

```
: 1505272073:0;git status
: 1505272107:0;echo 20:08
: 1505272182:0;if true\
then\
echo yes\
fi
: 1505272184:0;fc -W
```

No idea what the `:0` component is. It's always zero in my zsh history file. The preceding value is seconds since the UNIX epoch. If extended history is not enabled then the portion from the colon thru the semicolon isn't present.

**Comment by zanchey** [comment]
`history import --zsh`?

**Comment by krader1961** [comment]
> `history import --zsh`?

Yes, if something like this is implemented it should be a history subcommand that takes an option to specify whether the named history file was created by bash, zsh, csh, etc. so that it can be extended in the future. Probably reasonable to default to `--bash` if no creator flag is provided.

**Comment by krader1961** [comment]
Another option is to just provide a script that people can run which explicitly converts between the foreign format and fish's format and directly appends the converted entries to the default fish history file. The user would need to start a new fish instance or run `history merge` to see the imported entries. Unless, of course, the script was implemented as a function in which case it could run `history merge` as the final step. The risk with this approach is that the script/function has to be kept in sync with any change to the builtin history maintenance code as it evolves (e.g., changing from YAML to some other format).

**Comment by jinleileiking** [comment]
https://gist.github.com/christopherstott/59a5e36b8d2f3f015bb7

I tried to use this, but work not well

**Comment by jinleileiking** [comment]
my zsh_history, a period:
```
   9 : 1480407038:0;curl -XPOST 'localhost:8980/api/room?user_id111=4&method=publish' -v¬
       10 : 1480407070:0;curl -XPOST 'localhost:8980/api/room' -d '{"user_id": 7, "method":"publish"}' -H 'Content-Type: application/json'\¬
       11 ¬
       12 : 1480407115:0;curl -XPOST 'localhost:8980/api/room' -d '{"user_idxx": 7, "method":"publish"}' -H 'Content-Type: application/json'\¬
       13 ¬
       14 : 1480407121:0;curl -XPOST 'localhost:8980/api/room' -d '{ "method":"publish"}' -H 'Content-Type: application/json'\¬
       15 ¬
       16 : 1480407840:0;curl localhost:8980/upload¬
       17 : 1480407931:0;curl -XPOST 'localhost:8980/api/room' -d '{ "methodxx":"publish"}' -H 'Content-Type: application/json'\¬
       18 ¬
```

omit the line numbers :)

**Comment by krader1961** [comment]
@jinleileiking, There are a couple of problems with the tool you linked to besides it being written in JavaScript :smile: First, it doesn't handle multiline commands. Second, it doesn't correctly escape special characters like backslash. Third, it doesn't handle zsh history files that do not have timestamps. It is also inefficient with respect to the time and space required but that's a relatively minor issue given that this will normally be run once by someone migrating from zsh to fish.

**Comment by ridiculousfish** [comment]
It might be possible to have fish invoke zsh and pass it a command to print its history. That would avoid a lot of issues around e.g. locating the zsh file or dealing with different formats.

**Comment by krader1961** [comment]
> It might be possible to have fish invoke zsh and pass it a command to print its history....

That has its own problems. Not least of which is that zsh is not consistent in how it deals with backslashes in the history (`fc -l`) output. More specifically, sequences like `\n` are ambiguous. You also need to use `fc -li` or `fc -lt $custom_time_fmt` since the default format only shows the hour and minutes. In any case the human readable timestamp then needs to be converted back to seconds since the UNIX epoch. Which has well known solutions but why deal with the cost and ambiguities (e.g., around DST transitions) since the raw history file already contains the raw value we want.

It would be better to do `zsh -ic 'echo $HISTFILE'` to get the name of the history file. If there is no file name give up. Otherwise just parse that file since the format is trivial to handle, even including commands that span multiple lines. In fact, that might be a good idea for the bash case as well since it would allow fish to import bash history even if the user has customized the bash history file name.

**Comment by krader1961** [comment]
Also, note that if `EXTENDED_HISTORY` is not set then `fc -l` in zsh just prints the current time for each command. It would be better if fish detected whether or not command timestamps are available by reading the raw history file. It can then decide for itself what to do vis-a-vis synthesizing a timestamp.

**Comment by jinleileiking** [comment]
No progress?

This is a very BIG feature for zsh users (like me) to migrate to fish.

**Comment by rsalmei** [comment]
Does any of these work? Both in Python.
https://gist.github.com/dvdbng/e08ce5ba50f224b59c9fe2a91fdcea61
https://gist.github.com/hnykda/61032fdd08c79a592504167acb790fab

**Comment by rsalmei** [comment]
Actually they both seem to work. I'm only worried about the LRU in fish history (as explained in https://github.com/fish-shell/fish-shell/issues/2674)...
Should I de-duplicate all the commands found in zsh history, prior to insert in `fish_history`? Can I really just append, or should I sort the final file by `when`?

**Comment by jinleileiking** [comment]
After I installed some zsh plugins. I think my zsh = fish. So I do not to migrate. Closed. If anybody needs this feature , please reopen

**Comment by mqudsi** [comment]
@faho any reason for `will-not-implement`ing this? I think there should be some official answer to this, regardless if it's part of fish or a 3rd party script officially sanctioned by the docs.

**Comment by krader1961** [comment]
@mqudsi, Read my comments on this issue. The fact that a single user asserted they wouldn't migrate to fish because it couldn't import their zsh command history is not, in and of itself, sufficient justification to implement the feature. Especially since there is no reliable way to do so. The 3rd party script referenced by the O.P. is broken. It definitely should not be "sanctioned" in the fish docs.

I switched from zsh to fish as my primary interactive shell. The fact that fish did not import my zsh command history **was not even a top 100 issues consideration** in my decision to make the switch. If fish is going to import the command history of other shells what should be included in that set of shells? Why not `ksh`? `tcsh`? `bash`? What to do about commands in those histories that are not valid syntax for fish?

**Comment by rsalmei** [comment]
Hello, to anyone interested in migrating your zsh history to fish...
I'm happy to announce I've just published a python lib in PyPi to do this, check it out! 😃 
https://github.com/rsalmei/zsh-history-to-fish

**Comment by gordolio** [comment]
@rsalmei I just imported my history using your tool. Thank you for providing this.

I'll apologize now for the long comment, but I think these instructions are useful for new fish users. For any others coming across this thread, this was the process for me.

Because I had been using fish for a couple days, so I wanted to keep the existing fish history (prepend zsh-history to fish history file). My zsh_history file was configured to be `~/.history` because I wanted to bring in history from bash when I converted to zsh. But the default for zsh is `~/.zsh_history` so these instructions will reference that.

1. `pip install zsh-history-to-fish`
    OR if you have both python2 and 3 installed from homebrew like I did
    `pip3 install zsh-history-to-fish`
2. Export to a separate file first so you can concatenate both histories.
    `zsh-history-to-fish -o ~/converted_zsh_history ~/.zsh_history`
3. zsh-history-to-fish indents the converted history with 3 spaces instead of the default of 2. So to keep things sane I popped open the converted file in vim and ran the command...
    <pre>:%s/^   when/  when/</pre>
    This step is probably unnecessary.
4. Then concatenate both histories into a single in `~/full_fish_history`
    `cat ~/converted_zsh_history ~/.local/share/fish/fish_history > ~/full_fish_history`
5. After verifying everything looks right, go ahead and replace the history
    `cat ~/full_fish_history > ~/.local/share/fish/fish_history`

Then, of course, installing fzf makes reverse history search absolutely beautiful.
1. `brew install fzf`
2. `/usr/local/opt/fzf/install`
    Some warnings did appear for me, but the homebrew script successfully installed the fzf_keybindings so Ctrl+r works as expected. The interface for fzf is new. I'm used to continually pressing `Ctrl`+`r` to keep searching back in history, but the slick UI to arrow up/down between history items is nice!

I keep all my .dot files on github if anyone wants to reference them... [gordolio/shell-config](https://github.com/gordolio/shell-config)

**Comment by rsalmei** [comment]
You're welcome @gordolio, I'm glad you liked it!!
And thanks for the heads-up, the 3 spaces was a typo, I've already corrected it and released a new version on PyPi.

**Comment by jinleileiking** [comment]
Seems this issue got many people concerned. I reopen this. Let the project owner to close it

**Comment by floam** [comment]
Reopening because we can certainly try to accommodate the feature request. We can go off of `HISTFILE` and try to detect if the format is extended or not.

Even what @rsalmei shared is doable, because `fish_config` is Python. There could literally be a "import zsh history" button if all else fails. 

Not a fan of marking things will-no-implement just because they haven't been implemented yet. The issue should stay open until we have some kind of real answer.

**Comment by jesse-c** [comment]
I've just used @rsalmei's tool successfully. Thanks for making it.

**Comment by mcku** [comment]
There is a peculiarity with zsh history lines. For some reason, some UTF-8 strings are encoded in a way that is not understandable by some editors, including vi and gedit. 
Here is a command, just as an example: 
`echo Sh Ş - Gh Ğ - Ue Ü - Ie İ` 
now vi .zsh_history shows on the respective line: 
`: 158....74:0;echo Sh Å<83>¾ - Gh Ä<83>¾ - Ue Ã<83>¼ - Ie Ä°`

however same line is correct on fish history:
`- cmd: echo Sh Ş - Gh Ğ - Ue Ü - Ie İ`

interestingly, `tail`ing either of the history files yields correctly displayed lines.
hence fails the tool with the following:

@rsalmei i wish i had the time to go deeper but can post to somewhere else if fits better. This is definitely a blocker for me to switch to fish. :-(

**Comment by timokau** [comment]
It's not actually utf-8. See my comment [here](https://github.com/rsalmei/zsh-history-to-fish/issues/2#issuecomment-601642305).

**Comment by mcku** [comment]
Thank you for the pointer @timokau.

**Comment by faho** [comment]
Okay, there is an external tool, if you want, use that.

The zsh history format is sufficiently awkward that I don't feel like we need to ship something here.
