### ISSUE TITLE
How to check if a given variable is an integer or not?

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#4413]
This is just a question, so the info like version of fish-shell is unnecessary.

I'm writing a fish script, and it prompts for an input in middle of the script, and the input may be an integer, letter or just empty(`Enter` directly). Now I have to check if the input is not empty (not type `Enter` directly), it it contains something, check if it is an integer or a letter. I checked the documentation page and google or searched in this github page and got nothing.

So, how can I check an given variable is integer or not?

**Comment by krader1961** [comment]
The first thing to note is that in fish a variable can have zero, one, or more values. So you need to decide how you will handle each of those cases.

The fish version is still relevant since the answer depends on whether the `string` builtin is available. Assuming it is, and you have confirmed the var has a single value, you can do something like
 
```
if not string match -q -r '^\d+$' $var
    echo invalid integer
end
```

If you're dealing with a fish version that does not have the `string` builtin you'll need to use `awk` or a similar command to validate the value.

**Comment by c02y** [comment]
My fish shell version is very new (version 2.6.0-277-g8e2d1657-dirty), so I thought it was unnecessary.

Thanks, it works.
