### ISSUE TITLE
Feature request: Blacklist "dangerous commands" from completing

### ISSUE THREAD

**Issue by onodera-punpun** [fish-shell/fish-shell#4441]
The problem: I've had numerous times commands accidentally complete to `rm -r *` or similar dangerous commands because I too quickly (and without enough care) type `r` press `up arrow`, and hit `return`.

I know this is of course because of my own carelessness, but I still think it would be nice to blacklist certain commands (such as `rm -r *`) from completing. Alternatively the ability for users to blacklist commands from completing using regexp in some kind of config file.

**Comment by mqudsi** [comment]
I’ve been guilty of that as well, but note that this isn’t a command being completed but rather history search. Unlike ‘complete’, there’s really no heuristic to speak of at play here.

**Comment by zanchey** [comment]
See also #1511.

**Comment by mqudsi** [comment]
I'm closing this for the same reasons as #1511. This isn't likely to be implemented, there isn't a definitive solution suggested to the problem described, and it's a rather vague issue.

@onodera-punpun please feel free to comment back if you have more to add here, in particular, please read the objections to #1511 and note my comment above: it appears your concern is with history suggestions rather than completions and that's (currently) a very naive builtin with no specialization or customization options to speak of.
