### ISSUE TITLE
Disable escape as meta key

### ISSUE THREAD

**Issue by schvabodka-man** [fish-shell/fish-shell#4451]
Are there any possibility to disable alt key behaving as escape? I can't find anything about that in docs

**Comment by faho** [comment]
Could you expand a bit more on what you mean?

In a certain sense, "alt" _is_ escape - when you press alt+something, the terminal sends a specific sequence. What sequence in particular depends on the exact keys pressed and also on your terminal - try `fish_key_reader` to see what your particular setup sends.

However, usually stuff like alt+x will send `\ex` in fish notation - that's "an escape character, then an x". So holding down the "alt" key here added an escape character, which makes this indistinguishable from pressing escape and then x, except through timing.

For that, we have the $fish_escape_delay_ms variable - anything above that value (which is 300ms by default, and 100 ms in vi-mode) will be taken as "escape and something", anything below it will be understood as "alt and something".

(and just to be clear, usually the "alt" key by itself sends nothing, so there's no way for fish to figure out that it was pressed on its own)

So:

- Are you pressing alt and the thing you have bound to escape happens? That'd be weird

- Are you pressing alt+something and the thing you have bound to escape happens? Do you have something bound to alt+something?

- Something else?

**Comment by schvabodka-man** [comment]
I mean the possibility to alt act like different key in shell, not like escape. Is it actually possible or is it problem releated to my terminal app itself? I'm bad at unix shell(i prefer emacs frontends to all the stuff but sometimes i'm going to plain shell), so sorry for stupid question.

**Comment by faho** [comment]
You _cannot_ have alt act like a key on its own, _at all_.

You _cannot_ have "alt+x" look any differently than "escape+x", except via relying on timing.

That's not an issue with the shell nor with any particular terminal application. It's how UNIX terminals work.

Now, if you want to do something when you press escape, you can bind that. If you want to bind "escape+something" to something different than "alt+something", you could theoretically switch bind modes when you press escape and then make it react to other keys differently, which would effectively allow that, but that's advanced stuff, which is why I'm asking what exactly you want to do.

**Comment by schvabodka-man** [comment]
Ok, thanks for response. I think you can probably close this issue.
