### ISSUE TITLE
Job control issues with fisherman

### ISSUE THREAD

**Issue by kballard** [fish-shell/fish-shell#4477]
It looks like 93dad29ec670ffdcbb99aee082b2091b84d57e48 (set `COLUMNS` and `LINES` earlier) introduced a regression which causes `fisher update` to hang forever as its child `fish -c curl …` commands get suspended (see fisherman/fisherman#403).

**Comment by zanchey** [comment]
To be clear, the problem here is running any `fish -c` command in the background:

```fish
> fish -c "echo abc" &
> fg
Send job 1, 'fish -c "echo abc" &' to foreground
abc
```

**Comment by zanchey** [comment]
Entertainingly, I can only get this to happen on macOS, not on Debian Linux.

**Comment by mqudsi** [comment]
Is it a POSIX_SPAWN issue? Can you reproduce if you compile with `-DFISH_USE_POSIX_SPAWN=0`?

**Comment by floam** [comment]
You can also set `fish_use_posix_spawn` to 0 in the environment before starting fish, no need to recompile.

**Comment by zanchey** [comment]
No, the problem is that `reader_init` calls `get_current_winsize`, which calls `export_new_termsize`, which writes the termsize to the terminal via an ioctl. If the process is in the background, it gets SIGTTOU.

The termsize needs to be written back where possible because sometimes fish changes it (see #3746), but I wonder if this is trying to be too clever.

In any case, only writing the terminal size back when the fish process group is in the foreground should solve this.
