### ISSUE TITLE
Muparser provides too old configure, config.guess and config.sub

### ISSUE THREAD

**Issue by extrowerk** [fish-shell/fish-shell#4501]
They don't know about Haiku. Is it possible to update them?
autoreconf 2.69 cannot update them because:

> "configure.ac:16: error: possibly undefined macro: m4 include"

and

> "configure.ac:60: error: possibly undefined macro: AC_BAKEFILE"

Tested with the current git version.

**Comment by ridiculousfish** [comment]
Oh gross...

**Comment by ridiculousfish** [comment]
Long term fix is to eliminate separate muParser build.

**Comment by miqlas** [comment]
We got system provided muparser. Is ot possible to force the build system to use that? Pcre already allows it.

-- Z.

2017.10.24. dátummal, 7:13 időpontban ridiculousfish <notifications@github.com> írta:

**Comment by ridiculousfish** [comment]
We would like to fork muParser to remove features such as exception handling, so we aren't going to attempt to support building against a system muParser.

**Comment by mqudsi** [comment]
Does `cmake` work any better?

**Comment by miqlas** [comment]
Nope as the main cmake file calls configurein the muparser folder.

**Comment by data-man** [comment]
And why not use [libqalculate](https://github.com/Qalculate/libqalculate) or [exprtk](https://github.com/ArashPartow/exprtk) (it's awesome!)?

**Comment by ridiculousfish** [comment]
Well that ship has sailed! No doubt those are awesome and fast libraries, but the key idea for the moment is to simplify. Unifying the build under CMake without calling out to autotools is the next step.

**Comment by timofonic** [comment]
@ridiculousfish Why not simplify and improve at same time?

What about adopting Meson? It seems most major projects are switching to it. Would that solve the CMake issues too?

**Comment by faho** [comment]
@timofonic: @floam and me have looked into meson, and while the syntax is nice, it has a few issues for us.

One large thing is that it (and ninja) are rather new. New enough that they'd prevent us from building on Ubuntu before 16.04, which is used by Travis (our CI system). Also, since this is a shell we try to support older distributions that might be used on servers even with newer releases - e.g. RHEL 6.

And cmake really isn't _bad_ and doesn't have those issues. So it's a nice compromise.

And meson really wouldn't solve the issue at hand - which is that muparser still uses autostuff. So we'd have to write meson definitions for it, just like we could write cmake definitions for it now.

**Comment by ridiculousfish** [comment]
IMO muParser is totally fine - its build is complicated but not essentially so, which is to say we can produce a simple CMakeLists.txt for it. That's what I'm working on.

**Comment by faho** [comment]
This would be made moot by #4736.

**Comment by faho** [comment]
It's moot now. muparser is no more.
