### ISSUE TITLE
Request for feature: Special operator to assign command output 

### ISSUE THREAD

**Issue by monstruooo** [fish-shell/fish-shell#4526]
I was wondering if it's possible to get rid of parentheses/brackets for command substitution to allow more neat python-like assignment to variables.
Something like:
```
varable = command1 |
          command2 |
          command3 ;
```

Or: 

```
variable = if test condition ...
                blah blah blah
                ...
```
This is really one of the features of bash that makes code look kind of jumbled 

If it's difficult to achieve with the regular =, maybe you can introduce a special operator like, say, =;  or =|

So, the code would look like:
```
variable =; command1 
```
or:
```
variable =; if <test condition>...
```
or: 
```
variable =| command1 |
            command2 |
            command3 ;
```

**Comment by faho** [comment]
This won't be added - see "[The Law Of Orthogonality](http://fishshell.com/docs/current/design.html)".

One of the nice properties of fish's language is that it is so small - there isn't a huge amount of syntax to remember. Especially in comparison to sh, there are a lot of things that we just don't have as different syntactical concepts (e.g. we don't have `$''` quoting or `<<<` "heredocs" or `$*` vs `$@`).

What you are asking for is additional syntax that is pure sugar - it doesn't allow new things to be expressed, it just allows expressing the same old things in a (subjectively) more pleasing manner.

>This is really one of the features of bash that makes code look kind of jumbled

One of the features of sh-code that trips up many a newbie is that there cannot be a space between the variable name and the "=". E.g.

```sh
VAR=something # sets $VAR to "something"
VAR = something # executes the command "VAR" with the arguments "=" and "something"
```

This would have to have that property as well, because variable names can look like commands - e.g. I can call a variable "git", so what should

```fish
git = command1
```

do?

Plus, fish actually does not use "=" anywhere else, so this would be weirdly inconsistent.

>varable = command1 |
          command2 |
          command3 ;

So... what would this actually currently look like?

```fish
set variable (command1 | \
              command2 | \
              command3)
```

The major annoyance here is the `\\`. Otherwise it's just a matter of getting used to `(command)`, which is one of our syntactic concepts.

And #1285 asks for allowing pipes across lines, so this would turn into

```fish
set var (command1 |
         command2 |
         command3)
```

**Comment by monstruooo** [comment]
The thing is that I myself don't mind bash syntax. I write extensively in bash including rather complex scripts. But many people do seem to find bash syntax ugly or low on readability.  I hear it all the time. This is basically the main disadvantage with bash/shell scripts  as I see it. It's not that I can't write in it. It's that they prefer to read something in the style of python. 

This is why allowing pipe chains across line actually is a great point. I do it all the time. As well as opening new lines with indentation after logical operators. Like, say:
```
command1 &&
    command2 ||
    command3
```
I am splitting my pipelines and indenting them as well. These cosmetics are important because people don't like to read bash/shell scripts.  It's a bit like mouse clicks GUI designers are looking to reduce in their programs. These are mouse clicks people need to do in their brains to read scripts and the less brain clicks they do, the easier to read they find it

At any rate, I see your point. And you right about =. No problem. Incidentally, Why not?
```
set -c variable command1
```

**Comment by monstruooo** [comment]
This is an example from one our own scripts
```
seconds_behind=$(
	echo "$status" |
	egrep Seconds_Behind_Master |
	cut -s -d: -f2 |
	# remove leading/trailing space
	xargs 
)
```

Now if I can do it as, say: 
```
set -c seconds_behind
	echo "$status" |
	egrep Seconds_Behind_Master |
	cut -s -d: -f2 |
	# remove leading/trailing space
	xargs 
```
or even as:
```
set -c seconds_behind echo "$status" |
	egrep Seconds_Behind_Master |
	cut -s -d: -f2 |
	# remove leading/trailing space
	xargs 
```
, it would be perfect

From my experience, 50% of the bitching of "It works very well but please next time do it in python" comes because of this:
```
seconds_behind=$(echo "$status" | egrep Seconds_Behind_Master |	cut -s -d: -f2 | xargs )
```

**Comment by faho** [comment]
>Incidentally, Why not

>set -c variable command1

>? Then you don't need to use = at all

At that point, what have you gained? Instead of typing `()`, you're now typing `-c `, so you haven't saved any characters. And instead of always doing the same thing (`()`, when you want to capture a commands output), you now have a special "magic" option that does something different than what the syntax would suggest.

>"It works very well but please next time do it in python"

There's a reason python is always brought up as "the cleaner alternative" to shell scripting, and that's because it's actually very nicely designed. And its design is expressed in "The Zen of Python, by Tim Peters", which you can read by typing `import this` in an interactive python session.

It says (among other things):

>Readability counts.

and

>Special cases aren't special enough to break the rules.

Now, you've zoomed in on the first one of these, in particular your own interpretation of what is "readable", and completely forgot the second one.

I posit that things are readable when you can figure out what is going on at a glance.

In this case, that means that you should make the commands that are being run explicit, not implicit. A "-c " somewhere else in the line shouldn't change e.g. a "rm -rf /" from a string literal into a command that will actually run.

>From my experience, 50% of the bitching of "It works very well but please next time do it in python" comes because of this:

Honestly, I think you are looking at this line wrong. The "do it in python" stuff comes not from the `$()`, but from a few other things. Among them that POSIX-y shell scripting (like bash, dash, zsh etc) has a reputation for being dangerous (which is kinda true - dealing with spaces in filenames is a PITA), and in your particular case that you use `xargs` to trim whitespace.

Let me rewrite your code in what I consider to be nice fish script:

```fish
set -l seconds_behind \
	(string match 'Seconds_Behind_Master*' -- $status |
	cut -s -d: -f2 |
	# remove leading/trailing whitespace
	string trim)
```

Now, granted, we don't have a great replacement for `cut` (though one could use `string replace -rf 'Seconds_Behind_Master.*:' ''` instead of both the match and the cut), but isn't `string trim` nicer than abusing `xargs` here? Isn't `string match` a bit more readable than `grep` (if you don't already know it)? Isn't it nice and clear which things are executed (`string` twice and `cut` once, plus `set`)?

Of course someone who really believes this should be rewritten in python might argue that this is stringly typed and that it should really be using more expressive data structures instead of string matching, and I can't say that's always incorrect.

But that's not about the parentheses at all.

**Comment by monstruooo** [comment]
Look. I've never read a serious scientific paper that investigated the issue of readability. So this is a bit my guesses based on my experience. But as far as I could see, readability is very much related to white space and new lines. Basically you want to separate the elements within your action with white space and your actions by starting them on new lines. From this perspective, a pipe is more readable when every next command starts on the next line. That guy makes sense when he asks for multi line pipes. 

Now I would (reluctantly) agree that my bitching about parenthesis/brackets is more about cosmetics than multu-lining pipes and other constructs. And you have a point about set -c. Still, I think the best in terms of readability would be something like this:
```
output varable
    command1 |
    command2 |
    command3
```

now I don't want to waste your time since this issue is basically closed and I feel like I am now more like arguing just for the sake of it. But, I mean, pipes are kind of important in shell. In some respects, you can say, shell is basically a pipeline oriented language, unlike say functional or object oriented. You want to have it neat and pretty

PS

I liked string. Wasnt aware. I just started. But I am a fan. I want to migrate some of my scripting to fish. But right now my problem are conditionals. It comes out that double brackets prevent some errors that "if test" doesnt

**Comment by monstruooo** [comment]
I dont want to be an annoyance (I am still probably one). But just to cap it all, I just wanted to show you how we do it. In my view, you are missing a big part of the story. But maybe when you see it, you will have a better idea of what I have in  mind
```
function is_empty () { # space is not value, unlike [[ -z ]]
        echo $* |
        egrep -q -x '\s*'
}

function all_color_hosts () { # print all hosts in color environments
        for host
                in {master:dbmaster,auth1,auth2,emaildb}.{orange,red,blue,green,gold,stress}.websaas
        do
                echo $host
        done |
        sort -b -t. -k2 # sort by color
}

function ignore_host () {
        local host
        host="$1"
        is_empty $host &&
                return 2
        echo $host |
                egrep -q -f <(
                        echo "$ignore_hosts" |
                        # empty lines make grep match everything
                        egrep -v -x '\s*' )
}

########## Populating the list of all hosts and the list of masters

if
        is_empty $*
then
        hosts=$(
                all_color_hosts )
else
        hosts=$*
fi

```

**Comment by faho** [comment]
I'm sorry, but I don't see how that has an issue with command substitutions.

For me, as someone used to shell scripting, the biggest issue there is your idiosyncratic formatting.

I can see how all the weird symbols might be overwhelming, but, as it turns out, there's much less of that in fish.

Here's an attempt at a rewrite in fish:

```fish
function all_color_hosts -d "print all hosts in color environments"
        set -l hosts {master:dbmaster,auth1,auth2,emaildb}.{orange,red,blue,green,gold,stress}.websaas
        printf '%s\n' $hosts | sort -b -t. -k2 # sort by color
end

# This is unused because I could not find any place you used it.
function ignore_host -a host
    string match -qr '^\s*$' -- $host; and return 2
    if not contains -- $host $ignore_hosts
        echo $host
    end
end
    
# Whitespace is not a value, unlike with `test -z`.
# If you want, you can put this into its own function.
# I didn't because it's one simple command.
if string match -qr '^\s*$' -- $argv
    set hosts (all_color_hosts)
else
    set hosts $argv
end
```

Note that some of the changes are applicable to the bash version as well - using `printf` instead of `echo` saves a for-loop, for instance.

**Comment by monstruooo** [comment]
I am not sure what you call idiosyncratic. If you refer to my style of multilining everything, then you should keep in mind that if the ancients allowed you to multiline if or for constructs this way in bash, then it's for the reason.  This is because God saw that it was good. 

I was also checking it with people in the office and they said that it reads easier. The patriarchs knew what they were doing

**Comment by monstruooo** [comment]
In general the fish syntax is not bad. But what about that multi-lining of pipes? There are some issues with escaping new lines with backslash. It often gets lost when you copy code between editors or in emails
