### ISSUE TITLE
OS X High Sierra: unicode in `fish_prompt` gets wrong length calculated

### ISSUE THREAD

**Issue by paulswartz** [fish-shell/fish-shell#4539]
fish version: 2.6.0 and fa57565
OS: OS X High Sierra, 10.13.1

After upgrading, having a unicode character in my prompt (along with a right prompt) has the size calculated incorrectly.

<img width="374" alt="screenshot 2017-11-15 15 29 48" src="https://user-images.githubusercontent.com/214921/32858656-31e45652-ca1a-11e7-9f76-d9944e4a382a.png">

In the above screenshot, everything is normal when I have a fully ASCII prompt. When I source my `fish_prompt` to re-add the Unicode character, the cursor is positioned on the next line.

Everything was working normally before the update to High Sierra. It's not working in either iTerm or Terminal.

Happy to get any other debugging information.

**Comment by anordal** [comment]
Is that a double width character? Which codepoint(s) is it?

**Comment by paulswartz** [comment]
It's🍺  BEER MUG' (U+1F37A)

**Comment by anordal** [comment]
It looks as if fish doesn't account for character width when calculating the placement of the right prompt: Single-width characters are okay (even multi-codepoint characters are accounted for), yet for each beer, the right prompt gets shifted one more character onto the next line.

    function fish_prompt
        set beer (printf '\xF0\x9F\x8d\xba')
        printf '%s' $beer$beer$beer
    end
    function fish_right_prompt
        echo 0987654321
    end

I'm able to reproduce in all terminals I have handy: xterm, gnome-terminal and weston-terminal.

**Comment by ridiculousfish** [comment]
Probably `fish_wcwidth` needs to be updated.

**Comment by faho** [comment]
This works for me if I set HAVE_BROKEN_WCWIDTH to 0, i.e. rely on the OSs wcwidth. Maybe it's time to start relying on that again? It seems like the situation has improved dramatically.

**Comment by floam** [comment]
I agree, it seems now we are the ones with the lousy implementation. 🤕

**Comment by wcandillon** [comment]
I'm having the same issue. For instance if I use an emoji in my git commit message, everything gets broken.

**Comment by faho** [comment]
@wcandillon: Which emoji are you using? Can you try #4554?

**Comment by heyarne** [comment]
I'm facing the same issue, described in some greater detail [here](https://github.com/rafaelrinaldi/pure/issues/57#issuecomment-355064905) because I thought it had to do with my theme.

**Comment by ridiculousfish** [comment]
This should be fixed in 5282d3e7110f40fc9cb51f4ae952f65000bbf0ae . Note that wcwidth isn't sufficient since Terminal and iTerm2 measure emojis differently, and even iTerm 2 allows this to be controlled with a preference. fish tries to guess the right emoji size, but this can be set by the user via `fish_emoji_width` in case fish guesses wrong.

Thanks for filing, please comment if you still see a problem. We can update the heuristic for any emulators that use width-2 emoji.

**Comment by ronjouch** [comment]
> This should be fixed in 5282d3e . Note that wcwidth isn't sufficient since Terminal and iTerm2 measure emojis differently, and even iTerm 2 allows this to be controlled with a preference. fish tries to guess the right emoji size, but this can be set by the user via `fish_emoji_width` in case fish guesses wrong.
>
> Thanks for filing, please comment if you still see a problem. We can update the heuristic for any emulators that use width-2 emoji.

@ridiculousfish reporting on latest master fish-2.7.1-1096-ga9e9af5c under GNOME Terminal 3.28.1 using VTE 0.52.1. Emojis behave bad by default, setting `fish_emoji_width` to `2` fixes the issue (see mandatory GIF below).

Can you update the heuristic? Thanks for fish! 🙂

![fish-emoji-width-2-gnometerminal](https://user-images.githubusercontent.com/522085/39103057-8bac950e-4676-11e8-9ee7-c5b9bb3ea61e.gif)

**Comment by ridiculousfish** [comment]
Ugh, my Ubuntu 16.04 with gnome-terminal has 1-width emojis. I guess this depends on something else. Let me try to report the 2-width case.

**Comment by jyn514** [comment]
I have the same issue with '▶️ ' in my prompt. It should be 1, it seems to be 2.

**Comment by faho** [comment]
@jyn514 The solution is always the same:

- Upgrade fish to >= 3.0.2
- Set $fish_emoji_width to 2 if your system does Unicode >= 9 (most likely yes)
- Set $fish_ambiguous_width to whatever width your terminal shows ambiguous characters at (in this case 2)
- Don't use ambiguous characters of differing widths as that's not expressable.

In this case this character is of ambiguous width so do `set -g fish_ambiguous_width 2` (after upgrading to fish 3 if necessary), or set your terminal to show ambiguous characters as narrow instead of as wide.

----

In future please open a new issue or come to https://gitter.im/fish-shell/fish-shell. This issue is old, closed and doesn't really apply to the specific question.
