### ISSUE TITLE
Allow disabling universal variables

### ISSUE THREAD

**Issue by seagreen** [fish-shell/fish-shell#4542]
First, I apologize for opening such a large issue as my first issue. I just read the Design Principles document today and that alone convinced me to switch to Fish. The switch has gone swimmingly so far -- Fish is completely living up to its "Configurability is the root of all evil" principle.

I have run into one moderate problem. I already have a way to manage configuration state between machines (I use version controlled dotfiles, but the particulars of my solution aren't important here -- lots of other people use different ways). This makes Universal Variables a "Law of Orthogonality" violation for me. I'd like for my `~/.config/fish/config.fish` file to describe the entire state of Fish configuration on my machine, but now I also have to think about a second mechanism that also has its own way of storing state.

The few problems I've had so far have had to do with this issue, for instance not realizing I was setting a Universal Variables in my `config.fish` file, so when I removed it the setting still persisted. Persistent, mutable state on a machine is an easy way to create user confusion, and if we can get away without it (and the `config.fish` file already provides a great way of doing so) I think it's worth considering.

Also, thanks for Fish!

**Comment by zanchey** [comment]
fish uses universal variables a fair bit internally (eg colors, abbreviations), so this would be a pretty major change. Universal variables have been the source of some confusion and trouble over the years, but I'm not sure that replacing them with, say, autogenerated files in `~/.config/fish/conf.d/` would be any better.

**Comment by ridiculousfish** [comment]
fish poorly serves users who want to sync their dotfiles. There's also a substantial amount of hidden configuration: `abbr`, `funcsave`, and probably others I'm forgetting persist configuration in non-obvious ways. I'd love to see a thoughtful proposal on how these can be made more transparent to users and more easily modifiable with a text editor.

**Comment by faho** [comment]
I feel like there's two main problems with the fishd file:

- It's machine-specific, so copying it to a new machine won't help (#1912)

- It's weird in syntax (e.g. if I `set -U banana "some sentence"` it's going to be saved as `SET banana:some\x20sentence) (related to #3341)

The former would be solved by just always using the same file name, regardless of mac-address/hostname/whatever - preferably something that doesn't include `fishd` e.g. `uvars`, the latter would be solved by switching to a different format. #3341 proposes yaml or protobufs or json, but thinking about it now I'd just use fish syntax. Instead of `SET banana:some\x20sentence`, just use `set -U banana 'some sentence'` - or still keep the `SET` to make it clear this isn't some arbitrary script but change the escaping to something readable.

I feel like this is "more transparent" because it removes the confusion about which file will be used, makes the name more related to the current purpose (fishd is dead) and makes the syntax easier to understand.

>more easily modifiable with a text editor.

With syntax more closely aligned with fishscript, it would already be more easily modifiable. However, we'd need to nail down the semantics of changing it - the file currently says "Do NOT edit it directly, your changes will be overwritten.". Does that actually happen? It seems like it doesn't. We'd need to make sure of that.

Also, we currently have some `__fish_init_*` variables in there that some people might like to delete since they look ugly. That would cause some initialization to run again, so we would need to pick a nicer scheme.

**Comment by ridiculousfish** [comment]
Making the file name fixed, and eliminating the special syntax, I think would be good enough. Users with network home directories can put their variables as globals in `config.fish`.

The comment about "Your changes will be overwritten" is indeed false. It used to be that fishd (the daemon) held the contents in memory; now the file itself is the source of truth. Allowing edits seems harmless.

(I had some wild ideas about making it literally just fish code that gets sourced, but that lead to some ugly problems around ordering and erasing variables.)

**Comment by faho** [comment]
>(I had some wild ideas about making it literally just fish code that gets sourced, but that lead to some ugly problems around ordering and erasing variables.)

My idea was basically a restricted subset of fish, where you can only do `set -U` (plus an optional "-x") and no expansions. But that would possibly take _more_ explaining than using `SET` and the usual tokenization rules.

>The comment about "Your changes will be overwritten" is indeed false. It used to be that fishd (the daemon) held the contents in memory; now the file itself is the source of truth. Allowing edits seems harmless.

How would that work on the race condition front? I think fish holds a lock when it's modifying that file, correct? Any old text editor wouldn't do that.

----

And regarding the internal variables I mentioned: I think we should replace the `__fish_init_2.X.Y` vars with something like `__fish_initialized $number`, and then compare the versions where we previously tested the variable existence. E.g. set it to "300" for 3.0.

That would leave one variable, instead of our current 3.

**Comment by floam** [comment]
> __fish_initialized $number

I dig that. I've been loathe to add new ones to check for in a couple cases where it might be useful because I haven't wanted to pile up more.

**Comment by ridiculousfish** [comment]
> How would that work on the race condition front? I think fish holds a lock when it's modifying that file, correct? Any old text editor wouldn't do that.

fish does its best with the usual safe-save algorithm. It never modifies the file; instead it reads the old file, populates a new file, checks to see if the old file has changed (if so, starts over), and then moves the new file into place. 

If you break the lock you might see some dropped updates, but you shouldn't be able to see outright corruption.

> And regarding the internal variables I mentioned: I think we should replace the __fish_init_2.X.Y vars with something like __fish_initialized $number, and then compare the versions where we previously tested the variable existence

Yeah!

**Comment by seagreen** [comment]
Thanks for the thoughtful response to this issue. As I said I was hesitant about opening it at all and would have been fine if someone had just smooshed the "Close" button, but I'm glad that didn't happen.

A few thoughts:

+ Feel free to change the title.  The suggestion that Universal Variables could be toggleable is a "Configurability is the root of all evil" violation, I just thought it might go over better than "Rethink Universal Variables entirely.

+ Improving on this part of the situation would be really exciting:

> fish poorly serves users who want to sync their dotfiles. There's also a substantial amount of hidden configuration: abbr, funcsave, and probably others I'm forgetting persist configuration in non-obvious ways. I'd love to see a thoughtful proposal on how these can be made more transparent to users and more easily modifiable with a text editor.

I've been striving as hard as I can for declarative configuration on my machine. One of the most difficult things about this is user programs who scatter their configuration across multiple, badly documented files, so I'm happy to see Fish cares about this issue. A list of the current places Fish stores state would also be helpful to me.

+ This part is really good to know:

> The comment about "Your changes will be overwritten" is indeed false. It used to be that fishd (the daemon) held the contents in memory; now the file itself is the source of truth. Allowing edits seems harmless.

My current strategy is to version the `fishd.<machine_name>` file and whenever it changes (for instance when I set a universal variable by accident) just delete it and let Fish recreate it, glad to hear changes to it won't be rewritten once the file's deleted.

+ Perhaps the best way to proceed would be to draw a clear separation between the core of Fish and the tools to configure it. Fish the language could be written totally agnostic of the tools that will be used to change it, so it won't include things like special persistent variables. Then (still distributed with Fish, but conceptually separate) could be a command to configure fish imperatively by manipulating your config files. This would also provide a nice answer to the "why does fish include a webserver" people -- that the language and the webserver are two totally separate concepts, just bundled together for convenience.

**Comment by faho** [comment]
>A list of the current places Fish stores state would also be helpful to me.

Off the top of my head, all places that fish writes to:

- $XDG_CONFIG_HOME/fish (where $XDG_CONFIG_HOME defaults to $HOME/.config when unset) for most things (this includes config.fish, conf.d/*.fish, functions/*.fish and the fishd file) - these you probably want to keep

- $XDG_DATA_HOME/fish (defaulting to $HOME/.local/share/) for history and generated completions - these can be regenerated, but history is of course dependent on your input

- fish_config and some completions write to $XDG_CACHE_HOME/fish (default $HOME/.cache) - these should be completely safe to remove

Also in some cases $TMPDIR (or /tmp) (e.g. psub's temporary file and the named pipe to communicate uvar changes), but these are very much temporary.

Which of these do you consider "state"? Personally, I'd just backup/share ~/.config/fish in its entirety. Which currently has an issue with the uvar file (`fishd.gibberish`), but we've talked about changing that.

>This would also provide a nice answer to the "why does fish include a webserver" people

If fish includes a webserver, then so does python - because that's what we use. Personally, I don't have too much sympathy for people who think that's an issue.

>that the language and the webserver are two separate concepts, just bundled together for convenience.

It already is. `fish_config` is an entirely optional part of fish (though it'd be nice if the presets it offers were more easily accessible without it). You can remove the entire thing. There are even distributions that package it separately.

>Fish the language could be written totally agnostic of the tools that will be used to change it, so it won't include things like special persistent variables.

I don't think we want much modularisation, because we want to have a baseline of stuff that is available. And it really wouldn't gain much, because you can already basically treat uvars as an implementation detail, if you use global variables yourself.

There are a few universal variables that fish sets itself:

- `__fish_init_*` variables to guard some initialization (and upgrade code) - like I said, I'd consolidate this under one variable

- `fish_greeting` as a default (i.e. it's guarded with `if not set -q fish_greeting`)

- The `fish_*color*` as a default

- `fish_key_bindings` as a default

- `abbr` uses uvars as default, but you can use global ones instead

The default ones are all set after config.fish is read, so you can simply override them with `set -g var`. As you can see, the only uvars you can't go without are the `__fish_init_*` ones.

(Plus the classic+vcs prompt uses a uvar, which we might want to change)

**Comment by seagreen** [comment]
> Which of these do you consider "state"? Personally, I'd just backup/share ~/.config/fish in its entirety. Which currently has an issue with the uvar file (`fishd.gibberish`), but we've talked about changing that.

Thanks for the summary of where Fish stores stuff. Now that I understand it your plan of backing up just `~/config/fish` sounds perfect to me.

> I don't think we want much modularisation, because we want to have a baseline of stuff that is available. And it really wouldn't gain much, because you can already basically treat uvars as an implementation detail, if you use global variables yourself.

The problem is right now if you use `set` you have to remember which variables are uvars and which are globals. I think that `set` is such a basic function it would be good if it was as consistent as possible, and we had a separate function (eg `fish_set` or something, not sure of the name) that could be used to imperatively configure Fish.

Pretty much the first thing I did when I installed Fish was add `set fish_greeting ""` to my `config.fish`, decided maybe I liked the greeting, removed it, and then got confused about why the greeting wasn't showing up. Consistency is really important to user happiness, and different `set` targets behaving differently is rough on that front.

**Comment by Darkshadow2** [comment]
You can use `set` to figure out what is global and what is universal.

`set -U` will show anything that is universal
`set -g` will show anything that is global
`set -l` will show anything that is local (probably won't print anything at the prompt)
`set -x` will show anything that is exported
(and you can mix `-x` with the others, `set -gx` will show global exported, etc)

And, new, there's a `set -S` that really shows everything. I can't remember if this is only in 3.0 or also in 2.7, though.

You can also test for it specifically, if you want:

```fish
set -lq some_var; and echo 'Is local'
set -gq some_var; and echo 'Is global'
set -Uq some_var; and echo 'Is universal'
```

**Comment by mqudsi** [comment]
Universal variables have already been moved to a more discoverable (and syncable) location for fish 3.0.

The following may be placed in config.fish to unset all universal variables at startup (it does not shell out externally and should add minimal/no overhead), which is probably a better option for explicitly disabling the universal variables without breaking the behavior at the prompt for the user:

```fish
for v in (set --show | string match -e ": set in universal scope" | string replace -r '^\$([^:[]+).*' '$1')
    set -e $v
end
```

**Comment by comfortablynick** [comment]
@mqudsi thanks for this!

I can see the point about not wanting options to configure the behavior, but like the OP, I prefer for my config.fish to contain the entire configuration. I switch between three machines and two platforms, so the `fish_variables` file is useless to me.

I've added the code you posted to unset universal variables and I'll see how that works. Previously, I was deleting the `fish(_universal)_variables` file on each exit from the shell, but I'm sure that was creating some problems without me knowing it.

**Comment by faho** [comment]
>I've added the code you posted to unset universal variables and I'll see how that works. Previously, I was deleting the fish(_universal)_variables file on each exit from the shell, but I'm sure that was creating some problems without me knowing it.

That was rerunning a bunch of setup code every time.

How about just not using universal variables? If you don't set any, they should be generally harmless.

**Comment by comfortablynick** [comment]
> How about just not using universal variables? If you don't set any, they should be generally harmless.
I really like the abbreviation feature, and AFAIK, that is only done through universal variables, correct? I would love if abbreviations could behave like functions, which work exactly as I would hope.

**Comment by krader1961** [comment]
@comfortablynick Abbreviations can be set using global rather than universal vars. If you're running 2.7.0 or newer just do `abbr -g abbr_name abbr_value`. If you're running an older version you first need to do `set -g fish_user_abbreviations`.

**Comment by comfortablynick** [comment]
> Abbreviations can be set using global rather than universal vars. If you're running 2.7.0 or newer just do `abbr -g abbr_name abbr_value`. If you're running an older version you first need to do `set -g fish_user_abbreviations`.

Awesome, I didn't realize this! Seems to work great. Thanks! 

So is this really all that's needed to run fish without universal vars, provided everything is set in `config.fish`?

**Comment by faho** [comment]
>So is this really all that's needed to run fish without universal vars, provided everything is set in config.fish?

It's not entirely _without_ uvars - we still use them for some internal stuff (we could remove some of that, but not all of it). But you can just pretend they don't exist and don't care about them, yes.

**Comment by krader1961** [comment]
Also, the upcoming fish 3.0 release has stopped creating a machine specific uvar file. Which makes it much easier to copy your *~/.config/fish* directory to different machines and immediately have the same color theme since the color theme vars are normally setup as universal vars.

**Comment by sullimander** [comment]
I'm using fish 3.0 and syncing my `~/.config/fish` directory, but any of the universal variables that were set using `$HOME` got expanded to the full path. My user directory is not the same on all the machines I'm syncing. Is there a way to save the `$HOME` into the variable and have it expand at run time? Thanks!

**Comment by floam** [comment]
If this is a universal exported for some external program, maybe you could just stick a literal `~` (not expanded) into your problem variable? A lot of software will expand it itself.

**Comment by floam** [comment]
Otherwise, you're probably going to need to do something when the shell starts in config.fish to set it appropriately on each machine. I don't think we are going to provide a means for the variables to be evaluated on `env_get()`.

**Comment by nhooyr** [comment]
@sullimander its probably best to set the universal variable you want in `config.fish`.

**Comment by floam** [comment]
I think we've made what accommodation we can for this use case with fish 3.0 by no longer having a machine-specific filename, and users can choose to wipe out uvars if they really are dead-set against the way fish works. We are not going to add a universal variable kill switch or move towards a general preference for globals over our universal variable paradigm. I'm going to close this one up.
