### ISSUE TITLE
XTerm Color Formatting Not Working For RGB

### ISSUE THREAD

**Issue by gyroninja** [fish-shell/fish-shell#4552]
Hello, I am using fish 2.6.0 and am running into an issue with the text formatting.
This issue was caused by using fish_config which when you change colors will set a color variable to a RGB value (eg. 00afff). I found that whenever a color variable has a RGB value, it doesn't work and just ends up printing as white text. If I switch the variable to using a name (eg. cyan), the color shows up just fine.
I have tried setting TERM to xterm and xterm-256color and neither worked.

I'm not sure if it's related, but bright colors don't work for me either.

This might also addressed with having fish_config only set variables that the terminal can support.

**Comment by ridiculousfish** [comment]
Thanks for filing. What terminal emulator are you using?

**Comment by gyroninja** [comment]
Terminal Emulator: UXTerm
OS: GNU/Linux (LFS 8.0)

**Comment by faho** [comment]
>This might also addressed with having fish_config only set variables that the terminal can support.

The way this is supposed to work is that you set the variables to whatever you want, and fish figures out what it should map to when printing. When your terminal supports truecolor (24-bit full RGB) it'll just send the color as the RGB sequence, when it supports 256 colors it'll map it to whatever it thinks the closest match is (and same with 8 colors).

Can you do `set_color 00afff | od -t x1z`? This'll show us what sequence fish sends.

Can you tell us if $fish_term24bit is set? If it is, fish thinks your terminal can do 24-bit. We have a heuristic to detect terminals that can do this. 
Newish xterms understand 24-bit sequences, but map them to the nearest color from the 256 palette, so we don't automatically enable it there. This may depend on build options, which, since you are on LFS, you might not have set.

If $fish_term24bit is set, try `set fish_term24bit 0`.

The output of `env` would also be useful. Feel free to censor any sensitive information there.

**Comment by gyroninja** [comment]
In both xterm and xterm-256color set_color produces:
`0000000 1b 5b 33 38 3b 35 3b 33 39 6d                    >.[38;5;39m<
0000012`
$fish_term24bit is not set
env:
`DEVKITARM=/opt/devkitPro/devkitARM
DEVKITPPC=/opt/devkitPro/devkitPPC
DEVKITPRO=/opt/devkitPro
DISPLAY=:0
EDITOR=emacsclient -t
LC_CTYPE=en_US.UTF-8
SHELL=/usr/bin/fish
SHLVL=5
TERM=xterm-256color
TZ=America/Los_Angeles
WIILOAD=/dev/ttyUSB0
WINDOWID=56623117
WINDOWPATH=7
XTERM_LOCALE=en_US.UTF-8
XTERM_SHELL=/usr/bin/fish
XTERM_VERSION=XTerm(327)
fish_color_autosuggestion=555
fish_color_command=cyan--bold
fish_color_comment=red
fish_color_cwd=green
fish_color_cwd_root=green
fish_color_end=green
fish_color_error=brred
fish_color_history_current=--bold
fish_color_param=cyan
fish_color_pwd_root=green
fish_color_quote=yellow
fish_color_redirection=cyan
fish_color_selection=rwhite--bold--background=brblack
`

**Comment by faho** [comment]
`\e[38;5;39m` (the 0x1b/"." is the escape character) is the 256-color sequence. In my uxterm, fish produces that exact sequence as well, and it results in a blue-ish color.

`set_color red` on the other hand produces `\e[31m`, which is the old-style 8-color sequence.

The reason fish is still using the 256-color sequence even with just TERM=xterm is because it assumes that it's a result of misconfiguration. When you set e.g. TERM=linux, `set_color 00afff` will produce `\e[36m`.

In your case, you should build xterm with `--enable-256-color`, which should result in a much better experience. See e.g. [arch's build script](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/xterm).

**Comment by gyroninja** [comment]
>assumes that it's a result of misconfiguration.
Oh, I didn't know that.
Rebuilding xterm with `--enable-256-color` almost works. The 256 colors work in xterm, but not uxterm for some reason.
This no longer seems like a fish bug, so I'll probably figure out the rest on my own.

**Comment by gyroninja** [comment]
Turns out when I was trying to run uxterm it was actually invoking the system xterm rather than the one in the same directory as the xterm that was just compiled.
Everything works fine now. :)
