### ISSUE TITLE
Fish sets $EDITOR to value from /etc/profile, as opposed to ~/.bashrc

### ISSUE THREAD

**Issue by process91** [fish-shell/fish-shell#4558]
Fish Version: 2.7.0
Linux 4.13.12-1-ARCH SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
xterm-256color

**Description:** On a fresh install of fish, $EDITOR variable is pulled from /etc/profile, rather than ~/.bashrc

**Steps to reproduce:**
In /etc/profile:
```
EDITOR=/usr/bin/nano
```
In ~/.bashrc:
```
EDITOR=/usr/bin/vim
```
Restart, and in a fish shell (in gnome-terminal) I have
```
> echo $EDITOR
/usr/bin/nano
```

**Comments:**

- This ended up throwing me because at the [end of the fish tutorial](https://fishshell.com/docs/current/tutorial.html#tut_universal) it gives an example of how to set the editor variable universally, however it did not work for me. Instead, I got a message that $EDITOR was shadowed by a global variable.
- It seems that fish only pulls certain variables from /etc/profile, EDITOR being one of them, as attempting the same thing with FOO did not result in anything ($FOO was unset in fish). I could not find any documentation indicating that fish would pull default variables from anywhere.
- If it is going to pull the EDITOR variable from anywhere, wouldn't it be better to pull it from ~/.bashrc?

**Comment by faho** [comment]
Fish does not read /etc/profile _or_ ~/.bashrc. It doesn't understand POSIX syntax, so reading them wouldn't work.

What happens here is that, somewhere in your login stack (IIRC modern gnome explicitly does this, even on wayland where it's not strictly necessary), a (non-fish) login shell is run. That then reads /etc/profile and starts your stuff (desktop environment and such). And because $EDITOR is exported (there'll likely be an `export EDITOR` somewhere in /etc/profile), any child processes of that shell inherit it, and any children of those (and so on).

>Instead, I got a message that $EDITOR was shadowed by a global variable.

Because variables that fish inherits are global (because no other scope makes sense), you get a global $EDITOR. And because universal is a larger scope, that global $EDITOR overrides whatever universal variable you set. So if you access it, you get the global one, not the universal.

>It seems that fish only pulls certain variables from /etc/profile, EDITOR being one of them, as attempting the same thing with FOO did not result in anything ($FOO was unset in fish).

As you see, it doesn't _pull_ them. It inherits them. Add `export FOO` to /etc/profile and log in again, and you should see $FOO.

So, here's what you should do:

- Set $EDITOR globally in config.fish
or
- Remove that $EDITOR setting from /etc/profile
or
- Set $EDITOR in /etc/profile to what you actually want
or
- `set -eg EDITOR` in config.fish

**Comment by process91** [comment]
Thanks very much, I appreciate you explaining that. On this system I've made the change in /etc/profile. The strange thing is that there's no `export EDITOR` anywhere in /etc:

```
> sudo grep -rn '/etc' -e 'EDITOR'
/etc/yaourtrc:15:#EDITOR="$EDITOR"
/etc/profile:30:EDITOR=/usr/bin/vim
/etc/skel/.bashrc:12:EDITOR=/usr/bin/nano
/etc/mail.rc:63:# Startup into $EDITOR in compose mode ("automatic `~e'").
/etc/environment:8:EDITOR=/usr/bin/nano
/etc/texmf/xdvi/XDvi:183:!!! the editor used for `forward search'; can also be set via $EDITOR, $VISUAL
/etc/texmf/xdvi/XDvi:184:!!! or $XEDITOR. Setting the X resource will override the environment variables.
```
Nor is there an `export Editor` in my home directory:
```
sudo grep -rnw '/home/username' -e 'export EDITOR'
/home/username/.local/share/fish/fish_history:3457:- cmd: sudo grep -rns '/etc' -e 'export EDITOR'
/home/username/.local/share/fish/fish_history:3461:- cmd: sudo grep -rnw '/etc' -e 'export EDITOR'
/home/username/.local/share/fish/fish_history:3465:- cmd: sudo grep -rn '/etc' -e 'export EDITOR'
```

Maybe it's something Gnome Terminal does directly, either way I appreciate you explaining the issue and the fix for it!

**Comment by faho** [comment]
>`/etc/environment:8:EDITOR=/usr/bin/nano`

That one's it. /etc/environment isn't actually a shell-initialization file, but a "KEY=VALUE" file read by `pam_env`, which your login stack runs. It exports variables automatically (since its reason for existing is to set up the environment for other programs).

**Comment by mboratko** [comment]
Thanks so much for your help!! You fixed my issue, and I also learned something about /etc/environment that I didn't know as well!
