### ISSUE TITLE
Rsync looks like it is going to autocomplete over ssh, but doesn't

### ISSUE THREAD

**Issue by aThorp96** [fish-shell/fish-shell#4561]
Fish version: 2.6.0
System: 4.14.2-1-MANJARO #1 SMP PREEMPT Fri Nov 24 11:15:23 UTC 2017 x86_64 GNU/Linux
Terminal Emulator: xterm-256color
I have tried fish without any third party custumizations and the error still occurs. 

The problem seems to arise when you press tab in an rsync command over ssh after imput such as `rsync foo@bar.com:~/`. After such iniput tab will prompt for the ssh key (as if it is trying to auto compete over the internet [that would be a neat feature]), and upon entering the correct password will show the autocomplete suggestions as if you hit tab following `ls`.

**Comment by faho** [comment]
>as if it is trying to auto compete over the internet [that would be a neat feature]

It actually _is_. See [the rsync completion script](https://github.com/fish-shell/fish-shell/blob/master/share/completions/rsync.fish#L127). It seems like that gives no results, and because it doesn't have "-f" (which it probably should if your token is a remote path), it's giving you local files as well.

Does `rsync --list-only foo@bar.com:~/` print anything (with the `foo@bar.com` replaced)?

**Comment by aThorp96** [comment]
Ah, it does seem to be printing both my remote options as well as my local files, and `rsync --list-only foo@bar.com:~/` lists my remote directories and files. Thanks!

**Comment by faho** [comment]
So you are saying that the completion is working correctly, only there was nothing to complete in your case?

**Comment by aThorp96** [comment]
Comletion is working correctly, I had such a vast currect directory and a small remote directory, I didn't see that fish listed the remote directories for autocompletion.
