### ISSUE TITLE
define list with multiple lines and comments

### ISSUE THREAD

**Issue by pleycpl** [fish-shell/fish-shell#4563]
```fish
$ fish --version
fish, version 2.7.0
$ echo $TERM
xterm-256color
$ uname -a
Linux hostname 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
```

Hi, In shell script with multiple line and comments

```bash
$ vim example.bash
#!/usr/bin/env bash
ARRAY=("a" "b"
         "c")
echo "${ARRAY[@]}"
 
ARRAY2=("a" # first element
     "b" # second element
     "c")
echo "${ARRAY2[@]}"
$ bash example.bash # ---------------------------- Run
a b c
a b c
```

But, in fish shell i dont know with comments, i test some cases.

```fish
$ vim example.fish
#!/usr/bin/env fish
echo "-------Case 1"
set array 1 2 3
echo $array

echo "-------Case 2"
set array2 1 2 \
             3
echo $array2

echo "-------Case 3"
set array3 1 \ # first variable
     2 \ # second variable
     3
echo $array3
echo $array3[1]
echo $array3[2]
echo $array3[3]
 
echo "-------Case 4"
set array4 1 # first variable \
     2 \ # second variable
     3
echo $array4
echo $array4[1]
echo $array4[2]
 
echo "-------Case 5"
set array5 1 # first variable \
     2 # second variable \
     3
echo $array5
echo $array5[1]
echo $array5[2]
$ fish example.fish # -------------------------------------- Run
-------Case 1
1 2 3
-------Case 2
1 2 3
-------Case 3
fish: Unknown command '2  # second variable'
example.fish (line 15): 
    2 \ # second variable
    ^
fish: Unknown command '3'
example.fish (line 16): 
    3
    ^
1  # first variable
1
 #
first
-------Case 4
fish: Unknown command '2  # second variable'
example.fish (line 24): 
    2 \ # second variable
    ^
fish: Unknown command '3'
example.fish (line 25): 
    3
    ^
1
1

-------Case 5
fish: Unknown command '2'
example.fish (line 32): 
    2 # second variable \
    ^
fish: Unknown command '3'
example.fish (line 33): 
    3
    ^
1
1

```

I searched, but i didn't find it. I think that maybe fish parser isn't working this case.

**Comment by faho** [comment]
Bash here has the advantage of having the parentheses, so it knows that the array isn't done yet. Fish doesn't have those, so you need to mask the newline to express that the `set` command continues on the next line.

The `\` also needs to be right before the newline, because otherwise it would be ambiguous (or disallow adding a space to a value).

I.e.

```fish
set array3 1 \ # first variable
     2 \ # second variable
     3
```

won't work. The `\` is in front of a space, so it should mask that space (or otherwise you couldn't use `\ ` to add a `' '` element, which is inconsistent). You might also notice that

```fish
set array 1 2 3 \ 
4 5 6
```

will set the array to `1`, `2`, `3` and ` ` (`string escape $array` to confirm), because that line includes a space after the `\`.

You can do one of two things:

- Add a line that is just a comment (plus whitespace)

```fish
set PACKAGES \
nginx supervisor rabbitmq-server \
    # Python packages
python3-dev virtualenv
```

works (though the reader will not recognize that).

Or

- Use `set -a` or `set -p` to set your array in multiple expressions

```fish
set array3 1 # first variable
set -a array3 2 # second variable
set -a array3 3
```

-----

I'm not sure there is something to do here - in general we try to keep the syntax lean, to optimize learnability (if that is a word) over code-golf prowess. So I'd rather you need to type a few characters more than introduce a new syntactical concept. And as you've seen, the current semantics don't allow for "just" adding it without introducing something new.

**Comment by pleycpl** [comment]
`set -a` and `set -p`  doesn't exists in document. https://fishshell.com/docs/current/commands.html#set

**Comment by faho** [comment]
>set -a and set -p doesn't exists in document.

Oops, sorry! They've only been added to current git master, which will become 3.0. I assumed they were in 2.7.0.

**Comment by faho** [comment]
Obviously, you can achieve the same behavior with repeating the variable name:

```fish
set -a var value # is equivalent to
set var $var value

set -p var value # is equivalent to
set var value $var
```
