### ISSUE TITLE
How install Python3

### ISSUE THREAD

**Issue by xavierartot** [fish-shell/fish-shell#4565]
Hi,
need Python3 to use nvim

I did whereis python
`/usr/bin/python`
How can alias python to Python?

I installed python3 with Homebrew and 
fish, version 2.7.0

here my $PATH
echo $PATH
/usr/local/Cellar/python3 /usr/local/Cellar /usr/local/sbin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /Library/TeX/texbin

uname -a
Darwin MBPs-MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64

xterm-256color

**Comment by faho** [comment]
I'm afraid I don't quite understand what you want.

> need Python3 to use nvim

So you should install python3 in a place where nvim can find it. It seems like you installed it, now what happens when you run `nvim`? What message does it print?

> How can alias python to Python?

I'm assuming you mean "alias python3 to python, so that I get python3 if I execute `python`". If so, you can do `alias python=python3`. However, that wouldn't help with your nvim issue because shell aliases/functions aren't accessible to external programs. You need to have the actual file in $PATH where nvim can find it.

>I did whereis python

If nvim wants python3, then it'll look for `python3`, so you should also do `whereis python3`.
