### ISSUE TITLE
completion -f

### ISSUE THREAD

**Issue by navossoc** [fish-shell/fish-shell#4585]
I'm trying to create a completion file for fish 2.7.

So I was looking at some examples.
I'm not sure if fish is not working properly or if I'm misunderstanding the flag.

For example:
`complete -c hugo      -l config     -f -d "Configuration file"`

If I type in the shell:
`hugo --config(tab)(tab)`

The first tab will add a space, ok.
The second tab will suggests files in my directory.

Is that right?

The doc says:
> -f or --no-files specifies that the options specified by this completion may not be followed by a filename.

I'm testing it on Win/MSYS2 and Linux/Alpine, but both presents the same behavior.

So, to avoid weird issues because of the environment.
Which is a good OS/distro to test fish?

**Comment by faho** [comment]
What is happening here is that fish isn't completing the argument to "--config", but the argument _after_.

Because options often take an optional argument, the default behavior for fish is to complete both the option's argument and other things (like the completion for the command itself) when an option has been given.

To stop this, either 

- Stop file completion in general - this would mean adding `complete -c hugo -f` and using "-f" for all other completions that are triggered in this case (all with matching conditions).

- Use "-r"/"--require-parameter" as well (or "-x"/"--exclusive" as a shortcut for both "-r" and "-f")

> Which is a good OS/distro to test fish?

Whatever you like should work. I'm on Arch, others are on macOS, or Ubuntu, or ....

There are systems that we have less experience with (and hence probably more bugs on) like OpenBSD or NetBSD, but your preferred linux distro should work.

**Comment by navossoc** [comment]
Thanks for the answer! But I still don't get it.

To be honest `hugo` was just an example I found on the repo.
I'm trying to write a completion for `docker` command (a new one), the current is not up to date.

So the best way to learn it is: doing one from scratch (I think), but no luck at all.

I have tried this ways:

```shell
complete -c docker -f
complete -c docker -s v -l version -f -d 'version info...'
```

```shell
complete -c docker -s v -l version -f -r -d 'version info...'
```

```shell
complete -c docker -s v -l version -x -d 'version info...'
```

That are my whole file, nothing more, nothing less. I'm missing something?

If I type in shell:
`docker -(tab)`

It shows the suggestion for `-v` and `--version` as expected.
After I highlight the suggestion with `tab` and press `enter` to select it, it becomes:

`docker --version(space)`

If I hit tab again it is still suggesting files on my current directory.

The behavior I expected is: after that flag option, it may suggest more flags like (`--host` or whatever), but no files at all.
This command don't ask for a file, that is what I'm trying to instruct the shell to recognize.

Is it possible or I'm still doing something wrong?

Thanks.

**Comment by faho** [comment]
Please confirm for me that

- You are actually using fish 2.7.0 (`echo $version`) - the behavior here changed in 2.7.0, and you definitely want the new one here.

- Your completions are actually the ones being loaded (i.e. nothing from the old completions works, yours is first in $fish_complete_path - `for file in $fish_complete_path/docker.fish; test -e $file; and echo $file; end` shows yours first).

--------

>After I highlight the suggestion with tab and press enter to select it, it becomes:

>docker --version(space)

>If I hit tab again it is still suggesting files on my current directory.

All of your versions work for me (i.e. they don't suggest files after "--version"), as they should, so I'm imagining that something is wrong with your system (see above).

>The behavior I expected is: after that flag option, it may suggest more flags like (--host or whatever), but no files at all.

a) Fish does not suggest options unless the token starts with a "-" already (this does not apply if the option is generated via complete's "-a" option)

b) If you use "-x", then it won't offer anything for the next token that you haven't offered via "-a".

IIUC, docker does the `docker subcommand` thing, in which case you want fish's usual behavior here. So you'll want to add "-f" to everything that doesn't explicitly take files (e.g. you might have a "--configfile" option that does take files), and you want the `complete -c docker -f` thing so it doesn't offer files by default.

So you'll want something like (note: I have no real knowledge of docker):

```fish
# These options don't take arguments at all (because they don't have "-r" or "-a"), so the "-f" isn't necessary.
complete -c docker -s v -l version -d 'Print version and exit'
complete -c docker -s h -l help -d 'Print help and exit'
# This one requires an argument, so it needs "-x". 
# __docker_print_hosts is a function that prints hosts 
# for docker. (Maybe use __fish_print_hostnames if you don't require something special)
complete -c docker -s H -l host -d 'Operate on host' -xa '(__docker_print_hosts)'

# Some subcommands - "__docker_needs_subcommand" is a function 
# that checks the commandline to see if the docker call given there is missing a subcommand.
# See the git or systemctl completions for how to write something like that, or use
# `__fish_seen_subcommand_from` for a simple (but sometimes too simple) solution.
complete -c docker -n '__docker_needs_subcommand' -fa 'start' -d 'Start a container'
complete -c docker -n '__docker_needs_subcommand' -fa 'stop' -d 'Stop a container'
# start takes files, stop doesn't (this is just a stupid example, after all).
complete -c docker -n '__fish_seen_subcommand_from start' -r
complete -c docker -n '__fish_seen_subcommand_from stop' -f # maybe use a function that prints started docker containers?
```

Note: I was a bit confused here myself. You do _not_ want the `complete -c docker -f` call, because that makes it impossible to have certain commands that do take files (like "start" in the example above).

**Comment by navossoc** [comment]
Yes, now it is working properly.

I did a full wipe on the MSYS2 and rebuild all again.

```shell
echo $version
```

> 2.7.0

```shell
for file in $fish_complete_path/docker.fish; test -e $file; and echo $file; end
```

> /home/Rafael/.config/fish/completions/docker.fish

---

> IIUC, docker does the docker subcommand thing

Yes, it does, you are absolute right about it.

I was taking the wrong approach even knowing I would need to change on the future. It was baby steps to understand how the completion really works.

I'm was really confused because on the documentation said something and never worked as expected, but now after a rebuild everything is working properly and everything make sense again.

Thanks for your help, sorry to wast your time.
You have a awesome shell here by the way 🏆 

[]'s
