### ISSUE TITLE
Vim plugin problem caused by fish

### ISSUE THREAD

**Issue by wuzzapcom** [fish-shell/fish-shell#4611]
Version:   
fish, version 2.6.0-572-gcb352317
OS:
macOS High Sierra.
Terminal:  
iTerm 2.
I have installed vim plugin [esearch](https://github.com/eugen0329/vim-esearch). It showed me errors and I [opened](https://github.com/eugen0329/vim-esearch/issues/30) issue about this.
As a result, described in that thread, I figured out, that switching vim shell to /bin/bash fixed my problem. And my question: how fish may affect vim? Why does this problem exists?

**Comment by faho** [comment]
Normally, the issue is that some vim plugins "shell out", i.e. call the shell to execute some script (not just `/some/path/to/something.sh`, but `$SHELL -c 'some commands'`). Obviously that won't work since those scripts expect a POSIX-compatible shell, which fish isn't.

I'd love it if these things just called /bin/sh, which they need to support anyways, but that's a lost cause. So you should `set SHELL=/bin/sh` in your .vimrc.

In this particular case, the issue is that fish doesn't understand the `&>` redirection. Instead this would have to be something like `2>&1 >/dev/null`, which should also work in POSIX-compatible shells.

I have no real idea why vim tries to open a tmpfile here - maybe it's redirecting output there, and since fish prints something here (an error message) it tries to read it? But why it's gone at that point I don't know.

**Comment by wuzzapcom** [comment]
Yeah, thank you, I've got your idea.
