### ISSUE TITLE
Proposal: Add `then` keyword can be used like `if`.

### ISSUE THREAD

**Issue by acomagu** [fish-shell/fish-shell#4622]
Almost part of Fish has beautifully designed but `if` is strange a bit, because of behavior of `and` or `or` command in CONDITION.

```
if false
    or true
    echo OK
else
    echo NG
end
```
It displays "OK", because the `or true` statement is also in condition part of if statement.

It's strange, because the `or` command is usually considered as normal command, not special statement, but in case of that it looks like part of `if` statement.

It seems be strange, and can cause unexpected behavior.

So instead of that, I use `and begin` keyword, like:

```
false; or true; and begin
    echo OK
end; or begin
    echo NG
end
```

But it's ugly so I want new `then` and `else` keywords can be used like:

```
false; or true; then
    echo OK
else
    echo NG
end
```

Thank you!

**Comment by faho** [comment]
>It displays "OK", because the or true statement is also in condition part of if statement.

This has been changed in [fish 2.3.0](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.md#backward-incompatible-changes).

Your initial command now behaves like you want, because the `and` and `or` statements are now considered to be part of the condition.

I feel like that solves the issue. If not please speak up!

**Comment by acomagu** [comment]
> Your initial command now behaves like you want, because the and and or statements are now considered to be part of the condition.

I mean, that behavior is strange, so I want `then` keywords instead.

Sorry for confusing!

**Comment by faho** [comment]
Oh, sorry for misunderstanding!

So, the thing is

>It's strange, because the or command is usually considered as normal command, not special statement, but in case of that it looks like part of if statement.

The other interpretation - that the `or command` belongs to the if-body - doesn't make any sense!

If you had

```fish
if a
   or b
       c
else
   d
end
```

And the `or b` was part of the body of the if-statement, then `b` would never be executed! Because it would only be reached if `a` was true, so the `or` wouldn't do anything. So the `or b` is dead code that you could just remove without any changes.

Similarly if it was `and b` instead it would _always_ be executed (if the body is reached of course), along with "c", so you could just leave the `and` off and have exactly the same result.

That's why it was changed.

-----

Regarding your proposal of a "then" keyword.... that's one of those things that adds another way to do things that are already possible, which isn't really necessary. I don't think we want to do that.
