### ISSUE TITLE
Allow to wrap argparse call

### ISSUE THREAD

**Issue by dwt** [fish-shell/fish-shell#4627]
## Environment
```
(virtualfish) dwt@crest ~/C/P/fish> fish --version
fish, version 2.7.0
(virtualfish) dwt@crest ~/C/P/fish>   echo $version
2.7.0
(virtualfish) dwt@crest ~/C/P/fish> uname -a
Darwin crest.fritz.box 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
(virtualfish) dwt@crest ~/C/P/fish> echo $TERM
xterm-256color
```
# Problem

I want to wrap a function call, which does it's own argument parsing via `argparse`. My problem is, that there seems to be no way, to tell `argparse` that I only care for my additional argument, and that it shouldn't raise an error for all the other arguments that I don't care for.

So, what I'm searching for is a way to tell `argparse` that it should ignore all other arguments, except the one I'm specifying, and especially shall not consume them, but only what was specified.

This seems not to be possible.

# Workaround
I'm currently using this technique to work around the problem

```fish
functions --copy __vf_new __vf__new_projects_original
function __vf_new --wraps=__vf_new
    set -l options (fish_opt --short a --required)
    argparse --name 'vf new' $options -- $argv ^/dev/null
    if __vf__new_projects_original $argv; and test -n $_flag_a
        cd $_flag_a
        and pwd >?$VIRTUAL_ENV/.project
    end
end
```

This seems to work, but only at the price, that I don't see any error messages from argparse anymore. So I'm searching for a better way.

Is there an extension of the c-implemented argparse possible, or is there a better workaround? I think that being able to wrap shell commands or fish functions with another function by enhancing the supported arguments is n important and very powerful use case.

**Comment by faho** [comment]
>Is there an extension of the c-implemented argparse possible

This seems easy enough to implement, and I have also wanted it e.g. for writing completions (where a tool can receive new options that the completion script hasn't been updated for).

However, there are some edgecases I'm not sure about. For instance, if your wrapper has a "-b" option and the original command knows "-a" which takes an argument, could there be an invocation like

```fish
original -a -b
```

With "-b" not as an option but as the argument to "-a"?

For instance, with a directory `./--man-path`, `git --git-dir --man-path`, git actually uses that directory as the git-dir, instead of erroring out or printing the man-path. If your utility added the "--man-path", it would change that invocation to mean printing the man path.

That unfortunately _can't_ be detected, because there's no way to know which option takes an argument.

Still, it's probably better to note that in the documentation than to not do this at all (and always require all options to be mentioned). Any idea how we should word that?

**Comment by dwt** [comment]
Regarding the `command -a -b` thing, I would consider being able to wrap commands very highly and think that it would be very good first step.

One way to work around edge-cases you described could be that one can tell `argparse` to ignore other arguments in two ways:
* Just accept anything else you see (this has the edge-cases as described, would would IMO a be a great first step)
* Allow to reference (probably in addition) some specific arguments that need to be ignored (this would be the workaround for the problem you describe). Quick question: Does this happen to you regularly? (because it seems that naming a directory '-rf .' would be a quick way to shoot yourself in the foot if you try to remove it.

**Comment by ridiculousfish** [comment]
This is going to be gnarly to fix; punting this.

**Comment by krader1961** [comment]
As the person who implemented `argparse` I'll give my two cents. Adding a `--ignore-unknown-flags` flag is theoretically possible but suffers from several problems. For example, it means you can no longer do anything meaningful with `$argv` after calling `argparse` because it may still contain flags and their arguments in addition to non-flag arguments.

If I were inclined to address this issue I would add a `--reconstruct-argv` flag. You would first call `argparse` without that flag and specifying all the flags your wrapper and the underlying command recognizes. You would then either remove the `_flag_a` variable (to use the O.P. example) or omit that specification when running `argparse --reconstruct-argv`. Theoretical example using the O.P.'s example:

```
function __vf_new
    set -l options (fish_opt --short a --required)
    set -l options $options (fish_opt --short x)
    set -l options $options (fish_opt --short x --long exclude --required)
    argparse --name 'vf new' $options -- $argv
    # Remove the flag recognized by this wrapper from the options.
    set -e options[1]
    argparse --reconstruct-argv $options -- $argv
    # At this point `$argv` will contain all the flags originally parsed
    # and any non-flag arguments with the two separated by `--`.
    if __vf__new_projects_original $argv
        if set -q _flag_a
            cd $_flag_a
            and pwd >/$VIRTUAL_ENV/.project
        end
    end
end
```

Obviously I don't know what flags the underlying function recognizes so the ones I introduced are just to make the example concrete.

This solution also has potential problems. For example, it assumes the underlying command recognizes the common convention that `--` stops parsing argv for flags. But that's probably acceptable.

**Comment by faho** [comment]
Huh, turns out this was reported again as #5367, and I just closed that.

The solution I went with was simply to keep all unknown options in $argv, with the arguments, in the correct order (which necessitated turning off getopt's reordering!).
