### ISSUE TITLE
SSH autocompletion with username broke in 2.7 or 2.7.1

### ISSUE THREAD

**Issue by despairblue** [fish-shell/fish-shell#4639]
#4107 is only partially fixed. In 2.6 I could complete things like

`ssh root@<tab>`

<img width="1493" alt="screen shot 2018-01-04 at 11 10 02" src="https://user-images.githubusercontent.com/927609/34559024-99bfd15a-f140-11e7-9977-bd39e107533c.png">

In 2.7.1 this does not work anymore and I can only complete hostnames without the user:

`ssh root@<tab>`

<img width="393" alt="screen shot 2018-01-04 at 11 18 55" src="https://user-images.githubusercontent.com/927609/34559156-183ca0c6-f141-11e7-830c-d7236c34e51b.png">

`ssh <tab>`

<img width="353" alt="screen shot 2018-01-04 at 11 17 31" src="https://user-images.githubusercontent.com/927609/34559104-ea9551a4-f140-11e7-8733-40a196990ca5.png">

**uname -a**: `Darwin serenity.local 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64`
**echo $TERM**: `xterm-256color`

**Comment by faho** [comment]
I can reproduce this with 2.7.0 (and there's only one additional commit in 2.7.1, and it's related to iTerm2 on macOS, so there's no chance that changes anything), but not with master.

So I'm assuming this is fixed by the numerous changes we did to the ssh completions.

If you have a chance, it'd be nice if you could compile from master to confirm.

**Comment by despairblue** [comment]
@faho tried master, works there. Thank you for working on fish, I love it 👍
