### ISSUE TITLE
Redraw fish_prompt after command has run

### ISSUE THREAD

**Issue by LandonSchropp** [fish-shell/fish-shell#4654]
fish version: 2.7.0
Operating System: macOS 10.3.2

My fish prompt currently looks like this:

<img width="211" alt="screen shot 2018-01-10 at 9 49 41 am" src="https://user-images.githubusercontent.com/361591/34787297-9c370dea-f5eb-11e7-959c-66fb03d99342.png">

When a command exits with a non-zero status, I change the color of it to red so I can tell at a glance whether a command failed or not.

<img width="333" alt="screen shot 2018-01-10 at 9 50 32 am" src="https://user-images.githubusercontent.com/361591/34787323-b91d6bb6-f5eb-11e7-940f-61d1f5f48cfa.png">

This is nice, but what I really want is for the *last* prompt to be updated when I make a mistake rather than the *current* prompt. I'd like to do something like this:

<img width="316" alt="screen shot 2018-01-10 at 9 52 22 am" src="https://user-images.githubusercontent.com/361591/34787404-fe3c4c8a-f5eb-11e7-80f1-e7f6a1895c22.png">

Is it possible to repaint `fish_prompt` after a command has run?

Thanks!

**Comment by LandonSchropp** [comment]
To clarify, I'm looking to do this whenever `$status` is non-zero, not just when a command isn't found.

**Comment by davidawad** [comment]
Take a look at the `commandline` command. 

I don't know how *exactly* you would do what you're talking about, but here's what i have for in-place direct substitution of a fish command.  This is to give me bash substitution with `!$` and `!!`

```fish
  # enables !!
  function bind_bang
    switch (commandline -t)
    case "!"
      commandline -t $history[1]; commandline -f repaint
    case "*"
      commandline -i !
    end
  end

  # enables !$
  function bind_dollar
    switch (commandline -t)
    case "!"
      commandline -t ""
      commandline -f history-token-search-backward
    case "*"
      commandline -i '$'
    end
  end

  # enable keybindings
  function fish_user_key_bindings
    bind ! bind_bang
    bind '$' bind_dollar
    bind "&&" 'commandline -i "; and"'
    bind "||" 'commandline -i "; or"'
+
+   # vim keybindings
+   fish_vi_key_bindings
  end
```

**Comment by LandonSchropp** [comment]
Thanks for the detailed reply @davidawad!

The one piece I feel like I'm still missing is how to edit the prompt itself. The `commandline` command seems to replace the content after the prompt, but not the prompt itself. Any ideas for accomplishing that?

Also, the `&&` and `||` substitutions are awesome. I'm totally stealing those. I actually opened #4620 to ask for support for those operators, but your keybindings are a nice workaround for now.

Thanks again!

**Comment by krader1961** [comment]
I'm surprised no one else has commented, @LandonSchropp. What you're asking for is impossible in the general case. Fish has no way of knowing how the screen has been modified as the result of running a command. It therefore has no way of knowing if the previous prompt is even still visible. Think about running your favorite full-screen editor. Since the editor has modified the content of the entire screen the previous fish prompt won't be visible. That may not be true if your editor uses that alternate-screen capability of many terminals but is true in the general case. To avoid that confusion just create a file name */tmp/x* with these contents:

```
for i in $(seq 100)
do
    echo $i
done
exit 1
```

Then run it with `sh /tmp/x`. Notice that it wrote a bunch of numbered lines to your terminal, pushing the previous fish prompt off the screen, then exited with a non-zero status. How exactly is fish going to modify that previous prompt?

**Comment by faho** [comment]
>What you're asking for is impossible in the general case. Fish has no way of knowing how the screen has been modified as the result of running a command.

@krader1961 is correct here. And while it would be possible to change that for the specific case of a command not being found, that would require a bunch of rearchitecting - currently, this triggers an event, which then calls the registered event-handler, which then just prints its output. And that's a bunch of work, which adds a bunch of complexity, for little gain.

So I'm dismissing this. Sorry!

**Comment by LandonSchropp** [comment]
That's unfortunate but understandable. @krader1961, @davidawad and @faho, thanks for taking the time to help and consider this!
