### ISSUE TITLE
RFE: add support for using system-wide muParser

### ISSUE THREAD

**Issue by ignatenkobrain** [fish-shell/fish-shell#4660]
Same way as pcre2, please. It would simplify packaging for distributions.

Thanks!

**Comment by zanchey** [comment]
This isn't possible at this stage, because the muParser sources we ship have been [heavily altered](https://github.com/fish-shell/fish-shell/pull/4612) (removing the optimiser and moving from exception handling to explicit error propagation). I'm going to close this for now; at a minimum this would require upstreaming the error handling changes in some form and I don't think there's any appetite for that.
