### ISSUE TITLE
Invoke ls command always doing OSS sound test

### ISSUE THREAD

**Issue by nanangarsyad** [fish-shell/fish-shell#4664]
fish version :
fish, version 2.7.1-637-g069e4fd
OS:
Linux nsquare 4.14.13-041413-generic #201801101001 SMP Wed Jan 10 10:02:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$TERM:
xterm-256color
without third-party customizations. Maybe one thing to note, I am using ubuntu 18.04 (bionic) with manually installed ubuntu kernel (of course built by ubuntu).

I've been wondering why each time I invoking ls command, fish always showing me oss audio test.
At first i'm using ubuntu distribution package of fish. Then tried to build fish myself wondering it was caused by the ubuntu package I used initially. But in the end it gave me the same result as the previous one.

Here's the bug preview. https://asciinema.org/a/3oFOUcGTSFjAbtvJHHWmguGwB

If possible, could I debug fish by myself and how?
So, I could give more detailed information or maybe, hopefully, fix it myself.
Thank you.

Here's the log of cmake configuration, in case needed.
$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- Using bundled PCRE2 library
CMake Deprecation Warning at pcre2-10.22/CMakeLists.txt:84 (CMAKE_POLICY):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Found Readline: /usr/include
-- Found Editline: /usr/include/readline
-- The following features have been enabled:

 * gettext, translate messages with gettext
 * Documentation, user manual and documentation

-- The following OPTIONAL packages have been found:

 * Intl
 * Gettext
 * BZip2
 * ZLIB
 * Readline
 * Editline
 * Doxygen (required version >= 1.8.7)

-- The following REQUIRED packages have been found:

 * Curses
 * Threads

-- Configuring done
-- Generating done
-- Build files have been written to: /home/nanangarsyad/xsbox/fish-shell/build

**Comment by faho** [comment]
Most likely, something's defining an `ls` function.

So the output of `type ls` should help you. It should look something like

```fish
ls is a function with definition
# Defined in /usr/share/fish/functions/ls.fish @ line 6
function ls --description 'List contents of directory'
    set -l param --color=auto
    if isatty 1
        set -a param --indicator-style=classify
    end
    command ls $param $argv
end
```

If it does look like that, then either `isatty` is overridden - look at `type isatty`, or the first `ls` in your $PATH is not the normal `ls`. So try `command ls` to see if that does a soundcheck.

**Comment by nanangarsyad** [comment]
Thanks for your reply.
I'd tested all instructions you mentioned above.
It was just like what you'd predicted. Using `command ls` give me the correct output.
Here's the more detailed preview, https://asciinema.org/a/Pd9T35JNZFOh4rPlbY2MHFJLj
Could you give me some hint to solve this kind of error. I really love fish, if possible I wanted to use it as my default sh terminal.
Oh, and if possible could you give me some reference or google keyword regarding what you mentioned above in the more general context, e.g. isstty, override `ls`. I want to dive deeper in those topics.
Thank you, yet again.

**Comment by faho** [comment]
>Could you give me some hint to solve this kind of error.

Sooo... there is some command or function here that is not behaving as expected.

>Oh, and if possible could you give me some reference or google keyword regarding what you mentioned above in the more general context, e.g. isstty, override ls.

When fish is supposed to execute something, it'll try to find something by that name. It checks functions first (so you can do something like add an `ls` function that calls the `ls` command with the "--color=auto" option), then it checks its builtins, and finally external commands (i.e. executable files in $PATH).

`type` ([docs](http://fishshell.com/docs/current/commands.html#type)) is a function to help you figure out what kind of a thing something is. It'll do that same logic above, and it'll print information about it. For functions, that includes the definition - which makes it nice for debugging like this.

`isatty` ([docs](http://fishshell.com/docs/current/commands.html#isatty)) is a function to figure out whether a stream (like stdout) is connected to a terminal ("teletype" => "tty"). That's often used to print color to a terminal, but not to a pipe or similar.

-----

I'm willing to bet that your issue here is _not_ a function like I assumed at first. The reason for that is that not just `ls` shows this issue, but also `type` and `isatty`. And `type` shows it _after_ printing "XY is a function with definition", but before printing the definition.

So the problematic code needs to be between those two things, and it also needs to be in `ls` and `isatty`.

So let's check the definition of `type` (e.g. `type type`):

```fish
                        printf (_ '%s is a function with definition\n') $i
                        if isatty stdout
                            functions $i | fish_indent --ansi
                        else
                            functions $i | fish_indent
                        end
```

So it prints that string, and then checks `isatty`. And what isatty does is call `command test` (as a workaround, because our builtin `test` has a bug that we haven't been able to solve). Which someone might think is a good name for a tool to `test` OSS audio.

So, please test this:

```fish
command test -t 0
```

And if that exhibits your issue, please change your $PATH so that that utility doesn't appear first (`command -s test` will show you where it is) or rename it to e.g. `oss_test` or something.

**Comment by nanangarsyad** [comment]
Amazing !!!
Really amazing, thanks a lot. It was like what you predicted, the caused was a `test` executable file in my `/usr/local/bin`. After I renamed it into something else. The bug was really gone. It was really intriguing to play around with terminal and tty.
Ok I'll start to learn from the basic of terminal again, especially about `tty` and `sh`, after that I'll learn how fish worked by tracing the flow of the source code. I hope in the near feature I could contribute to this amazing project, and be a help to someone with a problem like myself.
Yet again, thanks a lot for the good support.

**Comment by faho** [comment]
>Yet again, thanks a lot for the good support.

Thanks for the entertaining issue!
