### ISSUE TITLE
iTerm window launches twice

### ISSUE THREAD

**Issue by Kamik423** [fish-shell/fish-shell#4666]
fish, version 2.7.1

I am using iTerm2 on MacOS.
I had a working Automator AppleScript program for opening an iTerm window at the current finder window on Mac. Worked fine for bash.

```
on run {input, parameters}
	tell application "Finder"
		if exists Finder window 1 then
			set dir_path to target of Finder window 1 as alias
		else
			set dir_path to desktop as alias
		end if
	end tell
	CD_to(quoted form of (POSIX path of (dir_path)))
end run

on CD_to(theDir)
	tell application "iTerm"
		try
			set newWindow to current window
			
			set sesh to current session
			tell newWindow
				create tab with default profile
				set sesh to current session
			end tell
		on error
			set newWindow to (create window with default profile)
			tell newWindow
				set sesh to current session
			end tell
		end try
		
		tell sesh
			write text "cd " & theDir & "&& clear"
		end tell
	end tell
end CD_to
```

When I switched to `fish` this broke, I replaced the `&&` with a `;`. This works, if there already is an iTerm window, but if there is none it opens one which still displays my greeting (so no command was run) and one which correctly changed to the directory and cleared. What is going on‽ 

(EDITED) Sometimes if I launch iTerm by clicking the icon I can (sometimes) see a second window appear and then vanish immediately. It then gives me a popup `Session #1 just terminated`. I think this is also related.

This might also be related to [this](https://github.com/oh-my-fish/oh-my-fish/issues/258) omf issue.

Not sure if I was supposed to report it here, or to iTerm, but I think this is the right place, because it worked with bash, and seems to be a fish initiation issue.

**Comment by Darkshadow2** [comment]
If you want the fish script to do the exact same as the bash script, you need to make that `write text "cd " & theDir & "; and clear"`

The second window appearing and vanishing shouldn't have anything to do with that omf issue (or fish), unless that sometimes happens when you create new tabs manually, then _maybe_ something in your config files is doing something odd.

The two windows thing happens when iTerm isn't running and you run that script. The script causes iTerm to launch (without activating), and at that point there is no window **BUT** (if you haven't changed the startup preferences) iTerm by default opens a window. So you end up with the default (iTerm opening a window) AND your script creates a new window (because when it asked for the current window, there was none). This should happen regardless of what your shell is.

You can fix it by adding `activate` under `tell application "iTerm"`. Though in this case, it will open the default window, and then your script will create a new tab, so you'll end up with one useless tab.

I thought your script was interesting, so I played around with it a bit and came up with something that will know if iTerm was running or not and, as a bonus, rather than using `clear` it sends Command-K to clear the buffer:

```applescript
on CD_to(theDir)
	tell application "System Events"
		set is_running to ((processes's name as list) contains "iTerm2")
	end tell
	tell application "iTerm"
		activate
		set newWindow to current window
		if is_running is true or newWindow is missing value then
			if newWindow is missing value then
				set newWindow to (create window with default profile)
			else
				tell newWindow
					create tab with default profile
				end tell
			end if
		end if
		tell newWindow's current session
			write text "cd " & theDir
		end tell
		-- This may ask you to allow Accessibility
		-- see https://support.apple.com/en-us/HT202802
		delay 0.5
		tell application "System Events"
			-- sends Command-K (Clear Buffer in Edit menu)
			key code 40 using command down
		end tell
	end tell
end CD_to
```

**Comment by faho** [comment]
@Kamik423: Has the question been answered to your satisfaction?

**Comment by Kamik423** [comment]
Yes, thank you, that worked brilliantly. Do I have to reply soething like

    Solved!

**Comment by faho** [comment]
There's a "Close" button that you can press 😄 . Let me do that for you!

**Comment by Kamik423** [comment]
Is the `Close` button only available to Members? I couldn't find any?

Also: I played around with the solution a little bit more and ended up with this:
```
on run {input, parameters}
	tell application "Finder"
		if exists Finder window 1 then
			set dir_path to target of Finder window 1 as alias
		else
			set dir_path to desktop as alias
		end if
	end tell
	CD_to(quoted form of (POSIX path of (dir_path)))
end run


on CD_to(theDir)
	tell application "System Events"
		set is_running to ((processes's name as list) contains "iTerm2")
	end tell
	tell application "iTerm"
		activate
		set newWindow to current window
		if is_running is true or newWindow is missing value then
			if newWindow is missing value then
				set newWindow to (create window with default profile)
			else
				tell newWindow
					create tab with default profile
				end tell
			end if
		end if
		tell newWindow's current session
			write text "cd " & theDir & "; clear; echo -en \"\\e[3J\"; fish_greeting"
		end tell
	end tell
end CD_to
```

using [this](https://stackoverflow.com/a/5367075/3646485) stack overflow answer.

Thanks for the help!

**Comment by Darkshadow2** [comment]
Was there something not working with sending Command-K to clear the buffer?

**Comment by Darkshadow2** [comment]
Oh, wait, I get it, you want `fish_greeting` to show up.

You can simplify that a bit: `write text "cd " & theDir & ";clear; echo -n \\e\\[3J; fish_greeting"`

The escape code doesn't need to be in quotes, but you do need to escape the bracket. If you were typing it in at the prompt in fish, it would look like this: `clear; echo -n \e\[3J; fish_greeting`

**Comment by Kamik423** [comment]
Also it does not have the small, but visible delay.
