### ISSUE TITLE
Invalid format of generated history yaml file.

### ISSUE THREAD

**Issue by schovi** [fish-shell/fish-shell#4675]
- fish version **2.7.1**
- Darwin Sarah.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
- xterm-256color

I found problem with generated yaml history file. 
For command `git commit -m "Test: something"` it generates:

```
- cmd: git commit -m "Test: something"
  when: 1516464765
```

Which seems OK, but when I try to parse it in Ruby (or some online validators I reach problem with colon `:`

i.e. http://www.yamllint.com/ will throw `(<unknown>): mapping values are not allowed in this context at line 1 column 27`

Valid format seems to be to wrap whole command into quotes `"` and escape quotes inside.
 
```
- cmd: "git commit -m \"Test: something\""
  when: 1516464765
```

**Comment by faho** [comment]
The history file is basically not valid yaml. Fixing this (most likely by switching to a different format) would require a backwards-incompatible break (i.e. old fish versions couldn't read the new file), and we're tracking that in #3341.

However: What you are trying to do is to count how often a certain command was executed, which wouldn't work even if it was valid yaml, because fish deduplicates history. That would require either that fish give up on deduplication (not going to happen because it's very useful otherwise), or that fish keep a tally, at which point the tool you are trying to use with it becomes superfluous.

The latter has been asked for in #2398, which I'm now going to reopen.

Since both issues - the history file format being bad and there being no way of getting how often you executed a certain command - are being tracked elsewhere, I'm closing this as a duplicate.
