### ISSUE TITLE
Running sudo on user-defined functions in fish

### ISSUE THREAD

**Issue by abhigenie92** [fish-shell/fish-shell#4710]
```
» fish --version
  echo $version
fish, version 2.7.1
2.7.1
```

```
» uname -a
Linux myhostname 4.9.78-1-lts #1 SMP Tue Jan 23 21:41:02 CET 2018 x86_64 GNU/Linux
» echo $TERM
xterm-256color

```
Issue:
```

    » cat ~/.config/fish/config.fish
    function take
    	command mkdir $argv;and cd $argv
    end
    
    function check
      sudo dmesg -c>/dev/null;
      make clean; make;
      /usr/local/bin/kedr start $argv;
      sudo insmod "$argv.ko"; sudo rmmod $argv;
      /usr/local/bin/kedr stop
      dmesg;
    end
    
    function sudo
      if functions -q $argv[1]
        set argv fish -c "$argv"
      end
      command sudo $argv
    end
```
While running I get this error:
```
    » sudo check "simple-no-macro"
    fish: Unknown command 'check simple-no-macro'
    fish:
    check simple-no-macro
    ^

```
is it  necessary to specify command before sudo?

**Comment by zanchey** [comment]
The problem here is that the function you've defined isn't present in the new instance of fish you start.

You'd be better off defining the `check` function in a file saved in `~/.config/fish/functions/check.fish`, which will then let the function work across instances.

Side note: bash does let you export functions across instances using environment variables, but both zsh and ksh use a similar method to fish - see [Propagating shell functions from _Unix Power Tools_](https://docstore.mik.ua/orelly/unix3/upt/ch29_13.htm).

**Comment by abhigenie92** [comment]
@zanchey is there a difference between `sudo dmesg -c>/dev/null;` and `command sudo dmesg -c>/dev/null;`

**Comment by zanchey** [comment]
Yes - `command` means "always run as external command", that is, `command sudo` will always run the disk file found with `type --path sudo`, whereas plain `sudo` will try a function called sudo, a builtin called sudo and finally a disk file called sudo.

**Comment by faho** [comment]
I'm assuming this has been answered. If not, feel free to reopen!

**Comment by klaplong** [comment]
> The problem here is that the function you've defined isn't present in the new instance of fish you start.
> 
> You'd be better off defining the `check` function in a file saved in `~/.config/fish/functions/check.fish`, which will then let the function work across instances.
> 
> Side note: bash does let you export functions across instances using environment variables, but both zsh and ksh use a similar method to fish - see [Propagating shell functions from _Unix Power Tools_](https://docstore.mik.ua/orelly/unix3/upt/ch29_13.htm).

I tried this solution, i.e. put a file `vim.fish` in the functions dir which starts neovim if it exists. Still I get "command not found", which means after sudo, fish doesn't look for functions.

**Comment by faho** [comment]
>after sudo, fish doesn't look for functions.

@klaplong: `sudo` doesn't look for functions. Fish just passes a string to sudo, and _that_ interprets it however it wants. And it just looks for commands, because it is not a shell.

This'll be an issue regardless of what shell you use.

There's a few possible workarounds, including running `sudo fish -c $thecommand` instead of `sudo $thecommand` directly, but the best is probably to create a full-on-script.

E.g. make a file ~/bin/somevim, add the following contents:

```fish
#!/usr/bin/env fish
if command -sq nvim
    nvim $argv
else if command -sq vim
    vim $argv
end
```

make it executable and add the directory to $PATH.

Or, if that's actually all you want to do, just create a symlink to nvim or vim in $PATH. E.g. run

```fish
for vim in nvim vim vi
    if set -l cmd (command -s $vim)
        echo Using vim $vim
        ln -s $cmd ~/bin/vim
        break
   end
end
```

once.
