### ISSUE TITLE
avoid creating new fish_history file

### ISSUE THREAD

**Issue by EMayej** [fish-shell/fish-shell#4711]
I want to:
link fish_history file to a file in Dropbox, so my command line history is the same on all my computers.

Right now:
fish shell keeps creating new history files.  I have to copy fish_history file to dropbox on one machine and restore it on another.

Is it possible to keep just one fish_history file without creating new one?
Or is there a workaround?

**Comment by faho** [comment]
So, you want to do `ln -s ~/Dropbox/fish/fish_history ~/.local/share/fish/fish_history`, to store your history file in dropbox?

>Is it possible to keep just one fish_history file without creating new one?

The reason we create a new fish_history file is because we write to a different file and then move that into place, to avoid issues with other fish sessions reading from the half-written file. That means we'd have to specifically support symlinks.

> Or is there a workaround?

Symlink the entire directory instead. Which would also add the "generated_completions", but that should be a minor thing.

**Comment by EMayej** [comment]
> Symlink the entire directory instead.

I'll take this. Thank you @faho .
