### ISSUE TITLE
Thoughts on wrapping sudo in a function for fish 3.0?

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4719]
We've seen a lot of issues where people try to use sudo to execute a builtin or function only to have it either fail or return unexpected results. I know we've discussed this before in one such issue, but how do we feel about including a very simple wrapper around sudo for fish 3.0?

```fish
function sudo
    if echo $argv[1] | string match -qr -- "^-"
        command sudo $argv
    else
        command sudo fish -c "$argv"
   end
end
```

If any "advanced" usage of sudo (`sudo -foo command ...`) is detected, the command is executed as-is, but for the most common case (`sudo command [args]`) the command is executed in a fish process with elevated rights.

Is this likely to introduce more problems than it would fix? Or would bundling this go against the fish manifesto?

**Comment by zanchey** [comment]
I am nervous! The existing behaviour is easy to explain, and consistent across shells.

Other uses of sudo include `sudo VAR=VALUE`, so that would need adding.

**Comment by faho** [comment]
I don't like this either. The issue is that, while it fixes 90% of the issue, the other 10% are made much more confusing.

It allows me to do `sudo prompt_pwd`. Okay, that's nice. But now I do `sudo --preserve-env prompt_pwd`, and suddenly it breaks?

I mean we could add some `argparse` magic there to pass sudo's options to it. Implementing that for just my sudo would be easy. But then someone else uses a different sudo implementation, or uses -h to run a command on a different host, or doesn't allow fish to run in the sudo policy....

There are just so many edge-cases here that are made in some way worse by this that I don't think it's the right thing to do.

**Comment by mqudsi** [comment]
Yeah, I did not want to go down the road of attempting to understand or parse any arguments passed to `sudo`. As @zanchey points out, I forgot about the `var=VALUE` case (do we support that yet?).

Not attached to this idea - feel free to close it with no hard feelings!

**Comment by faho** [comment]
>Not attached to this idea - feel free to close it with no hard feelings!

Doing just that!
