### ISSUE TITLE
Issue with Git autocompletion

### ISSUE THREAD

**Issue by LandonSchropp** [fish-shell/fish-shell#4720]
When I try to autocomplete git branches, fish includes `\e\[m` in the output.

[![asciicast](https://asciinema.org/a/161959.png)](https://asciinema.org/a/161959)

It's difficult to show in the screencast above, but the first time I tried checking out the `beagle` branch, it added `\e\[m` without the autosuggestion prompting me. You can see in tab completions that some of the branches contain `\e\[m`.

I was unable to reproduce this issue without third-party customizations. In fact, the Git branch autocompletion doesn't work at all. I can't see how anything I have installed locally would affect fish. My fishfile only has these three plugins:

```
edc/bass
brgmnn/fish-docker-compose
oh-my-fish/plugin-thefuck
```

Fish version: 2.7.0
macOS version: 10.13.2

**Comment by faho** [comment]
First of all: You have set git to use color "always", most likely via a git config option. Don't do that! It'll break a bunch of stuff, and git has autopaging anyway so the most likely case of `command | less` doesn't apply here.

Anyway, #4636 has been merged which works around this, so it's fixed in 3.0.
