### ISSUE TITLE
Annoying extra control character auto pending to the cli periodically after upgrade

### ISSUE THREAD

**Issue by Alsan** [fish-shell/fish-shell#4727]
After upgrading to the latest fish, I got an extra "[34~" at the command line periodically (around 40s). It will come whatever I'm typing or the terminal session is idle. Please see the asciinema recording below (a little bit long, because I've to wait for the extra control character auto pending).

Here is my setup info:
- fish version: 2.7.1-787-g8cf476fb
- os: Linux XPS13 4.14.8-041408-generic #201712200555 SMP Wed Dec 20 10:57:38 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- tern: xterm-256color
- asciinema recording: https://asciinema.org/a/3OW1lUJfLCIskYFVcj2PsV3SG

**Comment by faho** [comment]
>fish version: 2.7.1-787-g8cf476fb

Which fish version did you upgrade from?

>tern: xterm-256color

Which terminal is this actually?

Also, have you confirmed that your keyboard is not, in fact, broken? There's no cat sitting on it or something?

One easy way to test: Open up a terminal running fish, but then focus some other window. If the sequence doesn't appear, that means fish is actually receiving the sequence, in which case there's something wrong in other parts of your machine - the keyboard or some other piece of software is malfunctioning.

>I got an extra "[34~" at the command line periodically

This most likely means you're getting `\e\[34~` - i.e. there's an "escape" character before that. This is an escape sequence used by some terminals to denote the "f20" key. Since that's not commonly part of keyboards anymore it might be used for other keys.

Obviously, a workaround is to bind the sequence to a noop - `bind \e\[34~ true`.

**Comment by Alsan** [comment]
>> fish version: 2.7.1-787-g8cf476fb

> Which fish version did you upgrade from?

I can't remembert this exactly, the last update should be almost a week ago, and I'm using the nightly repo.

>> tern: xterm-256color

> Which terminal is this actually?

I'm using xfce4-terminal, version 0.8.6.

> Also, have you confirmed that your keyboard is not, in fact, broken? There's no cat sitting on it or something?

This couldn't be the case, I don't have the issue when I switch to BASH.

> This most likely means you're getting \e\[34~ - i.e. there's an "escape" character before that. This is an escape sequence used by some terminals to denote the "f20" key. Since that's not commonly part of keyboards anymore it might be used for other keys.

> Obviously, a workaround is to bind the sequence to a noop - bind \e\[34~ true.

I was thinking this is the color code of the prompt, therefore I've try to set the LS_COLOR to an empty string yesterday after my report of the issue. So far the issue is gone during the pass few hours. I might try your suggestion once it happen again.

BTW, I don't care whatever it is a key escape sequence or a color sequence, but why this happening periodically? Should it be optimized?

**Comment by faho** [comment]
Sorry for the delay, I've kinda forgotten about this!

> I was thinking this is the color code of the prompt

It's not a color code. While those also begin with `\e\[`, they all end with `m`.

Like I said, it's the "f20" sequence. And checking the asciinema recording (the actual .cast file - which is why asciinema is great), it actually records `[34~`. Which would also be what you expect when fish gets `\e\[34~` because the escape character is bound (default is "cancel"), while the rest just self-inserts.

>BTW, I don't care whatever it is a key escape sequence or a color sequence, but why this happening periodically?

If it is a key sequence, that means fish isn't doing it. Fish is receiving that actual sequence.

>This couldn't be the case, I don't have the issue when I switch to BASH.

Bash might be ignoring it ("Oh, the user pressed a key, but it's not bound to anything").

------

So, to confirm: Could you open up `fish_key_reader` and let that run until you receive the sequence? (Or after a while press ctrl-c to abort). Alternatively, you should be able to open up bash and press ctrl-v, which will trigger the "literal insert" mode.

**Comment by Alsan** [comment]
After switch back to bash as my shell, uninstall fish, clean up all folders in the uninstallation section of the faq, reinstall fish, switch to fish again, don't have the issue now. I still don't know why this happening, but anyway, this thread my close now.
