### ISSUE TITLE
M-d sometimes deletes more than one word

### ISSUE THREAD

**Issue by mithrandi** [fish-shell/fish-shell#4747]
Originally reported at https://bugs.debian.org/885397 and reproducible with fish 2.7.1.

When I delete a word with M-d (Alt + D), Fish ignores single-letter
words under the cursor. For example, if I've typed
```
	~> ls dir1 dir2 dir3
	      ^
```
and have my cursor at the marked ^, M-d deletes the word `dir1`:
```
	~> ls  dir2 dir3
	      ^
```
However, if the arguments are single letters—e.g.,
```
	~> ls a b c
	      ^
```
M-d deletes both `a` and `b`:
```
	~> ls  c
	      ^
```
This behavior does not appear terminal-linked; I can reproduce both in
xterm and in rxvt-unicode. It also does not occur if I have my cursor
on the space before the letter: M-d on
```
	~> ls a b c
	     ^
```
yields
```
	~> ls b c
	     ^
```
as expected.

**Comment by faho** [comment]
I can reproduce this. I'd imagine our state machine is off-by-one somewhere.

**Comment by faho** [comment]
Yup, what happens is:

The state-machine starts in "s_always_one", removes the "a", then goes to "s_whitespace". It consumes the whitespace, goes to "s_alphanumeric", and consumes alphanumeric characters until it finds something that isn't alphanumeric.

We want to change this particular case, but I'm not quite sure what behavior we want exactly.

Because one of our tests does successive "forward-word" (which moves just like `kill-word` does) through `echo foo_foo_foo/////`. With `^` denoting the cursor positions, the current behavior is:

```
echo^ foo^_foo^_foo^/^/^/^/^/    ^
```

These jumps from `^_foo` to `foo^_` use that, which is much nicer than one "forward-word" just going over the `_` and stopping.

**Comment by faho** [comment]
Okay, this should be fixed now.

**Comment by EvanTheB** [comment]
C-w has a similar strange behaviour. 

```
ls /abc
      ^
-> ls /

ls a
   ^
-> ls

ls /
   ^
-> 
```

If the last arg is a bare slash extra characters are deleted. Maybe this matches the definition of word used, but it is not expected or I think useful.
