### ISSUE TITLE
running a command should immediately add it to history

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#4754]
Version: `2.7.1`
OS: macOS
Terminal: Terminal.app

Did not try without any customizations, pretty sure it won't make a difference.

Anyhow, my issue is that if I run `cat /dev/urandom > /dev/null` and then open a second terminal and press up, `cat /dev/urandom > /dev/null` does not show up in my history. I think it should. I get very confused sometimes as I want to run the same command in parallel with different parameters often.

**Comment by krader1961** [comment]
Works for me. After you run the command that you believe isn't in your history do `tail ~/.local/share/fish/fish_history`. Do you not see the command you just ran? I see it in the history whether I run that `tail` command in the same session or a different session. Which means a new session should see it.

**Comment by nhooyr** [comment]
I do not see it in that file after I begin running the command. I only see it when I kill the command with ctrl+c.

**Comment by krader1961** [comment]
Ah, yes! That explains it. The command is only written to the history file after it completes and a new shell prompt is displayed. That is by design. Whether that should be changed is a question for the developers actively maintaining fish. Personally, I think the answer is "no". I've been using fish for several years and have never considered this behavior a problem. It does differ from ksh, for example, which writes the command to the history file before the command completes. But ksh doesn't write anything other than the command line. Whereas the fish command history is much richer and extensible. For example, it could be extended to include how long the command ran.

**Comment by krader1961** [comment]
> ..., it would just need to edit the history entry once the command finishes.

@nhooyr, We're not talking about a database such as Mysql or Postgress. It isn't possible to "edit the history entry". It is possible to append pre and post execution data about a command to the history file. Whether that is worth the cost is debatable.

**Comment by nhooyr** [comment]
Why don't we turn it into a database? Especially since we're considering https://github.com/fish-shell/fish-shell/issues/4154

**Comment by mqudsi** [comment]
This is in many ways #907

**Comment by faho** [comment]
I cannot reproduce the original issue.

I do a command that doesn't end and it is saved and recallable in new sessions, which also matches what I saw in #10302.
