### ISSUE TITLE
Default PATH environment variable should include $HOME/.local/bin

### ISSUE THREAD

**Issue by tomfitzhenry** [fish-shell/fish-shell#4757]
# Steps to reproduce

    $ fish --version
    fish, version 2.7.1
    $ cat /etc/debian_version
    buster/sid
    $ echo $PATH
    /usr/local/bin /usr/bin /bin /usr/games

## Expected
PATH should contain ~/.local/bin by default

## Actual
PATH does not contain ~/.local/bin by default

# Why do I expect PATH to contain ~/.local/bin ?

~/.local/bin is where a user's executables are placed according to:
* [Python's PEP-370](https://www.python.org/dev/peps/pep-0370/), and thus `pip install --user`
* [systemd's file hierarchy](https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#~/.local/bin)
* [Many fish user's config.fish](https://www.google.com.au/search?q=%22~%2F.local%2Fbin%22+path+site%3Agithub.com+filetype%3Afish)
* [Debian's /etc/skel/.profile](https://sources.debian.org/src/bash/4.4.18-1.1/debian/skel.profile/#L26)
* [Fedora's /etc/skel/.profile](https://src.fedoraproject.org/rpms/bash/blob/f28/f/dot-bash_profile#_10)

It'd be great if fish did this out of the box.

**Comment by faho** [comment]
I think this is worth thinking about. It seems this has caught on enough that it is expected to be there.

On the other hand, we don't want to unconditionally prepend it, not even when it's there. Or otherwise $PATH just grows when you're launching more shells.

So if we added this, I'd expect the logic to go something like this

```fish
if test -d ~/.local/bin
    if not contains -- ~/.local/bin $PATH
        set -p PATH ~/.local/bin
    end
end
```

I have a few open questions though:

- Would that slow down network $HOME too much?

- Is there a reason to have ~/.local/bin and not want it in $PATH? Maybe temporarily?

- Or to want it at the end of $PATH?

- Am I overlooking something with nested shells? Could $PATH grow here?

This would be the first time that we'd modify $PATH without direct user choice (`$fish_user_paths` is empty by default), so it's a bit of a policy change.

**Comment by zanchey** [comment]
I'm not so sure about this - default user path is an operating system policy, not a shell policy.

**Comment by faho** [comment]
The issue is that we have two operating systems here (debian and fedora) that have decided to enact that policy in shell (not e.g. systemd or pam or something), and not for fish.

So while it'd be great if something in the login stack would just set the variable for us or if OSs followed their own policy for fish as well, it doesn't seem like they do that in practice.

**Comment by mqudsi** [comment]
I'm with @zanchey on this. Going down the `PATH` rabbit hole is just asking for trouble; and `fish_user_paths` makes it easy to change it yourself, once and for all.

Otherwise, why not include `$GOPATH/bin` and `$HOME/.cargo/bin`, too? Those languages - and utilities written with them - are also gaining ground.

**Comment by tomfitzhenry** [comment]
> fish_user_paths makes it easy to change it yourself, once and for all

I use fish so I don't have to change these things myself.

"But mostly, configuration options should be avoided since they simply should not exist, as the program should be smart enough to do what is best, or at least a good enough approximation of it." https://fishshell.com/docs/current/design.html

Arguably $PATH isn't a configuration option, but that's a letter-of-the-law rather than spirit-of-the-law interpretation.

> Otherwise, why not include $GOPATH/bin and $HOME/.cargo/bin, too?

If the sole reason to include $HOME/.local/bin was to support pip, then indeed golang and rust's equivalents would have equally valid claims. The stronger reason is that $HOME/.local/bin is included in bash's $PATH [on two of the most popular distros].

**Comment by mqudsi** [comment]
Then the fish packages for those platforms should contain this as a downstream customization.

**Comment by ridiculousfish** [comment]
I think we should not do this. If there's an OS-level mechanism for communicating the path fish can and should take advantage of it: `/etc/environment`, `path_helper`, etc. But `$PATH` is too fundamental for fish to risk being helpful here.  Thanks for filing, it's worth discussing.
