### ISSUE TITLE
Ability to customize /etc/ssh

### ISSUE THREAD

**Issue by sassanh** [fish-shell/fish-shell#4759]
When using termux there's no `/etc/ssh/` and instead fish should use `/data/data/com.termux/files/etc`. It'd be nice if user could customize `/etc/ssh/` path, currently it's hardcoded here: https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_print_hostnames.fish#L22

**Comment by sassanh** [comment]
Otherwise after pressing `tab` in front of rsync in termux we see:
```
Standard input (line 21):
            builtin cd $relative_path
            ^
in function '_recursive'
	called on standard input

in function '_ssh_include'
...
```
and a lot more.

**Comment by faho** [comment]
That error should be removed by 4ca995311460bf41e0fc06690f5770f61d5d5c02.

I'm not sure we should add a dedicated customization point for this, since it's a rather unusual configuration. What kind of customization would you expect? A variable? A function?

(Personally, I'd love it if ssh could simply print out all that stuff - it would allow us to remove a bunch of complicated logic that ssh already knows how to do - but that's probably not going to happen)

**Comment by mqudsi** [comment]
We should probably change the already crazy `/etc/ssh/{,ssh_}known_hosts{,2}` to `{,/usr/local}/etc/ssh/{,ssh_}known_hosts{,2}` 😅

**Comment by mqudsi** [comment]
@sassanh can you create a symlink on your end instead?

**Comment by sassanh** [comment]
@faho if it's too much work, then I agree it's not worth it.
@mqudsi yeah, my device is rooted (it wasn't at the time) so symlink should work for me.

**Comment by faho** [comment]
So, what I ended up doing was to just hardcode the termux path and /usr/local/etc. I didn't find a way to figure out the termux path (via e.g. a variable), but it doesn't seem likely to change.

Hope that works!

**Comment by sassanh** [comment]
@faho that was kind of you, I can imagine how hard it is to try to maintain all different environments.
For extracting `termux` path you can consider using `$PREFIX`, it points to `/data/data/com.termux/files/usr/` but I agree that it's unlikely to change.

**Comment by zanchey** [comment]
As I see it, Termux should carry this patch and others like it downstream, as there's likely to be lots of little areas that need changing in the same way.

**Comment by sassanh** [comment]
@zanchey I agree but I think the mainstream should somehow silent the error mentioned above, it's ok if fish doesn't provide auto completion suggestions for rsync and likes, but showing an error bothers users and probably makes them waste time investigating the issue.

**Comment by faho** [comment]
>but showing an error bothers users

@sassanh: As mentioned above, the error should be fixed in 3.0 already.

And

>To find out termux path you can consider using $PREFIX, it points to /data/data/com.termux/files/usr/ but I agree that it's unlikely to change.

Yeah, I saw that one. The problem is the "/usr/" part. If we just stripped that, we'd effectively rely on /etc/ being in the same position relative to it - which isn't much better than relying on the full path. And given that it's a tiny bit more complex, I just picked the path.

@zanchey: This one is small and non-invasive enough that it's not a problem to carry it here. Termux is also unlikely to get this deep into it.

**Comment by sassanh** [comment]
@faho `etc/` is a subdirectory of `usr/` but it's alrigh, "it's unlikely to change".

**Comment by faho** [comment]
>etc/ is a subdirectory of usr/

@sassanh: Wait... is the path

- `/data/data/com.termux/files/etc` (== `$PREFIX/../etc`)

or

- `/data/data/com.termux/files/usr/etc` (== `$PREFIX/etc`)

?

Because in the former (which I used), "etc/" is _not_ a subdirectory of "usr/".

Which brings me to another point against using the variable - the name is _much_ too generic. `$PREFIX` is something that anyone could call a variable, so we'd try to read some random file if we used `$PREFIX/../etc`.

**Comment by sassanh** [comment]
This is what I have in my current setup:
```
# ls -d /data/data/com.termux/files/usr/etc/ssh
/data/data/com.termux/files/usr/etc/ssh
# ls -d /data/data/com.termux/files/etc/
/data/data/com.termux/files/etc/: No such file or directory
```
So on my setup (which is the default setup for current version) it's `$PREFIX/etc/`

**Comment by faho** [comment]
For posterity: I had fixed the path to that weird .../usr/etc one in 93209ab05367ff3ca9906d9c103a97ef370af860 already.
