### ISSUE TITLE
Not suggesting checking out current branch

### ISSUE THREAD

**Issue by sassanh** [fish-shell/fish-shell#4760]
It'd be nice if fish ignores the command in history which checks out current git branch, for example when you're in branch master and you type `git checkout `, it'd be nice if fish doesn't autocomplete it (based on last history) to `git checkout master`. `git checkout master` is the last in history and that's why I'm already in master and I don't need checking it out again. I suggest something similar to what we have for `cd`. (`cd` doesn't suggest changing directory to current directory.)

**Comment by faho** [comment]
For suggestions, this isn't realistically going to happen. Those are the exact same for every command - there's no scripting or anything involved. Adding either a special case for `git` or a way to influence suggestions via script would require a bunch of work for rather little gain.

Or are you talking about _completions (the thing that happens when you press TAB)?

**Comment by sassanh** [comment]
@faho I don't know about `_completions` and based on your comment I think we can close it. Maybe someday a fish developer gets obsessed about it and manages to implement it, but users can't force repository maintainers to waste time to satisfy their obsessions.
