### ISSUE TITLE
mkdir autocomplete not working as it was supposed to be

### ISSUE THREAD

**Issue by Mati365** [fish-shell/fish-shell#4765]
I'm using Linux Fish Shell ver. 2.7.1. 

When I wanna create directory named e.g. "Directory" shell is not autocompleting my command after pressing double tab. It shows only local folders but not my directory about which I'm thinking about! Can you fix it in next release?

**Comment by faho** [comment]
>It shows only local folders but not my directory about which I'm thinking about!

So we're supposed to read your mind? That requires you install the mind-reading-processing-unit (MRPU). If you don't have one, it won't work.

**Comment by Mati365** [comment]
Thanks! Coul you update docs to provide information about that?

**Comment by faho** [comment]
Okay, let's go back to being serious for a minute:

We _cannot_ complete what you are "thinking about" because there is no way for us to get that information. We _can't_ complete names of directories (or files) that don't exist yet.

To do that, we would _actually_ have to have some way to read your thoughts.
