### ISSUE TITLE
math no longer supports logical expressions

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4777]
I'm not sure if @krader1961's math implementation with muparser featured it, but the released version of fish that uses `bc` for `math` supports logical tests like `math 1 == 1`, which the new `tinyexpr`-based builtin doesn't.

Under fish 2.7.0, the following output is generated:

```fish
~> math 1 == 1; echo $status;
1
0
~> math 1 == 0; echo $status;
0
1
```

(I stumbled across an old script of mine which used `math` instead of `test` to evaluate the return value of an external command.)

Not sure what we want to do about this or how hard it would be to add in support, but in all cases we should make a decision either way whether this functionality is explicitly dropped or not. Naturally things like `math 1 >= 0` never worked thanks to the redirection operator (though it would trivial to fix that if we end up choosing to keep logical tests in `math` functional).

**Comment by faho** [comment]
>I'm not sure if @krader1961's math implementation with muparser featured it

It did. However, it did not return a failing status for a result of 0, so it wasn't really useful as a test. "a == b" just _printed_ "1" when it was true and "0" otherwise.

The math _function_ returned a status of 1 for a result of 0:

```fish
case 0
    # For historical reasons a zero result translates to a failure status.
    echo 0
    return 1
```

No matter the function. "==" just happens to have a result of 0 if the operands aren't equal.

>how hard it would be to add in support

For "==", actually surprisingly hard. This does _char_-comparison for operators to avoid having to strip whitespace or stop at the next token, so operators that are more than one character long pose a bit of a problem (I've thought about adding `**` as an alternative for exponentiation).

>we should make a decision either way whether this functionality is explicitly dropped or not. Naturally things like math 1 >= 0 never worked thanks to the redirection operator (though it would trivial to fix that if we end up choosing to keep logical tests in math functional).

In that case, I vote for dropping it. This is duplicated functionality, and always relied on a weird quirk (returning 1 on zero).

Use an explicit test.

**Comment by ridiculousfish** [comment]
Yes, this is what `test` is for. math doesn't need to do this.
