### ISSUE TITLE
RFC: $(...) for unescaped substitution

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4781]
This is rather crazy but it struck me that if we were to allow `$(....)` to act as the syntax for unescaped command substitution, we could solve two sticky problems in one go. The first is the obvious bash compatibility that we've gone back and forth over, but the second is fish's lack of syntax for achieving unescaped command substitution without resorting to `eval` (as manifested in #982 and the horrible workaround it would require).

I know it's kind of crazy, but it actually makes sense if you let it sink in a bit. `$(...)` has always been blacklisted since it triggers the error about "fish uses (....) for command substitution" so it won't break any code that's already in the wild (and it wouldn't hit until fish 3.0 in all cases). Additionally, any `$(....)` syntax will have been copy-and-pasted from a posix shell script, meaning it would have had to already deal with escaping issues and (hopefully) either is already quoted or is guaranteed not to need quotes.

The only danger with this is that a newbie to fish will attempt to use `$(...)` not knowing about `(...)` and the awesome benefits it brings. This can be worked around by either, a) only allowing `$(....)` when fish is not running interactively (for now, at least), b) emitting a message describing the difference between `$(....)` and `(....)` in fish the first time that syntax is used, or c) do nothing, as `$(....)` won't act any different from what they expect it to, but when they find out about `(....)` their jaw will drop.

**Comment by zx8** [comment]
I am a _massive_ fan of this!

However, it's been raised as a separate issue before @ https://github.com/fish-shell/fish-shell/issues/159 and discussed in various comments @ https://github.com/fish-shell/fish-shell/issues/4154.

**Comment by faho** [comment]
>It's been raised as a separate issue before @ #159

Yup, and I went much further in that one.

I believe we should support `$(...)` in general and I'd even go so far as to phase out `(...)`.

>(...) and the awesome benefits it brings.

@mqudsi: Which benefits? My assumption was that we'd do `$(...)` but still only split on newlines, so that would be strictly _more_ powerful. If of course you're suggesting that we'd split on spaces and tabs as well (or even actually using $IFS), then `(...)` would obviously be nicer. But I don't think we want to do that (it's usually not the right thing even in bash), and so the only thing `(...)` does is save one character.

**Comment by mqudsi** [comment]
No, I mean fully unescaped substitution. So while this would continue to not work:

```fish
mqudsi@ZBook /m/c/U/Mahmoud> find (echo ". -type f" -max-depth 1)
find: ‘. -type f -max-depth 1’: No such file or directory
```

this now would:

```fish
mqudsi@ZBook /m/c/U/Mahmoud> find $(echo ". -type f" -maxdepth 1)
./.csslintrc
./.deskmetrics
./.emulator_console_auth_token
./.eslintrc
./.gitconfig
....
```

**Comment by faho** [comment]
>presumably (per my original comment) code copy-and-pasted from bash would have dealt with that already.

It won't. In my experience, having stuff (including `$(...)`) split on spaces is the single most common source of bugs in POSIX scripts.

Which is why [some people recommend setting IFS to just tab and newline](https://www.dwheeler.com/essays/filenames-in-shell.html#ifs). (The entire thing is worth reading)

**Comment by anordal** [comment]
Please correct me if I'm wrong, but I've come to conclude that [it is NEVER correct to use $() in bash](https://github.com/anordal/naziquote/blob/master/how_to_do_things_safely_in_bash.md). Because there are ways to split a string into an array that are both explicit and does not invoke globbing.

And, it won't pass [shellcheck](https://www.shellcheck.net/) either.

**Comment by faho** [comment]
>I've come to conclude that it is NEVER correct to use unquoted $() in bash.

Basically, yes. Unless you fiddle with $IFS, or can guarantee that there's no $IFS characters that you don't want to split on (e.g. spaces) in the output.

>Compatibility with $() → Let's not replicate that.

So, my idea was that we'd use unquoted `$(command)` as the same thing as `(command)` - split on newline only. `"$(command)"` would not split at all, and we'd implement some other way (potentially giving `string split` special powers) to split the string on something else.

Anyway, we can discuss that in #159, so I'm closing this one as a duplicate.
