### ISSUE TITLE
Fish should check the current vi-mode when gaining focus and send the corresponding cursor shape sequence

### ISSUE THREAD

**Issue by kmoschcau** [fish-shell/fish-shell#4788]
Hi, this isn't really a problem that I encounter when I have fish running in just a plain gnome-terminal.
But it really becomes apparent, when using tmux.

When you change the vi-mode in a fish session inside tmux, that works fine. As soon as you switch to another pane or window, which has currently something running that also modifies the cursor shape (like (n)vim or another fish session with a different vi-mode) and then switch back, the cursor shape is not returned to how it was when leaving the first pane.
This also occurs, when you `exit` a tmux pane or window, that already has another fish session running, because for the execution time of the command, the cursor shape is returned to the default.
From what I gather, this might be fixable, if you have fish check it's current vi-mode when gaining focus and then sending the corresponding cursor shape sequence again.

Here is some system info from me (I masked the machine name):
```
$ fish --version
fish, version 2.7.1
```
```
$ uname -a
Linux XXXXXXXXXXXX 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ lsb_release
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```
```
$ echo $TERM
xterm-256color-italic
$ tmux new
$ echo $TERM
tmux
```

If you want me to record an asciinema recording, I can do so. I never used it before so I didn't do it right now. Not sure cursor shapes would show up on it anyway.

**Comment by faho** [comment]
I have an implementation of this that seems to be working - in my [tmux-focus](https://github.com/faho/fish-shell/tree/tmux-focus) branch.

It works suchlike:

- When tmux is detected (via the $TMUX variable being set) fish sends `\e\[\?1004h` to enable focus reporting on startup, postexec and `\e\[\?1004l` to deactivate it on preexec

- Then tmux will send `\e\[I` when fish's pane gains focus and `\e\[O` when it loses it (**I**n/**O**ut)

- Fish binds `\e\[I` to an event (via the cheesy `bind \e\[I 'emit fish_focus_in'`) and explicitly ignores `\e\[O` (and also `\e\[\?1004h` because I managed to get that while testing)

- The fish-vi-cursor function listens to that `fish_focus_in` event in addition to the other triggers.

I believe this is nicely encapsulated and could be extended to other terminals and ways of signalling focus.

HOWEVER: I don't want to add this for 3.0 (which is scheduled for next month) unless it receives a bunch of testing from people on a wide variety of terminals, with and without tmux. I've been burned too many times by how much variety in terminals there is.

If it doesn't get that testing, I'll add it after 3.0 so it gets some more time to bake.

**Comment by kmoschcau** [comment]
Sounds good to me. It's no hurry, just a cosmetic thing anyway.
