### ISSUE TITLE
rmdir tab completion stops working when multiple directories with same first characters have a space

### ISSUE THREAD

**Issue by defaultxr** [fish-shell/fish-shell#4789]
`rmdir` tab completion seems to stop working when there is more than one directory sharing a prefix with a space in them.

To reproduce, run these commands:

```
$ mkdir foo\ bar
$ mkdir foo\ qux
$ rmdir foo<TAB>
```

You should see it add the space as expected, but then repeated tab presses do nothing. Even if you type another character of the filename--i.e. `b`--and press tab, tab completion still doesn't work:

```
$ rmdir foo\ b<TAB>
```

...does nothing.

fish --version: `fish, version 2.7.1`. I also built fish from source (`fish, version 2.7.1-895-gb50541c6`) and still saw the issue.

uname -a: `Linux hm 4.15.6-1-ARCH #1 SMP PREEMPT Sun Feb 25 12:53:23 UTC 2018 x86_64 GNU/Linux`

echo $TERM: `screen-256color` (tmux in urxvt)

I can reproduce the behavior even from fish run via `sh -c 'env HOME=$(mktemp -d) fish'`.

**Comment by faho** [comment]
Yup, can confirm.

The issue here is that `rmdir`s completions do this:

```fish
complete -x -c rmdir -a "(__fish_complete_directories (commandline -ct))"
```

That `commandline -ct` outputs the current token ("-t") up to the cursor ("-c"). That's then passed to `__fish_complete_directories`, which does glob-expansion on that.

Only... we insert the longest common-prefix, which in this case is `foo\ `. And that doesn't expand any more, because we're doing what is equivalent to `'foo\ '*` - which won't match `foo bar` because there's no `\` in there.

This is a general issue, and there's a few things we can do:

- Just stick a `string unescape` in there, and other random places

- Change `commandline` so it does the unescaping (which needs a switch because keybindings need the raw data)

- Just skip `__fish_complete_directories` and complete all files (or add directory completion to the core C++ completion code)

I could swear we already have an issue open about this but I can't find it!

**Comment by defaultxr** [comment]
I just built fish from the latest commit on master and it looks like this issue is fixed in it!

**Comment by faho** [comment]
Yup, seems to be fixed!
