### ISSUE TITLE
Deduplicate argument history suggestions

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4795]
Currently, argument history iteration is a huge chore because it is extremely naïve as currently implemented and suggests literally every argument in the history that matches the current prefix, regardless if it's already been suggested or not.

Consider the following history items:

```fish
cp file1 file2
rm file1
touch file4
touch file1
mv file1 file3
cp file<UP>
```

The suggestions on repeated `<UP>` will be `file3`, `file1`, `file4`, `file1`, and finally `file2` (which is what I want). While these arguments are taken from deduplicated history entries, the completion arguments themselves are duplicates of previous suggestions. If I bypassed `file1` the first time, there's no reason to suggest it the second time.

**Comment by zx8** [comment]
@ridiculousfish I know it's a long shot, but since you're currently poking around the completion/suggestion code (looking at recent commits on `master`), any chance you could take a stab at this? 🙏

It's super annoying to have the same argument suggested over and over after I've skipped it the first time!

**Comment by ridiculousfish** [comment]
I think this is about token history search (alt-up). Yes this should be easy to fix.

**Comment by zx8** [comment]
@ridiculousfish https://github.com/fish-shell/fish-shell/commit/e51e854d8d11c154a17d48ab781a1f05222829ff is awesome, but has ever so slightly changed/broken the traversal order of history arguments (i.e. `history-token-search-backward`):

**Prior/expected behaviour:**
```sh
$ echo foo bar baz
foo bar baz
# alt-. keybind pressed
$ baz
```

**Current/unexpected behaviour:**
```sh
$ echo foo bar baz
foo bar baz
# alt-. keybind pressed
$ echo
```

---

Would it be possible to reinstate the old traversal order? More often than not, when ever I pressed `alt-.` it's to recall the _last_ argument of the previous command. This would also consistent be with bash.
