### ISSUE TITLE
Fish doesn't colour over SSH 

### ISSUE THREAD

**Issue by kirankotari** [fish-shell/fish-shell#4834]
I am using `fish version 2.7.1` on `darwin` with `xterm-256color`. When I do SSH to the server the default colours picked not fish shell. it's annoying do I need to do some thing in the server ? can't i handle these colours with host machine fish colour settings.

**Comment by krader1961** [comment]
The problem is that your color theme is stored as universal variables. And the universal variable database is currently per-machine. On the machine that displays the colors you like type `set -U | grep fish_color_`.

See issue #1912 where this has been discussed for a long time. However, note that if and when the uvar database is no longer per-machine you will still need to copy it (or make it available via a cloud/network filesystem like Dropbox or NFS) from the machine with the theme you like to the machine you are ssh'ing to.

**Comment by kirankotari** [comment]
It means I need to installing fish shell in the ssh'ing too ?

**Comment by faho** [comment]
>It means I need to install fish shell in the ssh'ing too ?

I'm confused.

If you `ssh someserver`, then it'll open an instance of $SHELL on "someserver", where $SHELL is the shell you have configured for that user on "someserver".

If that is not fish, then there is absolutely nothing that fish can do about your colors, because it's not running at that moment.

If it is fish, then @krader1961 is correct - you need to setup your colors on that machine again.

Do you have fish installed on the remote machine or not?

**Comment by kirankotari** [comment]
No I haven't installed fish on remote machine.
