### ISSUE TITLE
How to include gmsh in Ubuntu 17.04 (Zesty Zapus)?

### ISSUE THREAD

**Issue by Huq2090** [fish-shell/fish-shell#4843]

**Comment by zanchey** [comment]
@Huq2090, can you tell us what you've tried, and what the problem is?

**Comment by Huq2090** [comment]
I got this message in terminal:
E: Unable to locate package gmsh

**Comment by Huq2090** [comment]
Same happens when I tried to install atom. It shows:
E: Unable to locate package atom

**Comment by faho** [comment]
@Huq2090: This is a bit of a frustrating exchange for us. We need to pull information from you, rather than you just giving it to us.

Please err on the side of providing too much information rather than too little.

That being said:

This message is a typical error message from `apt`, the debian (and Ubuntu etc) package manager. So there are two things you could possibly be doing:

- Either you are entering `apt install atom` or something like that

- Or you have installed atom through some other means, and are trying to run it, in which case fish starts its "command not found" helper to tell you which package you need to install to get that command.

The former case has nothing to do with fish, and means you need to configure the repository or download the .deb directly from https://atom.io/.

In the latter case, we'd have to know some things:

- Is it working in bash?

- What is the value of `$PATH` in bash and fish? Please give us the output of `echo $PATH` in both.

**Comment by Huq2090** [comment]
Hi all,
thanks for helping me out!

It seems there was some problem with Ubuntu 17.04, I then switched to previous version and it working well now. 

Huq
