### ISSUE TITLE
Interactive process sent to background affects/breaks fish shell input stream

### ISSUE THREAD

**Issue by rderik** [fish-shell/fish-shell#4856]
Hello, 

I've noticed that when I'm using the rails console and I wish to send the process to the background and do something else fish input stream breaks.

**Fish version:** 2.7.1
**OS:** 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
**term:** xterm-256color

I did run fish without third-party customizations executing: `sh -c 'env HOME=$(mktemp -d) fish'`

How can you reproduce the error? just create a rails project or if you have any just go into that project and run:
`rails c`
then press <C-z> Control + z to send it to the background
now just try to use the shell in any normal way, try `ls` a couple of times and you'll notice that it acts as if the input is sent to both the `fish shell` and the `rails console`. 

If there is something I can help with I would gladly do it.

Thanks,

**Comment by krader1961** [comment]
Pressing [ctrl-Z] only suspends the job; it doesn't send it to the background to continue running. Are you also typing `bg`? Also, you're description is not clear as to what you're observing. Are you saying that as you type a command such as `ls` some of the characters are echoed by the fish shell and other characters are read by the `rails` job? An asciinema recording might help.

Because it's unlikely anyone who can help is running Ruby and Rails let's try to eliminate that as a variable. Put the following in a file named */tmp/read*:

```
#!/bin/sh
while read line
do
    echo "line |$line|"
done
```

Now type `chmod 755 /tmp/read` followed by `/tmp/read`. Enter a few chars and press [enter]. You should see it echoed. Now suspend the job and background it by typing [ctrl-z] then `bg`. You should see

```
Send job 1 '/tmp/read' to background
Job 1, '/tmp/read' has stopped
```

That second line is because the job is trying to read from the tty but can't so it receives a SIGTTIN which stops it. If you type anything at this point it should only be read by the fish shell.

**Comment by rderik** [comment]
Sorry for the lack of clarity, the job is only suspended it is **NOT** on the background (I didn't type bg so it is just suspended).

Look at my asciinema: https://asciinema.org/a/pDMvNsyNHek77Ulyx6Z95VTuH
I'm trying to type `ls` and it jumps back and forth between the rails console and the fish shell so it seems as if some keystrokes are going to fish and some others are going to the rails console. 

I ran some other tests and try it on `bash` and it has the same behaviour so it seems as if `rails console` is not handling the syscall for suspend. I'll report this bug to them as it seems it is not fish related.
