### ISSUE TITLE
dirh, prevd, and nextd do not work as usual after `builtin cd`

### ISSUE THREAD

**Issue by mumeiyamibito** [fish-shell/fish-shell#4869]
Hi

I'm using fish-shell 2.7.1 on LinuxMint 18.3 (64 bit) (4.13.0-37-generic).

I used the following function to list files after changing directory.
```
function cd
	if count $argv > /dev/null
		builtin cd "$argv"; and ls
	else
		builtin cd ~; and ls
	end
end
```
By the function, I was able to display file list on current directory. But commands `dirh`, `prevd`, and `nextd` did not work as usual.

I checked this function by turning it on and off, and it seemed that it was caused by `builtin cd`. Below is the result of `builtin cd` to `dirh`.
Normal cd
```
$ cd /tmp
$ mkdir a b
$ dirh
 1) /home/mumeiyamibito
    /tmp

$ cd a
$ dirh
 2) /home/mumeiyamibito
 1) /tmp
    /tmp/a

$ cd ../b
$ dirh
 3) /home/mumeiyamibito
 2) /tmp
 1) /tmp/a
    /tmp/b
```

builtin cd
```
$ cd /tmp
$ dirh
 1) /home/mumeiyamibito
    /tmp

$ builtin cd a
$ dirh
 1) /home/mumeiyamibito
    /tmp/a

$ builtin cd ../b
$ dirh
 1) /home/mumeiyamibito
    /tmp/b
```

How can I resolve this problem?

Thanks.

**Comment by krader1961** [comment]
That is the expected behavior. The `cd` history is maintained by the `cd` function, not the `cd` builtin. If you replace the standard `cd` function with your own implementation then it is up to you to mimic the behavior of the standard function (which also includes handling `cd -`). Run `type cd` to see the standard implementation (assuming you haven't already redefined it).

> How can I resolve this problem?

The simplest solution is to name your cd function something else and remove the `builtin` prefix. The more complex solution is to use `functions -c cd standard_cd` then use `standard_cd` instead of `builtin cd` in your function.

**Comment by mumeiyamibito** [comment]
@krader1961 

Thank your for your quick and accurate answer!
By the complex solution, both my cd function and `dirh` can be used.

**Comment by zanchey** [comment]
If you've got it working, I'll close this issue. See also #1640.
