### ISSUE TITLE
Memory corruption when setting array slice with wrong number of arguments

### ISSUE THREAD

**Issue by kballard** [fish-shell/fish-shell#4881]
Using `set` to set an array slice with the wrong number of arguments produces random memory corruption and/or a crash.

Reproduction:

```fish
set foo one two three
set foo[1..-1] four
```

Sometimes this leaves `foo` with a corrupt value. Sometimes fish crashes (I've seen a vm_map error, an exception, and also just it terminating with no output at all).

fish, version 2.7.1-1046-g36693341

**Comment by ridiculousfish** [comment]
I think this got fixed as 6f46f6b45 in master. Please reopen or file a new bug if not .Thanks!

**Comment by faho** [comment]
>I think this got fixed as 6f46f6b in master

@ridiculousfish: @kballard's reported version already includes that.

I can confirm it is _not_ fixed, though I need to check what this is supposed to _do_.

Because, as best as I can tell, you need to provide at most one value (with more than that it complains) and indices:

- `set foo[1] x` crashes
- `set foo[1] x y` complains "You provided 1 indexes but 2 values"
- `set foo[1 2 3] x y` complains about 3 indexes but 2 values
- `set foo[1 2 3] x y z` works
- `set foo[1]` crashes
- `set foo[1] x` works

**Comment by ridiculousfish** [comment]
Looks like it can only help to me!
