### ISSUE TITLE
git add isn't reporting untracked files

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4896]
```fish
mqudsi@ZBook /m/c/U/M/D/test> git --version
git version 2.16.2.345.g7e31236f6
mqudsi@ZBook /m/c/U/M/Downloads> git init test
Initialized empty Git repository in /mnt/c/Users/Mahmoud/Downloads/test/.git/
mqudsi@ZBook /m/c/U/M/Downloads> cd test
mqudsi@ZBook /m/c/U/M/D/test> ls
mqudsi@ZBook /m/c/U/M/D/test> touch hello
mqudsi@ZBook /m/c/U/M/D/test> git add <TAB>
```

That results in an error tone with no completions.

**Comment by faho** [comment]
Fallout from 6e56637c.

The git completions use `case '\?\?'` to match a literal `??`. Only inside single-quotes, `'\?'` expands to `\?`, and the glob isn't run here at all, so now `case '??'` matches a literal `??`, and `case '\?\?'` matches `\?\?`.

@ridiculousfish: Would it be worth it to fix this in general? I mean I'd love it if the `?` wildcard stayed for `case`, but just interpreting the `\` would at least make that part backwards-compatible.

Otherwise, we'd need to change at least the git completions, hg prompt, terlar_git_prompt and possibly the svn completions.
