### ISSUE TITLE
Abbreviations aren't expanded when space is rebound

### ISSUE THREAD

**Issue by InspectorMustache** [fish-shell/fish-shell#4898]
I had the crazy idea to rebind Space so that it runs `ls` when the commandline is empty. However, this stops abbreviations from working.
```
~> abbr u uname
~> u[Space]--> uname
~> bind \x20 'commandline -i \x20'
~> u[Space]--> u
```
Is this intentional? Since `bind \r 'commandline -f execute` still works, I'm guessing for Space, abbreviations are expanded when self-insert is called on \x20. But is there any way to call it that way from the commandline?

Tried on ArchLinux with fish 2.7.1 as well as most recent development version.

**Comment by faho** [comment]
>Is this intentional?

Well... it's the consequence of a bit of a shortcut used to implement abbrs.

They're triggered:

- By the "execute" bind function (which personally I disagree with)

- The "self_insert" bind function, but only when the character is >= ' ' or == '\n' or == '\r'

And `commandline -i` doesn't trigger that because it directly sets the buffer.

We should clean this up.

I propose adding an additional bind-function "expand-abbr", and bind space to execute that and insert a space. The main issue is that any bind function clears the character, so `self-insert` would read an additional one. The bind system could do with a bit of a cleanup in general
