### ISSUE TITLE
count incorrectly returns 1 for empty array

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4905]
```fish
~> set foo
~> count foo
1
~> echo foo[1]

~> set foo bar
~> count foo
1
~> set -e foo[1]
~> count foo
1
~> echo $foo[1]

~>
```

This is a problem because you can't test if `argv` is empty, and there's no way to distinguish between `""` and ``.

**Comment by krader1961** [comment]
Ummm, @mqudsi, are you drunk? :smile:

`set foo` is not the same as `count foo`. The former requires a bare var name. The latter requires the expansion of the var. That is, `count foo` is expected to return one because there is one arg. You presumably meant `count $foo` which counts how many elements are in var `foo`.

**Comment by krader1961** [comment]
Also, `set --show var_name` is your friend in these situations. Which is why I introduced it.

**Comment by mqudsi** [comment]
🤦‍♂️ 

Unfortunately I cannot use that excuse. Thanks, @krader1961. I hate shell scripting..
