### ISSUE TITLE
fish writes to tty are uninterruptible

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4921]
fish's writes to the console should be chunked with an abort check in the middle, so that `cat huge_file` can be (relatively) immediately interrupted with ctrl+c.

Currently, ctrl+c only kicks in after all output that has been generated by the running script (or shell itself) until that point in time has been read.

**Comment by faho** [comment]
For `cat huge_file`, this actually works for me.

Are you sure you're not executing a function/builtin, and hence stumbling over #1396?

**Comment by mqudsi** [comment]
Surprisingly it isn't that. It depends on two things, a) the rate at which output is generated by the command, and b) the rate at which the terminal is capable of handling said output.

I'm not sure if it's possible to work around this fish-side, but it definitely warrants discussion. `cat` generates output very quickly, and if there is output queued to be written to the tty, tty input must wait for that queued output to be output before the input is processed (by fish?). It's apparent on slow terminals like conemu under Windows or when connecting over ssh to a remote PC.

You can probably trigger it more easily by `cat`ing something containing ascii escapes for color or similar to further bog down the terminal.

The problem with functions is a level higher, where fish will buffer output until the function has completed execution.

**Comment by zanchey** [comment]
Ctrl-C interrupts processes because when it appears in the input stream, the TTY driver sends SIGINT to the foreground process group (see Signal madness in [The TTY Demystified](http://www.linusakesson.net/programming/tty/). `read()`/`write()` to the terminal, [at least on Linux](https://manpages.debian.org/stretch/manpages/signal.7.en.html), are interruptible by signals.

For _external commands_, the behaviour you're experiencing over SSH might be explained by:
 * the data is all already in-flight (or buffered somewhere in the network stack) by the time the signal arrives
 * the packet containing the Ctrl-C character gets queued after TCP window adjustments (ACKs etc), so if your upload speed
 * your terminal or X server is so busy redrawing that it's not reading input

For fish, running `echo (seq 1 1000000)` does give you an uninterruptible output, because fish just stops the parser when it receives SIGINT, by which stage the job is already running. That could possibly be fixed, I think.

On Windows, I have no idea.

**Comment by faho** [comment]
@mqudsi: Isn't this then the same as #4939?

Let me copy my comment from there and close it:

So in your case rg --help | grep something is interruptable with one Ctrl-c, while just rg --help isn't?

I can't reproduce - for one, because rg --help completes faster than I can press Ctrl-c, but even with cat /tmp/hugefile (1000 times the output of rg --help), I can kill it with one Ctrl-c.

@mqudsi: The SIGINT is sent to the foreground process group, which as you know works quite differently on WSL than linux, so I'd assume there's some difference there.

**Comment by mqudsi** [comment]
Yup. And also note that this isn't the same as #4939 at all, that one doesn't involve early termination or command execution and has more to do with the recent change to make `^C` preserve line contents (sometimes).

The issue here is actually that the process is terminating, but its output is being buffered (very slowly) to the tty and that takes a long time past termination to complete. What's weird is that a terminal window either outputs content suuuuuuuper slow like in the video, or it does it very fast such that I can't even `^C` fast enough to keep up with it. If I am running in `tmux`, it's guaranteed to be fast (regardless of the value of `TERM`, be it `xterm-256color` or `tmux-256color`).

I can start `rg --help` in a "slow" fish instance, switch to a fast instance, execute `rg --help`, and have it complete before the first instance has finished outputting.

**Comment by faho** [comment]
>Yup. And also note that this isn't the same as #4939 at all, that one doesn't involve early termination or command execution

Terribly sorry about that! I must have just seen the youtube link and assumed it was the same one!

>I can start rg --help in a "slow" fish instance

What makes a "slow" fish instance? Is there any way to predict that?

**Comment by mqudsi** [comment]
It's not a slow fish instance, it's a slow WSL terminal instance. Reproduces under bash, and likely (though not necessarily) not a shell-related issue.

Closing (at least for now). Thanks @faho and @zanchey for trying to pin this down.
