### ISSUE TITLE
Cannot set local fish_user_paths

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4932]
Akin to locally setting `$IFS` (which we will hopefully get rid of altogether soon enough), it should be possible to locally set `fish_user_paths` and have its value (temporarily) either concatenated with the universal value or supplant it altogether. Currently, a local variable with that value is ignored altogether.

Less preferably, if we choose not to support this then `fish_user_paths` should not be settable except in the universal scope and error message should be displayed accordingly.

**Comment by mqudsi** [comment]
I'm not a python coder, but I've discovered that python's `virtualenv` requires you to use the copy of python binaries in the project's local `bin` directory for modules to be installed via `pip` or loaded from the local project instead of to the global locations. 

Obviously directly editing `PATH` works here, too.

**Comment by faho** [comment]
>I'm not a python coder, but I've discovered that python's virtualenv requires you to use the copy of python binaries in the project's local bin directory

Sure, but there's numerous better solutions there.

One is editing $PATH like you said, another is adding a relative "bin/" entry, another is a tool that reacts to $PWD changes and adds it.

As I see it, $fish_user_paths is a single-purpose thing - a simple tool to add some directories to the default $PATH, without having to muck about in config files.

As it turns out, the code to handle that is actually quite complicated, so we definitely don't want to add more stuff to it.

**Comment by zanchey** [comment]
virtualfish is very much your friend in that specific instance - there's a whole bunch of other setup that's important too.

**Comment by mqudsi** [comment]
@faho sounds fair.
@zanchey thanks for the tip, I'll check it out.
