### ISSUE TITLE
New ctrl+c behavior is inconsistent

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4939]
The changes to keep text at the prompt after `^C` are not implemented consistently, `^C` in the first argument results in `^C` being posted to the commandline momentarily, before the content flashes and disappears. `^C` in a subsequent argument causes `^C` to be posted to the command line followed by a new prompt.

**Comment by mqudsi** [comment]
[fish issue 4939.zip](https://github.com/fish-shell/fish-shell/files/1959037/fish.issue.4939.zip) or https://www.youtube.com/watch?v=MLmfKXAXrHY&feature=youtu.be (make sure to view it at 1080p60fps if on YouTube).

**Comment by faho** [comment]
So in your case `rg --help | grep something` is interruptable with one Ctrl-c, while just `rg --help` isn't?

I can't reproduce - for one, because `rg --help` completes faster than I can press Ctrl-c, but even with `cat /tmp/hugefile` (1000 times the output of `rg --help`), I can kill it with one Ctrl-c.

@mqudsi: The SIGINT is sent to the foreground process group, which as you know works quite differently on WSL than linux, so I'd assume there's some difference there.

**Comment by faho** [comment]
Duplicate of #4921.

**Comment by mqudsi** [comment]
@faho this is a completely different issue, the only similarity is that it involves ^C.

The issue here is that ^C *at the prompt*, *without executing the commandline buffer* has inconsistent behavior. Watch the video and note that depending on what's in the prompt when ^C is pressed, the output changes between either clearing the entire buffer contents or appending ^C and moving to the next line.

**Comment by mqudsi** [comment]
@faho this doesn't reproduce for you?

**Comment by faho** [comment]
>@faho this doesn't reproduce for you?

Correct, it does not. I always get the "^C" displayed.

**Comment by mqudsi** [comment]
Interesting. I was able to reproduce it under putty so I presumed it wasn't a WSL issue, but I have confirmed that I don't see this behavior under macOS, even from the WSL terminal (over ssh). So it's actually a _core_ fish issue under WSL. Odd.

**Comment by mqudsi** [comment]
No longer reproduces after updates to both WSL and fish.
