### ISSUE TITLE
backward-kill-word doesn't work

### ISSUE THREAD

**Issue by KAMiKAZOW** [fish-shell/fish-shell#4955]
Using…
* fish, version 2.7.1
* Linux 4.16.3-1-default #1 SMP PREEMPT Thu Apr 19 20:56:06 UTC 2018 (2fd48c5) x86_64 x86_64 x86_64 GNU/Linux
* xterm-256color

… the Alt+Backspace key combo no longer works. It's properly defined in fish_config -> Bindings.

**Comment by TorosFanny** [comment]
I also encounter this issue. My fish version is 2.7.1, terminal emulator is kde's konsole 18.04.0, operating system is ArchLinux. I can use alt+backspace to delete a word in bash but not in fish both in konsole. So I guess there must be something wrong with fish shell. I encounter this issue recently after I do a ArchLinux system upgrade.

**Comment by krader1961** [comment]
@TorosFanny Run fish_key_reader and press that key combination and show us that output. And show us the output of `bind | grep backward-kill-word` on your system.

**Comment by TorosFanny** [comment]
Here, I pressed 'alt+backspace'
```
> fish_key_reader
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.394 ms)  hex:    8  char: \cH  (or \b)
bind -k backspace 'do something'
bind \e\b 'do something'
```
The following is for 'bind | grep backward-kill-word'
```
> bind | grep backward-kill-word
bind \e backward-kill-word
```

**Comment by faho** [comment]
@TorosFanny: You don't have alt+backspace bound to backward-kill-word.

Check `bind \e\b` to see if it is bound to anything else, otherwise add a binding.

**Comment by TorosFanny** [comment]
```
> bind \e\b
bind: No binding found for sequence “\e\b”
```

**Comment by TorosFanny** [comment]
OK, it works. Just using `bind \e\b backward-kill-word` command can solve the issue. Maybe the issue is caused by the new version fish shell doesn't make that default binding.

**Comment by faho** [comment]
Okay, I think I've figured out what the issue is.

We bind `\e\x7f` to "backward-delete-word", and AFAICT have always done so.

`\x7f` is the "DEL" delete character, which would, in a rational world, be sent when you press the "delete" key. However, there's long-standing confusion where backspace sends this instead of the `\b` backspace character (and most terminals by now make this configurable).

Since escape is alt in terminals (another historical quirk), `\e\x7f` translates to "alt+delete" or, because of the above, "alt+backspace".

Only it turns out that at least some terminals actually use `\e\b` for alt+backspace (NOW it's backspace?), and something entirely different for alt+delete.

And our fish_config thinks that `\e\x7f` is alt+backspace and calls it such, which means it shows up in the binding list there, which makes people think it is bound.

The solution seems to be to bind `\e\b` as well.
