### ISSUE TITLE
Unable to fetch http://ppa.launchpad.net/fish-shell/release-2/ubuntu/dists/trusty/Release.gpg

### ISSUE THREAD

**Issue by leon21j** [fish-shell/fish-shell#4956]
Getting this error on `apt-get update` on Ubuntu 14.04

`W: Failed to fetch http://ppa.launchpad.net/fish-shell/release-2/ubuntu/dists/trusty/Release.gpg  Connection failed`

**Comment by leon21j** [comment]
yeah my internet is ok, this is the only one that fails.

**Comment by leon21j** [comment]
If i hit this url i get not found:

http://ppa.launchpad.net/fish-shell/release-2/ubuntu/dists/trusty/main/binary-amd64/Packages

`W: Failed to fetch http://ppa.launchpad.net/fish-shell/release-2/ubuntu/dists/trusty/main/binary-amd64/Packages  Connection failed`

**Comment by leon21j** [comment]
Failed to fetch http://ppa.launchpad.net/fish-shell/release-2/ubuntu/dists/trusty/main/i18n/Translation-en

Same with this url too

**Comment by faho** [comment]
Look at http://ppa.launchpad.net/fish-shell/release-2/ubuntu/dists/trusty/main/binary-amd64/ - there's no "Packages", just "Packages.gz" and "Packages.bz2". Similarly with the translations - they're available in compressed formats.

It's been a while since I used Ubuntu/Debian, and I've never really been comfortable with the packaging format/tools etc.

@zanchey: ?

**Comment by zanchey** [comment]
How did you add this PPA to your system?

Can you show the output of `grep fish /etc/apt/sources.list /etc/apt/sources.list.d/*`?
