### ISSUE TITLE
Strange characters in git checkout auto completion

### ISSUE THREAD

**Issue by drew-y** [fish-shell/fish-shell#4957]
## Overview

When using tab completion after `git checkout` to select a branch, strange characters are added to the branch names. For example the autocompletion for master, looks like this: `\e\[32mmaster\e\[m  `. This does NOT happen after I run `sh -c 'env HOME=$(mktemp -d) fish'`. But the weird thing is I have zero third party plugins, or configurations. My .config/fish folder is empty.
I've looked through my .gitconfig file and can't find anything that would modify this behavior either.

Any help would be appreciated. Thanks!

[Recording of issue here](https://asciinema.org/a/8I5DMLXOkc3A7IxHMJOp1hh4Y) (Start at about 9 seconds in)

## System Info

- OS Version: macOS 10.13.4
- Fish Version: 2.7.1
- Terminals used: xterm-256color (iTerm2 and Hyper)

**Comment by faho** [comment]
Those are color sequences. You have `color=always` in your git configuration, which means that git colorizes output even when it's not going to a terminal. That's something I strongly recommend against - not just for fish, but in general. It'll break _anything_ that parses git's output.

Nevertheless, this has been fixed by #4636.

**Comment by drew-y** [comment]
Thanks for the help! Much appreciated. Looks like this was a dupe of #4720, sorry about that.
