### ISSUE TITLE
feature flags require restart of shell?

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4989]
@ridiculousfish I was playing around with the new feature flags feature and tried the universal variable approach, but found that changes don't take until a new instance is started.

Since (I think?) all other universal variables kick in immediately, can we change this behavior? If not, we should at least print a message or something informing the user a restart would be needed.

**Comment by ridiculousfish** [comment]
Sorry I missed this. Feature flags affect fundamental shell functionality. The reasons they should only be set at startup is:

1. We don't want to have functions or scripts setting these flags, and then depending the set behavior. If the flags cannot be dynamically changed then this is impossible.
2. There may be flags where supporting changing them dynamically is very difficult, e.g. a flag affecting the shell threading policy.

That's why these flags can't be changed during a session.

**Comment by ridiculousfish** [comment]
Printing a message when they're changed seems fine to me.
