### ISSUE TITLE
#: command not found

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4992]
```fish
~> if foo; \ #comment
      and bar
        baz
   end

 #comment: command not found
fish:
if test foo; \ #comment
             ^
```

Not sure why this is being evaluated thusly, the `\` doesn't precede the `#`. And the error pointer is pointing to the backslash instead of the hash.

**Comment by faho** [comment]
The command that hasn't been found is ` #comment` - the space is included.

This is because `\ ` escapes the space, making it not special. And spaces are special in that they separate tokens. So you now have a space literal starting a token.

`#` only introduces comments when starting a token. So now this `#` doesn't start a token, and it's in command position, so it's read as a command name.

**Comment by mqudsi** [comment]
Thanks, @faho.
