### ISSUE TITLE
 rename

### ISSUE THREAD

**Issue by boffi** [fish-shell/fish-shell#4995]

**Comment by faho** [comment]
Rename what exactly?

**Comment by boffi** [comment]
Ooops, I didn't realize (not at all!) that I was opening an issue.

But while we are at it... as you know, there is a number of different implementations of `rename` --- in my case I have chosen, via the Debian alternatives mechanism, to use the venerable perl script that, as first argument, takes a perl expression: that said, here it is what I tried and what `fish` replied
```
boffi@debian /h/boffi> rename -e 's/\ /_/g' piantine*
fish: No matches for wildcard ''s/\ /_/g' piantine*'. See `help expand`.
rename -e 's/\ /_/g' piantine*
boffi@debian /h/boffi> help rename
^C
```
`piantine*` is a wildcard matching a space ridden filename and `s/\ /_/g/` is the perl expression that does the job, it seems to me (not the most fish-wise person! I'm just trying out `fish`) that `fish` has a preconception about the type of the 1st argument, maybe it's the syntax of a different `rename` implementation?

As a side question, is it possible that I've opened an issue when I asked for help on `rename`?)

Let me close with a thank you very much for the really prompt reply! ፨ g

**Comment by faho** [comment]
>piantine* is a wildcard matching a space ridden filename

I don't think it _is_ matching a file.

The `piantine*` argument is expanded by fish (because the `*` isn't escaped or quoted), and fish does not get a match, so it's refusing to run the command.

With bash, it would also _try_ to expand it, but by default would then pass through the wildcard literally if it does not get a match.

So in bash `piantine*` and `'piantine*'` are equivalent _if no match is found_.

It is also possible that you are expecting slightly different match logic here - for instance does the filename start with a `.`? Could you give us the actual filename you are expecting to match?

If on the other hand you need `rename` to do the matching instead, you should quote the wildcard - `'piantine*'` or `piantine'*'` or `piantine\*`. You should also do this in bash, because the default behavior there is dangerous and error-prone.

**Comment by faho** [comment]
Also:

>Let me close with a thank you very much for the really prompt reply! ፨ g

We do allow questions here, and we usually close them after they've been answered.

**Comment by boffi** [comment]
> > piantine* is a wildcard matching a space ridden filename
> 
> I don't think it is matching a file.

```
boffi@debian /h/boffi> echo pia*
piantine aprile 2018.pptx
```

>

**Comment by faho** [comment]
Umh... wait. That error message is interesting:

>`wildcard ''s/\ /_/g' piantine*'`

That's expanding _both arguments as one_. That means it either must have messed up quoting or some confusable characters in there - e.g. that space after `g'` could be a non-breaking space, or the quotes could be different characters.

Did you copy/paste this from somewhere? A browser? Documentation?

Try retyping it.

**Comment by zanchey** [comment]
@boffi, did you manage to get this working?

**Comment by faho** [comment]
Closing for lack of response.
