### ISSUE TITLE
Is possible to detect if an auto-suggestion is being displayed?

### ISSUE THREAD

**Issue by da99** [fish-shell/fish-shell#5000]
Is it possible to detect if an auto-suggestion is being displayed? For example:

    commandline --auto-suggestion

(The reason is I want to `forward-char` when no suggestion is being displayed, but use `forward-word` when an auto-suggestion is being displayed.)

**Comment by krader1961** [comment]
Try this:

bind \cf 'set -l b (commandline --current-buffer); set -l c (commandline --cut-at-cursor); if test "$b" = "$c"; commandline -f forward-word; else; commandline -f forward-char; end'

Obviously you'll want to add the same binding for the right-arrow key. With that in place [ctrl-F] and [right-arrow] accept the autosuggestion one word at a time if the cursor is after the last typed character otherwise it moves forward one char. And you can still use [ctrl-E] to jump to the end of the line and accept the entire autosuggestion.

**Comment by da99** [comment]
Once again, you save the day @krader1961. It works  _perfectly_. Should that be included in the [documentation for `commandline`](http://fishshell.com/docs/current/commands.html#commandline)? Something like:

   _-b or --current-buffer select the entire buffer,_ including any displayed autosuggestion _(default)_

Here is the code expanded:
```

function my_forward
  set -l buff   (commandline --current-buffer)
  set -l cmd    (commandline --cut-at-cursor)

  if test "$buff" = "$cmd"
    commandline --function forward-word
  else
    commandline --function forward-char
  end 
end  
```
