### ISSUE TITLE
Can't use "home" and "end" keys

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5001]
I just installed fish, version 2.7.1 on my remote server (deb 9) and I can't use the "home" and "end" keys.

Home writes "OH" in the shell and end writes "OF".

With fish 2.5 on my home computer (using the same exact gnome-terminal to connect to the remote server), I don't have this issue

**Comment by krader1961** [comment]
If you run `fish_key_reader` and press those keys it will tell you what they send and whether it maps to a named terminfo attribute like `home` and `end`.  A likely explanation is your `$TERM` variable is set incorrectly. Fish doesn't have an explicit binding for `\eOH` and `\eOF`. Instead it relies on binding the key names; e.g., `bind -k home`. So if your terminfo doesn't match your terminal those keys won't work.

**Comment by BarbzYHOOL** [comment]
```
              hex:   1B  char: \c[  (or \e)
(  0.442 ms)  hex:   4F  char: O
(  0.435 ms)  hex:   48  char: H
bind \eOH 'do something'
```


So what should I do with that? I don't know anything about key bindings

**Comment by krader1961** [comment]
On my system I see this:

```
bind -k home 'do something'
bind \eOH 'do something'
```

That first line means that the `\eOH` sequence matches the `home` key definition in the terminfo database and thus `$TERM` is set correctly. Since it doesn't on your machine fish has no idea that sequence means you pressed the home key. As far as fish is concerned it's just three random characters you typed. So the first thing to do is `echo $TERM` and verify it is correct.

**Comment by BarbzYHOOL** [comment]
echo $TERM on my computer returns `xterm`

on my server it returns `linux` (in bash or in fish)

**Comment by krader1961** [comment]
It works in bash because bash hardcodes those two escape sequences rather than relying on `$TERM` to be set correctly. In other words bash is working around the fact you haven't set `$TERM` correctly. You can solve your immediate problem by creating a file named *~/.config/fish/fish_user_key_bindings.fish* with this content:

```
function fish_user_key_bindings
    bind \eOH beginning-of-line
    bind \eOF end-of-line
end
```

But you should really figure out why `$TERM` isn't set correctly.

**Comment by BarbzYHOOL** [comment]
what should my $TERM display? `xterm` ?

Maybe my $TERM is also bugged on my home computer (why it's not display xterm-256colors o_0)

**Comment by BarbzYHOOL** [comment]
set -x TERM xterm

doesn't fix it of course
my remote server is just a bare debian 9 container

if anyone has any idea, hit me up because on google, I find everything that is NOT related to this issue

**Comment by krader1961** [comment]
When `$TERM` is incorrect it is often because you are explicitly setting it in your *~/.profile*, *~/.config/fish/config.fish* or similar file. That is almost always the wrong thing to do. Your terminal should export `TERM` with the correct value and your shell should inherit it. And when using `ssh` to connect to a remote machine ssh will propagate the var to that machine.

You say that `set -x TERM xterm` doesn't fix the issue. That implies you don't have that terminfo entry installed. If it is installed then running `infocmp` should display its definition; otherwise, it will say something like "couldn't open terminfo file". Exactly how you install terminfo definitions varies by distro.

**Comment by BarbzYHOOL** [comment]
"And when using ssh to connect to a remote machine ssh will propagate the var to that machine."

I didn't use SSH to connect to that container, that may be why. I used lxc-attach from my hypervisor

I retried to set $TERM differently (because with Fish, when I left fish, it set it back to `linux`). If I leave fish and in bash, export TERM=xterm it works in fish afterwards (Fish is not set to default yet + I want to use it with byobu which gives another $TERM value -__- and I never heard of $TERM before today)
At least I can set $TERM manually in bash, but yes, it seems dirty...

So infocmp is installed
