### ISSUE TITLE
fish_right_prompt and copy pasting my commands

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5002]
fish 2.5 and 2.7

I made my fish right prompt display the time and an icon

When I copy a command, it copies this:

```
which symlinks                                                                                                                            ⌚ 20:58:25
/usr/bin/symlinks

```

As you can see it copied a symbol, the time and a lot of spaces.

Is it possible to avoid this for easy copy pasting while keeping my right prompt cool?

**Comment by krader1961** [comment]
No, because fish has no way to tell your terminal the right prompt characters should not be considered part of the line when copying the entire line. Note that the same issue applies to the left prompt. If you triple-click (or whatever you do to select the entire line) it will include the left prompt. That's just the nature of a character terminal UI.

**Comment by krader1961** [comment]
Also, if you're explicitly starting the copy by selecting the command (rather than selecting the entire line by triple-clicking or whatever) then all you need to do is stop dragging to the right when you reach the end of the command rather than the end of the line.

**Comment by BarbzYHOOL** [comment]
It's not happening on left prompt because I made it on two lines.

Yeah I was more speaking of when I copy a long output with its associated command

I was expecting this, :'(

**Comment by zanchey** [comment]
I don't think there's anything we can do here, unfortunately.
