### ISSUE TITLE
Implement global abbreviations

### ISSUE THREAD

**Issue by admirabilis** [fish-shell/fish-shell#5003]
fish, version 2.7.1

It would be best if `abbr` would expand after sudo. So typing something like `sudo mv<SPACE>` would expand to `sudo mv -i `. Maybe a way to implement that would be hardcoding `abbr` to work specifically after the sudo command too...

Currently, I have a `function` that wraps other functions so they may work with sudo. But `abbr` is much safer in that you see what additional arguments are being given.

<s><sup>Another blocking issue for my own reference https://github.com/fish-shell/fish-shell/issues/3233</sup></s>

**Comment by ridiculousfish** [comment]
fish should not establish an abbreviation-savvy whitelist, which users and new commands can't participate in.

IMO we ought to simply implement global abbreviations. These would be abbreviations which work everywhere, not just in command position.  I think this would solve most of the pain around sudo, and also enable e.g. `!!` which we could even ship by default.

**Comment by mig-hub** [comment]
I agree with @ridiculousfish because it is quite a common thing to have commands taking commands as argument like `sudo` but also `bundle exec`, `time`, `dotenv` to name a few and it is also quite common to write functions which take a command as an argument. Keeping a white list would be limiting and also they can be nested.

**Comment by mqudsi** [comment]
@ridiculousfish that would also address the questions we get about aliases that can trigger redirects or piping, which are possible under bash (and zsh?) thanks to the substitution of aliases prior to evaluation.

**Comment by alxpettit** [comment]
I think the option to whitelist/blacklist for global abbreviations would be super useful though -- for example, let's say I whitelist `youtube-dl` to `ytdl`. That's fine. And then I'm cding into the git repo for `youtube-dl` to try the latest commit, and oh no. It just tried to cd to `ytdl` instead. That's not helpful at all.

**Comment by faho** [comment]
>so, in my opinion, each global abbreviation should have a whitelist option, and a blacklist option -- and if neither are used, then it can apply everywhere default. 

Well... that just means you need to spend a whole bunch of time tweaking (and re-tweaking) this behavior.

I'd rather just we use a different binding for expanding global abbrs. E.g. ctrl-space.

**Comment by teresaejunior** [comment]
I'm more inclined to the whitelisting approach too, because if I forget to press Ctrl+Space after an abbr, it would defeat the purpose of setting aliases like `rm -i`, and I would need to keep using functions instead (which have the disadvantage of not showing explicitly what has been modified).

**Comment by manfredlotz** [comment]
Is there a chance it will be implemented? IMHO, it should be implemented in a way that it is a new option to use with `abbr`. Then it would be backward compatible which makes many people happy.

**Comment by faho** [comment]
>Is there a chance it will be implemented?

It's still open, so yes.

**Comment by manfredlotz** [comment]
For the time being I have implemented my own stuff https://gitlab.com/Lotz/fish_globabbr (taken code from https://github.com/fish-shell/fish-shell/issues/731) which works fine for me but I'm sure it doesn't fully cover the existing abbr functionality. 

So, let's hope it will be implemented.

**Comment by ridiculousfish** [comment]
Yeah I definitely think we should do something here. I want to expand abbreviations so that they can run arbitrary code like completions can, and also improve the pager.

**Comment by rajashekar007** [comment]
I really look forward to have this functionality.
@manfredlotz I tried with your change, it didn't work for me. Do I have to do something more than what is mentioned in README.

**Comment by manfredlotz** [comment]
Hm. I have no abbr statements in use but only globabbr. Perhaps you have also some other abbr statements which do interfere.

Just to make sure: you have a bind for ' '?

I have

$ bind | grep globab
bind ' ' '__fish_expand_globabbreviation; commandline -i " "'

**Comment by scooter-dangle** [comment]
+1 for opt-in (either by requiring an extra flag to `abbr` or using a different key-binding) rather than opt-out (all existing `abbr`s now expand everywhere).

That said, I don't know that this is a feature I've ever really desired. In the cases where I've been already in a command and realized I need something I've defined an abbreviation for, I do `<ctrl-U>`, type the abbreviation, and then type `<space><ctrl-a><c-y><space><ctrl-e>`. That's not super ergonomic, but I'm usually grabbing+editing more complicated commands from my history anyway rather than writing them out in a way that abbreviations would help.

Maybe it would be useful to have people use something like what @manfredlotz provided for awhile and see what effect it has on their workflow? E.g., how many global abbrevs do they end up defining? How many do they end up using frequently?

In the cases I currently use abbreviations, I would hesitate to make them global for fear of accidentally attempting to use them as arguments. It would force me to remember all my global abbreviations _at all times_, whereas with the current abbreviations, I can instead limit my thinking about them to the few contexts where they expand.

It's possible though that I'm just not being very imaginative about the benefits global abbreviations could provide to my workflow.

**Comment by sahilrajput03** [comment]
Please do this, thing!!
I vote +1 for this...

**Comment by smdotdev** [comment]
It would be great, if this gets implemented.
