### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5023]
Is it a good idea to install nightly builds from this PPA https://launchpad.net/~fish-shell/+archive/ubuntu/nightly-master

For example, I'd like to have a newer fish shell so I can use "and" (it was added in february if I recall) but is the master branch stable enough?

**Comment by faho** [comment]
We're quite likely to be quite biased here. Of course we're going to say "yes, it's great!".

Facetiousness aside, I've been running fish from git master for the last couple of years. I can't say I've never encountered _any_ issues, but as long as you know how to revert an update or switch to a different shell until it's fixed, you should be fine.

>I'd like to have a newer fish shell so I can use "and" 

`and` has been in fish since the beginning. I'm assuming you mean `&&`?

**Comment by BarbzYHOOL** [comment]
yes "&&" sorry :D 
Reverting an update from PPA, not sure how to do it though but thank you for the answer
