### ISSUE TITLE
Set job-control to full (was: job control (%last/$last_pid) does not work within scripts)

### ISSUE THREAD

**Issue by deanveloper** [fish-shell/fish-shell#5036]
fish 2.7.1

Ubuntu 18.04, GNOME terminal (xterm-256color)

third party extensions do not affect the issue

I would expect `%last` to be different for each `sleep` call

# test.fish
```fish
 ><>  ~/Desktop > cat test.fish                                        2:29:12pm

for i in (seq 1 5)
	sleep 5 &
	echo %last
end
```

# Expected
```fish
 ><>  ~/Desktop > fish test.fish                                       2:29:14pm
30528
30529
30530
30531
30532
```
# Actual
```fish
 ><>  ~/Desktop > fish test.fish                                       2:29:14pm
30528
30528
30528
30528
30528
```

Using `(jobs -lp)` as a substitute for `%last` seems to work, although I would expect `%last` to work for this.

My use case for this is that I want to display an image which has some information on it, and I want to record the information within the image, then write that information to a file, close the image, and open the next one.

```fish
for image in (ls *.png)

    eog $image &
    set PID %last    # substituting this with (jobs -lp) makes it work, although %last should work fine...
    echo "What does the image say?"
    read info
    kill $PID
    echo "$image - $info" >> my.file
end
```

**Comment by faho** [comment]
This is caused by "job-control" being enabled only for interactive jobs by default. `status` should print something to that effect.

If you do `status job-control full` at the beginning of the script, it should start working.

I have no idea what the idea behind that was.

@mqudsi: You've stared into this particular abyss for longer than I have. Any ideas why this is a thing?

**Comment by mqudsi** [comment]
Before anything else, note that this usage of `%last` has been deprecated in fish 3.0 and won't work. Using `jobs` is far more explicit and addresses a lot of the issues with job and process expansion.

That said, I think the job control determinations date back to the original code? They're very.. messy. My guess is this is in place (as a hack?) to prevent termination of background jobs when fish is exiting when invoked as a script. It's also used (most definitely as a hack) in lieu of a proper model that determines what sort of interaction should be allowed between child programs and the tty.

**Comment by faho** [comment]
>Before anything else, note that this usage of %last has been deprecated in fish 3.0 and won't work. Using jobs is far more explicit and addresses a lot of the issues with job and process expansion.

Oh, sure, that's correct. This would be `$last_pid` instead of `%last`.

Just to make sure everyone is on the same page: It's still a problem with that, because the underlying process management is at fault, not anything more superficial like the expansion.

>It's also used (most definitely as a hack) in lieu of a proper model that determines what sort of interaction should be allowed between child programs and the tty.

It's possible. We've already changed some of that model - #3922 allowed command substitutions access to the terminal (by putting them in a pgroup that got control of the terminal).

The only place I recall that manipulates this stuff is `eval`, though that explicitly enables "full" job control mode (yet another reason not to use eval, btw).

**Comment by faho** [comment]
Alright, I've now made it default to "full job control" after startup - if we get the signal handlers to be set earlier we can set it immediately.

Let's see what happens, and eventually hopefully remove the entire job control mode awfulness.
