### ISSUE TITLE
Listing directories - speed and convert from bash to shell

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5051]
fish 2.7.1

Not really an issue, but more about questions

1 - What is faster:

`ls -d */ .[^.]*/`

or

    find . -maxdepth 1 -type d | wc -l

I can't estimate time because it's not working in fish and anyway, in Bash, the time command gives different results each time I run the same command so no idea how to evaluate

And is running the builtin ls faster than the "command ls"?

2 - How to convert this to fish shell:

`ls -d */ .[^.]*/`

**Comment by faho** [comment]
>And is running the builtin ls faster than the "command ls"?

`ls` is not a builtin. It's a function that wraps the `ls` command, so it will always strictly be slower than the command. Usually not by much, though.

>I can't estimate time because it's not working in fish

From #5050, I know that your time _command_ has a smaller resolution than bash's time builtin. But since that's still doing milliseconds, does it really matter?

In fish, to measure how long something takes interactively, you can execute it and check the value of the `$CMD_DURATION` variable (since 2.7.1, it's been renamed to `$cmd_duration`) afterwards.

For example execute `find . -maxdepth 1 -type d`, and then check `echo $CMD_DURATION`. That prints the time in milliseconds.

On my system, `find ~ -maxdepth 1 -type d` takes about 7ms.

>How to convert this to fish shell:

>`ls -d */ .[^.]*/`

So... what does that do? `ls -d` lists _directories_ instead of opening them and listing their contents.

`*/` is a glob that the shell expands to all directories in the current directory, excluding hidden directories (those whose name starts with a ".").

Up to this point it works exactly like that in fish.

`.[^.]*/` is another glob. The `.` means that the matched file has to start with a `.`, the `/` means it has to be a directory. The`[^.]` bit means "something that isn't a dot", so the second character can't be a dot. The `*` then matches any amount of characters. So since the name has to start with a "." and has to have another character that isn't a dot this effectively shows hidden directories but not "." and ".." (i.e. the entry for the current directory and for the parent directory).

That's a careful workaround for some weird sh behavior - bash also has the "GLOBIGNORE" variable that can be set to ignore "." and ".." (which I've done so long ago that I have forgotten this is even a thing).

The good news is that fish does not have this weirdness, so you can simply match hidden files with `.*`, and hidden directories with `.*/`.

So, this is the fish version:

```fish
ls -d */ .*/
```

which on my system takes 8ms. Using `command ls` takes about 5ms.

So:

`find` - 7ms
`ls` - 8ms
`command ls` - 5ms

However, if you just need to list the directories, `ls -d */ .*/` does that work twice! Once when fish expands the glob, and another time when `ls` checks that all its arguments exist. So you don't actually need the `ls` at all!

`echo */ .*/` takes about 2ms because `echo` is a shell builtin that does not do that double-checking. Other builtins (like `set -l dirs */ .*/`) take the same time. If you want to know how many directories there are, you can use `count */ .*/`.

I hope that helps!

**Comment by BarbzYHOOL** [comment]
Ok, thank you for all that information! Very useful

So I now use "count" because it's faster than "ls" (and cleaner).

And just being curious, would it be possible to list all files but not the directories? (same with `count`)

**Comment by krader1961** [comment]
Create a function. For example, I wrote a "find files" function that I use many times a day to do things like `grep some_symbol (ff)` when working on source code.

```fish
$ type ff
ff is a function with definition
# Defined in /Users/krader/.config/fish/functions/ff.fish @ line 1
function ff --description 'Like ** but only returns plain files.'
    # This also ignores .git directories.
    find . \( -name .git -type d -prune \) -o -type f | sed -n -e '/\/\.git$/n' -e 's/^\.\///p'
end
```

This could also be done using pure fish script:

```
function ff2
    for f in **
        test -f $f
        and echo $f
    end
end
```

Note that the fish script version above implicitly excludes the *.git* directory (and any other file/directory beginning with a dot). Including dot files/dirs but excluding *.git/* is an exercise for the student. It also sorts the file names which the `ff` version does not and is therefore slower.

**Comment by mqudsi** [comment]
Use [hyperfine](https://github.com/sharkdp/hyperfine/).

Patch to choose shell commands are benchmarked under: https://github.com/sharkdp/hyperfine/pull/62

**Comment by faho** [comment]
Question has been answered, I'd say.
