### ISSUE TITLE
pdf version of the documentation

### ISSUE THREAD

**Issue by sabinem** [fish-shell/fish-shell#5063]
I just feel the documentation of `fish` would urgently need a PDF version. I could not find one.

Have you ever thought about porting the documentation to Read The Docs? May be this is not a good idea, it is just that you all the things such as PDF version and search field and a bunch of formatting options for free there.

**Comment by faho** [comment]
What specifically would a PDF version do better than the existing formats?

>Have you ever thought about porting the documentation to Read The Docs?

From my research, we wouldn't so much port it to "Read The Docs" as we'd port it to markdown or rst. Which isn't something I'm opposed to - in fact I think nobody is in love with the current doxygen-based system - but which would be a whole bunch of work.

It's also important to us that all of the docs be available locally - so you don't have to have an internet connection just to be able to understand your shell. Is that possible with Read The Docs?

**Comment by sabinem** [comment]
@faho:  

> What specifically would a PDF version do better than the existing formats?

I usually like to download documentation on my ipad and read it as a pdf when I am traveling or commuting. I feel it allows for a more focused reading experience.

>  as we'd port it to markdown or rst ... but which would be a whole bunch of work

Yes that is probably true, there might be tools for this. That would have to be researched.

> It's also important to us that all of the docs be available locally - so you don't have to have an internet connection just to be able to understand your shell. Is that possible with Read The Docs?

For now as far as I know Read The Docs is not immediately available offline: it offers an html version, but people would have to download it themselves.

**Comment by mqudsi** [comment]
fwiw since Github is huge on markdown, pandoc can do markdown to pdf, html, and more.

**Comment by reed9999** [comment]
> What specifically would a PDF version do better than the existing formats?

Asked 6 years ago, I know, but here's my use case: I often use Android apps to read documentation to me when I'm able to listen but not read my screen, with mixed results. For example sometimes I use the `@Voice` app. If I have to "share" every HTML page separately to the app then it may not be worth the bother. If I can give it a PDF and let it read for several minutes, then it's suitable for talking a walk or drive. 

To be sure not all doc makes sense when read aloud, but at least a single file lets me listen seamlessly to those portions that make sense when read.

**Comment by zanchey** [comment]
This feels like it should not be that hard to do with the Sphinx toolchain, but I have not yet been successful.

**Comment by gaoqiangks** [comment]
Is there a pdf version now?

**Comment by faho** [comment]
You *can* build your own:

```fish
sphinx-build -M latexpdf doc_src/ /path/to/output
```

The result is awkward. In particular it will give you one PDF, `fish-shell.pdf`, that has the entire documentation in there, but only the landing page as top-level and then the rest as "Other help pages".

Explicit color won't be used, so when we present the prompt or highlighting it won't really work, there are no links and it's pretty noticeable that separate docs are just slapped one after the other. Some parts also make pretty little sense in this context.

It is generally usable, but I don't see us offering it anywhere as a download. Frankly I'm tempted to close this issue and just let people build their own PDFs if they want, because I don't see us putting in the work to make them actually *good* and then maintaining that state - the docs would have to be adjusted in a bunch of places and we would have to keep that up.

But, well, have a look for yourself:

[fish-shell.pdf](https://github.com/user-attachments/files/17968398/fish-shell.pdf)

(this is the docs as of 1cad9898d620149c236692ee76, i.e. well after 3.7.1)

**Comment by faho** [comment]
Okay, closing as not-planned.

If someone puts in the work here that's cool, but I don't think that's gonna happen.
