### ISSUE TITLE
Prevent fish command from executing through fish_preexec

### ISSUE THREAD

**Issue by enricozb** [fish-shell/fish-shell#5068]
fish, version 2.6.0

I was wondering if there is a way to prevent a fish command from executing. I know that `fish_preexec` exists, but I can't seem to find a way to prevent the execution of a command through this function, without quitting the shell of course. After asking on stack overflow, the best answer that appeared was to bind the enter key, like this

```
function execute_ifnotls
    if test (commandline) = 'ls'
        echo
        echo "No"
        commandline ""
        commandline -f repaint
    else
        commandline -f execute
    end
end
bind \r execute_ifnotls
bind \n execute_ifnotls
```

However, this does not work with multiple lines.

Thanks for any help.

**Comment by zanchey** [comment]
It works with multiple lines, but causes some visual glitches, at least for me on 2.7.1.

**Comment by enricozb** [comment]
@zanchey If you type in `auto \` and enter, it goes onto a new line?

**Comment by faho** [comment]
>If you type in auto \ and enter, it goes onto a new line?


@enricozb: For me it does, though I've not tested it in 2.6.0, only 2.7.1 and git master.

There is a bug related to multi-line commandlines, though. This bit:

```fish
if test (commandline) = 'ls'
```

if the commandline has multiple lines, e.g. it looks like

```fish
line1
line2
```

then commandline will print multiple lines, which the command substitution will turn into multiple arguments, so after expansion it looks like

```fish
if test line1 line2 = 'ls'
```

which will break `test` and print errors. If you wanted that `ls` test, you probably wanted to see either if the entire commandline was ls, in which case you would save it as a variable and double-quote it like

```fish
set -l cmd (commandline)
if test "$cmd" = ls
```

or you want to know if any of the lines starts with `ls`, in which case you'd use `string match` instead of `test` like

```fish
if string match -rq '^ls' -- (commandline)
```

-----

Anyway, that was @zanchey's simple example for a condition. The basic principle is sound. It's possible that fish 2.6.0 had a bug that we've fixed in 2.7.0, which means you want to upgrade.

**Comment by mqudsi** [comment]
To answer the original question: no, there isn't because `fish_preexec` is an asynchronous event and not a callback. It is not awaited and the result of the function call is not evaluated.

**Comment by enricozb** [comment]
@faho Thank you for the MWE. I'll update to 2.7.1. @mqudsi Thank you for the response to the question. As that answers my question, and since there has been an alternative solution shown, I'll close the issue.
