### ISSUE TITLE
Unalias in fish

### ISSUE THREAD

**Issue by Alkeryn** [fish-shell/fish-shell#5076]
So in bash or zsh admiting i have this : 
`alias ls="ls --color=auto"`
doing `\ls` ignore all alias and run the original comand

also i have another issue

doing and `alias somecomand "sudo thecomand"`
make autocompletion for `sudo` instead of `thecomand`

**Comment by faho** [comment]
Fish internally has no aliases. The `alias` thing you are executing is itself a function that simply defines functions (see `type alias`).

So if you want to skip an alias, use `command thething` or `builtin thething`.

>doing and alias somecomand "sudo thecomand"
make autocompletion for sudo instead of thecomand

Fixed by bb7b6491326b19ed9d79e7aaf555b93d98e3e406 and 973533e37499dee6c816ae449cac9342be7e4dac, in the next release.

**Comment by Alkeryn** [comment]
but my initial issue is being able to do
`\ls`
so it run just /bin/ls
instead of any function / alias called ls
current behavior is just running the normal function
while in bash or zsh it "unalias"

**Comment by krader1961** [comment]
> but my initial issue is being able to do `\ls`

Fish prefers to minimize the amount of magic syntax. In this case just type `command ls` to bypass the function of the same name. Which is also clearer and safer since you are being explicit. Since you don't want the normal order of resolution, function => builtin => command, it is better to say `command whatever` or `builtin whatever`.

**Comment by krader1961** [comment]
Or, you know, just type `/bin/ls`.

**Comment by faho** [comment]
> because \ls is arguably shorter than command ls ^^

Fish never had as a goal that everything be as short as possible. We're trying to make things _understandable_, not short.

> or is it a way to bind it somehow

For a pseudo-general solution to "prefix the current line with some string", do

```fish
function prefix_line
    set -l cmd (commandline)
    set -l line (commandline -L)
    set cmd[$line] "$argv $cmd[$line]"
    commandline -r $cmd
end

# Here we bind control-g to insert "command "
bind \cg 'prefix_line command'
# And control-t to insert sudo
bind \ct 'prefix_line sudo'
```

**Comment by faho** [comment]
Question seems to have been answered, so I'm closing.

**Comment by soloturn** [comment]
alias is setting a function:
```
alias ls "eza --color=always"
```
unalias is removing the function defined:
```
functions --erase ls
```
