### ISSUE TITLE
Fish crashed while editing a command for `string replace` containing HTML escape sequences

### ISSUE THREAD

**Issue by lwolfsonkin** [fish-shell/fish-shell#5080]
- Fish version 2.7.1
- Linux login 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
- screen-256color

***

I'm not sure on the specifics, but somehow I managed to crash `fish` by editing some HTML escape sequences for ampersands and quotes and such (`&amp;`, `&quot;`, `&apos;`, etc). I was piping through `sed` and decided to use `string replace` instead, and then fish just crashed once I unquoted the `sed` command.

```
echo '&amp; &apos; &gt; &lt; &quot;' | string replace <E> fish: src/path.cpp:158: failed assertion: wd[len - 1] == L'/'
<E> fish: Backtrace:                                                                                                                                        ''&amp /&/g' | sed 's/ &apos;/\'/g' | sed 's/&quot;/;/"/g'                                                   <E> fish: 0   fish() [0x4c7fcc]
<E> fish: 1   path_can_be_implicit_cd(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >*, wchar_t const*, env_vars_snapshot_t const&) + 102
<E> fish: 2   highlighter_t::highlight() + 1647
<E> fish: 3   highlight_shell(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, std::vector<unsigned int, std::allocator<unsigned int> >&, unsigned long, std::vector<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, std::allocator<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > >*, env_vars_snapshot_t const&) + 284
<E> fish: 4   fish() [0x4ced16]
<E> fish: 5   std::_Function_handler<void (), int _iothread_trampoline<highlight_result_t>::perform<std::function<highlight_result_t ()>, void (*)(highlight_result_t)>(std::function<highlight_result_t ()> const&, void (* const&)(highlight_result_t))::{lambda()#1}>::_M_invoke(std::_Any_data const&) + 29
<E> fish: 6   fish() [0x4ab9eb]
<E> fish: 7   /home/lwolfso/.linuxbrew/lib/libpthread.so.0(+0x7364) [0x7fd1bab9f364]
<E> fish: 8   clone + 109
```
<img width="1280" alt="captura de tela 2018-06-29 as 13 39 32" src="https://user-images.githubusercontent.com/16690774/42106491-366bb424-7ba2-11e8-96ff-6d0958a3ddbc.png">

**Comment by faho** [comment]
This doesn't look to me like it is caused by the html-looking stuff.

It trips over an assertion ("working directory ends in a /") while highlighting.

So your edit triggered the highlighter again, and for some reason it did not have a proper working directory.

`highlight_shell()` does:

```c++
    // Do something sucky and get the current working directory on this background thread. This
    // should really be passed in.
    const wcstring working_directory = env_get_pwd_slash();
```

which is supposed to add a PWD that ends in a slash (because that simplifies a whole bunch of logic). Unfortunately, that method looks like this:

```c++
wcstring env_get_pwd_slash() {
    auto pwd_var = env_get(L"PWD");
    if (pwd_var.missing_or_empty()) {
        return L"";
    }
    wcstring pwd = pwd_var->as_string();
    if (!string_suffixes_string(L"/", pwd)) {
        pwd.push_back(L'/');
    }
    return pwd;
}
```

See how that returns a string that does not end in a "/"? If $PWD is "missing or empty", it returns the empty string!

I'm not quite sure what to do here. We can't just return "/", because that's the root directory (or should we fall back to some default?).

We probably want to skip highlighting paths if $PWD can't be read, because that's a much better failure mode.

But really, I'd love to know why this is missing $PWD in the first place? Maybe some threading issues? There is that comment above that the working directory "should really be passed in".

**Comment by ridiculousfish** [comment]
Good analysis faho. This should be easy to fix if we can find a reproducible case.

**Comment by mqudsi** [comment]
Just a thought: pwd can be empty if the directory has been deleted since fish entered it.

**Comment by zanchey** [comment]
That doesn't affect the PWD variable, though.

**Comment by floam** [comment]
@mqudsi

I notice that ksh keeps a [pwd file descriptor around](https://github.com/att/ast/blob/master/src/cmd/ksh93/bltins/cd_pwd.c), I think, after looking over their code a bit. Seems like they also mostly use `openat()` and friends, (must not be native on every platform?), giving it a fd for a directory to be relative to and a path that can be relative to that.

Maybe we don't need to work so hard to put together full absolute paths for everything?

**Comment by ridiculousfish** [comment]
Unfortunately openat isn't available everywhere.
