### ISSUE TITLE
command -a does not work as specified

### ISSUE THREAD

**Issue by sabinem** [fish-shell/fish-shell#5107]
fish, version 2.7.1-1246-geca4273f-dirty

`command -a` or `command --all` should bring back a list of external commands recognized by `fish` according to its man page:

```
>man command
command(1)                                               fish                                              command(1)

NAME
       command

command - run a program
   Synopsis
       command [OPTIONS] COMMANDNAME [ARGS...]

   Description
       command forces the shell to execute the program COMMANDNAME and ignore any functions or builtins with the same
       name.

       The following options are available:

       o -a or --all returns all the external commands that are found in $PATH in the order they are found.
```

But this does not work:
I get not output for `command -a` and `command --all` despite I having external commands in $PATH.

**Comment by faho** [comment]
This is supposed to extend the search for a given command.

If I did `command -s test`, and I had one in my ~/.local/bin, it would just print that, and ignore the one in /usr/bin (or /bin, or /sbin or whatever). I would have to use `command -sa test` instead if I wanted all matches. (The "-s" here is optional because executing _all_ matches makes no sense whatsoever)

This is like `type`'s `-a` - try `type -a test` - and it's also in the external `which` program.

------


We could obviously make it so a bare `command -a` lists all possible commands, but I think that would barely see any use and would give weird results in case you're passing empty lists - `command -sa $empty` would list a whole bunch of output and presumably return true, `command -saq $empty` would just always (on usable systems) return true.

It's also not what `type -a` or `which -a` (remember: which is an external program) do.

So I'd call for changes to the documentation.

**Comment by sabinem** [comment]
@faho : you are right, it is probably okay and my mistake, I totally missed that `COMMANDNAME` is required for this command. But the documentation, says so:

> command [OPTIONS] COMMANDNAME [ARGS...]

So I think you could also just close this, since the documentation is correct. 

Just this option confused me: 

> -a or --all returns all the external commands that are found in $PATH in the order they are found.

And it would be clearer if the option description would also contain some mention of the COMMANDNAME. 

So yes, enhancement to the documentation is the correct label for this. Thank you!
