### ISSUE TITLE
function --on-signal INT doesn't seem to work

### ISSUE THREAD

**Issue by juanrgon** [fish-shell/fish-shell#5160]
## Problem

`--on-signal INT` doesn't seem to work

If I define a function with `--on-signal INT`, if I'm at the terminal prompt and just hit ctrl-c, then the function does get called, but if I ctrl-c out of a long running command, the function doesn't run.

## How to reproduce

```sh
> sh -c 'env HOME=$(mktemp -d) fish'
> function interrupted --on-signal INT
    echo interrupted was caught
  end
> <hit ctrl-c>
interrupted was caught
> sleep 100 <hit ctrl-c before this exits; observe that 'interrupted was caught' is not printed>
```

## My Setup
```sh
> fish --version
fish, version 2.7.1
```
```sh
>  echo $version
2.7.1
```
```sh
> uname -a
Darwin <my-computer-name> 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

```sh
> echo $TERM
xterm-256color
```
```sh
> echo $TERM_PROGRAM
iTerm.app
```

**Comment by krader1961** [comment]
That is the expected, and correct, behavior. When you press [ctrl-C] the kernel tty driver tells the kernel to send SIGINT to the foreground process group. Since `sleep` is not a builtin it only affects that process and not the fish shell which spawned it. Bash behaves the same way since `sleep` is not a bash builtin. Ksh on the other hand behaves like you expect because `sleep` is a ksh builtin.

**Comment by zanchey** [comment]
Yes, I don't think there's anything fish can do here, although it would be worth noting in the documentation.

**Comment by juanrgon** [comment]
This makes sense. I've confirmed that this is the same behavior in bash:


```sh
> exec bash
bash-3.2$ interrupted () {
> echo interrupted was caught
> }
bash-3.2$ interrupted
interrupted was caught
bash-3.2$ trap interrupted INT
bash-3.2$ interrupted was caught

bash-3.2$ sleep 100
^C
