### ISSUE TITLE
Faint feedback when running process

### ISSUE THREAD

**Issue by tos-kamiya** [fish-shell/fish-shell#5174]
I tried to paste a multi-line command text and run commands but forgot typing a return key.
As a result, I wasted a couple of hours without getting any results, because the commands were not run.

I noticed that fish provides a faint visual feedback whether the shell is waiting for a command line or running a process. That confused me.

The following is an actual screenshot, including two terminals. One is waiting for a command line and the other is running a process.  Do you know which one is running a process?

![screenshot from 2018-09-07 17-40-44](https://user-images.githubusercontent.com/1262286/45208763-5c809700-b2c6-11e8-89b9-73ff46785d34.png)

```
$ fish version
fish, version 2.7.1
$ uname -a
Linux raybu 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ echo $TERM
xterm-256color
```

Regards,

**Comment by faho** [comment]
>Do you know which one is running a process?

The first - the cursor is at the beginning of the terminal's line, not the commandline.

>I noticed that fish provides a faint visual feedback whether the shell is waiting for a command line or running a process.

The issue here is that, while a process is running, the shell does not have control over the terminal. So we have limited choices for ways to signal that a process is running.

What would you like the feedback to look like?

If you define a function with `--on-event fish_preexec`, you can try to mock something up, or just to customize it for yourself.

E.g.

```fish
function pre --on-event fish_preexec
    echo pre
end
```

will just print "pre" before running a command.

**Comment by faho** [comment]
Oooh, I just rediscovered #3382, which asks for basically this (with the bash term of "$PS2").

So let's close this one as a duplicate and continue there!

**Comment by tos-kamiya** [comment]
Thank you for informing me the issue #3282.
I will read it.
