### ISSUE TITLE
Issues setting Anaconda Python as default Python

### ISSUE THREAD

**Issue by Guilherme-Routar** [fish-shell/fish-shell#5182]
Hello, I have installed Python 3.6.5 through Anaconda 3 and I set it as my default Python configuration in bash:

```
BASH
> python -V
>> Python 3.6.5 :: Anaconda, Inc.
> echo $PATH
>> /home/routar/anaconda3/bin
```
Later, I moved to Fish but it doesn't inherit the default bash configurations

```
FISH
> python -V
>> Python 2.7.12
```

I tried setting the default path in Fish by doing

`set -x PATH /home/routar/anaconda3/bin `

but I get the following error

`set: Warning: path component /home/routar/anaconda3/bin may not be valid in PATH.
`

If I enter bash and then go back to fish in the same terminal instance the path updates correctly to bash's defauly python configuration:

```
fish_sh > python -V
Python 2.7.12
fish_sh > echo $PATH
fish_sh > /home/routar/bin
fish_sh > bash

bash_sh > python -V
Python 3.6.5 :: Anaconda, Inc.
bash_sh > echo $PATH
/home/routar/anaconda3/bin
bash_sh > fish

fish_sh > python -V
Python 3.6.5 :: Anaconda, Inc.
fish_sh > echo $PATH
/home/routar/anaconda3/bin
```

Is there something I'm doing wrong? The path clearly exists.

**Environment specifications:**
```
fish, version 2.2.0
Linux Routar 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color
No 3rd party customizations
```

**Comment by zanchey** [comment]
Newer versions of fish (2.4.0 and above) will show the exact reason that the path may not be suitable, but the checks that are done are: does it exist, is it a directory, and is it accessible (does it have the execute bit set).

What does `stat /home/routar/anaconda3/bin` show?

**Comment by Guilherme-Routar** [comment]
It exists, is a directory and I think it's accessible:
0775/drwxrwxr-x

**Comment by Guilherme-Routar** [comment]
Full stat output:
```
stat /home/routar/anaconda3/bin

  File: '/home/routar/anaconda3/bin'
  Size: 12288     	Blocks: 24         IO Block: 4096   directory
Device: 10306h/66310d	Inode: 2887966     Links: 2
Access: (0775/drwxrwxr-x)  Uid: ( 1000/  routar)   Gid: ( 1000/  routar)
Access: 2018-09-17 16:06:11.423246028 +0100
Modify: 2018-09-11 10:47:35.719872832 +0100
Change: 2018-09-11 10:47:35.719872832 +0100
 Birth: -

```

**Comment by faho** [comment]
@Guilherme-Routar: At this point, I'm afraid I'm going to have to ask you to upgrade fish. Like @zanchey said, this behavior improved in subsequent versions, of which there have been 5 since 2.2.0 (not counting point releases).

2.2.0 is, by fish standards, ancient.

Since you are on Ubuntu, use [our PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-2).

Also, this:

>`set -x PATH /home/routar/anaconda3/bin`

Sets $PATH to _only_ the anaconda directory. Which, unless I'm completely misunderstanding what anaconda is, doesn't strike me as something you'd want - this removes e.g. the distribution's /bin and /usr/bin, which usually contain important stuff (e.g. `grep` and such).

Most likely you actually want `set -x PATH /home/routar/anaconda3/bin $PATH`, i.e. to _add_ the anaconda directory.

However, that issue mirrors your bash code.

**Comment by mqudsi** [comment]
Also newer versions have access to `fish_user_paths` which makes `PATH` customization a breeze.

@Guilherme-Routar did you sort this out (i.e. can we close this issue) or do you still need help?

**Comment by faho** [comment]
I'm assuming it's been sorted. We can reopen if it's not!

**Comment by csymvoul** [comment]
I added the following command: 
 `set -x PATH /home/csymvoul/anaconda3/bin $PATH` but I need to execute it every time I open the terminal. Should I do something different?

**Comment by csymvoul** [comment]
> 

Nevermind, I had to `conda init fish`, exit the terminal and then re-open it. I am going to leave the comment in case someone else bumps into the same issue.
