### ISSUE TITLE
fish sets cmd_duration, not CMD_DURATION on FreeBSD

### ISSUE THREAD

**Issue by danielb2** [fish-shell/fish-shell#5220]
For macOS I'm getting $CMD_DURATION set as per documentation, but for FreeBSD, I see $cmd_duration set.  I tried git cloning the repo and building a new build, same problem.

`sh -c 'env HOME=$(mktemp -d) fish'`

``` bash
daniel@luffy ~> fish --version
fish, version 2.7.1-1181-g18a163dc
daniel@luffy ~> echo $version
2.7.1-1181-g18a163dc
daniel@luffy ~> uname -a
FreeBSD luffy 11.1-RELEASE-p10 FreeBSD 11.1-RELEASE-p10 #0: Tue May  8 05:21:56 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

daniel@luffy ~> sleep 1
daniel@luffy ~> echo $CMD_DURATION

daniel@luffy ~> sleep 1
daniel@luffy ~> echo $cmd_duration
1017
```

**Comment by faho** [comment]
The variable was renamed in #4414, after 2.7.1, so this is probably just a difference in version.

**Comment by danielb2** [comment]
@faho then the documentation needs updating as I referenced it first to check

**Comment by zanchey** [comment]
How did you install fish on FreeBSD?

**Comment by danielb2** [comment]
Just installed with the latest github code, run the resulting build, and type `help`. Search for CMD_DURATION

**Comment by faho** [comment]
@danielb2: Please check the URL. Most likely you're not building the documentation, in which case `help` will redirect you to the online version at http://fishshell.com/docs/current/index.html, which reflects the latest release.

**Comment by danielb2** [comment]
But the latest version would have the documentation for lowercase no? So does the online version not have lowercase? I wouldn't think freebsd would release an unstable version and only the latest

**Comment by faho** [comment]
>But the latest version would have the documentation for lowercase no?

The latest _release_ would not, because that's 2.7.

What you have installed is straight from git master, what will become 3.0.

**Comment by krader1961** [comment]
This issue is a good example for why I stopped contributing changes to the fish project. Renaming `CMD_DURATION` to `cmd_duration` was gratuitous. If nothing else both spellings should have been supported for several releases. Changing var names like `CMD_DURATION` to lowercase was primarily advocated by a single individual who lacked the experience to understand the consequences of such a change. Especially without retaining backward compatible names for a few releases. And their reasoning for such a change in letter case was bogus.

**Comment by danielb2** [comment]
@krader1961 well said
