### ISSUE TITLE
Missing directories in /etc/fish

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5235]
Still in 2.7 (not for long)

 /etc/fish/functions
 /etc/fish/completions
etc...

should be created in /etc/fish on installation, as suggested here https://fishshell.com/docs/current/

**Comment by mqudsi** [comment]
@zanchey presumably you're just going to `sed -r /\b\/etc\/fish/\/usr\/local\/etc\/fish/g`?

**Comment by faho** [comment]
@mqudsi: As I understand it, we should _always_ read from /etc/, because that is where the system configuration lives.

I think the only real question here is whether we want to create those directories. Fish doesn't _need_ them, so we could also just leave it up to people to create. I'm not aware of any packaging conventions here.

**Comment by BarbzYHOOL** [comment]
Creating them allows people to understand immediately when they "ls /etc/fish", otherwise i was forced to google and then ctrl+f in the page quoted in the first message

**Comment by BarbzYHOOL** [comment]
(off topic, is youtube-dl.fish downloadable ? :P)
