### ISSUE TITLE
How to set $PATH persistently?

### ISSUE THREAD

**Issue by dag** [fish-shell/fish-shell#527]
# To prepend to $PATH persistently, since fish 3.2.0:

     fish_add_path /path/to/add

Top comment hijacked by @faho and @ridiculousfish to help people landing here from search engines. Original comment follows:

---

I try `set -U PATH ~/.cabal/bin $PATH` which sets it in the shell I type it in, but not any new shells I launch and it's gone if I restart the first shell as well.

Using git HEAD on Fedora 18.

**Comment by simonbcn** [comment]
The problem still exists. Where does the PATH when I enter in fish shell?
fish_user_paths is a good alternative to add paths to PATH, but in my case, I need remove some paths from my PATH but I can't. How can I do this?

**Comment by Dorian** [comment]
@yannickoo :+1: `set --universal fish_user_paths $fish_user_paths ~/.rvm/bin` worked for me

**Comment by timthelion** [comment]
Hm, well, I just did `set --universal fish_user_paths $fish_user_paths ~/plan9/bin` and ended up with a broken system :P so prepending `$PATH` isn't always the right thing™.

**Comment by faho** [comment]
@timthelion: In what way broken? Did you add it interactively or via config.fish (or similar)? (I'm asking because appending unconditionally to universal variables will cause them to blow up)

Or does your plan9 stuff just shadow something? Like e.g. it has an incompatible "grep"?

**Comment by timthelion** [comment]
Yes, it shadows almost everything, but it has extra commands as well, like venti and vac...

**Comment by faho** [comment]
>Now do you undestand what I mean by broken ;)

Yes. And in this case prepending to PATH is _definitely_ the wrong thing (like you said), but I'm not sure appending is much better. Of course it'd be nice to know what breaks, maybe we can fix it - which behavior do we rely on that the plan9 tools don't implement? I assume when they call something "mkdir" it makes directories, but it doesn't necessarily have a "-p" option.

Though my copy of the plan9port intro man page explicitly recommends against prepending to $PATH.

**Comment by floam** [comment]
It does support `mkdir -p`, which is the most common result for grepping the source tree for `system(`, `rm -Rf` is the other one and that would fail as plan9 tools only likes `-r`. Both are only used in the tests though so may not matter. Of course the brokenness in the library of .fish scripts may be intense.

**Comment by timthelion** [comment]
Well, I think that those utilities are provided in the plan9port in order to allow historic rc shell(plan9's own shell) scripts to work. Obviously, fish will never be (doesn't even want to be) compatible with those old plan9 shell scripts. So there is no reason to have access to those old utilities. However, that doesn't mean that a person wouldn't ever want to use plan9 utilities that don't exist in GNU posix or BSD... So for plan9port, in my opinion, it is best to append to the path and not prepend it. However, I understand that it would be unreasonable to change the behavior of `$fish_user_paths` just for plan9port ;). So my comment was more of a mater of interest. I ended up putting the appropriate commands in `~/.config/fish/config.fish`.

**Comment by nhooyr** [comment]
How can you set `fish_user_paths` in shared dotfiles? Should I be using only `$PATH` instead?

**Comment by faho** [comment]
@nhooyr: You could use $PATH, or you could add

```fish
if not set -q fish_user_paths[1]
    set -U fish_user_paths SOMEVAL
end
```

That being said, we should probably just remove the host part from the variable store. This is at least the third time in the last week this has come up.

**Comment by nhooyr** [comment]
@faho is there any advantage to using `fish_user_paths` for me?

**Comment by faho** [comment]
@nhooyr: The nice thing about universal variables is that you can set-and-forget. Need another component in $PATH? Run `set fish_user_paths $fish_user_paths /some/path` once and you're done. It's even synced to every currently running shell on that machine.

Of course since the store is currently not something you can just keep in git and use across machines it loses a bit of its utility, and I set all of them via a config file because of that.

**Comment by nhooyr** [comment]
@faho So no advantage for me right now because I need to sync across machines. Might as well use $PATH then. Thanks!

**Comment by thekyriarchy** [comment]
I came here trying to figure out how to get Cabal for Haskell set up with fish. 

What is the difference between: 

`set --universal fish_user_paths $fish_user_paths ~/.cabal/bin`

and

`set fish_user_paths $fish_user_paths ~/.cabal/bin`

**Comment by mqudsi** [comment]
It's the difference between `set` and `set --universal`, documented here: https://fishshell.com/docs/current/commands.html#set

> `-U` or `--universal` causes the specified shell variable to be given a universal scope. If this option is supplied, the variable will be shared between all the current users fish instances on the current computer, and will be preserved across restarts of the shell.

In this case, since `fish_user_paths` is already defined as a universal variable (and is not explicitly shadowed in another scope), `set fish_user_path ...` will be as-if the same scope as the existing variable were applied to them (so `--universal`).

**Comment by faho** [comment]
@thekyriarchy: You'll want to see [the fish documentation on "Shell variables"](http://fishshell.com/docs/current/index.html#variables) - specifically the "Variable scope" section (which is repeated in the `set` documentation).

In short: The former explicitly sets the universal variable. If that doesn't exist, it creates it. If it does, it modifies it - even if a variable of the same name exists in a different scope.

The latter will either modify the existing variable in the lowest scope (which could be local, global or universal - in that order), or it could create a function-scoped variable.

It's good form to explicitly specify the scope, so I'd recommend the former.

**Comment by thekyriarchy** [comment]
I tried both with and without --universal but either way it seems to not be preserved after reboots.

**Comment by faho** [comment]
@thekyriarchy: What is your setup? OS? fish version? What are the values of $HOME and $XDG_CONFIG_HOME?

If you `echo $fish_user_paths` right after starting fish, what does that print?

**Comment by krader1961** [comment]
@thekyriarchy, What version of fish are you running? What do the following commands output:

```
echo $HOME
ls -ld $HOME/.config/fish
echo $XDG_CONFIG_HOME
ls -ld $XDG_CONFIG_HOME/.config/fish
set -U | grep fish_user_paths
set -g | grep fish_user_paths
set -l | grep fish_user_paths
set -U | grep PATH
set -g | grep PATH
set -l | grep PATH
```

**Comment by Mc128k** [comment]
Alternative solution, thanks to Google Cloud SDK:

Place the file path.bash.inc in the ~/go folder:
```
script_link="$( command readlink "$BASH_SOURCE" )" || script_link="$BASH_SOURCE"
apparent_sdk_dir="${script_link%/*}"
if [ "$apparent_sdk_dir" == "$script_link" ]; then
  apparent_sdk_dir=.
fi
sdk_dir="$( command cd -P "$apparent_sdk_dir" > /dev/null && command pwd -P )"
bin_path="$sdk_dir/bin"
export PATH=$bin_path:$PATH
```

In fish config add the line:
```
bass source '/Users/yourUser/go/path.bash.inc'
```

This is nice, works everywhere

**Comment by NikhilVerma** [comment]
Just a warning to everyone here, I was bitten by this issue so I want to share

`set fish_user_paths $fish_user_paths /some/path`

If you do this your fish config cache will grow every single time you open your terminal, in my case it became several megabytes and the fish shell took ages to open.

The files are located in `~/.config/fish/fishd.xxx` have a look at yours

**Comment by sztadii** [comment]
SET fish_user_paths:/Users/sztadhaus/Library/Android/sdk

worked for me, bitches!

**Comment by jarcane** [comment]
Something I discovered today is that `set` has an append option. So if you want to avoid a bit of redundant typing you can do for instance:

```
set -Ua fish_user_paths ~/.local/bin
```

**Comment by thernstig** [comment]
> Something I discovered today is that `set` has an append option. So if you want to avoid a bit of redundant typing you can do for instance:
> 
> ```
> set -Ua fish_user_paths ~/.local/bin
> ```

When this is done, the fish_variables file is updated with something like:
`/home/myusername/\x2elocal/bin/`

The problem I have is that I want to sync my whole `~/.config/fish/` directory between machines, since I work in multiple machines. It'd be a great way to keep an awesome shell experience wherever I go. But since tilde is expanded to /home/myusername/ I cannot get it to work. I tried these options in the file fish_variables but nothing works: `\x7e/\x2elocal/bin/`, `$HOME/\x2elocal/bin/`, `"$HOME"/\x2elocal/bin/`.

Another question is why `~/.local/bin` is not set default as a PATH in the fish shell, as it is part of systemd spec: https://www.freedesktop.org/software/systemd/man/file-hierarchy.html

**Comment by faho** [comment]
>When this is done, the fish_variables file is updated with something like:
/home/myusername/\x2elocal/bin/

Unfortunately, the value will be expanded when set, and the tilde won't be expanded later, because that's not how $PATH works (the entry would be broken for every other program, with the exception of bash). That means this won't work, so you'll have to use a global variable for it and set it in config.fish.

>Another question is why ~/.local/bin is not set default as a PATH in the fish shell

Fish does not set $PATH by default - it inherits it from your environment. Which is a good default because that means fish gets the same $PATH as other shells. If you want ~/.local/bin to be added by default, ask your distribution to add it, or edit e.g. /etc/login.defs.

**Comment by thernstig** [comment]
@faho thanks for the great answer. In regards to `~/.local/bin` I do understand it might not be something fish wants to default. At the same time, the default bash installed with e.g. Ubuntu 18.04.2 LTS (my current install) has that dir set by default in the users .profile. I understand this can be set in other ways, but I though that fish is all about "sane defaults" and that directory is actually a very common "sane default". At the same time I understand it might not be the philosophy of fish to include such a default in fish (for a reason I am unaware of).

**Comment by spider-mario** [comment]
A bit more off-topic stuff, but… my universal variable `fish_user_paths` is shadowed by a global variable with the same name containing an old value of the variable, but as one single element. I have no idea where it comes from and a recursive search for `fish_user_paths` in `~/.config/fish` does not reveal much. What could be going on?

I am using fish 3.0.2.

```
> set -Ux fish_user_paths /usr/lib/ccache/bin/ $HOME/.local/bin ...
set: Universal variable 'fish_user_paths' is shadowed by the global variable of the same name.
> set -S fish_user_paths
$fish_user_paths: not set in local scope
$fish_user_paths: set in global scope, exported, with 1 elements
$fish_user_paths[1]: length=134 value=|/usr/lib/ccache/bin/ /home/.../.local/bin ...|
$fish_user_paths: set in universal scope, exported, with 7 elements
$fish_user_paths[1]: length=20 value=|/usr/lib/ccache/bin/|
$fish_user_paths[2]: length=21 value=|/home/.../.local/bin|
$fish_user_paths[3]: ...
```

`set -eg fish_user_paths` fixes it for the current shell but if I open a new one, it still has the old PATH.

**Comment by zanchey** [comment]
@spider-mario it's ok to open a new issue, or to ask on Super User or a similar forum.

Your problem is that you have exported a universal variable; this is almost always wrong because it leaks into child fish processes as a global variable.

**Comment by boxed** [comment]
I have to google this every time and I always end up reading through this thread. I suggest adding a command like `fish-add-user-path` that is idempotent when adding the same path multiple times, but otherwise is just syntactic sugar for setting `fish_user_paths`

**Comment by jonlorusso** [comment]
@boxed i've been trying to get myself adjusted to fish for about two months now.  I must've landed on this thread at least a dozen times.

**Comment by ridiculousfish** [comment]
`fish_add_path` sounds good to me if someone wants to tackle it.

**Comment by boxed** [comment]
```fish
#!/usr/bin/env fish
if argparse -n 'fish-add-user-path' -N 1 'h/help' -- $argv
    ;
else
    exit
end

function add_to_path_if_not_there
    set exists 0

    # normalize path to end with /
    switch $argv
    case "*/"
        set new_path $argv
    case "*"
        set new_path "$argv/"
    end

    for x in (string split " " $fish_user_paths)
        if test "$x" = "$new_path"
            set exists 1
            break
        end
    end

    if test "$exists" = "0"
        set -Ux fish_user_paths $fish_user_paths $new_path
    end   
end

# validate that paths exists
for x in (string split " " $argv)
    if test -d $x
        ;
    else
        echo "Path '$x' does not exist"
        exit
    end
end


for x in (string split " " $argv)
    add_to_path_if_not_there $x 
end
```

This is the first fish script I write so I'm pretty sure it's crap! But it does do The Right Thing mostly. If you pass it several invalid paths it only complains about the first one, not all of them. And it might be a good idea if it can accept invalid paths if you pass a flag.. maybe. 

But otherwise this seems to work, even if it's ugly :P

**Comment by pdxbmw** [comment]
@spider-mario I'm not sure if this addresses your issue, but I added `set -eg fish_user_paths` to `~/.config/fish/config.fish` and the setting now persists all sessions for me.

```bash
echo "set -eg fish_user_paths" >>  ~/.config/fish/config.fish
```

**Comment by kuvaldini** [comment]
Is there a way to set PATH for all users? Like `$fish_global_path` not _user_.

**Comment by zanchey** [comment]
You can change `$PATH` in `/etc/fish/config.fish` which is applied by all users.

**Comment by ElijahLynn** [comment]
Sure, a function is nice, but here is a quick abbreviation that I like just as much. 

`abbr --add path_add "set --universal --append fish_user_paths"`

usage:
`path_add` <space> <paste OR type path> <enter>

**Comment by boxed** [comment]
@ElijahLynn that doesn't validate the path and it's not idempotent.

**Comment by boxed** [comment]
Can't we reopen this? There is a bad UX problem here. Fish normally cares about this stuff!

**Comment by ridiculousfish** [comment]
@boxed this issue has been pulled in many directions so I am going to lock it.  I agree PATH often trips people up and there are probably things that can be improved about it. If you have a suggestion for improving how PATH gets set, please open a new issue.
