### ISSUE TITLE
Logo time

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#5280]
fish 3 deserves a new logo! This will go on the website, and also some swag ;)

I had a designer mock some things up. If we settle on one of these the designer will make a vector version.

Post your thoughts! Feedback / suggested changes are welcome. @zanchey @faho @mqudsi

# 1
![fish-3](https://user-images.githubusercontent.com/920838/47597523-5614b000-d944-11e8-88e2-3de62d581ec2.gif)

# 2
![fish-2](https://user-images.githubusercontent.com/920838/47597539-66c52600-d944-11e8-900f-f6e164bd7d95.gif)

# 3
![fish-1](https://user-images.githubusercontent.com/920838/47597543-6c227080-d944-11e8-8974-7bd81893120f.gif)

**Comment by oct2pus** [comment]
I think the third one is very charming personally

**Comment by faho** [comment]
I think I might have mentioned before that I'm red-green-blind.

The colors on the fish and cursor for the third one are in the "uncomfortable" range for me. I can tell them apart here, but my eyes don't like it when they overlap.

**Comment by ridiculousfish** [comment]
@faho what's your current terminal color scheme?

**Comment by faho** [comment]
You mean in terms of fish variables?

```fish
fish_color_autosuggestion -i 555
fish_color_command 005fd7
fish_color_comment 666
fish_color_cwd 0A0
fish_color_cwd_root A00
fish_color_end 8D003B
fish_color_error A00 --bold
fish_color_escape 0AA
fish_color_history_current 0AA
fish_color_host normal
fish_color_match 0AA
fish_color_normal B2B2B2
fish_color_operator 0AA
fish_color_param 00afff
fish_color_quote A50
fish_color_redirection FFF
fish_color_search_match --background=533
fish_color_selection --background=B218B2
fish_color_status --background=red white
fish_color_user brgreen
fish_color_valid_path --underline
fish_pager_color_completion B2B2B2
fish_pager_color_description 666
fish_pager_color_prefix --underline 0AA
fish_pager_color_progress 0AA
```

The palette is the Konsole preset "Linux", afaik that's the default.

**Comment by mqudsi** [comment]
Really nice work. I don't like the second, but the first is awesome as a logo while the third would be nice on the site, perhaps as the landing page hero image.

**Comment by zanchey** [comment]
> I had a designer mock some things up

😮 

2 & 3 remind me how weird actual fish look.

**Comment by ridiculousfish** [comment]
2.0, the "ascii fish" and the "climbing fish," now vectorized. @faho how do these look for you?

![ascii-fish](https://user-images.githubusercontent.com/920838/47693595-844df600-dbb7-11e8-9cfd-bdb8dbcfa233.gif)

![climbing-fish](https://user-images.githubusercontent.com/920838/47693597-8617b980-dbb7-11e8-922a-0ab8d81cfee1.gif)

**Comment by krader1961** [comment]
I like the aesthetics of the pseudo-ascii first version but the inclusion of the numeral "3" is problematic. What happens to that logo when major release 4 occurs? The macOS iTerm app has a similar problem. Even though iTerm major version 3 has been available for quite some time it is still referred to as "iterm2" in no small part because its [url](https://www.iterm2.com/version3.html) has the "2" baked into it.

**Comment by faho** [comment]
>@faho how do these look for you?

Yup, that works!

**Comment by mqudsi** [comment]
@krader1961 raises a good point, _but_ this is a logo and not the project name (we shot down renaming fish to fish3 for this release). It can presumably be altered/changed with little confusion down the road for future releases.

**Comment by avalonx** [comment]
@krader1961 
<3 is a heart, not a 3:
I didn't see the 3 as a "3". It is a "Heart" ❤️. In most text chat (iMessage, Facebook, etc), <3 is the text symbol/representation for heart. Try typing <3 and hit enter in a text chat and you'll see what I mean. Most people (especially younger) will see the tail as a heart. 

Color the whole <3 as blue not just the 3:
The fact that only the 3 is a different color makes it stand out so I can see how it can be seen as just a 3 and cause confusion. I recommend making both characters "<3" blue not just the "3" to avoid this confusion.

**Comment by faho** [comment]
><3 is a heart, not a 3:

@avalonx: But it's meant as a logo for fish version 3. So I'd assume that's intentional.

**Comment by avalonx** [comment]
@faho 

Note: I re-edited my post to add a color change of tail and fins as an option.

I understand. I was referencing Krader's point that the 3 would be problematic if when version 4 ever rolls around at which point the logo would be dated. Assuming the logo may stand more than one version, coloring the fins fixes that issue. But if you guys are going to make a new logo for version 4, then clearly its a non issue, but maybe it looks better with the fins and tail colored? Should a mockup be made with fins and tails colored blue and see what people think?

**Comment by avalonx** [comment]
What if we made the tail "<3" blue and the eye " . " plus top and bottom fins "^" "`" into orange or red?
That way the tail still stands out as a heart.

Or make the eye, top, and bottom fins blue, but the tail as red for a red heart?

**Comment by deanveloper** [comment]
when we get to version 4 we can just make it <4, which is like <3, but even more

**Comment by robinwhittleton** [comment]
❤️ the fish’s expression in #3.

**Comment by deanveloper** [comment]
Totally agree. 3 is my favorite for sure

**Comment by jorgebucaran** [comment]
I really hope this issue is non-blocking and we can still have a 3.0 release even without a new logo if no decision is made. 

In my opinion, we should let people submit logo ideas and choose from that. I'm sure there are great designers out there that are also fish shell users that would be happy to contribute a logo to the project free of charge. It just takes time. 

If pushed to say, I'd go with the first one, but only to avoid the use of clipart as seen in options (2) and (3). I'd rather keep the current logo and collect more logo ideas in this issue.

Now, for some perspective, here is the bash logo. 

![](https://user-images.githubusercontent.com/56996/48881099-db618680-ee56-11e8-8b04-f313eceac413.jpg)

We don't need something as polished as that. A logotype of the word `fish` can go long a way.


![](https://user-images.githubusercontent.com/56996/48882221-87f23700-ee5c-11e8-8803-0dbd6ac0e2a0.jpg)

**Comment by floam** [comment]
I'm digging the sassy illustrated fish in #3. It still looks good with the grey `>_`.

**Comment by ridiculousfish** [comment]
Yes of course this is not blocking 3.0.

**Comment by markstos** [comment]
As someone who studied graphic design and designed a number of company and project logos, I see merit in the ASCII logo.

I first read <3 as a heart, and then released it's also a "3". So it could outlive Fish 3, but it's also nice to fresh up logos every few years, so it doesn't need to be a "forever" logo, either. 

The ASCII logo is simple, clever, and evocative of the terminal. I find it to be a good visual representation of the "friendly terminal" message. The simple design will work well from tiny sizes to banner size, and the simple three color design will be inexpensive to physically print. 

In Logo option #3, the Fish looks "out of water". The fish looks uncomfortable balancing on the prompt and will presumably soon run out of oxygen and die. 

To add to the conversation, I've attached both logos at 100px size instead of 500px size. You can see that the Ascii version remains clear, while the "climbing fish" has lost a good deal of detail. The logo is more likely to be displayed at sizes closer to 100px than 500px.
![climbing-fish-100px](https://user-images.githubusercontent.com/25829/59462188-2cd06380-8df1-11e9-80a9-2c418b1b1827.png)
![ascii-fish-100px](https://user-images.githubusercontent.com/25829/59462189-2cd06380-8df1-11e9-9ec8-d091584230d5.png)

**Comment by maxirater** [comment]
I think its worth hiring a professional to do the logo for fish. #1 image is overly simple, it doesnt look like ascii, it just looks like an overly simple design. #2 and #3 images are not cartoonish enough, it looks like an actual painting instead of a design or logo. Also I think using a goldfish as a logo is not generic enough, it would only work if fish shell was called Goldfish shell. Take a look at the other logos used by the Linux community, you see all these logos have style and are very recognizable, they dont look like some random painting of a fish.
![004b9](https://user-images.githubusercontent.com/5192023/64582673-12038180-d343-11e9-91e9-63c30ed04e87.jpg)

**Comment by faho** [comment]
I would still quite like to see this happen, and I would quite hate for us to adopt a "stylized F" logo, or something as boring and safe as bash's. 

We're not big and "professional", we're the fun underdog, and the logo should reflect that.

Personally, I'd be okay with the ASCII fish logo as the main logo, and the cute derpy fish as the mascot. Give it a cute name like "Shelly".

**Comment by ridiculousfish** [comment]
I've updated the website with the ASCII logo

**Comment by phatblat** [comment]
“Shelly” 🤣 love it!

**Comment by ecogex** [comment]
I use and love fish. Let me suggest a more radical ASCII look for the Shelly mascot, that is actually writable!

`<" ( ( <`

This can be used directly in the terminal, and quickly modified ([speech bubble à la cowsay](https://en.wikipedia.org/wiki/Cowsay), colors etc.)

![fish](https://user-images.githubusercontent.com/5823195/93748639-e0312600-fbf8-11ea-91f8-847b83e062aa.png)

**Comment by faho** [comment]
I don't believe there's anything more to do here, we are now using a new logo, so I'm closing this.

**Comment by smiller171** [comment]
> 

Do you have an SVG version of the ASCII logo?

**Comment by Xiretza** [comment]
There's an EPS [here](https://github.com/fish-shell/fish-site/blob/fb5c89f8ca7f1d565d04f7f9448d8bd5d87534b4/artwork/ascii%20fish%20no%20BG.eps) which can be converted to SVG quite easily with inkscape:

```
$ inkscape -o fish.svg fish.eps
```

**Comment by smiller171** [comment]
Thanks!

The SVG if anyone else ever wants it 
![ascii fish no BG](https://github.com/fish-shell/fish-shell/assets/3587913/6ad4911a-fbba-4bb6-84cb-438a79a3e09c)

**Comment by mqudsi** [comment]
Interesting. In the in-line preview, the logo appears correctly colored. However, clicking on it opens the svg itself in a new tab, where it is no longer correctly corrected and is rendered in black-and-white.

I converted the eps again myself via a different method, and this SVG does not seem to behave in that idiosyncratic manner:

![fish_new](https://github.com/fish-shell/fish-shell/assets/606923/43879439-74cc-4e08-b7ce-11fbd9106811)

**Comment by smiller171** [comment]
Yours actually does the same thing for me @mqudsi. How strange

**Comment by splitbrain** [comment]
In case anyone needs it: I cleaned up the SVG a bit. It's now only two paths and fill colors. Everything not strictly needed was removed. The result is 2144 bytes.

![Image](https://github.com/user-attachments/assets/f2a595f6-dc38-4115-b2d1-5928feef7479)
