### ISSUE TITLE
Support for bash-like &&

### ISSUE THREAD

**Issue by seanr** [fish-shell/fish-shell#5299]
fish, version 2.7.1
Darwin Seans-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

This is a followup to https://github.com/fish-shell/fish-shell/issues/150 since that was unceremoniously closed. I think this needs to be reconsidered, given that shell examples all over the web user && as well as other things that fish craps out on. I frequently have to switch to bash altogether because I can't figure out how to convert an example to what fish expects/accepts. Better parity with bash would go a long way to promoting adoption of fish.

This may be a meta discussion, but IMHO, it's one that needs serious consideration. I lose a solid chunk of time dealing with these inconsistencies in my regular work, especially given that essentially all online examples assume bash these days.

**Comment by mqudsi** [comment]
Lots of acrimony here. fish 3.0 already supports `&&` and `||` and has other bash compatibility shims.

**Comment by seanr** [comment]
Specific example:
Bash, works:
`./script && ./other_script`
Fish:
`./script; and ./other_script`
Results in this:
```
fish: Unknown command './other_script'
fish:
./script; and ./other_script
                  ^
```

**Comment by seanr** [comment]
OK, I'll try that and report back.

**Comment by seanr** [comment]
3.0 is not listed here: https://fishshell.com/release_notes.html

**Comment by mqudsi** [comment]
> Specific example:
> Bash, works:
> `./script && ./other_script`
> Fish:
> `./script; and ./other_script`
> Results in this:
> 
> ```
> fish: Unknown command './other_script'
> fish:
> ./script; and ./other_script
>               ^
> ```

That's not supposed to happen. It works for me, here's an example from scratch:

```fish
mqudsi@Blitzkrieg /m/d/r/fish> printf '#!/bin/true\n' | tee foo1 | tee foo2
#!/bin/true
mqudsi@Blitzkrieg /m/d/r/fish> chmod +x foo1 foo2
mqudsi@Blitzkrieg /m/d/r/fish> ./foo1; and ./foo2
mqudsi@Blitzkrieg /m/d/r/fish>
```

---

fish 3.0 is in development, you can build from `master` or use a nightly build.

**Comment by seanr** [comment]
Ugh, that last bit turned out to be a typo (omitted the last character from a copy/paste in the second command) - I couldn't past the full command here because it's got client names in the paths.

**Comment by seanr** [comment]
So the `...; and ...` does work, but let's get 3.0 out so all the examples on the web (StackOverflow, composer docs, etc) work as expected without translation. ;)

**Comment by krader1961** [comment]
> So the ...; and ... does work, but let's get 3.0 out so all the examples on the web (StackOverflow, various docs, etc) work as expected without translation. ;)

@seanr Are you aware that fish is not a POSIX compatible shell? Which means the syntax it recognizes is not the same syntax recognized by bash, zsh, ksh, etc. Other than trivial statements like `cmd1 && cmd2` any statement you copy/paste that was meant for a POSIX compatible shell like bash will, hopefully, result in a syntax error when evaluated by fish. If you are unlucky the statement will be syntactically valid for fish but do something radically different. Like erasing your home directory. That's not to say fish should not support `&&` and `||`. Much like it provides the `export` shim for `set -gx`. It's just that every time another POSIX compatibility feature is introduced it seems to cause people to demand more POSIX compatibility. At what point does fish stop being fish?

If a feature is being added because it is a good fit for the design and goals of fish that's great. Wherever the idea originates. If it is being added primarily for bash or POSIX compatibility that seems to me like a poor decision.
