### ISSUE TITLE
fish should spawn new processes with the symlink'd PWD

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5300]
Since the changes to symlinked paths, the behavior is now inconsistent when fish launches new processes since fish is "in" one directory but launches the target process with a PWD that is different from its own.

At first I thought it was just a cosmetic issue - start fish and the prompt shows `~ >`, cd into a symlinked path, the prompt changes to `~/foo >`, run `exec fish` and the prompt changes to `/path/to/foo >` because the child process doesn't see the symlinked directory that the original fish instance saw.

However, I've now run into a few cases where there are oddities that result from fish using a symlinked path internally but launching processes with the actual path. For example, the workaround that I put in place for detecting when running out of CMake build directory no longer works if you build fish from a symlinked path then run it out of there - `CMAKE_BINARY_DIR` is the symlinked path but `PWD` when starting the new fish instance is not.

**Comment by faho** [comment]
This would involve either trusting an inherited $PWD or validating that it points to the same thing, right?

**Comment by faho** [comment]
The problem here is that, as soon as the launched process does getcwd(), it'll get the "real" path. I don't think we specifically translate $PWD for export.

That was the reason why we've resisted doing "logical" paths for so long.

**Comment by mqudsi** [comment]
> That was the reason why we've resisted doing "logical" paths for so long.

Remind me why we did?

**Comment by faho** [comment]
Because it makes `cd`ing through symlinked directories nicer. Really, everything "is" real, but that doesn't match the view that people have of it when they have to navigate it. Annoyingly, that includes myself!

We've tried for years to change people's minds, or to come up with alternative ideas, but we've ultimately been unsuccessful, so it's time to stop tilting at windmills.

I don't love it either, but I don't see a better alternative.
