### ISSUE TITLE
fish_config prompt tab looks broken in tmux

### ISSUE THREAD

**Issue by crocket** [fish-shell/fish-shell#5312]
```
$ echo $version
2.7.1
$ echo $TERM
screen
$ uname -a
Linux gentoo 4.14.65-gentoo #4 SMP Mon Sep 24 00:21:29 KST 2018 x86_64 AMD FX(tm)-8300 Eight-Core Processor AuthenticAMD GNU/Linux
```

`sh -c 'env HOME=$(mktemp -d) fish'` doesn't fix this issue.

My actual terminal environment is tmux in alacritty.

![2018-11-03_sat_00 50 50](https://user-images.githubusercontent.com/748856/47946402-9da3c900-df4e-11e8-8f2f-bcb8113c0895.png)

**Comment by faho** [comment]
Yup. Tmux has a different sgr0 ("exit attribute mode") sequence that it appears web_config.py can't handle, so `set_color normal` won't be converted correctly, so you won't see some parts of the prompts.

**Comment by crocket** [comment]
Is there a work around for tmux?

**Comment by faho** [comment]
The issue here goes deeper. fish_config turns text with ansi-escapes into html to render the prompts.

Only it assumes that ansi-escapes look like

```python
"""
         \x1b                    # Escape
         [^m]+                   # One or more non-'m's
         m                       # Literal m terminates the sequence
"""
```

Which does not apply to tmux's sgr0, which is `\E[m\017`.

Changing this requires removing this assumption, which requires parsing escapes entirely differently.

**Comment by faho** [comment]
Okay, I have now hacked around this by explicitly matching tmux's sequence.

It's not pretty, but works.
