### ISSUE TITLE
Unhandled/unsupported case for __fish_git_files under porcelain=2

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5317]
I ran into a case where `git checkout <TAB>` was not giving me the modified file(s) in the current repository and was only offering tags/branches for completion. I believe it's a convoluted `git status --porcelain=2` output that's causing `__fish_git_files modified` to not include these results.

```fish
mqudsi@Blitzkrieg /m/d/G/EasyBCD> git status --porcelain
 M EasyBCD/imports/profiles/grldr
?? EasyBCD 2.3 Beta - Build 205.exe
?? EasyBCD 2.3.1 Beta - Build 212.exe
?? EasyBCD Commercial Setup.exe
?? EasyBCD Setup.exe
?? EasyBCD/Easy Recovery Essentials.Designer.cs
?? EasyBCD/Easy Recovery Essentials.cs
?? EasyBCD/Easy Recovery Essentials.resx
?? EasyBCD/Resources/cdrom_mount-6.png
?? EasyBCD/Resources/cdrom_unmount.ico
?? EasyBCD/Resources/silk/stop.png
?? EasyBCD/imports/_lang/
?? EasyBCD/imports/libraries/NeoSmart.Localization.dll
?? EasyBCD/imports/libraries/_NeoSmart.Localization.dll
?? EasyBCD/imports/profiles/detect
?? EasyBCD/imports/profiles/easyldr2
?? keys.txt
mqudsi@Blitzkrieg /m/d/G/EasyBCD> git status --porcelain=2
1 .M N... 100644 100644 100644 2338159e2ce8607870d1b64942d7c53021c83cb2 2338159e2ce8607870d1b64942d7c53021c83cb2 EasyBCD/imports/profiles/grldr
? EasyBCD 2.3 Beta - Build 205.exe
? EasyBCD 2.3.1 Beta - Build 212.exe
? EasyBCD Commercial Setup.exe
? EasyBCD Setup.exe
? EasyBCD/Easy Recovery Essentials.Designer.cs
? EasyBCD/Easy Recovery Essentials.cs
? EasyBCD/Easy Recovery Essentials.resx
? EasyBCD/Resources/cdrom_mount-6.png
? EasyBCD/Resources/cdrom_unmount.ico
? EasyBCD/Resources/silk/stop.png
? EasyBCD/imports/_lang/
? EasyBCD/imports/libraries/NeoSmart.Localization.dll
? EasyBCD/imports/libraries/_NeoSmart.Localization.dll
? EasyBCD/imports/profiles/detect
? EasyBCD/imports/profiles/easyldr2
? keys.txt
mqudsi@Blitzkrieg /m/d/G/EasyBCD> __fish_git_files modified deleted
mqudsi@Blitzkrieg /m/d/G/EasyBCD> 
```

**Comment by faho** [comment]
The format isn't the problem. It's that our `git status` invocation doesn't print the directory.

In #5229, I decided to let git do the globs for us, both because that might know more and because it deals with ":/" prefixed paths better than we can. This works _great_ for untracked files and directories. Exactly like you want it - one path component every time, so it doesn't decend into anything to overwhelm you.

Only it appears that with modified files as here, it won't see the directory as modified, so it won't match the simple `*` `*/` globs we use. It would be possible to glob `**` to match everything, though that would possibly be quite slow in large repos.

**Comment by mqudsi** [comment]
Can you clarify which directory you are referring to?

**Comment by faho** [comment]
The "EasyBCD/imports/profiles/" part. Git doesn't think any of those are modified even though there's modified files in them.

Though now that I test it some more, I don't think I ever really checked the case of "untracked file in tracked directory" (as much as git tracks directories, meaning there is a tracked file somewhere in there). That also doesn't quite work, because git doesn't actually descend given directories to check for any matching files in there. We'll have to append a `**` glob there, which means searches without any token will be slow, but then again I'm not sure why I assumed it'd be faster without it? Also we will get the full path at once again, but progressively disclosing path components on one file isn't all that useful, and fish itself already does it if there are multiple. Only it'll show all of them at once.

**Comment by mqudsi** [comment]
Under d3ce4db3, with `git status --porcelain` returning the following:
```
?? .ignore
?? .vs/
?? CMakeSettings.json
?? GNUmakefile
?? GNUmakefile.in
?? _GNUmakefile
?? autogen.sh
?? build_tools/list_fish_functions.fish
?? complete_fzf.fish
?? job_control.expect
?? share/completions/openocd.fish
```

but `__fish_git_files untracked` returns the following:
```
.ignore Untracked file
:/.ignore       Untracked file
.vs/    Untracked file
:/.vs   Untracked file
CMakeSettings.json      Untracked file
:/CMakeSettings.json    Untracked file
GNUmakefile     Untracked file
:/GNUmakefile   Untracked file
GNUmakefile.in  Untracked file
:/GNUmakefile.in        Untracked file
_GNUmakefile    Untracked file
:/_GNUmakefile  Untracked file
autogen.sh      Untracked file
:/autogen.sh    Untracked file
complete_fzf.fish       Untracked file
:/complete_fzf.fish     Untracked file
job_control.expect      Untracked file
:/job_control.expect    Untracked file
```

Subdirectories already in the index (`build_tools` and `share`) do not have their results reported.

Also, may I suggest _not_ returning `:`-prefixed paths unless the user entered such a path for the current token? It results in basically duplicate suggestions for everything. I handle `./` similarly in `__fish_complete_suffix` by first stripping it from the input then appending it to the resulting completions if it had been specified, which is why `foo ./<TAB>` works but `foo <TAB>` does not list all local files twice, once with `./` and once without.

**Comment by mqudsi** [comment]
Thanks for that fix, @faho. It did the trick.

May I suggest _not_ returning `:`-prefixed paths unless the user entered such a path for the current token? It results in basically duplicate suggestions for everything. I handle `./` similarly in `__fish_complete_suffix` by first stripping it from the input then appending it to the resulting completions if it had been specified, which is why `foo ./<TAB>` works but `foo <TAB>` does not list all local files twice, once with `./` and once without.
