### ISSUE TITLE
Automatically jump when inputting

### ISSUE THREAD

**Issue by haodong** [fish-shell/fish-shell#5318]
`fish, version 2.7.1`

![wx20181105-204607](https://user-images.githubusercontent.com/8103074/47999064-42cfc480-e13c-11e8-8966-976e8bb23c0d.png)

I just input the command as normal `zip -r "..."`

**Comment by faho** [comment]
Duplicate of #5059, #4539, #4609 and numerous other issues.

The summary is that the terminal and fish need to agree on how wide characters are or our cursor movement for doing suggestions goes to wrong places, but this sometimes goes wrong because unicode is hard. Fish 3.0 will have numerous improvements.

**Comment by haodong** [comment]
@faho I feel so passionate to expect the up coming v3.0 fish. Thank you.
