### ISSUE TITLE
`string escape --style=url` mangles wide characters

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5322]
`string escape --style=url` is having a problem with wide characters. This worked at one point. Right now this is breaking the [file:// URL we send to Terminal.app and iTerm](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_config_interactive.fish#L279) if you change into a directory with non-ASCII characters.

## Expected behavior
```
$ string escape --style=url test://中
test://中
```

## Actual Behavior
```
$ string escape --style=url test://中
test%3A//-
```

**Comment by floam** [comment]
You're right, it should encode that character. We could probably just not be putting the protocol through the encoder if we wanted to keep it neat.

Would the expected behavior actually be this, though?
`test%3A%2F%2F%E4%B8%AD`.

Why not encode '/'?

**Comment by krader1961** [comment]
Start with https://www.w3schools.com/tags/ref_urlencode.asp

It's example encoder is even more strict and does encode "/". But that's only because it is doing the simplest rather than optimal encoding. I failed to document it in the code I wrote but see the `escape_string_url()` function in *src/common.cpp*. There are a handful of "safe" characters that are not ASCII alpha-nums and thus do not need to be encoded.

**Comment by krader1961** [comment]
And by "failed to document" I mean that I probably should have included a link to an authoritative document about what chars do not need to be encoded.

**Comment by floam** [comment]
What's the list of safe characters? The only list I can find is [RFC 3986's special reserved characters](https://tools.ietf.org/html/rfc3986#section-2.2). But this list contains both ':' and '/' so I feel like they should either both be encoded or both not be encoded.

The unreserved characters are `ALPHA / DIGIT / "-" / "." / "_" / "~"`.  - no slash there.

**Comment by faho** [comment]
This is probably my fault in #4979, since I removed a "wcs2string" from `escape_string_url()`, so it's now operating on wchar_t instead of char.

That should either be reverted or we should let all non-ascii characters through unescaped.

I don't think we want to escape all "/", since the special meaning for "/" is still correct. If you have some path in $path and do "file://$path", those "/" need to be there! If you escape them that makes it wrong.

Any way, if we can't find an authoritative source here, the best we could do is to check what the consumers handle. Does terminal.app accept `file://中`?

**Comment by floam** [comment]
> Does terminal.app accept file://中?

No.

`$ printf \e\]7\;file://rmbp.local/Users/floam/中\a;` - fails to set the title and proxy icon's path.
<img width="427" alt="screen shot 2018-11-07 at 2 56 26 am" src="https://user-images.githubusercontent.com/291142/48127505-bfe06400-e238-11e8-965a-ef3a2e6372b3.png">
<img width="405" alt="screen shot 2018-11-07 at 2 56 18 am" src="https://user-images.githubusercontent.com/291142/48127506-bfe06400-e238-11e8-8b26-ef23c7f15678.png">

`$ printf \e\]7\;file://rmbp.local/Users/floam/%%E4%%B8%%AD\a;` -it works
<img width="242" alt="screen shot 2018-11-07 at 3 01 15 am" src="https://user-images.githubusercontent.com/291142/48127773-66c50000-e239-11e8-846f-a43e987afb83.png">

**Comment by floam** [comment]
> I don't think we want to escape all "/", since the special meaning for "/" is still correct. If you have some path in $path and do "file://$path", those "/" need to be there! If you escape them that makes it wrong.

Sure, so you should set your script up so you're not URL encoding those slashes. But a function that does URL encoding? I think it should encode them. Python, ruby, perl all do this. This is for encoding the stuff that goes, typically, after `?query=` stuff in a URL. You wouldn't normally pass entire URLs through something that does URL encoding.

**Comment by floam** [comment]
AFAIKT @krader1961's list of safe characters was almost correct, but it just should not have had '/' in it.

**Comment by faho** [comment]
I just basically reverted this to the status quo, including --style=var, which as it turns out was also broken.

I've added tests with some actual multibyte characters, so hopefully this won't happen again.
