### ISSUE TITLE
tilde expansion mangles ~username/ paths

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5325]
On `master`, tilde-with-usernames expand to something with an extra character at the end. Looks like some length is off by one.

```
~ $ ls ~floam/.config
ls: /Users/floamm/.config: No such file or directory
~ [1] $ echo ~floam/ ~floam ~
/Users/floamm/ /Users/floam /Users/floam
```

**Comment by floam** [comment]
Bisects to 410e13dd749519552b1afa27fe5aed3bd9a201ad

**Comment by crocket** [comment]
It seems C++ string handling is not fool-proof.

**Comment by faho** [comment]
Yup, should be fixed now.

The problem was that the "out" pointer pointed to _before_ the "/", where the previous code expected it _on_ the slash if there is any. Simply reordering those lines makes it work.

Unfortunately, I don' think there's a great way to test this? We can just unit-test this one method, but I'd rather just test from script, e.g. `echo ~root/`, but I don't think there's a single username that we can count on existing?
