### ISSUE TITLE
cmd_duration: show fractions of a ms.

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5326]
I think we should make `$cmd_duration` a float with 2 significant digits shown after the decimal.

That extra bit of detail is nice for things that take on the order of ~20ms or less. Often after running something interactively, if I am curious how long it took, but it was pretty fast, I'll wind up a `for x in (seq 100)` loop and run it again, in order to get an accurate number from `$cmd_duration`. I've had it changed locally today and feel like I really like these results more from one-offs:

```
~ $ printf 0
~ $ echo $cmd_duration
0.05
~ $ fish_prompt > /dev/null
~ $ echo $cmd_duration
17.18
~ $ fish_prompt > /dev/null
~ $ echo $cmd_duration
17.31
```

Due to the fact that script authors already will have to deal with the uppercase to lowercase change, at the same time for 3.0 is the best opportunity we will have to revise the output.

It's pretty trivial to split on '.' to remove the fractions if they are not desired. With fish 3.0, `math` can easily work with decimals and everything is fast, so someone who wanted to truncate the variables can go ahead and use `math floor()` on it without worrying about speed.

What do people think?

**Comment by krader1961** [comment]
If finer grain resolution is needed you should add three digits for microsecond resolution. But rather than make another backward incompatible change I would suggest introducing a new var, `cmd_duration_usec`, that is a simple int. Since that is backward compatible it doesn't even need to be rushed into the 3.0 release. It can be added for the 3.1 release. Then mark the legacy `CMD_DURATION` and `cmd_duration` as deprecated and slated for removal with the 4.0 release.

**Comment by ridiculousfish** [comment]
I'm fine trying to make $cmd_duration a float after 3.0

**Comment by faho** [comment]
I'm going to close this in favor of `time`, which has microsecond resolution. Changing $cmd_duration is probably not worth it.
