### ISSUE TITLE
Remove `read --all-lines` again?

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5332]
This option is a shortcut that appears to be entirely unused (except for https://github.com/nthapaliya/dotfiles/blob/3e5db2b3e9c6cfacd2d10e910529606e790021a6/home/.config/fish/functions/gbb.fish#L19 I can't find a single use on github), so now is the ideal time to remove it again, if we decide it's not useful enough.

@mqudsi?

**Comment by zanchey** [comment]
As explained to me by @faho on Gitter, it is a shortcut for `read -d \n -z`. I'm not averse to that but it seems to me there are lots of ways to do the same thing (eg `read -z | string split '\n') which is not really in keeping with fish philosophy.

**Comment by zanchey** [comment]
If we're keeping it, we need to add a completion too :-)

**Comment by mqudsi** [comment]
There are no uses for it because it’s not in any releases yet.

**Comment by faho** [comment]
@mqudsi: But _we_ could use it without any release, and the fact that we're not tells me that this maybe isn't all that useful, which means it might be better to remove it.

It's a shortcut for something that isn't used all that often - for zero-delimited input, you probably don't want to split by-line, and for non-zero-delimited input, you probably don't want to read "all" of it in one go. And if you did, then you wouldn't want it to arbitrarily stop at the first NUL (you'd want it to fail).

**Comment by mqudsi** [comment]
@faho your original post was searching for references on all of github. I'm surprised there *were* any.

> I'm not averse to that but it seems to me there are lots of ways to do the same thing (eg `read -z | string split '\n'`) which is not really in keeping with fish philosophy.

@zanchey it's actually even longer than that, since you then have to read _that_ into an array.

---

I've spoken about this elsewhere - I think it's a mistake for the default `read` tokenizer to be a simple space because the first thing fish teaches newcomers is that unlike in bash, here space is your friend and you don't have to be afraid of it. When consuming input from another application, it is typically done line-by-line and not word-by-word (for anything but the most trivial of cases).

I wrote out all the above then I realized I was responding to the argument for `-L` or `--line`, which I strongly believe in (as you can tell), which was the primary reason behind the commit that simultaneously introduced `-A` / `--all-lines` (bd8c8ceb5994ba0945fbe331574f68c6d214408b).

I don't think reading *all* of a stream is a good idea in the general case, regardless of whether you are splitting on whitespace or newlines, although the limitations of fish lang might require doing so (c.f. https://github.com/fish-shell/fish-shell/commit/a5b8359c1cfad6b903fbc3106ca633e268b405f3#commitcomment-31091604). If you feel strongly enough about this to open up an issue, as long as `--line` stays you can feel free to drop `--all-lines` without any hard feelings on my end.

(although I must note that I think the discussion about `\0` characters within the bytestream isn't more than a mental exercise -- after all, until fish 3.0 a lot of our own commands didn't handle embedded NULs and they are rare in practice unless explicitly requested such as with `--print0`, and it would be trivial to write an implementation of `read` that would include NULs within lines without a problem -- the current restriction on "reading until the first NUL" is merely a side-effect of reusing `read -z` rather than simply consuming the entirety of the input stream)

**Comment by faho** [comment]
>On second thought, maybe we should keep that (for supporting --print0 output) and add a different flag to read to end of stream?

That might be possible, though the typical way to use it is `while read -z`, which means it's not really high priority.

>If you feel strongly enough about this to open up an issue, as long as --line stays you can feel free to drop --all-lines without any hard feelings on my end.

I have no issue about "--line", it's about "--all-lines".

-----

Sidenote:

> I think it's a mistake for the default read tokenizer to be a simple space because the first thing fish teaches newcomers is that unlike in bash, here space is your friend 

If you only use one variable and no --array, we don't split - `read line` really does read an entire line. The space behavior is optional and quite often useful!

**Comment by faho** [comment]
Okay, I've now removed --all-lines and warned the sole user.

**Comment by nthapaliya** [comment]
Thanks for the warning! I'll change my dotfiles. It gave me quite a chuckle (and dare I say, made me feel quite special) to be the sole user of a flag in the entire world. :)
