### ISSUE TITLE
Regression  in git master: fish title is not working correctly with tmux

### ISSUE THREAD

**Issue by actionless** [fish-shell/fish-shell#5339]
`fish, version 2.7.1-1686-g7437f82d9` (with stable 2.7.1 issue is not reproducible)

Arch Linux, tried URXvt and xst

1) open tmux
2) open fish inside tmux
3) open vim inside fish (ensure it have `set title` in `.vimrc`, usually it's default)
4) observe titlebar/tasklist of the terminal window

Expected result:
window name should change from `fish $current_dir` to `vim`

Actual result:
window name still stays `fish $current_dir`

**Comment by faho** [comment]
What is your `fish_title`? `type fish_title` should tell you.

This works for me, so I'm assuming it's down to your local customization.

**Comment by faho** [comment]
Ouch, no.

As it turns out, tmux prints two "titley" things: On the left, it shows the running program, on the right (and as the actual terminal title) it shows the programmable title.

And, as it turns out, `status current-command`, which was supposed to replace `$_`, does not work. It just always returns the "program_name" variable, which is a constant containing "fish".

@mqudsi: I'm going to commit a hacky solution to this, that uses the variable in the background. I'm not sure what the cleanest way to solve this is.

**Comment by actionless** [comment]
thanks, it helped!
