### ISSUE TITLE
Do we still need string.fish?

### ISSUE THREAD

**Issue by neersighted** [fish-shell/fish-shell#5384]
The `string.fish` wrapper is still present in the repo (and was last touched a year ago). Do we still need a `string` wrapper going into fish 3.0?

**Comment by ridiculousfish** [comment]
IIRC this wrapper prevents old 'string' functions from shadowing the builtin string function.

**Comment by neersighted** [comment]
Isn't `/usr/share/fish` at the bottom of the specificity-chain? Wouldn't `~/.config/functions/string.fish` override it, anyway?

**Comment by faho** [comment]
I mentioned this one explicitly in #5279.

It's an upgrade shim, and at some point we should remove it. But I don't think that's now, since 2.2 is still used in Ubuntu 14.04, which is still a supported release.

That changes next year, so the release after 3.0 can have it removed.

Let's track that in #5279!
