### ISSUE TITLE
idea: function returning multiple values

### ISSUE THREAD

**Issue by zhangfuwen** [fish-shell/fish-shell#5397]
Hi,
I am not a expert in shell scripting, and I am doing some shell scripting recently. 

I noticed that not a single shell implementation support returning multiple values or string values in a function.

Since fish is the most recently introduced shell implementation I could find, I think maybe we can talk about it here. Forgive me if it is not approperiate.

I did some search and found out that nearly all shells:
1. can only return a integer ( instead of a string ) from a function
2. can return only one value

shell scripting is fun and convenient .  but the function part is not.

What do you guys think? Maybe we should do that. If shell has a better function implementation, I think I will use it more often than python.

**Comment by ridiculousfish** [comment]
Functions are meant to be mostly interchangeable with ordinary external commands like `/bin/cat`: you can pipe them, etc. In fact it's often unknown to the user whether a command line invokes a function or external commands. Because external commands can only return an integer result, functions get the same limitation.

By all means continue to use Python and don't write real scripts in a shell scripting language :)

Closing for the above reasons. Thanks for sharing your ideas!
