### ISSUE TITLE
Does fish load `config.fish` every prompt? How to prevent source certain tools like pyenv?

### ISSUE THREAD

**Issue by legatoo** [fish-shell/fish-shell#5405]
>   fish --version
>   echo 2.7.1
> 
>  uname -a
>  Darwin eva_mac 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
> 
> echo $TERM
> xterm-256color
> 
> sh -c 'env HOME=$(mktemp -d) fish'
> changes my prompt. I installed omf and using eclm theme.

The problem is my prompt is relatively slow. It takes nearly 1~2s to show up every time I hit enter or commands. I tried the method to profiling fish which you offered in [this issue](https://github.com/fish-shell/fish-shell/issues/2854). the output file is:

[prompt_prof.txt](https://github.com/fish-shell/fish-shell/files/2671502/prompt_prof.txt)

besides the time git dirty takes, pyenv also takes alot:

> -2843   245505  -> and source (pyenv init -|psub)

My question is does fish process `source (pyenv init -|psub)` every time I hit enter? Is it possible to prevent doing this in an opening shell?

the script controls the prompt: 

```bash
# name: modified eclm
function _git_branch_name
  echo (command git symbolic-ref HEAD ^/dev/null | sed -e 's|^refs/heads/||')
end

function _is_git_dirty
  echo (command git status -s --ignore-submodules=dirty ^/dev/null)
end

function fish_prompt
  set -l last_status $status
  set -l cyan (set_color -o cyan)
  set -l yellow (set_color -o yellow)
  set -l red (set_color -o red)
  set -l blue (set_color -o blue)
  set -l green (set_color -o green)
  set -l normal (set_color normal)

  if test $last_status = 0
      set status_indicator "$green✔︎ "
  else
      set status_indicator "$red✗ "
  end
  set -l cwd $cyan(basename (prompt_pwd))
  
  set -l branch_name (_git_branch_name)
  #echo 'branch name is ' + $branch_name
  if [ $branch_name ]

    if test $branch_name = 'master'
      set -l git_branch "master"
      set git_info "$normal ($red$git_branch$normal)"
    else
      set -l git_branch $branch_name
      set git_info "$normal ($blue$git_branch$normal)"
    end

    if [ (_is_git_dirty) ]
      set -l dirty "$yellow ✗"
      set git_info "$git_info$dirty"
    end
  end

  # Notify if a command took more than 1 minutes
  if [ "$CMD_DURATION" -gt 60000 ]
    echo The last command took (math "$CMD_DURATION/1000") seconds.
  end

  echo -n -s $status_indicator $cwd $git_info $normal ' '
end
```

Thank you.

**Comment by faho** [comment]
> My question is does fish process source (pyenv init -|psub) every time I hit enter?

No. It's just that when you profile by doing

```fish
fish --profile /some/file -c 'fish_prompt'
```

that starts a new fish and profiles its entire run.

You want to check just the bits under "fish_prompt".

----

As an aside, I know that the pyenv people recommend `source (pyenv init - | psub)`. That's bogus, and I have opened [a PR](https://github.com/pyenv/pyenv-virtualenv/pull/286) there more than a month ago.

`psub` creates a temporary file with the contents of its stdin, that source then reads. Only source can just read from stdin to begin with:

```fish
pyenv init - | source
```

works.

Also, `pyenv init -` just prints a bunch of code that will most likely never change. Just take its output and append it to your config.fish, probably guarded by `if status is-interactive`, instead of running it on every shell start.

-----

As for why your prompt is slow: It takes ~100ms:

>317     106377  > fish_prompt

(this means that 0.317ms was spent doing "fish_prompt" itself, but 106ms was spent doing it and its children)

And of that, about 9ms was spent running `_is_git_dirty`.

You might want to check your right prompt too, if you have one. Profile `fish_right_prompt`.

**Comment by legatoo** [comment]
@faho Thanks for your reply. `pyenv init - | source` works, great!  With regards to `fish_right_prompt`., I don't have a right prompt. By the way, what's the meaning of `Time` and `Sum` in profiling file?

**Comment by legatoo** [comment]
@faho my prompt now act responsively. I think it may be because I was running a compiling job which consumed 70+% CPU, when I shut the compile, everything goes fine. Thanks so much for your help, and I will definitely try 3.0 👍
