### ISSUE TITLE
Color coding breaks when creating an alias function for ls

### ISSUE THREAD

**Issue by Prodeguerriero** [fish-shell/fish-shell#5408]
Hi all,

First off, some info on my setup:
```
Fish version: 2.7.1
MacOS 10.13.6
iTerm2 3.2.4
No omf, default theme.
```

I have been playing with fish for a couple of days and trying to get my bearings. I'll be upfront: I am not exactly a sh/bash ninja, so do consider me a n00b.

I wrote the following function to create an alias for `ls -Fhl`:
```
function lls
    command ls -Fhl $argv
end
```
The function itself works as expected, but the color coding of the terminal output seems to break.
<img width="584" alt="screen shot 2018-12-12 at 17 41 04" src="https://user-images.githubusercontent.com/15149858/49884517-57873280-fe35-11e8-9d17-b89a9fe56de7.png">

I hope I am not missing something obvious :P

Thanks a lot!

Any idea on why this is happening?

**Comment by Prodeguerriero** [comment]
Damn, I knew I was missing something obvious.
Thanks for pointing that out. Easy peasy.

🔒

**Comment by floam** [comment]
No problem!

A couple more things to be aware of:

If you simply remove the `command` part from your function, so that it's:

```fish
function lls
    ls -Fhl $argv
end
```
You will notice the color works - what's going on here is because you're not requesting the system `ls` command, but just `ls`, you are adding options to `ls`-the-function, which is our color-adding wrapper.

Also, I'll note that you also have the option to use a shortcut we provide to create these kinds of functions that work as aliases - the `alias` function:

```fish
alias lls 'ls -Fhl'
```

Which produces a function that goes like this:

```fish
function lls --description 'alias lls ls -Fhl' --wraps ls
    ls -Fhl $argv
end
```

You don't need to use `alias`, there's no real advantage, it's great to just do the function yourself, so that you understand what you're doing, but along with not putting `command` there, the other differences is that it would have used the `--wraps ls` on `function` - which tells fish's completer that `lls` is actually, deep down, `ls` - so tab completion works on `lls`:

```
lls<TAB>
-1                                      (List one entry per line)
-@                          (for -l: Display extended attributes)
-A                                  (Show hidden except . and ..)
-a                                          (Show hidden entries)
...
```

You might want to do this for your wrapper function. Have a nice day!

**Comment by Prodeguerriero** [comment]
Thanks for the extra info.
I have already tried the `alias` shortcut, but I got lost because I couldn't (and still cannot) understand how to effectively generate a `.fish` file.

If I do `alias mytest 'ls -G`, then do `functions mytest`, I get:
```
# Defined in - @ line 0
function mytest --description 'alias mytest ls -G'
	ls -G $argv;
end
```
The function is defined temporarily and only works within the Fish instance I used `alias` in.
What would be the best way to use `alias` to generate a `.fish` file inside `.config/fish/functions`?

**Comment by floam** [comment]
So, it's just like any other function you define interactively - like if you typed that function out. You can make it persist by using `funcsave` - `funcsave lls`. It will commit a lls.fish down into your fish functions dir.
