### ISSUE TITLE
builtin math: argument separator

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5420]
@faho and I were discussing `LC_NUMERIC` and how input and outputs are handled in fish and in other shells. He pointed out that the way `math` works, we would have difficulty allowing it to work out localized numeric output of commands, because we use a comma as an argument separator.

```fish
math 'ncr(2,5)'
```

I think this doesn't look very fishy anyhow, and it should just be be space separated:

```fish
math 'ncr(2 5)'
```

**Comment by j-f1** [comment]
How about `math '(ncr 2 5)'` (with optional parens)? It fits with the command substitution syntax.

**Comment by j-f1** [comment]
Probably not since the first thing after the paren would either be a function name or a number.

**Comment by faho** [comment]
@floam: You've skipped a few steps here!

The current "," is only a problem if we decide that localized numbers should be accepted.

Math currently on purpose sets LC_NUMERIC to C while it's running. This is so expressions mean the same thing regardless of locale.

But our `printf` not only accepts both current-locale and c-locale numbers, it also prints them in the current locale.

This should probably be consistent.

There's a few possibilities for how we could handle this:

- Only accept and print "." separated (ie C-locale) numbers in both - what math now does

- Accept both C-locale numbers and current-locale - what printf now does

- Accept _all_ locale numbers - i.e. allow "," even if the current locale doesn't use them

- Only accept localized numbers - this is just flat-out wrong.

The problem with the second one is that it's still locale-dependent - if I use a ","d number and send my code to @floam, it's gonna break for him. The third would fix that,  but would require us to actually write that code because we can't depend on a comma-using locale existing.

The former is my preferred solution. Dots are what programming languages typically use and what e.g. `bc` uses (which is what math used previously, if you recall). I don't think I even attempted to use commas with `math` for quite a while. This solution allows any `math` calls to work everywhere, unless some software is called that prints localized numbers. In my experience, that's not a big problem.

And if we decided on that, there'd be no need to change the separator in `math` (for the record, `bc` also uses commas here).

(it's possible there are other systems apart from "decimal point" and "decimal comma)

**Comment by faho** [comment]
One thing from #5421:

>even awk which will have commas in them because of LC_NUMERIC without thinking

My GNU Awk 4.2.1 only reads floats with ".", not localized ones, and outputs them with a ".".

**Comment by floam** [comment]
Mine:

`echo 5.29 | awk '{ print int($1), sqrt($1) }'`

**Comment by faho** [comment]
>The current "," is only a problem if we decide that localized numbers should be accepted.

I've closed that one, so I'm closing this one.
