### ISSUE TITLE
Tab completion and auto suggestion uses backslashes for escape characters instead of simply wrapping in quotes.

### ISSUE THREAD

**Issue by rsheasby** [fish-shell/fish-shell#5433]
Hi team.
Running git master - `fish, version 3.0b1-21-gfb679ac9c`
Not sure if this was an active design decision, or if it was simply made this way to replicate the behavior of bash, but when you try to tab complete a directory with spaces in it for example, it will tab complete it with backslashes behind every space instead of simply wrapping the path in quotes which looks much cleaner and easier to read. It does the same for the autosuggestions. I was unable to find any pre-existing issue for this so apologies if this is a duplicate.

**Comment by faho** [comment]
Yeah, sounds fair enough.

We do already have a heuristic in escape_string_script, though it's a bit simple, and we seem to disable it somewhere in the completion/paging system.

**Comment by mqudsi** [comment]
I'm not sure which is more user-friendly for editing (rather than viewing), as one can immediately tack input on to the end of a `\`-escaped string but not a quote-escaped one.

I think if we go this route we need to do what `cmd` and `powershell` do for completions, which is a bit involved:

`cd "C:\Program Files"\<TAB>` is fixed to `"C:\Program Files\"` before offering suggestions, which would autocomplete to the full path with one level of quotes opening and closing at the start and end of the suggestion.

**Comment by faho** [comment]
>one can immediately tack input on to the end of a \-escaped string but not a quote-escaped one.

If we decide to use quotes in escape_string_script, we also (already!) close the quotes, so you can.

E.g. if there are two files, `some file with spaces` and `some file with more spaces`, we currently complete the common prefix as `some\ file\ with\ `, but we could also use `"some file with "`, and you could immediately go on, even changing it to `"some file with "more\ spaces`.

**Comment by mqudsi** [comment]
Yup, but autocompleting *that* again does not clean up the quotes.

**Comment by mqudsi** [comment]
I meant completing `"/var"/lo<TAB>` completes to `"/var"/log/` without the quotes cleaned up to `"/var/log/"` (or dropped entirely in this case, as they aren't needed.

Regardless, there are certainly a lot of edge cases here.

One case that would probably be a straightforward switching of quoting modes would be argument/command completion from history, though. Unlike `<TAB>` completion, those are more "drop in place" rather than "build incrementally".

**Comment by floam** [comment]
This is reasonable for completion, but not for suggestions. The mechanics of the autosuggestions are such that they are previewed as a dimmed out suffix shown on the command-line beyond your cursor. You can't have it changing the stuff already typed, at least not before accepting them, and that would probably be jarring.

**Comment by stellarpower** [comment]
Would some issues be simplified by providing a setting for a preferred escape form? Such that in any cases like the above where there's an ambiguity, or in other cases, Fish should always pick the preferred form, if the option is set.

Using a backslash is quicker to type in various situations, but I unanimously prefer quotes in any given situation - it's closer to programming languages, so helps highlight textual values rather than switches, comes up in a different colour, and scans an awful lot better to my eye - Fish really excels at the colours and formatting here, and I use a lot of spaces in my paths so it makes life a lot less stressful. For my situation, I'd happily set an option that Fish can/should always replace backslash escapes with quotes, be it as I'm typing, when I hit tab, etc. I hate when software makes an assumption for me, and to that end I think it would work well to make it an explicit option, also with the options for the reverse - for users who always prefer backslashes - and to leave as the default and change nothing. Don't know if this helps much internally, but as an external feature it's something that would work nicely for me at least. If explicitly setting a preferred quoting method would make some of the above corner cases resolvable, then it's an option I'd gladly set anyway.

**Comment by faho** [comment]
>Would some issues be simplified by providing a setting for a preferred escape form?

No such setting will be added. That's not the way we do things.

**Comment by floam** [comment]
Something else that I think could help is to make it so foo\<tab> could complete an escaped space if in a dir with 'foo bar' and 'foo foo' files in it. Instead it actually removes the slash.

**Comment by stellarpower** [comment]
Are there any updates on this at all? I just lost about six hours because I accidentally sent a tarball inside the directory I was compressing, because my eyes didn't scan I had an extra slash at the end amongst all the backslashes - twice. It'd be really good to have it functioning. I try to open a quote before I hit tab, but still, as a default behaviour for any tab completion it would make life a lot easier.

**Comment by max-sixty** [comment]
Another motivating case, I think much simpler than the original (I think this is the same issue but say the word as I'll open a new one...)

I wanted to add a shortcut to wrap a command in `pueue add '$command'`. For example:

```fish
echo hello \
       world \
       it \
       me
```

...would wrap as...

```
pueue add 'echo hello \
   world \
   it \
   me'
```

But instead `commandline -r "pueue add $(string escape -- $command)"` gives us:

```
pueue add echo\ hello\ \\\nworld\ \\\nit\ \\\nme
```

...which is much much more difficult to read. Notably there are no quotes in the original — it would be easier for `fish` as well as a person to use quotes.

(+ thank you for fish — it's awesome!)

**Comment by max-sixty** [comment]
@krobelus thanks for fixing this!

Do you know whether this fixes the `string escape` example above? It looks like it might not; I can open a new issue if that's the case. Or test it on the next release if you're not sure.

**Comment by krobelus** [comment]
I changed `string escape` to also use quotes when the input contains `'`' or `\`. I guess the intention for the old behavior (of using backslash escapes) was that that works in other shells.. but the compatibilty breaks down as soon as we have a character like \n so I'm not sure if it's relevant

Your example is not fixed because when there is a newline in the input, we still use escapes.
We can definitely try to find some heuristics to make the output look better by default.
Need to think about the use cases.

It's easy to fix your immedate problem, for example this way (or use `string replace`)

	commandline -r "pueue add '$(printf %s $command | sed "s/\\\\/\\\\\\\\/g; s/'/\\\\'/g")'"

**Comment by max-sixty** [comment]
> It's easy to fix your immedate problem, for example this way (or use `string replace`)
> 
> ```
> commandline -r "pueue add '$(printf %s $command | sed "s/\\\\/\\\\\\\\/g; s/'/\\\\'/g")'"
> ```

Awesome, thanks a lot! I'll use this for now
