### ISSUE TITLE
Builtin wrapper functions produce a backtrace with invalid options

### ISSUE THREAD

**Issue by meain** [fish-shell/fish-shell#5434]
fish version: `2.7.1`

If I pass in an unknown argument to a builtin, it produces some unnecessary output and not just the `Unknown option` message.

```
meain@plank ~> cd -r
cd: Unknown option '-r'
/usr/local/Cellar/fish/2.7.1/share/fish/functions/cd.fish (line 30):
    builtin cd $argv
    ^
in function 'cd'
        called on standard input
        with parameter list '-r'


       cdcd - change directory
        -

   Synopsis
       cd [DIRECTORY]

cd: Type 'help cd' for related documentation
```

**Comment by floam** [comment]
I don't think he's complaining about seeing the synopsis, but that he's getting this part:


```
/usr/local/Cellar/fish/2.7.1/share/fish/functions/cd.fish (line 30):
    builtin cd $argv
    ^
in function 'cd'
        called on standard input
        with parameter list '-r'
```

@meain is that correct?

**Comment by meain** [comment]
@floam yes

**Comment by zanchey** [comment]
That could be fixed, though it's low-impact.

**Comment by faho** [comment]
Okay, what should we change here?

We could completely remove the complete backtrace and help, but that would just leave:

```
$ cd -r
cd: Unknown option '-r'
```

which seems alright if it's directly on the commandline like in that example, but what if it's inside a script somewhere? Then you can play hunt-the-bug.

We could probably remove the help or just point to it with "see `help cd` for help".

We should also shorten the backtrace, because this is ridiculous:

![Screenshot_20190326_155705](https://user-images.githubusercontent.com/5185367/55007526-da488d80-4fdf-11e9-9935-9d300c841c3b.png)

How about removing the multiple "on standard input" lines and the multiple empty lines here, for one?

So the backtrace looks more like

```
cd: Unbekannte Option '-r'
/usr/share/fish/functions/cd.fish (Zeile 40):
    builtin cd $argv
    ^
in function 'cd'
        with parameter list '-r'
in function 'd'
in function 'b'
in function 'a'
        called on standard input
```

?

Line information for all the functions would actually be nice, though.

I'm relabelling this as an enhancement because this is currently how it is supposed to behave.

**Comment by faho** [comment]
Okay, I've removed the empty lines.

What I'm working on now:

- Remove the "called on standard input" message

- Print the function arguments on the same line as the function

- Stop calling it "parameter list"

**Comment by faho** [comment]
Okay, here's what I've got:

```
cd: Unknown option '-r'
~/dev/fish-shell/share/functions/cd.fish (line 40): 
    builtin cd $argv
    ^
in function 'cd' with arguments '-r'
in function 'f'
in function 'd'
in function 'b' with arguments '-1q --wurst \$var ""'
in function 'a'
```

from

```
cd: Unbekannte Option '-r'
/usr/share/fish/functions/cd.fish (Zeile 40): 
    builtin cd $argv
    ^
in function 'cd'
	called on standard input
	with parameter list '-r'

in function 'f'
	called on standard input

in function 'd'
	called on standard input

in function 'b'
	called on standard input
	with parameter list '-1q --wurst $var '

in function 'a'
	called on standard input

```

(plus the docs in both - also the missing translation is down to me not yet installing the new version)

Any more ideas?

**Comment by faho** [comment]
The example from the OP:

```
cd: Unknown option '-r'
~/dev/fish-shell/share/functions/cd.fish (line 40): 
    builtin cd $argv
    ^
in function 'cd' with arguments '-r'

       cd - change directory

       cd [DIRECTORY]

       cd changes the current working directory.

cd: Type 'help cd' for related documentation

```

**Comment by faho** [comment]
Okay, now after #3404, the example looks like

```
$ cd -r
cd: Unknown option '-r'

~/dev/fish-shell/share/functions/cd.fish (line 40): 
    builtin cd $argv
    ^
in function 'cd' with arguments '-r'

(Type 'help cd' for related documentation)
```

I'm gonna declare this done for now.
