### ISSUE TITLE
history forward/backwards without arrows

### ISSUE THREAD

**Issue by izelnakri** [fish-shell/fish-shell#5471]
Hi I couldnt get the right bindings for arrowless history navigation. I guess `history-search-backward` and `history-search-forward` keywords are useful for these. How can I bind them to ctrl-k and ctrl-u?

bind ^k history-search-backward
bind ^j history-search-forward

doesnt work.

**Comment by faho** [comment]
>bind ^k history-search-backward

That's not how fish writes these keys. Ctrl is `\c`, so ctrl-k is `\ck`.

The up-arrow is bound to `up-or-search` (check with `bind -k up`, because it's a named key), down is down-or-search, so the binds are:

```fish
bind \ck up-or-search
bind \cj down-or-search
```

Unless you want _just_ the history search (X-or-search moves in that direction if you have multiple lines in the commandline, and only if you're at the end will it search the history), in which case you'd indeed use `history-search-backward`.

Also note that these things are already bound to ctrl-n and ctrl-p as well!

**Comment by izelnakri** [comment]
Thanks for your quick reply! After a day of search I found my fixes below, I think fish_vi_mode breaks few things:

```fish
function fish_user_key_bindings
    fish_vi_mode
    bind -M insert \cf accept-autosuggestion
    bind \cf accept-autosuggestion
    for mode in insert default visual
      bind -M $mode \ck 'history --merge ; up-or-search'
      bind -M $mode \cj 'history --merge ; down-or-search' 
    end
end
```
