### ISSUE TITLE
Failures in high level script functionality on illumos

### ISSUE THREAD

**Issue by Mno-hime** [fish-shell/fish-shell#5472]
On Openindiana I see following failures in "high level script functionality" test:

```
Testing file cd.in ... fail
Error output differs for file cd.in. Diff follows:
--- cd.tmp.err	2019-01-03 07:36:57.439371310 +0000
+++ cd.err	2019-01-03 07:36:22.809496268 +0000
@@ -4,9 +4,3 @@
 
 ####################
 # cd symlink completion
-rm: Cannot remove any directory in the path of the current working directory
-/tmp/cdcomp_test//through/the/looking/glass
-rm: Unable to remove directory /tmp/cdcomp_test//through/the/looking: Directory not empty
-rm: Unable to remove directory /tmp/cdcomp_test//through/the: Directory not empty
-rm: Unable to remove directory /tmp/cdcomp_test//through: Directory not empty
-rm: Unable to remove directory /tmp/cdcomp_test/: Directory not empty
Exit status differs for file cd.in.
Unexpected test exit status 2.
```

For cases like this, where `grep` option is required (`-o` here), which our `grep` does not have, we prepend `/usr/gnu/bin` in `$PATH`, so GNU utilities are executed preferentially. However, from unknown reason it fails here:
```
Testing file psub.in ... fail
Output differs for file psub.in. Diff follows:
--- psub.tmp.out	2019-01-03 07:36:58.476779984 +0000
+++ psub.out	2019-01-03 07:36:22.789465657 +0000
@@ -2,6 +2,6 @@
 bar
 baz
 psub file was deleted
-psub filename does not end with .cc
-psub filename does not end with .cc
+psub filename ends with .cc
+psub filename ends with .cc
 psub directory was deleted
Error output differs for file psub.in. Diff follows:
--- psub.tmp.err	2019-01-03 07:36:58.450481324 +0000
+++ psub.err	2019-01-03 07:36:22.812413444 +0000
@@ -1,6 +0,0 @@
-grep: illegal option -- o
-usage:  grep [-E|-F] [-bchHilnqrRsvx] [-A num] [-B num] [-C num|-num]
-             [-e pattern_list]... [-f pattern_file]... [pattern_list] [file]...
-grep: illegal option -- o
-usage:  grep [-E|-F] [-bchHilnqrRsvx] [-A num] [-B num] [-C num|-num]
-             [-e pattern_list]... [-f pattern_file]... [pattern_list] [file]...
```

```
Testing file realpath.in ... fail
Output differs for file realpath.in. Diff follows:
--- realpath.tmp.out	2019-01-03 07:36:58.892421022 +0000
+++ realpath.out	2019-01-03 07:36:22.789097243 +0000
@@ -5,7 +5,6 @@
 /x
 /abc
 /def
-/tmp/tmp.vOyXE8Ylyr
 fish-symlink handled correctly
 fish-symlink/nonexistent-file-relative-to-a-symlink correctly converted
 fish-symlink/symlink_file handled correctly
Error output differs for file realpath.in. Diff follows:
--- realpath.tmp.err	2019-01-03 07:36:58.881966614 +0000
+++ realpath.err	2019-01-03 07:36:22.810613146 +0000
@@ -1,2 +1,2 @@
 builtin realpath: /this/better/be/an/invalid/path: No such file or directory
-rmdir: failed to remove '/tmp/tmp.vOyXE8Ylyr': Invalid argument
+builtin realpath: .: No such file or directory
```

```
Testing file status.in ... fail
Error output differs for file status.in. Diff follows:
--- status.tmp.err	2019-01-03 07:36:59.059772300 +0000
+++ status.err	2019-01-03 07:36:22.823276164 +0000
@@ -1,5 +1,5 @@
 <W> fish: An error occurred while redirecting file '.'
-open: Invalid argument
+open: Is a directory
 status: Invalid combination of options,
 you cannot do both 'is-interactive' and 'is-login' in the same invocation
 status: Invalid combination of options,
```

**Comment by faho** [comment]
>we prepend /usr/gnu/bin in $PATH

Huh. How do you prepend that? It's possible that we set our PATH for the tests.

And should we be prepending it, like we do /usr/xpg4/bin if it exists?

Anyway, I had seen that, and I'd instead just drop the `grep` in favor of `string`, and the `diff` in favor of `comm`.

The `rm` differences are a bit more annoying. Do the GNU tools behave like we want them? Because otherwise I'd be inclined to just skip these.

**Comment by Mno-hime** [comment]
> > we prepend /usr/gnu/bin in $PATH
> 
> Huh. How do you prepend that? It's possible that we set our PATH for the tests.

We set `PATH` in the build environment: https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/make-rules/shared-macros.mk#L25. It defaults to `PATH.illumos` but is changed to `PATH.gnu`, where needed.

> And should we be prepending it, like we do /usr/xpg4/bin if it exists?

That should work for OI, may not for other illumos distributions. Safe should be to let the user define the environment (here `PATH`) and propagate it verbatim, where possible.

Other possibility is to test for features and then choosing the right binary, or approach to the binary.

> Anyway, I had seen that, and I'd instead just drop the `grep` in favor of `string`, and the `diff` in favor of `comm`.

Thanks. And sorry for our tools not being up-to-date with what one expects.

> The `rm` differences are a bit more annoying. Do the GNU tools behave like we want them? Because otherwise I'd be inclined to just skip these.

"GNU tools" (coreutils, GAWK, tar, ...) behave as expected, when they are available (and they are available by default on OI), they are available both by their expected name from `/usr/gnu/bin` and by prefixing them with `g` and sticking to the default `PATH`: GNU tar becomes `gtar`.

**Comment by faho** [comment]
>It defaults to PATH.illumos but is changed to PATH.gnu, where needed.

Ah, okay. So... I, personally, would heavily favor the GNU tools, but then I actually prefer having lots of features over clean minimalism. And given that we can't rely on the GNU tools everywhere anyway, as long as the non-GNU tools are reasonably standards-compliant, we should just deal with it.

The problem here is that your `rm` has an additional safety measure that stops us from doing the thing we want, which ordinarily would be a very stupid thing to do. But tests sometimes need to test stupid things.

Can you check if

```fish
sh -c "cd ..; rm $PWD"
```

works?

That should be a usable workaround that we can just plonk in here. I don't want to call `uname` if we can help it, and we can't "test" rm. Another possibility would be to use `grm` if it exists.


------------------

The final test tests a redirection - `> .` leads to an error, because `.` of course is a directory. I don't know how to check for either of these because we can't redirect the error itself, so the test harness will always complain about this.

We could again skip this by checking `uname`, or we could change the error (we pass along what  we get from the OS here)...

**Comment by Mno-hime** [comment]
> Can you check if
> 
> ```fish
> sh -c "cd ..; rm $PWD"
> ```
> 
> works?

Well, I guess it depends on what it means "to work"... You expect the `rm` to remove directory or I am missing something?

```bash
{global} newman@lenovo:~/Downloads/tmp1/tmp2 $ sh -c "cd ..; rm $PWD"
rm: /export/home/newman/Downloads/tmp1/tmp2 is a directory
{global} newman@lenovo:~/Downloads/tmp1/tmp2 $ echo $?
2

{global} newman@lenovo:~/Downloads/tmp1/tmp2 $ sh -c "cd ..; grm $PWD"
grm: cannot remove '/export/home/newman/Downloads/tmp1/tmp2': Is a directory
{global} newman@lenovo:~/Downloads/tmp1/tmp2 $ echo $?
1
```

I did not understand the case with redirection.

**Comment by faho** [comment]
>You expect the rm to remove directory or I am missing something?

Basically, yes. We expect it to remove $PWD, to test what fish does when $PWD is removed.

(Well, actually that's just one bit - the cd completion tests just want to clean up, so that's not all that important. Adding a commit for that now.)

>{global} newman@lenovo:~/Downloads/tmp1/tmp2 $ sh -c "cd ..; rm $PWD"

Sorry, `rm -r` or `rmdir`. We need to remove a directory.

>I did not understand the case with redirection.

It's just a case of OpenIndiana having a different error message than "everything" else. This is calling `somecommand > .`. Which makes no sense, because "." is a directory. This is supposed to error out, and on other systems it returns EISDIR, which has the message "Is a directory", but OI returns EINVAL, which has the message "Invalid argument". We simply expected a different error string.

It's just a bit tricky to get the tests to be okay with either.

**Comment by Mno-hime** [comment]
> > {global} newman@lenovo:~/Downloads/tmp1/tmp2 $ sh -c "cd ..; rm $PWD"
> 
> Sorry, `rm -r` or `rmdir`. We need to remove a directory.

Right, that confused me.

In `fish` I see what I expected:
```fish
newman@lenovo ~/D/t/tmp2> sh -c "cd ..; rmdir $PWD"; echo $status                      
0
newman@lenovo ~/D/t/tmp2> sh -c "cd ..; grmdir $PWD"; echo $status
0
```
And exactly the same with `rm -r`/`grm -r`.

Now I understand your case with redirection. I see the same thing.

**Comment by faho** [comment]
For those playing along at home, the remaining issues here are:

- realpath.in, which uses `rmdir` to delete $PWD, which OI protects against - so we have to go around those protections, most likely via `sh -c "cd ..; rmdir $PWD"`, which would disconnect the `rmdir` from the cwd.

- status.in, which attempts a redirection from a directory, and simply gets a different (more informational!) error message. We either skip that test or change the error - though that requires re-testing what the actual error is. Unless we simply declare getting an EISDIR from open means it's EINVAL. Which, I suppose, it is? But other systems may also sometimes return EISDIR. Or we test this differently, with an invocation test, so we can then intercept the error just for the test?

**Comment by Mno-hime** [comment]
Confirmed it works. Thanks!
