### ISSUE TITLE
Exclude `history` operations from history?

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5482]
Suggestion: exclude `history search` and `history delete` when used with additional arguments from history, as their arguments have a high chance of triggering duplication of search terms, e.g. `history search foo` the first time returns `foo` correctly, but thereafter returns both `foo` and `history search foo`.

**Comment by faho** [comment]
`history delete` also has a high possibility of including sensitive information.

I feel like this has a lot of overlap with #4327, because in both the idea is to provide some mechanism to not save something to history, and that it preferably not be a leading space.

There's a few possible ideas (add a "nohist" decorator, or a special binding that doesn't add it to history, add a function that is run to determine whether something is added to history, actually add $HISTCONTROL and $HISTIGNORE), but I feel like most apply to both?

**Comment by j-f1** [comment]
`function --no-history` could be an API

**Comment by mqudsi** [comment]
Yes, my primary motivation for this was data leaks via `history delete` but I purposely filed this as a separate issue from the "no history" option as I think it could be resolved on its own immediately and without too much controversy.

**Comment by faho** [comment]
>I think it could be resolved on its own immediately and without too much controversy.

@mqudsi: What do you propose? Hard-coding, in C++, that we don't save history if the commandline starts with "history", or "history delete" and "history search"?

**Comment by mqudsi** [comment]
Some version of that, yes. As ugly as it sounds.

**Comment by zanchey** [comment]
That sounds a bit too magic to me.

**Comment by mqudsi** [comment]
@zanchey on the flipside, `history` can be made to not emit any commands starting with `history` which is a lot less magic, but I think the reduced transparency in that choice makes the former suggestion more palatable.

**Comment by ridiculousfish** [comment]
I'm going to close this, this is too magic as zanchey says. It's better to be predictable.
