### ISSUE TITLE
--argument-names version doesn't overide $version

### ISSUE THREAD

**Issue by edouard-lopez** [fish-shell/fish-shell#5510]
### Env

```
❯ fish --version
fish, version 3.0.0
```

### Description

From [changelog in `2.4b1`](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.md#significant-changes):
> The **`$version` special variable can be overwritten**, so that it can be used for other purposes if required.

However, trying to use `version` as an `--argument-names` value doesn't overwrite it as shown below:
```
function foo --argument-names version
  echo $version
end
```

```
❯ foo 'abc'
3.0.0  # should be 'abc'
```

:warning: This seem to be a regression on `3.0.0` as I don't have this on `2.7.1`

**Comment by faho** [comment]
We went back on this.

$version is now the variable to consult to figure out fish's version. This is because it was available in every fish version that was ever released, and a version variable isn't of much use if it's not available.

So now it's not overridable anymore because we want it to contain the version, so you'll have to pick a different variable name. Sorry!

**Comment by edouard-lopez** [comment]
I used  different variable name. However, a warning would be useful
