### ISSUE TITLE
An ampersand followed by a minus sign (&-). The file descriptor will be closed.

### ISSUE THREAD

**Issue by actionless** [fish-shell/fish-shell#5522]
fish, version 3.0.0

is it expected result or should it behave like ` > /dev/null` ?

```fish

$ cat file.txt >&-
cat: standard output: Bad file descriptor

```

**Comment by faho** [comment]
That is the expected result. Fish doesn't support that feature because it's seldom useful (over redirecting to /dev/null), is additional syntax (even if very slighty) and it can sometimes lead to weird results.

However, I'm going to leave this open in case someone feels differently.

**Comment by actionless** [comment]
thanks for clarifying

just one more question, what are the possible usecases for giving to application closed descriptor? i've tested with several apps and about half of them just failing before printing any useful result to any other open fd

**Comment by faho** [comment]
>just one more question, what are the possible usecases for giving to application closed descriptor?

The application could react to it, e.g. by not generating any output and terminating early, just to give a return status. In practice, I don't think I've seen that.

>about half of them just failing before printing any useful result to any other open fd

That, I have seen.

Usually, what you'll do instead is use a `-q` option, like `diff -q` or `type -q`.

**Comment by mqudsi** [comment]
I'm reopening this issue because I think there is some value to implementing this at some point (and it would not be merely for the benefit of being posix/bash compatible). 

As @faho mentions, there *are* ramifications for sending a closed `stdin` to an application that the application could respond to (for example, I raised an issue with the httpie project about one such use to disambiguate input when there are multiple choices: https://github.com/jakubroztocil/httpie/issues/660), and moreover, this functionality is actually missing from fish at this time (unless I'm the one that's missing something). While the observed behavior in many cases is similar (but not necessarily identical) to that of redirecting to `/dev/null`, the semantics differ.

So regardless of whether this ends up being implemented as `<&-`/`>&-` or if it gets a more fishy syntax, it's a valid request for a missing feature (please correct me if I'm wrong about the missing functionality, anyone!).

**Comment by floam** [comment]
I also don't like that that the shell literally can't do this.

**Comment by faho** [comment]
>While the observed behavior in many cases is similar (but not necessarily identical) to that of redirecting to /dev/null, the semantics differ.

So... my main question is if there is any practical case where that matters, and where it matters in favor of closing? I'm aware of things failing when you close stdout, but I'm not aware of things working better when you close stdout, so it seems to be fairly useless.

**Comment by ridiculousfish** [comment]
There seems to be some confusion here...

fish has always supported closing fds in redirections via the `>&-` syntax. Closing an fd makes it invalid and so an error message is appropriate.
