### ISSUE TITLE
bad-switch test broke on FreeBSD

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5543]
This was working some commits back, but 

```
[8/11] cd /usr/home/mqudsi/fish-shell/build/tests && ./invocation.sh
Testing shell invocation functionality
Testing file invocation/bad-switch.invoke ... fail
    -Z
Error output differs for file invocation/bad-switch.invoke. Diff follows:
--- invocation/bad-switch.tmp.err       2019-01-17 14:20:10.034121000 -0600
+++ invocation/bad-switch.err   2019-01-17 14:19:46.903725000 -0600
@@ -1,2 +1,2 @@
-fish: invalid option -- Z
+./fish: invalid option -- 'Z'
 RC: 1
```

@faho I don't want to touch this and break the reason for the original change.

**Comment by faho** [comment]
Already fixed, you need a make clean.

Am Do., 17. Jan. 2019, 21:21 hat Mahmoud Al-Qudsi <notifications@github.com>
geschrieben:

**Comment by faho** [comment]
e7221a21

**Comment by mqudsi** [comment]
It actually used to work, but it broke with some of the recent changes.

Hopefully if we switch to CTest we won't need to clean to reflect changes to the tests.

**Comment by faho** [comment]
> it broke with some of the recent changes.

Not quite.

The last change to it was e7221a21efcc290f4425771dea41d9100509ee8a, which renamed the file to "bad-switch.invoke.disabled". Since the tests are found via `*.invoke`, that one will just be ignored. I am confident that there's not been another change that breaks that assumption, or that renames the file back or something.

It's possible you worked on a commit before that, and it left the test behind, but that's not normal, and `make test` should be picking up on deleted and renamed files as well.
