### ISSUE TITLE
Run CI tests on FreeBSD

### ISSUE THREAD

**Issue by asomers** [fish-shell/fish-shell#5544]
Travis may not support FreeBSD, but Cirrus-CI does.  If fish had been running CI tests on FreeBSD, then bug #5453 never would've shipped.  Cirrus is free, and fairly easy to setup.  Here's an example of a Rust project using Cirrus: https://github.com/nix-rust/nix/blob/master/.cirrus.yml .

**Comment by asomers** [comment]
cc @mqudsi

**Comment by faho** [comment]
I have been running the tests on builds.sr.ht for a while now, see https://builds.sr.ht/~faho.

It's still on FreeBSD 11 for now, but it also offers some interesting linux distributions.

Unfortunately, it doesn't feature macOS, and probably won't. Which is important for me, since I don't plan on buying apple hardware.

**Comment by asomers** [comment]
Ahh, cool.  But it looks like you haven't set it up to report status for PRs?  Does builds.sr.ht have that ability?

**Comment by zanchey** [comment]
@j-f1, we [https://travis-ci.org/fish-shell/fish-shell](already use Travis). I'm not opposed to adding another platform, though.

**Comment by faho** [comment]
> Does builds.sr.ht have that ability?

I think it does, but to work automatically it requires owner approval (i.e. @ridiculousfish) to set up the webhooks.

Anyway, we don't rigorously do PRs, so the most important bit for a CI is the email that it's broken afterwards.

**Comment by faho** [comment]
See #5655.

**Comment by faho** [comment]
This should have been closed last year: 67883737c0a5e0e9e2be21605c0f3270c5f0cbb4

FreeBSD CI is now run via Cirrus
