### ISSUE TITLE
Prompt with git information takes too much time to appear in a large git project

### ISSUE THREAD

**Issue by peey** [fish-shell/fish-shell#5551]
Fish version: 2.7.1
OS: Ubuntu 16.04
Terminal: Default
Does the problem appear in shell entered by `sh -c 'env HOME=$(mktemp -d) fish'`? No

To reproduce the issue, use this configuration:
```
  set -g __fish_git_prompt_show_informative_status true
  set -g __fish_git_prompt_showcolorhints true
```
And have the git information as a part of the prompt. In particular I'm using [this prompt function](https://github.com/oh-my-fish/theme-cbjohnson/blob/master/fish_prompt.fish)

Clone a large git project (e.g. https://github.com/WebKit/webkit) and cd into it. The prompt takes very long to appear, and I can't open any other terminals until I kill it or wait for it. Even after it has appeared for the first time, it becomes very slow to enter commands for some reason. Typed characters take a long time to appear, making the command line useless.

**Comment by faho** [comment]
This is pretty much a git issue. There's no faster git call we can use to get the provided information, so you'll have to disable that if it takes too long for you.

**Comment by zanchey** [comment]
You can also just disable `__fish_git_prompt_showdirtystate` for that repository.

**Comment by peey** [comment]
@zanchey I don't think that works when `__fish_git_prompt_show_informative_status` is available. 

Nevertheless, erasing it for particular directories works for now. It's not scalable yet, I could probably automate it to disable it and remember the directory when prompt takes more than 5 seconds to appear, but that's for another time.

Thanks @faho!

**Comment by faho** [comment]
>I don't think that works when __fish_git_prompt_show_informative_status is available.

You know what?

It should.

Not only $__fish_git_prompt_showdirtystate (darn these names are unwieldy), but more importantly the git configuration.

Because git has this nice configuration system that does per-repo overrides of global settings, so you can enable "bash.showDirtyState" by default, and then disable it for a specific repo. And since `git config` is really fast, asking for these isn't much of a problem. Plus we already do that if you don't have informative status set.

So I'm reopening this, so that we can react to the repo's settings, which is much nicer than mucking about with regexes.
