### ISSUE TITLE
eval double expands variables

### ISSUE THREAD

**Issue by simotek** [fish-shell/fish-shell#5565]
In fish 3.0 eval now double expands variables rather then single expanding them.

New Behavior: 
```
simon@tek-top ~> set -l X echo hello
simon@tek-top ~> eval $X
hello
simon@tek-top ~> set -l Y \$X
simon@tek-top ~> echo $Y
$X
simon@tek-top ~> eval $Y
hello
```

Expected behavior:
```
simon@tek-top ~> eval $Y
echo hello
```

I am trying to expand environment variables exactly once, so that I can read in something like `$PATH /sbin /usr/sbin` and expand it accordingly, as a work around calling `eval echo $Y` works but is this the intended behavior?

**Comment by ridiculousfish** [comment]
This is behaving correctly. `eval $Y` undergoes variable expansion to become effectively `eval '$X'`.  Then `eval` evaluates the string `$X` which expands it again.

In fish 2.7, `eval $Y` would be an error because variables cannot be used as commands. In 3.0 they can be used as commands which is why this no longer errors.

It looks like you're interested in expanding a string, not executing it. If you have a variable `Y` whose value is `$X`, and you want to expand Y two times, `eval echo $Y` looks OK to me. Let me know if you need more details.

Thanks for filing!

**Comment by simotek** [comment]
`eval echo $Y` is ok except for hitting issues with terminal escape sequences in eval, so if there is another way that isn't likely to hit https://github.com/fish-shell/fish-shell/issues/5568 that would be useful.

**Comment by ridiculousfish** [comment]
If you want to avoid terminal escape sequences, probably `tr` to replace \x1d is sufficient. However if you have terminal escape sequences in $PATH you may have bigger issues :)
