### ISSUE TITLE
math: Error: Missing operator, set_color: Unknown color with 3.0.0

### ISSUE THREAD

**Issue by rifuso** [fish-shell/fish-shell#5587]
When I upraded from 2.7.1 to 3.0 (via homebrew on mac 10.13.6) I got these errors the next time I started up Fish:

```
><> ><(((^> OH_MY_FISH Loaded! <^)))>< <><
math: Error: Missing operator
'140.6 > 144'
       ^
math: Error: Missing operator
'236.6 > 144'
       ^
math: Error: Missing operator
'44.6 > 144'
      ^
set_color: Unknown color '72.612.6D2.6'
set_color: Unknown color '72.612.6D2.6'
```

I had to do brew switch fish 2.7.1 to go back to the working version.

**Comment by faho** [comment]
You need to upgrade your OMF plugins.

The new `math` builtin in 3.0 does not support comparisons. `test` can now do floats, though.

**Comment by rifuso** [comment]
Thanks for the suggestion, faho. I upgraded the plugins and I still get the same errors.

I don't know what the fish-spec plugin does but that seems to be the only one aside from OMF:

Plugins
fish-spec	omf

I updated everything, but still get the errors.

**Comment by faho** [comment]
> fish-spec omf

omf itself doesn't have these kinds of uses, and I can't find fish-spec anywhere anymore. So maybe it's been dropped?

I suggest you try removing fish-spec.

**Comment by faho** [comment]
Ah, okay, apparently it's [part of OMF](https://github.com/oh-my-fish/oh-my-fish/tree/master/pkg/fish-spec). And it doesn't have these kinds of uses, so you hae something somewhere else.

Do `grep "math.*>" -r ~/.config/fish` to find the offending use and remove it.

**Comment by rifuso** [comment]
Thanks faho! That was a great suggestion. I ended up finding the problem in .local/share/omf in the fish_prompt.fish file of the theme that I had installed: pastfish, which hasn't been updated in a number of years.

https://github.com/pastleo/theme-PastFish/blob/master/fish_prompt.fish

Besides replacing "math" with "test", is there something else I can do to make this file work with Fish 3.0?  It looks like the $color variable in that file is no longer being set.

**Comment by faho** [comment]
>Besides replacing "math" with "test", is there something else I can do to make this file work with Fish 3.0? 

There are _three_ things that need to be changed:

- The math comparison - instead of `  if math "$argv[1] > $argv[2]" > /dev/null`, use `    if test "$argv[1]" -gt "$argv[2]"`

- Math now does float by default, so the `set minToday (math` line needs to have `set minToday (math -s0`, or the final colors will end up with a component after the "." (most likely). The other lines are purely addition and modulo, so they won't cause a non-integer component to appear.

- The `^/dev/null` redirection for `git` needs to be `2>/dev/null` instead - we deprecated that syntax, and you can already disable it via a feature flag.

Otherwise it seems to work. It still invokes `bc` a bunch which fish doesn't actually need any more, but I don't quite understand the math involved, so I'm not rewriting that.

**Comment by rifuso** [comment]
faho, I made the change and it's running without errors now. Thanks so much for taking the time to help me out!
