### ISSUE TITLE
How can I use wpgtk with fish?

### ISSUE THREAD

**Issue by harrisonthorne** [fish-shell/fish-shell#5601]
**Fish version: ** 3.0.0
**OS and Terminal: ** Arch Linux 4.20.4-arch1-1-ARCH, xterm-256color (Alacritty)

okay i don't know if the information above really matters (nor do i know where else to ask this question), but I've been having problems getting [wpgtk](https://github.com/deviantfero/wpgtk) working with fish. But I love fish.

wpgtk requires the following to be ran with bash to change colors: `(wpg -t &)` but with fish, the parentheses don't work like they do in bash. `wpg -t` works to change the colors, but wpgtk's color output is printed to stdout through fish. This is noticeable when I'm working in Neovim and execute a shell command (`:! echo "Hello world!"` for example). This is why wpgtk requires the parentheses when using bash so that output isn't printed through the shell.

`wpg -t > /dev/null` when run won't change the colors of the terminal.

How do I get the right results in fish? (Terminal colors change, but color garbage isn't printed in programs like Neovim)

**Comment by zanchey** [comment]
The output of `wpg -t` might be helpful so that we can see what the input is.

**Comment by harrisonthorne** [comment]
When run in the shell, `wpg -t` doesn't print anything (so it probably isn't stdout? forgive me if i was wrong, maybe just ignore that)

But when run in nvim, i get this (brace yourself):

```
^[]4;0;#100603^[\^[]4;1;#D7522D^[\^[]4;2;#C1683F^[\^[]4;3;#D4954A^[\^[]4;4;#74748F^[\^[]4;5;#C8ACA3^[\^[]4;6;#CFD2D6^[\^[]4;7;#e4e7e9^[\^[]4;8;#331107^[\^[]4;9;#ff6129^[\^[]4;10;#ff8141^[\^[]4;11;#ffc34d^[\^[]4;12;#8686ca^[\^[]4;13;#ffd3bc^[\^[]4;14;#e1faff^[\^[]4;15;#fc
ffff^[\^[]10;#fcffff^[\^[]11;[90]#100603^[\^[]12;#fcffff^[\^[]13;#fcffff^[\^[]17;#fcffff^[\^[]19;#100603^[\^[]4;232;#100603^[\^[]4;256;#fcffff^[\^[]708;[90]#100603^[\
```

**Comment by faho** [comment]
>wpg -t doesn't print anything

Oh, no, it does, just nothing _visible_.

So, what `wpg -t` does is print escape sequences to tell the terminal to switch its palette.

These escape sequences need to go to the terminal, not your editor or something else.

If you run `:!wpg -t` in nvim, what that does is run the command, read its output, and put that into its buffer. It then displays the contents of that buffer in an escaped manner, so they won't reach your terminal in a way that it still interprets. They'll reach your eyeballs, though.

>wpg -t > /dev/null when run won't change the colors of the terminal.

That means that `wpg -t`'s output is thrown away instead of sent to the terminal, so obviously it won't reach it, so it won't change the color.

>wpgtk requires the following to be ran with bash to change colors: (wpg -t &)

Where did you get that from? I can't find it in the documentation.

That code means to run `wpg -t` in the background, inside a subshell. A subshell is a bit of an isolated environment where changes don't apply to the parent, so you can e.g. `(cd somewhere; doathing)` and the working directory outside won't have changed.

>This is why wpgtk requires the parentheses when using bash so that output isn't printed through the shell.

I'm not quite sure how the output here should be different. If you run `wpg -t` directly in bash, it should just work. Output normally goes to the terminal, and the backgrounding seems to be a bit of a micro-optimisation (unless `wpg -t` keeps running for reasons I don't quite understand).

-----

What I'd love to know is a bit more context:

- How do you run `wpgtk`? Inside nvim? Outside of it?

- Does it work in bash, or did you just assume it does? (It's possible your terminal doesn't support palette switching!)

- How do you know that it doesn't work? Just that the colors remain the same?

One possibility for instance is that fish uses RGB-colors instead of the palette colors if it detects that your terminal supports it. So the colors we print won't go through the palette, so changing the palette won't change them.

Try `set fish_term24bit 0`.

**Comment by faho** [comment]
>I have wpg -t at the very top of my fish config file (to apply wpgtk colors when a new terminal is opened; no ampersand needed), so that seems to be why I'm getting the escape code color garbage with every shell command I do in nvim.

Ah, okay.

Fish executes config.fish for _every_ shell, while bash only sources .bashrc for interactive ones.

So you need to guard `wpg -t` with `status is-interactive`, like so:

```fish
if status is-interactie
   wpg -t
end
```

**Comment by harrisonthorne** [comment]
Yes!! You have no idea how happy this makes me. Thank you for the help.
