### ISSUE TITLE
funced doesn't work if $EDITOR is more than a single word

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#5625]
My `$EDITOR` variable is a full job, not just a single word. This works in most contexts, but `funced` doesn't seem to support this.

```
> echo $EDITOR
mvim -f -c "au VimLeave * !open -a Terminal"
> funced foo
fish: Unknown command ''mvim -f -c "au VimLeave * !open -a Terminal"''
/usr/local/share/fish/functions/funced.fish (line 97): 
        if not $editor $tmpname
               ^
in function 'funced'
	called on standard input
	with parameter list 'foo'

Editor exited but the function was not modified
```

fish, version 3.0.0-21-g742fde0d

**Comment by lilyball** [comment]
I'm pretty sure this used to work. I'm guessing it broke when `funced` learned the `-s` flag.

**Comment by faho** [comment]
This works if you set $EDITOR as a list - `set EDITOR nvim -f -c "au VimLeave * !open -a Terminal"` should work.

The reason is that we now use the variable-as-a-command (`if not $editor`) instead of `eval`, which would of course expand the input again.

I feel like that's the right choice, especially since:

- This allows the same $EDITOR to work on the commandline - `$EDITOR $file` works

- This allows it to work with $EDITORs with weird characters - here your $EDITOR has a `*` in it. Previously we would have globbed that.

**Comment by lilyball** [comment]
This new approach doesn't work given that one of the parameters has spaces in it. It would not have globbed the `*` because it was part of a double-quoted string.

Using a list will work for fishscript, but this is a variable that's exported to the environment, and it appears fish's approach towards exporting arbitrary list variables to the environment is to space-separate them. So if I convert my `EDITOR` into a list, it will work for `funced`, but will fail horribly if I invoke any command that itself uses `EDITOR` (such as `git commit`).

**Comment by floam** [comment]
I'm not sure this isn't a bug.

**Comment by faho** [comment]
>This new approach doesn't work given that one of the parameters has spaces in it.

That one parameter then needs to be one element.

>It would not have globbed the `*` because it was part of a double-quoted string.

Ah, that's right.

>Using a list will work for fishscript, but this is a variable that's exported to the environment, and it appears fish's approach towards exporting arbitrary list variables to the environment is to space-separate them.

Yes.

>will fail horribly if I invoke any command that itself uses `EDITOR` (such as `git commit`).

Because that last argument would then be split? Yikes. That's unfortunate.

Does git actually handle the quotes here? Because e.g. bash wouldn't. With your current $EDITOR, try `$EDITOR somefile` in bash. It'll split wrong, keep the quotes and perform the glob.

>I'm not sure this isn't a bug.

Not really. It's a trade-off.

**Comment by lilyball** [comment]
I’ve been using this EDITOR for years. Every tool that uses it, either handles it correctly, or fails because it expects EDITOR to be a single command it can exec instead of pass to a shell. I’ve never seen a case where it interprets the multi-word EDITOR but splits the quoted string on spaces. I’m not at my computer right now so I can’t explicitly test bash, but git definitely handles this correctly.

FWIW most programs handle this correctly.

**Comment by lilyball** [comment]
I’d say this is definitively a bug. The primary use-case of EDITOR is as an environment variable, not a shell variable. The current approach makes it impossible to use EDITOR correctly when an argument contains spaces or shell-special variables.

**Comment by floam** [comment]
> Not really. It's a trade-off.

I think if `$EDITOR` ran as a command can't just work, `funced` and the rest of our scripts simply need to do whatever they need to do to treat it like every other piece of software does, or it's a bug, because it's not working right.

**Comment by faho** [comment]
I still disagree, but it's probably not worth fighting over.

8e60ebcd3 restores the previous behavior.
