### ISSUE TITLE
complete --wraps can cause a background thread to burn CPU

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5638]
I happened upon a fish process using "300%" CPU that was still interactive, when working on the `alias` script, which sets `--wraps` on functions it creates, and this is a reduced test-case:

```
~ $ complete -c a --wraps "a (b)"
~ $ complete -c a --wraps "a (b) "
~ $ a<TAB>
```

A thread is going nuts trying to walk the wrap chain.

[sample.log](https://github.com/fish-shell/fish-shell/files/2849394/sample.log)

**Comment by ridiculousfish** [comment]
Sounds like #5541

**Comment by faho** [comment]
He... "sudo -s -s -E"".

As reported by @SamHH in #5646, `alias sudo="sudo -s"` also exhibits something like this.

And the underlying cause should be fairly similar - `sudo` is a wrapper for `sudo -s`, only those completions call `complete -C`. This gets around our depth restrictions - because this is an entirely different `complete` call, the counter starts again at 0.

Similarly, in @floam's example you need _both_ wrap calls. So I'd imagine one wraps the other, so it ping-pongs from one to the other and back again.

**Comment by ridiculousfish** [comment]
I think there may still be some exotic hangs for completions that themselves invoke `complete` but this fix should address the problem in practice.

**Comment by zanchey** [comment]
I elected not to mention this in the release notes, though happy to take comments otherwise.
