### ISSUE TITLE
PWD not updated properly

### ISSUE THREAD

**Issue by foonathan** [fish-shell/fish-shell#5647]
Executing the following command:

```
env -C /tmp fish -c 'echo $PWD'
```

With fish version 3.0.0 this prints `/tmp`, as expected.

With fish version 3.0.1 this prints `/home/foonathan`, which is incorrect.
The same is true when disabling third-party customizations. I'm using Arch Linux and the behavior can be reproduced on all kinds of terminals.

**Comment by faho** [comment]
@ridiculousfish: I'm assuming dfa61926e8f48a012872873e8b889c02401d898e trusts $PWD, without checking that it actually represents the working directory correctly?

**Comment by heppu** [comment]
Any update on this one?

**Comment by ridiculousfish** [comment]
Ok a timeline:

In fish 2.x, `$PWD` was always derived from `getcwd()`. This is the "always resolves symlinks" behavior.

In fish 3.0.0, $PWD was separate from `getcwd()` except a bug made fish discard PWD at launch. So the (accidental) behavior was "fish resolves symlinks at launch".

In fish 3.0.1 that bug was fixed, so $PWD is $PWD, and the working directory is the working directory, and fish makes no attempt to second-guess either.

In the command: `env -C /tmp fish -c 'echo $PWD'` what happens is that `env` sets the `$PWD` environment variable, and does NOT change the current working directory. So fish inherits a $PWD and a cwd that disagree.

fish is fine with this disagreement, while other shells apparently try to fix it, but only at launch. 

It seems like what is desired it "allow PWD and cwd to disagree, except at launch, where we retain PWD only if it can be resolved to the cwd". If this `env -c PWD` thing is a common pattern then I suppose fish should implement that too.

**Comment by Maxr1998** [comment]
I came to this issue because I had this bug in the terminal of all JetBrains IDEs, including Android Studio, as well as in VSCode - while `pwd`/`$PWD`, and thus, the prompt were shown as my user home, `ls` correctly showed the contents of my project dir.

So, I guess this pattern is common enough to warrant implementing a workaround in fish as well.

**Comment by hauleth** [comment]
This breaks almost all terminals nested in the editors. Vim and NeoVim are affected as well.

**Comment by SamHH** [comment]
This also breaks at least two commonly used terminals (Alacritty, Termite) when supplying a current working directory option.

**Comment by AlekSi** [comment]
Same problem with VSCode. Is there any workaround?

**Comment by ridiculousfish** [comment]
I think we need to do a 3.0.2 perhaps for this fix alone.

**Comment by ridiculousfish** [comment]
Anyone experiencing this, I would appreciate testing on Integration_3.0.2 (commit 5c994b0d474424057c7d36065c56e56066e0e0d4).

**Comment by hauleth** [comment]
Workaround for NeoVim (do not work in Vim as it has no `DirChanged` event):

```viml
augroup workaround_fish_issue
    autocmd!
    autocmd DirChanged * let $PWD = v:event.cwd
augroup END
```

**Comment by jorng** [comment]
Just built `Integration_3.0.2` branch on macOS, and it seems to be resolved.

```
fish, version 3.0.1-1-g5c994b0d
```

**Comment by Maxr1998** [comment]
@ridiculousfish built via `aur/fish-git`, and I can confirm it works fine in Android Studio.
