### ISSUE TITLE
add function scope option to the `set` command

### ISSUE THREAD

**Issue by xiaq** [fish-shell/fish-shell#565]
Doc of `set` builtin says:

> The scoping rules when creating or updating a variable are:
> 1. If a variable is explicitly set to either universal, global or local, that setting will be honored. If a variable of the same name exists in a different scope, that variable will not be changed.
> 2. If a variable is not explicitly set to be either universal, global or local, but has been previously defined, the previous variable scope is used.
> 3. If a variable is not explicitly set to be either universal, global or local and has never before been defined, the variable will be local to the currently executing function. Note that this is different from using the -l or –local flag. If one of those flags is used, the variable will be local to the most inner currently executing block, while without these the variable will be local to the function. If no function is executing, the variable will be global.

The upside is that well-known global variables (`$PATH`, `$EDITOR`, etc.) can be set within functions without an explicit `-g`. However, the behavior of the following function can be confusing:

```
function f
    set var val
end
```

If the user has a global variable named `var`, this function alters the global environment. Otherwise it has no impact on global environment. To make the function safe one has to always write

```
function f
    set -l var val
end
```

which is quite tedious. Therefore I propose that `set` should always imply function scope within functions.

**Comment by alphapapa** [comment]
I'm converting another Bash script to Fish, and ran into this.  I used `set -l` in a function, and I expected it to define the variable in the function's scope.  But the `set -l` was also inside a `while` loop, so it actually defined it locally to that loop.

This is very confusing.  I'm no expert, but I can't think of any other languages that have block- or loop-local variables (that are defined inside the loop, I mean; of course there is e.g. `for (( i=1; i<=steps; i++ ))`.

This is so unusual that I think it should be considered a bug and changed.  Defining a variable with `-l` inside a function should use the function's scope.  If the block-local behavior is desired, there should be a separate switch for that.

**Comment by martin-g** [comment]
Java/Scala has block level variables. JavaScript/ES2015 (aka ES6/Harmony) also supports them with `let someVar = someValue`.

**Comment by alphapapa** [comment]
Ok.  And sure, there are lisps with things like `(let ...`.  But I think it is very unusual for a shell scripting language to behave this way.  I don't think it's worth the extra confusion (and the resulting bugs).  The unusual behavior should be enabled by a separate option.

**Comment by ridiculousfish** [comment]
Note that the default behavior of `set` is function scoped. You have to opt in to block scoping with `-l`

**Comment by alphapapa** [comment]
Hm, I didn't realize that.  That's another way that Fish somewhat confusingly differs from Bash:
```sh
#!/bin/bash

function foo {
    bar=baz
}

echo $bar
foo
echo $bar
```
```fish
#!/usr/bin/env fish

function foo
    set bar baz
end

echo $bar
foo
echo $bar
```
I'm sure you've given all this much more thought than I have, and I'm late to the party, I know--but I just wonder if these subtle-yet-significant differences are worth it.  It seems like every time I convert a little Bash script to Fish, I run into some of these gotchas, and I'm not sure how the differences help me.  :)

**Comment by faho** [comment]
>Hm, I didn't realize that. That's another way that Fish somewhat confusingly differs from Bash:

For those reading along at home, that code prints "" and "baz" for bash and "" and "" for fish. Essentially, both allow for a few different levels of scoping (global and local at least), only bash is global by default (change the assignment to `local bar=baz` to get local).

And quite frankly, basically every other programming language behaves like fish does, and the only advantage bash has is familiarity. But if we'd see familiarity as important, we wouldn't be doing fish.

Now, there's a few things to change here - I'd argue for a switch to `set` to force function-level scope, since now code like this:

```fish
function foo
   if true
     set bar bie
   else
     set bar drink
   end
  echo $bar
end
```

can't help but change the global variable bar if it is defined. This _needs_ an additional `set -l bar` before the `if`, and it's ugly and a real stumbling block.

Either that or abolish block-level scope or always shadow variables (which seems overly restrictive) or make "capturing" global variables explicit.

**Comment by alphapapa** [comment]
Thanks for clarifying; I should have listed the output myself.  :)

> And quite frankly, basically every other programming language behaves like fish does, and the only advantage bash has is familiarity. But if we'd see familiarity as important, we wouldn't be doing fish.

Well, for "programming" languages you're probably right, but for shell scripting, I think the opposite is true.  For example, not only Bash behaves that way, but POSIX sh does, as well as zsh.  So that behavior isn't just a Bashism--it's the standard behavior for shell scripting.

Now, as you said, that doesn't necessarily mean Fish should do so as well.  However, in this case, I think that Fish should follow their example.  

My reasoning is this: For major, obvious differences in syntax (like using `end` instead of `fi/done/esac/}`, using `set var (command)` instead of `var=$(command)`), a new user can't help but be aware of it.  If you get it wrong, the script will probably give an error as soon as you try to run it.  But for variable scoping and other more subtle issues, the difference is not immediately obvious; and even if someone reads about it, it's likely he'll forget about it until he experiences the difference by falling back on old habits and causing a bug.

Now I may be wrong.  :)  And if someone can show me an example of why the way Fish currently does scoping is actually beneficial and outweighs the benefit of familiarity, I'd be glad.  But so far, I see this current behavior as more of a problem than a benefit.

I agree with you that `set -l` should behave as Bash `local` does and define a variable local to function scope.  That would be more consistent and intuitive.  And then, a `set -b` for block-local scope would complement it nicely, similar to a `let` in lisps, but by being explicit it would avoid causing unintended bugs, especially for new Fish users.

I would argue against making capturing global variables explicit, because I think one of the benefits of shell scripting--especially Fish--is that it's lightweight and less verbose than "real" programming languages.  For me, I have a different mental mode when doing shell scripting, and I'm used to functions having access to global scope, even though I try to avoid doing that when possible as a best practice.  I think that most people who are familiar with shell scripting expect functions to have access to global scope implicitly, and I think that this is one of the kinds of behavior that Fish should emulate rather than redefine.

Thanks for all the great discussion and your work on Fish!  :)

**Comment by faho** [comment]
>Now I may be wrong. :) And if someone can show me an example of why the way Fish currently does scoping is actually beneficial and outweighs the benefit of familiarity, I'd be glad. But so far, I see this current behavior as more of a problem than a benefit.

Basically, it all goes back to "structured programming" from the seventies (you know, the "GOTO considered harmful" crowd, Dijkstra et al). If variables are global by default, people will use tons of global variables. And global variables are like "spaghetti code", except regarding data and not code flow. If you use them, it can be hard to see where the data stored in them comes from, especially when you're using functions written by other people - if they happen to have a global variable of the same name as one of yours (or, and this I think is a real problem, one of you does `set VAR` on a variable the other declared global to try to get function-level scope), unrelated functions change your data.

This is one of those things that should never have been that way in bash/sh to begin with (like word-splitting), and fish has the opportunity to change it. I think it should, even if at the expense of a bit more unfamiliarity.

>I agree with you that set -l should behave as Bash local does and define a variable local to function scope. That would be more consistent and intuitive.

That might cause some breakage in existing fish code and would need a flag-day transition. That's why I advocated for a "switch" to `set` (though my wording wasn't great). Keep `set` as-is - either create a new variable with function-level scope or set the existing variable and keep the scope - and add a "-f" option to force function-level scope, shadowing other variables by the same name if necessary.

>Thanks for all the great discussion and your work on Fish! :)

I believe the canonical way to express that is "So long and thanks for all the Fish!" :smile:.

**Comment by chamini2** [comment]
Completely agree with @faho, there should be a `-f` option to specify a var as function scoped. As I said in #3323

> ... it makes sense to me that if there's a **default** scoping style, it should be also offered as an option in the flags. It seems weird that we get half the behaviour: looking for vars in each scope and if none were found create a new one scoped to the function; this introduces the idea of _"function scoped variables"_ but then doesn't allow for fully using that scoping style through a flag.

Would a PR for this flag be accepted?

**Comment by alphapapa** [comment]
I agree with @chamini2 about this:

> It seems weird that we get half the behaviour: looking for vars in each scope and if none were found create a new one scoped to the function;

This is a strange inconsistency: for `set` to implicitly set a variable in global scope, but only if that variable is already defined--otherwise it sets block-local scope.  It would be much better if it were consistent and always followed the same behavior by default, requiring a flag to change it.  

This is the kind of behavior that can lead to bugs that are very hard to find, because since it depends on global state (which tends to be "invisible" when coding and debugging), it's hard to reproduce in a test case unless you already know what the problem is--and then why would you need a test case?  :)

Anyway, here's what I'm thinking right now.  The question seems to be about variables' default scope: should it be block-local or function-local?  My vote is for function-local by default, with something like `set -b` for explicit block-local scope.  When called outside of a function, `set` should be global by default.  Inside a function, `set -g` should be required to set global scope.  

Then there's the matter of setting a variable within a function that is already a global variable: if `set` is used without `-g`, should the existing global variable be set, or should a function-local variable be set?  I'm going to go out on a bit of a limb here and say that I think Fish should disallow this: if a user tries to set a variable inside a function that has the name of an existing global variable, Fish should throw an error.  The user should use a different name for the function-local variable.  The reason is to avoid a situation like this:

```fish
function fry
  echo "Frying thing: $thing"
  set thing "$thing fries"
end

set thing potato
fry
echo "Now it's $thing"
```

Now does `fry` change the value of the global `thing` or does it set a function-local `thing`, in which case the last line of the script would print "Now it's potato" instead of "Now it's potato fries"?  I think the best thing to do here would be to force the user to be explicit by calling `set -g` inside the function, and throw an error if a bare `set` is used, since `thing` is already a global variable.

Accessing variables inside a function is another issue.  Shadowing global scope by default seems to make sense since it is consistent with other shell scripting.  Another option would be to explicitly capture or shadow global variables from within a function, but that seems cumbersome to me; if I'm writing a shell script, it's because I don't want to have the rigor of a "real" programming language.  :)

**Comment by alphapapa** [comment]
Ugh, I just got bitten by this *again* when converting a Bash script to Fish:
```fish
function convert_time_to_seconds
    set -l times $argv
    set -l fields (echo $times | tr ' ' '\n' | tr ':' ' ')

    switch (count $fields)
        case 2
            set -l hours 0
            set -l minutes $fields[1]
            set -l seconds $fields[2]
        case 3
            set -l hours $fields[1]
            set -l minutes $fields[2]
            set -l seconds $fields[3]
        case '*'
            die "Weird time from MPC:$times  Fields:$fields  Numfields:"(count $fields)
    end

    # Remove leading 0 from fields
    for field in hours minutes seconds
        echo "DEBUG: FIELD:$field VALUE:$$field"
        set -l $$field (echo $$field | sed -r 's/^0//')
    end

    echo (math "($hours * 60 * 60) + ($minutes * 60) + $seconds")
end
```

The error:
```
DEBUG: FIELD:minutes VALUE:2 18
in command substitution
        called on line 15 of file ~/.bin/wct.functions.fish

in function “convert_time_to_seconds”
        called on standard input
        with parameter list “1:21 3:53”

set: Variable name can not be the empty string
~/.bin/wct.functions.fish (line 36):         set -l $$field (echo $$field | sed -r 's/^0//')
```
It was non-obvious how the variable name could have been the empty string, since in the `DEBUG` line, `$$field` was not empty!

After several minutes it hit me that the `set -l` statements in the `switch` were scoping to *only within the `switch` block*.

So to fix this, I first have to put this above the `switch`:
```fish
set -l hours
set -l minutes
set -l seconds
```
Then I can use plain `set` in the `switch` and get function-local scoping.

This is incredibly counter-intuitive.  It really needs to be fixed.

**Comment by ridiculousfish** [comment]
Thanks for the great write-ups @alphapapa 

The existing default behavior where `set` modifies a global if one exists, otherwise it introduces a new function-scoped variable, is definitely problematic. Changing this default is difficult since it has compatibility implications. However introducing a new flag for function-scoped variables seems like something we all agree on.

**Comment by faho** [comment]
From @krader1961 in #3465:

>>make it so set -f behaves like set -l outside of a function

>I'm ambivalent. I agree that throwing errors is not friendly. On the other hand letting people shoot themselves in the foot is also not friendly. The -l and -g flags have well defined, fairly obvious, meanings outside of a function block. The same is not true for -f. Also, what does it mean to do set -qf outside of a function? Will it return all locally scoped vars? And if so then it's not consistent with the behavior we expect inside a function. And if not then why would should set -f be equivalent to set -l outside of a function body?

These are tough questions because they have subtle implications.

So let's first try to answer the behavior inside of a function.

The main issue for me there is that `set -f` inside of a function _is_ the same as `set -l` unless you are also inside of a block. I.e.

```fish
function banana
    set -l flounder 0
    set -f arglebargle 1
end
```

Here $flounder and $arglebargle have _exactly the same_ visibility. It's only when you do

```fish
function apple
    if true
        set -f haberdashery 2
        set -l humpty 3
     end
    # $humpty won't be defined here anymore
end
```

The question here is how much we want "function-scope" to be its own thing, versus just a shortcut for another scope.

- Do local variables shadow function ones?

They probably should, so you can do easy temporary variables. Also, it's _already_ what happens:

```fish
function a
    set -l a 1
    if true
       set -l a 0
       echo $a # will output 0
    end
    echo $a # will output 1
end
```

- Do function variables count as local ones?

This is obviously a new thing because we don't currently have a way to query for function-scope.

To me the answer is no, because if you had a function var and defined a local one, it would _shadow_, not overwrite it. Because it is effectively its own scope, it should really count as that.

I've said before that a `set -qfl` might be nice here, to see if a variable is defined either in local _or_ function scope.

With that in mind, let's try to tackle the behavior outside of a function:

>The -l and -g flags have well defined, fairly obvious, meanings outside of a function block.

True.

>The same is not true for -f.

Let's make one up, then. As we've seen above, we'd effectively understand function scope to be "a scope above the highest local scope up to a function". The only "change" needed here is that that function does not need to exist. So "function scope" outside of a function would be the highest local scope. It would shadow global and universal, and be shadowed by any local vars. So if you did

```fish
if true
   set -f samovar 1
end
echo $samovar
```

it would output 1. Which seems kind of useful.

>Also, what does it mean to do set -qf outside of a function? Will it return all locally scoped vars?

Like inside of functions, it would only return true for variables defined with `set -f`, since they could be shadowed by locally scoped ones.

>And if so then it's not consistent with the behavior we expect inside a function.

I believe it would be.

>And if not then why would should set -f be equivalent to set -l outside of a function body?

That's the trick - it wouldn't be.


------


Now of course there's some weirdness here, since

```fish
set -l fruit banana
if true
    set -f fruit orange
end
echo $fruit
```

would print "banana".

Personally, I can't think of any way to make it more consistent.

Does that make sense?

**Comment by chamini2** [comment]
I have no objections to @faho's proposal, makes sense to me. So we would be creating a new scope instead of the having an alias for a local scope.

Since with @faho's proposal this scope would be included outside of a function too, maybe the name of the scope should not be `function scope` but `outer scope` (_bike-shedding_, I know); apart from that, seems a good solution.

**Comment by ridiculousfish** [comment]
Thanks for the great and detailed proposal faho. Also see 7b12fd26 for a relevant commit. This introduced the "top level local scope."

> Let's make one up, then. As we've seen above, we'd effectively understand function scope to be "a scope above the highest local scope up to a function". The only "change" needed here is that that function does not need to exist. So "function scope" outside of a function would be the highest local scope. It would shadow global and universal, and be shadowed by any local vars

I wonder about the behavior of unadorned (no-scope-specified) `set`. Today it first attempts to modify an in-scope existing variable, then if it does not exist, introduces a new variable in function scope, or global scope if not in a function. This global scope behavior is very useful, since it allows users to directly set variables without worrying about scope, e.g. by typing `set -x LD_LIBRARY_PATH ~/libs` and this will be global.

A new "top level function scope" would force us to qualify this further: unadorned `set` introduces a new variable in the nearest function scope, except for the top level one. However maybe this isn't so bad if nobody will encounter it: users may never know the top level function scope exists.  

Is there any good reason to run `set -f` at top level? I can't think of any. With that in mind perhaps it's better to make `set -f` error at top level. We wouldn't be preventing any legitimate use cases, and we might be saving the user from themself.

**Comment by chamini2** [comment]
> I wonder about the behavior of unadorned (no-scope-specified) set...

This was the reason this flag is even being discussed, the _unadorned_ `set`
does this scoping rule not achievable through a flag, that's why we are
introducing this one.

> Is there any good reason to run set -f at top level? I can't think of any. With that in mind perhaps it's better to make set -f error at top level. We wouldn't be preventing any legitimate use cases, and we might be saving the user from themself.

This makes sense to me now that I think about it. The docs could say that an _unadorned_ `set` searches an existent variable in all scopes and if none are found, it creates a variable with `-f` option if in a function and with `-g` option otherwise. Keeping `-f` specific for functions.

If we defined a `function scope` outside of functions, it would be a _new_ global scope that sometimes is in functions, adding more complexity to the scoping rules outside of a function, IMHO.

Please give your opinion so we can move forward with this! :)

*****

##### Some examples

In the top level

```bash
set -f a    # error
set -qf     # error
```

In a function

```bash
function f
  set var 0
  if true
    set -f var 1
  end
  echo $var   # 1
end
```

```bash
function f
  set -l var 0
  if true
    set -f var 1
  end
  echo $var   # 0
end
```

```bash
function f
  set -l vl 0
  set -f vf 1
  set -qf     # vf
  set -ql     # vl
end
```

**Comment by ridiculousfish** [comment]
Revisiting this case:

```
function f
    set -l fruit banana
    if true
        set -f fruit orange
    end
    echo $fruit #banana
end
```

Now the first top-level `set -l` looks like a footgun, forever shadowing the function-scoped variable.

If `set -f` only works inside functions, is there any harm in collapsing the function scope with its outermost local scope? So that `set -f` just means the same as `set -l` at top level inside the function.

There's also a question of `--no-scope-shadowing` functions, in particular `eval`. It's annoying today that `eval 'set -l foo bar'` doesn't work (it ends up setting `foo` inside the `eval` function). Here's an opportunity to rectify that.

**Comment by alphapapa** [comment]
> If set -f only works inside functions, is there any harm in collapsing the function scope with its outermost local scope? So that set -f just means the same as set -l at top level inside the function.

IMO it should definitely be collapsed.  Having `set -f` within an `if` within a function *not* set the variable in the function-level scope would be extremely confusing.

And that makes me question the whole notion of `set -f` in the first place.  If `-l` and `-f` both exist, that would imply that code written like this would somehow be sensible:
```fish
function peel_if
    set -f fruit apple
    if test (today) = tuesday
        set -l fruit banana
        if test $fruit = banana
            peel $fruit
        end
    end
end
```
But clearly it's not.  What languages allow shadowing variables within a function's own shadowed scope, other than, e.g. Lisps, which do it explicitly with `let`?  It's a bad idea.  Just use separate variables.

Just like it's a bad idea in most languages to give variables in a `for` loop the same name as variables outside of the loop, it's a bad idea to shadow variables inside control blocks.  They aren't anonymous functions.  

Block-level-scope/shadowing is just asking for trouble.  There should only be two scopes: global and function, so there should only be bare `set` and `set -l`.  At least, I think this should be the long-term goal.
