### ISSUE TITLE
contains: Unknown option '-v/bin'

### ISSUE THREAD

**Issue by Drogglbecher** [fish-shell/fish-shell#5662]
Version: 3.0.1
OS: Darwin 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
Term: screen-256color

When starting fish (even without config) the following issue appears:

```
contains: Unknown option '-v/bin'
/usr/local/Cellar/fish/3.0.1/share/fish/config.fish (line 426):
            if not contains $entry $result
               ^
in function '__fish_macos_set_env'
        called on line 228 of file /usr/local/Cellar/fish/3.0.1/share/fish/config.fish
        with parameter list 'PATH /etc/paths /etc/paths.d'

from sourcing file /usr/local/Cellar/fish/3.0.1/share/fish/config.fish
        called during startup


       contains - test if a word is present in a list

   Synopsis
       contains [OPTIONS] KEY [VALUES...]

contains: Type 'help contains' for related documentation
```

**Comment by faho** [comment]
It seems you have a directory in /etc/paths or $PATH that looks like `-v/bin`.

That's most likely wrong (it's not an absolute path).

Regardless, we should not fail in this manner.

**Comment by faho** [comment]
@Drogglbecher: Hey, it appears this issue has also been hit by another user on Stackoverflow (https://stackoverflow.com/questions/54736560/why-is-fish-3-0-printing-an-error-message-on-start), and that seems a bit unlikely.

Could you tell me if you're using any third-party customization? OMF, fisher, tacklebox, anything? Because it's possible that some tools has a bug that adds bogus $fish_user_paths components, and fixing it there would help its users, since the best we can do is to paper over it by not printing an error.

**Comment by lthibault** [comment]
@faho This is `blz` from stackoverflow.  In case it's relevant:  I am using OMF.  I suspect the issue was caused by `pyenv` in my case, however.

**Comment by Drogglbecher** [comment]
Hey, sry for the late answer but in the end @faho was correct: it was my own fault. Sry for that.

An environment variable ending with `-v` was not expanded correctly, thus the next one I added to `PATH` had the ending `-v/bin` 😔

**Comment by lthibault** [comment]
@Drogglbecher No sweat!  I basically made the same mistake as you 😉
