### ISSUE TITLE
add support for complete yarn command to run script directly

### ISSUE THREAD

**Issue by Austaras** [fish-shell/fish-shell#5674]
currently fish only support for completion for `yarn run <script>`, while `yarn <script>` is not supported

 [relevant yarn document](https://yarnpkg.com/en/docs/cli/#toc-user-defined-scripts)

**Comment by faho** [comment]
So... this would be a simple addition, I'm just not sure if it wouldn't then offer too many options? One goal of completions is to point people towards what they want to do, and sometimes that means not offering superfluous stuff.

How many <script>s are there in a typical project?

**Comment by Austaras** [comment]
That makes sense though.A small project will have maybe 3 scripts (build serve test) or some more(lint etc. etc.),and [complex project](https://github.com/angular/angular/blob/master/package.json) may have 10+ scripts 
But I believe user can handle them using by typing first few chars and letting fish to complete the rest?

**Comment by faho** [comment]
>[complex project](https://github.com/angular/angular/blob/master/package.json) may have 10+ scripts

Yeah, that'll work.

> But I believe user can handle them using by typing first few chars and letting fish to complete the rest?

Let me explain why I think that we should sometimes not offer absolutely everything: Let's say you use the completion to see what this `yarn` thing can do, and then you get hundreds of badly-described (because we can only autogenerate that) unimportant things.

That would be the case e.g. if you use `make <TAB>`. It'll give you hundreds of source files because technically every "src/thing.o" is a target. So it's hard to see that `test` or `dist` is there, and those are the actual important "real" targets. So if `make file=thing` existed, we would only offer that. It's about signal/noise ratio. (Unfortunately for `make` we can't)

In `yarn`s case, `yarn run ` is available if you want to run a script, so it would be enough to complete scripts for that (and in fact I think it's a bad feature to allow them without `run` as well - if I were a yarn author, I would not  have added it!).

However, if a complicated project only has 10 or so of these, then it's not much of an issue. It's also probable that these scripts are more important and useful than make's autogenerated garbage targets.

So let's add it!

**Comment by Austaras** [comment]
Thanks for detailed explanation!
