### ISSUE TITLE
Allow `switch` with zero arguments

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5677]
I think one should be able to `switch` on a variable that may or may not be set:

```fish
switch $LANG
    case 'en_US*'
...
end
```

If `$LANG` is unset:

`fish: switch: Expected exactly one argument, got 0`

(Same with command substitutions which may sometimes print nothing.)

I think it should just silently short circuit and do nothing.

**Comment by floam** [comment]
It will work if the string is quoted. The command substitution situation might be a better example.

**Comment by floam** [comment]
Here's an example of a user being bitten:

from [`__fish_complete_mount_opts.fish`](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_complete_mount_opts.fish#L146):
```fish
    switch (string replace -r '=.*' '=' -- $last_arg)
        case uid=
            set -a fish_mount_opts uid=(__fish_print_user_ids)
        case gid=
            set -a fish_mount_opts gid=(__fish_print_group_ids)
        case setuid=
            set -a fish_mount_opts setuid=(__fish_print_user_ids)
        case setgid=
            set -a fish_mount_opts setgid=(__fish_print_group_ids)
    end
```
When there are no replacements done, this will cause an unexpected error. (`mount -o <TAB>` does it here.)

**Comment by faho** [comment]
>When there are no replacements done, this will cause an unexpected error.

Not the one you're thinking of.

Because this uses `string replace -r` _without_ `-f`/`--filter`. So if no replacement is done to a given argument, it is printed as-is.

That means if `$last_arg` has one element, it'll check it, and because it has no "=" (because otherwise it would have done a replacement) it won't match any case and nothing will happen. Which might or might not be what you want.

If $last_arg is empty, it's equivalent to `switch $last_arg`, and if it has multiple args #3042.

------

Anyway, I agree that `switch` with something that happens to expand to zero arguments shouldn't error. The question is what case it should match. Since an empty quoted list expands to the empty string, it would logically match `case '*'` or `case ''`. But that might make the user think that it's the empty string.

E.g.

```fish
switch $empty
    case ''
       # oh cool, it's the empty string!
       echo banana$empty # prints nothing!
```

An alternative is to not let it match anything. That would be the most consistent, and would allow you to quote it to let it match something.

Then there's the question of what happens to zero arguments - should just

```fish
switch
    case '*'
```

continue to error? Probably yes, but if that prevents us from allowing empty expansions it seems worth it to allow it as well.

----

I actually think whatever we do here isn't backwards-incompatible - we're removing an error, so any code that used this was broken.

**Comment by floam** [comment]
I was thinking maybe, a case with zero arguments?

`case` and `case (false)` does not error.

**Comment by floam** [comment]
Or, if that's just too weird, I think it's also not terrible for no case to match at all, the switch does nothing. Maybe you could pick up on that with `switch ... end; or ...`?

**Comment by ridiculousfish** [comment]
My first reaction is that `case '*'` is sufficient. You wouldn't normally write a switch statement that deliberately matches zero arguments, so it's sufficient to group this into an error handling catch-all glob. If you expect to sometimes get zero arguments it's easy to handle this outside of the switch or inside of the case.

**Comment by mqudsi** [comment]
I'm ok with what @ridiculousfish said so long as switch with zero literal arguments remains a syntax error.

**Comment by faho** [comment]
Yeah, I allowed things that expand to nothing, while keeping `switch ` as a syntax error.
