### ISSUE TITLE
abbr doesn't work when used in fish script

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#5682]
fish, version 3.0.1

For example, I created an abbr `find` to `find -L` which will always follow symbolic links. But I defined another function such as `fa` that will use `find` command, if I defined `find -L` as an abbr, the `fa` will not follow  symbolic links.

But if I change the abbr of `find -L` to `alias`, `fa` function will work like it uses `find -L`.

I defined multiple functions that use `find` command, and there are other situations like this, such as `less` to a long string `less -RM -s +Gg`, I couldn't just change every `less` in my config.fish to `less -RM -s +Gg`.

If abbr and alias work differently in this kind of situation, I have to choose when to use abbr and when to use alias, I read somewhere in the issue page that developers suggested using abbr instead of alias.

So `abbr` only works in typing mode in terminal, not in script? Why not make `abbr` work in script mode too, like alias?

**Comment by faho** [comment]
Abbreviations are just that - abbreviations.

You type them, they expand, they cease to exist.

(We currently execute them without expansion if you execute directly after typing the abbr, without a space or anything. That's wrong. We should be executing what the commandline shows).

**Comment by c02y** [comment]
Why not make abbr more powerful?

If this cannot be done I guess I'll just change all my aliases to functions then.

**Comment by faho** [comment]
>Why not make abbr more powerful?

Because _the point_ is that they don't exist.

You know how some people have these fifty git aliases, like

```fish
alias gs="git status"
alias gl="git log"
alias gc="git commit"
```

?

With aliases, that means that suddenly you have a command called `gl`, and you need to remember what it does, and using it in a script is weird and...

With an abbr, you press `gl`, and `git log` shows up in the terminal. The actual command is still `git log`. You see `git log`, whether you've used the abbr anywhere isn't stored in history, ...

That's what abbrs are for. There's a command you want to use, but you don't want to type all of it.

Functions are more of an encapsulation. There's this function, you call it to do stuff, it does the stuff somehow. They could also be external commands or builtins, conceptually.

Both have a reason to exist, and unifying them makes them _worse_, not better.
