### ISSUE TITLE
split0 always exits with 1

### ISSUE THREAD

**Issue by hyperfekt** [fish-shell/fish-shell#5701]
version: 3.0.1
happens without third-party customizations: yes
regression from fish 2.7.1: does not apply

`echo -n -e "a\x00b" | string split0` correctly splits between a and b, but exits with status code 1 despite having performed a split. This is contrary to the statement in the documentation that if a split was performed, `string split[0]` returns with status code 0.
Compare `echo -n -e "a b" | string split " "`, which correctly exits with 0.

**Comment by faho** [comment]
Yup. The problem is that `split0` already receives the arguments from stdin split on NUL.

We need to add a mode that just soaks up all input from stdin and doesn't split it at all.

**Comment by hyperfekt** [comment]
Out of curiosity: If split0 can't receive a null-separated string as argument, and receives stdin already split on NUL, what other modes are there?

**Comment by faho** [comment]
Splitting on newline, for all other string commands.

builtin_string.cpp has a method "nextstr()" that every string subcommand uses to get "the next argument", whether that's the next line from stdin, or the next argument from argv.

Only that won't work for split0, because that needs to get argv separated as it is, and stdin completely unsplit. And the only difference is the exit code.

**Comment by faho** [comment]
Okay, as it turns out we never split on NUL elsewhere, so I just changed it to not split at all, and then split0 actually does something.
