### ISSUE TITLE
Need more code style guide (text width, use of empty line)

### ISSUE THREAD

**Issue by xiaq** [fish-shell/fish-shell#571]
* Some code wraps lines to limit the text width, some don't.
  * Perhaps adopt the traditional 80-column limit or go a little wider? Either way *some* limit should be set, otherwise we end up with super-long lines like:

 ```
                                  _(L"Variables may not be used as commands. Instead, define a function like 'function %ls; %ls $argv; end'. See the help section for the function command by typing 'help function'."),
```
 * Google C++ Guide says [80-char](http://google-styleguide.googlecode.com/svn/trunk/cppguide.xml#Line_Length), but they also use [2-space indentation](http://google-styleguide.googlecode.com/svn/trunk/cppguide.xml#Spaces_vs._Tabs). Since fish uses 4-space indentation, some bigger value is more sensible.

* The use of empty lines seem inconsistent within the project. I propose the following:
 1. No empty line between comments and what it describes.
 1. No leading or trailing empty lines within a block.
 1. 2 empty lines between two independent top level entities (function declarations/implementations, variable declaration, class declaration, macro definition). When two entities are strongly related, compress that to 1 or 0 (when both entities occupy a single line, like two variable declarations) empty lines.
 1. 1 empty line between two independent entities within class blocks; compress to 0 if two are strongly related.

**Comment by krader1961** [comment]
I strongly endorse the broad terms of @xiaq's proposal if not every specific recommendation. One of the things I learned to value after joining Google was consistency in how the code is formatted. It makes it far easier to read the code without errors of interpretation. It doesn't matter if I, or you, agree on the standard. For example, I dislike Google's two space indent and would prefer four spaces but my preference isn't relevant. All of my changes must use a two space indent. The fact that all of the code adheres to the standard makes it far easier for me, and everyone else in the company, to read it. The fact that there is a published comprehensive standard minimizes arguments about whether or not a change should be accepted as is.

If you are contributing to a project you are encouraged to lobby for changes that improve the project. Including changes to the coding style guide. But you're not free to submit changes in a style you personally prefer that are at odds with the project's established style. One of the things driving me nuts right now as a new contributor to fish is the wildly varying style because it makes it hard to grok the code.

**Comment by ridiculousfish** [comment]
Yes, agreed, as long as the style guide is enforced via an automated tool and not via code reviews. The gofmt model is pretty great. If someone wants to write up a clang-format config or something, and maybe even integrate it into the Makefile so running it is painless, then that would be swell.

**Comment by krader1961** [comment]
I ran all the core code through the astyle command @ridiculousfish mentioned in his comment on 2013-03-05. I was underwhelmed by the improvements it made. Yes, it removed a lot of trailing whitespace and fixed some indentation and internal whitespace issues but missed many others. It still left long lines untouched and generally didn't do a whole lot to improve the consistency and readability of the code. That is, the improvements were mostly superficial.

So I ran a few files through `clang-format` using its builtin Google style but with four space indents. Specifically, I put the following in a *.clang-format* file at the top of the project:

```
BasedOnStyle: Google
IndentWidth: 4
```

Wow! A huge improvement. Granted, I'm biased because that's the style I'm used to (albeit with a two space indent). But consider that *builtin.cpp* went from 4153 to 3471 lines and the resulting information density was much higher without sacrificing readability.

Note that similar to pylint for Python clang-format makes it easy to suppress its behavior where that is needed via `// clang-format off` and `// clang-format on`. Also, I'm not wedded to an 80-column limit and would be willing to bump it to 100, but probably not much more because long lines make it more difficult to perform side-by-side diffs of files unless you have a 30" monitor.

I would really, really, like to apply clang-format with the above options to all the core source. Then add a Makefile target to apply it to any files in the current uncommitted change via something like `make style`. Does anyone have strong feelings about doing so?

I agree with @ridiculousfish's desire that the style rules only be enforced

> as long as the style guide is enforced via an automated tool and not via code reviews

However with respect to C code the one exception might be comments. None of the tools enforce any comment style other than maximum line length. I would prefer the `//` style always be used for comments on a line of code. It should also be used for most block comments documenting the behavior of a function. The older C style `/* ... */` comment block should only be used at the top of a module. I recognize this proposal is likely to be controversial and it is therefore orthogonal to applying clang-format to the existing code to fix all the other inconsistencies.

TBD: What to do with *.fish* files.

**Comment by bucaran** [comment]
For fishfiles I use `fish_indent`. I've pretty much internalized it to the point I think I am a human `fish_indent`, but I still use it to format my code. I find delegating this responsibility to a tool is one of the most relieving things I have started doing recently.

**Comment by ridiculousfish** [comment]
If we are going to reformat, I and anyone else who maintains a branch will need to do some git stuff before and after to keep the branch mergeable. So give us a heads up :)

**Comment by krader1961** [comment]
As for fish scripts the authoritative answer is the `fish_indent` command just as `gofmt` is authoritative for the Go language. That doesn't deal with every style issue (e.g., variable and function naming conventions) but does eliminate squabbling about indentation and line lengths.

**Comment by krader1961** [comment]
Does anyone have a strong opinion regarding C++ source line length limits? The oclint checker defaults to 100 chars. The clang-format tool defaults to 80 (at least using --style=google). I'm okay with either but we need to decide on a specific limit if we're going to have tools like oclint and clang-format help us.

**Comment by krader1961** [comment]
FWIW, I think a 100 char line length limit is a reasonable compromise. A couple of years ago Google changed the limit for Java from 80 to 100 but still has a limit of 80 for other languages like C++ and Python. The 80 char limit is simply a holdover from the days of 80-column Hollerith cards and terminals like the DEC VT100. I'm moderately opposed to a wider limit since that makes side-by-side terminals or diff tools harder to fit onto a screen with a font size old geezers like myself can read.

**Comment by ridiculousfish** [comment]
Hard-wrapping lines to conform to a piece of cardstock designed in 1928 is indeed absurd. All tools that present source code should be able to soft wrap. But until they do, I can live with 100 character lines.

**Comment by krader1961** [comment]
Next question:  Placement of braces. The fish style guide currently calls for the Allman style which always breaks (starts a new line) before a left-brace. Not a single one of the predefined clang-format styles uses that brace style. And for good reason. It's information density is much lower. Informal testing shows that fish code would be approximately 10% shorter by line count using one of the other brace styles.

I recognize that portions of the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) are controversial. Especially regarding topics like exception handling and RTTI (the LLVM style guide, among others, makes the same recommendations). However, the portions that pertain to how the code is formatted seem to be uncontroversial and is supported "out of the box" by `clang-format --style=Google`. I'm not wedded to that style (I did almost no C++ programming at Google). But we need to pick one of the major styles supported by clang-format. The only other styles I think are reasonable are WebKit and LLVM. And I'm lukewarm about the LLVM formatting style.

**Comment by krader1961** [comment]
> All tools that present source code should be able to soft wrap.

The tools I use do support soft wrap and probably very few people are using an environment which does not. Nonetheless, there are other reasons to impose line length limits. For example, editing, not to mention reviewing code diffs, tends to be easier with hard line breaks at a reasonable limit. Too, the obvious counter argument is that all reasonable text formatting tools should be able to deal intelligently with hard returns. Tools like Markdown and LaTeX do so and if we're using a tool that doesn't we should switch to another tool.
