### ISSUE TITLE
Can't scroll with trackpad on git diff

### ISSUE THREAD

**Issue by nathanchapman** [fish-shell/fish-shell#5713]
Fish version: 3.0.2
MacOS Mojave 10.14.3 (18D109)
Darwin Kernel Version 18.2.0
Disabled third-party customizations and still experienced this

I'm unable to scroll with the trackpad in a `git diff` in fish. It appears the git diff output tool is reconfigured in fish with different behavior.

Using the same git installation and configuration, `git diff` with a small change will open `less` as the pager in my ZSH setup, but in fish it will output to stdout like if the pager was set to `cat`. With a larger diff, the pager opens in both ZSH and Fish, but I cannot scroll in Fish with the trackpad (only arrows and spacebar). I've tried manually opening a file with `less` and I'm able to scroll with the trackpad normally, so fish is likely using a different editor for git diffs but I can't locate that.

Any ideas why the `git diff` behavior is so different or how I can configure that editor?

**Comment by zanchey** [comment]
The output of `type git` might be handy.

**Comment by nathanchapman** [comment]
Output of `type git` is `git is /usr/local/bin/git` for both ZSH and fish

**Comment by Darkshadow2** [comment]
`git` uses `less`, unless you have a configuration that specifies something else. You can look and see using `git config -l` and see if you have anything under `core.pager`.

The thing with `git diff` with a small change acting like `cat` is actually the default behavior of `git`. I actually was looking into this recently, and this stackoverflow comment sums it up pretty well: [How do I prevent git diff from using a pager](https://stackoverflow.com/questions/2183900/how-do-i-prevent-git-diff-from-using-a-pager/18781512#18781512).

As to the scrolling, do you maybe have a different `less` on the system and `zsh` and `fish` are using different `PATH`s? Or maybe you've set the `LESS` environment variable in one and not the other that is changing the way `less` works? Or have one of the other `less` environment variables set in one and not the other?

I suspect it's either the `LESS` or `LESSKEY` environment variable, as if that's set, `git` will use that instead of its default.

**Comment by nathanchapman** [comment]
@Darkshadow2 Thank you so much!

ZSH:
```
❯ echo $LESS
-R
```

Fish:
```
❯ echo $LESS

```

### Solution

In Fish, run the follow:

```
set -U LESS "-R"
```
