### ISSUE TITLE
Syntactically wrong test expressions are treated as false

### ISSUE THREAD

**Issue by tsdh** [fish-shell/fish-shell#5723]
I'm using fish 3.0.1 and this is no regression from 2.7.

With fish, syntactically wrong `test` expressions are simply treated as being false:

```fish
# fish
$ if test -a -z !; echo Yes; end; echo Running 
test: Unexpected argument type at index 0
Running
```
@zanchey already told me, that this conforms to the standard `[` in Bash and ZSH, and he's right:

```bash
# Bash
$ if [ -a -z ! ]; then echo Yes; fi; echo Running 
[: too many arguments
Running
```
However, most people (including me) always used `[[` in Bash/ZSH.  When using that, such a syntax error leads to an error aborting the execution which is a much better behavior IMHO.

```bash
# Bash
$ if [[ -a -z ! ]]; then echo Yes; fi; echo Running
zsh: parse error near `!'
```
It would be great if I could have this behavior also in fish.

**Comment by faho** [comment]
TBH, `test` is broken. It's specified in such a way that it's always going to have problems.

One big thing is that `test something`, i.e. with one argument, is required to return true. This is even worse with combining operators like `-a`, which is what happens here - this is `test; and test -z !`. Because `test` defaults to testing string-emptiness (it's basically automatically doing a "-n"), that's false.

That's already discussed in #2037, so let's keep it there.

Btw, here's what POSIX has to say:

>The KornShell-derived conditional command (double bracket [[]]) was removed from the shell command language description in an early proposal. Objections were raised that **the real problem is misuse of the test command ([), and putting it into the shell is the wrong way to fix the problem**. Instead, proper documentation and a new shell reserved word (!) are sufficient.

**Comment by tsdh** [comment]
@faho Thanks for the pointer to #2037.  I'll watch that.
