### ISSUE TITLE
Tab completion of "git diff" results in "set: Array index out of bounds"

### ISSUE THREAD

**Issue by vrevelas** [fish-shell/fish-shell#5728]
fish version 3.0.2
OS: Ubuntu 16.04
terminal: GNOME Terminal 3.18.3
regression from fish 2.7.1: yes
able to reproduce with sh -c 'env HOME=$(mktemp -d) fish': yes

to reproduce:
```
➤ git init
➤ touch file1 file2
➤ git add .
➤ git commit -m init
➤ rm file1
➤ git diff<SPACE><TAB> set: Array index out of bounds
```
expected: no `set: Array index out of bounds` error. you have to put a space after the diff subcommand before hitting tab for a completion to trigger the issue.

the number of errors increases with the number of deleted files.

**Comment by faho** [comment]
Please confirm that `echo $version` shows 3.0.2, not 2.2.0 (the default version shipped with Ubuntu 16.04).

"Array index out of bounds" has become quite a rare error since we removed it from most cases. Simply expanding a non-existent variable index doesn't trigger it anymore, so `$var[50]` expands to nothing instead of causing the error.

The only remaining case is `set var[-X]`, if the variable doesn't have at least X elements. And as fate would have it, there's one case of that in the git completions in a path that is only used if you have an old git, as you would if you used an old Ubuntu version:

```fish
                set -l abs (string split / -- $relfile)
                # If it's in the same directory, we just need to change the filename.
                if test "$abs[1..-2]" = "$previousfile[1..-2]"
                    set previous[-1] $abs[-1]
```

However, I don't understand how that would be triggered. `$previousfile` here is wrong - it should be `$previous`, I missed it when renaming the variable. The variable is _set_, it's just always empty.

So `test "$abs[1..-2]" = "$previousfile[1..-2]"` should **not succeed, ever**!

Because it apparently does, that means that "$abs" is empty, which means that the line I expected from git is wrong (I have a new git version, not the old one that requires us to compute relative paths ourselves).

So: I'd like the output of

```fish
command git -c status.relativePaths -c core.quotePath= status --porcelain -z --ignore-submodules=all -uno
```

please!

**Comment by vrevelas** [comment]
Hi, yes I can confirm the version. I upgraded fish using the 3.x PPA.
```
➤ uname -a
Linux athlp0195 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
➤ fish --version
fish, version 3.0.2
```
the output of the git command you requested in the minimal reproduction repo is
```
➤ command git -c status.relativePaths -c core.quotePath= status --porcelain -z --ignore-submodules=all -uno
 D file1⏎
```
where fish has displayed the "⏎" character because the output from git has no newline at the end, it's not part of the git output. maybe your newer git version adds a newline and that's the source of the issue?

**Comment by faho** [comment]
>maybe your newer git version adds a newline and that's the source of the issue?

Doesn't matter. Most things in fish ignore a trailing newline either way.

No, the issue is simpler:

> D file1⏎

That path doesn't have a second path-component (because it's a relative path to a file in the current directory), so `$abs[1..-2]` is nothing, so `test "$abs[2..-1]" = ""` is true.

The solution is to, simply, use that, and I'm pushing a commit to that effect.

If you want, you should be able to download share/completions/git.fish from after that and save it as ~/.config/fish/completions/git.fish.

(Note that I'm pretty sure this would work if the error were removed, but I don't think we can do that in general because I have no idea what `set var[-2]` should sensibly do if it had less than 2 elements)

**Comment by vrevelas** [comment]
thanks!
