### ISSUE TITLE
Right prompt wrapping

### ISSUE THREAD

**Issue by glasserc** [fish-shell/fish-shell#5742]
I'm having symptoms very similar to #5564, but on a different operating system and terminal. I believe the specific character that is causing problems in my right prompt is `…`, HORIZONTAL ELLIPSIS, which I haven't changed from the default specified in `__fish_git_prompt.fish`.

I don't have this problem universally -- I can reproduce it using a specific nix-shell command, but I haven't been able to identify what exactly is in that command that causes wrapping to start happening.

I'm running fish 3.0.1 on NixOS using the terminal GNOME Terminal 3.30.0.

`$TERM` is `xterm-256color` and `uname -a` reports `Linux golden-cloud 4.14.105 #1-NixOS SMP Tue Mar 5 16:58:03 UTC 2019 x86_64 GNU/Linux`.

It's possible that my fish_right_prompt function is relevant, so here's that:

```
function fish_right_prompt
    # We don't need this; we're pretty much always ourselves
    #echo -n -s "$USER" @
    # We don't need this; it's already in the title bar (see
    # fish_title.fish)
    #echo -n $__fish_prompt_hostname

    set -l color_cwd
    switch $USER
        case root toor
            if set -q fish_color_cwd_root
                set color_cwd $fish_color_cwd_root
            else
                set color_cwd $fish_color_cwd
            end
        case '*'
            set color_cwd $fish_color_cwd
    end

    echo -n -s (set_color $color_cwd) (prompt_pwd) (set_color normal)

    __show_only_git_branch
end

function __show_only_git_branch
    __fish_git_prompt " %s"
end
```

I tried to reproduce this using the `env HOME=$(mktemp -d) fish` trick but of course in that case I didn't have any right prompt, so I wasn't really able to see if it still happened.

Following the advice in #5564, I tried every combination of the following settings:

GNOME Terminal "Ambiguous-width characters": Narrow (default), Wide
`fish_emoji_width`: unset, 1, 2 (I assumed it was OK to just set them using `set`, please correct me if that's wrong)
`fish_ambiguous_width`: unset, 1, 2

I still always got line wrapping.

**Comment by faho** [comment]
> fish_emoji_width: unset, 1, 2 (I assumed it was OK to just set them using set, please correct me if that's wrong)

That's indeed correct. Fish 3.1 will try to guess if your system needs 2 or 1, for now unset is the same as 1 (the old pre-unicode 9 width).

To figure out the correct width, run the following:

```fish
printf '%s\n' aaa \U1F603
```
If the smiley is as long as 1 a, the correct $fish_emoji_width is 1, if it's as long as 2, it's 2.

Since you appear to have a reasonably up-to-date system, it's probably 2.

>GNOME Terminal "Ambiguous-width characters": Narrow (default), Wide

That corresponds to $fish_ambiguous_width 1 (or unset) or 2. Any other combination is by definition wrong.

Horizontal ellipsis is classified as ambiguous, so this is the important part.

However: If you have another ambiguous character in your prompt, and the terminal displays them in a different width (i.e. there's two different widths for ambiguous chars) that's unsupportable and a bug in your terminal.

(Also, all of this is assuming you've built fish with the included wcwidth - the system one doesn't obey those settings, so if you've build fish with -DINTERNAL_WCWIDTH=NO you'll have to rebuild without)

-------

I've just tried with your right prompt and the default values, and it works.

Most likely:

>.I don't have this problem universally -- I can reproduce it using a specific nix-shell command, but I haven't been able to identify what exactly is in that command that causes wrapping to start happening.

What command is it? Most likely the suggestions in that include some character that causes issues. Some hangul jamo (i.e. korean characters) and the variation selectors are known to cause problems.

**Comment by glasserc** [comment]
> (Also, all of this is assuming you've built fish with the included wcwidth - the system one doesn't obey those settings, so if you've build fish with -DINTERNAL_WCWIDTH=NO you'll have to rebuild without)

Ah, yes, that makes sense. Per https://github.com/NixOS/nixpkgs/pull/53069 it looks like the build of fish in Nix does not use the internal wcwidth, and per https://github.com/NixOS/nixpkgs/commits/master/pkgs/shells/fish/default.nix this change happened before moving to 3.0.1, so I'm certainly not using the internal wcwidth.

As far as I know, there's no other surprising characters in my prompt. Here's a screenshot to serve as proof:

![Screenshot from 2019-03-14 09-55-21](https://user-images.githubusercontent.com/17006/54362854-17a43700-4640-11e9-87ed-4baf12395a2d.png)

(This version has a slightly more elaborate prompt with a N showing that you're in a nix-shell -- taking it out doesn't make the problem go away, which is why I originally posted without it.)

---

The command that reproduces it is a nix-shell command: `nix-shell requirements-clean.nix -j 1 --command fish`. With the following `requirements-clean.nix`, I get wrapping:

```
{ pkgs ? import <nixpkgs> {},
}:
pkgs.python37.pkgs.buildPythonPackage {
  name = "python37-interpreter";
}
```

With the following contents instead, I don't get the wrapping behavior:

```
{ pkgs ? import <nixpkgs> {},
}:
pkgs.python37
```

I'm still trying to figure out what the difference should be. In both cases, `fish` should be the same (system-level build, not coming from the nix-shell in any way). This might be more of a NixOS issue than a fish issue.

I only started having this symptom recently. I switched last week from NixOS 18.09 to 19.03 (i.e. unstable), which means moving from fish 2.7.1 to 3.X, and I guess that's where the problem started. If not, I can try bisecting nixpkgs to try to see where things started to go wrong.

**Comment by faho** [comment]
>The command that reproduces it is a nix-shell command: nix-shell requirements-clean.nix -j 1 --command fish.

Wait, so you _run_ that command, it opens up a new fish, and that exhibits the issue immediately, without you enterering anything?

**Comment by glasserc** [comment]
Yes, that's correct. It'll immediately start wrapping lines, as in the screenshot.

**Comment by floam** [comment]
Can you record an [asciinema](https://asciinema.org)?

**Comment by glasserc** [comment]
OK, I was afraid that was going to be hard but it was easy. https://asciinema.org/a/UnVItFQGzOy1fop3mBPFKtyLo

**Comment by faho** [comment]
Okay, I've now played the cast on my system, and here's the empty prompt copied from both child fishes:

```
>                                       ~/t/s/fish-right-prompt-wrap master|…4 N
>                                        ~/t/s/fish-right-prompt-wrap master|…4 N
```

Can you see which one is the broken one?

The latter, because it starts the right prompt one cell later, so it ends up one cell over the line, wrapping into the next. That causes this nice staircase.

Now, I have absolutely no idea what causes this, and it's quite weird that it would be caused by a different python interpreter. My bet would have been on the completion generation - that's a python script, and we start it on launch, in the background, if the completions haven't been generated yet. So if you had a different $XDG_DATA_HOME, we might rerun it.

But this isn't it. The only difference I can think of is $COLUMNS/$TERM or locale. If these environments differ in any of those that could cause this.

**Comment by faho** [comment]
>But this isn't it. The only difference I can think of is $COLUMNS/$TERM or locale. If these environments differ in any of those that could cause this.

@glasserc:
That means the output of `set` in both of these would be useful. Feel free to censor anything you consider private. Since it's gonna be long, uploading as files is probably the way to go.

**Comment by glasserc** [comment]
Just `set > file.txt`? It seems like it's trimming long environment variables. Anyhow, here goes..

[clean.txt](https://github.com/fish-shell/fish-shell/files/2975850/clean.txt)

[dirty.txt](https://github.com/fish-shell/fish-shell/files/2975851/dirty.txt)

I noticed that `LANG` is getting set differently. I tried setting it using `set -x LANG en_US.UTF-8` in the "dirty" shell and it didn't fix the problem. (It did something else strange. The ellipsis became a `â|`.)

**Comment by faho** [comment]
>Just set > file.txt? It seems like it's trimming long environment variables.

Yup - the long values are very unlikely to matter, but they'd distract.

>I noticed that LANG is getting set differently.

A broken $LANG setting could cause this problem. I see that "dirty" has it set to C.UTF-8. That's a common convention on Debian (and Fedora IIRC), but does not actually exist in upstream glibc (not to mention POSIX), so it's possible that you don't actually have a locale by that name.

The output of `locale` in both would be helpful (on my system that does not have C.UTF-8 it prints "locale: Cannot set LC_CTYPE to default locale: No such file or directory", but then goes on to say "LC_CTYPE="C.UTF-8"", so we need stderr as well).

> tried setting it using set -x LANG en_US.UTF-8 in the "dirty" shell and it didn't fix the problem

Did you expect it to fix the earlier prompt? That won't work, it's already gone by.

It should, however, fix the following prompts, if the locale is accessible (`locale` should not print any errors).

>(It did something else strange. The ellipsis became a â|.)

That seems like it's reencoding the ellipsis - that's #2613. Which further points to C.UTF-8 not existing.

Really, ideally fish would be started with the proper locale, at very least an accessible encoding (I mean ideally ideally the standard would just be UTF-8 encoding always, but that's a bit of a pipe dream).

**Comment by glasserc** [comment]
Thank you very much for your help debugging! I was able to track down the code that is setting `LANG` to https://github.com/NixOS/nixpkgs/blob/2fcb11a2442b27834db87b2f62511037c31b5e36/pkgs/development/interpreters/python/mk-python-derivation.nix#L93, which seems related to https://github.com/NixOS/nixpkgs/pull/55826/. I'm not 100% sure what the way forward is -- there's a good argument that I'm misusing Nix here -- but to try to get more information I opened https://github.com/NixOS/nixpkgs/issues/57911. One way or another, this isn't really a problem with `fish`. Thank you again!
