### ISSUE TITLE
Bash error when trying to access __fish_git_prompt_informative_status on fish_prompt event

### ISSUE THREAD

**Issue by Pobega** [fish-shell/fish-shell#5748]
I'm trying to set my git prompt color based on the current status (as opposed to using the icons), but when I access the builtin `__fish_git_prompt_informative_status` I get a bash: command not found error.

Is there an alternate way to do this, or something I'm missing?

I currently have it set to the `fish_postexec` event and it works as expected, the error only shows up when setting it to the `fish_prompt` event.

**git.fish**:
```
set __fish_git_prompt_char_stagedstate "s"
set __fish_git_prompt_char_dirtystate "d"
set __fish_git_prompt_char_untrackedfiles "u"
set __fish_git_prompt_char_conflictedstate "c"
set __fish_git_prompt_char_cleanstate "C"
     
set __fish_git_prompt_color_branch green --bold
     
function in_git_status
  if string match -q -- "*$argv[1]*" (__fish_git_prompt_informative_status)
    return 0
  end
  return 1
end  
     
function set_git_color --on-event fish_prompt
  if in_git_status C         # Clean
    set __fish_git_prompt_color_branch green --bold
  else if in_git_status d    # Dirty
    set __fish_git_prompt_color_branch red --bold
  else if in_git_status c    # Conflicted
    set __fish_git_prompt_color_branch yellow --bold
  else if in_git_status u    # Untracked
    set __fish_git_prompt_color_branch red
  else if in_git_status s    # Staged
    set __fish_git_prompt_color_branch purple
  end
end  
```
**Error**:
```
Welcome to fish, the friendly interactive shell
bash: __fish_git_prompt_informative_status: command not found...
~/.config/fish/conf.d/git.fish (line 1): 
__fish_git_prompt_informative_status
^
in command substitution
	called on line 13 of file ~/.config/fish/conf.d/git.fish

in function “in_git_status”
	called on line 22 of file ~/.config/fish/conf.d/git.fish
	with parameter list “C”

in function “set_git_color”
	called on standard input

in event handler: handler for generic event “fish_prompt”
```

**Comment by faho** [comment]
>I get a bash: command not found error.

That's not a fish error (obviously).

I'm betting that it comes from your command-not-found handler, which happens to be a bash script.

And it comes because fish can't find the `__fish_git_prompt_informative_status` function, because it's not in its own file.

`__fish_git_prompt_informative_status` is a helper function for the git prompt, and as such in `__fish_git_prompt.fish` (or now `fish_git_prompt.fish`).

The fish_prompt event fires before that is loaded (as part of your prompt calling `__fish_git_prompt`).

So you need to explicitly load it by calling `source` on it. E.g. `source $__fish_data_dir/functions/__fish_git_prompt.fish`, or to be pedantic:

```fish
for f in $fish_function_path/__fish_git_prompt.fish
    test -e $f; and source $f; and break
end
```

Or just call `__fish_git_prompt` instead of the informative status function directly.

**Comment by Pobega** [comment]
Thanks for the detailed explanation, I figured it was something like that but I guess I didn't think to directly source `__fist_git_prompt.fish` -- that more or less resolved the issue! Should've been obvious but I'm new to fish, I appreciate the reply.

The only thing remaining is that it doesn't seem to work the first time the prompt is drawn (my branch is always drawn as green.)

Also off topic, I've been looking through the docs and I can't find it but is there a list of the fish vars like `$__fish_data_dir`?

**Comment by faho** [comment]
>The only thing remaining is that it doesn't seem to work the first time the prompt is drawn (my branch is always drawn as green.)

That's because you don't have a scope for your variable - `set __fish_git_prompt_color_branch green --bold` will default to creating a local variable if no var of that name exists, which will be gone by the time the git prompt is run for real. But that sets up a global variable of that name, so the next time that `set` will update that instead.

-------

Sooo... one thing I'd like to know is why you're writing this as an event handler in the first place?

Why not just add it to your prompt?

Plus, I'd expect this to be _quite_ slow in a slightly larger git repository, because:

```fish
if in_git_status C         # Clean
    set __fish_git_prompt_color_branch green --bold
  else if in_git_status d    # Dirty
    set __fish_git_prompt_color_branch red --bold
  else if in_git_status c    # Conflicted
    set __fish_git_prompt_color_branch yellow --bold
  else if in_git_status u    # Untracked
    set __fish_git_prompt_color_branch red
  else if in_git_status s    # Staged
    set __fish_git_prompt_color_branch purple
  end
```

ends up running `__fish_git_prompt_informative_status` up to 5 times (plus the one time for the _actual_ git prompt).

Considering that's a rather costly function (~40ms just in the fish-shell repo, for 1 call), that's gotta hurt.

The easy thing there is to cache the output in a variable instead.

-----

Also, the git prompt can actually already do this! Just `set -g __fish_git_prompt_showcolorhints 1`, and then set the following variables to your liking:

- $__fish_git_prompt_color_flags
- $__fish_git_prompt_color_branch
- $__fish_git_prompt_color_dirtystate
- $__fish_git_prompt_color_stagedstate
- $__fish_git_prompt_color_flags
- $__fish_git_prompt_color_branch
- $__fish_git_prompt_color_dirtystate
- $__fish_git_prompt_color_stagedstate
- $__fish_git_prompt_color_branch_detached

**Comment by Pobega** [comment]
> Sooo... one thing I'd like to know is why you're writing this as an event handler in the first place?

Mostly for organization so I could have it in `git.fish` and not have to have `prompt.fish` rely on sourcing it (loose dependency)

> Also, the git prompt can actually already do this!

Unless I'm misunderstanding, these variables seem to control the color of the extended status stuff which I'm not using, I'm trying to color the prompt as a whole like so:

![fish screenshot](https://raw.githubusercontent.com/pobega/dotfiles/master/fish.png)

**Comment by faho** [comment]
>Mostly for organization so I could have it in git.fish and not have to have prompt.fish rely on sourcing it (loose dependency)

Then I'd still make my own `my_fish_git_prompt` function that prints git information suitable for the prompt, and just call that from the prompt.

The way this currently works is quite brittle.

>Unless I'm misunderstanding, these variables seem to control the color of the extended status stuff which I'm not using

Ah, yes, it does.

> I'm trying to color the prompt as a whole 

The problem with that is that there's no one color. You can have staged changes in a dirty repo with untracked files, and you might want to deal with them in any order (stage untracked files because they're missing from the commit being prepared, commit the staged changes to then stage the "dirty" changes for the next commit, etc.).

This isn't an "or", like you'd do with color,  this is an "and" like you'd do with symbols.

But sure, if you want it that way. I'd recommend uncoupling from the informative status a bit because that does a bunch of work you don't need or want (in particular it _counts_ all those changes, which can take quite a while). E.g. instead of calling that and seeing if there's a "d" in the output (presumably because you've set the dirty char to "d"?), call `__fish_git_prompt_dirty`. Same for untracked and staged.

The only thing that doesn't have a helper function (because, for some reason, it's only done in the informative prompt) is "conflicted" (or as that calls it "invalid") state, and that should just be `git diff --staged --diff-filter=U --quiet`. "clean" is the default case if nothing else matches.

**Comment by Pobega** [comment]
How do these helper functions work? As far as I can tell `__fish_git_prompt_dirty` just prints out the dirty character, regardless of whether or not I'm in a Git repository.

I could definitely make it work if there was some way to do `if __fish_git_prompt_dirty`, but as far as I can tell the output from those functions is extremely inconsistent.

**Comment by zanchey** [comment]
```function __fish_git_prompt_dirty --description 'fish_git_prompt helper, tells whether or not the current branch has tracked, modified files'
        set -l dirty

    set -l os
    command git diff --no-ext-diff --quiet --exit-code 2>/dev/null
    set os $status
    if test $os -ne 0
        set dirty $___fish_git_prompt_char_dirtystate
    end
    echo $dirty
end
```

They shouldn't be run in a directory that isn't a git repository, which is the first thing the git prompt checks.

**Comment by Pobega** [comment]
Right but even in a repo that is synced to master, these functions always seem to output the character (so there doesn't seem to be a reliable way to use them to get this information)

```
~/Work/chro/neve/test-repo (test) git status
On branch test
nothing to commit, working tree clean
~/Work/chro/neve/test-repo (test) __fish_git_prompt_staged 
#
~/Work/chro/neve/test-repo (test)
```

**Comment by Pobega** [comment]
Maybe it'd be better to explain what I am trying to achieve:

I want to utilize the single-character prompt notifications (ie `__fish_git_prompt_staged`) to make my shell look like this:
`~/repo (master !?+)`
But I also want the branch name to be colored based on the highest priority status. I'm just trying to figure out the easiest way to get the context of the git repository I'm in using the fish builtin stuff. It seems like it should be possible but I think I may not be fully understanding how to utilize the helper functions properly.

**Comment by faho** [comment]
>these functions always seem to output the character 

Some of these are overly coupled, yes. `__fish_git_prompt_dirty` and `__fish_git_prompt_untracked` don't always print the character, but `__fish_git_prompt_staged` prints the invalid char if not given a non-empty argument (should be a sha, this is from `git rev-parse HEAD` done earlier).

Soo... it's a bit annoying to use these as a test because they always return 0. If they returned 1 if the status didn't match it'd be easier to use like `if __fish_git_prompt_dirty >/dev/null`. That's a worthwhile change that we should probably make.

But you can still check the output on these, which depends on the prompt _less_ than you currently do:

```fish
    if test (__fish_git_prompt_dirty) = "*"
    else if test (__fish_git_prompt_untracked) = "%"
    else if test (__fish_git_prompt_staged "c0ffee") = "+" # staged shows invalid state if it's not given an argument
    # We use string match because there's an "=" somewhere in the output
    else if string match -q "*=*" -- (__fish_git_prompt_showupstream)
    else
    end
```

(technical note: `test` sucks. If there are ever fewer or more arguments than you expected it breaks. In this case it works because these functions always print at least a newline, but never more than one.)

**Comment by Pobega** [comment]
Thanks for the help! I think my distros package being out of date was also causing a bit of confusion (`version 2.7.1`, Fedora 29) as a lot of the helper functions don't seem to be available in my `__fish_git_prompt.fish` (as well as it still having the two underscores in the filename)

Unfortunately it seems like given my outdated version of fish I'll be tied to calling `__fish_git_prompt` twice. (though I wonder if I could just plop the `fish_git_prompt.fish` from the repo into `~/.config/fish/conf.d/` to override the system one)

I appreciate the help @faho !

**Comment by faho** [comment]
>Unfortunately it seems like given my outdated version of fish

See https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish - we offer packages for Fedora 29 and 28.
