### ISSUE TITLE
%jobname to bring stopped jobs to foreground

### ISSUE THREAD

**Issue by ottoshmidt** [fish-shell/fish-shell#5752]
Don't you think that putting stopped jobs back to background by %name would be nice, as it is in other shells?
(It's an enhancement)

**Comment by faho** [comment]
We've just removed that in 3.0.

Use `jobs` to get the PID for the job.

**Comment by ottoshmidt** [comment]
Can you briefly explain the reason behind? Just curious.

**Comment by faho** [comment]
Briefly: It's an additional special character that needs to be escaped for something that was barely used and never really worked properly.

"%firefox" looks like it'll give me the PID for my firefox process, but it can't actually, because firefox wasn't started by that particular shell.

There were also some specific issues with the implementation - errors were impossible to suppress (e.g .`set pid %whatever` would _always_ print an error if there was no match), plus the entire TOCTTOU problem (what if the process stopped in between matching and acting on that match?). 

Plus we're not all that enthused by job control in general, to be perfectly honest.

See #4230 for previous discussion.

**Comment by ottoshmidt** [comment]
Cheers!
