### ISSUE TITLE
ssh Broken Pipe on MacOS inside tmux

### ISSUE THREAD

**Issue by jsrpy** [fish-shell/fish-shell#5755]
Fish: fish, version 3.0.2
MacOS Mojave 10.14
Darwin MBP 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

I ssh into a number of VM daily with built-in Terminal plus tmux, and recently added fish shell to my terminal. I experienced `packet_write_wait: Connection to 125.111.111.111 port 60000: Broken pipe` after being idle on the shell for some time. 

Not sure if this has anything related to tmux with fish together? They don't like each other? Because, it seems to me that a normal Terminal with fish shell ssh does not have such issue.

Normally, when a new Mac machine experiences broken pipe on terminal, we can solve it by configuring `/etc/ssh/ssh_config`, adding `ServerAliveInterval 120` to keep connection alive.

Did fish override this setting by default? If not, it might be a tmux/terminal problem.

**Comment by faho** [comment]
Does your config.fish print _anything_, or touch the terminal in any way (e.g. `stty`) if it's not interactive?

Fish sources that file _always_, and ssh does not expect such output.

**Comment by jsrpy** [comment]
@faho ehh, I don't even have that config file. (Is this a _problem_?)

**Comment by faho** [comment]
Well, no.

Can you try without tmux?

**Comment by faho** [comment]
Oh, wait, you already said it didn't.

Lemme check if there's anything that might cause this with tmux from our end.

**Comment by faho** [comment]
Okay, we don't really do much specially for tmux - we might enable the vi cursor (but that's only done interactively, if you explicitly enabled it or vi-bindings), and after 3.0.2 we also react to tmux's focus-in and out sequences, but that's also a binding thing and purely passive. In 3.0.2, we explicitly ignore those sequences.

We also don't set any settings in ssh, and we're not responsible for keeping the connection alive (ssh is).

So I don't see this being triggered just because of something in fish.

**Comment by jsrpy** [comment]
Eh okay, maybe it's something to do with the Mojave upgrade. 

Let me do more testing from my side.

**Comment by faho** [comment]
@jsrpy: Any news here?
