### ISSUE TITLE
Off-by-one error for df, dt, dF, dT motions with vi key bindings

### ISSUE THREAD

**Issue by veryjos** [fish-shell/fish-shell#5770]
In vi, `df` and `dF` are inclusive (in that they delete the character the motion is targetting) and `dt` and `dT` are exclusive. Right now, in fish, all of these commands delete one character less than they do in vi.

To reproduce:
1. enable fish_vi_key_bindings (`fish_vi_key_bindings`)
2. write some text, attempt to use `df`, `dF`, `dt`, or `dT` and observe how it differs from vi

* Reproduced with a fresh environment
* fish --version: `fish, version 3.0.2`
* uname -a: `Linux josbox 4.20.15-1-MANJARO #1 SMP PREEMPT Sun Mar 10 08:50:44 UTC 2019 x86_64 GNU/Linux`

**Comment by faho** [comment]
This is a more general problem because emacs' and vi's idea on where the cursor is differs.

See e.g. #4025, #4683.

Adding "forward-char" and "backward-char" to bindings doesn't _really_ work because they'd also be executed if the command _fails_ (e.g. do "dfG" on a line that doesn't have a "G").

At the very least it would have to be "forward-jump and backward-char" (and forward-jump would have to be adjusted to set the bind status).

(Yes, that is indeed just "and" without a semicolon - this isn't fish-script, it's the DSL for bind functions, which is a bit weird)

**Comment by veryjos** [comment]
Have you guys considered using neovim as a backend to drive the shell prompt?

Is the plugin API robust enough to facilitate that? That's something I would be interested in working on- a plugin for fish that uses neovim as a backend to get proper vi bindings.

**Comment by faho** [comment]
>Have you guys considered using neovim as a backend to drive the shell prompt?

It's been thrown around idly. I can't say I'm a fan of the dependency, and I'm not sure if it would actually work well, but if someone implemented it and it's well-done we might merge it.

**Comment by mqudsi** [comment]
I looked into it a few times myself, but the last time that I sat down to do it I was put off by the assumptions neovim makes about the purposes behind the integration. The RPC api is (was?) very restrictive in terms of how an integration must be approached and the kind of state that would be kept client-side, so I ended up tabling my efforts.

**Comment by rayhogenson** [comment]
This off-by-one inconsistency also applies to selecting text in visual mode: in vim, the selection includes the character under the cursor. In fish, the selection includes up to but not including the character under the cursor.
