### ISSUE TITLE
Sharing prompt for others to select with fish_config

### ISSUE THREAD

**Issue by koesherbacon** [fish-shell/fish-shell#5776]
Hello there. This isn't an issue per se but I can't figure out another way ask this so I'm asking here.
<br>
I've created a prompt for both my normal user as well as when using root via 'sudo su' and I think others might like to use it when customizing fish using 'fish_config' . How can I go about sharing it and possibly adding it to those available via 'fish_config'?

<br>
Should I fork fish and add it that way? Figure out how to add it to 'oh_my_fish' even though I do not use it myself? Just create a git repo and/or gists and hope people stumble upon it?

<br>
I know that this this isn't really an issue with the fish shell itself a question like this is probably very low priority, but any info you feel like sharing would be nice to receive.

<br>
For the future, what's the best way to contact you and other fish users without opening an issue like I've done this time?  Thanks for making my favorite shell and taking a look at this question when you get a chance.
<br>
Thanks again,
    ⁓ Ev
<br>

**Comment by faho** [comment]
`fish_config` currently doesn't have a real way to _add_ prompts to it - that's #2577.

>Just create a git repo and/or gists and hope people stumble upon it? 

That's probably the way I'd go about it. Come to think of it, I actually have - my own prompt is at https://github.com/faho/config/tree/master/fish/.config/fish/functions. If someone finds it and decides it's nice, they can use it. There's no real need to turn it into a "project" or to offer it as a "plugin" because all you have to do is download the file to ~/.config/fish/functions.

Though I'm also not an OMF user, so maybe they'd view that differently.

>For the future, what's the best way to contact you and other fish users without opening an issue like I've done this time?

Probably https://gitter.im/fish-shell/fish-shell. Though we do allow questions here - that's what the label is for - for one-off things that probably scales better.

**Comment by floam** [comment]
We're also open to improving the included prompts and would consider new ones. Someone just would need to open a PR and see what folks think.

**Comment by faho** [comment]
Okay, the question has been answered, the proposed enhancement is already tracked elsewhere. Closing!
