### ISSUE TITLE
prompt shows weird output after terminal emulator starts

### ISSUE THREAD

**Issue by gnumoksha** [fish-shell/fish-shell#5781]
### The issue
As a user, I use the fish_config to set the color scheme to "Old School" and the prompt to "Informative Vcs". After that almost every time I open my [terminal emulator](https://github.com/jwilm/alacritty) I see some new lines on the screen as follows:

![Screenshot from 2019-03-30 23-52-40](https://user-images.githubusercontent.com/696797/55284232-a905ef80-5348-11e9-9a7f-6958359346ce.png)

### Additional information
```console
$ fish --version
fish, version 3.0.2
$ uname -a
Linux bombadil 4.19.0-1-amd64 #1 SMP Debian 4.19.12-1 (2018-12-22) x86_64 GNU/Linux
$ echo $TERM
xterm-256color # My terminal emulator is Alacritty
```

> Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:
>   sh -c 'env HOME=$(mktemp -d) fish'

Executing the command above does not produce the same issue, but executing only "fish" has the same result. The issue only happens at terminal emulator startup.

### Notes
* [This](https://fishshell.com/docs/current/faq.html#faq-titlebar) did not work.

**Comment by faho** [comment]
>Executing the command above does not produce the same issue, but executing only "fish" has the same result. The issue only happens at terminal emulator startup.

Sooo... the obvious step here would be to check your configuration. In particular fish_greeting, which is used only at terminal startup to provide some output.

As it can be used as a function or a variable both `type fish_greeting` and `set --show fish_greeting` would be nice to see.

**Comment by faho** [comment]
@gnumoksha: Ping? Have you found what does this? Otherwise, can you check fish_greeting?

**Comment by orbitz** [comment]
I'm experiencing similar thing, but it happens on every time.  I run fish in tmux.  Here is an example of what it looks like, I did not add the white space/new line between prompt and ls

```
orbitz@bsdell ~/p/a/mono|(default|@)✓>
                                        ls
LICENSE           Makefile
```

However, when I switch to a new tmux window then back again, it changes:

```
orbitz@bsdell ~/p/a/mono|(default|@)✓> ls
LICENSE           Makefile
⏎
```

**Comment by orbitz** [comment]
And my system info:

```
orbitz@bsdell ~/p/a/mono|(default|@)✓> fish -v
fish, version 3.0.2
⏎
orbitz@bsdell ~/p/a/mono|(default|@)✓> echo $TERM
screen
⏎
orbitz@bsdell ~/p/a/mono|(default|@)✓> freebsd-version
12.0-STABLE
⏎
```

**Comment by orbitz** [comment]
Something else might be going on because I downgraded to fish 3.0.0 and am still getting this odd behaviour.  I did not downgrade any dependencies that came with 3.0.2 though.

**Comment by orbitz** [comment]
So this seems to be some interaction with tmux, I do not experience this when I use fish directly in `st`

**Comment by VlkrS** [comment]
I'm experiencing the same issue with tmux and fish 3.0.2 on FreeBSD 12

**Comment by orbitz** [comment]
>Something else might be going on because I downgraded to fish 3.0.0 and am still getting this odd behaviour. I did not downgrade any dependencies that came with 3.0.2 though.

Clarification: I think this was because I had some shared library still be access or something.  After restarting my machine, the downgrade had fixed the issue.

**Comment by orbitz** [comment]
For me, this seems to be related to tmux in some way.  I am on fish-3.0.0 and upgraded tmux to 2.8 today and am seeing the "return" symbol after every command.

When I use fish-3.0.2, I am seeing the behaviour from https://github.com/fish-shell/fish-shell/issues/5781#issuecomment-482953277

**Comment by faho** [comment]
@orbitz: This kind of behavior appears if your terminal (which in this case is both tmux and whatever that is running in) and fish disagree on the width of a character.

In your prompt, you have `✓`. Does it work if you remove that character? Does it work if you remove other characters from your prompt? Did you build fish yourself? Did you use the INTERNAL_WCWIDTH build option? Anything in your fish or tmux configuration that has any effect? What locale does tmux run with (fish will try to get a UTF-8 locale, so if it's running inside tmux it's possible that that is running with LC_CTYPE=C, and so will get a different idea of the width of characters)

Also:

>upgraded tmux to 2.8

The current tmux release is 2.9. Does it work if you upgrade to that?

**Comment by orbitz** [comment]
>Does it work if you remove that character?

Yes and no, as I play with this more, I get very inconsistent behaviour.  When I do not have the check mark I do not get the "return" symbol, however the cursor hops around like a drunkard, going lines down and tab complete overwriting itself.

> Did you build fish yourself?

No, all packages are installed via pkg on FreeBSD

> Did you use the INTERNAL_WCWIDTH build option?

I do not know.

> Anything in your fish or tmux configuration that has any effect?

I am not sure how to determine this as I do not know what is wrong.  But I can at least say that this behaviour appeared after upgrading software, not after performing an configuration change.

> What locale does tmux run with 

The output of `locale`:

```
LANG=
LC_CTYPE=en_US.UTF-8
LC_COLLATE="C"
LC_TIME="C"
LC_NUMERIC="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_ALL=
```

Thank you for the response.

**Comment by faho** [comment]
>The output of locale:

Okay, that looks like fish's fallback fallback. It is started with no locale, so it tries to read the system configuration, doesn't find any, so it at least falls back to an LC_CTYPE that can read UTF-8, so it has  a *chance* of getting the correct character width.

Which means tmux (fish's parent process) is running with a C locale, which means if it does wcwidth() it'll get the wrong answer.

That means your system is misconfigured. Either:

- Set the locale to something that can understand utf-8 for tmux as well.

or

- Remove all non-ASCII characters from your prompt

**Comment by orbitz** [comment]
Could you describe what exactly the configuration should be?  I'm not sure if its's related, but I do have the following in `~/.login.conf`

```
me:\
        :charset=UTF-8:\
        :lang=en_US.UTF-8:\
        :setenv=LC_COLLATE=C
```

It's still unclear to me why this started recently.

**Comment by faho** [comment]
>Could you describe what exactly the configuration should be?

I have no idea, as I'm not all that familiar with FreeBSD (basically just enough to run fish's test suite on it occasionally).

It is possible you have to `setenv` LANG too, as it seems to not take effect. Or it's to do with tmux bypassing that system. 

Or you need to `set -g utf8 on` in tmux.conf, which was apparently necessary at one point, according to https://unix.stackexchange.com/questions/52512/bad-utf8-display-with-tmux. Or that's just a workaround for starting tmux with a misconfigured locale, I'm not sure.

**Comment by orbitz** [comment]
One thing I don't get is when I run bash, I get the expected locale:

```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
orbitz@bsdell ~> locale
LANG=
LC_CTYPE=en_US.UTF-8
LC_COLLATE="C"
LC_TIME="C"
LC_NUMERIC="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_ALL=
orbitz@bsdell ~> exec bash -l
orbitz@bsdell:~$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=
```

My bash rc does set LANG, however I tried doing `set -U LANG en_US.UTF-8` and I got underlines instead of unicode characters.

I guess I'll just try random things tomorrow and hopefully something works.  But I'd like to reiterate: something in tmux or fish changed recently to cause this to happen, I haven't modified configs at all.  Maybe the configs were always run, I can't speak to that, but things were working fine for the last 2 years I've been running fish on FreeBSD.

**Comment by orbitz** [comment]
I also tried the tmux config.  No dice.

**Comment by faho** [comment]
>One thing I don't get is when I run bash, I get the expected locale:

If you run tmux in that bash, what locale do you get? How do you start tmux? How do you start bash? If you run fish in that bash, what's your locale there? What happens if you start bash without `-l`?

Let me try to explain the problem in a bit more detail:

- tmux  is started with a default locale, which is non-utf8 (how is tmux started?)

- tmux starts fish with that same locale (because it just passes on the environment variables)

- fish gets that default locale (*all* locale variables unset, or the fallback doesn't kick in)

- fish tries to get a proper locale. Reads system config (e.g. /etc/locale.conf, /etc/env.d/02locale, /etc/sysconfig/i18n), finds nothing. Finally falls back to LC_CTYPE=en_US.UTF-8 so at least it has a fighting chance of handling utf-8 correctly. (this is why you see just LC_CTYPE set, and not LANG

So it appears that the process you use for starting tmux does not set the locale.

**Comment by orbitz** [comment]
I downgraded tmux back to the previous version, using fish 3.0.0, and things are working as expected.  I looked at what the changes in the tmux package here and the log says:

```
Add a default option to use utf8proc for Unicode normalization,
case-folding, and other operations.

It is substantially better and more up-to-date than the libc functions
providing the same features.
```

I guess I'll try to open a bug in tmux although I'm not sure if this is a tmux bug the change in how tmux is compiled is exposing something fish is doing wrong.

**Comment by orbitz** [comment]
>Yeah, that's most likely just masking the actual issue. Your locale is still set up wrong.

I am having a hard time confirming that.  Specifically:

1. `tmux` believes it is talking UTF8, at least according to the documentation if it did not it would have rewritten the checkbox and return symbol as `_`, but it is displaying them as expected.
1. I did an experiment where I started `tmux` (which started a `fish` shell), then `exec bash -l`, which gave me the expected good locale with `en_US.UTF-8`, in all variables.  Then I did `exec fish`, and `locale` told me everything was `en_US.UTF-8` as well, and yet fish still behaved incorrectly.  However, because bash does not do as fancy things with the terminal as fish does, I am not sure how to confirm bash is working as expected.

Can you suggest an experiment which can help me determine which component is configured incorrectly?

**Comment by Darkshadow2** [comment]
Is your tmux actually linked against utf8proc? I was having problems with fish running under/in it in that case, too. It always prints the newline character (whatever that character is called, when you run a command that doesn't end in a newline) _after you've made the window scroll_. Before that it acts normally, unless you have a right prompt then it prints a blank line after your prompt and your cursor will be there.

I couldn't figure out what was going on and just recompiled tmux without utf8proc. Everything works normally then. Definitely something strange going on there. I don't think it has anything to do with how the locale is set, as everything except `LC_ALL` was set as `en_US.UTF-8` for me.

**Comment by orbitz** [comment]
@Darkshadow2 I believe it is, when I revert to the build of tmux without utf8proc, things seem to work as expected.  What you've described is exactly what I'm seeing when using 2.8 compiled against utf8proc.

**Comment by faho** [comment]
>Can you suggest an experiment which can help me determine which component is configured incorrectly?

@orbitz:

The major question here is if bash sets the locale as part of its initialization - this is common especially for login shells. So you'll have to try just `bash`, no login, without tmux. Then it would be nice to know how you start tmux, and to try to start `tmux` in a shell with a good locale, and then fish inside *that*. 

Then it would be nice if you could set your prompt to a simple version like just `function fish_prompt; echo $PWD '>'; end; function fish_right_prompt; end` and figure out which other character is causing issues.

Character width is a bit of a problem because they've *changed* in Unicode, particularly during the Unicode 8->9 transition, but system support is lagging. Since tmux's support apparently improved, it's likely that it jumped ahead, but fish still defaults to the old value. You can set this in fish via `$fish_emoji_width` - the post unicode9 value being "2", the pre-uni9 value being "1". Additionally, there are "ambiguous width" characters that may be displayed as 2 or 1 cells wide depending on the interpretation. This can be controlled via the $fish_ambiguous_width variable. For this, it would be nice if you could figure out the character that's causing the issue. But all of this only even starts to apply if you have a unicode-supporting locale - without that, it's basically unsupportable.
