### ISSUE TITLE
No tilde env var expansion

### ISSUE THREAD

**Issue by ryan-shaw** [fish-shell/fish-shell#5793]
```fish, version 3.0.2
3.0.2

18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

xterm-256color
```

I am trying to specify a DOCKER_CERT_PATH with `export DOCKER_CERT_PATH=~/.docker/docker-host-dev/`

which causes `docker ps` to return `could not read CA certificate "~/.docker/docker-host-dev/ca.pem"` if I replace `~` with `$HOME` it works as expected so I believe the `~` in the env var is not being expanded.

You can reproduce this situation using the following:

```fish
touch ~/test.txt
export TEST=~/test.txt
cat $TEST

export TEST=$HOME/text.txt
cat $TEST
```

**Comment by zx8** [comment]
Using `export` isn't the "correct" way to set environment variables in fish. It only exists for some degree of compatibility with other shells.

Under the hood, `export` is just a hacky fish function ([`export.fish`](https://github.com/fish-shell/fish-shell/blob/bc66921ac9c10bf6a36e2b9b9f9dd83347b1d3e6/share/functions/export.fish)) which performs some chopping and changing before calling out to fish's `set` builtin, so I'm not really surprised this doesn't work as you expect.

Try this instead:

```sh
set -gx TEST ~/test.txt
```

**Comment by ryan-shaw** [comment]
Ah I see! Looking at the `export` function it uses `set -gx` so I'm wondering why it would still be an issue in this case

**Comment by faho** [comment]
Two things come together to produce this end-result:

1. Fish doesn't natively support `export`

2. Fish doesn't expand `~` anywhere but the start of the word. (Bash does, but the rules are weird and not actually documented, IIRC)

Imagine a simplified `export`:

```fish
function export
    set -l kv (string split -m 1 = -- $argv)
    set -gx $kv[1] $kv[2]
end
```

`$argv` with your initial call is `TEST=~/test.txt` because of (2). So this splits it to `TEST` and `~/test.txt`.

Then it expands $kv[1] to `TEST` and $kv[2] to `~/test.txt`, and fish doesn't perform tilde-expansion on the latter because it only expands `~` literals.

Like @zx8 said, you want `set` instead of `export` in native fish code.

Adding this to `export` would be much easier if we had the `expand` builtin (#751). I should try looking at that again.

**Comment by faho** [comment]
See also #1410.

**Comment by ryan-shaw** [comment]
Great, thanks for explaining. I may have to go back to bash or zsh as I don't want to modify these bash files that setup the docker envs.

**Comment by faho** [comment]
>I don't want to modify these bash files that setup the docker envs.

Fish indeed can't source arbitrary files written for bash or zsh, and that's a general thing, and won't go away even if we changed the tilde-expansion semantics to match.

If you want, you can:

- Run fish from bashrc
- Use https://github.com/edc/bass to read those files
- Transform them while sourcing with `string replace -r 'export ([^=]*)=(.*)' 'set -gx $1 $2' </path/to/file | source` (this assumes there's one export per line at most)

**Comment by ryan-shaw** [comment]
> Use https://github.com/edc/bass to read those files

Thanks, I haven't come across this! I shall give it a try.
