### ISSUE TITLE
$dirprev variable scope is not honored using cd

### ISSUE THREAD

**Issue by Geospace** [fish-shell/fish-shell#5797]
Using `fish, version 3.0.2`, on macOS Mojave 10.14.4.

I would like to share my `cd` / `cdh` history between fish instances.

Quoting `man cdh`:

```
Note that the cd command limits directory history to the 25 most recently visited
directories. The history is stored in the $dirprev and $dirnext variables which
this command manipulates. **If you make those universal variables your cd history is
shared among all fish instances.**
```

Taking a look at the `share/functions/cd.fish` file, we can see that the `$dirprev` variable is set at the global scope, shadowing the universal variable of the same name.

Maybe we can fix this by honoring `$dirprev` scope if its set universally? I opened https://github.com/fish-shell/fish-shell/pull/5796 to this effect.

**Comment by 0ion9** [comment]
.. I'm not sure about this `set -U -a ..'. It's functional but it seems to be saying something false - that we care about forcing the variable to universal, which is odd because the previous line just confirmed that the variable IS universal.

What about the following?

```
set -q dirprev
and set -a dirprev $previous
or set -g -a dirprev $previous
```

Which to me reads as:
"Respect the current scope of dirprev, whatever it is, and append to it. If it's not set, set it globally and append to it."

**Comment by Geospace** [comment]
Fixed by https://github.com/fish-shell/fish-shell/pull/5796 ! ;)
