### ISSUE TITLE
Issue when set $PATH in config.fish file

### ISSUE THREAD

**Issue by qlem** [fish-shell/fish-shell#5810]
version **3.0.2**
distribution **Archlinux** 
kernel **5.0.7-arch1-1-ARCH**

When i set $PATH in config.fish, the new path is appended two times in $PATH.

#### config.fish file
```
$> cat config.fish
set -x PATH $PATH /foo/baz
```

#### env after restart
```
$> echo $PATH
/some/default/paths /foo/baz /foo/baz
```

**Comment by faho** [comment]
Most likely, you're actually running `fish` twice. Or fish is already started with that path component.

Note that appending to exported variables in config.fish isn't wise - if you run another `fish` as a child, that'll have the offending path _three times_, and if you run another fish inside that it'll have it four times.

Either check if the component is already included:

```fish
contains -- /foo/bar $PATH
or set -ax PATH /foo/bar
```

or add it in e.g. ~/.pam_environment or /etc/environment.

**Comment by faho** [comment]
Most likely, you're actually running `fish` twice. Or fish is already started with that path component.

Note that appending to exported variables in config.fish isn't wise - if you run another `fish` as a child, that'll have the offending path _three times_, and if you run another fish inside that it'll have it four times.

Either check if the component is already included:

```fish
contains -- /foo/bar $PATH
or set -ax PATH /foo/bar
```

or add it in e.g. ~/.pam_environment or /etc/environment.

**Comment by qlem** [comment]
It is very strange because i use fish as default shell, not as interactive shell. So i running fish one time, at the session log in. I tried to clear the path, reboot, set the path in config.fish then reboot again, but i stay with dublicate paths.

I don't understand how to append properly to path. The doc is not clear. What is the equivalent of export PATH=$PATH:/foo/baz for fish ?

**Comment by faho** [comment]
>What is the equivalent of export PATH=$PATH:/foo/baz for fish ?

That was the equivalent. The issue is this:

- Your system runs a fish before, e.g. in logging in

- That fish _also_ reads config.fish, because fish _always_ reads config.fish, even in a login shell or when not interactive (that's what `status is-interactive` is for)

So it adds the path to $PATH, the children inherit that new, adjusted path, and your next fish adds the path _again_.

Like I said: appending to exported variables in config.fish isn't wise.

Either check if the component is already contained, or set the variable in your login environment elsewhere, e.g. via pam_environment.

**Comment by qlem** [comment]
Thank you for the explanations @faho. I thought that fish only read config.fish only one time at the login, so that config.fish was the equivalent to .bashrc. The documentation is not very clear about this fact in my opinion. Especially section about [$PATH](https://fishshell.com/docs/current/tutorial.html#tut_path) and  [Startup (Where's .bashrc?)](https://fishshell.com/docs/current/tutorial.html#tut_startup). 

The only reference that explains how to add PATH variable when using a login shell is the first example in the section [Initialization files](https://fishshell.com/docs/current/index.html#initialization). It is not really put in highlighting.

**Comment by faho** [comment]
>An another question, how to append path to $XDG_DATA_DIRS please ? I do the same thing that append path to $PATH but its seems doen't work:

@qlem: Sorry, I missed that one.

The issue is that $XDG_DATA_DIRS isn't a path variable. 

$PATH and friends are really lists, but UNIX doesn't support list variables, so it does this encoding scheme where you separate the elements with a `:`. Because fish does support lists, it splits all path variables (by default these are all variables whose name ends in "PATH") on ":" so you can use them as lists. It adds the colon back when exporting them to commands, or when you quote them.

So you either treat $XDG_DATA_DIRS as a normal variable, and do `set -x XDG_DATA_DIRS $XDG_DATA_DIRS:/my/other/path`, or use `set --path XDG_DATA_DIRS` to turn it into a path variable and then use it as a list. (The former is annoying if if is _empty_, because you then need to take care not to add the `:`, because that would be treated like there's an empty element, and empty elements in these lists are usually understood to mean $PWD)

(Also, this is describing the situation in fish >= 3.0. fish before that knew no path variables, it only treated $PATH, $CDPATH and $MANPATH as lists)
