### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by pat-s** [fish-shell/fish-shell#5834]
Compared to `bash` which loads instantly, `fish` takes about 2-3s to start.

I am starting `fish` with an empty `.config/fish/config.fish`.

Doing `fish -d 2` show that it spents a lot of time in `/usr/share/fish/config.fish`.
I tracked the problem down to the following part in `/usr/share/fish/config.fish`:

https://github.com/fish-shell/fish-shell/blob/32ad1a6e628b26b1c75bfee44706e1cd9637c9e2/share/config.fish#L94-L118

Commenting this part lets `fish` load instantly. I haven't played around enough to see whether commenting this has any bad consequences.

Does nobody else face this slow startup? I am wondering if it is related to my system only. 

<details>
<summary>Details</summary>

fish, version 3.0.2
3.0.2

Terminal: st
OS: ArchLabs

```
uname -a
Linux tux 5.0.7-zen1-1-zen #1 ZEN SMP PREEMPT Mon Apr 8 10:36:23 UTC 2019 x86_64 GNU/Linux
```

</details>

**Comment by faho** [comment]
What this most likely means is that you have a massive $fish_user_paths. Solve that and it'll start up nice and snappy.

**Comment by pat-s** [comment]
Indeed, it was related to `fish_user_paths`.
I had `set -U already` but no `set -e` before. Adding this solved the issue.

Thanks a lot for the quick reply, this was bugging me a lot!

**Comment by hoijui** [comment]
for me, slow startup was casued by the _powerline_ packed. I did not want it anyway, so I removed it with `omf remove powerline`.

**Comment by jooize** [comment]
Absurd. You mean Fish can not handle the 125 KB of paths I placed in `fish_user_paths`?

**Comment by jooize** [comment]
Wonderful. Everything using Fish is fast again!

I ended up with this problem because of confused instructions for how to actually set `PATH`. PyEnv instructs at https://github.com/pyenv/pyenv#understanding-path to use the following.

```fish
set -Ux PYENV_ROOT $HOME/.pyenv
set -Ux fish_user_paths $PYENV_ROOT/bin $fish_user_paths
```

I'm using:

```fish
# Personal executables
set -x PERSONAL_EXECUTABLES "$HOME/Executables"
status --is-interactive; and contains $fish_user_paths "$PERSONAL_EXECUTABLES"; or set --universal --append fish_user_paths "$PERSONAL_EXECUTABLES"

# MacPorts (package manager)
contains $fish_user_paths /opt/local/bin; or set --universal --append fish_user_paths /opt/local/bin
contains $fish_user_paths /opt/local/sbin; or set --universal --append fish_user_paths /opt/local/sbin

# PyEnv (Python manager)
contains $fish_user_paths {$HOME}/.config/pyenv/bin; or set --universal --append fish_user_paths {$HOME}/.config/pyenv/bin
status --is-interactive; and pyenv init - | source
status --is-interactive; and pyenv virtualenv-init - | source
```

Is this the way to do it?

I notice my humor was not appreciated. :( Tried to make it obvious with the smiley reaction.

> Absurd. You mean Fish can not handle the 125 KB of paths I placed in `fish_user_paths`?

> fish-shell deleted a comment from jooize 3 minutes ago

Anyhow, thanks for Fish!

**Comment by faho** [comment]
>contains $fish_user_paths /opt/local/bin; or set --universal --append fish_user_paths /opt/local/bin

Other way around. `contains /opt/local/bin $fish_user_paths`. It checks if the first argument is in the rest of the arguments.

(also see #7028)

**Comment by jooize** [comment]
Ah, figures. Noticed today `fish_user_paths` was filling up again.

Regarding “won't help you much”, do you also mean setting `PATH` just makes more sense and I should probably leave `fish_user_paths` alone?

Thank you, @faho.

**Comment by faho** [comment]
>Regarding “won't help you much”, do you also mean setting $PATH just makes more sense and I should probably leave $fish_user_paths alone

What I mean by that is that the value in universal variables is that you set them once, and they stay that way. So you can just run `set --append fish_user_paths ~/.local/bin`, interactively, and you're done with it. No need to open up your editor, add a new line, restart fish, ...

But since you're in your editor in config.fish anyway, that doesn't matter. Instead what you need to do is to take care not to endlessly append to it, and once you're doing that, you can just do the exact same thing to $PATH, and skip the middleman.

>I'm unsure about when to quote/escape in Fish. When to use {} or "" or neither. How they actually behave in different contexts.

`{}` isn't quoting. Used with variables like `{$PATH}` it's separating. The variable will be expanded like it would outside of quotes, only fish knows where the variable name ends.

So if you're doing something like:

```fish
set prefix fear
echo $prefixful
```

that won't work, because fish will try to expand the variable with the name "prefixful". You need to use `{}` to make it

```fish
echo {$prefix}ful
```

and it will echo "fearful".

Now, double-quotes kind of force a variable into one string. Whether a variable is unset or has multiple elemnts won't matter, it will be turned into exactly one argument. When the variable is empty, it will be turned into the empty string, when it has more than one element, it will join those elements with spaces (or ":" if it's a path variable, to allow turning $PATH into the familiar `/usr/bin:/bin:/sbin` that some programs expect).

Of course that will also make it clear where the variable name ends because variable names can't include spaces, so the above could also be `echo "$prefix"ful`.

*Most of the time, in fish, you don't need to double-quote variables.* (the one big exception is with `test`, because we just took that from POSIX wholesale, and it has some questionable argument parsing)

This is in stark difference to POSIX sh (including bash, but not typically zsh), because that does what is known as "word splitting". If it sees an unquoted variable it splits it into arguments on the characters in $IFS (by default that's space, newline and tab).

So if you do

```fish
a="foo bar"
rm $a
```

it will pass "foo" and "bar" as separate strings to `rm`.

Fish doesn't do that, it keeps the elements as they are. If you do

```fish
set a "foo bar"
rm $a
```

It will see that $a has one element, the string `foo bar` and pass it as one argument.

E.g. in your example above:

>    set -x PERSONAL_EXECUTABLES "$HOME/Executables"

$HOME has one element, so the quotes here won't change anything.

**Comment by jooize** [comment]
That is exactly what I wanted to learn. Very well explained, in good detail. Thank you for taking the time! I have some follow-up questions, but feel free to ignore them and go about your day.

> `{}` isn't quoting. Used with variables like `{$PATH}` it's separating.

- Do I in Fish only need to worry about quoting variables when using Fish builtin `test`?
- May builtin `test` in the future be made to handle variables as Fish otherwise does?

**Comment by faho** [comment]
>Do I in Fish only need to worry about quoting variables when using Fish builtin test?

Yes.

>May builtin test in the future be made to handle variables as Fish otherwise does?

It can't.

The problem is that `test` is POSIX-conforming, and POSIX has some demands that are... not great.

It demands that `test` with any one non-empty argument return true, so that

```fish
test somestring
```

works to test if somestring is empty.

That sounds nice, until you think about

```fish
set -l empty
test -n $empty
```

That returns *true*, and it has to, because POSIX demands it.

Another is that the grouping is broken by design (the standard actually says that test only has to work for up to four arguments, after that it's okay to just completely break), and that the operators are fairly ill-specified, because it has these zero, one, two, three argument modes.

It's designed ambiguous, and can't be fixed in the shell model. Bash's approach is `[[`, which is actual syntax, and can therefore e.g. turn off word splitting in that context.

The solution is to introduce something else. We don't entirely know what it looks like - `[[` isn't too awful in context, but it's quite complicated, especially if we wanted to match bash (which isn't a goal of us, but if we can it's an easy win). #6124 has some proposals.

**Comment by faho** [comment]
Wait, that said "only". No, you don't *only* need to quote with test, but
that's the most common case by far.

Esko <notifications@github.com> schrieb am Mo., 25. Mai 2020, 20:44:

**Comment by jooize** [comment]
Oh, thanks for clarifying that important distinction. Any hint for how to understand when?

**Comment by zanchey** [comment]
Using `test`, any variable that could contain a path, and anything that comes from user input is my usual guide.
