### ISSUE TITLE
Allow customizing which characters are consumed by `kill-word`

### ISSUE THREAD

**Issue by GeorgeLyon** [fish-shell/fish-shell#5841]
Currently, Ctrl-W removes path components, which are split on `"/={,}'\""` 

It would be nice if we could (optionally or otherwise) add ":" to that list. 

The concrete use case I have is ssh addresses such as 
`git clone git@github.com:fish-shell/fish-shell`

It would be nice if two taps of Ctrl-W produced `git clone git@github.com:`, ready for specifying a different repository. Currently, it produces `git clone `.

**Comment by mqudsi** [comment]
I'm not sure about the complexity of adding customization here (vs adding a custom binding to `ctrl-w` that does what you want), but I am interested in any problems with just adding `:` to that list of characters universally. It would seem to be rare for it to not indicate some form of word separation to which `kill-word` should apply rather than `kill-bigword`.

**Comment by faho** [comment]
Note: `kill-word` indeed stops at the `:` - `backward-kill-path-component` (the default binding for ctrl-w) doesn't.

But yeah, I'd add `:` and `@` to the default list there. Even though they are technically allowed in paths (UNIX is weird and allows everything but 0x2f "/" and 0x00 NUL), it's much more likely they're used like this.
