### ISSUE TITLE
`history` function hangs in master branch builld

### ISSUE THREAD

**Issue by amosbird** [fish-shell/fish-shell#5855]
fish version: 3.0.2-1004-ge8fd83ca

`history` function hangs.

**Comment by floam** [comment]
Specifically, it's not the builtin history itself, but the history function piping it to a pager: `builtin history | less`

**Comment by faho** [comment]
Yup, the `less` gets a SIGTTOU.

**Comment by faho** [comment]
Huh... this seems like that bufferfill process we create gets assigned the terminal?

**Comment by faho** [comment]
So what happens is that we run

```fish
builtin history | less
```

and we start `less` first, but then acquire the terminal again for `builtin history`.

**Comment by faho** [comment]
Okay, as far as I can see, there's three possible solutions here:

- Fork for the builtin, like bash does, and have it join the same pgroup as the external command
- Only acquire the terminal for the ~2 builtins that might actually use it (`read` and possibly `eval`)
- Have the external command stay in our pgroup if there's a builtin in the same pipeline.

The first seems crappy because it requires more forking (and wouldn't work with `read`), the second seems crappy because it still wouldn't fix `cat | read` and `read | cat`, and the third seems alright?

I'm going to implement it for now, if anyone knows of a better solution, feel free to revert my upcoming commit and implement that!

**Comment by ridiculousfish** [comment]
I ended up reverting this as a5a5ccb73db7884e0f0a084a134dc12c30336ec7 . Once the tests were running again I found the commit broke the tests. Also it feels wrong to not give external commands their own pgroup so I want to think more deeply about this.

**Comment by faho** [comment]
>Also it feels wrong to not give external commands their own pgroup so I want to think more deeply about this.

Okay. So as far as I can tell, we might need the terminal in both positions:

```fish
read | cat # `read` needs the terminal
```

and

```fish
cat | less # `less` needs the terminal
```

and in `read | less` both commands need the terminal.

Which means that they can't be different pgroups. And we can't fork for the builtin, because that means `read` can't propagate variable changes, so the builtin is in our pgroup. Which means the external command needs to be in our pgroup as well.

Does that make any sense?

An alternative that just papers over the problem is to only acquire the terminal for builtins that might need it, like `read` and `eval`. That fixes the immediate issue with `history`, because the builtin there is `history`. It's massively ugly, though, and the failure mode for `read | less` is absolutely awful.

**Comment by ridiculousfish** [comment]
I ended up fixing this similar to a5a5ccb but in a more modest way. I had the realization that the first process should always lead the pgroup, and if the first process is fish internal, then fish must lead the pgroup. So just check for that and claim the job's pgroup if the first process is fish.
