### ISSUE TITLE
`set_color` adds a new line

### ISSUE THREAD

**Issue by KuSpa** [fish-shell/fish-shell#5890]
### Specs:

echo $version `2.7.1`
uname -a `4.15.0-50-generic #54-Ubuntu`
echo $TERM `xterm-256color`

## Issue
set_color adds a newline at the end of my function :(
```
function fish_prompt
    echo '>> ' 
    set_color normal
end
```
results in 
```
>>
my command here
```
## Expected
```
>> my command here
```

**Comment by KuSpa** [comment]
reading the FAQ and `man echo` turns out, that I was missing a `-n` for the `echo` command. However I would update the [simple prompt examples](https://fishshell.com/docs/current/tutorial.html#tut_prompt) :)

**Comment by faho** [comment]
>However I would update the simple prompt examples :)

Yup, done.

There's a bit of a lie there in that you often don't need `echo -n` in a prompt, because we eat a trailing newline (nom!) in command substitutions (which the prompt is executed as).

So if you do

```fish
function fish_prompt
    echo something
end
```

that does the same as

```fish
function fish_prompt
   echo -n something
end
```

Because the newline is the last character. But add any output after it (like, say, a color sequence) and it's not the last character, so it stays.

But that's probably a bit too much for introducing the prompts in the tutorial.
