### ISSUE TITLE
Backward search and completion is broken

### ISSUE THREAD

**Issue by raichoo** [fish-shell/fish-shell#5891]
Apparently `dd4e0a3b6d4d5d5117c45c44319518ef4cb1c7e4` breaks all kinds of backward search for me.

OS FreeBSD

```
> keyword
backword search
> command that contains keyword<Return>
executes 'keyword' and not 'command that contains keyword'
```

Reverting named commit fixes the issues for me.

**Comment by floam** [comment]
Can you explain the steps to reproduce? The code you posted I can't make sense of.

**Comment by faho** [comment]
The issue here was that "ending" the search can mean two different things:

- Abort it, leaving the search term in the commandline
- Finish it, using the search item as the new commandline

And I only thought of the first! Sorry!

So for now I made it so only `cancel` (typically bound to escape) aborts, while everything else finishes. This is in line with the previous code, only it hardcoded it to escape and we no longer pass that char through here as a char.

**Comment by raichoo** [comment]
Thanks, that seems to work just fine!
