### ISSUE TITLE
Switchin to vim mode in tmux is slow

### ISSUE THREAD

**Issue by theScrabi** [fish-shell/fish-shell#5894]
```
OS: Linux Mint 19.1 Tessa x86_64
Kernel: 4.15.0-50-generic
Shell: fish 2.7.1
Terminal: gnome-terminal/xterm-256color
```

I have the issue that when pressing `esc` inside a tmux/screen session for entering the vim mode it takes fish a second until it actually is in that mode.  Can someone confirm similar issues, and if so would you know why it behaves like this and what could be done to enter that mode faster again?

**Comment by faho** [comment]
When fish switches vi-mode, it also reexecutes your prompt, so that it can display the changed mode.

In the coming release that's been refined to only reexecute fish_mode_prompt if possible.

What you want to do is to make your prompt faster.

>fish 2.7.1

Also I'd recommend upgrading to fish 3.0.2, which is faster in many ways. For Ubuntu and derivatives like Mint we offer [a PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3).

**Comment by theScrabi** [comment]
All right I upgraded. The issue is still there, but I'll wait until the next version :)

**Comment by faho** [comment]
>switching back works instantly

Aaaaah, okay. No, you're seeing something else: In a terminal, "alt" is also escape - if you press alt+g, what we see is an escape character and then a g. So to determine whether you pressed the actual escape key, we need to wait to see if we get something else.

The time we wait for is controlled via the $fish_escape_delay_ms variable, set to a value in milliseconds. It defaults to 100ms, which is way too high, and which is why it was reduced to 30ms in git master.

**Comment by zanchey** [comment]
From memory, there's a delay in tmux as well.

I set the following in my `.tmux.conf`:

```tmux
set-option -sg escape-time 50 # default is 500 msec, which makes vim awful to use
```

**Comment by theScrabi** [comment]
I see :D @zanchey your solution worked thanks :)
