### ISSUE TITLE
"open" builtin alternatives

### ISSUE THREAD

**Issue by JanczarKurek** [fish-shell/fish-shell#5901]
Let's talk about "open" builtin. In my opinion, it has some major drawbacks.

Current State
-------------------

First and most - it depends on some user-wide settings, for example, default program for opening .cpp file is the same, regardless of whether I am trying to open it from nautilius or fish. Lots of people are quite serious with the rule "what starts in terminal, stays in terminal" and would prefer nautilius to open clion, but fish to open vim.

Furthermore, for some types of files, I would like to specify default behavior, or pass by default some parameters without altering system-wide settings.

To be honest - adding new functionality to "open" sounds counter-intuitive, so I would like to propose zsh-like solution.

My Take
------------

Consider having new builtin lets say "assign_command" with simple syntax such as
```fish
assign_command ext "do something"
```
 As you would expect, after executing such  command, if you type

```fish
./my_file.ext
```

Would just call
```fish
do something ./my_file.ext
```

I am currently working on POC for this one, so it would be great to get some opinions whether or not this kind of feature would be accepted.

**Comment by faho** [comment]
>Let's talk about "open" builtin.

We don't really _have_ an open "builtin".

We have a function that defers to the OS-provided tools, and even that isn't used if a command called `open` exists (e.g. on macOS). It exists basically only so you can type `open` instead of `xdg-open`. And even that isn't universally loved (https://github.com/fish-shell/fish-shell/issues/5091#issuecomment-405113001).

And personally, I don't think we need to ship a thing where you can set that "*.txt" should be opened in "vim". Just use `vim file.txt` or `$EDITOR file.txt`.

Additionally, this can comfortable live as a "plugin" or just completely independent tool that works on all shells.

So I am rejecting this. Sorry!

**Comment by zanchey** [comment]
Yes, I concur - this is outside the scope of fish-shell.

**Comment by JanczarKurek** [comment]
Just want to point out - there is already some kind of "omit command" functionality shipped with fish-shell - directories can be opened without explicitly referring to "cd" command.

**Comment by faho** [comment]
>I mean, why the same argument does not apply to implicit cd?

Because `cd` *has* to be implemented in the shell. It's also much smaller in scope.
