### ISSUE TITLE
fish_color_* variables should use ANSI 4bit colors by default

### ISSUE THREAD

**Issue by bool3max** [fish-shell/fish-shell#5919]
The current default theme uses 24bit ("true") colors for `fish_color_*` variables. 

Having the default theme use sane (as in red for errors etc..) 4bit ANSI colors would allow users with pre-configured terminal palettes to have a nicer experience out of the box.

**Comment by faho** [comment]
We use truecolor so a theme looks like it's supposed to.

If you want your theme to look like your palette, set it up that way.

**Comment by faho** [comment]
That's probably overly dismissive, so let me try to explain my reasoning more clearly:

We have to pick one here - we can only either do truecolor, or not, by default.

Truecolor has the advantage that it expresses clearly which colors should be used, and the terminal gets that information and can act on it (notably this doesn't always mean exactly those colors are used - xterm doesn't), and it has a fighting chance of looking like the theme is supposed to look, across terminals and operating systems. But if a terminal decided that it wanted its palette to win, it would still have more information if we gave it truecolor, so it could then achieve *better results* than without.

So we chose it, and if you don't like it you can disable it via `set -U fish_term24bit 0`, and never have to worry about any of it again

It's also simply just a nice flashy feature that was quite a bit of work to get to enable by default, because getting the detection right was quite tough.
