### ISSUE TITLE
[200 when paste 

### ISSUE THREAD

**Issue by ldakhoa99** [fish-shell/fish-shell#5925]
$ fish --version
fish, version 3.0.2

## Issue 
When I paste something from clipboard I have [200...[201-
Example:
I copy `https://github.com/fish-shell/fish-shell/`
And when paste into terminal it will be `[200https://github.com/fish-shell/fish-shell/[200-`

I already put these code in config.fish but it not work
```fish
function __fish_disable_bracketed_paste --on-event fish_preexec
    printf "\e[?2004l"
end

```

**Comment by zanchey** [comment]
What terminal are you using?

To disable it completely, you need to do something like this in your `config.fish`:

```fish
function __fish_disable_bracketed_paste --on-event fish_prompt
    functions --query __fish_enable_bracketed_paste; and functions --erase __fish_enable_bracketed_paste
    printf "\e[?2004l"
end
```

This is because the setup for enabling bracketed paste runs in the first `fish_prompt` handler, so you can't override it directly in `config.fish`.

**Comment by faho** [comment]
@ldakhoa99 If I'm reading your [dotfiles](https://github.com/ldakhoa99/dotfiles) correctly, you're using tmux inside of iTerm2.

You also don't appear to have a lot of custom keybindings - just the fzf stuff, and ctrl-f for forward-char.

Can you run `bind \e\[200\~` and `bind -M paste \e\[201\~`?

My guess is this line in fish_variables is the culprit:

```
SETUVAR fish_key_bindings:fish_user_key_bindings
```

That sets *all the keybindings* to "fish_user_key_bindings", but that only defines:

```fish
function fish_user_key_bindings
    ### fzy ###
    bind \cr 'fzy_select_history (commandline -b)'
    ### fzy ###
end

fzf_key_bindings
```

Presumably your shell is still functional because it never erases the (very very sparse!) fallback bindings.

----

Please run `set -U fish_key_bindings fish_default_key_bindings`, and then try pasting again.

**Comment by ldakhoa99** [comment]
Thanks, @faho @zanchey, I solve with put @zanchey function into `config.fish`.
and then run `set -U fish_key_bindings fish_default_key_bindings`

**Comment by faho** [comment]
No, don't. Remove the function, you don't want to turn off bracketed paste - there is no reason to do so, and numerous against it.
