### ISSUE TITLE
Tab autocompletion not working

### ISSUE THREAD

**Issue by n3o77** [fish-shell/fish-shell#5955]
I'm on fish 3.0.2 on OSX Mojave with Iterm 3.3.0 Beta.
When I want to switch through autocomplete suggestions (i.E. files) the tab button won't select the first result. But hitting tab shows the suggestions list, just doesn't select one. If i use shift + tab then both work fine. If I use `sh -c 'env HOME=$(mktemp -d) fish'` everything works fine, so i guess i accidentally changed a setting. I tried to find something for the past hour but tbh i'm not sure what the best way is to tackle this issue and where to look. Any help would be very appreciated.

**Comment by faho** [comment]
Which command are you trying to complete?

Is tab still bound to `complete` - see `bind \t`?

**Comment by n3o77** [comment]
thanks so much for the quick response and even solution. i had a second binding to `bind -m expand \t expand:execute` which blocked it. After removing this one everything is working again.

**Comment by sugamkarki** [comment]
Its not working in mine either. How can I enable it?  ```complete | grep \t ``` is empty.

**Comment by faho** [comment]
@sugamkarki You want `bind \t`, like I mentioned above. `complete` prints what sort of things fish knows to complete, and `grep \t` passes a literal tab character to `grep`, so it would not find the text `\t`.

Most likely something in your configuration, including any plugin you installed, changed your binding and it doesn't work anymore.

Also: In future, please open a new issue or ask on https://gitter.im/fish-shell/fish-shell. This issue is very old, closed, and most likely a different problem.
