### ISSUE TITLE
Suggestion/question: alternative bindings for alt-up/alt-down

### ISSUE THREAD

**Issue by mfilej** [fish-shell/fish-shell#6009]
I'm noticing that most (if not all) bindings that use arrow keys also have alternatives closer to the home row. For example, `up`/`down` also work as `ctrl-p`/`ctrl-n`, `alt-left`/`alt-right` can instead be used as `alt-b`/`alt-f`, etc.

As far as I can tell there are no alternatives for `alt-up` and `alt-down` and I find myself not using them as often as I could, because I have to reach for the flimsy up/down keys on the laptop keyboard.

I was also wondering how to rebind those myself—I wasn't able to find the right function names on [this list](http://ridiculousfish.com/sphinx-demo/cmds/bind.html#special-input-functions) nor the default bindings for these key combinations in the output of `type fish_default_key_bindings`.

**Comment by faho** [comment]
The way to find a keybinding is to start `fish_key_reader` and press that combination. That will then tell you the sequence, in this case the output will probably (these sequences aren't standardized, which is why `fish_key_reader` is important here, but this is a common one) be something like 

```fish
bind \e\[1\;3A 'do something'
```

So you execute `bind \e\[1\;3A` to just list what it is bound to, and that will print

```fish
bind --preset \e\[1\;3A history-token-search-backward
```

So it's the "history-token-search-backward" function. Then you put `bind somethingelse history-token-search-backward` (without the "--preset" - that's for when you want to make a full binding set like `fish_default_key_bindings`) into your config.fish.

Repeat for alt-down and you're done.

**Comment by mfilej** [comment]
Thanks, that was super helpful! And `fish_key_reader` is amazing, thanks for the tip.

I was able to bind the functions to my liking, so that's awesome.

I was wondering if `history-token-search-backward` and `history-token-search-forward` should be added to the docs and the man page? I'm happy to look into it and submit a pull request.

* * *

One more thing out of curiosity: when I press alt-up or alt-down in the key reader I get this:
```
~ ❯ fish_key_reader                                                                                                                        ↪ 127
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.738 ms)  hex:   1B  char: \c[  (or \e)
(  0.809 ms)  hex:   5B  char: [
(  0.870 ms)  hex:   42  char: B
bind \e\e\[B 'do something'
~ ❯ fish_key_reader
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.885 ms)  hex:   1B  char: \c[  (or \e)
(  1.072 ms)  hex:   5B  char: [
(  0.998 ms)  hex:   41  char: A
bind \e\e\[A 'do something'
```

Is `\e` supposed to appear twice or is this a misconfiguration in my shell?

**Comment by faho** [comment]
>Is \e supposed to appear twice or is this a misconfiguration in my shell?

That's what your terminal sends, apparently. The shell doesn't really have anything to configure.

>I was wondering if history-token-search-backward and history-token-search-forward should be added to the docs and the man page? I'm happy to look into it and submit a pull request.

Yeah, that would be nice. The docs are built with sphinx (in git, the releases used doxygen but we've switched since), and the correct place to add this would be [the bind page](https://github.com/fish-shell/fish-shell/blob/master/sphinx_doc_src/cmds/bind.rst).

**Comment by zanchey** [comment]
This seems to be sorted.
