### ISSUE TITLE
Function autoloading vs aliasing

### ISSUE THREAD

**Issue by patrickf3139** [fish-shell/fish-shell#6023]
Hi, back when I got into fish a long time ago, I remember there was some sort of push for people to autoload their functions rather than creating aliases for them in their config.fish as that would speed up shell start up. My memory is now hazy and I don't exactly remember why anymore. Based on my best understanding, I think these are the pros and cons of autoloading compared to aliases. Could someone verify this or correct me or add to my list?

Pros of autoloading
- fish doesn't have to load the function on every startup
- changes to autoloaded functions propagate through all shells without having to re-source anything

Cons
- one the first execution of the autoloaded function, fish has to do IO to find the file and load it
- won't know if there's a syntax error with the definition until trying to execute it

**Comment by faho** [comment]
>I think these are the pros and cons of autoloading compared to aliases.

Wrong dichotomy!

Fish does not know about "aliases". There's an `alias` function that creates functions, for people used to doing that from bash, zsh et al.

You can run `alias foo=bar; funcsave foo`, and it'll create an autoloaded function file from the "alias".

Or you could create a function file with multiple functions in it, or put all your functions into config.fish.

>one the first execution of the autoloaded function, fish has to do IO to find the file and load it

This is basically a non-issue. You don't execute enough different functions for the first time for this to matter, and even across shells the IO is often nearly free because the OS caches it.

>won't know if there's a syntax error with the definition until trying to execute it

This is also basically a non-issue - you need to test your functions anyway.

>fish doesn't have to load the function on every startup

This is the big one - if we eagerly loaded every function file on fish's startup, it'd take ~200ms per shell start on my system, and I don't have tons of functions and a fairly fast SSD.

If you use big third-party frameworks like oh-my-fish and rotating rust, you'd have a worse time.

Now, obviously this could also be improved by e.g. concatenating all the function files into one, but that'd be quite the bit of spaghetti.

But that's from the POV of writing fish - from a user's perspective, these things already use autoloading, and you're probably writing fewer functions that fish ships.

Personally, I think organization is largely a matter of personal preference - pick and choose how you organize your functions, we just give you tools to do so.

Whether you should use `alias` or `function`? I'd pick `function` most of the time, unless you're doing a ton of aliases of the `alias gs="git status"` variety, in which case I'd think about using `abbr` instead.

The reason being that `alias` is slower because it's a function itself that does a bunch of work every time that `function` can skip. It's also not really the native syntax and discouraged even in bash.

**Comment by patrickf3139** [comment]
@faho First, thank you so much for maintaining and improving fish! And thank you for answering my question with such generous insight and patience.

I have a clarification questions 
> If you use big third-party frameworks like oh-my-fish and rotating rust, you'd have a worse time.

Sorry what's rotating rust (typo?)? But mostly I don't understand why third party frameworks are worse. Which is important to me because I used to use OMF and now use fisher.

**Comment by zanchey** [comment]
Rotating rust is a term used to describe magnetic storage-based hard drives (which have worse latency and often speed compared to SSDs).

Third-party frameworks allow you to install lots of functions into the autoload directories, which would cause significant slowdown on startup if they were all loaded straight away.

**Comment by patrickf3139** [comment]
Ah thanks for the clarification. I get it now!
