### ISSUE TITLE
Build failure on older G++

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#6027]
fish master fails to build from source on older versions (4.8 and 4.9) of GCC:

```
/usr/src/packages/BUILD/src/history.cpp:838:45: error: cannot convert 'const file_id_t' to 'dev_t {aka long long unsigned int}' in initialization
      file_id_t history_file_id{kInvalidFileID};
```

**Comment by faho** [comment]
Can you try with the old-style

```c++
file_id_t history_file_id = kInvalidFileID;
```

?

**Comment by zanchey** [comment]
Yes, that builds.

**Comment by faho** [comment]
Okay, so let's just return to that old style for the time being, in this case.

I don't think there's any advantage here (since AFAIK that's mostly related to type inference, and that's not happening here - it's doing const file_id_t to file_id_t), but I wouldn't forbid the newer style in general, because it seems to work for the most part.
