### ISSUE TITLE
A way to disable the WSL update warning

### ISSUE THREAD

**Issue by no-boot-device** [fish-shell/fish-shell#6038]
`fish, version 3.0.2-1440-g2ddde381`
`Linux cyberia 4.4.0-17134-Microsoft #706-Microsoft Mon Apr 01 18:13:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`
I *know* I'm out of date, but unfortunately, I can't do anything about it at this point of time. There appears to be no way to disable this warning.

**Comment by ridiculousfish** [comment]
What does the warning say?

**Comment by zanchey** [comment]
https://github.com/fish-shell/fish-shell/blob/ce178fd6fda1e6b4b9fe50d53042f787d9d81377/src/common.cpp#L169-L177 as part of #5661

Does fish actually work in that environment? The comments in #5298 and #5661 make it sound like it's either silently or noisily broken.

**Comment by ridiculousfish** [comment]
Oh no

**Comment by ridiculousfish** [comment]
From 552af31ab0. @no-boot-device it looks like there's no easy way to silence this warning in released fish, unless you are comfortable running atop master?

**Comment by no-boot-device** [comment]
Yeah, no, I'm fine with either being patient or being atop master. What would I have to do in master?

**Comment by ridiculousfish** [comment]
I will just remove the warning. I don't think it's appropriate for the shell to push the user to update their OS. Thanks for filing!

**Comment by zanchey** [comment]
AIUI, the shell is effectively inoperative on that OS version, so it's either silently broken or noisily broken.

**Comment by mqudsi** [comment]
It's not a "warning" in the sense that "hey, be careful" so much as it is a "don't bother using fish, it's not going to work." It's not a *suggestion* to upgrade, it's a requirement for fish to work correctly.

I would like to revert 5101bdeb9f2d2d0a362619edde3da8c1b9cd7101 [for the reasons outlined here](https://github.com/fish-shell/fish-shell/commit/5101bdeb9f2d2d0a362619edde3da8c1b9cd7101#commitcomment-34824395).

**Comment by faho** [comment]
If it really is worthless, I would actually make it a hard error.

**Comment by mqudsi** [comment]
I had worked around the issues in the 3.0 `master` builds but after code review from *I think* @ridiculousfish we decided to remove the workarounds since they added a lot of stinky code smell and a working WSL release was pushed to production prior to 3.0 shipping. Fish 2.0 was silently broken and did not visibly warn about it. Fish 3.0 shipped with the workarounds removed (and I believe this message in place).

@ridiculousfish requested I include some sort of workaround in the discussion over at 5101bdeb9f2d2d0a362619edde3da8c1b9cd7101, so af4b54e63567906f51b777ba6118b49686e22f6e changes the (reverted) check and associated startup message from a warning to a hard error but also simultaneously introduces an intentionally undocumented `FISH_NO_WSL_CHECK` environment variable that bypasses the check entirely (on your own head be it, though!).
