### ISSUE TITLE
set append/prepend shouldn't clear exported status unless --unexport is specified

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#6094]
In fish 3.0.2, using `set --prepend` or `set --append` on an existing variable with one of the scope flags (e.g. `--local`) clears the exported status of that variable. This is rather surprising, the exported status of the existing variable should only be cleared if `--unexport` is specified since the `--append` or `--prepend` flag is attempting to modify the existing variable.

```
> set -lx foo a
> set -qlx foo; echo $status
0
> set -al foo b
> set -qlx foo; echo $status
1
```

**Comment by lilyball** [comment]
I realize that e.g. `set foo bar` preserves exported status but `set -l foo bar` clears it. I find this surprising as well (specifying a scope just identifies what variable I'm modifying), but less surprising than the append/prepend issue behavior.

**Comment by mqudsi** [comment]
I personally would imagine that defining a variable in a new scope should not automatically export the local variable.

Imagine a user has an exported variable `foo` in the global scope, then runs a completion that for some reason *locally* defines the same variable `foo` to have a different value. Environment variable `foo` affects how an external command `bar` runs, and that completion executes `bar` (not intending to change its behavior from that which the user overrode).

`set -l foo` defines a *new* variable in a new scope, and that variable should not magically be exported just because a completely different variable that happened to exist and share the same name was. But I definitely agree that the `prepend`/`append` issue is a bug and should be fixed.

**Comment by lilyball** [comment]
> I personally would imagine that defining a variable in a new scope should not automatically export the local variable.

I didn't suggest it would. I was referring to overwriting a variable with a new value at the same scope. For example, consider the following code:

```fish
set -el foo # make sure we have no local foo
set -gx foo bar
set foo baz # modifies the global foo, still exported
set -g foo qux # modifies the global foo, no longer exported
```

I consider this to be surprising behavior. Especially if I were doing a modification like `set -g foo $foo[1] bar $foo[2..-1]` which is very clearly a modification to an existing value.

In fact, checking the documentation on `set` right now, the fact that `set -g foo bar` doesn't preserve the existing exported status of `foo` violates the documented behavior:

> The exporting rules when creating or updating a variable are identical to the scoping rules for variables:
> 
> 1.  Variables may be explicitly set to either exported or not exported. When an exported variable goes out of scope, it is unexported.
> 
> 2.  If a variable is not explicitly set to be exported or not exported, but has been previously defined, the previous exporting rule for the variable is kept.
> 
> 3.  If a variable is not explicitly set to be either exported or unexported and has never before been defined, the variable will not be exported.

(copied straight from the fish 3.0.2 `set -h` output)

---

That said, talking about `set -g foo` is somewhat tangential because this particular issue was specifically filed on `--append` / `--prepend`, where it's very clearly trying to modify an existing variable. Of course, if we do want to fix `set -g foo bar` to conform to documentation and preserve existing exported status, that would naturally fix `set -gp` as well.

**Comment by ridiculousfish** [comment]
Yep I agree, nice.
