### ISSUE TITLE
`history delete` doesn't remove anything

### ISSUE THREAD

**Issue by rien333** [fish-shell/fish-shell#6142]
Previous versions of `history delete <term>` used to give you a deletion menu, or at the very least delete stuff. Now nothing happens at all, except when I add `-c` to the deletion command (note the spaces that prefix my `history` commands so that they themselves are not included):

```fish
> echo bar
bar
>  history | grep bar | head -1 
echo bar
>  history delete bar 
>  history | grep bar | head -1
echo bar
```

System info:
```fish
> fish --version
fish, version 3.0.2-1582-g4747bdd7e
> uname -a
Linux **** 5.3.1-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 21 11:33:49 UTC 2019 x86_64 GNU/Linux
> echo $TERM
xterm-kitty
```

`history delete` might have been broken since https://github.com/fish-shell/fish-shell/issues/6070.

**Comment by faho** [comment]
Well, no. It's not broken, it's just now searching for *exact* matches, instead of containing matches like it did previously, contrary to the documentation.

Do `history delete 'echo bar'` and it'll delete your `echo bar`.

However, I do believe that offering containing matches is a better solution. We should revert the behavior and change the documentation instead.

@zanchey, any objections?

**Comment by zanchey** [comment]
I mean, this was an unintended behaviour change in 2.4.0, but I'm really not fussed either way.
