### ISSUE TITLE
How to Pass Multiple Arrays as Arguments to a Function

### ISSUE THREAD

**Issue by mingcenwei** [fish-shell/fish-shell#6150]
- Fish version: 3.0.2
- OS version: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
- Term: xterm-256color
- Problem persists irrespective of HOME environment variable

Currently it seems there's no natural way to pass multiple arrays as arguments to a function.

Sample code:
```fish
#!/usr/bin/env fish
function func -a numbers colors
    for number in $numbers
        for color in $colors
            echo "$color""$number"
        end
    end
end

set var1 1 2
set var2 'red' 'green' 'blue'

func $var1 $var2
echo
func "$var1" "$var2"
```

Output
```
21

red green blue1 2
```

However, I want to find a way to print this result
```
red1
green1
blue1
red2
green2
blue2
```

**Comment by faho** [comment]
Yes, and that's a pretty fundamental part of how shell scripts in general work - arguments are purely positional.

Even the named arguments are currently just names for the argument in that position.

If you want to make a function act on multiple arrays, you'll have to work around it by

- using global variables
- using a delimiter (e.g. joining the arguments with "," or something)
- passing one array via stdin, the other as arguments
 or 
- exporting the variables and passing the name like

```fish
set -x numbers 1 2
set -x colors red green blue
function func -a numbervar -a colorvar
    for number in $$numbervar
        for color in $$colorvar
            echo $color$number
        end
    end
end
func numbers colors
```

Or any other way you can think of.

We have no plan to change this because it's a fundamental limitation of UNIX for external commands, so it would require a different way of calling functions with passed arrays. Also because it is a fundamental UNIX limitation commands tend to be written in a way that deals with it (see how often you get commands that require comma or colon-separated lists of things).
