### ISSUE TITLE
How to make MC to use EDITOR as set up in fish?

### ISSUE THREAD

**Issue by bvn13** [fish-shell/fish-shell#6162]
My environment:
1. fish, version 2.7.1
2. Linux boyko-v 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
3. xterm-256color

I have an issue with midnight commander using fish shell underneath.
I have set up emacs-daemon and want to use emacs as client to this daemon.
So I create a function to start emacs as client:

```
> cat ~/.config/fish/functions/emacst.fish 
function emacst
    emacsclient -t $argv;
end
```

Although I've use this environment
```
> cat ~/.config/fish/config.sh
set -x -g EDITOR emacst
> echo $EDITOR
emacsclient -t
```
or even 
```
> cat ~/.config/fish/config.sh
set -x -g EDITOR emacsclient -t
> echo $EDITOR
emacsclient -t
```
when I start MC and edit any file it opens emacs in GUI mode not using emacs-client.

How to set it up properly?

**Comment by bvn13** [comment]
UPD:

When I start MC with
```
env EDITOR=emacst mc
```
it cannot edit eny file.

**Comment by faho** [comment]
>when I start MC and edit any file it opens emacs in GUI mode not using emacs-client.

In short, the easy solution is to upgrade fish to 3.0.2. We've changed how lists are exported in that so it should now work.

In fish < 3, you want to set $EDITOR to one string like `set -gx EDITOR "emacsclient -t"`.

----------------

>When I start MC with

>env EDITOR=emacst mc

>it cannot edit eny file.

That's to be expected. Functions do not exist outside of fish, so `mc` can't find anything called `emacst`. If you need it to be used, you'd have to put the code into a full script instead of just a function.

E.g. instead of

```fish
function emacst
    emacsclient -t $argv;
end
```

in ~/.config/fish/functions/emacst.fish, create a file called `emacst` in ~/.local/bin, add

```fish
#!/usr/bin/env fish
emacsclient -t $argv
```

`chmod +x` it and add ~/.local/bin to $PATH (e.g. via $fish_user_paths).

**Comment by bvn13** [comment]
@faho 

>> when I start MC and edit any file it opens emacs in GUI mode not using emacs-client.

> In short, the easy solution is to upgrade fish to 3.0.2. We've changed how lists are exported in that so it should now work.

Does not work for me.

```
> fish --version
fish, version 3.0.2
> echo $EDITOR
emacsclient -t
```

When I try to edit any file in MC now it throws an exception in console:
```
error: unknown command "/home/bvn13/.config/fish/config.fish", see 'snap help'.
```

**Comment by faho** [comment]
Apparently this is just how mc works. Setting $EDITOR to `emacs -nw` doesn't work for me in fish, neither does setting it to `"emacs -nw"` in bash. It'll just open `emacs`.

It used to be a bug that it wouldn't open it at all (http://midnight-commander.org/ticket/1425), but now it just ignores everything after the space.

So you'll have to make a script and point $EDITOR to that.

**Comment by bvn13** [comment]
@faho Thanks. It was done with script as you mentioned. Thanks.
