### ISSUE TITLE
How to test if the result of a command is empty?

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#6173]
fish 3.0.2

I would like to test if a dir is empty.

```
test -z (ls -A)
test: Expected a combining operator like '-a' at index 2
```
I tried `test -z "(ls -A)"` but it doesn't work.

- If I try this in an empty dir, it works fine.
- If I try in a dir with 1 file, it works fine
- If 2 files in that dir, `test: unexpected argument at index 2: 'test1'`
- If 3 files in that dir, `test: Expected a combining operator like '-a' at index 2`

**Comment by faho** [comment]
Unfortunately `test` is awful, and `test -z` is true (this is because our `test` is POSIX-compatible, and POSIX demands that `test` with any one non-empty argument return true).

That means you'll have to save the command's output to a variable and test that:

```fish
set -l var (ls -A)
test -z "$var"
```

Or use `not string length -q -- (ls -A)`.

(and yes, there are numerous issues open about `test` being badly in need of a replacement - e.g. #6124, and also issues about better command substitution #159)

**Comment by BarbzYHOOL** [comment]
ok thank you, both are not easy to remember :(

**Comment by faho** [comment]
That's almost entirely unrelated to what this issue is about, and easy enough to write yourself.

Try

```fish
function is_empty_dir
    test -d "$argv"
    or return 1 # not a directory, so not an empty directory
    # count counts how many arguments it received
    # if this glob doesn't match, it won't get arguments
    # and so it will return 1
    # because we *want* an empty directory, turn that around.
    # the `{.*,*}` ensures it matches hidden files as well.
    not count $argv/{.*,*} >/dev/null
end
```

**Comment by stephane-archer** [comment]
Thank you for your help. I don't think it's unrelated, the message is starting with "I would like to test if a dir is empty."
