### ISSUE TITLE
Why is systemctl's wildcards unable?

### ISSUE THREAD

**Issue by ddgreen** [fish-shell/fish-shell#6175]
Hi.

I often use `systemctl restart neutron-*agent.service`.
This command is valid in bash.

But, I found this command invalid in fish.
```
root@ubuntu ~# systemctl restart neutron-*agent.service
fish: No matches for wildcard “neutron-*agent.service”. See `help expand`.
systemctl restart neutron-*agent.service
```

Please tell me why.

Thanks.

**Comment by ddgreen** [comment]
example service
```
neutron-dhcp-agent.service         neutron-ovs-cleanup.service
neutron-metadata-agent.service     neutron-server.service
neutron-openvswitch-agent.service
```

**Comment by faho** [comment]
TL;DR: Quote wildcards. Not just in fish, but also in other shells.

----

`systemctl` in this example is never run, because fish tries to match the wildcard to *files* (because `*` is the glob operator, so it matches files).

Bash also tries this, but has (by default) a misfeature where, if it doesn't match anything, it will pass the unexpanded glob along.

This means if there are matching files it will only pass them. E.g. try the following in bash:

```bash
touch neutron-bananaagent.service
systemctl restart neutron-*agent.service
```

See also http://mywiki.wooledge.org/BashFAQ/004.

**Comment by ddgreen** [comment]
Oh, I have misunderstood.
Thanks.
