### ISSUE TITLE
Broken flags after function definition with named args

### ISSUE THREAD

**Issue by amiller27** [fish-shell/fish-shell#6186]
fish version: fish, version 3.0.2-1620-g055a3321
OS: Ubuntu 18.04
Terminal: terminator

a7913c3 (the fix for #6147) breaks function definitions that look like this:
```
function _pisces_bind_pair -a mode left right -d "Creates bindings for the given pair: autoclose and skip closing symbol"
```

Definitions like this are common in packages, that example is taken from laughedelic/pisces, it also breaks oh-my-fish/theme-bobthefish and probably others.  It seems like the solution would be to assume the argument names end when another flag is encountered instead of erroring out.

**Comment by faho** [comment]
> breaks function definitions

Not *quite*. The function definition was already broken, in that the options were never applied (instead variables with those names were defined), only fish never complained.

However I agree that this isn't an acceptable way to fail.

We should just pass all free arguments (those not belonging to any option) to `--argument-names` if it has been given (excluding the first of course, because that's the function name).

For the time being, let's revert a7913c3.

**Comment by amiller27** [comment]
Even arguments that are passed before `--argument-names` or after other options?  So in the definition
```
function foo a --argument-names b --no-scope-shadowing c
```
the argument names would be `a b c`?  That seems much less intuitive than what I was intending to do (treat non-options between `--argument-names` and the next option as the argument names) but if that's what you want I can change the PR.
