### ISSUE TITLE
make git completion work with --git-dir (and --work-tree)

### ISSUE THREAD

**Issue by fdupress** [fish-shell/fish-shell#6219]
Git completion assumes it is being run in a "standard" working tree, where `git rev-parse --git-dir` behaves nicely. This causes some frustration when dealing with git repositories where the git directory is separate from the working tree (or trees).

`git rev-parse` (obviously) takes account of any `--git-dir` and `--work-tree` parameters. (So that `git --git-dir=foo rev-parse --git-dir` returns `foo` as expected if `foo` is a git directory, and similarly with `git --work-tree=foo rev-parse --show-toplevel`.) It also provides ways to test if we are in the work tree or git directory (using `--is-inside-git-dir` or `--is-inside-git-tree`).

Updated to reflect a slightly more thorough reading of git-rev-parse's documentation (and in particular, the existence of the `--show-toplevel` option for file).

**Comment by krobelus** [comment]
Yeah, then we could also parse `-C`. from git's man page:
> For example the following invocations are equivalent:
>              ` git --git-dir=a.git --work-tree=b -C c status`
 >              `git --git-dir=c/a.git --work-tree=c/b status`

Also typing `git checkout <TAB>` inside a bare repo prints an error. (we cannot do git checkout without knowing the worktree location). Same when inside the git dir.
There's probably a lot more but let's focus

**Comment by zx8** [comment]
Would be great to support the associated environment variables as well, `GIT_WORK_TREE` and `GIT_DIR`.

https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

**Comment by krobelus** [comment]
I have added support for flags like `--git-dir` in my [branch](https://github.com/fish-shell/fish-shell/compare/master...krobelus:git-completions), which also fixes the errors I mentioned. It's WIP but everything seems to work fine.

> Would be great to support the associated environment variables as well, `GIT_WORK_TREE` and `GIT_DIR`.
> 
> https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

Good catch; this already works if these environment variable are exported (because git completions call git from the same environment as the actual command).
If however, you use something like `env GIT_DIR=/repo.git git log <TAB>` this won't work, and that's probably not gonna be changed before we have good subcommand support - something like `and git <TAB>` does not work at all, see #2705.

**Comment by zx8** [comment]
@krobelus That's great – does that mean that this will now be possible: https://gitter.im/fish-shell/fish-shell?at=5d08a4018e050f62aa415ee6?

**Comment by krobelus** [comment]
@zx8 Yes, something like `complete -c foo --wraps 'git --git-dir repo.git --work-tree repo'` (or `-C` but that will mess up relative paths) will work with my changes, I will create a PR soon.

**Comment by fdupress** [comment]
Just so you guys know: I lost the ability to test this almost as soon as I opened the issue. I'll give it a try on other platforms as soon as I can.
