### ISSUE TITLE
sudo tab-completion does not suggest binaries in /sbin any more

### ISSUE THREAD

**Issue by lord-carlos** [fish-shell/fish-shell#6259]
Hey guys. I updated from debian oldstable to stable. 2.7.? to fish, version 3.0.2

Now it can't complete programs that are in `/sbin` or `/usr/sbin` with sudo.
For example `sudo send<TAB>` does not complete to `sudo sendmail`, it does so in bash. Also worked fine with fish 2.7.? and debian oldstable.

Both path are not in `$PATH`. Should I add them? It was not needed before. And bash also does not need it.

Linux cube 5.2.0-0.bpo.3-amd64 #1 SMP Debian 5.2.17-1~bpo10+1 (2019-09-30) x86_64 GNU/Linux
echo $TERM: screen

 `sh -c 'env HOME=$(mktemp -d) fish'` does not help

**Comment by zx8** [comment]
I actually think fish 3.0.x is correct here and fish 2.7.x (presumably) contained a bug whereby `sbin` paths were checked for binaries, regardless of what was on the user's `$PATH`.

`sbin` paths (e.g. `/sbin`, `/usr/sbin`, etc.) contain the "system" binaries and traditionally will not be on the user's `$PATH`, but will be on the `root` user's path, i.e.

```
$ docker run -it --rm debian:10.1

root@d22cbabbd0b3:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

root@5d4c6d372cb6:/# adduser --disabled-password --gecos "" foo
Adding user `foo' ...
Adding new group `foo' (1000) ...
Adding new user `foo' (1000) with group `foo' ...
Creating home directory `/home/foo' ...
Copying files from `/etc/skel' ...

root@5d4c6d372cb6:/# su - foo

foo@5d4c6d372cb6:~$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

In the above session, attempting to complete any binaries within the `sbin` directories does not work, as I would expect, and I can only assume the fact that it worked before on fish 2.7.x was indeed a bug that has since been fixed.

That said, checking my `~/.config/fish/config.fish` on macOS, I can see that I have manually added `/usr/local/sbin`, `/usr/sbin` and `/sbin` to my `$PATH`, so you may want to do the same if you intend to run them via `sudo`.

I don't think it makes sense - or is worth the additionally complexity - to attempt to do something smart and e.g. try to check the effective user's `$PATH` when running `sudo [-u]`.

IMO the easiest option is just to add the `sbin` directories to your own user's `$PATH` and be done with it. 😄

**Comment by zanchey** [comment]
`__fish_complete_subcommand_root` adds those paths before calling `__fish_complete_subcommand`, but 1c4940c04c133e434e32ca25e1366625ff1bb413 added completions with `complete -C` (which loops back into the normal complete machinery). I'm not sure why that's not combined with the use of `__fish_complete_subcommand_root`, though.

**Comment by lord-carlos** [comment]
Hey @zanchey 
Thanks for the quick help and confirmation.
Can you think of any workaround I can use while this is getting patched?
Is it not a bit weird that I'm the first one to notice this?

With kind regards.

**Comment by faho** [comment]
I would imagine most users on linux now run with a merged /usr.

I don't have a split-/usr machine to test, but I'd imagine copying the sudo completion script (at e.g. /usr/share/fish/completions/sudo.fish) to ~/.config/fish/completions/sudo.fish and adding `set -lax PATH /sbin /usr/sbin` in the right place might work.

**Comment by zanchey** [comment]
Oh right, it got wiped out entirely by 76749468aa248331aa4dcae8e91d4a4a4ebdc0e1.
