### ISSUE TITLE
Tab completion sub-selection highlighting bleeds past last result

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#6263]
```
$ fish --version
fish, version 3.0.2-1733-gdeefdaec
```

---

## Problem

![image](https://user-images.githubusercontent.com/8544900/67849688-ea3cc880-fafe-11e9-8085-d81ed861bb34.png)

## Repro

![out](https://user-images.githubusercontent.com/8544900/67963924-4edb4e80-fbf7-11e9-9198-65257f32c892.gif)

**Steps:**
```fish
$ git --<TAB>
# hit CTRL+S to enter 'search' mode
# type 'w' to filter results containing 'w'
```

**Comment by faho** [comment]
Bisects to d502ad2c253d931a1674909a4b402285e8c4a4cf, so let's just revert that.

**Comment by PerBothner** [comment]
Actually, the bug is not directly due to the reverted change.

Rather, the problem is a pre-existing missing `s_set_color`.

I created pull request  #6275 to un-revert the clr_eos change, but with the missing s_set_color call.
Conceptually, there should perhaps be two separate pull-requests (one to add the missing s_set_color, one to revert the reversion).
