### ISSUE TITLE
Builtin math: `^` operator is left-associative

### ISSUE THREAD

**Issue by 0x005c** [fish-shell/fish-shell#6280]
The result of `math '3^0.5^2'` is currently:
```
~> math '3^0.5^2'
3
```
That mean, `^` operator is left-associative.
I think this is a bug because exponentiation operators in many languages are right-associative.

version:
```
~> fish --version
fish, version 3.0.2-1757-g47c0b5f9
```

**Comment by ridiculousfish** [comment]
Seems like a fun isolated bug to tackle for anyone interested. Thanks for filing!

**Comment by asprazz** [comment]
Hie @ridiculousfish, I am really interested. Issue is really interesting and as I am new here I will need a little help. I have built it and I am looking into tinyexpr.cpp but not sure about changes..

**Comment by floam** [comment]
Easy fix. This is configurable in upstream TinyExpr and that author just likes the left-to-right because that's how spreadsheets do it. I think it will confuse people. I'll change it.

**Comment by floam** [comment]
Or if you want to give it a shot @asprazz, go ahead! Look at this code upstream:

https://github.com/codeplea/tinyexpr/blob/ffb0d41b13e5f8d318db95feb071c220c134fe70/tinyexpr.c#L415

See it has a compile time option for `TE_POW_FROM_RIGHT`? That provides a different version of the `factor()` function which has a while loop with different logic. Ours needs to be adapted to do the same thing. It's a little tricky because we've diverted our code from theirs quite a bit but it might be a fun practice to try to apply the same differences you see to our codebase if you like!

**Comment by asprazz** [comment]
@floam Thank you for clarification. I will be working on this now.. :) :100:

**Comment by asprazz** [comment]
Hie @floam, Can you please look into my changes ?
I have removed a bunch of code saying => -a^b = -(a^b) as -2^2 = 4 not -4
Not sure about this tho :)

**Comment by ArashPartow** [comment]
This issue was raised with the author a long time ago:

https://github.com/codeplea/tinyexpr/issues/10#issuecomment-241535479
