### ISSUE TITLE
Fish shell daemon breaks invocation from other command

### ISSUE THREAD

**Issue by kuon** [fish-shell/fish-shell#6326]
fish, version 3.0.2

I am using rua, which spawns the shell for package analysis, but fish seems to behave differently than other shells.

Relevant issue: https://github.com/vn971/rua/issues/90

**Comment by faho** [comment]
Looks like #5663 - it's not that the keys are "ignored", it's that we forgot to turn terminal modes back to normal, so you don't see output because terminal echo is off, and pressing enter doesn't work because we've turned on distinguishing between \n and \r, so you'll have to press ctrl-j. (fish turns it off because it handles output itself for syntax highlighting and wants to allow binding ctlr-j and ctrl-m to different things).

And I can indeed reproduce the issue with 3.0.2 and can confirm it works with current master.

**Comment by kuon** [comment]
Great, sorry for duplicate issue.

Cheers.
-- 
Nicolas Goy
