### ISSUE TITLE
HAVE_STD__MAKE_UNIQUE doesn't work

### ISSUE THREAD

**Issue by neheb** [fish-shell/fish-shell#6357]
If in CMakeLists.txt you change the CXX standard to 14 and above, it fails to compile as make_unique becomes ambiguous.

**Comment by faho** [comment]
Okay.

For the record we currently have no plans to move beyond C++11. The newer standards don't change as much as that one did and support still isn't ubiquitous, especially given we still try to support old RHEL and Illumos.

So currently that's a "don't to that, then".

**Comment by ridiculousfish** [comment]
This is because we set [cmake policy CMP0067](https://cmake.org/cmake/help/v3.8/policy/CMP0067.html) to OLD, which is empirically required to build PCRE.

C++14 is pretty minor so I expect fish will leapfrog it. I don't think we want to dig into the PCRE build failure, so I'm closing as NTBF. Of course we'll take a PR if you want dig into the PCRE build failure. Thanks for filing.

**Comment by neheb** [comment]
BTW this recently broke with the gnu++11 change.
