### ISSUE TITLE
RFC: Bytecode for fish scripts

### ISSUE THREAD

**Issue by danzimm** [fish-shell/fish-shell#6381]
Hey folks, this morning I was playing with the idea of creating a fish bytecode to try and optimize script performance. I was thinking of a model similar to python where some sort of "optimized" script could be placed next to the fish script itself. I have a couple of comments before we get started with the discussion:
- I'm not super familiar with the internals of interpreting scripts, so there may be some optimizations around this already. If that's the case point me to that code and I'll close this issue!
- This idea isn't super thought out at the moment, just something in passing. My motivation lies in improving startup time- I have quite a few startup scripts and they take a non-negligible amount of time to run on my decked-out iMac Pro
- It's probably not realistic, but this could unlock a roadmap to incorporating a JIT of some sort. Could be a cool side project to work on 😎

I would be interested in driving this feature / getting a V1 out if this would be a welcome addition. I'll try to start gathering metrics later today about my startup time, and maybe even create a naive implementation of this feature to see what improvement I could make.

**Comment by faho** [comment]
Been asked for before, unfortunately it's not realistic or compatible with the shellscript model Also most time is spent in external commands anyway, so it won't help that much. Sorry, closing.

**Comment by danzimm** [comment]
Quick update: naively wrapping my config.fish() in `python -c 'import time; print time.time()'` shows that my startup scripts take ~110ms. I guess this isn't that sluggish, but starting up bash with a very similar set of startup scripts seems a bit snappier.
--
It's probably better to investigate where the slow down comes via profiling rather than investing time in this feature.
--
@faho no worries, makes sense! I might fork and have some fun anyway for my own edification

**Comment by krobelus** [comment]
> It's probably better to investigate where the slow down comes via profiling rather than investing time in this feature.

Yeah, check out `fish --profile`. My `fish -c true` around 20ms.

**Comment by ridiculousfish** [comment]
Hey DanZ! 👋 

Bytecode would indeed be a big undertaking. However a bytecode interpreter would have another large benefit in enabling concurrent / background fish functions.

Right now we have a straightforward tree-walking interpreter. This means that running fish script requires the C stack. That's why you can only run one fish function at a time.

If we had a bytecode representation, we pull a [Stackless Python](https://github.com/stackless-dev/stackless/wiki) and break that dependence. Fish functions would use an explicit stack and we could have many of them.

While on that topic, a second approach would be something like [libmill](http://libmill.org) or Rewrite It In Rust for async (just joking, or am I)

A third approach is explicit threads, which is what I'm exploring now.

**Comment by ridiculousfish** [comment]
If your goal is just performance there's a lot we can do without needing bytecode. Our string handling is still pretty naive  - we use `std::wstring` pervasively and it's quite allocation intensive. I have another branch that reimplements strings via COW under the hood, but I haven't been able to produce enough benefit to justify that yet.

**Comment by danzimm** [comment]
Hi @ridiculousfish! I miss seeing you on chat!

I'll be honest, other than for performance, it sounded like a fun thing to hack on. The prospect you mentioned sounds cool. If I end up getting some free time I'll try hacking something up and send it over!
