### ISSUE TITLE
How to create the packages for the new Fedora releases 

### ISSUE THREAD

**Issue by dmouse** [fish-shell/fish-shell#6430]
The [current](https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish) rpm built for Fedora is outdated, the current versión is 30 and 31, how to can I help to get updated the rpm binaries?

**Comment by zanchey** [comment]
I tried turning the builds on but they fail the stricter RPM checks (mostly against Python) in newer Fedora. This is a problem fixed in the nearly-arrived 3.1 release, so I haven't devoted much energy to the problem; a patch which applies against 3.0.2 would be useful as it can be deployed in OBS without having to roll a whole new release (though it will rebuild the existing binaries for all platforms, which is less desirable).

It also may not be worth it - fish 3.0.2 is already in Fedora 30 and 31, so can be installed without our repository.

**Comment by dmouse** [comment]
I updated the documentation about how to install for fedora
https://github.com/fish-shell/fish-site/pull/84

**Comment by zanchey** [comment]
Yep, I think that's a reasonable thing to do for now.
