### ISSUE TITLE
fish: Unknown command arp  :-/

### ISSUE THREAD

**Issue by K4S1** [fish-shell/fish-shell#6441]
Hi,

Can't seems to get ARP running with fish.
Just me or have anyone else seen this ?
Have googled around and searched issues here but didn't find any related cases

Sorry if this is an complete noob error, my 2 day with fish :-)

```
ks@mx~> arp
fish: Unknown command arp
ks@mx~> sh -c 'env HOME=$(mktemp -d) fish'
             
Welcome to fish, the friendly interactive shell
ks@mx /h/ks> arp
fish: Unknown command arp
ks@mx /h/ks> exit
ks@mx~> bash
ks@mx:~
$ arp
Address                  HWtype  HWaddress           Flags Mask            Iface
192.168.1.175           ether   ff:ff:ff:ff:ff:ff   C                     eth0
_gateway                 ether   ff:ff:ff:ff:ff:ff   C                     eth0
192.168.1.185           ether   ff:ff:ff:ff:ff:ff   C                     eth0
192.168.1.5             ether   ff:ff:ff:ff:ff:ff   C                     eth0
ks@mx:~
```

```
ks@mx~> neofetch --config /home/ks/.config/neofetch/config-version.conf --ascii /home/ks/startascii
 \__/    OS: MX x86_64 
 (oo)    Kernel: 4.19.0-6-amd64 
//||\\   Shell: fish 3.0.2 
         DE: Xfce 
         WM: Xfwm4 
         Terminal: xfce4-terminal 

ks@mx~> echo $TERM
xterm-256color
ks@mx~> uname -a
Linux mx 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
ks@mx~>
```

**Comment by faho** [comment]
So when fish can't find a command but another shell can that has one of two causes:

- It's a function or builtin in another shell and fish can't run those
- It's an external command that's not in $PATH in fish, but is in the other shell

Since I doubt it's a builtin or function, compare the value of $PATH in both shells:

```fish
echo $PATH
```

**Comment by K4S1** [comment]
Right U are !
/usr/sbin missing :-) +1

```
ks@mx~> echo $PATH
/usr/local/bin /usr/bin /bin /usr/local/games /usr/games
ks@mx~> command -v arp
ks@mx~> bash

ks@mx:~
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin
ks@mx:~
$ command -v arp
/sbin/arp
```

As I understand Docs, I can add perm to $PATH if I use the global variable $fish_user_paths
https://fishshell.com/docs/current/tutorial.html#tut_path

`set -U fish_user_paths /usr/sbin $fish_user_paths`
```
ks@mx~> arp
Address                  HWtype  HWaddress           Flags Mask            Iface
192.168.1.175           ether   ff:ff:ff:ff:ff:ff   C                     eth0
_gateway                 ether   ff:ff:ff:ff:ff:ff   C                     eth0
192.168.1.185           ether   ff:ff:ff:ff:ff:ff   C                     eth0
192.168.1.5             ether   ff:ff:ff:ff:ff:ff   C                     eth0
ks@mx~>
```

It did the job :)
But is it the right way to fix this ?

Thanks for your quick replay :-)

**Comment by faho** [comment]
So typically /usr/sbin is among the system paths that fish will just inherit from its parent process. Your system is weird in not adding it via e.g. /etc/login.defs or pam or... but instead apparently opting to add it via bash's configuration.

Technically this will result in /usr/sbin being *first* (because $fish_user_paths is prepended), which means if you had a thing of the same name there and in another of the $PATH components fish would pick that and bash would pick the other. To be honest it probably won't matter, because having things of the same name doesn't happen in practice, in system directories (the  debian folks won't like it if two things have the same name).

You could instead modify $PATH directly, via something like

```fish
contains -- $PATH /usr/sbin; or set -a PATH /usr/sbin
```

(and the same thing for /sbin)

(also for GNU/Linux it's becoming rare to even have a separate /usr/sbin)

**Comment by K4S1** [comment]
I just checked the `/etc/login.defs`

```
#
# *REQUIRED*  The default PATH settings, for superuser and normal users.
#
# (they are minimal, add the rest in the shell startup files)
ENV_SUPATH	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV_PATH	PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

Found I have 2 variables as you see.
Can't tell you why there are 2. but it could indicate this is why I have issues, according to the results.

I will try raise a question with the MX people. To see if they can explain to me. Why the fish shell are only installed as normal user... or how it's working :) "Not an expert"
But Fish Shell was installed via there packet installer. 

But again thanks for you help, and a great shell ! :+1:

**Comment by K4S1** [comment]
FYI:
Just found that the .bashrc have the add of /sbin and /usr/sbin to $PATH for mx linux.
```
# Add sbin directories to PATH.  This is useful on systems that have sudo
 echo $PATH | grep -Eq "(^|:)/sbin(:|)"     || PATH=$PATH:/sbin
 echo $PATH | grep -Eq "(^|:)/usr/sbin(:|)" || PATH=$PATH:/usr/sbin
```
And why fish is not getting it.
Never seen this before now. but a bit weird, I will agree.

**Comment by krobelus** [comment]
It may be convenient to use bash as login shell but configure your terminal to run fish.
This way you get your environment set up as your distro intends it to, and fish should work without any extra configuration.
