### ISSUE TITLE
fish not displaying colours correctly in Alacritty

### ISSUE THREAD

**Issue by docbiz** [fish-shell/fish-shell#6455]
fish appears to not recognise that Alacritty is capable of supporting 24-bit colours, even though `fish_term24bit` is set to `1`. The following image is one example of this:

<img width="659" alt="colours" src="https://user-images.githubusercontent.com/10088591/71536235-21fc9c80-2905-11ea-8c71-f7e3d9671b3b.png">

Do you have any ideas about what's going on? Please let me know if there's any other information I can provide.

I'm running:
- fish 3.0.2,
- Alacritty 0.4.0, and
- macOS 10.14.6 (Mojave).

**Comment by faho** [comment]
Not a fish issue, I'm afraid.

When $fish_term24bit is set to 1, that causes fish to emit RGB sequences:

```fish
$ set_color 859900 | string escape
\e\[38\;2\;133\;153\;0m
```

(133 is decimal for 0x85, 153 for 0x99)

Once that's done, the terminal interprets those sequences however it wants, and in this case it seems alacritty doesn't want to pick that exact color. I know xterm maps RGB sequences back to its 256 color palette, it's possible alacritty does something similar.

Anyway, the cause is alacritty.

**Comment by docbiz** [comment]
Thanks for the quick and informative response (and sorry for casting the blame with fish). I'll raise an issue with Alacritty.

Do you know if there are any workarounds?

**Comment by faho** [comment]
>Do you know if there are any workarounds?

It is quite literally impossible to work around this from inside the terminal.
