### ISSUE TITLE
funcsafe not working in windows 10 Linux Subsystem

### ISSUE THREAD

**Issue by woutyboy3** [fish-shell/fish-shell#6462]
fish, version 3.0.2 on ubuntu 18.04 as windows 10 Linux Subsystem

The funcsafe command

- first i make the alias lss: `alias lss="ls -hal"`
- then the funcsafe command: `funcsave lss`
Then I get this error `mkdir: cannot create directory ‘/home/wout_junius/.config’: Permission denied
funcsave: Could not create configuration directory`

so then I do sudo so it can create it: `sudo funcsave lss`
now I get this error message `sudo: funcsave: command not found`

So what do I do? or is it impossible

**Comment by faho** [comment]
Step back for a minute. Right now you're randomly adding `sudo` to commands, and that's not the right way to go about things.

That directory "/home/wout_junius/.config" is in your home directory (the "/home/wout_junius" part). Your home directory is your user's domain. Everything in there should belong to that user, which means everything should be writeable to that user. `sudo` shouldn't be necessary in your home directory.

Even though creating the directory indeed fails with "Permission denied" as the error, you still shouldn't use `sudo` because it shouldn't fail like that in your home directory in the first place. What you need to do is figure out where the permission error comes from and solve *that*.

My guess is you've run `sudo` like this before, and that created a .config that's not writeable to your user. So try looking at it with `ls -l ~/.config`, and if it says it's not owned by your user or doesn't have the correct permissions, use something like `chown $USER:users ~/.config` and `chmod 755 ~/.config` to fix it by reassigining it to your user and giving it the normal permissions.

------

> now I get this error message sudo: funcsave: command not found

The reason this fails like that is because `funcsave` is itself a function. That means it only exists inside fish, and an external command like `sudo` won't find it. Even if it wasn't, though, what `funcsave` does requires it to look inside fish for the function to save, so this *can't* work with `sudo`. The best you could do would be `sudo fish -c funcsave`, which will open a new fish and tell that to funcsave, but you'd have to somehow pass that the new function definition you'd want to save.

**Comment by faho** [comment]
It seems the question has been answered so I'm closing. If you have any followups feel free to ask!
