### ISSUE TITLE
Fish shell "kill -9" doesn't work as expected?

### ISSUE THREAD

**Issue by rohitkrishna094** [fish-shell/fish-shell#6469]
I have installed Cygwin on windows and set fish as default shell. I did this by right clicking Cygwin.bat(inside the location `C:\cygwin64`) file and changing the last line to (note fish there)

`cd /d "%~dp0bin" && .\fish --login -i`

Now when I double click Cygwin.bat, I get a nice prompt from fish as shown.
![image](https://user-images.githubusercontent.com/18495886/71770306-14dd4000-2ef9-11ea-8f89-220442dfb42c.png)

Now when I type `kill -9` however, this is what I get. The thing is it straight away prints not enough arguments even though I have not yet pressed the return key. Even before I type the pid, it throws this error. 
![image](https://user-images.githubusercontent.com/18495886/71770338-756c7d00-2ef9-11ea-9bdc-8b0dbe6acf93.png)

Initially I thought this was Cygwin's problem, so I changed the shell to bash and tried to do the same. I have no problems with kill command if I used bash as my default shell in Cygwin. So I am assuming this has to with fish shell. 

Fish Version: 2.7.0
Operating System: Windows 10
Terminal: Cygwin (echo $TERM shows xterm-256color)

**Comment by faho** [comment]
So there's a few things to note here. First of all: Your fish is outdated. The current release is 3.0.2, and even in the 2.7 series (which is unsupported, just to be clear) there is 2.7.1. So you'll want to upgrade fish, and cygwin [offers 3.0.2](https://cygwin.com/packages/summary/fish.html).

Or, since you are on Windows 10 you could try the Windows Subsystem For Linux which gives a more typical linux environment.

So what is happening here is that fish is loading the completion script for `kill` before you're executing anything to support the autosuggestions - mainly it needs to figure out if an argument can be a file or not.

Our kill completion script needs to know which version of the `kill` program you're using, so it executes `kill -L`. In GNU kill, this will list all known signals, while other kills will error out because it's an unknown option.

So we test `kill -t`, because there are versions that produce a nicer table with that, then we test `kill -L`.

And it seems that that logic doesn't quite work out on the exotic cygwin kill (https://cygwin.com/cygwin-ug-net/kill.html).

According to the documentation the following should happen:

- `kill -t` should fail (and most likely print an error)
- `kill -L` should also fail
- `kill -l 1` (and all integers up to 31) should work

I'm willing to bet that last one (`kill -l 1`) is wrong even though the docs seem to say otherwise.

**Comment by ohk2kt3t4** [comment]
For reference this is the output on fish 3.0.2 on cygwin;

- `kill -t`: 
kill: unknown signal: t
Try `kill --help' for more information.

- `kill -L`:
kill: unknown signal: L
Try `kill --help' for more information.

- `kill -l 1`:
HUP
kill: not enough arguments

- `kill -l`:
kill: not enough arguments
HUP INT QUIT ILL TRAP ABRT EMT FPE KILL BUS SEGV SYS PIPE ALRM TERM URG STOP TSTP CONT CHLD TTIN TTOU IO XCPU XFSZ VTALRM PROF WINCH PWR USR1 USR2 RTMIN RTMIN + 1 RTMIN + 2 RTMIN + 3 RTMIN + 4 RTMIN + 5 RTMIN + 6 RTMIN + 7 RTMIN + 8 RTMIN + 9 RTMIN + 10 RTMIN + 11 RTMIN + 12 RTMIN + 13 RTMIN + 14 RTMIN + 15 RTMIN + 16 RTMIN + 17 RTMIN + 18 RTMIN + 19 RTMIN + 20 RTMIN + 21 RTMIN + 22 RTMIN + 23 RTMIN + 24 RTMIN + 25 RTMIN + 26 RTMIN + 27 RTMIN + 28 RTMIN + 29 RTMIN + 30 RTMIN + 31 ⏎

(yes, order is different for some reason)

I will see if I can dig into the source, but for the time being I think we can special case this for cywgin?

**Comment by faho** [comment]
Okay, I just hardcoded the signal numbers on Cygwin.

@zanchey acefa61e8 should be good for 3.1.0 - this failure mode is awful and it's only used on cygwin. The following commits should stay on master.

**Comment by ridiculousfish** [comment]
This is incredible. Nice detective work.
