### ISSUE TITLE
disown-parent test fails on NetBSD

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#6476]
Running the tests on NetBSD (via sr.ht - https://builds.sr.ht/~faho/job/132496) errors out with the following:

```
Testing file checks/disown-parent.fish ... Failure in checks/disown-parent.fish:

  There were no remaining checks left to match stderr:1:
    disown: Could not find job '4567'

  when running command:
    env fish_test_helper=../test/root/bin/fish_test_helper ../test/root/bin/fish checks/disown-parent.fish
```

this is with 33a234e19 which is 484e590b7 without a rebase.

This seems like something in our job-id logic doesn't really work out?

I've not had the time to test on a real NetBSD system.

**Comment by ridiculousfish** [comment]
Got NetBSD running with Vagrant. The problem is that `fish_test_helper print_pid_then_sleep` is exiting immediately, instead of sleeping for .5 seconds. The reason is a rather stupid bug:

    usleep(1000000 / .5);  //.5 secs

This is of course two seconds, not half a second. But~ NetBSD has in `man usleep`:

    "The microseconds argument must be less than 1,000,000."

And here it's not, so we don't sleep, so the job gets reaped really fast.
