### ISSUE TITLE
Trying to understand the correct way to add aliases

### ISSUE THREAD

**Issue by jamesla** [fish-shell/fish-shell#6485]
I have over 300 aliases added to my config.fish file and as a result it is slowing down the startup time of when I open a new shell. 

I was wondering whether fish has a better mechanism for adding aliases so that my shell startup time won't be affected?

**Comment by faho** [comment]
The most performant thing is autoloaded functions. Save your aliases in files named after them (plus ".fish") in ~/.config/fish/functions, preferably as functions, and they'll slow your shell startup time down precisely not. Easiest way to create them is `funcsave $alias`, e.g. `funcsave gs`. Do that once per alias, and it will create the corresponding file (with a function) for each.

`alias` adds a bit of overhead because it's also just a function that creates functions (see `type alias`), so just replacing it with proper function definitions (which also allow more flexibility) helps.

Also we have abbreviations, which bypass functions entirely and which I would recommend especially for all those cryptic "gs=git status" aliases, because they expand in-place so you just see the original command. Use `abbr --add gs "git status"` to add them, and that can be done once interactively because it uses universal variables (or add `--global` to use global variables instead and add the `abbr` invocation to config.fish).

Also you could always audit your aliases for ones you aren't using.

**Comment by jamesla** [comment]
Ok nice thanks for such a detailed writeup. abbr are much faster and all is well
