### ISSUE TITLE
test error when starting tmux from config.fish

### ISSUE THREAD

**Issue by qlem** [fish-shell/fish-shell#6509]
Hi everyone,

I use fish as interactive shell only. I set up my `config.fish` to start tmux with a new session or from an existing session:
```
# start tmux
if status is-interactive
    if test -z "$TMUX"
        set id (tmux ls | grep -vm1 attached | cut -d: -f1)
        if test -z "$id"
            tmux new-session
        else
            tmux attach-session -t "$id"
        end
    end
end
```

When I launch my terminal (`alacritty`), although tmux start well, an output error from `test` is displayed:
```
test: Missing argument at index 5
$>  ...
```

Versions:
```
$> fish --version
fish, version 3.0.2
$> tmux -V
tmux 3.0a
```

I don't understand why. Can you help me ?

**Comment by faho** [comment]
This most likely comes from some *other* bit of configuration, like some third-party configuration - Oh-My-Fish, fisherman, etc.

Unfortunately `test` in 3.0.2 is quite annoying in that it doesn't give you the wrong argument, which is why in the upcoming 3.1.0 it'll show you a full backtrace (#5771).

Honestly it'd probably be easiest to build fish from git master, start it once and follow the backtrace that would print. Otherwise you'd have to try to disable bits of your config to isolate it.


-----

However, in this case we do have your config (https://github.com/qlem/dotfiles/blob/master/.config/fish/config.fish), and you've not shown a part there:

```fish
# Start X at login
if status is-interactive 
    if test -z "$DISPLAY" -a $XDG_VTNR = 1
        exec startx -- -keeptty
    end
    if test -z "$TMUX"
        set id (tmux ls | grep -vm1 attached | cut -d: -f1)
        if test -z "$id"
            tmux new-session
        else
            tmux attach-session -t "$ID"
        end
    end
end
```

and sure enough `if test -z "$DISPLAY" -a $XDG_VTNR = 1` has an unquoted variable at what test calls "index 5", so if that's not set the call will look like `test -z "" -a = 1`, in which case you'll have that awkward "= 1" there which test won't understand.

So: Quote that $XDG_VTNR.

**Comment by qlem** [comment]
Thank you @faho for your reactivity, your informed response and your investigation in my dotfiles !

I will add that quotes !
