### ISSUE TITLE
&& doesn't work still does not work

### ISSUE THREAD

**Issue by evandrocoan** [fish-shell/fish-shell#6534]
Steps
```
root@evandro-pc /h/evandro# echo '[[ "$-" != *i* ]] && return' > test.sh
root@evandro-pc /h/evandro# source test.sh 
test.sh (line 1): Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
[[ "$-" != *i* ]] && return
                   ^
from sourcing file test.sh
	called on standard input

source: Error while reading file “test.sh”
```

Environment
```
root@evandro-pc /h/evandro (master)# fish --version
fish, version 3.0.2-2189-g5bfb6fef7

root@evandro-pc /h/evandro (master)# echo $version
3.0.2-2189-g5bfb6fef7

root@evandro-pc /h/evandro (master)# uname -a
Linux evandro-pc 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

root@evandro-pc /h/evandro (master)# echo $TERM
xterm-256color

root@evandro-pc /h/evandro# sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish

root@evandro-pc /h/evandro (master)# cat /etc/os-release 
NAME="Linux Mint"
VERSION="19.1 (Tessa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.1"
VERSION_ID="19.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tessa
UBUNTU_CODENAME=bionic
```

https://github.com/fish-shell/fish-shell/issues/150

**Comment by faho** [comment]
Can't reproduce - I get

```
test.sh (line 1): $- is not a valid variable in fish.
[[ "$-" != *i* ]] && return
     ^
from sourcing file test.sh
```

Please double-check you were actually running the correct fish version, and you've correctly explained the reproduction steps.

-----

`&&` is supposed to work, but `[[` isn't, and `$-` still isn't a thing, also `return` outside of functions isn't allowed.

It's absolutely still not expected for fish to be able to read arbitrary shell script, and it won't be. If you want a POSIX-compatible shell (like one that can source your bashrc, like you seem to be trying here), you still have to look somewhere else. This is by design.

**Comment by evandrocoan** [comment]
How can I see the version of the running fish shell?

**Comment by 0ion9** [comment]
^ `echo $FISH_VERSION`.

**Comment by faho** [comment]
To be clear, I'm expecting that the shell you originally ran the test in is a different one from the one you gave the version output for (and $FISH_VERSION is the same as $version).

One thing that makes me think that (apart from, you know, things not making sense otherwise) is that your prompt changed:

```
root@evandro-pc /h/evandro# echo '[[ "$-" != *i* ]] && return' > test.sh
```

```
root@evandro-pc /h/evandro (master)# fish --version
```

See that "(master)" part? That's the git branch. Since the directory is the same either you did a `git init` after, or the prompt changed. And given that we enabled git prompt display recently, switching from fish 2.7 (which can't do `&&`) to fish from git master would do that.

Note that `source` will, by definition, not start a new shell, but will execute the file in the current one (so variable changes and such stick). So if you do `echo $version`, and it says something after 3.0, and you then `source` that file in that shell, then it's a bug.

**Comment by evandrocoan** [comment]
I have trouble configuring fish as my default shell because after I installed it on my Linux, it did not put the binaries on `/usr/local/bin/fish` and the command on the first page said to use that directory:
![image](https://user-images.githubusercontent.com/5332158/73566510-cf059000-4442-11ea-99c6-7d7e669b36bf.png)

Today when I ran `echo $FISH_VERSION` the version was correctly 3.0.2 and
```
root@evandro-pc /h/evandro (master)# source test.sh
test.sh (line 1): $- is not a valid variable in fish.
[[ "$-" != *i* ]] && return
     ^
from sourcing file test.sh
source: Error while reading file “test.sh”
```

Was doing the same error as yours.
