### ISSUE TITLE
FLOGF can stomp on errno, giving misleading wperror output

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#6545]
There's currently a moderate number of instances where the code calls `FLOG` and then `wperror()` or friends. I'm not sure this is right, because `FLOGF` can (in some situations?) overwrite `errno` which means the output of `wperror` is wrong.

My old friend, RHEL 6, is failing a test with:

```
Testing file checks/directory-redirect.fish ... Failure in checks/directory-redirect.fish:

  The CHECKERR on line 7 wants:
    {{open: Is a directory|open: Invalid argument}}

  which failed to match line stderr:2:
    open: Illegal seek
```

The following produces the correct message, though still fails the test:

```
diff --git a/src/io.cpp b/src/io.cpp
index 22bf1dd..0b1bc8b 100644
--- a/src/io.cpp
+++ b/src/io.cpp
@@ -256,8 +256,8 @@ bool io_chain_t::append_from_specs(const redirection_spec_list_t &specs, const w
                     if ((oflags & O_EXCL) && (errno == EEXIST)) {
                         FLOGF(warning, NOCLOB_ERROR, spec.target.c_str());
                     } else {
-                        FLOGF(warning, FILE_ERROR, spec.target.c_str());
                         if (should_flog(warning)) wperror(L"open");
+                        FLOGF(warning, FILE_ERROR, spec.target.c_str());
                     }
                     return false;
                 }
```

I'm not sure if something's being inlined here that shouldn't, or it's just an old glibc that happens to call `lseek` as part of `vfwprintf`, but I wonder if we can make it more robust in general.

**Comment by faho** [comment]
>The following produces the correct message, though still fails the test:

I would imagine it flips the message around? First the open error, then the warning?

---------

Sooo... how about we just save and restore errno in FLOGF (at least if we do decide to print something)?

**Comment by faho** [comment]
Or, if it's a performance issue (no idea how expensive errno is, tbh), we could of course only save it *here*, and then hope everyone thinks of doing it.

IIRC this was the only case where we used "should_flog" in order to use "wperror", and I couldn't come up with a nicer way to express it (wperror is kinda bad for this, with how it uses global state), so I don't think there are other places this is *currently* needed.

**Comment by ridiculousfish** [comment]
Saving and restoring errno should be very cheap.

**Comment by zanchey** [comment]
It's not the `should_flog` call that is the issue, it's that FLOG makes library calls that alter errno. There's a handful of other places where FLOG is followed by `wperror()` or friends, and I don't think we can guarantee that everyone will remember not to do that.

**Comment by faho** [comment]
>It's not the should_flog call that is the issue, 

Oh, that was badly phrased. What I meant was that this is the only thing that's doing this "wperror *and* flog" pattern I recall, because of the "should_flog".

You're saying there's a "moderate number" of places?

> it's that FLOG makes library calls that alter errno.

Sure. That's wrong anyway, a logging call should not have any effect on the rest of the program. You should be able to throw it in with abandon.

So let's just redefine flog to do 

```c++
auto old_errno = errno;
// do the thing
// ...
errno = old_errno;
```

**Comment by zanchey** [comment]
`rg -A1 'FLOG.?'` shows 17 instances at present, so I think it's common enough. Your solution sounds good.
