### ISSUE TITLE
Provide a builtin C++ implementation for command-not-found 

### ISSUE THREAD

**Issue by opensource-assist** [fish-shell/fish-shell#6548]
- Fish doesn't support any such functions yet
- The current command-not-found utility:
    - is not written for Fish
    - It's buggy
    - It's written in Python which is makes it a little inefficient, as it wastes a lot of time finding a missing package.
    - It's in a third-party package so you can't be sure it's always available. 
    - It(probably) doesn't support missing command query caching.

**Comment by faho** [comment]
It's also entirely OS-specific. There's no way for us to provide such a thing for every distribution under the sun.

Sorry, but no. If the tool is buggy, complain to whoever makes the tool.

**Comment by faho** [comment]
To be more specific:

>is not written for Fish

Doesn't matter. It's callable by fish, it doesn't have to be written for fish. We give it the command, it gives us where to find it.

>It's written in Python which is makes it a little inefficient

Also doesn't matter, because searching for a command isn't something you'd do in tight loops. It's not performance critical.

Python's overhead is on the order of *milli*seconds, and those just don't matter here.

>It(probably) doesn't support missing command query caching.

Again, if you are missing commands in tight loops, you're doing something wrong.

>It's in a third-party package so you can't be sure it's always available.

On most systems they are typically installed. If not, they should be "recommended" or optdepends for the fish package. If still not, somebody was trying to trim the system down, in which case okay. This isn't super critical. You don't have missing commands all the time.

**Comment by opensource-assist** [comment]
@faho

> Also doesn't matter, because searching for a command isn't something you'd do in tight loops. It's not performance critical.

command-not-found is integrated into Bash and is run automatically. Sometimes it gets stuck in finding a missing package and consumes a lot of time. or blurts out buggy output.

> Python's overhead is on the order of milliseconds, and those just don't matter here.

Are you sure about that? Fish is being run on all types of devices with not so powerful CPUs. Python's overhead is on the order of miliseconds, but command-not-found's is not.

> On most systems they are typically installed.

command-not-found is not installed by default, at least on Debian systems.

> they should be "recommended" or optdepends for the fish package

That's a good idea.
