### ISSUE TITLE
Failure in checks/colon-delimited-var.fish on OpenIndiana

### ISSUE THREAD

**Issue by Mno-hime** [fish-shell/fish-shell#6556]
fish 3.1 beta1 test suite compiled with GCC 6.5 fails on OpenIndiana with:
```
Testing file checks/colon-delimited-var.fish ... Failure in checks/colon-delimited-var.fish:

  The CHECK on line 8 wants:
    a:.:b

  which failed to match line stdout:1:
    /usr/xpg4/bin:a:.:b

  when running command:
    env PATH="a::b" CDPATH="d::e" MANPATH="x::y" ../test/root/bin/fish checks/colon-delimited-var.fish
```

**Comment by krobelus** [comment]
Could this be due to the vendor directories for configuration snippets?
Some file in `$vendor_confdirs` in [share/config.fish](https://github.com/fish-shell/fish-shell/blob/Integration_3.1.0/share/config.fish#L286-L295) could add the PATH entry.

What changed is that `/usr/local/share/fish/vendor_conf.d/*.fish` are included by default, even if running from a different prefix (like the tests do).

**Comment by zanchey** [comment]
Nope, this is added deliberately in `share/config.fish`:

https://github.com/fish-shell/fish-shell/blob/b313ba555afc2c42f0c46cfd15bed2cbee490986/share/config.fish#L119-L129

From all the way back in 2006! 8a2846ed4474b1dff43af914694c3d895ba31c87

I actually think we should drop these kind of platform hacks but at the very least it should be skipped when the tests are running.

**Comment by faho** [comment]
>I actually think we should drop these kind of platform hacks

The one reason I can see for this is that we used to call external tools quite a bit, and the solaris ones are... different, so this would help quite a bit. But since this was introduced we've reduced our dependence on external tools quite a bit (e.g. via string and math), so this has even less of a reason for existing.

So: Yes, let's remove it, but preferably for 3.2. For 3.1 I'd just accept the failure - turning the test off doesn't seem like it'd help much.

**Comment by Mno-hime** [comment]
Just FYI, I run the build and test with GNU utilities taking precedence in the `$PATH`.

Anyway, I am happy to give patch a shot, when there's one.

**Comment by zanchey** [comment]
Something like this should work:

```
diff --git a/share/config.fish b/share/config.fish
index 400556832..6157c7c1c 100644
--- a/share/config.fish
+++ b/share/config.fish
@@ -123,7 +123,7 @@ end
 # system utilities.
 #

-if test -d /usr/xpg4/bin
+if begin; not set -q FISH_UNIT_TESTS_RUNNING; and test -d /usr/xpg4/bin; end
     not contains -- /usr/xpg4/bin $PATH
     and set PATH /usr/xpg4/bin $PATH
 end
```

**Comment by faho** [comment]
>Something like this should work:

TBH I'd rather just remove that code entirely:

```diff
diff --git a/share/config.fish b/share/config.fish
index 400556832..acba33c09 100644
--- a/share/config.fish
+++ b/share/config.fish
@@ -115,19 +115,6 @@ function : -d "no-op function"
     true
 end

-#
-# This is a Solaris-specific test to modify the PATH so that
-# Posix-conformant tools are used by default. It is separate from the
-# other PATH code because this directory needs to be prepended, not
-# appended, since it contains POSIX-compliant replacements for various
-# system utilities.
-#
-
-if test -d /usr/xpg4/bin
-    not contains -- /usr/xpg4/bin $PATH
-    and set PATH /usr/xpg4/bin $PATH
-end
-
```

Granted it's a *bit* late in the cycle.

**Comment by ridiculousfish** [comment]
Patching the test in 3.1, and removing the xpg4 check in master, seems sensible to me.

**Comment by zanchey** [comment]
If @Mno-hime can confirm that my patch works I'll do that.

**Comment by Mno-hime** [comment]
I run the @faho's change now, happy to test a 3.1-specific one too.

**Comment by zanchey** [comment]
@Mno-hime please see https://github.com/fish-shell/fish-shell/issues/6556#issuecomment-580759905

**Comment by Mno-hime** [comment]
@zanchey That works for me too. Thanks!
