### ISSUE TITLE
Incorrect symlink completion for the unlink command

### ISSUE THREAD

**Issue by morozov** [fish-shell/fish-shell#6576]
```sh
$ fish --version
fish, version 3.0.2

$ echo $version
3.0.2

$ uname -a
Linux *** 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ echo $TERM
xterm-256color
```

I tried the scenario below in a temporary environment as suggested. When completing a link name for the `unlink` command, regardless of whether the link points to a file or a directory, the completion result should not contain a trailing slash. Otherwise, the resulting command is invalid:
```sh
$ mkdir a
$ ln -s a bcde
$ unlink bc<TAB><TAB>
$ unlink bcde/
unlink: cannot unlink 'bcde/': Not a directory

$ unlink bcde # entered w/o completion
$ echo $status 
0
```

**Comment by faho** [comment]
I'm gonna reject this.

The reason is that adding the "/" is *correct* if you want to decend further to remove a symlink *inside* that directory. If we didn't add it, you'd need to add one "/" per-level. As it is now, if you do want to remove a directory symlink, you have to remove the "/" *once*.

Now, it would also be possible to scan the directory for symlinks, but that would require descending the entire tree, which would take a looooong time in quite typical cases (`unlink /`, press TAB), and the only way to figure out how long it would take is to try it.

Also we don't have special `unlink` completions - these are the normal file completions (augmented with generated completions that just add options), and keeping consistent in something as low-level as completing directories is important.

**Comment by morozov** [comment]
Thank you for the detailed explanation, @faho. I agree with the resolution.
