### ISSUE TITLE
(possible cmake issue) undefined reference to symbol 'tparm'

### ISSUE THREAD

**Issue by Roguelazer** [fish-shell/fish-shell#6587]
I'm attempting to build `fish` 3.1 for our RHEL 6-based distribution (upgrading from a backported 3.0.2), but linking is failing with

```
undefined reference to symbol 'tparm'
```

It looks like the CMake file is adding `-lcurses` to the linker command line without adding `-ltinfo`, which is required for older versions of ncurses. Unfortunately, while I know a lot about autotools, I'm not much of an expert in cmake, so I'm not sure what needs to change about `ConfigureChecks.cmake` to teach it this fact.

I have verified that running `cmake3 -DCURSES_LIBRARY="-lcurses -ltinfo" ..` fixes it but that feels pretty hacky.

I think this is the same as #6546 but who knows.

**Comment by zanchey** [comment]
Nah, it's an issue with RHEL 6. The way the [spec file](https://github.com/fish-shell/fish-shell/blob/3.1.0/fish.spec.in#L51) handles this is by setting `-DCURSES_EXTRA_LIBRARY=tinfo` on the command-line, which is probably the best way to go.

Out of interest, is there a reason you're building from source rather than using the RHEL 6 packages? Also, since we're considering dropping Python 2 support (#6537), do you have Python 3 available somehow?

**Comment by Roguelazer** [comment]
We do have a bunch of things backported (like python 3.8 and gcc8 and a new enough pcre2 that we can avoid static linkage) as a kind of backport toolchain, so it's easier to use our own package.

It still seems like it might be nice for the cmake stuff to autodetect this the way the autotools build system always was able to, but I don't feel super strongly about it.

**Comment by zanchey** [comment]
Looking at CMake's `FindCurses`, it should do so automatically, so I wonder why it's not working.

**Comment by zanchey** [comment]
Well that was a diverting journey...

* FindCurses looks for both ncurses and curses libraries
* If both exist, unless `CURSES_NEED_NCURSES` is set, the whole path looking for extra libraries like tinfo isn't taken
* On RHEL 6, there's a `/lib64/libcurses.so` which is a [linker script](https://sourceware.org/binutils/docs/ld/Implicit-Linker-Scripts.html#Implicit-Linker-Scripts) (I was today years old when I learned that these exist) which points directly at ncurses, but that's enough to be detected as a curses library
* On Debian 10, there's a similar file but that points at ncurses and adds `-ltinfo`, meaning the linker adds that automatically

Honestly I don't know that this ever worked as intended. I'll pass it on upstream.

**Comment by zanchey** [comment]
Oh, it's because FindCurses doesn't actually care whether you use the CURSES or NCURSES variables, and RHEL 7 fixed this by adding `-ltinfo` to the linker script in `/usr/lib64/libncurses.so`.

It's difficult to know what to do here, and I'm pretty tempted to do nothing - fish can't require ncurses because it does build and run on some systems which only have X/Open curses; any fixes to CMake will only appear in future versions, which will require manual backporting to RHEL 6; and the RHEL 6 arrangement is arguably broken, or at least incomplete.

**Comment by mqudsi** [comment]
We can link against `libtinfo` if and only if it is found and we are using ncurses (rather than curses)?

**Comment by faho** [comment]
Yeah, no, there's no use in doing more for RHEL 6, and so far nobody has stepped up to do it. I'm declaring this done.

**Comment by mqudsi** [comment]
I disagree, it's an easy fix (see my last comment) and is actually a bug in our CMake code, as automated (n)curses detection should include a check for libtinfo (the symbols are either defined in curses or in tinfo, and you can either run configure checks to see which library causes the code to compile or just link libtinfo iff it is found).

**Comment by faho** [comment]
>I disagree, it's an easy fix (see my last comment) and is actually a bug in our CMake code

If you want to fix it, go right ahead (which it seems you did). It's just that this was open as a question since february, and nobody seemed to be working on it.

**Comment by mqudsi** [comment]
Thanks for triaging.
