### ISSUE TITLE
fish 3.1.0 does not include /usr/local/bin in the PATH

### ISSUE THREAD

**Issue by raszi** [fish-shell/fish-shell#6594]
```
$ /usr/local/bin/fish --version
fish, version 3.1.0

$ uname -a
Darwin 300024m0 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

$ sh -c 'env HOME=$(mktemp -d) /usr/local/bin/fish'
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
ikaraszi@300024m0 /U/ikaraszi> echo $PATH
/Users/ikaraszi/.rvm/gems/ruby-2.6.2/bin /Users/ikaraszi/.rvm/gems/ruby-2.6.2@global/bin /Users/ikaraszi/.rvm/rubies/ruby-2.6.2/bin /usr/local/sbin /Users/ikaraszi/bin /usr/bin /bin /usr/sbin /sbin /Users/ikaraszi/.rvm/bin
```

As you can see it does not include `/usr/local/bin` which is causing a lot of issues.

**Comment by faho** [comment]
Fish typically does not modify $PATH. It inherits it from its parent, and will use $fish_user_paths to add paths. It will also read /etc/paths.d.

Add it somewhere there, and you will have it.

**Comment by gretel** [comment]
@faho thanks, setting it manually does solve some but not all issues - functions in `.config/fish/conf.d` have `PATH` set without any changes declared in `config.fish`.

**Comment by faho** [comment]
Not if you set it via $fish_user_paths, /etc/paths.d or in fish's parent process. The latter two of which will also fix it for *everything* - if you want /usr/local/bin for fish, you most likey want /usr/local/bin for *all* processes.

**Comment by heydonovan** [comment]
Upgrading fish broke this for me, thought it was homebrew. Wonder why it worked before. 🤔 

Added `set PATH /usr/local/bin $PATH` to the `~/.config/fish/config.fish` file.

**Comment by gretel** [comment]
alright, setting `PATH` on fish's parent process works. 
wonder why i didnt see this happening prior to `3.1.0` 😕

**Comment by dotboris** [comment]
I've done some digging and found out what's going on.

In the fish v3.1.0 release, we got the following change

> - __fish only parses `/etc/paths` on macOS in login shells__, matching the bash implementation (#5637) and avoiding changes to path ordering in child shells (#5456). It now ignores blank lines like the bash implementation (#5809).

This was done in https://github.com/fish-shell/fish-shell/pull/5637

I've installed both fish v3.1.0 & fish v3.0.2 on my mac and I've done tests to confirm the difference:

In the following tests, I'm using `env -i` to clear my environment so that I start with no environment variables from my parent process.

Fish v3.0.2:

```sh
# 3.0.2 Non login shell
$ env -i /usr/local/Cellar/fish/3.0.2/bin/fish -c 'echo $PATH'
/Users/boris/.local/alt/shims /Users/boris/.poetry/bin /Users/boris/bin /Users/boris/.gem/ruby/2.3.0/bin /Users/boris/.cargo/bin /Users/boris/.composer/vendor/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/Wireshark.app/Contents/MacOS
# 3.0.2 Login shell
$ env -i /usr/local/Cellar/fish/3.0.2/bin/fish -l -c 'echo $PATH'
/Users/boris/.local/alt/shims /Users/boris/.poetry/bin /Users/boris/bin /Users/boris/.gem/ruby/2.3.0/bin /Users/boris/.cargo/bin /Users/boris/.composer/vendor/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/Wireshark.app/Contents/MacOS
```

Notice that they're both the same.

Fish v3.1.0:

```sh
# 3.1.0 non login shell
$ env -i HOME=/Users/boris /usr/local/Cellar/fish/3.1.0/bin/fish -c 'echo $PATH'
/Users/boris/.local/alt/shims /Users/boris/.poetry/bin /Users/boris/bin /Users/boris/.gem/ruby/2.3.0/bin /Users/boris/.cargo/bin /Users/boris/.composer/vendor/bin /usr/bin /bin /usr/sbin /sbin
# 3.1.0 Login shell
$ env -i HOME=/Users/boris /usr/local/Cellar/fish/3.1.0/bin/fish -l -c 'echo $PATH'
/Users/boris/.local/alt/shims /Users/boris/.poetry/bin /Users/boris/bin /Users/boris/.gem/ruby/2.3.0/bin /Users/boris/.cargo/bin /Users/boris/.composer/vendor/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/Wireshark.app/Contents/MacOS
```

Notice that `/usr/local/bin` and some other paths only show up in the login shell.

## Workaround

To work around this, I've changed my terminal (iTerm) to start fish as a login shell (call `/usr/local/bin/fish -l` instead of `/usr/local/bin/fish`)

**Comment by ohk2kt3t4** [comment]
> Upgrading fish broke this for me, thought it was homebrew. Wonder why it worked before. 🤔
> 
> Added `set PATH /usr/local/bin $PATH` to the `~/.config/fish/config.fish` file.
@heydonovan You might want to guard that set statement to prevent PATH from growing, see #5117

**Comment by raszi** [comment]
The reason why I opened the ticket because the behavior changed from the previous version to this version.

Although changing the shell from `/usr/local/bin/fish` to `/usr/local/bin/fish -l` solved my problem.

**Comment by ffittschen** [comment]
When I change the shell to `/usr/local/bin/fish -l` I always get these errors when opening a new shell in iTerm or Terminal:

```
source: Error encountered while sourcing file '/var/folders/m2/8kggf73s7tdc3c14z5btfx5w0000gn/T//.psub.oNmBkVq73I':
source: No such file or directory
```

Is there any other workaround to get the old behavior back?

**Comment by faho** [comment]
@ffittschen It seems you set $TMPDIR to an unusable path in your configuration for login shells. That's not gonna work, and you should fix it.

**Comment by faho** [comment]
Okay, so now I know what's going on here - 3.1.0 changed it so we handle /etc/paths and such like bash et al. Since this is a concern across shells and other programs, being compatible is important here, and there's no great reason to not be compatible, so that's the right choice (of course a design wherein the login process reads these things once would alleviate these problems and free shells from having to reimplement this or call the slow path_helper tool, but that's Apple's decision).

So: If you want fish to read /etc/paths, then like bash you're gonna have to start it as a login shell. If you chsh and set your terminal to start your shell it should happen automatically, if you start "a command" then you need `fish -l`.

**Comment by jcardinal** [comment]
> @ffittschen It seems you set $TMPDIR to an unusable path in your configuration for login shells. That's not gonna work, and you should fix it.

Sorry to hijack the issue, but could you elaborate? I started having the same issue with 3.1.0 and I don't understand where I should be fixing this. (fwiw, I've never knowingly set $TMPDIR to anything anywhere.) Also, if there's any chance it's related, `ls` has started defaulting to `-F` since I installed fish 3.1.0 🙃

**Comment by faho** [comment]
>Also, if there's any chance it's related, ls has started defaulting to -F since I installed fish 3.1.0 upside_down_face

It's not related, but it is another change in 3.1 - 488e208cca9da3e6ecb07a6bfe13646805db59ed.

>I started having the same issue with 3.1.0 and I don't understand where I should be fixing this. (fwiw, I've never knowingly set $TMPDIR to anything anywhere.)

Just to make it clear: The $TMPDIR issue is the one ffittschen was having, with "Error encountered while sourcing file 'SOMETHING/.psub.GOBBLEDIGOOK'". We use $TMPDIR in psub, unless it's not set in which case we default to /tmp.

If that is what happens to you, check if something in your configuration (or your third-party "plugin" stuff) sets $TMPDIR. Check the output of `set -S TMPDIR` for a start.

**Comment by dminca** [comment]
I've just installed `fish v3.5.1` via `homebrew` on MacOS BigSur and it doesn't drop anything under `/usr/local/bin`, instead what you should do if you want the shell change to work, you'd have to point to the location where homebrew installs it (you can find that by `which fish`), for my case it's in `/opt/homebrew/bin/fish`

Then I could do `echo "/opt/homebrew/bin/fish" | sudo tee -a /etc/shells` and finally `chsh -s /opt/homebrew/bin/fish` 😉

**Comment by hieupv2412** [comment]
> I've just installed `fish v3.5.1` via `homebrew` on MacOS BigSur and it doesn't drop anything under `/usr/local/bin`, instead what you should do if you want the shell change to work, you'd have to point to the location where homebrew installs it (you can find that by `which fish`), for my case it's in `/opt/homebrew/bin/fish`
> 
> Then I could do `echo "/opt/homebrew/bin/fish" | sudo tee -a /etc/shells` and finally `chsh -s /opt/homebrew/bin/fish` 😉

Respect. Thank you! 😊

**Comment by Ytired** [comment]
> I've just installed `fish v3.5.1` via `homebrew` on MacOS BigSur and it doesn't drop anything under `/usr/local/bin`, instead what you should do if you want the shell change to work, you'd have to point to the location where homebrew installs it (you can find that by `which fish`), for my case it's in `/opt/homebrew/bin/fish`
> 
> Then I could do `echo "/opt/homebrew/bin/fish" | sudo tee -a /etc/shells` and finally `chsh -s /opt/homebrew/bin/fish` 😉

Thank you! bro😃
