### ISSUE TITLE
New `time` builtin cannot be detected as a builtin

### ISSUE THREAD

**Issue by charlesbjohnson** [fish-shell/fish-shell#6598]
Hi 👋 

I've just upgraded to 3.1.0 and have just learned about the new `time` builtin. I'm running into a small issue, though, where the `builtin` command doesn't seem to be aware that `time` is now a builtin.

```
$ builtin -n | grep time; echo $status
$ 1
$ builtin -q time; echo $status
$ 1
```

~As far as I can tell, this is because it was removed from `src/builtin.cpp` in 664d6fb13298976f35ae9278ebb7a08e9beb6feb. I'm not very familiar with this project, but would you accept a PR adding it back as a `builtin_generic`?~

Edit: It's a little bit more work than I thought, see #6599.

**Comment by krobelus** [comment]
Ugh this is a bit tricky since it's implemented as dedicated node in the grammar in order to support timing fish functions and blocks.
When adding `time` as generic builtin, the tests fail because `a=b time` is supposed to call the external command `time`, which it doesn't if it is a builtin. This behavior might not be too important, because one can use the more explicit `a=b command time` instead. So we could break it (changing the test), or add some workarounds like we do for `and`/`or`.

Also `time -h` and `time --help` are not supported currently. Similar story here.

**Comment by faho** [comment]
I'm pretty sure we do something similar to what is required here for `command`.

**Comment by ridiculousfish** [comment]
Right, these keywords have a dual life as both a keyword and a builtin. The builtin form is used for `--help` in particular; it doesn't need to do anything more than that.
