### ISSUE TITLE
How to see fish functions with `man -k` or `apropos`?

### ISSUE THREAD

**Issue by okamsn** [fish-shell/fish-shell#6608]
Hello,

Fish comes with a function `man` to make `man` prefer its own documentation, but it does not affect `man -k` or `apropos`.

- This works: `man abbr`.
- This finds nothing: `man -k abbr`, `apropos abbr`.

What is the proper way to include the Fish manual pages in the `apropos` search?

Thank you.

**Comment by ridiculousfish** [comment]
You can put fish's man pages in MANPATH, for example:

    set -ax MANPATH $__fish_data_dir/man

Does that work for you?

**Comment by okamsn** [comment]
No, that does not work.
Before doing that, `man -k abbr` gives

    Text::Abbrev (3perl) - abbrev - create an abbreviation table from a list

but after, it gives

    abbr: nothing appropriate.

This behavior is on Xubuntu 19.10 with Man 2.8.7 and Fish 3.1.0. Does it work for you?

**Comment by faho** [comment]
So `man abbr` just checks $MANPATH for the file and opens it. `man -k abbr` starts apropos, which then reads the whatis database and such to find it.

I *think* you need to update the whatis database, which we can't do because it's typically root-owned. Or it's enough to pass $MANPATH with the fish directory to `apropos`?

On my system the following worked:

```fish
sudo mandb /usr/share/fish/man:/usr/local/man:/usr/local/share/man:/usr/share/man:/usr/lib/jvm/default/man
MANPATH=/usr/share/fish/man:/usr/local/man:/usr/local/share/man:/usr/share/man:/usr/lib/jvm/default/man apropos abbr
```

Tho note that man is almost entirely unstandardized, and there are quite varying implementations in the wild.

**Comment by Darkshadow2** [comment]
Only impossible to update it for /usr/share/man on macos. `makewhatis` still updates any other man path given to it.

(Actually, it's not impossible, you just have to jump through hoops to do it.  Disable SIP and mount the root partition as read/write, and `makewhatis` will work. That's just a pain to do.)

**Comment by okamsn** [comment]
It works if I do `sudo mandb $__fish_data_dir/man`. I was hoping that it could be done without `sudo`, but I accept that this is not the case.

 Thank you.
