### ISSUE TITLE
Confusing color markups show on the documentation page

### ISSUE THREAD

**Issue by kidonng** [fish-shell/fish-shell#6640]
Color markups such as `<red>` and `<gray>` show on the documentation page, for example:
https://github.com/fish-shell/fish-shell/blob/master/doc_src/tutorial.rst#L85-L87

```
You'll quickly notice that ``fish`` performs syntax highlighting as you type. Invalid commands are colored red by default::

    > <red>/bin/mkd</red>
```

![image](https://user-images.githubusercontent.com/44045911/75095904-afdac800-55d4-11ea-9e53-e6d01cb0d584.png)

It's quite confusing. Don't know if it is intended as the markup is for indicating purpose, or the documentation generator doesn't parse the markup into color style correctly.

**EDIT:** Went to see the web archive and got this:

![image](https://user-images.githubusercontent.com/44045911/75096068-976bad00-55d6-11ea-9682-7a8aae5c01aa.png)

So my latter assumption is right, it's unexpected behavior.

**EDIT 2:** Just ran into more confusion:

![image](https://user-images.githubusercontent.com/44045911/75096133-7061ab00-55d7-11ea-88b2-b8379e8d1bf6.png)

![image](https://user-images.githubusercontent.com/44045911/75096135-75265f00-55d7-11ea-8fc2-ea55fb613889.png)

Guess I should turn to the old documentation site for the moment😅

**Comment by faho** [comment]
Yeah, this used to be parsed by the doxygen documentation generator.

We don't have a great solution to color this as I don't think sphinx supports this kind of coloring in code blocks, but we can just turn off the blocks.

>Guess I should turn to the old documentation site for the momentsweat_smile

No, you should not. The new site has quite a number of improvements, even with some weird markup.

Anyway, should be fixed in 3.1.1.

**Comment by kidonng** [comment]
Thanks for the quick fix 😊

> No, you should not. The new site has quite a number of improvements and corrections, even with some weird markup.

I wrote Edit 2 because there's a typo (the second < should be >, hope you also fix it), which made me think the documentation was not stable😅 that's it.

**Comment by faho** [comment]
>I wrote Edit 2 because there's a typo (the second < should be >, hope you also fix it), which made me think the documentation was not stablesweat_smile that's it.

No, it's correct.

This is an stdin redirection. Instead of passing `grep` the file*name* as the second argument, which means grep will open the file to read it, this opens the file and connects it to grep's standard input.

Just like `>` opens the file and connects it to standard output, causing grep's writes to end up there.

**Comment by kidonng** [comment]
Sorry I don't make it clear, I'm talking about this sentence:

> stdin and stdout can be redirected via the familiar < and <.

which should be:

> stdin and stdout can be redirected via the familiar < and >.

**Comment by faho** [comment]
>Sorry I don't make it clear, I'm talking about this sentence:

Oh, yes, of course! Terribly sorry, fixing immediately!

**Comment by zanchey** [comment]
Fixed in Integration_3.1.1 as  62f53e300acf32 and cb34efe897808703675 with thanks to @faho
