### ISSUE TITLE
CTRL+L keybind uses a string replace rather than clear +x

### ISSUE THREAD

**Issue by ghost** [fish-shell/fish-shell#6732]
#2855

It works fine as it is, but is `clear -x` a bit more simple?

`bind \cl clear\ -x\ \; \ commandline\ -f\ repaint` seems to work as expected on my system

Also, if you find that `clear` from ncurses 6 without the -x doesn't actually clear your scrollback as it should, as I find with urxvt, you can confirm that is a just terminal problem if `printf "\e[3J\033c"` does work.

**Comment by faho** [comment]
>Also, if you find that clear without the -x doesn't actually clear your scrollback as it should

It should **not**. That's the entire problem and reason for hacking that in the first place. `clear` should "clear" the screen. Clearing the scrollback as well is a landgrab, and one that is *terrible* user experience if you didn't expect it, because it then removes information you might have relied upon.

It's not a termcap problem if it doesn't clear scrollback, it's a problem if it *does*.

----

Guess I'd have to check how this works on other systems - old ncurses, NetBSD, etc...

**Comment by buckshee** [comment]
fixed the last paragraph, clearly ( 🥁🤡) its not a big problem, anyone using clear in a srcipt is proably not even going to notice.

Do you think a built-in called 'cls' for the key bind that just directly does the escape would be a better thing?

On ubuntu 16.04 with ncurses 6.0, `clear -x` is not a listed option (compat build?), and exit status was 0 with no output
