### ISSUE TITLE
Incorrect behaviour with regard to 'or' command

### ISSUE THREAD

**Issue by lriuui0x0** [fish-shell/fish-shell#6745]
fish, version 3.1.0

WSL
Linux 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color

Not using third party customization. The problem persists after running the command.

Reproduce problem:

Run the following command: 

$argv is set to empty
```
if test (count $argv) -eq 0 ; or test (count $argv) -eq 1 ; and test $argv[1] = 'push' ; echo 'x' ; end
```

Fish reports `test: Missing argument at index 2`. I think the expected behaviour is only the first `test` runs and the command echos 'x'.

**Comment by zanchey** [comment]
In one sense, your command is incorrect - you must always surround variable arguments to `test` with quotes, otherwise it is potentially invalid.

What happens here is you are running `a; or b; and c`, or `a || b && c`. Fish parses this with left-to-right associativity, that is, as `(a || b) && c`, whereas you expect `a || (b && c)`. bash behaves the same here.

This doesn't seem to be a bug, in my view; if you want the alternative behaviour you can use `begin` and `end` blocks, or just make a giant test expression:

```
if test (count $argv) -eq 0 -o \( (count $argv) -eq 1 -a "$argv[1]" = 'push' \)
   echo x
end
```

**Comment by lriuui0x0** [comment]
> What happens here is you are running a; or b; and c, or a || b && c. Fish parses this with left-to-right associativity, that is, as (a || b) && c, whereas you expect a || (b && c). bash behaves the same here.

That clarifies it. Thanks! After wrapping it within `begin ... end`. The command works :)
