### ISSUE TITLE
Tab completion bug with unicode prompt

### ISSUE THREAD

**Issue by vrinek** [fish-shell/fish-shell#6754]
```sh
# fish --version
fish, version 3.0.2
# echo $version
3.0.2
# uname -a
Linux taco 5.3.0-7642-generic #34~1584134558~19.10~2c304de-Ubuntu SMP Sat Mar 14 00:32:42 UTC  x86_64 x86_64 x86_64 GNU/Linux
# echo $TERM
st-256color
```

It's quite difficult to explain the bug without a video:
[![asciicast](https://asciinema.org/a/IlhyitpMdx2sPAiuzgIKDJgHP.svg)](https://asciinema.org/a/IlhyitpMdx2sPAiuzgIKDJgHP)

Pretty much I type `asci` and hit tab, some odd duplication of text happens, then I repeatedly hit backspace. That last `a` character is not deletable anymore and it does not seem to exist in fish's _mental representation_ of the command line contents because when I hit enter, fish does not complain about `a: command not found`.

FYI, this is the entirety of my `~/.config/fish/config.fish`:
```fish
starship init fish | source
```

The terminal I'm using is [Alacritty](https://github.com/alacritty/alacritty) and I have installed fish via [nix](https://github.com/NixOS/nix). This bug also manifests on fish v3.1.0 (from which I had to downgrade for other reasons). It also is not limited to Alacritty, it also happens on other terminals like Konsole.

Starting fish with `sh -c 'env HOME=$(mktemp -d) fish'` fixes the issue so I can only assume it is triggered by [starship's](https://starship.rs/) default prompt, probably due to the unicode characters (default prompt is `❯`). The issue does not manifest when I change the prompt character to `>` (ascii), and also does not manifest in bash (with same starship prompt configured).

**Comment by faho** [comment]
What happens here is the same thing as in #6584 #4539, and many other issues, and the solution is the same:

You need to configure your terminal so that the displayed with of "❯" matches what your OS's "wcwidth" function returns. In this case that'll be "1", if your terminal displays "❯" as using two cells you need to fix it, most likely by adjusting its configuration.

I can't reproduce this with the starship prompt with st, alacritty or konsole, with fish 3.1.0 (which had numerous fixes in the unicode department, in particular farting around with $fish_emoji_width should typically not be needed anymore)

Also note:

>The terminal I'm using is Alacritty

># echo $TERM
>st-256color

That's wrong. $TERM for alacritty (and most other terminals) should be "xterm-256color". Mixing and matching these is wrong.

**Comment by vrinek** [comment]
Apologies for the very late response.

I just tried what you suggested and it looks like even with `xterm-256color` I experience the same issue.

At this point I'm on the following configuration:
```
# fish --version
fish, version 3.1.2
# echo $version
3.1.2
# uname -a
Linux taco-linux 5.4.0-7629-generic #33~1589834512~20.04~ff6e79e-Ubuntu SMP Mon May 18 23:29:32 UTC  x86_64 x86_64 x86_64 GNU/Linux
# echo $TERM
xterm-256color

# and just for completeness,
# alacritty --version
alacritty 0.4.3
```

Maybe I should also mention that I installed fish with Nix, similar to https://github.com/fish-shell/fish-shell/issues/6584 I assume.

**Comment by faho** [comment]
@vrinek The issue in #6584 was specifically that the locale wasn't unicode capable.

If you execute `locale` and that prints something not ending in "UTF-8" (or "utf8") for "LC_CYTPE" then your system configuration is broken and needs to be fixed, by setting a unicode-capable locale.

**Comment by faho** [comment]
@mthadley: This solution is *not* to remove the unicode character, the solution is to fix your locale settings.

If you have this problem, then it's most likely down to your `locale` being set to C instead of something unicode-capable (like e.g. en_US.UTF-8). Change that and it's fixed. There is no issue in fish to workaround, there is misconfiguration of *your system*.

**Comment by mthadley** [comment]
@faho Sorry, I didn't mean to link back to this issue or give you a notification. I forgot that Github does that for extended commit messages, and it was just meant for my own reference until I can get around to figuring out what's wrong with the locale.

**Comment by faho** [comment]
Ah, okay.

Yeah, I've looked into this further, and it seems like nix without nixos doesn't include the locales. See https://github.com/NixOS/nixpkgs/issues/6878 and https://github.com/rycee/home-manager/issues/354.

So apparently you need to install "glibcLocales" and point $LOCALE_ARCHIVE at that.

**Comment by mthadley** [comment]
@faho Thanks, that fixed it for me! Hooray for fancy unicode characters in my prompt again.

**Comment by faho** [comment]
Yeah this is 100% a nix issue.

**Comment by jbddc** [comment]
I also have this issue on macOS with fish installed via nix, but my locale seems to be fine. What else could be at play here?
