### ISSUE TITLE
Ctrl-Left/Right Arrow doesn't work with vi key bindings

### ISSUE THREAD

**Issue by YaLTeR** [fish-shell/fish-shell#6755]
fish version 3.0.2
Fedora 31 and Arch Linux, Tilix and Alacritty

Ctrl-Left/Right Arrow do something weird instead of working when the vi key bindings are active. Alt+Left/Right Arrow works fine.

1. `sh -c 'env HOME=$(mktemp -d) fish'`
2. `fish_vi_key_bindings`
3. Type something and try using Ctrl-Left/Right Arrow

**Comment by faho** [comment]
Please execute `fish_key_reader`, press ctrl-left. That'll give you something like

```fish
bind \e\[1\;5C 'do something'
```

Take that, chop off the "do something" bit, so that you just execute

```
bind \e\[1\;5C
```

On my system that just says it's bound to "forward-word" in the default bindings and nothing in the vi ones, which seems correct.

**Comment by YaLTeR** [comment]
That's the same as I get. So I guess it tries executing the sequence literally which leads to the "weird behavior" (exiting to normal mode and sometimes inserting additional text from previous command).

**Comment by faho** [comment]
Well, that's to be expected. Ctrl-arrow sends

```
\e\[1\;5C
```

which is escape, then `[1;5C`. So it does the thing for escape, which is exit to normal mode, then the thing for `[', which is searching history, then the thing for `;`, which is repeating a jump, then the thing for `5`, which is nothing, then the thing for `C`, which is killing a line and repainting.

I don't think there is a good way around this, because we can't conclusively enumerate all possible escape sequences, and I don't think there is a set enough pattern for these.

**Comment by YaLTeR** [comment]
Maybe ctrl+arrows should be bound for the vi insert mode by default? In the actual vim insert mode ctrl+arrows also jumps words.

**Comment by faho** [comment]
Huh, so it does.

Yeah, lemme fix that.
