### ISSUE TITLE
Weird artifact [127] after unknown command

### ISSUE THREAD

**Issue by DonkeyShot21** [fish-shell/fish-shell#6768]
I am getting a weird artifact ([127]) after unknown command. Then after another command is executed successfully it goes back to normal. Look at the screenshot attached, it is hard for me to explain what is going on.

Version: 3.1.0
OS: Manjaro KDE
Terminal: Konsole or Yakuake
Without third-party customization it has the same behaviour.

![image](https://user-images.githubusercontent.com/19649581/77016796-0ab7d300-6979-11ea-8b4a-5cc9bd1eb359.png)

**Comment by faho** [comment]
That's the command's return status ($status). The default prompt prints it if it isn't 0, and if a command isn't found fish sets it to 127.

**Comment by DonkeyShot21** [comment]
Ok sorry for being a noob. Can I ask why it is placed there? It really looks like a glitch. Also, why is it repeated even if I press return?

Finally, how can I get rid of it? Google doesn't work lol

**Comment by faho** [comment]
>Also, why is it repeated even if I press return?

Because pressing return with an empty commandline runs nothing, so it doesn't change $status.

>Finally, how can I get rid of it? Google doesn't work lol

Same way you'd do anything to your prompt. Modify the `fish_prompt` function. E.g. use `funced fish_prompt` to edit it, find where the status is printed, remove it. Once you're happy use `funcsave fish_prompt` to save it.

**Comment by DonkeyShot21** [comment]
Ok great, thanks! I'll close.
