### ISSUE TITLE
Add an option in history builtin to show timestamps

### ISSUE THREAD

**Issue by siteshwar** [fish-shell/fish-shell#677]
We are storing timestamps for starting time of each command in history. We should enable history builtin to show these timestamps when an option like "--with-time" is passed. For e.g.

```
history --with-time
```
should output :

```
Sun Apr 21 01:12:25 IST 2013  man fdisk
```

Ideas are welcome on how to choose date/time format and how to separate timestamps from command.

**Comment by krader1961** [comment]
I would also like to see this implemented. The reason is that I sometimes find myself wanting to know not just whether or not I ran a specific command but when I did so. For example, I report attacks against my web server when they come from cloud providers. It's useful to know not only if I already reported a given attack but how far back in time I did so. Yes, my reporting tool could (and really should) keep track of that information but that's just a real world example for why the feature requested by @siteshwar can be useful.

My recommendation is to employ the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) in keeping with the overarching philosophy for the fish-shell. Which means no new options or configurable behavior. The timestamp should be in a shortened [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601) using local time and therefore without an explicit timezone. Because of the nature of this data, especially the timespan likely to be covered, we can probably omit the year but I recommend including it to avoid ambiguity. I also see little need for a resolution more fine grained than the minute. In other words, I would recommend 'YYYY-MM-DD hh:mm' as the standard format for the timestamp and it should always be prefixed to the command and separated from it by a space. The original example by @siteshwar would look like this under my proposal:

```
2015-04-21 01:12 man fdisk
```

This matches the output of @ndemou's script with the omission of the second the command was run. It is also unambiguous and trivial to parse without having to worry about locale specific, or personal, conventions. Also, if we really wanted to be anal we could use "T" rather than a space to separate the two elements of the timestamp per the ISO 8601 specification:

```
2015-04-21T01:12 man fdisk
```

However, I think that worsens readability without a commensurate improvement in any other aspect of the `history` command output.

I was also going to ask that there be a variable that mirrors $history which has the timestamps so that I could write a function that iterated over both vars and thus have access to the command and the timestamp. However, I think that, at least initially, this change should be limited to the behavior of the `history` command and not add a new special-case variable.

**Comment by faho** [comment]
>local time and therefore without an explicit timezone

Okay - though it'd probably be nice if it checked $TZ, if anyone needed conversion they could do it afterwards.

>I also see little need for a resolution more fine grained than the minute

I'm quite certain if we did up-to-minute, someone would ask for seconds. Since we already have seconds (it's unix time after all), why not just print them?

**Comment by krader1961** [comment]
> though it'd probably be nice if it checked $TZ

Not sure what you're suggesting. When I say it should be displayed in local time I mean the UTC timestamp should be converted to the timezone as defined by $TZ before being displayed.

As far as the resolution, minutes or seconds, I don't have a strong opinion. Minutes should be more than sufficient detail and adding seconds takes three more chars on the line. But it's not worth arguing about so a format of "YYYY-MM-DD hh:mm:ss" is fine by me.

**Comment by faho** [comment]
>Not sure what you're suggesting.

On my system (archlinux), $TZ is undefined. Programs check /etc/localtime instead. Only that's not as easily overridable.

>When I say it should be displayed in local time I mean the UTC timestamp should be converted to the timezone as defined by $TZ before being displayed.

That's okay then.

**Comment by krader1961** [comment]
> On my system (archlinux), $TZ is undefined. Programs check /etc/localtime instead.  

@faho: Is your archlinux user space code based on glibc? If it isn't does it not follow the convention of using whatever timezone was explicitly set via $TZ? I primarily use Mac OS X and various flavors of Linux. Both fall back to /etc/localtime if $TZ isn't defined but use $TZ if it is defined. Regardless, this should be a non-issue in practice for any system that implements the family of functions that include `localtime()`.

Regarding @faho's point that as soon as we display the time to a resolution of  one minute people will ask for a resolution of one second. Why not display milliseconds? Or microseconds? Or nanoseconds? Such people make me think of a coworker who took data with a resolution of three significant digits and computed percentages with nine significant digits. Causing me to exclaim "WTF!". Just because there are innumerate people doesn't mean we should cater to them. Nonetheless, despite the fact most people are innumerate I still agree that we should display the timestamp with a resolution of seconds if only to forestall a lot of ill-founded requests to show the second the command was run.

**Comment by faho** [comment]
>Is your archlinux user space code based on glibc?

Yes, it is. I didn't know that implemented that logic. Now that I think about it, it sounds kinda logical.

>Regarding @faho's point that as soon as we display the time to a resolution of one minute people will ask for a resolution of one second. Why not display milliseconds? Or microseconds? Or nanoseconds? Such people make me think of a coworker who took data with a resolution of three significant digits and computed percentages with nine significant digits.

Well, we _have_ enough precision for seconds - the one thing missing is leap seconds and there's been 36 (IIRC) of those since 1970. We don't have enough for milliseconds. I just don't see a reason for downsampling, so I think that we should offer all we can.

**Comment by pickfire** [comment]
> My recommendation is to employ the KISS principle in keeping with the overarching philosophy for the fish-shell.

I like the KISS Principle too, that's what keep arch linux alive.

> The timestamp should be in a shortened ISO 8601 format using local time and therefore without an explicit timezone.

Of course, why not. https://xkcd.com/1179/

**Comment by krader1961** [comment]
Actually, we do, in theory, have enough precision for milliseconds or even finer grained timestamps. All we have to do is switch from time(2) to gettimeofday(2). Which is my point. Just because we're using a library or syscall with a given precision doesn't mean that level of precision should be displayed in the `history` output. Having said that, I still accede to your point that enough users are likely to, misguidedly, ask for a displayed timestamp with a resolution of one second that we might as well do so in the first implementation.
