### ISSUE TITLE
Tab completion for watch does not suggest executables that are not in $PATH

### ISSUE THREAD

**Issue by lyu** [fish-shell/fish-shell#6798]
fish version: 3.1.0, with the default configuration
OS: Arch Linux x86_64
TERM: xterm-256color
watch version: procps-ng 3.3.16

Steps to reproduce:

- Create a bash/python/binary/whatever executable file under the current directory
- In the shell, type `watch -n 0.5 ./`, and hit tab

Expected behavior: fish suggests a list of executable files and/or directories under the current path

Observed behavior: nothing happens

**Comment by krobelus** [comment]
Good catch, also happens for other commands, like `sudo` that use `__fish_complete_subcommand`.
Introduced via #6249; we can probably just fix this by making `__fish_complete_external_command` a bit smarter, although I'm not super convinced the current version with `find` is ideal, because fish already knows how to do that. So it's probabliy better to call `complete -C (commandline -ct)` and filter out functions and builtins.

**Comment by krobelus** [comment]
Fixed in master and in 3.1.1 at the cost of also suggesting functions, builtins and abbreviations, which is probably not a big deal, I don't think anyone had complained about that before.

Keeping this open to decide if we should do something like [adding a complete --executables-only options](https://github.com/krobelus/fish-shell/compare/complete-executables-only~2..complete-executables-only) to make it possible for users to get completions for external commands onlly.

**Comment by zanchey** [comment]
Closing this one as fixed for now with further enhancements in #6943.
