### ISSUE TITLE
Portable fish (static linked with musl libc)

### ISSUE THREAD

**Issue by anki-code** [fish-shell/fish-shell#6808]
Hi!

For [xxh project](https://github.com/xxh/xxh) I've built [statically linked portable fish binary](https://github.com/xxh/fish-portable) with [musl libc](https://www.musl-libc.org/). I've tested it in Alpine, Ubuntu 14/16/18, CentOS and Arch. You can just run it and it works.

Try it standalone:
```
mkdir /tmp/fish && cd /tmp/fish
wget https://github.com/xxh/fish-portable/raw/master/result/fish-portable-musl-alpine-Linux-x86_64.tar.gz
tar -xzf fish-portable-musl-alpine-Linux-x86_64.tar.gz
./bin/fish.sh
```

Or try it with [xxh](https://github.com/xxh/xxh):
```
xxh +RI xxh-shell-fish
xxh myhost +s xxh-shell-fish
```

Could anyone take a look on [building process](https://github.com/xxh/fish-portable/blob/master/fish-portable-musl-alpine.Dockerfile), try the result binary and give advice or ideas how to reduce result file size (now it around 60mb)? Feedback is appreciated.

Thanks!

**Comment by krobelus** [comment]
You can build without debug info (which is mostly useful to get nice backtraces when fish crashes I guess).

Here's how the size of a fish binary changes with different build flags (all dynamically linked against glibc):

```
 52M cmake -DCMAKE_BUILD_TYPE=ReleaseWithDebugInfo (the default)
 32M cmake -DCMAKE_BUILD_TYPE=Debug
2.4M cmake -DCMAKE_BUILD_TYPE=Release
1.7M cmake -DCMAKE_BUILD_TYPE=MinSizeRel
```

**Comment by joanbm** [comment]
I did just take a quick look and the version I have built using my Dockerfile in the other thread is only 30MB, so it's definitely strange that yours is 60MB.

Broken down my fish binaries are roughly:
* 10MB for the fish binary
* 10MB for fish_indent and fish_indent and fish_key_reader
* 10MB for completions

For reducing the size of the main fish binary, try building with size reduction flags, or maybe packing with UPX is also a good possibility?

I am also not sure if fish_indent and fish_key_reader are really necessary. If they are, since I guess most of the size is taken by linked libraries, then maybe it's possible to prune unnecessary ones them or somehow make a "semi-static" build where the libraries are shared between the fish, fish_indent and fish_key_reader binaries? I don't know much about static and dynamic linking to help with this.

I may be able to take a further look at this, but unfortunately I am quite busy recently so no promises.

**Comment by anki-code** [comment]
@krobelus many thanks! The size was dramatically decreased to 8mb with `cmake -DCMAKE_BUILD_TYPE=MinSizeRel` and it still works!

**Comment by krobelus** [comment]
Sadly the binary alone is not really useful on its own. It has some basic functionality, but for example up-arrow history search does not work, since it is implemented as a function.
So you probably want to include the `share` folder from the fish sources, which contains functions and other configuration. I think AppImage uses a squashfs to store directory trees in a single file.

**Comment by anki-code** [comment]
Yes, I've tried AppImage and added it to xxh first. The problem with `fish.AppImage` is it build on fresh version of GLIBC and not working on a bit older Linux distros. I've wrote the recommendation for fish team here - https://github.com/fish-shell/fish-shell/issues/6475#issuecomment-598113384 . For example Python PEP recommend use manylinux2010 to build AppImages.

**Comment by anki-code** [comment]
> but the use case is to run it on systems that don't have any fish version

You're completely right. I see in `/usr/share/fish` seven megabytes of functions and other stuff. It's not so big. If I want to just add it as a directory along with my fish binary what environment variables or arguments I should run fish?

**Comment by krobelus** [comment]
You should use `make install` (set `-DCMAKE_INSTALL_PREFIX=prefix` for the installation destination).

This will create a directory hierarchy like this, then fish will be able to find the `share` directory`:

```
prefix/bin/fish/
prefix/share/fish/
prefix/share/doc/fish/
...
```

Then just tar up all of that up.

You'll see if it works when fish set's the correct  `$__fish_data_dir`.
If you don't create such a directory hierarchy, then fish thinks it is being run from its source tree and uses different paths.

**Comment by frederickjh** [comment]
I believe the man pages are used by Fish for completions of external programs, not sure if this is the same for internal completions too.

**Comment by anki-code** [comment]
> Then just tar all of that up.

It works pretty cool! Thanks! I've added this to [xxh/fish-portable](https://github.com/xxh/fish-portable) and to [xxh-shell-fish](https://github.com/xxh/xxh-shell-fish).

>  you will need sphinx and -DBUILD_DOCS=ON.

I've facing that sphinx install is not trivial in Alpine. Will do it a bit later.

So I'm going to close this issue with great feeling of help. Thanks!
