### ISSUE TITLE
Add array completion to `complete` 

### ISSUE THREAD

**Issue by snowe2010** [fish-shell/fish-shell#6833]
`zsh` has the concept of `value` completions, also known as array completions. This would be something like `command --option-that-takes-several-values=val1,val2,val3` where `val1`, `val2`, and `val3` are distinct items in a list.

Here is an example of how this renders in a terminal:

![zshexample](https://user-images.githubusercontent.com/1534535/77861462-5452ba00-71d2-11ea-8493-d8314b437bb7.gif)

I am only able to come up with one solution, due to not knowing all the different things that zsh actually supports. 

`--value-separator` and `--option-type` flags, where `--value-separator` defines the separator (default to `,`) but is only used if `--option-type` is specified where `--option-type` is of type `array` (or whatever you decide)
Obviously this leaves room for more option-types, like hashes/maps (`--opt=key:value,key2:value2` where `--value-separator=,` and `--key-separator=:` and `--option-type=hash`)

I haven't completely thought through this so feel free to poke holes.

**Comment by krobelus** [comment]
So the status quo is that completions have to manually split the token, and then print a new valid token. For example with a token `a,b,^,c`, cursor is the `^`:

```fish
for value in $possible_values
    printf "a,b,$value,c\t$description_for_value\n"
end
``` 

It works this way currently because a completion replaces the entire token. Making this more flexible is #6687. If we have that, it might be sufficient in above example to compute `$value\t$description_for_value\n` as completion, but then we'd also need to specify where to insert that completion, for example by specifying delimiters.

---

We could add support for your example to `complete`:
But I think it would be better and more flexible to provide a helper function instead that abstracts splitting the current token, and printing it with the all possible arguments filled in.

Another example use case is git commit ranges, which are two (optional) values separated by `..` or `...`.

**Comment by snowe2010** [comment]
@krobelus So I got help from @ridiculousfish in creating a script: 

```fish
function get_foo_args
    # Here are our possible comma-separated values.
    set choices happy green dragon

    # Get what the user has typed so far as the token under the cursor.
    # For example, this might be "--stuff=abc,def"
    set token (commandline -ct)
    
    # We don't know if the user used a space or = separator.
    # Split about =, and take the last part.
    set input (string split = -- $token)[-1]
    
    # Get the items that the user has written so far, discarding the last item.
    # That is, if the user wrote "happy,green,dr<tab>" then we want to discard the 'dr'.
    set input (string split ',' -- $input)
    set -e input[-1]
    set input (string join ',' -- $input)

    # Now propose every possible choice, trimming leading and trailing commas.
    for choice in $choices
        echo "$input,$choice" | string trim --chars ',' 
    end
end

complete -c foo --exclusive --long-option stuff --arguments "(get_foo_args)"
```

is this what you mean by splitting manually? The issue with this is that it doesn't remove tokens you've already completed, it also shows the entire token as a single string in the output. So if my token gets really long it becomes super confusing what you're actually tab completing. I realize the first issue could be solved just by checking tokens, but helper functions here would definitely help. IN regards to the token always being a concatenation of previously completed tokens, that's just a bit frustrating, especially when the zsh solution is so nice looking (though absolutely terrible to understand the syntax for).

**Comment by krobelus** [comment]
Yeah, exactly. At the moment you have to print the entire token from your completion function.
Lifting that requirement should be possible, maybe with an additional flag to `complete`.

The current model is quite easy to understand. I agree it is not ideal for this use case.
Take a look at [share/completions/fish.fish#L19-23](https://github.com/fish-shell/fish-shell/blob/master/share/completions/fish.fish#L19-L23) which is a concise example of multi-value completions for `fish --features=`. This could be extracted to a helper function, or just copied. Unfortunately the completion does not work as smoothly as your recording, since you have to type backspace after completing a value to complete another one.
If we add a dedicated  flag, then we can match zsh's behavior here. It'd look like this:

```fish
complete -c foo --exclusive --long-option stuff --arguments "happy green dragon" \
         --argument-separator ","
```

We should make a list of commands that sport this pattern. If this happens often then it's probably worth adding special support.

**Comment by faho** [comment]
Sooo... has anyone here checked out our [__fish_append](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_append.fish) helper function?

That does basically what this does. Even if it's not perfect, it's at least prior art?

**Comment by exploide** [comment]
> We should make a list of commands that sport this pattern. If this happens often then it's probably worth adding special support.

I think it is definitely worth it.

```
nmap --script=smb-enum-users.nse,smb-enum-groups.nse,smb-enum-services.nse
mount -o remount,bind,ro olddir newdir
journalctl --output-fields=verbose,export,json
su --whitelist-environment=TERM,LC_LANG
curl --proto =http,https
```

just to list some of the more common.

**Comment by snowe2010** [comment]
Oh awesome examples @exploide. Thank you!

**Comment by exploide** [comment]
> Sooo... has anyone here checked out our __fish_append helper function?

Also [__fish_complete_list](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_complete_list.fish) seems to serve a similar purpose.

**Comment by exploide** [comment]
It seems `__fish_append` and `__fish_complete_list` work very similar. Despite `__fish_append` takes the arguments directly, while `__fish_complete_list` takes a command to produce arguments. And `__fish_complete_list` has prefix functionality.

I'm wondering whether it makes sense to unify the usage of these functions and remove one of them?

Then, what is left in this issue? The appearance of previous arguments in the completion pager?

**Comment by faho** [comment]
It seems there's nothing left to add here. Use the helper functions that are already there.

If there's a more specific issue that should be discussed, probably in a separate issue.
