### ISSUE TITLE
/usr/share/fish/vendor_functions.d/ is empty

### ISSUE THREAD

**Issue by filipallberg** [fish-shell/fish-shell#6841]
I just upgraded from fish v2 to v3.

My `/usr/share/fish/vendor_functions.d/` is completely empty and so I cannot invoke `prompt_iamroot`. Admittedly, the directory is not on my path either (maybe because it is empty?)

```
$ echo $fish_complete_path 
/tmp/tmp.EZbgN6N3q6/.config/fish/completions /etc/fish/completions /usr/share/fish/vendor_completions.d /usr/local/share/fish/vendor_completions.d /usr/share/fish/completions /tmp/tmp.EZbgN6N3q6/.local/share/fish/generated_completions
```

however, the function is not anywhere inside `/usr/share/fish`. Heres my set-up,

```
$ fish --version
fish, version 3.1.0
```
```
$ uname -a
Linux dev 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.12 (stretch)
Release:        9.12
Codename:       stretch
```
```
$ sudo apt-cache policy fish
fish:
  Installed: 3.1.0-1.1
  Candidate: 3.1.0-1.1
  Version table:
 *** 3.1.0-1.1 500
        500 http://ftp.de.debian.org/debian testing/main amd64 Packages
        100 /var/lib/dpkg/status
     3.1.0-1 500
        500 http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_9.0  Packages
     2.4.0-1 990
        990 http://ftp.acc.umu.se/debian stretch/main amd64 Packages
````

Ran `sh -c 'env HOME=$(mktemp -d) fish'` but problem persists.

**Comment by faho** [comment]
There's a bit of a misunderstanding here.

That vendor_functions.d is empty is entirely expected. It's a directory that is meant for *other vendors* to put their functions in. So if you want to have something there, you (or a thing you install) has to put it there. Fish doesn't ship anything in it.

So if you expect a "prompt_iamroot" function there, you've forgotten to install it.

>Admittedly, the directory is not on my path either (maybe because it is empty?)

Well, no, because you're checking $fish_*complete*_path, which is meant for *completions*. Check $fish_*function*_path.

**Comment by filipallberg** [comment]
Oh okay, I wonder what spawned that function to exist then. When I search for it I just find it inside of cygwin :s 

Closing this. Sorry for the confusion.
