### ISSUE TITLE
Export function to child fish scripts

### ISSUE THREAD

**Issue by fdcds** [fish-shell/fish-shell#6842]
I would like to write code like the following:
```fish
function do
  echo "doing..."
end
export -f do
exec another-script.fish do
```

`another-script.fish` would contain something like `eval $argv`. I would expect it to execute the `do` function from the parent script.

I am using Fish 3.0.2 on Linux 5.5.11 in KDE Konsole.

**Comment by faho** [comment]
Bash has something like this. It's a fairly obscure little-known function that had its time in the lime light when it was the cause for the [shellshock vulnerability](https://en.wikipedia.org/wiki/Shellshock_(software_bug)).

So: Because it is of very little use and potential cause for concern, we will not be implementing this.

Please find some other way to pass your thing, whether that be as a separate script that you name, or as code via an argument or stdin that you `eval` or `source`.

**Comment by fdcds** [comment]
I am using this code now:
```fish
set -l script (mktemp)
chmod +x $script

function onexit --on-process-exec %self
        rm -f $script
end

echo "#!/usr/bin/fish
        echo "doing..."
" > $script

another-script.fish $script
```

Note that I am not using `exec`, because `--on-process-exit` would not trigger in that case.
