### ISSUE TITLE
Optimize -c away for simple cases

### ISSUE THREAD

**Issue by jruere** [fish-shell/fish-shell#6902]
fish, version 3.1.0
3.1.0
Linux serpico 5.6.4-arch1-1 #1 SMP PREEMPT Mon, 13 Apr 2020 12:21:19 +0000 x86_64 GNU/Linux
xterm-256color

It would be awesome to exec the command command to run in simple cases such as `fish -c firefox` instead of forking as it would not leave a shell waiting uselessly for the child.

Some applications always use the current shell to start commands (such as i3).

**Comment by zanchey** [comment]
Can I clarify what you're suggesting here is that for long-running graphical commands such as Firefox, that fish rewrite any invocation to be:
* `exec firefox`, which closes the current shell and replaces it with firefox, though won't close the terminal
* `firefox &`, which starts Firefox in the background.
* `nohup firefox &` or `firefox &; disown`, which starts Firefox in the background and removes it from the job list so that closing the terminal does not close the process

In general I don't think there's any way of detecting which commands you want this done for; it might be better to define an abbreviation (eg `abbr --add firefox 'firefox &'`) so that the invocation is automatically replaced, but I'm keen to hear other perspectives.

**Comment by zanchey** [comment]
Can you make a screencast or something? I don't understand, sorry. i3 runs `execl(SHELL, SHELL, '-c', cmd)`, and I thought fish pretty much did the same things bash did there (but possibly not!)

**Comment by zanchey** [comment]
Oh, wait, I think I understand: `fish -c "sleep 100"` has both the fish and sleep processes running, while `bash -c "sleep 100"` execs sleep.

I wonder if this is specified anywhere.

**Comment by faho** [comment]
To be honest I'm not enthused about this. The optimization is barely existent - it's one process that literally does nothing but wait. You couldn't skip the initialization (the thing you want to execute could be a function) or anything, it's really just a bit of memory and a PID.

And in turn it's complicating our code and the mental model.

**Comment by jruere** [comment]
Bear in mind that it's not one process, it's one per application running.

Feel free to close this. Simplicity is important.

**Comment by ridiculousfish** [comment]
It's a reasonable request but I think it would be too complex. Note that you can use `exec` manually: `fish -c 'exec firefox'` and this works. Thanks for filing!
