### ISSUE TITLE
pgrep and pkill completions produce an error with busybox ps

### ISSUE THREAD

**Issue by onodera-punpun** [fish-shell/fish-shell#6918]
```fish
~ fish --version
fish, version 3.1.0
~ echo $version
3.1.0
~ uname -a
Linux punpun 5.5.13-zen2-punpun #1 ZEN SMP PREEMPT Sun Apr 5 20:55:32 UTC
2020 x86_64 GNU/Linux
~ echo $TERM
st-256color
```

error:

```
~ pkill ps: unrecognized option: x
BusyBox v1.31.1 (2020-04-18 19:11:24 CEST) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER] [-T]

Show list of processes

    -o COL1,COL2=HEADER Select columns for display
    -T          Show threads
```

**Comment by zanchey** [comment]
This fix doesn't work, at least on my system with busybox; `ps -o comm` is still an error.

**Comment by krobelus** [comment]
That's really strange, it works on Ubuntu with busybox 1.27.2.
It's in busybox [here](https://git.busybox.net/busybox/tree/procps/ps.c?h=1_31_stable#n379), the standard they reference says that `comm` is "recognized in the POSIX locale"

I get:
```
$ busybox ps asdf
ps: bad -o argument 'asdf', supported arguments: user,group,comm,args,pid,ppid,pgid,etime,nice,rgroup,ruser,time,tty,vsz,sid,stat,rss
```

Maybe it is because `ps` is a function? But that can't be since I'm using `command ps`..

**Comment by zanchey** [comment]
Hm, I'm on OpenWRT with Busybox 1.30.1, which might be further trimmed down.

**Comment by zanchey** [comment]
That might be as good as it gets for now, unfortunately.
