### ISSUE TITLE
Provide index of  token under cursor (commandline)

### ISSUE THREAD

**Issue by ypnos** [fish-shell/fish-shell#6922]
Looking at [bash completion support](https://devmanual.gentoo.org/tasks-reference/completion/index.html), there is variable `COMP_CWORD` available:

> An index into `${COMP_WORDS}` of the word containing the current cursor position.

An equivalent seems to be missing in fish. There is `commandline --cursor`, and `commandline --current-token`, but they both don't provide the index of the token.

I am facing this obstacle when porting a custom completion script over to fish.
Is  there a way to get the index in `commandline --tokenize` corresponding to the cursor position?

**Comment by faho** [comment]
Let me do you one better: https://github.com/fish-shell/fish-shell/blob/2421eb618074442d02800e7ff1e811fddef87d30/share/completions/npm.fish#L56

**Comment by ypnos** [comment]
So you are saying the cursor is always under the last token or after the last token (line 61 in your script)?

**Comment by faho** [comment]
Uuuummm... no, that's a bug.

That should actually be `commandline -opc`, ie. `commandline --tokenize --current-process --cut-at-cursor`.

As it currently stands, it will break when either the cursor has been moved back (i.e. there are things *after* the cursor, which should not be influencing the completion) or when there are other things in the commandline (e.g. if it's a pipeline). Those two things are solved by `--cut-at-cursor` and `--current-process` respectively.

**Comment by ypnos** [comment]
If I understand correctly, you are working around the problem by just showing the 'relevant' part left of the cursor to npm. So in almost all cases this will do the job, because there are seldom cases where the right-hand side of the cursor would be evaluated to determine possible completions.

Another workaround could be to use `count (commandline --tokenize --cut-at-cursor))` to determine `COM_CWORD`. In this case we can pass on the full information (full command line and token under cursor).

Right?

**Comment by faho** [comment]
>If I understand correctly, you are working around the problem by just showing the 'relevant' part left of the cursor to npm. So in almost all cases this will do the job, because there are seldom cases where the right-hand side of the cursor would be evaluated to determine possible completions.

Evaluating the right-hand side for completions is an entirely different decision, and we don't do it. Personally, I consider it wrong. If you go back to earlier in the commandline, you can change things, so you should get completions like you would get had you not written the bits after.

>Another workaround could be to use count (commandline --tokenize --cut-at-cursor)) to determine COM_CWORD. In this case we can pass on the full information (full command line and token under cursor).

Yes.

----

It would be nice to know what exactly you want to know this for. I don't consider the bash environment variables to be a particular good interface (the only reason we've bothered at all with that translation is because npm expects it, so we can piggy back on its completion interface - a hand-written fish completion would be much better - at the very least it could offer descriptions).

I also can't recommend looking at everything in fish from a rosetta stone angle.

>Btw from my experience with fish 3.1.0 it appears that --tokenize and --current-process do not go together (the latter has no effect on the output of the former).

You're probably misunderstanding what --current-process does.

Imagine a commandline like

```fish
echo $flounder >&2 | less; and echo $catfish
```

If you don't use --current-process, commandline --tokenize will show the entire thing. If you do, it will only show the "process" the cursor is over - the "echo $flounder", "less" or "and echo $catfish".

If this didn't work, a large number of our completions would be broken, so I highly doubt that's the case (and I also can't reproduce it)

**Comment by ypnos** [comment]
Thank you for explaining --current-process. My intention is not to work with the bash variables, I just used them as an easy reference to clarify my question.

In case you are interested, this is the completions I am working on and I will soon incorporate what I learned here: https://github.com/herbstluftwm/herbstluftwm/blob/master/share/herbstclient.fish

**Comment by ypnos** [comment]
@faho You might need to revisit your use of `commandline -opc`. It seems to omit the token currently under the cursor.

**Comment by krobelus** [comment]
> `commandline -opc` seems to omit the token currently under the cursor.

That's intentional, most completions are supposed to compute choices for that token without looking at it. If you also need the token under the cursor use `commandline --current-token` which will be the empty string if the cursor is inside whitespace.
