### ISSUE TITLE
Desiderata for terminal emulator capability reporting

### ISSUE THREAD

**Issue by gnachman** [fish-shell/fish-shell#6984]
This is perhaps an abuse of issues; please feel free to redirect me if I shouldn't be asking this here.

Some terminal emulator authors (VTE, xterm, tmux, mintty, libvterm, iTerm2, and others) are discussing building a new mechanism for reporting capabilities. For context: mintty/mintty#881

My goal is to collect desires from developers of popular applications. What capabilities do you wish you could discover about terminals that you don't already get from terminfo?

For example, being able to detect 24-bit color support, available cursor styles, bracketed paste support, and mouse reporting modes are the kinds of capabilities that would be included. They would likely be exposed through a combination of a new environment variable and a to-be-determined control sequence that reports them.

The results of this survey are being collected here: https://docs.google.com/spreadsheets/d/1H4OK8z98ptySnAPjlej56lrL6b0S1j6okwp7KLRTDBQ/edit#gid=0

Thanks in advance for your time!

**Comment by ammgws** [comment]
I can't see the file atm but background colour is one that seems to come up now and then

**Comment by gnachman** [comment]
This value would be available via an environment variable and a control sequence that reports back the capabilities. It seems to me that `COLORFGBG` and `OSC 11 ; ? ST` are meant to do the same, although `COLORFGBG` is not particularly precise.

**Comment by zanchey** [comment]
That's a heck of a thread! I'm glad you've settled on feature detection, I think we learned from the Web that user agent sniffing is not sustainable.

**Comment by zanchey** [comment]
I had a look through the fish source, and you've already got the things we try and do sniffing/whitelisting for:

- cursor styles
- 256-bit colour
- 24-bit colour
- UTF-8 support
- Ambiguous width characters
- Unicode version
- Title setting
- Bracketed paste
- OSC 7
- Focus reporting

**Comment by textshell** [comment]
Thanks for looking up what fish currently uses. 

I'm curious what decisions fish bases on the availability of focus reporting?

What definition of utf-8 support does fish use? It that detection based on termios IUTF8 or on something different?

How fine grained is fish's unicode version understanding?

The rest seems fairly clear.

**Comment by faho** [comment]
>I'm curious what decisions fish bases on the availability of focus reporting?

Super cheesy: If $TMUX is set.

>What definition of utf-8 support does fish use? It that detection based on termios IUTF8 or on something different?

The sniffing we do is to run `unicode_start` if $TERM = linux. Otherwise we purely go via locale.

>How fine grained is fish's unicode version understanding?

If wcwidth says U+1f603 is 2 wide it's unicode >= 9, if it's 1 it's <= 9. We don't care about anything more at the moment.

(Yes, we use wcwidth a bunch which we kinda need to get away from because it's not sufficient)

**Comment by textshell** [comment]
Thanks for the answers.

> > I'm curious what decisions fish bases on the availability of focus reporting?
> 
> Super cheesy: If $TMUX is set.

We i'm curious about is if there are any changes in fish's behavior based on the expectation that focus reporting is supported/not supported. I mean other than settings the mode. From what i can see it's not¹. So i'm curious why it's not just always used?

¹ https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_config_interactive.fish#L241 seems to be where this detected.

> 
> > What definition of utf-8 support does fish use? It that detection based on termios IUTF8 or on something different?
> 
> The sniffing we do is to run `unicode_start` if $TERM = linux. Otherwise we purely go via locale.

I think calling `unicode_start` is quite specific (i'd say it's a linux init system bug workaround). Apart from that, are you unhappy with the reliability of the locale based detection of utf8 mode?

> 
> > How fine grained is fish's unicode version understanding?
> 
> If wcwidth says U+1f603 is 2 wide it's unicode >= 9, if it's 1 it's <= 9. We don't care about anything more at the moment.
> 
> (Yes, we use wcwidth a bunch which we kinda need to get away from because it's not sufficient)

I've looked and fish basically has it's own wcwidth implementation that is parameterized on:
* east-asian ambiguous width
* unicode >= 9 flag, either sniffed (terminal env vars) or from system system wcwidth.

So maybe something simple will do here before a more complete solution can be devised.

Do you know of any other terminal interactions you would like to use in fish that are supported by some terminals, but are not feasible because reliable detection is not possible?

**Comment by faho** [comment]
>So i'm curious why it's not just always used?

It's not always turned on because we can't be sure the terminal handles the sequence sensibly - meaning either turning on focus reporting or swallowing the sequence.

I'm pretty sure we've had things like that happen with one of the emacs terminals.

For bracketed paste we ended up enabling it everywhere because I could not find a single case of it not being supported.

>Apart from that, are you unhappy with the reliability of the locale based detection of utf8 mode?

Sometimes system misconfiguration happens and the locale ends up as C, that's about it. I'd love for posix to finally include C.UTF-8, but I'm not holding my breath (it's been held up in glibc for years now).

>Do you know of any other terminal interactions you would like to use in fish that are supported by some terminals, but are not feasible because reliable detection is not possible?

We've listed the worst offenders - cursor shape and truecolor. Getting that to an acceptable level took some doing.

It's probably worth noting that for cursor shape in particular we don't really care if the terminal ends up switching. If it swallowed the sequence that would also be okay.

So if y'all end up making a modern terminal standard, if that could just require that so our check could be simplified to `if set -q MODERN_TERM` that would be swell.

Then there's also the problem of the term-in-a-term. If you launch konsole, start tmux and in that launch gnome-terminal, we have no way of figuring out which terminal we end up in. We see $TMUX, $KONSOLE_VERSION and $VTE_VERSION, but have no idea which terminal is the inner one.

**Comment by gnachman** [comment]
> Then there's also the problem of the term-in-a-term. If you launch konsole, start tmux and in that launch gnome-terminal, we have no way of figuring out which terminal we end up in. We see $TMUX, $KONSOLE_VERSION and $VTE_VERSION, but have no idea which terminal is the inner one.

My hope is that we can make this good enough that you don't care. Instead, you should tailor the way you use particular control sequences for the reported capabilities. It would be good to know how fish modifies its behavior when it knows it's in a terminal multiplexer. Are there control sequences you wrap with DCS? Do you change how you use DECSCUSR? Do you do something fancy for italics and inverse text? Anything else?

**Comment by faho** [comment]
>Are there control sequences you wrap with DCS?

For those who'd have to look it up (like, say, me): "Device Control String (DCS  is 0x90)". It's ESC P.

>Do you change how you use DECSCUSR?

Indeed, we wrap it, but it's the only thing we do that for.

https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_vi_cursor.fish#L85-L89

>Do you do something fancy for italics and inverse text?

Only thing we do is also enable italics/dim for a broken macos xterm-256color entry. Otherwise just send sitm/ritm and friends.

>Instead, you should tailor the way you use particular control sequences for the reported capabilities. 

If at all possible for many things I would like to not even care about the capabilities. For things like DECSCUSR, OSC7, focus reporting, bracketed paste, I just want to fire and forget. If the terminal decides to ignore it, then that's up to it.

If not, checking the capabilities is okay, but still more complicated than it needs to be from our side.

**Comment by gnachman** [comment]
> Only thing we do is also enable italics/dim for a broken macos xterm-256color entry. Otherwise just send sitm/ritm and friends.

I had a quick look through macos terminfo entries and it looks nothing people use these days has SGR 2 for `enter_dim_mode`.

> If at all possible for many things I would like to not even care about the capabilities. For things like DECSCUSR, OSC7, focus reporting, bracketed paste, I just want to fire and forget. If the terminal decides to ignore it, then that's up to it.

Some broken terminals will print part of DECSCUSR (though I don't know which ones: this is hearsay). The goal is to layer this on top of terminfo to account for the things it does poorly or not at all. You can get away with fire and forget, for the most part. Eventually someone will complain that their janky terminal does the wrong thing, and then you may want to check for that capability.

Thanks for your feedback. I've incorporated it into my spreadsheet.

**Comment by zanchey** [comment]
I'll close this for now then! Thanks for the request!
