### ISSUE TITLE
fg resets terminal modes

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7010]
Since 29754f354, which closed #2315, we keep the terminal modes for external commands.

This generally works, but `fg` specifically resets them.

To reproduce:

```fish
$ stty susp \cg
$ cat
# press ctrl-g to background cat
$ stty -a # shows susp = ^G
$ fg
# press ctrl-g to background cat
$ stty -a # shows susp = ^Z
$ fg
# press ctrl-g, nothing happens
```

I think this is because we specifically re-re-set the terminal modes in https://github.com/fish-shell/fish-shell/blob/9be510fa6bb79730bfdb0ae3c1a416cd69858708/src/proc.cpp#L870-L875, which fg sets when the job is stopped: https://github.com/fish-shell/fish-shell/blob/9be510fa6bb79730bfdb0ae3c1a416cd69858708/src/builtin_fg.cpp#L109.

I am not entirely sure why that is or if that is still necessary. To me it seems like the modes should be set before we run a command, so setting them again should be useless at best.

**Comment by ridiculousfish** [comment]
Thanks for capturing this. The idea here is that, if a job stops, we save the tty's modes as part of the job, in case the job modified its own modes. When the job resumes, we restore its modes at that point.

**Comment by faho** [comment]
And that sounds entirely acceptable.

I now see I've misdiagnosed the problem. I assumed we restored the default modes instead of the job's modes *for that job*, but that's not what we're doing. We are, at some point (when executing a builtin?), overriding our modes for external commands with the defaults again, and that's causing issues with a _second_ job.

I.e.

```fish
> stty susp \cg # set suspend key to control-g
> cat
# press control-g
Job 1, 'cat' has stopped
> stty -a # will tell you susp is "^Z" again
> fg
# restores the old modes, so susp is ^G
> cat
# restores the normal modes again
# press control-g, nothing happens
```

**Comment by mqudsi** [comment]
>  We are, at some point (when executing a builtin?)

It's actually when we are restoring control of the terminal after bringing a previously background job to the foreground. We go out of our way to restore the terminal flags, because the normal flag restore routines are circumvented when calling `fg` and then waiting to regain control of the tty.

This was required because we were previously taking an all-or-nothing approach to tty modes/flags and needed to make sure an external command, once `fg`'d, would not render the tty unusable for the shell. See the following:

https://github.com/fish-shell/fish-shell/blob/0414be75cc15dd06e9ef6de59215d60018d4ad4c/src/proc.cpp#L973-L982

The restoration of term modes was drafted by @bruce-hill and adapted/committed as 9fd9f70346587331e40159aaa1d808bf1eb6e2b9 to deal with a back-and-forth of #121 returning as a regression as discussed in #2114.

We now explicitly prevent certain changes from propagating to future external processes, but that would need to be rechecked in `continue_job`.

All the code that sets or restores the terminal flags desperately needs to be unified. This issue is the problem I was running into and attempting to describe in the comments on 29754f35402fb247cc9e390c95315259fe859847: the shell's own tty flag/states was leaking into the state used for external processes. Your changes to separate and persist (some) flags for external commands were bypassed by `fg`, which was causing our internal tty settings to be applied to subsequent commands after `fg` (as I was trying to explain, it was fish that was corrupting the tty flags for future applications and not any of the applications I'd actually run in the repro steps). 

We need to clean up the code to clearly delineate between shell tty flags and external command tty flags, and take care not to confuse the two (my rust experience now makes me want to reach for the type system here and use two different types that cannot be assigned to one another to store the two different sets of flags/attributes).

**Comment by faho** [comment]
Okay, I can no longer reproduce this with 018f1f7e2
