### ISSUE TITLE
Default Fish welcome message is not designed for discorveablity

### ISSUE THREAD

**Issue by psychoslave** [fish-shell/fish-shell#7016]
Hello, thanks for all the Fish!

I'm a new user of Fish, and was attracted by its user friendly philosophy.
 
As of Fish, version 3.0.2 bundled in Fedora 31, the default configuration won't provide much relevant information when it stast, in my case:
>Bienvenue dans fish, le shell amical et interactif

Of course it's in French here, but I didn't yet figured out how to inform Fish to use `LANG=C`. I tried `set -x LANG C; fish` but it didn't do the trick.

I think a default welcome like the following would be more informative:
```
Welcome in Fish, the friendly interactive shell
This is version 3.0.2 running in Fedora 31 on localhost
Type `help` for an introduction
Type `fish_tutorial` for an interactive tour
Use `set fish_greeting 'Custom message'` in ~/.config/fish/config.fish to alter this welcome message.
```

Of course there is currently no `fish_tutorial`, but you got the point.

What is your opinion on that?

**Comment by krobelus** [comment]
Does it really just print one line for you? That would be s a bug.
By default it should currently show:

```
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
```

I think this is enough, because by typing "help", the user can discover everything else.

>  I tried set -x LANG C; fish but it didn't do the trick.

That should definitely work, unless you are executing this from another shell, like bash where `set` does something different. Try `env LANG=C fish`. Then inside fish `echo $LANG` should print `C`.

**Comment by faho** [comment]
>Does it really just print one line for you? That would be s a bug.

Yeah, we only add the second line conditonally:

```fish
        if test $__fish_initialized -lt 2300
            set line2 \n(_ 'Type `help` for instructions on how to use fish')
        end
```

This was probably meant to *add* it when upgrading, but the way it turns out is that it might miss some cases instead.

I agree that we don't want to add all sorts of crap to the message. It should tell you enough to get started, and the minimum is how to get help. Especially how to get rid of it should *not* be in the message because that just makes it sound like you have to get rid of the message. It makes it look worse.

The "tour" doesn't exist right now and the versions aren't super important (if you want use something like `neofetch` as the greeting).

I've fixed the fish_greeting bit, I'm rejecting the rest.
