### ISSUE TITLE
scp user@ip:/dir/string-* doesn't work

### ISSUE THREAD

**Issue by Titaniumtown** [fish-shell/fish-shell#7043]
Fish Version: fish, version 3.1.2
OS: Arch Linux
TERM: alacritty

My issue is that I can't include asterisks in scp paths coming from remote machines, it works in bash, but not in fish. For now I have to run all my scp w/ asterisk related stuff under bash.

**Comment by faho** [comment]
Quote the asterisk.

The issue here is that bash *tries* to match a file, can't, so it passes along the literal asterisk. That's an awful way to handle things and means you get stuff like

```bash

   for f in ./*.mpg; do
       # Okay, so we ran the glob, however we still need to make sure it exists,
       # because it could have not matched and stayed literally.
       # Or there actually is a file called "*.mpg" in the current directory - UNIX allows it!
       test -f "$f" || continue
       mympgviewer "$f"
   done
```

fish doesn't do that. It tries to match files, sees that there are none and aborts.

If you want to pass a literal asterisk, quote it:

```fish
scp "user@ip:/dir/string-*"
# or
scp user@ip:/dir/"string-*"
# or
scp user@ip:/dir/string-"*"
# or
scp user@ip:/dir/string-\*
```

**Comment by zanchey** [comment]
It's time for this to go in the FAQ.

**Comment by Titaniumtown** [comment]
Thx @faho for the info!

**Comment by faho** [comment]
Yeah, added to the FAQ.
