### ISSUE TITLE
alias in fish script not working

### ISSUE THREAD

**Issue by jessehui** [fish-shell/fish-shell#7069]
Hi,
I can't set alias in fish script. Please see output:
```shell
# cat test.sh
alias rmi='rm -i'
alias ltest='ls -a'
rmi core.*
ltest .

# fish test.sh 2>&1
test.sh (line 2):
alias rmi='rm -i'
^
test.sh (line 3):
alias ltest='ls -a'
^
test.sh (line 4):
rmi core.*
^
test.sh (line 5):
ltest .
^
```
Did I have anything wrong?

`fish, version 3.1.2`
`kernel: 4.9`

**Comment by faho** [comment]
Works for me.

Note that `alias` is just a function that defines functions, so this is probably your fish not finding alias.fish.

I suggest checking your configuration for anything that messes with $fish_function_path.

In particular it would be quite helpful if you tried this *without* any customization like the issue template tells you to:

> Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:
>
>     sh -c 'env HOME=$(mktemp -d) fish'

**Comment by faho** [comment]
Also, as a general thing, the kernel version is entirely useless in most cases. What we'd want is your *distribution* and the version of that, because we are interested in the *configuration* and things like the libc it uses. The kernel is an implementation detail. "Ubuntu 20.04" is helpful, "kernel 5.2" is not.

This isn't specific to fish but goes for most places where you talk about "linux" (or GNU/Linux or whatever you want to call it)

**Comment by ridiculousfish** [comment]
As faho says, please try with HOME set to a temporary directory, to rule issues related to your config.

**Comment by jessehui** [comment]
Thank you @faho and @ridiculousfish . I will take a try !

**Comment by faho** [comment]
Closing for lack of response.
