### ISSUE TITLE
__fish_complete_suffix unable to complete path starting with tilde

### ISSUE THREAD

**Issue by emorozov** [fish-shell/fish-shell#7070]
```
fish, version 3.1.2
 ~ echo $version
3.1.2
```

I'm often using commands like `unzip ~/Downloads/archive.zip` but fish makes this very cumbersome experience because `__fish_complete_suffix` can expand filenames and paths but it fails to expand a path starting with tilde.

To reproduce, try typing:
`unzip ~/Dow[TAB]` (use any subdirectory from your home directory)
Expected result: fish completes name of the existing directory (`~/Downloads`)
Actual result: nothing happens, you have to type the full path manually without any completion whatsoever.

It looks like a bug to me.

**Comment by faho** [comment]
1. `unzip` no longer uses complete_suffix (and tbh it's useless in most cases)
2. Yeah, it should, but this requires something like an `expand` builtin to do these, because it's not just tildes, it's variables and globs as well. Once that's in, adding this is trivial and the obvious next step.

So I'm closing this in favor of #5811
