### ISSUE TITLE
First call to `read` always results in a welcome message even when executed from a script

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#7080]
I'm pretty sure this is a regression, since I noticed it in the middle of one of my pipelines written in fish script:

```fish
#!/usr/local/bin/fish

read foo -l
echo $foo
```

I believe this used to just spit back whatever word was entered, but now it first prints the greeter then executes the `read`:

![image](https://user-images.githubusercontent.com/606923/83712718-fbe1d380-a5eb-11ea-8c6d-052726f12349.png)

(I use shebangs when using fish to replace existing python/bash scripts to create self-contained, single-file "executables" that don't depend on outside state.)

If it is indeed a regression, it's either in the logic that prints the prompt at startup or the logic that determines if the new fish instance is interactive or not. I'm hoping the former.

**Comment by faho** [comment]
So the greeting (and this does call the `fish_greeting` function, I have a custom one) via `__fish_config_interactive`, which is triggered by the first fish_prompt event (via share/config.fish).

The culprit here is likely 1b0ec2177305ed15c5a6630a0a3068dcbc64835f, which undid b77e2a67f8c3a2faf32c04926aaaea7572abcbba, which added an explicit "is-interactive" check that I didn't get.

It appears that "interactive" has multiple meanings here.

Yeah, reverting.

**Comment by mqudsi** [comment]
Thanks, @faho.
