### ISSUE TITLE
Use `-` as `cd -`

### ISSUE THREAD

**Issue by hauleth** [fish-shell/fish-shell#709]
Changing folder using only it's name works, and it's great. But why not work like ZSH and use also `-` to return to last visited folder?

**Comment by Siecje** [comment]
```cd -``` works on fish 2.2.0

**Comment by floam** [comment]
`-` does not work as `cd -`

**Comment by krader1961** [comment]
> - does not work as cd -

@floam, why did you reopen this three year old issue? The consensus seemed to be that fish shouldn't automatically make `-` an alias for `cd -`. Anyone who wants that can run `abbr --add -- - cd -`.

**Comment by floam** [comment]
Where can I read about not wanting `-` as a `cd -` alias? All I see here is some resistance to the basic concept of "cd -".

**Comment by krader1961** [comment]
> Where can I read about anyone not wanting - as a cd - alias?

Yeah, you're probably right. The wording of some of the comments is ambiguous. But that makes your reopening this even stranger since `cd -` works now and supposedly worked as of 2.2.0. So I'm still perplexed why you reopened this issue.

**Comment by floam** [comment]
the substance of (my reading of) this issue: "Use `-` as `cd -`"

As in, implicitly typing `-` should do the same thing as typing `cd -` - just like `~` or `..`. We have `cd -` but it is not treated consistently like the other path aliases or whatever they are called.

**Comment by floam** [comment]
(It could well be this is best wontfix'd -- I haven't thought too hard about it yet -- but the issue should reflect reality/developers will :smile:)

**Comment by faho** [comment]
>(It could well be this is best wontfix'd -- I haven't thought too hard about it yet -- but the issue should reflect reality/developers will)

I agree. Though personally, I don't have any strong feelings either way. 

I don't know of a command `-` so it wouldn't clash with that - and naming a command so is also a bad idea.

But I think it's kind of expected that "-" is a special argument, and the code would either have weird layering (since c++ would have to call the `cd` _function_) or more complicated (since the cd function would have to be moved to c++).

I'm not using it, but then I'm not using implicit-cd anyway. My thought processes just go "I want to change directory" and my hands have already typed `cd`.

**Comment by floam** [comment]
I think the way it would need to work would be that - is a legit path component when an argument to our cd, no? Then the `-<enter> behavior would just happen with the existing mechanics. That would mean: `cd /usr/local/bin; cd /tmp/; ls -/fish` would be `ls /usr/local/bin/fish`. What would this break?

**Comment by ridiculousfish** [comment]
There's some discussion in #22 (!) regarding the cd behavior. Where we landed is that implicit cd paths must start with a dot, slash, or tilde. `-` would then not be an implicit cd path per these rules.

**Comment by krader1961** [comment]
We absolutely should not make `-` be a "legit path component" ala `cd -/../share`.

Anyone wanting `-[enter]` to be equivalent to `cd -` can do this trivially: `abbr -- - 'cd -'`. It might be reasonable to make that a default abbreviation that is created by the first interactive fish shell. If no one has a problem with doing so I'm happy to implement that. Otherwise this should be closed "will-not-fix".

**Comment by ridiculousfish** [comment]
Nice find that `abbr -- - 'cd -'` works! I think that's sufficient, and so we don't need to mess with `cd`. I'll close.
