### ISSUE TITLE
Fish shell is not working on VS Code.

### ISSUE THREAD

**Issue by rasitiri** [fish-shell/fish-shell#7097]
Fish shell is working correctly on my computer. But it is not working on vscode. And it gives an error like this:

> Failed to execute process '/usr/bin/uname'. Reason:
> The total size of the argument and environment lists 48MB exceeds the operating system limit of 2MB.
> Try running the command again with fewer arguments.
> Failed to execute process '/usr/bin/basename'. Reason:
> The total size of the argument and environment lists 48MB exceeds the operating system limit of 2MB.
> Try running the command again with fewer arguments.
> Failed to execute process '/usr/bin/git'. Reason:
> The total size of the argument and environment lists 48MB exceeds the operating system limit of 2MB.
> Try running the command again with fewer arguments.

```
fish, version 3.1.2
Linux asusx556 4.15.0-30deepin-generic #31 SMP Fri Nov 30 04:29:02 UTC 2018 x86_64 GNU/Linux
xterm-256color
```

**Comment by faho** [comment]
Taking a guess here: Most likely your environment variables are too large.

You probably have something like the following in config.fish:

```fish
set -U fish_user_paths $fish_user_paths /something/else
```

Universal variables are stored on disk, and adding to them like that means they *grow* whenever you launch fish (every time).

Environment variables count towards a processes argument list for the purposes of the OS's limit, so fish can no longer execute an external command.

Run `set -e fish_user_paths` (or whatever variable) and remove that line from your config. Instead just execute it once interactively.

**Comment by rasitiri** [comment]
> Taking a guess here: Most likely your environment variables are too large.
> 
> You probably have something like the following in config.fish:
> 
> ```fish
> set -U fish_user_paths $fish_user_paths /something/else
> ```
> 
> Universal variables are stored on disk, and adding to them like that means they _grow_ whenever you launch fish (every time).
> 
> Environment variables count towards a processes argument list for the purposes of the OS's limit (see e.g https://www.in-ulm.de/~mascheck/various/argmax/), so fish can no longer execute an external command if the environment gets too large.
> 
> Run `set -e fish_user_paths` (or whatever variable) and remove that line from your config. Instead just execute it once interactively.

I get the point. You're right that my fish config file contains variables. Is there a way to set variables permanently?

**Comment by faho** [comment]
>Is there a way to set variables permanently?

Variables set with `-U` *are permanent*. That's what the `-U` (short for `--universal`) *is*.

Like I said:

>Instead just execute it once interactively.

Just run `set -U fish_user_paths /whatever/paths/you /want/here` interactively, *or* run `set PATH $PATH /whatever/path/you/want` in config.fish.

Do *not* run anything that *adds* to a universal variable (one defined with `set -U`) in config.fish, because that will cause it to grow every time you start fish. You can technically run e.g.

```fish
set -U fish_user_paths ~/.local/bin
```

in config.fish, because that doesn't use the previous value. (or you could *check* if a thing is in the variable and only add it if it isn't)

The next fish release will have a `fish_add_path` command that does the right thing wherever you use it.
