### ISSUE TITLE
can't append directory with space to $PATH

### ISSUE THREAD

**Issue by skivvies** [fish-shell/fish-shell#712]
If I `set PATH $PATH /Applications/install4j\ 5/bin` the following message is output at other times while I'm using fish:

set: Warning: path component /Applications/install4j may not be valid in PATH.
set: No such file or directory
set: Warning: path component 5/bin may not be valid in PATH.
set: No such file or directory

**Comment by faho** [comment]
Nobody can reproduce this, let's assume it's fixed.

**Comment by floam** [comment]
What he did was something I've done, thinking the PATH magic was two way:

`set PATH /usr/bin:/bin`

You must use spaces while using `set` even on PATH.

**Comment by nhumrich** [comment]
I have this same issue

**Comment by krader1961** [comment]
@nhumrich, I don't understand the point of your comment that

> I have this same issue

What does `echo $FISH_VERSION` output? What command(s) did you run that produced the error? Is this something you think fish can handle better to avoid an error? If so can you explain what you expected fish to do?

**Comment by krader1961** [comment]
@nhumrich, Unless you're seeing the same errors as in the original comment (ignoring the portions that are obviously unique to the person reporting the problem) I would recommend opening a new issue and possibly referencing this issue.

**Comment by nhumrich** [comment]
I did pretty much have the exact same issue as the OP
```
set: Warning: path component /home/nhumrich/.bin may not be valid in PATH.
set: No such file or directory
```
I fixed it once i realized `~/.bin` did not exist on my system anymore. But because I assumed it did, I didnt understand the error.
I thought these where two different warnings. It would have helped a lot if is was one warning, such as 
```
set: Warning: path component /home/nhumrich/.bin may not be valid in PATH.
  reason: No such file or directory (/home/nhumrich/.bin)
```
I honestly had no idea what the issue was at first, it was not obvious that the `no such file or directory` was referring to the line above.
