### ISSUE TITLE
Stash state not shown with informative git prompt

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7136]
fish, version 3.1.2
Linux archlabs 5.7.2-arch1-1 GNU/Linux

Run on clean fish:

```shell
ilan@archlabs ~> cd src/
ilan@archlabs ~/src (master)> git stash list
stash@{0}: WIP on master: b91c01e Initial commit
ilan@archlabs ~/src (master)> set -U __fish_git_prompt_showstashstate true
ilan@archlabs ~/src (master $)> #Shows stash state :)
ilan@archlabs ~/src (master $)> set -U __fish_git_prompt_show_informative_status true
ilan@archlabs ~/src (master|)> #Doesn't show stash state :(
ilan@archlabs ~/src (master|)> set -e __fish_git_prompt_showstashstate
ilan@archlabs ~/src (master|✔)> 
```

Reproduction is simple, just enter a git repository with stashed changes while __fish_git_prompt_showstashstate and __fish_git_prompt_show_informative_status are both set.

**Comment by faho** [comment]
Yeah, this tried to be too clever.

Note that you very likely don't want the informative prompt - it's quite wasteful because it counts everything (including untracked and modified files, which can be super costly!).

If it's just because of the nicer *symbols*, use $__fish_git_prompt_use_informative_chars instead - I have been unable to convince people to make that the default, so we're stuck with remembering what on earth `*` was again.
