### ISSUE TITLE
(function) complete command not file 

### ISSUE THREAD

**Issue by tamis-laan** [fish-shell/fish-shell#7141]
Hey I have wrote this fish function in my config to do window swallowing:
```
# Window swallowing
function swallow 
  set id (xdo id)
  xdo hide 
  $argv
  xdo show "$id"
end
```
However when I use it in my terminal fish it's completion system completes files not commands. Is there some way to set the completion behavior for this function?

**Comment by faho** [comment]
What you want is to use `complete` to define how this function completes.

The default is, indeed, to offer files.

There's no direct thing to offer "commands" (really you want to complete this thing as if it didn't exist), but it's simple enough to use `complete -C` to complete "like something else":

```fish
complete -c swallow -f -a '(set -l cmd (commandline -opc; commandline -ct); complete -C"$cmd[2..-1]")'
```

The "-f" tells it to supress the default file completion, and "-a" takes a script that generates completion options. In this case we get the current commandline and pass all but the first token (because that is `swallow`) to `complete -C`, to complete "like" that.

So if you did `swallow git <TAB>`, it would complete like "git ".

Put that into a file called "swallow.fish" in $fish_complete_path or into config.fish.

**Comment by tamis-laan** [comment]
Works like a charm! thanks faho!
