### ISSUE TITLE
Lisp-like math operators (+ (\* 2 2) 3 4)

### ISSUE THREAD

**Issue by cben** [fish-shell/fish-shell#716]
Since fish command substitution looks like lisp code, it'd be neat to make math easier to use with a series of functions.  Instead oh having to (math 3 + 4 + 5) we'd be able to just (+ 3 4 5).

Problems:

*, <, > require escaping, but that's also true with 'math'.

/ chdirs to the root dir, even if followed by arguments - they're silently ignored.  Arguably that's a bug.

**Comment by Undeterminant** [comment]
I don't see any problem with using symbols, and having a `-` alias doesn't seem more worth it when `cd -` is already easy to type.

**Comment by bucaran** [comment]
Just for fun. `Alt+/` gets me a ÷ on my Mac. 

```fish
function ÷
   if [ $argv[2] -eq 0 ]
       echo Infinity
   else
       echo "$argv[1]/$argv[2]" | bc -l
   end
end
```fish

**Comment by Undeterminant** [comment]
@bucaran: Right now, it `cd`s to the root directory, because any command with a slash at the end is interpreted as a `cd`.

**Comment by bucaran** [comment]
@Undeterminant Mmm, I see. That explains everything :+1:

**Comment by Undeterminant** [comment]
Bumping this because I think that it'd be pretty awesome if we could implement these as builtins. I'd be willing to offer code for it if it seems like a worthwhile change.

**Comment by alphapapa** [comment]
I've been using these for a while:
```fish
function mathOp
	set op $argv[1]
	set -e argv[1]
	set expr $argv[1]
	set -e argv[1]	
	for arg in $argv
		set expr $expr $op $arg
	end
	math $expr
end
function +
	mathOp + $argv
end
function multiply
	mathOp '*' $argv
end
function \*
	mathOp '*' $argv
end
```
So you can do:
```fish
➤ + 2 2
4
➤ echo (\* 2 (+ 2 2))
8
```
I don't know if using `/` as a command would be a good idea, though, even if it were possible... :)

**Comment by Undeterminant** [comment]
That's awesome! I'd use `x` instead of `multiply`, and just `div` for division. Although I really like those and thing we should add something like that to upstream.

**Comment by krader1961** [comment]
I agree with @xfix when they say

> Feels too clever in my opinion. It's fish, not Lisp. Perhaps it would work, but without symbols.

The problem with using names like `add` and `mul` is that doing so creates conflicts with any external command with the same name. Yes, that is unlikely. Nonetheless, as has been discussed recently in other issues (e.g., adding a `join` command as a synonym for `string join`) adding new commands should only be done if there isn't another way to solve the problem. And in this case we already have a working solution: the `math` command.

Closing because there is no compelling reason to implement a second way to write math expressions.
