### ISSUE TITLE
After deleting fish_prompt.fish settings fish started lagging

### ISSUE THREAD

**Issue by AlphaKennyBudy** [fish-shell/fish-shell#7160]
fish, version 3.1.0

I am using WSL2 Ubuntu 20.04 LTS.

Yeah, my mistake, I just removed fish_prompt.fish settings without a backup 😅
So, it did change a lot, first of all my omf default theme changed and now it shows machine name instead of a cute fish.
But most important, it started lagging so much on <kbd>TAB</kbd> autosuggestion and fish execution, so I don't know what to do. I didn't configure fish by myself, so I don't remember or even know what settings did it have. Thank you!

Executing `sh -c 'env HOME=$(mktemp -d) fish'` solved the problem a bit, but it still lagging.

**Comment by faho** [comment]
When something about fish is lagging, most of the time it is a massive universal variable.

Please check the output of `set -U` for a variable with a lot of values (e.g. fish_user_paths). Then check config.fish for a place where you do something like

```fish
set fish_user_paths $fish_user_paths /some/path/
```

>Yeah, my mistake, I just removed fish_prompt.fish settings without a backup

Now, it's unlikely that fish_prompt would be doing something like that, but if it did it would be easy enough to just pick a different one. Just start `fish_config` and pick a prompt.

Also 

>fish, version 3.1.0

3.1.0 is quite an awkward version to stop at because 3.1.2 was released with important bug fixes. I recommend upgrading.

**Comment by AlphaKennyBudy** [comment]
I am sorry, I just moved from omf to starship and it did solve a problem. Now it behaves like omf, but it doesn't lag. Also, it may occur because I am using WSL2 with Windows directories (WSL2 works slower than WSL1 with directories on Windows)
> 3.1.0 is quite an awkward version to stop at because 3.1.2 was released with important bug fixes. I recommend upgrading.  

How can I update fish without downloading .tar e t.c. files from /releases?
`sudo apt update && sudo apt upgrade` doesn't help me. `sudo apt install fish` says me that 
> fish is already the newest version (3.1.0-1.2).

**Comment by faho** [comment]
> sudo apt update && sudo apt upgrade doesn't help me. sudo apt install fish says me that

Yeah, Ubuntu is apparently not maintaining the package. Thankfully we have [a PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3) you can add.

Anyway, the question here has been answered, and it's just about OMF being slow.
