### ISSUE TITLE
Bug with case-insensitive autocompletion 

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#7211]
These screenshots explain the issue better than I can articulate it.

Given the following scenario and typing `a_<TAB>` (note: lowercase):

![image](https://user-images.githubusercontent.com/8544900/87883309-5e592c80-c9fe-11ea-8a4f-68d3929ed24c.png)

And then selecting `_C/` from the list:

![image](https://user-images.githubusercontent.com/8544900/87883336-96606f80-c9fe-11ea-955d-65ac688b7a5c.png)

I get an invalid completion. This should have been `A_B_C/`, but the prefix was stripped off, making the autocompletion invalid.

**Comment by krobelus** [comment]
I can't reproduce - does it also happen with `env -i HOME=(mktemp -d) TERM=$TERM fish`?

`complete -C 'cd a_b'` ought to include the prefixes, it prints

```
A_B/
A_B_C/
```

**Comment by zx8** [comment]
Yep, repros without any of my personal configuration also.

Here are the exact steps I took:
```
$ cd (mktemp -d)

$ mkdir A A_B A_B_C

$ cd a<TAB>
A/  A_B/  A_B_C/

# Now *manually* type the underscore and hit <TAB> again
$ cd a_<TAB>
/  _C/
```

**Comment by gokulsoumya** [comment]
I can reproduce this on fish built from 90d8df8 (with setting temporary `$HOME` also) :

| Commandline | Completion Behaviour |
|--|--|
| `cd a`  |  works |
| `cd A`  |  works |
| `cd A_` |  works |
| `cd a_` |  *does not work* (behavior as zx8 mentioned) |
| `cd a_b`|  works |
| `cd A_B`|  works |

IIRC this bug was in before 3.1.2; I noticed it but kept forgetting to open a ticket.

**Comment by krobelus** [comment]
Oh snap, I broke this in `28d67c8f` which is not in any released version yet.

It only happens when there is a common prefix among completions.
Case-correcting completion takes place, which is why the completion replaces the entire token.
This makes it incorrect to strip the common prefix from completions - they would still replace the entire token.

Thanks for the report!

**Comment by zx8** [comment]
Just upgraded to https://github.com/fish-shell/fish-shell/commit/a61e97a8b9056255f302ba2c54a9bb6cdce9838b and I can still reproduce using the same steps @ https://github.com/fish-shell/fish-shell/issues/7211#issuecomment-660710160...

![image](https://user-images.githubusercontent.com/8544900/87886344-03cacb00-ca14-11ea-9829-c9de70aadd08.png)

**Comment by krobelus** [comment]
Right, somehow I didn't realize that the pager was broken as well - should be fixed now.
