### ISSUE TITLE
Autosuggestion is not shown (but completion does work) when line wraps to a newline

### ISSUE THREAD

**Issue by Aster89** [fish-shell/fish-shell#7213]
- fish, version 3.1.2
  - Linux greywarden 5.7.9-arch1-1 #1 SMP PREEMPT Thu, 16 Jul 2020 19:34:49 +0000 x86_64 GNU/Linux
  - rxvt-unicode (urxvt) v9.22 - released: 2016-01-23

To reproduce:

1. Start to write a command, made up of several words, for which the full completion is longer than the width of the terminal;
2. hit <kbd>Alt</kbd><kbd>Right</kbd> repeatedly to complete the entire line;
3. you'll see that the ghost line disappears as soon as the partially completed line wraps at the terminal edge.

(The issue persists with `sh -c 'env HOME=$(mktemp -d) fish'`.)

[![asciicast](https://asciinema.org/a/SeU1HsCNrWZ6ObLkoYPiomiRy.svg)](https://asciinema.org/a/SeU1HsCNrWZ6ObLkoYPiomiRy)

**Comment by ridiculousfish** [comment]
I think this is saying that the autosuggestion disappears if fish chooses to lay out the command line below the prompt. I thought there was a reason for that but this comment suggestions it may not have been on purpose:

```
    // 5. Newline separator (left prompt visible, right prompt hidden, command line visible,
    // autosuggestion visible).
```

maybe we should show the autosuggestion in this case.

**Comment by faho** [comment]
See also #5874.

**Comment by Aster89** [comment]
@faho , shouldn't the present issue be marked as enhancement too? I mean, it may be related to, but it's not the same as #5874.

**Comment by faho** [comment]
@Aster89 It's not clear (well, to me, at least) whether this isn't just a symptom of the same underlying cause as #5874 yet, so it might just be a complete duplicate.

But at the end of the day the bug/enhancement labels don't matter all that much and the precise distinction often isn't easy or helpful. Duplicates are a bit more helpful because they allow us to focus on issues instead of looking at what turns out to be the same thing in multiple places.
