### ISSUE TITLE
File completion for zathura not working if input contains a dot

### ISSUE THREAD

**Issue by antoyo** [fish-shell/fish-shell#7233]
```
$ fish --version
fish, version 3.1.2
$ echo $version
3.1.2
$ uname -a
Linux hostname 5.7.10-arch1-1 #1 SMP PREEMPT Wed, 22 Jul 2020 19:57:42 +0000 x86_64 GNU/Linux
$ echo $TERM
xterm-termite
```

I use ArchLinux and the same issue happens with `sh -c 'env HOME=$(mktemp -d) fish'`.

My problem is that the completions are not shown when my input contains a dot (`.`).

For instance, `zathura billets<TAB>` shows: `billets.pdf`, but `zathura billets.<TAB>` shows nothing.

**Comment by ridiculousfish** [comment]
fish does not provide completions for zathura in its standard install. Do you know where you got the completions from?

**Comment by antoyo** [comment]
I didn't install any completions for zathura. But it seems to have different completions (i.e. it will show `.pdf` files in the completions, but not other files).

How can I know where those completions where installed to?

**Comment by krobelus** [comment]
`grep . $fish_complete_path/zathura.fish` will show all possible completion files.

On Arch the `zathura` package installs it to `/usr/share/fish/completions/zathura.fish`.
Since this is a third party completion, it should rather go into `/usr/share/fish/vendor_completions.d/zathura.fish`.

[The upstream completions](https://git.pwmt.org/pwmt/zathura/-/blob/develop/data/fish-completion.in) contain lines like `__fish_complete_suffix .pdf`, the dot should be dropped to fix this issue. You can report it there.

**Comment by antoyo** [comment]
@krobelus Are you sure about that?

Every completion in the fish repo (for example, [this](https://github.com/fish-shell/fish-shell/blob/6746060c148fe44fa6696b3d91f4726b2858d9de/share/completions/asciidoctor.fish#L3)) contains the dot.

**Comment by krobelus** [comment]
Oh sorry I had misdiagnosed the problem. Should be fixed now.
