### ISSUE TITLE
No completions for fish's own man pages

### ISSUE THREAD

**Issue by dag** [fish-shell/fish-shell#726]
For example `man commandl[tab]`.

**Comment by faho** [comment]
Unfortunately, that doesn't seem to work, at least with archlinux's `man` and `apropos` from [man-db](http://www.nongnu.org/man-db/) - when it comes to _listing_ man pages, whether with `apropos $SEARCHTERM` or `man -k $SEARCHTERM` it seems to ignore the fish man directory completely.

**Comment by faho** [comment]
Okay, I figured this one out - man-db's `apropos` (and `man -k`) _exclusively_ go through the database, and to create that for fish, one needs to add a line defining the directory as man directory _and_ a line defining a cache directory for it to /etc/man_db.conf. Run `mandb` again, and suddenly completion works.

Which sucks, since there doesn't seem to be a way to make it work with from fish alone.

**Comment by krader1961** [comment]
This was fixed by PR #3762 (commit ec1915958).
