### ISSUE TITLE
Concat string and variable without spaces

### ISSUE THREAD

**Issue by robs-nice99** [fish-shell/fish-shell#7287]
fish, version 2.7.1

Ubuntu 18.04.5 LTS

tried fish without third-party customizations: yes

Hello,

This seems like something simple, and I'm probably missing something, but I have looked several times for a clear explanation, without result.

I have a value in a variable:

`set a 19`

And not I want to print "19s", meaning, the variable value followed by some string, with no spaces.

`echo $a s` -> "19 s"
`echo $as` -> ""
`echo ($a)s` -> "(19)s"
`echo {$a}s` -> "{19}s"

Thanks!

**Comment by faho** [comment]
>  echo {$a}s -> "{19}s"

Please try again, that should print `19s` like you want.

Alternatively quoting the variable would also work if it only has one element: `echo "$a"s`

>fish, version 2.7.1

Also I would recommend you use [our PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3) as that fish version is quite out of date.

**Comment by robs-nice99** [comment]
Thanks for the quick answer!

In fact I'm quoting everything 

`"echo {$a}s"` -> "{19}s"

So I shouldn't quote big strings with spaces and so?

**Comment by faho** [comment]
>In fact I'm quoting everything (I wrote it incorrectly in the original post)

Ah, that explains it. Or rather I'm willing to bet you actually ran `echo "{$a}s"`, with the `echo` outside of the quotes.

What's happening here is that brace expansion - what handles the `{}` - isn't active in quotes, so fish just sees the `$a` and replaces it with the value of the variable named `a`.

What you want to do here is explain to fish that what comes after the `a` isn't part of the variable name anymore.
There are a few ways to handle that. Either you can close the quotes before and open them again after:

```fish
echo "something"{$a}"s"
```

or you can use `printf`:

```fish
printf "%ss\n" $a
```

(the `%s` here is a placeholder that will be replaced with an argument, so this will put $a there)

or use `$a[1]` if you want the first value of a:

```fish
echo "$a[1]s"
```

or, if $a can have multiple elements (all fish variables are lists), it might even make sense to close the quotes, then use `"$a"` and then open quotes again:

```fish
echo "something""$a""s"
```

>So I shouldn't quote big strings with spaces and so?

Quoting is about marking things as special *to fish*. When you use quotes, fish won't do certain things to your argument. It won't split it into separate arguments (so `"one thing"` will be passed as one thing), it won't expand globs (`*`), braces (`{}`), tilde (`~`), etc.

In double-quotes (`"these"`) it will still expand variables (`"$a"`), in single-quotes (`'these'`) it won't (the only things special in single-quotes are `\'` to mean one single-quote and `\\` to mean one backslash).

If a "big string" contains no characters that are special to fish quoting is useless - `"banananana"` is exactly the same as `banananana`, and quoting `-r` as `"-r"` won't change what the command does with it. It's not *harmful*, it just does nothing.

If a string contains characters that are special to fish, you *have* to quote if you don't want them to have their special meaning.

This includes spaces - `rm "one file"` will remove a file called `one file`, `rm one file` will remove a file called `one` and a file called `file` (but not spaces inside variables - if you `set a "one file"` you can just use `$a` later because fish remembers that it was one thing, you don't have to keep quoting it again and again and again).

As a special case for `echo` that will put spaces between its arguments, so `echo "one thing"` and `echo one thing` would end up printing the same thing (but `echo one    thing` would also print `one thing`).

**Comment by robs-nice99** [comment]
So right! My typing mojo is not the best today. I mean `echo "{$a}s"`.

Thanks for the detailed explanation!

**Comment by faho** [comment]
Question has been answered, closing.
