### ISSUE TITLE
Abbreviations

### ISSUE THREAD

**Issue by dag** [fish-shell/fish-shell#731]
Introduce abbreviations as an alternative to aliases, possibly replacing them.

Abbreviations are exactly like aliases, except they're expanded into their full form live as you type them on the commandline.  Say you have `gc` as an abbreviation for `git commit`; now if you type `gc -am "did stuff"` the commandline changes when you type the space after "gc" and finally ends up as `git commit -am "did stuff"`.  This should only happen in command position, and when you type a space or hit enter.

*Original text follows:*

## Replace aliasing with self-expanding short forms

I don't know what to call these but anyway.  The idea is that if you type "g" as a command it expands to "git" when you type a space or enter.

Arguments for:

* It solves many of the issues with completions.  Since the alias expands "live", the git completions work as normal and `commandline` doesn't have to lie or do any other hacks like that.
* It's easy to implement.  I can kinda do it with `bind` and `commandline` although I didn't try to write a complete implementation.  We don't need any changes to `function` or `complete` etc, as in other proposed solutions.
* It's arguably "fishy": the user can see the expanded form, it's not hidden in an alias; it's instant and live, similar to completions, prompt repainting with `prevd-or-backward-word` etc.
* When copy-pasting a command-line for instructions to others, it won't be full of your custom aliases that they have no knowledge of.
* You can edit the expanded form if it's only almost-right.

Arguments against:

* Doesn't solve the problem with `alias git=hub`, a problem that doesn't currently exist but is introduced with some alias completion proposals such as this one.  However you can simply write a normal function `function git; hub $argv; end` instead to side-step this proposed alias system.
* Some might find it surprising to have the command-line change as you type, without pressing anything like Tab or such.
* The reason you can edit the expanded form is also the reason you can't delete what you typed with simply two backspaces.  Even CTRL-W might not be enough as you might have `gc` expand to `git commit` for example.  CTRL-U will do if it's the only command but it will delete too much if you're using the alias for a pipe for example.  Perhaps we could introduce a new binding for "kill current command but not whole buffer".
* :question:

Prior art:

* `:abbreviate` in Vim
* I think maybe search engines in Chrome?

Discuss.

**Comment by binaryphile** [comment]
Hey folks,

I wanted to make a note after having used abbreviations for quite some time now.

I'm a big fan, and they make my life much easier.  I especially like the fact that other people can see what commands I'm issuing, in a familiar form.

My only dislike is that there is no history for abbreviations.  Since I use abbreviations for almost every command, this has ended up with me losing history functionality for the most part.  While you may think that abbreviations should be short enough to not need history functionality, I find myself missing it quite a bit.  I have over 200 abbreviations defined, and some of them differ only slightly.  Having history show me the one I issued yesterday, for example, would be immensely useful for the more involved and less-frequently used abbreviations.  As I practically live with abbreviations, I've had to resort to using functions instead where I need history support since I really don't have history otherwise.

Thanks again for the feature.

**Comment by ridiculousfish** [comment]
@binaryphile Would you like to propose what the UI for this should look like?

**Comment by binaryphile** [comment]
Good question.  I guess I'd just like if any expansion were triggered then for the abbreviation to go into the history list.  So if I my abbreviation were "gclon" for "git clone", then when i hit space (or semicolon), "gclon" would be added to my history.  I wouldn't alter the normal behavior of storing the expanded command in history, so both would be available.

After that, when I began typing a prefix of the abbrev (such as "gcl"), I'd expect "gclon" to be the first option for autocompletion to pop up.

Ideally, at that point I'd be able to hit alt-f and have it both complete automatically to the expanded version, plus further offer a new autocompletion of the expanded command from history.  I'd want that  because I may have entered further arguments after expansion, and would want to have that available in as few keystrokes as possible via the same route I entered it in the first place (abbrev then arguments).  Since the abbreviation in the history wouldn't have them, alt-f would be the most natural method for me to move further along the completion argument by argument.

I think ctrl-f wouldn't change and would just move forward to the end of the abbreviation, not the expanded version, since there would be no visual cue as to what you'd be expanding to.

**Comment by ElijahLynn** [comment]
I just got a nightly build up and running to finally test this! I really like this feature and love the fact is has the `abbr` command that ships with it. 

My feedback is that it just needs a good way to export for dotfiles. I am thinking these should all go into one file in the format `abbr --show` outputs. `abbr --show` is good enough for me for now, I am just going to pipe them into a dotfile for now. But I do want an easy way to import them again when that time comes. So if Fish could import that format now that would be a good next step.

**Comment by ElijahLynn** [comment]
Following the command in the example to add a new abbreviation fails with this error. 

![selection_235](https://cloud.githubusercontent.com/assets/1504756/6450792/4bfaa510-c0f8-11e4-9f0e-dd70c8db4add.png)

**Comment by zanchey** [comment]
Currently you need to enter `abbr -a "gco git checkout"` but I think it would make more sense to support the case described in the manual.

**Comment by ElijahLynn** [comment]
Ahh, thanks!

**Comment by zanchey** [comment]
48d3536 makes that change.

**Comment by zanchey** [comment]
I think we should either leave the '=' separator support in the next minor release and disable it after that, or (silently?) upgrade people's `fish_user_abbreviations`.

**Comment by zanchey** [comment]
I'm going to close this as fixed; I filed #2051 to track the migration. Many thanks to @dag for the concept and all those who tested it - looking forward to seeing this released soon!

**Comment by ElijahLynn** [comment]
W00t, thanks everyone, I really LOVE this feature!!

**Comment by dideler** [comment]
I'm loving abbreviations, it's a much friendlier experience than aliases. Thanks so much!

I came across this thread while looking up how to store abbreviations in dotfiles<sup>[1], [2]</sup>.
 If anyone stumbles here for the same reason, you can use `abbr -s/--show`. For example

```
abbr --show >> ~/.config/fish/config.fish
```

[1]: https://github.com/fish-shell/fish-shell/issues/731#issuecomment-56252503
[2]: https://github.com/fish-shell/fish-shell/issues/731#issuecomment-76825189

**Comment by ElijahLynn** [comment]
@dideler I am using something similar to that for automated backup, I also recommend piping to `sort`.  

`abbr --show | sort > fish_abbreviation_backup;`

I put everything into a fish_abbreviation_backup file and then add that to Homeshick for backup. It is all automated though and runs on cron. After I backup I `source fish_abbreviation_backup` so that fish shows alphabetical order when doing an `abbr --show`.

Would be nice if fish kept abbreviations in a file, similar to how it does things with functions.

**Comment by krader1961** [comment]
> Would be nice if fish kept abbreviations in a file...

From the man page: "Abbreviations are stored using universal variables." Which means you'll find them in the *~/.config/fish/fishd.macaddr* file under var name `fish_user_abbreviations`. The `abbr` command simply manipulates that universal var.

**Comment by ElijahLynn** [comment]
Thanks, would it be okay to consider the idea of keeping them in ~/.config/fish/abbreviations.fish so we can add them easily to our dotfiles?

**Comment by faho** [comment]
@ElijahLynn: What I do is I have a file called "abbrs.fish" in ~/.config/fish/conf.d/, with the following contents:

```fish
if not set -q fish_initialized
	abbr -a alsamixer alsamixer -c0
	abbr -a e emacs -nw
	abbr -a \$PAGER less
	abbr -a mu4e emacs --eval "\(mu4e\)"
	abbr -a pm pulsemixer
	abbr -a rm rm -I
	abbr -a sc systemctl
	abbr -a upo upower -i /org/freedesktop/UPower/devices/battery_BAT0
	abbr -a usc systemctl --user
	# Double-escaping needed
	abbr -a d2 env WINEPREFIX=/home/alfa/.wine32/ wine ~/.wine/drive_c/Program\\ Files\\ \\(x86\\)/Diablo\\ II/Diablo\\ II.exe
	abbr -a c curl -LO -C -
	set -U  fish_user_paths ~alfa/.local/bin $GOPATH/bin
	set -U fish_initialized
end
```

I have this in [my dotfiles](https://github.com/faho/config), and I can just drop it into any machine I haven't yet used it on, and if I want to reset the abbrs, I can erase them all (I do `set -e fish_user_abbreviations; set -e fish_initialized`) and restart fish.

**Comment by ElijahLynn** [comment]
Thanks, I may be missing this but that looks like you need maintain that manually and don't get to add manage them easily with the `abbr` command.

**Comment by faho** [comment]
You add the abbr command there. This can even be the output of an `abbr --show` call.

**Comment by AlexWayfer** [comment]
> Only in command position is probably a good start. Then we can maybe experiment with the argument position use cases I suggested before.

I think not only a position in the start would be handful, example: `s` for `sudo` and `n` for `nano` which can expands from `s n` to `sudo nano`, but not in the current implementation.
