### ISSUE TITLE
vi mode will cause ctrl + f invalid

### ISSUE THREAD

**Issue by juniway** [fish-shell/fish-shell#7312]
fish version: 3.0.2
OS: Mac OS X
terminal: iTerm 2

Problem:
 if I enable vi mode by fish_vi_key_bindings, then ctrl + f (used for autocompletion) will become invalid.

**Comment by faho** [comment]
Yes, this is to be expected. Ctrl+f is an *emacs*-style binding, so it's not active in the vi-mode.

Either bind just *it* with something like 

```fish
bind -M insert \cf forward-char
```

or use full hybrid bindings. See [the docs](https://fishshell.com/docs/current/index.html#command-line-editor).

Or use any movement, the basic idea is that everything that goes over the suggestion will accept the part it went over, the exception being forward-char which accepts the entire thing even tho it only goes over one character, because accepting just one character isn't all that useful.

**Comment by faho** [comment]
Question has been answered, so I'm closing. If you have any follow-ups feel free to ask tho!

**Comment by MostFrabjous** [comment]
i (today) use 
`bind -M insert ctrl-f accept-autosuggestion `
