### ISSUE TITLE
random should be mod 32768 not 32767

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#732]
The documentation says that the output of `random` is 0 <= N < 32767.

Surely this should be 0 <= N <= 32767 ?

The relevant code in `builtin.cpp` is:
```
append_format(stdout_buffer, L"%ld\n", labs(res%32767));
```

**Comment by krader1961** [comment]
I'll chip in my two cents since I threw together a small change to address essentially the same point raised in issue #1272. While it's always better to use a cryptographically strong rather than weak PRNG anyone using the shell random number generator for cryptography is using the wrong tool. The random number generator provided by ksh, bash, zsh, and fish is meant for trivial tasks on a local machine (e.g., generating a unique identifier) where a small chance of a collision isn't catastrophic. If you're using it for anything else you've got a major problem.

**Comment by faho** [comment]
Fixed by https://github.com/fish-shell/fish-shell/commit/ef31aa94f8673482fca3e23e4ea0e88c60014526 - #2641. Let's track suggestions for a better interface in #2642.
