### ISSUE TITLE
complete should allow setting default function

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7322]
As of 903b7888d3baad2e5e4f7a766e9b6fb0164b2b25, complete no longer requires the `-c` argument, and can be used as `complete foo -l opt`. I propose that we go one step further and not require the `foo`, given that `complete` is virtually always used in completion files that should (must?) be named as their command. `complete` should default to the basename of the current file just as `argparse` defaults to the current function.

**Comment by IlanCosman** [comment]
I'd say we're already pretty knee deep in magic with autoloading. "Put this file in that folder with that specific name, and we'll get it for you when you need it." I don't see this as worse than that. Completions and functions are already restricted in their file names to match their commands. Why is this okay for autoloading but not ok for `complete`?

**Comment by mqudsi** [comment]
All fish scripts (i.e. no shebang) should work did you do `cat foo.fish | source` where all path info is stripped. This wouldn’t work.

**Comment by IlanCosman** [comment]
That's a very good point that I hadn't considered. How about instead `complete` default to a variable for example `_fish_complete_func_name` or something. One would set that at the top of each long completion file and then leave off the funtion name from every complete afterwards. This could even be built in to `complete`, like `complete --set-function blah`.

**Comment by faho** [comment]
Yeah, nah. That's even more magic, and even more weird implicit state you're carrying around.

If passing the command is too long for you, just pass a variable:

```fish
set -l c -c my-super-long-command

complete $c -l first-option -s f
```

The reason to do something slightly naughty with `argparse` is that

1. it's about *error* messages, so you only find out you didn't pass a name when something goes wrong, which is precisely the wrong time for that - in contrast, this is just a shortcut
2. it's about the *function*, which argparse is already coupled to by setting `$argv`, and which is already more of a thing inside fish script - autoloading is supposed to be invisible at this level (this doesn't entirely work with variable handlers, but that's unfortunate)

Since it appears we dislike this proposal, I'm closing the issue. Thank you for the idea(s)!
