### ISSUE TITLE
Emacs/readline-style shortcuts do not work with the escape key

### ISSUE THREAD

**Issue by zyanai** [fish-shell/fish-shell#7338]
Fish version: `fish, version 3.1.2`, installed with homebrew
I tried fish without third-party customizations with the suggested command.
Operating system: Mac OS
Terminal: Any. I did test kitty, iTerm and terminal.app.

After recently updating fish, using shortcuts like `<ESC>b` and `<ESC>f` stopped working. This is only an issue on Mac OS, since "alt" (option) can't be used as the shortcut modifier key (it's more like an altGr).

To reproduce:
1. Write any text, e.g. "foo bar baz"
2. Press `<ESC>b`

Expected: Cursor moves to first character of 'baz'
Actual: 'b' gets outputted to the line.

**Comment by faho** [comment]
See https://fishshell.com/docs/3.1/cmds/bind.html#special-case-the-escape-character.

What happens here is that alt+char sends escape+that character, so pressing escape and the character happens to work.

However, since escape is also a key by itself fish needs to disambiguate it by waiting for a bit after the escape character was seen, and in 3.1 we reduced that timeout to make the common case of using alt+char and escape on its own better.

If you want to use escape+char, set $fish_escape_delay_ms to a higher value, e.g. 

```fish
set -g fish_escape_delay_ms 100
```

**Comment by zyanai** [comment]
That works, thanks!
Sorry for the nuisance.

**Comment by zanchey** [comment]
Also you can change the action of the Option (Alt) key in Terminal.app/iTerm: there's a setting called "use Option as Meta".
