### ISSUE TITLE
umask symbolic modes are buggy

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#738]
A quick note, and one that should be relatively easy to fix post fish-2.0.

Symbolic modes in `umask` are buggy. Using `+` or `-` in a mode causes a syntax error (because of an array dereference of a non-array variable). Even having fixed this in my local branch, the + or - options do not actually appear to alter the umask in any appreciable way. They make the umask documentation quite confusing too.

**Comment by krader1961** [comment]
OMFG! This is done via a fish variable set by a `umask` function rather than a builtin command. Setting the variable causes magic C++ code to be run. Which means that changing the behavior is problematic since it should probably only be done in a major release if doing so involves turning the implementation into a builtin.

Note that `echo $umask` "works" in fish but produces no output in bash.

**Comment by krader1961** [comment]
In addition to the other problems with the `umask` function it depends on the `perl` command. Obviously that is not a good idea. If we can't do it with the available fish functionality we should at least be using Python since that is already a hard dependency and Perl is not.
