### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7394]
Currently there is a singular issue template that is focused on bug reports. It is neither applicable to, nor offers any guidance on, the format of feature requests, questions, etc, but appears regardless whenever you open an issue. It is also using the older style of issue templates that GitHub has deprecated. 

> You are using an old version of issue templates. Please update to the new issue template workflow. Learn more

The new style of issue templates offers a menu of templates and then automatically assigns a label based on the one selected.

I suggest that we create a set of new issue templates including bug reports, feature requests, and questions. I am happy and willing to self-assign this. I may have a few questions for the fish maintainers though, starting with: Where should questions go? Do we prefer that people create issues for them, or should they be directed to the gitter (which can be easily done through the new template system)?

**Comment by faho** [comment]
I've not opened an issue anywhere with multiple templates. How does that work? Do you have to select one? So you get the choice between "I want to report a problem", "I want to ask a question" and "I want to request a feature"?

I'm not too sold on the idea of investing too much effort and adding more steps/barriers here because enough people don't use the current template as it is, and questions often end up being feature requests.

>Where should questions go? Do we prefer that people create issues for them, or should they be directed to the gitter

Really either is *fine*. Gitter is probably overall the better system for answering questions, but I don't think we want to ask people to create yet another account just to ask a question, and questions will end up here regardless, so we might as well allow them. Also like I said, questions often end up becoming feature requests (or bugs!).

**Comment by IlanCosman** [comment]
Here, my project Tide uses issue templates: https://github.com/IlanCosman/tide/issues/new/choose. You can play around with it. My templates were heavily inspired by Starship's issue templates.

It's really not much effort at all, just tailoring my existing templates to fish, copying some of what you have in the current template. As for adding barriers, I suppose? It's one more click so not much more work. The real "barrier" has always been the template itself, since people don't want to fill them out. My templates much more strongly encourage people to fill them out than yours, but I can change that if you wish.

**Comment by zanchey** [comment]
I don't know there's much to be gained here.

**Comment by mqudsi** [comment]
Projects do this when there are (or they expect to have) a lot of low-effort issues with people that can't figure out how to provide information relevant to the maintainers to help address or categorize their concerns. It also helps with projects seeing dozens of issues a day because you can apply labels in an effort to somewhat automagically triage the issues.

Oftentimes issue templates are outdated, too rigid, or too few and do not properly cover what users that know what they're doing need. Also it may require categorization the reporter is not aware of, such as where to draw the line between a bug report and a feature request or whether something is a question or a problem. 

I've never seen a project where adopting complex issue templates wasn't a somewhat user-hostile move put in place at the request of the maintainer in an effort to maintain some semblance of sanity in the issues section. I'm happy we don't do this.

**Comment by zanchey** [comment]
Thanks for the suggestion, but it doesn't sound like we're keen on this.
