### ISSUE TITLE
Improve undoing fuzzy completion matches

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7433]
On StackOverflow someone complained that it's sometimes unwanted to turn something like `/etc/ft` into `/etc/fstab`.

In that case it was a fuzzy match (a "fuzzy_match_subsequence_insertions_only" match to be precise), because "ft" fuzzy-matches "fstab", but really it was just a typo.

Of course it's always possible to use undo (well, once 3.2 is released), but that requires an extra binding you have to know about.

I think we might find a way to do better.

Some idle ideas:

- Always open the pager if the match is fuzzy
- Allow "cancel" (i.e. escape) to undo a completion if pressed right after it (this would work for *all* types of completion matches)

**Comment by krobelus** [comment]
I like the cancel idea. Redoing is also intuitive by pressing tab again.

Maybe disable it when the pager was used to select a completion,
because that's harder to redo after accidentally pressing escape.
Also, in the pager the user manually confirms any fuzzy match, so the motivating problem doesn't really exist here.

**Comment by terminator14** [comment]
I was the one on [stack overflow complaining](https://stackoverflow.com/q/64576246/6423456). Thanks faho for the reply.
Just to repeat the example I gave on stack overflow for this, this is what happens to me when working on a file in a git repo:

- I have a file in the current directory named `lib.py` that has been modified since my last commit
- I type `git difftool li` and hit `<tab>`, expecting to end up with `git difftool lib.py`
- Fish replaces what I wrote with `git difftool templates/nxt_connect/dish_controls.html`, because from what I understand, it doesn't have a built-in completion file for `git difftool` so it doesn't even check the current directory for files when I hit tab


At this point, I have 2 options:

1. Hold backspace for several seconds until I delete the arg it filled in (templates/nxt_connect/dish_controls.html), and replace it with `lib.py`; OR
2. Hit Ctrl+u to delete my entire line, and start from scratch

Because I can type "git difftool" faster than waiting for backspace to delete that long string, I choose option 2. This basically means that fish's autocompletion messed up so bad that it was easier for me to delete the entire line, and start from scratch, than fix it by hand.

An undo function would be nice.

The bigger issue I have with this is that fish tries to be smarter than the user. It decides that what the user wrote isn't what he meant, and that it will delete what he wrote, and replace it with something else, which some people might be ok with, but others are not. I find it incredibly annoying, and wish there was a way to disable this.

faho mentioned on stack overflow that this probably won't happen. That's too bad.

**Comment by faho** [comment]
@terminator14 Please check what the issue actually *does*.

>An undo function would be nice.

This is now implemented. All you have to do in the next release is press escape after the completion was accepted, and it will undo that acceptance.

So you enter `ls /etc/ft`, press TAB, that turns it to `ls /etc/fstab`, press escape, that turns it back to `ls /etc/ft`.

In addition to that, the next release *has* a general undo functionality, bound to ctrl-z, so you can press that to undo *any* change to the commandline.

>are willing to do a quick search online for a way to disable this could have a simple flag in some config file that they could set to do just that.

Again: This is not how fish operates. We try really really really hard not to make things an option.

**Comment by terminator14** [comment]
You mentioned that on stack overflow. I don't quite understand - why are options bad? Almost every open source project has config files with options you can enable and disable. I, along with many others I'm sure, always thought options were a good thing.

**Comment by faho** [comment]
>I don't quite understand - why are options bad? Almost every open source project has config files with options you can enable and disable.

Please read [our design document](https://fishshell.com/docs/current/design.html#configurability-is-the-root-of-all-evil).

In short: Options are usually a cop-out when you can't bring yourself to just pick, and they increase the surface area and thereby make things *worse*, not better.

But anyway, I don't particularly want to debate this at length. In short: An option to disable this form of fuzzy matching won't be added. If you come up with a solution that doesn't include an option we can discuss it.

**Comment by terminator14** [comment]
I see. Had a quick look. Some of the points in the document I agree with. Others I don't, but like you said, this isn't the place to debate that.

Thanks for the info.
