### ISSUE TITLE
Fish config dir variable empty on iTerm

### ISSUE THREAD

**Issue by doron-cohen** [fish-shell/fish-shell#7439]
Hi, I am having an issue with Fish's config dir location. At first Fish configured it's config dir in `~/.config` (which is wrong on Mac OS). Everything worked but when I set XDG variables in `conf.d/xdg.fish` it all got messy. I included these vars:
```
set -Ux XDG_CONFIG_HOME $HOME/Library/Preferences
set -Ux XDG_DATA_HOME $HOME/Library
set -Ux XDG_CACHE_HOME $HOME/Library/Caches
```

Ever since the fish session I started with when opening iTerm worked with `~/.config/fish` but when I started a new fish shell from within, it would work with `~/Library/Preferences/fish`! I edited at least 5 different fish config files including `$__fish_data_dir/config.fish` but it will not set the fish config dir variable to the value I want.

All I wanted is to move the config dir to one place and keep the XDG variables set.

Version: `fish, version 3.1.2`
OS: Mac OS Catalina 10.15.7
Terminal: iTerm 3.3.12
```
> echo $TERM
xterm-256color
> uname -a
Darwin hostname 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

**Comment by faho** [comment]
>config dir in ~/.config (which is wrong on Mac OS)

It's not wrong. It just uses one particular set of conventions over another.

It's also not the only project to do so (e.g. git and tmux do as well).

But mainly we don't want to have to tell people to "use this directory, unless you're on macos, then use this".

---------------

So, what is happening here is that fish decides where to look *before* it has the universal variables.

That's because the universal variables are stored in $XDG_CONFIG_HOME/fish/fish_variables, which means it would have to have the variable before it can get the variable.

That also explains why it works in your child fish: That inherits $XDG_CONFIG_HOME, so it has it before it tries to look for fish_variables.

What you would have to do is to pass XDG_CONFIG_HOME to the parent fish as well, e.g. via your terminal.

Unfortunately https://gitlab.com/gnachman/iterm2/-/issues/5307 says that iTerm doesn't support setting environment variables (and I don't think you can set variables above that so iTerm inherits them as well?), so you'd have to set the "shell" it executes to a wrapper script or something like `/usr/bin/env XDG_CONFIG_HOME=... fish`.

Personally I'd recommend not bothering.

**Comment by doron-cohen** [comment]
Moving to `~/.config` solved this issue
