### ISSUE TITLE
Fish shell autocompletion gets duplicated on linux

### ISSUE THREAD

**Issue by joelmagner** [fish-shell/fish-shell#7449]
fish: version 3.1.2
OS: 5.4.0-51-generic #56~18.04.1-Ubuntu SMP Tue Oct 6 09:47:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Term: Default Ubuntu terminal (gnome?).
Config: default fish config.

![image](https://user-images.githubusercontent.com/20977161/97962043-a8e79480-1db4-11eb-98c7-e847d146c004.png)

Seems to only happen if the autocompletion has to extend onto a new row. Works fine when window size fits autocompletion.

![image](https://user-images.githubusercontent.com/20977161/97962173-e77d4f00-1db4-11eb-9dbb-8debe3eba711.png)

**Comment by faho** [comment]
>Term: Default linux terminal.

There is no such thing. "Linux" is much more diverse than that.

Since you're using Ubuntu, I'm assuming it's Gnome terminal.

But anyway, here is what's happening: Fish and the terminal disagree on the width of a character. In this case you have some replacement character in there (that's that box that I *think* reads "0080"?). So when fish starts printing the autosuggestion and moving the cursor, it goes out of sync with the terminal.

What you need to do is:

1. Make sure you have your locale set correctly. `locale` should say something ending in ".UTF-8" for "LC_CTYPE".
2. Try your terminal's settings for ambiguous width characters. Gnome Terminal has in its settings an option about "Ambiguous-width characters". You want to set this to narrow, *or* you want to set it to wide *and* `set -g fish_ambiguous_width 2` inside fish.

Unfortunately, this is something that fish and the terminal need to agree on, and there is no good way to receive that information for fish.
