### ISSUE TITLE
How to prevent command to execute?

### ISSUE THREAD

**Issue by KirliAdam** [fish-shell/fish-shell#7460]
Hello I am using Fish-shell 3.1.2
I have function which uses fzf search and opens the selected file with $EDITOR. But when I cancel the command with ESCAPE key it still opens the empty $EDITOR window. How can I solve this problem?
This is the demonstration:
https://imgur.com/KsLFd6J

and this is my function it is binded to `ctrl+e`
``` fish
function __fzf_open_file --description "Open the file with default editor."
    set --local --export SHELL (command --search fish)
    if test $status -eq 0
        $EDITOR (fd --hidden --follow --color=always --type f --exclude=.git 2>/dev/null |
        fzf --ansi --preview='__fzf_preview_file {}') 
    end
    commandline --function repaint
end
```

**Comment by faho** [comment]
So, you're executing $EDITOR on the output of the command substitution. That's the bit you are aborting - the `fd | fzf` part.

Fish will just go on executing no matter how a command substitution exits. If you don't want that, you'd have to

1. Store the output in a variable
2. Check $status again

Something like

```fish
set -l file (fd --hidden --follow --color=always --type f --exclude=.git 2>/dev/null |
        fzf --ansi --preview='__fzf_preview_file {}') 
and $EDITOR $file
```

The `and` here will only cause `$EDITOR $file` to be run if the previous command succeeded, and the previous command here is what is *in the `()`* (because that's what `set` passes on).

**Comment by KirliAdam** [comment]
```fish
function __fzf_open_file --description "Open the file with default editor."
    set --local --export SHELL (command --search fish)
    set -l file_selected (fd --hidden --follow --color=always --type f --exclude=.git 2>/dev/null |
        fzf --ansi --preview='__fzf_preview_file {}')
#       and $EDITOR $file
    if test $status -eq 0
#       commandline --insert(string escape "$EDITOR $file_selected")
        and $EDITOR $file
    end
    commandline --function repaint
end
```

With this code it is functioning as intended.
Thank you for your time and replies.
