### ISSUE TITLE
How to set autosuggestions in italics

### ISSUE THREAD

**Issue by noib3** [fish-shell/fish-shell#7473]
fish version: 3.1.2.
terminal: alacritty 0.5.0
OS: macOS Catalina 10.15.7

I can get command autosuggestions in bold gray with
```fish
set gray 797979
set fish_color_autosuggestion $gray\x1e\x2d\x2dbold\x1e
```
Is there a way to get *italics* instead of **bold**? My terminal can use italics, `echo -e "\e[3mhello\e[0m"` prints *hello*.

**Comment by faho** [comment]
>I can get command autosuggestions in bold gray with

I mean you *can*, but really what you have there is equivalent to

```fish
set fish_color_autosuggestion 797979 --bold
```

You've probably read  your fish_variables file, which has some additional encoding. `\x2d` is just hex notation for `-` and `\x1e` is something that fish, for internal reasons, uses as a separator.

But really the color variable values are meant to be the same as arguments to [set_color](https://fishshell.com/docs/current/cmds/set_color.html).

That also neatly answers your question because `set_color` also takes a `--italics` option, so

```fish
set fish_color_autosuggestion 797979 --bold --italics
```

**Comment by noib3** [comment]
I tried
```fish
set fish_color_autosuggestion 797979 --italics
```
but it doesn't seem to work. Both
```fish
set fish_color_autosuggestion 797979 --bold
```
and
```fish
set fish_color_autosuggestion 797979 --underline
```
work without problems. I can print italics with `echo -e "\e[3m...\e[0m"`, and italics comments work inside vim. Any ideas about what is going on here?

**Comment by faho** [comment]
In that case the most likely thing is that your terminfo entry is broken - the common "xterm" one from macOS is (and the related ones like "xterm-256color" include it, so they are affected as well).

Fish has a workaround, but that only applies if $TERM_PROGRAM is set to "Apple_Terminal" or "iTerm.app". You could try that.

Alternatives include updating your terminfo.

Weirdly enough https://github.com/alacritty/alacritty/issues/4321 says alacritty doesn't support italics on macOS yet, so it's possible they just haven't come to that issue yet?

Really it's a bug in macOS and needs to be fixed there.

**Comment by faho** [comment]
Okay, no, you can just install the alacritty terminfo, others aren't supported by them anyway:

https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo
