### ISSUE TITLE
Better syntax for multiple string operations?

### ISSUE THREAD

**Issue by supercheetah** [fish-shell/fish-shell#7500]
fish, version 3.1.0

This is just an improvement request.

Recently I had done something like the following (to split up something like `a    :  bc;de;fg` and get just the trimmed part after the colon and changing the semicolons to commas and a space to return `bc, de, fg`):

    for i in *; echo $i; somecommand $i -value=(othercommand $i -arg|string split ":"|string replace -a ";" ", "|string trim)[2]; end

It seems to me there ought to be some better way to do multiple string operations like that in a more succinct manner, but I'm not quite sure what that ought to look like.  Or is there a better way that perhaps I missed in the documentation?

**Comment by krobelus** [comment]
Regex replacement works here

```
$ echo 'a ; b;c ; d ; e' | string replace -ra '\s*;\s*' ', '
a, b, c, d, e
# or with plain old sed
$ echo 'a ; b;c ; d ; e' | sed 's/\s*;\s*/, /g'
a, b, c, d, e
```

**Comment by supercheetah** [comment]
Almost, but you changed out the colon after `a` for a semicolon, which would result in this:

    > echo 'a : bc;de;fg'|string replace -ra '\s*;\s*' ', '
    a : bc, de, fg

But that said, on thinking it over, an extra regex replace could be done too, which still results in an extra string operation:

    > echo 'a : bc;de;fg'|string replace -r '[^:]+\:\s*(.*)' '$1'|string replace -ra '\s*;\s*' ', '
    bc, de, fg

**Comment by krobelus** [comment]
Yeah, it's reasonable to do it in two steps. I think `sed` is the most succinct one, you can also chain commands like
`sed 's/a/b; s/A/B/'`

If there is a way to do it with a single Perl-compatible regex, the same can probably be used with `string replace`. I haven't found one though. Anyway, closing since I don't see a tangible improvement.

**Comment by supercheetah** [comment]
What about using parenthesis to, well, string them together starting with the innermost one so that at least you only need to write `string` once?
```
string ((split ":") replace -a ';' ', ') trim
```

**Comment by faho** [comment]
>What about using parenthesis to, well, string them together starting with the innermost one so that at least you only need to write string once?

Parentheses are already used for command substitutions - this would try to run a command called `split`, and then (conceptually) run its output as the command with the arguments `replace -a`...

In other words it already *has* meaning, and we can't just completely throw the entire synax out.

**Comment by zanchey** [comment]
I think there's definitely some merit to the concept though, even if the UI isn't clear. sed handles this well but has the disadvantage of not taking input as command-line arguments.

One of the major benefits of the string builtin is that it is a relatively straightforward and readable interface. Is the composability with pipes enough? Or should `string` have a `process` subcommand that acts something like sed's `-f`?

**Comment by ChristoferK** [comment]
@zanchey, I agree that, in this, and a few other notable situations, `FiSH`'s syntactic and semantic choices are either unnecessarily cumbersome or horribly restrictive.  Have you considered writing a function to implement compound string manipulations the way you want ?  I did this, and it also provided the opportunity to include the functionality `set_color` offers in a similarly ill-conceived way.

**Comment by faho** [comment]
>Or should string have a process subcommand that acts something like sed's -f?

This would look something like

```fish
string match -r "foo" -f split -n ":" -f trim -r -- $args
# instead of
string match -r "foo" -- $args | string split -n ":" | string trim -r
```

which is about 20% shorter, at the cost of being quite confusing, semantically. I don't think the "-f" is enough of a separator to have the "split" or "trim" stand out, and now the arguments are sooo far away fromm the `match` that it's easy to forget about it by the time you get there.

Plus now we have two ways of writing the thing, and the argument parsing for this would be tricky.

An alternative would be to have string operations available as `@match` or something, to avoid stomping on commands called "join" or "split" or similar.

```fish
@match -r "foo" -- $args | @split -n ":" | @trim -r
```

which is a good 25% shorter.

But of course that also means there's two ways of calling it, and we're reserving more words, and we'd have to tell people about these in the documentation ("you can also call this as `@match`"), which makes that more annoying to read.

To be quite honest: I don't think any of this is worth it. It's only for saving a few characters, and decreases readability. It's good for code golfing, which fish isn't geared towards.

**Comment by ChristoferK** [comment]
:> But that said, on thinking it over, an extra regex replace could be done too, which still results in an extra string operation:
> 
>     > echo 'a : bc;de;fg'|string replace -r '[^:]+\:\s*(.*)' '$1'|string replace -ra '\s*;\s*' ', '
> 
>     bc, de, fg


You can do it with a single regular expression string replacement:

```
string replace --all --regex '(^.+:\h*)?(?<T>\w+)(\h*;\h*)' \
                             '${T}, ' "a : bc;de;fg"
```

**Comment by ChristoferK** [comment]
> To be quite honest: I don't think any of this is worth it. It's only for saving a few characters, and decreases readability. It's good for code golfing, which fish isn't geared towards.

@faho I think you're underestimating the benefits of what 20-25% less code can have.  It will make a core set of functions (that are undoubtedly used frequently) quicker to write out, which makes a big difference when accumulated, both in terms of time spent typing code and by improving the enjoyment to the scripter when it comes to using `FiSH` as a language (not something to be dismissed as trivial, since `FiSH`'s language design is its best feature—**`string`** notwithstanding—and after using it twice, it was how nice it feels to script with it compared to, say, `bash`, that made it an easy choice to adopt as my shell, and get many of my friends switching too).

It's surprising you say it would decrease readability.  I think readability would be dramatically _increased_.  One of the most negatively impactful attributes of a piece of text when it comes to readability is the length (width) of its lines.  It's probably why many editors set the column width to around 80, but there are too many situations where word wrapping isn't available (here on GitHub is one example) and being forced to scroll horizontally is not tolerable; and when word wrapping is performed, it is usually not in line with the code's formatting (which is very much the case in a terminal).

Both of your suggested syntactic sugars immediately appeal far more than the present syntax for all the reasons stated above.  When I first started using `FiSH`, one of the early things I did was create variables of the ilk _`set -xg MATCH string match`_, and so on.  Then, in use, it was much like your **`@match`**, which is what convinces me it is something that ought not to be taken out of consideration right away, and perhaps others can contribute syntax solutions that will have the same advantages as the two you've put forward but with fewer of the concerns you raised.

**Comment by zanchey** [comment]
I was thinking something along the lines of:

`string process 'match -r "foo"; split -n ":";  trim -r'`

but having tried it, while it is a bit more writable, it is a lot less readable. The "single regex" above suffers from the same problem.

So I think this has been a good discussion, but it looks like the general trend is against it. Thanks for prompting it @supercheetah!
