### ISSUE TITLE
source: Error encountered while sourcin file '/usr/local/Cellar/fish/3.1.2/share/fish/functions/isatty.fish': source: Interrupted system call

### ISSUE THREAD

**Issue by pardmeister** [fish-shell/fish-shell#7506]
fish version 3.1.2
iTerm2 Build 3.4.1
macOS Big Sur Version 11.0.1

Every time I open a new tab or start iTerm2 I get the above error. Tried deleting fish totally and re-installing it from scratch. The shell seems to work fine, it's just that it keeps printing out these errors intermittently.

**Comment by ridiculousfish** [comment]
Likely this is due to some part of your config. Does it happen if you run with an empty home `env HOME=(mktemp -d) fish`?

**Comment by mqudsi** [comment]
@ridiculousfish Do you think we should we be retrying (not indefinitely, of course) on EINTR in a few more places?

**Comment by ridiculousfish** [comment]
Hard to say, depends on what those few more places are!

If we do retry I think it should be indefinite. A function should either swallow signals or propagate them; there's no reason to swallow the first 100 signals, but propagate the 101st. But we can't make progress on this until we know what's causing it.

**Comment by pardmeister** [comment]
Hi

Thanks for the feedback, tried it with an empty home, and not seeing anything. Will keep monitoring for a while since the errors showed intermittently.

If it turns out that it is a config issue, what would I need to do to reset it?

**Comment by pardmeister** [comment]
My ~/.config/fish/config.fish only loads fishmarks

```fish
# Load fishmarks (http://github.com/techwizrd/fishmarks)
. $HOME/.fishmarks/marks.fish
```

**Comment by mqudsi** [comment]
@ridiculousfish I normally would have agreed with you, but I've learned the hard way that `EINTR` is underspecified and that it sometimes needs a special rain dance.

It's really hard to know if it's a transient error that can be handled locally (by trying again) or if there's nothing you can do at the call site and should bubble-up/error-out. You could end up stuck indefinitely if you assume it was just a timing fluke and the next call will complete without `EINTR`, but it could also be an overly paranoid respond to just error out unless you always have a way of bubbling up the specific interrupt error all the way to the original caller - and most of the code doesn't have that kind of functionality because it expects user/application-level errors triggered by (but functionally separate from) system errors.

**Comment by ridiculousfish** [comment]
Interesting; if we retry indefinitely on EINTR how might we get stuck? Are there platforms which deliver EINTR repeatedly or something?

**Comment by pardmeister** [comment]
@ridiculousfish and @mqudsi Thanks for this, is there more that I can do to assist with getting to the bottom of this? It's happening a lot more frequently now, with most commands, e.g. ls

**Comment by ridiculousfish** [comment]
@pardmeister it might be similar to #5665. What does `functions isatty` show? How about `which [`?

**Comment by mqudsi** [comment]
@ridiculousfish there are a lot of edge cases, but an example of a really straightforward one (though not one that we would run into, at least currently) is a naive function oblivious to the context it's running under that simply takes an fd writes to it. If it were passed a handle to the tty stdout and the calling program installs a signal handler for `SIGTTOU` then becomes no longer the tty owner, then each time that seemingly straightforward function attempts to write to the provided fd, it'll fail with `EINTR`. As the default `SIGTTOU` handler is not invoked, the program doesn't suspend and there's no delay - it'll be a tight loop attempting and re-attempting to write to the same fd on `EINTR`, oblivious to the fact that the write itself is what is causing the `EINTR` (in response to the received but effectively ignored `SIGTTOU`), ad infinitum.

A more niche variant that we absolutely *could* be running into is network I/O. While under Linux the `intr` mount option for nfs was always opt-in and now does absolutely nothing, it's still supported on other platforms (FreeBSD for sure and from what I can gather, macOS as well -- OT, but why the heck does `man nfs` return "no man page is available" on macOS?) and can cause any I/O operation to return `EINTR` if the network connection is disconnected or times out. If you're on a transient network connection - and I've run into this - with an nfs share mounted, you can easily keep getting `EINTR` in perpetuity each time you try the write, and if you don't bubble it up at some point, the software will hang. But let's say it's a `copy_file(....)` routine that runs into a transient network timeout because the wifi connection is spotty or the network server is overloaded, and that the file is a few gigabytes in size - surely a single `EINTR` *shouldn't* terminate the copy and lose all progress that's been made. 

Aside from nfs where Linux has apparently opted into just abandoning all hope of EINTR being handled correctly, I believe it's EINTR can still happen with CIFS and I've definitely run into it with fuse (with the fuse-ntfs3g driver). Even more interestingly, you'd think that `SA_RESTART` might prevent you from ever seeing `EINTR` (although I wonder what it would do in a case like the SIGTTOU issue described above - would it effectively hang forever without bubbling back any errors to the caller?) but that isn't actually guaranteed to be the case because `SA_RESTART` textually only applies to posix calls that are explicitly documented as potentially returning EINTR, but EINTR can - apparently without violating posix - be returned even for calls like `stat()` - which *doesn't* explicitly call out EINTR as an error you can expect to run into - on nfs with the `intr` option or for random fuse filesystems. I don't know if in practice `SA_RESTART` would swallow those results but it's not guaranteed in the POSIX text and I wouldn't be surprised if it didn't in practice.

(Of course, that's not to mention the system calls that *shouldn't* be retried on `EINTR`, like `close(2)` which may (and does) return EINTR but, at least on Linux and FreeBSD, still results in the fd being closed, so retrying would result in an error and/or undefined behavior. Personally, I just never look at the return from `close(2)` except perhaps to log it for posterity purposes.)

**Comment by mqudsi** [comment]
@pardmeister if you attach strace to fish and share the log, that would be quite helpful. (in another terminal, `strace -p (pidof fish) -o strace.log`)

**Comment by pardmeister** [comment]
@mqudsi, @mqudsi  It seems that the issue has now been resolved, it could be the very many OS updates that happened since. I'm happy to close this for now, should it happen again, we can revisit this? I will then run the strace and share the log.

Thanks very much for your assistance and the shell.
