### ISSUE TITLE
for loop can't make a local variable

### ISSUE THREAD

**Issue by Dante-Broggi** [fish-shell/fish-shell#7507]
Hello, I am using `fish, version 3.1.2`, on macOS Mojave.
Is there a way to have `for` not clobber existing variables?
Specifically, is there a way to have
```fish
set -l index 1; for index in (seq 10)
  echo $index
end; echo $index
```
print
```
1
2
3
4
5
6
7
8
9
10
1
```
as I would expect from non-shell programming languages?
Perhaps it could be a `-l` flag on for, eg.
```fish
set -l index 1; for -l index in (seq 10)
  echo $index
end; echo $index
```

**Comment by faho** [comment]
To be clear: `for` will clobber a *local* variable (or a global if executed in the top scope, e.g. right in the commandline). It just uses the current scope (before the block introduces a new one).

I don't think introducing an option here is worth it because the workaround is super simple: Just rename the variable. That's nicer anyway because it means you don't have two variables of the same name to juggle.

Sorry, but I'm rejecting this, thank you for the idea!

**Comment by zanchey** [comment]
As an alternative you can wrap it in a block:

```fish
set -l index 1
begin
    for index in (seq 10)
        echo $index
    end
end                
echo $index
```
