### ISSUE TITLE
load string function shadowing string builtin

### ISSUE THREAD

**Issue by guillonb** [fish-shell/fish-shell#7509]
I want to define a wrapper function for the string builtin, as in [https://www.xspdf.com/help/52798129.html](https://www.xspdf.com/help/52798129.html), and I want this wrapper to be named `string` (thus shadowing the builtin command) and to be accessible from `fish` start. Hence, I tried (1) to source its code in the loaded-at-startup file `$HOME/.config/fish/config.fish` and (2) to place its code in `$HOME/.config/fish/functions/string.fish` so the function is autoloaded. In both cases, it works (the function is defined) but I get some extra lines concerning fish command completion, at `fish` startup (before the first prompt). Here are the lines :
```
complete --exclusive -p /etc/init.d/* -d 'Reload service configuration' -a reload
complete --exclusive -p /etc/init.d/* -d 'Stop and then start service' -a restart
complete --exclusive -p /etc/init.d/* -d 'Print service status' -a status
complete --exclusive -p /etc/init.d/* -d 'Stop service' -a stop
complete --exclusive -p /etc/init.d/* -d 'Start service' -a start
complete -c '['
complete -c !
complete -c ! --wraps not
complete -c . --wraps source
complete -c '[' --wraps test 
```

This happens with the following minimal example :
```fish
$ function string
      builtin string $argv
   end
```

To reproduce the bug (twice, for (1) and (2)): [https://asciinema.org/a/SNx5Hk2GWie6395Szq31YGeA0](https://asciinema.org/a/SNx5Hk2GWie6395Szq31YGeA0)
```fish
$ set -l tmphome (mktemp -d)
$ mkdir -p $tmphome/.config/fish/functions
$ sh -c "env HOME=$tmphome fish"
[everything is fine]
$ echo 'function string; builtin string $argv; end' >$tmphome/.config/fish/config.fish
$ sh -c "env HOME=$tmphome fish"
[get the lines]
$ exit
$ mv $tmphome/.config/fish/config.fish $tmphome/.config/fish/functions/string.fish
$ sh -c "env HOME=$tmphome fish"
[get the lines again]
```

My setting:
```fish
$ fish --version; echo $version
fish, version 3.1.2
3.1.2
$ uname -a
Linux Gacrux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
$ echo $TERM
xterm
```

**Comment by faho** [comment]
The problem here is that wrapping `string` doesn't *work*.

This is because `string` will only read from stdin if it is directly redirected.

So a commandline like `thing | string` should read from stdin, but in your case the string *builtin* is one step down.

So fish's startup happens to call

```fish    
complete -c(builtin -n | string match -rv '(source|cd|exec|realpath|set|\\[|test|for)') --no-files
```

which happens to turn into  `complete --no-files` because the `string` does nothing, and that happens to list all the completions in 3.1.2, which are the hard-coded completions for builtins. That's just a symptom, the root cause is that wrapping string doesn't work.

The solution is to not wrap string (we might have to forbid it, like we do e.g. `set` and `argparse` - with #7459 it starts being able to write variables, at which point wrapping it will work even less).

Make a function with an actual name instead of trying to add stuff to `string`.

**Comment by guillonb** [comment]
Thanks for the answer. I'm not sure to completely understand what happens here, as
```fish
$ echo "thing" | builtin string upper
```
as well as
```fish
$ function mystring; string $argv; end
$ echo "thing" | builtin string upper
```
work as expected (so my above problem is the use of `builtin` within a function). Based on your comment, I also found a workaround, which seems to work correctly for my use:
```fish
$ function string
       if isatty
           builtin string $argv
       else
           cat |  builtin string $argv
       end
  end
```
Nevertheless, I got the message: wrapping `string` is a bad idea and will fail in future.

**Comment by faho** [comment]
>Thanks for the answer. I'm not sure to completely understand what happens here, as

Okay, let me try to explain.

`string` takes the strings to work on either on stdin or as arguments.

So

```fish
string upper foo bar
```

is the same as

```fish
printf '%s\n' foo bar | string upper
```

This is obviously quite useful, but there's an issue in how to distinguish these cases.

Take this example:

```fish
function thing
    set -l upper (string upper $argv)
    while read -l input
        echo Read a line: $input
    end
end
echo someoutput | thing
```

If you pass arguments, they'll be passed along to `string`, and it will work on them. But if you don't, this would execute the equivalent to `set -l (string upper)`, and that string reading from the function's stdin would be quite surprising.

We've had a similar case with `source` - people did `source (somecommand)` and if `somecommand` didn't have output the `source` would read from stdin and fish would appear to hang.

Just refusing to read from *the terminal* isn't quite enough, because with that function above `string` would suddenly empty the function's stdin.

So string refuses to read from stdin unless it is "directly redirected", i.e. attached to a pipe or fd *directly*.

Now, there's a missing `--stdin` flag to force it to read from stdin inside a function, which would fix this case, currently (and be useful in general to avoid having to use `cat | string` in functions), but because #7459 makes `string` in some cases create local variables making a wrapper function would break anyway (just like making a wrapper around `set` - you'd suddenly break `set -l` because the wrapper introduces its own scope), so we're going to have to disallow making a function called `string`, like we disallow making a function called `set` and `read` and `argparse`, because they *can't* work when they are wrapped.

>work as expected (so my above problem is the use of builtin within a function)

It's not, you're not using `mystring` in the second example - `echo "thing" | mystring upper` won't read from stdin, so it will print nothing (because it has 0 strings to work on as arguments).
