### ISSUE TITLE
Add a way to expand tokens

### ISSUE THREAD

**Issue by dag** [fish-shell/fish-shell#751]
Let's say the binding is CTRL-X.

Now we can be more selective: `rm *.png` CTRL-X `rm a.png bc.png foo.png` CTRL-W `rm a.png bc.png`

We can confirm that we typed the right thing before executing: `mkinitrd (uname -r)` CTRL-X `mkinitrd 3.8.11-200.fc18.x86_64`

Or that we typed enough: `kill %fi` CTRL-X `kill 1580 1684 2021 3431 3822` oops I only wanted firefox

Possible problems to solve:
- Evaluation has side-effects (at least for subshells) such as printing to stderr.  Completions have the same problem though.
- Are the problems with `eval` relevant to this?
- The result needs to be properly quoted or escaped so that it works exactly like running the commandline without expanding anything (other than the obvious stuff like `(date)` depending on when it's run).

This idea came out of #731 but I now think they're two separate ideas.

**Comment by krader1961** [comment]
I was going to close this as "will-not-implement" because we most definitely do not want to expand constructs like subcommands. However, expanding wildcards is safe from side-effects and could be useful. So I'm adding the "RFC" (request for comment) label to solicit more feedback on the idea.

**Comment by zanchey** [comment]
I think @faho was working on something along these lines.

**Comment by faho** [comment]
Yep, I have attempted to make an "expand" builtin. The way it currently works is that it'll perform all safe expansions on its arguments, unless an option is given to skip a particular one. So `expand '{$a}*' will perform variable-expansion, brace-expansion and wildcard-expansion, while `expand --no-wildcard '{$a}*'` will not do the wildcard-expansion.

I still have a few open questions:

- Should this have an option to _do_ command substitutions? (Currently it doesn't, and I'm quite sure it should not do them by default)

- Should this already escape the string, or have an easy option to do so?

- How about newlines? A "-z" option to do NUL-delimited output?

- Are there any changes to make it more useful for other usecases? (My initial motivation was to make fuzzy expansion usable by completion scripts, which would require some more work)

**Comment by krader1961** [comment]
It seems to me that it must escape all strings so that when word splitting is done you get the same tokens that would occur from the unexpanded args. This includes escaping newlines and other non-printable chars (e.g., tabs).

My personal preference is for the default (no flags) behavior to only do wildcard and brace expansion. With var expansion being opt-in. Note that the original problem statement also asked for job expansion. I think that is a bad idea. If we allow it then it must also be opt-in (not enabled by default).

I would defer deciding whether to do command substitution. Let's implement the most useful feature (wildcard and brace) expansion then see how people react. Also, why does it need to be a builtin command? If someone wants to see the results of expansion just use `echo`. As I see it this is only useful as a bind function that mutates the command line in place.

**Comment by zanchey** [comment]
Job (or process) expansion has no side-effects, but it's racy in the sense that the results may quickly become inaccurate - is that your concern?

**Comment by krader1961** [comment]
The problem with expanding job specifiers in this manner doesn't help. Consider the example in the original problem statement. You type something like `%fi` and expand it to zero or more PIDs. Even if it expands to a single PID and you expect a single PID how do you know that is the correct PID? It would be more useful to implement tab completion of job specifiers so that you can see more context (e.g., process name, args, owner) before selecting a PID. Job specifiers (and the PIDs they expand to) are quite different from wildcards. In the latter case you can readily tell whether the resulting file names are what you expected. Which isn't the case with PIDs.

**Comment by faho** [comment]
>It seems to me that it must escape all strings so that when word splitting is done you get the same tokens that would occur from the unexpanded args. This includes escaping newlines and other non-printable chars (e.g., tabs).

Keep in mind that we don't have POSIXy word-splitting, and we have `string escape`.

The issue is if this offers already escaped files, you could not then use these strings to actually operate on those files. E.g. `for file in (expand 'a*'); test -d "$file"; and echo $file; end` would not be guaranteed to work.

There is of course the issue of newlines in filenames, but note that we have largely ignored it in general, and it's not actually a huge problem in practice. Also, I don't have much sympathy for people who use those and am a strong proponent of https://www.dwheeler.com/essays/fixing-unix-linux-filenames.html. Anyway, this could be fixed by adding a "-z" option.

>Also, why does it need to be a builtin command? If someone wants to see the results of expansion just use echo. As I see it this is only useful as a bind function that mutates the command line in place.

This is useful for at least two things - for the binding described in this issue, and for completions (e.g. to make `__fish_complete_directories` behave like the built-in file completion wrt variables and tildes and such). To be usable in both, it can't be just a bind function.

>Note that the original problem statement also asked for job expansion. I think that is a bad idea. If we allow it then it must also be opt-in (not enabled by default).

My implementation currently does job expansion simply because it was easy to do so. (All this maps rather neatly to the "expand_flags_t" enum)

>My personal preference is for the default (no flags) behavior to only do wildcard and brace expansion. With var expansion being opt-in.

When would you not want var expansion? I see this being useful to do the same kind of transformations that would happen if the argument were used in the commandline (with the exception of command substitutions because those are dangerous). In the completion example, you'd want to expand variables because that would also be done when the token you completed is actually evaluated.

Additionally, it's consistent to do _all_ expansions by default, instead of doing _some_ and opting in to others.

>Even if it expands to a single PID and you expect a single PID how do you know that is the correct PID?

`ps -p`? Anyway, job expansion isn't really useful for either of the use cases I have in mind (since it's not used as part of larger tokens), so I'd be okay with nixing it for now.

**Comment by krader1961** [comment]
I'm confused by your example, @faho. Specifically this one: `for file in (expand 'a*')`. Why do we need an `expand` command for this when you can already just do `for file in a*`? Perhaps you meant something like the following:

```
set glob 'a*'
for file in (expand $glob)
```

Note that in that case you don't need var expansion since that will have already been done by the parser and `expand` will receive `a*` as its argument. Nor is var expansion needed for this scenario (do this in the fish-shell dir):

```
set x c
echo {$x}*
set x _
echo {$x}*
```

You only need var expansion if you want to do something like this:

```
set prefix abc
set glob '{$prefix}*'
for f in (expand $glob)
```

And I'm not convinced we want that extra level of indirection by default. On the other hand it might be what we want for the completions use case. It could be suppressed via a `--no-vars` for the key binding use case where the user almost certainly wants only bare globs expanded. I'd like to see some more examples of how this would be used in completions.

**Comment by krader1961** [comment]
Also, the proposed `expand` command is more general than the `glob` command we've talked about and can therefore obviate the need for the latter. But to do so `expand` will also need to have options for controlling how globs that don't match any files are handled.

**Comment by faho** [comment]
>Why do we need an expand command for this when you can already just do for file in a*? Perhaps you meant something like the following:

Sure. The `'a*'` was just meant as a simple example. Anything that expands to `a*` will behave the same.

>And I'm not convinced we want that extra level of indirection by default.

That is kind of the point of this builtin. You have a string in a variable, and you want to expand it as if you had it as a literal.

>On the other hand it might be what we want for the completions use case.

Yes, exactly.

> But to do so expand will also need to have options for controlling how globs that don't match any files are handled.

What do you mean specifically? Unfortunately I can't find the issue where we've discussed `glob`, so pointers would be appreciated.

**Comment by cben** [comment]
Prior art:  
gnu readline lib has `tilde-expand` command (bound to <kbd>Alt+~</kbd> by default) that expands `~` and `~user` in-place.  
Also, if you add `set expand-tilde on` to ~/.inputrc, <kbd>TAB</kbd> completion will also expand tildes in-place, iff it successfully finds one or more completions (so `mkdir -p ~/nosuchdir/` won't expand in-place, and `~root/` doesn't expand if you don't have permissions to read /root).

(Both have some other divergences from bash's tilde expansion rules (#1410) e.g. don't expand `FOO=~/dir`.   But that's just because they're implemented independetly bash.  E.g. <kbd>Alt+~</kbd> also works in Python repl using readline, although it makes little sense there...)

**Comment by tmewett** [comment]
Came to the github just now to suggest this! Actually, I was going to suggest an interactive 'preview' for globs when attempting to tab-complete them. But I think expanding inline is more flexible as it allows filtering and further editing, too

**Comment by faho** [comment]
This is now possible in master with `commandline --tokens-expanded`:

```fish
bind ctrl-alt-e 'commandline -rt -- (commandline -xt | string escape | string join " ")'
```

This will not run command substitutions, which is a safety measure. If you want that, use `eval`.

I believe that's everything done, so I'm closing this.

**Comment by avindra** [comment]
Built upon [@dag's](https://github.com/fish-shell/fish-shell/issues/751#issuecomment-18058960)  solution:

```fish
function __fish_list
    for item in $argv
        echo $item | sed -e 's/ /\\\\ /g'
    end
end

# Expand tokens upon CTRL-ALT-E (i.e., as in Bash)
#
# ref1: https://github.com/fish-shell/fish-shell/issues/751#issuecomment-18058960
# ref2: https://github.com/fish-shell/fish-shell/issues/751#issuecomment-2282787121
function bind_expand_all
    set -l tokens (commandline --tokens-expanded)
    if test -n "$tokens"

        set -l value (eval __fish_list $tokens | tr \n ' ')

        if test -n "$value" -a "$value" != ' '
            set pos (math "1+" (commandline --cursor))
            commandline -r $value

            # restore cursor position
            commandline --cursor $pos
            commandline -f backward-char
        end
    end
end

bind ctrl-alt-e bind_expand_all
```

https://github.com/avindra/dotfiles/blob/8ad2e50663fd2393fccad06648095bb9c9ab6127/.config/fish/config.fish#L234C1-L261C32

If my line is:

```fish
ls (which sed) (which ls) (which mv)
```

then running the function expands it to

```
ls /usr/bin/sed /usr/bin/ls /usr/bin/mv
```

however, it doesn't work when trying to expand output from python (or node)

```sh
echo (python3 -c "print(2)")

echo (node -e 'console.log(2)')

# both of these throw an `Unknown command` error
```

any suggestions to make it work for the node/python example?

**Comment by ridiculousfish** [comment]
@avindra just replacing `--tokens-expanded` with `--tokens-raw` should do what you want.

```
function bind_expand_all
    set -l tokens (commandline --tokens-raw)
    if test -n "$tokens"
        #set --show tokens 2>&1

        set -l value (eval __fish_list $tokens | tr \n ' ')

        if test -n "$value" -a "$value" != ' '
            set pos (math "1+" (commandline --cursor))
            commandline -r $value

            # restore cursor position
            commandline --cursor $pos
            commandline -f backward-char
        end
    end
end
```

**Comment by krobelus** [comment]
> function bind_expand_all
>     set -l tokens (commandline --tokens-raw)

commandline --tokens-raw is deprecated (it has confusing semantics
and should have never been added), and it's unnecessary: a simple
"(commandline)" does the same thing here.

(but it's also affected by various issues with this functions, it
will break on multiline or composite commands)
