### ISSUE TITLE
Pasting an emoji character results in a visual duplication artefact

### ISSUE THREAD

**Issue by dnicolson** [fish-shell/fish-shell#7510]
Pasting an emoji character such as "ℹ️" will result in what appears to be two overlapping characters but only one character is written:

![PixelSnap 2020-11-26 at 17 38 19@2x](https://user-images.githubusercontent.com/2276355/100375514-31510200-300e-11eb-9f30-503c8c5ac956.png)

The problem exists in 3.1.2 and appears to have been introduced in 3.0.0, version 2.7.1 is not affected.

The issue has been reproduced with version 3.1.2 in the following environments:
macOS Big Sur v11.0.1 (20B29)
Linux ubuntu-512mb-fra1-01 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by faho** [comment]
From [the FAQ](https://github.com/fish-shell/fish-shell/blob/master/doc_src/faq.rst#im-getting-weird-graphical-glitches-a-staircase-effect-ghost-characters):

In a terminal, the application running inside it and the terminal itself need to agree on the width of characters in order to handle cursor movement.

This is more important to fish than other shells because features like syntax highlighting and autosuggestions are implemented by moving the cursor.

Sometimes, there is disagreement on the width. There are numerous causes and fixes for this:

    It is possible the character is simply too new for your system to know - in this case you need to refrain from using it.
    Fish or your terminal might not know about the character or handle it wrong - in this case fish or your terminal needs to be fixed, or you need to update to a fixed version.
    The character has an "ambiguous" width and fish thinks that means a width of X while your terminal thinks it's Y. In this case you either need to change your terminal's configuration or set $fish_ambiguous_width to the correct value.
    The character is an emoji and the host system only supports Unicode 8, while you are running the terminal on a system that uses Unicode >= 9. In this case set $fish_emoji_width to 2.


In this particular case :information_source:  is an actual official emoji, so you need to do the $fish_emoji_width thing.

This has been spruced up in various ways for 3.2.0 (including a limited form of autodetection).

**Comment by dnicolson** [comment]
Setting `$fish_emoji_width` to 2 or any other value did not seem to have any effect. On both macOS and Linux `LC_ALL` is `en_US.UTF-8`. The problem also exists with version `3.1.2-1668-ga14e64ed6`.

Including a space after the emoji ("ℹ️ ") doesn't cause the problem.

**Comment by faho** [comment]
>Including a space after the emoji ("information_source ") doesn't cause the problem.

If a space after the thing is enough to fix it, then that means the terminal is trying to *draw* it two-wide, but only reserves one cell. In that case I can't see fish having any effect at all - it does not influence how the terminal renders things. 

My advice? Pick a different character or font and spare yourself the trouble.

**Comment by dnicolson** [comment]
> If a space after the thing is enough to fix it, then that means the terminal is trying to _draw_ it two-wide, but only reserves one cell. In that case I can't see fish having any effect at all - it does not influence how the terminal renders things.

This is the result of pasting "echo ℹ️ " in iTerm 3.4.2beta3 ([asciinema](https://asciinema.org/a/TxJKm0Ubx6GbBSMSm2xyjotpY)):

![100392196-0da1b200-3036-11eb-9ad4-28aa3856e0df](https://user-images.githubusercontent.com/2276355/100398737-46e71b80-3050-11eb-819e-8234f4cd29b9.gif)

![100392192-0b3f5800-3036-11eb-921e-52d01a9b6acb](https://user-images.githubusercontent.com/2276355/100398739-48b0df00-3050-11eb-848a-7af83a5cd3af.gif)

**Comment by faho** [comment]
So, U+2139 (INFORMATION SOURCE) is *narrow* according to the unicode [east asian width table](http://www.unicode.org/reports/tr11/).

That means it should be drawn as 1-cell wide, and that's what fish expects. It's possible to use a variation selector to select emoji presentation, but fish handles that since 28455235b11524c094383097538fb56a3c2e4b4a, so it doesn't seem like you're using one here.

iTerm (or whatever that is using) is rendering the character as 2-wide (you can see it being as wide as the "t" and "e" above it), and that's wrong.

**Comment by zanchey** [comment]
[U+2139](https://www.fileformat.info/info/unicode/char/2139/index.htm) on its own is different to U+2139 [U+fe0f](https://www.fileformat.info/info/unicode/char/fe0f/index.htm) though - it should be treated as 2-wide with the width selector.

Anyway it's wrong in both Terminal.app and Chrome (excitingly) on my Mac so who knows what's happening here. I think picking a different character is extremely wise.

Here's how it looks in Chrome from the OP: ![Chrome display](https://user-images.githubusercontent.com/520741/100516139-bbd76400-31bc-11eb-9534-c81fd6486b46.png)
