### ISSUE TITLE
fish_config: No module named 'distutils.spawn'

### ISSUE THREAD

**Issue by Natsurii** [fish-shell/fish-shell#7514]
I was trying to setup fish on fresh install of Raspbian OS 32bit on RPi4.
Running `fish_config` threw a Python web error:
`Traceback (most recent call last):
  File "/usr/share/fish/tools/web_config/webconfig.py", line 11, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils.spawn' `

This behaviour also shows on `sh -c 'env HOME=$(mktemp -d) fish'`

Here is some technical details.
$ fish --version 
fish, version 3.1.2

$ uname -a
Linux raspberrypi 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux

$ echo $TERM 
xterm-256color

$python3 --version
Python 3.7.3

**Comment by mqudsi** [comment]
What method did you use to install fish?

**Comment by zanchey** [comment]
[Debian packages don't install `distutils` by default](https://stackoverflow.com/a/61944585/125549), so you need to `apt install python3-distutils`.

Either we should add a dependency to the Debian packages or drop the use of `distutils`.

**Comment by faho** [comment]
We use distutils for two really rather small things:

- Checking if `termux-open-url` exists (via distutils.spawn.find_executable, which we explain elsewhere is *quite bad* and fails to check that the path is executable!)

- Checking if the macOS version is >= 10.12.5 via distutils.LooseVersion

I'm just going to remove the former - we already check if $PATH includes a path with "com.termux" in it. If it turns out it's needed we can reuse the path checking we do elsewhere already.

The latter I'd replace with:

```python
import platform

def isMacOS10_12_5_OrLater():
    """ Return whether this system is macOS 10.12.5 or a later version. """
    try:
        version = [int(x) for x in platform.mac_ver()[0].split(".")]
        if version[0] < 10: return False
        if version[0] > 10: return True
        if version[1] < 12: return False
        if version[1] > 12: return True
        if version[2] < 5: return False
        return True
    except:
        return False
```

If anyone on macOS could confirm this is working that'd be grand.

**Comment by zanchey** [comment]
I think you can just compare the version elements as a list directly:

```python
def isMacOS10_12_5_OrLater():
    return [int(x) for x in platform.mac_ver()[0].split(".")] >= [10, 14, 5]
```

**Comment by faho** [comment]
Oooh, that's cool. I'd have thought that does a simple pair-wise comparison, which would fail e.g. on 10.13.4, but it turns out it does a "compare as long as they're equal" thing.

It still needs a try/catch for when there's no mac_ver() to give because it's not a mac, but otherwise, yeah, that should work. As long as apple doesn't start giving version numbers in song instead, that is.

**Comment by faho** [comment]
Alright, let's just do it.

@zanchey I'm assuming we can drop the python3-distutils recommends from debian/control now?

**Comment by zanchey** [comment]
> @zanchey I'm assuming we can drop the python3-distutils recommends from debian/control now?

done in f396a4328

**Comment by floam** [comment]
> It still needs a try/catch for when there's no mac_ver() to give because it's not a mac, but otherwise, yeah, that should work. As long as apple doesn't start giving version numbers in song instead, that is.

I think mac_ver() exists everywhere.

**Comment by faho** [comment]
>I think mac_ver() exists everywhere.

1. It exists but returns a list of empty strings, so we'd have to fiddle around it
2. This was already fixed in 9de809ee9829cc9e519129a52e1607a34ad589f5 by just catching the exception and returning False

**Comment by floam** [comment]
Comment just left because I was going over that code: I believe the right exception to catch is ValueError, basically everywhere, right?

**Comment by faho** [comment]
The error you get on a non-mac system is:

> ValueError: invalid literal for int() with base 10: ''
