### ISSUE TITLE
fish's behavior with LS_COLORS unset is misleading

### ISSUE THREAD

**Issue by ericonr** [fish-shell/fish-shell#7518]
fish, versão 3.1.2-1615-ge6cdd315d

`echo $LS_COLORS` -> empty

You can see the issue here: https://asciinema.org/a/ncH6EBQdBWL7gH6tCKSJIDkFS

Basically, it seems to be a bad interaction between GNU `ls` and how fish interprets its output. With `LS_COLORS` empty, `ls` will show a color that's usually used for valid symlinks on invalid ones, which kind of sucks already, but then `fish` also puts the `@` (normally used for valid symlinks) in front of the symlink, which is quite confusing.

Switching to bash to source `/etc/profile` made it all go back to normal, but I'm opening this issue to see if a (cheap and simple) workaround could be implemented.

**Comment by faho** [comment]
>Basically, it seems to be a bad interaction between GNU ls and how fish interprets its output. 

Fish does not interpret `ls` output. It just wraps `ls` by default to pass some arguments, including `--color=auto` and `-F` ("classify").

If that adds an `@`, then that's apparently because it was a symlink, and because `ls` classifies like that.

If you wish to pass different options to `ls`, make your own ls function/alias or create an empty file at ~/.config/fish/functions/ls.fish to mask the function entirely.

**Comment by ericonr** [comment]
Well, those seem like somewhat weird defaults.

Thank you for clearing this up! (and for the tips :) )
