### ISSUE TITLE
Complete multiple command parameter completion at once

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [fish-shell/fish-shell#7525]
fish: version 3.1.2
os:ubuntu 18 

I have some commonly used commands, such as "commond  -s file1 -d file2 ". But I don't want to achieve it by pressing'tab' several times, but I wrote the script commond.fish as follows

```bash
complete -c commond -x  -d "a test" -a "   ' -s file1 -d file2'    ' -w file1 -d file2'    "
```
 After fish treatment
```bash
commond  -s file1\ -d file2
```
How to delete this symbol '\'?

In addition, can I realize that the cursor will automatically jump to the offset of file1, file2 after completion? (so that I no need manually move the cursor to modify the file1, file2 characters)

thanks!

**Comment by faho** [comment]
This is currently not supported and I don't see a clean way for doing so (how would you specify that it's two separate tokens and not either one of the two or one long token?), or a real use case - usually when you have two tokens, that's because the second token can be one of several things. Else why require the second? 

Sorry!

**Comment by YU5Z8X2CvH1fv4ep** [comment]
Sorry, there may be a problem with my description. The md format does not correctly display the symbol "\" I said. I want to remove the escape character "\" for spaces. Is there a way to do it?

**Comment by faho** [comment]
Oh, no, I understood what you said.

What happens here is that fish takes everything you give it as a completion candidate as *one "word"*.

So when you e.g. give it filenames to complete, and you pass `filename with spaces`, it will think that's one thing, and insert it as `filename\ with\ spaces`.

There is no way around this. We would have to add a feature to somehow allow you to mark something as "this is multiple words", and then insert them separately. We'd also have to display them differently in the completion pager (the menu where you select the completions).

What I was saying is that I don't think that's a feature we should add. This is because I can't think of a nice way to unambiguously mark things, because it would require some delicate work on the pager and because I don't think it's very useful or often needed - if a command expects two words, that's typically because it needs the information from both.

If you need a way to enter less, use abbreviations or functions or variables, depending on what you want to do exactly.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> 哦，不，我明白你的意思。
> 
> 这里发生的是，鱼将您作为补全候选者提供的所有内容都当作_一个“单词”_。
> 
> 因此，当您给它提供文件名以完成并传递时`filename with spaces`，它会认为这是一回事，并将其插入为`filename\ with\ spaces`。
> 
> 这没有办法。我们将不得不添加一项功能，以某种方式允许您将某些内容标记为“这是多个单词”，然后分别插入它们。我们还必须在完成页面程序（您在其中选择完成内容的菜单）中以不同方式显示它们。
> 
> 我的意思是，我认为这不是我们应该添加的功能。这是因为我想不出一种清楚地标记事物的好方法，因为这将需要在寻呼机上做一些细致的工作，并且因为我认为这不是很有用或不需要的-如果命令需要两个单词，通常因为它需要来自两者的信息。
> 
> 如果您需要一种输入更少内容的方法，请使用缩写词，函数或变量，具体取决于要执行的操作。

ok.thanks!
