### ISSUE TITLE
Question- busybox links not for use in fish?

### ISSUE THREAD

**Issue by 62f** [fish-shell/fish-shell#7537]
https://github.com/ish-app/ish/issues/1088

**Comment by faho** [comment]
What seems to happen here is that bash et al will try to start a file without a shebang with /bin/sh, which fish won't do. The solution is to add a proper shebang.

**Comment by 62f** [comment]
But busybox applets are nothing but ln -s, not even real files, and there are about two hundred of those, and editing a binary such as busybox, for instance with ed, to insert this "proper /bin/sh initialization" for such a file in the past has either crashed or left the system in an unbootable state. Not to mention that neither vi nor ed are usable because they're part of the uncooperative busybox. So where does the magic incantation go, and how did it vanish? I've tried multiple times reloading and unloading both busybox and fish using the apk package manager to no avail- it seems that doing such should have restored the former functionality, but NO. Of course not.
What fool am I to expect such a miracle to fall upon me...

**Comment by 62f** [comment]
I would hazard an educated guess that every 'heavily-typed' call to one of these improper busybox applet links would need a #! plus possibly the explicit pathname before each applet's name in every command. That would require a splendidly-acute awareness of which commands those were, which I decided absolutely NOT to task myself to learn 200 more associations, so I tried your alternate method: relinking one of them (less) 
# Pandemonium immediately ensued.
Use of that new system link somehow spontaneously ruined the busybox binary itself and rendered the OS unusable, then crashed it, and voila, it's unbootable. I attempted to rescue the system before it was too late by `exit` from fish, but evidently exit ALSO is a busybox applet, so of course exit failed. I've just been asked to try to send a dd/compressed copy of this ko'd partition in to the lab for forensic analysis.

**Comment by faho** [comment]
>But busybox applets are nothing but ln -s, not even real files

Correct, they aren't. Busybox applets are simply code in the busybox binary itself, and busybox decides what to execute by looking at the name it's been invoked as (its argv[0]).

So when you call `busybox` it'll allow you to pass a name, when you copy busybox and call the copy "rm" it'll behave like "rm", when you call a link named "less" to busybox it will start the "less" applet. In your case you don't have symlinks - like [busybox upstream recommends](https://busybox.net/FAQ.html#getting_started), but scripts that are written in such a way that they start busybox with that name.

Really links are *simpler* and *smaller* and *better*. Use them.

As to the crashes: This looks like you did something wrong, e.g. making "busybox" the link to "less" instead of the other way around. I'm afraid I can't be of much assistance here because I don't have the right context or a device to execute ish on.

**Comment by 62f** [comment]
Alpine is smart in that regard: I have tried every way I could think of to make those reverse links, & each attempt fails with "file already exists". The problem I'm having though is with iSH itself. If that wasn't the case I would not be posting this: knowing I had a defective busybox binary, I tried replacing it with another from a working clone of the filesystem. To my dismay, the replacement does not function at all. I am supposing that it must be due to mismatched file permissions, as both binaries claim to be of identical size. This isn't the first problem I've had with file permissions in a musl environment, I've watched other binaries overstep the user permissions and literally eradicate bits of files, once leaving nothing of a intact except its name entered into the file table.
