### ISSUE TITLE
Nitpick: prompt_pwd function name

### ISSUE THREAD

**Issue by dag** [fish-shell/fish-shell#755]
It seems in fish things are either builtins, or meant to be used on the commandline or commonly in scripts, or prefixed with `fish_`, or with `__fish_`.  `prompt_pwd` seems to be the one exception.

**Comment by faho** [comment]
I can't speak for anyone else, but I'd like to have functions and variables without dunderscore ("__") to be customization points. `prompt_pwd` for example can be exchanged by the user if they feel the need, while I wouldn't want them changing __fish_sysconfdir (outside of building, of course) or __fish_abbr_get_by_key, and I don't think users care about __fish_complete_users all that much - that thing should just work and not clutter up sensible names (though local functions would help a bunch for all those completion functions).

Because of that, and because prompt_pwd is now documented, I'm closing this.
