### ISSUE TITLE
Not picking up binary in $PATH.

### ISSUE THREAD

**Issue by bentinata** [fish-shell/fish-shell#7568]
```
fish, version 3.1.2
Linux 5.9.14-arch1-1
xterm-256color
```

I have set PATH using `~/.pam_environment` and it's applied into the shell, but `fish` complain unknown command. I'm pretty sure this worked fine before. `which` fail when using `sh -c 'env HOME=$(mktemp -d) fish'`.

https://asciinema.org/a/380408

**Comment by faho** [comment]
Your $PATH includes a directory called `~/.local/bin/`, but it's **a literal ~**. `which` (which is an external command that's basically useless - use `command -v` instead) will expand the `~` to $HOME, which is why the second one fails - at that point $HOME/.local/bin/serve isn't the correct path anymore because $HOME is a temp directory.

Really, ideally your system would be expanding that "~", it appears to not be. #6641 asks for fish to do that.

The obvious workaround is for you not use `~` here, or to use $fish_user_paths - just run

```fish
set -U fish_user_paths ~/.bin ~/.local/bin
```

once interactively and it'll be done.

**Comment by bentinata** [comment]
For anyone who's stumbled here, and just like me, prefer using `pam_env.conf(5)` and doesn't want to update using `$fish_user_paths`. You can use `@{HOME}`. Not really pretty, but not really hardcoding your username. :grin:

```
# ~/.pam_environment
PATH  DEFAULT=@{HOME}/bin:@{HOME}/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin
```
