### ISSUE TITLE
vi-mode hang on iTerm2

### ISSUE THREAD

**Issue by ihomway** [fish-shell/fish-shell#7573]
```sh
$ fish --version
fish, version 3.1.2

$ env | grep TERM_PROGRAM
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.4.3

$ echo $__fish_sysconf_dir
/opt/homebrew/Cellar/fish/3.1.2/etc/fish

$echo $__fish_config_dir
/Users/puer/.config/fish

$ lipo -info (status fish-path)
Non-fat file: /opt/homebrew/bin/fish is architecture: arm64
```

I'm trying to turn vi-mode on, which I did was to add the `fish_user_key_bindings` function, it looks like:

```sh
function fish_user_key_bindings
  fish_vi_key_bindings
end
```

After save this function and reopen my terminal (iTerm2), it just stuck on the "I" mode, no response when I pressed any keys (include the `esc`). When I switch to the Terminal.app, I can type in now, but its response was very slowly.

On iTerm2 👇
<img width="536" alt="Screen Shot 2020-12-23 at 6 09 59 PM" src="https://user-images.githubusercontent.com/9472797/102985432-1fe61180-454a-11eb-9873-5781274ac53c.png">

**Comment by ihomway** [comment]
I'm working on Apple Silicon.

**Comment by faho** [comment]
>I'm trying to turn vi-mode on, which I did was to add the fish_user_key_bindings function, it looks like:

That's not it. Just put `fish_vi_key_bindings` into config.fish, no need for `fish_user_key_bindings`.

**Comment by ihomway** [comment]
This is my fish config, which path is `~/.config/fish/config.fish`
```sh
set -g fish_user_paths "/opt/homebrew/bin" $fish_user_paths

status --is-interactive; and source (rbenv init -|psub)

fish_vi_key_bindings
```

I had added the `fish_vi_key_bindings ` in `config.fish`, it's not work, there is no "I" in the front of the command line.
And here is what `set --show fish_key_bindings`
```sh
$fish_key_bindings: not set in local scope
$fish_key_bindings: not set in global scope
$fish_key_bindings: set in universal scope, unexported, with 1 elements
$fish_key_bindings[1]: length=25 value=|fish_default_key_bindings|
```

I install fish via Installer at the very begging since brew will install the x86 one. 
Recently I reinstall my brew via the arm64 way, and then reinstall fish via brew.
So is there any possibility because I had a Installer-version installed before install fish via brew?

**Comment by faho** [comment]
>I had added the fish_vi_key_bindings in config.fish, it's not work, there is no "I" in the front of the command line.

If that doesn't work, then that's most likely because something keeps changing it *back*. Which would also explain why adding it to fish_user_key_bindings breaks stuff - then fish will spin in circles changing keybindings back and forth.

Given that your prompt is not one of ours and I'm pretty sure it's one of the oh-my-fish ones, I'd check there.

`functions --handlers` can tell you if anything registered as a variable handler for fish_key_bindings - it should only be `__fish_reload_key_bindings` and `__fish_repaint`, but basically anything could be fiddling with this.

**Comment by ihomway** [comment]
This is what `functions --handlers` output,
```
Event signal
SIGTRAP fish_sigtrap_handler
SIGWINCH __fish_winch_handler

Event variable
fish_color_cwd __fish_repaint
fish_color_cwd_root __fish_repaint
fish_color_host __fish_repaint
fish_color_status __fish_repaint
fish_color_user __fish_repaint
fish_key_bindings __fish_repaint
fish_key_bindings __fish_reload_key_bindings
fish_user_paths __fish_reconstruct_path

Event generic
fish_command_not_found __fish_command_not_found_handler
fish_exit __fish_disable_bracketed_paste
fish_preexec __fish_disable_bracketed_paste
fish_prompt __fish_enable_bracketed_paste
```

-------

I didn't have the `oh-my-fish` installed, and did you mean the `[I]` and `[N]` prompt are not set by fish?

**Comment by faho** [comment]
>I didn't have the oh-my-fish installed, and did you mean the [I] and [N] prompt are not set by fish?

No, the `[I]` and `[N]` thing is fish's `fish_mode_prompt`. It's a separate function.

I just noticed that we ship a prompt with `⤑ ~` - it's the "robbyrussell" prompt. Sorry!

-------

Anyway, since executing `fish_vi_key_bindings` should change $fish_key_bindings, and it ends up as `fish_default_key_bindings` again, *something* must be changing it back, so I'd double check your configuration.

Something like

```fish
grep 'fish_.*key_bindings' -r ~/.config/fish/
```

should show you where a binding function is executed or $fish_key_bindings is changed.

Of course also check that you really added `fish_vi_key_bindings` in a place that is executed, and not e.g. inside an `if status is-login` block when your shell isn't a login shell (tho IIRC on macOS it typically is).

**Comment by ihomway** [comment]
The output is:
```she
/Users/puer/.config/fish//config.fish:# fish_vi_key_bindings
/Users/puer/.config/fish//fish_variables:SETUVAR fish_key_bindings:fish_default_key_bindings
```

-------

By the way, I tried to input `fish_vi_key_bindings` in terminal, I found that the `fish_vi_key_bindings` function will be called twice (I think this is a expected behavior), and all after that the `fish_default_key_bindings`  will called.

**Comment by faho** [comment]
Okay, as a guess, try

```fish
set -g fish_key_bindings fish_vi_key_bindings
```

**Comment by ihomway** [comment]
Works 🎉🎉🎉🎉

I still confused why this happened? I don't remember I have set this `fish_key_bindings` to` fish_default_key_bindings` before.

Thank you so much for helping me to solve this problem.

**Comment by ihomway** [comment]
I found this solution only work in current session. If I restart shell, the key binding will be reset to `fish_default_key_bindings`, `set -u fish_key_bindings fish_vi_key_bindings` not works.

**Comment by faho** [comment]
>I found this solution only work in current session

Yes, it's a *global* variable. Those are only valid in the current session.

It'll probably work if you put that `set -g` into config.fish.

>set -u fish_key_bindings fish_vi_key_bindings not works.

Careful, this is case-sensitive! `set -u` will "unexport" a variable - it's the inverse of `set -x`.

You want a *universal* variable, and those are set with `set -U`.

It would be great if you could try

```fish
set -U fish_key_bindings fish_vi_key_bindings
```

and report back. I'm assuming something about universal variables is broken in 3.1.2 with your macOS version, so I'm expecting this to not work.

It's possibly already fixed in git. @ridiculousfish would know more.

**Comment by ihomway** [comment]
I add an `echo "$fish_key_bindings"` command in `__fish_config_interactive.fish`, just before `if not functions -q "$fish_key_bindings"`(line 190). And then I executed `set -U fish_key_bindings fish_vi_key_bindings`, it output:
```sh
fish_vi_key_bindings
fish_default_key_bindings
```

It seems like the `fish_key_bindings ` still be over written.

**Comment by faho** [comment]
Well, that means one of a few things:

- Your fish is somehow re-reading the universal variable file instead of writing the universal variable to it (this could happen e.g. if fish didn't have the right permissions for it, but also if fish 3.1.2 had problems on your version of macOS)
- Your fish_user_key_bindings resets it
- Your fish_vi_key_bindings function has been altered and resets it
- Some other thing resets it

Honestly, I'm assuming it's the first.

**Comment by ihomway** [comment]
I agree with you. I tried to install another copy of fish via the official Install Application, and then switch to the new copy to be the default shell, and everything goes well.

So I think this issue maybe relate to brew of the installed location.

The new copy, which installed via Installed, located at `/usr/local/bin/fish`, 
the old one, which installed via brew, located at `/opt/homebrew/bin/fish`.

**Comment by ihomway** [comment]
I add write permission of `/opt`, problem fixed.
Just like you said, it's a permission issue.

Finally, I can say this problem is fixed 🎉🎉🎉🎉

**Comment by ihomway** [comment]
Thank you again, and I think this issue can be closed now.

**Comment by faho** [comment]
I'm quite confused by why that didn't error out, actually.

In my tests it does - "error: Unable to open temporary file".

You wouldn't happen to know what was wrong with the permissions exactly?

**Comment by ihomway** [comment]
All I got was when the `/opt`'s permissions are like this:
```sh
drwxr-xr-x   3 root  wheel    96 Dec 21 15:33 opt/
```
this problem happened, after I add group write permissions:
```sh
drwxrwxr-x   3 root  wheel    96 Dec 21 15:33 opt/
```
the problem was gone.

**Comment by faho** [comment]
This is weird?

- This is using /opt, which is weird to begin with - it should be $XDG_CONFIG_HOME/fish (or ~/.config/fish if that isn't set), so presumably your $XDG_CONFIG_HOME or $HOME is set to point there
- When I remove write permissions to my ~/.config/fish, I get a proper error, and I don't get fish re-reading the universal variable file - the updated values stay and are used, so this entire thing doesn't happen

Anyway, the most likely root cause seems to be macOS-specific and I don't have that, so if somebody wants to see what's up here, be my guest.

**Comment by ihomway** [comment]
That's because I'm using the M1(Apple Silicon), `brew` is installed at `/opt/homebrew/bin/brew` (as brew suggests
[*/opt/homebrew on macOS ARM*](https://docs.brew.sh/Installation)), so `fish` is installed at `/opt/homebrew/Cellar/fish/3.1.2/bin/fish`. And `fish`'s configuration is still under $HOME.

```sh
$ ls -l ~/.config/fish/
total 48
drwxr-xr-x   3 puer  staff     96 Dec 24 17:43 completions/
drwxr-xr-x   3 puer  staff     96 Dec 24 17:43 conf.d/
-rw-r--r--   1 puer  staff    675 Dec 25 19:24 config.fish
-rw-r--r--   1 puer  staff     41 Dec 24 17:43 fish_plugins
-rw-r--r--   1 puer  staff  12512 Dec 25 18:55 fish_variables
drwxr-xr-x  34 puer  staff   1088 Dec 24 18:51 functions/
```

**Comment by faho** [comment]
> fish is installed at /opt/homebrew/Cellar/fish/3.1.2/bin/fish.

Yeah, but where the fish binary is shouldn't matter, it shouldn't be writing there?

The universal variables file I was talking about is that "fish_variables" in ~/.config/fish. *That directory* should be writable (not the file - we replace the entire file, so the directory's write permissions apply), /opt shouldn't matter one bit.
