### ISSUE TITLE
cd relies on stat(3), which on buggy filesystems may fail even if a directory exists

### ISSUE THREAD

**Issue by fabh2o** [fish-shell/fish-shell#7577]
The linux system call `stat()` (stat(3) in linux man page) can return < 0 when invoked over a file or directory that reside in a not properly  configured filesystem (observed in misconfigured permission on fuse).
In that case `stat()` fail even if a directory exists, so `cd`ing to those directories fails and file/folder autocompletion (and probably every time fish use `stat()` in the filesystem) fails as well.
As reported and tested on gitter, `access()` apparently works, as does actually changing the directory.
The following [branch](https://github.com/faho/fish-shell/tree/cd-error2) solves the `cd` problem, but there is still work to do to get autocompletion to properly work.

**Comment by faho** [comment]
Yeah, the solution here is probably to just *try* `chdir(3)` without checking first, and only later figuring out why it errored exactly.

The linked branch opens directories, which I'm not quite comfortable with. Also note that this won't fix syntax highlighting or autocompletion, because we don't want to open directories for those either, but it's probably okay given that the underlying filesystem is buggy, so we really have no other choice.
