### ISSUE TITLE
normalize and document __fish_status_to_signal 

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7595]
I think that this is a case exactly like `prompt_pwd`, where Fish can offer a convenient service for those creating a prompt. I [currently use](https://github.com/IlanCosman/tide/blob/main/functions/_tide_item_status.fish#L20) this undocumented function in my prompt, Tide (well technically i'm using `__fish_pipestatus_with_signal` because this is before 293a3a628d6d5d6220518e3991e989b38cf50c8e is released).

**Comment by IlanCosman** [comment]
Does the `fish-future` tag mean that the idea is accepted @faho? I'm happy to open a PR if that is the case.

**Comment by faho** [comment]
>Does the fish-future tag mean that the idea is accepted @faho? I'm happy to open a PR if that is the case.

"fish-future" means that it's something we'll add in "the future" - whenever that is. So it is accepted, yeah.

In contrast "fish-X.Y" means we'd like to work on it in that cycle, if possible, and "next-major" means it'll have to wait for the next major release - whenever that is. I didn't tag it as fish-3.2.0 because I don't think this should hold up the 3.2.0  release at this point.
