### ISSUE TITLE
[Question/feature request] Change completion pager keybinds to vi keybinds

### ISSUE THREAD

**Issue by toniz4** [fish-shell/fish-shell#7598]
fish, version 3.0.2

It's possible to change the pager completion keybinds to vi keybinds? So up h would be left, j down, etc..

**Comment by faho** [comment]
They already are, when you're in normal mode. In insert mode anything you're typing is, well, inserted, so moving doesn't seem like the correct thing to do.

>fish, version 3.0.2

That version is a bit out of date, you'll want to upgrade to 3.1.2 - some of this changed there. We have some PPAs for a variety of distributions, you can find them on https://fishshell.com/.

**Comment by toniz4** [comment]
Got it, thanks!

**Comment by toniz4** [comment]
Sorry for reopening this, i could not adapt with this keybinds. There is any way to enter normal mode when opening the completion pager?

**Comment by faho** [comment]
There is not.

If you're *in* normal mode you can navigate the pager with hjkl, but because entering normal mode goes back a character (for some reason that's what vi does) that's a bit annoying.

Instead you'd do something like

```fish
bind -M insert j 'commandline -P; and down-or-search; or commandline -i j'
bind -M insert k 'commandline -P; and up-or-search; or commandline -i k'
```

to bind j/k to move in the pager from *insert* mode as well. Similar for h/l.

**Comment by toniz4** [comment]
That works as intended. Thanks!

**Comment by lyonelz96** [comment]
@faho I was looking for something like this, thanks!
@toniz4 One thing to note is if you use the search at all these bindings will make it break (You won't be able to type hjkl)

**Comment by maybebyte** [comment]
I found the character insertion behavior to be a little counterintuitive with CTRL-J, CTRL-H, and CTRL-L because those normally cause fish to execute the current line, delete the previous character, or clear the screen. Here's the version I use that replicates this behavior.

```
bind -M insert \cj 'commandline -P; and down-or-search; or commandline -f execute'
bind -M insert \ck 'commandline -P; and up-or-search'
bind -M insert \ch 'commandline -P; and commandline -f backward-char; or commandline -f backward-delete-char'
bind -M insert \cl 'commandline -P; and commandline -f forward-char; or commandline -f clear-screen'
```

I think the proper fix that'd benefit everyone might be to disable vim bindings in fish when searching inside the pager and pass through through the keys, then reactivate them after the selection has been made. Then holding down control as a workaround would be unnecessary. But I'm not sure how to do this yet.
