### ISSUE TITLE
add pipefail

### ISSUE THREAD

**Issue by aeosynth** [fish-shell/fish-shell#763]
http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

> If pipefail is enabled, the pipeline’s return status is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands exit successfully.

this would make `set` even easier to work with:

```
if set foo (false | bar)
```

**Comment by kballard** [comment]
I don't think we should make `pipefail` the default. For example, the command `yes | head -10` exits with code `0`, but with `pipefail` it exits with code `141` (due to `SIGPIPE`). More generally, tools like `head` that consume part of their input and then exit would report failure if the program providing the input tries to write any more data. This includes `less` (which doesn't read all its input if you quit early) and other pagers.

Since this behavior is something that you'd really only want to use on specific pipelines, it seems like we should instead just have a syntax to request that a particular pipeline should evaluate to the `and` of the component jobs (instead of the default `or`). Some variation on the normal pipe operator (`|`). If we used `&&` then I'd suggest `|&&` but we don't use that. I'm actually tempted to say we should just support `foo | and bar` for this behavior.

**Comment by ridiculousfish** [comment]
Very good point @ kballard. I hate to introduce more syntax like `|&&`, but the `foo | and bar` idea is kind of amazing!

**Comment by maxnordlund** [comment]
I also like the ` foo | and bar` syntax, feels most natural to me. It kinda mirrors `foo; and bar` but also pipes the output from `foo` to `bar`. Then `foo | bar` would be the same as `foo | or bar`.

**Comment by ohspite** [comment]
To me, the `foo | and bar` syntax implies that `bar` will only be run if `foo` exits with status 0. Sort of similar to `foo | ifne bar`.  This is different than `pipefail` behavior where all commands are run in a pipeline, possibly simultaneously, and only the exit status of the pipeline potentially changes.  

Also, would you have to type it after every pipe, and what happens if you don't?
```
foo | and bar | and baz | and qux
# vs
foo | and bar | baz | and qux
```

Rather than changing the behavior of pipes with a `pipefail` variable, the leftmost nonzero status could just always be recorded in a new variable similar to `status`.  I can't think of a very good name, but something like `status_pipefail` or `status_all`.

**Comment by cben** [comment]
1. Are there any common cases except SIGPIPE where left command failing is "normal"?
   I'm not sure I'd seriously propose a definition of "rightmost non-0 that didn't die from SIGPIPE" but it might just be very convenient.

2. Is `yes | head` returning non-0 actually bad?  It's obviously a problem in strict mode (#805) but otherwise, why would I care?

  OK, here is one case: `find | grep -q '~$'; and echo "Backup files found."`.  grep -q exits as soon as it sees one match, causing SIGPIPE (unless find exits quickly, it's a race).  But the purpose was to check only grep's status.

OTOH consider `if ls $DIR | not grep -q '~$'; echo "Definitely no backup files."; end`: if you don't have permission to read $DIR, ls errors out and in this case it'd be wrong to claim "Definitely no backup files".
So the exact purpose — test last command or all — depends on the use case.
IMHO, testing all commands (i.e. pipefail) would be a saner default (if compatibility weren't a concern).

**Comment by krader1961** [comment]
Closing because we don't want to add a pipefail option ala bash and can't change the current behavior. Also, something like $pipestatus as discussed in issue #2039 is more flexible and a helper function could be provided to return zero if all commands in the pipeline exited successfully or the rightmost non-zero status.
