### ISSUE TITLE
bind prints raw control characters when no slash-escape exists for it

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#7631]
The default set of binds includes a binding on the `del` control character.

https://github.com/fish-shell/fish-shell/blob/a4f5dd50544b20b8af1097d13eb091fe7ca35c52/share/functions/fish_default_key_bindings.fish#L62

But when you ask `bind` to then print its bindings, it just prints the `del` control character raw:

```
bind --preset -k backspace backward-delete-char
bind --preset  backward-delete-char
bind --preset -k sdc backward-delete-char
```

(piping that into `less` will show the control character as a highlighted `^?`)

`bind` should instead show any non-printable character as a hex or unicode escape, if there's no key name for it. Though in this particular case maybe it should just show it as `\c?`, which is a bit confusing and generally can't be typed but is technically accurate.

fish, version 3.1.2

**Comment by faho** [comment]
`bind` calls `escape_string_script` here, which `string escape` also uses, so that would need to be adjusted.

I'd just make it so DEL ends up being shown as `\x7f`. That's as likely to be of use as `\c?`, and is what we actually use in the binding scripts.

I'm not sure if any *other* characters need this adjustment as well - all control characters?

But since the immediate issue is with DEL, let's do that first.
