### ISSUE TITLE
Invalid digital signature

### ISSUE THREAD

**Issue by MrDogeBro** [fish-shell/fish-shell#7656]
**OS:** OSX 10.11.6

When I download the installer for OSX and open it to install fish, it errors due to an invalid digital signature.

Error: 
```
fish-3.1.2-1.pkg can't be installed because its digital signature is invalid.
The package may have been corrupted or tampered with. Get a new copy of the package and try again.
```

I have tried downloading it multiple times and have tried downloading the installer from the Github release as well as the official website.

I also tried to use the installer on a different machine running OSX 10.11.6 and I got the same error on that machine as well.

**Comment by faho** [comment]
Pretty sure we need @ridiculousfish to take a look at this, I don't have the ability to confirm this, let alone build a new package.

**Comment by Darkshadow2** [comment]
There was a thread about this on the Xcode-users list. I just re-read it, and it seems that it happens if you use Big Sur (macOS 11) to codesign the package (basically).  The package won't open pre 10.12.

Here's the thread on groups.io: [Installer pkg built with Xcode 12.2 won't open in macOS 10.10 and 10.11](https://apple-dev.groups.io/g/xcode/topic/installer_pkg_built_with/78782558)

**Comment by ridiculousfish** [comment]
[Big Sur productsign doesn't add the SHA1 hash](https://developer.apple.com/forums/thread/664842) which is all 10.11 knows about. It looks like there's no known workaround yet :(

**Comment by faho** [comment]
Ah, lovely. Is it possible to build the pkg on an older version and run it on Big Sur?

Or would we need two different .pkg? 

Or do we just drop support for everything < 10.12, at least with the .pkg? Our current minimum version is 10.9, so that's 3 years of macOS releases we'd be skipping, but if I'm reading wikipedia correctly even 10.12 is already unsupported by Apple since October 2019. Do we need to support operating systems that are older than the one the vendor already dropped over a year ago?

**Comment by ridiculousfish** [comment]
I've gotten [this workflow](http://users.wfu.edu/cottrell/productsign/productsign_linux.html) to work and the package installs on macOS 10.9, 10.11, 11.1, and also Apple Silicon. I'll check it in shortly and upload a fixed pkg.

**Comment by ridiculousfish** [comment]
I've uploaded re-signed Mac installers packages to the [3.1.2 release](https://github.com/fish-shell/fish-shell/releases); the fishshell.com website should pick them up automatically. Tested on 10.9, 10.11, 10.13, 11.1, Intel+AppleSilicon. So this should be fixed now; please comment or reopen if you still see this. Thanks for filing!
