### ISSUE TITLE
Test tty in Config

### ISSUE THREAD

**Issue by noahstrong2** [fish-shell/fish-shell#7665]
fish version 3.1.2 on kitty
Hi all, I'm trying to set up a command to exec startx only on tty2 and sway only on tty1. I've done a lot of searching but I can't seem to find anything that will work. I'm thinking something along the lines of `(tty) = /dev/tty1` should work but it won't accept it and I get an error about the syntax. If anyone has done something like this or knows how I'd really appreciate some help. I'll attach below my current setup for startx and exec sway.
`if status --is-login
     if test -z "$DISPLAY" -a $XDG_VTNR = 1
         exec startx -- -keeptty
     end
 end`

 `test -z "$DISPLAY" -a -z "$WAYLAND_DISPLAY" -a -n "$XDG_VTNR" && test 1 -eq "$XDG_VTNR" && QT_QPA_PLATFORM=wayland SDL_VIDEODRIVER=wayland XDG_SESSION_TYPE=wayland exec sway`

**Comment by faho** [comment]
First of all: If you're trying to start some form of service, use a real service manager instead - systemd is generally acceptable, otherwise I'm sure there are other things. Shells are horrible at this stuff.

Secondly: If you get a syntax error, it would be very nice to actually show the syntax you used and the error you get.

This works for me:

```fish
if status --is-login
    if test (tty) = /dev/tty1
          exec startx -- -keeptty # or start sway or whatever
   end
end
```
