### ISSUE TITLE
Unknown command: hostname when OS isn't Windows

### ISSUE THREAD

**Issue by akiirui** [fish-shell/fish-shell#7669]
- fish, version 3.1.2-1985-g261e13e0c

[share/functions/hostname.fish](https://github.com/fish-shell/fish-shell/blob/master/share/functions/hostname.fish) only work with Windows with cygwin.

This file let fish add the `hostname` to complete list, but will showing `Unknown command: hostname` when entered this command.

And trigger `fish_command_not_found`.

This function is it necessary? if yes, we should add other OS part into this.

**Comment by faho** [comment]
It is necessary on cygwin because that's weird, if possible you should install the `hostname` command - we do *not* want to override this on operating systems that have one.

I don't think there is anything to add here.

**Comment by zanchey** [comment]
What about move this into `share/config.fish`, to avoid the function appearing to exist when it does not?

**Comment by faho** [comment]
Looking closer at this, the rationale here is

```
        # Cygwin's hostname is broken when computer name contains Unicode
        # characters. This hack "fixes" hostname in Cygwin.
```

So cygwin *has* a hostname command, but it was broken in 2013, and according to the commit message (64921fe08a35aedc2715471b45b78d583660ddb7) it was broken for *fish_config*, so this is down to the sample prompts calling `hostname`.

Since they no longer do (they use `prompt_hostname`, which uses the $hostname variable), we can just remove the entire thing.
