### ISSUE TITLE
fish_prompt not behaving like interactive shell

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7675]
```fish
ilan@arch ~> echo $COLUMNS
112
ilan@arch ~> function fish_prompt
                 fish --command "echo \$COLUMNS"
             end
80
80
80
80fish --command "echo \$COLUMNS"
112
80
```

Is this intended? I found it quite unexpected, since afaik everything in `fish_prompt` should behave as though it were being run interactively in the current shell.

**Comment by faho** [comment]
What happens here is that, inside fish_prompt, stdout isn't connected to the terminal, because fish_prompt's output is going into a buffer like it's a command substitution.

So when the inner fish tries to query the output terminal's dimensions, it sees that it isn't a terminal and defaults to 80 (like it would assume when the terminal doesn't return dimensions).

So what you need to do, if you need $COLUMNS in this context, is to pass it explicitly - e.g.

```fish
COLUMNS=$COLUMNS fish -c 'echo $COLUMNS'
```

**Comment by IlanCosman** [comment]
Makes sense, thanks Fabian as always 😄
