### ISSUE TITLE
unbind keys

### ISSUE THREAD

**Issue by antoniomokuzai** [fish-shell/fish-shell#7677]
fish, version 3.1.2

Linux func 5.4.72-gentoo #1 SMP PREEMPT Mon Nov 2 07:39:57 -00 2020 x86_64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz GenuineIntel GNU/Linux

rxvt-unicode-256color
 
I found the default behavior of using Ctrl-p and Ctrl-n to navigate the history redundant, what's wrong with the up and down arrow? And my tmux config wants to use those bindings for other things, so I went about unmapping them:

I read the man page and tried a few other optional parameters too, but the bottom line, the following should just work in config.fish, but it did not, even "bind -e -a" did not remove the Ctrl-p Ctrl-n mapping

function fish_user_key_bindings
      bind -e \cp
      bind -e \cn
      bind -e -a
end

I have a feeling this is hardcoded somehow. I can map them to do other actions, such as 'echo WTF', but I cannot unmap them, hence those key strokes are consumed by fish, tmux never got them.

**Comment by antoniomokuzai** [comment]
I am using rxvt-unicode, but it has nothing to do with this, because Ctrl-p and Ctrl-n is navigating history in linux console too.

**Comment by faho** [comment]
>I am using rxvt-unicode, but it has nothing to do with this, because Ctrl-p and Ctrl-n is navigating history in linux console too.

Yes, the bindings are handled by fish - the terminal just sends the characters.

----

When you use `bind --erase` it erases your customization, which means it falls back to the defaults.

What you want is to map the binding to do nothing. `true` should do the trick, so

```fish
bind \cp true
```

**Comment by antoniomokuzai** [comment]
There is a HUGE difference between not consuming the keystrokes and consuming the keystrokes to do nothing - what you are suggesting is the latter, I want the former.

**Comment by antoniomokuzai** [comment]
I am not sure about your other comment about which gets the keystrokes first, because in my case, tmux is started from config.fish, fish is both inside and outside of tmux.

**Comment by faho** [comment]
No, when fish launches something else it doesn't read any keys at all anymore.

Tmux is your terminal, it reads the keys.

To bind something without the prefix, use `bind-key -n`, e.g

```tmux
bind-key -n C-p select-pane -t 1
```

in tmux.conf

**Comment by faho** [comment]
Okay, I've checked and double-checked that `bind-key -n` works with fish 3.1.2 and current git master, *without* doing any rebinding in fish.

Your mental model is wrong. There's a common misconception that the shell sits between the application and the terminal. It does in the sense that it's the parent process, but it doesn't regarding terminal control, because it directly passes control of the terminal to the application and relinquishes it itself. Fish always reads all input it receives, it never passes any on, precisely *because* it doesn't have the terminal when something else should have it.

Tmux on the other hand *does* sit between the terminal and the application - that's why I say it is a terminal.

So when you start an xterm that starts fish that starts tmux that starts fish, here's what happens:

- xterm starts fish, gives it control of the terminal
- fish starts tmux, giving up control of the terminal to it (you probably want `exec tmux` here to ditch the outer fish entirely)
- tmux keeps that terminal, opens a new one, starts the inner fish and gives that control over the inner terminal
- You press a key, xterm gets it, sends it through its terminal to the controlling process, which is tmux
- Tmux checks if it cares about the key and either acts on it, or sends it on through the inner terminal
- If tmux didn't use up the key the inner fish gets it

Now, this is a bit simplified and there could be bugs in fish, but I've tested it and it works for me, so most likely you just didn't use `bind-key -n`. If you don't use the `-n` this is a prefix-mapping, so you have to press your prefix (typically ctrl-a or ctrl-b, I forget which one tmux uses) and *then* the key.

I think that answers the question, if you have any more feel free to ask!
