### ISSUE TITLE
Fish environment variables with Kitty

### ISSUE THREAD

**Issue by mordax777** [fish-shell/fish-shell#7700]
OS: Arch Linux x86_64
Kernel: 5.10.13-arch1-2
Shell: fish 3.1.2
WM: sway 1.5.1
Term: xterm-kitty 0.19.3 

I am in a bit of a dead-end with my problem, so I turn myself here to find some help.

Here https://github.com/kovidgoyal/kitty/issues/3294 is a detailed description of the problem I have with `Kitty`. But to summarize also the comments: I am having trouble starting `Kitty` with my configuration file. The developer from `Kitty` suggested that I miss some environment variables that I require in `sway` when starting the terminal with a keybinding. So I posted here https://github.com/kovidgoyal/kitty/issues/3294#issuecomment-775043394 explaining how I am getting the environment variables from systemd's `environment.d` to `sway` via my `fish config`. I also believe it loads the environment variables correctly to `sway` because I rely on them in some other application that loads and runs them just fine. I was unsure if the issue is coming from `fish`, but if it started `Kitty` in `bash` with `$hyper+Return exec kitty /bin/bash`, the configuration gets pulled correctly. The developer of `Kitty` also referenced the method https://github.com/kovidgoyal/kitty/issues/3294#issuecomment-775198249 which builds the path to the config file from the environment variables. I took the method and let it run manually in a similar fashion to how I would start Kitty. The method worked since it correctly built the config file paths with the environment variables.

Do you guys maybe know what could be causing this problem?

**Comment by faho** [comment]
So... where is kitty supposed to find its config? What's that directory and where do you set it?

The reason `kitty --debug-config` might be showing you the wrong config is because *it* has the correct environment variables, which are applied *inside* the terminal, by the shell. So that "kitty" you start there would then have a different state.

Also: Fish's config file is in $XDG_CONFIG_HOME. That means setting $XDG_CONFIG_HOME from it is futile, because it won't be found then!

Anyway, what's most likely happening here is that whatever you're doing to start kitty (you never actually specified) is never starting fish anywhere, so you don't get whatever you're doing in fish's config applied.

>if it started Kitty in bash with $hyper+Return exec kitty /bin/bash

This does not start "kitty in bash". This starts "bash in kitty".

**Comment by mordax777** [comment]
> So... where is kitty supposed to find its config? 

Yes, because if I start Kitty from an running Terminal, the config gets pulled.

>What's that directory and where do you set it?

Default one, so ~/.config/kitty/kitty.conf

> The reason `kitty --debug-config` might be showing you the wrong config is because _it_ has the correct environment variables, which are applied _inside_ the terminal, by the shell. So that "kitty" you start there would then have a different state.

`kitty --debug-config` always prints the correct configuration, even when the terminal did not apply the configuration.

> Also: Fish's config file is in $XDG_CONFIG_HOME. That means setting $XDG_CONFIG_HOME from it is futile, because it won't be found then!

https://github.com/kovidgoyal/kitty/issues/3294#issuecomment-775043394 here you can see how I am setting XDG_CONFIG_HOME.

> Anyway, what's most likely happening here is that whatever you're doing to start kitty is never starting fish anywhere, so you don't get whatever you're doing in fish's config applied.
> 
> This does not start "kitty in bash". This starts "bash in kitty".

Ok, so if I understand correctly, I need to start first fish somehow and then Kitty? I am a bit confused at this point since I thought that the shell will be loaded automatically since it configured for my user under `/etc/passwd`

**Comment by faho** [comment]
>Ok, so if I understand correctly, I need to start first fish somehow and then Kitty? I am a bit confused at this point since I thought that the shell will be loaded automatically since it configured for my user under /etc/passwd

So... what often happens under X11 is that "the session" starts your shell to then start itself. This is why things you set in your shell's configuration often end up being applied.

But there's nothing guaranteeing that and in your case it doesn't appear to be happening. (it's also a terrible idea because systems like adding stuff to /etc/profile.d, and that won't end up being applied if your shell isn't compatible)

>kitty --debug-config always prints the correct configuration, even when the terminal did not apply the configuration.

Ah, so this is one of kitty's weird automagic things where it talks to the running terminal?

>kovidgoyal/kitty#3294 (comment) here you can see how I am setting XDG_CONFIG_HOME.

It's not actually very explicit. You're setting $XDG_CONFIG_HOME in some file in environment.d, but I don't know why you then need to "pull" those in? I thought environment.d was applied to all systemd user services, so it should already be applied to sway (and its children)? Unless you're not starting that as a user service, I suppose.

>Default one, so ~/.config/kitty/kitty.conf

Note that ~/.config is the default for $XDG_CONFIG_HOME if that's not set. So I'm a bit confused as to why kitty won't find that path by default?

-----

There is one bit of brokenness in your fish config:

```fish
for line in (systemctl --user show-environment)
    set key (echo "$line" | cut -d '=' -f 1)
    set value (echo "$line" | cut -d '=' -f 2- | tr -d \$\')
    set -g -x "$key" "$value"
end
```

Give it a line like `XDG_CACHE_HOME=$HOME/.cache`, and actually check its value - `echo $XDG_CACHE_HOME` will print `HOME/.cache`. This doesn't actually work.

**Comment by mordax777** [comment]
> It's not actually very explicit. You're setting $XDG_CONFIG_HOME in some file in environment.d, but I don't know why you then need to "pull" those in? I thought environment.d was applied to all systemd user services, so it should already be applied to sway (and its children)? Unless you're not starting that as a user service, I suppose.

If you take a closer look at the `fish config` that I use to pull the environment variables, I also start my `sway` session beneath the `for` loop. I start it with  `systemd-cat -t sway sway`, which starts the process(without `systemd`), but prints the output from the application to the `journalctl` under the name sway. So, to get the `environment.d` variables into `sway`, I import them via the `for` loop above. At this point, you are probably asking yourself, why I am doing these crazy things :smile:  `sway` sadly does not support `display managers` nor `systemd` officially. The only real supported way to start sway is via `TTY`(more: https://wiki.archlinux.org/index.php/Sway#Starting). 

>Give it a line like XDG_CACHE_HOME=$HOME/.cache, and actually check its value - echo $XDG_CACHE_HOME will print HOME/.cache. This doesn't actually work, so it could be what is breaking your kitty.

This is the output of `systemctl --user show-environment`:
```
HOME=/home/aljaz
LANG=en_US.UTF-8
LOGNAME=aljaz
MAIL=/var/spool/mail/aljaz
PATH=/home/aljaz/.local/bin/:/home/aljaz/.local/bin-private/:/home/aljaz/go/bin/:/home/aljaz/.gem/ruby/2.7.0/bin:/usr/local/bin:/usr/bin
SHELL=/usr/bin/fish
USER=aljaz
XDG_RUNTIME_DIR=/run/user/1000
LANGUAGE=en_US
LC_MONETARY=de_DE.utf8
LC_TIME=de_DE.utf8
XDG_CONFIG_HOME=/home/aljaz/.config
XDG_DATA_HOME=/home/aljaz/.local/share
XDG_CACHE_HOME=/home/aljaz/.cache
GOPATH=/home/aljaz/.local/share/go
LESSHISTFILE=-
EDITOR=nvim
VISUAL=nvim
MANWIDTH=999
AUR_PAGER=nvim
DIFFPROG=meld
LIBVA_DRIVER_NAME=iHD
MOZ_ENABLE_WAYLAND=1
QT_QPA_PLATFORM=wayland-egl
WLR_DRM_NO_MODIFIERS=1
XDG_CURRENT_DESKTOP=sway
XDG_SESSION_TYPE=wayland
_JAVA_AWT_WM_NONREPARENTING=1
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DISPLAY=:0
GPG_TTY=
SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh
SWAYSOCK=/run/user/1000/sway-ipc.1000.1335.sock
WAYLAND_DISPLAY=wayland-0
```
So the mentioned problem where I trim the string should not be the issue here.

>Since you're setting the defaults anyway, just remove the xdg settings entirely, to be honest.

I tried removing the `xdg`'s from my environment.d, but the issue still persists.

**Comment by faho** [comment]
> I also start my sway session beneath the for loop. I start it with systemd-cat -t sway sway, which starts the process(without systemd)

Shells are crappy at service management, I recommend letting a proper service manager handle it. But that's unrelated and probably requires some form of cooperation from sway.

>This is the output of systemctl --user show-environment:

Well, as we've established above the *systemd environment* isn't important, because you're not using systemd here.

And the *fish environment* does that broken pulling, so that's where the breakage is. The first fish in the stack poisons the well for all its children (and their children, and so on).

>I tried removing the xdg's from my environment.d, but the issue still persists.

Did you reboot after that?

**Comment by mordax777** [comment]
I changed the Shell script to:
```shell
for line in (systemctl --user show-environment)
    set key (echo "$line" | cut -d '=' -f 1)
    set value (echo "$line" | cut -d '=' -f 2-)
    set -g -x "$key" "$value"
end
```
removed the `xdg`'s and rebooted.

**Comment by faho** [comment]
>I changed the Shell script to:

This is still broken as long if any variables reference other variables.

--------

So, from the top:

- Starting kitty from a keybinding in sway starts kitty, but not with the correct configuration
- The shell running inside that either has $XDG_CONFIG_HOME set correctly or not set
- Starting another kitty from that starts with the correct configuration

If so, I'm still hung on environment variables, because that is *how* kitty would find the configuration. Things other than environment variables just don't seem relevant here, it's really the only thing it's likely to be.

So what would happen is that kitty is started with the wrong environment, and then whatever shell it starts fixes it for itself and its children, but of course can't fix kitty's state.

Please execute the following:

```fish
ps -p (ps --no-headers -o ppid -p $fish_pid | string trim)
cat /proc/(ps --no-headers -o ppid -p $fish_pid | string trim)/environ | while read -lz -d= var; echo $var; end
```

inside the fish running in a broken kitty.

This should print kitty's environment, which might give us a clue.

**Comment by mordax777** [comment]
> Starting kitty from a keybinding in sway starts kitty, but not with the correct configuration

Correct.

> The shell running inside that either has $XDG_CONFIG_HOME set correctly or not set

`XDG_CONFIG_HOME` is always defined since I set it via `environment.d` and the `fish` script. 

> Starting another kitty from that starts with the correct configuration

Correct.

Please note, the beneath output is also with the removed `xdg`'s from `environment.d`:
```shell
❯ ps -p (ps --no-headers -o ppid -p $fish_pid | string trim)
  cat /proc/(ps --no-headers -o ppid -p $fish_pid | string trim)/environ | while read -lz -d= var; echo $var; end
    PID TTY          TIME CMD
  47307 ?        00:00:00 kitty
SHELL=/usr/bin/fish
LESSHISTFILE=-
LANGUAGE=en_US
I3SOCK=/run/user/1000/sway-ipc.1000.1455.sock
SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh
LIBVA_DRIVER_NAME=iHD
LC_MONETARY=de_DE.utf8
DIFFPROG=meld
XCURSOR_SIZE=24
GPG_TTY=
EDITOR=nvim
XDG_SEAT=seat0
PWD=/home/aljaz
AUR_PAGER=nvim
LOGNAME=aljaz
XDG_SESSION_TYPE=wayland
FZF_DEFAULT_COMMAND=fd --type f --hidden --follow --exclude .git
MOTD_SHOWN=pam
HOME=/home/aljaz
LANG=en_US.UTF-8
_JAVA_AWT_WM_NONREPARENTING=1
XDG_CURRENT_DESKTOP=sway
STARSHIP_SHELL=fish
SWAYSOCK=/run/user/1000/sway-ipc.1000.1455.sock
WAYLAND_DISPLAY=wayland-0
INVOCATION_ID=1a389650de19469cb4212c27d1be9eea
STARSHIP_SESSION_KEY=9839066025324268
QT_QPA_PLATFORM=wayland-egl
MANWIDTH=999
XDG_SESSION_CLASS=user
TERM=linux
FZF_CTRL_T_COMMAND=fd --type f --hidden --follow --exclude .git
USER=aljaz
VISUAL=nvim
DISPLAY=:0
SHLVL=1
MOZ_ENABLE_WAYLAND=1
XDG_VTNR=1
XDG_SESSION_ID=1
XDG_RUNTIME_DIR=/run/user/1000
LC_TIME=de_DE.utf8
WLR_DRM_NO_MODIFIERS=1
JOURNAL_STREAM=8:17727
PATH=/home/aljaz/.local/bin/:/home/aljaz/.local/bin-private/:/home/aljaz/go/bin/:/home/aljaz/.gem/ruby/2.7.0/bin:/usr/local/bin:/usr/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
FZF_DEFAULT_OPTS=--height 40% --layout=reverse --border
MAIL=/var/spool/mail/aljaz
GOPATH=/go
_=/usr/bin/kitty
```

**Comment by faho** [comment]
>The shell running inside that either has $XDG_CONFIG_HOME set correctly or not set

>XDG_CONFIG_HOME is always defined since I set it via environment.d and the fish script.

But the fish script is *broken*. 

>Please note, the beneath output is also with the removed xdg's from environment.d:

Yeah, no, sorry, that output is correct. If kitty is supposed to find your $XDG_CONFIG_HOME at /home/aljaz/.config/, and it's configuration in the default path there, this is the environment to do it.

So if this kitty couldn't find it, I have no further idea.

**Comment by mordax777** [comment]
> But the fish script is broken.

I also tried removing the whole fish script and running sway manually, but had the same result.

Funny enough, I tried switching my default shell to `/bin/bash` and setting `XDG_CONFIG_HOME`, but I am getting the exact same result as with fish.

**Comment by faho** [comment]
>Funny enough, I tried switching my default shell to /bin/bash and setting XDG_CONFIG_HOME, but I am getting the exact same result as with fish.

Well, that pretty much means the problem is not with fish.

**Comment by mordax777** [comment]
> Well, that pretty much means the problem is not with fish.

correct, closing this one.
I might take this now to the sway folks. I am running out of ideas at the moment.

But thank you for your help and all the quick responses. It was already really helpful. :slightly_smiling_face:
