### ISSUE TITLE
Wrapper/patch for passing specific .env variables (LINES= COLUMNS=) for every command execution?

### ISSUE THREAD

**Issue by maksmeshkov** [fish-shell/fish-shell#7707]
fish, version 3.1.2
Gentoo Linux, amd64

To fix https://github.com/alacritty/alacritty/issues/4560, every command has to be launched with LINES and COLUMNS variables set to null.
TL;DR: `LINES= COLUMNS= htop` works correctly after resizing, but `htop` does not. And this does not affect every terminal emulator (`urxvt` works fine, but `termite` and `alacritty` do not). And this is not a `fish`'s problem as `bash` is also affected. 

How to make a wrapper/patch for every executed command (either with fish functions or source code)?

**Comment by faho** [comment]
First of all, fish doesn't export these, so I'd look what on your system does,because that's your root cause.

Secondly, to unexport a variable, use `set --unexport`, so

```fish
set --unexport COLUMNS
```

in your config.fish should do.

**Comment by maksmeshkov** [comment]
Thank you very much, this worked!
```
set --unexport COLUMNS
set --unexport LINES
```

**Comment by faho** [comment]
Note: This is very much not a *fix*. It's a workaround. The *fix* is to not export them in the first place.

Since this seems to be happening for a bunch of people there's probaby *some* popular piece of software that has a bug.

I'll leave it to y'all to get together and figure out what you have in common.

**Comment by faho** [comment]
Note: This is very much not a *fix*. It's a workaround. The *fix* is to not export them in the first place.

Since this seems to be happening for a bunch of people there's probaby *some* popular piece of software that has a bug and exports these.

I'll leave it to y'all to get together and figure out what you have in common.

**Comment by ahmedkhalf** [comment]
I was experiencing this issue with qtile
