### ISSUE TITLE
fish_indent and interactive reader don't indent continuations the same

### ISSUE THREAD

**Issue by rouge8** [fish-shell/fish-shell#7720]
As of 5e8a248758bd1de28b629a7ec2f4130d96211e13, `fish_indent` and the interactive reader indent this function differently:

```fish
function testfunc
    cmd \
        --opt1 val1 \
        --opt2 val2 \
        --opt3 val3 \
        --opt4 val4
end
```

The interactive reader indents it like above and prior to 5e8a248758bd1de28b629a7ec2f4130d96211e13, so did `fish_indent`. 

After 5e8a248758bd1de28b629a7ec2f4130d96211e13, `fish_indent` reformats it to:

```fish
function testfunc
    cmd \
        --opt1 val1 \
            --opt2 val2 \
            --opt3 val3 \
            --opt4 val4
end
```

I tried debugging by adding a failing test to `tests/checks/indent.fish`, but I think I ran into a limitation of littlecheck: "littlecheck **permits leading whitespace** on matching lines and does not yet support something like the `--strict-whitespace` option to FileCheck" which I think means it can't test the exact `fish_indent` output...

**Comment by faho** [comment]
>I think I ran into a limitation of littlecheck: "littlecheck permits leading whitespace on matching lines

You can just regex-match the beginning/end of line to match leading/trailing whitespace so a separate option isn't really needed.

E.g.

```sh
#!/bin/sh
echo "   foo"
# CHECK: foo

echo "   foo"
# CHECK: {{^}}   foo
echo "   foo"
# CHECK: {{^}}  foo
echo "   foo"
# CHECK: {{^}}    foo
````

(and `{{$}}` for the end of the line)
We should probably add this to the littlecheck docs.

**Comment by krobelus** [comment]
I meant to run `fish_indent -w share/**.fish` but forgot to do so with my latest changes. It should not change any formatting.
There's also another embarassing regression on `share/completions/emerge.fish`.

**Comment by rouge8** [comment]
Got it. In that case, a simple failing test:

```sh
echo -n '
function hello_continuations
   echo cmd \
   echo --opt1 \
   echo --opt2 \
   echo --opt3
                  end
' | $fish_indent

#CHECK: function hello_continuations
#CHECK: {{^}}    echo cmd \
#CHECK: {{^}}        echo --opt1 \
#CHECK: {{^}}        echo --opt2 \
#CHECK: {{^}}        echo --opt3
#CHECK: end
```

**Comment by faho** [comment]
>I meant to run fish_indent -w share/**.fish but forgot to do so

We could also run `fish_indent --check share/**.fish` as a test, but I've been wary of doing so because I don't want to bother everyone just adding a simple completion script with having to match formatting 100%.

Am I wrong about that? Should we ask everyone to run `fish_indent` on their stuff?

(also I can't complain about someone else forgetting to run tests - I apparently forgot to run them after the recent fallback binding changes. I'll fix them later)

**Comment by IlanCosman** [comment]
> Am I wrong about that? Should we ask everyone to run fish_indent on their stuff?

I think so. Working with completions is already  more work, and implies a higher level of Fish knowledge, than running `fish_indent` on your changes. I don't think it's an unreasonable burden at all.

**Comment by faho** [comment]
>I don't think it's an unreasonable burden at all.

We want adding completions to be as frictionless as possible. That's also why e.g. we don't list the completions in the build system (which basically rules out meson unless you want to do awkward hacks!).

There is a difference between figuring out the thing you actually want to do - making a completion script for a thing you know better than us because you actually use it, and adding heaps of procedure on top.

Plus this is one of those tests that fails and sounds the alarms even tho it's entirely non-critical, which makes you annoyed at the tests themselves, and makes you less likely to listen to the tests that actually *do* matter.

(this is also why flakey tests are so awful and why it sometimes pays to *remove* a test, if it fails more for spurious reasons than it helps)

That's my position, anyway.

**Comment by krobelus** [comment]
Thanks for reporting, and thanks for the test case!

> We want adding completions to be as frictionless as possible.

Yeah, that's the main thing. I feel like for many completions, `fish_indent` mainly changes the unnecessary quotes and spaces; other than that it matches fairly well what users write (which is the point, after all).

I imagine there could be some automated way of adding the formatting server-side (like a Git clean/smudge filter) but if it takes up people's attention, it's hardly worth it.
