### ISSUE TITLE
function --on-variable misses Universal variable changes when changed rapidly

### ISSUE THREAD

**Issue by soraxas** [fish-shell/fish-shell#7735]
```fish
$ fish --version
fish, version 3.1.2
```

When a universal variable is changed, the `function --on-variable` does not fire the variable is being set in a hasty succession.

Perhaps related to #7260 with the way that the universal variable is optimised when syncing across fish processes.

## Setup

**fish process 1**
```fish
set -U __test
function foo --on-variable __test
      echo $__test
end
```

**fish process 2** (in a different terminal)
```fish
function foo --on-variable __test
      echo $__test
end
```

## Execute 1
**fish process 1**
```fish
for i in (seq 100)
      set __test $i
end
```

### [Outputs]
**fish process 1**
```fish
1
2
[...]  # no numbers are missing (i.e. 3 to 98)
99
100
```
**fish process 2**
```fish
1
9
30
56
83
100
# the followings are of a different execution instance
1
10
35
64
95
100
# the followings are of a different execution instance
1
11
37
70
100
```

## Execute 2

Adding a bit of a delay allows **fish process 2** to successfully process the events
**fish process 1**
```fish
for i in (seq 100)
      set __test $i
      sleep 0.1   # values less than 0.1 (e.g. ~0.08) will tends to have noticeable missing events in process 2
end
```

### [Outputs]
**fish process 1**
```fish
1
2
[...]  # no numbers are missing (i.e. 3 to 98)
99
100
```
**fish process 2**
```fish
1
2
[...]  # no numbers are missing (i.e. 3 to 98)
99
100
```

## Thoughts

Perhaps fish is polling / queueing the events at around 100ms (the universal variable notifier across process), which makes it so that the `--on-variable` does not get fired? Note tha the opposites is true too (i.e. if process 2 is setting the variable, process 1 will have missing events while process2 will have no trouble in firing all of the events)

I don't think this is too big of a practical issue (if, given that,  we can ensure `--on-variable` fires if the rate is not as rapid), but I still want to reports this (I didn't saw other issues mentioning this) as it's something that one would want to keep in mind if people are using this as a poor man's `emit` event across processes (it sort of works but not as robust as same process `--on-event` or `--on-signal`.)

**Comment by faho** [comment]
This appears to me to be as expected. The first fish instance writes the values, the second reads them, but there's nothing stopping the first from updating the values while the second is still reacting.

So there's no real way around this and this is simply not what universal variables are designed to do.

(note that we have a few different universal variable notification strategies depending on what your OS offers, which is sadly woefully unstandardized, they might behave differently, but really this isn't in-scope for universal variables)

So I'm closing this as "don't do that, then".

See also #7379 where we discuss removing universal variables as they currently are entirely.

**Comment by soraxas** [comment]
I guess what I would expect is that the events would be queued (even if it's not "real-time"), rather than discarded silently without any warnings specifying this quirks in the manual. Two quick `set -U <VAR>` is enough to cause other processes to miss the variable-change event.  However, I do agree that this is not what universal variables is for.

**Comment by zanchey** [comment]
It's worth adding a note in the documentation to say that these may not be fired multiple times in quick succession.

Any attempt to use universal variables as a synchronisation mechanism is going to run into race conditions anyway.

**Comment by faho** [comment]
>I guess what I would expect is that the events would be queued

Well, yeah, but there isn't any queueing mechanism here! We don't have e.g. a pipe between any two fishes (because that's super wasteful).

Conceptually, fish 2 just notices the file has changed, and then reads it again and fires its handlers and eventually checks again, and in that time, fish 1 can change the file multiple times. Anything else would require either a queue (which gets gnarly once you have more than 2 fishes), a synchronization mechanism (which would require fish 1 to slow down until fish 2 has caught up) or for fish 2 to just keep reading and firing off the handlers (which would require fish 2 to possibly abort its handlers if they are too slow). E.g. what should happen if you had

```fish
function on-test --on-variable __test
    sleep 0.1
    echo $__test
end
```

Even if fish 2 read *more* than the current "every 100ms" or so, if you want to always read *everything* it would require synchronization given that multiple fishes could be writing and one reading.

So it's not worth getting into, and the only real guarantee we can give is that you get the "last" event - the only real bug here would be if fish 2 missed that __test has been set to 100. Everything else is off-label use.

All of this is just one more argument for scrapping universal variables as they are, because they look like something they aren't - an IPC mechanism. They're just something to persist variables, which is "magically" picked up by other sessions so you don't have to set them there as well.

**Comment by soraxas** [comment]
I see, I didn't realise that the universal variables are not communicated between process but is implemented as like a file watch (which make sense given its current behaviour, and to ensure persistent state). 

And yes, to reiterate I don't think this is of too big of a practical concern. But as zanchey had said I think it's worth mentioning this in the man as this behaviour is different than that of a `--on-event` and `--on-signal` (due to the practical implementation details).

**Comment by zanchey** [comment]
Added some language to the documentation to note this.
