### ISSUE TITLE
fish_config may not work in certain cases in WSL (2)

### ISSUE THREAD

**Issue by nosed1ve** [fish-shell/fish-shell#7741]
I am aware that the bug in which `fish_config` does not work in WSL 2 because of the fact that the string in `/proc/version`  is `microsoft` and not `Microsoft` is being fixed in the new release, however, in the function `runThing()` in `tools/webconfig/webconfig.py`, we are calling `cmd.exe` as it is, without mentioning it's full path.

Some people(like me) may have `appendWindowsPath = false` in their `/etc/wsl.conf` which turns of the adding of windows path elements to the WSL linux $PATH. If this is the case, `cmd.exe` would not be found in $PATH and hence `fish_config` would fail.

To fix this all that needs to be done is that we need to call `cmd.exe` by it's full path, which is `/mnt/c/Windows/System32/cmd.exe`.

There is one small edge case that might need to be considered however. That is that if the user changed their windows filesys mount location, it wouldn't be /mnt/c anymore, and might be something else, like /windir/c.

I am willing to make a pull request when I have time if required.

**Comment by faho** [comment]
>There is one small edge case that might need to be considered however. That is that if the user changed their windows filesys mount location, it wouldn't be /mnt/c anymore, and might be something else, like /windir/c.

It seems like the best solution here is to add the default location to $PATH temporarily, so we get it either via the user's configured $PATH or the default location. It'll still fail if they changed the mount location (why would you do that, tho) *and* didn't add it to $PATH, and I don't see a way of supporting that.

>I am willing to make a pull request when I have time if required.

That would be great, yeah.

**Comment by nosed1ve** [comment]
>  It'll still fail if they changed the mount location (why would you do that, tho) 

Some people do it for convenience, `/windir/c` makes more sense than `/mnt/c`, or some ppl change mount location to /, so the `c` directory becomes `/c`, which I believe is default on cygwin and is more convenient too.

Anyway, what I was thinking was, we can run a shell script, which finds the location of the `c` directory using a `find` command.
Then we can call `cmd.exe` using the `c` dir path we found from the `find`.

If that is too much, the $PATH solution seems best. Can we assume that the `c` directory PATH is first in `$PATH`? That way, we can get the `c` dir path in the `webconfig.py` script by doing something like `os.environ.get('PATH').split(':')[0]`.

> That would be great, yeah.
Sure thing, I'll do it as soon as I have some time on my hands.

**Comment by faho** [comment]
>If that is too much

It is too much, yes.

For one running `find` on your entire system can easily take minutes, for another it's not our responsibility - if you don't have it in $PATH *or* the default location you've configured your system that way, and it's either broken by accident (in which case you should fix it) or on purpose, in which case you know what you're doing. There's no need to third-guess the user here (the second guess is using the default location). Since you've not given us the location where we would find cmd.exe, we also can't assume any old cmd.exe lying around is the right one.

What we *can* do is print a nice error when we need cmd.exe and can't find it, even after checking the default.

>If that is too much, the $PATH solution seems best. Can we assume that the c directory PATH is first in $PATH?

There's no need for that. Just add the default location (at the end) and then do a normal $PATH lookup - which I think subprocess.call does automatically, so just adding it should suffice? If it doesn't (the docs are kinda lacking here) we already have a `find_executable` helper function that you could just use. If that fails, print an error about how we can't find cmd.exe so it needs to be added to $PATH.

If it's in another directory you've configured, we'll find it and use it first, if the default location is already in we'll just check it twice. Either way there's no real harm.

**Comment by nosed1ve** [comment]
Ok got it, sounds good.

So just to be clear, this is the flow for launching cmd.exe right:

- use `find_executable()` to try to find `cmd.exe` path
- if a path is returned, we can simply use that path for invoking `cmd.exe`
- if a path is not returned, try invoking `cmd.exe` with it's DEFAULT full path, which should be `/mnt/c/Windows/System32/cmd.exe`
- if that does not work, then try invoking `cmd.exe` by using the last item in `$PATH` as the path to the windows mount dir
- if that still does not work, print an error message saying something like `Please add the windows mount directory to the end of your $PATH` blah blah

**Comment by faho** [comment]
>if a path is not returned, try invoking cmd.exe with it's DEFAULT full path, which should be /mnt/c/Windows/System32/cmd.exe

No need. Just always add /mnt/c/Windows/System32 to the path find_executable checks. You'll probably want to give an optional paths argument to find_executable and pass $PATH *plus* the default here (and if it isn't passed let it check $PATH itself). If you say there's a few typical paths that are used by convention (like /c/Windows/System32) you can add those as well.

>if that does not work, then try invoking cmd.exe by using the last item in $PATH as the path to the windows mount dir

$PATH was already checked in find_executable.

>if that still does not work, print an error message saying something like Please add the windows mount directory to the end of your $PATH blah blah

No need to add it to the end specifically. Just "Please add the windows system32 directory to $PATH".

**Comment by nosed1ve** [comment]
Ok I got what needs to be done, should I go ahead with the pull request?

**Comment by faho** [comment]
Sure, go ahead.

**Comment by nosed1ve** [comment]
Aight, I'll let you know when I make the pull request.

**Comment by faho** [comment]
Just open it, I'll get notified anyway.
