### ISSUE TITLE
Can't search for commands like "if" and "for"

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#7757]
Over in fish-shell/fish-site#97, @mikelward points out:
If I search for "for" using the left-side search box on https://fishshell.com/docs/current/index.html, it takes me to https://fishshell.com/docs/current/search.html?q=for&check_keywords=yes&area=default, which says

> Your search did not match any documents.

It would be super helpful if all fish commands were searchable.

Commands that seem broken:

- if
- for
- cd
- and
- or

Commands that are <= 3 chars that seem to work:

- end
- set (albeit suboptimal search ranking)

Is it possible Sphinx has the ones that don't work as stopwords?

**Comment by faho** [comment]
I [looked into this a while back on gitter](https://gitter.im/fish-shell/fish-shell?at=6032d6f27ba8124e547df5de) (which is why I never bothered opening this here):

We could, theoretically, copy sphinx's search language for english and hack the stopwords. That's about fifty lines of super brittle code that won't gain any upstream improvements. Even if we did that, `if`, `or` and `cd` would still be rejected as too short, so it would really only work for `for` and `and`, and even there you'd have hundreds of false-positives with bad search ranking.

Honestly, that doesn't seem worth it. The real fix is in upstream sphinx.

**Comment by ilyagr** [comment]
Perhaps the message `Your search did not match any documents. Please make sure that all words are spelled correctly and that you've selected enough categories.` could be modified to add a second paragraph:

"Fish commands such as `if` and `for` are too short to be included in the search index. You can find them in the index of all commands (link to Commands page)"

If there was a desire to show off, this could happen only when the search query is, in fact, short.

**Comment by faho** [comment]
Okay, I have a *massive* hack:

![Screenshot_20210302_140616](https://user-images.githubusercontent.com/5185367/109652843-8e55da00-7b60-11eb-9d32-5b7f46624b8a.png)

**Comment by faho** [comment]
Alright, I committed it (with added descriptions).

This really seems like the best thing we *can* do unless sphinx' search function is redesigned, given that "and" is awful to search no matter what you do.

(I guess we could also intercept the search and hardcode a result for "and", but I don't know *where*, and that only really works if you're searching for exactly "and")
