### ISSUE TITLE
Release 3.3.0

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7759]
How long until the next release? Just kidding 😂 Beat ya to it @zanchey 😄 

To quote the wise @zanchey: 
> Let's try and avoid another year between drinks! I think increasing the release cadence will actually shorten the amount of work for each release, so I'd be happy to try and do it in 2-3 months time.

I agree. While this was only my first fish release as part of the community, it's seems clear that both devs and users would be happier with a quicker release cycle. What can we do to make that a reality? I'm happy to help in any way I can 😄

**Comment by rubyFeedback** [comment]
Hopefully we won't have to do as much scrolling to the tarball for the next release though!!!

**Comment by mqudsi** [comment]
I appreciate the enthusiasm and I agree the community has shown interest in getting its hands on improvements and new features sooner rather than later in the form of stable releases, but this issue really adds nothing and isn't actionable at this time. Perhaps we can re-open this PR instead of creating a new issue when the time comes, but I'm closing it for now. Thanks for the ❤️ and support, guys!
