### ISSUE TITLE
`set --erase` incorrectly handles indices

### ISSUE THREAD

**Issue by branchvincent** [fish-shell/fish-shell#7776]
While testing out the new `fish_add_path --move`, I noticed incorrect paths being removed/moved stemming from https://github.com/fish-shell/fish-shell/blob/c96a07dc9611a4302298ad287dff2278caf5887d/share/functions/fish_add_path.fish#L66

A simple repro is:

```fish
> set arr 1 2 3
> set -e arr[1] arr[2] # expanded form of arr[$indexes] above
> echo $arr
2 # expected 3
```

As you can see, `set -e arr[1]` works fine but presumably when `set -e arr[2]` occurs, `arr = 2 3`. The elements should be erased in index-descending order as `set -e arr[1 2]` correctly handles. Thus, a workaround for my initial issue is

```diff
diff --git a/share/functions/fish_add_path.fish b/share/functions/fish_add_path.fish
index cac0d9d4f..11e1017a0 100644
--- a/share/functions/fish_add_path.fish
+++ b/share/functions/fish_add_path.fish
@@ -63,7 +63,7 @@ function fish_add_path --description "Add paths to the PATH"
     set -l newvar $$var
     if set -q _flag_move; and set -q indexes[1]
         # We remove in one step, so the indexes don't move.
-        set -e newvar[$indexes]
+        set -e newvar[(echo $indexes)]
     end
     set $mode newvar $newpaths
```

<details>
  <summary>System info</summary>

```fish
> fish --version
fish, version 3.2.0

> uname -a
Darwin Branchs-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

> echo $TERM
xterm-256color

> sh -c 'env HOME=$(mktemp -d) fish'
# reproduces
```
</details>

Btw, amazing work on fish! It is such a joy to use!

**Comment by faho** [comment]
Ooh, this is a bit subtle.

Since `set` is a "normal" builtin and not a piece of syntax, this runs the normal expansions. So, because $indexes is a multi-element list, it expands as a cartesian product ("everything with everything"), so

```fish
set -l indexes 1 2 3 # for example
set -e newvar[$indexes]
```

becomes something like

```fish
set -e newvar[1] newvar[2] newvar[3]
```

and then `set` just goes through its arguments and runs everything immediately - removes the first element, removes the second element (but on the new list!), removes the third element, ...

The simplest fix here is to just quote the "$indexes", and that's what I'm going to do.
