### ISSUE TITLE
Non-default browser used for http:// links

### ISSUE THREAD

**Issue by afedulov** [fish-shell/fish-shell#7814]
```
fish, version 2.7.1
Linux Mint: 4.15.0-135-generic #139-Ubuntu x86_64 GNU/Linux
Tried without customizations: yes
```
---
I have Chrome and Brave browsers installed. Chrome is set a the default browser, however whenever I click on any link in Fish, it opens in Brave.
Ways to reproduce:
```
$ echo http://example.com
http://example.com <---click
```
I tried setting `set -x BROWSER chrome`, but it does not help.
Executing `xdg-open http://example.com` opens Chrome, as expected.

**Comment by faho** [comment]
This is a *terminal* issue, fish has no control over what happens when you click something, and setting $BROWSER won't have any effect on it because it's *above* the shell, if you will.

Also:

>fish, version 2.7.1

This fish version is 3 years old, it is missing almost half the commits made to fish in its entire lifetime.

Please upgrade. Go to https://fishshell.com/, find your operating system and you'll most likely find a PPA.

**Comment by afedulov** [comment]
@faho, thanks for pointing in the right direction. I am using `tilda` dropdown terminal and it hax `x-www-browser` set for URL handling. Switching to `xdg-open` helped. I also upgraded to 3.2. I personally see no difference, but half of the commit of all time definitely sounds impressive ;)

**Comment by afedulov** [comment]
@faho thanks for pointing at the right direction. I am using

**Comment by faho** [comment]
> I personally did not yet see much difference

@afedulov You might enjoy looking at [the release notes](https://fishshell.com/docs/current/relnotes.html) then.
