### ISSUE TITLE
Completion support for TERM=dumb

### ISSUE THREAD

**Issue by binshengliu** [fish-shell/fish-shell#7834]
The issue is fish no longer completes with `TERM=dumb` in `3.2.0`.

We use `TERM=dumb` for testing purpose to precisely capture completion candidates. But since `3.2.0` fish no longer auto completes for `TERM=dumb` and breaks our [test cases](https://github.com/facebookresearch/hydra/issues/1442).

826db22db is the last commit that completion still works for dumb.
[![asciicast](https://asciinema.org/a/s1QlRR2KHJ5pQk9MehRxIqXpn.svg)](https://asciinema.org/a/s1QlRR2KHJ5pQk9MehRxIqXpn)

Since ada03d350 completion doesn't work for dumb.
[![asciicast](https://asciinema.org/a/6nMvmQyReQHo77KWvClGyFOUH.svg)](https://asciinema.org/a/6nMvmQyReQHo77KWvClGyFOUH)

It would be great if we can still have the basic completions work for dumb as it's very useful for testing.

System:
```
$ uname -a
Linux debian 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
```

Fish version: `fish, version 3.1.2-982-gada03d350` onwards.

**Comment by faho** [comment]
If you are just interested in the completion *candidates* you probably want `complete --do-complete="your commandline here"`. That will just print them with one per line and descriptions after a tab. It can be run from a script and does not require a full terminal (but can of course also be used in pty tests).

I don't think we want to print the pager with $TERM=dumb because I'm pretty sure actual dumb terminals can't handle it - is there cursor movement in those? So you would have to pick a different $TERM (maybe ansi or xterm-mono?)

**Comment by faho** [comment]
Looking at the "dumb" terminfo entry, this is all it does: It has 80 columns (hardcoded!), supports a bel, resetting the cursor to the beginning of the line (by printing a carriage return - `\r`), moving the cursor down (by printing a line feed - `\n`) and scrolling forward (with line feeds).

That's definitely not enough to do a pager, so not doing it is *correct*. That fish ever displayed a pager if $TERM is set to dumb is a bug.

So, I would take a look at your tests, but they all start with

> # Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved

So I don't believe I'm allowed to. There's a LICENSE file in the root directory, but it seems logical to me that file headers would take precedence.

Anyway, from the filename and context I assume you're using `expect`, so instead of entering the command you'd want to complete and then a tab and then hacking around the pager's formatting, simply send `complete --do-complete="whatever you want to complete"` and a newline and just look at the lines it outputs.

There really is no use in testing the pager, because if the pager breaks that's not your responsibility (it'd be a fish bug) and if the pager changed (e.g. sort order or number of columns) it would require you to do awkward version detection.

**Comment by krobelus** [comment]
Yeah, we use non-interactive fish to test the behavior of `complete`. That should cover your use case.

Since `expect` uses `TERM=dumb`, the actual completion insertion can't really be tested with that.
[Here](https://github.com/fish-shell/fish-shell/pull/7744/files#diff-f3039f6d54f71f1c10ffac8fc0633d294776fec4156d75886f5f020f62108db7R1) is an idea on how to test interactive functionality using tmux. However, that's quite fish-specific and should probably make it into the fish sources, should you go into that direction :)

**Comment by krobelus** [comment]
The fact that ada03d350938e6d14d359bde0ed6e5b02b3f9c1f broke dumb terminals is interesting. If there is a good use case we can probably fix that somehow (revert? special case dumb?). Let's see where else dumb terminals will pop up?

**Comment by binshengliu** [comment]
You are right we only test completion candidates and basic interactions. We used dumb so we didn't need to test all the paging and formatting that come with other TERMs.

In 3.1.2, it seems there was no pager with TERM=dumb. What I observed is the candidate shows up one by one on the command line (maybe \r and overwriting? not sure how it works internally). Anyway, that behavior made testing much easier. With other TERM (like ansi), there were always formatting characters hard to avoid.

`complete --do-complete` is cool and definitely gonna try it out! The reason I still hope to have the basic completions (one candidate per TAB) with dumb is we can test the basic interactions (TAB) without assuming the formatting. 

From a user perspective, I also hope `ls prefix[TAB]` could show/cycle completions if that's technically possible. Now `ls unambiguous_prefix[TAB]` works and `ls ambiguous_prefix[TAB]` doesn't which is a bit inconsistent.

**Comment by binshengliu** [comment]
BTW, I guess the licencing shouldn't be a problem for you to have a look at as I'm not working for Facebook too. I was just adding fish completion to their project.

**Comment by faho** [comment]
>What I observed is the candidate shows up one by one on the command line (maybe \r and overwriting? not sure how it works internally)

That seems like fish decides to do one column because of the width, so if you e.g. shortened your candidates fish could suddenly decide that it can fit in more columns and print more. It's not something you want to rely on in any case - which is also why this isn't something you want to test interactively.

>complete --do-complete is cool and definitely gonna try it out! The reason I still hope to have the basic completions (one candidate per TAB) with dumb is we can test the basic interactions (TAB) without assuming the formatting.

Those aren't the basic interactions you are responsible for. If you want to know that "somestr" only matches "somestring", you can do `complete --do-complete="somestr"` and see that it only prints "somestring".

>If there is a good use case we can probably fix that somehow (revert? special case TERM=dumb?). Let's see where else dumb terminals will pop up?

@krobelus The problem is that "dumb" doesn't specify enough features to be able to print a pager, so trying to do so means actual dumb terminals would be broken.

>BTW, I guess the licencing shouldn't be a problem for you to have a look at as I'm not working for Facebook too.

Frankly, no. You decided that it's not a problem for you, that doesn't make it not a problem. Those headers are at best misleading and superfluous and at worst actually change the licensing for the worse, and I don't want to take the risk to find out.

They should be removed, or Facebook should be honest and change the LICENSING file to match.

**Comment by binshengliu** [comment]
I tried the complete command and it works great for testing custom completions. I think I misunderstood what you meant by the header. Now I see. Since you have clear reasons this shouldn't be supported, I think I should close the issue.
