### ISSUE TITLE
Bug: How come it takes a long time after entering the incorrect command before it shows the next prompt?

### ISSUE THREAD

**Issue by Joe23232** [fish-shell/fish-shell#7841]
If I put in some incorrect command that does not exist, for some weird reason it takes a long time before it again shows the prompt.

![jfMYRrXM8F](https://user-images.githubusercontent.com/34926497/111871146-cb352400-89dc-11eb-8dc5-4b2f81743624.gif)

Here is what I mean.

I have tried running these commands (after logging in back to `bash`) after `cd`ing into the directory of the config files of `fish`.

```bash
rm -fr fish
```
I tried to uninstall `fish`:
```bash
sudo pacman -Rcs fish
```

ANd then I did reinstall it:
```bash
sudo pacman -S fish
```
I did a reboot and still the same issues. Any idea?

**Comment by faho** [comment]
So we have this issue template, it would be nice if you filled it out.

In particular your fish version is of interest here. Is this fish 3.2.0 or fish 3.1.2?

Do you have any customization? Can you confirm that you did indeed remove ~/.config/fish? The way you phrased it makes it sound like you deleted ~/.config/fish/fish, which won't help.

Then there's the simple question: What changed about your system recently? Did you update anything, change any configuration?

This now sounds like it's just *nonexistent* commands. In that case fish executes the `fish_command_not_found` function, which will try to ask pacman, which will take a while.

What happens if you replace that handler with the one that just prints the error:

```fish
function fish_command_not_found
    __fish_default_command_not_found_handler $argv
end
```

**Comment by faho** [comment]
Yeah, arch *just* updated to 3.2.0, and that adds a command-not-found handler based on pacman's file database.

Unfortunately that's kinda slow, but there's nothing we can do about that. You can disable it by doing as I said above, or you can install `pkgfile` which is faster.

**Comment by IlanCosman** [comment]
Honestly I'd say the feature isn't worth the cost right now. It's remarkably annoying because you _just_ mispelled something (already a small annoyance), and instead of immediately correcting it you have to wait for a second like the machine is laughing at you. 😄

Could we perhaps cache the pacman file database on startup or something?

**Comment by faho** [comment]
>Could we perhaps cache the pacman file database on startup or something?

Nope, it's not caching, subsequent calls aren't really faster.

This just takes a bit, depending on the machine. On my laptop it's ~1.5s, which seems okay since trying to execute an unavailable command shouldn't happen too often - it's already highlighted as invalid!

**Comment by Joe23232** [comment]
> Yeah, arch just updated to 3.2.0, and that adds a command-not-found handler based on pacman's file database.

How come it uses `pacman`, I don't quite get that if I am not using `pacman`, just `fish` to type in an incorrect command?

> You can disable it by doing as I said above

```
function fish_command_not_found
    __fish_default_command_not_found_handler $argv
end
```

Do I just add this to the config file?

**Comment by IlanCosman** [comment]
> How come it uses pacman, I don't quite get that if I am not using pacman, just fish to type in an incorrect command?

When Fish can't find the command you entered, it consults with your package manager, in this case `pacman`, to look for a relevant package to install. If `pacman` is slow, then that process might take a bit.

> Do I just add this to the config file?

Yes.

**Comment by zanchey** [comment]
That's obnoxiously slow in my view; could we suggest that the Arch maintainers disable this by default? It's pretty reminiscent of the `sl` utility, which was supposed to train people to type `ls` correctly but in fact just caused rage.

**Comment by Joe23232** [comment]
> When Fish can't find the command you entered, it asks your package manager, in this case pacman, to look for relevant packages to install. If pacman is slow, then that process might take a bit.

Oh that makes perfect sense and that could be a nice handy feature actually.

> Yes, you add it to config.fish

Thanks mate :)

> Unfortunately that's kinda slow, but there's nothing we can do about that. You can disable it by doing as I said above, or you can install pkgfile which is faster.

You mentioned I can also use `pkgfile`. So is this built on top of `pacman`?

**Comment by Joe23232** [comment]
@IlanCosman

Hi mate, I don't think I am supposed to add:

```
function fish_command_not_found
    __fish_default_command_not_found_handler $argv
end
```
to the config file.

What am I supposed to do for it to stop searching through `pacman`?

**Comment by IlanCosman** [comment]
> What am I supposed to do for it to stop searching through pacman?

You... add that snippet to your `config.fish`. Or, to make it easier, you can just paste the snippet into the commandline, run it, and then run `funcsave fish_command_not_found`.

**Comment by Joe23232** [comment]
> > What am I supposed to do for it to stop searching through pacman?
> 
> You... add that snippet to your `config.fish`. Or, to make it easier, you can just paste the snippet into the commandline, run it, and then run `funcsave fish_command_not_found`.

That seems to have worked, thanks :) But how does it work? This entire command?

**Comment by IlanCosman** [comment]
The snippet simply makes the `fish_command_not_found` function pass its arguments through to fast default command_not_found handler. When you paste the snippet into the commandline, Fish stores that function only for the current shell instance. `funcsave` writes that stored function to disk so that it will automatically be loaded on shell startup, thus always overriding the slow pacman-based `fish_command_not_found`.

**Comment by Joe23232** [comment]
Thanks mate, but what does this line: `__fish_default_command_not_found_handler $argv` mean actually?

**Comment by IlanCosman** [comment]
You should read about basic Fish syntax in the [Fish introduction](https://fishshell.com/docs/current/index.html). What you're specifically asking about though is [functions](https://fishshell.com/docs/current/index.html).

**Comment by Joe23232** [comment]
Ok thanks mate.

**Comment by krobelus** [comment]
I'd also prefer disabling this by default; I opened https://bugs.archlinux.org/task/70103

**Comment by krobelus** [comment]
I feel it's disruptive more often than helpful, because most errors are simple typos - often I don't take time to notice the "error" highlighting.

**Comment by faho** [comment]
Alright, it's disabled. Let's see if the pacman people manage to speed it up, then we can enable it again.

**Comment by markstos** [comment]
`pacman` is noticeably slow on my system, but `pkgfile --search nvim` returns about 10x faster-- 132 ms vs 1,380l ms for pacman.

I think checking for `pkgfile` instead of `pacman` provides a reasonable middle ground.

**Comment by faho** [comment]
>I think checking for pkgfile instead of pacman provides a reasonable middle ground.

We... [already do](https://github.com/fish-shell/fish-shell/blob/783736c77f904e5177ec98be5678b7785b7b687d/share/functions/fish_command_not_found.fish#L50-L59). We've checked for pkgfile since fish 2.2.0 from 2015.
