### ISSUE TITLE
Starting fish background job in an event/variable handler borks commandline for duration of job

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7842]
`fish, version 3.2.1-5-gd79f86407`
Tested on MacOS and Arch

https://user-images.githubusercontent.com/6318351/111875553-acd91500-8957-11eb-9495-c1eacbb3ab9b.mp4

```fish
function on_foo --on-event foo
    fish --command "sleep 3" &
end
```

Syntax highlighting will be disabled for the full duration of the background job, i.e if you replace `sleep 3` with `sleep 10` it'll take 10 seconds to come back instead.

This also happens with `--on-variable`, and I presume all other handlers though I haven't tested them. 

Interestingly this bug doesn't appear when running other commands such as `sleep` or `kill`, it only seems to work with `fish`.

Not sure if this is a regression.

**Comment by IlanCosman** [comment]
@faho Is there anything I can do right now with fish script to remove this problem? Fish 3.3 might be a while and this is an annoying bug in my project 😄

**Comment by faho** [comment]
@IlanCosman I'll leave you in the capable hands of the others, I'm taking a break.

**Comment by IlanCosman** [comment]
@ridiculousfish 😅 Sorry to bother, but would you happen to know a fancy Fish trick to get around this?

**Comment by krobelus** [comment]
@IlanCosman on Linux you can use `setsid` to launch fish in a new process group.
Then the background fish is in a new process group that doesn't own the terminal, so 013a563ed0fc2cb400d914efffbeb8b87061673c does the job.

```fish
function on_foo --on-event foo
    setsid fish --command "sleep 3" &
end
```

I'm not sure about which portable solution is best. Apparently `nohup` works as well instead of `setsid`.

**Comment by IlanCosman** [comment]
Huh, it seems simply setting `status job-control full` fixes this. Sick!

**Comment by faho** [comment]
>Huh, it seems simply setting status job-control full fixes this. Sick!

@IlanCosman That is emphatically *not* a knob you want to touch (to be honest it should not exist to begin with, but we're working on that).

Instead simply set the background process's stdin to /dev/null:

```fish
    fish --command "sleep 3" </dev/null &
```

Since the issue is that fish only checks if the group controlling the stdin *terminal* is its group, just make it so that stdin isn't a terminal.

**Comment by IlanCosman** [comment]
Thanks a ton @faho! Yah, setting the job-control was a bit sketchy, I noticed it was setting the user's `last_pid` outside of Tide but decided that minimal risk was an ok tradeoff.

This is why you can't take a break Fabian, I need you too much ❤️😂

**Comment by zanchey** [comment]
This reproduces for me in 3.2.1, so I don't think it's a regression.

**Comment by faho** [comment]
It's a regression from 3.2.0, caused by  013a563ed0fc2cb400d914efffbeb8b87061673c

**Comment by zanchey** [comment]
OK, I'd prefer to keep the regression tag for "things that aren't in a release" as it means I can skip over them for the release notes.
