### ISSUE TITLE
fish_config doesn't open web browser on OpenBSD

### ISSUE THREAD

**Issue by rapenne-s** [fish-shell/fish-shell#7909]
# Required checks and output

```
$ fish --version
fish, version 3.2.1
$ echo $version
3.2.1
$ uname -a
OpenBSD kongroo.lan 6.9 GENERIC.MP#441 amd64
$ echo $TERM
xterm-256color
```

I tried `sh -c 'env HOME=$(mktemp -d) fish'` with no success.

# Problem

When I use `fish_config`, fish is opening the html file with `nvim` while not giving it full focus on the terminal so input is mangled and shared across fish_config and nvim run, using Ctrl+Z I can get out of nvim and press `ENTER` to leave fish_config. I made an asciinema record available here : https://asciinema.org/a/EYwE21chl9l1wa9wN0GxudOqV . While in the editor I'm trying to escape it with `:q` but as I said, the input is not all sent to the editor. I tried with both sakura and xterm as terminal emulators. Sometimes nvim edits a html file with a redirect code sometimes it's an empty file with the message `shutting down` displayed on the top of the terminal.

in `fish/tools/web_config/webconfig.py`, I got the output of `webbrowsers.get().name` and the result on my system is `xdg-open` but yet, if I create an html file in `/tmp/something.html` and use `xdg-open file:///tmp/something.html` I correctly have Firefox opening the file and not nvim. In the processes list, when running `fish_config` I see a `/bin/sh /usr/local/bin/xdg-open file:///tmp/somethingrandom.html` but yet vim is started.

I tried on a fresh profile and I have the same issue, I remember I've been able to use `fish_config` on my system a few months ago so I downgraded fish to 3.2.0 and 3.1.2 with no better success.

I am out of ideas to understand what's happening here. It seems fish_config is using xdg-open but the wrong program is used, while using xdg-open manually it works fine as expected.

**Comment by faho** [comment]
You probably want to set $BROWSER.

**Comment by rapenne-s** [comment]
Using `set -x BROWSER firefox` it works fine.

**Comment by faho** [comment]
Yeah, this is somewhere in the depths of xdg-open's awkwardness. Something about the environment changes enough that its fickleness breaks. (If you want to feel some pain, I suggest opening xdg-open in an editor)

Unfortunately I don't believe there's anything we can do here - the weird input/output thing seems to be caused by python's webbrowser module not setting up the terminal (and why would it, it's not made to launch terminal apps).

But really, the fix is to burn down xdg-open and replace it with something a tenth of the length (but that would require cooperation from the various desktops on a sensible system).
