### ISSUE TITLE
Runaway cursor when using escape+undo in vi mode

### ISSUE THREAD

**Issue by krobelus** [fish-shell/fish-shell#7910]
Steps
1. `fish_vi_key_bindings`
2. `bind -m insert u undo`
3. Press <kbd>Alt+u</kbd>

The cursor jumps to the first character of the line (inside the prompt).

**Comment by faho** [comment]
Figured it out: `alt+u` is `\eu`, which is executed as two bindings:

- Escape, which switches to normal mode and does "repaint-mode"
- "u", which then does undo

The issue is that repaint-mode does a `screen.reset_line()` but then only does a repaint if it is "needed" - well, it is needed because we just reset the line, moving the cursor to the beginning.

One possibility is to skip the repaint *and* cursor move if the mode prompt buffer didn't *change*.

https://github.com/fish-shell/fish-shell/blob/3ce67ecbd2348fbe13e86a00bea6ce998710729a/src/reader.cpp#L3571
