### ISSUE TITLE
No Escape of Backslash in Single Quotes

### ISSUE THREAD

**Issue by MagicMuscleMan** [fish-shell/fish-shell#7923]
If you use backslashes a lot (and you have to for e.g. regexps), Fish's approach of not being able to get rid of escaping even by using single quotes gets quickly quite annoying. From the [documentation](https://fishshell.com/docs/current/#quotes):

> The only meaningful escape sequences in single quotes are \\', which escapes a single quote and \\\\, which escapes the backslash symbol.

I suggest, to change single quote such that a backslash is not seen as an escape sequence except if it is followed by the single quote character itself. This would get rid of a lot of escaping and would still allow all possible expressions like

- '\\' to get a backslash
- '\\'' to get a single quote
- '\\\\'' to get a backslash followed by a single quote

Besides simplifying the syntax for users, this would also increase compatibility to other shells like Bash, which are more user friendly in this regard.

Note, that this suggestion is different than the one proposed in #4907 as the escaping of the single quote would not be changed, therefore the presented counter argument does not apply.

Example of the problem (the one from today which finally convinced me to submit an issue):
`apt policy wireless-regdb wireless-tools | rg '^(\\S+)[\s\S]+?\\* (?:\\S+\\s+){3}(\\S+)' -Uor '$1 $2'`
needs five slashes more than Bash and really makes an already hard to read command even more hard to read.

If you fear backwards incompatibility, this could still be implemented with a feature flag with default on as discussed in #5556.

**Comment by krobelus** [comment]
That's an interesting idea, providing Bash-compatibility for many practical cases, while being different from the POSIX single-quote behavior.
fish's quoting is closer to languages like Python, which is nice because many people are familiar with that quoting style.
but fish lacks raw string literals.. can we hijack backticks? :thinking:

**Comment by faho** [comment]
> but fish lacks raw string literals.. can we hijack backticks? thinking

I suspect this is a joke, but in case it's not: Backticks are an *awful* character to do anything with, and I would appreciate if we didn't use them at all.

**Comment by faho** [comment]
So, the current rules for escaping in single-quotes are:

- `\'` becomes `'`
- `\\` becomes one `\`
- `\s` stays `\s` (with any other character except for `\` and `'` in place of `s`)

Your proposal is

- `\'` becomes `'`
- `\\` stays `\\`, if not followed (possibly indirectly) by `'`
- `\\` becomes `\` if followed by `'`
- `\s` stays `\s`

So the only case this touches is `\\`. It's slightly more complicated as it has one more case.

Unfortunately I don't believe it's feasible *even with* a feature flag, because that would require you to write

```fish
if status test-feature less-escape
    # (not entirely sure that's what you meant, but this is just to illustrate)
    apt policy wireless-regdb wireless-tools | rg '^(\S+)[\s\S]+?\* (?:\S+\s+){3}(\S+)' -Uor '$1 $2'
else
    apt policy wireless-regdb wireless-tools | rg '^(\\S+)[\s\S]+?\\* (?:\\S+\\s+){3}(\\S+)' -Uor '$1 $2'
end
```

If you want to be compatible with both settings.

And, given our experiences with feature flags, I don't think people will actually do that by themselves so it'll just lead to a ton of bug reports in projects written in fish.

My position is the same as with #4907: "Changing the behavior of single quotes now is quite the compatibility break, and adding yet another way of quoting doesn't sound appealing". Sorry.

**Comment by MagicMuscleMan** [comment]
The proposal I thought about actually is
- `\'` becomes `'`
- `\s` stays `\s` (with any other character except for `'` in place of s)

I think you need your additional two cases only to support a real backslash at the end of single quotes. For me it would be fine to not support this case in single quotes, because if it's needed it can always be written as `'string'\\`, which has slightly lower user complexity as `'string\\'` because the user does not need to think about one additional rule.

So it were really easy: Single quotes do quote everything with the only exception to be able to print the quote character itself.

I agree with your reasoning about the feature flag, even if I only thought about it as a compatibility flag, but the benefit is probably negligible. So, yes, it would be a compatibility break towards older Fish versions and would need a suitable Fish version change to be implemented. On the other hand, it would increase compatibility towards other shells and would make Fish more user friendly. For me the pros are worth the cons.

I wondered how big of a compatibility break this would be. Besides a lot of completions (which could be converted automatically on first look), this seems to affect 7 files on my PC. I used
`rg '(\'.*?\\\\\\\\)|(\\\\\\\\.*?\')' (locate .fish)`
to find these files, which might have missed some occurrences in multiline quotes, but this could be improved upon. However, I think it neatly shows the ridiculous syntax we are talking about here.

I would of course volunteer to change all files included in fish itself, however, I'd probably need support/guidance to change the parser. But this work is obviously only be worth doing if there is a chance that the change could be accepted.

**Comment by faho** [comment]
>it can always be written as 'string'\\, which has slightly lower user complexity as 'string\\' because the user does not need to think about one additional rule.

That's now a special *case* you need to think about! "If I want a backslash at the end, I need to end the quote first". That's not obvious and awkward.

-------

Our current rule here is fundamentally reasonable. It's simple, consistent, familiar (it matches similar rules in e.g. python) and allows expressing everything.

Your proposal leads to fewer backslashes being needed and, if we were to write an entirely new shell, would be a contender (along with "to add a literal double quote, use `''`", and a slew of other changes to bad design decisions in early fish).

However the compatibility break here is too big a problem - it's hard to audit, annoying to support both variants (because you still need to write the old version for years to come) and I don't see e.g. oh-my-fish (which is a semi-active project that still supports fish 2.2) adopting any of this, which leads to unhappy users.

So I am rejecting this, sorry!

**Comment by MagicMuscleMan** [comment]
Thanks for considering the proposal, @faho . Although I obviously hoped for a different decision and have different opinions of the weighting of the arguments, I really appreciate your time to state your reasoning clearly.

**Comment by floam** [comment]
> but fish lacks raw string literals.. can we hijack backticks? 🤔

Backticks are actually one of the only symmetrical symbols that are naturally enclosing of inner text we really have left. As a bonus, they are basically safe to use and will not disrupt the arguments much of anything takes because other shells use them too!

**Comment by faho** [comment]
>Backticks are actually one of the only symmetrical symbols that are naturally enclosing of inner text we really have left

Unfortunately, backticks have a lot of issues.

They are hard to distinguish from single quotes, they are awkward to type on key layouts that assume you might type french words sometimes (like the german qwertz that defaults to having them as deadkeys) and they don't actually quote or enclose in these languages, so we would use them for an unfamiliar purpose. Plus this would use them for quite a different purpose than other shells, making switching from them more confusing. And using them this way would add another quoting style that would also have to be explained.

Like most sigils, the usage wouldn't explain itself, but would have to be memorized. And given that this isn't something that comes up constantly, it's hard to remember.

**Comment by floam** [comment]
I didn't know that about your German keyboard layouts, @faho. How troublesome is it for your average person to use them in markdown like on on GitHub or Reddit on e.g. Linux?

**Comment by faho** [comment]
>How troublesome is it for your average person to use them in markdown like on on GitHub or Reddit on e.g. Linux?

It's annoying - personally I set the nodeadkeys variant everywhere, but that requires at the very least knowing that it *exists*. And in some cases it requires work to add it.

Of course it's not impossible to use it - you just have to type more so the layout figures it should insert it by itself (I always end up typing \`\` and erasing the second one if I end up on a deadkeyed system), but it makes it a much less ergonomic character by default.

**Comment by floam** [comment]
On a US keyboard layout it's the key right next to 1 and under escape, and does not require shift or anything. It's the easiest key to enter of `, ', or ". I probably wouldn't be a fan of some boutique difficult-to-enter character as syntax either. Is this the most common layout in Germany, like if I bought a laptop today? 

I do think most people, or at least most people younger than you or I are going to be much more likely to associate  the character with either markdown's code mode or the-most-verbatim quotes in JavaScript since 2015 rather than confusing them with command substitution shell syntax.

**Comment by faho** [comment]
>Is this the most common layout in Germany, like if I bought a laptop today?

To a first approximation the *only* layout in Germany. Other layouts are specialty items you would have to specifically order.

And I'm assuming it's similar for french/belgian/swiss. I don't know how it's in other languages.

----

But anyway, while I see this might be interesting to you, that's just one part of the problem, and makes it sound like it's a regional thing when it isn't. The glyph being confusable isn't just a regional issue. It being a reuse of the same character with a different meaning is another, as is the issue with having a third quoting style to teach, ...

**Comment by nanikamado** [comment]
How about using raw string literals like [`r####"the Rust's one"####`](https://doc.rust-lang.org/stable/reference/tokens.html#raw-string-literals)? You can put as many `#`s as you like around `""`, and you don't have to escape anything if you put enough `#`s. We already use `#` for comments so we should use some other character, but anyway it might be easy to type and not confusing.

For example,
```fish
alias latex-paren='ruby -pne \'$_.gsub!(/(?<!\\\\\\\\left)\\(/,"\\\\\\\\left(");$_.gsub!(/(?<!\\\\\\\\right)\\)/,"\\\\\\\\right)")\' -i'
```
would become
```
alias latex-paren=r##"ruby -pne r#"$_.gsub!(/(?<!\\left)\(/,"\\left(");$_.gsub!(/(?<!\\right)\)/,"\\right)")"# -i"##
```
