### ISSUE TITLE
Piping to Head Gives Error 'write: Broken pipe'

### ISSUE THREAD

**Issue by lucas979797** [fish-shell/fish-shell#7924]
#### System Info:
Fish Version: `3.2.1`
OS: macos Big Sur
Terminal: Terminal (macos default)

#### Problem:
Running `history | head -n 1` produces the following output:
```
echo hello
write: Broken pipe
```
`echo hello` is expected as that is the last command I ran, but `write: Broken pipe` is not.

Looking back at previous issues, #2516 from 2015 does seem to be somewhat related to this, so I'm thinking that it might be some kind of latent bug?

**Comment by faho** [comment]
What happens is that `history` writes data, then head reads that data and once it has a line closes the pipe.

This is a common problem in shellscripts (also a big issue in conjunction with bash's `set -e` and `set -o pipefail`). There isn't an actual fixable *problem* here, the only real changeable thing is the error message.

What you want is to use $history[1] instead of piping to `head`. That will give you the full item *even if it is multiline*, without this error, and will be quicker, so it's the better choice regardless.

**Comment by lucas979797** [comment]
@faho thanks for the explanation and work around suggestion. Makes sense why the error is being thrown. Using `$history[1]` works perfectly for my use case so i'm happy.
