### ISSUE TITLE
Mode prompt shown once at startup

### ISSUE THREAD

**Issue by ollef** [fish-shell/fish-shell#7949]
I've set

```
function fish_mode_prompt
end
```

in `~/.config/fish/functions/fish_prompt.fish` and it works most of the time, but the `[I]` is shown on the first prompt when I start Fish, so the first two prompts look like this when my prompt is `%`:

```
[I] %
%
```

I'm using Fish version 3.2.1.

**Comment by ollef** [comment]
It works if I move the `fish_mode_prompt` function to `~/.config/fish/functions/fish_mode_prompt.fish`. Perhaps this is the expected behaviour?

**Comment by faho** [comment]
It is, yes.

**Comment by ollef** [comment]
I found the relevant documentation about this here: https://fishshell.com/docs/current/#autoloading-functions

Cheers!

**Comment by faho** [comment]
What happens is this:

- fish executes fish_mode_prompt. To do that it reads fish_mode_prompt.fish. Because you don't have one, that's still the default
- fish executes fish_prompt, reads fish_prompt.fish - this redefines the mode prompt, but it has already been executed.

Which explains why it works with a separate fish_mode_prompt.fish.

In general autoloading works by reading a file named after the function. Other functions given in that file will also be *read* and defined, but that will only happen once the file is loaded to begin with. In general you should keep functions in their own files or define them eagerly e.g. in config.fish.

**Comment by ollef** [comment]
Thanks for the explanation!
