### ISSUE TITLE
Exiting fish from a keybinding which calls a function

### ISSUE THREAD

**Issue by enricozb** [fish-shell/fish-shell#7967]
# Environment
```
version: fish, version 3.2.1
uname: Linux xibalba 5.11.16-arch1-1 #1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000 x86_64 GNU/Linux
term: alacritty
```

The behavior I'm reporting still occurs under `sh -c 'env HOME=$(mktemp -d) fish'`.

# Problem & Reproduction
The following keybinding _correctly_ exits the shell when typing ctrl+t:
```
bind \ct exit
```
However, the following keybinding _does not_ exit the shell when typing ctrl+t:
```
function myexit
  exit
end
bind \ct myexit
```
Why is this the case?

**Comment by faho** [comment]
The `exit` builtin doesn't immediately *exit*, it marks the session for exit so fish has a chance to clean up, e.g. to fire the exit handlers and such.

In a binding, you're still in the read loop, and it only checks the "session should exit" flag the next run through, so trying to run any command then exits.

Just `exit` works because there's also an `exit` bind function, so `bind \ct exit` does the equivalent of `commandline -f exit` - which also works here as a workaround.

**Comment by enricozb** [comment]
Thanks for the explanation.
