### ISSUE TITLE
Empty expansions void “first character” status of home expansion and opening brackets

### ISSUE THREAD

**Issue by kopischke** [fish-shell/fish-shell#7971]
Running fish version 3.2.2 (installed via Homebrew) on macOS 11.3 in the stock Terminal.app. I tried fish without third-party customisations by executing `sh -c 'env HOME=$(mktemp -d) fish'` and checked whether it affected the behaviour I am reporting (it did not).

---------

A quirk of fish’s parser I have run into while working on my syntax plugin for the [Nova editor](https://nova.app) (yes, it’s me again; I am so frightfully sorry!) is that there are special rules applying to the first character of some tokens, but hoi that “forest character” is pinpointed when expanding is incosistent.

Specifically:
1. Function names cannot start with `-`;
2. Any command argument starting with `-` is considered an option (up to `--`, at least for fish’s own command);
3. Variable expansion has to start with `$`;
4. Unquoted `[`  is not considered an unpaired bracket when starting a shell word;
5. Unquoted `~` triggers  home directory expansion when starting a shell word.

All well and good, until you realise that empty expansions (by which I mean things like empty quotes ~~or line continuations~~ \[EDIT: nope, these work as expected\], which expand to nothing for the purpose of the next shell word) affect those items differently:

```fish
function ''-foo; ls`; end # => invalid function name “-foo”
ls ''-a                   # => executes “ls -a”
var=foo echo ''$var       # => foo
''[                       # => unpaired bracket error
ls ''~                    # => no such file or directory
```

The first three I expected, the last two less so; after all, all of these expand to the string starting after the empty single quotes.

**Comment by faho** [comment]
>`ls ''~                    # => no such file or directory`

`~` expansion only happens at the start of a word, and that's *during expansion*, so before quoted things are removed. Just like e.g. `$v''ar` expands a variable called `$v`, not `$var`.

Which also explains `echo ''$var`. (note that, unlike bash, fish sets the variable override *first* and then expands - we decided that the other way around was useless).

>Any command argument starting with - is considered an option (up to --, at least for fish’s own command);

Option handling is *up to the command*! It's not done by "the shell" proper, even for builtins it's run by the builtin logic. Which explains

```fish
ls ''-a                   # => executes “ls -a”
```

Here `ls` receives, after expansion, quoting etc: `-a`. The `''` is entirely eliminated.

Which also explains

```fish
function ''-foo; ls`; end # => invalid function name “-foo”
```

Conceptually, `function` receives `-foo` as first argument. This is also *correct*, because if you tried calling a function named `''-foo` later that would just resolve to `-foo` again.

>Unquoted [ is not considered an unpaired bracket when starting a shell word;

That's #2485 again - bracket handling is awkward.

The rest seems to be entirely expected. Closing in favor of #2485.

**Comment by kopischke** [comment]
I am aware that this is rarely going to be a problem in practice (_aka_ “who writes that?”), but it might point to  problems with the interaction of fish’s rather generous expansion rules and token validation in the parser.

**Comment by faho** [comment]
For all but the third, there *are no problems* in the expansion rules and token validation. It's entirely expected! That is how this works! If you don't expect it your mental model is wrong! You simply misunderstood the order of steps. It goes "expand stuff", then "remove quotes" and then "parse options" (which is also typically in the actual external command).

Funnily enough, all of these are shared with bash, because that does the operations in the same order. Try `ls ''~ ''-a` in that and you'll get the same results.

And the third is another manifestation of bracket handling being this awkward additional half-parsing step - hence #2485.

**Comment by kopischke** [comment]
@faho:

> The rest seems to be entirely expected.

Yes, the first three are expected, as I noted – I included them to highlight the inconsistency. The home expansion issue I have to disagree with you about: you are, of course, technically entirely correct, but I’d argue understanding this degree of parser logic is a bit much for a shell user. Coming fto this without intimate knowledge of parser working, this behaviour is surprising, even if it is not a bug in the implementation as such. I’d expect something that is _effectively_ `~` to be treated as `~`.

**Comment by kopischke** [comment]
> Funnily enough, all of these are shared with bash, because that does the operations in the same order. Try `ls ''~ ''-a` in that and you'll get the same results.

Well, and there was me thinking fish aims to be less quirky than bash 😉. My point still stands, and I’d expect the same thing in bash, were I to still expect anything from bash …
