### ISSUE TITLE
Variable definitions accept escapes for names and index operators

### ISSUE THREAD

**Issue by kopischke** [fish-shell/fish-shell#7980]
Running fish version 3.2.2-258-g555af3761 (built from HEAD via Homebrew) on macOS 11.3.1 in the stock Terminal.app. I tried fish without third-party customisations by executing `sh -c 'env HOME=$(mktemp -d) fish'` and checked whether it affected the behaviour I am reporting (it did not).

---------
This is related to #7969 and a follow-up to the fix for that issue. While 555af37616893160ad1afb208a957d6a01a7a315 stops character escapes being accepted in variable expansion, **character escapes are still valid**

1. **for variable identifiers and the indexing operators in variable definitions via `set`,**
2. **and for variable identifiers only (as indexing is not valid there) for `for` loop variables.**

555af37616893160ad1afb208a957d6a01a7a315 thus introduces an inconsistency where

```fish
# variable expansion behaviour
fo=ba foo=bar echo $fo\157        # => bao

# variable definition behaviour
set fo\157 bar; echo $foo         # => bar
set foo\1331\135 qux; echo $foo   # => qux
for \157 in (seq 5); echo $o; end # => 1 2 3 4 5
```

which I find utterly surprising behaviour.

**Comment by kopischke** [comment]
Also note that disallowing escapes in variable identifiers and indexing is consistent with how fish handles these in variable overrides. Personally, I’m all in favour, just not a fan of the inconsistent state this is in after 555af37616893160ad1afb208a957d6a01a7a315.

**Comment by krobelus** [comment]
Two possible directions are
1. go back to the old  and declare this undefined behavior for now
2. reject escapes in all the examples you give

variable overrides are the odd one, because are detected before escapes are expaned. This does not work:

    fo\157=bar echo $foo

Which can probably be changed to be closer to their older siblings `set` and `for`.

If we detected brackets earlier in the parser, this wouldn't be an issue. Maybe we can simplify the implementation.

**Comment by kopischke** [comment]
Well, I sympathise with punting “we’d need to refactor the parser” to the “fish-future” milestone, but seeing this is a bit of a blocking issue for my syntax plugin, I have to ask: whither https://github.com/fish-shell/fish-shell/commit/555af37616893160ad1afb208a957d6a01a7a315? Will that stay in 3.3 (where it is slated for release)? My apologies for being a pain in the _gluteus maximus_, but variable expansion parsing with that commit is incompatible with parsing without it …

**Comment by krobelus** [comment]
ok, let's maybe add it to the next milestone. Though I don't really know what the final behavior should be.

> seeing this is a bit of a blocking issue for my syntax plugin

How come? I think a syntax plugin can be very useful even without accurate support for escapes in variable names, because those are rare.

**Comment by kopischke** [comment]
> > seeing this is a bit of a blocking issue for my syntax plugin
> 
> How come? I think a syntax plugin can be very useful even without accurate support for escapes in variable names, because those are rare.

To be sure it can. How far you want a plugin to cover usage cases beyond the usual ones I think of as a matter of system robustness and of friendliness towards users with non mainstream usage patterns. I tend towards heavy emphasis on those by dint of “works well for common cases, you’re on your own beyond that” software falling me too often, but that is just my preference.

**Comment by faho** [comment]
So this is the last issue remaining in the [3.3 milestone](https://github.com/fish-shell/fish-shell/milestone/27).

As such, I'd like to have a decision on what to do.

Basically, as I understand it, this is an inconsistency introduced by 555af37616893160ad1afb208a957d6a01a7a315. We now can set variables that we can't then read.

So we have four options:

- also disallow `set`ing variables with these names, which would be a bit of a layering violation because once `set` is executed the expansion already happened, so we need to do this in the parser
- fix #7969 in a different way
- revert 555af37616893160ad1afb208a957d6a01a7a315, and re-introduce #7969 - especially just for 3.3
- for 3.3, do nothing

The first two of these require some *work*, and the first is a bit unclean and complicates the grammar.

The latter two are both easy.

Now, because this is one of those edge cases that don't really happen unless you're trying to break things, I don't think it's high priority either way. Real, actual, code that people write in anger is always more important than anything theoretical you can come up with when messing around.

However, because this needs to be specifically called out in the CHANGELOG as a breaking change (whether it actually breaks real code it is the only "Syntax change" listed for 3.3), and because this introduces a new *restricting* inconsistency (as opposed to allowing too much like before), I vote for reverting 555af37616893160ad1afb208a957d6a01a7a315. That then allows us to fix the inconsistency later on in a more comprehensive way - this probably involves making braces a proper part of the grammar (we have numerous issues with `{}` and `()` as well).

I'm also not sold on escapes in variable names being much of an issue. Specifying `$fo\6f` is weird, but it's not clear to me that it's *wrong*. Not allowing them means you get to treat `\\` as a separating character for variable names, but allowing it makes it possible to spell characters that would otherwise look weird (e.g. because of font or locale constraints). But the bigger issue is certainly allowing to specify `[]` slice operators as escapes.

If nobody has any objections, I'll do the revert next weekend, or sooner if we want to cut a release before then.

**Comment by zanchey** [comment]
I think we should revert it for now.

**Comment by faho** [comment]
Alright, I've reverted it now (7059eaa4abff89e7ae13e3962fdb5ae5342a11d2).

Reopening #7969 and closing this.
