### ISSUE TITLE
Resizing iTerm2 window causes a huge mess

### ISSUE THREAD

**Issue by jacobcxdev** [fish-shell/fish-shell#7985]
When resizing iTerm2's window on macOS 11.3.1, anything in the terminal's window becomes a huge mess.

https://user-images.githubusercontent.com/27970288/117654209-5933bc80-b18d-11eb-93f1-9f95d209b582.mp4

```fish
$ fish --version
fish, version 3.2.2

$ echo $version
3.2.2

$ name -a
Darwin Jacobs-MacBook-Pro.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin

$ echo $TERM
xterm-256color
```

**Comment by faho** [comment]
Fish has no influence over what happens when you run `man`, and with $fish_handle_reflow set to 0 it doesn't do anything in response to the resize, so there isn't anything we can do here.

You appear to be using a multi-line right prompt from somewhere, which isn't supported on our end. It's only achievable with hacks, and most likely one of those is listening to SIGWINCH (the resize signal), which leads to breakage like this.

Fundamentally, once the terminal handles reflow on resize, the application can't be handling it as well - there's an unsolvable race between them.

**Comment by jacobcxdev** [comment]
> You appear to be using a multi-line right prompt from somewhere

I'm running a clean install of Fish with the following Fisher plugins:
```
ilancosman/tide
jethrokuan/z
franciscolourenco/done
joseluisq/gitnow
jorgebucaran/autopair.fish
acomagu/fish-async-prompt
```

To be honest, I'm not sure whether that would be from one of them or iTerm2 itself.

**Comment by faho** [comment]
Either tide, which is a prompt, or fish-async-prompt, which is a massive hack to allow async prompt handling, should be causing your issue while running man.

**Comment by faho** [comment]
Must be something else in your config listening to SIGWINCH then.

Either way, question has been answered and there's nothing for fish to do here, so I'm closing this.

**Comment by chandanrakholia** [comment]
Solution for this error: 
1. go to iterm > settings > Advanced
2.  find "Terminal window resize smoothly" and make it "yes".

This will solve window resizing issue in iterm2.

**Comment by akshatgoel07** [comment]
> Solution for this error:
> 
> 1. go to iterm > settings > Advanced
> 2. find "Terminal window resize smoothly" and make it "yes".
> 
> This will solve window resizing issue in iterm2.

It did not work!

**Comment by BbIXOD** [comment]
same here with kde terminal. alacrity also does pretty weird thing on resize if there are already something was written

**Comment by yousihy** [comment]
The only workaround for this was just to type `clear` and it seems to refresh the terminal properly. I wish there is a better solution. But at least it works
