### ISSUE TITLE
The `open` command creates an intermediate window?

### ISSUE THREAD

**Issue by tamis-laan** [fish-shell/fish-shell#7994]
I have a fish function in my `fish.config` to swallow commands that I run from the terminal:

``` fish
# Window swallowing
function swallow 
  if test (count $argv) -eq '0' 
      echo "No arguments given"
  else
      set id (xdo id)
      xdo hide 
      $argv > /dev/null 2>&1
      xdo show "$id"
  end
end

# Completion for window swallowing
complete -c swallow -f -a '(set -l cmd (commandline -opc; commandline -ct); complete -C"$cmd[2..-1]")'
```

However after updating to version `3.2.1` the `swallow` command no longer works with `open`. It looks as if `open` opens a new window and then starts the application causing the first window to close and thus unhides the terminal.

**Comment by faho** [comment]
The `open` command just refers to an operating system specific implementation. On systems that use `xdo` that's most likely xdg-open.

And because xdg-open is awful and *sometimes* waits for what it started, but most of the time doesn't, we now background and disown what it does unconditionally - see #7215. This just brings it in line with how it works *mostly*, and how it's most useful. 

Unfortunately your thing relies on `open` waiting for the window, and that doesn't work, and was never supposed to work. On other desktops with a different xdg-open backend it wouldn't have worked to begin with.

**Comment by tamis-laan** [comment]
Strange because this only happens after i updated fish to `3.2.1` I did not update anything else.

**Comment by faho** [comment]
That's because #7215 added the workaround for the xdg-open bug you're relying on.

**Comment by faho** [comment]
Alright, to summarize:

- `open` calls `xdg-open` where appropriate
- `xdg-open` refers to a backend for your desktop environment - e.g. `kde-open` for KDE, `gnome-open` for Gnome
- It also has a "generic" path for when it doesn't recognize your DE
- This "generic" path, in contrast to the others, does not fork off what it starts and instead waits for it
- This is unexpected behavior and a bug in xdg-open
- Since 3.2.0 we work around it by backgrounding and disowning xdg-open
- Your code requires whatever it starts to stick around in the foreground, which for xdg-open requires that bug to be present
- Your code would not work in e.g. KDE or Gnome because those already fork off
- Your code now works nowhere because we work around the bug

Sorry. I'd love it if someone wrote a better replacement for xdg-open that gave you the option of waiting or not, and we could add support for it in `open`. But until that happens we're better off making `open` work the same, expected, way everywhere.
