### ISSUE TITLE
Need a better and less expensive default prompt

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#8]
The default prompt in fish is quite expensive (something like 10 fork calls). Let's make one that's still interesting but cheaper.

**Comment by faho** [comment]
With the `string` stuff merged, we could probably bring this down to 3 by replacing the `sed` call.

Otherwise `hostname`, `cut` and `uname` are only called once on first load, so with that we should have a zero-fork prompt for every call but the first. I don't think it can be less expensive. (cut might also be replaced with IFS/read or `string`)

**Comment by faho** [comment]
With #2448 merged, I can't see how we could improve it more, so I now consider this fixed.
