### ISSUE TITLE
Prompt glitches with emoji

### ISSUE THREAD

**Issue by y0ast** [fish-shell/fish-shell#8003]
When I paste `☺️` into my terminal, it backspaces the prompt one character. Additionally if this command is autocompleted later, it will backspace too and even go into the previous line for multiple autocompletions.

This problem happens in `alacritty` and `foot`, but *not* `kitty`. The problem is that `☺️` (U+263A, U+FE0F) is width 2, but both alacritty and foot render it as U+263A or `☺` which is width 1. This means fish gets the length of the line wrong and starts "backspacing". `kitty` renders (U+263A, U+FE0F) as `☺️` which is what `fish` expects and everything is fine (this was fixed in #7237 I believe).

Interestingly, this problem does not show up on the asciinema recording, since it renders the emoji correctly... !

It looks like this on `foot` terminal:
![1621087504_screenshot](https://user-images.githubusercontent.com/485778/118364110-f7a98e80-b58e-11eb-9fc9-3381b1bd4439.png)

and the same on `alacritty`.

It's quite painful when I now type `echo` it'll try to autocomplete `echo ☺` but for every character I type I go further backwards into the previous line. The only workaround is to manually delete it from my history.

---

fish 3.2.2
Linux arch 5.12.3-arch1-1
Terminal is `foot` or `alacritty` (but `kitty` is fine)

```
  sh -c 'env HOME=$(mktemp -d) fish'
```
Did not change behavior

Related to:
https://github.com/fish-shell/fish-shell/issues/7237
https://github.com/fish-shell/fish-shell/issues/7959

**Comment by faho** [comment]
If the terminal renders it at the wrong width, there is nothing we can do.

The terminal and fish have to agree on the width, there is no protocol or anything to communicate it.

**Comment by y0ast** [comment]
That's fair enough! I do want to point out that `kitty` (and iTerm2) is the exception here, and most terminals consider `☺️` single width.

As a salient point, the `☺️` emoji causes problems when running `kitty` with `bash`, which does think its single width.

**Comment by faho** [comment]
>Is there perhaps some way to avoid autocomplete from flushing too many characters?

There isn't, because it doesn't. It handles the width correctly (if it didn't we'd fix that), and then your terminal bungles it. Unfortunately:

- There is no feasible way for us to know if the terminal screws it up, because there is no feasible communication channel here
- There is no feasible way to add specific characters to a quirk list because that would depend on knowing the terminal, but
- There isn't even a feasible way for us to detect which terminal you're running with which idea of the width, because it's both configurable ("handle ambiguous characters as double-width" is a popular option) and depends on OS libraries like libc (which provides wcwidth, which is commonly used for this sort of thing)

I'm afraid Unicode in terminals is basically broken and probably gonna stay that way for a long long time.

**Comment by y0ast** [comment]
Thanks for the very detailed reply!
