### ISSUE TITLE
calling fish shell with -l from bash shell, and do rsync/scp will hang forever

### ISSUE THREAD

**Issue by thuzhf** [fish-shell/fish-shell#8036]
fish --version: 3.2.2
echo $version: 3.2.0

uname -a: Linux myhost 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

echo $TERM: screen

how to reproduce:
1. two servers: server1, server2
2. on both servers, set bash as your user's login shell
3. in the end of ~/.bash_profile, paste: 
``` bash
if command -v fish &>/dev/null; then
    export SHELL=`which fish`
    [ -z "$FISH_VERSION" ] && exec "$SHELL" -l
fi
```
4. on server1, do: `touch /tmp/test_abc`
5. on server2, do: `rsync server1:/tmp/test_abc /tmp/`
6. now you will see the program hangs (forever)

The reason someone does this is because s/he doesn't have root access on some servers and fish shell is not in /etc/shells, but s/he still wants to use fish as his/her login shell.

**Comment by faho** [comment]
Yes, scp and friends do a lot of things via $SHELL. In this case just calling `$SHELL` starts fish *without passing it the arguments*, so it won't actually be doing anything. And passing it the arguments won't work because those are meant for bash.

This bit needs to only be done for interactive shells, e.g.


```sh
if [[ $- = *i* ]] && command -v fish &>/dev/null; then
    export SHELL=`which fish`
    [ -z "$FISH_VERSION" ] && exec "$SHELL" -l
fi
```

(also `which` should just be `command -v` here - `which` is an awkward external command)

-----

>fish --version: 3.2.2
echo $version: 3.2.0

Either this is wrong and you haven't actually checked, or you still have an old fish session running from before the upgrade to 3.2.2. I suggest restarting fish.

**Comment by faho** [comment]
Here's your issue:

- Log in via ssh as the offending user
- It starts a bash login shell, which starts a fish session
- In that fish, run `bash -lc 'echo foo'` - this is supposed to only run `echo foo` and exit, but because of the `-l` starts a login shell which reads bash_profile, which starts fish ($FISH_VERSION isn't typically exported, so the check for it shouldn't fail - if it does you need to temporarily remove that check to reproduce the issue). Since fish doesn't receive commands to run it checks if stdin is a terminal and then starts an implicitly interactive session, so you end up with a fish session waiting for your input.

**Comment by thuzhf** [comment]
> Yes, scp and friends do a lot of things via $SHELL. In this case running `$SHELL` starts fish _without passing it the arguments_, so it will see that stdin is a terminal and hang around waiting for commands that never come. And passing it the arguments won't work because those are meant for bash.
> 
> This bit needs to only be done for interactive shells, e.g.
> 
> ```shell
> if [[ $- = *i* ]] && command -v fish &>/dev/null; then
>     export SHELL=`which fish`
>     [ -z "$FISH_VERSION" ] && exec "$SHELL" -l
> fi
> ```
> 
> (also `which` should just be `command -v` here - `which` is an awkward external command, and even in bash `$(command -v fish)` is recommended over backticks)
> 
> > fish --version: 3.2.2
> > echo $version: 3.2.0
> 
> Either this is wrong and you haven't actually checked, or you still have an old fish session running from before the upgrade to 3.2.2. I suggest restarting fish.

You're right, I still have an old fish session running.

**Comment by thuzhf** [comment]
Thanks a lot! That's exactly what you described here, and the solution you suggested solved my confusion and my problem.
