### ISSUE TITLE
Strict mode options

### ISSUE THREAD

**Issue by timbertson** [fish-shell/fish-shell#805]
When writing scripts in bash, I always use some combination of:

 - `set -e` (fail if any command fails)
 - `set -u` (fail if any undefined variable is referenced)
 - `set -x` (print each command before it's executed)
 - `set -o pipefail` (a failed command in a pipeline will cause the parent command to fail)

Additionally, it would be nice to have an option like pipefail that applies to subshells (i.e causes `echo (false)` to return nonzero status).

It doesn't seem like any of these are available in fish, which doesn't usually matter for interactive use but kills it as a scripting language for me (which is a shame, because fish's sensible variable-expansion would make it much harder to accidentally get quoting wrong).

Any chance of adding similar features?

**Comment by oconnor663** [comment]
> A more idiomatic way to do this in fish would be an event handler, something like this:
 ```
function die --on-event command-failed
    exit
end
```
but I'm not sure how this could be lexically scoped.

Solving this problem in general would be *very* useful. I've run wanting to `cd` just for the duration of a function. (So did [these guys](https://stackoverflow.com/questions/22540798/change-directory-in-fish-function-and-return-to-original-directory-after-abort).) It sounds like the same solution could apply there.

The brute force answer might be to make blocks aware of the cwd and of event listeners and other things like that, so that then we could have some special command for block-scoped-cd or block-scoped-on-signal. But that seems like a lot of special casing and work. One idea that seems to work well is what Python does with [context managers](https://docs.python.org/3/library/contextlib.html). If there was some mechanism for defining a function to "do work now -- and then do this other thing when the current block ends", then it would be super easy to define block-scoped cd and listeners and everything else, and fish could consider defining some of those functions by default too.

**Comment by Ericson2314** [comment]
For the `or` problem. we could preserve the meaning of `;`, `; and`, and `; or`, but make it so that newlines have the meaning of `; and`.

Might sound weird to bash users, but Rust has got me use to final `;` or lack thereof making a difference.

**Comment by oconnor663** [comment]
Special casing `or` for strict mode makes sense to me, unless that would be a huge change in the way `or` is implemented now. (Is it actually just a regular command?)

> 3) Just make pipefail the default any only behavior of pipes. Any reason why it should not be?

That sounds great. For commands in a pipe whose exit status you want to suppress, you can use do something like this (assuming `or` does get special-cased):

    ... | begin command_with_weird_error_codes; or true; end | ...

This is the same thing you'd do in bash with `pipefail` on, just with fish's grouping syntax. Alternatively, you could define a function that does the same thing, and put that in the pipe.

**Comment by faho** [comment]
See also #510, which asks for a `set -e` equivalent.

**Comment by nateleavitt** [comment]
I also agree with this. I've been trying to write a fish script that does a variety of things with command line arguments, and it's been difficult. Maybe fish scripts don't fit well here...?

**Comment by hexsel** [comment]
I'd be ok with some functions disallowing failures or having handlers.  Alternatively, maybe a _try-catch_ style construct?

    try
        cp abc.txt /someinvalidfolder
    catch
        echo $_fish_failure $_fish_failed_cmd $fish_failure_line
        exit $_fish_failure_code
    end

**Comment by Ericson2314** [comment]
For process failure, `begin ...; end; or ...` *is* try-catch. Conversely, I don't think using undefined variables should be recoverable.

**Comment by hexsel** [comment]
@Ericson2314 maybe I'm missing something, the documentation for "begin" (http://fishshell.com/docs/current/commands.html#begin) seems to mention it "The block is unconditionally executed" which is the opposite that this is suggesting.

The point here IMO was to avoid writing a 100 line script with every single line preceded by "and".

**Comment by Ericson2314** [comment]
Sorry, I meant that with respect to one of the proposals above where we change the meaning of `;` or make newlines implicit `; and` instead of implicit `;`. Then the first command to fail causes the entire begin block to fail.

**Comment by cben** [comment]
I scripts/blocks fail on first failing command (whether opt-in or by default),
I think a non-silent failure would be more useful.
Don't just stop, print the offending command and exit code to stderr.  Like `make` does.
Not sure that'll *always* be desired, but I think silently stopping, with no hint where it stopped or that it stopped at all [1] is — in most cases — a bug in itself.

Verbose failure would also mean `foo; and bar` at top level also needs some special casing.

About newline differing from `;` — it's a clever hack but will backfire on this quite sensible style:

    long_command_1
    or long_command_2
    or long_command_3

IMHO too subtle non-orthogonality.  No matter how well it's documented, people who reformat code between `;` and separate lines will face some very surprising debugging.

It sounds like special-casing the `or`/`and` builtins solves everything?  
(Custom or-like functions that inspect output from previous commands would still be mostly useless.)

**Comment by Ericson2314** [comment]
Yeah it's a dirty trick, I won't deny it. But note that there is no need to use `or foo` on its own line when plain `foo` means the same thing (in "strict mode").

I must say, I am not a fan of the `; or`/`; and` syntax. These are *binary* operators, so syntactically making them look like unary ones is completely misleading.

**Comment by cben** [comment]
> note that there is no need to use or foo on its own line when plain foo means the same thing (in "strict mode").

The reason to say `or foo` on its own line is when commands are long and putting each on its own line improves readability.  I don't want strict mode to break the `;`/newline equivalence, because I think nobody will remember the subtle difference.

----

I'm not _entirely_ a fan of the unary or/and either.  It's just that until recently it had no deal-breaking drawbacks.  The other complaints I've seen were:

1. It's not like in bash.
2. `if` and `while` take one command (unlike bash which has `then`/`do`) so require awkward `if begin COND1; and COND2; end; BODY; end`.
3. Nesting conditions requires awkward `begin COND1; or COND2; end; and COND3`.

I'd say (2) and (3) are actually complaints about begin..end.
(2) has been practically solved in #1428 by making `and`/`or` significant syntax — they magically group after `if`/`while`.

If we didn't care about backward compatibility, I'd say the right syntax is not unary nor binary — it's Lispish *surrounding*.  Using "and"/"or" in prefix position wouldn't read like english (and is too incompatible) but perhaps:
```
all
    COND1
    either
        COND2
        COND3
    end
end
```
would be good?

However given compatibility it seems we're gonna keep unary or/and, yet make them more and more significant syntax.
Which is slightly messy, as they can no longer be explained simply as "check $status and maybe run command"...

**Comment by Ericson2314** [comment]
Hmm I like it! `begin`, `all`, and `any` ("either" implies 2, and "any" is used for this elsewhere) are 3 basic kinds of blocks, each of which interpret newline/`;` in different ways. Safe mode is about making other blocks act like `all` rather than `begin` (Including the implicit top-level block).

**Comment by timbertson** [comment]
I'd argue that `either` / `any` could be misleading - I might expect something called `any` to bail out as soon as one command succeeds (like a chain of `||` in bash). I think `try` may be a better name. There's no `catch`, it's just that failed statements in a `try` block do not automatically cause termination. So it'd be:

```
all
    COND1
    try
        COND2; or echo "That failed, but we don't care..."
        COND3
    end
end
```

..and by default (to maintain backwards compat), the topmost block is implicitly a `try`. I don't know how `begin` would interact with this - maybe it could turn into a deprecated alias for `try`?

**Comment by Ericson2314** [comment]
@timbertson haha, I would expect that too, because that is what I intended! `begin...end` is `;` chain, `all...end` is `&&` chain, and `any...end` is `||` chain. Because there is no `catch` as you noted, I prefer `all` over `try`.

Now `all` and `any` should mean the same thing in "safe mode" and "scary legacy mode". Maybe `begin` would be called `unconditional` in "safe mode" to be a bit clearer? We can bikeshed a shorter name, or just keep `begin`.

Let's just disallow `or` and `and` in "safe mode", since nobody has a good plan for implementing them or making them not terribly confusing.

**Comment by timbertson** [comment]
I think that may be a bit too drastic - making inside-out lisp-ish logic for 

What about a very targeted change - by default, everything is strict. But we introduce a `try` keyword which can prefix any command. It won't prevent that command from returning a nonzero $status, but it will (internally, somehow) prevent the terminate-on-error logic. So you could then do:

```
do_something
try something_which_might_work; or echo "that failed!"
```

`and` and `or` still do what they're supposed to (although `and` becomes less necessary), while we get an obvious prefix (`try`) for commands that we're allowing to fail.

**Comment by Ericson2314** [comment]
what do these do?
```fish
begin; begin; try false; end; end;
begin; not try true; end;
```

IMO, the correct way to think about strict mode is not that things terminate on error, but that ignored error codes are bubbled up until something inspects them. I'd argue that it is due to this confusion that `set -e` is implement so inconsistently in traditional shells (http://www.in-ulm.de/~mascheck/various/set-e/).

Also is it so drastic if strict mode is optional? Like the old syntax, it re-uses an existing syntactic form `foobar...end`, rather than introducing something new such as infix syntax.

**Comment by anordal** [comment]
I just learned the hard way that in bash, `set -u` treats empty arrays as an error. Except of course, [there is a "dreadful" workaround](http://stackoverflow.com/questions/7577052/bash-empty-array-expansion-with-set-u). That's a big enough tradeoff of readability for correctness that I don't know if I want to type `set -u` in bash ever again.

Which leads me to conclude that bash is unusable for safe shellscripting (if such a thing exists), at least we can do better. I guess `set -u` is also the least controversial of the "safe mode" options — maybe we could even have it always on, and no way to turn off.

Anyway, in `set -u` mode, `$a` in fish would mean the same as `${a[@]+"${a[@]}"}` in bash.

**Comment by actionless** [comment]
is anyone working on it or it's still on the discussion stage?
i am feeling like i could try to implement it if it's cleared up how the syntax for that could look like

**Comment by krader1961** [comment]
I just quickly skimmed this issue. It is most definitely still in the discussion stage. And some of the proposals, like make the default behavior be "strict", could only be done in a major release because it breaks backward compatibility.

**Comment by actionless** [comment]
i personally prefer the way with setting some env var for that

**Comment by OlivierDupre** [comment]
For information, I have a workaround for `set -x` equivalent.
```
set cmd "My command here with my "'$param" here and "$anotherParam
echo $cmd
eval $cmd
```

Of course, this is less elegant, but it works... ;)

**Comment by anordal** [comment]
Yes, `set -x` is for debugging, and there are other ways to debug that are nearly as good. Plus, people tend to clean up their debug printouts when done debugging, as opposed to leaving `set -x` enabled, which I'm no fan of – I agree with Dag that it could be an option to fish. Anyway, I think `set -x` is a separate discussion, as it doesn't make the language any stricter.

But while I'm at it:

> echo $cmd

My favourite is `echo «$cmd».` Exploits cartesian product to print each argument enclosed in those funny guillemet quotes (choose something funny on your keyboard) so you can tell the arguments apart in case they contain whitespace.

**Comment by anordal** [comment]
Why do we need a separate mode?
* in bash, `set -e` is useless in interactive mode because any failing command logs you out. But I think it should be possible to have the same strict language (wrt. failure propagation) interactively, and just not get logged out.
* backward compatibility (with people's scripts). Or we could do it for fish 3.0 and forget about backward compatibility (à la python3).

> > > fail if any command fails
> >
> > fish relies more heavily on functions than most shells, and most functions cannot easily be made compatible with this
> 
> I don't understand why - I would have thought that to implement this, a function failure would be treated like a command failure. And a failed command call made in a function would cause the function to also fail.

I don't understand either. Are return values hard to control? Do we use $status to communicate other things than failure? I do know a builtin that does that: `count` with no arguments returns 1 on success. We have at least 15 functions that depend on that (grep for "if count"). In my mind, that just means we must fix those as well. As a first step, the documentation should avoid advertising any entropy in $status on success.

**Comment by Ericson2314** [comment]
@anordal I agree this should work fine in interactive mode. Every real language with fatal errors doesn't exit the REPL when one is encountered.

Comparability is still a concern though---consensus to a make a breaking release doesn't mean the problem goes a way but just that people decided to move forwards despite it.

**Comment by kopischke** [comment]
Having had to contend with side effects of _rbenv_’s decision to go “strict” I can only deem idiotic \[[1](https://github.com/nobodyzzz/rbenv-plugin/pull/2), [2](https://github.com/nobodyzzz/rbenv-plugin/pull/3)\], I must say I am less than sold on it. I tend to agree with GreyCat’s assessment that _bash_’s `set -e` is a [is a non-feature, bordering on an antipattern,](http://mywiki.wooledge.org/BashFAQ/105) very much inferior to explicit error checking.

**Comment by Ericson2314** [comment]
@kopischke I agree that bash's `set -e` is broken, and introduces as many subtle gotchas as it alleviates. But... I think that's just sh being sh and not an idea with the problem itself?

See my comment in https://github.com/fish-shell/fish-shell/issues/805#issuecomment-169250041 I think sh's crucial mistake was to approach the mode from a "failure means exit" perspective. Then things like `x=${foo}` and `if false ...` are important exceptions to the rule. If one thinks instead in terms of making sure errors are not implicitly ignored, as I say in comment, then it's clear that the assignment to `x` "remember" the exit status, and `if` handles the exit status, so aborting should not be done.

Not only is this a good mental model for the fish user, but it also lends itself to an implementation strategy (make sure whatever holds the exit status isn't destroyed but moved), so I'm confident that we can avoid gotchas.

**Comment by kopischke** [comment]
> IMO, the correct way to think about strict mode is not that things terminate on error, but that ignored error codes are bubbled up until something inspects them.

Well, that is certainly a much more sane concept than the `errexit` mess, but I am still dubious: what bit the `rbenv-plugin` developers in the, ahem, lower back, and what I tried to fix was **the assumption that return codes above 0 signal an error**, when, in the case of `grep`, the code is a Boolean return value. With exit values the only reliable way to communicate results without worrying about `stdout` or `stderr` (which can be suppressed and often have another dedicated use, as is the case for `grep`), that kind of behaviour makes sense and is orthogonal to the assumption that non-zero is an error.

_bash_’s `errexit` adds insult to injury, but at the core is an issue every “error handling” mechanism will have to cope with, barring us all starting to use something like PowerShell.

> Also is it so drastic if strict mode is optional?

That depends entirely on how painless it is to break out of its scope, be it in plugins / extensions / subscripts or globally without affecting the main script, I’d say.

**Comment by ridiculousfish** [comment]
Thanks for your links to the ruby issues - very instructive. One idea I had is that strict mode is a property of a scope. This would avoid opting code like plugins in when they don't expect it. Do you think that would help?

**Comment by kopischke** [comment]
@ridiculousfish that would certainly help: as far as I’m concerned, the more limited and explicit the scoping of this kind of feature, the better.

**Comment by Ericson2314** [comment]
Yeah strict mode can and should be lexical. I'd like it to eventually become mandatory (say a breaking fish release), but even then we have three kinds of blocks: do all commands, break at first failure, break at first success. (Look earlier in the thread to read more about this.)

@kopischke In your case I see two principles. If the non-standard error codes are explicitly handled, then no implicit aborts will happen. If the non-standard error codes are not implicitly handled, then whatever information they additionally encode will be discarded anyways. I'd make a function, taking a command and args, which calls the command than converts the error code to the standard. Then the error code *of the function* will be handled implicit by strict mode in the original script, which will be the correct behavior.

**Comment by anordal** [comment]
Agree that when it comes to modes, lexical scoping is preferrable over global state. But what about inner scopes (such as `if`, `while`, `for` and so on) of a strict mode scope, are they also strict? I think they ought to be, all the way in to a scope that is explicitly not, but not cross function boundaries:

```fish
begin --break-on-failure
    if true
        # still in strict mode
        begin --no-break-on-failure
            # strict mode disabled
        end
    end
end
```

I think the requirements are:

1. it must not cross software module boundaries. I suppose not crossing function boundaries would satisfy this.
2. it makes sense to restrict the number of places one has to look for it
3. as a safety feature, it's not good if it's easy to accidentally disable by adding an inner scope

Reason for (2):  You cannot proofread a piece of code without knowing if strict mode is on or off: In normal mode, you must handle the errors; in strict mode you must handle the non-errors (usually by `; or true`). Expected errors *should* be handled anyway, for human readable error messages, but that's a different concern.

> the assumption that return codes above 0 signal an error, when, in the case of grep, the code is a Boolean return value.

aka. the non-errors. But depends on context, as you *would* consider it an error if grep doesn't find the match in a situation where you expect it to.

Reason for (3): The way I look at all kinds of strict mode, they are safety features: They make sloppy code fail, so the paranoid programmer can know that the code is free of certain classes of bugs. Specifically with --break-on-failure, that if the program works, it means that no exit status handling is missing.

**Comment by krader1961** [comment]
> 1. it must not cross software module boundaries. I suppose not crossing function boundaries would satisfy this.

Presumably this rule also includes `source` since it represents a module boundary akin to python's `import`.

FWIW, I used to use `set -e` (or `set --errexit`) a lot. Then I learned better habits and stopped using it for the crutch that it is. So I'm not a fan of introducing it to fish but do recognize for certain classes of scripts it has utility. If we do add this feature it absolutely has to have lexical scoping and function and module boundaries represent different lexical scopes. It also must not be the default behavior.

**Comment by actionless** [comment]
>Then I learned better habits

do you mean handling each command's return code/output or smth else?

**Comment by krader1961** [comment]
Closing this as a duplicate of issue #510. While it is true this issue was originally broader than just dealing with unhandled command failures the fact is the discussion has been focused almost solely on the latter. So I'm going to close this as a duplicate of #510. Other topics, such as a bash `set -x` equivalent for fish should be discussed in issues dealing with each specific feature (e.g., #3427).
