### ISSUE TITLE
The PPA does not have builds for Ubuntu 21.04

### ISSUE THREAD

**Issue by IndianBoy42** [fish-shell/fish-shell#8051]
I am installing from here to get the most up to date stable version: https://launchpad.net/~fish-shell/+archive/ubuntu/release-3

An interesting thing is happening, I am on Ubuntu 21.04 and according to launchpad there isn't a build registered under this version. `apt` nevertheless updates from this PPA, but for some reason installs `3.2.1-1~focal`, not even the latest focal version.

I dont know enough about how APT and PPAs work to really diagnose the problem.

My workaround was to add the ppa with `groovy` instead of `hirsute`, and then it found 3.2.2. I dont know if the problem would go away if you provided builds for hirsute (21.04) directly

**Comment by IndianBoy42** [comment]
![fishppa](https://user-images.githubusercontent.com/5981889/121242539-4537c380-c8cf-11eb-8cd5-829f0b1c4a71.png)

Here is the output of `apt-cache madison fish` to show the latest versions of fish it is finding from different repositories

As you can see, when i add the repository as hirsute it has `3.2.1`, while groovy has `3.2.2`

**Comment by zanchey** [comment]
Yeah, I must have forgotten to copy the package over at some stage. I've done it now.

The reason that it has a distribution name in the version is because of the design of apt repositories, which can only contain one binary package for any particular version number. There's been talk of an automatic reversion/rebuild function in Launchpad for ages but it hasn't come about yet.
