### ISSUE TITLE
How to reset cursor shape after entering neovim via a keybinding

### ISSUE THREAD

**Issue by noib3** [fish-shell/fish-shell#8066]
fish --version: 3.2.2

I have
```
set fish_cursor_default block
set fish_cursor_insert line
```
in my config, but if I enter neovim through a keybinding, the cursor shape is not reset to a line when I exit and it stays a block, even if I'm back to insert mode.

A way to test this is with
```
bind -M insert \cS 'nvim -u NONE ~/foo'
```
and then pressing `Ctrl+s`.

**Comment by kidonng** [comment]
https://github.com/neovim/neovim/wiki/FAQ#cursor-style-isnt-restored-after-exiting-or-suspending-and-resuming-nvim

**Comment by noib3** [comment]
@kidonng I think it can be fixed from fish since this only happens if I execute neovim via a keybinding.

**Comment by faho** [comment]
It probably won't be fixed from fish.

The issue here is that key bindings aren't really *meant* to execute interactively running applications. We don't do a number of things inside keybindings because they don't make sense there - like resetting the cursor.

That's because we really have no way to know if the thing you are executing inside the key bind is an interactive application or just e.g. a simple `grep`, so if we did reset the cursor we'd reset it *all the time*, which is not only wasteful but can also interfere with other things (we'd be generating output to the terminal at random times).

So, the correct solution is indeed for nvim to set its cursor - it already sets the cursor shape on mode switch by default, apparently, so tbh it could probably set the cursor shape on start.

But anyway, typically you'd use a function instead of a key binding for starting interactive apps - `function nfoo; nvim -u NONE ~/foo; end`.

**Comment by faho** [comment]
Question has been answered, closing!
