### ISSUE TITLE
Add configuration option to disable `/bin/sh` fallback

### ISSUE THREAD

**Issue by ericonr** [fish-shell/fish-shell#8086]
fish 3.3.0

One thing I really like about fish is that it doesn't just implement "POSIX" like behavior for the sake of being compliant; this included the `/bin/sh` fallback. It's dangerous, as exemplified in https://github.com/fish-shell/fish-shell/pull/7802#issuecomment-796709965, and very confusing for users, because the error message goes from "useful" to "complete gibberish that sh prints out".

Arguably #7802 should have implemented it as opt-in, since it's a non feature that only really helps the 0.1% using binaries based on cosmopolitan; the rest of fish users will get a worse experience due to a corner case that could have been solved by the cosmopolitan docs recommending running things with `sh ./path/to/executable`.

That PR implements a weird heuristic and lead to new platform specific fixes that were made necessary for it (e74b9d53df886c9c03b89edb57a094354f09f35b), and more special conditions (694e112a9b90c4f72e8cf813e42bb80b928241bd) that have to be tested and taken into account when figuring out edge cases.

So that 99.9% of fish users don't have to "pay" this price, I'd request that this feature be made opt-in; if that isn't possible, an option to opt out at least would be of great help.

**Comment by faho** [comment]
No, thank you.

This is the heuristic that all other shells also follow, and it's not the sort of thing that should have an option.

**Comment by ahesford** [comment]
This is a case of being so preoccupied with whether or not we could, we didn't stop to think whether we should. The example in the comment linked above shows what fantastic nightmares can befall thoughtless application of the no-shebang rule. Script authors can avoid this by making explicit the intended environment in a shebang, and users can avoid this by explicitly invoking the shell on an un-shebanged script. Failing to run an un-annotated script at least forces the user or the author to reevaluate what is happening.

The primary justifaction for merging #7802 seems to be "this is consistent with what other people are doing, because they want to be consistent with past practices." This is a ridiculous justification that fails to withstand scrutiny in all sorts of human endeavors. Sticking to the Linux and Unix realm, it's the same kind of argument used to oppose the [`/usr` merge](https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/). Sometimes past behavior is foolish because resource constraints or lack of foresight produced the simplest, rather than the best, implementation. We should strive to make things *better*, not preserve poor design decisions.

If walking back #7802 isn't on the table, I join ericonr in advocating for opt-in or opt-out behavior to rein in potential destruction.

**Comment by faho** [comment]
>If walking back #7802 isn't on the table

It is not.

>advocating for opt-in or opt-out behavior 

Neither is that. That's not how fish works. We don't hide features behind flags.

>The example in the comment linked above shows what fantastic nightmares can befall

[...]

>rein in potential destruction.

That's *vastly* overstating the issue. The chance for "destruction" is minimal. It only happens if 1. you've written a fish script without a ".fish" suffix or a shebang, and 2. that fish script happens to do something harmful in posix shells. (or technically other programming languages but those have even less overlap with posix script)

I wrote the comment linked above and I know how careful I had to be to write a working example. It's not really something that happens by accident.

It's also super easy to entirely avoid - use a shebang or a ".fish" suffix.

----

We made this change for a reason, we're not just walking it back because of arguments *we already made* and decided against - with improvements. We don't do opt-out or opt-in because a feature might not be entirely to your taste.

Note that this already looks like it's going in circles. Please try to either bring something *new* to the discussion or refrain from commenting.
