### ISSUE TITLE
[Question] Unknown color

### ISSUE THREAD

**Issue by rky-do** [fish-shell/fish-shell#8115]
Hi.
I'm not good at English.
sorry.

fish is error message.
Very in trouble.

```
set_color: Unknown color '^/dev/null'
```

fish: 3.3.0
Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

Is there a solution.
I'm sorry in poor English.

Thank you.

**Comment by faho** [comment]
Fish 3.3.0 disabled the `^` redirection syntax that was deprecated in fish 3.0.0, 2.5 years ago.

This can still be undone, for the time being, with

```fish
set -Ua fish_features no-stderr-nocaret
```

However, what you really want to do is to find the offending line and replace `^/dev/null` with `2>/dev/null`.

Something like

```fish
grep '\^/`' -r ~/.config/fish
```

This will find something like

```fish
set_color red ^/dev/null
```

Replace it with

```fish
set_color red 2>/dev/null
```

and if it's from a plugin pester the author. This has been deprecated (and could already be disabled) since fish 3.0.

**Comment by rky-do** [comment]
It was very helpful!!!!!!!
Apparently the plugin is the cause...

Close issue.

Thank you.
