### ISSUE TITLE
Suggestion: Functional Filter and Map

### ISSUE THREAD

**Issue by ramonGonzEdu** [fish-shell/fish-shell#8135]
```
fish, version 3.2.2
```
```
3.2.2
```
```
Linux linx-PC 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```
xterm-256color
```

This is a basic suggestion that would add two (or three) builtins:
* Filter - Takes 2 parameters. 1st, a fish list. 2nd, a fish function name. It then runs the provided function once for each element of the list and prints a new list containing only the list items that returned 0.
* Map - Takes 2 parameters. a fish list. a fish function name. It runs the provided function once for each element of the list and prints a new list containing the results of the function calls.
* Foreach? - same as map but has no output.

These are meant to be equivalent to the javascript `Array.prototype.map`, `Array.prototype.filter`, and `Array.prototype.forEach` functions in a more efficient way

**Comment by ridiculousfish** [comment]
Do you have a use case in mind? In practice I think most commands already accept multiple arguments, in particular `string`.

**Comment by hyiltiz** [comment]
The "idiom" usage for `filter`, `map` and `fold`/`reduce` operations on the command line is usually first separate items (typically by newlines) and pipe through, and use utilities such as `grep`, `xargs`. I can see some advantage of including these functionals as fish internals, since that might allow mapping over not just strings (`grep`, `xargs` etc. all assume strings) but over numeric lists and maybe even list of lists etc. However, ultimately, if you are dealing with complex data structures such as those, you probably are better off with a programming language designed to deal with those, rather than twisting the `s/arm/fins/g` of your shell.

**Comment by faho** [comment]
Okay, this proposal is quite vague and appears to not have gone beyond the idea that higher order functions are, as the kids would say, "cool".

It lacks an explanation of how these things would fit, or what they would really be useful for.

In a shell model, with anemic data structures and expensive function creation and no local scope for functions, this doesn't really work.

E.g.

```fish
filter var function
```

wouldn't work as such. It would be

```fish
set -l var foo bar baz
function func
    # do stuff
end
set -l out (filter var function)
```

instead of

```fish
set -l out
for f in foo bar baz
    # do stuff
    set -a out result
end
```

or more likely

```fish
set -l out (func foo bar baz)
```

At which point I have no idea what the `filter` form helps.

So, I believe this would be a "Yeah, nah" in australian.

Sorry, but no.
