### ISSUE TITLE
Help with youtube-dl parameter in alias

### ISSUE THREAD

**Issue by amithiel** [fish-shell/fish-shell#8136]
Hi there,
I'm new to fish, and i'm pulling my hair trying to get this to work.
So, i added an alias to fish:

alias download='youtube-dl --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s"'

That won't work: No matches for wildcard.

What have i tried so far:

alias download='youtube-dl --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" "$argv"'
alias download='youtube-dl "--extract-audio --audio-format mp3 -o" "%(title)s.%(ext)s" "$argv"'

Nothing works! however, pasting this full command directly in fish, it works:

youtube-dl --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" "URL"

What am i doing wrong in the alias?

cheers

**Comment by faho** [comment]
The solution to all problems with `alias` is to make your own function directly:

```fish
function download
    youtube-dl --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" $argv
end
```

However, in your case the issue seems to be using an older version of fish that had a bug in alias. So upgrade and that's gone. But really just define functions directly, it's easier and barely longer.

**Comment by faho** [comment]
>Hi! thanks for the reply, however, that didn't work either. same error :(

In that case, since there is definitely no wildcard in any of that, check `type youtube-dl`. You probably have that overridden with another alias/function.

**Comment by amithiel** [comment]
that's odd, it works fine in bash.

~ » type youtube-dl                                                                                             
youtube-dl is /usr/bin/youtube-dl

**Comment by faho** [comment]
Again: This does not feature a wildcard of any kind. There is no `*` or `?` anywhere here.

So the issue isn't in the function, it's somewhere else. Either you're trying to enter a link without quoting it (e.g. you still can't do `download http//example.com?foobar` because that contains a `?`), or the problem is somewhere *else* in your config.

To reiterate: Fish always expands wildcards. If you try

```
youtube-dl "https://www.youtube.com/watch?v=dIiZ3vvZ78s"
```

and that works, and then you try

```
download https://www.youtube.com/watch?v=dIiZ3vvZ78s
```

and that doesn't, that's because you haven't quoted the second link and it includes a `?` wildcard.
