### ISSUE TITLE
Why does `_validate_int` begin with a single underscore instead of two?

### ISSUE THREAD

**Issue by kidonng** [fish-shell/fish-shell#8168]
fish 3.3.1

---

This is not a bug report, but an inconsistency I discover and then forget from time to time.

`_validate_int` is the _only_ "private" function from Fish that begins with a single underscore instead of two. I consider most plugins nowadays use a single underscore for their "private" function, and two underscores for Fish's is a convention that can be useful sometimes.

This issue is asking to either make it have consistent names by prefixing it with two underscores, or un-dunder it by removing the underscore entirely.

**Comment by zanchey** [comment]
I think it's because it was supposed to match the variables and so on set by `argparse`; see https://github.com/fish-shell/fish-shell/issues/4211.

**Comment by kidonng** [comment]
Hmm, I'm not asking for the reasoning behind the function, I'm talking about the function name being inconsistent with the rest of "private" functions.

**Comment by faho** [comment]
You asked "Why does _validate_int begin with a single underscore instead of two?", and that's the answer - to be consistent with the rest of `argparse`, specifically the variable names. It's the test function for argparse's flag value validation.

Now, we can of course think about un-undering it (a "dunder" is specifically a "double underscore" in python jargon - think `__init__`), but to do that we would have to explore the reasoning why it is the way it is.

And I don't think that reasoning is sufficient, so I would be okay with un-undering it and making it "validate_int", or renaming it to "fish_validate_int" or something. Ideally it would then be changed to also work standalone so that it doesn't require argparse's calling convention:

```fish
if validate_int --min 5 --max 8 5
```

**Comment by kidonng** [comment]
> You asked "Why does _validate_int begin with a single underscore instead of two?", and that's the answer - to be consistent with the rest of `argparse`, specifically the variable names. It's the test function for argparse's flag value validation.

I'm dumb, thanks for explaining!

> a "dunder" is specifically a "double underscore" in python jargon - think `__init__`

That's good to know!

> And I don't think that reasoning is sufficient, so I would be okay with un-undering it and making it "validate_int", or renaming it to "fish_validate_int" or something.

Glad that you think so! I find it strange to hide the function behind underscores when it is intended for ordinary usage.

**Comment by zanchey** [comment]
I don't really see the benefit, seeing as the old name should be kept around essentially forever (or break existing completions), and it's not something you use on the command line.

**Comment by ridiculousfish** [comment]
Let's close, seems like the question has been answered.
