### ISSUE TITLE
Add Support for Repos that Utilize LFS

### ISSUE THREAD

**Issue by brotatos** [fish-shell/fish-shell#8169]
```
➜ fish --version                                                                                                                     20:12:05
fish, version 3.3.1
```

Using fish_git_prompt becomes sluggish, as that command utilizes the non-LFS version of getting the repositories status (`git status -s`).

Comparison:
```
➜ time fish_git_prompt                                                                                                               20:14:51
 ...
________________________________________________________
Executed in    1.12 secs      fish           external
   usr time  812.77 millis   10.73 millis  802.05 millis
   sys time  674.04 millis   20.25 millis  653.79 millis

```
vs `git lfs status`
```
➜ time git lfs status                                                                                                                20:15:03
...
________________________________________________________
Executed in  271.85 millis    fish           external
   usr time  100.37 millis  541.00 micros   99.83 millis
   sys time  395.92 millis  279.00 micros  395.64 millis
```

**Comment by faho** [comment]
So what's the logic here? If `git-lfs` exists, just always use `git lfs status` as a drop-in replacement for `git status`?

Which part here is slow? We only use `git status --porcelain` for the informative status (which is already slow to begin with). What does

```fish
fish --profile /tmp/profile -c 'fish_git_prompt'
sort -nk2 /tmp/profile
```

say for the last twenty or so lines?

**Comment by faho** [comment]
Blergh, `git lfs status` supports `--porcelain`, but not `-unormal` or `-z`. `-z` means it's broken with filenames with newlines, `-unormal` means it descends into subdirectories, ruining performance in some cases. It also fails to find the .git directory in at least one of my repos.

`git lfs ls-files` just doesn't do what we want, at all.

Sorry, that's not usable for us, you'll have to write your own prompt that works around those idiosyncracies.

I'm closing this as will-not-implement with the understanding that if someone manages to make this work (e.g. because of enhancements in git-lfs) we'll merge it, but it doesn't appear possible at the moment.
