### ISSUE TITLE
Fish doesn't start with ill-defined fish_prompt.fish

### ISSUE THREAD

**Issue by jonashaag** [fish-shell/fish-shell#8199]
Fish version 3.3.1

Reproduce:

Define `functions/fish_prompt.fish` as an empty file. Or as follows, happened to me:

```
if ...
  function fish_prompt
    ...
  end
else # forget to write entire else branch
  function fish_prompt
    ...
  end
end
```

Start fish. It hangs seemingly forever. Maybe it keeps looking for the `fish_prompt` function to show the prompt?

**Comment by faho** [comment]
In my case, what seems to happen:

- With an empty file, it falls back on the fallback immediately
- With a file that doesn't define fish_prompt, it falls back on the fallback immediately
- With a file that has unknown commands it takes a while because it runs the command-not-found handler for each, but then it falls back to the fallback prompt

So it seems there's something else you're doing.

**Comment by jonashaag** [comment]
You are correct, it's more complicated than that. I haven't found a minimal reproducing example easily. Will reopen when I find it.
