### ISSUE TITLE
color: fish is assuming terminal's background color is black

### ISSUE THREAD

**Issue by frogtile** [fish-shell/fish-shell#8210]
<details>
<summary>Info</summary>

* version - 3.3.1
* `$TERM` - `xterm-256color` Gnome Terminal
* `uname -a` -  `Linux fedora 5.11.12-300.fc34.x86_64 #1 SMP Wed Apr 7 16:31:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* third-party customizations - no (fresh install)
</details>

... for completion menu.

![Fish running on Gnome Terminal](https://user-images.githubusercontent.com/87414805/128440270-d747849c-f181-4a2a-9956-9a3d363904da.png)

**Comment by frogtile** [comment]
It turns out markdown inside of HTML tags needs doesn't work if there is one LF after `>`

https://talk.commonmark.org/t/does-markdown-inside-of-html-tags-needs-two-lf-after/3937

**Comment by faho** [comment]
Yeah, making a colorscheme work in both dark and light backgrounds is quite hard and limiting, and therefore not something we do for all colorschemes.

The default colorscheme works in both since #3412 was fixed, which this looks like a manifestation of.

Unfortunately, since the colors are stored in universal variables, they won't be upgraded so you'll have to pick the colorscheme again. Start `fish_config`, click the "fish default" theme and done.

**Comment by faho** [comment]
Okay, question has been answered, closing.

(of course if you can demonstrate that this is a problem with the new setting of $fish_pager_color_prefix set to `normal --bold --underline` we'll reopen, but honestly that would also be a bug in your terminal - light colorscheme with a normal color of "blinding white", so we'd have to find a different color)
