### ISSUE TITLE
Index range expansion treats ending index 0 as 1

### ISSUE THREAD

**Issue by kidonng** [fish-shell/fish-shell#8213]
fish --version: 3.3.1

Quoting the [docs](https://fishshell.com/docs/current/language.html#lists):

> List indices start at 1 in fish, not 0 like in other languages.

> An invalid index is silently ignored resulting in no value (not even an empty string, just no argument at all).

However, it seems index range expansion treats ending index 0 as 1:

```
$ set -S LESS
$LESS: set in universal scope, exported, with 4 elements
$LESS[1]: |-R|
$LESS[2]: |-i|
$LESS[3]: |-M|
$LESS[4]: |--incsearch|

$ echo $LESS[0]
fish: array indices start at 1, not 0.
echo $LESS[0]
           ^

$ echo $LESS[2..0]
-i -R

$ echo $LESS[2..1]
-i -R
```

This behavior is, at least for me, unexpected and seems in contrary to what the docs says (it is 
an invalid index but doesn't result in no value).

Or in other words, why can the index end with 0 if it can't start at 0?

**Comment by kopischke** [comment]
I am sorry to be that guy, but actually, your example seems to work as specified. To my understanding, `$LESS[2..0]` means “all the indexes in reverse order down from 2 to 0“, which includes index 1 and thus outputs the values for the valid index values 2 and 1, then silently drops the invalid index 0.

Unlike the `$LESS[0]` example, where nothing but the invalid 0 index has been given and hence the error message helps understanding why there is not output, I am not sure there would be more value in refusing to output the valid values in the `$LESS[2..0]` range just because it ends with the invalid 0 index.

**Comment by kidonng** [comment]
There's also this:

```
$ echo $LESS[-0..2]
-R -i
```

**Comment by kopischke** [comment]
Well, there is no such thing as negative zero value, just zero, so what this is apparently interpreted as would be `$LESS[0..2]`, a sequence to which my above observation applies:

> Unlike the $LESS[0] example, where nothing but the invalid 0 index has been given and hence the error message helps understanding why there is no output, I am not sure there would be more value in refusing to output the valid values in the $LESS[2..0] range just because it ends with the invalid 0 index.

You could make an argument that the minus denotes user intent to count from the range end, I suppose, in which case it should output the last two values instead of the first two, I suppose, but that has nothing to do with 0 being a valid index.

**Comment by kopischke** [comment]
Ah, I see I have missed your first example. That is an inconsistency, right enough; fish should either process all ranges still valid after dropping the 0 index, or error out on all ranges including a 0 index.
