### ISSUE TITLE
Cannot set/persist correct TERM value

### ISSUE THREAD

**Issue by Nolaan** [fish-shell/fish-shell#8215]
```
-> fish --version
fish, version 3.2.0
```

Hi all,
I'm having hard times figuring out why fish would not accept the provided value for TERM variable.
I have no plugins, and can't find where it would be overriden.

```set --show TERM
$TERM: set in global scope, exported, with 1 elements
$TERM[1]: |xterm|
```
None of the below commands would change the situation **after login/logout** : 
```
set -gx TERM xterm-256color
set -Ux TERM xterm-256color
set -lx TERM xterm-256color
```

Thanks

**Comment by faho** [comment]
The $TERM value is inherited as a global variable from fish's parent process, which is most likely the terminal. Universal variables are of a higher scope than globals, so the inherited global value takes precedence. See https://fishshell.com/docs/current/faq.html#why-doesn-t-set-ux-exported-universal-variables-seem-to-work.

What you really want is to either fix the value *in your terminal settings*, or not touch it at all because the value should match the terminal you use, so what that picks should typically be correct. If it can actually do xterm-256color things, then the default for that terminal should probably be changed, so you should complain to the terminal's authors.

If you *really must* change the value, use

```fish
set -gx TERM xterm-256color
```

inside config.fish.

**Comment by faho** [comment]
Question has been answered, no reaction, closing!
