### ISSUE TITLE
Add commandline --is-complete?

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#8223]
@faho The recently added `commandline --is-valid` doesn't quite do what people want when they say "transient prompt".

The purpose of a transient prompt is to allow the user to have a good looking prompt while not cluttering up scrollback history.

```fish
# ---config.fish---
function fish_prompt
    if not set -e transient
        echo
        echo $PWD
    end
    echo '>'
end

function maybe_execute
    if commandline --is-valid
        set -g transient
        commandline -f repaint
    end

    commandline -f execute
end

bind \r maybe_execute
```

https://user-images.githubusercontent.com/6318351/129803675-a33ce591-eb1c-4d10-b71b-962b317653a7.mp4

As you can see, when running a command, the prompt correctly folds into a smaller, less obtrusive prompt. But if the commandline has an error or is empty, then the full prompt is redrawn, which is a waste of scrollback history.

What I'm [pretty sure people actually want](https://github.com/romkatv/powerlevel10k/#transient-prompt) is this:

```fish
# ---config.fish---
function fish_prompt
    if not set -e transient_prompt
        echo
        echo $PWD
    end
    echo '>'
end

function maybe_execute
    commandline --is-valid

    # If commandline is complete (i.e pressing enter will produce a new prompt)
    if test $status != 2
        set -g transient_prompt
        commandline -f repaint
    end

    commandline -f execute
end

bind \r maybe_execute
```

https://user-images.githubusercontent.com/6318351/129804214-8b88e9f1-13d6-4799-9a18-70aeba481d9f.mp4

---

So do we keep `commandline --is-valid`, and just make it clear in the docs how to do the 'correct' way? Or do we replace `commandline --is-valid` with `commandline --is-complete`?

**Comment by mqudsi** [comment]
This was (for me, at any rate) really hard to understand because of all the loose or subjective terminology and your hard-coded `$status != 2` in the "valid" version.

Am I right in understanding that what you want is "if I press enter, will this execute?" and you don't care if it's going to execute but return an error (parse-time or run-time), execute but reprint the buggy prompt, etc. just if it's going to execute at all? e.g. a hypothetical `commandline --will-execute`?

Because if that's the case, I don't think your "is-complete" version above actually does that. If the command line contains `echo \` (no trailing characters) you get `$status = 1` and if it contains `echo |` you get `$status = 2`, but neither will execute.

**Comment by IlanCosman** [comment]
> This was (for me, at any rate) really hard to understand because of all the loose or subjective terminology and your hard-coded $status != 2 in the "valid" version.

Agreed. To be honest it's a bit hard for me to understand, and I wrote it 😅 

> or, more explicitly, `commandline --next-enter-will-end-edit-and-attempt-execution`

Yes, Please add that flag verbatim 😄

I do not care whether it's an error, or an empty line, or an execution. All I care about is whether a new prompt will be displayed or not. I.e are we done editing the line or not (open brackets, open quotes, newline escape, etc.)

**Comment by mqudsi** [comment]
Also, completely apart from all that, I'm not sure `commandline -f repaint` will suffice for what you are doing if the command that's executed writes to the output but doesn't overwrite all the previous contents. I had to patch your transient prompt with the following to make it work when you execute something like `echo`:

```fish
function fish_prompt
	printf \e\[0J
	if not set -e transient_prompt
		printf \n$PWD
	end
	echo '> '
end

function maybe_execute
	commandline --is-valid

	# If commandline is complete (i.e pressing enter will produce a new prompt)
	if test $status != 2
		set -g transient_prompt
		commandline -f repaint
	end

	# printf \e\[0J;
	commandline -f execute;
end

bind \r maybe_execute
```

**Comment by IlanCosman** [comment]
Yah. I was going to bring that up in another issue 😩 What a mess 😂

**Comment by mqudsi** [comment]
I would naively expect that a function setting `transient_prompt` and then calling `commandline -f repaint` on `fish_preexec` would be exactly what you need, except it seems to be called after the association between the previous command line buffer and the `commandline` builtin is broken - or maybe it's that the repaint is delayed until the execution has completed, I'm not sure which.

(This is aside from the fact that `fish_preexec` doesn't fire on `^J`/`<enter>` with a completely empty command line (but it *does* fire if the command line just contains even a single space) - and there actually is a good reason for that because we patched that exception in when someone complained with a valid reason for why `fish_preexec` shouldn't fire for an empty prompt, only I can't remember the reason right now.)

**Comment by faho** [comment]
> But if the commandline has an error or is empty, then the full prompt is redrawn, which is a waste of scrollback history.

It is redrawn (note: I'm not sure if it's reexecuted - I believe we just show the old prompt again?) because that's what we do on error - display the error under the prompt and show a new prompt, as if we had executed a command. We don't currently have the capability to show the error under the prompt but keep the same prompt line.

This isn't a property of `commandline --is-valid` and would be the same if we just allowed you to repaint from a preexec handler or similar (which I would still like to do).

That we currently treat empty commandlines as an error instead of incomplete is a weird implementation detail that we can change (or you could check `commandline | string length -q`).

**Comment by faho** [comment]
I don't think I'm entirely sure what's asked for here - what should change in fish or what question needs to be answered?

**Comment by IlanCosman** [comment]
Alright I think I'll close this, not sure if the `\` problem got sorted out, if not I can open a different issue for that. The main thrust of this issue was discuss and rejected 👍
