### ISSUE TITLE
[Bug]: Also handle directory passed to fish

### ISSUE THREAD

**Issue by thunder-coding** [fish-shell/fish-shell#8258]
## Steps to reproduce
```fish
cd $TMPDIR
fish .
```

Passing any folder/directory to fish results in a infinite loop where fish keeps saying `error: Unable to read input file: Is a directory`

https://github.com/fish-shell/fish-shell/blob/498e5fa9b0be1f96328cbfcca7ea1e17d034b226/src/reader.cpp#L4227

This is the file where the problem needs to be solved

## What should be done when a directory is passed to fish

Fish should set the current directory to the supplied directory passed through command line

## Platforms I confirmed the bug on
- Android 11 Termux fish 3.3.1
- Android 7 Termux fish 3.3.1

**Comment by faho** [comment]
Running `fish .` means to tell fish to read `.` *as a script file* - this runs like `fish foo.fish`, except instead of `foo.fish` you've given a directory. That doesn't work, for obvious reasons.

>Fish should set the current directory to the supplied directory passed through command line

I disagree. We should simply reject it when a directory is passed as a script file. Otherwise we'd have to introduce another way of running fish - with a file, read the file, with a directory, go to that directory. This is unfamiliar (e.g. bash doesn't do it) and you're, to my knowledge, the first person to  try that.

So let's just fix the failure mode.
