### ISSUE TITLE
Centering text with fish shell...

### ISSUE THREAD

**Issue by snacksncode** [fish-shell/fish-shell#8282]
Fish: version 3.3.1.

This might sound silly but I'm trying to center a text inside fish shell. But I'm too smooth brain for that. I usually get command substitution errors when trying to get values. All I need is to combine (string length $text) with (math $COLUMNS / 2 + [That string length]) and pass it to printf. But for the past 1.5h I've been unsuccessful. Please help haha.

Example of what I'm trying to do:
```
printf "%*s\n" (math $COLUMNS / 2 + (string length "123456789012345678901234567890")) "123456789012345678901234567890"
```

Any ideas?

**Comment by faho** [comment]
Math does operator precedence.

You're computing

    (columns / 2) + length

what you need is

    (columns + length) / 2

The simplest thing to do is probably to add another "/ 2" after the length argument:

```fish
printf "%*s\n" (math $COLUMNS / 2 + (string length "123456789012345678901234567890") / 2) "123456789012345678901234567890"
```

**Comment by snacksncode** [comment]
Okay, thanks, you're right. The problem occurs when I'm trying to do this:
```fish
set text "ajdhkjad"; printf "%*s\n" (math $COLUMNS / 2 + (string length ($text)) / 2) $text
``` 
($text) gives me a "command substitution" error. But actually there's `fortune` command there instead of text that's why I need to store it in a variable (output changes each time you run `fortune`). How can I deal with that?

**Comment by faho** [comment]
> ($text) gives me a "command substitution" error.

Yes, this is because `(something)` is a command substitution. You don't want the parentheses to be a command substitution. In fact in this particular bit you don't want them at all? `$text` is a variable not a command to run!

```fish
set text (fortune); printf "%*s\n" (math $COLUMNS / 2 + (string length $text) / 2) $text
```

However, fortune may print multiple lines, so you need to go through each line separately:

```fish
set text (fortune)
for line in $text
    printf "%*s\n" (math $COLUMNS / 2 + (string length $line) / 2) $line
end
```

Also, the length and columns might not be even, so you probably need to add `--scale=0` to your math invocation to just use an integer (`printf` won't be able to pad to 35.5):

```fish
set text (fortune)
for line in $text
    printf "%*s\n" (math --scale=0 $COLUMNS / 2 + (string length $line) / 2) $line
end
```

(of course if the text includes any leading or trailing spaces those will be used as well, add `| string trim` after the `fortune` to throw them away, if you wish)

**Comment by snacksncode** [comment]
Wow thanks that almost fixes it all haha. I've added the colors myself with `set_color`. Also I've noticed a small bug, with my version of fortune it's not a problem but maybe it future it might become relevant.
I'm using this for my greeting:
```
#/usr/bin/fish
function fish_greeting
    set text (fortune /usr/share/fortune/question-answer-jokes | string trim)
    set_color blue
    for line in $text
        printf "%*s\n" (math --scale=0 $COLUMNS / 2 + (string length $line) / 2) $line                                                     
    end
    set_color normal
end
```
And it works because the output doesn't contain any weird characters. But when output string has something like "--" it parsed it as a command option and breaks haha. Any way of telling the shell to treat this as "text only"?
My normal working output: https://i.imgur.com/KsncAaF.png
"Possible" error with normal fortune (or any other weird output I guess): https://i.imgur.com/ZAT7AGF.png

**Comment by faho** [comment]
>But when output string has something like "--" it parsed it as a command option and breaks haha. Any way of telling the shell to treat this as "text only"?

You might want to read [the documentation](https://fishshell.com/docs/current/cmds/string.html):

>Arguments beginning with - are normally interpreted as switches; -- causes the following arguments not to be treated as switches even if they begin with -. Switches and required arguments are recognized only on the command line.

So: 

```fish
string length -- $line
```

This isn't an issue for `printf` because that doesn't accept any options, nor for math because that doesn't accept any options after the first non-option, and if it looks like a number will interpret it as a number (so `math -2 + 3` will print "1" instead of reading `-2` as an option).

**Comment by snacksncode** [comment]
> You might want to read the documentation
Yup my bad for not looking that up.
**Thank you soo much**, it was interesting that fish actually splits string by lines with a for loop.
Have a nice day! :)

**Comment by faho** [comment]
>it was interesting that fish actually splits string by lines with a for loop.

It's not the for-loop, it's the command substitution.

This:

```fish
set text (fortune)
```

is where the splitting happens. After that $text[1] is the first line, $text[2] is the second, and so on.

**Comment by snacksncode** [comment]
Oh, didn't know that. I'm coming from more of a "JS" oriented mind. Shell scripts are weird to me
