### ISSUE TITLE
Unknown version incongruency

### ISSUE THREAD

**Issue by nomadoda** [fish-shell/fish-shell#8291]
I have just updated fish with `brew install fish` because I was excited to use the `fish_add_path` function which was added in `3.2.0`, but I'm unable to execute the command because it doesn't exist for some reason. I check my fish version:

```
fish --version
fish, version 3.3.1
```

It looks good. But when I check the `$version` variable:

```
echo $version
3.1.2
```

There is some discrepancy that I cannot understand. I assume this must be the root cause to my issue. What is this `$version` variable and why is it not the same as `fish --version`? I tried setting it, but it seems to be readonly.

```
uname -a
Darwin Zodiapps.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64
```

This is not the case when running without third-party customizations

**Comment by faho** [comment]
>It looks good. But when I check the $version variable:

Running `fish --version` starts a *new* fish, and that will then state its version.

Running `echo $version` asks the current version.

So: You either haven't started a new fish since updating, or you still have an old fish that's started by default.

Check your terminal settings for what shell its supposed to start, see if `command -sa fish` prints more than one fish, check `status fish-path`.

**Comment by zanchey** [comment]
Or use `exec fish`.

**Comment by nomadoda** [comment]
Thanks for the swift help. I understand the discrepancy now. When I installed the arm64 compatible version to `/opt/homebrew/bin/fish` I hadn't actually changed the previous path set in `/etc/shell` (`/usr/local/bin/fish`). I changed this and ran `chsh -s (which fish)` to update the default shell.
