### ISSUE TITLE
Command substitution fails with windows newline

### ISSUE THREAD

**Issue by champignoom** [fish-shell/fish-shell#8317]
fish version: 3.3.1
system: Manjaro 21.1.4
extensions: none

Steps to reproduce: run `echo a(printf '1\r\n2\r\n3')b`
Expected result: 'a1b a2b a3b'
Actual result: 'b a3b'

**Comment by faho** [comment]
Command substitutions don't *care* about carriage returns. This is on purpose, this is unix, not windows.

Use `string trim -c \r`:

```fish
echo a(printf '1\r\n2\r\n3' | string trim -c \r)b
```

**Comment by champignoom** [comment]
Thanks for the explanation. I understand now how the result was produced.

But I doubt if this is the ideal design: fish-shell is -- after all -- a shell, which needs some fault tolerance for the high frequency of usage. Whether the processed file is from windows or from linux (no, windows and linux are not mutually insulated) is almost always of little importance to the user and therefore should not be the source of distraction.

Since a dedicated switch is sufficient to solve this problem, the consistency of design should not prevent the shell from being user friendly.

**Comment by faho** [comment]
>fish-shell is -- after all -- a shell

It is a *unix* shell. 

WIndows line endings are highly irregular, and doing magic on characters is *less* user friendly, not more. We don't actually know that that `\r` is just there for a windows line ending! It could be an arbitrary character that's meant to be there!

There's a reason other tools like e.g. `grep` also don't magically do this.

Sorry, but this will not be changed. If you have windows line endings, fix them, which is easily done with `dos2unix` (to fix up a file) or `string trim` (for output from a command).

Since the question has been answered and there is no further work to be done, I'm closing this.

**Comment by champignoom** [comment]
I see. Below is a bit off-topic.

I guess the rationale for fish-shell to split only on `\n` is mainly to avoid the agressive splitting on all whitespaces like in bash, which is a problem when non-newline spaces are important.

But splitting iff encountering `\n` effectively breaks the completeness of the shell, as discussed in https://github.com/fish-shell/fish-shell/issues/5942 .

I would suggest to break the result on `\0` and make a `split-zero [newline | spaces | -r regex]` or something to ease the splitting:

- this makes the behavior complete, as no executable can read its argument beyond `\0`
- this makes splitting on newline less of a special case than splitting on all whitespaces
- this eases the usage of pkg-config in fish-shell (no, the workaround given in https://fishshell.com/docs/current/faq.html#my-command-pkg-config-gives-its-output-as-a-single-long-string does not always work without removing newlines in addition)

**Comment by faho** [comment]
>I would suggest to break the result on \0 and make a split-zero [newline | spaces | -r regex] or something to ease the splitting:

You will be pleased to find [string split0](https://fishshell.com/docs/current/cmds/string-split0.html).

Other than that, splitting on newlines is a fantastic default, because that's how unix tools operate in practice.

In particular, splitting on NULL does *not* work if the tool doesn't use NULLs as delimiters! It doesn't help with pkg-config because the problem with pkg-config is that it uses *spaces*, and it does not have a NULL-separated mode like e.g. `find -print0`.

**Comment by champignoom** [comment]
> You will be pleased to find string split0.

Thanks for the pointer. It makes the design complete indeed.

I guess https://github.com/fish-shell/fish-shell/issues/5942 could be closed perhaps?

**Comment by champignoom** [comment]
Sorry I misunderstood the specialty of split0 -- it does not make `\0` the separator, but rather mix up the "text newlines" with the "array type signature newlines", which shows the inconsistency in addition to the incompleteness.

So,

> Other than that, splitting on newlines is a fantastic default, because that's how unix tools operate in practice.

indeed, except when it breaks both consistency and completeness.
