### ISSUE TITLE
How to turn off printing of the ⏎ symbol when fish inserts a newline.

### ISSUE THREAD

**Issue by d-air1** [fish-shell/fish-shell#8329]
Fish Version - 3.3.1
Operating System: EndeavourOS (Arch)

uname -a:
Linux 5.14.8-zen1-1-zen #1 ZEN SMP PREEMPT Sun, 26 Sep 2021 19:36:16 +0000 x86_64 GNU/Linux

echo $TERM:
xterm-256color

Terminal Emulator:
kde's konsole

I've seen the various issues in the past about printing this symbol: ⏎ . However my issue isn't about this symbol being shown when it shouldn't be. 
The issue is that it interferes with konsole's builtin feature to open links in your browser of choice. 
Trying to open a link will fail because the ⏎ symbol with also be a part of the forward url. 
<br>
For example something like say https://google.com becomes https://google.com⏎ . 
<br>
This causes me to have to manually edit the url and load the page again. konsole already knows to automatically strip newlines from url's but it does not automatically know to strip this symbol decided on by fish from the url. If I could just turn the printing of this symbol off, it would save me the trouble of having to edit the url bar every time.

**Comment by krobelus** [comment]
Interestingly gnome-terminal has the same behavior.. but I think they're both wrong. URLs can only contain alphanumeric ASCII characters and a handful of special characters, see https://stackoverflow.com/questions/7109143/what-characters-are-valid-in-a-url. Meanwhile, [this](https://invent.kde.org/utilities/konsole/-/blob/ce18a9c8dd8a20491ed2e383e99ef54a76b04dd1/src/filterHotSpots/UrlFilter.cpp#L19) is the regex used by Konsole.

So I think we should fix terminals instead; I don't see why not.
(BTW I hope you don't hit this case very often since most commands should print a trailing newline).

**Comment by d-air1** [comment]
So, I should file this upstream with kde and ask them to change the regex to only allow for valid url characters. Thanks for pointing me in the right direction.

**Comment by page-down** [comment]
For the URL part, this reminds me of a recent discussion[^1] on HN.
The URL mentioned above is a valid URL. There is no single authoritative URL specification[^2].

There are also many users who expect URLs with Unicode to be recognized correctly.

I suggest trying [kitty](https://sw.kovidgoyal.net/kitty/) terminal, which has better URL support and can be customized.

Configure kitty `url_excluded_characters`[^3] to exclude any characters you don't want in the URL matching rules.
```text
url_excluded_characters ⏎
```

`printf "https://github.com"` becomes <ins>https://github.com</ins>⏎

[^1]: [In search of the perfect URL validation regex (2010) | Hacker News](https://news.ycombinator.com/item?id=28654767)
[^2]: From the founder of cURL: [My URL isn’t your URL (2016) | daniel.haxx.se](https://daniel.haxx.se/blog/2016/05/11/my-url-isnt-your-url/)
[^3]: [url_excluded_characters - kitty.conf - kitty](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.url_excluded_characters)

**Comment by d-air1** [comment]
That's something to take note of. I understand that kitty is extremely customizable, but I would rather stick with konsole at this point. It's got everything I need and is also pretty configurable with all the switches, toggles, and buttons I've come to expect of kde software.

**Comment by krobelus** [comment]
My bad sorry I was thinking too quick.
If the terminal displays `https://example.com/cœur`, then the entire thing is the URL because it can be parsed by a URL parser.
The URL encoding will be `https://example.com/c%C5%93ur`.

I considered adding a [Zero-Width Space](https://unicode-explorer.com/c/200B) before the `⏎` but that does not have the Unicode property "space", so it won't be matched by `\s`, which means that terminals will include it in their URLs.

I'll close this since I don't see a solution without drawbacks:
- unconditionally adding a space will make the common case more confusing
- fish won't look at your command output, so it can't be smart.
As a workaround please make your programs print URLs with a trailing newline, that's the convention (and Bash expects it as well)

**Comment by d-air1** [comment]
No probs. That's what I ended up doing, just writing functions to append a newline to the few commands that don't end with one.

**Comment by krobelus** [comment]
> just writing functions to append a newline to the few commands that don't end with one.

Sounds like the commands themselves should be fixed, (then they also work in other shells, where there's no fish function to save the day)
