### ISSUE TITLE
Open up GitHub Discussions for Offtopic fish talks

### ISSUE THREAD

**Issue by thunder-coding** [fish-shell/fish-shell#8339]
Currently all questions for help related to fish are asked through GitHub Issues or Stackoverflow or Gitter. It would be great if we can move atleast the GitHub issues to Discussions as it makes sense to use Issues just for bugs and feature requests.

Also through discussions the community can also showcase fish stuff.

**Comment by IlanCosman** [comment]
Agreed. I recall asking questions on gitter, but finding the answers again is quite difficult, which discussions would solve.

**Comment by IlanCosman** [comment]
Counterpoint: Remove most of the others. besides Gitter, because that one is active.

1. Mailing list are afaik essentially legacy at this point, and ours isn't used pretty much at all.
2. The Stack overflows are not used a ton, maybe one question per week on average, from my eyeballing. And, as you mentioned, it has the notable disadvantage of being awkwardly split.
3. Gitter can stay, because it's fairly popular.

Advantages of Discussions are:
1. Everything* in one spot on the Github Repo. Improves discoverability.
2. Hooks in with issues nicely. None of this "as mentioned by so and so on Gitter" that is impossible to find later.

Thoughts?

**Comment by zanchey** [comment]
I'd be happy to give it a whirl on a trial basis. Maybe turn it on and review a few months after a release?

**Comment by zanchey** [comment]
OK, I actually looked at Discussions properly, and it's basically just "issues with more threading"?

I really don't feel strongly either way, and the button that converts a discussion straight to an issue is nice, but are our issues really that crowded that it's causing a problem? Is it a problem that we tend to close all question-tagged issues after a week or two, and then they get locked after a while?

**Comment by IlanCosman** [comment]
> Many questions start off as mistaken issues.

I think there may be some chicken-vs-egg effect going on here.

Basically, issues do not _encourage_ questions. Because there are no issue templates, the user is immediately confronted by a bug report template which asks them to gather system information, explain how to reproduce, etc. There is no indication that issues is an acceptable/recommended place to ask questions (I didn't even know it was. Is it?)

E.g:
> Found a bug? Have an awesome idea? Please open an issue.

So _of course_ the `question` tag is basically `dumb-or-mistaken bug-report-or-feature-request`. Because all people can submit are bug reports and feature requests!

I don't disagree that this would continue to happen, even if people had a question template to choose. But I think it would be lessened. More experienced/less headstrong users ask questions, which would then transition into feature requests/bug reports.

---

> I have no interest in discussing omf/fisher.

Fair enough. But I don't think discussions would significantly impact the quantity of such questions, only spread them out a little. We still get plenty of such questions on gitter. Still, a point in your favor.

---

> Asking questions via a discussion is as heavy as asking it via an issue

See earlier. The difference would be that discussions are explicitly for asking questions, while issues has absolutely not been.

---

Furthermore discussion are objectively _better_ than issues for asking questions. They have threads. They have sorting by age/upvotes. They have accepting an answer.

**Comment by IlanCosman** [comment]
Not to get all sentimental, but I really appreciate you sharing how you're feeling with us @faho. Maintainer burnout is a big problem, and the demands of the community are the biggest part of that.

I think the solution is largely already in place though. A few fish-shell members have already volunteered to help out, and actually, discussions should be much less centralized than issues.

1. Users can choose their own category, such as Q/A, so no one has to label anything
2. Discussion aren't closable, so no one with admin powers needs to do anything
2. The discussion "ends" when an answer has been selected by the asker

So in theory the whole process should run without any intervention from admins. That's if there are enough people with expertise and motivation to answer, which, in fairness, is a big if. Still, I am hopeful that discussions would actually lift some of the burden off your shoulders Fabian.

**Comment by krobelus** [comment]
I guess for discussions that report bugs (like #8849, #8831) we are supposed to make an issue (for labels, milestones and searchability)
We can convert issues to discussion, but sadly the inverse does not work (only creating a new issue for a discussion).
I prefer to avoid using the github web UI for everyday stuff. I have some tooling to read/write issue comments but haven't extended it to discussions yet. Also reply-by-email sometimes doesn't work for discussions, I'll try to report a bug.
