### ISSUE TITLE
Cannot set _ alias

### ISSUE THREAD

**Issue by r67018** [fish-shell/fish-shell#8342]
In fish, _ is defined as a function.
So when you set the alias, commands such as "type" don't work properly.

e. g.
```sh
$ alias _=ls
$ type ls
ls: cannot access '%s is a function': No such file or directory
lsls: cannot access ' with definition': No such file or directory

# Defined in /usr/share/fish/functions/ls.fish @ line 13
function ls --description 'List contents of directory'
    set -l opt --color=auto
            isatty stdout
            and set -a opt -F
            command ls $opt $argv
end
```
Is there a workaround for this?

```sh
$ fish --version
fish, version 3.1.0
$ uname -a
Linux sleepcat 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ echo $TERM
screen-256color
```

**Comment by floam** [comment]
And right call on the enhancement label. Oops.

**Comment by faho** [comment]
> I had long wondered why the heck it wasn't prior

It was part of fish's minimalist bent - we used to have that "Law Of Minimalism" that forbade anything from being a builtin if it could be a command. This even included `echo`, which would then add milliseconds of delay to any time you wanted to print a string.

>I wonder how we'd have approached this issue a few years ago?

Probably not at all - "if it hurts, don't do that". Which I would still find acceptable - you could also override e.g. `rm` to do `cp` instead, and it would break a bunch of scripts. So that's a bad idea, and I would recommend against it.

The reason we made builtin names reserved was, for the most part, because they can't be overridden without breaking functionality - `set` can't be a function because that breaks `set -l` (and since it imports variables, `string` also can't be overridden anymore). 

We did it for `test` because people tried to call test runners and stuff that, so it was a common issue. For `_` it technically can be safely overridden (like I said, make it `printf %s $argv`), but because the name isn't all that well-known it's okay to reserve it as well.
