### ISSUE TITLE
fish package in PPA for Ubuntu 21.10 (impish indri)

### ISSUE THREAD

**Issue by estshorter** [fish-shell/fish-shell#8356]
It seems that `ppa:fish-shell/release-3` does not have a package for Ubuntu 21.10 (impish indri).
see: https://launchpad.net/~fish-shell/+archive/ubuntu/release-3

Do you have any plan to upload the package?

related: https://github.com/fish-shell/fish-shell/issues/8051

**Comment by ridiculousfish** [comment]
cc @zanchey

**Comment by donpdonp** [comment]
A ping for 22.04

**Comment by zanchey** [comment]
Should be there already (but has the impish name in the package)

**Comment by faho** [comment]
That was probably me - I tried copying it, it complained and I decided to back away. I have no idea how the launchpad interface works and if that built a new package or not (I did select the option to rebuild it instead of copying the binaries over), or how to rename it, or why the codenames are used here at all.

**Comment by zanchey** [comment]
I did it on April 1st (see https://launchpad.net/~fish-shell/+archive/ubuntu/release-3/+sourcepub/13407685/+listing-archive-extra); your attempt did fail though.

The problem is that Launchpad is set up as one giant archive, but we need the package to be built for each release. If you upload one source archive it only gets built for one release, but it can't have the same name/version as any other releases unless you copy it over. So there's some code in the release scripts that appends the release name to the Debian version, rebuilds the source package then uploads it.

For newer versions of Ubuntu, I just copy the most recent packages as generally backward-compatibility is maintained and it avoids having to re-run the source package build on a separate occasion.
