### ISSUE TITLE
Linter for .fish scripts

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8357]
Hello! Is there any linter like shellcheck for .fish scripts?

**Comment by alxpettit** [comment]
Less needed than Bash, but linters are still important if we want more ecosystem support.

Linters can be integrated with IDE environments and provide intelligent contextual information.

For instance, if someone is writing a nontrivial collection of `.fish` files in a VSCode or Intellij Idea project, there's no way for them to know, e.g., that they misspelled a variable name once, outside of runtime errors and explicit testing. A good-quality IDE can execute both a syntax check tool and a linter on each change and considerably speed up development.

**Comment by alxpettit** [comment]
I recommend reopening this, if you'll consider it.

**Comment by faho** [comment]
This was marked as a question asking for an existing linter. There isn't one.

If you want to ask for a linter to be developed,

1. that could be an external project
2. it would need quite a bit more work - what should it lint? what are the issues you want to check?

So I've closed this for now because otherwise it's dead weight.

**Comment by alxpettit** [comment]
Ah, yeah, sorry. I forgot the wording of the original question.

what is the appropriate issue tracker for 'external' projects?

**Comment by faho** [comment]
>what is the appropriate issue tracker for 'external' projects?

What I mean by "external" is that it can be a third-party thing. It doesn't have to be an official fish-shell project.

I don't believe a full linter is really in-scope for fish proper.

And you would then have to figure out what exactly to look *for*, because e.g.

>that they misspelled a variable name once

That can't be 100% accurate, because you only know which variables exist until runtime. At the very least you can inherit variables from the environment.

Using an undefined variable name is also not necessarily an error - it expands to nothing, which is often what you want.

This is unlike languages like e.g. rust or go, and more like e.g. python, *but even more extreme*.

So the concept of a "linter" needs to be thought through here. What are the issues you can and want to check?

**Comment by alxpettit** [comment]
> That can't be 100% accurate, because you only know which variables exist until runtime. At the very least you can inherit variables from the environment.

Ideally, you should have a full LSP able to scan and cache all objects so it can give intelligent, fast input on stuff like that without complicating compatibility. That way you can use a single tokenizer and parser layer for linting, syntax checking, expansion predictions, and everything else. It's the ultimate solution... :P

But, of course, highly nontrivial.

I'd say even a minimal linter that only knows the context of the current file could give meaningful input. I imagine one would establish a comment syntax to direct the linter, and use that to do things like, e.g. inform it of external variables you intend to use outside of the expected defaults (`PATH`, `HOME`, etc). This would be adequate to catch a lot of common errors.

> Using an undefined variable name is also not necessarily an error - it expands to nothing, which is often what you want.

I think variable names expanding to nothing is... _questionable_ in the context of scripting. For instance, if you have a `$prefix/some/path` and `$prefix` is accidentally empty, you may end up accidentally having a script that, e.g., nukes the wrong directory. 

Now, this is easily avoidable for cautious, experienced scripters, but the fact that such a pitfall exists makes it that little bit less `Friendly`, and that's something to consider. Honestly... I can only think of a couple scripts I've ever written that made use of empty expansion. Usually it is undesired behavior.

But, that said, maybe I'm the odd one out here. If silent empty expansion is a desirable feature for most people, it may make less sense to even make a linter. I wonder if there is some community mechanism by which to gauge this?

**Comment by ThisNekoGuy** [comment]
@faho 

> No. But it is largely unneeded, because Fish has better syntax than posix shells: https://stackoverflow.com/questions/42660371/is-there-a-linter-for-fish-like-there-is-for-bash-with-shellcheck

Except when it isn't clear how fish scripting is supposed to work with basic if-checks and no one being able to answer how elsewhere:
![Screenshot_20220801_010915](https://user-images.githubusercontent.com/28468662/182083102-e9744e40-3ee9-4735-adc8-0e9c3d0b8635.png)

**Comment by faho** [comment]
@ThisNekoGuy If you want to check if `lolcat` and `neofecth` exist as commands, you would do:

```fish
if command -sq neofetch && command -sq lolcat
    neofetch | lolcat
end
```

What you are doing here is almost entirely the opposite. `command -v neofetch` will print something like "/usr/bin/neofetch" if it succeeds and nothing if it doesn't, you have silenced stdout and redirected stderr to a file called "1" so you check nothing.

Anyway, that has very little to do with this issue, or with linting, or whatever. You should read [the documentation](https://fishshell.com/docs/current/tutorial.html#conditionals-if-else-switch), which has a relevant example:

```fish
if grep fish /etc/shells; and command -sq fish
    echo fish is installed and configured
end
```

----

Can I ask you to simply open another issue or ask on gitter.im/fish-shell/fish-shell if you have a question, instead of commenting on old unrelated issues?

**Comment by ThisNekoGuy** [comment]
@faho Apologies; I was looking at the documentation [but I came up with this instead](https://fishshell.com/docs/current/cmds/if.html#), which gave me the wrong impression about the reliability of the documentation.
