### ISSUE TITLE
argument parsing confusion: fish --profile -c

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#8379]
This was a mind bender for a moment:

```fish
> fish --profile -c 'echo foo'
echo foo: No such file or directory
> # what
> fish --profile -c echo foo
echo: No such file or directory
> #  no builtins, no PATH, what is this?!
```

Obviously I just forgot that `--profile` requires a filename; I thought it was optional and somehow imagined it'd print the profile to stdout at exit. It should not accept something starting with `-` like `-c` unless given as `--profile=-c` or after a `--`.

**Comment by faho** [comment]
Okay, I'm going to call this done with 91ce41a2b49509054be707137ff703e1b09c48ef. We now explain better that we're trying to run `echo foo` as a file.

Like I said, I do not believe changing how `--profile` works is a good idea. Optional arguments have issues, which is why we have [specific documentation about the caveats](https://github.com/fish-shell/fish-shell/blob/master/doc_src/cmds/argparse.rst#note-optional-arguments).
