### ISSUE TITLE
How do I `read` arrow keys, exactly?

### ISSUE THREAD

**Issue by godDLL** [fish-shell/fish-shell#8443]
I've tried and tried reading the `\e\[A` and such, but one can only see them triggered in the `--null` mode for `read` builtin; any other mode just eats them up silently.

Is there a legit way to read arrow keys? Rebind them temporarily, mayhap?

Fish version 3.3.1 on OSX 10.12.6

**Comment by faho** [comment]
`read` in the normal interactive mode acts like fish's interactive reader. That means it'll read keys and act according to the bindings. An arrow will cause arrow things to happen - move the cursor, go through the history, ...

But once you press return it will close the reader and leave what the commandline buffer contained in the variable. And the commandline buffer contains the edited version of whatever you typed - if you pressed left-arrow, that'll move the cursor, but it won't change the buffer.

So that doesn't work and isn't supposed to work. 

>Rebind them temporarily, mayhap?

If you unbind arrow, it'll stop you from moving the cursor, but still won't insert the full escape sequence in the buffer because fish fundamentally won't add control characters to the buffer.

`read --null` will read them because it's a mode to reproduce exactly what was entered, typically so `find . -print0 | while read --null` works.

**Comment by godDLL** [comment]
Yes, nothing new there.

My question is how does one create a menu system? The `read --null` thing does not return after an arrow pressed, and doesn't react to `--nchars 1` the way I'd expect, just ignores it. 

I did try binding with `bind -k left fname` so that I could temporarily intercept that, but again – that seems to be ignored.

What gives?

**Comment by faho** [comment]
> My question is how does one create a menu system

Currently: Use fzf or similar, or just ask for a number.

Otherwise, wait for someone to implement #2805.

**Comment by zanchey** [comment]
Or look at `dialog` or `whiptail`.

**Comment by godDLL** [comment]
Thanks @faho this gives me the idea of how things are at the moment.

> Or look at `dialog` or `whiptail`.

@zanchey Or fzf, or many others, right.  
Yeah, I have my own called `menu` that I've whipped up in Nim. Very simple, no deps, stays in the terminal, no alt-screen even.

That's how I do it on my machine. Or use fzf, if it's more than a 5-10 items.

But my question was for the purposes of packaging a stand-alone Fish script for portable distribution. 

So then, I'll be using `j [ ,` and `l ] .` for arrows [in my script](//gist.github.com/godDLL/b4a43505b0dac4f12dcd73046efae5ee#file-time-log-fish-L55), for now. Can't say I'm very happy about that, but, you know, gotta move on.

Thanks everyone!
