### ISSUE TITLE
Functions not listening to events before the first load

### ISSUE THREAD

**Issue by wojtekerbetowski** [fish-shell/fish-shell#845]
Here's my case - I've a function myfunc in ~/.config/fish/functions

    $ functions myfunc 
    function myfunc --on-event doneevent
        echo done
    end
    $ 

If I enter new fish shell, the function is not 'activated' (not reacting to event). 

    $ emit doneevent
    $ 

Although is I 'touch it' (call `myfunc`, or call `functions myfunc`) then it starts listening.

    $ functions myfunc 
    function myfunc --on-event doneevent
        echo done
    end
    $ emit doneevent
    done
    $ 

It seems that event listeners are not activated by default. The workaround is to manually activate it in config.fish (lame).

**Comment by languitar** [comment]
I also just stumbled across this. Some kind of fix or at least explanations in the doc would be great.

**Comment by bucaran** [comment]
It would be lovely if fish could predict which functions have event handlers attached and autoload them, but that would be unecessarily complicated maybe? The `config.fish` is the entry point to the shell fission, I mean, fish session, and that's where any configuration loading should take place or at least get started off. That's not a workaround, it's how it is. If you like to do things the clever way, don't define any functions in `config.fish`, but rather source a file that loads your configuration. 

This is how we currently do it in [`oh-my-fish`](https://github.com/bpinto/oh-my-fish/blob/master/oh-my-fish.fish).

**Comment by zanchey** [comment]
What wording would be helpful?

**Comment by faho** [comment]
So now since #1382 has shown up, there seems to be a need to allow event handlers to be added from the outside.

How should that look? Asking people to add something to config.fish is obviously not great, but the best I've come up with is adding an additional directory (called "events" or "hooks" or similar) that essentially contains functions that will either always be sourced or sourced on every event, but even that isn't exactly beautiful.

Another solution (which would also be useful for e.g. function descriptions) is to, on start, peak at the function definition part of any .fish file, but that's very specialized.

**Comment by bucaran** [comment]
@faho Yes. Have a `events` directory and source all files in there at the start of the shell. Fish could do that just like it autoloads functions in `$fish_function_path`, but IMO this should be handled in userland.

For example in Wahoo, we source any `$WAHOO_CUSTOM/init.fish` file during session start. This could easily be augmented to also source any `$WAHOO_CUSTOM/events.fish` file, where we could suggest users to write their event handlers. Since the framework loads this automatically at the start, it would work across different shell sessions.

**Comment by faho** [comment]
>For example in Wahoo, we source any $WAHOO_CUSTOM/init.fish file during session start. This could easily be augmented to also source any $WAHOO_CUSTOM/events.fish file

Really, files are nicer to outsiders wishing to add event listeners. E.g. pantheon-terminal could just drop-in a file (that can be properly managed by the package manager) to do the notification stuff. Of course that also implies override-logic like for completions.

**Comment by zanchey** [comment]
A good solution to #1956 should enable this.

**Comment by bucaran** [comment]
@zanchey Careful, you are stumping on userland territory.

BTW, ~~Wahoo~~ → [Oh My Fish!](https://github.com/fish-shell/oh-my-fish) now supports this basic feature by sourcing `$OMF_PATH/events.fish` and `$OMF_CUSTOM/events.fish`.

**Comment by zanchey** [comment]
How do you mean, userland territory?

**Comment by bucaran** [comment]
@zanchey This is an old thread. I am saying, why should Fish address loading files with function events if that's something users could handle sourcing any relevant files.

**Comment by faho** [comment]
See e.g. #1382 - so that outside packages can drop in event handlers to enable additional features.

**Comment by bucaran** [comment]
@faho Ah, I see. Oh :disappointed:
