### ISSUE TITLE
Long options for echo builtin

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8451]
I suggest add the following long options for `echo`:

- `--no-newline` for `-n`
- `--separate` for `-s`
- `--unescape` for `-E`
- `--escape` for `-e`

Long options are more verbose and user friendly. Maybe I can try to do it but unfortunately I don't know C++ now.

**Comment by ridiculousfish** [comment]
In general short options should have long equivalents, but we should not be adding new options to `echo`, because `echo` is often used to output unknown strings, which may be accidentally interpreted as options. That's why POSIX says that `echo` shouldn't even recognize `--` (though fish's implementation does).  Closing.

**Comment by EmilySeville7cfg** [comment]
Maybe I am mistaken but is there any problem to support `--` to allow unknown strings entered after it? And when we have to refer to POSIX in general? ;) I wanna understand not to fill wrong issues in the future.

**Comment by ridiculousfish** [comment]
The concern is something like `set var -- --escape && echo $var` which would not print what you might expect. In principle, probably we ought to use `echo --` everywhere, but we don't and users don't, especially because other shells don't support that. 

As for POSIX compatibility, fish is roughly "stick to POSIX when it's not actively bad." Supporting `--` in `echo` was done (perhaps inadvertently) in 1d4a0fb091f649634d90149f2a4c1cb14a7ae23f which was a long time ago.
