### ISSUE TITLE
Delete word bacwards/forward

### ISSUE THREAD

**Issue by Stylo2k** [fish-shell/fish-shell#8464]
## Question

fish, version 3.3.1

I can not figure out how to bind the ctrl + del and the ctrl + backspace to delete a word forward/backward.
 I have tried to add the following to my config.fish file but it did not work :
![image](https://user-images.githubusercontent.com/65516452/142728782-dcd35567-8a2e-4e12-ae00-957bd1d0e225.png)

**Comment by faho** [comment]
`-e` is to *erase* a pre-existing binding.

`--preset` is to adjust the *preset* bindings instead of your own. As a user you don't need it.

Also, the way you have spelt the key is broken: `\c[3;5~]` has the `;` unquoted. `;` ends the current command.

So this runs `bind --preset \c[3`, and then it runs the command `5~]` with the arguments `backward-kill-path-component`.

What you want to do is to run `fish_key_reader`, press whichever key combination you want bound. It will tell you something like

```
Press a key:
              hex:   1B  char: \c[  (or \e)
(  0.041 ms)  hex:   5B  char: [
(  0.027 ms)  hex:   33  char: 3
(  0.028 ms)  hex:   3B  char: ;
(  0.036 ms)  hex:   35  char: 5
(  0.041 ms)  hex:   7E  char: ~
bind \e\[3\;5~ 'do something'
```

See that last line? That's what you want. Just take that `do something` and replace it with `backward-kill-path-component`:

```fish
bind \e\[3\;5~ backward-kill-path-component
```

**Comment by Stylo2k** [comment]
Works like a charm! Thanks a lot, for informing me about the `fish_key_reader`. Searched everywhere and no one recommended it. 
fish is even cooler than I thought
