### ISSUE TITLE
string replace drops NUL and following text

### ISSUE THREAD

**Issue by imcaizheng** [fish-shell/fish-shell#8468]
## Version
fish, version 3.3.1

## Expectation
``` fish
$ echo text | string replace 'ex' \0es | tr '\0' '\n'
t
est
```

## Actual Result
``` fish
$ echo text | string replace 'ex' \0es | tr '\0' '\n'
tt
```

## Related Issues
1. [string escape drops NUL and following text](https://github.com/fish-shell/fish-shell/issues/4605)
2. Nul char causes unexpected result even on command line. For example, `echo 1\0"2"` outputs `1` instead of `12`

**Comment by faho** [comment]
NUL chars *cannot* be passed as arguments. Your `\0es` is effectively an empty argument.

This is a general UNIX thing - you *can't* call e.g. `grep \0es`. We could special-case builtins here, but so far we haven't done so, because there's typically little use in doing that - you don't just add NULs all over the place, because many things can't handle NULs.

**Comment by imcaizheng** [comment]
@faho Thanks for the clarification! I think this issue can be closed now.
