### ISSUE TITLE
[Bug] $fish_cursor_unknown not working

### ISSUE THREAD

**Issue by realmazharhussain** [fish-shell/fish-shell#8470]
Since my (poorly worded and mis-understood) issue #8469 was closed without my problem being actually solved. I open this issue.

### Problem

- Need line cursor everywhere (including in commands being run by fish e.g. pacman, bash, read, etc.) except in visual,normal,replace mode
- Following code should do what's stated above but doesn't
  ```fish
  set fish_cursor_default block      blink
  set fish_cursor_unknown line       blink
  set fish_cursor_insert  line       blink
  set fish_cursor_replace underscore blink
  set fish_cursor_visual  block
  ```
  **Note:** Every line except the one with `fish_cursor_unknown` works perfectly and this line seems to do nothing
- There seems be no appearent way to do what I want

### My Setup

**Fish Version:** 3.3.1
**OS:** Manjaro
**Fish Installation:** Manjaro Repositories

**Comment by faho** [comment]
`fish_cursor_unknown` is the value that is used when no other variable for the mode has been defined.  E.g. if you haven't set $fish_cursor_insert and switch to insert mode, fish tries $fish_cursor_unknown instead. Since you have defined all the other variables it won't be used at all in your configuration.

It's *not* the value that is used for external commands. That doesn't currently exist, and that's tracked in #4656.

**Comment by realmazharhussain** [comment]
Thanks
