### ISSUE TITLE
Several PCRE hints for string builtin

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8475]
I wanna add the following hints while typing regex via complete for string builtin:

- \d, \D, \s, \S, \w, \W
- [[:alnum:]], [[:alpha:]], [[:ascii:]], [[:blank:]], [[:cntrl:]], [[:digit:]], [[:graph:]], [[:lower:]], [[:print:]], [[:punct:]], [[:space:]], [[:upper:]], [[:word:]], [[:xdigit:]]

I create this issue as a reminder for myself to do it. ;)

**Comment by floam** [comment]
That is going to be tricky.

**Comment by krobelus** [comment]
In theory, computing comletions based on `commandline -t` is possible, but there are limits.
Say we offer a comletion

    complete : -xa '(echo (commandline -t)\\[[:alnum:]])'

This will work if you type something like `: someprefix`.
But regex args are usually quoted, like `: 'someprefix`.
The quote will be escaped when inserting the above completion. We don't have a good ways to deal with incomplete tokens in fish script but this technique works for `: 'someprefix`:

    complete : -xa '(echo -n (commandline -t | string unescape); echo [[:alnum:]])'

The final version should probably only offer completions if we have at least one character.
So if there is a \ we offer \d etc.

So yeah, it seems tricky to get right because we don't have a framework for sub-token completions, but it might be possible without resorting to C++

**Comment by mqudsi** [comment]
I think I did something in the ffmpeg completions that would be along the same lines as what's needed here.

There's a couple of other possible examples, but I'm thinking of the code used to complete filter expressions: https://github.com/fish-shell/fish-shell/blob/fbac70ab3865df45bc33542c86c8159cbd9a286f/share/completions/ffmpeg.fish#L240-L321

**Comment by EmilySeville7cfg** [comment]
Thanks :) I will consider the given completion

**Comment by EmilySeville7cfg** [comment]
Sorry but I will not implement it. :( You can assign anybody else or let this issue be unassigned unless somebody implement it.

**Comment by ridiculousfish** [comment]
Closing; someone else is free to tackle this if they like.
