### ISSUE TITLE
preexec function incompatible with python `input()`

### ISSUE THREAD

**Issue by ElDifinitivo** [fish-shell/fish-shell#8484]
fish: v3.3.1

os: Void Linux 5.13.9_1

term: alacritty (xterm-256color), kitty (kitty), tmux (screen256-color)

I'm testing out a preexec function which calls a python script that requires stdin through the `input()` function. What I'd expect is for every time the function is called and the python script is run, that the script will stop and wait for input before continuing.

However, only on its first run with a fresh `fish` process will the shell allow me to type anything at all. Subsequent calls to the preexec function will print the `input()` prompt, but any keyboard input will not be registered, required <C-c> to kill the process.

I've tried this on both alacritty and kitty, in and out of tmux, and with an unmodified `~/.config/fish` except for the preexec function saved under `conf.d`.

To reproduce: run the below and start a new fish instance.

```fish
$ echo -e "function preexec --on-event fish_preexec\n    python3 -c 'input()'\nend" > ~/.config/fish/conf.d/preexec.fish
```

I have also tried this on `zsh` with its preexec hook as well as [on bash](https://github.com/rcaloras/bash-preexec) and it works flawlessley on those two shells. Is there something obvious I'm missing with how `fish` handles preexec?

**Comment by faho** [comment]
This works for me:

```fish
function pre --on-event fish_preexec
    stty sane
    python3 -c 'print("foo"); a = input(); print("input was: ", a)'
end
```

The reason your thing doesn't appear to work is because fish does much more with the terminal. E.g. highlighting and autosuggestions requires it to handle the output much more closely, so it turns off the default input echoing. That's why you're not seeing anything.

And pressing return doesn't end the input reading because fish turns on the mode that allows it to distinguish \r from \n - which also makes it possible to tell ctrl-m (which *is* \r) from ctrl-j (which *is* \r).

So python is reading input, but it's not being echoed, and it never reads a newline so it never stops reading. So it appears nothing is happening.

To change that, `stty sane` restores the terminal settings to a reasonable setting. (I would have called it something else, but oh well)

This isn't done in preexec commands because it's not expected you'd be handling the terminal there.

**Comment by ElDifinitivo** [comment]
Ah I got it now, I had a feeling I was missing something as the python script worked 100% of the time when called directly. I'm still new with fish after years of zsh so I haven't gotten full hang of it yet.

Thank you!
