### ISSUE TITLE
Cannot modify a global list by index when `-l` or `--local` option is set

### ISSUE THREAD

**Issue by imcaizheng** [fish-shell/fish-shell#8504]
## Fish Version
``` fish
$ fish --version
fish, version 3.3.1
```

### Examples
Inside a block try to create a local variable, by modifying the global one.

``` fish
function test_local_scope
  begin
    set -l animals[3] giraffe
    echo $animals
  end
end

set -g animals fish cow
test_local_scope
```

Same as the above except using the `--append` approach.
``` fish
function test_local_scope
  begin
    set -la animals giraffe
    echo $animals
  end
end

set -g animals fish cow
test_local_scope
```

### Expectation
Both examples output `fish cow giraffe`.

### Actual Result
The second example worked as expected while the first example output two spaces + `giraffe`, just like the values in the global variable all disappeared inside the block.

**Comment by mqudsi** [comment]
I think both are pedantically correct but I'm not sure the first should be supported because it's weird. Maybe even the second.

`set array[3] foo` sets the 3rd index of existing variable `array` to `foo`, or if no such variable existed, creates a new variable and sets the third index to `foo` (the other indices are left empty). In the OP's example, `set -l array[3] foo` does just that, without any thought to the global scope because `set -l` will either mutate an existing *local* variable or create a new one.

`set -a foo bar` though is just shorthand for `set foo $foo bar`, making the second example `set -l animals $animals giraffe` and since at that point `$animals` only exists in the global scope, a new local variable `animals` is created but filled from the contents of the existing global variable `animals`. 

But the first example makes it look like the value of a single element in an existing global array is being shadowed with a local variable, which is of course something we don't support. I find the second less confusing (and it's also helpful for doing things like temporarily appending to `fish_user_paths` in a one-liner), but I certainly wouldn't miss it if it were disallowed.

**Comment by mqudsi** [comment]
I'm going to close this because I can't see us doing anything here that wouldn't break some valid usage case or the other, and it's hard to say what exactly is the most intuitive behavior for the actions described. Feel free to discuss this further and we can always reopen it if we find something definitively wrong.
