### ISSUE TITLE
git and openssl completions incomplete

### ISSUE THREAD

**Issue by derust** [fish-shell/fish-shell#8516]
fish, version 3.3.1 on macOs

#### fish
```sh
❯ git clone --                                                                  master
--bare                                                (Make a bare Git repository)
--branch  (Use a specific branch instead of the one used by the cloned repository)
--depth                  (Truncate the history to a specified number of revisions)
--help                                       (Display the manual of a git command)
--mirror                                (Set up a mirror of the source repository)
--no-checkout       (No checkout of HEAD is performed after the clone is complete)
--no-hardlinks                             (Copy files instead of using hardlinks)
--origin                (Use a specific name of the remote instead of the default)
--quiet                               (Operate quietly and do not report progress)
--recursive               (Initialize all submodules within the cloned repository)
--verbose                           (Provide more information on what is going on)
```

#### zsh
```sh
$ git clone --
--bare                 --jobs=                --recurse-submodules   --shared
--branch=              --local                --reference-if-able=   --single-branch
--checkout             --mirror               --reference=           --sparse
--config=              --no-...               --reject-shallow       --tags
--depth=               --no-checkout          --remote-submodules    --template=
--dissociate           --no-hardlinks         --separate-git-dir=    --upload-pack=
--filter=              --no-tags              --server-option=       --verbose
--hardlinks            --origin=              --shallow-exclude=
--ipv4                 --progress             --shallow-since=
--ipv6                 --quiet                --shallow-submodules
```

#### fish
```sh
❯ openssl  pkey -   //tab here show nothing
```
#### zsh
```sh
$ openssl pkey -
-engine   -- use the specified engine, possibly a hardware device
-in       -- input file
-inform   -- input format
-out      -- output file
-outform  -- output format
-passin   -- input file pass phrase source
-passout  -- output file pass phrase source
```

Fish is a fabulous shell,  I love it
But IMHO command auto-completion is a killer feature for daily use,
Why fish doing it so poor? 
Is it because it harder to implement than Zsh since Fish is not POSIX compatible,
Or just simple because Zsh has larger user base therefore  more contributors than Fish?

**Comment by faho** [comment]
The completions simply need to be adjusted.

PRs welcome.

**Comment by derust** [comment]
Sorry for the unthought words & thanks for your great work

I was just surprised that Zsh's auto-completion is better than Fish, and nobody told me that before.

**Comment by faho** [comment]
>I was just surprised that Zsh's auto-completion is better than Fish, and nobody told me that before.

Completions are always a best-effort thing. There is such a large surface of things to complete that it's essentially impossible to have everything. It's always going to be a work-in-progress.

There are cases we are worse than zsh, there are cases we are better than zsh. In this case, we are better in providing descriptions - what is "--branch"?

So a blanket "fish is doing poorly" is simply wrong and unhelpful.

----

I will be adding the options you have mentioned.

**Comment by floam** [comment]
I totally understand the impulse to be a harsh critic when ones notice an obvious wart on our beloved fish, but it's really not a great look when it comes off unkind. Keep in mind:

zsh has many more individuals and enterprises that put together completions for their shell, which of course has millions more users than fish does and it is a very mature project. fish completions can be quite rich and provide a pretty awesome tailored interactive experience, and that takes a lot of time and effort. Since we work on completions and we're also core developers of the shell, and we all have some opinions about aspects of the fish completions system that could be made so that we could more easily write completions, or express certain things easier, nothing is really gong to get easier without blood sweat and tears either way, short of more people contributing completions or contributing to fish internals.

fish is not worked on by a huge team. There's one individual, @faho, that has most consistently worked on maintaining the completion library that has expanded, aged, grown in complexity, and become saddled with more and more software he does not even use personally, whilst behavior of the software changes over time, yet the completions have improved in quality the platform support improved despite his limited access and general grumpiness towards certain BSD and Mac matters: he's done this for years and it's really quite amazing.

**Comment by wuhx** [comment]
@floam
No, it's not a critic. The only intention is to point out an issue on Fish (apology for the `so poor` part).

Git and OpenSSL are just two examples. There must be other applications that have the same problem, 

there is already an [ISSUE](https://github.com/fish-shell/fish-shell/issues/6073) about Fish's git auto-completion which closed, but git's auto-completion in Fish is still incomplete.



**The purpose of this issue is to know the reason behind why Fish's auto-completion is incomplete.**

Is it harder to implement or just less manpower than Zsh?

I think @faho 's answer is later.



then my thought is:

1. let people know some of their favorite app's auto-completion may not work as well as Zsh. 
2. have a separate repo(or other better way) to hold fish's auto-completion file, make user easily find or contribute to.
3. find a way to translate bash or Zsh 's auto-completion file to Fish automatically.

 Fish is a fabulous shell, for its fancy look, fast speed  & work out of the box.
But let's face it, auto-completion is its weak point, for whatever reason.

We can either fix it or point it out to users, so they can have other choices, 
who may be sold by an online article, and spend hours to transfer his Zsh environment to Fish.

**Comment by derust** [comment]
@floam
It's not a critic. The only intention is point out an issue on Fish (apology for the `so poor` part).

Git and OpenSSL are just two examples. There must be other applications that have the same problem, 

there is already an [ISSUE](https://github.com/fish-shell/fish-shell/issues/6073) about Fish's git auto-completion which closed, but git's auto-completion in Fish is still incomplete.


**My purpose is to know the reason behind why Fish's auto-completion is incomplete than Zsh**

Is it harder to implement or just less manpower than Zsh?
I think @faho 's answer is later.


then my thought is:

1. have a separate repo(or other better way) to hold fish's auto-completion file, make user easily find or contribute to.

2. find a way to translate bash or Zsh 's auto-completion file to Fish automatically.

**Comment by faho** [comment]
@derust Please do assume that you're not the first one to think about this.

Using bash's completions has been discussed and rejected. In short they would require executing arbitrary bash scripts and they're worse than what we would want, lacking descriptions.

Adding a separate repo also doesn't help, because it does not make more people contribute, and means having to keep it usable with multiple fish versions.

The solution is really really really simple: Do the work. The completions simply need to be done. To a certain degree you can do man parsing and  machine translation, but to have actual good completions someone needs to step up and do the work.

-----

Anyway, this doesn't lead anywhere. The only actionable thing here is that a few options in git and openssl is missing. We'll add those and then we'll close, please stop discussing anything else because it's not helpful.

**Comment by faho** [comment]
Okay, this issue isn't really actionable because working on especially the git completions is an ongoing process. That's why I'm closing it.
