### ISSUE TITLE
`command -v` doesn't print shell builtins or function names

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#8543]
In other shells `command -v` outputs shell function names and builtins and is not just a `which`-alike for commands in PATH. My recollection is `-v` was added specifically for some POSIX parity; I think it should follow.

**Comment by floam** [comment]
every other shell: 
```
$ command -v printf
printf
```

**Comment by krobelus** [comment]
sounds good. Interestingly, this is also for keywords that are not really commands, `command -v in` prints `in`

**Comment by floam** [comment]
Almost everyone: 

```shell
~ $ ksh -c 'command -v in'
in
~ $ dash -c 'command -v in'
in
~ $ zsh -c 'command -v in'
~ [1]$ bash -c 'command -v in'
in
~ $ sh -c 'command -v in'
in
~ $ tcsh -c 'command -v in'
in
```

**Comment by faho** [comment]
Yes,, this is right.

`command` in posix is super confused, and it's very very hard to figure out what it is supposed to be *for*.

The way we do it is much cleaner:

- `command` is for external commands. Running something with `command` runs /usr/bin/thatthing, searching it searches for that thing
- `functions` checks functions
- `builtin` checks builtins
- `type` checks all of them

Please don't break that.

**Comment by faho** [comment]
>My recollection is -v was added specifically for some POSIX parity

To be clear since the difference was apparently missed in #8547:

`command` basically always had `-s` or `--search`, and needs them. The POSIX-compatibility bit is just that `-v` is treated the same as `-s`.

I do not believe changing both of them together (which would break every current use of `command -s`) or changing just -v (making it diverge and breaking every current use of it) are good ideas.

**Comment by floam** [comment]
Fair enough
