### ISSUE TITLE
<Tab> to accept suggestion rather than <Enter>

### ISSUE THREAD

**Issue by tristone13th** [fish-shell/fish-shell#8572]
**YOUR TEXT HERE**

Is there any way to accept the suggestion using \<Tab\> rather than \<Enter\> when I have typed <Enter> and the suggestion window poped up?

**Comment by faho** [comment]
You can press either something that does "accept-autosuggestion", or whatever moves the cursor over the suggestion plus, as a special case, enter (which does "execute"). This includes e.g. right-arrow or ctrl-f.

Tab is a bit annoying, because how would you then trigger normal completions? E.g. you enter

```fish
git a
```

and it suggests `git add myfile`. You press tab, but actually you wanted `git apply`. How would the key binding know that?

So I don't know of a good way to bind tab to also accept it, or how the logic would even work.

**Comment by tristone13th** [comment]
> You can press either something that does "accept-autosuggestion", or whatever moves the cursor over the suggestion plus, as a special case, enter (which does "execute"). This includes e.g. right-arrow or ctrl-f.
> 
> Tab is a bit annoying, because how would you then trigger normal completions? E.g. you enter
> 
> ```fish
> git a
> ```
> 
> and it suggests `git add myfile`. You press tab, but actually you wanted `git apply`. How would the key binding know that?
> 
> So I don't know of a good way to bind tab to also accept it, or how the logic would even work.

Sorry for the misleading information. I just don't want to fill the command automatically when I'm moving around between the suggestion items, I prefer to use \<Tab\> to accept the right item and fill it in the command line, is there anyway to realize this feature?

**Comment by faho** [comment]
> is there anyway to realize this feature?

Like I said: No. I have no idea how that would work, because how would you then do completions?

You can, of course, make tab accept the suggestion, but then you have to pick a different key to complete.

E.g. 

```fish
bind \t accept-autosuggestion
bind \cg complete
```

to make ctrl+g do tab completion instead.

There is also no way to stop autosuggestions from being accepted when you move over them, and we will not be adding that as an option.

**Comment by tristone13th** [comment]
> > is there anyway to realize this feature?
> 
> Like I said: No. I have no idea how that would work, because how would you then do completions?
> 
> You can, of course, make tab accept the suggestion, but then you have to pick a different key to complete.
> 
> E.g.
> 
> ```fish
> bind \t accept-autosuggestion
> bind \cg complete
> ```
> 
> to make ctrl+g do tab completion instead.
> 
> There is also no way to stop autosuggestions from being accepted when you move over them, and we will not be adding that as an option.

Okay, thanks for your reply!

**Comment by zanchey** [comment]
Sounds like the question has been answered.
