### ISSUE TITLE
Ctrl - Alt - UpArrow inserts [1;7A

### ISSUE THREAD

**Issue by tim-hilt** [fish-shell/fish-shell#8581]
fish-version: 3.3.1
OS: Arch Linux, kernel 5.15.10-arch1-1
`$TERM`: `xterm-kitty` (but also tested with Alacritty and Konsole)

I also tried it without customization.

Let me prefix this by saying: I'm not sure this is a bug, but I consider it at least sketchy UX. My issue is basically described by the title. It also happens with other modifier-key-combinations. I have searched the web far and wide, but didn't seem to find any answer to my problem.

Is there some way to disable this behavior?

**Comment by faho** [comment]
Simple:  This key isn't bound, because it's key sequence that isn't included in terminfo. The actual sequence starts with an escape. The reason we print the other characters is because these are actual characters we read and we have no way of knowing that they belong to an escape sequence (unfortunately that is how this works).

So, simply bind them:

```fish
bind \e\[1\;7A whatever
```

and probably B, C, D instead of A for left, right, and down.

If you just want to neuter them, make "whatever" `true`.

**Comment by tim-hilt** [comment]
Will do, thanks for the quick feedback!

**Comment by faho** [comment]
Okay, question appears to have been answered.
