### ISSUE TITLE
Git bare repo completion really slow

### ISSUE THREAD

**Issue by jorpilo** [fish-shell/fish-shell#8592]
fish version: 3.3.1
OS: Arch linux 5.15.10-arch1-1
Terminal: Alacrity, $TERM=xterm-256color

I have created a git bare repo to manage my dotfiles in the following way:
```fish
git init --bare $HOME/.cfg
alias -s cfg='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
cfg config --local status.showUntrackedFiles no
```

so when I want to add a file I just run
`cfg add somefile.txt`

The autocomplete in fish works out of the box however it's extremely slow and simple autocomplete such as `cfg add file` takes around 15-20 seconds

I have profiled an autocomplete of a git add, the file is really big so I have sorted it and cut the end. I can provide the full file if necessary.
[git_add_profile.txt](https://github.com/fish-shell/fish-shell/files/7782353/git_add_snippet.txt)

Any recommendation or suggestion to improve this completion time?

**Comment by jorpilo** [comment]
I found the issue.
`cfg rev-parse --is-bare-repository` returned always false unless executed from the .git folder

```
~
❯ cfg rev-parse --is-bare-repository
false

~
❯ cd .df

~/.df on  legion
❯ cfg rev-parse --is-bare-repository
false

~/.df on  legion
❯ git rev-parse --is-bare-repository
true

```

Therefore __fish_git_files was not detecting the bare repo.

Instead of rev-parse, using `git config --get core.bare` works fine.

I have changed fish_git_files to the following and it's working, in addition, if the repo is a bare repo, I have just returned __fish_complete_path to get some completion:

```
    # Save the repo root to remove it from the path later.
    set -l root (__fish_git rev-parse --show-toplevel 2>/dev/null)
    or return

    set -a root (__fish_git config --get core.bare 2>/dev/null)
    or return

    # Skip bare repositories.
    if test "$root[2]" = true
        __fish_complete_path
        return
    else
        set -e root[2]
    end
```

**Comment by krobelus** [comment]
> alias -s cfg='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

git will change directory to the worktree ($HOME), that's why you are not in a bare repo.

So the completions are correct, just really slow, because they are running

	git status --porcelain=2 -uall

in your $HOME.

`-uall` descends into every untracked directory, wherease `-unormal` is the default from git status (for untracked files inside directories only show the directory). Unfortunately we can't easily use that for completions.

I think the recommended solution is to ignore untracked files, perhaps use `echo '*' >> ~/.gitignore` and then un-ignore the paths you care about.

The __fish_complete_path workaround works in your cases, but it will wrongly give files in actual bare repositories.
You can use something like `complete cfg -n '__fish_git_using_command add' --force-files` in your config for a similar effect, but that leaves other subcommands.

**Comment by faho** [comment]
Okay, question was answered, closing!
