### ISSUE TITLE
subshell in fish does not behave as expected

### ISSUE THREAD

**Issue by comalice** [fish-shell/fish-shell#8616]
### software versions

* `fish, version 3.3.1`
* `Linux <redacted> 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 GNU/Linux`
* `echo $TERM` yields xterm-256color
* no customizations

### expected behaviour

In bash, redirecting a subshell produces a valid file descriptor that can be consumed by other applications on the command line.

```
# wc <(echo "lol wat")
      1       2       8 /dev/fd/63
```

### actual behaviour :(

In fish, it appears the file descriptor is consumed by fish, and the contents of the subshell are delivered to the parent shell as a string.

```
# wc (echo "lol way")
wc: 'lol way': No such file or directory
```

### etc.

I could not find much in the documentation on file descriptors or how fish generates/manipulates them.

**Comment by faho** [comment]
>  wc <(echo "lol wat")

This is process substitution.

Fish's `()` is the same as bash's `$()` - "command" substitution.

To do something like process substitution, use `psub`, like

```fish
wc (echo "lol way" | psub)
```

Or, even simpler, just *pipe* it into `wc` because you can:

```fish
echo "lol way" | wc
```

Please read the documentation, in this case https://fishshell.com/docs/current/fish_for_bash_users.html#process-substitution.

**Comment by comalice** [comment]
It looks like I had my terminology mixed up. Thank you for pointing me the right direction!
