### ISSUE TITLE
RFC: Rendering escaped spaces as dots or another special character in the command line

### ISSUE THREAD

**Issue by andmis** [fish-shell/fish-shell#8620]
This is not a great user experience:
![image](https://user-images.githubusercontent.com/5308024/148488217-d92436a2-682e-451f-929f-f8562a06d38c.png)

What if we render it like this?
![image](https://user-images.githubusercontent.com/5308024/148489022-e92d4a1e-bd60-4068-a4b7-ba576d221cf4.png)

Or this?
![image](https://user-images.githubusercontent.com/5308024/148489138-e598803d-4905-45ed-9beb-84e100305f90.png)

The user would still type backslash-space to produce one of these. We would have to decide whether backspacing over it deletes the escaped space, or reverts to a backslash. We would also need to be careful about how to render filenames that have the actual literal character (center dot or underbrace or whatever) we are using for "escaped space".

But IMO that looks pretty cool... and it would be really nice to have pretty-looking folder names when browsing in a directory tree that has a lot of files and folders with spaces.

**Comment by krobelus** [comment]
Not sure, feels a bit like a workaround for https://github.com/fish-shell/fish-shell/issues/5433
We could complete `ls ~/G` to `ls ~/"Google Drive/"` and a second <kbd>Tab</kbd> makes it `ls ~/"Google Drive/My Drive/"`

**Comment by faho** [comment]
Fish's commandline is just that: A command line you can type commands in fish's syntax into. Both of these would either imply more syntax (i.e. you could *type* what it shows) or break copy-paste. Neither of which are, in your words "great user experience".

So let's keep this in #5433.

**Comment by floam** [comment]
Wouldn’t break copy and paste if fish interpreted a literal of that character as a space, and requires THAT be escaped to use in a path.

**Comment by andmis** [comment]
@floam are you saying you like the proposal? :)

**Comment by floam** [comment]
Yeah I do. I hate slash space escapes. I hate reading paths and using a mental parser to unescape. I think it's bad UX.

I've toyed with a few ideas about this.

I hadn't thought of actually using a character to represent it. My thoughts have been either interactively forcing it over to quoted escape without that being jarring, and I had some ideas about paths being rendered interactively with a background color or reverse text to indicate a token is a long contiguous thing and spaces are inclusive, with spaces perhaps being actual spaces but rendered with a underline set and/or an off color. But that does break copy and paste. 

I think some variation of your idea has merit.

**Comment by floam** [comment]
Reopening since I kinda want to chat about this more. Sorry I missed it.

**Comment by zanchey** [comment]
#5433 is what Windows' command interpreter does and it is good UI, I think

**Comment by faho** [comment]
Yeah. This is asking for one of two things:

Either we introduce a new character that is interpreted as an escaped space. This would have to be a non-ascii character (because there is no applicable ascii character) that is available in all fonts, and it would have to look sort of space-like but not really. This would be the first non-ascii special character we have, and it would be the first you couldn't type on a normal keyboard. It would also be entirely unfamiliar to people coming from any other shell or programming language I'm familiar with.

Or we would introduce our first difference in what the commandline contains conceptually and visually. This would break copy-paste, but we could special-case it for pasting into fish specifically. It would still break if you pasted into an editor and then tried to run that file as fish script. It would be confusing since there'd be a disconnect between the actual language and the rendering.

Both ideas seem obviously horrible to me, especially when we can just improve the quoting/escaping heuristic. Let's just do that instead.

**Comment by floam** [comment]
Yeah probably not practical.
