### ISSUE TITLE
Integrate shellfirm project into fishshell

### ISSUE THREAD

**Issue by kaplanelad** [fish-shell/fish-shell#8634]
Hey, I'm trying to integrate [shellfirm](https://github.com/kaplanelad/shellfirm) project to fishshell terminal

I added the following code to config.fish FILE 

```bash
function pre_exec
    {EXUCUTE MY BINARY}
    commandline -f execute
end

function fish_user_key_bindings
    bind \r pre_exec
end
```

The `{EXUCUTE MY BINARY}` is my custom binary which prompts a message to the user. and it works, the binary executing and show the promo by the but when I click my answer it did not receive my key types. 

for example: 
```bash
 ~> rm -rf /tmp/
#######################
# RISKY COMMAND FOUND #
#######################
* You are going to delete everything in the path.

Solve the challenge:: 9 + 0 = ? ^C to cancel

```
The terminal freeze and can enter my answer. 

Can you please help me to figure out what I'm doing wrong?

**Comment by faho** [comment]
>The terminal freeze and can enter my answer.

Most likely it is not. Just enter your answer and press ctrl-j.

In short: When fish itself has control of the terminal, it sets some terminal "modes". This includes things like turning off echoing of the output, which is necessary to support syntax highlighting, and making it so ctrl-j (which is the same as \r) and ctrl-m (which is the same as \n) are distinguishable, which makes the return key send \r instead of \n.

When fish runs a binding, it doesn't reset these things even if it runs an external command because it has no idea that this should take control of the terminal. Bindings aren't meant for running long-running commands or commands that need access to the terminal.

You can try to add `stty sane` in there:

```fish
function pre_exec
    stty sane 
    {EXUCUTE MY BINARY}
    commandline -f execute
end
```

This will reset the terminal modes to a specific default set. It might break other things. Like I said: Bindings aren't meant for this, this isn't the sort of integration we want to have.

>Hey, I'm trying to integrate shellfirm project to fishshell terminal

Fish is a shell, not a terminal. "fishshell terminal" is not a thing.

**Comment by kaplanelad** [comment]
Thanksyou @faho.
Adding `stty sane` fixed the issue
