### ISSUE TITLE
fish_title: too damned long?

### ISSUE THREAD

**Issue by martisj** [fish-shell/fish-shell#8641]
fish: `3.3.1`
macos: `12.1`
kitty: `0.24.1`
starship: `1.1.1`

Tried `sh -c 'env HOME=$(mktemp -d) fish'` and this worked.

`~/.config/fish/functions/fish_title.fish`
```fish
function fish_title
    if set -q argv[1]
        echo $argv[1]
    else
        echo (basename "$PWD")
    end
end
```

### Expected
A window title with the last dir in `$PWD` e.g. 'frontend'
What I get is `~/p/d/frontend`

If I run `funced fish_title` I get this:

```fish
# Defined interactively
function fish_title
            if set -q argv[1]
                echo $argv[1]
            else
                prompt_pwd
            end
        
end
```

I don't understand where that is coming from. Help is much appreciated 🙏

**Comment by faho** [comment]
`functions -D fish_title` will tell you where it is loaded.

In this case, kitty defines it: https://github.com/kovidgoyal/kitty/blob/47dbaac54f1107be1613ac2e1237c8a719ac12d2/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish#L57-L65. Because this is defined eagerly, it defeats autoloading - fish knows the function already, so it won't be loading it again.

You'll have to open an issue there.

**Comment by page-down** [comment]
This is set by default with kitty's new shell integration feature.
You can turn it off by putting `shell_integration no-title` in `kitty.conf`.

https://sw.kovidgoyal.net/kitty/shell-integration/

As far as I know, this "fish_title" exists for the following reasons.
(Disclaimer: This is just my personal inference.)

- Would like to provide users with a short title when using across different supported shells (Part of the consideration is that the tab will use the title)
- Enabled by default only when run in the terminal, also respects user configuration.
- When needed (e.g. remote SSH host), the user can configure it manually by source a single integration script file.
- Since it is better to match the features supported by the terminal as much as possible, it maybe redundant to show all tabs starting with `fish` (fish /full/path/to/pwd), so defined its own `fish_title`.

I think the integration should be implemented in a way that does not break shell functionality.

Approaches I can think of:

- Put it in `vendor_functions.d` (But how to disable loading the functions from here? Controlled by the environment variable value `no-title` passed from kitty.)
- Insert function folder path in `fish_function_path` as needed when running integration scripts, before `$__fish_data_dir/functions` (Generally the last one).
- (However it is not possible to provide users with integration scripts through a single file.)

I happen to use both fish and kitty, and am cared about this issue. Is there a better way to implement this?
Hopefully, maybe in the future, the integration script in kitty can be completely removed.

**Comment by faho** [comment]
>Approaches I can think of:

All of these will work, with the additional possibility of just not shipping a special title at all. 

I don't believe it's kitty's job to dictate the default title. The reasons you give all boil down to either believing this title is "better", or some appeal to consistency with other shells, neither of which I find convincing.

**Comment by floam** [comment]
> Since it is better to match the features supported by the terminal as much as possible, it maybe redundant to show all tabs starting with fish (fish /full/path/to/pwd), so defined its own fish_title.

I think it is a little unfortunate our default includes "fish" **and** sets both the tab title and window title to the exact same thing. It's indeed redundant IMO, so I understand why they decided to just bend things to their will here.

IIRC, I wanted __fish_config_interactive at one point to just default fish to setting nothing at all at one point, if we detected either terminal.app or were doing the OSC 7 thing for the current working directory, assuming the terminal is going to do it richer and better and knows the shell name, program name, etc.

Their default is actually wiser than that inclination, as it'll fill the $argv gap.

The terminal knows about everything except basically fish functions. kitty's default seems like it might just be a better default in 2021 for many terminals.

I think we also have an open issue somewhere regarding setting the tab and window title separately.

**Comment by floam** [comment]
Ah https://github.com/fish-shell/fish-shell/issues/2692

**Comment by page-down** [comment]
My point is that as a presentation platform, a bridge between the user and the command line program, it should be able to faithfully present the creator's work and ideas.

As a command line program, it might be able to collaborate with the terminal and work together to bring a better user experience to the user.

I don't want to argue, for now I just do what I can contribute, at least not to affect the user's configuration.

As a user of two great open source software, this is good enough for me.

**Comment by floam** [comment]
If it's not obvious what the pain point is - I believe they removed the `(status current-command)` component to avoid some variation of the not-ideal out of the box experience in Terminal.app on a fresh Mac install with fish defaults. I guess they are not getting the redundant cwd since they left that bit in.

<img width="801" alt="Screen Shot 2022-01-16 at 12 28 48 AM" src="https://user-images.githubusercontent.com/291142/149652859-7ea347ce-9283-414c-abb3-d9707b39fad0.png">

I think they're just trying to do for their users using fish the same thing Terminal.app does for zsh here - defaults that don't suck for their terminal and their users.

> I don't believe it's kitty's job to dictate the default title.

Well, it should not be the user's job, and if our defaults aren't working for them and they have no way to control which terminal title components we provide, it **is** their job to fix it for their users. It's kind of like that whole thing with unacceptable sans-serif and monospace defaults. and the next most ideal ui-monospace fix not actually being adopted (yet). We dictate the font out of care for our users.

**Comment by faho** [comment]
>Well, it should not be the user's job, and if our defaults aren't working for them and they have no way to control which terminal title components we provide,

If there is an issue with our default title, then we should simply fix it? So far I've not seen any issues opened about it.

**Comment by floam** [comment]
> If there is an issue with our default title, then we should simply fix it? So far I've not seen any issues opened about it.

I think so, yeah.

**Comment by faho** [comment]
You mentioned there's something similar with Terminal.app. What is it and how do we fix it?

**Comment by page-down** [comment]
I remember the first time I tried fish, I immediately wrote my own fish_title.fish and didn't think to post an issue about this little thing.

@kovidgoyal
Do you have any comments on this?

**Comment by floam** [comment]
@faho see the screenshot above. It's the duplication of "fish" appearing in the window title bar and the tab title bars. And also the path appearing twice.

We don't currently do anything about it. At one point I had committed something that just disables fish_title entirely for Terminal.app/VTE where we are reporting the cwd and should have been able to assume the terminal's are rendering that info their own way.

It had to be reverted for some reason.

**Comment by faho** [comment]
>It had to be reverted for some reason.

b2f047421de0ac9fc89de74e26fc22cd0a10531b. "VTE terminals apparently do not use the OSC sequence to compose title components"

I don't know why a terminal would use the cwd reporting to compose a title sequence, tbh. That seems like a recipe for redundancy.

So we'd disable the title if we're doing cwd reporting but aren't in VTE, or are in specifically kitty or terminal.app. Simple enough.

**Comment by floam** [comment]
I think something that basically needs to be figured out is how do we want to fix it? We do report the CWD to certain terminals via OSC 7 escapes, and they take care of presenting the path to the user. We could use that to logically decide not to print the pwd, but there's no real rule to follow to have any idea if the terminal takes care of presenting the name of the shell / foreground command or not. I think some VTE terminals do accept OSC 7 but it's not the case they print the command name.

**Comment by floam** [comment]
It could also be assuaged by having different default window and tab titles,  since what this really kills is the tabs that all end up ellipsized and the same, or go back to only setting the window title. Which should let the terminal know, hey, you do you on the tabs.

But I have no idea what the actual _problem_ was that prompted https://github.com/fish-shell/fish-shell/issues/47.

**Comment by kovidgoyal** [comment]
To me, as kitty's maintainer it is important to present a unified, consistent and rich out-of-the-box experience for kitty users, that they can then customize however they like. 

Most shells default to not setting a window title at all, so kitty provides one. In the case of fish the default title style really doesn't suit kitty's UI, so by default kitty overrides it. 

The next release of kitty, thanks to efforts from @page-down will not override titles set by users, only the default one set by fish. I think that should eliminate any bug noise you get as a result of kitty's shell integration script. If you think integration between kitty and fish can be improved further, I am all ears and happy to collaborate. Indeed in an ideal world I would like to get rid of kitty's shell integration scripts completely which can only happen if shells are willing to implement the features natively.

**Comment by floam** [comment]
> I don't know why a terminal would use the cwd reporting to compose a title sequence, tbh. That seems like a recipe for redundancy.

Well, one reason why is perhaps you aren't using them to compose a title sequence. as in some title string. Terminal.app uses these for the path/document embues a window:
https://user-images.githubusercontent.com/291142/149654335-981c7d79-7533-4dfa-9c97-c7583e728e18.mov

Maybe even with a "title string" windowing modality you'd still want to selectively shows/hide different title components depending on the context or user preference.

**Comment by faho** [comment]
> Indeed in an ideal world I would like to get rid of kitty's shell integration scripts completely which can only happen if shells are willing to implement the features natively.

Weeeeeellllllll...

We already *do* a lot of this natively!

We already do print a title, we already do set the cursor shape.

What we won't be doing is try to be consistent with other shells - e.g. getting the title schema they use.

>the default title style really doesn't suit kitty's UI

@kovidgoyal What doesn't suit here? Is it the issue that you want to represent OSC7 in the titlebar as well and so you get duplicated information?

I'd be happy to figure out a title that works for everyone, as long as the request isn't to use the exact same format as these other shells.

**Comment by kovidgoyal** [comment]
kitty doesnt use OSC 7, it's a bad idea for reasons I wont go into here. As for why fish_title doesnt suit the UI (this has been a while so I may have forgotten some details):

1) Its too long especially with tabs, when used as tab titles. 
2) Having fish in the tab/window title is not useful and takes up valuable screen estate
3) Having the directory displayed while running a command has too high a cost for the benefit it provides.

I attach a screenshot of how the kitty tab bar looks with just four tabs each running one fish

![screenshot](https://user-images.githubusercontent.com/1308621/149654732-34b2a661-dda0-4186-a014-a82ad5484663.png)

And now the same thing with kitty's title style:

![screenshot](https://user-images.githubusercontent.com/1308621/149654773-b78e1b2f-46b5-4527-a729-d5bf40eacc53.png)


I am sure you have good reasons for the title style you chose, however it isnt really suitable for kitty. A good compromise would be to have some kind of variable controlling the default title style. kitty's shell integration script could set it and fish's default title function could respect it.

A more involved process is to define a new escape code to extend the existing one to allow programs to set both a short and long title. I am willing to do the work on kitty side for this, if you commit to using it in fish.

**Comment by faho** [comment]
>A good compromise would be to have some kind of variable controlling the default title style.

We have a function. Because the title needs to be dynamic, it would have to be some format string, which isn't the kind of API we tend to use. There's a reason we have a fish_prompt function and not a $PS1 variable.

>A more involved, but ultimately better, process is to define a new escape code to extend the existing one to allow programs to set both a short and long title. I am willing to do the work on kitty side for this, if you commit to using it in fish.

Not something I would see us use. For one it's a very very very niche case, for another it's yet another escape code that we would have to detect support for. I know I sound like a broken drum here, but that's really the worst part of dealing with terminals.

----------------

Now, what we *can* do here is adopt something close to your title style. No "fish" and a shortened $PWD. I'm not sure if we want to drop $PWD if there is a different command running, as that would leave things as `emacs` or `vim` a lot.

**Comment by kovidgoyal** [comment]
On Sun, Jan 16, 2022 at 01:59:06AM -0800, Fabian Homborg wrote:
> >A good compromise would be to have some kind of variable controlling the default title style.
> 
> We have a function. Because the title needs to be dynamic, it would have to be some format string, which isn't the kind of API we tend to use. There's a reason we have a fish_prompt function and not a $PS1 variable.

I wasn't suggesting you provide a format string. It was a variable like
fish_title_style=short|long
which the default fish_title() function would read and respect.

> 
> >A more involved, but ultimately better, process is to define a new escape code to extend the existing one to allow programs to set both a short and long title. I am willing to do the work on kitty side for this, if you commit to using it in fish.
> 
> Not something I would see us use. For one it's a very very very niche case, for another it's yet another escape code that we would have to detect support for. I know I sound like a broken drum here, but that's really the worst part of dealing with terminals.

I think I've mentioned this elsewhere but you should really consider
using escape code based detection, it will solve a lot of your issues.
But anyway, that's your look out.

> 
> ----------------
> 
> Now, what we *can* do here is adopt something close to your title style. No "fish" and a shortened $PWD. I'm not sure if we want to drop $PWD if there is a different command running, as that would leave things as `emacs` or `vim` a lot.

Both emacs and vim are capable of setting titles on their own these
days. But in the name of compromise, I am willing to drop kitty's title
function if you use a shortened pwd without fish as that addresses my
major concern.

**Comment by faho** [comment]
>if you use a shortened pwd without fish as that addresses my
major concern.

Done.

**Comment by floam** [comment]
We also set something in the C++ in case the function isn't defined.

**Comment by floam** [comment]
`#define DEFAULT_TITLE L"echo (status current-command) \" \" $PWD"`

**Comment by kovidgoyal** [comment]
> > if you use a shortened pwd without fish as that addresses my
> > major concern.
> 
> Done.

Also done: https://github.com/kovidgoyal/kitty/commit/71106bcd3946b77bbe94d6942af1131399789237

**Comment by floam** [comment]
`#define DEFAULT_TITLE L"echo (status current-command) \" \" $PWD"`

Seems obvious to change that to just $PWD to match as well as we can, or since we do ship a fish_title function these days, it seems like the effect of deleting that maybe ought to just cause no title to be set. Not really a big deal though, for the present discussion.

**Comment by floam** [comment]
Hey that sure is nicer probably everywhere. I'm surprised we hadn't at least been using `prompt_pwd` before. I think a number of us have had our own set for a long time. Thanks @faho, and thank you @kovidgoyal!

<img width="583" alt="Screen Shot 2022-01-16 at 2 44 57 AM" src="https://user-images.githubusercontent.com/291142/149656860-295e6d03-3a32-42aa-a27a-493a54a7a97c.png">

**Comment by faho** [comment]
Counting this as fixed now.

**Comment by page-down** [comment]
@faho @floam 

After connecting via SSH, I find it difficult to distinguish by the title on the tab, e.g. all are shown as "~" (at HOME).

Since we already check SSH in `prompt_login`, does it make sense to output the hostname in `fish_title` as well?

prompt_login.fish
```fish
# ...
# If we're running via SSH, change the host color.
set -l color_host $fish_color_host
if set -q SSH_TTY; and set -q fish_color_host_remote
    set color_host $fish_color_host_remote
end
```

hostname title prefix:
```text
hostA: ~
hostB: ~
```

Thank you.
Disclaimer: The ability to show the hostname in title when connecting via SSH (zsh, bash) will be available in the next kitty release.

Also I found that when the hostname does not contain "." the `prompt_hostname` exit code is 1.
Sometimes this affects the following conditional checks.
E.g. `set -l _prefix (prompt_hostname)` is 1 (failed)

**Comment by faho** [comment]
>Since we already check SSH in prompt_login, does it make sense to output the hostname in fish_title as well?

Sure, added.
