### ISSUE TITLE
du command

### ISSUE THREAD

**Issue by bigbutch** [fish-shell/fish-shell#8779]
butch@butch-Bonobo-Extreme ~> du -sh ~/.cache/thumbnails
du: cannot access '/home/butch/.cache/thumbnails': No such file or directory

butch@butch-Bonobo-Extreme ~> rm -rf ~/.cache/thumbnails/*
fish: No matches for wildcard “~/.cache/thumbnails/*”. See `help expand`.
rm -rf ~/.cache/thumbnails/*
When I run these 2 commands in bash I have no problem. Is there another way I could run these 2 commands in Fish without problem?

**Comment by faho** [comment]
The reason your commands don't run is because the directories you're talking about don't exist.

You need to *create* them for the other two commands to make any sense. Can't measure or remove what isn't there.

>When I run these 2 commands in bash I have no problem.

I would be quite surprised if that's the case. The directory does not appear to exist, so bash would also not find it.

What does `echo ~/.cache/thumbnails` in both shells say?

----

In future, please fill out the issue template - we need:

1. Your fish version (`echo $version`)
2. Your operating system

**Comment by bigbutch** [comment]
Sorry I am kinda new at Ubuntu.
butch@butch-Bonobo-Extreme ~> echo $version
3.1.0
Ubuntu 20.04 is what I am running

**Comment by bigbutch** [comment]
I fish I ran butch@butch-Bonobo-Extreme ~> echo ~/.cache/thumbnails
/home/butch/.cache/thumbnails

In bash  this iss what I got butch@butch-Bonobo-Extreme:~$ echo ~/.cache/thumbnails
/home/butch/.cache/thumbnails

Thanks for your assistance. Sorry about confusion

**Comment by bigbutch** [comment]
Hello, I went to my home folder  and I do have a thumbnails folder there. Do you have any idea why fish wouldn't be finding it. It's  home/butch/.cache/thumbnails

**Comment by faho** [comment]
Okay, those are the same directories. That means the `du` will be failing in bash the same way.

The `rm` should fail in both bash and fish, but in different ways.

That is because fish will error when the glob (the `*` bit) doesn't match. See https://fishshell.com/docs/current/faq.html#my-command-prints-no-matches-for-wildcard-but-works-in-bash.

In this case, because the directory doesn't exist, that difference doesn't matter.

Like I said: You can't measure (`du`) or remove (`rm`) what isn't there.

Also:

>butch@butch-Bonobo-Extreme ~> echo $version
>3.1.0

That's a rather old fish version and has known bugs. Unfortunately the Ubuntu package is poorly maintained. You can go to https://fishshell.com/ to find a PPA to get an up-to-date version directly from us.

**Comment by bigbutch** [comment]
I installed 3.4.0 thanks alot faho.
