### ISSUE TITLE
File completions for `git restore --staged` are the same as `git restore`

### ISSUE THREAD

**Issue by ariasuni** [fish-shell/fish-shell#8843]
Fish 3.4.1

File completions for `git restore --staged` are the same as `git restore`, even though the first is used to unstage files, while the other is used to to discard changes in working directory. File completions for these two commands should be completely different; right now, they are useless for `git restore --staged`.

**Comment by faho** [comment]
Please confirm you are using the up-to-date git completions, this should already be handled:

https://github.com/fish-shell/fish-shell/blob/71a6f979a5efdbc2c5cc8f3674819439e95cda6a/share/completions/git.fish#L1781-L1782

(this should be using `__fish_contains_opt` so it can also support the `-S` short version, but `--staged` appears to already be handled)

**Comment by ariasuni** [comment]
Ah, I see: the problem is that fish doesn’t know about my Git aliases. Is there a way to tell fish that e.g. `git re` should be treated as `git restore`?

**Comment by faho** [comment]
If it's an actual formal git alias it should already work:

https://github.com/fish-shell/fish-shell/blob/71a6f979a5efdbc2c5cc8f3674819439e95cda6a/share/completions/git.fish#L623-L629

**Comment by ariasuni** [comment]
- I can confirm that my `git.fish` is up-to-date.
- The alias `re = restore` works (i.e. it completes modified files but not untracked files), but `res = restore --staged` doesn’t (completes the same as `git restore`)
- Weirdly, `git config -z --get-regexp 'alias\..*'` doesn’t give all my aliases (not `re` or `res`), but `git config --get-regexp 'alias'` does (probably unrelated, since completion for `re` is working).

**Comment by faho** [comment]
>The alias re = restore works (i.e. it completes modified files but not untracked files), but res = restore --staged doesn’t (completes the same as git restore)

Ah, that's it. See how that code checks the output of `commandline`? That's the actual current commandline.

Yours looks like `git re <something>`, which doesn't include `--staged`.

So we would have to expand the alias here.

>Weirdly, git config -z --get-regexp 'alias\..*' doesn’t give all my aliases (not re or res)

Note: With `-z`, this will print NULL-bytes. For unix reasons, that's the string terminator and it's very very easy to truncate strings with it (e.g. you *cannot* pass a string containing a NULL to a command - because that gets `char **argv`, and that's NULL-terminated).

We could special-case builtins, but we currently don't.

Really what you want to do with this is pass it to something like `string split0`:

```fish
set -l aliases (git config -z --get-regexp 'alias\..*' | string split0)
```

That will split on NULLs, and give your aliases correctly.

(we're not using it without `-z` because that uses newlines, and those are allowed in aliases - it's UNIX again)

**Comment by ariasuni** [comment]
Awesome, thanks!
