### ISSUE TITLE
Bind Shift+Space to Space by default

### ISSUE THREAD

**Issue by gpanders** [fish-shell/fish-shell#8874]
Fish version: 3.4.1
OS: macOS 12.3
Terminal: iTerm2

When using a terminal that supports the CSI u modifiers, Shift+Space is sent as `\x1b[32;2u`. This is the case for e.g. iTerm2. Unfortunately, Shift+Space is an *extremely* easy combination to mistype when one simply meant to insert a space. Consider the case when you're setting an environment variable:

```fish
set -U SOME_VAR foo
```

After typing `Shift+r` to enter `R` if I press Space while my finger is still holding shift, the sequence `\x1b[32;2u` is sent instead of a space. This happens quite often (for me, at least).

It is possible to tell fish to simply insert a space when this sequence is received:

```fish
bind \e\[32\;2u 'commandline -i " "'
```

I propose making the above binding a default as a convenience. I don't have any data for this assertion, but I would hazard a guess that most people would want Shift+Space to simply insert a space. Those who want to use that extra combination for something else can always map it themselves, though I'd bet that is a minority use case.

**Comment by krobelus** [comment]
> I don't have any data for this assertion, but I would hazard a guess that most people would want Shift+Space to simply insert a space.

I agree, because this makes it easier to type all caps.

So I think we definitely want that binding (I assume it doesn't collide with anything else).

What key sequence does Shift+Backspace send for you? This might have the same problem.

---

A related problem is that I get `\e\[27\;5\;13~` when I press Control+Return in the foot terminal.
I often trigger this accidentally after a Control+F that accepts an autosuggestion.
Should probably map that too by default, to match the behavior of traditional terminals.

**Comment by gpanders** [comment]
>What key sequence does Shift+Backspace send for you? 

`\e[127;2u`
