### ISSUE TITLE
Windows paths break on MSYS2/Fish

### ISSUE THREAD

**Issue by ajeetdsouza** [fish-shell/fish-shell#8883]
I'm using Fish 3.3.1 under MSYS2, installed via `pacman -Syu fish`. When I `cd` into a Windows path, such as `cd "C:\\"`, it throws the following error:

```
cd: The directory 'C:\' does not exist
```

However, `cd "C:\\"` works on bash, zsh, as well as dash. I even tested out `os.chdir("C:\\")` in Python and it worked. I'm not sure what's different around Fish's path validation logic here, but it seems to be what's breaking under MSYS.

Related: https://github.com/ajeetdsouza/zoxide/issues/375

**Comment by faho** [comment]
Please confirm the issue with fish 3.4.1, which had a total of 1115 commits since 3.3.1.

You'll also find our cd logic here isn't super complicated - we open the path and pass the fd to fchdir (https://github.com/fish-shell/fish-shell/blob/e3c4cde042ae7e5e8465b4b422d7deac29b41775/src/builtins/cd.cpp#L77-L79).

However, windows paths aren't something we're used to handle, this is ambiguous (is this a directory in the local $PWD called `C:\`? that's a perfectly allowable unix path!) and tbh the way forward on Windows is WSL, not msys.

So if someone figures this out and it's a simple fix that doesn't make anything else *worse*, sure, we'll take it.

**Comment by ajeetdsouza** [comment]
> Please confirm the issue with fish 3.4.1, which had a total of 1115 commits since 3.3.1.

I checked the source code, and this error should be reproducible on the latest release. I wasn't able to manually verify this, since there's no .EXE available on GitHub Releases, and the [website](https://fishshell.com/) only lists 1 installation method on MSYS2 (`pacman -S fish`), which currently has 3.3.1.

I found the culprit [here](https://github.com/fish-shell/fish-shell/blob/e3c4cde042ae7e5e8465b4b422d7deac29b41775/src/path.cpp#L182:17). This function is supposed to:

1. Return the directory if it is an absolute path
2. Normalize and return the directory if it is a relative path
3. Check CDPATH if it contains this directory

If no directory is found, it throws an error [here](https://github.com/fish-shell/fish-shell/blob/e3c4cde042ae7e5e8465b4b422d7deac29b41775/src/builtins/cd.cpp#L61). I think an extra condition needs to be added to end of this function that does a filesystem check to see if the directory exists. Ideally, this code would only run on Windows builds if possible.

**Comment by faho** [comment]
>I think an extra condition needs to be added to end of this function that does a filesystem check to see if the directory exists

"Look before you leap" is wrong. It introduces problems if something happens between the check and the actual usage.

It also won't help because:

>If no directory is found, it throws an error [here](https://github.com/fish-shell/fish-shell/blob/e3c4cde042ae7e5e8465b4b422d7deac29b41775/src/builtins/cd.cpp#L61).

That's not the error you're getting, because this doesn't ever check if a directory *exists*, it only applies $CDPATH. It's a string operation, not a file operation. (not sure that error is reachable anymore, tbh)

The error you are getting is [this one](https://github.com/fish-shell/fish-shell/blob/e3c4cde042ae7e5e8465b4b422d7deac29b41775/src/builtins/cd.cpp#L113-L115), when attempting to `cd` to all possible $CDPATH components has failed.

Because what happens is that `path_apply_cdpath` absolutizes the directory, and, like I said, assumes `C:\` refers to a directory called `C:\` inside one of the directories in $CDPATH.

So if you are in /tmp, it will attempt to cd to `/tmp/C:\`, which fails because that doesn't exist.

That's the ambiguity I complained about above. `C:\` is a perfectly allowable unix directory name.

>Ideally, this code would only run on Windows builds if possible.

Adding special code that only runs on minority platforms isn't a great idea and should be avoided if at all possible.

-----

The issue here is, fundamentally, that fish wants an absolute directory for $PWD, so it can do path computations on it. And `C:\` is an absolute path, but only on specific windows-y systems.

I don't know what exactly would be involved in fixing that, and tbh I'm not enthused about the idea of adding code here that isn't just specific to windows (which we do not natively support) but specific to some windows compatibility layers when WSL seems to be the way forward and doesn't have this problem (AFAIK - pretty sure they use `/mnt/c` instead of `C:\`).

**Comment by ajeetdsouza** [comment]
> That's not the error you're getting, because this doesn't ever check if a directory exists, it only applies $CDPATH. It's a string operation, not a file operation. (not sure that error is reachable anymore, tbh)

I'm actually a bit confused at the logic there, tbh. The `path_apply_cdpath` function returns a list of paths. Now, inside the function:

- If the path starts with `/`, we add it to the returned list.
- If the path starts with `./`, `../` or is equal to `.`, `..`, we normalize it and add it to the returned list.
- Otherwise, we loop through CDPATH, and for each element we add a path to the returned list.

For the purpose of simplicity, let's assume that my CDPATH is empty. Now if I `cd foo`, that doesn't match the first two conditions either. The returned list should be empty, and yet we throw an error if the returned list is empty. How is this function not throwing an error in this case? If some kind of normalization is happening beforehand, then why isn't it already an absolute path?

---

> Adding special code that only runs on minority platforms isn't a great idea and should be avoided if at all possible.

That's understandable, I'll close this issue then. Thanks!

**Comment by faho** [comment]
>let's assume that my CDPATH is empty

$CDPATH always implicitly contains ".": https://github.com/fish-shell/fish-shell/blob/e3c4cde042ae7e5e8465b4b422d7deac29b41775/src/path.cpp#L198-L199

So the returned list isn't empty, it contains $PWD/your/path.

That's why I said the error might not be reachable anymore.

**Comment by ajeetdsouza** [comment]
Makes sense. Thank you for clarifying!

**Comment by canton7** [comment]
> and tbh the way forward on Windows is WSL, not msys.

That's very much not true. Using WSL to interact with files in Windows-land is slow, and not recommended.

This is `time git status` in a large repo from WSL:

```
Executed in   34.14 secs    fish           external
   usr time    0.47 secs  267.00 micros    0.47 secs
   sys time   23.89 secs  296.00 micros   23.89 secs
```

And msys:

```
Executed in  246.88 millis    fish           external
   usr time   15.00 millis    0.00 micros   15.00 millis
   sys time   15.00 millis    0.00 micros   15.00 millis
```

Quarter of a second vs half a minute. Never mind that fact that if you interact a git repo from WSL and then switch to Windows (or vice versa), git needs to rebuild the index, which on WSL takes a good few minutes. 

WSL is great if you're staying within its world (a `git status` in the same repo cloned within WSL takes only 82ms). When you're working with files on a Windows filesystem but you just want some better command-line tools (and a better shell), msys is still very much the preferred option.

**Comment by faho** [comment]
From our perspective, WSL allows us to (mostly) pretend things are linux, while the other compatibility layers all require some awkward acrobatics to make some concessions to the windows heritage.

That's why, for us, the solution is indeed WSL. If that has performance problems, complain to Microsoft who can invest resources in getting them fixed.

Anyway, this isn't the place to discuss the relative merits of each. This is about a specific problem: We want an absolute path, and msys has more absolute paths, because it also allows windowsy "C:\" paths, and so we would have to fudge our path logic to handle that as well, and I don't think we're going to do that.

**Comment by miklcct** [comment]
> From our perspective, WSL allows us to (mostly) pretend things are linux, while the other compatibility layers all require some awkward acrobatics to make some concessions to the windows heritage.
> 
> That's why, for us, the solution is indeed WSL. If that has performance problems, complain to Microsoft who can invest resources in getting them fixed.
> 
> Anyway, this isn't the place to discuss the relative merits of each. This is about a specific problem: We want an absolute path, and msys has more absolute paths, because it also allows windowsy "C:" paths, and so we would have to fudge our path logic to handle that as well, and I don't think we're going to do that.

So don't you plan to natively support Windows as a first-class citizen (i.e. to use fish as a Windows shell, in place of cmd or PowerShell)?

**Comment by faho** [comment]
> So don't you plan to natively support Windows as a first-class citizen (i.e. to use fish as a Windows shell, in place of cmd or PowerShell)?

Correct. Fish natively on windows is not planned and has never been planned.
