### ISSUE TITLE
Incorrect PWD behaviour with symlinked home directory

### ISSUE THREAD

**Issue by sgorblex** [fish-shell/fish-shell#8888]
I have my home directory in the physical location `/blob/home/sgorblex` (where `/blob` is the mount point of my HDD), however it is set in `/etc/passwd` (and in `$HOME` too) to be the classic `/home/sgorblex`, since I have a symlink `/home` -> `/blob/home`.

I'm not sure why, but when I start the shell (at the opening of the terminal or with `env -i fish`) the prompt shows `/blob/home/sgorblex` as PWD, therefore not showing `~`. This is not the case if I run the `cd` command/builtin, which brings me to `/home/sgorblex`, correctly shown in the prompt as `~`.

Shouldn't the shell start on `$HOME` (`/home/sgorblex`), or at least recognise I'm in the home directory by showing `~`?

Using fish version 3.4.1 on Arch Linux (kernel 5.17.3).

**Comment by faho** [comment]
The only way fish can respect your logical $PWD via /home/sgorblex is if $PWD is passed as that - and it [does do that](https://github.com/fish-shell/fish-shell/blob/91760b0771d49e12fb5d29742da93ebb75c386bc/src/env.cpp#L387-L401). Otherwise it has no idea that you could possibly be using the other path - all it can do is `getcwd`, and that will give the resolved path. So this simply is not possible with `env -i`.

I'm guessing your terminal passes $PWD as the resolved, physical path, or doesn't pass $PWD at all.

Try going to /home/sgorblex and *then* start `env -i PWD=$PWD fish`, and it should resolve as home.

You will see the same behavior with bash.

**Comment by faho** [comment]
Question was answered, closing
