### ISSUE TITLE
Pressing the up key after Ctrl-C adds "^[[A" to the input, not previous command

### ISSUE THREAD

**Issue by Arro** [fish-shell/fish-shell#8893]
fish version: `3.4.1`
os: macOS `12.3.1`
terminal: Tabby `1.0.174`

When I'm Ctrl-C'ing a command, it doesn't allow me to cycle through previous commands.  When I press the up key after Ctrl-C, it adds "^[[A" to the input, not the previous command.  I've tried searching for this issue and was unable to find any results.

See screenshot:

<img width="842" alt="Screen Shot 2022-04-20 at 9 29 56 AM" src="https://user-images.githubusercontent.com/180387/164242088-34e32150-7032-4d20-ba25-363fd583a878.png">

**Comment by zanchey** [comment]
I haven't been able to reproduce this with `cat` (I don't have `npm` installed) on Tabby 1.0.176/macOS 12.3.1/fish 3.4.1-193-g91760b077.

**Comment by Arro** [comment]
I also have Hyper (version `3.2.3`) installed, and it also produces the same problem.  That's why I think it's a fish problem.

**Comment by Arro** [comment]
> `^[[A` is old-school notation for what fish would write as `\e\[A`. It's the default escape sequence for "up arrow".
> 
> The reason this would appear on the terminal is that either:
> 
> * The `echo` terminal mode is still enabled - this causes the _terminal_ to echo characters on its own. We disable that one pretty hard because it would interfere with autosuggestions and highlighting, so fish does its own echoing.
> * Another terminal is still running and reading from the terminal and echoing the characters.
> 
> Now, typically I'd suggest checking `stty`, but that's not really going to work because it would print the terminal modes for _external_ commands - fish resets them for itself, but keeps a (cleaned up) subset for external commands.
> 
> So, really, what I can suggest here is
> 
> 1. Try with a "known good" terminal like Terminal.app or iTerm
> 2. Try it with a different, simpler, program like `cat` instead of `npm`
> 3. Try it with a different shell like bash or zsh
> 4. Try it without configuration - note that we ask this in the issue template!

Thanks for this info. 


> If this only occurs with `npm`, chances are good it's an npm problem. If it only occurs in Hyper and Tabby, both of which are built on a similar web-technology stack, chances are it's an issue in e.g. [xterm.js](https://github.com/xtermjs/xterm.js), which both of them use to do the actual terminal emulation.

In the last few minutes, I've determined it 99% *is* npm related.  So I'll go ahead and close this.

**Comment by tagplus5** [comment]
I am using iTerm2 and I am seeing the same situation

**Comment by MaximeBernard** [comment]
Ok so all my team is able to reproduce the problem. It's not only `Ctrl+C` but `up arrow`, `down arrow`, `left arrow` and `right arrow`.

Prompt gets stuck in this until I hit `Enter` key. It's only stuck visually because if I press `up arrow + enter`, previous command is started.

> Try with a "known good" terminal like Terminal.app or iTerm

Tried both - same problem.

> Try it with a different, simpler, program like cat instead of npm

`cat` works fine. problem seems to appear only with `npm` or `yarn`.

> Try it with a different shell like bash or zsh

My boss only use `zsh` and has no problem... until he tried `fish` and reproduced the issue.

And here's the fun part. When he `zsh` inside `fish`, he had the problem as well.

> Try it without configuration - note that we ask this in the issue template!

```
fish, version 3.5.1
```
Did `sh -c 'env HOME=$(mktemp -d) fish'` and `yarn start`

<img width="478" alt="image" src="https://user-images.githubusercontent.com/2752221/191756814-8b315f81-c6be-4c4e-b84f-69676fb098f3.png">

**Comment by faho** [comment]
>Ok so all my team is able to reproduce the problem. It's not only Ctrl+C but up arrow, down arrow, left arrow and right arrow.

Are they all on macOS?

What exactly are you executing? `npm run dev`? I believe that relies on project configuration, do you have an opensource project that this reproduces with?

>fish, version 3.5.1

Can you try master? This smells like 5cf077820727656778e96abbc1f88955db41dbcc could be relevant.

>And here's the fun part. When he zsh inside fish, he had the problem as well.

Can you give the output of `stty -a` in zsh outside of fish and fish?

**Comment by MaximeBernard** [comment]
Yes, we're all on macOS.

--- 
I managed to make a simple repro: 
- Copy that inside a `package.json`.
```json
{
  "scripts": {
    "start": "concurrently \"echo a && cat\" \"echo b && cat\""
  },
  "dependencies": {
    "concurrently": "^7.4.0"
  }
}
```
- yarn install
- yarn start
- `Ctrl+c`
--- 
This seems to be linked directly to `concurrently` and `yarn`. I found https://github.com/open-cli-tools/concurrently/issues/283 if it helps.

> Can you give the output of stty -a in zsh outside of fish and fish?

(my fish)
```
speed 38400 baud; 70 rows; 165 columns;
lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
	-extproc
iflags: -istrip icrnl -inlcr -igncr -ixon -ixoff ixany imaxbel iutf8
	-ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
	min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
	stop = ^S; susp = ^Z; time = 0; werase = ^W;
```

(my boss zsh)
```
speed 38400 baud; 98 rows; 242 columns;
lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
	-extproc
iflags: -istrip icrnl -inlcr -igncr ixon -ixoff ixany imaxbel iutf8
	-ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
	min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
	stop = ^S; susp = ^Z; time = 0; werase = ^W;
```

**Comment by faho** [comment]
Okay, got it:

When you run this, the process tree looks like:

```
fish(27943,27943)───node(29680,29680)─┬─node(29691,29680)─┬─cat(29698,29680)
                                      │                   ├─cat(29699,29680)
```

(the first number is the pid, the second is the process group id or pgid)

Now, when you `strace` the fish process and the two nodes from another terminal with something like `strace -p 27943 -p 29680 -p 29691 -e ioctl` (that last part limits it to the `ioctl` syscall which is what I'm interested in on linux), and then ctrl-c it, you get this (lightly edited for readability):

```
[pid 29680] --- SIGINT {si_signo=SIGINT, si_code=SI_USER, si_pid=29680, si_uid=1000} ---
[pid 29680] +++ killed by SIGINT +++
[pid 27943] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=29680, si_uid=1000, si_status=SIGINT, si_utime=26 /* 0.26 s */, si_stime=5 /* 0.05 s */} ---
[pid 27943] ioctl(0, TIOCSPGRP, [27943]) = 0
[pid 27943] ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 27943] ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig -icanon -echo ...}) = 0
[pid 27943] ioctl(1, TIOCGWINSZ, {ws_row=32, ws_col=162, ws_xpixel=1463, ws_ypixel=592}) = 0
[pid 27943] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=29838, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
[pid 29691] ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
[pid 29691] ioctl(1, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
[pid 29691] ioctl(2, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
[pid 29691] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=29834, si_uid=1000, si_status=1, si_utime=0, si_stime=0} ---
[pid 29691] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=29839, si_uid=1000, si_status=128, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=29840, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
```

To explain, what happens is:

- The upper node gets the signal (SIGINT) and dies
- Fish (pid 27943) is notified that its child died (SIGCHLD)
- It reacts by:
  - Checking the terminal's controlling group (which is still fish's)
  - Checking the terminal's modes (they include "echo")
  - Setting the terminal's modes again to turn "echo" off
  - Querying window size
- Then, the lower node (pid 29691):
  - Resets all the terminal modes on all its standard file descriptors, including "echo" again
  - Exits

Because the lower node isn't fish's direct child, fish doesn't get a notification that it died (those other three SIGCHLDs don't map to any of the node or cat processes, I have no idea where they are coming from).

So node politely screws the terminal back up after fish reconfigured it. From our perspective it could just not have done anything and things would have worked.

Or, alternatively, it should go all the way and properly clean up - stop its children and wait for them to exit, then it can clean up and exit. That way we would get a proper SIGCHLD at the proper time and could do our own cleanup.

I do not believe there is anything we *can* do here, so from my perspective this is https://github.com/nodejs/node/issues/41143.

**Comment by faho** [comment]
Oh, and to be clear: I get the exact same results in bash and an unconfigured zsh.

I'll leave this open for a bit to see if anyone has any clever ideas, but I'm assuming it's not fixable on our end.

**Comment by MaximeBernard** [comment]
Ok so here are my findings:

- you don't have any issue in zsh as long as your terminal is started by it (term -> `zsh` -> `yarn` -> `concurrently`) (but you do have the issue if you term -> `fish` -> `zsh` -> `yarn` -> `concurrently`)
- you don't have any issue if you use `npm` instead `yarn` so my guess is `npm` is cleaning up the mess `concurrently` is doing but `yarn` does not. (probably https://github.com/yarnpkg/yarn/issues/4667) 

Would it be possible (maybe unwanted) for fish to list all the pid tree (I'm thinking `pstree`), and before cleaning, waiting for all children to be killed?

I'm fine if you don't want to handle this because this is not your fault.

**Comment by faho** [comment]
>you don't have any issue in zsh as long as your terminal is started by it (term -> zsh -> yarn -> concurrently) (but you do have the issue if you term -> fish -> zsh -> yarn -> concurrently)

I reproduced it in a terminal that immediately started zsh.

>Would it be possible (maybe unwanted) for fish to list all the pid tree (I'm thinking pstree), and before cleaning, waiting for all children to be killed?

It isn't. What if the child is a daemon?

We have no way of knowing if the child is supposed to die at all.

**Comment by spenceryue** [comment]
In my case, I had a node.js script that spawned a child process with `spawn()`.

```js
const { spawn } = require('child_process');
const { readFileSync, rmSync, writeFileSync } = require('fs');
const { resolve } = require('path');

function main() {
  // some setup code to write an `.env.production.local` file before starting next.js.
  // writefileSync(OUTPUT, "...");

  spawn('yarn', process.argv.slice(1), { stdio: 'inherit' })
    .on('exit', cleanup)
     // Exit codes that would be set by node.js by default if no handler existed (according to Node.js docs).
    .on('SIGINT', cleanup.bind(null, 128 + 2))
    .on('SIGTERM', cleanup.bind(null, 128 + 2));

  // No-op handlers to prevent exit before child exits. 👈 This fixed things.
  process.on('SIGINT', () => {});
  process.on('SIGTERM', () => {});
}

function cleanup(code) {
  rmSync(OUTPUT);

  process.exit(code);
}

const OUTPUT = "...";

main();
```

I fixed the problem by making sure the child process exits before the parent.
