### ISSUE TITLE
`adduser` completions barf in the terminal

### ISSUE THREAD

**Issue by ammgws** [fish-shell/fish-shell#8896]
I think https://github.com/fish-shell/fish-shell/pull/8479 forgot to use the  `--quiet` flag. 

```sh
>adduser --no-create-home --disabled-password --disabled-login newuse/usr/share/fish/completions/adduser.fish (line 18): No matches for wildcard ''(string match --regex '^[^#].*' < /etc/shells)''. See `help wildcards-globbing`.
complete -c adduser -l shell -d 'Use shell as the user\'s login shell, rather than the default' -x -a '(string match --regex '^[^#].*' < /etc/shells)'
                                                                                                      ^
from sourcing file /usr/share/fish/completions/adduser.fish
in command substitution
```

Env:
```
>fish --version
fish, version 3.4.1
>uname -a
Linux proxmoxserver 5.13.19-6-pve #1 SMP PVE 5.13.19-15 (Tue, 29 Mar 2022 15:59:50 +0200) x86_64 GNU/Linux
```

**Comment by faho** [comment]
>I think https://github.com/fish-shell/fish-shell/pull/8479 forgot to use the --quiet flag.

No, worse - this quoting is broken.

**Comment by ammgws** [comment]
Yeah just noticed it was actually trying to glob!

**Comment by faho** [comment]
Okay, I now added a test that sources all completion scripts that we have commands for and checks if that produces any output.

This is of course imperfect, because it doesn't *run* the completions and it can't check completions that don't have the commands installed (we only autoload completion files if the command exists, and the completions only make sense if it does).

We already check the syntax for all our fish files so actual syntax errors are already caught.

I also found two additional completions that spew errors: [dpkg-reconfigure](https://github.com/fish-shell/fish-shell/commit/e358ec0ce23ae6bcd33625bc79549ef1c963a816) and [rustc](https://github.com/fish-shell/fish-shell/commit/10785ba814192bba4783f4da913593eeeaf29027)
