### ISSUE TITLE
Should expanding wildcard on TAB depends on file or completion?

### ISSUE THREAD

**Issue by NextAlone** [fish-shell/fish-shell#8910]
Version: fish, version 3.4.1-215-g71ff8780c

Noticed that new function that expands wildcard on TAB, when using like `git restore` command, i think that when typing TAB, `git restore foo/bar*` will expand depending on which that can be restore, but not the files that exist in `foo/bar*`

**Comment by krobelus** [comment]
Interesting idea.

The current behavior is that `git restore foo/bar*`+Tab+Return has the same effect as `git restore foo/bar*`+Return (without the Tab).
IOW, Tab merely performs file globbing, just like evaluation would do.
That's a sensible and predictable behavior.

I can see that users expect it to use completions.
I guess we could try to make globs match against custom completions (and fall back to the file system).
Doesn't sound trivial. One question is how to compute custom completions, do we remove * from the token from the commandline when doing so? Or perhaps remove the entire token (in this case `foo/bar*`), because completion lists all nested paths anyway

**Comment by NextAlone** [comment]
That another point. Now wildcard only match files, and if there is need to change it to match completions if available, not only on <TAB> but all the time.

**Comment by mqudsi** [comment]
I think expansion of wildcards should be purely a core shell concern and should not involve completions. It becomes too difficult to reason about if you bring completions into the picture and also has an inversion of dependencies where expansion isn't just a matter for the parser but also depends on execution too.

**Comment by NextAlone** [comment]
ok, got that
