### ISSUE TITLE
No way to add newlines in funced without $EDITOR

### ISSUE THREAD

**Issue by stephenvisser** [fish-shell/fish-shell#893]
When creating a function from the command line, newlines perform as expected: the enter key will always create a newline at the current cursor position.

After saving and `funced`ing, though, there is no way to add a new line. I would expect the enter key to always create a new line unless the cursor is on the `end` (last) line, in which case it is safe to assume the user has completed the editing.

**Comment by krader1961** [comment]
It's not clear what the original problem was. The `funced` command puts you in your editor where you can easily add new lines. Upon exiting the editor the revised function is loaded. Closing since things seem to work just fine today.

**Comment by Vadskye** [comment]
The original problem involved the *built-in* editor that fish provides for `funced` if you have not configured a custom editor. I still see the same behavior. Using alt-enter works (thanks siteshwar!), but that isn't documented anywhere I can find. I agree with the behavior proposed by stephenvisser - or, failing that, to document the behavior of alt-enter in `funced --help`.

**Comment by faho** [comment]
@Vadskye: Thanks for the explanation.

IIUC, this is actually reusing our commandline-editor via `read`, in which enter is bound to the "execute" bind function.

We might want to change that so that it only executes when the cursor is at the end. Either in general, or only within `read`.

Either way, this should be revisited.

**Comment by krader1961** [comment]
Try doing `funced -i funced` and pressing up arrow to move to a line before whatever is the first one on your screen. Now press [ctrl-C] and repeat the funced only this time press [down-arrow] twice and observe that pressing [up-arrow] no longer works. Granted, both behaviors are bugs that should be fixed. I'm impressed it works as well as it does. But it's going to be a long time before the builtin editor is an adequate replacement for a real editor like vim or emacs.

But since we're not likely to remove this feature I agree we should document that [alt][enter] self inserts a newline. We should not complicate the implementation by making [enter] behave differently depending on where it is located in the text being edited. That would be confusing, not backward compatible, and mean that inserting a newline at the end of the function is the only place that would still require [alt][enter].

**Comment by Vadskye** [comment]
Haha, point taken. I'm happy with just documentation for the behavior, then - and I'll just finally figure out how to persistently set environment variables with `fish` so I can use my normal $EDITOR.

**Comment by krader1961** [comment]
> I'll just finally figure out how to persistently set environment variables with fish so I can use my normal $EDITOR.

This is normally done by setting the relevant environment variables in your *~/.config/fish/config.fish* or a script that it sources. For example, I set such variables in *~/.config/fish/environ.fish* which I then source from *~/.config/fish/config.fish*:

```
    if test -f $HOME/.config/fish/environ.fish
        source $HOME/.config/fish/environ.fish
    end
```

The actual code is somewhat more complex than that but only due to my particular requirements. Most people will be just fine adding something like

```
set -x EDITOR (type -p vim)
```

to their *~/.config/fish/config.fish* file.

**Comment by Vadskye** [comment]
Ah, sorry, that wasn't meant as a request for information - I figured I would just look at the documentation. But thank you! That's very helpful.

**Comment by gruber** [comment]
Newbie fish user here. FWIW, on a Mac running 10.12.4 and the latest fish from Homebrew, Alt-Return does the same thing as Return: it ends editing rather than insert a newline. I'd rather have no-modifer Return insert a newline unless at the trailing end, but I'd be satisfied with Alt-Return if actually worked for me. Any ideas why it doesn't?

**Comment by krader1961** [comment]
@gruber: Run `fish_key_reader` then press [alt-enter]. What does it report? It should output this:

```
              hex:   1B  char: \c[  (or \e)
(  0.366 ms)  hex:    D  char: \cM  (or \r)
bind \e\r 'do something'
```

If it doesn't then you haven't properly configured your terminal to treat the [alt] key as meta (i.e., prefix the next key with an escape character). It's also possible you have customized your key bindings. Typing `bind \e\r` should report `bind \e\r commandline\ -i\ \\n` in both default (emacs) and vi key binding modes.

**Comment by gruber** [comment]
"If it doesn't then you haven't properly configured your terminal to treat the [alt] key as meta" -- bingo, that was it. Turning that on in Terminal.app's prefs fixed it for me. Thanks!
