### ISSUE TITLE
There must be something wrong in man completion

### ISSUE THREAD

**Issue by NextAlone** [fish-shell/fish-shell#8930]
![image](https://user-images.githubusercontent.com/12210746/166802550-0038d66a-5936-4c61-8241-e314a50d2fc9.png)

The manpage exists, but __fish_completion_man didn't complete it.

**Comment by faho** [comment]
Is this on macOS? We've had issues with macOS' apropos before, which is why [__fish_apropos](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_apropos.fish) exists.

This will create the whatis database in the background, which will take a while.

Before that's done, we can only complete our own man pages, which is what's happening here. Unfortunately the root cause is that macOS has broken its own apropos (and then it was fixed and then it was re-broken in a point release), and there appears to be nothing more we can do here.

If you're not on macOS you might want to check that you have `apropos` installed.

**Comment by NextAlone** [comment]
> Is this on macOS? We've had issues with macOS' apropos before, which is why [__fish_apropos](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_apropos.fish) exists.
> 
> This will create the whatis database in the background, which will take a while.
> 
> Before that's done, we can only complete our own man pages, which is what's happening here. Unfortunately the root cause is that macOS has broken its own apropos (and then it was fixed and then it was re-broken in a point release), and there appears to be nothing more we can do here.
> 
> If you're not on macOS you might want to check that you have `apropos` installed.

Arch Linux，with aprops installed

**Comment by faho** [comment]
This would have been great to know immediately, which is why the issue template asks for it.

Anyway: Is apropos in $PATH? `type apropos`

Is $MANPATH set to anything? `set --show MANPATH`

Is it just the plocate man page or all of them?

Which `man` implementation are you using? Stock mandb or mandoc?

**Comment by faho** [comment]
Ah, I know what this is.

Run `mandb` as root to regenerate your database.

**Comment by NextAlone** [comment]
Thanks for your work, i will close this.
