### ISSUE TITLE
fish: Unknown command fish_add_path

### ISSUE THREAD

**Issue by osilkin98** [fish-shell/fish-shell#8939]
In this instance, fish is being used on a Raspberry Pi model 3B+.
Environment Details:
```sh
pi@raspberrypi ~/Downloads> fish --version
fish, version 3.0.2
pi@raspberrypi ~/Downloads> uname -a
Linux raspberrypi 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l GNU/Linux
pi@raspberrypi ~/Downloads> echo $TERM
xterm-256color
```

When attempting to add a new value to my path, I ran `fish_add_path` only to receive an error that the command is unknown:
```shell
pi@raspberrypi ~/Downloads> fish_add_path 
fish: Unknown command fish_add_path
```

What should I do to work around this?

**Comment by faho** [comment]
`fish_add_path` was added in fish 3.2.0, released in march 2021.

You want to upgrade fish, try the PPA linked at https://fishshell.com/

**Comment by osilkin98** [comment]
I've tried downloading [fish_add_path](https://raw.githubusercontent.com/fish-shell/fish-shell/91760b0771d49e12fb5d29742da93ebb75c386bc/share/functions/fish_add_path.fish) and saving it as `/etc/fish/functions/fish_add_path.fish`, however it still does not seem to be working. 

Strangely, `fish_add_path` appears under the `functions` within the UI for `fish_config`. The very first line states that the function is defined in the saved location, however it does not appear to be usable.

![image](https://user-images.githubusercontent.com/16809287/167267539-881180f0-dd68-497d-b81d-d57290f4738b.png)

**Comment by faho** [comment]
Fish 3.0.2 is no longer supported. Upgrade fish.

Here's how many % of commits (to master) each release since 3.0.0 contains and when it was released:

| Release | Commits% | Releasedate | 
 | ---- | ---- | ---- |
| 3.0.0 | 58.88% | 2018-12-28 |
| 3.0.1 | 59.31% | 2019-02-11 |
| 3.0.2 | 59.33% | 2019-02-19 |
| 3.1.0 | 73.52% | 2020-02-12 |
| 3.2.0 | 88.08% | 2021-03-01 |
| 3.3.0 | 91.45% | 2021-06-28 |
| 3.4.0 | 98.7% | 2022-03-12 |

So fish 3.0.2 is missing 40% of all commits ever made to fish. We will no longer support it, because it's so different from an up-to-date fish that it isn't worth our time.

**Comment by osilkin98** [comment]
@faho This seems to be an issue with Raspbian, while it appears to have version `3.4.1` for armhf, the most recent release under buster is Fish 3.0.2.

**Comment by krobelus** [comment]
> ```sh
> ***@***.*** ~/Downloads> fish --version
> fish, version 3.0.2
> ***@***.*** ~/Downloads> fish_add_path 
> fish: Unknown command fish_add_path
> ```

you'd need to upgrade, fish_add_path was introduced two releases ago in 3.2.0
