### ISSUE TITLE
fish version is dropped in build when using make as root

### ISSUE THREAD

**Issue by danielb2** [fish-shell/fish-shell#8973]
git master points to 3.4.1

git version 2.36.0

reproducible on:
- MacOS Mojave (10.4.3)
- Alpine Linux 3.16.0

```
daniel@zoro /U/d/t/fish-shell (master)> make
cmake --build build
[0/2] Re-checking globbed directories...
[1/6] cd /Users/daniel/tmp/fish-shell && /User...sion_gen.sh /Users/daniel/tmp/fish-shell/build
FISH_BUILD_VERSION=3.4.1-271-gec6fd088f
[6/6] Linking CXX executable fish

daniel@zoro /U/d/t/fish-shell (master)> ./build/fish --version
fish, version 3.4.1-271-gec6fd088f

daniel@zoro /U/d/t/fish-shell (master)> sudo make
cmake --build build
[0/2] Re-checking globbed directories...
[1/6] cd /Users/daniel/tmp/fish-shell && /User...sion_gen.sh /Users/daniel/tmp/fish-shell/build
FISH_BUILD_VERSION=unknown
[6/6] Linking CXX executable fish

daniel@zoro /U/d/t/fish-shell (master)> ./build/fish --version
fish, version unknown
```

some debugging:

```
daniel@luffy /h/d/t/fish-shell (master)> ./build_tools//git_version_gen.sh
FISH_BUILD_VERSION=3.4.1-271-gec6fd088f

daniel@luffy /h/d/t/fish-shell (master)> sudo ./build_tools//git_version_gen.sh
FISH_BUILD_VERSION=unknown
```

further debugging:

```
daniel@luffy /h/d/t/fish-shell (master)> git -C . describe --always --dirty
3.4.1-271-gec6fd088f

daniel@luffy /h/d/t/fish-shell (master)> sudo git -C . describe --always --dirty
fatal: unsafe repository ('/home/daniel/tmp/fish-shell' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /home/daniel/tmp/fish-shell
```

Looks like git has changed some behavior since the script was written

The reason this is an issue is that when `make install` is run, the linking is done again, and the version is dropped. Perhaps if it didn't relink it wouldn't be an issue.

**Comment by faho** [comment]
Okay. What happens here is that git had a CVE related to arbitrary code being run when you run `git status` and similar, and instead of doing something about those arbitrary code bits they decided to lock it down entirely.

So now `git` will refuse to do basically anything once it detects the .git directory is owned by someone else.

Unfortunately, I don't know of any way around that - we need to run `git describe` here to get the git version, and that *should be* a safe command but the git people decided against distinguishing between safe and unsafe commands. If we could just tell `git describe` to simply compute the fudging git version and not run any arbitrary code, we would. But as it stands, any single `git` command will just refuse to work here.

Fortunately, the command tells you what you can do as a workaround:

>        git config --global --add safe.directory /home/daniel/tmp/fish-shell

This will mark /home/daniel/tmp/fish-shell as "safe" and restore the previous git behavior for it. You'll need to run it as root.

**Comment by faho** [comment]
Okay, I added a horrible horrible hack and @zanchey will hate me for it.

If `git describe` fails with a 128 status (meaning the permission failed), we simply keep a pre-existing version file. This basically makes the normal `cmake; make; sudo make install` run work and nothing else, but that's 99% of what people need.

**Comment by krobelus** [comment]
I think we can avoid the hack by running `git -c safe.directory="$FISH_BASE_DIR" describe`

**Comment by faho** [comment]
>I think we can avoid the hack by running git -c safe.directory="$FISH_BASE_DIR" describe

Nope, safe.directory isn't accepted on the commandline. Try

```fish
sudo git -c safe.directory=$PWD describe
```

it won't work. I think it *could* be accepted on the commandline, mainly it can't ever be accepted in the local in-repo config file, but as it stands it isn't.

**Comment by zanchey** [comment]
That's probably as good as it's going to get.
