### ISSUE TITLE
Add flag to `path extension` to not return the `.`

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#8992]
I'm in the process of migrating my personal fish scripts over to use the new `path` builtin (awesome work @faho!) and I've come to a piece of code along the following lines:

```fish
set extension (string replace -r -- '.+\.(.+)$' '$1' $filename)
switch $extension
    case sh bash zsh fish
        # do something
    case '*'
        # do something else
end
```

It would be neat if `path extension` had a flag to strip the leading `.` so I don't have to specify it for every extension (`.bash .zsh .fish .txt`) in my `case` statement.

---

⚠️ Unrelated bonus issue which I don't think is important enough to justify a separate ticket: `help path` takes me to `/share/doc/fish/tutorial.html#path` which is docs for the `$PATH` variable, not the new `path` builtin:

```
$ path
path: missing subcommand

(Type 'help path' for related documentation)
```

**Comment by faho** [comment]
Originally, path's extension handling didn't include the dot, because that was supposed to be implied.

However, that makes the extension on "foo." (the empty extension) and "foo" (no extension at all) indistinguishable, so you could no longer always reconstruct the filename.

So I switched it and now you can do

```fish
set -l ext (path extension $file)
set -l name (path change-extension '' $file)
echo $file$ext
```

and it will reconstruct the filename.

I don't believe not including the dot is important enough that it deserves an option - you can always do a `string replace` yourself. It also barely saves any typing:

```fish
case .sh .bash .zsh .fish
```

has four extensions, so four dots, while `path extension -n $filename`, with a `-n` short option to remove the dot, has two additional characters. That's saving a whopping two characters.

If you had even more extensions, you could use

```fish
case .{sh,bash,zsh,fish}
```

which adds 3 characters - only one char more than the `-n` short option, *and* that's constant and a normal thing you can use elsewhere, not a special option that only applies to `path extension`.

If you had a massive list of extensions, e.g. stored in a file, you could store them in a variable and prepend the dot:

```fish
set -l exts .(cat my-extension-file)
switch $extension
    case $exts
```

(or use `.$exts` instead of adding it where you set the variable)

So: This is a very minor character-saver. I simply do not believe it is useful enough to be added, so I am rejecting this. Sorry!

----

>`help path` takes me to /share/doc/fish/tutorial.html#path which is docs for the $PATH variable, not the new path builtin

This was fixed in 9361325137f77b8fa51dc32b56d37378304ec49a, I neglected to link it.
