### ISSUE TITLE
Add git root path completions

### ISSUE THREAD

**Issue by Undeterminant** [fish-shell/fish-shell#901]
On all git commands, you can specify a path that starts with `:/` to operate on the root of the current repo. It would make sense for fish to complete these paths.

**Comment by faho** [comment]
How does one get the root of the current repo?

**Comment by zanchey** [comment]
`git rev-parse --show-toplevel`

**Comment by faho** [comment]
This is actually rather hard, especially since it would have to be integrated with the various kinds of completions - modified files and staged files need to be handled differently (`git ls-files` only prints files in the current directory and subdirectories, `git diff --name-only` prints paths relative to toplevel).

I'm working on it - I don't think I'll add it for _every_ command, though.
