### ISSUE TITLE
Failure in checks/fds.fish

### ISSUE THREAD

**Issue by simon28li** [fish-shell/fish-shell#9017]
Hi,when I ran the test in version 3.1.2, there was an error similar to [#7304](https://github.com/fish-shell/fish-shell/issues/7304). Have you solved this problem? I tested the latest version and still reported the same error.

```
Testing file checks/fds.fish ... Failure in checks/fds.fish:

  The CHECK on line 6 wants:
    0 1 2

  which failed to match line stdout:1:
    0 1 2 3 4

  when running command:
    ../test/root/bin/fish -C "set helper ../test/root/bin/fish_test_helper" checks/fds.fish
```

Here is some necessary information.
```
# fish --version
# fish, version 3.1.2
# uname -a
# Linux localhost 4.18.0-193.el8.aarch64 #1 SMP Fri May 8 11:05:12 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
# echo $TERM
# xterm

```

**Comment by faho** [comment]
>Hi,when I ran the test in version 3.1.2, there was an error similar to https://github.com/fish-shell/fish-shell/issues/7304.

Yes, we have, that is why that issue is closed.

> I tested the latest version and still reported the same error.

Most likely you're not.

Open up checks/fds.fish in a text editor and put in

```fish
echo $version
```

Then rerun the tests again. This should be printing something like "3.4.1", and the test won't be able to match it so it will think it is an error.

> fish, version 3.1.2

3.1.2 is years out of date. It is missing over 25% of all commits ever made to fish and it is entirely out of support. Even if your operating system thinks it isn't, it is.

**Comment by faho** [comment]
Okay, I can reproduce this if I start bash, run

```sh
exec 3<>/tmp/three
exec 4<>/tmp/four
```

and then run the tests *manually*, via `test/root/bin/fish -C "set helper test/root/bin/fish_test_helper" ../tests/checks/fds.fish`.

That failing is *fine*, because it already skips a bunch of otherwise necessary setup. It's not something we can support.

The real way to run the tests is to build fish with cmake, and then run `ninja test` or `make test` or similar. That works.

So: The error seems to be in your setup, not fish.

**Comment by simon28li** [comment]
> I can reproduce this if I start bash, run
> 
> ```shell
> exec 3<>/tmp/three
> exec 4<>/tmp/four
> ```
> 
> and then run the tests _manually_, via `test/root/bin/fish -C "set helper test/root/bin/fish_test_helper" ../tests/checks/fds.fish`.
> 
> That failing is _fine_, because it already skips a bunch of otherwise necessary setup. It's not something we can support.
> 
> The real way to run the tests is to build fish with cmake, and then run `ninja test` or `make test` or similar. That works.
> 
> So: The error seems to be in your setup, not fish.

In fact, I built using cmake and then executed the make test, which is consistent with the result of executing the command alone. In addition, this problem should really be the problem of the environment, because some of my machines do not appear. I will check them carefully.Thanks a lot.

**Comment by faho** [comment]
Okay, I've now added a specific error to the test that tells you to close the fds. I'm suspecting that your cmake version is older than mine (because your kernel also is, uh, quite a bit older) and that newer cmakes close superfluous fds, which would explain why `ninja test` won't reproduce for me.
