### ISSUE TITLE
Fish crashes at start on Haiku

### ISSUE THREAD

**Issue by extrowerk** [fish-shell/fish-shell#9067]
Fish: https://github.com/fish-shell/fish-shell/releases/download/3.5.0/fish-3.5.0.tar.xz
OS: Haiku x86-64 hrev56272
Terminal: Haiku's terminal

Fish built like:
```
cmake . \
	-DCMAKE_CXX_FLAGS="-DB_USE_POSITIVE_POSIX_ERRORS" \
	-DCMAKE_EXE_LINKER_FLAGS="-lposix_error_mapper" \
	-DCMAKE_INSTALL_PREFIX=/Ports/Inst/fish \
	-DCMAKE_BUILD_TYPE=Debug
```

The positive_error_mapper stuff is there only because Haiku uses negative error codes in default.
I have tested Fish without it, no difference.
I have also tested without debug enabled, no difference.

Starting Fish results:
```
/Ports/Inst/fish/bin> sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
fish: /Ports/Testring/fish-3.5.0/src/proc.h:93:static proc_status_t proc_status_t::from_exit_code(int): ret < 256
Kill Thread
```

Link: https://github.com/fish-shell/fish-shell/blob/3.5.0/src/proc.h#L93

Haiku just got a locale.h support, which makes Fish on Haiku realistic again, but as the locale code not mature yet it can contain some bugs. Also bugs can lurk in other part of the system too.

**Comment by faho** [comment]
Something, somewhere, sets a status of >= 256.

A backtrace is going to make this a lot easier. Realistically, looking at the uses of proc_status_t::from_exit_code(), we have:

- Uses with our own STATUS_CMD_ERROR and friends, which we define ourselves as < 256
- Uses with literals like "1"
- Uses with the last status value - which should already be checked
- Uses with EXIT_FAILURE, which is implementation-defined

So the most likely issue is that you've defined EXIT_FAILURE to be >= 256, or we have some number type fuckery (over/underflow).

We should stop using EXIT_FAILURE and EXIT_SUCCESS because they're implementation-defined anyway, because we want these values to be the same everywhere. Try patching them to be STATUS_CMD_ERROR and STATUS_CMD_OK, respectively.

**Comment by floam** [comment]
They seem to have pedestrian values: 0 and 1. https://github.com/haiku/haiku/blob/573b7b1f213152b795015e9658ee8144e414485a/headers/posix/stdlib.h

Some -debug output or a stack trace would be really nice. There might be some idiosyncrasy with the kinds of signal numbers, status we're getting from the OS. I don't know.

**Comment by floam** [comment]
I suspect it's happening in `proc_status_t::from_exit_code(exit_code_from_exec_error(err))` where we care about exec() or posix_spawn() return codes.

**Comment by floam** [comment]
All I've got is that the "Kill Thread" output is probably from `strsignal()`, SIGKILLTHR 21.

**Comment by floam** [comment]
@extrowerk can you please provide some more information?

**Comment by faho** [comment]
What I'd like is at the very least a backtrace - we know *a* call for proc_status_t::from_exit_code(int) gets an int >= 256, but we don't know *which*. It might be enough to figure out how it gets that.

Or it breaks by calling it with one of our bit-fiddled status_t values with the signal stuff shoved in there, in which case we'd probably have to figure out how the signal bits work here. A link to Haiku's waitpid(2) might be useful.

Alternatively, I'd like a link to a Haiku version that has the locale stuff or some directions as to how to get them working - I downloaded an image from https://www.haiku-os.org/get-haiku/r1beta3/ and ran that in a VM and it fails at building because of missing locale_t.

**Comment by extrowerk** [comment]
I am on vacation right now, will provide more info after i return. Thank you.

**Comment by extrowerk** [comment]
> Alternatively, I'd like a link to a Haiku version that has the locale stuff

Any recent nightly contains it:
https://download.haiku-os.org/nightly-images/x86_64/

**Comment by floam** [comment]
It seems like some basic stuff like tossing away the first 8 bits doesn't work the same here for the status, or we've got some preprocessor crap messing this all up.

**Comment by extrowerk** [comment]
> It seems like some basic stuff like tossing away the first 8 bits doesn't work the same here for the status and signal (or values can be a different type?), else we've got some crap included messing this all up through the preprocessor.

I dont understand what you wrote, but if you have any question about Haiku feel free to ask me. Only try to not forget: Haiku is not *nix, if something different, there is a reason for that, and if you cant write in a directory you should read the faq and the user guide and accept the fact the system folders arent writeable. Not even with sudo.

**Comment by faho** [comment]
>if you cant write in a directory you should read the faq and the user guide and accept the fact the system folders arent writeable

Nobody is trying to write to a system folder here.

>Haiku is not *nix

Yes, but we are trying to treat it like a *nix, the only way fish is going to run on Haiku is via the posix compatibility layer.

And that's where the issue appears to be. Our working theory is that Haiku encodes exit statuses (i.e. the numeric return code that you'd get via $status or $? plus whether it received any signals) differently, and something will have to adapt here.

To explain: `waitpid()` gives us a value that explains how and why a process exited - it encodes the numeric status and the signal (if any) in one integer, and that can then be decoded with macros like "WIFEXITED" and "WEXITSTATUS". Because that's a nifty encoding, we internally store our process exit information the same way. (which might be overkill, but that's how it is)

Only Haiku's encoding here might be different, which results in larger values than we expect. It's possible the fix is as simple as removing the assert (wouldn't be the first time), but that requires confirming that everything works and doesn't break catastrophically because we suddenly assume a process exited with status 25435 because it received signal 5353 - i.e. we produce garbage data.

**Comment by faho** [comment]
Alright I found part of the problem.

Haiku's WEXITSTATUS (a macro that extracts just the numeric return code from a wait status value), [looks like](https://github.com/haiku/haiku/blob/8f16317a5b6db5c672f331814273e5857555020f/headers/posix/sys/wait.h):

```
#define WEXITSTATUS(value)	((value) & 0xff)
```

while [glibc's](https://github.com/bminor/glibc/blob/master/bits/waitstatus.h) looks like

```
#define	__WEXITSTATUS(status)	(((status) & 0xff00) >> 8)
```

These differ, in that the Haiku version uses the lower byte, the glibc version uses the second-lowest byte. They're turned around!

Now, we wouldn't typically care about this, except that

1. We want to construct such a value ourselves
2. We can't ask Haiku to do it for us because it doesn't have the W_EXITCODE macro (that turns a return code and a signal value into a wait status)

Now, we already do have a path for constructing the code ourselves without W_EXITCODE, used by musl, but that uses the same format as glibc:

https://github.com/fish-shell/fish-shell/blob/dd815eef387e56e7a481a4672e4fdfab6e4654aa/src/proc.h#L74-L78

Presumably we could check a specific WEXITSTATUS to see if it gives us the status we expect. If it doesn't we try it the other way around, so we could figure this out without resorting to `__HAIKU__` defines.

I have an idea for how to do that, but I'm going to have to wait for my haiku vm to finish compiling fish. This might take 30 minutes.

**Comment by extrowerk** [comment]
Thank You!
