### ISSUE TITLE
Question translating command to fish

### ISSUE THREAD

**Issue by sascha-andres** [fish-shell/fish-shell#9068]
I have an issue translating a command from bash to fish. This is not  a bug but missing knowledge on my side, and the docs I found have not helped me understand.

This is the command:

    (setsid socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:"npiperelay.exe -ei -s //./pipe/openssh-ssh-agent",nofork &) >/dev/null 2>&1

This starts socat in the background and essentially discards all output. How would I write something like this in fish? It is meant to be part of config.fish, so running it in the foreground is not an option

**Comment by faho** [comment]
The `()` here start the command in a subshell, which is typically unnecessary.

You can try just leaving them off, the rest is *almost* the same - you now need to move the redirections before the `&` because that already terminates the command.

```fish
setsid socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:"npiperelay.exe -ei -s //./pipe/openssh-ssh-agent",nofork >/dev/null 2>&1 &
```

**Comment by faho** [comment]
Okay, I think I figured out why the subshell is there.

What we're doing here is reverse engineering - you have your finished code, and we need to figure out why it is the way it is. Bash script is full of subtleties, and so that's not always easy.

`()` starts a subshell, which means it starts a new bash process as a clone of the original - it inherits all of the environment and after that is fully separate. That's typically used to isolate changes from the original process. E.g. you'd do

```sh
(cd /tmp; ls)
```

to execute `ls` in /tmp, without having the original shell also move to /tmp. And if any other global variable is changed inside the subshell, it also doesn't affect the original shell.

But that's not what happens here!

What happens is:

1. A subshell is started with stdout and stderr connected to /dev/null - any processes it starts will inherit that
2. The `setsid` process is started in the background
3. The subshell might print a message that a background process was started (bash doesn't, here, by default, but other shells or with configuration it might)
4. That message (and any other message the subshell might print on its own) goes to /dev/null, i.e. nowhere
5. The subshell exits and leaves its background processes around
6. Because the backgrounded process was started in a subshell, the original shell has no idea, and e.g. `jobs` won't list it and `fg` won't foreground it

So: This subshell is essentially a `disown`.

That means in fish-ese this would be:

```fish
setsid socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:"npiperelay.exe -ei -s //./pipe/openssh-ssh-agent",nofork >/dev/null 2>&1 &
disown
```

**Comment by sascha-andres** [comment]
Thanks! Now coming up with no errors!
