### ISSUE TITLE
`fish_config theme save` returns "Too few arguments"

### ISSUE THREAD

**Issue by AgingOrange** [fish-shell/fish-shell#9088]
fish 3.5.0 on macOS Big Sur 11.6.7

Basically, I'm following the example from https://fishshell.com/docs/current/faq.html#how-do-i-customize-my-syntax-highlighting-colors

`fish_config theme show` works
`fish_config theme choose [name_of_theme]` works
`fish_config theme save` returns "Too few arguments"

**Comment by mqudsi** [comment]
As far as I can tell, the documentation is wrong here because from my reading of `fish_config.fish`, `fish_config theme save xxx` is to replace the theme of name xxx with the current/active theme colors/config.

At first I thought `fish_config.fish` just conflated the arg count for `fish_config theme choose` with `fish_config theme save` because they were being handled in the same block, but it seems that `fish_config theme save` is something entirely different from what the docs intend at this step.

**Comment by mqudsi** [comment]
This is fixed for the next release.
