### ISSUE TITLE
Launching fish asks for a password

### ISSUE THREAD

**Issue by DevFlock** [fish-shell/fish-shell#9102]
```
fish, version 3.1.0
Linux DevLaptop 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color
```
This was a fresh install of fish so no customizations

I installed by running the following:
```
sudo apt-get install fish -y
sudo chsh -s $(which fish)
```

Whenever I launch a new terminal it launches with a `Password: ` prompt. I can put anything in here, or even ctrl c it and I can still access the fish terminal. Although if the password is wrong it outputs `chsh: PAM: Authentication failure`,

**Comment by faho** [comment]
Fish doesn't ask for a password. It doesn't have that functionality and never did.

Read your error message carefully:

>chsh: PAM: Authentication failure

This tells you what asked for the password: `chsh`.

It appears that you have added a `chsh` call to your configuration, like you've added `sudo chsh -s $(which fish)` to config.fish.

That's unnecessary and unhelpful - chsh changes system configuration, so the changes it makes are already persistent. It's also unhelpful because changing your shell when you already have a shell running is too late.

Remove what calls chsh from your configuration.

As a sidenote: "fish, version 3.1.0" is quite old. It is missing over 25% of all changes ever made to fish. It's not even the last release of the 3.1 series, that would be 3.1.2.

**Comment by DevFlock** [comment]
Oh yeah it seems that I have added `chsh -s /usr/bin/fish` in my fish config file. Thanks!
