### ISSUE TITLE
Randomly Fish invoked oom-killer

### ISSUE THREAD

**Issue by yuvaramachandran** [fish-shell/fish-shell#9106]
engineer@OpenWRT ~> fish --version
fish, version 3.1.0
engineer@OpenWRT ~> echo $version
3.1.0
engineer@OpenWRT ~> uname -a
Linux OpenWRT 4.19.208 #1 SMP PREEMPT Mon Aug 1 16:50:12 UTC 2022 armv7l GNU/Linux
engineer@OpenWRT ~> echo $TERM
xterm
engineer@OpenWRT ~> sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
engineer@OpenWRT /h/engineer>
[fish_oom_issue.txt](https://github.com/fish-shell/fish-shell/files/9250447/fish_oom_issue.txt)

**Comment by faho** [comment]
>fish, version 3.1.0

fish 3.1.0 is about two and a half years old and four minor releases behind. It lacks over 25% of all commits ever released.

Try again with fish 3.5.1 and report back.

**Comment by yuvaramachandran** [comment]
Sure i will try with 3.5.1 and update. 

Thanks

**Comment by floam** [comment]
It might just use too much memory for your router with openwrt. Your only hope might be if we start storing stuff as UTF-8 and use string_vew.

**Comment by faho** [comment]
This shows an RSS of 81435. I believe that's in kilobytes, so that's ~81 megs of memory. That's off from a typical value by a factor of 10 to 25 or so (I see somewhere between 2500 and 6000 here).

So it stands to reason that there's a memory leak, and so it stands to reason that this should be tested with the latest version in case we've fixed it.

It would, of course, be possible to improve fish's memory usage (in fact I'm working on fixing an egregious case), but a typical use in the single digit megs isn't a massive problem, and we've not seen a lot of reports for out-of-memory crashes.

Not that we're likely to start storing stuff as UTF-8 (we are *extremely* tied to wchar), or that string_view would help much - we *already* pass most things as reference or pointer.

**Comment by yuvaramachandran** [comment]
> > fish, version 3.1.0
> 
> fish 3.1.0 is about two and a half years old and four minor releases behind. It lacks over 25% of all commits ever released.
> 
> Try again with fish 3.5.1 and report back.

I have upgraded to fish 3.5.1. OOM issue not yet observed so far.
