### ISSUE TITLE
math: Add scale argument to "round"

### ISSUE THREAD

**Issue by kseistrup** [fish-shell/fish-shell#9117]
The fish `math` functions seems to get it wrong sometimes, when doing integer math:

```sh
> math --scale=0 "22 / 5"         # this is all fine
4
> math --scale=0 "22 / 5 - 5"     # this ought to give -1
-0
> math --scale=0 "-5 + (22 / 5)"  # parentheses or reverting expression doesn't help
-0
```

This has been a problem for all fish3 releases, as far as I can tell, but I always thought it was an error in my scripts.

```sh
> fish --version
fish, version 3.5.1
> uname -a
Linux home 5.18.16-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:04 +0000 x86_64 GNU/Linux
```

**Comment by faho** [comment]
Integer math is truncated, not rounded. The documentation explains this.

**Comment by faho** [comment]
After a further look, the wording there is fairly confusing:

> A scale of zero causes results to be rounded down to the nearest integer. So 3/2 returns 1 rather than 2 which 1.5 would normally round to. This is for compatibility with bc which was the basis for this command prior to fish 3.0.0. Scale values greater than zero causes the result to be rounded using the usual rules to the specified number of decimal places.

So, yes, it does explain that it truncates via the example, but "rounded down" and "to the nearest" is somewhere between misleading and outright wrong. I've now tried to improve that.

Anyway, this was implemented as an awkward compatibility compromise, and so it probably needs to stay an awkward compatibility compromise, because I don't believe it's worth the cost of fixing it (because *finding* places where people even use integer math is hard, let alone figuring out which rounding they expect).

So this will just be how the cookie crumbles.

**Comment by kseistrup** [comment]
I respect your decision, but finding a place where people use integer math is not hard:

* https://codeberg.org/kas/qtime/issues/5

And `bc` does get it right:

```sh
$ echo '22 / 5 - 5' | bc --scale=0
-1
```

As I said, I respect your decision, but the conclusion will be that using integer math in fish to calculate array indices cannot be done reliably and should be avoided.

**Comment by kseistrup** [comment]
And PS:

> Integer math is truncated, not rounded.

That is what I expected in my calculations. `math 22 / 5` should give `4`, and `math 22 / 5 - 5` should give the same as `math 4 - 5`: `-1`.

**Comment by faho** [comment]
>I respect your decision, but finding a place where people use integer math is not hard:

Not finding *a* place, finding *all the places*.

I'm talking about the issues with a compatibility break.

**Comment by kseistrup** [comment]
I stand corrected.

**Comment by krobelus** [comment]
I think we should fix this because the other behavior doesn't make sense.
As you point out, truncating only at the end should results in incorrect evaluation of parenthesized expressions (compared to manual evaluation). We should truncate eagerly.

---

my `bc` doesn't accept `--scale` but I can set the scaling

```
$ echo 'scale=0; (22 / 5) - 5' | bc
-1
$ echo '(22 / 5) - 5' | math --scale=0
-0
```

**Comment by krobelus** [comment]
Hmm okay it's not so simple.

The problem you are seeing is that `bc` (hence fish 2.x) use `scale` for
the precision of all computations, whereas the new builtin `math` uses the
scale only when printing the results.

Another test case to illustrate the issue:

	$ echo 'scale=3; (1 / 3) * 4' | bc
	1.332
	$ echo '(1 / 3) * 4' | math --scale=3
	1.333

This example suggests that the behavior of `math` is actually better because gives a more precise result.
Also it's closer to what Python does, which is a good sign.

In Python you'd just use explicit truncation which we can also do:

	$ math 'floor(floor(22 / 5) - 5)'
	-1

I don't think we should try to go back `bc` semantics here.
Since the confusion stems from the fact that `--scale` only applies to the output, how about deprecating it in favor of something like `round(x, scale)`?
We'd just need to add an optional second argument to `round()`.

**Comment by kseistrup** [comment]
@krobelus Thanks for elaborating.

When writing the fish script that uses integer math for array indices I was actually thinking about Python's integer division (`//`):

```py
>>> 22 // 5 - 5
-1
```

And for the few values I tested it seemed that fish3 was getting the same results. Unfortunately it didn't hold up for all the values I needed.

**Comment by krobelus** [comment]
Adding  `//` to builtin `math` sounds fine too.

**Comment by kseistrup** [comment]
If `--scale=0` worked the way it does in `bc` there wouldn't be a need for `//`. Also, `//` is only of limited help if the rest of the calculations (i.e., without setting `--scale=0`) is floating point.

**Comment by kseistrup** [comment]
PS: The nested `floor()` “solution” mentioned above seems to solve my problem until `--scale=0` one day works as expected in fish3. Thanks for that.

**Comment by krobelus** [comment]
> If --scale=0 worked the way it does in bc there wouldn't be a need for //. Also, // is only of limited help if the rest of the calculations (i.e., without setting --scale=0) is floating point.

Once again: I think we should deprecate `--scale` because  it  is easily misunderstood. Going back to the `bc` behavior would make other cases worse.

> PS: The nested floor() “solution” mentioned above seems to solve my problem until --scale=0 one day works as expected in fish3. Thanks for that.

Note that the equivalent to `--scale=0` would be `trunc()` which doesn't exist yet. Shouldn't be much work to add ;)

**Comment by kseistrup** [comment]
I have found a solution that works for me, so just for the record (and bookmark):

Gavin D. Howard has authored a well-written `bc` implementation (in C) that can also be compiled as a math library with C bindings (in case someone decides that it would be nice to have full `bc` compatibility built into fish3):

* https://git.yzena.com/gavin/bc/

Disclaimer: I am neither a developer, nor a programmer, so I don't even know if C is freely mixable with C++.

**Comment by faho** [comment]
Yeah, nah, incorporating bc for us is a non-starter at this point.

It's a fairly awkward dialect that has weird incompatible implementations. Also that particular author is a fairly unpleasant person, and I would not want to depend on his software.

----

Anyway, switching the meaning of `--scale=0` strikes me as a bad idea at this point. I don't believe truncation is a terrible idea, either. Often when I want integer math, I really do just want to throw away all non-integer bits.

Adding an argument to `round` to specify rounding should be okay.
