### ISSUE TITLE
fish_prompt detect clear/terminal initialization

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#9142]
```fish
function fish_prompt
    echo
    echo $PWD
end
```

This produces a newline between each prompt essentially, visually separating them. However, when the terminal is first opened, or when we run `clear`, the newline is unnecessary. Is there a way of preventing the newline after the terminal has been cleared/initialized? Or otherwise having a line between prompts normally, but not after a clear/new shell?

**Comment by page-down** [comment]
How about using a global flag? If it is the first run then set the flag and skip outputting blank line.

Since clear is an executable, you can write a function `clear` and reset the flag before executing command clear.

```fish
function fish_prompt
    set -q _prompt_init
    and echo
    or set -g _prompt_init
    echo $PWD
end

function clear
    set -e _prompt_init
    command clear
end
```

The above also works when pressing Ctrl+L.

**Comment by faho** [comment]
In general, it's not possible to figure out if something cleared the terminal.

E.g. on my terminal, `clear` prints the same as `echo \e\[H\e\[2J\e\[3J`. So you could use that, or you could use another command that also clears the screen. E.g. what if a script file does `clear` at the end?

You *could*, theoretically, ask the terminal for the current position - `echo \e\[6n`.

However, we've never done that because it's awkward. You have to wait for the terminal to respond. This can happen in milliseconds (which is *already* slow!), or it might take seconds (think a remote link over ssh), or it might not happen at all (terminal doesn't support it). This is also why we don't do feature detection via queries. It's not usable in general. Even if it works in a specific terminal, you have no guarantee that it works in the user's, and the failure mode - waiting for seconds - is terrible. (this is very much a case where I disagree with terminal developers)

Additionally, it would require a read timeout (#1134), and terminals don't print a newline or NUL after the position, so it would require a custom read terminator ("R").

To be quite honest: I wouldn't bother with collapsing the newline. I don't think I personally would bother with the separation at all, because we already guarantee that your prompt is on a new line after the output (that's when that `⏎` character appears).

**Comment by floam** [comment]
I'd just disagree a little bit, and say that it'd be a bad idea to have a timeout for multiple seconds for terminal query stuff. Either it works in a hundred ms or the connection is too slow to do it. I don't think that such a feature should be avoided like the plague or evaluated on like the worst implementation worst case scenario.

**Comment by faho** [comment]
Okay, question has been answered, closing.
