### ISSUE TITLE
Bitwise `not` operation in math command

### ISSUE THREAD

**Issue by ian-h-chamberlain** [fish-shell/fish-shell#9148]
```console
$ fish --version 
fish, version 3.5.0
$ echo $version 
3.5.0
```

It seems #7281 added bitwise AND, OR, and XOR, but I cannot find any way to do a bitwise NOT operation. Is this supported, or if not could it be added? 

It seems the unary `!` or `~` operators are not taken already and could be used, but I imagine a `bitnot` function would make the most sense for consistency with the other bitwise functions.

**Comment by faho** [comment]
The big problem with NOT is that it implies a specific bit width, while we internally do everything in double, converting to long long only for the bit operations.

I.e. what should `math bitnot 0xF` do? Is it 0? Is it 0xF0? 0xFFFFFFFFFFFFFFF0?

Note that "long long" is machine-dependent and at least 64 bits, so that last answer is the naive answer you'd get.

So a "nand" kinda makes more sense, and then you can do `math bitnand 0xF, 0xFF` to supply your own width.

**Comment by juntuu** [comment]
Shouldn't `nand(a, b)` be `not(and(a, b))`, not `and(not(a), b)`? Or maybe it should be called something else?

Also flipping selected bits can be done with xor: `xor(0xF, 0xFF) = 0xF0`.

The xor has one possible drawback compared to the suggested nand: it doesn't clear bits outside the mask. But that could be done with one extra `and` in case the other operand might be wider than the mask `and(xor(a, mask), mask)` or `xor(and(a, mask), mask)`.

**Comment by faho** [comment]
Ah, it appears this is trickier to do for nand than I assumed:

Since we don't have a set width, we pretend leading zeroes don't exist until we "need" them. This means naively

```
nand 0x2, 0x1
```

is... 0x3 - whereas you might expect 0xf.

One possibility is selecting leading zeroes up to the next nybble, but it's unclear that that's what you want in every case, so xor is probably the way to go.

xor helps us because it naturally ignores leading zeroes - 0 xor 0 is just 0 - so we can just ignore them.

And, well, `bitxor` already exists!

That means this can probably be closed. I'll leave it open for a bit for someone to disagree with me.

**Comment by faho** [comment]
Done.

**Comment by ian-h-chamberlain** [comment]
Thanks for the notes, for my use case this seems to work, I suppose there are a lot of different ways to work around this for the alignment use case (using modulo, integer division, etc).

```fish
set align 0x10
set ptr 0xDEADBEEF
math --base 16 "bitxor(bitor($ptr + $align - 1, $align - 1), $align - 1)"
math --base 16 "floor(($ptr + $align - 1) / $align) * $align"
```

Actually, when experimenting I noticed something else interesting: this seems to work basically how I originally wanted:
```fish
math --base 16 "bitand($ptr + $align - 1, -$align)"
```

Is that simply a "lucky" side effect due to the bitwise representation of negative numbers? Should the use of negatives in bitwise operations be explicitly disallowed, or perhaps a documentation note added about how they work?

**Comment by krux02** [comment]
I just stumbled upon the documentation of `bitnot` being missing. This did bother me, not because I would need it (I don't) but because it is totally possible to implement `bitnot` if you don't know the amount of bytes if you use signed numbers (unsigned it doesn't work). There is a pattern in bitnot. `bitnot(3)` is `-4`, no matter how many bytes you use. The same consistency exists for any other value. The way I like to explain it is, conceptually positive numbers have an infinite amount of leading `0` bits and negative numbers have an infinite amount of leading `1` bits. If you flip bits in a number, you also have to flip this infinite prefix. On computers, this infinite prefix is only stored partially, if you flip all bits of it, the result will be correct. Long story short, bitnot can be implemented.

**Comment by faho** [comment]
>Long story short, bitnot can be implemented.

Quite simply put: I do not believe that behavior is a good and intuitive choice for `math`.

The bitwise operations here aren't a huge thing to begin with, and when they are you want something like e.g. handling permission bits (so for `not` you would want to flip them).

And in that case, giving negative numbers is entirely unhelpful.

**Comment by krux02** [comment]
> Quite simply put: I do not believe that behavior is a good and intuitive choice for `math`.

What's the problem here? This is the behavior of any other language that has bitwise not on signed numbers.

> The bitwise operations here aren't a huge thing to begin with

True. But as they are, without a `not`, they feel incomplete. And the *documentation* why it can't be done bothers me.

>  and when they are you want something like e.g. handling permission bits (so for `not` you would want to flip them).
> And in that case, giving negative numbers is entirely unhelpful.

Is it really? Have you tried it? Because I have, and I see no problem in it. In context of bitmasks, the negative numbers are the inverse bitmasks. Those that consist of only 1 bits and only a few of them are set to 0.
