### ISSUE TITLE
Error when setting has default shell on macOS

### ISSUE THREAD

**Issue by RandomWater** [fish-shell/fish-shell#9161]
On fish 3.5.1 using OS X 12.5
I keep getting this error loading up my terminal:

[Command not found: /bin/fish]

[Could not create a new process and open a pseudo-tty.]

Can anyone help me with this?

**Comment by faho** [comment]
This is one of those cases where the error message helps:

> [Command not found: /bin/fish]

Okay, so `/bin/fish` can't be found. This is, most likely, because it doesn't exist.

/bin/fish would be a very unusual path for fish to be in. Usually it's either /usr/local/bin/fish, or /opt/homebrew/bin/fish (if you used homebrew).

So: You gave the wrong path to `chsh`.

Open your terminal settings, tell it to run a specific command instead of "the shell", like /bin/bash. Then redo the steps you did to make fish the default shell, except this time use the actual path to fish. To figure that out, try `command -v fish` (this will work in bash, fish and zsh).

**Comment by RandomWater** [comment]
Thanks, dude you really helped me!
