### ISSUE TITLE
Recursively load snippets in `conf.d/`

### ISSUE THREAD

**Issue by metov** [fish-shell/fish-shell#9173]
It seems like when I put a file in `conf.d/test.fish` it gets executed on startup as you would expect. (I am testing it by putting `echo "Hi!"` in the file, which prints "Hi!" on shell startup.) However, if I put it in `conf.d/foo/test.fish`, it stops working. It looks like fish only sources the files that are directly below `conf.d/`, and does not recursively walk through the folder.

Is this expected behavior? Is it deliberate?

I like to keep my customization segmented into separate files and organize these into directories. For example, I'd like to have a `conf.d/alias/` directory, where I can put files like `git.fish` or `docker.fish` that have my aliases. Is this supported in fish?

**Comment by faho** [comment]
Yes, this is deliberate.

We don't want to complicate this any more, if you want to support it, it's easy enough to do:

```fish
for file in ~/.config/fish/conf.d/*/*.fish
    source $file
end
```

**Comment by metov** [comment]
Fair enough! Just 2 more questions:

1. If I want to support multiple subfolders, would `~/.config/fish/conf.d/**.fish` also work?
2. Would `find ~/.config/fish/conf.d/ -name '*.fish'` also work? Would it be much slower than your version? My main concern is to avoid making the shell slow to load/render prompt.

My current use is such that one level of subdirs will probably be enough for a while. I'm asking mostly out of curiosity.

Also, it might be worth stating explicitly that it is not recursive in https://fishshell.com/docs/current/index.html#configuration or https://fishshell.com/docs/current/language.html#configuration. I checked these pages before, and it did sound like it was probably not recursive, but I wasn't entirely clear if I understood it right.

**Comment by faho** [comment]
>If I want to support multiple subfolders, would ~/.config/fish/conf.d/**.fish also work?

No, that would also match all files directly in conf.d. It would have to be

`~/.config/fish/conf.d/*/**.fish`

The `/*/` means it needs to go at least one level deep.

>Would find ~/.config/fish/conf.d/ -name '*.fish' also work?

Same problem as above. I think find had a `-mindepth` option or something?

>Would your version be much faster

Probably. Last time I profiled this, the cut-off point for `find` being faster was ~5000 files on my system.

The only real way to tell is to profile it.

>Also, it might be worth stating explicitly that it is not recursive

If we tried to mention everything that is *not* the case we'd be busy for a long time.

I believe we have, in total, have had this question twice since conf.d was added 6 years ago. It doesn't appear to be a common point of confusion, and it's easy enough to check.

**Comment by metov** [comment]
Makes sense! Thank you for the detailed answer. I don't think anything else needs to be done on this so I'll go ahead and close it for you.

>Same problem as above. I think find had a `-mindepth` option or something?

Indeed it does, and that would be the solution.
