### ISSUE TITLE
git add path autocompletion is slow (regression?)

### ISSUE THREAD

**Issue by tastyminerals** [fish-shell/fish-shell#9196]
Fish version: 3.5.1
OS: Monterey 12.5.1

Potential duplicate of #4117.

Typing in `git add tests/` and hitting `Tab` takes noticeably long before fish provides autocompletion options

`sh -c 'env HOME=$(mktemp -d) fish'` exhibits the same behavior.

Trying out the [standalone Fish app](https://github.com/fish-shell/fish-shell/releases/download/3.5.1/fish-3.5.1.app.zip) for Mac exhibits the same behavior.

**Comment by faho** [comment]
Okay, so let me ask the same thing I asked in 4117:

Run

```fish
fish --profile /tmp/some_file -c 'complete -C"git add "'
sort -nk 2 /tmp/some_file
```

What's the output?

**Comment by tastyminerals** [comment]
The above creates a `some_file` which contains 3549 lines. Which ones do you need to see?

**Comment by faho** [comment]
That run took a total of 52ms (31ms loading the completion script, 21ms running the actual completion) and wasn't slow.

I suspect what you're seeing is XCode's git being slow the first run on each boot. This happens because it'll try to see where the git executable is and checks codesigning and stuff.

Try profiling again after a fresh boot.

As I understand it we don't have a good way around that.

**Comment by faho** [comment]
Okay, I'm closing this because I'm assuming it's down to XCode's awkwardness, which as far as I know we have no good way to fix.
