### ISSUE TITLE
broken prompt for read in scripts

### ISSUE THREAD

**Issue by Wasja7** [fish-shell/fish-shell#9227]
fish, version 3.5.1 on Arch Linux

Since the update to 3.5.0 the prompt behaves strangely when called with `read` in a script. Keybindings for cursor navigation like Ctrl+a or Ctrl+e don't work. In vi-mode the mode indicator always shows "[N]", changing the mode doesn't work at all.
This is easily reproducible by running `fish -c 'read'`. Calling `read` in an interactive mode doesn't have this problem.
Maybe this has something to do with #8797?

**Comment by faho** [comment]
Indeed, this was caused by us not setting up keybindings when `fish_prompt` wasn't fired.

Should be fixed now by simply doing interactive setup when an interactive read is called as well.

(in future we could skip *some* of it, but this should be harmless since it worked that way up to 3.5.0, so this is the conservative choice)
