### ISSUE TITLE
Could fish support string manipulating?

### ISSUE THREAD

**Issue by leafonsword** [fish-shell/fish-shell#924]
Bash and zsh both support string manipulating,could fish also support?
I wish fish's string manipulating could be more friendly than bash/zsh~

**Comment by newhook** [comment]
@X4/@ridiculousfish have you given any more thought to the idea of replacing the fish language with something more real? What I don't see is how this works correctly on the command line? After all "ls" isn't a valid piece of lua. What did you have in mind?

**Comment by ridiculousfish** [comment]
I'm keeping an open mind :)

**Comment by newhook** [comment]
One idea could be to keep the fish language as is, and then allow native language functions:

pyfunction blah
     // python code goes here
end

All of the fish variables would be made available as python defined variables. Lists would be converted to python lists and so forth.

**Comment by newhook** [comment]
Upon reflection that approach doesn't work all that well. I have a better idea which I'm trying out to integrate python scripting into fish.

**Comment by newhook** [comment]
Ok, so I tested out my idea and it works. The basic idea is to write a python extension for fish. The current implementation exposes a fish module in python. It has the following functions:

# Add a new function with the given name.
fish.add(name, function)
# Get a fish variable.
fish.get(variable)
# Split a string variable into a list (used for fish arrays).
fish.split(string)
# set -g b
fish.set("a", "-g", "b")
# Evaluate a command. For example, fish.call('cd /')
fish.call(string)

I added a fish_python_path (like fish_function_path). All python files in this path are evaluated. For example:

// test.py
import fish

dirstack = []
def pushd():
   argv  = fish.split(fish.get('argv'))
   pwd = fish.get('PWD')
   dirstack.append(pwd)
   fish.cmd("cd %s" % (argv[0]))

fish.add('pushd', pushd)

Python files are reloaded upon change, much like the autoloaded fish functions. To this point the change hasn't made all that many changes to the fish internals. Most of the changes involve function.cpp to add a new python function, and exec.cpp to call a python function rather than a fish function.

Any thoughts? Concerns? Comments?

**Comment by ridiculousfish** [comment]
(I reformatted your comment)

**Comment by ridiculousfish** [comment]
Is the idea that fish would embed a Python interpreter?

**Comment by newhook** [comment]
Yes. I guess it could be optional, although it strikes me that making it mandatory would provide a more uniform and standard environment. The change I made added entries to configure.ac to detect the python installation and configure the includes and libraries appropriately.

**Comment by X4** [comment]
What I meant by exposing the internal state of fish was to expose an API similar to Web API's that are often times accessible through Resful URIs. I was thinking that fish could've been implemented using a FSM or PEG, which means that you can eather expose a stack oriented API DSL for the FSM, or in the case of a PEG just provide a language DSL that resembles a Restful API with URIs giving acces to fish functions, history etc.

That way you save a lot of time exposing fish functions via modules and are not bound to existing language bindings. Well if you're just lazy and have no lust to use a PEGs (in case you've not used it in the fish code) why not integrate a simple httpd and expose the fish API programatically? You'd save time exposing each new function and people would have a shell with built in Web API.

**Comment by ridiculousfish** [comment]
@X4 Sorry, I still don't understand what you're proposing. Today, I might write this on the command line:

    ls *.txt

This is parsed and executed according to the fish language. If we dropped the fish language and replaced it with Python or Lua or WebAPI or whatever, how would the user run that command? What would the user type?

**Comment by Undeterminant** [comment]
This and #156 are actually duplicates, I think.

**Comment by ridiculousfish** [comment]
Good call, let's track in #156
