### ISSUE TITLE
Only search in command names when completing, skipping descriptions

### ISSUE THREAD

**Issue by daanturo** [fish-shell/fish-shell#9269]
When searching for a command with `pager-toggle-search`/`complete-and-search`, sometimes command descriptions also match my search term, producing lots of noises.

How do I configure the searcher so that it only considers command names while ignoring descriptions?

```
fish --version
echo $version

fish, version 3.5.1-467-g70d2e97c9
3.5.1-467-g70d2e97c9

uname -a
Linux my-host 5.19.13-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Tue, 04 Oct 2022 14:37:01 +0000 x86_64 GNU/Linux

echo $TERM
xterm-256color

```

**Comment by faho** [comment]
Currently there is nothing to make you only search the actual completion text and not the description.

This is a trade-off - either we search only the names, which makes finding things via the descriptions awkward (I filter the git completions for "local" to narrow it to local branches quite often) or we search both, which might have more hits.

If you have too many hits, you either need to search more or narrow your initial command.

I don't believe adding a separate mode here is sensible - it's one of those power user things that only three people will ever find, and even if they found it, they need to think of using it in the moment.

E.g. we could add a separate binding "pager-toggle-search-names-only", or we could add a DSL "name:foo", but the fundamental issue there is discoverability vs the implementation complexity.

(e.g. how would you search for something looking like "name:foo"? would we have a "both:", and so you'd need to look for "both:name:foo"? what happens if you go from pager-toggle-search-names-only to pager-toggle-search?)

So I'll be tentatively rejecting enhancements here because I don't believe they're worth it.
