### ISSUE TITLE
head: cannot open '/proc/1/sched' for reading: No such file or directory

### ISSUE THREAD

**Issue by Onur-Cansever** [fish-shell/fish-shell#9275]
fish, version 3.4.0
3.4.0

Linux orion 5.19.14-gentoo-dist #1 SMP PREEMPT_DYNAMIC Wed Oct 5 17:59:19 -00 2022 x86_64 AMD Ryzen 5 5500U with Radeon Graphics AuthenticAMD GNU/Linux

With sh -c 'env HOME=$(mktemp -d) fish' command, there is no warning and issue. In normally running fish I get this warning after each comamands: head: cannot open '/proc/1/sched' for reading: No such file or directory

**Comment by faho** [comment]
>With sh -c 'env HOME=$(mktemp -d) fish' command, there is no warning and issue

That means the problem is in your configuration.

Which would be plausible, because fish itself doesn't really use /proc, and has no use of proc/*/sched that I can find.

**Comment by faho** [comment]
One thing that might be using this is older versions of `systemd-detect-virt`, see https://github.com/systemd/systemd/pull/17917. This was dropped in systemd 248-2.

We use it in the disco prompt: https://github.com/fish-shell/fish-shell/blob/07b2f1054bfa42b67ca5d132e2320e620daa0fb3/share/tools/web_config/sample_prompts/disco.fish#L43-L52, but that doesn't print an error in case /proc/1/sched doesn't exist. I just confirmed with systemd 247 on a system without that file. Also it only ever executes it once, so you wouldn't be seeing it after each command even if it was spewing an error.

What you are looking for is a line like

```fish
﻿head /proc/1/sched
```

because your error specifically mentions "head".

That [turns up a few times on github](https://github.com/search?l=&p=6&q=head+%2Fproc%2F1%2Fsched+extension%3Afish+extension%3Ash+language%3AShell&ref=advsearch&type=Code), mostly to try to detect if you are running in a container (which has been broken for years):

https://github.com/DeedWark/Bash-Tips/blob/2c9f7c8504de1b1c11d4f01a9313c78d35bd4921/container_detector.sh

https://github.com/dbudakov/otus-linux-2020-01/blob/06ba03c6e2122d6bc2854861f7ba4ff245c0bc85/05.process_fork/scripts/custom_ps.sh

https://github.com/empsafety/applications/blob/c9030f3070b58bd1b78e0ab49b0edf8b96abbde0/smart-city-app/certs/self-sign.sh

**Comment by faho** [comment]
Okay, the pure prompt uses this, and fails to check if /proc/1/sched exists: https://github.com/pure-fish/pure/issues/301

**Comment by Onur-Cansever** [comment]
ty, you are perfect sir. You can close topic, I just use other prompts for fish except the pure.

**Comment by edouard-lopez** [comment]
@Onur-Cansever if you are using `pure` you can [try the fix here](https://github.com/pure-fish/pure/pull/302).
