### ISSUE TITLE
prompt color as battery level indicator

### ISSUE THREAD

**Issue by tamis-laan** [fish-shell/fish-shell#9282]
I would like to use the prompt as a battery indicator. I would like to change the color from green to yellow to red to indicate battery level. Is this possible? I know one can use `fish_prompt` to change the prompt but this only updates the prompt for each entry and not continually making it unsuitable for battery indication.

**Comment by mqudsi** [comment]
There's no native support for async prompts but you can use something like this: https://github.com/acomagu/fish-async-prompt

**Comment by mqudsi** [comment]
I'm closing this as I think it's been answered, but feel free to respond with any followups. We can always reopen if there's a need.

**Comment by floam** [comment]
I don't think you need an async prompt, since the prompts redraw on their own when universal color variables change.

**Comment by tamis-laan** [comment]
@floam that sounds interesting how would that work?

**Comment by faho** [comment]
Alas, @floam is working on outdated information - 69c71052efa54c4409694255cef602f479db589a.

We used to have variable handlers for the various color variables, and then would call `commandline -f repaint`. But because changing the color variables is something people like to do inside the prompt, this led to an infinite recursion (well, "infinite" - it would hit the maximum stack depth).

So you *could* set up a universal variable, and a handler for it that calls `commandline -f repaint`, and then you could get another program to tell fish to change the variable.

This is also basically how those async prompt thingies operate - they use a universal variable to communicate with another process.

**Comment by tamis-laan** [comment]
@faho I see! How would I trigger commandline -f repaint from a running bash script?

**Comment by faho** [comment]
In your fish config, do:

```fish
function my_repaint_listener --on-variable my_counter
    commandline -f repaint
end
```

Then, in some script, call:

```
fish -c 'set -U my_counter (math "($my_counter + 1) % 50")'
```

This will increment the universal variable $my_counter, rolling over when it hits 50. The rolling over is out of an abundance of caution - technically `math` would start failing once your variable becomes too large (2 ^ 53, to be exact). The important part is just that it needs to *change*, so the running fishes realize.

**Comment by tamis-laan** [comment]
@faho this seams to work really well :) thnx!
