### ISSUE TITLE
[Help] Docker startup scripts on WSL2 for fish-shell

### ISSUE THREAD

**Issue by buinguyenhoangtho** [fish-shell/fish-shell#9284]
Hello guys. Im using WSL2 + Fish-shell+Docker for my work.
I already setup the fish-shell with WSL2 - Ubuntu 20.04.5 LTS Distro. I want to setup docker startup everytime i open Terminal. I was look up [this website](https://blog.nillsf.com/index.php/2020/06/29/how-to-automatically-start-the-docker-daemon-on-wsl2/) and see this script. But only work with **ZSH**. Can anyone help me how can i use it on fish-shell with `fish-config`.

The **zsh** scripts

```bash
echo '# Start Docker daemon automatically when logging in if not running.' >> ~/.zshrc
echo 'RUNNING=`ps aux | grep dockerd | grep -v grep`' >> ~/.zshrc
echo 'if [ -z "$RUNNING" ]; then' >> ~/.zshrc
echo '    sudo dockerd > /dev/null 2>&1 &' >> ~/.zshrc
echo '    disown' >> ~/.zshrc
echo 'fi' >> ~/.zshrc
```
Im not good at scripting so.. i hope you can help me 😄

**Comment by faho** [comment]
So, this adds a script to your ~/.zshrc.

The script looks like this:

```sh
# Start Docker daemon automatically when logging in if not running.
RUNNING=`ps aux | grep dockerd | grep -v grep`
if [ -z "$RUNNING" ]; then
    sudo dockerd > /dev/null 2>&1 &
    disown
fi
```

This isn't fish-compatible in a few ways:

1. Fish only does `$(foo)` (which are recommended even in posix script!) and `(foo)` command substitutions, not the backtick version
2. Fish sets variables with `set name value` instead of `name=value`
3. `if` ends with `end` and doesn't have a vestigial `then` attached.

So, this should look like

```fish
# Start Docker daemon automatically when logging in if not running.
set -l RUNNING (ps aux | grep dockerd | grep -v grep)
if [ -z "$RUNNING" ]
    sudo dockerd > /dev/null 2>&1 &
    disown
end
```

However: Fish reads its configuration file *always*, even in non-interactive shells, so you probably want to guard this. WSL seems to be launching a login shell, so you can check `status is-login`:

```fish
if status is-login
    # Start Docker daemon automatically when logging in if not running.
    set -l RUNNING (ps aux | grep dockerd | grep -v grep)
    if [ -z "$RUNNING" ]
        sudo dockerd > /dev/null 2>&1 &
        disown
    end
end
```

Ideally you'd be using an actual service manager like systemd to start this instead of cheesing it via the shell.

Anyway, if you have to use the shell, you'd put that into config.fish.

Also I would recommend you have a look at https://fishshell.com/docs/current/fish_for_bash_users.html to see the differences between bash (and mostly zsh) and fish.

**Comment by faho** [comment]
Question was answered, closing!
