### ISSUE TITLE
Ctrl and Alt + arrows shortcuts

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#9304]
fish 3.3.1 (but gonna update)

1) I'd like to be able to move past a word with Ctrl but also delete that word with Ctrl + Backspace
2) And in my editor Sublimetext, I also have Alt+arrow to move between groups of characters, it's more "refined" than Ctrl, so it serves a slightly different purpose. Is it available in fish?

**Comment by faho** [comment]
The issue is that what ctrl-backspace sends is unclear and non-standard.

In my terminal, backspace sends `\x7f`, which the terminfo entry also says it should, so it's also available as `-k backspace`. Ctrl-backspace sends `\b`, which is the actual backspace *character*.

Now you open up xterm, and it's the other way around - ctrl-backspace sends `\x7f`, backspace sends `\b`.

And my terminal sets $TERM to... xterm-256color.

So we've bound both of these to what the backspace key should be doing, as there's literally no way to tell which is correct.

If you want something different, follow https://fishshell.com/docs/current/interactive.html#custom-bindings - launch `fish_key_reader`, press your key, and use that `bind` command it prints.

>And in my editor Sublimetext, I also have Alt+arrow to move between groups of characters

Alt-left/right is bound to "prevd-or-backward-word"/"nextd-or-forward-word". These will move through directory history when the commandline is empty, and move word-by-word otherwise.

**Comment by faho** [comment]
> But I think there is a conflict with my terminal: Tilix. When I have a split panel open, it switches to the other panel.

That means that your terminal won't be telling fish that you pressed the keys.

Again: Start `fish_key_reader`, press whatever keys you want. If it doesn't tell you any keys, or it tells you weird keys, then that's because that is what your terminal sends.

>So what should I do with that?

You'll have to reconfigure your terminal or, if that's not possible, switch to a different one.

**Comment by BarbzYHOOL** [comment]
i configured it correctly

I also now use alt + up arrow to get the last used argument, it's faster (or sometimes i type !$)
