### ISSUE TITLE
RFC: allow switch case fall through with explicit `fallthrough` keyword

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#9308]
`switch` statements in fish do not fall through. Only the first matching case is executed. This is obviated a bit with cases taking multiple parameters.

Still, this sometimes gets in the way.

I propose a `fallthrough` keyword that, when encountered in a `case`, causes the next proceeding `case` to be evaluated.

For example, the example switch in the documentation:
```fish
switch $animal
    case cat
        echo evil
    case wolf dog human moose dolphin whale
        echo mammal
    case duck goose albatross
        echo bird
    case shark trout stingray
        echo fish
    case '*'
        echo I have no idea what a $animal is
end
```

Would echo "evil" and "mammal" if $animal were "cat" and the first case fell through:
```fish
switch $animal
    case cat
        echo evil
        fallthrough
    case cat wolf dog human moose dolphin whale
        echo mammal
    case duck goose albatross
        echo bird
    case shark trout stingray
        echo fish
    case '*'
        echo I have no idea what a $animal is
end
```

Or a real world example, `touch` completions could have a the BSD portion simplified as:

```fish
switch (uname -s)
    case Darwin DragonFly FreeBSD
        complete touch -s A -d "adjust timestamps by relative value [-][hh]mm]SS" -x
        fallthrough
    case Darwin DragonFly FreeBSD NetBSD
        complete touch -s h -d "act on symbolic links themselves"
        fallthrough
    case Darwin DragonFly FreeBSD OpenBSD SunOS
        complete touch -s d -d "set to specified YYYY-MM-DDThh:mm:SS[.frac][tz]" -x
        fallthrough
    case '*'
        # common BSD options
        complete touch -s c -d "don't create file if it doesn't exist"
        complete touch -s r -d "use times from specified reference file" -r
end
```

**Comment by floam** [comment]
Or, reuse `continue`?

**Comment by faho** [comment]
>Or, reuse continue?

That would be an awkward compatibility break.

The issue is that `continue` can currently be used in that place, if you have a surrounding loop:

```fish
﻿for f in 1 2 3
    switch $f
        case 1
            continue
        case '*'
            echo $f
    end
end
```

prints 2 and 3. If `continue` was a fallthrough it would print 1 as well.

-----

Tbh I'm not sold that adding fallthrough is worth it to begin with, but if we did reusing `continue` would *not* be the way to go.

**Comment by faho** [comment]
And here's why I'm not sold on fallthrough:

That real world example is a transformation of this:

```fish
    set -l uname (uname -s)

    contains $uname Darwin DragonFly FreeBSD
    and complete touch -s A -d "adjust timestamps by relative value [-][hh]mm]SS" -x

    contains $uname Darwin DragonFly FreeBSD NetBSD
    and complete touch -s h -d "act on symbolic links themselves"

    contains $uname Darwin DragonFly FreeBSD OpenBSD SunOS
    and complete touch -s d -d "set to specified YYYY-MM-DDThh:mm:SS[.frac][tz]" -x

    # common BSD options
    complete touch -s c -d "don't create file if it doesn't exist"
    complete touch -s r -d "use times from specified reference file" -r
```

Which is 9 lines with actual source, or 14 physical lines.

And not only is the version with fallthrough 14/15 lines, it's also less clear which option applies to which BSD. To figure out that `-h` is a thing on NetBSD, I need to follow the fallthrough and look at the case before the current one.

----

Just spitballing, here's an alternative idea:

"switchall", a version of *switch* that will run through *all* matching cases instead of stopping at the first one:

```fish
switchall (uname -s)
    case Darwin DragonFly FreeBSD
        complete touch -s A -d "adjust timestamps by relative value [-][hh]mm]SS" -x
    case Darwin DragonFly FreeBSD NetBSD
        complete touch -s h -d "act on symbolic links themselves"
    case Darwin DragonFly FreeBSD NetBSD OpenBSD SunOS
        complete touch -s d -d "set to specified YYYY-MM-DDThh:mm:SS[.frac][tz]" -x
    case '*'
        # common BSD options
        complete touch -s c -d "don't create file if it doesn't exist"
        complete touch -s r -d "use times from specified reference file" -r
end
```

This is 11/12 lines, and if you want to know what case something applies to, you just need to look at the last case statement. The trade-off is that you need to repeat the cases, but in turn you also don't need to use "fallthrough".

In reading the example with fallthrough, I've been confused a few times as to whether `-d` applies for NetBSD because it doesn't list NetBSD in the final non-default case. But then it could also be:

```fish
    case Darwin DragonFly FreeBSD
        complete touch -s A -d "adjust timestamps by relative value [-][hh]mm]SS" -x
        fallthrough
    case NetBSD
        complete touch -s h -d "act on symbolic links themselves"
        fallthrough
    case OpenBSD SunOS
        complete touch -s d -d "set to specified YYYY-MM-DDThh:mm:SS[.frac][tz]" -x
        fallthrough
```

which I would argue shows nicely how weird this is to read (and also why we use fallthrough in C++ sparingly).

And if you want to list all the cases anyway, switchall just forces you to do that.

I would also assume it is easier to implement than a fallthrough.

But even there, I'm not sold that the juice is worth the squeeze.

**Comment by floam** [comment]
>     case Darwin DragonFly FreeBSD
>         complete touch -s A -d "adjust timestamps by relative value [-][hh]mm]SS" -x
>         fallthrough
>     case NetBSD
>         complete touch -s h -d "act on symbolic links themselves"
>         fallthrough
>     case OpenBSD SunOS
>         complete touch -s d -d "set to specified YYYY-MM-DDThh:mm:SS[.frac][tz]" -x
>         fallthrough

No, because -A and -h and -d would not be created for macOS, DragonFly BSD, FreeBSD.

With switchall, I imagine the question that would come up is "how do I make some `break`?".

**Comment by faho** [comment]
>The idea was fall through would just try the next case if it also matches.

That seems like the word "fallthrough" doesn't really explain it, it's more like a "trynext".

Which I guess explains why you wanted to reuse "continue".

**Comment by floam** [comment]
Yeah, it's not a fall through in the regular sense of `switch`.

**Comment by floam** [comment]
Could do something funky like let break/continue take a parameter, that lets you specify the construct to pop out of: `continue switch`.

**Comment by floam** [comment]
It's probably just not worth it. The `contains` idiom I've been using isn't the worst thing in the world.
