### ISSUE TITLE
implement printf -v: to place string directly into a variable

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#9315]
There are difficulties with assigning the output of `printf` to a variable. Throw newlines and nulls into it, and my brain is turning to mush.

Imagine this line:

> printf "%s\n%f foo\x00and this" cats 15

Here's what I've tried:

```shell
> printf "%s\n%f foo\x00and this" cats 15
cats
15.000000 fooand this⏎                                                                                                                                                                            > set VAR (printf "%s\n%f foo\x00and this" cats 15)
> set --show VAR
$VAR: set in global scope, unexported, with 2 elements
$VAR[1]: |cats|
$VAR[2]: |15.000000 foo|
> set VAR (printf "%s\n%f foo\x00and this" cats 15 | string collect)
> set --show VAR
$VAR: set in global scope, unexported, with 1 elements
$VAR[1]: |cats\n15.000000 foo|
> set VAR (printf "%s\n%f foo\x00and this" cats 15 | string split0 | string collect)
> set --show VAR
$VAR: set in global scope, unexported, with 1 elements
$VAR[1]: |cats\n15.000000 foo\nand this|
> # hmm
```

… - this goes on, I waste time with piping to `read` and trying some tricks with `string escape` - but my brain is mush.

Let's implement `-v`:  it's an extension to printf(1) implemented by zsh and bash at least - where `printf -v foo bar` places formatted 'bar' in local variable $foo. It's convenient.

**Comment by faho** [comment]
This makes `printf` of all things another command that can set a variable.

It's a pretty cheesy thing, especially considering that variables can't contain NULs. They are exported as a NUL-delimited array!

**Comment by floam** [comment]
It's not a POSIX feature.

**Comment by floam** [comment]
> variables can't contain NULs. 

I'd expect them to only cut off when exported.

**Comment by faho** [comment]
I just edited my comment - we would have to change how we pass arguments to builtins. Currently that uses null_terminated_array_t already. `printf` isn't where the issue happens.

**Comment by faho** [comment]
Here: https://github.com/fish-shell/fish-shell/blob/3286c3cb6bf6b5067ee6eb591f68d9c1d6af0ee8/src/builtin.cpp#L452-L454

There's your problem.

Tbh if you want to juggle around NULs there's probably a nicer way, like keeping it as a list and using `string join0` where you need to pass it to something via stdin.

**Comment by floam** [comment]
I'm not following exactly - `printf -v` would not require a change in how arguments are passed to builtins to work, we passed it as an escape in the example.

**Comment by faho** [comment]
I'm saying if we adjust that, we won't need `printf -v`. Your initial `set` example with `string collect` will just work!

And `printf -v` is extremely weird and cheesy, so not having it is, in my humble opinion, preferable.

**Comment by floam** [comment]
And, I like the feature even if NULs weren't a thing - you don't even need to know how command substitutions work. Let alone use command substitutions and a subcommand of `string` just to avoid the newlines.

**Comment by faho** [comment]
I quite dislike the feature. I consider it a misfeature.

Like I said, it adds an option to `printf`, so now you need to do that `--` separation again, making it harder to just print an arbitrary string.

It's also just a conceptual mess - why does `printf`, which prints a formatted string, suddenly get to set a variable? Why not `math` or `path`? Is this necessary? We do have setting in some places like `argparse`, but that's because that sets *multiple* variables and allows it to express something that otherwise would be quite hard, and would require it to be used in a special way (think of how `getopt` needs to be used in a `while` loop). In fact, for a short while, `math` used to have (read) access to variables so you could do `math x + 2` and it would add 2 to the value of $x, and we removed it because it's weird that math can read variables, and conceptually unnecessary.

And the original impetus for this is simply incorrect - `printf -v` wouldn't work here the same way the other attempts didn't work, because of our argument passing. If you did `printf -v foo a\x00b` you would still get $foo set to "a", unless the argument passing is changed.

So I am quite against adding a weird feature just because other shells have it. We aren't posix, but we also aren't bash or zsh.

The "posix-me-harder" label isn't because a particular feature is "in POSIX" formally, it's there for issues that are asking for more compatibility - "just do what bash/zsh do", and it's there to remind us that fish very much isn't posix. So we should think about what makes sense for fish, not what makes sense for "an ordinary shell".

In this case `printf -v` wouldn't actually be enough. Unlike bash, where it's pretty much opt-in, we put scoping front and center. So it would be `printf -lxv`. We would have to introduce all those variable options like scope or exporting or possibly even `--path`, `--append`, `--prepend` to *printf* of all places.

The much simpler option is to just ask people to set the variable just like they would set it with any other command. Actually fix the underlying issue - the argument passing - and suddenly you can even do it with NULs. In a limited way, because shells by their nature, because of the APIs they use, are bad at handling arbitrary binary data, but still.

**Comment by floam** [comment]
> If you did printf -v foo a\x00b you would still get $foo set to "a", unless the argument passing is changed.

`printf -v foo "a\x00b"` will work.

**Comment by floam** [comment]
You shouldn't need to worry about using `--` in any general cases, as the ostensible first argument that printf takes is the format string, which is explicit at call sites. `printf $foo` is a dangerous form in other ways.

**Comment by faho** [comment]
>printf -v foo "a\x00b" will work. I think our argument passing is out of the scope of this.

It's really not.

Because if the argument passing is fixed, you can do any of these

```fish
set VAR (printf "%s\n%f foo\x00and this" cats 15 | string collect)
set VAR "cats"\n"15.0 foo"\x00"and this"
```

because your example here is unrealistic. If you have a hardcoded literal string, you can just use the literal string.

What you really want is

```fish
set VAR (find . -print0)
```

and that doesn't work because of argument passing. And even if you did `printf -v foo "a\x00b"` or `printf -v foo %s (find . -print0)`, without fixing the argument passing, you now couldn't use $foo anywhere! If you try to `printf %s $foo` it would print "a". If you tried to `string match $foo` it would match "a".

The only thing that `printf -v` adds is yet another way to set variables, modelled after a thing that in bash is mostly used to get indirect variable access.

It isn't useful for the thing you thought it was useful for. It isn't something that's asked for a lot, it isn't something that brings a lot of practical compatibility because it's not used a lot even in bash, and where it is used it's mostly used for reasons that don't matter to fish. It's just yet another way to set variables.

It also doesn't really help you not learn how command substitutions work, because command substitutions are really fricking important and so you need to learn them anyway.

>I thought it was a reference to POSIX_ME_HARDER.

It is, but the broader implication here is that $POSIX_ME_HARDER (now $POSIXLY_CORRECT) was invented by GNU because they didn't want to be compatible because they decided the compatible behavior is bogus.

So, as bash doesn't perfectly follow posix, we don't perfectly follow bash. In fact we follow pretty imperfectly, and that's on purpose.

----

I also want to ask you to please look at my entire argument. We've been down this road before, and only answering to specific points is a bad way to have a discussion.

**Comment by mqudsi** [comment]
I'm all for adding POSIX features in the name of *user* compatibility: things that would stop users from being able to do things that are common to do in other shells, commands/scripts they'd copy-and-paste from other places, or things that aren't possible any other way. 

This entire thing strikes me as a misfeature for many different reasons. I wouldn't implement it just to say we implement all of posix *and* I don't think there's any other reason to implement it. If it's a really complicated feature and not one that fish devs would regularly use, there's a great chance it'll have issues or fall into disrepair. We haven't had anyone request this (please correct me if I'm wrong), and no one is going to be porting a bash script that does this kind of stuff line-for-line to fish (it would have to be a rewrite).

**Comment by floam** [comment]
Okay, this is not a popular idea.
