### ISSUE TITLE
Add a JSON parser

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#9347]
Let's introduce some ability for fish to handle structured data out of the box. 

`printf`: %J

`read`: --json

Ideas for a minimal tool: https://github.com/dominictarr/JSON.sh

How ought it work? Can we steal some ideas from PowerShell or Capsicum?

**Comment by faho** [comment]
We do not have any data structures capable of expressing either dictionaries or nested lists, so I do not see this working.

**Comment by faho** [comment]
It seems nobody else is immediately interested, so I'm going to close this as "not planned".

Handling json isn't something that never happens, so it's not a completely terrible idea to add something that deals with it. I'd add something to handle json before I'd add something that handles mail, for sure.

But it's also not something that happens in every script, and there are well-known tools to handle it that work with fish - like `jq` and friends.

And given that it's not a constant concern and that we couldn't actually improve over `jq` because we don't have the data structures for it, it seems like anything to handle it would at the very least be a long way out. The issue to add dictionaries (#390) has been stalled for years with no clear idea on syntax or semantics, and that would need to be solved, and then the issue of nesting would have to be solved before we even begin to approach adding something here.
