### ISSUE TITLE
alias ls breaks scp completion

### ISSUE THREAD

**Issue by fiplox** [fish-shell/fish-shell#9363]
Aliasing ls to anything else then just ls (ls -l, exa, etc.) breaks scp if the default shell on server is fish.
If aliased to `ls -l`, scp with tab completion gives this (uranus is ssh server, tab pressed after `uranus:`):
```sh
$ scp uranus:drwxr-xr-x\\\ \\\ \\\ \\\ 5\\\ user\\\ \\\ \\\ \\\ \\\ user\\\ \\\ \\\ \\\ \\\ \\\ \\\ \\\ \\\ \\\ 4096\\\ Nov\\\ 20\\\ 12:05\\\
```
I use `exa`, and setting `alias ls 'exa -s type --color auto --icons'` just breaks scp completion.

fish version 3.5.1

probably related to #6724 as rsync is working as expected.

**Comment by krobelus** [comment]
should be fixed by b98cee10bb37bcc33c8686d092eb8a85ff23ae3c
Note that in general, overriding well-known programs with different behavior can lead to breakage in many parts of the system.
One partial remedy is to define aliases in interactive sessions only (see the snippet in the default `~/.config/fish/config.fish`), that would have prevented this particular problem
