### ISSUE TITLE
sudo -sE and fish -c (and user functions with sudo)

### ISSUE THREAD

**Issue by Susensio** [fish-shell/fish-shell#9381]
I have `sudo` aliased to `sudo -sE` in order to to get a more consistent behaviour whenever I execute `sudo` from `fish`. That way, my user functions still exists and I don't have to remember which one is a system command.
The problem is it's misbehaving when using variables. I think the problem is that `sudo -sE` translates to `sudo -E fish -c` with some substitutions to the command passed, as stated by `man sudo`.

MRE:
```fish
>> echo '$HOME'
$HOME
```

I'm using single quotes bc I don't want to perform variable substitution. Then I try to `sudo` it:
```fish
>> sudo -sE echo '$HOME'
/home/susensio
```

However, if I go into sudo completely, it behaves as expected:
```fish
>> sudo -sE
>> echo '$HOME'
$HOME
```
How can I avoid this variable substitution when calling `fish -c`?

**Comment by faho** [comment]
You are asking `sudo` to execute the arguments you give to it in a shell, then you give it shell script and it is run in a shell.

I don't understand what exactly you are expecting differently.

This command:

```fish
sudo -sE echo '$HOME'
```

has the outer fish give `sudo` a literal `$HOME`. But then *sudo* goes and starts a shell and tells that

```fish
echo $HOME
```

because that is what you asked it to? You told `sudo` to run this in a shell!

>I have sudo aliased to sudo -sE in order to to get a more consistent behaviour whenever I execute sudo from fish. That way, my user functions still exists and I don't have to remember which one is a system command.

Fish will update $HOME when it doesn't fit the current user. This is because it will also try to *write* to $HOME, and that's broken if $HOME is still /home/susensio but the user is root. Trying to keep $HOME pointing to another user's home directory is a bad idea.

**Comment by Susensio** [comment]
I edited my original comment because the last command has an error.
Summing up, these two works as expected:
```fish
>> echo '$HOME'
$HOME
```
```fish
>> sudo -sE
>> echo '$HOME'
$HOME
```

This one does not
```fish
>> sudo -sE echo '$HOME'
/home/susensio
```
The only difference is that the later is calling '`fish -c` under the hoods. Is there a workaround to make this work?

> Fish will update $HOME when it doesn't fit the current user. This is because it will also try to write to $HOME, and that's broken if $HOME is still /home/susensio but the user is root. Trying to keep $HOME pointing to another user's home directory is a bad idea.
I didn't understand this part. How should I do it, then, if I want to maintain my user functions with root privileges?

**Comment by faho** [comment]
Okay, let me try to explain in more detail:

```fish
sudo -sE echo '$HOME'
```

This is a command you run inside a fish session. That fish will go, determine the arguments, see what it needs to expand, handle quotes, ...

It will, at the end, see that you have these arguments:

`sudo`, `-sE`, `echo`, `$HOME`.

The last of which is what remains of `'$HOME'` after it has handled the quotes, which cause the `$` to not be expanded.

The command here is the first argument which is `sudo`, so we start `sudo`.

sudo sees that it got the arguments `-sE´, `echo` and `$HOME`. `-s` tells it to run a shell, and so it does.

It starts a fish and gives it the argument `-c` (to tell it to run a command), and gives it the rest of the arguments as one string: `echo $HOME`. So it does the equivalent of

```fish
fish -c 'echo $HOME'
```

However, it's only the *equivalent*. It doesn't *actually* pass those quotes (hopefully, at least). What it should do is simply start a command with these three arguments:

`fish`, `-c` and `echo $HOME`.

The quotes are a thing for inside of a shell. They aren't actually used to run a command.

And so that fish starts, it sees that it's supposed to run some commands (`-c`), and the commands are `echo $HOME`. This causes it to print `/home/susensio` because the `$HOME` is no longer quoted.

So the reason this happens is that you told `sudo` to run a shell, and so you now have two levels of shell to deal with.

If you wanted to have that quoted, you would need to execute the equivalent of

```fish
fish -c 'echo \'$HOME\''
```

and so you need to get sudo to do that. Unfortunately it appears `sudo` doesn't like that.

What *should* be working is this:

```fish
sudo -sE echo '\'$HOME\''
```

which passes `'$HOME'` to sudo, and which should cause *it* to pass `echo '$HOME'` as the command.

However it appears that `sudo` mangles the arguments even more and possibly performs some escaping (or even expands the variable itself?), so this doesn't work. That's not great, the `-s` function is rather annoyingly designed.

The best workaround is to simply not use it and instead tell sudo the command manually:

```fish
sudo -E fish -c 'echo \$HOME'
```

This will print your desired `$HOME`. Or write it to a file and run it with `sudo -E fish foo.fish`.

>How should I do it, then, if I want to maintain my user functions with root privileges?

Copy them, add that directory to $fish_function_path, ...

Trying to keep $HOME to another user's home directory has a bunch of problems.

**Comment by Susensio** [comment]
Perfectly explained. I've managed to get it working without messing with environment variables. This is my `sudo` wrapper, in case some find it useful.

```fish
function sudo -d "Sudo with fish user functions"
  # Substitute double bang !!
  if test "$argv[1]" = !! 
    set argv "$history[1]"
  end

  # If fish function, execute with fish
  if functions -q "$argv[1]"
    set cmdline (
      for arg in $argv
          printf "\"%s\" " $arg
      end
    )
    set -x function_src (string join "\n" (string escape --style=var (functions "$argv[1]")))
    set argv fish -c 'string unescape --style=var (string split "\n" $function_src) | source; '$cmdline
    command sudo -E $argv

  # If command, remove and use system bins
  else if test "$argv[1]" = "command" 
    command sudo $argv[2..-1]

  else
    command sudo $argv
  end
end
```

It's based on this gist https://gist.github.com/NotTheDr01ds/6357e48b511735c42b94c4cc081ac5dc 

Now I can call my fish functions with `sudo` and variable substitution works as expected.
