### ISSUE TITLE
bash error while install fish using brew on Ubuntu

### ISSUE THREAD

**Issue by Trid-collab** [fish-shell/fish-shell#9401]
I have trying to install fish using fish using brew in Ubuntu 22.04
The installation finshes without error
but when I try to run fish it give me the following error

`-bash: /home/linuxbrew/.linuxbrew/bin/fish: Bad address`

Could you help directing me to the resolution. I am new to fish and installing for the first time. I guess I am missing something here

**Comment by faho** [comment]
This seems to be an error when your $PATH or $ORIGINAL_PATH contains paths with `\\` in windows environments like msys or wsl. See for example https://stackoverflow.com/questions/41699029/cant-run-git-in-git-bash-bash-mingw32-bin-git-bad-address.

(note that you should mention if you use fish inside one of those, as they are a fairly leaky abstraction, which is why we sometimes need to work around their issues. In this case it seems to be a misconfiguration leading to an error in bash)

**Comment by Trid-collab** [comment]
I am trying to install fish through brew on Ubuntu on WSL2. The rest packages installed through brew seems in this platform seems to work well. The issue is only with fish that I get this error

**Comment by faho** [comment]
This is https://github.com/Homebrew/homebrew-core/issues/115895 - it might be solved by a WSL2 update (`wsl --update`).

**Comment by Trid-collab** [comment]
Using the fully qualified path - /home/linuxbrew/.linuxbrew/bin/fish? gives the following:
`-bash: home/linuxbrew/.linuxbrew/bin/fish: No such file or directory`

I am installing on WSL2 after  running the wsl --update - the only difference my Laptop is on Win 10 ver 21H2 not on the latest one , not sure if that's issue

**Comment by faho** [comment]
> the only difference my Laptop is on Win 10 ver 21H2 not on the latest one , not sure if that's issue

I would assume so, given that the linked issue says you need 22H2.

You might also need to reinstall or rebuild fish.

**Comment by Trid-collab** [comment]
Got it working, had to deinstall the install wsl2 . upgraded win 10 to 22h2 and then installed wsl2 and updating it using wsl --update
