### ISSUE TITLE
Curlrc in fish shell

### ISSUE THREAD

**Issue by Trid-collab** [fish-shell/fish-shell#9404]
I am trying to run the following command on the fish shell which is rnr running on Ubuntu 22.04 on WSL2 behind a firewall

I am running the same command on my bash shell on the same system - for which I have a .curlrc file in $HOME dir with "insecure" option for bypassing the firewall issues - which works.

In fish for the same stuff to work where do I need to place my .curlrc

`
HOMEBREW_CURLC=1 brew install fisher ==> Downloading https://ghcr.io/v2/homebrew/core/fisher/manifests/4.4.3 
curl: (60) SSL certificate problem: unable to get local issuer certificate More details here: https://curl.se/docs/sslcerts.html 
curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it. To learn more about this situation and how to fix it, please visit the web page mentioned above.`

`Error: fisher: Failed to download resource "fisher_bottle_manifest" Download failed: https://ghcr.io/v2/homebrew/core/fisher/manifests/4.4.3`

**Comment by krobelus** [comment]
This command should work the same way in bash and fish
What is the output of `type brew` in both shells?
Also, can you record the output of `env` in both shells and show their difference?
e.g. `env > env-in-bash`  and `env > env-in-fish` followed by `diff -u env-in-bash env-in-fish`

**Comment by faho** [comment]
This looks suspiciously like https://github.com/Homebrew/brew/issues/2609 and https://github.com/Homebrew/brew/pull/3482 - "HOMEBREW_CURLC=1" was never, as far as I can tell, a thing, but "HOMEBREW_CURL=1" was, only it was removed (because it was never sufficiently documented).

Try `HOMEBREW_FORCE_BREWED_CURL=1 brew install fisher` to see if that fixes your problem.

If that's not it, read on.

--------------------

The shell doesn't have a lot of influence over a program reading its config file. All that can really change is:

1. "curl" isn't the same "curl" in both, but a function that does something else or a different version
2. The environment variables are set differently so curl doesn't find its config files

From https://everything.curl.dev/cmdline/configfile#default-config-file:

> The default config file is checked for in the following places in this order:

> 1. $CURL_HOME/.curlrc
> 2. $XDG_CONFIG_HOME/.curlrc (Added in 7.73.0)
> 3. $HOME/.curlrc

(and some places for Windows, but WSL2 isn't windows in this case)

Since these places use environment variables, you to check the values of $CURL_HOME, $XDG_CONFIG_HOME and $HOME in both shells. This should work in both:

```fish
echo HOME: $HOME
echo XDG_CONFIG_HOME: $XDG_CONFIG_HOME
echo CURL_HOME: $CURL_HOME
```

The other possibility is that you have a function or alias in bash that you don't have in fish, or that the `curl` you execute is a different file. Try `type curl` in both to see if that is the case.

**Comment by faho** [comment]
*Alternatively* there used to be an option "HOMEBREW_CURL**R**C". You're missing an "R".

No idea if it still exists.

**Comment by Trid-collab** [comment]
Sorry, my bad. typo the first time and then the fish shell autocomplete/auto suggestions everytime - didn't notice the typo. Thank you for pointing it out.

**Comment by faho** [comment]
>BTW can you suggest a better way to manage the curl permission

Not a curl expert, sorry.

The underlying issue appears to be that your firewall man-in-the-middles your traffic, so you probably need to include the certificates it uses in your trust store. I can't be any more specific than that.

Since it works I'm going to be closing this issue.
