### ISSUE TITLE
Some translation strings are missing from the template

### ISSUE THREAD

**Issue by SilentoA** [fish-shell/fish-shell#9425]
I copied the repository and generated a template, but the required string for translation is not there. 

Here is a small example. Being in fish type `touch -` and press `tab` to show hints. Now copy the following text (Change access time) and try to find it in the template:

```
user@host ~/G/Fish> ls
fish.po
user@host ~/G/Fish> grep "Change access time" fish.po
user@host ~/G/Fish [1]> 
```

What can be done about it?

Archlinux, fish version 3.5.1

**Comment by faho** [comment]
The template needs to be regenerated from time to time, by running build_tools/fish_xgettext.fish.

I'm doing that now.

**Comment by faho** [comment]
The specific text "Change access time" isn't a string in fish, btw. So it's no wonder you won't find it, it's not something you'd translate. (it does exist exclusively in sv.po, but those parts are probably outdated - our translations are in a terrible state, to be quite honest)

**Comment by SilentoA** [comment]
Translation of this line `change access time (atime)` does not work, it is still displayed in English.

**Comment by SilentoA** [comment]
@faho I did this procedure again. But the translation is not picked up, something is clearly wrong.

**Comment by faho** [comment]
To use updated translations you need to actually install them.

(there's possibly some way to get gettext to read them from a specified file, but I've never found my way around that)

**Comment by SilentoA** [comment]
The translation is installed, but, as I said, it is not picked up.

**Comment by faho** [comment]
Works for me.

**Comment by SilentoA** [comment]
I understand you, there will be no help.

**Comment by faho** [comment]
What I mean is that just installing the updated translations, via something like `make install` was the step that I needed.

If that doesn't work for you, there is something else that you are missing, and you need to find that out. But what that is I am afraid I cannot help you with because I have no idea what your system looks like. I don't know how you installed the translations, how you are building fish.

In my case I use the PKGBUILD from [the AUR fish-git package](https://aur.archlinux.org/packages/fish-git) modified to point to my local copy of the repo.
