### ISSUE TITLE
Why is fish reading /etc/profile.d/xx.sh ?

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#9431]
Hello,
I have migrated from an Ubuntu to another and i'm figuring out why Fish shell is reading what is in this sh (or bash) file that I created myself. I've macde a google search and it was said on this repo that fish doesn't read /etc/profile cause it's not posix smthg

I'm wondering what is read in this file (i have put functions, aliases, environment variables). Well obviously the functions do not work and aliases do not seem to either. So it read only env var? is it documented somewhere?

**Comment by faho** [comment]
Fish does not read /etc/profile or /etc/profile.d/*.sh.

What happens here is that something in your login stack starts a posix login shell, and that reads these files, and any exported variable there will be exported to child processes, which fish inherits.

This is a general unix thing and not specific to fish.

**Comment by BarbzYHOOL** [comment]
Ok so I should not worry much? (tried in two different terminals either, same result)

**Comment by faho** [comment]
>Ok so I should not worry much? 

This is entirely normal.

>(tried in two different terminals either, same result)

Of course, because the *terminal* already has the environment!

When your system boots, it runs the init process. This process then runs all your services, including the desktop, which then starts all the other programs. Eventually it starts your terminal, and that then starts fish.

With the exception of the init process, *every single process* has a parent process, and has inherited the environment variables from its parent. Fish inherited the environment from the terminal, which inherited it from your desktop, which inherited it from something doing the login, which inherited it from....

And all of these processes can make changes to their environment and pass it on.

This is a fundamental unix idea.

**Comment by BarbzYHOOL** [comment]
thanks @faho I note it down
