### ISSUE TITLE
Package fish as a snap

### ISSUE THREAD

**Issue by Netanel-M** [fish-shell/fish-shell#9432]
Hi, this weekend I had some fun learning fish but noticed by package manager's version was too old for the documentation. My package manager(apt under pop-os) has version 3.3.1 and I wanted to use the latest (3.5.1 as of writing this ticket).

I used this as a good opportunity for me to learn to package with canonical's snap and [packaged fish as a simple classic mode unconfined snap.](https://github.com/Netanel-M/fish-snap)

I was wondering whether it is alright that I publish this snap so other people can use it to get the latest version.
Canonical requires explicit permission from the owner of the software, and additionally I know that some developers are not keen on snap at all. 
So let me know if it's fine for me to publish it. You can find the yaml specification in the link above.

If you are not familiar you can read more about snap [here](https://en.wikipedia.org/wiki/Snap_(software)).

**Comment by faho** [comment]
Fish is licensed under the GPLv2, you are allowed to do this.

Now, as far as I'm concerned: I don't enjoy snaps as a technology, I think Canonical has forced them on Ubuntu users and keeps, to my taste, a too tight grip on it (including the server). It has also been annoying for fish to deal with because e.g. Ubuntu has packaged firefox as a confined snap, which forbids it from accessing /tmp - this presents challenges for fish's webconfig tool.

I do not believe snaps are a good fit for a shell because one feature they want to push forward is sandboxing which makes exactly zero sense for a shell.

I also do not believe releasing a snap is all that helpful to actual users as we have [an official PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3) for Ubuntu and similar repositories for a variety of other distributions. You can probably also use this for Pop!_OS.

But, like I said: It's free and open source software, do what you want. If we get a bug report about it I'll probably ask people to try the deb package to rule out any issues.

**Comment by Netanel-M** [comment]
I hear you loud and clear. I will refrain from publishing it, as I do not want to offend.
I also agree with your criticism regarding canonical tight grip on snap.  The first thing I did was package fish with flatpak on my local machine (and I do prefer flatpak to snap), but as flatpak does not have an unconfined mode it makes little sense to use it with a shell.

**Comment by faho** [comment]
Last time I checked flatpak wasn't appropriate for a shell like fish because of the sandboxing, and I don't know what an "sdk extension" in this sense is.

To be honest these packaging formats are different enough from "classic" distro packages that it might be annoying to support from our end, and I would prefer they not be made by someone uninvolved with the project.
