### ISSUE TITLE
argparse: capture local $argv of calling scope

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#9441]
argparse is typically used like this:

```fish
function myfunc
    argparse a/alpha b/beta -- $argv
    . . .
end
```
argparse ought to only require the `--` sentinel followed by arguments if the user desires preparing some arguments for it to process.

With some improvements to the builtin the common case could be simplified to:

```fish
function myfunc
    argparse a/alpha b/beta
    . . .
end
```

The builtin just needs to, instead of erroring when a `--` is not encountered, make a closure over local $argv.

**Comment by faho** [comment]
That means this now silently does the wrong thing:

```fish
argparse $argv
```

**Comment by floam** [comment]
What is that supposed to do? `argparse $argv --`?

**Comment by faho** [comment]
Currently, when you do

```fish
argparse h/help f/foo b/bar $argv
```

that will error out telling you you need a `--`.

That means the easy mistake of forgetting the `--` isn't possible.

With your change, this instead parses like

```fish
argparse h/help f/foo b/bar $argv -- $argv
```

which parses $argv *with $argv as option specs too* (which *may* be invalid, but often won't be). That adds an opportunity for an easy to make but annoying to find mistake.

In exchange for a pure shortcut I do not believe that is worth it.

**Comment by floam** [comment]
Something else this could allow for - out of the scope of this request for comments - is argparse could, behind an option, remove the arguments from argv it has dealt with.

**Comment by faho** [comment]
>argparse could, behind an option, remove the arguments from argv it has dealt with

I'm sorry, I don't think I understand what you mean.

My best interpretation is something that argparse has always done.

When it is done, it saves all unprocessed arguments in $argv (and always $argv, no matter what arguments you give it):

```fish
argparse d/dir= h/help -- -d=foo pos --dir bar pos2
echo argv is $argv
```

prints "pos pos2". This isn't behind an option because argparse always did it that way.

**Comment by floam** [comment]
> When it is done, it saves all unprocessed arguments in $argv (and always $argv, no matter what arguments you give it):

I had no idea. That's exactly what I was going to suggest. That's actually kind of strange considering, but hey cool kinda. I do think a default of just assuming `argv` makes a little more sense in light of that information.

The goal is to simplify what is kind of a domain-specific language in the `argparse` incantation, one that most of the time is always the same, `--` `$argv` - the problem is I'm getting feedback that it's worth having a *required* `--` argument in light of the likelihood of `argparse flags $argv` being attempted.

**Comment by faho** [comment]
>I'm getting feedback that it's worth having a required -- argument in light of the likelihood of argparse flags $argv being attempted.

That is, in fact, the feedback you are getting, yes.

The fear is that this will confuse users and lead to a hard to diagnose but easy to make mistake, in trade-off for a minor convenience.

This is specifically likely because until now we're asking for the arguments to be explicitly given, and so if we removed that the user would only have to forget a `--` - which is already a thing that is constantly forgotten everywhere.

>The goal is to simplify what is kind of a domain-specific language in the argparse incantation

Semantically what you are asking for is "the `-- $argv` part is implied if not given". That means at very best you save the keystrokes `-- $argv`, while requiring users to remember that it'll read $argv, and making the above mistake possible.

That doesn't simplify, that complicates the DSL by introducing an additional special case!

**Comment by faho** [comment]
Okay, I'm gonna close this because it doesn't seem wise to me to allow an easy mistake to pass through in exchange for a minor shortcut.
