### ISSUE TITLE
Add conda env create and conda env list completions

### ISSUE THREAD

**Issue by jvanheugten** [fish-shell/fish-shell#9452]
fish version 3.5.1
OS: ubuntu

I'm trying to add extra functionality for completion of the `conda` package to https://github.com/fish-shell/fish-shell/blob/master/share/completions/conda.fish : 
* `conda env` (top level option)
* `conda env list` (option to List the environments) and `conda env create` (top level option to create new environment)
* `conda env create -f <file_search>` and `conda env create --file <file_search>` (create new environment using a requirements file and show filename completion)

I'd like to contribute, but I'm new to fish shell.
I tried to add this, and it almost works in `completions/conda.fish`, but not quite:
```
__fish_conda_top -a env -d "Conda options for environments"
__fish_conda env -a create -d "Create a new environment"
__fish_conda env -a list -d "List all conda environments"
__fish_conda env -a create -s f -l file -r -d "Create environment from yaml file"
```

The issue is I can't get the completion of the options to `create` to work correctly: `conda env create -<TAB>`. It shows all options from top-level conda instead of just `-f` or `--file`.
Also, completion of `conda env create <TAB>` will propose `list` or `create` again.

**Comment by faho** [comment]
Yeah, the conda completions are too naive.

>It shows all options from top-level conda instead of just -f or --file.

It actually doesn't offer "all" options for top-level conda. It shows all options for `conda create`, because the conda completions use the very simple `__fish_seen_subcommand_from`, which really only checks if the word appears. It has no idea if that word is the actual subcommand, because options - in `git -C log status` the subcommand is "status", the "log" is an argument to `-C`, and so it overmatches. For simpler completions this is okay.

This needs something more like [the git completions](https://github.com/fish-shell/fish-shell/blob/d2f5daf8e8985209ae34577c137b6077e1a57624/share/completions/git.fish#L561-L593) (except without the caching - for git that's needed because those completions are massive, for conda it won't be).

>Also, completion of conda env create <TAB> will propose list or create again.

Well, you didn't tell fish that it should only offer `create` if it hadn't been already. This needs an additional completion.

Lemme see if I can whip something up, this is slightly more advanced.

**Comment by faho** [comment]
Alright I added something and included a modified version of your env completions.

That should be an acceptable starting point (and yes, we are working on simplifying subcommand completions - #7107)

**Comment by jvanheugten** [comment]
Thank you for the solution. I'm reading through your adjustments to learn so hopefully can contribute next time.
