### ISSUE TITLE
Aliasing with sudo commands

### ISSUE THREAD

**Issue by TH3-S4LM0N** [fish-shell/fish-shell#9453]
version: `3.5.1`
os: Arch Linux
terminal: Alacritty

---------
I have various commands that require root (eg `pacman`) aliased to `sudo <command>`, but as it's being run by sudo, not the actual command, so tab completion doesn't work, same problem as #6899. My question is how would I create a function that would have the effect of what was proposed in #6899:
> The simple workaround is to actually make a proper function,  like
 ```fish
function ssh
    TERM=screen-256color command ssh $argv
end
```
but run with root perms instead of env vars?

```fish
function pacman 
    sudo command pacman $argv
end
```
gives `sudo: command: command not found`, since `command` is a shell function. (root runs bash)

**Comment by faho** [comment]
`sudo` is an external command and it won't run shell functions (or builtins, which `command` is).

So:

```fish
function pacman
    sudo pacman $argv
end
```

Note: I *heavily* recommend against naming this function the same thing. For pacman specifically, I know that it'll break the completions (because the completions do e.g. `pacman -Q` to list the installed packages to complete packages you could remove).

Just name it something else.

**Comment by faho** [comment]
Question has been answered, closing.
