### ISSUE TITLE
Please re-add global/universal abbreviations!

### ISSUE THREAD

**Issue by ajgringo619** [fish-shell/fish-shell#9471]
After upgrading to fish v3.6, this "feature" makes no sense. When trying to roll out custom environments on new systems, this causes me to jump through hoops I shouldn't have to.

Is my only solution to downgrade to v3.5.1?

**Comment by faho** [comment]
You can just add the abbreviations in config.fish or a file in conf.d. That should have about the same number of hoops as having it in fish_variables.

**Comment by faho** [comment]
Note: You are already being rude. I suggest you tone it down, or we will have to take moderation decisions as necessary.

**Comment by ajgringo619** [comment]
Sorry about my perceived tone; that was not my intention. After thinking about this issue for a bit, I think my number one concern was the lack of warning. `abbr -a -U` should have thrown an error, or at least a deprecation warning. I had no idea that this had changed until I switched to another terminal. `abbr --help` made no mention of the changes, either.

Your posted solution works, so thank you for that.

**Comment by 239** [comment]
So since 3.6.0 `abbr -a` does not save the abbreviations anymore? Where is this change documented and why are there no warnings about it?

**Comment by faho** [comment]
Have you checked [the CHANGELOG](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.rst#deprecations-and-removed-features-1):

> Abbreviations are no longer stored in universal variables. Existing universal abbreviations are still imported, but new abbreviations should be added to config.fish.

It also says so in the documentation, but arguably in 3.6.0 it was a bit unclear so we've clarified it.

**Comment by 239** [comment]
I have seen this in the log but I did not realize that `abbr` has no persistent way of adding/erasing. That would be clearer:
> abbreviations should be added/**deleted** in config.fish **manually**.
I doubt that many longtime users will read the log in detail and IMHO it still feels like two steps forward and one back.

**Comment by asportnoy** [comment]
@faho

In my opinion, one of the big benefits Fish has over other shells is being able to manage persistent things via commands without having to add them to  config file. For example, `set -U` and `funced --save`. Both of those can be listed and managed via commands and will persist across sessions, plus avoid having a long and unorganized config file (I know you can split it up into multiple files in `conf.d`, but still not ideal). Furthermore, they will apply instantly, so you don't need to start a new session or copy the command from your config file and run it yourself.

I think that removing the automatic, persistent management of aliases is a big step back from that. Especially since the new behavior was still possible before. It just seems like you removed a feature that was loved by many and replaced it with a worse option.

I would understand changing the default scope to local. That would be consistent with `set` and `funced`. But I don't understand the benefit of removing the _option_ to have them be universal. Leaving the option but making local the default seems like an approach that would make everyone happy.
