### ISSUE TITLE
Additional `PATH` directory entries randomly disappear between commands

### ISSUE THREAD

**Issue by zolrath** [fish-shell/fish-shell#9478]
## System Info
fish, version 3.6.0
WSL2 Ubuntu 22.04/macOS 13.1
[dotfiles](https://github.com/zolrath/dotfiles/tree/main/dot_config/private_fish)
This is reproducible on both my WSL install and macOS computer.

## Issue

It would seem that between commands my `PATH` loses the additional paths that have been added via `fish_add_path` in my `conf.d/paths.fish` file. Commands that are in paths that are added in my `conf.d/paths.fish` will randomly fail as their directory is suddenly no longer in `PATH`. While I am showing this issue with `lazygit`, it occurs with other commands as well and is not ex

## Random Failures
![image](https://user-images.githubusercontent.com/454563/212566037-4a406596-d2af-46d6-90d8-f49a97320f72.png)

## Normal Path
![image](https://user-images.githubusercontent.com/454563/212566122-4045e4b0-eb1b-42ec-8302-2fa5ca6eb77b.png)

## Broken path
When typing `lazygit` if the autocomplete is red, I can backspace and instead echo my `PATH` to see the additional entries are missing.
![image](https://user-images.githubusercontent.com/454563/212566127-fb8658f1-efe3-4886-98ac-5c1a067784b6.png)

**Comment by faho** [comment]
Think I found it. Try removing this line:

https://github.com/zolrath/dotfiles/blob/3125ec28768f044b52ab70bcf960826028b8a72b/dot_config/private_fish/conf.d/paths.fish#L1-L2

This file is executed *always* (well, unless run with `--no-config`). Fish runs its configuration *in all shells*, whether interactive or not, and it has a variable listener for $fish_user_paths, that removes directories from $PATH.

So, it stands to reason you have something that runs a separate fish process in the background, runs your config again and that erases $fish_user_paths, which is, since you haven't given a scope in `fish_add_path`, a *universal* variable.

Since it is a universal variable there really is no need to erase it. Alternatively use `fish_add_path -g` (at least for the first call).

**Comment by zolrath** [comment]
Ahh I see, that worked! 
Thank you very much for both the fix and the explanation!
