### ISSUE TITLE
Ctrl+g should quits the history search

### ISSUE THREAD

**Issue by pierrelegall** [fish-shell/fish-shell#9484]
In the new history search of Fish 3.6, `Ctrl+g` do nothing. However, in shells like Bash or Zsh, it quits the history search.

If fact, `Ctrl+j` already do the job. But you know, muscle memory...

### Current behavior

`Ctrl+g` do nothing in the history search.

### Expected behavior

`Ctrl+g` quits the history search.

### Congrats

Fish version 3.6 is awesome, good job to the team!

**Comment by krobelus** [comment]
I think Escape (or `Control-[`) has this behavior - it restores the command before history search (or are you looking to keep the search query?)
Today you can add a binding using `bind \cg cancel`.
I'm sympathetic towards adding this binding by default because it's a well-known Emacs chord.

> If fact, Ctrl+j already do the job

this does something slightly different, it accepts the selected history item

**Comment by pierrelegall** [comment]
Same behavior as Escape is perfect from my point of view ;)
