### ISSUE TITLE
Plugins Missing After Restart Terminal

### ISSUE THREAD

**Issue by ajmeireles** [fish-shell/fish-shell#9491]
Hello!

I'm having a strange problem. Whenever I install a plugin it gets removed when I restart the terminal. I'm installing the plugin: https://github.com/jhillyerd/plugin-git and when I close the terminal it doesn't exist anymore in the abbreviations, and I need to install again (using Fisher) or make a update: `fisher update`

What am I doing wrong?

Fish Version: 3.6.0
System: Ubuntu 22.10

**Comment by faho** [comment]
This plugin stores abbreviations in universal variables. That no longer works since the recent update to abbreviations.

What it does would *almost* work, except it [checks a universal variable as a shortcut](https://github.com/jhillyerd/plugin-git/blob/a7bf861097d34f4db0fd7384bc19c712148feb55/functions/__git.init.fish#L9).

It needs to be updated, by removing that line. Or, if they want to support older fish versions, they can do this instead:

```fish
not builtin -q abbr
and set -q __git_plugin_initialized; and return 0
```

What you can do is to just remove the variable and run the initialization again:

```fish
set -e __git_plugin_initialized
__git.init
```

or run their `__git.reset` function, which after a few layers of indirection does essentially the same thing.

I'm going to close this as a bug in that plugin.
