### ISSUE TITLE
Just ">" for a specific folder after a wrong command

### ISSUE THREAD

**Issue by hrakotonarivobocasay** [fish-shell/fish-shell#9494]
**fish, version 3.1.0 (starship theme)**
**OS : Ubuntu 20.04**
**Terminal :** Guake / Default terminal
**Problem:** 
I actually have this in juste one specific folder
![image](https://user-images.githubusercontent.com/88330691/213392365-c698d3bd-b91d-41ce-8230-8b110f2b46fb.png)

**Instead of**
![image](https://user-images.githubusercontent.com/88330691/213392631-8b2d9799-75dc-42ce-abc8-06b51be05443.png)

This after a bad command I think, I wanted to type "clear" but I had to type "lear" or something like that I don't remember exactly. So for the file that was in progress, I still have this problem even when leaving the terminals (no problem with bash).

Any idea to fix ?

Thanks

**Comment by faho** [comment]
>fish, version 3.1.0 (starship theme)

Fish 3.1.0 is 2 years and five minor releases out of date. It's not even the newest release in the 3.1 branch, that's 3.1.2 (for some reason Ubuntu never even updated *that*).

It is missing 31.1% of all commits made to fish, and as such we no longer support it.

Please try again with fish 3.6.0, we offer PPAs at https://fishshell.com/.

----

Concerning your problem: We are unlikely to find something to help because it's not even clear what you *did*. You don't know what you executed, so anything could have happened. You could have executed a script or a command that ended up changing your configuration or removing files.

I can offer you some ideas, but you'll have to do the debugging work yourself.

What you want to do is to figure out what is working - are you still running *fish*? E.g. try `echo $version`. Does that print the fish version? Does running `fish` fix anything? *Can* you even run commands? Maybe your configuration got broken - try `mv ~/.config/fish ~/.config/fish-bak`.

Is the issue just starship? What happens if you run `function fish_prompt; echo $PWD '$'; end`? Does your prompt change to that?

**Comment by hrakotonarivobocasay** [comment]
Hi @faho 

Thank you for your response. 

Finally fixed after apt upgrade.
