### ISSUE TITLE
Add Fossil support to fish_vcs_prompt

### ISSUE THREAD

**Issue by nat-418** [fish-shell/fish-shell#9497]
Currently, fossil-scm is supported for fish completions, but not in, e.g., the informative-vcs prompt.

fish, version 3.5.1
Linux laptop 5.15.86 #1-NixOS SMP Sat Dec 31 12:14:48 UTC 2022 x86_64 GNU/Linux
xterm-256color
I tried running fish without third-party customizations and it did not affect behavior.

To reproduce, type `fish_vcs_prompt` in a fossil repository checkout directory.

**Comment by faho** [comment]
This is a textbook example of "patches welcome". We're gonna need someone who knows fossil to write something.

**Comment by nat-418** [comment]
I am working on it. For now I am still trying to figure out how fish_vcs_prompt works. Adding support for Fossil should be pretty easy given that we have `fossil info` and `fossil status` that give us all the information we need in a simple key-value format.

**Comment by faho** [comment]
`fish_vcs_prompt` is just a cover function that goes through all the known vcsen.

It simply calls `fish_git_prompt` for git and `fish_hg_prompt` for mercurial.

What you want is this:

A file called `fish_fossil_prompt.fish`, with a function called `fish_fossil_prompt` (i.e. the same name as the file, no .fish ending) that functions as the entry point. You can add more functions inside the file, but that is the one that ends up being called.

Then, you want the function to at the very least have this:

```fish
function fish_fossil_prompt
    if not type -q fossil
        # no fossil installed, we gracefully fail
        return 127
    end
    
    # do whatever to get the fossil info
    set -l info (fossil info)
    # *jazz hands* MAGIC */jazz hands*

    echo -- $fossil_branch $fossil_repostate # I don't know fossil, put whatever useful info here
end
```

You basically want to look at the [hg prompt](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_hg_prompt.fish), not the git one because that's overly complicated for legacy reasons (especially the fifty million configuration variables it exposes).

If this prompt is fast enough, we can add it to fish_vcs_prompt to enable it by default. It especially needs to be *very quick* (on the order of single-digit milliseconds) outside of a fossil repo, even if fossil is installed.

If fossil itself is slow at figuring out if it is a fossil repo or not, you can do [what the hg prompt does](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_print_hg_root.fish) (mercurial is quite slow in starting up, so we don't want to pay that cost for everyone on every prompt), and figure it out yourself (mercurial looks for a ".hg" directory with a "dirstate" file IIRC).

If it still isn't fast enough, we can accept it like the svn prompt - as off by default.
