### ISSUE TITLE
-exec not working in find

### ISSUE THREAD

**Issue by torifat** [fish-shell/fish-shell#95]
I tried to use-
`find . -type f -name "*.mp3" -exec mv {} . /;`

But, it is saying that `mv` can not find the file.

I switched to `bash` and it worked there.

Although, this is working just fine-
`find . -type f -name "*.mp3"`

I also tried to do the following but with no luck-
`find /full/path -type f -name "*.mp3" -exec mv {} . /;`

**Comment by stephane-chazelas** [comment]
Note that brace expansion was introduced by csh. Csh (back in the end of the 70s) explicitly made a documented special case for `{}` alone to be left alone (though `{}foo` would expand to `foo`).

All other shells that implemented brace expansion thereafter (tcsh, ksh, zsh, bash, yash at least)  copied that behaviour (except for the `{}foo` -> `foo` part).


I can't imagine anyone relying on `{}` expanding to an empty argument. I'd expect people would use `''` or `""` for that instead, so I don't expect aligning with other shells would break anything.


<sup>`rc` is another shell where `{}` needs to be quoted, but that's not for brace expansion there (`{` and `}` are used in the syntax of the language).</sup>

**Comment by faho** [comment]
>spam? one message is not spam

@BarbzYHOOL:

Sorry, that came on much stronger than I intended.

What I meant was that this issue is _quite_ old, so resurrecting it isn't really all that great.

>I feel like opening a new issue to ask this question is way more spammy (and time wasting :P)

I _would_ actually prefer a new issue over random questions all over the place. When an issue is still "hot", as in it is either open or has been closed semi-recently, or when your question is "why does the enhancement that was added here not work for me", then it's alright to reuse an existing issue.

But when it's essentially a request to rethink something that was closed years ago, then a new issue is the right way to go.

Either that, or try gitter.im/fish-shell/fish-shell first.
