### ISSUE TITLE
commandline --line always reports 1

### ISSUE THREAD

**Issue by JanDeDobbeleer** [fish-shell/fish-shell#9507]
Using fish 3.5.1 it seems that `commandline --line` always returns 1. Maybe I'm misinterpreting what it does, my expectation is that it returns the line we're on in the console buffer with the first line starting at 1. I'm seeing the same issue with `commandline --cursor` that always returns 0. The behaviour is the same regardless of where I execute this command.

**Comment by faho** [comment]
It reports where on the line the cursor currently is. That means it only really makes sense when run from a binding. E.g. bind ctrl-g to print it:

```fish
bind \cg 'commandline --line >&2'
```

Now enter, interactively:

```fish
if true
    echo 
```

and press ctrl-g, you'll see a "2" appear. Do the same with `commandline --cursor` and you'll see some other number appear.

Of course when you execute it as a command in the commandline it won't give sensible results, but that's of course because, well, you aren't in the process of editing a commandline.

**Comment by JanDeDobbeleer** [comment]
@faho ok, makes sense thanks! In that case I have to find another way to get that information.
