### ISSUE TITLE
Following build instructions for debian results in cmake failing to finish execution successfully.

### ISSUE THREAD

**Issue by anakimluke** [fish-shell/fish-shell#9511]
I followed the steps on a debian 11 VM, so it should be easier to reproduce.

First, I followed the build instructions normally:

```sh
git clone https://github.com/fish-shell/fish-shell
cd fish-shell
mkdir build; cd build
cmake ..
```
It complained about not finding ncurses, so I proceeded to installing the suggested packages on the instructions page:

```sh
sudo apt install build-essential cmake ncurses-dev libncurses5-dev libpcre2-dev gettext
cmake ..
```
Got error:
```
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_policy):
  The OLD behavior for policy CMP0066 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Setting build type to default 'RelWithDebInfo'
-- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
-- Fetching and configuring PCRE2 from https://github.com/PCRE2Project/pcre2.git
-- Populating pcre2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/myuser/fish-shell/build/_deps/pcre2-subbuild
[ 11%] Performing update step for 'pcre2-populate'
[ 22%] No patch step for 'pcre2-populate'
[ 33%] No configure step for 'pcre2-populate'
[ 44%] No build step for 'pcre2-populate'
[ 55%] No install step for 'pcre2-populate'
[ 66%] No test step for 'pcre2-populate'
[ 77%] Completed 'pcre2-populate'
[100%] Built target pcre2-populate
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could not find OPTIONAL package Readline
-- Could not find OPTIONAL package Editline
CMake Error at build/_deps/pcre2-src/CMakeLists.txt:314 (MESSAGE):
  At least one of PCRE2_BUILD_PCRE2_8, PCRE2_BUILD_PCRE2_16 or
  PCRE2_BUILD_PCRE2_32 must be enabled


-- Configuring incomplete, errors occurred!
See also "/home/myuser/fish-shell/build/CMakeFiles/CMakeOutput.log".
See also "/home/myuser/fish-shell/build/CMakeFiles/CMakeError.log".
```

It also errors out if I try to use the system installation of pcre2, running with `cmake .. -D FISH_USE_SYSTEM_PCRE2=ON`:

```
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_policy):
  The OLD behavior for policy CMP0066 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Setting build type to default 'RelWithDebInfo'
-- Using system PCRE2 library /usr/include
CMake Deprecation Warning at cmake/Tests.cmake:48 (cmake_policy):
  The OLD behavior for policy CMP0037 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:204 (include)


-- The following OPTIONAL packages have been found:

 * Curses

-- The following REQUIRED packages have been found:

 * Threads

-- The following features have been disabled:

 * gettext, translate messages with gettext
 * Documentation, user manual and documentation

-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SYS_PCRE2_LIB
    linked by target "fishlib" in directory /home/myuser/fish-shell

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

```

Btw, thanks for work on making this shell!! I like it very much :3

**Comment by faho** [comment]
I can't reproduce.

What happens for you is:

1. cmake can't find your pcre2 installation
2. it tries to build pcre2 before building fish
3. that fails

I can't reproduce the first part. I have just downloaded a debian 11 iso, installed it onto a vm, run that exact apt invocation and built fish from the 3.6.0 tarball.

It found the system pcre2 and compiled. The pcre2 packages that were installed as a result of that invocation: libpcre2-16-0 libpcre2-32-0 libpcre2-dev libpcre2-posix2.

With those, running `mkdir build; cd build; cmake ..; make` compiled fish against the system pcre2. It did not try to build pcre2. The compiled fish runs.

If I explicitly tell it to build its own pcre2 with `-DFISH_USE_SYSTEM_PCRE2=OFF`, it downloads and builds that (but requires git to do so).

So it stands to reason that your system is configured differently.

Getting down to it, compiling pcre2 fails for you because it fails to select the appropriate width - it needs to be built with the appropriate wchar_t width. In our case, we select that simply from the WCHAR_T_BITS macro, which on linux should typically be "32":

https://github.com/fish-shell/fish-shell/blob/7f2cb474373bcedfc6f56836ef7bcb492737ecdf/cmake/PCRE2.cmake#L2-L4

However, this is secondary. Ideally, it would simply find your pcre2 package, and you should try to find out why it doesn't.

>It also errors out if I try to use the system installation of pcre2, running with cmake .. -D FISH_USE_SYSTEM_PCRE2=ON:

Using the system pcre2 is *the default*, if possible. What this does is simply forbid it from even trying to build pcre2, so it's not surprising that this doesn't work - it never found pcre2!

**Comment by anakimluke** [comment]
After some investigating, I found the problem: I was running cmake on a dirty `build` directory. Removing all files from the directory and running cmake again makes it work as expected. You didn't get the error probably because you installed the dependencies before trying to run cmake.

Is this a bug or is it expected behaviour?

**Comment by faho** [comment]
That's how cmake works.
