### ISSUE TITLE
complete.cpp does not parse PATH directories with parenthesis correctly.

### ISSUE THREAD

**Issue by Forethinker** [fish-shell/fish-shell#952]
I am having this problem in Windows, but I have a feeling it will happen in other OS as well.
When I try to autocomplete any command, I get the following message 11 times:

    fish: The file 'x86' is not executable by this user
    in command substitution
            called on standard input,

This corresponds to the number of directory that includes "Program Files (x86)" in PATH.

I have no trouble running binaries in these directories. For example, firefox is correctly identified as a binary and I can execute it, even though it is in '/cygdrive/c/Program Files (x86)/Mozilla Firefox/firefox.exe'.

**Comment by oysteinkrog** [comment]
Also seeing this.

**Comment by faho** [comment]
Is this an issue in complete.cpp or actually in the completion scripts, especially "cd"s (hint: #2289)?

I've just tried

```fish
mkdir "Program Files (x86)"
cd Prog<TAB>
```

(with that PR applied)

and it worked.

**Comment by ridiculousfish** [comment]
Yay!

**Comment by zanchey** [comment]
This still isn't fixed:

```fish
mkdir -p ~/\(blah\)
ln -s /bin/tar ~/\(blah\)/somenewcommand
set -gx PATH ~/\(blah\) $PATH
```

Then type `somenew` and hit Tab.

```
fish: Unknown command 'blah'
in command substitution
        called on standard input
```

**Comment by jrobeson** [comment]
this issue would apply to wine users on OSX and linux as well.

**Comment by krader1961** [comment]
If no one else is working on fixing this I'll take a stab at it.

**Comment by justinmayer** [comment]
That would be great, Kurtis. Much appreciated!

**Comment by zanchey** [comment]
There are concerns (many thanks to Josh for raising them) that this can be used to cause privilege escalation or arbitrary code execution for other users.

Since the `cd` completion has been fixed to avoid `eval`, I haven't managed to reproduce a similar problem without adding a directory with brackets to the path; if you can convince someone to do `set PATH /(rm -rf /)` then I suspect you can convince them to run arbitrary code regardless.

I thought about trying to add a symlink to a bracket-containing directory to the path, but the symlink is not derefenced so that can't be used.

**Comment by zanchey** [comment]
In other words, although I think a definitive fix would be great, I don't think this needs to block 2.3.0.

**Comment by ridiculousfish** [comment]
Thanks zanchey. I'll also look to see how feasible a fix is.

**Comment by floam** [comment]
> if you can convince someone to do set PATH /(rm -rf /) 
Or do [basically anything](http://thejh.net/misc/website-terminal-copy-paste).

**Comment by floam** [comment]
(bracketed paste can help with that trick, I think)

**Comment by ridiculousfish** [comment]
I have a fix for this in #2912. It's nice because it unifies completions for commands (which need to respect PATH) with those for cd (which respect CDPATH). @krader1961 (or anyone) do you want to review?

**Comment by krader1961** [comment]
The change proposed by @ridiculousfish fixes the core issue. But, FWIW, other problems remain. For example, my `$CDPATH` contains the parent directory where I keep all the third-party projects I track. If I `cd ~/tmp` and type `cd ./fish` followed by [tab] it still enumerates the two fish directories in my third-party tree. Since that happens with and without the aforementioned change I recommend it be merged. We can tackle the other unexpected behaviors in a separate issue if anyone is bothered by them.

**Comment by ridiculousfish** [comment]
@krader1961 that problem is due to `__fish_complete_cd`. We might consider just removing `__fish_complete_cd`, since the C++ one should be pretty good.

**Comment by faho** [comment]
@krader1961: Should be fixed in d7c690b.

>We might consider just removing __fish_complete_cd, since the C++ one should be pretty good.

Do we already have a C++ completion for enterable directories that takes into account $CDPATH?

**Comment by ridiculousfish** [comment]
Yes - the logic is there to service the autosuggestion.

**Comment by krader1961** [comment]
FWIW, @faho's change fixed the `cd ./fish[tab]` problem I noted. I also removed the *share/completions/cd.fish* file from my system and didn't notice any ill effects. So, as @ridiculousfish, suggested it might be a good idea to simply remove the `__fish_complete_cd` function.
