### ISSUE TITLE
Error while using fish command on windows

### ISSUE THREAD

**Issue by mohamedmehdigara** [fish-shell/fish-shell#9529]
**fish command not recognized**

**Comment by faho** [comment]
I'm sorry, we are gonna need a *lot* more context than that.

How did you install fish? Cygwin or WSL? Where and how are you trying to run fish? What is the exact error message and which program prints it?

**Comment by mohamedmehdigara** [comment]
Hi. How to install fish with npm?

**Comment by faho** [comment]
You don't install fish with npm.

Fish is not a node package and so it is not available on npm.

**Comment by faho** [comment]
I will leave you with a link to https://fishshell.com/, where you can find ways to install fish in cygwin, msys2 or WSL.

It is not a native windows program so it needs one of these linux compatibility layers. You would need to use one of them.

If you have any further questions you can ask them here, but I would recommend that you first read a bit and try to see what you actually *want*, because it seems like you came here immediately after finding out that fish is some sort of software that one might install.
