### ISSUE TITLE
Add -f/--force flag to fish_add_path

### ISSUE THREAD

**Issue by adamhl8** [fish-shell/fish-shell#9549]
This is a duplicate of #8386 but I wanted to open up this topic to some discussion. I think there should be a way to force `fish_add_path` to add a path even if the path doesn't exist. 

Just as an example, I have a script that bootstraps my development environment and expects a certain directory to be on my path. So in my `config.fish` I have:

```
fish_add_path ~/some_dir
```

`some_dir` does not initially exist but my script creates it, places some executables in it, and runs those executables. Running my script fails because at the time `fish_add_path` runs the directory didn't exist.

Obviously the solution is to just create the directory first or do something like `set -Ua fish_user_paths ~/some_dir`, but the nice thing about `fish_add_path` is that it won't add duplicates so it makes scripts much cleaner/simpler.

So to be clear, the `-f/--force` flag would be to force adding a path even if the directory doesn't exist, but still do nothing if it's a duplicate.

**Comment by faho** [comment]
`fish_add_path` is a simple tool for simple purposes.

Complicating it with even more options is contrary to its purpose.

Just add the paths yourself:

```fish
contains -- ~/some_dir $fish_user_paths
or set -Ua fish_user_paths ~/some_dir
```

**Comment by mattmc3** [comment]
Just a note for future Fish users searching for how to "force" `fish_add_path` to do what you want (since I myself just had to search for this):

The `-m/--move` flag for `fish_add_path` also works like a `-f/--force` flag might, in that the default behavior for `fish_add_path --prepend` will be a no-op for anything that's in `$PATH` already. That's not helpful if you want to force a prepend. For example, I have a `prepath` variable with directories that I want to always be at the front of $PATH, and I want that to happen even if they are already in `$PATH`. `-m/--move` makes that possible:

```
set -q prepath && fish_add_path --move --prepend $prepath
```

I know your question is about force-adding non-existent directories, but I figured I'd comment as well to catch anyone else asking how to force `fish_add_path` to work.
