### ISSUE TITLE
Fish doesn't load functions that are in a subdirectory in functions/

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#9624]
fish 3.3.1

I have several functions in a custom directory `.config/fish/functions/local_only/` but they are not loaded. Is it normal? what can I do and how? or should i just (finally) upgrade to the newer fish shell and it will solve all my problems?

thanks

**Comment by faho** [comment]
>Is it normal?

Yes, this is normal.

>what can I do and how?

Either don't use a subdirectory or add the subdirectory itself to $fish_function_path:

```fish
set -p fish_function_path ~/.config/fish/functions/local_only
```

>or should i just (finally) upgrade to the newer fish shell and it will solve all my problems?

We would always recommend upgrading, but it won't have any changes in this area and I don't think we want to change this.

**Comment by BarbzYHOOL** [comment]
> Either don't use a subdirectory or add the subdirectory itself to $fish_function_path:

There is no issue with adding it to the fish function path, right? I can do this fine? (it's always better to organize your files hehe)

**Comment by ridiculousfish** [comment]
Yes you should be able to add a subdirectory to `fish_function_path`, if that doesn't work then it's a bug.

**Comment by faho** [comment]
>There is no issue with adding it to the fish function path, right?

It will be added as another lookup directory, and functions will be found there, too.

They will still only be looked up by the name of the function - if you have a function `foo` in a file called foo.fish in ~/.config/fish/functions/ and in ~/.config/fish/functions/local_only/, it will be found if you run `foo`, and it will be found in whichever of these directories is first in $fish_function_path.

It's fundamentally a flat namespace, you can't call functions as e.g. `local_only/foo` because that looks like a relative path and will try to run the *command* found in $PWD/local_only/foo. That's also why I don't believe

>it's always better to organize your files hehe

because now "foo.fish" can be in either directory and to figure out which foo.fish is actually read you need to order them by directory.

If you have a specific need to make a directory, e.g. because you share this one among multiple machines but not that one, you can make a directory. But just for "organization" I wouldn't actually recommend it, because it just makes it harder to find your functions.

**Comment by BarbzYHOOL** [comment]
thanks, gonna try

I'm not the type of person who gives the same name to functions/files anyway ^

**Comment by BarbzYHOOL** [comment]
I added it twice, how do I remove one occurrence?

**Comment by zanchey** [comment]
`set --erase fish_function_path[1]` or whatever the index of the duplicate entry is will do it.

I'd add `set -p fish_function_path ~/.config/fish/functions/local_only` to your `config.fish` to make it permanent.

**Comment by BarbzYHOOL** [comment]
how do you know what is the index easily? if there are many entries

**Comment by ridiculousfish** [comment]
`set --show fish_function_path` if you're doing it manually will show you the values and their indexes.

Our [gitter chat room](https://gitter.im/fish-shell/fish-shell) is a better place for asking for help.

**Comment by faho** [comment]
Okay, I'm gonna call this question answered.

**Comment by BarbzYHOOL** [comment]
thanks!
