### ISSUE TITLE
[fish_indent] Support indention using tabs

### ISSUE THREAD

**Issue by d12bb** [fish-shell/fish-shell#9633]
I don't want to start the old war again here, but for users preferring ~~a superior style of indention~~ to use tabs, I propose `fish_indent` should at least provide a flag to not convert these precious tabs to spaces again.

**Comment by faho** [comment]
No.

This is on purpose, we only support one style so there is no quibbling about which options you should enable.

**Comment by d12bb** [comment]
Sorry, searched only issues, not PRs for duplicates before. I apologize.

**Comment by faho** [comment]
Sorry, it appears my message wasn't sent.

Tabs are a terrible solution *for fish* - you can't input tabs in the reader (because tab completes), tabstops are a massive pain for width calculations, tabstops default to 8 which is extremely wide.

More than that switching to tabs would be a massive change in style and would require reformatting *everything that has ever been formatted with fish_indent*.

Switching to tabs is a bad idea, adding style options is a bad idea. If you need to use tabs use expand/unexpand. That is what they are made for.

Sorry if fish_indent is not your preferred style, you are free to format your own code differently. I think this discussion has been had.
