### ISSUE TITLE
Setting fish shell as default cause login loop

### ISSUE THREAD

**Issue by DawidekM** [fish-shell/fish-shell#9639]
Hi, having some weird issue

While I set up fish to be default shell (by adding 'exec fish' to ~/.bashrc) it cause login loop after rebooting. On Wayland I'm going back to login screen immediately, on Xorg having black screen for a second and there go back to login. If i delete this line from tty i can log in without any trouble. 

OS: Nobara Linux 37 (Based on Fedora 37)
Fish version: 3.6.0
Terminal: Gnome Terminal
Display Manager: GDM

**Comment by faho** [comment]
This was reported to GDM as https://gitlab.gnome.org/GNOME/gdm/-/issues/556, and they rejected it.

GNOME upstream recommends you use `chsh` instead because the typical Xorg workarounds like `[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] || exec fish` don't work with how they set up wayland.

I don't think there is anything we can do here, unfortunately.
