### ISSUE TITLE
Executing 'fish' command in programs will close without any message and return 127

### ISSUE THREAD

**Issue by werifu** [fish-shell/fish-shell#9685]
### My environment:
```shell
> fish --version
fish, version 3.6.1

> uname -a
Darwin myMacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64

>echo $TERM
xterm-256color
```

### problem

When I execute 'fish' command programmatically, there will be no any message like "Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish" which is shown in real shell but only exit with a code of 127.

For example, I run 'fish' in Node.js:

```javascript
import { spawn } from 'child_process';
const shell = spawn('fish', []);
shell.on('close', (data) => {
  console.log('close', data);
});
shell.stdout.on('data', (data) => { 
  console.log('data', data.toString());
});
shell.stdin.write('echo "hello world"\n');
```

and I will only get an output of `close 127` which is triggered by shell.on('close'). However, if I run 'zsh' or 'bash' instead of 'fish', I will get `data hello world` and the process does not exit.

I also try this using Rust:

```rust
use std::process::Command;

fn main() {
    let output = Command::new("fish")
        .arg("-i")
        .output()
        .unwrap();

    println!("{}", String::from_utf8_lossy(&output.stdout));
}

```
But nothing happens.

If I run `cargo run` in fish while replacing the `new("fish")` to `new("zsh")`, it will change the current shell to zsh, while still in zsh if I run this program in zsh and using `new("fish")`.

I don't know why this happens.

ps: I have run `sh -c 'env HOME=$(mktemp -d) fish'` before reporting, which did not change the result

**Comment by faho** [comment]
You've not actually connected the streams correctly.

In your npm example: stdout is not a terminal, stdin is a directory (no idea how that happens) and fish has no commands to run. So it quits.

In addition, this way of running fish won't really work because, unlike other shells, fish reads the entire input file before running, so it doesn't run broken files.

>When I execute 'fish' command programmatically, there will be no any message like "Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish" which is shown in real shell but only exit with a code of 127.

That message is only shown if fish is actually interactive.

So you'll have to connect a terminal. To do it programmatically, use a pty.

**Comment by werifu** [comment]
Thanks for your answer! 
> To do it programmatically, use a pty.

useful for me
