### ISSUE TITLE
doesn't build on NetBSD 6

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#969]
On the mailing list, [William Ross reports that the build of fish fails](http://sourceforge.net/mailarchive/message.php?msg_id=31222280); this is due to `tparm()` taking a `char*` on Linux/FreeBSD, and a `const char*` on NetBSD.

We already hack around something similar in iconv on FreeBSD, so perhaps we can do the same for NetBSD.

**Comment by floam** [comment]
NetBSD build works on https://github.com/floam/fish-shell/commit/e2c231cad75db627f2e005e5a696f991e012728f - I need to figure out the right way to unbreak it it with regular tparm though. What's the proper way to hack around that?

**Comment by zanchey** [comment]
There's a lot of changes in that commit, but basically it looks like `#define tparm tiparm`?

**Comment by floam** [comment]
> There's a lot of changes in that commit, but basically it looks like #define tparm tiparm?
To summarize the commit? For NetBSD, it does that, then the necessary `const char *`'ing on things until it can compile successfully because of NetBSD's tiparm using const char's and everyone else just using char pointers. (And then, dealing with the ramifications of having their term.h included: the renaming of a few variables that began conflicting with macros,)

It doesn't yet work on Linux or OS X (unless you [sabotage Linux](https://github.com/sabotage-linux/netbsd-curses), I suppose...) and is just the minimal work necessary to make it compile and run with clang on NetBSD 7 (no `-fpermissive` anymore.).

**Comment by zanchey** [comment]
Right, according to the manual page `tparm` on NetBSD does actually take varargs, so you might be able to get away without that - but it's the `const char` business that gets tricky. Probably the way to make it work is write a configure test then use that to create a typedef, but I'll defer to those with greater C knowledge.

**Comment by floam** [comment]
Not in my manual or term.h.

**Comment by floam** [comment]
```
     char * tparm(const char *cm, long p1, long p2, long p3, long p4, long p5,
         long p6, long p7, long p8, long p9);
```

**Comment by zanchey** [comment]
Apologies - I may have misread.

**Comment by floam** [comment]
Wait. This is in my term.h.

/* Default to X/Open tparm, but allow it to be variadic also */

#ifdef TPARM_VARARGS

#  define tparm tiparm

#  define ti_parm ti_tiparm

#endif

**Comment by faho** [comment]
It builds on NetBSD 8 now, and the tparm changes should also be alright for 6.
