### ISSUE TITLE
Undesired behaviour when using eval inside a postexec hook

### ISSUE THREAD

**Issue by 1412031** [fish-shell/fish-shell#9749]
https://asciinema.org/a/5jJpvxoPJpIkcpWrVwRX3sZlE

Hello, I've written this function 
```fish
function hook__update_last_cmd_output --on-event fish_postexec
    eval $argv | string collect | read -zU last_cmd_output
end
```

In case I'm not missing anything it shouldn't require a ctrl+c after exiting a command like vim.

**Comment by faho** [comment]
Uuuhhhh... this won't do what you want it to.

This will run a second vim, with its output connected to a pipe instead of the terminal, and that's why it'll need a ctrl-c.

This doesn't work, and can not work, because you fundamentally run the command again. If you want the last command's output, you need support from your terminal to do so, fish can't help you. And the bad news is I don't know any terminal that does this.

**Comment by 1412031** [comment]
Yes I see your point, you're right, thanks for the prompt response.

Let me know if a new feature request issue requesting a feature as with the following summary makes sense and if it looks like something you'd like to implement.

_Add a global variable (possibly a list akin to history), or a new status subcommand where fish will store and display the output of the last command where applicable._

**Comment by zanchey** [comment]
That's not possible without significant interference in the way that terminal-based programs work (and therefore very brittle, non-portable etc), so we won't be doing that.

**Comment by zanchey** [comment]
see #2644

**Comment by 1412031** [comment]
> see #2644

Interesting, thanks for the reference.

**Comment by faho** [comment]
Alright, I think that's the answer then - this simply can't work.
