### ISSUE TITLE
'$' char in grep expression prevents execution

### ISSUE THREAD

**Issue by tjcelaya** [fish-shell/fish-shell#975]
Was attempting to execute this one-liner 

```
ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
```

when I get this error: 

```
fish: Did you mean (COMMAND)? In fish, the â$âhelp expand-command-substitutionâ
```

(I suppose the garbled message is due to my shell's encoding, but that's my own problem). I fixed it by changing the grep expression to 

```
ls -R | grep "^\." | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
```

so it seems like its the first end-of-line expression breaking it, but the second one passes just fine.

**Comment by Gastove** [comment]
This is surely a mis-understanding along the above lines, but I'm hitting something very similar:

```
$ echo '$cow$ chow' | string split ' '
$cow$
chow
```

Great. Single-quote working as expected. But:
```
$ echo '$cow$ chow' | string split ' ' | grep -v '$cow$'
$cow$
chow
```

On the other hand:
```
$ echo '$cow$ chow' | string split ' ' | grep -v '\$cow\$'
chow
```

Just to scope the question a bit better, I've hit this trying to filter out lines containing `$folder$` from a long file -- `echo/string split` just make an easier reproduction. 

So. Similar misunderstanding? Expected behavior? New/different thing that should have its own issue?

**Comment by faho** [comment]
@Gastove:

>Similar misunderstanding?

Basically, yes.

>Expected behavior?

Yes. The problem here isn't fish at all. Your grep receives `$cow$` exactly. Only it then interprets it as a regular expression - in which `$` usually means "end of the line". And since it then matches that expression against each line, and each line can only have one end, it won't work.

If you want to match certain characters that have a meaning in regular expressions literally with grep (or `string match -r`), you'll have to escape them - not for _fish_, but for the tool that uses the regular expression. This applies to `$`, it applies to `.`, `*` and a bunch of other characters. 

Which exactly depends on the particular tool and the regular expression dialect it uses - grep tends to read things as literal by default, while our `string` (which is built on the pcre2 library) prefers to read characters as special by default.

Alternatively, you can use `grep -F` (or the alias `fgrep`), which interprets the pattern as a literal string instead of a regular expression.

**Comment by Gastove** [comment]
@faho AH. Yeah okay, that does make sense -- I had gotten it in to my head that grep, by default, doesn't interpret regex characters, but that is, uh, definitely wrong. Memory is silly.

Thanks so much for the time and the thoughtful explanation! And thanks for fishshell, which is 💯
