### ISSUE TITLE
Current working directory in Fish prompt is omitted

### ISSUE THREAD

**Issue by Silverbullet069** [fish-shell/fish-shell#9780]
Hi, I'm currently using Fish Shell as my main working shell for a month. I've found out that if the current working directory is too long, Fish Shell automatically omits it. How can I turn off this feature?

I'm currently using Fish v3.6.1 in Git Bash on Windows (don't ask why, I'm just into Windows :3)

Nothing's here:
![1-nothing](https://user-images.githubusercontent.com/80348187/236791455-1c45b789-988d-467b-81ab-6d5c9d1185ba.jpg)

Current working directory:
![2-current-working-directory-length](https://user-images.githubusercontent.com/80348187/236792125-3fce43b7-575f-4847-9d8a-35bf8d725f84.jpg)

If shorter, it's back:
![3-it-s-backed](https://user-images.githubusercontent.com/80348187/236791464-ea4e0964-ad74-425b-9afe-037380418277.jpg)

**Comment by faho** [comment]
This depends on your fish_prompt function. Check how that prints your pwd. This isn't one of ours, we don't use directory symbols like that (because they are non-standard).

Fish will truncate lines that are too long, but you should see a ".../foo" in that case, so the most likely cause is your prompt (or "theme" as some call it) omits it.

**Comment by Silverbullet069** [comment]
@faho Yep, this is the behavior of @IlanCosman/Tide custom prompt/theme. I've check the ```fish_prompt``` written by his contributors and damn... couldn't understand a thing...

**Comment by faho** [comment]
You'll have to ask the tide people then, sorry!
