### ISSUE TITLE
fish dnf package complete broke on Fedora 38: complete: Skipping completions for non-existent command

### ISSUE THREAD

**Issue by sky96111** [fish-shell/fish-shell#9783]
fish, version ``3.6.0``
package source ``fish-3.6.0-2.fc38.src.rpm``
``Fedora Linux 38 (Workstation Edition)``
kernel ``6.2.11-300.fc38.x86_64``

````
dnf version
4.15.0
  Installed: dnf-0:4.15.0-1.fc38.noarch at Sat Apr  8 08:38:58 2023
  Built    : Fedora Project at Thu Apr  6 08:24:21 2023

  Installed: rpm-0:4.18.1-1.fc38.x86_64 at Sat Apr  8 08:38:26 2023
  Built    : Fedora Project at Wed Mar 15 14:26:01 2023
````
---

setp to reproduce
1. clean install or upgrade to Fedora 38
2. ``dnf upgrade`` to latest edition
3. run command fish, now fish can only complete sub-command(e.g. dnf install, dnf info), package name complete broke.

expected behaviour
type in ``dnf install `` and press TAB, a package list will be list

actual behaviour
``dnf install `` and press TAB, it complete to ``dnf install \%\{NAME\}`` , no package name complete
the same as command ``dnf info `` and ``dnf remove``

I've tried
1. run ``fish_update_completions``
2. run ``fish -o fish.log -d complete``
when I tap TAB in package complete, the log shows:
````
complete: Skipping completions for non-existent command
complete: Skipping completions for non-existent command
complete: Skipping completions for non-existent command
````

**Comment by faho** [comment]
Do you have `sqlite3` installed? What does `sqlite3 /var/cache/dnf/packages.db "SELECT pkg FROM available WHERE pkg LIKE \"$tok%\""` print (replacing the `$tok` with some partial package name)?

What does `dnf repoquery --cacheonly "$tok*" --qf "%{NAME}" --available` print (again, replacing `$tok` with e.g. `sql`).

We try to use sqlite3 here because `dnf repoquery` is, or at least was when this was written, slow as molasses. Since the schema was terrible it's possible they fixed it and that path needs to be adjusted.

**Comment by faho** [comment]
Fuuuun. They apparently broke `--qf` (whatever that is).

I'm guessing you installed sqlite3 just now for this?
