### ISSUE TITLE
abbr should make a permanent saving

### ISSUE THREAD

**Issue by simonbcn** [fish-shell/fish-shell#9792]
```
fish, version 3.6.1
Linux cachyos 6.3.2-1-cachyos-lto

```

Currently `abbr` creates abbreviations that persist only in the current session. What is the point of this?
`abbr` should permanently save them when creating them or have a command (`--save`) that allows you to do so.

Having to manually add them to a configuration file breaks the concept of a shell like `Fish`, where everything can be handled from the command line without having to edit the configuration files directly: `alias --save` / `funcsave` / ...

**Comment by simonbcn** [comment]
Apparently you are the only one who thinks this should be the case. Not only that, it is absurd that all commands that create functions, aliases, etc... have a permanent save option and `abbr` is the only one that does not.

**Comment by faho** [comment]
>Apparently you are the only one who thinks this should be the case

I'm not - we decided collectively.

`abbr` is simply too powerful to store it in universal variables, and even automatically storing it in a file is weird, because it can call a function - do you store the function again or not?

So, we decided that you'd simply do it yourself, by simply editing files.

>Not only that, it is absurd

This is starting to become rude. I would suggest stepping back for a minute.
