### ISSUE TITLE
Failed to build from 'master' branch

### ISSUE THREAD

**Issue by SchweinDeBurg** [fish-shell/fish-shell#9795]
After commit 60d439ab22228622ade90a63a60b038e41d2d044 I've got the following error: [fish-3.6.1-rpmbuild.log](https://github.com/fish-shell/fish-shell/files/11494530/fish-3.6.1-rpmbuild.log)

Commit 364f8223b28574be05a897f6732165453f8e89b5 was successfully built at May, 13th. GCC version 9.3, Ruct version 1.68.2.

**Comment by SchweinDeBurg** [comment]
No, it is Fedora 27 and of course `<vector>` is present at its standard location `/usr/include/c++/9`.

**Comment by faho** [comment]
Worth noting that there have been two commits in-between and neither of them touched builtin.h.

If it can't find `vector`, which is a system header, it would most likely be a configuration issue with your system. Or it could be a bug in corrosion/cxx that mistranslates some parts or compiles them in the wrong order.

Note also that there's currently very little reason to build master if you're not developing fish. It's just a slower, slower to build and buggier version of 3.6.1 with very few enhancements.

And `<vector>` not being found eventually won't be a problem because we won't use C++'s vector because we won't use C++ at all.

**Comment by faho** [comment]
> Fedora 27

Fedora 27 is, of course, from 2017 and hasn't been supported for about 4.5 years.

**Comment by SchweinDeBurg** [comment]
> And `<vector>` not being found eventually won't be a problem because we won't use C++'s vector because we won't use C++ at all.

Currently `std::vector` is used widely in the Fish's C++ code. So I think You are right about `corrosion/cxx` bug,

**Comment by faho** [comment]
>Currently std::vector is used widely in the Fish's C++ code. So I think You are right about corrosion/cxx bug,

I'm actually leaning towards a misconfiguration, because nothing here touched builtin.h. But anyway, just build 3.6.1 if you want to use a newer fish version than your distribution ships - which will sidestep all of the rust/c++ integration parts, and if you want to develop fish please upgrade your system.

**Comment by faho** [comment]
Alright I'm gonna close this because I don't believe we want to spend more time on it as it'll go away once c++ does.

There's really no use here, master is currently not what you want to run as an ordinary user. Build 3.6.1.
