### ISSUE TITLE
Backslash new line doesn't ignore comments.

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#983]
From http://unix.stackexchange.com/questions/85253/is-it-possible-to-have-comments-in-multiline-commands-in-fish

Following code doesn't work, when in my opinion, it should.

```sh
function my_function
  echo "hello" | \
  # remove 'l' 
  tr -d 'l'
end
```

**Comment by jakwings** [comment]
Why should it work? Why not just support this normal example instead?

```fish
echo fish |
  cat -A
```

**Comment by jakwings** [comment]
Maybe fish is the first shell to support this style of commenting (wow, bash cannot do this):

```fish
echo long \
  # important comments
  very long \
  # read
  more
```

output: `long very long more`

@krader1961 new bug for fish_indent

**Comment by jakwings** [comment]
This fails:

```fish
echo A\
  #
  B
```

Because the backslash is attached to "A", not sure if this is a bug.

**Comment by krader1961** [comment]
`fish_indent` converts your first example into the form I would expect:

```
echo long # important comments
very long # read
more
```

I would argue the parser is broken not least because it treats the comments differently in those two examples differently. But also because the new behavior, comments on a line by themselves are effectively invisible, surprised me. Note that if you remove the embedded comment from the second example it works as expected echoing `A B`. However, since @ridiculousfish implemented support for that odd style a year ago I suppose we'll have to modify `fish_indent` to sensibly reformat it. I'll open an issue to track that.

P.S., note that you can't do this:

```
function my_function
  echo "hello" | \  # remove 'l' 
  tr -d 'l'
end
```

The placement of the comment on a line by itself is critical to make the "trick" work.

**Comment by jakwings** [comment]
@krader1961 
> P.S., note that you can't do this: …

Well, then that backslash doesn't introduce line continuation.

The implementation by @snnw just misses the point that `A\` (plus \n) in my second example is a string token, where the backslash is not standalone.

Overall, I don't think line continuation should be this special. There is no documentation for this feature. I suggest removing it.

According to the StackExchange question, fish should work like bash without the extra backslash.

> I tend to use this idiom a lot in bash, piping several commands and splitting each command in its own line with a commment for each.

The poster didn't even know what a comment after the line continuation behaves in bash. What he wanted is a more convenient pipe `|`, not a special backslash.

**Comment by krader1961** [comment]
I'm in agreement with you, @jakwings. Mind opening a new issue that references this one and says basically what you said in your last comment?
