### ISSUE TITLE
fish history errors with "error: Unable to read input file: Is a directory"

### ISSUE THREAD

**Issue by rvanlaar** [fish-shell/fish-shell#9843]
```
fish --version
fish, version 3.3.1
```
```
echo $version
3.3.1
```
```
uname -a
Linux MiX 5.19.0-32-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
```
echo $TERM
xterm-256color
```

Running the command `fish history` results in an endless scrolling output on stderr with:
`error: Unable to read input file: Is a directory`

The history is viewable when in the browser with fish_config.

**Comment by rvanlaar** [comment]
Leaving this here for others who have the same problem.
Running a fish command with `fish` in front of it has this error.

The command ran was `fish history`, it should've been just `history`.

**Comment by faho** [comment]
> Running a fish command with fish in front of it has this error.

Yes, because `fish something` tells fish to run a file called "something", just like `bash something` or `python something` would. It's an interpreter, and can run script files.

This specific error occurs because you have a directory called "history" in your current directory. If you didn't have that, you would get "no such file or directory" or similar.

>fish, version 3.3.1

As a general thing: This is 3 minor releases and ~15% of all commits ever made to fish behind.

If you want to report a bug, it's nice to test it with the current release, which at the moment is 3.6.1. You can find packages for your OS at https://fishshell.com/
