### ISSUE TITLE
Building fish on a machine with no internet doesn't work

### ISSUE THREAD

**Issue by kaysond** [fish-shell/fish-shell#9893]
I tried compiling fish at work today to test out the fix for #9891. Unfortunately I work on a machine that does not have internet access, so the current build process doesn't work out of the box. The solution is not too bad, though. You have to do the following on a machine with internet access:

```shell
git clone https://github.com/fish-shell/fish-shell.git
cd fish-shell
git submodule add https://github.com/mqudsi/corrosion.git corrosion-vendor
cd fish-rust
cargo vendor
```
Then follow the instructions in the output of `cargo vendor`

If you copy that "fixed" repo over to an offline machine, you should be able to build with the instructions as written, assuming you have all the dependencies (which are not listed correctly - see below).

---
I have a few minor gripes that I think would be worth addressing:

- The minimum gcc version in the fish-shell readme is wrong. [fish-shell/cxx](https://github.com/fish-shell/cxx) uses some typing features in c++11 that aren't fully supported  until **v5.5.0** (readme lists 4.8). I haven't actually finished the build yet (need to now compile gcc 5.5), so its possible there's something that needs a newer version. I'll report back
- It's a little sketchy to have the build process grab a repo from another author, and one that's a fork, no less (corrosion). It took me aback at first when I saw cmake fetching it. When I looked at the repo and saw it was a fish contributor, I wasn't really worried, but it's a security risk nonetheless, since the version isn't pinned. Better to grab a specific commit from the official repo using cmake FetchContent GIT_TAG. 
- fish_rust has a bunch of critical build infrastructure dependencies that are pointing to forks of the official repo. Some in the fish-shell org, some in personal repos. Best case scenario here would be to just pin the right version from the official repo, second best would be to move the personal ones into the fish org.

I know this is a work in progress, but wanted to share my experience of the current state! Thanks for reading!

**Comment by zanchey** [comment]
Thanks for the input. As you say, it's pretty irritating to do builds on a machine without internet access - that's why the [development builds](https://github.com/fish-shell/fish-shell/wiki/Development-builds) have stopped - but there's no intention to ship a Rust-based release using corrosion or CMake so that will all eventually go away. For now the priority is getting the port done.

A more up-to-date list of dependencies would be useful though again it's all very much in flux. Since you've just done it would you send a patch for the readme?

Running builds to test out fixes is fine to satisfy your curiosity but the overall performance of the shell will be significantly worse and I don't think anyone recommends it as a daily driver at the moment.

The forks are there because those packages need patches. The ones that are left in personal repositories are again scaffolding only, and will not be used in an official release.

**Comment by mqudsi** [comment]
Since we’re continuing #9892 here, I just want to point out that libclang is only needed for autocxx and will not be required once the port is complete.

**Comment by kaysond** [comment]
> A more up-to-date list of dependencies would be useful though again it's all very much in flux. Since you've just done it would you send a patch for the readme?

Sure, I'll double check my machine on Monday and submit a PR. 

> The forks are there because those packages need patches. The ones that are left in personal repositories are again scaffolding only, and will not be used in an official release.

I saw that for some of them; the ones that raised an eyebrow were the scaffolding ones that are not patched. Since they're not going to be used for releases, it really doesn't matter, but it might be nice to leave a note :)

> Since we’re continuing https://github.com/fish-shell/fish-shell/issues/9892 here, I just want to point out that libclang is only needed for autocxx and will not be required once the port is complete.

gcc won't be needed either if its full rust, right? Guess the whole dependencies section will have to be re-written anyways...

**Comment by faho** [comment]
I took a crack at it, if you have anything more to add do of course feel free to file a PR (or just suggest it here).
