### ISSUE TITLE
case sensitive issues

### ISSUE THREAD

**Issue by TonyWael** [fish-shell/fish-shell#9918]
Hey guys, not sure this is the right place to add this issue, I'm having some weird experience with `mkdir` in fish-shell. 

```fish
fish --version
fish, version 3.6.1
```

<img width="730" alt="image" src="https://github.com/fish-shell/fish-shell/assets/3015633/5350eee3-054c-4248-90ce-8e22cb2d10b5">

**Comment by faho** [comment]
MacOS' filesystem is typically case-insensitive. As far as I know you can change it, but it can cause issues with some software so I'm not sure it's recommended (I hear Adobe's stuff is terrible).

Anyway, this is outside of fish - it called `mkdir` once with the argument "abc" and then with the argument "ABC" and that's the end of its responsibilities.

It's not a bug in mkdir because it simply tells the OS to create a directory and the OS tells it that it already exists - because according to the case rules it does.

There is nothing we can change here, it's simply the semantics of your operating system.

**Comment by TonyWael** [comment]
Thanks @faho, after posting this I realised I did have case-insensitive enabled. You may close this issue, thanks!
