### ISSUE TITLE
Fish SIGSEGVs when executing commands with invalid `LC_ALL=`

### ISSUE THREAD

**Issue by SandaruKasa** [fish-shell/fish-shell#9928]
Linux 6.4.7, xterm-256color.
fish, version 3.6.1-716-g0b291355b

Not the latest 4728eaf6427db09f1b8d5a7f55eb679ecd6afe6c, because 35aa7636eb4561a6deb3ee5598549b02f011afa2 introduced a couple of typos, which prevent the Rust part from compiling.

> Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:
> `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'`

Yes, I've tried.
No, it doesn't affect the behavior.

> Tell us how to reproduce the problem.
```fish
LC_ALL=hello whoami
```
is enough to make it SIGSEGV.

This problem doesn't happen with fish 3.6.1.

**Comment by SandaruKasa** [comment]
Ran git bisect. It tells me 6638c78b30310c9c0b235e989827d9639a7897c4 is the first bad commit.

**Comment by henrikhorluck** [comment]
This line in C++ dereferenced a potential null-pointer: 
https://github.com/fish-shell/fish-shell/blob/6638c78b30310c9c0b235e989827d9639a7897c4/src/env_dispatch.cpp#L680

This line in Rust segfaults since `setlocale` returns null
https://github.com/fish-shell/fish-shell/blob/4728eaf6427db09f1b8d5a7f55eb679ecd6afe6c/fish-rust/src/env_dispatch.rs#L716
