### ISSUE TITLE
Weird behavior related to standard output stream of an executable created by C++ compiler

### ISSUE THREAD

**Issue by Silverbullet069** [fish-shell/fish-shell#9949]
I'm pretty rusty in C++ so I decided to finally put much effort in renewing my knowledge, begins with understanding the standard input output of C vs C++, then I stumble on this bug.

Below are my C++ code in **00-buffer.cpp**:
```
#include <iostream>

int main()
{
  std::cout << "test 1\n";
  printf("test 2\n");
  std::cout << "test 3\n";
}
```

Then I compiled and ran it:
```
g++ 00-buffer.cpp -o test && ./test
```

Output: 
test1
test3
test2

BUT, it should be 1, 2, 3, respectively.

Note that I've used **my Git Bash run Fish Shell on top** to run.

If **my Git Bash doesn't run Fish Shell, just simply default Bash**, reran I got 1, 2, 3, which is correct

So, my question is: Does Fish Shell handle standard output different from Bash?

**Comment by faho** [comment]
> So, my question is: Does Fish Shell handle standard output different from Bash?

The output does not go through fish.

The output goes directly to the terminal.

What can happen, however, is that fish sets the terminal up differently.

Fish itself uses the terminal in unbuffered mode, because that makes it easier to handle its own output. 
I have no idea why on your system that wouldn't be reset, I cannot reproduce it, but git bash is a pretty weird environment.

C++'s iostream stuff is typically buffered, while printf bypasses that specific buffer.

This is, in fact, the difference between passing a `\n` and `std::endl` (which flushes the buffer implicitly).

**Comment by Silverbullet069** [comment]
> C++'s iostream stuff is typically buffered, while printf bypasses that specific buffer.

@faho Only when I type  ```std::ios_base::sync_with_stdio(false)``` then you are right. But mine uses default behavior - synchronization between the C++ output (<<) and C output (printf). So the result has to be 1, 2, 3.

I've tried to flush explicitly:
```c++
printf("test 1\n");
fflush(stdout); // print everything in the C standard output stream

cout << "test 2\n";
cout.flush(); // print everything in the C++ standard output stream

printf("test 3"); 
fflush(stdout);
```

This works :v I got 1, 2, 3, respectively. But doing this right after every outputs is a pain in the ass. In addition to the issue link you provided, it seems there will be no fix in near future. I've decided to leave the Git Bash environment for good :)

P/s: Tell your bro that Git Bash is real sucks. 
1- No symlink (had to use ```mklink```)
2- No pseudo-terminal (had to prepend ```winpty``` to every program, just to run MySQL shell/Python interpreter/...)
3- Redirection bug in some program (tried to run ```mysqldump -u root -p sakila > sakila_copy.sql``` and you will know it)
