### ISSUE TITLE
command "export"  compatibility with bash and zsh

### ISSUE THREAD

**Issue by q2333gh** [fish-shell/fish-shell#9957]
fish, version 3.3.1

```fish
#danger:
export PATH=$PATH:/opt/wasi-sdk-20.0/bin
```
If I exec this command . it will just break my fish PATH. although  reopen will fix this problem .   
but it took me  1 hour to find out way and fix it .   

```fish
#right syntax:
#temporary:
set -x PATH $PATH /opt/wasi-sdk-20.0/bin
#permenant:
echo 'set -x PATH $PATH /opt/wasi-sdk-20.0/bin' >> ~/.config/fish/config.fish
```
why not **warn** fish user  this command ? 
i like fish shell. but some compatibility with bash and zsh really troubled me a lot  ocaasionaly.  

and even better : why not fully compatible with bash ?

**Comment by faho** [comment]
> If I exec this command . it will just break my fish PATH. 

This is because $PATH is a list, and will therefore combine all list elements with the attached string. See https://fishshell.com/docs/current/language.html#combining-lists-cartesian-product.

The solution is to double-quote the expansion - which is also what you would do in bash with essentially any expansion.

```fish
export PATH="$PATH:/opt/wasi-sdk-20.0/bin"
```

Or, alternatively, use `fish_add_path`:

```fish
fish_add_path /opt/wasi-sdk-20.0/bin
```

which will take care that the new path is only added once.

> and even better : why not fully compatible with bash ?

Because that is one of the basic ideas of fish. If you want a bash-compatible shell there are other alternatives.

**Comment by q2333gh** [comment]
> 
thank you  for reply ! it helped me understand more about fish .   
and i like fish coloring , auto cmd suggestions , and design philosophy!
