### ISSUE TITLE
Allow `math` to take piped input

### ISSUE THREAD

**Issue by ModProg** [fish-shell/fish-shell#9959]
When building large expressions and wanting to e.g. increase the output by 1 it would be nice if this could be done through piping, as using command substitution with can make it harder to handle as it adds another layer of nesting.

My idea would be to either, append the piped input to the arguments, i.e.

```fish
echo 100 | math  1 +
```

would output 101, or have a `stdin` constant/function i.e.

```fish
echo 100 | math stdin + 1
```

One thing that could be considered is automatically joining the stdin with `,` which would mean something like this would work

```fish
seq 1 6 | math max
```

would return `6`.

**Comment by faho** [comment]
math already takes piped input, but it needs to be the entire expression:

```fish
seq 1 6 | string join ',' | string replace -r '^' 'max ' | math
# or
math max (seq 1 6 | string join ,)

echo 100 | string replace -r '$' ' + 1' | math
```

I don't believe the additional complexity of adding a marker for where to put the additional input is really worth it. For the most part, the sort of computations with stdin I do are things like

```fish
list-of-numbers | string join + | math
```

to get the sum of a list of numbers.

**Comment by ModProg** [comment]
Oh ok, so my request is rather about having a way to better combine piped and regular input, which might or might not be generally useful enough.

And I also just thought of a case where the intent might not be necessarily easily clear:

```fish
seq 1 6 | math max 3, stdin
```

One could expect that to either yield `3`, `3`, `3`, `4`, `5`, `6` or just `6` depending on whether one wants to basically apply a minimum to the input list or collect the input list.

> I don't believe the additional complexity of adding a marker for where to put the additional input is really worth it. 

Yeah I'm not sure how much work that is, as a user, the most clear and difficult to mess up solution would be to have math collect stdin in a constant that can just be used, same as e.g. `pi`, but on the other hand, I don't know if there are enough usecases that would benefit from this.

**Comment by faho** [comment]
> One could expect that to either yield 3, 3, 3, 4, 5, 6 or just 6 depending on whether one wants to basically apply a minimum to the input list or collect the input list.

math currently always produces exactly one result (or an error), so it would be "6".

The confusing case is when you expect it to partially evaluate an expression on stdin:

```fish
printf %s\n 2 + 5 | math max stdin
```

would produce "math max 2, +, 5", which would be an error. It would have to be

```fish
printf %s\n "2 + 5"
```

which would also change how whitespace is handled - currently spaces and newlines are entirely equivalent.

**Comment by ModProg** [comment]
> math currently always produces exactly one result (or an error), so it would be "6".

Yes, I just thought of it as a possible further development of this.

> The confusing case is when you expect it to partially evaluate an expression on stdin:
> 
> ```fish
> printf %s\n 2 + 5 | math max stdin
> ```
> 
> would produce "math max 2, +, 5", which would be an error. It would have to be
> 
> ```fish
> printf %s\n "2 + 5"
> ```
> 
> which would also change how whitespace is handled - currently spaces and newlines are entirely equivalent.

Makes sense, that is an entirely different additional problem.

**Comment by faho** [comment]
> Yes, I just thought of it as a possible further development of this.

Doing one computation at a time is an intentional design, and makes it easy to deal with math's output - if your expression is well-formed, you always get exactly one result. Math results are often passed to `test` or e.g. as arguments to `string repeat -n`, so that's a useful property.

It would have been possible to allow you to do multiple computations - the library math is based on allowed "," to separate expressions, so you could have done

```fish
math "5 + 5, 2 x 3"
```

But that mixes two entirely different computations, and so (and because that made detecting errors like `sin(5,2)` weird) I ripped it out.

So the idea was to simply let one math handle one computation - if you need more, that's why loops exist.

> Makes sense, that is an entirely different additional problem.

It's part of why adding this would be weird, not really a separate thing.

----

I have some experience using math, and I don't think this is helpful often enough to warrant the additional complexity and weirdness in changing it now, so I'll be closing this.
