### ISSUE TITLE
Proper Unicode Grapheme Cluster Support

### ISSUE THREAD

**Issue by christianparpart** [fish-shell/fish-shell#9964]
Hey guys,

I would like to have fish shell properly support complex grapheme clusters, especially ZWJ emoji sequences.

I am very well aware that most terminals don't even support this. But a few seem to rise trying to provide proper Unicode Grapheme Cluster support (rendering as well as VT sequence interpretation).

One can already paste e.g. `echo "👩‍❤️‍👨👩‍❤️‍👨👩‍❤️‍👨"` into a fish shell session, but that will result in quite some white spaces also being inserted.

What I imagine is either auto-detecting support ([Terminal Unicode Core](https://github.com/contour-terminal/terminal-unicode-core/releases) draft spec), using some heuristic, or as a config option to get it explicitly enabled.

I actually started looking into fish-shell source code, but it's not necessarily small either. Do you think an outside contributor could implement this as a good-first-issue? What would be needed to be touched?

### Side Notes

```sh
$ fish --version
fish, version 3.6.1

$ echo $TERM
contour

$ lsb_release -a
LSB Version:    :core-4.1-aarch64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 38 (Thirty Eight)
Release:        38
Codename:       ThirtyEight
```

**Comment by faho** [comment]
> Do you think an outside contributor could implement this as a good-first-issue?

Definitely not.

This is *quite* complicated, and would need to be added in a bunch of gnarly places, across the board.

For one you would have to replace `wcwidth`, pretty much across the codebase.

>What I imagine is either auto-detecting support ([Terminal Unicode Core](https://github.com/contour-terminal/terminal-unicode-core/releases) draft spec),

I have never heard of that spec. Do any terminals implement it?

One major issue in the terminal space is that literal hundreds of terminal developers have ideas and write specs, but they don't communicate enough to actually get them *implemented everywhere*.

And so when I see a spec like that my immediate reaction is to discount it because it's not gonna be implemented in the terminal I use, or the ones that most of our users use.

We don't implement specs that don't have broad support.

**Comment by christianparpart** [comment]
> As an additional complication, this is a terrible time to propose changes like that because the fish source is undergoing a large-scale change - we're porting to rust.

I do not want to mandate what you should do and not. But it saddens me to some degree. Your codebase is large and well established, I do not see any objective benefit of switching languages. :-)

> I have never heard of that spec. Do any terminals implement it?

yeah, this is not advertised for now(!), i am the author of it, just like i am the author of [Contour Terminal](https://github.com/contour-terminal/contour) emulator, which is providing proper Unicode Grapheme Cluster support, and thus, implementing this spec was easy, since we already have the requirements met. Anything else, I'd treat as serious bug that needs fixing ASAP.
I planned to advertise it a bit more when i'm having more time to focus on protocol extensions again.

The spec was in the talks at windows terminal at least, too, but I can't find the refs to my memory as of right now.

> We don't implement specs that don't have broad support.

Generally (not necessarily explicitly to this mode), I feel kinda sad about it, because that's why we don't move forward in the TE-vs-Unicode space, as everyone is too conservative and afraid of being the first to move. (just generally speaking here).

Apart from the spec mentioned, there would be other ways (heuristic or config var). 
So, would you generally be interested in such thing?

### side node

There is another thing I planned to implement in fish shell eventually, that is hooking into mouse move & click events within the shell. This is currently technically impossible without VT sequence extensions, and I implemented a draft for that with a PoC CLI demo tool. 
Now I am concerned it would never be accepted by fish-shell, iff i'd ever made it to be implemented.

**Comment by christianparpart** [comment]
> For one you would have to replace wcwidth, pretty much across the codebase.

(sorry, I did hit <CR> too quick) - `wcwidth` should not be used anyways, but if at all, then `wcswidth`, and with GCs it'll become more complex anyways. What we did, is actually implementing a grapheme cluster segmentation algorithm (theory provided by Unicode spec) and then store one GC per column.

**Comment by faho** [comment]
> Generally (not necessarily explicitly to this mode), I feel kinda sad about it, because that's why we don't move forward in the TE-vs-Unicode space, as everyone is too conservative and afraid of being the first to move.

From our perspective, the absolute *least* of our problems is terminal developers being afraid to implement features!

Everybody wants to implement their own cool stuff, nobody wants to get *others* to buy in.

And since, unlike web browsers, it's quite a fragmented space, with tens to hundreds of relevant players, you don't have something like Chrome or Safari or (possibly) Firefox that can propose and implement a thing and it's suddenly useful to web developers because a lot of their users will have access to it.

Plus the function detection and querying mechanisms are, to put it mildly, terrible - $TERM is functionally a zombie, because everyone and their mom claims to be xterm-256color. Querying involves round-trips that are potentially unbounded and with ssh in the mix who knows how long you should wait.

>wcwidth should not be used anyways, but if at all, then wcswidth, and with GCs it'll become more complex anyways

Of course - but that isn't the code we currently have. This would have to replace wcwidth, because that is what we currently use.

>Apart from the spec mentioned, there would be other ways (heuristic or config var).
So, would you generally be interested in such thing?

You said yourself: "I am very well aware that most terminals don't even support this".

I wouldn't be enthused about a config var, and I've written enough terminal-detection heuristics to last me a lifetime, but if it would help enough people to be worth the complication it would be okay.

Unfortunately, as it is now, I do not believe adding this complexity is helpful because basically none of our users could use it.

I believe that, yes, the future will have grapheme cluster support in terminals. But I don't think that adding it according to your spec, and with added config knobs and heuristics, at this time, is helpful.

To explain the context I'm coming from: Just today I saw people hem and haw over updating the unicode support in their pty-using application from unicode 8.

>The spec was in the talks at windows terminal at least, too, but I can't find the refs to my memory as of right now.

Tell you what: Once they, or a terminal of similar importance, do, we can revisit this. Hopefully by then we'll be in a better space that it's nicer to add something like it.

Until then, I'm closing this as unplanned.

In the meantime, I recommend you work on getting as many other terminal devs on board as you can. I wish you luck because that's a terrible task.

**Comment by christianparpart** [comment]
> Everybody wants to implement their own cool stuff, nobody wants to get others to buy in.

I feel you. I experience this myself already, for the above spec, for the so called "Good Image Protocol" as well as my mouse protocol extension. It's a lot of politics and too many too strong opinions that have rarely the intent to come to a consensus.

> I believe that, yes, the future will have grapheme cluster support in terminals. 
> But I don't think that adding it according to your spec, and with added config knobs and heuristics, at this time, is helpful.

I'd like to understand the why in "I don't think that adding it according to your spec [...] is helpful". The spec itself does not require config knobs nor heuristics, as pointed out in the spec, it's trivial to detect using a VT sequence that every serious TE implements (`DECRQM`).

> Tell you what: Once they, or a terminal of similar importance, do, we can revisit this. Hopefully by then we'll be in a better space that it's nicer to add something like it.

This is exactly the point I was making above (afraid of being the first). I truly believe in what I have implemented wrt that context is the way to converge to a better Unicode experience in the TE space.

> In the meantime, I recommend you work on getting as many other terminal devs on board as you can. I wish you luck because that's a terrible task

May the politics fight begin. But again, the good thing about the spec is, that with `DECRQM`, it is okay to not support it as a TE, the app can simply detect and optionally explicitly enable the conformance mode. All it gives the app is guarantees. Guarantees on how GCs are treated.

I do respect the decision of you not wishing to implement it though. Have a nice day.
