### ISSUE TITLE
env disables aliases

### ISSUE THREAD

**Issue by sigmaSd** [fish-shell/fish-shell#9987]
An example example explains better
```
alias helloworld=ls
helloworld # works
env a=1 helloworld # fails
```

Don't know if this is a bug or expected for some reason ?

fish, version 3.6.1

**Comment by faho** [comment]
`env` is an external command. Aliases are functions, they only exist inside the shell.

Yes, this is expected, nothing for us to fix here.

In current fish versions, you can just call `a=1 helloworld` because fish supports variable overrides since version 3.1.

Otherwise, you'd have to do something like `env fish -c 'helloworld'` - if the function is autoloaded that would work.

**Comment by sigmaSd** [comment]
thanks
