### ISSUE TITLE
funced stopped working

### ISSUE THREAD

**Issue by polsvoice** [fish-shell/fish-shell#9999]
I'm using fish 3.6.1, running on Geruda (kernel 6.4.12-zen1-1-zen) in yakuake (although it gives me `xterm-256color` when I do `echo $TERM`.) My `$EDITOR` is micro.

When I enter `funced my_function`, I get
```
Editor exited but the function was not modified
```
and it opens the editor set in `$VISUAL`, which is kate.

When I enter the function code into kate and try to save, I get an error message that says
```
The document could not be saved, as it was not possible to write to /tmp/fish.6bEK1f/my_function.fish.
Check that you have write access to this file or that enough disk space is available.
The original file may be lost or damaged. Don't quit the application until the file is successfully written.
```
I tried running fish without third-party customizations, and I got the same result.

Why is fish trying to write to a temp file instead of the `functions` directory?

**Comment by faho** [comment]
In short: Set VISUAL to `kate --block`.

----

The error message actually tells you what you need to know:

>Editor exited but the function was not modified

The editor has already exited by the time it opens - this is because running `kate` just forks off without waiting for it to edit. Fish expects to wait for the editor to exit so it knows when it can use the file.

This breaks the $EDITOR/$VISUAL contract, and so it's not usable. This is a common problem with GUI editors, unfortunately they all seem to have a different option for how to disable it (for sublime it's `subl -w`). In kate's case you need the `--block`/`-b` option.

This isn't just a fish issue, it will also break e.g. git's commit editor.

> Why is fish trying to write to a temp file instead of the functions directory?

It uses a temporary file so it can load the function without permanently overwriting any customization you already have.
